- .circleci/config.yml
- ci/activate_creds.sh
- ci/deploy.sh
- ci/install_gcloud.sh
- ci/upload_cloud_creds.sh
- tools/deploy.py
These cover auto-deployment of the API server. To handle deployment of the UI as well, we will want to choose among:
1. **Selected, see #19**: Split the "build" task into a "workflow" with two tasks, one for API and one for UI
~~2. Use a customer Docker image that has java *and* node installed~~
~~3. Start from the default Docker image (with java) and install node each time we need it (slow :/)~~
I'd like to merge in this state, so we have working auto-deploy for the API server on merge-to-master.
> Deploy scripts

- ui/app.yaml
This ensures that URLs like `login` work in our "single page app" design, by serving the same default `index.html` no matter what url is requested.
Before this fix:
https://20170717t223357-dot-all-of-us-workbench-test.appspot.com/login
After:
https://20170718t205535-dot-all-of-us-workbench-test.appspot.com/login
> Serve all paths as index.html to accommodate ng routes

- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.test.ts
API calls on the test and prod environments had an extra /.
> Removed extra slash at the end of prod and test environments

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/web.xml
This is necessary because basePath in Swagger isn't used when generating Spring code, and other attempts to set the context root in AppEngine to /api/v1 weren't working.
Switching to servlet 3.1.
Removing stuff from build we didn't need.
> Changing /api/v1 to be a part of each endpoint path

- api/db/changelog/db.changelog-1.xml
- api/src/main/java/org/pmiops/workbench/api/CohortController.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortDao.java
- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- api/src/main/java/org/pmiops/workbench/exceptions/BadRequestException.java
- api/src/main/resources/workbench.yaml
Changing ID used for cohorts in external API to be the numeric database ID, assigned by the server on creation.
> Removing external ID from cohort DB representation.

- api/db/setup_local_database.sh
Otherwise you just get an error that setup_local_vars.sh cannot be found, but not an indication of where it is / should be.
> Add error message if db setup script is run from the wrong directory.

- .gitignore
- ui/package-lock.json
- ui/package.json
This follows comments at https://github.com/angular/angular-cli/issues/7113#issuecomment-317383178 which suggest that having a specific version of `enhanced-resolve` breaks the `ng build` `--environment` flag.
It also adds `package-lock.json` to our repo, per Brew's suggestion (also recommended by NPM docs; new as of NPM 5.0). This includes all installed packages, not just the top-level dependencies we specify, so we won't run into situations where different dep resolutions will (invisibly) break some of us in the future.
> Fix building with `--environment test`.

- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
I didn't deploy an example, because the current wait time is fast enough that you can't really see it, but if you grab the branch and add a settimeout before it sets cohortsLoading to false, you can see what the behavior looks like.
> Added loading spinners to datatables

- api/libproject/devstart.rb
- api/project.rb
that can subsequently be used to access database connection info.
Example output can be found here:
https://console.cloud.google.com/storage/browser/all-of-us-workbench-test-credentials/?project=all-of-us-workbench-test&organizationId=394551486437
Changing args passed to commands to be a Hash (map), rather than a flat list.
TODO: have a better way of printing usage for commands with options
> Adding create-db-creds command, used to create a vars.env file in GCS

- api/docker-compose.yaml
- api/libproject/devstart.rb
Also adds a `docker-clean` command and documentation about when it's useful.
> Start containers separately for easier debugging

- ui/src/app/views/workspace/component.html
I split edit into two options: edit and review.
Edit will take you to the ability to edit cohort name and description, while review will take you to the cohort review page. I'm hoping that this matches up closer to our understanding of what users might do with cohorts.
@jscherdin and @freemabd1, does this match up with your understanding of how users might interact with cohorts?
Also, I removed the URL column on the cohort data table, because I suspect users will navigate via links rather than through copy and pasting URLs.
> Broke edit out into two more explicit options

- api/libproject/devstart.rb
- hooks/apply-git-secrets.sh
- hooks/commit-msg
- hooks/pre-commit
- hooks/pre-push
- hooks/prepare-commit-msg
- ui/libproject/devstart.rb
- ui/package.json
Git hooks installed by the `shared-git-hooks` NPM module are done within the docker container, so the symlinks are not correct on the host machine. For me, that made them fail silently. Additionally, if I don't start the UI, they don't get installed.
Now they are installed using a local git config (available since version 2.9). I also fixed some other issues and factored out some common code.
When this PR is merged, each developer will want to run
```bash
find .git/hooks -type l -exec rm {} \;
```
to clean out the old hooks.
> Fix git secrets and git hooks

- api/build.gradle
David Mohs and I ran into an issue where if a swagger definition was removed, but the generated files weren't manually cleaned, then it wouldn't run the API. This remedies that issue.
> Clean old generated files before generating

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/cohort-builder/search/model/search-result.ts
- ui/src/app/views/cohort-builder/search/wizard-modal/wizard-modal.component.ts
- ui/src/app/views/cohort-builder/search/wizard-select/wizard-select.component.ts
- ui/src/app/views/cohort-builder/search/wizard-tree-parent/wizard-tree-parent.component.ts
- ui/src/helper-functions.ts
- ui/tslint.json
I'd like to keep our 100-columns rule in most places, and just disable it around import blocks where statements are too long. I know this puts a little burden on cohort builder folks (since you're likely to be dealing with long imports the most), but hopefully that's OK. This lets us keep the same lint rules elsewhere (where lines were already sneaking by our radar). Followup to #110.
> Selectively disable max-line-length rule around long import blocks. Revert to 100 columns.

- api/libproject/devstart.rb
With reuse of code.
Note: we should consider uploading some shared creds for all-of-us-workbench-test@ into our credentials bucket, and using those, so we don't have to have every developer holding on to a separate key while their server is running. But for now, this works.
> Changing dev-up to run as all-of-us-workbench-test@appspot.gserviceaccount.com.

- ci/activate_creds.sh
I ran into this while debugging deployment; not our issue I don't think, just making it clearer when things go wrong.
> Check for required env var before use, report error in activate_creds.sh.

- client/libproject/devstart.rb
- client/py/.gitignore
- client/py/README.md
- client/py/aou_workbench_client/__init__.py
- client/py/setup.py
From client/py/README.md, to try it out:
```
virtualenv venv
. venv/bin/activate
pip install 'https://github.com/all-of-us/workbench/archive/pyclient-v0-0-rc1.zip#egg=aou_workbench_client&subdirectory=client/py'
python -c 'from aou_workbench_client import swagger_client; print swagger_client'
```
This provides a PIP-installable, versioned Python client with the Swagger client as a submodule. I expect to mostly wrap the swagger client, to provide easier functionality. Still TODO is all that wrapping. To publish the client, we'll run `./project.rb swagger-regen`, commit it to the `generated-py-client` branch, and tag it.
> [RW-28] Add Python client stub and rules to generate Swagger Python client, installable via PIP.

- ci/deploy.sh
- tools/deploy.py
This avoids creating a new version in AppEngine on every deploy, and gives us the capability to name versions.
> Setting version in deploy.py.

- ui/src/app/views/app/component.css
- ui/src/app/views/bug-report/component.css
- ui/src/app/views/cohort-builder/search/cohort-builder/cohort-builder.component.css
- ui/src/app/views/cohort-builder/search/wizard-modal/wizard-modal.component.css
- ui/src/styles.css
I did not convert px in:
- 1px borders. I think the notion here is 'the thinnest solid line'. I'm not sure if there's a better unit.
- Shadow offset of 1px (similar).
- @media rules in Cohort Browser. Some of these aren't used, also.
Tangentially, I removed any units from 0 values. I also left `vh` alone (new to me, seems fine).
Demo: https://20170922t173307-dot-all-of-us-workbench-test.appspot.com
> [RW-82] Convert px to rem in stylesheets.

- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/src/dev/server/Dockerfile
- libproject/workbench.rb
- ui/docker-compose.yaml
- ui/libproject/devstart.rb
- ui/src/dev/server/Dockerfile
To try this, check out the branch locally and
* remove all volumes (`docker-compose down -v`)
* remove all root-owned files (`sudo rm -rf src/generated build db/.gradle tools/build src/main/webapp/WEB-INF/appengine-web.xml`)
At this point you should see no files owned by root:
```
$ find . -user root | wc -l
0
```
And you should see no old volumes hanging around:
```
$ docker volume ls | grep gradle-cache | wc -l
0       0       0 -
```
Then you can try building and running with local user priviliges:
```
docker-compose build
./project.rb dev-up
```
> Jmandel/as-local-user Run docker as local user instead of root

- api/src/main/java/org/pmiops/workbench/api/BugReportController.java
Incidental changes while I was using BugReportController as a handy example for admin permissions:
* Wrap to 100 columns.
* Group external and internal imports.
Do we have style conventions and/or a linter going for Java?
> Formatting in BugReportController.

- api/libproject/devstart.rb
- libproject/workbench.rb
Revert "Cleanup in api Ruby: Use Dir.chdir context guard, common.run_inline. Use spawn() for all of Workbench. (#184)"
This reverts commit 7691ad7e23ae0de762ce40893739111cd126180f. Broke --creds_file in API deploy.
Planning to submit TBR as soon as CircleCI passes since it's a clean rollback.
> Revert API devstart.rb changes which broke API deployment --creds_file.

- api/libproject/devstart.rb
@dmohs I think you accidentally switched `--creds_file` to `--creds-file` in #181 which broke auto-deployment from master (https://circleci.com/gh/all-of-us/workbench/1807) but which doesn't get used on CircleCI's topic branch runs nor in deployment from workstations.
> Fix hyphen => underscore in flag.

- api/libproject/devstart.rb
- libproject/workbench.rb
Clean rollforward of #184, rolled back in #186. (I believe the error was actually caused by #181, fixed separately in #187.)
> Cleanup in API Ruby: Use Dir.chdir context guard, common.run_inline. Use spawn() for all of Workbench.

- api/build.gradle
Required for now; 0.26 contains breaking changes.
> Pin com.google.cloud:google-cloud-bigquery to 0.25.0-beta

- api/build.gradle
https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard
Hopefully this will get Spring Boot startup logging going to Cloud Console.
> Exclude slf4j as per:

- .circleci/config.yml
- ui/docker-compose.yaml
- ui/package.json
We had previously been running our swagger codegen three times on startup, once in the ruby script, and then once on each of `npm start` and `npm test`. This fixes that issue.
> Remove multiple codegens on UI startup

- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/redux/reducer.ts
Currently requests in the "outer scope" of an entity (SearchGroupItem, SearchGroup) are re-fired upon every addition or removal of a SearchGroupItem or SearchGroup to the SearchRequest. If the count for an removed entity is 0 or if the entity has no constituents (and hence no count) we would rather not fire a request when it is deleted so that we can (A) avoid the network overhead and (B) minimize the amount of time interesting numbers are obscured from the user by spinners - i.e., at the moment removing an empty group obscures the total count.
> Removing entities only refires requests if it has to

- api/db/changelog/db.changelog-8-ws-index.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/Application.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/README.md
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/tools/build.gradle
* Factor out WorkspaceService (wrapping WorkspaceDao).
* Combine copies of 'get workspace and throw if it doesn not exist'.
* Add methods for research purpose review, and associated tests.
* Incidental fix of string formatting in exception messages (in WS files only).
Following discussion captured in https://docs.google.com/document/d/1uNf6_5TZxnQt8BP_wWoGxPcGwaIZAhZswW3bXwbswHU about how to make more complicated stuff than Spring-Data repositories are set up for. Glad for feedback on that -- are the right things `@Query`s, using model objects, etc? Also curious what people think about doc links in READMEs.
This leaves a major TODO of RW-215, adding transactionality / entity versioning. I think that's likely to cause some further changes (especially in tests) because of how Spring …
> [RW-183] Create WorkspaceService to handle research purpose review.

- api/src/main/java/org/pmiops/workbench/db/model/User.java
Exists in XML as:
```
<createIndex
indexName="idx_user_email"
tableName="user"
unique="true">
<column name="email"/>
```
> [RW-220] Remove superfluous Java declaration of index for User.

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/QueryBuilderFactory.java
In exceptions and log statements, convert `s.format(p)` to `String.format(s, p)`. `String.format` is a static function, so these instances were ignoring the string it was called on and just returning the first parameter.
This was mostly in exceptions, but also affected `Logger.log` calls which, when including a `Throwable` argument, require a pre-formatted string. (Only `Logger.log(String msg, Object param)` or `Logger.log(String msg, Object[] params)` can use the `Logger`-specific `{N}` style format strings.)
> [RW-217] Fix calls to String.format.

- api/src/main/resources/workbench.yaml
Adds a definition for `Attributes` to the swagger files, provisionally - this should be considered subject to change as we explore what's needed here.
The difference between an `Attribute` and a `Modifier` is both semantic and a difference of scope - an attribute applies to a single criterion (i.e. a Medication code may need extra information about dosage to make sense) and a modifier applies to a whole grouping (a `SearchGroupItem`, technically) - e.g., equivalent to "select from these five codes everyone who is in some age range".
> Add provisional Attribute defn to Swagger

- ui/src/app/cohort-search/redux/actions/service.ts
fixes a bug where the UI would fail to recognize that the SearchRequest was empty before attempting to contact the API
> Fixes RW-228: ui fails sometimes to recognize empty SearchRequest

- api/config/config_test.json
This reverts commit 7084ee8a7430ee5df9c266d6d817be99be2f9a8e.
This broke CircleCI on master, see for example https://circleci.com/gh/all-of-us/workbench/2743 (:tools:loadConfig fails).
Submitting TBR since it's a clean rollback and CircleCI is broken (after a retry as well).
> Revert "Shorten billing prefix and add comment. (#256)"

- ui/src/app/cohort-search/redux/actions/service.spec.ts
- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/wizard-modal/wizard-modal.component.ts
Fixes a bug where adding a SearchGroupItem to a SearchGroup with an existing count of 0 failed to trigger a request for the updated total count.  The bug occurred because the now-outdated group was being considered when checking for intersections with the null set.
> RW-229 FIX

- api/db/changelog/db.changelog-9-ws-index-fix.xml
- api/db/changelog/db.changelog-master.xml
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.ts
- ui/src/app/views/review/component.css
- ui/src/app/views/review/component.html
- ui/src/app/views/review/component.ts
This also fixes the database index for workspaces on review status; it was "unique" but should not have been. (Liquibase supports deleting/creating but not modifying indices.)
This has some obvious rough edges, which I'm leaving in because we need to decide how this will be used (or if it will live elsewhere) still: No undo nor list of processed workspaces; no separate error explanation beyond the default toast; no UI test.
> [RW-183] Add rough UI for research purpose review.

- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
Tested:
```
workbench$ api/project.rb update-cloud-config --account mark.fickett@pmi-ops.org --project all-of-us-workbench-test
...
:tools:loadConfig (Thread[Task worker,5,main]) completed. Took 9.975 secs.
BUILD SUCCESSFUL in 36s
```
> Shorten billing project prefix, to avoid 30-character limit from GCP.

- client/py/aou_workbench_client/auth.py
- client/py/requirements.txt
This is a first sketch of how auth will work. I think metadata API + fallback on gcloud will stay, but it might well move around. This lets us exercise the Swagger-generated Python client lib and verify that it can talk to the API (from dev workstations or from GCP VMs).
I plan to add tests before submitting, but would like y'all's feedback on the approach.
> Implement py client authentication.

- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Following advice on https://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect/34724168 .
I've deployed a version of the API service with this change. It handles traffic fine.
The lowest "last packet sent successfully to the server" listed in error messages is about 24h, so I could sit on this for a day and submit if there are no errors, or just submit now and keep an eye out for more errors / try different approaches if it's not fixed.
> [RW-235] Set test-on-borrow db property, to avoid db connection timeouts.

- client/py/README.md
- client/py/aou_workbench_client/auth.py
- client/py/example.py
- client/py/setup.py
This is the process I've been using. I'm open to suggestions for a simpler workflow, and/or glad to turn this into a `project.rb` script if it looks like a suitably durable process.
My goals are:
* Produce a git tag which can be used for versioned installation via PIP.
* On the master branch, .gitignore the Swagger-generated files.
> Update Python client docs: describe releasing and auth details; split out example script.

- api/src/main/webapp/WEB-INF/appengine-web.xml.template
From deploying a test to all-of-us-workbench-test, I think this avoids remaining db connection staleness. However, I'm still seeing plenty of socket exceptions.
> [RW-235] Add test-while-idle db options.

- ui/src/app/views/workspace-share/component.html
- ui/src/app/views/workspace-share/component.ts
This is a preparation for adding FC sharing.
Firecloud does not allow users to edit their own permissions, so we should forbid that via the UI as well.
> Cannot remove self from workspace.

- api/db/changelog/db.changelog-11-version.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/Etags.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/java/org/pmiops/workbench/exceptions/ConflictException.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/WorkspaceDaoTest.java
- Add an `etag` to mutable resources in the workbench API (workspace, cohort) to allow the client to detect attempted stale updates to a changed resource
- Rationale: set directly in the resource (rather than via HTTP headers) to enable clearer semantics on List/Get, e.g. on ListWorkspace should return a resource that can be used to make an update.
- Returning an etag directly on the resource is recommended by [Google API style](https://cloud.google.com/apis/design/design_patterns#etags)
- Use of `etag`s during updates are optional; if unset by the client we will apply the update without knowing whether it is "stale"
- Add an @Version version column to these models which is automatically incremented and checked during all updates
- Add versioning to User to detect concurrent modification …
> [RW-215] Add workspace/cohort/users versions and etags

- api/src/test/java/org/pmiops/workbench/db/dao/WorkspaceDaoTest.java
I pattern matched the only directory named "dao". `db/dao` did not yet exist.
> mv WorkspaceDaoTest to the proper package

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
- The conflicting update modal has a "reload" option instead of going back, this seems like the most likely action one would want to take.
- Updated the wording in a few places for "edit mode" vs create mode.
> Add specific error handling for update conflicts; improve edit page

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/workspace-share/component.ts
- `ShareWorkspace` now accepts and returns a `workspaceEtag`
- `updateUserRoles` now increments the `workspace.version` column by advancing `workspace.lastModified`; it is worth noting that this is not bullet-proof as there is no global consistency for a server-side `new Instant()` call, however it is still very unlikely for that two servers would generate the exact same millisecond timestamp, especially since we expect concurrent modification to be a rare user-driven occurrence.
- Another option here is to force a version increment via `auditingHandler.markModified()`; we'd need to switch to \@EnableJpaAuditing and refactor our lastModified columns to get this (it does not work in isolation with \@Version from my testing). Didn't pursue this further as there may be other implications and …
> [RW-215] Add etag support to ShareWorkspace

- .circleci/config.yml
- api/docker-compose.yaml
- api/libproject/cloudsqlproxycontext.rb
- api/libproject/devstart.rb
- api/libproject/gcloudcontext.rb
- api/libproject/generate_appengine_web_xml.sh
- api/src/dev/server/Dockerfile
- ci/Dockerfile.circle_build
- ci/deploy.sh
- ci/install_gcloud.sh
- libproject/workbench.rb
Decided to improve this since I wanted the functionality in-place so I could test changing the URL for FireCloud to the dev instance. This dockerizes the deploy for developers and also unifies some of the code between what Circle runs and what developers run.
> Dockerized deploy

- ui/src/app/views/app/component.css
- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.ts
Rationale: Clarity's top-nav content had some undesireable behavior
around reloading the page, where it reset which tab it had highlighted,
so I did a quick re-implementation there, so that we have control
over what is active
> Change top bar to have our active logic.

- api/libproject/devstart.rb
Previous behavior:
- Every time CircleCI runs, we redeploy the `circle-ci-test` GAE version
- The `circle-ci-test` is serving 100% traffic
- There is no distinction between `--promote` vs `--no-promote` in this scenario, since the `circle-ci-test` version is already serving traffic. If it weren't serving traffic, then `--promote` would switch traffic over to it.
New behavior:
- For master pushes, we redeploy the `circle-ci-test` GAE version, which should always serve 100% traffic
- For git tag pushes, we deploy a GAE version with that tag name, but don't promote (AFAIK no one is using this currently, but may be useful later for releases).
- For everything else, we don't touch the GAE deployment
The UI server was not affected here, as it already only repushes for master commits.
> Don't redeploy the test API server on every CircleCI run

- .circleci/config.yml
- ci/deploy_ui.sh
Don't promote on git tag CircleCI runs. AFAIK we're not using git tags for anything and I'm not sure if CircleCI is configured to run on git tags anyways, so this is just for consistency going forward.
> Update UI deployment to match API; rename script

- api/build.gradle
Overhead seems negligible:
```
./gradlew generateApi
BUILD SUCCESSFUL in 2s
4 actionable tasks: 2 executed, 2 up-to-date
```
> Require validation before codegen

- api/build.gradle
- api/db/changelog/db.changelog-13.xml
- api/db/changelog/db.changelog-master.xml
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/java/org/pmiops/workbench/db/dao/CdrVersionDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortDao.java
- api/src/main/java/org/pmiops/workbench/db/model/CdrVersion.java
- api/src/main/java/org/pmiops/workbench/utils/PaginationToken.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/ParticipantCounterTest.java
- api/src/test/java/org/pmiops/workbench/test/SearchRequests.java
TODO: use review statuses
TODO: use CDR version
TODO: support returning anything other than participant IDs.
Sample request/response:
*Request:*
curl -H "Authorization: Bearer ya29.GlwfBQYkQt-ghPCV9kqy15m-1qb_rWBpQtJeAQ_LkHMXpizIeF4e4QyK6VQbGu9geBnA7MkTNf8XHdNpqHr9ksoK7mJ2btb9FRE3TDnQjifF61z_rVV2ZZDt6X3lJw" -H "Content-Type: application/json;charset=utf-8" -X POST -d '{"cohortName": "Danz cohort", "pageSize": 10}' http://localhost:8081/api/v1/workspaces/aou-free-test--2116819717/aaaa/materializeCohort
*Response:*
{"results":[{"person_id":1},{"person_id":2},{"person_id":4},{"person_id":5},{"person_id":6},{"person_id":7},{"person_id":8},{"person_id":12},{"person_id":14},{"person_id":16}],"nextPageToken":"eyJvZmZzZXQiOjEwLCJwYXJhbWV0ZXJIYXNoIjoxOTg1NDYyNDE0fQ=="}
> [RW-122] Returning participant IDs in materialize cohort endpoint.

- .circleci/config.yml
Our CircleCI test task is so noisy it's hard to even follow the logs. Plus, there is so much logging that you often have to download the log to view it, since Circle will only display the first 400k characters (which should be plenty). This PR makes Circle's web UI useful again.
> Less noise in Circle test

- ui/src/app/data-browser/ConceptClasses.ts
- ui/src/app/data-browser/chart/chart.component.ts
- ui/src/app/data-browser/lazy-tree/lazy-tree.component.ts
- ui/src/app/data-browser/mobile-charts/mobile-charts.component.ts
- ui/src/app/data-browser/my-concepts/my-concepts.component.ts
- ui/src/app/data-browser/search/search.component.ts
- ui/src/app/data-browser/services/achilles.service.ts
The current UI build process generates some warnings caused by a long-standing bug in the Typescript compiler where it has difficultly recognizing a module's exported _types_ when the same module exports concrete objects (classes, constants, etc).
Given that in typescript, a class definition actually generates an interface and may be used as an interface where necessary, the most expedient means by which to remove the build warnings is to remove the extraneous interface triggering them, which I have done.
> remove redundant interface

- api/build.gradle
It appears that Gradle forks the JVM when running tasks. According to `top`, when running tests, our memory usage steadily increases. This change causes the JVM forks to start with less memory so that the tests finish before the memory usage grows beyond the upper bound.
Helpful info on solution:
https://discuss.gradle.org/t/travis-ci-org-gradle-launcher-daemon-client-daemondisappearedexception-gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-have-crashed/13106/3
> Reduce memory usage in tests

- api/build.gradle
Without removal, I see the following when creating a new account (which attempts to read invite keys from GCS):
```
api_1                    | Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
api_1                    | 	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
api_1                    | 	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:73)
api_1                    | 	at com.google.cloud.RetryHelper.run(RetryHelper.java:73)
api_1                    | 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
api_1                    | 	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:194) …
```
> Drop guava dep from build.gradle to fix GCS access

- api/config/config_test.json
Test env is currently broken, as it appears that all DB rows were dropped as of last night (12/19) around 9PM PST (more likely, the tables were deleted then recreated).
Workbench currently fails on user initialization (required for most calls), as it cannot create new billing projects for any user that already has one.
> Update billing project prefix

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench.yaml
The existing GET and PUT methods for `ParticipantCohortStatus` objects did not share an endpoint; now they do.
> GET and PUT participant statuses from the same endpoint

- api/build.gradle
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/auth/UserAuthentication.java
- api/src/main/java/org/pmiops/workbench/auth/UserInfoService.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
Allowing pet SAs to use our API; resolving them to their corresponding user record by calling /me on FireCloud.
Making user records created for GSuite domain users that don't already have them on any API call.
Changing dev-up to run db-data-migration (to insert CDR version row.)
> Enforcing that only GSuite domain users get user records.

- api/src/main/resources/workbench.yaml
This is not a very heavy refactor.  I noticed that [swagger lets you specify shared path parameters](https://swagger.io/docs/specification/2-0/describing-parameters/) and realized we could cut some of the copy-pasted stuff in `workbench.yaml` by using those, and I also stripped the quotes from response status codes (for uniformity). As you can see, there's a net reduction of 400 lines, which is nice.
Oh I also used swagger's `basePath` path-prefixing ability for API versioning as seen [in swagger's docs](https://swagger.io/docs/specification/2-0/api-host-and-base-path/)
> Swagger cleanup some path variables

- api/src/main/resources/workbench.yaml
Apparently swagger ignores `basePath` and swagger 3.0 replaces it entirely anyways, so this PR reverts that change from the last one (restoring the `/api/v1` prefix to all API endpoints).
https://github.com/swagger-api/swagger-codegen/issues/5244
> Restore path prefix since swagger ignores basePath

- api/src/main/resources/workbench.yaml
Our current plan is to deploy our UI at something.org and our API at api.something.org. URLs are important for usability, so ours should be as short and meaningful as possible. Given the aforementioned scheme, the "api" part is redundant, so this PR removes it.
> Remove "api" from API URLs

- api/src/main/java/org/pmiops/workbench/config/CommonConfig.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
This [1] says:
> - Google App Engine: use com.google.api.client.extensions.appengine.http.UrlFetchTransport.
>   - com.google.api.client.apache.ApacheHttpTransport doesn't work on App Engine because the Apache HTTP Client opens its own sockets (though in theory there are ways to hack it to work on App Engine that might work).
>   - com.google.api.client.javanet.NetHttpTransport is discouraged due to a bug in the App Engine SDK itself in how it parses HTTP headers in the response.
[1] https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.19.0/com/google/api/client/http/HttpTransport
`com.google.api.client.googleapis.util.Utils.getDefaultTransport` returns `com.google.api.client.javanet.NetHttpTransport`. This PR uses `UrlFetchTransport` in both places.
> Use UrlFetchTransport as HttpTransport for Google client library

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- api/src/main/java/org/pmiops/workbench/db/model/ParticipantCohortStatus.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortReviewDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/WorkspaceDaoTest.java
- Clone cohorts and reviews when cloning a workspace.
- Add a `CohortService` to later support a standalone `CloneCohort` method
- `@Autowire` the workspace controller to achieve better similarity to the server environment (this required adding `setUserProvider`, as I couldn't figure out how to bind a dynamic value for user/userProvider in the test configuration).
> [RW-285] Clone cohorts and reviews on workflow clone; fix tests

- ui/src/app/cohort-search/criteria-wizard/attributes/attributes.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/selection/selection.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/wizard/wizard.component.spec.ts
- ui/src/app/cohort-search/overview/overview.component.spec.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.spec.ts
- ui/src/app/cohort-search/search-group-list/search-group-list.component.spec.ts
- ui/src/app/cohort-search/search-group/search-group.component.spec.ts
- ui/src/app/views/cohort-edit/component.spec.ts
- ui/src/app/views/cohort-edit/component.ts
This should be considered temporary until the UI is designed to include spinners, etc - really, rather than providing dummy data for the frames when the component is rendering before the API call comes back, either (A) the data should be loaded via a resolver or (B) we should separate the form from the data (via the reactive forms framework) and have them disabled - perhaps with a spinner - until the data is loaded.
> Hotfix name errors in CohortEditComponent

- ui/src/app/app-routing.module.ts
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
- Multiplex workspace edit page into a total of 3 modes: edit, create, clone
- Clone has an existing workspace, and redirects to the new workspace upon creation
- Using a standin icon from clr for copy (the same used for the cohort clone option); let me know if there's a better asset I should be pulling in
> [RW-286] Implement Clone UI

- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
- User could not edit when cloning readonly workspaces
- Reset the editor saving/error states upon transient clone failure
> Fix a few clone UI bugs

- .circleci/config.yml
Previously, we would only explicitly call `ng build` when attempting to deploy, which only happens on master merges.
Without this change, I believe we do have partial compilation checks in place, but only for files which were transitively included for `ng test`.
> [RW-341] Always ng build in Circle

- .circleci/config.yml
Split UI test and compile into separate stages. `ng build` is super spammy and pushes down the test output failures.
> Split out test vs compile

- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/config/CacheSpringConfiguration.java
This should allow Spring to figure out metadata about the database while it's starting, and still require clients to specify CDR version afterwards.
> Make CdrDataSource return default CDR version during initialization.

- api/config/config_local.json
- api/config/config_test.json
- api/docker-compose.yaml
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/resources/workbench.yaml
- ui/package-lock.json
- ui/package.json
- ui/src/app/app.module.ts
- ui/src/app/services/error-reporter.service.ts
- ui/src/app/services/server-config.service.spec.ts
- ui/src/app/services/server-config.service.ts
- ui/src/app/services/sign-in.service.ts
- Log uncaught client-side errors to Stackdriver
- Add dependency on `stackdriver-errors-js` and `stacktrace-js`
- `window` hackery to get `stackdriver-errors-js` working properly, since it's not a real module (https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/2)
- Add a "server config" section for 
- Create a wrapper for `ConfigService` which effectively produces a singleton `Observerable<ConfigResp>`
- Split into local/test config.json files
> [RW-145] Add optional Stackdriver reporting, refactor configs

- ui/src/app/cohort-search/overview/overview.component.ts
Saving a cohort on the cohort search app was not correctly redirecting to the workspaces overview.
> Bug fix RW-356

- ui/src/app/charts/chart-container/component.ts
- ui/src/app/cohort-review/cohort-review/cohort-review.component.ts
- ui/src/app/cohort-review/directives/fullPage.directive.ts
- ui/src/app/cohort-review/participant-detail/participant-detail.component.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.ts
- ui/src/app/cohort-review/set-annotation-detail/set-annotation-detail.component.ts
- ui/src/app/cohort-review/set-annotation-master/set-annotation-master.component.ts
- ui/src/app/cohort-search/charts/google-chart.directive.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/criteria-wizard/attributes/age-form.component.ts
- ui/src/app/cohort-search/criteria-wizard/attributes/attributes.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/attributes/attributes.component.ts
- ui/src/app/cohort-search/criteria-wizard/explorer/explorer.component.ts
- ui/src/app/cohort-search/criteria-wizard/selection/selection.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.spec.ts
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.ts
- ui/src/app/cohort-search/criteria-wizard/wizard/wizard.component.spec.ts
- ui/src/app/cohort-search/overview/overview.component.spec.ts
- ui/src/app/cohort-search/redux/actions/service.spec.ts
- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.spec.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.ts
- ui/src/app/cohort-search/search-group-list/search-group-list.component.spec.ts
- ui/src/app/cohort-search/search-group/search-group.component.spec.ts
- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.ts
Removes a leading underscore used to indicate privacy of a property unless the underscore is preventing the variable from shadowing a keyword or other variable (such as `_type`) or the underscore is part of a managed property, i.e.
```
class SomeClass {
private _theProperty;
get theProperty() {/* ... */}
set theProperty(value) {/* ... */}
}
```
> cleanup unwanted underscore prefixes

- api/libproject/devstart.rb
so that it spits out public fields to vars.env stored in GCS.
> Changing command for generating DB creds

- api/config/config_local.json
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/AuditController.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/interceptors/CronInterceptor.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/cron.xml
- api/src/test/java/org/pmiops/workbench/api/AuditControllerTest.java
- api/src/test/java/org/pmiops/workbench/interceptors/CronInterceptorTest.java
Implements the policy described https://docs.google.com/document/d/14HT1GWXHPMaCc9rhCM0y5CglAIY-GgRBwebdZpqwEDs
Endpoint is to be called as an app engine cronjob (which just takes a GET URL). Adds a daily cron config and updates deployment to support it.
Assumptions:
- This endpoint is light-weight enough to allow it to run on the API servers
- We're fine for now just using log metric based alerting, when we want to enable those
- It's fine to load all FC project IDs into memory
> [RW-146] Implement BigQuery audit logs endpoint + cron

- api/libproject/devstart.rb
(What I hadn't realized earlier -- when using %W{} as we are, it's important that each array element passed in is non-empty.)
> Fixing deploy

- api/libproject/devstart.rb
(Apparently --version was being dropped before when it was on its own line.)
> Really fixing build

- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java
- api/src/main/resources/application.properties
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Prior to this change, the `spring.datasource.*` settings in application properties were ineffective (beyond basic connection info for the workbench data source). In the standard single DB approach, the `DataSource` is wired up by applying `@ConfigurationProperties` onto it. In our case, this was the Tomcat data source, which implements `PoolConfiguration`, allowing autosetting of tomcat-related pool properties. With the multidb approach, we're no longer using full autoconfiguration, so we need to be more explicit about what is being autopopulated with properties.
- Moves the DB-related properties onto a custom namespace "workbench", since they cannot be used interchangeably with the standard spring properties (e.g. the tomcat property does nothing).
- For now, we use a single shared …
> [RW-349] Fix property plumbing to data sources

- .circleci/config.yml
- api/build.gradle
- api/libproject/devstart.rb
This adds about two minutes to our CircleCI runs, which isn't great, but gives us a jumping off point for iterating.
> Check API dependencies for vulnerabilities

- api/libproject/devstart.rb
- client/libproject/devstart.rb
- ui/libproject/devstart.rb
The rationale behind this change is that it is onerous to need to go through and find the Common.register_command piece whenever we change a dev script. Also, this means that when adding a new dev script, we just need to add code in one place, and not in two.
> Move command register to be with command.

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
- Note: the cloner can modify any of these fields before cloning.
- Try to guess whether the cloner would want to tick the "review requested" box
- Also fix a bug in editability of the diseaseOfFocus.
> Populate all research purpose details by default in the clone UI

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
I wound up debugging this anyways; the Jira issue wasn't really necessary. On an unrelated point, while I was here I dropped the auth modifier. It doesn't seem to be necessary (my requests go through without).
For some reason Spring didn't like `StatusApi` as a binding key; I tried a qualifier on a whim and it worked:
```
api_1                          | Caused by: 
api_1                          | org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.pmiops.workbench.firecloud.api.StatusApi' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
api_1                          | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory …
```
> [RW-383] Fix StatusApi binding

- ui/src/app/views/account-creation/component.ts
`this.contactEmail` is no longer referenced as an input, so validation permafails currently.
> Fix account creation validation

- api/db-cdr/generate-cdr/cloudsql-import.sh
- api/libproject/devstart.rb
- Set up service account key before running
- Don't require account passed in; just use appengine service account
- Make SA owner on the file (it won't be if it's not all-of-us-workbench-test)
- Wait for the import to finish after it's kicked off.
> Fixes to Cloud SQL import script

- .gitignore
- ui/package.json
Adds a simple command `yarn run coverage` that will run the test suite and generate a code coverage report.
> Add yarn coverage command

- .circleci/config.yml
- api/libproject/devstart.rb
Note that integration tests still fail locally with errors like:
rg.pmiops.workbench.google.DirectoryServiceImplIntegrationTest > testDirectoryServiceUsernameIsTaken FAILED
com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
at com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:800)
at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:112)
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:40)
at com.google.api.client.extensions.appengine.http.UrlFetchRequest.execute(UrlFetchRequest.java:74)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
at …
> Fixing Ruby for integration, bigquery test

- api/src/dev/server/Dockerfile
- api/src/dev/server/with-uid.sh
- ui/src/dev/server/Dockerfile
- ui/src/dev/server/with-uid.sh
Previously we only checked for the root user which caused problems when a dev was unlucky-enough to have a UID matching one of the users in the image.
> Warn when UID is set to ANY existing user

- api/db/changelog/db.changelog-26-billing-status.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/tools/build.gradle
- Add explicit free tier billing project status tracking and plumb through to the client
- Fix our representation of the Firecloud billing projects API to match reality
- Move BigQuery role granting from `CreateWorkspace()` -> `initializeUser()`; this seemed a more appropriate place, and I don't think we should be seeing any projects in AoU that we haven't initialized ourselves.
- Write the config file when cloning, as is done during workspace creation
> Synchronize clone() behavior with create()

- .circleci/config.yml
- api/libproject/devstart.rb
(This will hopefully get the SA key file in the deployment and make account creation work properly.)
Removing unnecessary gsutil commands from circle config
> Moving gsuite admin SA fetch before appengine stage.

- api/db/build.gradle
I think we're going to want a new command line utility specifically for managing rows in cdr_version soon... and then shift to using that here as well. But for now, this fixes a bug.
> Fixing passing of CDR and public DB name into CDR version insert.

- .circleci/config.yml
- ci/Dockerfile.circle_build
Sending for review, but I haven't yet been able to test this. Need access to dockerhub to test images. Alternative to using `dockerize` would be to loop with `nc -z 127.0.0.1 3306`; this might be relatively hairy bash to put in the config file though. I *believe* a single `nc` invocation would not necessarily cover the issues we're seeing (though it's proven difficult to repro).
Local `circleci build` also fails for me:
```
$ circleci build --job api-local-tests -v $(pwd):/home/circle/workbench
====>> Spin up Environment
Build-agent version 0.0.4710-44beb0a (2018-02-27T20:05:34+0000)
Starting container allofustest/workbench:buildimage-0.0.10
using image allofustest/workbench@sha256:bb261fd62fa3124c44e80cbdeca9eb5bff06cf697c7083f4efdfb26a53c0b492
Starting container mysql:5.7
using image …
```
> [RW-410] Await MySQL startup in Circle

- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
(In Cloud, what I had before would fetch back api:circle-ci-test, which isn't really helpful... for now we'll just hardcode "api-" on front.)
> Switching to api prefix to avoid weirdness

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
THis logging would have been useful last week when we started reported notebook service down due to a cert issue (vs notebook service returning a negative response).
> Add logging on status check failure

- ui/libproject/devstart.rb
The CircleCI logs are getting clogged up with spammy build percentage stuff, this should suppress that. 
Example: https://circleci.com/gh/all-of-us/workbench/8150
> Suppress build output when merging to master

- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/cluster-service-stub.ts
This moves things closer to my [design doc proposal](https://docs.google.com/document/d/1GbaL1otgswBEOqfte8JO8uQDG_vSEG4a-qcKMEdufLI/edit), while leaving things in a mostly-working intermediate state.
Key changes:
- Switch from 1 cluster : researcher+workspace to 1 cluster : 1 researcher
- Change the assumed directory structure on the notebook cluster.
- Switch cluster creation to be lazy on GET (using a generic List endpoint to support future extension)
- Remove several as-of-yet unneeded Cluster APIs from Workbench
- Update the notebooks UI to directionally match what we want (not really matching any particular mocks yet, though).
- Drop the concept of cluster management.
- Drop explicit localization and notebook select/multiselect. Just click a notebook to open.
Changes to follow:
- …
> Switch cluster creation to lazy, reduce API/UI surface

- ui/src/app/cohort-search/redux/actions/service.ts
If the last item is removed from a search group, we should remove the search group.
> Fix: Removing the last item should remove the group

- ui/src/app/services/sign-in.service.ts
I noticed this error in the console, and also noticed signout being broken.
`this.currentAccessToken` gets set on `subscribeToUser()`, so the deleted line appears redundant to me. If it was actually necessary for some weird reason, should rework to guard against the signed out case.
Please merge this for me or hijack my branch if needed, I will likely not be online when this is reviewed.
> [RW-429] Fix SignInService in the signed out case

- ui/libproject/devstart.rb
- ui/src/app/services/error-reporter.service.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
- ui/src/environments/test-env-base.ts
Unfortunately I couldn't come up with a better way to detect whether we were running a local development deployment or not. Using the protocol as a proxy is the best I got. Let me know if you have any ideas on this (deployed should always be https, else it's probably local).
My requirements are that SD reporting is disabled for a local workstation deployment, continue to be enabled the test GAE UI, and that I don't depend too much on what host devs access their local deployment on, e.g. localhost vs 0.0.0.0 vs myhostname etc.
Here's what I tried:
- `isDevMode()` - this is `true` in test
- `process.env.ENV === 'production'`; this is a signal that the Angular app has been compiled for production. I believe it will be set when we `ng build --prod` (I've not verified though). Unfortunately …
> [RW-425] Disable Stackdriver for http:// hosts, to catch local dev; always log

- api/libproject/devstart.rb
- api/scripts/README.md
- api/scripts/setup_notebook_cluster.sh
- Push new pyclient release
- The default `pip` version as of the latest Leo image is 3.4, this explains why I wasn't able to see AoU installed on py2.7 kernels; install on both
- Autopush scripts on circle-deploy
- Add docs for testing local changes to user scripts
Confirmed locally that this user script fixes the py2/3 issue.
> Update pyclient, install for both py2.7 and py3.4, document/deploy scripts

- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PhecodesQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/ParticipantCounterTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/PhecodesQueryBuilderTest.java
It turns out we didn't really need it anywhere... and queries should run faster without it I believe. 
All BigQuery tests pass, a bit faster than before.
> Removing distinct from BigQuery SQL

- ui/src/app/resolvers/workspace.ts
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
- Reduce spinner count on the workspace page from 4 -> 2, now it's just the two tables
- Use the resolver-provided `Workspace`, instead of double-requesting
- Disable "new notebook" and keep spinning the notebooks table until your cluster is online
> Simplify workspace loading flow

- api/db/vars.env
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java
- api/src/main/resources/application.properties
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
- public-api/src/main/resources/application.properties
This enables sharing the CDR DBs across multiple nonprod environments.
Also:
- Fix a several setup_project bugs in `devstart.rb`
- Remove dead functions from `devstart.rb`
Notes:
- This is desirable as the CDR itself is shared across nonprod environments and it is slow to produce the CDR SQL databases.
- The plan is to use the `all-of-us-workbench-test` DB instance as the shared nonprod CDR db.
- There is no requirement that the SQL instance be in `all-of-us-workbench-test` or any other environment. This is just an existing environment which already has a Google MySQL instance.
> [RW-440] Support loading the CDR DBs from a different SQL instance

- ui/src/app/cohort-review/cohort-review.module.ts
- ui/src/app/cohort-review/detail-procedures/detail-procedures.component.css
- ui/src/app/cohort-review/detail-procedures/detail-procedures.component.html
- ui/src/app/cohort-review/detail-procedures/detail-procedures.component.spec.ts
- ui/src/app/cohort-review/detail-procedures/detail-procedures.component.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
Note to the sharp-eyed: this PR adds a component `detail-procedures` which is almost identical to `detail-conditions`.  I believe that eventually each of the review tabs may be similar enough to warrant having them derive from a common component superclass (or using a common template or what have you), but at the moment we're not _exactly_ sure how different they will eventually be.  So the plan basically is to perform the refactor (if there will be one) after each concrete tab has been built so that we know exactly what a superclass needs to provide and don't burn time / energy implementing stuff that never gets used.
> Add Procedures tab table

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/utils/OperatorUtils.java
- api/src/main/resources/client_api.yaml
and, ors, not recursively.
Adding NOT_EQUAL operator.
> Switching filters specification in API to allow for arbitrary

- ui/src/app/cohort-search/criteria-wizard/explorer/explorer.component.html
- ui/src/app/cohort-search/criteria-wizard/quicksearch/quicksearch.component.html
This is a temporary measure to prevent users from hitting RW-417 while we wait on finalized specs for the behavior, look, and feel of the search bar.
> Stopgap: comment out search bar

- .circleci/config.yml
- ui/libproject/devstart.rb
- ui/src/app/cohort-review/cohort-review.module.ts
- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/cohort-search/criteria-wizard/explorer/explorer.component.ts
- ui/src/app/cohort-search/criteria-wizard/quicksearch/quicksearch.component.ts
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.ts
- ui/src/app/cohort-search/overview/overview.component.ts
- ui/src/app/data-browser/data-browser.module.ts
- ui/src/app/data-browser/one-concept/one-concept.component.html
- ui/src/app/views/app/component.ts
- ui/src/app/views/error-handler/component.ts
- ui/src/app/views/profile-page/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
The 2-3s stall-time on initial page load dissipates with `--aot` enabled, which leads me to believe that during this time the browser is mostly doing JIT compilation. It may be that we recently brought in more Typescript deps somehow, which is why this seemingly got worse recently, but `--aot` has never been enabled for our GAE deployments.
We don't want to enable this locally as it takes way longer to recompile after a change. Later I would like to do further compilation optimizations, but there's a bunch of NgModule problems blocking that.
> Build with --aot for deploys; fix compilation errors

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/notebooks.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- Dynamically materialize config files rather than writing from GCS -> localizing, using the [Jupyter server contents API](https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API). Dynamically materializing is vastly preferred to writing a file to GCS, as we no longer need to worry about outdated config files.
- Pull in parts of the Jupyter Server API swagger into `notebooks.yaml` to formalize the above calls
- Write a second config file, `.delocalize.json`, when localizing notebooks. This enables delocalization on Leonardo (only for clusters created as of 1 week ago).
Two major things to cleanup here:
- There are a lot of serial calls to Jupyter server happening here to initialize the directory structure we want. This could be fixed in several ways, possibly with FRs to Leo. …
> Enable delocalization on AoU Leo clusters

- .circleci/config.yml
- ui/libproject/devstart.rb
- ui/src/environments/environment.prod.ts
Also unifies the Circle and deploy usage of `yarn build`, and adds a command so that you can run a standalone `build` with the same settings.
`--prod` takes about 2 minute
`--aot` takes about 1 minute
On normal Circle runs, check that `--aot` works. `--prod` felt slightly too slow for this case.
`--aot` seems to catch most of the compilation errors one would hit with `--prod`. `--prod` includes `--aot`, but primarily adds tree-shaking and uglification.
> Use --aot in test, --prod elsewhere

- ui/src/app/app-routing.module.ts
- ui/src/app/services/sign-in.service.ts
The goal of this change is to avoid the flicker of the signed-out screen, as described in [[RW-458]](https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=planning&selectedIssue=RW-458)
> Wait on initial nav for gapi to load

- ui/src/app/views/account-creation/component.html
- ui/src/app/views/invitation-key/component.html
This is to remove the lorem ipsum text from our UI before the April 16th launch. We should consider whether we want a contact to ask for an invitation key from.
> Eliminate account creation lorem ipsum

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/resources/client_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilderTest.java
Moving logic to generate an Iterable<Map<String, Object>> into FieldSetQueryBuilder and AnnotationQueryBuilder. (CohortMaterializationService then constructs a response from it.)
Adding logic to enforce that annotations can't be named "person_id" or "review_status". 
(I'm working on tests now.)
> Implementing annotation queries using native SQL.

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/breadcrumb/component.css
- ui/src/app/views/breadcrumb/component.html
- ui/src/app/views/breadcrumb/component.ts
- ui/src/app/views/signed-in/component.html
https://precisionmedicineinitiative.atlassian.net/browse/RW-486
* Add new breadcrumb component
* Re-organized the workspace routes a little bit so the breadcrumb trail makes sense
* Added links for all of the workspace sub pages
* I still need to add tests for this but wanted to get through the AoU commit->PR process before the day is out.
* An artifact of using routes for breadcrumbs is that when we add it to any branch of the routing tree, we need to add it to all of the branch children as well.
Workspaces:
Workspace
Cohort Builder
Edit Workspace
Share Workspace
Clone Workspace
> RW-486: Breadcrumbs

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/resources/client_api.yaml
("not" is a reserved word in Python, and hence Swagger generates this field as "_not"; using something else like ifNot produces nicer Python client lib code.)
> [RW-510] [RW-511] Renaming not to ifNot, fixing log message order

- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.ts
- ui/src/app/views/invitation-key/component.spec.ts
- ui/src/testing/stubs/profile-service-stub.ts
- We were submitting both on form submit and click, so one would generally fail with a 409
- We were doing username checks on empty string, which was a 403 error
- Add regression test
- Clean up dead properties
> [RW-528] Don't double-create accounts, don't check for username ''

- api/libproject/devstart.rb
- ci/Dockerfile.circle_build
- deploy/libproject/deploy.rb
- deploy/libproject/jirarelease.rb
- For staging: creates a new release ticket
- For stable (later prod): finds an existing ticket, adds a comment
- Override JIRA calls/setup with --no-update-jira
- Still getting the JIRA account setup, but this PR assumes there are basic auth creds in a JSON file in GCS.
- Only create a ticket *after* a successful deploy. If a deploy fails partway through, we'll need to manually intervene.
Caveats:
- The flag interactions and defaults are a bit hairy
- Should be possible, but will require the right flag munging to recover if a deploy fails halfway-through
> Integrate jira-ruby into deploy tool

- .circleci/config.yml
This should now generate a JIRA release ticket when we cut a new build.
Also:
- Make test releases quicker
- Reuse the keyfile for API/UI deploys in test
> Leverage new deploy script in Circle

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
This is actually not required when creating a Firecloud account.
> [RW-431][RW-512] Don't set a Firecloud contact email

- .circleci/config.yml
There are multiple test logs to link to in the release ticket, so the workflow link is better here, e.g. https://circleci.com/workflow-run/08953d2e-570b-41bf-8a2e-6df1ec38e456
> Better CircleCI release URL

- api/config/config_test.json
This was enabled temporarily with #721 to debug an auth issue. That issue has been resolved now and this generates a lot of log spam.
> Disable FC debug logging in test

- api/libproject/devstart.rb
I'm going to add a note in the environment setup documentation about how in prod you should change the maintenance release channel / timing to production / later. For all other environments we're using "preview" so we find out earlier if a new version of Cloud SQL gives us trouble.
> Setting maintenance window settings for project setup script.

- ui/src/app/app-routing.module.ts
This route has no attached component anymore, sharing is in a modal. Cleaning up.
> [RW-592] Remove share route

- deploy/libproject/deploy.rb
Confusingly without this, `v` gets set to `true`
> Fix --circle-url flag setup

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
Previously if a delete failed, all subsequent test runs would fail as they share a single constant ID. This also reduces the likelihood of conflicts between two simultaneous test runs.
> Use a (likely) unique username for directory service testing

- api/scripts/setup_notebook_cluster.sh
Tested locally. This is currently a no-op as Leo hasn't split out these kernels in prod yet. Luckily Leo appears to not care that these kernels don't actually exist yet.
> [RW-541] Disable upcoming pyspark{2,3} kernels

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/test/java/org/pmiops/workbench/exceptions/ExceptionUtilsTest.java
- ui/src/app/views/settings/component.ts
- ui/src/app/views/workspace/component.ts
- Fix bug in throwing 504s
- Retry polling on errors
- Shift cluster create slightly later
Considered making `CreateCluster()` async, but longer-term I don't think we really want this. Better to get a concrete status from this call before continuing. As Leo improves the CreateCluster endpoint, this will get faster.
> [RW-620] [RW-623] Improve CreateCluster interactions

- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.ts
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
Demo: https://calbach-dot-all-of-us-workbench-test.appspot.com
You'll need to create a new account to hit the initialization flows.
Also:
- Serializes `getProfile` -> `getWorkspaces` on the list workspaces page; partially addressing RW-608 (@UrsaStutsman FYI).
- Fixing notebooksLoading logic (now we don't get a flash of an empty table on initial load)
> [RW-520] [RW-608] Update spinner treatments for workspaces and notebooks

- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.html
BQ's default format looks like `2008-10-04 00:00:00.000 UTC`, which is good enough, particularly since it seems likely we'll drop support for timestamps and use only dates in the affected field.  If we begin using custom formats we'll need to either (A) parse the string into Dates before handing off to `DatePipe` or (B) find another solution besides `DatePipe`
@rushtong tagged as the reporter or the original error
> Remove timestamp formatter

- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/auth/UserInfoService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
Changing clients to catch WorkbenchExceptions or just throw them back to the client.
Note there are some cases here where we would have returned a 500 before (for ServerErrorException) but now return whatever error FireCloud gave us... in general I think that's OK.
> Changing FireCloudService to no longer throw ApiException.

- ui/src/app/services/sign-in.service.ts
Check whether the response came back before checking access token. I believe that if there is no AuthResponse, the user is signed out.
> [RW-662] Null check to authResponse

- ui/src/app/cohort-search/constant.ts
We have a pair of errors from stackdriver that most likely are generated by the fact that there is not yet any data in the Physical Measurement trees.  While those errors are being investigated, we'll just turn off access to PM in the UI.  Besides, the UI for PM needs to be redone anyways.
> Disable Phys Meas for the time being

- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
This fixes two issues with the modifiers page.  First, for the category "event date", we erroneously had "on or before" mapped to "greater than or equal to" (and similarly for "on or after").  This is basically just a typo.  
Secondly, when reinstantiating the modifiers page with existing data (i.e. when editing an existing search group item) we need to use `patchValue` rather than `setValue`, as the latter will complain if there is no data for the secondary form field (`valueB`) as there often is not.  This is the bug discussed in RW-658.
There is another path to the kind of bug RW-658 discusses, and that is for the user to deliberately supply bad information (i.e. select an operator that needs two operands but only supply one).  However, form validation will need to be implemented …
> Modifier fixes

- ui/src/app/views/admin-review-id-verification/component.html
- In the short term, contact email will be the way to manually verify an identity (combined with our email verification).
- Merge researcher first/last name into one column to free up some real estate.
> [RW-695] Add the contact email to the ID verification page

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
At some point these codepaths diverged and we started maintaining two regexes. The original regex did not capture notebook filenames with spaces. This was fixed in `listNotebooks()`, but not in `cloneWorkspace()`.
> [RW-760] Consolidate notebook pattern matching, add regression test

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/BugReportController.java
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/BugReportControllerTest.java
- ui/src/app/views/bug-report/component.css
- ui/src/app/views/bug-report/component.html
- ui/src/app/views/bug-report/component.ts
If requested, makes a best effort to grab notebook logs from the researcher's cluster and attaches them to the bug report email. We have no other way of accessing these logs currently, because only the user has access to their own cluster.
It should be possible to refactor this code to use the Jira attachment API, once we switch bug reporting to use that.
> [RW-760] Add optional notebook log dump to bug reporting

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/homepage/component.css
- ui/src/app/views/homepage/component.html
- ui/src/app/views/homepage/component.ts
Demo (manually hacked with `hasDataAccess()` always returning `false`):
https://calbach-dot-all-of-us-workbench-test.appspot.com/
`enforceRegistered` is not `true` anywhere currently, though I would like to move to requiring it in staging/stable per RW-712.
These pages are changing, so the UI details I think are not too critical. In general, I do think we need a more directed initial profile setup flow than what we currently have, so ultimately this data access check might manifest differently. The main thing is just getting the plumbing and logic setup here. 
Also, update the button styling so the disabled homepage buttons don't look clickable.
> [RW-782] Gate homepage -> workspaces on data access, if enforceRegistered

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Partly addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-805
There is more work to do, so this PR does not complete 805.
Relates to https://github.com/all-of-us/workbench/pull/912
* Set the user's email verification status in the right place. We no longer need to use mailchimp to know if the user's email is verified now.
* Remove outdated test
> [RW-805][risk=no] Set user email verification in the right place

- .codacy.yml
This glob seemingly only matched files at the root. The config file documentation is quite sparse, but this new approach seems to be the way that many other repo's setup their globs.
> [RW-745][risk=no] Attempt to fix Codacy globs

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/OfflineClusterController.java
- api/src/main/java/org/pmiops/workbench/auth/ServiceAccounts.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineClusterControllerTest.java
- Update Leo APIs
- Factor out service account access token creation
- Add an endpoint which cleans up running notebook clusters
- Add configuration for the maximum allowed lifetime for a cluster
A follow up change will add the cronjob configuration for this.
> [RW-767][risk=low] Implement a notebook cluster cleanup cron

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
Apparently the default instance of a bean still needs to be qualified when injected.
> [risk=no] Fix cluster API

- api/build.gradle
- public-api/build.gradle
https://precisionmedicineinitiative.atlassian.net/browse/RW-696
https://precisionmedicineinitiative.atlassian.net/browse/RW-697
Upgraded jackson library to the latest. The recommended solution is to upgrade to 2.9.4 or higher. I chose to bump that to the latest version instead. 
See security warning here: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32043
Tested both unit tests and integration tests locally. Tested functionally via a versioned deployment.
> [RW-696][RW-697][risk=no] Upgrade Jackson

- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/account-creation/component.ts
A mismatch at the end of the string means we have to traverse a graph with binary branching for the `.` vs `.char`. Add regression test.
Also drop `'` from valid username characters, was this included by mistake?
> [RW-755][risk=no] Avoid n^2 regex pattern

- deploy/libproject/jirarelease.rb
- Chomp the newline after the commit
- Only one star needed for Jira bold (it would seem)
> [risk=no] Tweak release ticket formatting

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-41-billing-project-retry.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Open question (which is somewhat rhetorical): Should we log the error message we get back from Firecloud? I assume yes, but it will involve reworking what we get back from list billing projects to include a bit more info than just the status.
> Retry billing project creation twice

- .codacy.yml
Hopefully I will have better luck with a more explicit file path. Unfortunately ignoring this file via the UI got overruled on the next Codacy run, where it presumably pulled in codacy.yml again. I've chipped away at the style rules to the point where this is the only remaining file with issues...
> [risk=no] Yet another attempt at Codacy exclusion

- ui/src/app/app-routing.module.ts
- ui/src/app/views/homepage/component.ts
- ui/src/app/views/workspace-list/component.ts
Consistent with the rest of the `/workspaces` URLs, as well as the pattern used for `/cohorts/build`.
> [risk=no] workspace/build -> workspaces/build for consistency

- ui/src/app/views/workspace/component.ts
Cookie seemingly wasn't getting set without this, though it worked during local testing (possibly my cookie hadn't expired yet).
> [risk=low] Add missing withCredentials

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
- ui/src/app/app.module.ts
- ui/src/app/views/workspace/component.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Note that this doubly encodes the Leo API URL on client (environment.ts) and server (config.json).
Alternative considered:
Add the leoBaseUrl to the ServerConfigResponse.
+ (+) Single definition
- (-) Higher complexity introduced by instantiating Notebook-related services in an asynchronous manner
- (-) Possible race conditions if notebook requests get made before we get back the server config response
> [RW-847][risk=low] Switch local/test to FC/Leo dev 

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/utils/index.ts
- ui/src/app/views/notebook-redirect/component.css
- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/cluster-service-stub.ts
- ui/src/testing/stubs/leo-cluster-service-stub.ts
- Add a new notebook page which waits for the cluster to load, sets up auth, and localizes or creates a notebook.
- Drop the notebook spinner from the workspaces page, instead opening/creating a notebook brings you to the new redirect page.
- Rough out a framework for a loading UX with more detailed messaging on this page (UX input pending).
- ~~Fix a bug in postMessaging of the clientId to Leonardo (I may split this out to get that in sooner)~~ https://github.com/all-of-us/workbench/pull/950
TODO
- ~~Unit test for the new view~~
- UX is a placeholder, getting input from Lou on this
- ~~Related: UX pending - we may not want the nav bar on this view~~
~~For future PRs~~
- ~~Integrate cluster "resume" into this new page~~
> [RW-680][RW-432][risk=low] Notebook redirect instead of modal

- api/build.gradle
- public-api/build.gradle
Huge kudos to @biopete for finding the source of the issue. 
See [RW-934](https://precisionmedicineinitiative.atlassian.net/browse/RW-934). We started to see errors in overnight processes with swagger validation. This update seems to fix the problem.
> [RW-934][risk=no] Upgrade GAE-gradle and swagger gen libraries

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
I realize from the PR history that using this list in all environments was intentional. That said, it's very confusing to find this in our configs, and most reasonable people would assume this was a bug. Fixing this now to avoid future developers burning time looking into this.
> [RW-948][risk=no] Use a less confusing ID verification list name

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/resources/workbench.yaml
This API predated me. This is not used by any Workbench client code currently.
FYI @danqrodney in case you remember some context on this.
> [risk=no] Drop unused request invite key API

- api/libproject/devstart.rb
I think that we should deploy demos to GCS separately from other artifacts, I just felt kind of weird pushing our startup script at the same time as demos. They are kind of separate things. (In that one is getting created by developers, and the other theoretically by scientists)
Please also:
* Verify all tests go green, …
> [RW-859][RW-860] Separate demos from other gcs artifacts

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
(It turns out the roles returned from FireCloud are "Member" not "member"... local testing confirmed this fix.)
> Making member comparison case-insensitive [risk=no]

- ui/src/app/views/homepage/component.css
- ui/src/app/views/homepage/component.html
The rest of the codebase uses 2-space indentation. I tried to apply this to all CSS files in the codebase, but this was the only one using 4 spaces. The regex for finding HTML which violate this rule was too complex so I just fixed the dashboard template (most use 2-space, but it's possible there are some using 4-space).
I just created a PR since this felt to nitpicky to ask for a follow-up PR on...
> [risk=no] Code spacing fix on homepage

- public-ui/src/environments/environment.local.ts
- public-ui/src/environments/environment.prod.ts
- public-ui/src/environments/environment.stable.ts
- public-ui/src/environments/environment.staging.ts
- public-ui/src/environments/environment.test.ts
- public-ui/src/environments/environment.ts
- clientId is not needed since data browser does not do login
- `testing` was unused
- `allOfUsApiUrl` was oddly included only in staging
- add a prod environment file
> [RW-940][risk=low] Clean up public-ui environment files

- ui/src/app/services/profile-storage.service.ts
This is a bit of a band-aid to avoid users getting stuck in a "failed to load profile state", which will be much more likely once I add the IDV redirect page. There may be other ways to also reduce parallel calls by the client or improve the API impl.
> [RW-1010][risk=low] Retry on getProfile 409s

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/guards/registration-guard.service.ts
- ui/src/app/services/profile-storage.service.ts
- ui/src/app/views/unregistered/component.html
- ui/src/app/views/unregistered/component.spec.ts
- ui/src/app/views/unregistered/component.ts
- ui/src/testing/stubs/profile-service-stub.ts
- ui/src/testing/stubs/profile-storage-service-stub.ts
This changed logic only applies when enforceRegistered is enabled. This currently affects staging/prod, but soon will also affect stable.
New logic:
- For nearly all signed in pages, guard according to data access level.
- If the user does not have registered access, redirect them to the new "unregistered" page.
- The unregistered page will submit IDV request, ToS, demographics, training, if any of the above have not already been submitted.
If a registered access user hits the unregistered page, they will be redirected according to the "from" parameter (if any), or the dashboard homepage otherwise.
> [RW-930][risk=no] Add unregistered view and guard to redirect to it

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- ui/src/app/services/profile-storage.service.ts
- ui/src/app/views/unregistered/component.html
- ui/src/app/views/unregistered/component.spec.ts
- ui/src/app/views/unregistered/component.ts
- ui/src/testing/stubs/profile-service-stub.ts
- Return conflict errors from registration-related profile methods as needed.
- For users who are already ID verified, and are missing other fields, we'll now submit the rest and redirect after.
- Retry registration API conflict errors
> [RW-1033][RW-712][risk=low] Retry IDV failures and navigate on completed registration

- api/build.gradle
- api/tools/build.gradle
- common-api/build.gradle
- public-api/build.gradle
* Lock dependency versions: https://precisionmedicineinitiative.atlassian.net/browse/RW-321
* Upgrade okhttp version: https://precisionmedicineinitiative.atlassian.net/browse/RW-699
This PR sets all flexibly specified versions to the actual version that gets pulled in. While there, I addressed the okhttp story since it was easy.
This PR does not address many reported snyk errors. In the cases where there are fixes, they require code changes which is not in scope. Several others have no remediation. I am detailing those here for reference.
Upgrading the following library causes problems for some developers. Choosing to ignore this until we have a better solution. 
```
✗ Medium severity vulnerability found in com.google.guava:guava
Description: Deserialization of Untrusted Data
Info: …
```
> [RW-321][risk=low] Make flexible dependency versions fixed

- api/config/config_stable.json
(+) Makes staging, stable, prod all consistent w.r.t. user registration. Now exercise the same codepaths.
(-) New users in stable will need to be ID verified. For now we can have a process where users request this via slack in `#workbench-beta` (will need to communicate this change).
(-) In terms of business need, this verification is only required in production, since other environments will only contain synthetic.
Note: if users want to create many accounts without waiting on human verification, they can still use the test environment.
> [RW-712][risk=no] enforceRegistered in stable

- ui/src/app/views/signed-in/component.ts
ProfileStorageService does an initial `reload()` upon creation. The only reason to call `reload()` again here is if the logged in user were to change - we no longer allow this to occur in a single client session (by forcing a hard page reload).
Currently going to any signed in page will result in to calls to `/me` (1) from the ProfileStorageService ctor and (2) from this code, which introduces more chances for conflict exceptions.
Also, please let me know whether this inline styling is needed.
> [RW-1033][risk=no] Avoid spurious profile reload

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
Currently, you will consistently get an initial profile conflict error when you first login *if* you had first enabled 2SV.
> [RW-1033][risk=no] Handle more profile conflict errors

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
it's a data problem. The extra result that is now showing up in the test has a birthday of 08/01/1980.
> [RW-1078][risk=no] fixed broken BQ test case.

- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/account-creation/component.ts
This also changes the username field to display errors live, even when the username is in focus, because it was weird to not be able to click next and have no validation about why.
Please also:
> [RW-1052][Risk=no] Block account creation until after username taken returns

- ui/src/app/cohort-review/create-review-page/create-review-page.html
- ui/src/app/cohort-review/create-review-page/create-review-page.ts
Hides message on Generate Review page that shows the max participants allowed for cohort review if the cohort has less than 10000 participants. Fixed cancel button to route back to cohorts instead of workspace page.
> [RW-763][RW-1054][risk=no] Fix max participants, cancel button for Generate Review

- ui/src/app/guards/sign-in-guard.service.ts
- ui/src/app/utils/index.ts
- ui/src/app/views/login/component.spec.ts
- ui/src/app/views/login/component.ts
- ui/src/app/views/signed-in/component.ts
Unfortunately we can’t fix this without doing a deeper rework of our sign in flow (switching to server side oauth) or breaking certain users' ability to login (reverting to the previous pop-up approach) because we can’t generate a dynamic redirect URI while also matchin our redirect whitelist. I tried tacking on query parameters and hash fragments, nothing makes it through, and GoogleAuth doesn't appear to have any capability to attach extras onto the sign in call.
Secondarily, this removes the navigation on user signout, as this caused a navigate/reload combo which made the page half-navigate and half-render on sign out before reloading the page.
> [RW-1055][risk=no] Drop the login "from" feature for now

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/WorkspaceUserRole.java
- api/src/test/java/org/pmiops/workbench/db/model/WorkspaceUserRoleTest.java
See ticket for background. Looking for feedback on this pattern. If it looks good, will apply to all other stored enum values as well.
> [RW-872][risk=low] Don't store enum ordinals for WorkspaceAccessLevel

- api/build.gradle
- common-api/build.gradle
- public-api/build.gradle
I just looked back at the history and see possible complications per https://github.com/all-of-us/workbench/pull/958... Will review what happened there.
The reason I want this is that the Google `Truth.assertWithMessage()` fails with older guava versions.
> [risk=low] Bump Guava to 26.0

- ui/src/app/cohort-search/modal/modal.component.html
I'm not sure how intentional this language was, so feel free to run by the rest of CB team if you think this change would be controversial. In general our product guidance has been to spell out any program-specific acronyms.
> [risk=no] Spell out AoU in drug criteria hint

- ui/src/app/app-routing.module.ts
- ui/src/app/cohort-review/routing/routing.module.ts
- ui/src/app/views/breadcrumb/component.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1118
Updated the breadcrumb displays for the following cohort pages:
* Create new cohort
* Review cohort
* View cohort page (Overview/Participants)
* Edit Cohort
> [RW-1118][risk=low] Update cohort breadcrumb displays

- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
Setting an unescaped URL to the window location escapes only as needed, which is why notebooks with spaces in the name currently work fine.
However, strings that are already URI escaped will not be re-escaped here, we therefore need to explicitly escape before redirecting. Else for example a notebook containing `%2B` (+), gets unescaped as `+`, which causes downstream failures on redirection.
> [RW-1042][risk=low] URI encode notebook names during redirection

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDao.java
- api/src/main/java/org/pmiops/workbench/db/model/CohortAnnotationDefinition.java
- api/src/main/java/org/pmiops/workbench/db/model/CohortReview.java
- api/src/main/java/org/pmiops/workbench/db/model/ParticipantCohortStatus.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerMockTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortAnnotationDefinitionDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/model/StorageEnumsTest.java
PR 3/3 for converting workbench off enum ordinal value storage.
> [RW-1132][risk=low] Don't store cohort builder enum ordinals

- ui/src/app/views/login/component.css
- ui/src/app/views/login/component.html
- ui/src/index.html
We could not actually use the font we used elsewhere for sign in, per [google's branding guidelines](https://developers.google.com/identity/branding-guidelines), but we weren't actually loading the font correctly. This loads in the font and displays it properly.
Please also:
> [RW-1113][Risk=no] Fix font for sign in button

- api/build.gradle
After a docker-clean, I was getting the following exception upon trying to read the invite key from GCS:
```
api_1                          | Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
api_1                          | 	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
api_1                          | 	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:73)
api_1                          | 	at com.google.cloud.RetryHelper.run(RetryHelper.java:73)
api_1                          | 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
api_1                          | 	at …
```
> [risk=low] Exclude guava5 everywhere

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
Hashing the spec string instead of the SearchRequest object in order to
avoid issues with non-stable hashing of enums.
(It's a little simpler to keep pagination handling logic in CohortMaterializationService from a testing perspective.)
> [RW-1149] Moving parsing of cohort spec into CohortMaterializationService. [risk=no]

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
Nicole is frequently wedging her cluster due to running too much intensive processing (likely RAM-limited). Since autopause is now in effect, we should be able to justify using a slightly better machine (1vcpu, 4GB) -> (2vcpu, 8GB)
> [RW-1217][risk=no] Bump machine size to n1-standard-2

- .github/PULL_REQUEST_TEMPLATE.md
I'm tired of seeing this boilerplate, and when left undeleted it obfuscates any description the author might have written. With this change, you'll still see the template when you create a new PR, which I think is the only real purpose for it.
Alternatively, I might argue to remove this entirely since `CONTRIBUTING.md` is linked in the sidebar when you create a new PR. We can leave that idea for future discussion.
> [risk=no] Comment out PR template so it's only visible on creation

- .circleci/config.yml
This turned out to be pretty easy, I was just very confused about what the "build" task was doing in gradle.
For posterity, here is what I was originally trying out:
```
gradle build integration -x test
```
i.e. "build the integration target but skip the tests".
This actually just tells gradle to run the "build" task, followed by the "integration" task, while excluding the "test" task. This caused compilation issues because "integration" depends on the "test" compilation target in order to get some of it's deps, like the "common-api". By not building that, I was getting failures importing those classes into test classes.
`build` is actually just a default task installed by the Java plugin as outlined here: https://docs.gradle.org/current/userguide/java_plugin.html#_lifecycle_tasks , it is …
> [RW-968][risk=no] Compile integration tests in Circle

- ui/src/app/views/unregistered/component.html
- ui/src/app/views/unregistered/component.spec.ts
- ui/src/app/views/unregistered/component.ts
This should only display if you do an initial load of the unregistered page. A loading spinner would be better here, but this page is a stop-gap anyways.
> [RW-1147][risk=no] Display loading text on unregistered page

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/resources/client_api.yaml
- api/src/main/resources/workbench.yaml
Implementation of each will come later.
For the moment, I'm not proposing we deprecate materializeCohort... there may be clients that can't easily query BigQuery themselves, and could still use it. But we won't use it anymore in our pyclient library once this gets implemented.
> [RW-1286] Adding getDataTableQuery and getCohortAnnotations methods [risk=no]

- ui/src/app/views/app/component.html
- ui/src/app/views/routing-spinner/component.css
- ui/src/app/views/routing-spinner/component.html
- ui/src/app/views/routing-spinner/component.ts
- ui/src/app/views/signed-in/component.css
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.spec.ts
Ultimately I think this may have come down to a browser rendering issue, AFAICT the HTML/CSS stacking order defined did not match what was being rendered in the browser - my interpretation is that a correct rendering would have placed the spinner on top of everything (including the top-nav). Toggling various CSS properties on/off (and returning to the original CSS state) in chrome inspector resulted in things reaching the correct state. I remain perplexed as to why the browser rendered the top-nav on top of the loading screen at all, it seems by sheer coincidence this happened to also be the desired behavior.
Ultimately to solve this I made two changes:
- Switch from opacity-based visibility to "display", this seems to be more obvious signal for the browser to redraw (rather than scaling …
> [RW-1289][risk=no] Fix z-index loading screen rendering problems

- api/src/main/resources/client_api.yaml
Making query optional. 
Removing unused matchType and standardConcepts fields. (We'll worry about handling mappings from non-standard to standard concepts in a follow-up.)
This just changes the API; implementation changes will follow.
> [RW-1277] Adding per-domain and per-vocab counts to concept search API.

- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.ts
- ui/src/app/views/routing-spinner/component.ts
A side-effect of #1217 removed the initial loading screen. This seems useful to have e.g. when you initially sign into workbench (and your profile is super slow), so add back in an initial routing spinner (full-screen, not limited under the top-bar).
> [risk=no] Bring back the initial full-screen routing spinner

- public-ui/package.json
- public-ui/yarn.lock
- ui/package.json
- ui/yarn.lock
Even in the latest version of `@clr/ui`, they still depend on an older version of bootstrap which we'd already upgraded off of. I ran the UI locally - compilation worked and I didn't notice any obvious issues clicking around.
> [RW-1373][risk=no] Upgrade bootstrap

- api/build.gradle
- api/buildSrc/src/main/groovy/org/pmiops/workbench/tooling/IncrementalHotSwapTask.groovy
Simple refactor - move the `IncrementalHotSwapTask` class to `buildSrc` for a cleaner build file.
Tested locally by spinning up a local instance, making some minor code changes, and watching the console rebuild.
> [risk=no] Refactor Hotswap class

- api/db-cdr/changelog-schema/db.changelog-18.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
Shows the schema changes I'm hoping to have to our Cloud SQL metadata... the synonyms column will allow for faster concept searching, and the domain_vocabulary_info table for faster vocab count retrieval when the user hasn't entered a search term yet.
> Adding synonyms column to concept, domain_vocabulary_info table

- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
Depends on https://github.com/all-of-us/workbench/pull/1234
Note: due to the 60% page-width consistency on the clone page, this will wrap to the next line on most screens. Not sure if that affects the UX and whether we want more spacing beneath
Screenshots:
> [RW-1312][risk=no] Add checkbox for cloning collaborators

- ui/src/app/views/workspace-nav-bar/component.css
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.spec.ts
- ui/src/app/views/workspace-nav-bar/component.ts
Notes:
- Put activated contents inside the button, required dropping the borders/padding 
- Required removing the intermediate button borders for now; implementing them with the clarity button group is tricky - possibly a follow-up (note: the mocks show the dividers spanning only about 75% of the button heights, whereas the current implementation spans 100%)
Demo: https://calbach-dot-all-of-us-workbench-test.appspot.com/
> [RW-1341][risk=no] Implement selected tab styling

- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/testing/stubs/concept-sets-service-stub.ts
- ui/src/testing/stubs/concepts-service-stub.ts
Also adds support in the concept sets stub to optionally add a concept service stub dependency for cross-integration (e.g. adding concepts by ID).
Screenshot:
> [RW-1285][risk=no] Implement "remove concepts" from concept set support

- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/AbstractQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/MeasurementQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PMQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PPIQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PhecodesQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/VisitsQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/resources/client_api.yaml
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/CdrJpaConfig.java
- api/src/test/java/org/pmiops/workbench/testconfig/TestJpaConfig.java
Changing API to return a generic "configuration" dictionary, rather than a list of query parameter values. (This is what pandas.read_gbq is going to use, is a bit more flexible for changes in future, and it's simpler than converting QueryParameterValue to the previous parameter objects.)
Working on tests now.
> [RW-1286] Implementing getDataTableQuery [risk=no]

- api/db-cdr/generate-cdr/cloudsql-import.sh
- api/libproject/devstart.rb
generate-cloudsql-db runs in service account context now for the project specified in the argument so it works in all projects.
> Biopete/build w sa [risk=low]

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
This replaces materialize cohort, and allows us to remove the materialize_cohort functions from the python client (and replace them with API calls specifically for getting annotations.)
> [RW-1451] Implementing getCohortAnnotations [risk=low]

- api/config/cdr_versions_local.json
- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/tools/src/main/java/org/pmiops/workbench/tools/UpdateCdrVersions.java
- Fix prod CDR configs to point to an actual CDR that's available in prod (it's currently broken)
- Rename to "Dataset" to avoid the opaque "CDR" acronym
- Require an "id" in CDR JSONs; use this as the primary key
-> I prefer this to introducing a new ID type
> [RW-1416][RW-1355][risk=low] Rename CDRs, fix prod CDR config

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/resources/client_api.yaml
- api/src/test/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
Adding columns to CdrQuery, CohortAnnotationsResponse; these will be used to give the names of columns in resulting data frames (whether or not there are any results.)
> Fixing annotation DB reading of enum values. [risk=no]

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
null is an expected input here, as a recent resource is a union of different types; cohorts and concept set resources will not have a notebook path.
> [risk=no] Don't log null when converting notebook names

- ui/src/app/views/workspace-edit/component.ts
As requested by karthik, commenting out the Fill later option on workspace edit page . Since we will be expanding the requirements in coming sprints, i have just commented it out rather than removing the functionality itself
> [RISK=NONE]Removing fill details later option on workspace edit page

- ui/src/app/views/workspace-share/component.html
- ui/src/app/views/workspace-share/component.ts
- Previously 500 errors appeared to succeed
- When choosing "reload workspace", also restore the current workspace collaborators
> [RW-547][risk=no] Show unexpected errors on share

- ui/src/app/app-routing.module.ts
- ui/src/app/views/app/component.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.ts
- ui/src/environments/test-env-base.ts
- ui/src/index.html
https://precisionmedicineinitiative.atlassian.net/browse/RW-436
Moves the GA tracking id from the index page into the app so we can make use of different IDs per environment. The ids provided have been created in GA.
I copied from two places for the bulk of the code here: 
* https://developers.google.com/analytics/devguides/collection/gtagjs/
* https://github.com/angular/angular-cli/issues/4451#issuecomment-384992203
> [RW-436][risk=no] Add env-specific GA ids

- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
(It used to say "limit null"... now it doesn't have a limit.)
> [RW-1503] Fixing SQL when max_results is null and outer SQL is generated. [risk=no]

- ui/src/app/app-routing.module.ts
- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.ts
Because we don't want the components to be simultaneously rendered on the page, we actually just need a component-less router entry above "concept sets" in the route hierarchy to place the breadcrumb. I forgot about these component actions so I misadvised here.
Separately I forgot to set the loading property on my modal.
> [risk=no] Fix concept set details routing and loading

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Previously we depended on inter-window communication between Workbench and Leo to communicate the Oauth client ID to use for credential refreshes. This was brittle and would fail in particular basic modes, e.g. copy-paste a link or closing the original parent tab.
This inter-tab communication also somehow broken within the past few releases so currently we don't seems to plumb through a client ID at all, i.e. tabs die after 1h.
I've confirmed locally that this properly plumbs down the client id.
> [RW-474][risk=low] Set a default cluster oauth client ID on all Leo clusters

- ui/src/app/views/new-notebook-modal/component.ts
- ui/src/app/views/resource-card/component.ts
This actually wasn't working anyways on account of a Leo regression. We now set a default client ID server side as of #1385 .
> [RW-474][risk=no] Tear down inter-tab communication code

- ui/src/app/views/concept-add-modal/component.html
- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.ts
- ui/src/testing/stubs/concept-sets-service-stub.ts
- Concept set deletion now redirects to concept sets list page
- Concept removal uses disabled FAB UX
- Fix disablement of "add to set" FAB and selected count (+some refactoring)
- Minor wording tweak on "add to set" modal
> [RW-1530][RW-1533][risk=no] Concept set bug fixes

- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-578
- Include authuser in cloud console link, it's typical for users to be multilogged in (especially with the research account as secondary) since we require creation of a second google account to use workbench.
- Open in a new tab by default
> [RW-578][risk=low] Fix GCS link for multilogin users

- ui/src/app/views/concept-set-list/component.ts
> [RW-1559][RISK=NO]Bad formatting for concept set tooltip

- api/src/main/resources/emails/welcomeemail/content.html
This has a problem. The links only work when you click on the text, and the blank space is not a click target. It properly represents with cursors though, and it is functional.
> [RW-1577][Risk=no]Not great email formatting, but the links work. 

- ui/yarn.lock
This happened automatically after starting the UI for me - doe the same happen for you? Not sure why I'd have two versions.
> [risk=no] Update yarn lock to match Jasmine upgrade

- api/db/changelog/db.changelog-52-user-nonce.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/config/CommonConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/test/FakeLongRandom.java
- ui/src/app/views/account-creation-modals/component.spec.ts
- ui/src/app/views/account-creation-modals/component.ts
- ui/src/app/views/account-creation-success/component.html
- ui/src/app/views/account-creation-success/component.spec.ts
- ui/src/app/views/account-creation-success/component.ts
- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/account-creation/component.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1233
- Store a random int64 on account creation and return it
- Require that unauthenticated "resendWelcomeEmail" and "updateContactEmail" calls provide this value, effectively limiting those calls to the same account creation client session.
- Implement a `FakeLongRandom` class for testing purposes, faking out the whole Random implementation was too onerous.
> [RW-1233][risk=low] Implement an account creation nonce to secure resend/updateContactEmail

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-1598
I'd consider null to be an invalid input to this method, and I'd rather not mask any bugs that might arise from this returning false.
> [RW-1598][risk=no] null recent resource regression test (slightly contrived)

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-1671
Previously, update workspace ignored any changes to the research purpose that were submitted from the UI, but handled it correctly on create and clone. This change adds the same save-research-purpose functionality back into update workspace.
> [RW-1671][risk=no] Save Research Purpose Update Workspace 

- deploy/libproject/deploy.rb
https://precisionmedicineinitiative.atlassian.net/browse/DB-51
Prod databrowser was temporarily disabled while we implemented a sign-in gate on the site. This work has been completed now by Bru: [DB-89](https://precisionmedicineinitiative.atlassian.net/browse/DB-89).
> [DB-51][risk=low] Reinstate public API/UI deploys in prod

- ui/src/app/views/concept-add-modal/component.css
- ui/src/app/views/concept-add-modal/component.html
- ui/src/app/views/concept-add-modal/component.spec.ts
- ui/src/app/views/concept-add-modal/component.ts
This fixes the mismatch of display from text area and input on the create concept, and makes it so if there are no concept sets in the domain, we keep the UX consistent and display a tooltip to the user regarding the lack of concept sets.
> [RW-1702][Risk=no] Fix display of concept modal

- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
This reverts commit ce6ac784bbb9517d53107dc4eb2ebc086384dddd.
The original PR may have fixed issues with certain notebook names, but broke our URI encoding model. This includes notebooks with spaces in the name, e.g. all of our demo notebooks.
> [RW-1754][RW-1667][RISK=LOW][P3] Revert "Notebook name with special chars (#1533)"

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/db-cdr/generate-cdr/run-achilles-queries.sh
1. Standard concepts which are also source concepts were being counted as two different concepts (even after the standard concepts having source count in source count value)
2. This was causing two rows of data and disrupting graphs.
> [risk=no] DB-142 (Adding source concept check during count generation)

- api/src/main/webapp/WEB-INF/web.xml
- public-api/src/main/webapp/WEB-INF/web.xml
Requested by Neil N.
Note: In production this only serves as defense-in-depth, as we require access via the "WAF", which performs the https upgrade as well.
> [risk=no] Require https for API services

- api/config/config_prod.json
At least one user has already hit this limit and is stuck. Adding more retries on billing account creation may allow their account to be restored.
> [risk=low] Increase FC billing account creation retries in prod

- api/db-cdr/generate-cdr/make-bq-public-data.sh
- public-api/src/main/java/org/pmiops/workbench/cdr/model/QuestionConcept.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-api/src/main/resources/public-api.yaml
- public-api/src/test/java/org/pmiops/workbench/cdr/DataBrowserControllerTest.java
- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.ts
- public-ui/src/app/views/survey-view/survey-view.component.ts
1. Some drug concepts also seem to be in procedure occurrence table causing two sets of achilles results of different domain, so filtering the results in any domain page to display only of that domain.
2. Not rounding the source count value of concepts from 0 to 20.
3. Displaying only top ten source concepts.
> [risk=no] DB-15 [6-7] Filtering achilles results by domain and rounding source counts only > 0 and not = 0

- api/demos/Get Started in R Notebooks.ipynb
Typo fixes and also two changes per the recent update to the leonardo image:
* Python is now version 3.6
* the qwraps2 package is failing to install due to a missing system dependency.
> [risk=low] Update paths for notebook extensions

- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/cb_search_api.yaml
- api/src/main/resources/client_api.yaml
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/jira.yaml
- api/src/main/resources/mandrill_api.yaml
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
With the new Swagger (2.4). We need to make sure to add the parameter consumes - application/json to post/put/patch endpoints that have params in their bodies. If the endpoint has no params, or only params in their path, do NOT add this parameter!
> [No ticket][Risk=low] update aou-utils

- public-api/src/main/java/org/pmiops/workbench/cdr/model/QuestionConcept.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
The prod data has weird age deciles like 11 (110-120), 98 and such. 
Filtering away those results to make the bar graph look clean.
> [risk=no] Display only valid age deciles in graph

- ui/package.json
- ui/src/app/components/icons.tsx
- ui/src/app/components/tables.tsx
- ui/src/app/utils/index.ts
- ui/yarn.lock
This adds some basic components for tables, pagination, and sortable headers. The style is currently modeled on the Clarity table, but that can be changed later. The current implementation does a basic flex layout, which works best for small tables with limited rows and columns, but it could be replaced with a "virtual scroll" implementation later, if desired.
> [risk=no] add table components

- ui/src/app/components/buttons.tsx
This adds a basic button component with the existing style variants. Usage is like this:
`<Button onClick={...}>Save</Button>`
`<Button type='secondary' onClick={...}>Cancel</Button>`
There's a lightweight wrapper for tracking hover state. We can decide later whether it's worth bringing in a heavier library like `react-interactive` later.
The lower level `Clickable` component can serve as a useful abstraction of basic button-like behavior (specifically disabled state), without any styling baked in. It can be used as a base for one-off icon buttons, menu items, etc.
Note: This is currently using a div element without any accessibility attributes, due to some unfortunate browser behavior around disabled buttons. So it does not score well from a screen reader or keyboard perspective. Looking …
> [risk=no] add buttons

- ui/package.json
- ui/src/app/components/modals.tsx
- ui/src/app/views/account-creation-modals/component.tsx
- ui/src/main.ts
- ui/yarn.lock
This introduces the `react-modal` library for backing our modal implementation. Main benefits:
* The modal is rendered in a 'portal', meaning the markup appears at the end of the body element. This ensures that it always appears over the main content without worrying about z-index.
* It does focus management, ensuring that a user cannot tab out and interact with the underlying page while the modal is open.
It also has hooks for doing animations, if we want to wire that up at some point.
> [risk=no] add react-modal

- ui/src/app/utils/index.ts
- ui/src/app/views/quick-tour-modal/component.tsx
I went down a bit of a rabbit hole here... but ultimately the behavior is pretty close to what we want with minimal boilerplate. Only real limitation is incompatibility with arbitrary levels of style tuple nesting.
Also, eventually the TS compiler should just handle this for us: https://github.com/Microsoft/TypeScript/issues/11152
> [risk=no] CSS typing proposal

- ui/src/app/components/modals.tsx
- ui/src/app/utils/index.ts
There are AoT [compilation issues](https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60#ahead-of-time-aot-compile) with the current `@ReactComponent` decorator approach. The compile error isn't totally clear, but I suspect it's stemming from having a functional decorator that returns another decorator (at least, that's the first error we hit when using this approach):
```
./project.rb build --environment test
...
ERROR in app/views/rename-modal/component.tsx.ts(25,2): Error during template compile of 'RenameModalComponent'
Function expressions are not supported in decorators in 'ReactComponent'
'ReactComponent' contains the error at app/utils/index.ts(155,31)
Consider changing the function expression into an exported function.
```
I also tried switching `ReactComponent` to be …
> [risk=no] Uglier but AoT friendly ReactWrapper approach

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
Full details: https://precisionmedicineinitiative.atlassian.net/browse/RW-1939
This line was deleting data it shouldn't have. My understanding is that this deletion was an optimization and not a functional requirement, so just log it for now. In the future, we should reassess our technical design in this area - i.e. what the expected behaviors are and how we want AoU+FC workspaces to interact.
> [RW-1939][risk=no] Do not delete workspaces when keeping FC/AoU in sync

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/resources/client_api.yaml
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/SurveyModule.java
- common-api/src/main/resources/common_api.yaml
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-api/src/test/java/org/pmiops/workbench/cdr/DataBrowserControllerTest.java
1. Modified concept search to fetch counts by searching with wildcard* and to fetch actual concepts by the exact match.
2. Added order number ordering in survey results fetch.
Detail:
Bug: This line https://github.com/all-of-us/workbench/blob/master/common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java#L85 for wildcard * search 
is causing DB-190 issue.
For Eg: Search on 507 code fetches all the concepts that have 507 in concept code along with the source concept that is exact match and the standard concept of the particular source concept.
Eg matched codes: 50792001, 50749006, 50799005, 507, 50711007.
So fixed this line to add wildcard* only in the case of fetching survey counts.
Reason to add this when fetching survey counts is the survey angular view fetches all the …
> DB-190 [Wildcard* search causing issue on source vocabulary search]

- ui/package.json
- ui/src/tsconfig.jest.json
- Allows tsx tests to reference "jest" without compilation failure.
- `yarn test` doesn't compile tsx tests
- `npx jest` now complains on compile failure, to match previous behavior of `yarn test`
> [risk=no] Split out karma/jest tsconfigs - only compile one or the other

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
See https://precisionmedicineinitiative.atlassian.net/browse/RW-1970
Proposed procedure:
Please approve and merge this PR (please merge yourself - no need to wait for me), pull `ch/v1-3-rc6` locally and perform the normal cherry-pick process in the playbook from there (no need to do full Workbench QA as there are no changes - just verifying that the homepage loads will suffice).
This particular change isn't going into master because we're in an odd position where the fix already exists in master, but isn't isolated to a clean commit.
I've verified this fixes RW-1970 locally.
> [RW-1970][risk=no] Fix SurveyModule native SQL

- ui/src/app/app.module.ts
- ui/src/app/services/fetch.module.ts
This will allow for injection of fetch-based API stubs with proper credential plumbing and without explicit inclusion of the base URL. See the module comment for details.
I believe we'll likely want these kinds of services available via `props` once we're fully on React. @panentheos to sanity check that assertion.
CC: @UrsaStutsman 
Example usage:
- https://github.com/all-of-us/workbench/pull/1663
- https://github.com/all-of-us/workbench/compare/srubenst/settings-page...ch/fetch-fix?expand=1
> [RW-1972][risk=low] Add a swagger codegen fetch module

- ui/src/app/utils/index.tsx
Converts the main utils file to tsx, so we don't have to keep using `createElement`. This is its own PR to make sure git parses it as a rename, to make merges and rebases easier.
> [risk=no] convert utils to tsx

- ui/src/app/components/alert.tsx
- ui/src/app/components/forms.tsx
- ui/src/app/components/headers.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/components/modals.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/views/invitation-key/component.tsx
Adds a little HOC to abstract the pattern of applying styles to a base element, while still allowing explicit overrides. Forwards `ref` to the wrapped element.
> [risk=no] add withStyle

- ui/src/app/app-routing.module.ts
- ui/src/app/utils/navigation.tsx
This exposes the `navigate` and `navigateByUrl` methods via a module, so they can be used by React components without injecting.
Usage:
```
import {navigate} from 'app/utils/navigation';
<Button onClick={() => navigate(['somewhere'])}>
```
Note: Angular routing seems to be extremely fragile, which is why the code is formulated the way it is. Specifically, the actual call to `navigate` must originate from within a Component class, so we need to store callback functions to make that happen.
> [risk=no] expose navigation for react components

- ui/src/app/components/headers.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/views/account-creation-modals/component.tsx
- ui/src/app/views/account-creation/component.spec.tsx
- ui/src/app/views/account-creation/component.tsx
- ui/src/app/views/invitation-key/component.tsx
- ui/src/app/views/rename-modal/component.tsx
Introduces `TextInput` and `TextArea` components to standardize the basic text input appearance. The exact design may be tweaked with e.g. nicer focus outlines and success/error states, but I wanted to get the abstraction in place so people can start using it.
n.b. Width defaults to `100%`, but can be overridden via `style`
> [risk=no] standardize text inputs

- ui/src/app/views/concept-set-list/component.html
- ui/src/app/views/concept-set-list/component.ts
- ui/src/app/views/notebook-list/component.html
- ui/src/app/views/notebook-list/component.spec.ts
- ui/src/app/views/notebook-list/component.ts
- ui/src/app/views/rename-modal/component.spec.tsx
- ui/src/app/views/rename-modal/component.tsx
- ui/src/app/views/resource-card/component.html
- ui/src/app/views/resource-card/component.tsx
- ui/src/testing/stubs/workspaces-api-stub.ts
Cleans up the code and UX of the notebook rename modal. Notes:
* The modal now handles the rename itself, rather than delegating out to the parent container, so it should work properly and consistently in all locations.
* Performs inline validation to give the user feedback sooner. Pre-loads the notebook list when the modal mounts in order to provide duplicate name validation.
* Cleans up unused code in notebook list and concept set list.
Note: The two commented error paths should be entirely unexpected/unknown errors, so I think just logging is ok for the moment, but we should come up with a more robust solution for those kinds of error cases soon.
> [risk=no] improve notebook rename flow

- ui/src/app/utils/index.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/workspace-nav-bar/component.ts
This adds an HOC to enable components to access the current workspace from the route. It injects a prop `workspace` of type `WorkspaceData`. Usage is similar to other HOCs:
```const MyComponent = withCurrentWorkspace()(BaseComponent)```
> [risk=no] add withCurrentWorkspace

- ui/src/app/components/spinners.tsx
- ui/src/app/views/rename-modal/component.tsx
Adds a standard spinner overlay component. Can be used to provide feedback that an action is in progress, as well as block the underlying UI.
Typical usage is to set `position: relative` on the container you want to overlay, then conditionally render the `SpinnerOverlay` inside that container (at the end, to make sure it's on top of other elements).
See the included example (note that modals already `position: relative` on them)
> [risk=no] add spinners

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
Checking NIH status requires an authenticated request. When creating a new account, the request is not authenticated.
> [risk=no] Fix auth on account creation

- common-api/src/main/java/org/pmiops/workbench/interceptors/SecurityHeadersInterceptor.java
- public-ui/app.yaml
- ui/app.yaml
... now that it's been working for a while.
> [risk=low] Bump strict-transport-security max-age from 1d -> 1y

- .circleci/config.yml
Stolen from @zarsky-broad and split out ahead of https://github.com/all-of-us/workbench/pull/1723 to mitigate high flakiness we're seeing.
https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
> [risk=no] Use --runInBand to mitigate jest timeouts

- ui/tsconfig.json
Revert ECMAScript version to es5 due to issue in cohort builder
> [risk=no] Revert back to es5

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortreview/ReviewQueryBuilder.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-2076
- Reverts https://github.com/all-of-us/workbench/pull/1728 temporarily, tried fixing the tests here but I don't understand the original issue fully and I'm not sure about expected behavior so should wait on @freemabd1 . Per discussion with @dolbeew , sounds like this is an existing issue which is probably not critical to the next release.
- Fixes error message testing to match updated behavior from #1727 .
> [RW-2076][risk=low] Fix BigQuery integration tests

- .circleci/config.yml
- common-ui/common-ui-devstart.rb
https://yarnpkg.com/lang/en/docs/cli/cache/
https://circleci.com/docs/2.0/caching/#yarn-node
Also freeze yarn.lock generation on Circle + deploys for improved determinism.
On a sample run, this reduced `yarn install` runtime from ~30 -> ~18s. Not great, but at least it's following the standard docs.
> [risk=no] Cache the yarn cache

- api/src/dev/server/Dockerfile
- ci/Dockerfile.circle_build
- public-ui/src/dev/server/Dockerfile
- ui/src/dev/server/Dockerfile
Some project.rb commands result in `Failure: 'getpwuid(): uid not found: 1992018429'` in certain situations, particularly when creds are uninitialized. There are other ways to get around it, but downgrading avoids the issue entirely.
https://github.com/GoogleCloudPlatform/gsutil/issues/575
> [risk=no] Downgrade gcloud to 215.0.0 to avoid gsutil error

- ui/src/app/components/containers.tsx
Adds a react version of `app-top-box`, renamed to FadeBox for Terra compatibility. It has a more conservative styling without built-in margins, so it's not a drop-in replacement. As components get converted, they typically get re-styled anyway, so switching at that point should be the most straightforward.
> [RW-1895][risk=no] add FadeBox

- ui/src/app/utils/navigation.tsx
- ui/src/app/views/app/component.ts
- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/cohort-list/component.ts
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-list/component.ts
Creates a few new observable 'stores' to extract route-related info from the angular router.
`urlParamsStore` contains the raw params object
`routeConfigDataStore` contains the `data` object from the route definition
Also converts a couple components to use the stores, removing dependency on the router.
> [RW-2080][risk=no] proxy route data for react conversion

- ui/src/app/cohort-review/overview-page/overview-page.spec.ts
- ui/src/app/cohort-review/overview-page/overview-page.ts
- ui/src/app/cohort-review/page-layout/page-layout.spec.ts
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-review/query-report/query-report.component.spec.ts
- ui/src/app/cohort-review/query-report/query-report.component.ts
- ui/src/app/utils/navigation.tsx
This creates `currentCohortStore` as a mechanism to expose the current cohort without depending on the router. Also converts `page-layout` and `overview-page` as example usages.
> [risk=no] extract current cohort from route

- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-review/review-state.service.ts
- ui/src/app/cohort-review/set-annotation-create/set-annotation-create.component.spec.ts
- ui/src/app/cohort-review/set-annotation-create/set-annotation-create.component.ts
- ui/src/app/cohort-review/set-annotation-item/set-annotation-item.component.spec.ts
- ui/src/app/cohort-review/set-annotation-item/set-annotation-item.component.ts
- ui/src/app/cohort-search/demographics/demographics.component.spec.ts
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.spec.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
- ui/src/app/cohort-search/overview/overview.component.spec.ts
- ui/src/app/cohort-search/overview/overview.component.ts
- ui/src/app/resolvers/cohort.ts
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/app/component.ts
- ui/src/app/views/concept-add-modal/component.spec.ts
- ui/src/app/views/concept-add-modal/component.ts
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/app/views/conceptset-create-modal/component.spec.ts
- ui/src/app/views/conceptset-create-modal/component.ts
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/signed-in/component.ts
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
This transforms several components with the goal of removing direct router dependencies. The general approach is to read directly from our new 'stores', instead of the router data. Adds `queryParamsStore` to hold url query params. It also cleans up a couple pieces of data that were unused.
> [risk=no] refactor away router dependencies

- ui/src/app/cohort-review/detail-all-events/detail-all-events.component.spec.ts
- ui/src/app/cohort-review/detail-page/detail-page.spec.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.ts
- ui/src/test.ts
There were some test failures due to missing state stubs, but they were not showing up consistently because data from previous tests was sticking around.
This adds the needed stubs, and also resets the stores between each test so these cases should show up consistently in the future.
> [risk=no] reset state between tests

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
This PR makes a few changes to populate the custom GSuite schema fields required for Moodle SAML integration.
While I was in this code, I also changed the way we store a user's contact email address in GSuite. This will now show up in two places:
1) The "Contact_email_address" custom schema field.
2) A secondary email address with type "home".
Plus some small additions to the integration test to verify these things work.
RELEASE COORDINATION: the custom schema has already been added to our dev GSuite, but not prod. I will make those changes before this PR gets merged, after which point this PR will be safe to run in all environments.
> [RW-2034][risk=no] Auto-populate Institution and contact email address for new users

- api/docker-compose.yaml
This makes it so that Elastic is not accessible e.g. via an internal corporate DNS for your workstation.
> [risk=no] Don't expose Elastic outside localhost

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/views/account-creation/component.spec.tsx
- ui/src/app/views/account-creation/component.tsx
1) Update UI to show error message if username is less than 3 characters
2) Update profile api
3) Update tooltip
> [RW-2004][RISK=LOW] Require higher minimum length for workbench usernames

- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
Context: I tried running a CLI as my pmi-ops.org account (to disable a user). I confusingly received a 404 error message from the API. Authentication issues should return a 401.
> [risk=no] Return 401 rather than 404 for invalid user identities

- api/src/main/resources/application.properties
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-1478
Spring enables `health` and `info` endpoints by default (as well as many other JMX endpoints). Turn all of them off so we can enable them purposefully when needed.
> [RW-1478][risk=no] Turn off all magic spring endpoints

- api/src/main/resources/workbench.yaml
Cron job xml had the following entry
<cron>
<url>/v1/cron/bulkSyncTrainingStatus</url>
<target>api</target>
<description>Periodic Sync users training status</description>
<schedule>every 24 hours</schedule>
</cron>
> [RISK=LOW]Correcting path for failing bulk sync training status cron job

- ui/app.yaml
homepage video links were never working in test + downstream envs, but always worked in local; I think this is why? Would love someone more familiar with app engine to verify that's what I'm doing in the yaml
> [P3][RW-2179] include mp4s as static file types to upload to app engine

- api/db-cdr/generate-cdr/cloudsql-import.sh
1. This pr fixes the cloudsql import which fails when the replication / backup job runs between the csv import jobs.
> [DB-164] [risk=no] fixing cloudsql import

- ui/src/app/views/signed-in/component.html
Per guidance from Roxana, the AoU support email will actually be "support@researchallofus.org". This isn't (yet) attached to the Zendesk application, but it will go live once Zendesk is security approved.
> [risk=no] Update the AoU support email address

- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.spec.tsx
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.tsx
This fixes two issues with the participant charts:
* Charts no longer display stale data when switching between participants via the navigation buttons.
* Charts render more quickly when switching tabs.
Note that the root cause of the staleness issue was the data being placed in instance variables in the component. This should be avoided in most cases, since it creates 'pseudo-state' that persists on the component. In this case, that data was leaking across re-renders, causing subsequent chart pages to show incorrect information.
The fix is to compute the chart series directly in the render path, without storing it anywhere. This is the preferred approach for all kinds of derived data needed for rendering.
> [risk=no] fix participant chart

- ui/src/app/resolvers/concept-set.ts
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/test.ts
This extracts the concept set into a store, in order to remove dependence on the router. This is the same pattern used for the other resolver data.
> [risk=no] extract concept set state into store

- ui/src/app/views/conceptset-create-modal/component.tsx
- ui/src/app/views/resource-card/component.tsx
This fixes a bug that if you don't select a domain when creating a concept set and choose the default instead, the default is set in correctly and is a bogus value that covers the whole card.  Default is now `CONDITION`.  
Also fixes a bug which did not truncate resource card descriptions; descriptions are now truncated at 4 lines like in image below.
> [P0][RW-2220][risk=no] fix concept set create modal

- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/tools/src/main/resources/bigquery/es_person.sql
Splitting this PR out for discussion primarily. This is a design change (also made a comment in the design doc: https://docs.google.com/document/d/1N_TDTOi-moTH6wrXn1Ix4dwUlw4j8GT9OsL9yXYXYmY/edit?hl=en#heading=h.jduorqros7hm)
This changes from a per-domain event approach to a single schema and nested field for all events. This maintains the top level per-domain ID fields to allow for "TOP N conditions" type aggregations.
Pros:
- Single template for all search group queries, don't need to worry about mixed domain types in a criteria tree (as much)
Cons:
- May be less useful for aggregation later in unforeseen use cases.
> [RW-1948][risk=no] Switch to events, fix visits, minor schema code cleanup

- ui/src/index.html
While checking in on the Zendesk dialog again, I noticed that the dialog title wasn't getting set properly.
Turns out the web widget config needs to be used a bit differently... this makes the fix.
Contact us --> Help Desk
Before:
After:
> [RW-1885] [risk=no] Small tweak: change Zendesk config to properly set the form title.

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
Fixes a long-standing bug where we return a 500 errors on malformed requests. Looking at a security ticket complaining about these 500s finally forced the issue.
> [RW-1302][RW-319][risk=no] Return a 400 on bad requests

- api/db/changelog/db.changelog-59-cluster-config-default.xml
- api/db/changelog/db.changelog-59-cluster-config-override.xml
- api/db/changelog/db.changelog-master.xml
- api/src/integration/java/org/pmiops/workbench/NotebooksIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-2209
Will add a CLI for this in a follow-up. For now, tested manually via oauth2l+curl.
Design notes:
- Repurposes the `MANAGE_GROUP` authority as a more general `DEVELOPER` authority, used to guard this admin endpoint; this subsumes all other authorities if granted.
- The cluster override config is implemented as a JSON blob in a SQL column for easy future extension. This felt natural given we're merging this into the cluster creation request. This is the same approach we use for the server config, but is a novel pattern as a column on an existing model.
- I chose to reencode the JSON in the DB model (rather than use the Swagger version) because best practice is to keep client and storage representations independent.
- For now …
> [RW-2209][risk=low] Implement per-user cluster overrides

- api/build.gradle
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/resources/mockito-extensions/README.md
- api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
While working on some unit tests for RW-2236 I found myself stuck in a corner where I couldn't make progress without being able to mock a method on GoogleCredential. The problem was that all of GoogleCredential's core methods were marked as final.
Based on my reading of https://www.baeldung.com/mockito-final and https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2, Mockito 2 added some tricks to support this in a reasonably easy-to-use way.
I'm not by any means an expert here, so I don't know if this would have unintended consequences. But it worked like a charm for my use case, and doesn't seem to break any other tests.
I'm not attached to this at all. If there are strong objections, I'm happy to revert! The only impact is, I won't be able to test the impersonated-credential …
> [risk=no] Upgrade Mockito and add the mock-maker-inline extension

- README.md
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
Number may be floats and should be indexed as such.
> [risk=no] Fix docs and value_as_number index type

- ui/src/app/views/homepage/component.tsx
> [risk=no] Only show dashboard footer link scrollbars on overflow

- api/config/config_local.json
- api/demos/physical-measurements.json
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/notebook-redirect/component.html
Implement counts for all types except(Deceased and BP). We now produce counts for all trees:
1) Surveys - All Surveys, Questions and Answers
2) PM - All types except **Blood Pressure**
3) Condition(ICD9/10, Snomed) - All types
4) Procedure(ICD9/10, CPT, Snomed) - All types
5) Demographics - All age, gender, race and ethnicity except **Deceased**
6) Drugs - All types
7) Measurements - All types
8) Visits - All types
> [RW-2263][risk=no] Implement counts for all types except(Deceased and BP)

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
Mirrors what I did in data-browser to fix a security issue where we leaked a SQL exception with details (could be used by an attacker to gain additional information and find an exploit potentially).
https://github.com/all-of-us/data-browser/pull/136
> [risk=no] Don't leak internal exception details to end users

- api/db/changelog/db.changelog-61-backfill-beta-bypass.xml
- api/db/changelog/db.changelog-master.xml
- ui/src/app/guards/registration-guard.service.ts
- ui/src/app/views/homepage/component.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
Digging into what was causing QA failures for the upcoming weekly release, I found two largely-separate issues:
1) The frontend access guard involved two pieces of complex logic based on a combination of config.enforceRegistered and environment.enableComplianceLockout. There was a subtle error in homepage/component.tsx that was causing access tasks not to be shown to new and non-beta-approved users.
I realized that the logic would be simpler to reason about & test if we removed the front-end "enableComplianceLockout" flag altogether. With this change, all front-end access decisions are made purely based on whether the user's data access level is registered or not (and whether config.enforceRegistered is true).
2) There was an issue where our bypass backfill script was updating the …
> [RW-2240] [risk=moderate] Simplify frontend access guard and add backfill for betaAccessBypass

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
Build QueryJobConfiguration for BQ for participant ids.
This method will produce a sql template that varies depending on the cohort definition. The base sql template is as follows:
`select person_id
from `${projectId}.${dataSetId}.search_person` search_person
where search_person.person_id in (
select criteria.person_id from (
select person_id, entry_date, concept_id
from `${projectId}.${dataSetId}.search_all_domains`
where concept_id in(@p0)
) criteria
)`
To use with the DataSetBuilderController please drop the following code block into your specific method. Make sure to inject BigQueryService and ParticipantCounter into your controller. Need to make sure that proper access is required and that the cdr version is set as well. Ex: …
> [RW-2357][risk=no] build QueryJobConfiguration for BQ for participant ids.

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/app/components/resources.tsx
- ui/src/app/views/resource-card/component.tsx
Add 'Rename' option to the snowman menu for cohort cards for editing name and description (the 'Edit' option now edits the actual criteria of the cohort).
@blrubenstein I've been tagging you on a lot of reviews lately since there have been changes to workbench components included. Let me know if should rotate others in on reviews like this.
> [RW-2293][risk=no] Add rename option to cohort cards

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticUtils.java
- api/tools/src/main/resources/bigquery/es_person.sql
- Confirmed this new setting catches the regression we saw here.
- Reindexed and pointed to new indices (decided to restart the versioning suffix here at "1")
> [RW-2414][risk=no] Fix field name mismatch in age_at_start

- ui/src/app/views/signed-in/component.css
Got an update from Lou to remove the box-shadow from the environment label (displayTag)
> [RW-2111][risk=no]: Remove box shadow from environment label (displayTag)

- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticUtils.java
- api/tools/src/main/java/org/pmiops/workbench/tools/elastic/CloudStorageShardedLineIterator.java
More scalable and reliable indexer implementation. Cuts indexing time down to ~2h from ~6.5h.
- Send concurrent indexing requests via a threadpool.
- Greatly increase buffering on reading from GCS (this was the primary bottleneck, actually)
- Add timing logs
- Add bulk insertion retries
- bugfix: Fix reading from BigQuery
> [RW-2361][risk=low] Optimize indexer and improve logging

- ui/src/app/cohort-search/overview/overview.component.html
- ui/src/app/cohort-search/overview/overview.component.ts
Fixes error when after saving a new cohort, it stays on the save modal instead of redirecting to the cohort actions page
> [RW-2419][risk=no] Fix redirect after saving new cohort

- api/db/changelog/db.changelog-67-compliance-training-expiration.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- ui/src/testing/stubs/profile-service-stub.ts
This PR fixes an issue with the eRA Commons logic where we were too aggressive in returning error statuses from the UserService method.
Specifically: when we have a Moodle ID for a user, but that user hasn't completed any trainings, we seem to get an empty response from the Moodle API. (See examples in the RW-2392 description.) Instead of returning an error in that case, we should clear out the compliance training completion bit.
I also took the chance to finish up the rename of training --> complianceTraining.
> [RW-2392] [risk=low] Fix eRA Commons logic, and finish module rename.

- README.md
Java is needed to build locally but was not listed in the build dependency list. @blrubenstein suggested adding this and `yarn` to a "local development" section of the build dependency list.
> [risk=no] Adds Java as build dependency. Moves yarn and Java build deps to local development section.

- README.md
- api/build.gradle
- api/db/load_vars.sh
- api/db/vars.env
- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/libproject/generate_appengine_web_xml.rb
- api/libproject/generate_appengine_web_xml.sh
There was a bug with the first revision where the generate xml step would always use the vars from db/vars.env.
We now use the vars in the environment and added steps on how to load the db/vars.env to your local setup to the README
> API Server start speed up - take 2

- api/db/load_vars.sh
- api/libproject/devstart.rb
- api/libproject/generate_appengine_web_xml.rb
`./project-rb dev-up` is not currently working because docker does not interpolate environment variables when loading env files. The generate rb scrip makes up for this by adding another step to interpolate the DB_HOST variable.
> [risk=no] Fix dev-up

- ui/src/app/views/workspace-edit/component.tsx
Use the `props` Workspace Name instead of the `state` Workspace Name in the header text, making it equal to the _fixed_ original name instead of the _editable_ cloned name.
Also fix a typo
> [RW-2489][risk=no] Use original Workspace Name on Clone/Duplicate Workspace page

- api/db-cdr/changelog-schema/db.changelog-27.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/StandardProjection.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
3 cases:
1) if search term only matches source code then return list of source codes like search term
2) if search term matches both source/standard codes then return list of standard codes like search term
3) if search term does not match on code, then return list of standard synonyms like search term
> [RW-2556][risk=no] return source or standard matches for list search

- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
Fixes the following exception on create - 
- Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'statusEnum' in 'field list'
Fixes the following exception on getCurrentBufferSize() - 
- org.hibernate.hql.internal.ast.QuerySyntaxException: billing_project_buffer_entry is not mapped
One important question that we should look into... why did our tests not catch this? The tests go through both of these operations using a real Dao but they pass without these changes. These failures only come up when running it manually through the application.
> [RW-2467][risk=no] Fix JPA issues with BillingProjectBufferEntry

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
While digging into the past weekend's Terra incident (see RW-2578 for details) I found it was very hard to tell exactly how many times the workbench was making changes to the all-of-us-registered-prod group.
This PR adds some add'l logging which will help us more confidently assess how many changes are happening.
> [RW-2578] [risk=no] Additional logging for data access level changes and sync jobs.

- ui/src/app/views/workspace-share/component.tsx
- ui/src/app/views/workspace-wrapper/component.ts
- ui/src/app/views/workspace/component.ts
There already was a to-do at workspace component close to remove the reload, once workspace component is moved from angular - react.
The reload was done to refresh the userRole parameter inside Workspace object. This is solved by using the reloadWorkspace method inside workspace-share before emitting the closing event.
> [RW:2514][RISK:LOW] When sharing a workspace - clicking the cancel button causes the entire page to refresh

- deploy/libproject/deploy.rb
Note: I've removed these services in all environments, deploys may fail by default in the meantime. This can be worked around by explicitly specifying `--app-version TAG --git-version TAG` to the deploy command.
> [risk=no][RW-1974] Drop data browser services references from deploy scripts

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
Shared Workspaces cannot use "Save As" since the modal encodes the URI which turns our current delimiter `:` into characters that Jupyter doesn't decode correctly when it goes back to their API.
The solution is to change it into characters that do not get encoded. We chose `__`.
> [RW-2260][risk=no] Fix "Save As" URI encoding on shared workspaces

- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/review-utils/primeReactCss.utils.ts
- ui/src/app/cohort-review/table-page/table-page.tsx
- ui/src/app/views/dataset-page/component.spec.tsx
- ui/src/app/views/dataset-page/component.tsx
- ui/src/testing/stubs/concepts-api-stub.ts
Restrict names in the participant detail table in review to 2 lines. If the text overflows, show a 'Show more' link that displays an overlay with the full text when clicked.
> [RW-2373][risk=no] Add 'Show more' link for long names in review

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/test/java/org/pmiops/workbench/CallsRealMethodsWithDelay.java
- api/src/test/java/org/pmiops/workbench/TestLock.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
I ended up going with a MySQL lock after trying out transactions and table locks. I ruled out transactions since I believe they lock on a row by row basis and I needed something that locked on the table level. I chose a generic lock over table locks since I just needed the consume code to run in sequence. The consume code doesn't have to block other updates to the table.
Had to do some funky stuff to be able to test concurrency. I'm not super happy with what came out of it since there is manual clean up that needs to be done to prevent side effects and the underlying locking implementation had to be stubbed out but it works.
> [RW-2622][risk=no] Add consume project to Billing Project Buffer API

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
While testing the cron jobs locally, I noticed that a couple of the sync processes were continually updating the "completionTime" for the given access module every time the sync ran. This stabilizes the completion times so they don't get updated for all users on every run.
> [RW-2392] [risk=no] Improve stability of access module completion timestamps

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
This fixes the one remaining "fixable" issue with the failing cron jobs in our test environment.
Most of the rest of our failures are due to user rows for nonexistent GSuite accounts, which isn't worth the effort to clean up for now.
On prod, our jobs are currently succeeding except for the eRA Commons. That one is still pending enablement of credential impersonation on prod, https://precisionmedicineinitiative.atlassian.net/browse/PD-3409
> [RW-2392] [risk=no] Avoid syncing access modules for service accounts

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
Doing a 2FA sync on every call to GET /me added a significant amount of lag to the endpoint based on local testing. This PR removes the 2FA sync. It should be a safe change since we make an explicit call to sync 2FA whenever the user hits the homepage.
Local Testing Results of 50 GET /me calls
average w/ sync - .96312 s
average w/o sync - .163540 s
> [RW-1665][risk=no] Speed up GET /me

- api/db/changelog/db.changelog-79-drop-fc-index.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- Add regression test
- Drop index
- Push active status filtering down to the DAO level (this is necessary for DAO methods that return single elements)
> [RW-2677][risk=low] Avoid uniqueness conflicts with deleted workspaces

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/cohort-review/page-layout/page-layout.spec.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.ts
- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.spec.ts
- ui/src/app/cohort-search/list-modal/list-modal.component.spec.ts
- ui/src/app/cohort-search/list-modifier-page/list-modifier-page.component.spec.ts
- ui/src/app/cohort-search/list-node/list-node.component.spec.ts
- ui/src/app/cohort-search/list-search-bar/list-search-bar.component.spec.ts
- ui/src/app/components/card.tsx
- ui/src/app/views/concept-add-modal.tsx
- ui/src/app/views/concept-homepage.spec.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/concept-set-actions.tsx
- ui/src/app/views/workspace-nav-bar.spec.tsx
- ui/src/app/views/workspace-nav-bar.tsx
- ui/src/app/views/workspace-wrapper/component.spec.ts
- ui/src/app/views/workspace/component.spec.ts
Moves all `registerApiClient` calls in `beforeEach(async())` to `beforeEach()` to match the rest of the app. Seems likely this has something to do with the flakes since it was mostly calls to register `CohortBuilderApi` that were moved.
> [risk=no] Another attempt at fixing flaky test

- ui/src/app/views/dataset-page.tsx
Tooltip will appear only when textOverflow property is applied
> [RW-2647][RISK=NO]Column names on Data Set Builder don't fit

- .github/PULL_REQUEST_TEMPLATE.md
I think this will make it easier to open up the CONTRIBUTING.md doc. 
As currently written, it tries to open a PR:
>Please remember to keep in mind the security levels outlined in [CONTRIBUTING.md](CONTRIBUTING.md) and to 
With the change, it will contain the link that can be used to access the file.
> [risk=no] Update link to CONTRIBUTING.md

- ui/src/app/views/signed-in/component.html
> [RW-2758][risk=no] rm settings button, settings view was removed

- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
Updates to the workspace create/edit page with new research purpose fields created a regression in the workspace About page causing nothing to show up underneath the "Research Purpose" header.  This PR fixes it so that it displays the same information that it used to (the "description" field was renamed "intendedStudy" and reallocated to that rp question).  The `ResearchPurposeItems` object also changed into a list with new fields. 
Although this page will change with the release of the new About page with dataset builder, this fixes things until Bedford.
> [risk=no] fix research purpose regression on ws about page

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- ui/src/app/views/workspace/component.ts
- Upon sharing, this enables writers/owners to launch clusters in that project.
- This will not actually be utilized yet within the application.
- Recode the reset cluster button, as this would have created conflicting clusters in the wrong project before we launched `useProjectBillingBuffer`
Will backfill these roles as a follow-up.
FYI @jmthibault79
> [RW-2657][risk=moderate] Grant canCompute to workspace editors/owners

- api/build.gradle
- api/libproject/devstart.rb
- api/src/main/resources/fireCloud.yaml
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillCanCompute.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-2657
Acting as the GAE default SA for the given environment:
```
for each owned workspace:
ensure writers and owners have canCompute
``` 
- Required pulling in the getWorkspaceACL Firecloud swagger
- Includes a billing project filter to avoid touching local/old workspaces
- There are surprisingly many workspaces for which the GAE SA has "NO ACCESS", this warrants some follow-up investigation.
> [RW-2657][risk=moderate] Implement canCompute backfill script

- ui/src/app/views/workspace-edit.tsx
fixed two null pointer errors on workspace edit page:
* running "includes" on null object when checking if the "other population" was selected
* checking if we have any specific populations selected when verifying all fields filled for the save button.  (this one happened when we had "no" selected in the initial ws then tried to edit it to say "yes"; see below comment)
note that these happened on duplicate and edit because we are fetching a ws object that has already been created, and when these fields are left empty on initial create they are returned as null.
> [RW-2817][P1] fix null pointer bugs on ws edit 

- ui/src/app/views/workspace-edit.tsx
This will remove this warning from the ui unit tests and from the UI page of workspace-edit (in the console) for users.
```
ERROR in src/app/views/export-data-set-modal.tsx(15,46): error TS2305: Module '"/Users/ajang/Firecloud/workbench/ui/src/generated/fetch/index"' has no exported member 'KernelTypeEnum'.
src/app/views/export-data-set-modal.tsx(93,18): error TS2339: Property 'generateCode' does not exist on type 'DataSetApi'.
src/app/views/export-data-set-modal.tsx(101,18): error TS2339: Property 'generateCode' does not exist on type 'DataSetApi'.
src/app/views/export-data-set-modal.tsx(127,9): error TS2345: Argument of type '{ dataSetRequest: { name: string; includesAllParticipants: boolean; description: string; conceptSetIds: number[]; cohortIds: number[]; values: DomainValuePair[]; …
```
> [RW-2726][risk=no] Fix unique key warning in workspace-edit

- ui/src/app/utils/navigation.tsx
- ui/src/app/views/breadcrumb.tsx
- ui/src/app/views/resource-card.tsx
With this change, cards (like notebooks, data sets, cohorts) and breadcrumbs are now anchor links.  This enables user behavior like right-click, middle-click, shift-click, and command-click.
> [RW-2736][risk=no]Convert cards and breadcrumbs to anchor links

- ui/src/app/views/resource-card.tsx
Now shows ?jupyterLabMode=false
> [risk=no] Fix ?jupyterLabMode=undefined in notebooks redirect URLs

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Slightly more automated parsing + gets rid of the unchecked Java warning.
Copied from my now deleted backfill script: https://github.com/all-of-us/workbench/pull/2221/files#diff-3e77476e30c3fda73b42c53d56c9f977R96
> [risk=no] Refactor WorkspaceACL handling to avoid Java warning

- ui/src/app/utils/resourceActionsReact.ts
- ui/src/app/views/resource-card.spec.tsx
- ui/src/app/views/resource-card.tsx
RecentResource uses a `string`; this was being coerced as a string number on the workspace page, while recent-work was broken.
> [RW-2899][risk=no] Fix resource card lastModified time handling

- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
When cluster is already running, don't show the "may take 10 minutes" language. Some minor cleanup so that we only set `progressComplete` on one of Unknown, Initializing, Resuming.
> [RW-1605][risk=no] Fix cluster load messaging on notebooks redirect

- ui/src/app/views/export-data-set-modal.tsx
- ui/src/app/views/new-dataset-modal.tsx
Export data set via snowman : opens the notebook in a new tab and returns back to Data tab
Update/save data set: opens notebook in a new tab and then closes the save modal and return back to data tab
> [RW-2847][risk=no]Open Notebook from Data set in a "new tab" by default

- api/src/main/resources/workbench.yaml
- ui/src/app/components/buttons.tsx
- ui/src/app/components/icons.tsx
- ui/src/app/components/popups.tsx
- ui/src/app/views/workspace-list.spec.tsx
- ui/src/app/views/workspace-list.tsx
- ui/src/app/views/workspace-share.tsx
See the bug description with some add'l info on the breakage.
With this PR, users will see a brief spinner on the workspace card itself while we're loading the user roles:
I tried to add a minimal unit test that checks that we're correctly loading data and populating the workspace-share props. And some add'l docs on the API to clarify that you need to include the full desired ACL, not just newly-shared users.
> [RW-2983] [risk=no] Load user roles before opening the workspace share modal.

- deploy/libproject/jirarelease.rb
Already generated API token per https://confluence.atlassian.com/cloud/api-tokens-938839638.html and pushed to all `jira-login.json` files. After the next release, will update these JSON files to omit the password.
> [RW-2998][risk=low] Use an API token rather than a password for Jira auth

- api/build.gradle
I ran this locally and it seems to work fine:
```
./gradlew dependencyCheckAnalyze
...
> Task :dependencyCheckAnalyze
Generating report for project api
Found 216 vulnerabilities in project api
...
BUILD SUCCESSFUL in 6m 59s
1 actionable task: 1 executed
```
There's no evidence to suggest this will directly fix the connection flakiness we observed... but at least we won't be on a 1+-year old version of the plugin.
> [RW-2994] [risk=no] Update our version of the dependency-check plugin.

- api/src/main/resources/fireCloud.yaml
I don't know how this happened - the source api-docs.yaml is correct (and has been for at least 3y), but it cost me ~1h of debugging to find. Also some weirdness around `workbenchRole` vs `role`; I don't know whether that was originally an issue in the docs or that was a problem of our own design - this endpoint never worked and the only place we call this, we're suppressing exceptions.
> [risk=no] Fix firecloud.yaml bugs on removeUserFromBillingProject

- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
The per user free tier project goes away with 1ppw, and this was only really relevant in local/test, so should be fine to remove the guard entirely.
> [RW-3042][risk=no] Don't block "create workspace" on free tier billing project

- ui/src/app/views/dataset-page.spec.tsx
- ui/src/app/views/dataset-page.tsx
If we select a survey in  data set it results in error while getting value for surveys. 
If we do end up showing the value , the big query will have to change to include ds_survey rather than observation. For bedford release i do not think its best to change the big query so close to release rather filter out survey in concept set for data set page.
> [RW-3058][RISK=NO] Selecting Survey Concept set on dataset page results in exception while retrieving value

- ui/src/app/components/spinners.tsx
While working on https://github.com/all-of-us/workbench/pull/2345, I found myself wishing I were able to make the spinner overlay semi-opaque to make it clearer to the user which part of the screen was currently "loading", by graying it out a little bit.
This PR adds a simple prop to our core Spinner component, which should allow that to happen. By default opacity is zero, which should make this change a no-op for all existing usage.
> [No ticket] [risk=no] Adds an 'opacity' prop to the spinner component

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
My original manual testing notebook did not include non-trivial multiline code blocks - oops.
> [RW-3084][risk=no] Allow pre tags in notebook HTML

- api/config/config_local.json
- api/config/config_test.json
This PR flips the test config to begin enforcing the registered state. We think this will help us catch regressions, and perform more realistic performance testing, in our push-on-green test environment.
There should be two main impacts:
(1) The UI should now force-redirect new users to the "registration tasks" page in test. Use the self-bypass button to allow yourself entry.
(2) New workspaces should be created with an authorization domain (https://github.com/all-of-us/workbench/blob/master/api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java#L133).
> [RW-2501] [risk=no] Turn on enforceRegistered in test.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticSearchService.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtilTest.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
This PR addresses updating the ElasticFilters to use the CriteriaLookupUtil. 
CriteriaLookupUtil was created to consolidate criteria lookup logic between BQ and Elastic.
> [RW-2875][risk=no] refactor ElasticFilters to use CriteriaLookupUtil

- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- api/tools/src/main/resources/bigquery/es_person.sql
Add value_source_concept_id to elastic index for ppi data from the observation OMOP table. When CB searches for any categorical data for surveys data(PPI) we now need to match against value_source_concept_id instead of value_as_concept_id.
> [RW-2872][risk=no] Add value_source_concept_id to elastic index for ppi data

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/interactive-notebook.tsx
- ui/src/app/views/notebook-in-use-modal.tsx
This does not tackle the jupyter extension around locking. That I am going to do in a separate PR. Also fixes a key mismatch in the API with the gcs metadata.
> [RW-2708][Risk=no] Srubenst/notebook locking ux

- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
Verified via local manual testing. 
Specifically this avoids copying lock metadata when cloning a notebook. We currently have no other need to copy GCS metadata on any blob copy, so just turn it off everywhere.
> [RW-3115][risk=no] Don't copy blob metadata

- ui/app.yaml
I'm unclear from the documentation whether this content security policy will fail, so enable in report-only mode for now.
> [RW-1960][RW-1961][RW-1962][risk=low] Add security headers, CSP in report only mode for now

- ui/app.yaml
Will come up with a more lenient policy and fix forward. Right now it's generating 100s of console errors per page
> [RW-1960][risk=no] Revert spammy content security policy reporting

- ui/src/app/pages/app/component.ts
- ui/src/index.html
Move GA initialization into `index.html`, rather than constructing a Javascript script string piecemeal at runtime.
This allows us to define a tighter Content Security Policy (RW-1960), i.e. disallowing unsafe-inline scripts. Tested via manual deploy to GAE.
> [RW-1960][risk=low] Refactor sketchy Google Analytics initialization

- ui/src/app/pages/analysis/notebook-redirect/component.ts
Resolves a notebook localization issue, possibly from #2327 
1. Create a notebook and save it
2. Return to notebooks list page
3. Open the notebook -> directs user to readonly preview
4. Edit the notebook being previewed.
Problem behavior:
* was attempting to localize the notebook without the `.ipynb` suffix
* call to API /localize resulted in 404
* UI displayed "503 server busy" with infinite spinner
A more thorough fix would be to audit our use of "full" network name (with suffix) vs. "display" name (without) vs. simply "notebook name" in the UI.
But this quick fix should immediately unblock dev work.
> [risk=no][ticket=no]Use fullNotebookName to localize

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
This turns on the VPC flow logging functionality in all of our environments.
This has been enabled in test for ~1-2 weeks. I've confirmed that flow logs are enabled in newly-created workspaces in test, and we haven't encountered any issues or problems with users accessing notebooks as a result.
> [RW-2060] [risk=no] Enable VPC flow logs in higher envs.

- ui/app.yaml
- ui/src/index.html
CSP primer: https://developers.google.com/web/fundamentals/security/csp/
Spec: https://content-security-policy.com
tl;dr: this protects against XSS and injection of unexpected content on our site
- Enables a content security policy in report-only mode; this will log violations to a UI endpoint - we won't log the JSON report content, but we can track instances of violations via GAE logs
- Policy generated via the [CSP tester extension](https://chrome.google.com/webstore/detail/csp-tester/ehmipebdmhlmikaopdfoinmcjhhfadlf).
- A single policy is used for both dev and prod. This seems simplest to keep configuration understandable - there is not much risk in allowing connections across environment backends.
- This policy whitelists our exact inline script contents in `index.html`, this will …
> [RW-1960][risk=no] Add a content security policy in report-only mode

- ui/app.yaml
Apologies, I guess I failed to manual test the `report-uri` which was a late addition. Verified this fixes the issue by a manual demo server deploy: https://calbach-dot-all-of-us-workbench-test.appspot.com
> [RW-1960][risk=no] Fix CSP syntax

- api/config/config_test.json
to allow Gatling perf tests to run in test. https://all-of-us-workbench-test.appspot.com/
> Increase billingProjectBufferCapacity size to 100 in test env

- api/db-cdr/generate-cdr/copy-bq-dataset.sh
For lack of a better place to put this, I'm proposing tracking this "BigQuery dataset copy" script within the generate-cdr folder.
I used this script when wrapping up https://precisionmedicineinitiative.atlassian.net/browse/RW-3112 for copying a synthetic CDR from pmi-ops.org project into a test.firecloud.org project.
If there's a feeling that this is either risky or clutters up the generate-cdr folder, I'm happy to punt on merging this in.
> [RW-3112] [risk=low] Add a one-off script to copy a synthetic CDR from one loc to another

- .gitignore
- ui/tsconfig.json
When editing/viewing the UI code in Visual Studio Code, I noticed that paths weren't resolving correctly. It looks like this is because we're using webpack implied roots (like `app`). Adding paths for `app` and `generated` to `.tsconfig` fixed that.
Additionally, I want to ignore the `.vscode` directory this editor creates.
An open question is whether this can go in a shared `.editorconfig`.
> fixes for VS Code editor

- .gitignore
- ui/tsconfig.json
This reverts commit 2ba9f8406e59022d0cc1108827d3cab6d5d31a20.
We had some (all) yarn test failures due to components under `app` not being found.
> Revert "fixes for VS Code editor (#2442)"

- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillBillingProjectUsers.java
Very few workspaces are actually shared so this skips most of the work. The script was a no-op for creators.
> [RW-3188][risk=no] Minor backfill optimization - skip creators

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
moving synth cloud cdr version from synth_r_2019q3_1 -> synth_r_2019q3_2 in test/staging/stable
> [RW-3217][risk=no] moving synth cloud cdr version.

- api/config/cdr_versions_prod.json
incrementing cloud cdr versions below:
{
"cdrVersionId": 2,
"name": "All of Us Dataset v1",
"dataAccessLevel": 1,
"bigqueryProject": "aou-res-curation-output-prod",
"bigqueryDataset": "R2018Q4R1",
"creationTime": "2018-11-13 15:09:27Z",
"releaseNumber": 1,
"numParticipants": 116157,
"cdrDbName": "r_2019q1_4"
},
{
"cdrVersionId": 3,
"isDefault": true,
"name": "All of Us Dataset v2",
"dataAccessLevel": 1,
"bigqueryProject": "aou-res-curation-output-prod",
"bigqueryDataset": "R2019Q2R1",
"creationTime": "2019-06-25 00:00:00Z",
"releaseNumber": 2,
"numParticipants": 191037,
"cdrDbName": "r_2019q2_2"
}
> [RW-3219][risk=no] moving cloud cdr version.

- ui/app.yaml
Seeing this URL reported in prod, though it seems only in certain scenarios does it make XHRs
> [RW-1960][risk=low] Include Google Analytics in content-security-policy

- ui/tsconfig.json
When loading UI as a project in IntelliJ, the compiler threw a bunch of warnings that suggested something was wonky in the Angular configuration (i.e. `Cannot find module` for all modules, `--jsx is not set`). This change fixed all of the warnings.
> [No ticket] [risk=no] Set default jsx compiler option in tsconfig

- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
One can now copy notebooks and concept sets from a read-only workspace to another workspace without cloning the entire read-only workspace.
> [RW-3229] [risk=low] Enable copy notebook / concept set from readonly workspace

- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
`window.open()` and `window.history.back()` calls previously created a race condition.
> [RW-3029][risk=no] Actually open exported dataset notebooks in a new tab

- api/db-cdr/generate-cdr/copy-bq-dataset.sh
- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/project.rb
- api/src/dev/server/Dockerfile
Example invocation:
```
./project.rb publish-cdr --project all-of-us-rw-staging --bq-dataset synthetic_cdr20180606
```
This...
- Creates the dataset (if it doesn't exist)
- Copies all tables from the source dataset
- Adds the registered tier google group as a READER
Notes:
- gcloud upgrade needed due to `bq` error in docker: `SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)`
- JOB_PROJECT should be explicitly specified on copy, I'm not sure where it got this from without specification (possibly the gcloud default project)
- Switched script to `-ex` to fail on error and log all commands directly, rather then echo'ing
- There's some duplication with the base level ./project.rb. I can't import that without bringing in all the global commands, and the …
> [RW-3165][risk=low] Add ./project.rb command for publishing a CDR

- api/config/config_perf.json
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortReviewDao.java
- api/src/main/resources/cb_review_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.tsx
- ui/src/app/cohort-review/participants-charts/participants-charts.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
- ui/src/app/cohort-search/overview/overview.component.tsx
1. Removing cohortId/cdrVersionId and replacing with cohortReviewId in most review api calls.
2. Fix corresponding test cases.
> [RW-3297][risk=no] Removing cohortId/cdrVersionId and replacing with cohortReviewId

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
Rated this as moderate risk since it defines a new connection to the recently created firecloud.org prod CDR dataset (note: this is likely to be applied tomorrow, ahead of the next actual code release).
- I decided to proliferate the number of CDR versions in staging/stable, rather than upgrade in place, to minimize disruption to existing workspaces.
- Production now defaults to the new firecloud.org CDR project
> [RW-3206][risk=moderate] Update CDR project locations

- ui/package.json
- ui/yarn.lock
PR-ing myself because it could not be done automatically.
Here's the security alert: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/set-value/open
> [risk=no, ticket=no] Bump set-value to 2.0.1 per dependabot recommendation

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
This fixes an issue we encountered when trying to turn on VPC-SC BigQuery enforcement in test. By default, the BigQuery client library executes queries in the context of the current default project (in our case, the App Engine project, e.g. all-of-us-workbench-test).
With VPC-SC BigQuery enforcement enabled, a query that's executed in the context of a project outside of the perimeter is considered "cross-perimeter", even if the query itself only accesses resources within the perimeter and the acting service account is whitelisted for access.
This PR should allow us to turn on BigQuery enforcement in the test environment. We may want to prepare a cherry-pick onto the current release in order to gain business & security approval to push it out next week. This will be required to enable …
> [RW-3354] [risk=low] Scope all BigQuery service instances to the current CDR project

- api/cluster-resources/README.md
- api/cluster-resources/aou-snippets-menu.js.template
The session data I was depending on was null for large notebooks, i.e. while Jupyter UI was still initializing. Fallback to listening for notebook load.
> [RW-3304][risk=low] Add fallback snippets behavior for large notebooks

- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
- api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java
Concept set constructor being called at the start of method 'cloneConceptSetAndConceptIds' was already taking care of concepts for new concept set, hence the extra call to bulkcopy was causing sql constraint exceptions
> [RW-3375]Workspaces with concept sets cannot be duplicated

- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
This sub-organization will have 2FA enforcement disabled, allowing us to self-manage 2FA enforcement at the application layer.
@gjuggler FYI
> [RW-3333][risk=low] Add org unit for new researcher accounts

- ui/app.yaml
- ui/src/index.html
Incapsula apparently injects a script onto the pages it returns. We can't precompute a hash of this script, so our only option for now is to allow unsafe-inline, if we don't want to break whatever Incapsula is doing.
> [RW-1960][risk=no] Relax the content security policy to allow for Incapsula script shenanigans

- ui/package.json
- ui/yarn.lock
See vulnerability here: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/webpack-dev-server/open
> Update to webpack-dev-server 3.1.11 to fix vulnerability

- ui/app.yaml
We haven't gotten any reports on this policy, and this is the original cause of the security ticket. Wrapping up this ticket here and filing another story to finish the primary policy.
> [RW-1960][risk=no] Enforce CSP on non-index.html resources

- api/config/featured_workspaces_test.json
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/pages/workspace/workspace-library.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
- ui/src/environments/test-env-base.ts
- ui/src/testing/stubs/workspaces-api-stub.ts
- Split out `workspaceList` into distinct lists of `publishedWorkspaces` and `featuredWorkspaces`.
- Hide the `Published Workspaces` tab behind a feature flag.
- Take `WorkspaceLibrary` props and state definitions out of the type parameter...
> RW-3417 [risk=no] workspace library changes

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
Also switch from FailedPrecondition to BadRequestException, which is now more appropriate for this situation.
> [RW-3418][risk=no] Cleanup additional 1ppw leftover comment

- ui/src/index.html
Walked through pages and checked components changed. Components affected include:
- cohort search/review components
- other components - resource card, h1, base buttons, one error
- homepage
Most are subtle changes and I didn't see any line wrapping issues. Examples:
Right side has font-weight 500.
Left side has font-weight 500.
> [RW-3454][risk=no]adding missing montserrat font weight 500

- ui/src/app/app.module.ts
- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/page-layout/page-layout.css
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.spec.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.css
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.ts
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/components/buttons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
Created `help-sidebar` component, designed to match this [Invision screen](https://projects.invisionapp.com/share/ZURSZVNW4RE#/screens/356269832). Used in the following pages/components:
- Data homepage
- Data Set page
- Cohort Builder
- Cohort Review Participants page
- Cohort Review Participant Detail page
- Concept homepage
- Concept Set Details page
Also moved `sidebar-content` component from `detail-page` in cohort review to new `help-sidebar` component.
> [RW-2484][risk=no] Create help tips sidebar component

- api/cluster-resources/aou-snippets-menu.js.template
This feels more natural. Raised in feedback from @deflaux. Also approved by Karthik.
> [risk=no] Create a new cell when inserting a snippet

- ui/src/app/components/popups.tsx
Prevent workspace navbar menu and modifier tooltip from being overlapped.
> [RW-3469][risk=no] Fix z-index for menu and tooltip

- api/src/dev/server/Dockerfile
One of these versions went out of date and is no longer available (curl package). This was probably overly specific - if we really want to lock in specific versions, we can periodically push a local dev docker image rather than building locally. I don't know that these versions were intentional, this was a carry-over from the original alpine image.
> [RW-3481][risk=no] Don't pin ubuntu package deps

- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
This may be revisited in the future, but for now this is needed for the migration so we don't drop non-notebook user data.
> [RW-3403][risk=low] Copy all GCS objects from the workspace bucket on clone

- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
the homepage background change (from dark blue to grey) affected the registration-dashboard headers, which are nearly invisible here:
I changed them to be the "primary" color and the warning sign to be the "warning" color:
This is currently being reviewed by Lou (designer) before it is ready to be reviewed by another dev.
This can be tested by going to the url like: http://localhost:4200/?workbenchAccessTasks=true
> [RW-3473][risk=no] make the registration dashboard headers readable on new background

- ui/src/app/pages/homepage/homepage.tsx
- ui/src/styles.css
Background color update and adding an additional comment on a feature flagged feature just to make sure we're deleting a file once we stop using it.
The color is a lighter grey.
before:
after:
> [no ticket][risk=no] default background color update

- ui/src/app/pages/signed-in/component.css
Background div is not adjusting to the size of the content. 
Cuts of on longer pages (Data page):
Overflows on shorter pages:
> [RW-3492][risk=no] Fix main background to adjust to size of content 

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Point fix for RW-3247 that stuffs the abbreviated column name (as determined from sniffing the `ds_linking` table in the CDR and built into a static map). This isn't a long term fix, as we [hope](https://precisionmedicineinitiative.atlassian.net/browse/RW-3495) to pull all that linking stuff out and simplify this whole process.
See my #2573 for some ongoing improvements to this class originally aimed at fixing this bug.
> [RW-3247][Risk=NO] Qualify the PERSON_ID column name

- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/TestJpaConfig.java
**Background**
ParticipantCohortStatusDao is a custom jpa crud implementation. This evolved out of the need to manually create batched insert statements. For unknown reasons Spring JPA nor JDBC batching works in appengine running in the cloud. It's old school but it solves our batching issue by using JdbcTemplate/NamedParameterJdbcTemplate. 
In the test case ParticipantCohortStatusDaoTest there is some funkiness with using ParticipantCohortStatusDao and JdbcTemplate in the same test. Seems that neither was using the same datasource/transaction. I'm using TestJpaConfig to override these issues and allows for everything in test to use the same datasource. Also, noticed that the test wasn't using the @DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)
> [RW-3462][risk=no] changing flaky test case.

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/utils/index.tsx
Searches entire help tip content, not just from current page. Used modified version of highlighting function from concept set search.
> [RW-2795][risk=no] Add search bar to help tip sidebar

- ui/src/app/components/inputs.tsx
Currently all date pickers will break when selecting a date from the calendar popup. Breaking change occured in #2537 , seems likely it was unintentional.
> [risk=no] Fix datepicker input

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/resources/fireCloud.yaml
This change specifies specific parameters to fetch when we call `getWorkspace` from FireCloud. This is intended to be a performance upgrade from what happens right now. From analysis of the code base, these are the only fields we need, and they are used basically everywhere.
> [RW-3491][Risk=low] Parameterize get workspace

- ui/src/app/pages/signed-in/component.ts
- ui/src/app/pages/workspace/workspace-about.spec.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/testing/stubs/cdr-versions-api-stub.ts
Problem: All cdrVersionStore access is done synchronously, however nothing was preventing components from rendering before CDRs were loaded.
Solution: Implement "withCdrVersions" HOC which blocks until CDR version load.
The rest of the data stores work inconsistently; the data load is highly decoupled from the assumption of synchronous data access. We should reassess this pattern.
> [RW-3540][RW-3342][risk=no] Fix synchronization of CdrVersionStore

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Tested locally. Verified I could reset my password via recovery email link.
Required upgrading the gsuite SDK.
> [RW-2032][risk=low] Include recovery email on user creation

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/utils/index.tsx
Last ticket for the help tip sidebar! Positioned at the bottom of the sidebar container, gives the user two options for support:
- FAQs - opens a new tab to the [Research Hub FAQ page](https://www.researchallofus.org/frequently-asked-questions/)
- Contact us - opens the Zendesk widget
> [RW-2796][risk=no] Add support footer to help sidebar

- api/db/vars.env
- api/libproject/devstart.rb
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Critical distinction:
- minInstances: all versions will maintain this instance count, regardless of whether they are actively serving traffic
- minIdleInstances: only the traffic-serving version will maintain this instance count
https://cloud.google.com/appengine/docs/standard/python/config/appref
> [RW-3560][risk=no] minIdleInstances over minInstances

- ui/src/app/pages/app/component.ts
- ui/src/app/pages/signed-in/component.ts
This addresses a bug where a user needs to sign in twice when they’ve been automatically logged out by our system.
The problem seems to be that there is no way to definitively know if the user had just signed in. This is because we use Google oAuth for authentication. From our systems POV, we send them to a Google auth link and the user returns at some later point with a valid token. When we send them off for Google authentication, we do not know if the authentication flow will be successful. When the user comes back, we do not know if this was their first sign in or not.
This distinction is necessary because we consider a user to be signed out if they have been inactive for 30 minutes. At the moment, it doesn’t seem like there is a way to know that a user had just signed in so we proceed …
> [risk=low][RW-3455] Fix double log in bug

- api/libproject/devstart.rb
10 was chosen arbitrarily, there is no evidence that we need this many tasks ahead of public launch. 1 is nice to avoid the very slow initial load on low use.
@gjuggler @blrubenstein FYI
> [risk=no] Downgrade prod to 1 idle API task

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
This codepath gets hit when a user visits the site and gets lazily created, rather than getting created by the account creation page. This happens primarily during local development.
Aside from this, the NPE is clearly visible within the UserService, since another method passes `userAffiliations = null`.
> [risk=no] Fix returning user creation

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-101-billing-project-garbage-collection.xml
- api/db/changelog/db.changelog-master.xml
- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/billing/BillingGarbageCollectionService.java
- api/src/main/java/org/pmiops/workbench/billing/OfflineBillingController.java
- api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectGarbageCollectionDao.java
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectGarbageCollection.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/cron.xml
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Cron endpoint for reassigning the Billing Projects associated with deleted Workspaces to "garbage collection" Service Accounts as a workaround to https://precisionmedicineinitiative.atlassian.net/browse/RW-3069
These GCSAs need to be created manually in the appropriate project for each environment and their credentials are copied to the environments' credentials buckets under a `garbage-collection` subdirectory.  When all the GCSAs for an environment become associated with too many groups, we will need to add more of them.
> [RW-3435][risk=medium] Billing Project Garbage Collection cron endpoint

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
Sneaky bug here: the "values" member of DataSet does not actually contain values we want to compare against.  Instead it refers to `DomainValuePair`s which must then be dereferenced to get their actual values.
This is confusing!  I'm going to fix that situation, but in PR #2631 since that is a much larger change.  This PR simply fixes the bug.
> [RW-3458][risk=no] Sort based on DataSet "sub-value" rather than value

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
The map error was caused by passing in all domains from the domainvaluepairs, not just the unique ones. Aside: could we just use a map for domainValuePairs.
Another issue was the library method StringUtils.capitalize() didn't convert already uppercase letters to lowercase.
This lets me get through the dataset request stuff, but I'm seeing permissions errors locally 
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
"code" : 403,
"errors" : [ {
"domain" : "global",
"message" : "all-of-us-workbench-test@appspot.gserviceaccount.com does not have storage.objects.create access to fc-secure-3f9af1df-24a5-44b2-82de-4c72e800a06d/notebooks/bb.ipynb.",
"reason" : "forbidden"
} ],
"message" : "all-of-us-workbench-test@appspot.gserviceaccount.com does …
```
> [RW-3623][RISK=no] domains must be unique and we need actual title case

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/resources/workbench.yaml
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/utils/index.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
The reason to do this is to reduce the chance we would hit the appengine timeout, and make it more likely we don't hit unexpected timeouts. Also, this allows us to display queries that return more quickly to the user before all queries have returned.
Attached is a screenshot of a domain loading:
For Mocks, those are here:
https://projects.invisionapp.com/d/main?origin=v7#/console/12820961/385557370/inspect
> [RW-3525][Risk=no] Preview per domain

- ui/src/app/pages/homepage/homepage.tsx
Karthik requested a wording change on the homepage.
Before:
After:
> [no ticket][risk=no]reword homepage subtitle

- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/cohort-search/utils.ts
- Prevent total count call with no includes criteria
- Prevent adding groups with no active items to search request
- Show excludes groups even if there are no includes groups
> [RW-3652][risk=no] Prevent unnecessary total count calls in CB search

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/utils/index.spec.tsx
- ui/src/app/utils/index.tsx
This is to avoid the AppEngine hard timeout limit, giving us the full time for each retry. 
Open question for reviewers: should I add a 'requested rows' parameter to the request that shrinks with each retry? This would be an optional parameter with some reasonable default.
> [RW-3528][Risk=no] Retry Preview Table from Front End only

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
Firecloud responded to `getBillingProjectStatus` with a `AddingToPerimeter`, a value that we are not currently tracking. Adding it so we do not NPE when we run into it.
Note: It's not clear when this change went out as it is undocumented, https://github.com/broadinstitute/firecloud-orchestration/blob/8aa0915a34e78893b07dccf9666291500a5d348b/src/main/resources/swagger/api-docs.yaml#L5196
> [risk=no] Fix NPE caused by missing "AddingToPerimeter" FireCloud status

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
This addresses the bug in RW-3651, by using map as opposed to directly calling `toString`, which would NPE when there was no object in the optional.
> [RW-3651][Risk=no] Move from toString to map

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillBillingProjectUsers.java
I am taking the same approach we took to parameterizing getWorkspace to say that the tests for this should be covered under rainforest/puppeteer, since it is ultimately an integration style change.
> [RW-3611][Risk=no] Add fields parameter to listWorkspaces

- api/src/main/java/org/pmiops/workbench/db/model/UserRecentWorkspace.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
In `UserRecentWorkspace`, the `@Column` annotation for `getLastAccessDate` was in camel case and should have been in snake case.
In `WorkspaceServiceImpl`, calls to `getRecentWorkspaces` that resulted in `user_recent_workspaces` needing to be pruned threw an error on the `.deleteByWorkspaceIdIn` because Spring thinks it should have been part of a transaction and it was not. So added a `@Transactional` to `getRecentWorkspaces` since that's where we get the data we pass in to `pruneInaccessibleRecentWorkspaces`.
> [RW-3653] [risk=no] Fix bug in Hibernate table mapping and add missing @Transactional to getRecentWorkspaces

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
The product ideal that Karthik and I talked about was to have the dataset variables qualified by the id, and then a comment at the top describing what dataset it corresponded to. ID ended up falling through, because there were no guarantees the dataset was created in the DB at this point, so I moved to random eight numeric characters. Eight was an arbitrary number I chose as likely enough to avoid conflicts, but few enough that it doesn't create too much clutter in the notebook.
> [RW-3518][Risk=no] Srubenst/data set variable names

- ui/src/app/pages/workspace/workspace-card.tsx
Default line-height is usually 1.2. Of course a line-height of 17 exploded things.
should be
> [no ticket] [risk=no] remove line-height

- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/login/sign-in.tsx
The new demographics survey has larger controls, where the overlap is more noticeable. Though this was already a problem on existing creation pages.
Transition point (increased window size a few pixels between screenshots):
> [RW-3684][risk=no] Tune background image transition points on account creation

- ui/src/app/pages/workspace/workspace-edit.tsx
Now has the following UX:
* Create Workspace -> No is selected for Request Review
* Edit Workspace -> existing workspace's Request Review selection is retained
* Duplicate Workspace -> No is selected for Request Review for the new workspace
> [RW-3384][risk=no] Fix workspace edit behavior for RW-3384

- .circleci/config.yml
- api/docker-compose.yaml
Should now be resolved per https://discuss.circleci.com/t/mysql-v5-7-docker-image-issue-october-16th-2019/32933
Reverts all-of-us/workbench#2686
> [risk=no] Revert "patch version of mysql in circle"

- api/libproject/devstart.rb
See the RW-3714 bug description for more details. This is a temporary fix to try and unblock deployments to test. We'll plan to rollback once a code fix is in.
> [RW-3714][risk=no] Remove data dictionary tasks from dev scripts

- api/src/main/java/org/pmiops/workbench/cohorts/CohortCloningService.java
A call to `save` was ignoring the result, and thus not capturing the cohort ID (leaving it at zero). Later, the foreign key between dataset and cohort tables could not be satisfied b/c cohort 0 did not exist.
Unit test updates to follow.
> [RW-3710][RISK=NO] Fix foreign key error in clone 

- api/libproject/devstart.rb
We're observing some high latency occasionally in production when many requests are issued in parallel and new instances are started without warmup. We can also try to tune our instances to accept more concurrent requests before scaling via the perf environment.
> [RW-3709][risk=no] Adjust prod idle task count upwards

- ui/src/app/pages/app/component.ts
- ui/src/app/services/sign-in.service.ts
- ui/src/app/utils/analytics.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
- ui/src/index.html
This PR is a step towards handling the "incorrect user counts" issue.
After digging into the Analytics data some more, I concluded that the bulk of our discrepancy is from short-lived user sessions that land on the login page of workbench.researchallofus.org but don't sign in. (This makes sense, since the site is publicly-accessible.)
The best way to ensure we're looking only at active, logged-in users is to track it as a custom dimension. I added a new per-session custom dimension in each of our Analytics properties, and this code will cause our client to start logging to this dimension. Once this pushes to prod, we can add segments & filters to data studio to differentiate between "all sessions" and "logged-in sessions".
One bump I encountered along the way was that at some point our …
> [RW-3578][risk=no] Track a loggedIn custom dimension in Analytics

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
Fix an issue caught by @freemabd where the wrong ID list was set. This happened to work locally (if the range of cohort IDs and concept IDs was close enough).
> [RW-3710][risk=no] use right ID list

- api/src/main/webapp/WEB-INF/cron_default.yaml
This cleans up projects stuck in various states more frequently, preventing the buffer from getting gummed up due to project creation issues. See https://pmi-engteam.slack.com/archives/CP4QVDS2H/p1571411860325500 for related discussion.
> [risk=no] Clean the buffer hourly (up from daily)

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- Keep `n1-standard-2` for perf to save some costs.
- Increase all other environments to `n1-standard-4`, from n1-standard-2
- Increase all environments boot disk size from `40GB` -> `50GB`
> [RW-3736][risk=low] Move cluster defaults to config, increase size

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceImplTest.java
Currently notebook plots don't work. These are implemented with inline data URIs, which are reasonably safe to render.
> [RW-3628][risk=low] Allow base64 notebook images, disallow other sources

- .gitignore
- api/build.gradle
- appengine-cron-emulator/src/main/java/org/broad/Cron.java
Stop-gap to get local dev working again. Longer term solution is https://precisionmedicineinitiative.atlassian.net/browse/RW-3755
> [RW-3755][risk=no] Fix cron, add error logging

- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/search-state.service.ts
Removes the tooltip from search group items and adds expanding section below each item with a list of selected criteria and modifiers.
> [RW-3543][risk=no] Make search items expandable to show selections

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
Apparently if a method without a `@Transactional` calls a method with a `@Transactional` in the same classfile you will get an error. This has to do with how Spring handles objects - for things like this it wraps the entire instance in a proxy that intercepts calls to annotated methods. If the first method called on the instance is not a `@Transactional` method, the proxy won't catch the call.
I _could_ set `@Transactional` on the class itself, which says 'by default, run everything in this class in a transaction with propagation required'. Bringing that one up in eng sync.
> [no ticket][risk=no] push @Transactional all the way up the ServiceImpl call stack

- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/app/utils/navigation.tsx
@blrubenstein noticed during QA that in some situations, it’s possible for Firecloud to return: OWNER → NOACCESS. The current solution assumed that once we saw OWNER, we were safe to assume that subsequent calls would also return OWNER. With this new knowledge, we now have no way of confirming whether a workspace is “ready”.
This solution simply avoids the extra GET here (which was a nice optimization anyways). This defers the next access check until a later user action (e.g. create cohort, etc), which might still fail, but which becomes less likely to fail as time passes. Doing anything more complicated than this on our side introduces risk, I think after this the next improvement is to fix the root issue in Sam.
> [RW-2818][risk=no] Further mitigate non-deterministic workspace ACL on creation

- api/build.gradle
Eliminates pages of warnings on local API server startup like:
```
api_1_53d67eaeafd6       | 2019-10-24 01:17:00.482:WARN:oeja.AnnotationParser:qtp1912962767-20: kotlin.sequences.SequencesKt___SequencesKt scanned from multiple locations: jar:file:///w/api/build/exploded-api/WEB-INF/lib/kotlin-stdlib-1.3.10.jar!/kotlin/sequences/SequencesKt___SequencesKt.class, jar:file:///w/api/build/exploded-api/WEB-INF/lib/kotlin-stdlib-1.3.50.jar!/kotlin/sequences/SequencesKt___SequencesKt.class
```
> [RW-3716][risk=no] Stop the Kotlin logspam

- ui/src/app/pages/homepage/homepage.tsx
Remove the section “How to Use the All of Us Researcher Workbench” from home page.
Styles and HTML were removed. Margin was added to the bottom between the main page and the bottom banner.
The goal is to re-add this in the future. I opted to delete the code rather than commenting the code out in order to keep the code base a bit cleaner. We can pull in whatever we need at that point.
Code for the old page (without feature flag) was removed in its own commit so that we don't have to pull it back in later.
Before
After
> [RW-3776][risk=no] Remove howtouse section from homepage

- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
- ui/src/app/styles/datatable.ts
- Get rid of extra white space on rows with single-line names ([RW-2812](https://precisionmedicineinitiative.atlassian.net/browse/RW-2812))
- Adjust spacing in column headers ([RW-3579](https://precisionmedicineinitiative.atlassian.net/browse/RW-3579))
Before:
After:
> [RW-2812][RW-3579][risk=no] Fix participant detail table styles

- api/src/integration/java/org/pmiops/workbench/NotebooksIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/WorkbenchConstants.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/notebook-redirect/component.ts
- ui/src/app/pages/analysis/reset-cluster-button.spec.tsx
- ui/src/app/pages/analysis/reset-cluster-button.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
Using the same variables that we use in code snippets - `CDR_VERSION_CLOUD_PROJECT` and `CDR_VERSION_BIGQUERY_DATASET`.
> [RW-3586][risk=no] Populate CDR version as env vars in notebooks

- api/src/main/webapp/WEB-INF/cron_default.yaml
I knew there was added risk in renaming the API endpoint, but I failed to double-check my own soft dependencies and test thoroughly locally.
At some point we should also seek to have monitoring that would have caught this more immediately when it was pushed to test – either through cronjob failure logs, and/or through the buffer becoming depleted.
> [RW-3779][risk=no] Fix the API endpoint targeted by the billing buffer cron task.

- ui/src/app/pages/profile/data-use-agreement-content.tsx
- ui/src/app/pages/profile/data-use-agreement-panel.tsx
- ui/src/app/pages/profile/data-use-agreement.tsx
This is a follow up to the DUA update. There are four main changes in here:
1. The sanctions modal appeared to be unused, so I removed it. 
2. There were several <p> tags, which not only didn't carry our styling with them, but also threw browser warnings when they had lists within them. I moved those into divs and added a paragraph style to them. That removed the warnings and also gave them the same font-color, spacing, and sizing as the rest of the page.
3. There was a list item that was not closed in the right place. This threw a warning. I closed it in the correct place which removed the console warning.
4. There were several <li> elements, which I moved to use our <IndentedListItem> object, which has some spacing styles attached. This helps ensure uniform styling throughout the page.
> [No Ticket][Risk=no] Removes old code and updates to use our styles

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
This makes a performance-focused optimization, to directly store & use the response object from a Terra cloneWorkspace call.
I had to finagle the API docs a bit, to pretend that get/list/clone/create Workspace all share the same underlying Workspace API model schema. As I understand from David An, this isn't strictly correct, but in practice the schemas are similar enough for our current usage.
David's team is tracking API doc fix-ups in https://broadworkbench.atlassian.net/browse/AS-21. I've set a watcher on that ticket, and we should do a one-off re-import of their Swagger once we're confident the API docs match reality.
TESTED: manually tested on a local env by duplicating a workspace as an owner. Seemed to work fine.
> [RW-3784][risk=no] Remove extra "get" call from cloneWorkspace

- ui/src/app/pages/data/data-set/dataset-page.tsx
Before: we allow shrinking screen width arbitrarily, but text overlaps into the the next section
After: we prevent decreasing screen width past a certain size and text does not overlap
> [RW-3674][risk=no]Set a minimum width on the Dataset Builder to prevent text collisions

- api/src/main/java/org/pmiops/workbench/WorkbenchConstants.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
Per conversation with Nicole Deflaux:
```
My recommendation would be to keep it simple: one new environment variable WORKSPACE_CDR where is value would be both the project id and the dataset name such as   'fc-aou-cdr-prod.R2019Q4R3'.
The only use case that comes to mind where I want the BigQuery project *only* is if I am programmatically trying to list all the BigQuery datasets in a particular GCP project. AoU curators might want to do this on occasion, but they know how to make that happen without the convenience of the environment variable.
```
There's an extra change here because Spotless has some opinions.
> [no ticket][risk=no] Change CDR env var name

- api/libproject/devstart.rb
While working on docker-sync stuff, I realized it would be really helpful for our dev scripts to track timings of each of the setup steps. Example output from changes in this PR:
Database startup...
...
Database startup complete (0.66s)
Database init & migrations...
...
Database init & migrations complete (27.43s)
Pushing configs & data...
...
Pushing configs complete (506.18s)
All dev-env setup steps complete (534.28s)
> [RW-3355] [risk=no] Add benchmark timing log messages for dev-up.

- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
One of my PRs merged and broke the build even though my branch passed due to git cleanly resolving a merge despite there being some functional changes.
Adds the necessary stub call.
> [risk=no] Add missing stub clone workspace call

- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- Prevent multiple age/deceased parameters on the same search item
- Fix int/string conversions when adding or reading age attribute operands
> [RW-3795][risk=no] Prevent multiple age parameters

- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
Full cluster names can be longer than this script expects.  This increase accommodated all of the currently-on-test clusters.
> [risk=no]Increase cluster name display width for deletion script

- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/demographics/demographics.component.css
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/utils.ts
- Show message for Sex Assigned at Birth wizard if no data in CDR
- Change parameter names and search item titles to show criteria types instead of 'Demographics'
- Update text for Sex and Gender in criteria dropdown list
> [RW-3765][risk=no] Update demographics display and text

- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Use angle brackets in declaration so that we're relying on the smarter flavor of generics.
> [RW-3858][RISK=NO] fix generic ambiguity warning

- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
Fixes issue when editing a non-age demographics item on an existing cohort, the count preview was empty.
Before:
After:
> [RW-3868][risk=no] Fix count preview when editing demo items

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/RetryHandler.java
When working on #2796, I was getting exceptions like:
```
api_1                    | SEVERE: java.lang.ClassCastException
api_1                    | java.lang.ClassCastException: org.pmiops.workbench.exceptions.NotFoundException cannot be cast to org.pmiops.workbench.notebooks.ApiException
api_1                    |     at org.pmiops.workbench.notebooks.NotebooksRetryHandler.convertException(NotebooksRetryHandler.java:14)
api_1                    |     at org.pmiops.workbench.utils.RetryHandler.run(RetryHandler.java:38)
api_1                    |     at org.pmiops.workbench.notebooks.LeonardoNotebooksClientImpl.createCluster(LeonardoNotebooksClientImpl.java:125)
api_1                    |     at org.pmiops.workbench.api.ClusterController.listClusters(ClusterController.java:133)
api_1 …
```
> [no ticket][risk=no] Don't try to cast WorkbenchExceptions to ApiExceptions

- api/cluster-resources/README.md
- api/cluster-resources/setup_notebook_cluster.sh
The current 2 Mib/s is too restrictive and causes Jupyter server errors.
I made several attempts to make Wondershaper long-lived across restarts, but I don't think it's possible without changes to Leo. Will discuss with Leo team next week. That change is tracked by https://precisionmedicineinitiative.atlassian.net/browse/RW-3874
Other changes here:
- Removed old pyclient for slightly faster startup (easier testing)
- Used make install to put wondershaper on path, not necessary for this change but may help later in setting up the recurring runs
> [RW-3706][risk=no] Increase VM upload rate limiter to 16Mib/s

- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/utils/errors.tsx
This catches an additional situation where processing might continue after the user leaves the page. Uses the fetch abort pattern which we could adapt elsewhere.
> [RW-3855][risk=no] Abort pending fetches on unmount as well

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/workbench.yaml
- ui/src/app/pages/analysis/reset-cluster-button.spec.tsx
- ui/src/app/pages/analysis/reset-cluster-button.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
Introduced in this release's commits, so we can fix it before it goes to Production
> [risk=low][no ticket]Use the Workspace's firecloudName when interacting with Cluster APIs

- api/src/test/java/org/pmiops/workbench/db/LiquibaseTest.java
See https://github.com/all-of-us/workbench/pull/2812 to see a failing example after I added a liquibase changelog file and "forgot" to add it to the changelog master file.
> [RW-3052][risk=no] Add test that verifies all liquibase files are indexed for migration

- ui/package.json
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/pages/data/cohort-review/annotation-definition-modals.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/yarn.lock
(Opt) Bare strings always scare me. Either here or as a follow-on, we could use https://github.com/nfriend/ts-key-enum to refer to these keys in a type-safe way.
_Originally posted by @gjuggler in https://github.com/all-of-us/workbench/pull/2813_
This PR addresses this issue but also contains package updates since there were warnings about security issues (with outdated packages) and only NON-breaking changes.
I'm not entirely sure what our process is for updating packages. Ideally, we could depend on our tests to catch regressions, but there may be other best practices as well. I'm open to any ideas or suggestions!
Give a heads up to others to pull in these changes on their local UI branches.
-----
Chatting with Zarsky, he recommended reading the changelog of updated direct dependencies, …
> [noticket][risk=moderate] key enum and package updates

- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/services/setup.ts
We were handrolling validation for this page. I've switched it to `validation.js`. Everything is now more or less in the same place.
Relatedly, I can't believe validation.js doesn't have a truthiness validator. I guess it was originally intended for validating pretty simple forms and not whatever it is we're doing.
> [RW-3844][risk=no] convert to validate.js

- ui/package.json
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/pages/data/cohort-review/annotation-definition-modals.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/yarn.lock
Reverts all-of-us/workbench#2817
When looking to update and audit packages, I ran `yarn install` and got the following warning:
```▶ yarn install          
yarn install v1.17.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```
which I realized is probably because the package in the above PR was installed with npm when our system should only be using yarn as a package manager. Reverting the PR so that we can do this mo betta.
> Revert "[RW-3902][risk=moderate] key enum and package updates"

- api/cluster-resources/setup_notebook_cluster.sh
Partly reverts changes from https://github.com/all-of-us/workbench/pull/2807
Before:
After:
> [RW-3905][risk=no] Revert removal of AoU pyclient package

- ui/package.json
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/pages/data/cohort-review/annotation-definition-modals.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/yarn.lock
This is essentially the same PR as this one:
https://github.com/all-of-us/workbench/pull/2817
minus many updates to packages, which are being handled in a separate PR.
----
(Opt) Bare strings always scare me. Either here or as a follow-on, we could use https://github.com/nfriend/ts-key-enum to refer to these keys in a type-safe way.
_Originally posted by @gjuggler in https://github.com/all-of-us/workbench/pull/2813_
This PR addresses this issue
----
Previously, npm was accidentally used to install the package. We use yarn instead of npm as a package manager so that was resolved in my local env by deleting the package-lock.json file that npm generated. It doesn't seem like it affected the dev code at all. Phew!
I considered adding the package as a yarn devDependency with: `yarn add --dev …
> [RW-3902][risk=moderate] key enum and package updates - take #2

- api/cluster-resources/setup_notebook_cluster.sh
- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
This upgrades us to the new Jupyter Docker image. We are using the 'GATK' image, because it has up to date python and R. Manually tested in both R and Python by exporting a dataset, running both queries generated, and trying setup and a selection of other snippets. (All of the AoU specific snippets, unless I noticed a pattern that broke them, like with measurement_ext)
> [RW-3686][Risk=moderate] Upgrade Jupyter docker

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
See PR description for more details. We've decided to extend the Firecloud API request timeout to err on the side of caution for next week's workshop.
> [RW-3878][risk=no] Bump firecloud timeout from 40 to 60s

- ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts
Found errors while updating dependencies
```
Error:(39, 7) TS2322: Type '{ accessLevel: WorkspaceAccessLevel; id?: string; etag?: string; name: string; namespace?: string; cdrVersionId?: string; creator?: string; googleBucketName?: string; dataAccessLevel?: DataAccessLevel; researchPurpose?: ResearchPurpose; creationTime?: number; lastModifiedTime?: number; published?: boolean; }' is not assignable to type 'WorkspaceResponse'.
Property 'workspace' is missing in type '{ accessLevel: WorkspaceAccessLevel; id?: string; etag?: string; name: string; namespace?: string; cdrVersionId?: string; creator?: string; googleBucketName?: string; dataAccessLevel?: DataAccessLevel; researchPurpose?: ResearchPurpose; creationTime?: number; lastModifiedTime?: number; published?: boolean; }'.
Error:(105, 34) …
```
> [noticket][risk=no] remove unused code in workspace-wrapper test

- api/config/config_prod.json
Simple config change to guard against heavy use of workspace creation and cloning during the DRC workshop happening on Thursday.
There's an open question on what the correct long-term buffer size in production should be... based on what we see in the workshops and ongoing usage, we may be able to keep a smaller buffer (possibly with a higher replenishment rate) for ongoing workshops and even public launch scenarios.
> [RW-3961][risk=no] Bump prod project buffer limit from 100 to 200.

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
This change was originally made as a performance optimization: https://github.com/all-of-us/workbench/pull/2522 . Now that we have partial field responses on `getWorkspace()`, this approach is probably the same as or faster than the `getWorkspaceAcl()` approach, and requires less custom logic on our side.
From looking at the code and surrounding context for the comment about "not using this for access checks", I'm comfortable using this as we are in our application (but have an email out to clarify), and at worst it looks equivalently authoritative to getWorkspaceAcl: https://github.com/broadinstitute/rawls/blob/e4983e78748dffcc444924ec2b3c96a9bcd1e06a/core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala#L317-L330
Manual testing: published a workspace …
> [RW-3829][risk=low] Revert ACL check logic

- ui/src/app/cohort-search/utils.ts
Seems flaky and fails tests for random components with the error message:
```
HeadlessChrome 70.0.3538 (Linux 0.0.0) ERROR
{
"message": "An error was thrown in afterAll\nUncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.",
"str": "An error was thrown in afterAll\nUncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'."
}
HeadlessChrome 70.0.3538 (Linux 0.0.0): Executed 22 of 41 ERROR (0 secs / 7.39 secs)
HeadlessChrome 70.0.3538 (Linux 0.0.0) ERROR
{
"message": "An error was thrown in afterAll\nUncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.",
"str": "An error was thrown in afterAll\nUncaught TypeError: Failed to execute …
```
> [risk=no] Attempt fix for failing UI test

- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/recent-resources.tsx
- ui/src/app/pages/homepage/recent-workspaces.tsx
So, this fixes a few things. First, it addresses the ticket, which is to remove the jitteriness/movement of the page when you share or delete a recent workspace. Then, from feedback from Lou, it hides the recent resources header when there is no content there. Third, it reduces the amount of spinner jitteriness while the data is loading.
There is one todo that I am going to pick up, where if there are no recent resources, it currently hides the header and the area for the content, Lou wants it to have some text stating "you have no recent resources" instead, to reduce content moving. Doing that as a follow up task/PR since it is technically a new functional change.
> [RW-3801][Risk=no] Fix jitteriness with share and delete, and improve loading spinners

- ui/src/app/cohort-common/combo-chart/combo-chart.component.tsx
- ui/src/app/cohort-search/gender-chart/gender-chart.component.tsx
Sets height for graphs based on the number of labels on the vertical axis, with a minimum of 200px. Prevents missing labels when there are too many categories, as seen in bottom chart in the attached screenshot:
The data is correct but the chart looks wrong because there are more bars than labels.
> [RW-3972][risk=no] Fix height for CB graphs

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
Per slack discussion, comparing to the current time may not be correct given:
- large sets of billing projects (syncBillingProjectBuffer may not visit all projects within the deadline)
- Firecloud API errors, or extended outages
Transitions in either of these cases would result in leaked billing projects.
> [risk=no] Improve cleanBuffer CREATING -> ERROR transition logic

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CdrVersionsController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/CdrVersionsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
We found a better way to dynamically change the value provided by Spring Providers in tests that no longer relies on exposing a test only method on our controllers.
To expand on the point above, we used to use a pattern of exposing a `setXProvider` methods on our service/controller classes for the sole purpose of being able to modify the provided value in tests.
ex. `@VisibleForTesting setUserProvider(Provider<User> userProvider) {}`.
We would use this in our tests by creating a provider to return the value we wanted to test and calling the `setUserProvider` method with our mocked provider.
We believe this was necessary because Spring would essentially treat values returned through the `Provider` mechanism as an immutable singleton, so it would cache the initialized value and return that …
> [risk=no][RW-3843] Refactor out usages of @VisibleForTesting for Spring Providers

- api/config/featured_workspaces_staging.json
Minimally, this will be useful for manual QA purposes. This is a gap I identified when pushing out new featured workspaces content a few weeks back. 
Before:
After:
> [risk=no] Add featured workspaces in staging for QA purposes

- ui/src/app/services/sign-in.service.ts
This currently generates a JS error whenever someone hits the site in the signed out state (see console). AFAICT it wasn't causing any actual user-facing issues.
```
Uncaught TypeError: Cannot read property 'getImageUrl' of undefined
at SignInService.get [as profileImage] (sign-in.service.ts:106)
at SignInService.push../src/app/services/sign-in.service.ts.SignInService.nextSignInStore (sign-in.service.ts:113)
at sign-in.service.ts:72
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
at Object.onInvoke (core.js:4760)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
at NgZone.push../node_modules/@angular/core/esm5/core.js.NgZone.run …
```
> [risk=no] Don't populate signInStore when not signed in

- api/build.gradle
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillBillingProjectUsers.java
- api/tools/src/main/java/org/pmiops/workbench/tools/FetchFireCloudUserProfile.java
- api/tools/src/main/java/org/pmiops/workbench/tools/FetchWorkspaceDetails.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ServiceAccountAPIClientFactory.java
This adds a new project.rb tool which can take a Firecloud Project ID or workspace namespace and output workspace details (creator + collaborator emails).
Example Input
`./project.rb fetch-workspace-details --project all-of-us-workbench-test --projectId=aou-rw-test-3f23b78e`
Example output
```
***
***
***
Workspace Name: Should be seen
Workspace Namespace: aou-rw-test-3f23b78e
Creator: ericsong3@fake-research-aou.org
Collaborators:
ericsong3@fake-research-aou.org (OWNER)
ericsong@fake-research-aou.org (WRITER)
***
***
***
```
> [risk=low][RW-3982] Create project.rb tool to get workspace details from project ID

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
During the workshop, we realized all the dates in the preview table in dataset builder were very close to the Linux Epoch. When I poked around locally, the values from the API seemed to be similarly incorrect. When looking at the values side by side with something that would be pointing to a date similar to what we might expect, it looked like they might be off by a factor of 1000. Ariel and I determined BQ was likely returning data in seconds rather than milliseconds.
Tested manually and it looks fine
> [RW-3988][Risk=no] Srubenst/preview data time formatting

- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
Issue: https://precisionmedicineinitiative.atlassian.net/browse/RW-3822
**Solution**: If the selected concept set introduces a new domain add values to valueSet as well as selected domain list 
**Testing**:
1) Add a concept set with Domain say 'Condition'
a) the values tab should be populated with list of Condition domain values
b) All of the values should be selected by default
c) Values tab header should have the selected Checkbox with label Deselect All 
2) De-select some of the values
a) Values tab header should have the un-selected Checkbox with label Select All 
3) Select another Concept set with the same domain 'Condition'
a) There should be no change in values, not only the values remain the same also the header should still say 'Select All' with un-selected checkbox
> [RISK=LOW][RW-3822] Default selection of values

- api/src/main/java/org/pmiops/workbench/actionaudit/adapters/ProfileAuditAdapter.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/adapters/ProfileAuditAdapterImpl.kt
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
The closest thing we have right now to a "login event" is the `getMe()` method on the `v1/profile` endpoint. This works to catch logins, but also captures profile display actions.
As of right now, we think this is better than nothing. The extra events are during a session anyway, and shouldn't lead to wildly inaccurate conclusions.
> [RW-4007][RISK=NO] Login Auditing

- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/pages/profile/data-use-agreement-panel.tsx
- ui/src/app/pages/profile/data-use-agreement.spec.tsx
I decided there were two major tests missing. One to verify the saving of DUA information, and the other test to verify initials all need to be correct on the front end to save.
> [RW-3870][Risk=no] Add DUA tests

- api/src/integration/java/org/pmiops/workbench/ApplicationTest.java
- api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortFactoryTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
The decision was to go with Truth, which means moving out the assertions from AssertJ.
The only place where there might be pain is around the use of `isWithinPercentage()` which has no direct analog. I tried to find a reasonable workaround there.
> [RW-3602][RISK=NO] Replace uses of AssertJ with Truth

- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- Fixes issue where selecting a domain tab with no results doesn't remove previous rows from the table or show the empty message
- Prevents spinners from overlapping other content and hides results messaging while loading data (eg: 'Showing top 0 of 0 Conditions')
- Format all counts with commas
> [RW-3866][risk=no] Minor UI fixes for concept search

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.css
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.spec.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.html
- ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/app/services/review-state.service.ts
- Removes `HelpSidebar` from individual pages and adds it to `WorkspaceWrapperComponent` so it shows on all pages within a workspace (except `InteractiveNotebookComponent`).
- Adds a `helpContent` property to the data for each route with the help sidebar that determines the help tip content.
- Moves handling of participants/annotations for `SidebarContent` component into `review-state.service.ts` instead of using `props`.
@freemabd to deploy and test locally, especially annotations
@NehaBroad for general review, especially changes to workbench code
> [RW-3771][risk=no] Move help tips sidebar into workspace wrapper

- api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java
Dev notes
* This PR makes some small changes / additions to our tracing code to improve the readability of spans representing incoming AoU API calls.
* The changes mostly improve the way we extract information from Swagger-generated API methods and whatnot.
* One potentially controversial change: the "Test" prefix is gone from the span name. I realized that treating it as a label probably made more sense.
* I coded this one rainy Friday afternoon several weeks back... it's been sitting in a local branch since then and I finally had a chance to wrap it into shape. It's super low-priority.
Before:
After:
(Note: the "Recv" prefix is auto-added by Stackdriver when the span type is set to Span.Kind.SERVER, see [code](https://github.com/census-instrumentation/opencensus-go/commit/b8f3b913f034c56 …
> [no ticket][risk=no] Improve trace method name & labels for inbound API spans

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Certain R packages could not be installed due to outdated libraries, and we no longer populate the environment variable WORKSPACE_BUCKET.
Solution: use the latest version of terra-docker-gatk as our docker image, which includes an updated R build and restores WORKSPACE_BUCKET.
PR to update terra-docker-r with the fix to RW-3973: https://github.com/DataBiosphere/terra-docker/pull/54
PR to update terra-docker-gatk to include the fixed terra-docker-r: https://github.com/DataBiosphere/terra-docker/pull/60
PR to update all terra docker images with the fix to RW-4078: https://github.com/DataBiosphere/terra-docker/pull/63
Jenkins-triggered PR to push the [docker image](https://us.gcr.io/broad-dsp-gcr-public/terra-jupyter-gatk:0.0.6) to GCR: …
> [RW-3973][RW-4078][risk=low]Update jupyter docker to terra-jupyter-gatk:0.0.6

- ui/src/app/pages/data/cohort-review/cohort-review.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
Fixes issue where previous cohort is still loaded in `currentCohortStore` if the user goes directly from cohort review to building a new cohort.
> [RW-4073][risk=no] Remove unneeded cohort store references

- api/src/main/java/org/pmiops/workbench/monitoring/signals/GaugeSignals.java
Description:
API startup error: `NoClassDefFoundError: com/google/appengine/repackaged/com/google/common/collect/ImmutableMap`
Replace this import with a reference to `com.google.common.collect.ImmutableMap`
---
> [risk=no]Import correct ImmutableMap

- api/src/main/java/org/pmiops/workbench/api/OfflineAuditController.java
- api/src/main/webapp/WEB-INF/cron_default.yaml
This cron needs to be updated or deleted to handle VPC-SC.
Description:
---
> [RW-3331][risk=no] Disable defunct BigQuery audit cron for now

- ui/angular.json
- ui/src/app/components/rename-modal.tsx
- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/new-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/workspace/new-workspace-button.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/pages/workspace/workspace-share.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/app/utils/analytics.ts
- ui/src/environments/environment.localtest.ts
Dev Notes
- I tried to trigger the event as close to the onClick as much as possible
- I wanted to centralize the logic so there's a single place to look at what events we're tracking
- The `getCurrentPageLabel()` bit might be controversial but I felt like it was the cleanest way to infer where we currently are on the page. The traditional way passing the info down through props/args would have resulted in a *lot* of new info being shuttled around. 
Things I learned
- One form of Google Analytics tracking is firing “Events”.  “Events” have three levels specificity of Category, Action, and Label. See https://support.google.com/analytics/answer/1033068#Anatomy
- As it applies to our application, I view “Category” as a product area, “Action” as a verb that the user would do, “Label” as …
> [RW-3689][risk=no] Google Analytics Events - Workspaces

- api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
Description:
- Adds Users w/o workspaces to the workspace export tool
- Add access level to the collaborators column
Things I learned
- Spring Dao `findAll` will return an iterable.  This can be easily converted to a stream (and then into Java collections) using Guavas `Streams.stream(iterable)`.
---
> [RW-4072][risk=no] Include users without workspaces in user data export

- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceImplTest.java
- ui/src/app/pages/analysis/interactive-notebook.tsx
5MB is chosen as the cutoff here. From manual testing, I found that with our current GAE task configuration, previews would start failing around ~10MB. I couldn't find any good tooling for analyzing memory use on GAE Java servers, there is probably room for improvement here. It is possible that we are still susceptible to OOMs from concurrent preview requests on a single server with this approach.
Too large error:
Unexpected error:
---
> [RW-3998][risk=low] Reject previews of large notebooks, add preview page error handling

- ui/app.yaml
This should have no bearing on security or the application; it is just to satisfy AppScan alerts.
Description:
---
> [RW-3428][risk=no] Apply stricter frame-ancestors to static UI resources

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditAdapterImpl.java
Description:
Alerting threw an exception due to missing fields.  The offender turned out to be the timestamp.
---
> [risk=no]Fix self bypass

- ui/src/app/pages/data/concept/concept-set-details.tsx
Description:
This PR adds a loading spinner to the concept delete modal in concept sets. I left the disabled state on the buttons because I wasn't sure what our pattern was around that, and it seemed like the smallest change. This addresses 4109, because we could not reproduce the users original bug, this is the approach from product to try to make what is happening more visible. 
---
> [RW-4109][Risk=no] Add spinner to delete modal

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/resources/workbench.yaml
This removes an unused endpoint from our swagger and controllers. 
The use of this endpoint was removed as part of https://precisionmedicineinitiative.atlassian.net/browse/RW-706 via this PR: https://github.com/all-of-us/workbench/pull/873
---
> [No Ticket][Risk=low] Remove stale endpoint

- api/tools/src/main/java/org/pmiops/workbench/tools/CommandLineToolConfig.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
- api/tools/src/main/java/org/pmiops/workbench/tools/FetchFireCloudUserProfile.java
- api/tools/src/main/java/org/pmiops/workbench/tools/FetchWorkspaceDetails.java
- api/tools/src/main/java/org/pmiops/workbench/tools/LoadDataDictionary.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
- api/tools/src/main/java/org/pmiops/workbench/tools/SetAuthority.java
- api/tools/src/main/java/org/pmiops/workbench/tools/UpdateCdrVersions.java
- `@SpringBootApplication` is an alias for 3 annotations, one of which was problematic:
- `@Configuration` (effectively: this class can declare beans)
- `@EnableAutoconfiguration` (import basic Spring modules, e.g. JPA, REST stuff, Liquibase)
-  :warning: `@ComponentScan` (start grabbing all beans indiscriminately from the current source tree rooted at this package)
- ComponentScan had the side effect of muddling up all tool bean configs (including everything in every CLI tool) in the source directory into the same context, this was unexpected and undesirable.
- For a given CLI tool, in addition to that tool's `@Configuration`, the only thing we actually wanted to scan was the `CommandLineToolConfig`, which now needs to be explicitly brought in
- Also switch to a parent/child …
> [risk=low] CommandLineToolConfig restructuring for CLI bean isolation

- common-api/src/main/java/org/pmiops/workbench/db/model/CommonStorageEnums.java
- common-api/src/main/resources/common_api.yaml
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
** Both items below are feature flagged for local and test environments only
- Add tabs for Surveys and Physical Measurements in concept search ([RW-4149](https://precisionmedicineinitiative.atlassian.net/browse/RW-4149))
- Add Physical Measurements card on Concept homepage ([RW-4145](https://precisionmedicineinitiative.atlassian.net/browse/RW-4151))
---
> [RW-4149][RW-4145][risk=no] Add new tabs and tile behind feature flag in concept search

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
new demographic data trees have duplicate concept ids in the criteria table and are causing the following error in prod:
`java.lang.IllegalStateException: Duplicate key 1177221 (attempted merging values I prefer not to answer and I prefer not to answer)`
> [RW-4215][risk=no] fixing Map error

- api/src/main/java/org/pmiops/workbench/api/StatusAlertController.java
- api/src/main/resources/workbench.yaml
When there was no status alert in the DB, we were getting a JS error because the Swagger autogen client side code was trying to parse json out of the response (which doesn't exist in a 204). I guess 204s are Bad. We send back an empty StatusAlert object now.
> [no ticket][risk=low] Fix js error with 204 from status alert

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Haven't fixed this everywhere because we do a bunch of inane DOM choices like sticking the checkbox in one flexbox and the label at the top of the flexbox next to it... but here is at least one clickable checkbox label.
> [no ticket][risk=no] Clickable checkbox label

- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
This PR moves the following daos into the ConceptService used by the ConceptsController. This moves all database interaction from the ConceptsController into the service layer.
- DomainInfoDao
- SurveyModuleDao
Also, removing entityManager since it's no longer referenced.
> [risk=no] moving domainInfoDao and surveyModuleDao into the ConceptService

- ui/package.json
- ui/yarn.lock
Description:
Upgrade serialize-javascript to 2.1.1 or higher, as alerted [here](https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/serialize-javascript/open) 
---
> [risk=no]Upgrade vulnerable serialize-javascript

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Reverts all-of-us/workbench#2945
This was causing a breakage where the new LabeledCheckbox component was being used in the workspace-edit UI. The fix is non-trivial, so we'll get a rollback in so we're safe for next week's release.
> [RW-4223][risk=no] Revert the clickable checkbox label change.

- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/main/resources/client_api.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/DomainInfoDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/DomainInfoDao.java
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-survey-add-modal.spec.tsx
- ui/src/app/pages/data/concept/concept-survey-add-modal.tsx
- ui/src/app/pages/data/concept/survey-details.tsx
Concept set builder now implements tab counts for PM and Surveys. 
All domains including Surveys in concept set builder will use ConceptsController.searchConcepts
> [RW-4236][risk=no] - adding counts for PM and Surveys

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/appengine/AppEngineMetadataSpringConfiguration.java
- api/src/main/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterService.java
- api/src/test/java/org/pmiops/workbench/monitoring/MonitoringServiceTest.java
- api/src/test/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterServiceTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
We need to use the `generic_node` [MonitoredResource](https://cloud.google.com/logging/docs/api/v2/resource-list) type since we run on AppEngine and can have multiple nodes writing at once.
Since we don't have a namespace, I chose the short name of the environment. For the instanceId, sometimes we get an exception saying it's not available, and I just use a GUID for that. This hopefully only happens on local, but we're more concerned with avoiding hitting the rate limits when we have escalated instance counts than with debugging performance of particular instances at the moment.
---
> [RW-4226][RISK=no] Use descriptive, unique-per-instance MonitoredResource specification

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/auth/ServiceAccounts.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
After #2962 merged, we started seeing 401 errors in test when creating a new workspace.
I tracked this down to an issue where the newer GoogleCredentials library doesn't do what I was expecting when calling GoogleCredentials.getApplicationDefault(). See the new comments on the ServiceAccounts method which describes the issue in some detail.
This PR essentially brings back the logic to switch how we generate scoped service credentials based on the operating environment: if App Engine, use the AppIdentityService; if development, use ADCs. This method is called by a couple config classes for APIs which use our service identity to call downstream APIs.
---
> [RW-2840][risk=no] Use AppIdentityService to generate service-backed credentials

- ui/src/app/components/inputs.spec.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/components/tables.tsx
- ui/src/app/pages/analysis/confirm-playground-mode-modal.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
I ended up digging into the checkbox issue a bit more on Friday. I think this is the most balanced approach to fixing the issue. The crux of the matter is this: should a checkbox manage its own checked state, or should it always blindly render the value passed in via props?
After taking stock of existing usage in the Workbench, I realized that in most scenarios, it's fine to allow checkboxes manage their own state. Wrapping components can pass in the initial value, and listen for changes by providing an .onChange(checked) prop.
In one or two use cases, though, we seem to be expecting the checkbox to always render the value passed in via props. The wrapping component implements the toggling behavior by listening to onChange events, updating its own state, and using that state variable to …
> [RW-3650][risk=no] Add label support to our core CheckBox class and add type-safety and unit tests.

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Choose a version of Reticulate which includes this PR: https://github.com/rstudio/reticulate/pull/699
This is a temporary solution.  A longer-term fix is described here: https://docs.google.com/document/d/10FPO4fIAjGZUsLf1EKhDsUwS7afUMWBxsNR5KhSkLq4/edit#
Description:
---
> [risk=low][RW-4241] Install a specific version of reticulate to avoid a kernel-crashing bug

- api/src/main/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterService.java
- api/src/test/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterServiceTest.java
The `MonitoredResource` structure now contains information on our environment and project, so we don't need to keep any of that in the metric names as we had originally. Additionally, project-level information is already in place in the `StackdriverStatsConfiguration` object. Using these mechanisms should be a better experience for automation, as we're working with metadata directly instead of pulling it out of a longer string.
---
> [no ticket][risk=no] Use same metric names for all environments

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ClusterAuditor.java
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ClusterAuditorImpl.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/ClusterAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- ui/src/testing/stubs/cluster-api-stub.ts
- ui/src/testing/stubs/cluster-service-stub.ts
Description:
This adds an endpoint which allows security admins to delete all clusters in a project. We went with delete because Leonardo doesn't currently allow for stopping clusters as a project owner, just deleting them.
Manual test on local included:
Deleting current user's cluster as that user.
Deleting another user's cluster as one user, in a workspace the user does not have access to. 
I would love some thoughts on the unit tests here, because I am unsure where the cost/benefit lands for amount of unit tests. (The one I wrote just basically verifies that it hits Leo)
---
> Add admin delete clusters in project endpoint

- api/src/main/java/org/pmiops/workbench/monitoring/GaugeRecorderService.java
We now have enough output from the gauges that it's getting in the way if you're not working directly on instrumentation.
> turn down logLevel

- api/src/main/java/org/pmiops/workbench/monitoring/views/GaugeMetric.java
All gauge metrics should use LastValue aggregation, since [Stackdriver uses the aggregation type](https://cloud.google.com/monitoring/custom-metrics/open-census) to determine the MetricKind.
> [no ticket][risk=no] Make all Gauges use LastValue aggregation.

- README.md
Merged too soon.
@ericsong `appengineRun` does not depend on `compileGeneratedJava`.
> [no ticket][risk=no] update README.md again

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/notebooks.yaml
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Description:
Tested by deploying a notebook with these images and running the Notebook Tester workspace's notebooks.
Confirmed that the cluster is using these images by querying Leonardo.
Cluster creation time does not appear to be meaningfully affected.  Translated "timings" at the end of dataproc-initialization-script-0_output : 
GCR run 1: 18:21:18 to 18:23:28
GCR run 2: 18:33:37 to 18:35:46
GCR run 3: 18:47:57 to 18:50:03
Dockerhub run 1: 19:12:44 to 19:15:16
Dockerhub run 2: 16:50:55 to 16:52:57
Dockerhub run 3: 17:07:38 to 17:09:49
---
> [risk=low][RW-4231]Use dockerhub jupyter and welder images

- api/db/changelog/db.changelog-115-addColumn-user-create-modified.xml
- api/src/main/java/org/pmiops/workbench/db/dao/RdrExportDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
This will remove the not null constrain on the  columns creation and last_modified_time as well as removing the default values.
The reason behind this is that rather than populating creation_time with first_sign_in (which can be null as well as incorrect) or the current date time, we will spend effort in trying to find ways to populate the column with close to actual creation_date time for existing user (maybe checking when the got the email for registration or other way). In order to do that its better to have the values as null so it will be easier to find users that needs updating.
There is another ticket that is going to take care of populating the correct creation and last_modified_time for existing users https://precisionmedicineinitiative.atlassian.net/browse/RW-4278
> [RISK=LOW][No ticket] Removing null constraint from User table column creation and modified time 

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/DomainInfoDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/DomainInfoDao.java
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- ui/src/testing/stubs/concepts-api-stub.ts
adding PM and Surveys to concept search. This PR includes changes for:
- make-bq-data.sh - update standard concept counts for measurements
- ConceptsController - converting TO_CLIENT_CONCEPT function to a regular method and updating   search to include PM/Survey
- ConceptService - updating service to include PM/Survey calls
- CbCriteriaDao - implemented survey db calls here to allow proper ordering of questions
- ConceptDao - Implemented PM db calls here
- DomainInfoDao - added source/standard checks and implemented call for PM
> [RW-4233][risk=no] adding PM and Surveys to concept search

- api/config/cdr_versions_perf.json
- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
move cloud cdr versions in config files
**cdr_versions_test.json** 
synth_r_2019q3_3 -> synth_r_2020q1_1
**cdr_versions_staging.json**
synth_r_2019q3_3 -> synth_r_2020q1_1
**cdr_versions_stable.json**
synth_r_2019q3_3 -> synth_r_2020q1_1
**cdr_versions_perf.json**
synth_r_2019q3_3 -> synth_r_2020q1_1
**cdr_versions_prod.json**
synth_r_2019q3_2 -> synth_r_2020q1_1
r_2019q4_3 -> r_2020q1_1
> [RW-4302][risk=no] moving cloud cdr versions.

- api/db/changelog/db.changelog-115-addColumn-user-create-modified.xml
This PR will add default values 'Jan 1 1970' TO user column creation_time and last_modified_time. 
In order for this to reflect on test i will rollback changes for existing 115 as well as remove the entry from databasechangelog in just this case
> [RISK=NO][No ticket]Add default value to creation_Time

- api/db/changelog/db.changelog-115-addColumn-user-create-modified.xml
- api/db/changelog/db.changelog-116-drop-user-creation-modified.xml
- api/db/changelog/db.changelog-117-add-user-creation-modified-column-again.xml
- api/db/changelog/db.changelog-master.xml
This PR has 3 database script file:
1) 115 : Skip if USER TABLE have creation_time and last_modfied_time COLUMNS already else create the two columns with
- creation_time with not null 
-  last_modified_time with null constraint. and default value as current_timestamp
2) 116: DROP column creation_time and  LAST_MODIFIED_TIME if they exist in USER else skip
3) 117: Add columns creation_time and  LAST_MODIFIED_TIME  again with null constraints and defaultdate as 1970 Jan 1
The reason for three scripts are as follows:
1) Date with null constraint cannot be updated later with another default value as it starts giving liquibase base exception 
_liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Data truncation: Incorrect datetime value: '0000-00-00 00:00:00' for column …
> [RISK=MEDIUM][no ticket] Add default value to user creation date and last modified time

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/webapp/WEB-INF/cron_default.yaml
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchLocationConfigService.java
While testing i saw the following (silly) errors:
1) Cron yaml url doesnt case match the entry in workbench.yaml
2) String Equal was using == rather than .equal because of which the correct location was not being send.
3) Send Workspace Collaborators Status as ACTIVE to RDR
> [RW-4091][RISK=NO] Correct exportRDR cron URL

- api/build.gradle
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/billing/BillingGarbageCollectionService.java
- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillBillingProjectOwners.java
Description:
We are increasing the scope of the AoU workspace owner (also the Firecloud project owner) to grant the owner role on the corresponding billing project. This grant takes place on new workspace creation as well as workspace sharing. Ownership is removed if a user is removed as an owner from a billing project.
This PR also adds a project.rb command which will backfill all existing workspace owners as billing project owners. This is an adaptation of the backfill billing project users script. The most notable changes are
- Granting "owner" instead of "user"
- Not skipping over workspace creators
Running the dry-run version of the script on stable results in 468 calls
`INFO: [DRY RUN] Would have... added 468 users as billing project owners` 
---
> [RW-2695][risk=moderate] AoU workspace owners are now billing project owners instead of users

- api/cluster-resources/README.md
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- Read from our static API https assets
- Add instructions for testing local cluster resources
- Teardown/refactoring of GCS pushing steps is tracked by https://precisionmedicineinitiative.atlassian.net/browse/RW-4313
- Verified manually that all extensions and scripts successfully loaded/executed via a local API server (which by default, references static assets in the test environment).
> [RW-4230][risk=low] Switch cluster resources from GCS -> https static

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
Description:
This was requested to establish a rough estimate of the effect of how often users are affect by notebook locking.
---
> [RW-4235][risk=no] Log when a user observes a held notebook lock

- api/src/main/java/org/pmiops/workbench/api/OfflineRdrExportController.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/interceptors/CloudTaskInterceptor.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
This PR will introduce a new interceptor for Cloud task. The target for cloud task (task handlers ) should have the following :
1) The swagger definition should have the 
a) tag 'cloudTask'
b) security set to [] (to avoid checking for OAuth)
2) If the queue Name is different from rdrQueue add to the interceptor header list. This header is automatically added by the google cloud.
- [X ] This PR meets the Acceptance Criteria in the JIRA story
- [ X] The JIRA story has been moved to Dev Review
- [ X] This PR includes appropriate unit tests
- [ X] I have run and tested this change locally
> [RW-4091][RISK=MODERATE]Interceptor for Cloud task

- api/db/changelog/db.changelog-120-update-demographics.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurvey.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorTest.kt
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
- ui/src/app/pages/login/account-creation/account-creation-options.tsx
- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Description:
This adds `professionalUrl` to our DB, and changes gender identity and sexual orientation options to free text with a boolean identifier, per new caps requirements. This does not address the styling on the account creation survey page, which will be done in a follow up task. 
---
> [RW-4279][RW-4293][Risk=low] Add db fields for demographic survey

- ui/src/app/pages/workspace/research-purpose.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
The issue in RW-4311 was related to the checkbox behavior change from #2973, where checkboxes began to hold their own 'checked' state by default, using the 'checked' prop only for setting the initial value.
The solution here was to construct the initial Workspace state in the component constructor rather than in the componenDidMount method. This also aligns better with React's guidance; from [the docs](https://reactjs.org/docs/react-component.html#componentdidmount): "You may call setState() immediately in componentDidMount() ... Use this pattern with caution because it often causes performance issues. In most cases, you should be able to assign the initial state in the constructor() instead."
IMO the various pieces of logic are also clearer when bundled into a createInitialWorkspaceState …
> [RW-4311][risk=no] Fix checkbox issues in workspace form

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
- api/src/main/resources/client_api.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/DbConcept.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/DbConceptRelationship.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/DbConceptSynonym.java
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- ui/src/app/pages/data/concept/survey-details.tsx
- ui/src/environments/test-env-base.ts
- ui/src/testing/stubs/concepts-api-stub.ts
- Added the ability to create/edit/delete PM and Surveys inside the Concept Set Builder.
- Updated/added test coverage for each new bucket type
- Updated routing after deleting concept sets
- In test/staging/stable/prod PM will be behind feature flag because it is causing problems in Data Set Builder
> [RW-4247][risk=no] Reworking Concept Set Builder to include PM and Surveys

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
The request body for cloud task was set to Object just so RDR is unblocked and we can start export data. This PR is replacing generic Object to Array of Long
---
- [ X] This PR meets the Acceptance Criteria in the JIRA story
- [ X] The JIRA story has been moved to Dev Review
- [ X] I have run and tested this change locally
- [ X] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
> [RW-4091][RISK=NO]Change the return object for cloud task to array of long

- api/config/config_local.json
- api/config/config_test.json
Billing lockout needs https://github.com/all-of-us/workbench/pull/3040 to merge before its functional.
Disabling the feature for now.
---
> [risk=no] Disable billing lockout in local and test

- ui/src/app/pages/data/data-set/dataset-page.tsx
Description:
- Use hyphens to break words that overlap the table cells
Before:
After:
- Also added title attributes to column headers so the full text will show on hover
---
> [RW-3910][risk=no] Set word breaks in dataset preview table columns

- api/libproject/devstart.rb
- api/src/main/resources/notebooks.yaml
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
Usage:
```
./project.rb list-clusters --project all-of-us-rw-prod
... # find cluster of interest
./project.rb describe-cluster --id aou-rw-xxxxxx/all-of-us-xx
```
Prints command line instructions for inspecting the logs directory for the cluster.
Sample output: https://pmi-engteam.slack.com/files/U5KGPEEPK/FSS4UKYF5/describe-cluster_output
> [RW-4322][risk=low] Implement describe-cluster debug tool

- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/monitoring/attachments/MetricLabel.java
- api/src/main/java/org/pmiops/workbench/monitoring/views/GaugeMetric.java
The closest API I could find for this information was the [Users List API](https://developers.google.com/admin-sdk/directory/v1/reference/users/list). There's no count or summary I could find, so I'm hitting it with the max page size of 500 and then fetching more. I might be able to reduce the size of each user returned using the fields attribute.
I put a label on the gauge for the domain name. This is both a reminder and for future-proofness, in case we wanted to have multiple domains per environment or somehow look at multiple environments in the same chart someday. We don't expect either of those to happen yet.
Here's a screen shot with it in action.
[Stackdriver dashboard link](https://console.cloud.google.com/monitoring/dashboards/custom/18329516758933998444?project=all-of-us-workbenc …
> [RW-4314][risk=no] Gauge metric for GSuite Domain Account Count

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- ui/src/app/pages/workspace/workspace-edit.tsx
This simplifies the flow for the new Zendesk ticket integration. In the future, we might add this capability back in.
> [RW-4132][risk=low] Disallow editing of workspace "request review"

- ui/src/app/components/breadcrumb.tsx
- ui/src/app/components/status-alert-banner.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/app/pages/workspace/invalid-billing-banner.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
This adds a banner for users viewing a workspace with inactive billing.
The banner
I had to refactor the existing status banner a bit to reuse it. Some styling changes were made along the way.
Another big change was using `ReactDOM.createPortal` to allow the banner to be rendered from any component. Previously it would render to the top right corner of its parent component so it wouldn't go to the correct position unless the parent fit the entire page.
TIL
- ReactDOM.createPortal allow you to render components anywhere in the DOM. https://reactjs.org/docs/portals.html
- Our method of passing in props through `withCurrentWorkspace` `withUserProfile` etc, pass in the props AFTER the component has already been constructed and rendered. Thus, any state that relies on it must be checked in …
> [RW-4284][risk=no] Inactive Billing status banner

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
This PR contains a bit of prep work and cleanup that's loosely related to the Terms of Service signature UI:
1) Remove our redundant environment.enableAccountPages flag, and instead propagate the WorkbenchConfig.enableNewAccountCreation flag and use that. This will help reduce bugs as we roll out the new-account functionality in the backend & UI.
2) Remove the unused enableHomepageRestyle flag. It's set to true in all environments, so is overdue for removal.
> [RW-4159][risk=no] UI environment flags & feature flag cleanup

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/moodle.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Moodle sends us epochs in seconds and everything we use for time in Java thinks everything should be in milliseconds.
> [risk=no][RW-2957] seconds/millis issue

- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
Fixes a bug in the new dataset modal where the code preview button is on the wrong line.
---
> [risk=no] Fix code preview UI bug in new dataset modal

- .circleci/config.yml
I'm not sure if we're just using more virtual memory now, or if our machine size was somehow reduced with the CircleCI plan change. 
See inline comment for explanation. Also https://circleci.com/docs/2.0/java-oom/
> [risk=no] Reduce api-local-test memory limit

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
Display concept name instead of criteria question in survey results
- Move dao call from CBCriteriaDao to ConceptDao
- Change queries to use mysql rank that allows for same ordering as criteria table
- Change queries to be native since JPQL doesn't handle rank functions
> [RW-4369][risk=no] Display concept name instead of criteria question in survey results

- ui/src/app/pages/analysis/notebook-redirect.tsx
All the `<i>` tags were treated as flex items and getting `display: block` applied to them. Fixed by wrapping the entire text block in a `div` so that becomes the flex item and the `<i>` tags get their usual `display: inline` applied.
@gjuggler FYI
> [risk=no] Fix text display on notebook loading page

- api/build.gradle
- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/zendesk/README.md
- api/src/main/java/org/pmiops/workbench/zendesk/ZendeskConfig.java
- api/src/main/java/org/pmiops/workbench/zendesk/ZendeskRequests.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/zendesk/ZendeskRequestsTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- Note: this pulls in a new 3p Java library (ZD unofficial client library)
- Integrates using an unauthenticated Zendesk client via client lib. See Readme.md for details.
- On create/clone, if review is requested files a Zendesk request
- Zendesk request ticket contains both formatted workspace description (similar to edit/about pages) as well as a raw JSON view of the research purpose, in the event that we fail to update the ticket formatter when making changes to the workspace model.
Manually tested this in the sandbox env.
Future work:
- The Zendesk comment API supports HTML comments. A future version could integrate an HTML templating library to render a more readable view.
- A path for setting up an authenticated client is described in the readme, if we wanted to do subsequent ticket …
> [RW-4132][risk=moderate] Integrate with Zendesk for workspace review requests

- api/src/main/java/org/pmiops/workbench/db/model/DbUserDataUseAgreement.java
I was taking a look at RW-3881 (API failure when updating a user profile), and this was the first error I ran into. There may be more reasons it's failing, but this one looks like a super simple fix.
I decided to update the entity annotation rather than write a Liquibase migration to rename the column, to avoid adding a Liquibase change that might affect our rollback-ability in next week's release.
---
> [RW-3881][risk=no] Fix small typo in DbUserDataUseAgreement annotation.

- api/docker-compose.yaml
- ui/docker-compose.yaml
This should prevent accepting connections from outside localhost. Tested locally manually.
> [risk=no] Bind docker ports to localhost

- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/tables.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/notebook-redirect.tsx
- ui/src/app/pages/homepage/recent-workspaces.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
I ran into this while working through https://github.com/all-of-us/workbench/pull/2973. React items that show up in a list need to have unique keys, otherwise React will complain. I'm not sure if it has any functional impact, but the console warnings went away once I added these keys.
---
- [n/a] This PR includes appropriate unit tests
- [yes] I have run and tested this change locally
> [no ticket][risk=no] Add keys for flex row entries to suppress React errors

- ui/src/app/components/help-sidebar.tsx
Issue comes from having the sidebar open by default when entering a workspace, but didn't take into account navigating from a page inside a workspace that doesn't contain the sidebar (only notebooks AFAIK)
---
> [RW-4410][risk=no] Fix help sidebar state when navigating from a notebook

- ui/src/app/components/side-nav.tsx
Straightforward. Note, we should standardize our usage of icons soon. Switching in between clarity and fontawesome is getting confusing and also makes refactoring harder.
---
> [RW-3803][risk=no] Flatten side bar items for User Support

- ui/src/app/pages/signed-in/component.ts
Test this out @ https://calbach-dot-all-of-us-workbench-test.appspot.com/
-> currently configured for 30s modal, 60s timeout.
Two additions in combination should cover the known issues with setTimeout:
- Before updating the last active timestamp - check that they haven't already surpassed the time limit. This covers the case where a user sleeps their machine, comes back, and resumes activity immediately.
- Every 1m, reset the `setTimeouts()` to account for the actual remaining time according to LocalStorage. This covers the case where a user wakes up their machine and then doesn't interact with the tab again (they could still view the content).
Manually verified by sleeping my laptop and reopening the site after 1m.
> [RW-3554][risk=low] Shore up inactivity detection logic

- api/config/config_local.json
- api/config/config_test.json
Comments are not a thing in JSON. Certain JSON parsing libraries, including `jq` CLI will choke on this.
> [risk=no] rm invalid JSON comments

- ui/package.json
- ui/src/app/components/modals.tsx
- ui/yarn.lock
Description:
`@types/color` has a bug in version 3.0.1 if you use a version of Typescript older than 3.7, which we do: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41612.
I also saw an error along the lines of "cannot convert Color to string" so I updated that line as well.
---
> [risk=no] Fix to allow compilation of the UI after wiping node_modules and yarn.lock

- ui/src/app/pages/workspace/workspace-wrapper/component.ts
The help tips sidebar closes when the route changes, but on route changes caused by navigating between participants in cohort review, we want it so stay open if it's already open so the annotations UI is still available.
---
> [RW-4422][risk=no] Keep sidebar from closing when navigating participants in review

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java
Description:
This adds cdr env variable support, moves us to bigrquery, and removes the named parameters section. This has been tested locally with cohorts with both list variables, variables with single values, and queries with no named parameters, in both R and Python
---
> [RW-3790][RW-3587][Risk=low] Remove named params and move to bigrquery

- api/build.gradle
- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/BaseControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/login/sign-in.tsx
In prep for launch, this PR adds a new config variable requireVerificationKey which controls the frontend & backend components which require a verification key to be input by users. When this is off, the frontend will not collect an invitation key & the backend will not verify it.
A few notes:
**Jira ticket**
I'm attaching this to the broader "enable feature flag for registration pages" issue, since it's thematically related and this is one more step on the way towards enabling that flag.
**Environment var vs. feature flag**
I'm modeling this flag as an "access" config variable rather than a feature flag, since we may wish to control access with an invitation key in lower environments (such as preprod) even once this is opened up in prod. Feature flags should have an expectation that they …
> [RW-3685][risk=low] Add a config variable controlling invitation key verification

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
As this reaches each environment with the next release:
- Will run https://github.com/all-of-us/workbench-devops/pull/12
- Will run SQL to manually billing-unlock all workspaces
> [RW-4144][risk=no] Move the new VUMC billing account for new projects and for spending checks

- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/utils/index.tsx
Key changes:
- Consolidate domain/value set loading through one pathway
- The original trigger is setting `state.selectedDomains`
- Subsequent loading and autoselection of domain values is done in `componentDidUpdate`
- Add a unified loading/lookup layer for domain -> valueSets
- Switched prepackaged concept set representation from `boolean` -> `Set<demograpics|surveys>`
Demo @ http://calbach-dot-all-of-us-workbench-test.appspot.com/
Also identified several areas for further simplification here.
> [RW-4303][risk=no] Refactor datasets page and fix race conditions

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
Creates a local storage item to indicate whether the sidebar is open or closed. This way, the sidebar is open automatically only the first time a user logs in and enters a workspace. If the user re-enters a workspace or refreshes the page, it will get the sidebar state from local storage.
Also added a box-shadow in the sidebar so it's clearer that there is content being covered up.
---
> [RW-4437][risk=no] Track sidebar state in local storage

- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
This was accidentally left in https://github.com/all-of-us/workbench/pull/3054 after making a design change mid-PR-review.
> [no ticket][risk=no] Remove termsOfServiceRows from DbUser model

- ui/src/app/pages/data/data-set/dataset-page.tsx
Description:
This changes the error message for the dataset builder preview. It also adds a width to the message, otherwise it spreads across the entire page. 
---
> [RW-3895][Risk=no] Change error message for dataset builder preview

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
- common-api/src/main/java/org/pmiops/workbench/db/model/CommonStorageEnums.java
- common-api/src/test/java/org/pmiops/workbench/db/model/CommonStorageEnumsTest.java
Description:
1. About half of `ProfileController.updateProfile()` deals with old-style Institutional Affiliations, so I moved that into its own method.
2. The shorter version of `UserService.createUser()` exists solely for AuthInterceptor's use, and the parameter list now matches what it knows about.
3. CommonStorageEnumsTest did not comprehensively check for missing map values like StorageEnumsTest does.
4. project.rb connect-to-db now starts the local DB if it's not running
---
> [risk=no] A grab bag of small refactorings while doing other work

- ui/src/app/pages/data/concept/concept-homepage.tsx
Survey name was not getting passed to the tab count call when a survey was selected.
> [risk=no] Fix survey count request

- api/config/config_local.json
- api/src/main/java/org/pmiops/workbench/api/UserController.java
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
Note - I wanted to add a tooltip to the disabled options but it's difficult to do since we're using a library to handle our dropdowns. I think we should look into a more flexible library or roll our own. Even finding out if they support `disabled` was a struggle since it's not documented anywhere. I had to read their source to find out.
---
> [risk=no][RW-4384] Disable closed billing accounts in dropdown

- README.md
- ui/yarn.lock
Description:
`yarn install` failed on my Mac after upgrading to Node 12.
Problem and Solution:
The transitive dependency `fsevents` added Node 12 compatibility in version 1.2.9, and we call for an earlier version in yarn.lock.  I edited `yarn.lock` to remove the entry for the older fsevents and ran `yarn install` to upgrade.  That resolved the issue.
Previous attempts:
TIL about the "resolutions" section of packages.json which helps force version numbers of transitive dependencies.  Ensuring that fsevents would not attempt to install a version before 1.2.8 resolved my problem.   However!  resolutions has an unfortunate bug: it can override the "optional" flag in some cases.  Since fsevents is a Mac-only optional build dependency, this had the side effect of preventing builds on Linux, …
> [risk=no][RW-4238]Update yarn.lock for Node 12 compatibility on Mac

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Description:
This removes the limit for our generated SQL queries. I tested to make sure large queries fail loudly with both Python and R. R failed loudly, Python failed not as loudly, but its hard to tell if it is because my computer went to sleep or there were memory problems. I did successfully download about 43 million rows though. My test query was `SELECT * FROM condition_occurrence`
---
> [RW-4450][Risk=no] Remove limit on SQL query in notebooks

- api/src/main/resources/cb_search_api.yaml
- api/src/main/resources/workbench.yaml
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.ts
- ui/src/app/cohort-search/utils.ts
- ui/src/app/utils/resourceActions.ts
Add an "Edit criteria name" option to the search item snowman menu to set a custom item name. Uses the `RenameModal` component used for renaming other resources.
---
> [RW-3994][risk=no] CB - Add rename option to search items
