all-of-us/workbench

- api/src/main/resources/cb_search_api.yaml
> [risk=no] update search parameter

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
Convert all fields with type as timestamp to format yyyy/MM/dd HH:mm:ss
and then sort the values as per input of data set values
> [RISK:NONE] Format preview value for Timestamp

- api/db/changelog/db.changelog-77-data-set-last-modified.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DataSet.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/app-routing.module.ts
- ui/src/app/components/buttons.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/styles/colors.ts
- ui/src/app/utils/resourceActions.ts
- ui/src/app/utils/resourceActionsReact.ts
- ui/src/app/views/concept-table/component.tsx
- ui/src/app/views/data-page/component.spec.tsx
- ui/src/app/views/data-page/component.tsx
- ui/src/app/views/dataset-page/component.spec.tsx
- ui/src/app/views/dataset-page/component.tsx
- ui/src/app/views/resource-card/component.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
> [RW-2537][Risk=low] Working getDataSet, deleteDataSet, listDataSet and data set edit page

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
> [RW-2537][Risk=no] Fix null pointer

- ui/src/app/views/dataset-page/component.tsx
> [No Ticket][Risk=no] Fix small style things

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/settings/component.spec.tsx
- ui/src/app/views/settings/component.tsx
Note: this does not make any changes to cluster creation or status checking - only the API signature.  ~So: the parameter must still be equal to the free tier billing project!~
Also some small opportunistic refactoring.
> [RW-2476][risk=no] Add billing project name param to listClusters

- api/config/config_local.json
Currently NPEs on workspace creation
> [risk=no] Turn off buffer for local development

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Verified locally that without this after creating a new account that I (as the workspace owner), can execute BigQuery jobs in my own project.
@gjuggler FYI
> [RW-2630][risk=low] Stop redundant granting of BigQuery roles

- api/cluster-resources/playground-extension.js
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
I forgot about this during code review. Looks like I had a comment in one direction but not the other to keep these in sync.
> [risk=no] Update playground extension prefix, update comment

- api/cluster-resources/playground-extension.js
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/BaseQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCriteria.java
small change to query builder.
> [risk=no] small change to query builder.

- ui/src/app/app.module.ts
- ui/src/app/components/resources.tsx
- ui/src/app/views/dataset-page/component.tsx
- ui/src/app/views/resource-card/component.tsx
- ui/src/app/views/workspace/component.spec.ts
Removes menus on the data set page per Lou and Greg's recommendations, and then refactor and tear things out.
> [No Ticket][Risk=no] Remove menu from data set list and refactor to remove code

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
removing code from synonyms column
adding source to standard mapping info to relationship table
changed rank1 in synonyms column to be domain specific
> [RW-2571][risk=no] Modifications to the criteria table build script

- api/src/main/java/org/pmiops/workbench/cohortbuilder/BaseQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
small change to query builders
> [risk=no] small change to query builders

- api/src/main/java/org/pmiops/workbench/cohortbuilder/BaseQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
> [risk=no] cleanup in query builder

- ui/src/app/components/resources.tsx
- ui/src/app/views/export-data-set-modal/component.spec.tsx
- ui/src/app/views/export-data-set-modal/component.tsx
- ui/src/app/views/resource-card/component.tsx
> [RW-2646][Risk=no] Srubenst/export to notebook menu item

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- Follow-up cleanup from https://github.com/all-of-us/workbench/pull/2141
- Remove unused JiraConfig
> [RW-2658][risk=no] Fully switch to cluster resource bucket config, trim unused config values

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
> [RW-2552][risk=no] log admin user bypass action

- ui/src/app/views/login/component.tsx
> [RW-2684][Risk=no] Fisma wording changes

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchEnvironment.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- common-api/src/test/java/org/pmiops/workbench/config/WorkbenchConfigTest.java
- ui/src/app/views/admin-user-bypass/component.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Merging only after we bring to the security call and get approval from the security council.
> [DO NOT MERGE] [RW-2667][Risk=high] Add development environments only self bypass

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
> [RW-2688][Risk=no] Srubenst/fix data preview error handling

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
adding api call for source to standard mappings per conceptId
> [RW-2557][risk=no] adding api call for source to standard mappings per conceptId

- ui/src/app/views/registration-dashboard/component.tsx
> [RW-2631][risk=no] Include ?authuser on Google security URL

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/components/card.tsx
- ui/src/app/views/cohort-actions.tsx
- ui/src/app/views/concept-add-modal.tsx
- ui/src/app/views/concept-homepage.spec.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/concept-set-actions.tsx
- ui/src/app/views/concept-set-actions/concept-set-actions.component.tsx
- ui/src/app/views/workspace-nav-bar.spec.tsx
- ui/src/app/views/workspace-nav-bar.tsx
- ui/src/app/views/workspace-wrapper/component.spec.ts
- ui/src/app/views/workspace/component.spec.ts
> [RW-2661][Risk=no] Srubenst/concept set actions

- ui/intellij-typescript-style.xml
The style file is WIP. If you find some setting that works better to appease our linter, please export the change and submit a pull request.
> [risk=no] add intellij typescript style file

- ui/src/app/views/workspace-edit.tsx
> [RW-2596][risk=no] stigmatization table

- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/concept-set-details.tsx
per the react conversion, most of the permissions things were fixed, however I 
* changed the styling of ellipses menu to not disable the whole menu but rather show tooltips for disabled actions
* disabled adding concepts to sets if user is a reader, plus added a tooltip
> [P2][RW-2610][risk=no] fix reader permissions on concept set

- ui/src/app/views/workspace-share.spec.tsx
- ui/src/app/views/workspace-share.tsx
- ui/src/app/views/workspace-wrapper/component.html
- ui/src/app/views/workspace-wrapper/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
> [RW-2621][Risk=no] Srubenst/workspace share side panel update

- ui/src/app/app.module.ts
- ui/src/app/views/cohort-list.tsx
- ui/src/app/views/concept-set-list.tsx
- ui/src/app/views/data-page.tsx
- ui/src/app/views/notebook-list.tsx
- ui/src/app/views/recent-work.tsx
- ui/src/app/views/resource-card.spec.tsx
- ui/src/app/views/resource-card.tsx
- ui/src/app/views/workspace/component.spec.ts
> [RW-2612][Risk=no] Fix duplicate

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- Include user ID in cluster names for uniqueness, if useBillingProjectBuffer is on
- Added test
- Refactored test to take advantage of improved provider stubbing approach
Alternative considered:
Generate a random ID for the cluster name. Rejected for now, as it would be more challenging to identify the right cluster via `listClusters` - we would need to filter down by owner (and there might be multiple matches). A 1:1 mapping is simplest for now.
> [RW-2735][risk=low] Unique cluster names + test refactors

- README.md
> [risk=no] Note linting and Intellij setup in README

- ui/src/app/views/workspace/component.html
> [risk=no] Fix billing project reset button check

- ui/src/app/views/workspace-nav-bar.tsx
> [risk=no] Fix accidental duplicate menu text

- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
We need to keep opening notebooks in the free tier billing project until the bp buffer feature is enabled.
> [risk=no][RW-2760] Continue using freeTierBillingProjectName for now

- ui/src/app/views/workspace-edit.tsx
> [RW-2765][Risk=no] Remove extra !

- api/db-cdr/generate-cdr/bq-schemas/search_all_domains.json
- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
- ui/src/app/cohort-search/list-search/list-search.component.spec.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/list-tree/list-tree.component.spec.ts
Build blood pressure data into single row in search all events table
> [RW-2749][risk=no] Build blood pressure data into single row in search all events table

- api/db/changelog/db.changelog-81-add-billing_migration_status-workspace.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Add an enum to workspace to track migration status of 1PPW
> [risk=no][RW-2607] Add billing migration status to Workspace

- api/src/main/java/org/pmiops/workbench/db/model/User.java
> [RW-2769][risk=no] rm unused eager fetch on user model

- ui/src/app/utils/index.tsx
- ui/src/app/views/workspace-list.spec.tsx
- ui/src/app/views/workspace-list.tsx
> [RW-2764][Risk=no] Fix share workspace

- ui/README.md
- ui/src/app/app.module.ts
- ui/src/app/components/tables.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/views/workspace-about.tsx
- ui/src/app/views/workspace-edit.tsx
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
> [RW-2594][risk=no] New research purpose on ws About page

- api/src/main/java/org/pmiops/workbench/db/model/User.java
- ui/src/app/app.module.ts
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/components/tables.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/views/workspace-about.tsx
- ui/src/app/views/workspace-edit.tsx
- ui/src/app/views/workspace-list.spec.tsx
- ui/src/app/views/workspace-list.tsx
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
- ui/yarn.lock
Hides input fields while loading to prevent incorrect cohort definitions
> [RW-2766][risk=no] Add loading spinner to age/deceased wizard

- api/build.gradle
- common-api/build.gradle
> [RW-2789][risk=no] Ignore generated/build files for spotless

- api/db-cdr/changelog-schema/db.changelog-30.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fix CBCriteriaDao call for icd9/icd10 lookups
> [RW-2790][risk=no] fix CBCriteriaDao call for icd9/icd10 lookups

- api/cluster-resources/README.md
- api/cluster-resources/setup_notebook_cluster.sh
https://precisionmedicineinitiative.atlassian.net/browse/RW-2748
This is a workaround while Leo investigates and fixes in the base docker image: https://broadworkbench.atlassian.net/browse/IA-1002
> [RW-2748][risk=no] Include gfortran on AoU clusters for R support

- api/db/changelog/db.changelog-82-add-cascade-delete-admin-actions-after-user-delete.xml
- api/db/changelog/db.changelog-master.xml
Have confirmed that the cascade works as wanted.
> [Risk=moderate][No Ticket] Add cascade on user delete to admin history

- api/cluster-resources/setup_notebook_cluster.sh
- This gets installed within the Jupyter docker image on Leo; I was not able to verify whether this egress control affects JupyterLab as well (it's not currently functional)
- Depends on https://broadworkbench.atlassian.net/browse/IA-1013 which is currently deployed in dev only. This shouldn't need sequencing, as failures in this script do not fail cluster startup (logged only).
- Tested and verified locally with a deployed version of the script:
> [RW-2254][risk=no] Install wondershaper on AoU clusters

- api/build.gradle
- api/src/integration/java/org/pmiops/workbench/IntegrationTestConfig.java
- api/src/integration/java/org/pmiops/workbench/google/CloudResourceManagerServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/auth/Constants.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerService.java
- api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/cron.xml
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/CommandLineToolConfig.java
Please take an initial look. This is probably not ready to merge, but want some eyes on it. Next step is setting up the cron.
> [RW-2062] [risk=no] rubenst/attempt at cross org reporting

- api/db/changelog/db.changelog-83-other-population.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceMapper.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace-about.tsx
- ui/src/app/views/workspace-edit.tsx
Also now shows it in the "About" page
> [RW-2784][P3] save research purpose "other" population 

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
I totally forgot these... mind taking a quick look?
> [RW-2062][Risk=no] Srubenst/fix org ids

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- ui/src/app/styles/colors.ts
- ui/src/app/views/concept-homepage.spec.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/testing/stubs/concepts-api-stub.ts
> [RW-2494][RISK=NO] Include Surveys in Concept Set Selector - Home Page

- ui/src/app/utils/zendesk.ts
- ui/src/app/views/quick-tour-modal.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/environments/environment-type.ts
- ui/src/index.html
Our branding is "Research**er** Workbench" so we should use that in all cases.  Good catch @dmohs
> [risk=no][no ticket]Replace all instances of "Research Workbench"

- ui/src/app/app-routing.module.ts
- ui/src/app/views/app/component.ts
> [risk=low][RW-2737]Set Notebook page title to notebook name

- api/config/config_local.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/profile-page.spec.tsx
- ui/src/app/views/profile-page.tsx
> [RW-2771][Risk=no] Disable DUA and add null completion time handler

- api/db/changelog/db.changelog-84-add-last_status_changed_time.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/billing/BillingController.java
- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/cron.xml
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
"Error" Handling.
All its really doing is finding projects that have been stuck in the temporary states for too long and set them to ERROR.
The timeout for CREATING is 60m and ASSIGNING is 10m.
> [risk=no][RW-2474] Billing Project buffer error handling

- ui/src/app/views/notebook-redirect/component.html
> [RW-2825][risk=no] Update cluster start estimate to be more accurate

- api/src/main/webapp/WEB-INF/cron.xml
Per https://broadworkbench.atlassian.net/browse/CA-253
> [No Ticket][Risk=no] Add back cron job for 2sv

- ui/src/app/views/cohort-actions.tsx
- ui/src/app/views/concept-set-actions.tsx
> [RW-2815][Risk=no] Fix styling on action cards

- api/db-cdr/generate-cdr/bq-schemas/search_all_domains.json
- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
changing scripts to add value_source_concept_id for PPI data.
> [RW-2787][risk=no] changing scripts to add value_source_concept_id for PPI data

- api/config/config_local.json
- api/config/config_test.json
Blocked on https://github.com/all-of-us/workbench/pull/2225
> [RW-2659][risk=low] Enable project billing buffer in local/test

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
> [RW-2688][Risk=no] Fix bad-request handling

- ui/src/app/components/spinners.tsx
- ui/src/app/views/workspace-edit.tsx
> [RW-2813][Risk=no] Make spinner lower down and have overlay

- ui/src/app/views/registration-dashboard.tsx
See InVision mocks at https://projects.invisionapp.com/d/main?origin=v7#/console/12820961/356642855/preview
> [no ticket][risk=no]Fix ERA Commons registration text

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
criteria table generation script
- fixed icd10 parent count issue
- changed PPI answers to look at new column
- fixed PM count issue
- fixed bug that was showing zero count visits
- added code to bring in other standard condition vocabs
- fixed bug in measurement snomed
updated review flat table generation script to use new criteria table
updated dataset builder flat table generation script to use new criteria table
> [RW-2767][risk=no] update criteria table generation script

- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
Adds error messaging to the participant table, participant detail table and annotations in cohort review.
Participant table api call fail (same as participant detail table):
Participant table no results (same as participant detail table):
Annotation save failure (goes away after 5 seconds):
> [RW-2488][risk=no] Add error messaging in cohort review

- ui/src/app/views/workspace/component.ts
> [RW-2904][P0][risk=no] reload user roles after share

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/resource-card.tsx
Delete cohort/concept used in a dataset : should see the following warning message
> [RW-2843][RISK=LOW]Behavior when a cohort/concept set referenced in a Dataset is deleted

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/dataset-page.tsx
- ui/src/app/views/new-dataset-modal.spec.tsx
- ui/src/app/views/new-dataset-modal.tsx
Default update dataset modal 
Button text for default update 
Button text if data set is updated
> [RW-2844][RISK=NO]Make export to Notebooks selected by default when saving Dataset

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
Update the testing pattern for UserControllerTest as well.
> [RW-2894][risk=no] Require registration for user search

- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/workspace-nav-bar.spec.tsx
- ui/src/app/views/workspace-nav-bar.tsx
> [RW-2333][Risk=no] Fix tabs for Bedford release

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
> [RW-2688][Risk=low] Srubenst/fix union issue

- api/db/changelog/db.changelog-86-drop-tos.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/testing/stubs/profile-service-stub.ts
- TOS is subsumed by DUA, remove all references
- Demo survey is not implemented, return this HTTP status for now
> [RW-2897][risk=no] Clean up profile endpoint bit-rot

- api/config/config_local.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.html
- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.ts
- ui/src/app/cohort-search/list-modal/list-modal.component.ts
- ui/src/app/cohort-search/list-modifier-page/list-modifier-page.component.tsx
- ui/src/app/cohort-search/list-overview/list-overview.component.html
- ui/src/app/cohort-search/list-overview/list-overview.component.spec.ts
- ui/src/app/cohort-search/list-overview/list-overview.component.ts
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.html
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.spec.ts
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.ts
- ui/src/app/cohort-search/list-search-group-list/list-search-group-list.component.html
- ui/src/app/cohort-search/list-search-group-list/list-search-group-list.component.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.html
- ui/src/app/cohort-search/list-search-group/list-search-group.component.spec.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.ts
- ui/src/app/cohort-search/utils.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.test.ts
Makes new cohort builder UI work with updated api calls. Will need to enable local feature flags to test.
This also enables list search in test environment to start user testing.
**Temporal does not work on this branch
> [RW-2682][risk=no] Update CB list search with new api calls

- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtil.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.html
- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.ts
- ui/src/app/cohort-search/list-modal/list-modal.component.ts
- ui/src/app/cohort-search/list-modifier-page/list-modifier-page.component.tsx
- ui/src/app/cohort-search/list-overview/list-overview.component.html
- ui/src/app/cohort-search/list-overview/list-overview.component.spec.ts
- ui/src/app/cohort-search/list-overview/list-overview.component.ts
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.html
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.spec.ts
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.ts
- ui/src/app/cohort-search/list-search-group-list/list-search-group-list.component.html
- ui/src/app/cohort-search/list-search-group-list/list-search-group-list.component.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.html
- ui/src/app/cohort-search/list-search-group/list-search-group.component.spec.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.ts
- ui/src/app/cohort-search/utils.ts
- ui/src/environments/environment.test.ts
org.pmiops.workbench.exceptions.ExceptionAdvice serverError: java.lang.IllegalArgumentException (ExceptionAdvice.java:54)
java.lang.IllegalArgumentException: Multiple entries with same key: class SearchParameter {
parameterId: param6
name: Cholera
value: 001
domain: Any
type: ICD9
subtype: CM
group: true
ancestorData: false
standard: true
conceptId: null
attributes: []
}=[44835564, 44823922, 44829696, 44827441] and class SearchParameter {
parameterId: param6
name: Cholera
value: 001
domain: Any
type: ICD9
subtype: CM
group: true
ancestorData: false
standard: true
conceptId: null
attributes: []
}=[44835564, 44823922, 44829696, 44827441]
at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.ja …
> [RW-2922][risk=no] fixing error.

- api/src/main/resources/cb_search_api.yaml
> [RW-2934][risk=no] adding term as query param.

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
> [risk=no] Fix gsuite integration test

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
> [RW-2845][Risk=no] Srubenst/mult cells per domain

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/profile-page.spec.tsx
- ui/src/app/views/profile-page.tsx
> [RW-2771][Risk=no] Disable showing empty info for eRA commons

- ui/src/app/views/dataset-page.tsx
> [RW-2848][Risk=no] Srubenst/select all wording

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
adding fixes for drugs and codes search.
> [RW-2944][risk=no] adding fixes for drugs and codes search.

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/cohort-search/list-demographics/list-demographics.component.ts
- ui/src/app/cohort-search/list-search-group-list/list-search-group-list.component.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.html
- ui/src/app/cohort-search/list-search-group/list-search-group.component.ts
- ui/src/environments/environment.local.ts
Fixes two demographics bugs:
- RW-2939: Prevent duplicate selections in race/gender/ethnicity wizards
- RW-2949: Fix submenu in criteria drop downs so all open on hover instead of click
> [RW-2939][RW-2949][risk=no] CB Demographics bugs

- README.md
Updated the link to be generalized to UI and API and moved it to the setup section.
> [No Ticket][Risk=no] update-intellij-setup

- .gitallowed
- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/notebooks.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
There are several known Welder bugs - this cannot be enabled yet. The flow is approximately correct though.
> [RW-2710][risk=low] Add flag-disabled Welder support

- ui/src/app/views/survey-details.tsx
> [No Ticket][Risk=no] Fix master colors

- api/db/changelog/db.changelog-master.xml
adding file extension to db.changelog-master.xml
> [risk=no] fixing liquibase problem.

- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtil.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtilTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fix for surveys concept id lookup
> [risk=no] fix for surveys concept id lookup

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fixing endpoint for ingredients lookup.
> [risk=no] fixing endpoint for ingredients lookup.

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/exceptions/GatewayTimeoutException.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
> [RW-2688][Risk=no] Srubenst/fix timeouts

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
> [risk=no] fixing ingredients

- README.md
- api/db/load_vars.sh
Making the script compatible to be used by both bash and zsh, which Apple is moving to.
> [RW-2980][risk=no] zsh compatible api setup

- ui/src/app/views/workspace-about.tsx
- ui/src/app/views/workspace-edit.tsx
> [RW-2865][risk=no] about page styling

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
> [RW-2846][Risk=no] Add head(5) to notebook export.

- ui/src/app/components/buttons.tsx
- ui/src/app/components/spinners.tsx
- ui/src/app/icons/edit.tsx
- ui/src/app/icons/icon.tsx
- ui/src/app/icons/reminder.tsx
- ui/src/app/icons/scroll.tsx
- ui/src/app/views/breadcrumb.tsx
- ui/src/app/views/cohort-list.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/data-page.tsx
- ui/src/app/views/homepage.tsx
- ui/src/app/views/profile-page.tsx
- ui/src/app/views/recent-work.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/app/views/sign-in.tsx
- ui/src/app/views/sliding-fab.tsx
- ui/src/app/views/workspace-share.tsx
> [No Ticket][Risk=no] More styling fixes

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/cohort-search/utils.ts
- ui/src/app/components/buttons.tsx
- ui/src/app/components/spinners.tsx
- ui/src/app/icons/edit.tsx
- ui/src/app/icons/icon.tsx
- ui/src/app/icons/reminder.tsx
- ui/src/app/icons/scroll.tsx
- ui/src/app/views/breadcrumb.tsx
- ui/src/app/views/cohort-list.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/data-page.tsx
- ui/src/app/views/homepage.tsx
- ui/src/app/views/profile-page.tsx
- ui/src/app/views/recent-work.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/app/views/sign-in.tsx
- ui/src/app/views/sliding-fab.tsx
- ui/src/app/views/workspace-share.tsx
- Show codes for all conditions, procedures and measurements items
- Prevent empty values for optional properties on search parameters
> [RW-2958][risk=no] Update codes in tooltip for search group items

- README.md
- api/db/load_vars.sh
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/utils.ts
- ui/src/app/components/buttons.tsx
- ui/src/app/components/spinners.tsx
- ui/src/app/icons/edit.tsx
- ui/src/app/icons/icon.tsx
- ui/src/app/icons/reminder.tsx
- ui/src/app/icons/scroll.tsx
- ui/src/app/styles/colors.ts
- ui/src/app/views/breadcrumb.tsx
- ui/src/app/views/cohort-list.tsx
- ui/src/app/views/concept-homepage.tsx
- ui/src/app/views/data-page.tsx
- ui/src/app/views/homepage.tsx
- ui/src/app/views/profile-page.tsx
- ui/src/app/views/recent-work.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/app/views/sign-in.tsx
- ui/src/app/views/sliding-fab.tsx
- ui/src/app/views/workspace-about.tsx
- ui/src/app/views/workspace-edit.tsx
- ui/src/app/views/workspace-share.tsx
Call api for ingredients of brands returned by list search
> [RW-2977][risk=no] Update drugs UI for CB list search

- ui/src/app/views/interactive-notebook.tsx
Passing in the url params as props the correct way so they are always available. Previously, it would pass in the props from the page being navigated FROM.
> [risk=no][RW-2706] New Notebooks page does not load on navigate

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/resource-card.tsx
Pending approval from Karthik and Lou
> [RW-2945][RISK=No]Change language when cohort/concept sets are deleted

- ui/src/app/icons/circleWithText.tsx
- ui/src/app/views/dataset-page.tsx
Ref: https://projects.invisionapp.com/share/Q2EVSLW7Y#/screens
> [RW-2850][RISK=NO] Change wordings and add numberings to “Create Dataset” page

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
> [RW-2688][Risk=low] handle no concepts in set per domain

- ui/src/app/views/admin-user-bypass.spec.tsx
- ui/src/app/views/admin-user-bypass.tsx
- ui/src/app/views/admin-user/component.spec.ts
- ui/src/app/views/homepage.spec.tsx
- ui/src/app/views/homepage.tsx
- ui/src/app/views/profile-page.tsx
- ui/src/app/views/registration-dashboard.spec.tsx
- ui/src/app/views/registration-dashboard.tsx
> [RW-2927][Risk=no] Hide DUA if not enabled in config

- api/db/changelog/db.changelog-master.xml
> [risk=no] Corrects filename reference in liquibase.

- ui/src/app/views/export-data-set-modal.tsx
- ui/src/app/views/new-dataset-modal.spec.tsx
- ui/src/app/views/new-dataset-modal.tsx
- ui/src/app/views/workspace-library.tsx
These components need more manual testing as a follow-up - our application does not use backslashes in the URL path.. Should also test on various notebook name characters, including spaces and `%`.
> [risk=no] JS test fixes, notebook URL fixes

- ui/src/app/views/workspace-edit.tsx
See ticket description for more details.
> [RW-2982] [risk=no] Fix the workspace edit CDR version select, and add Typescript safety.

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
See following log for the bug this attempts to fix: https://console.cloud.google.com/logs/viewer?project=all-of-us-workbench-test&minLogLevel=0&expandAll=false&timestamp=2019-07-05T17%3A50%3A11.587000000Z&customFacets&limitCustomFacetWidth=true&interval=NO_LIMIT&resource=gae_app%2Fmodule_id%2Fapi%2Fversion_id%2Fcircle-ci-test&logName=projects%2Fall-of-us-workbench-test%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2019-07-01T18%3A27%3A45.329697000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22api%22%0Aresource.labels.zone%3D%22us17%22%0Aresource.labels.project_id%3D%22all-of-us-workbench-test%22%0Aresource.labels.version_id%3D%22circle-ci-test%22%0Atimestamp%3D%222019-06-27T17%3A59%3A01.398156000Z%22%0AinsertId%3D%225d1504270008c2438d9a7 …
> [RW-2688][Risk=no] Srubenst/attempt to fix deadline exceeded

- ui/src/app/views/profile-page.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/environments/environment-type.ts
Steps 1-7 of RW-2905.  Step 8 will require more effort, and can be done independently.
> [risk=no][RW-2905] Text and URL updates for the user registration flow

- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- deploy/libproject/jirarelease.rb
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/list-overview/list-overview.component.html
- ui/src/app/cohort-search/list-overview/list-overview.component.ts
- ui/src/app/cohort-search/list-search-group-item/list-search-group-item.component.ts
- ui/src/app/cohort-search/list-search-group/list-search-group.component.html
- ui/src/app/cohort-search/list-search-group/list-search-group.component.ts
- ui/src/app/cohort-search/search-state.service.ts
- ui/src/app/views/export-data-set-modal.tsx
- ui/src/app/views/new-dataset-modal.spec.tsx
- ui/src/app/views/new-dataset-modal.tsx
- ui/src/app/views/profile-page.tsx
- ui/src/app/views/registration-dashboard.tsx
- ui/src/app/views/workspace-edit.tsx
- ui/src/app/views/workspace-library.tsx
- ui/src/environments/environment-type.ts
- Update group counts when temporal select or input changes
- Fix display and timing of loading spinners and error icons on cohort overview page
- Prevent duplicate api calls when updating items or editing/cloning an existing cohort
> [RW-2989][risk=no] Fix group count updates on temporal field change

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
**Do not merge**: until last week's release is reconciled.
@ericsong @gjuggler @blrubenstein FYI
> [RW-2659][risk=low] Launch 1ppw

- ui/src/app/views/workspace-edit.tsx
- ui/src/app/views/workspace-list.spec.tsx
- ui/src/app/views/workspace-list.tsx
- ui/src/app/views/workspace-nav-bar.tsx
> [RW-2798][Risk=no] Make data tab default

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
adding feature flag to DataSetServiceImpl
> [risk=no] adding feature flag to DataSetServiceImpl

- ui/src/app/views/dataset-page.tsx
> [RW-2688][Risk=no] Add error messaging to data set page

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- ui/src/app/views/dataset-page.tsx
Jira ticket describing work is here: https://precisionmedicineinitiative.atlassian.net/browse/RW-3008
moving CDR versions for Bedford release.
> [risk=low] moving CDR versions for Bedford release.

- README.md
- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtil.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/views/dataset-page.tsx
> [risk=no] fixing a few small CB bugs

- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
> [RW-2688][Risk=no] Enable Data Set Builder

- ui/src/app/views/workspace-wrapper/component.html
- ui/src/app/views/workspace-wrapper/component.spec.ts
- ui/src/app/views/workspace-wrapper/component.ts
> [RW-3041][Risk=no] Fix share modal in nav bar

- api/build.gradle
> [risk=no] Run cron emulator on appengineStart (used by dev-up)

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Will add tests and more docs, pushing up for initial review.
> [RW-3009][risk=low] Workspace OWNER grants billing project user

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
> [risk=no] fixing broken BQ test.

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- ui/src/app/cohort-search/search-group-select/search-group-select.component.spec.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.ts
turn on universal search in staging, stable and prod.
> [risk=no] turn on universal search in staging, stable and prod.

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace-edit.tsx
> Adds disease ontology search to workspace edit page

- ui/src/app/views/signed-in/component.html
> [risk=no] Fix sidebar code style issue (PR follow-up)

- api/config/config_stable.json
- api/config/config_staging.json
> [risk=no] turning off elastic.

- ui/app.yaml
- ui/src/assets/gsdv.txt
See https://precisionmedicineinitiative.atlassian.net/browse/RW-2016
> [RW-2016][risk=no] Stable domain is now verified, rm verification key

- README.md
> [No Ticket][Risk=no] Improve auth documentation for macs

- api/db-cdr/generate-cdr/make-bq-data.sh
fixing survey-module table to include correct question counts for surveys.
> [RW-3068][risk=no] fixing survey-module

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceImplTest.java
@gjuggler @jmthibault79 FYI
See code comments for known caveats here. Open to suggestions on how to better cover the `<style>` case.
> [RW-2924][risk=low] Sanitize notebook previews

- api/db/changelog/db.changelog-89-add-data-use-agreement-signed-version.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/components/buttons.tsx
- ui/src/app/components/icons.tsx
- ui/src/app/views/data-use-agreement.spec.tsx
- ui/src/app/views/data-use-agreement.tsx
- ui/src/testing/stubs/profile-api-stub.ts
DB, UI, API changes and tests for saving the DUA version that a user has signed.
> [RW-2599][risk=low] Save DUA version signed

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/cohort-search/list-search-bar/list-search-bar.component.ts
fix CB prod issue with drug trees.
> [risk=no] fix CB prod issue with drug trees.

- ui/src/app/views/interactive-notebook.tsx
> [risk=no][RW-2999]Don't hardcode readonly notebook iframe height

- ui/src/app/components/buttons.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/views/concept-set-details.tsx
- ui/src/app/views/workspace-list.spec.tsx
- ui/src/app/views/workspace-list.tsx
- ui/src/app/views/workspace-nav-bar.tsx
Re-add the icons to dropdown menus.
> [RW-2883][risk=no] re-add snowman menu icons

- ui/src/app/views/workspace-edit.tsx
> [P3][risk=no][RW-3078] switch toggle positions in research purpose

- ui/src/app/cohort-search/list-modal/list-modal.component.html
- ui/src/app/cohort-search/list-search-bar/list-search-bar.component.html
- ui/src/app/cohort-search/list-search-bar/list-search-bar.component.ts
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/list-tree/list-tree.component.css
- ui/src/app/cohort-search/list-tree/list-tree.component.html
- ui/src/app/cohort-search/list-tree/list-tree.component.ts
- Update text for brands & ingredients (RW-2967)
- Italicize 'All of Us' in drugs wizard (RW-2972)
- Move code in list search table to separate column (RW-3061)
> [RW-2967][RW-2972][RW-3061][risk=no] Text updates for Drugs wizard

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Although we're likely going to roll this out rather quickly, I opted to keep this under control of a feature flag so it doesn't affect our prod project buffer without active enrollment in a separate PR.
> [RW-2060] [risk=no] Add feature flag and code to enable VPC flow logs. Enable in test.

- README.md
- api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
- api/doc/denormalized-tables.md
- api/libproject/devstart.rb
>  [No Ticket][Risk=low] Add documentation and update dataset linking table

- api/config/featured_workspaces_prod.json
Backfill prod feat workspace release
> add featured workspaces to prod config

- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
> [ticket=no][risk=no]remove deprecated anyListOf()

- README.md
> [risk=no] updating readme.

- api/config/config_local.json
- api/config/config_test.json
> [RW-2952][risk=low] Enable local/test welder

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceImplTest.java
Also refactor storage.get() to return a better error
> [risk=low][RW-2707]notebook locking metadata endpoint

- ui/src/app/views/app/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
> [RW-3077][risk=low] rm unused tcell

- api/db-cdr/changelog-data/db.changelog-27.xml
- api/db-cdr/changelog-data/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/util/CriteriaLookupUtil.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fixing ancestor lookup problem.
> [risk=no] fixing ancestor lookup problem.

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
> [No Ticket][Risk=no]Srubenst/fix data set parse bug

- ui/src/app/components/search-input.tsx
- ui/src/app/views/workspace-edit.tsx
> [RW-3070][risk=low] Moves disease search into new component.

- api/build.gradle
- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FirecloudApiClientTracer.java
- api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java
- api/src/main/java/org/pmiops/workbench/mandrill/MandrillApiClientTracer.java
- api/src/main/java/org/pmiops/workbench/mandrill/MandrillConfig.java
- api/src/main/java/org/pmiops/workbench/moodle/MoodleApiClientTracer.java
- api/src/main/java/org/pmiops/workbench/moodle/MoodleConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksApiClientTracer.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
> [RW-2864][Risk=moderate] Srubenst/tracing

- ui/src/app/views/data-use-agreement.tsx
> [RW-2906][RISK=NO] Replace Google docs in DUA page

- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
> [risk=no][ticket=no]Add one notebookLockingEmailHashTest case

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- common-api/src/main/java/org/pmiops/workbench/db/model/CommonStorageEnums.java
- common-api/src/main/resources/common_api.yaml
- ui/src/app/views/concept-add-modal.tsx
- ui/src/app/views/data-page.tsx
- ui/src/app/views/dataset-page.spec.tsx
- ui/src/app/views/dataset-page.tsx
1) Show one on data Set page a concept set with id : -1 name Demographics and domain person.
2) If user selects such concept set, create a concept set with name "Demographics" and concept Id: first from domain: gender/race/ethnicity.
3) Once the concept set is created step 1 will not be required as it will list out all the created concept set on data set page which will include Demographics as well
3)However Demographics concept set is filtered out in the concept set list on Data page
> [RW-2102][RISK=LOW]Create Demographics visual selector Data Set builder

- api/db-cdr/generate-cdr/make-bq-data.sh
fixing error in cdr build scripts
> [risk=no] fixing error in cdr build scripts

- ui/src/app/pages/analysis/interactive-notebook.tsx
> [RW-2921][Risk=no] Display appropriate message on preview page

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Please merge before cutting release tomorrow.
> [RW-2952][risk=low] Enable Leo Welder in all environments

- ui/src/app/components/modals.tsx
> [RW-3141][P1] fix modal overlay styling

- ui/src/app/components/breadcrumb.tsx
> [P0][RW-3143] fix workspace breadcrumb to route to data tab

- ui/src/environments/test-env-base.ts
> [RW-3077][risk=no] Drop remaining missed reference to tcell

- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/page-layout/page-layout.css
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
- Fix sorting for participant and participant detail tables (RW-3060 & RW-3020)
- Add label for tabs in labs graphs row expansion (RW-3019)
- Fix scrolling issue on participant detail page (RW-2811)
> [RW-3060][risk=no] Fix cohort review bugs

- api/db/changelog/db.changelog-90-review-version.xml
- api/db/changelog/db.changelog-master.xml
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortReviewDao.java
- api/src/main/java/org/pmiops/workbench/db/model/CohortReview.java
- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
This PR addresses the following:
1) Rename and Delete of Cohort Review
2) Adding Etag to handle concurrent edits
3) Adding creator to the Cohort Review
> [RW-3089][risk=no] Rename and Delete cohort reviews

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
> [risk=low][RW-3161]Create projects in a Service Perimeter

- ui/src/app/pages/workspace/workspace-nav-bar.tsx
> [No Ticket][Risk=no] Fix tabs labels to add back analysis

- ui/src/app/pages/workspace/workspace-list.tsx
> [RW-2211][risk=low] Adds "filter by" control to workspace list.

- ui/src/app/cohort-search/cohort-search/cohort-search.component.css
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
Adds cohort name above the search group columns on the cohort edit page
> [RW-2585][risk=no] Add cohort name to cohort edit page

- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
removing unnecessary validation.
> [risk=no] removing unnecessary validation.

- ui/src/app/pages/workspace/workspace-list.tsx
> [RW-2211][risk=low] Adjusts semantics of workspace list filter.

- api/build.gradle
- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillBillingProjectUsers.java
Backfill template stolen from https://github.com/all-of-us/workbench/pull/2221.
This script may need to be run periodically until we perform the 1PPW migration.
CC @gjuggler @jmthibault79
> [RW-3188][risk=low] Add billing project user backfill script

- ui/src/app/pages/workspace/workspace-about.tsx
> [RW-3147][P2] reload collaborators after sharing

- .circleci/config.yml
Per https://cloud.google.com/bigquery/docs/estimate-costs, it looks like BQ provides 1TB of on demand processing per month for free. I suspect that we aren't going to hit that cap with our tests, since Brian was saying we only create a couple hundred rows for the tests, which should be under the cap. Something to keep an eye on though.
> [RW-3044][Risk=low] Run bigquery tests on every pr

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixed problem with "rank1" for drugs
fixed problem with criteria attributes where the IDs were colliding
added in the 3 new PPI surveys
cleaned up PPI criteria including changing the subtype
> [RW-3067][risk=no] updating criteria creation script

- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/db/model/ConceptSet.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- ui/src/app/components/copy-modal.spec.tsx
- ui/src/app/components/copy-modal.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/utils/resourceActionsReact.ts
- ui/src/testing/stubs/workspaces-api-stub.ts
> [RW-2459][Risk=no] Srubenst/copy concept sets

- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
> [RW-3224][RW-3226][RISK=NO]Connect Tools From What's Next Page

- ui/src/app/cohort-review/cohort-review.module.ts
- ui/src/app/cohort-review/create-review-modal/create-review-modal.tsx
- ui/src/app/cohort-review/page-layout/page-layout.html
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-review/query-report/query-report.component.tsx
- ui/src/app/cohort-review/routing/routing.module.ts
- ui/src/app/cohort-review/table-page/table-page.tsx
- Moves cohort description page to a separate route to help with Google Analytics.
> [RW-2808][risk=no] Add route in review for cohort description

- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
Changes : 1) Add sticky footer which includes Save( orUpdate) and Analyze button
2) Update the Preview data header :
a) To indicate it is step 4
b) Include the link 'View Preview Table' (which will always be enable)
c) Remove Refresh preview link
> [RW-3231][RISK=NO] Update Data set page

- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/utils/navigation.tsx
> [RW-3232][risk=no] Use stricter encoding for angular navigation by URL

- ui/src/app/pages/data/data-page.tsx
> [RW-3236][Risk=no] Fix data page images

- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/node-info/node-info.component.ts
Also includes updates to use new colors file and minor fixes to physical measurements tree.
> [RW-3096][risk=no] Add source/standard limitation language to CB wizard

- ui/src/app/icons/edit.tsx
- ui/src/app/icons/playground-mode-icon.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
> [RW-3142][Risk=no] Disable playground fully when read-only

- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-3238][P2][risk=no] redirect from workspace edit to data tab

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
- api/db-cdr/generate-cdr/make-bq-data.sh
- api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
updating bq ls to allow for more results.
> [risk=no] updating bq ls to allow for more results.

- ui/src/app/cohort-review/cohort-definition/cohort-definition.component.tsx
- ui/src/app/cohort-review/participants-charts/participants-charts.tsx
- ui/src/app/cohort-review/query-report/query-report.component.tsx
- Align Demographics chart with domain charts
- Match blue in domain charts to darker blue in Demographics chart
- Replace color strings with `colors.ts` values
> [RW-2806][risk=no] Update cohort description chart styles

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtil.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtilTest.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
updating code/tests for new PPI subtypes.
> [RW-3132][risk=no] updating code/tests for new PPI subtypes.

- api/src/dev/server/Dockerfile
> [RW-3201][Risk=low] Update dockerfile for api build

- api/src/dev/server/with-uid.sh
> [no ticket, no risk] Fixes run-local-all-migrations

- api/src/dev/server/Dockerfile
This reverts commit 5ee5c5926db3692874ccffdabb022f48e6019693.
> [risk=no,ticket=no] Revert "[RW-3201][Risk=low] Update dockerfile for api build (#2471)"

- api/config/cdr_versions_stable.json
> [risk=no] removing typo

- api/docker-compose.yaml
- api/src/dev/server/Dockerfile
Resolves the stack trace crash due to incompatibility between Alpine and `opencensus-exporter-trace-stackdriver`.
> [RW-3201][risk=low] Re-attempt ubuntu dev docker

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [risk=no][RW-3161]New workspace projects are created in the Service Perimeter for Staging, Stable, and Prod

- ui/src/app/pages/data/data-set/dataset-page.tsx
> [risk=no] Drop "AoU" from "All Participants" cohort

- api/db/changelog/db.changelog-92-dataset-add-prepackaged-conceptsets.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DataSet.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/db/model/CommonStorageEnums.java
- common-api/src/main/resources/common_api.yaml
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
> [RW-2100][RISK=LOW]Create Survey Pre-Made Concept Set

- ui/src/app/components/icons.tsx
- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
- ui/src/app/styles/colors.ts
Create a `SnowmanIcon` component to deduplicate a bunch of magic styles
> [no ticket] [risk=no] standardize snowmen

- ui/src/app/components/resource-card.spec.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
Updated one unit test and a small refactor to make ResourceCardMenu inputs nicer.
Changes related to RW-2625 will go in another PR.
> [RW-3229] [risk=no] first pass on tests + refactors

- api/libproject/devstart.rb
> [No Ticket][Risk=no] Fix appengine tasks on perf to 10

- api/cluster-resources/README.md
> [risk=no] Update cluster-resource README to reflect bucket ACL changes

- api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
code cleanup for controllers/test cases
> [risk=no] test cleanup.

- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-3368][risk=no] Autoselect the default CDR when cloning

- ui/src/app/cohort-review/annotation-definition-modals/annotation-definition-modals.component.tsx
- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- Add deceased to sidebar info
- Update text for annotation field type options to be more user-friendly
- Update titles and text for annotation modals
- Show warning message before deleting an annotation
> [RW-2778][risk=no] Updates for annotations in CB review

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.css
- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/guards/can-deactivate-guard.service.ts
Show a warning dialog if a user tries to navigate away from cohort builder when there are unsaved changes to their cohort.
When creating a new cohort:
When editing an existing cohort:
> [RW-3064][risk=no] Warn users about unsaved cohort changes

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
> [RW-3306][Risk=moderate] Move to workspaceAcl call on FireCloud

- api/src/bigquerytest/java/org/pmiops/workbench/api/BigQueryServiceTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/BigQueryTestService.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
So it seems that the least intrusive way to solve this problem was to override BigQueryService#getBigQueryService().
> [risk=no] fixing BQ test cases to run inside Intellij

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
> [risk=no] test case cleanup

- api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java
converting CohortAnnotationDefinitionControllerTest from mock test to integration test.
> [RW-3379][risk=no] conversion from mock test to integration test.

- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
> [RW-3029][Risk=no] Get rid of race condition on new data set modal

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
> [risk=no] fixing equals

- ui/app.yaml
> [No ticket][Risk=no] Add missing policy information for perf environment

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
> [RW-3378][Risk=no] Fix R generated code

- ui/src/app/pages/signed-in/component.ts
> [risk=no][RW-3210]Only call getCdrVersions when the profile has Registered Access

- api/build.gradle
Remediating some of the findings in this Snyk report: https://app.snyk.io/org/all-of-us-researcher-workbench/project/681ed9fe-4281-4244-bf0a-3f64ed414704/
Explicitly pin our Spring Boot version to ~1.5.3.RELEASE~ (some chose higher or arbitrary versions) **now 1.5.22.RELEASE**
Update vulnerable Jackson version to 2.9.9
> [risk=low][no ticket]Update a few vulnerable packages

- ui/src/app/pages/analysis/notebook-redirect/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
> [no risk, no ticket]Remove enableJupyterLab feature flag (always false) and jupyterLabMode

- api/libproject/devstart.rb
> [No Ticket][Risk=no] Try bumping perf instance numbers

- ui/src/app/cohort-review/create-review-modal/create-review-modal.tsx
- ui/src/app/cohort-review/detail-header/detail-header.component.tsx
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
- ui/src/app/cohort-search/utils.ts
Events based on the Google doc tabs for [Review List](https://docs.google.com/spreadsheets/d/1V_Zp0ZtN8f237LNcaGQA-WZzYJu9g8ECq80gJCV8njA/edit?ts=5d4052a7#gid=733768841) and [Review Individual](https://docs.google.com/spreadsheets/d/1V_Zp0ZtN8f237LNcaGQA-WZzYJu9g8ECq80gJCV8njA/edit?ts=5d4052a7#gid=1011708973)
> [RW-3104][RW-3106] Add Google Analytics to Cohort Review

- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/table-page/table-page.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/node/node.component.html
- ui/src/app/cohort-search/node/node.component.ts
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/search-group/search-group.component.html
- ui/src/app/cohort-search/tree/tree.component.html
Add text to error messages for failing api calls. Also includes some cleanup so all messages display correctly.
For cohort builder:
> Please try again or contact Support in the left hand navigation.
For cohort review:
> Please try refreshing the page or contact Support in the left hand navigation.
> [RW-3358][risk=no] Update CB error messages

- api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java
> [No Ticket][Risk=no] Change to string format

- README.md
This PR is to add documentation to run tests in IntelliJ. This is due to us having trouble figuring out how to run the tests locally due to missing documentation.
> [No Ticket][Risk=no] Add documentation for testing in IntelliJ

- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
> [risk=no]Describe BillingMigrationStatus

- api/build.gradle
> [risk=low][no ticket]Update a few more vulnerable packages

- ui/src/app/cohort-review/detail-page/detail-page.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/components/help-sidebar.tsx
Fixes issue where the user is unable to close the create and edit annotation modals.
> [RW-3490][risk=no] Fix annotations modals 

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
Comment was deemed too long by Spotless.
> spotless fix

- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/components/help-sidebar.tsx
Annotation updates were failing after switching participants
> [RW-3516][risk=no] Fix annotation updates in cohort review

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/selection-info/selection-info.component.ts
allow source/standard mix for Condition and Procedure domains
> [RW-3514][risk=no] allow source/standard

- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
> [RW-2814] Call to Action and minor wording changes

- ui/src/app/cohort-search/list-search/list-search.component.tsx
- Increase width of Code column
- Add tooltip for values in the Name column that get cutoff
> [RW-3513][risk=no] Update display of list search table

- api/buildSrc/src/main/groovy/org/pmiops/workbench/tooling/IncrementalHotSwapTask.groovy
- api/src/dev/server/Dockerfile
> [RW-3401][risk=no] Fix incremental builds - don't hardcode java location

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- api/tools/src/main/resources/bigquery/es_person.sql
Adding a Boolean elastic type to the person index that is driven by existence of person id in the OMOP death table.
> [RW-3467][risk=no] adding deceased to elastic person index.

- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/resources/workbench.yaml
> [risk=no][no ticket] A few small changes I made in the course of doing actual work

- api/config/config_perf.json
> [RW-3474][risk=low] Enable VPC-SC in perf

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java
- api/src/main/java/org/pmiops/workbench/config/ConceptCacheConfiguration.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoImpl.java
- api/src/main/resources/cb_review_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
- ui/src/app/pages/data/cohort-review/detail-tabs.component.tsx
- ui/src/app/pages/data/cohort-review/page-layout/page-layout.ts
- ui/src/app/pages/data/cohort-review/table-page.tsx
Removing inheritance from ParticipantData objects
Also, simplified the filtering
> [RW-3559][risk=no] Removing inheritance from ParticipantData objects

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-3531
> [RW-3531][risk=moderate] Override default leo scopes to broader cloud-platform

- api/doc/cron-jobs.md
- api/src/main/java/org/pmiops/workbench/api/OfflineAuditController.java
- api/src/main/java/org/pmiops/workbench/billing/OfflineBillingController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineAuditControllerTest.java
- api/src/test/java/org/pmiops/workbench/interceptors/CronInterceptorTest.java
- ui/src/app/services/swagger-fetch-clients.ts
As called out in api/doc/cron-jobs.md
> [no ticket][risk=no] Update controllers to match our Offline naming norm

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/cohort-search/overview/overview.component.tsx
fixing dao issue for drug lookups
> [RW-3591][risk=no] fixing dao issue for drug lookups

- api/build.gradle
Also: use more variables in gradle.build
> [risk=low][no ticket] Upgrade Jackson to address vulnerabilities

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/billing/BillingGarbageCollectionService.java
- api/src/main/java/org/pmiops/workbench/billing/OfflineBillingController.java
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectGarbageCollection.java
- api/src/main/resources/workbench.yaml
We can't retrieve the results of cron endpoints from Cloud Console, but we can see logs.
Since our cron endpoints don't return anything, they should be 204 No Content instead of 200 OK
> [risk=low][RW-3435]Follow up: record ownership transfer by logging instead of return value

- api/config/config_perf.json
For nightly perf test runs in Perf env.
> [risk=no][no ticket] Increase billing buffer capacity to 500 in perf env

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/resources/workbench.yaml
- ui/src/app/pages/login/account-creation/account-creation.tsx
with the feature flag set to NO users were not able to create account because of institution is required error. This should fix that
> [RW-3601] [risk=low] Fix database errors when creating user accounts

- api/build.gradle
Now we're moving on to the medium-severity vulnerabilities: https://app.snyk.io/org/all-of-us-researcher-workbench/project/681ed9fe-4281-4244-bf0a-3f64ed414704
> [risk=low][no ticket]Dependency version updates as suggested by Snyk

- api/src/test/java/org/pmiops/workbench/db/dao/CohortAnnotationDefinitionDaoTest.java
> [risk=no][no ticket]Flaky test fix suggestion

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Includes the following changes:
- Update language explaining results when searching Drugs domain ([RW-3547](https://precisionmedicineinitiative.atlassian.net/browse/RW-3547))
- Change change column title from 'More Info' to 'View Hierarchy' ([RW-3095](https://precisionmedicineinitiative.atlassian.net/browse/RW-3095))
- Prevent whitespace in search input from returning no results ([RW-3549](https://precisionmedicineinitiative.atlassian.net/browse/RW-3549))
> [RW-3547][risk=no] CB language updates

- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.css
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/search-group-select/search-group-select.component.html
- ui/src/app/cohort-search/search-group/search-group.component.html
- ui/src/app/cohort-search/search-group/search-group.component.ts
- ui/src/app/cohort-search/utils.ts
Includes the following changes:
- Move Demographics to the 'Program Data' section of the criteria dropdown ([RW-3583](https://precisionmedicineinitiative.atlassian.net/browse/RW-3583)) 
- Fix capitalization of Ethnicity and Race selections ([RW-2973](https://precisionmedicineinitiative.atlassian.net/browse/RW-2973))
- Open wizard to edit a search group item when item name is clicked ([3542](https://precisionmedicineinitiative.atlassian.net/browse/RW-3542))
> [RW-3583][risk=no] Minor UI updates for CB 

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortreview/ReviewQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/PageRequest.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoCustom.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoImpl.java
- api/src/main/resources/cb_review_api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
This PR makes PCS filtering a bit simpler.
> [risk=no] Participant Cohort Review refactor

- ui/angular.json
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.localtest.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
- ui/src/environments/test-env-base.ts
rename `environment.ts` and comment other environment files
> [no ticket] [risk=low] fix confusingly named frontend config files

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortFactoryImpl.java
fixing total count when asking for chart data.
> [risk=no] fixing total count when asking for chart data.

- api/src/main/java/org/pmiops/workbench/cohorts/CohortFactoryImpl.java
adding missing props for cohort review.
> [RW-3647][risk=no] adding missing props for cohort review.

- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaAttributeDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortAnnotationDefinitionDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortReviewDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
> [RW-3664][risk=no] updating tests.

- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-3384][risk=no]Update stigmatization language and UX

- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/tables.tsx
- ui/src/app/pages/admin/admin-user-bypass.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-navigation-bar.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/concept/concept-survey-add-modal.tsx
- ui/src/app/pages/data/concept/survey-details.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/profile/data-use-agreement.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-library.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
> [risk=no][no ticket]Use FlexColumn and FlexRow where possible

- ui/src/app/cohort-search/constant.ts
> [RW-3669][risk=no] moving demo menu position.

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
renaming alias to match alias names in ds_linking table.
> RW-3536 renaming alias to match alias names in ds_linking table.

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
> [RW-3394][risk=low] Support non-CDR queries via BigQueryService

- api/db/changelog/db.changelog-104-dataset-name-unique-in-workspace.xml
- api/db/changelog/db.changelog-master.xml
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DataSet.java
- api/src/main/java/org/pmiops/workbench/db/model/DataSetValue.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
> [RW-3666][RW-3670][Risk=no] Clone datasets with workspace

- ui/src/app/pages/workspace/workspace-card.spec.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
> [RW-3708][risk=no] Fix disabled menu tooltips, add regression test

- api/db-cdr/generate-cdr/make-bq-data.sh
updating  _mapping_* tables name changes to _ext.
> [risk=no] updating  _mapping_* tables name changes to _ext.

- api/config/config_prod.json
> [RW-3691][risk=low] Bump prod project buffer size from 20 -> 100

- api/libproject/devstart.rb
Verified `./project.rb deploy --project all-of-us-workbench-test --version calbach --no-promote --dry-run` at least now passes.
> [RW-3719][risk=no] Fix config key typo

- README.md
- api/config/cdr_versions_prod.json
Moving to new CDR.
https://precisionmedicineinitiative.atlassian.net/browse/RW-3677
> [RW-3677][risk=no] Moving to new CDR

- api/libproject/generate_appengine_cron_yaml.rb
> [risk=no] Follow-up Ruby feedback

- ui/src/app/pages/data/concept/concept-table.tsx
Dropping for now since it doesn't work. Propose a broader concepts UI refactoring before attempting to reintegrate this feature: https://precisionmedicineinitiative.atlassian.net/browse/RW-3724
> [RW-3646][risk=no] Drop concepts search vocab filter

- ui/src/app/pages/workspace/workspace-library.tsx
> [RW-3479][risk=no] Drop unhelpful workspace library text

- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
> [risk=no] fix for cb_search_person.

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataDictionaryEntryDao.java
- ui/src/app/components/popups.tsx
- ui/src/app/pages/admin/admin-user-bypass.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
> [RW-2866][Risk=no] Srubenst/data dictionary ui

- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
> [RW-3156][risk=no] adding text changes.

- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
> [RW-3441][risk=no] Enable feature flag enableHomepageRestyle

- ui/package.json
> [risk=no] Clear mocks between jest unit test runs

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
> [RW-3754][Risk=no] Remove getWorkspace from create

- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
Reverts all-of-us/workbench#2728
https://precisionmedicineinitiative.atlassian.net/browse/RW-3441
there are a couple tickets blocking this release.
> Revert "[RW-3441][risk=no] Enable feature flag enableHomepageRestyle"

- api/db/changelog/db.changelog-105-workspace-free-tier-usage.xml
- api/db/changelog/db.changelog-106-workspace-billing-account-fields.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/billing/BillingAlertsService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceFreeTierUsageDao.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/java/org/pmiops/workbench/db/model/WorkspaceFreeTierUsage.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/billing/BillingAlertsServiceTest.java
> [risk=low][RW-3594]Store free tier billing costs in the DB

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/LoadDataDictionary.java
- api/tools/src/main/resources/data_dictionary_exports/AllOfUsDatasetV3.yaml
We were getting a duplicate upload error because it was fetching via cdr name but saving with the default cdr.
Also adds an export file for the new prod CDR.
> [risk=no][RW-3714] Fix Data Dictionary loading bug

- api/db/changelog/db.changelog-107-workspace-free-tier-usage-user-index.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/billing/OfflineBillingController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceFreeTierUsageDao.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/resources/bigquery/README
- ui/src/app/pages/profile/profile-page.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Rename BillingAlertsService to FreeTierBillingService
Add user_id index for searching workspace_free_tier_usage
> [risk=low][RW-3221]Display free tier usage and quota information in user profile

- api/config/featured_workspaces_local.json
- common-api/src/main/resources/common_api.yaml
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/pages/workspace/workspace-library.tsx
- ui/src/testing/stubs/featured-workspaces-config-api-stub.ts
- Adds categories for featured workspaces
- Removes original featured workspaces tab
- Fixes bug where we were indicating that the page has loaded after only 1 or 2 requests has completed.
> [RW-3688][risk=no] Sections under Featured workspaces

- common-api/src/main/java/org/pmiops/workbench/cdr/model/StandardProjection.java
> [risk=no] removing unused object.

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/node/node.component.ts
- Get ANY count from parent question for answers with attributes
- Use question in parameter name for answer selections with attributes
> [RW-3753][risk=no] Fix display of PPI criteria with attributes

- ui/src/app/components/CustomBulletList.tsx
- ui/src/app/components/headers.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/recent-workspaces.tsx
- ui/src/app/styles/colors.ts
> [RW-3539][risk=no] New landing page for users with no workspaces

- ui/src/app/components/help-sidebar.tsx
- Link Data Dictionary icon to [Google doc](https://docs.google.com/spreadsheets/d/1dsvJV8B7EXQj5EWa2XG-KAhs-l7FsQnyJSSFMstLF2U/edit#gid=183931508)
- Add title tags to sidebar icons
> [RW-3668][risk=no] Link data dictionary doc to sidebar

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
> [risk=no][no ticket]update defaultFreeCreditsLimit to $100 (from $300)

- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
Reverts all-of-us/workbench#2734
Previously reverted due to blocking tickets. Those tickets are all done now so reverting the revert now.
https://precisionmedicineinitiative.atlassian.net/browse/RW-3441
> Revert "Revert "[RW-3441][risk=no] Enable feature flag enableHomepageRestyle""

- api/build.gradle
> [risk=low][no ticket]Update vulnerable Jackson Databind version ... again

- ui/src/app/pages/data/data-set/dataset-page.tsx
This updates the preview dataset error wording. The server error exception now provides a link to open zendesk, which to make work we needed to get the profile in props to get all the user information.
> [RW-2655][Risk=no] Open zendesk and update preview wording

- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
> [risk=low][RW-3780] Fix Dataset Export to Notebook bug

- api/db/changelog/db.changelog-108-user-data-use-agreement.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDataUseAgreementDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/UserDataUseAgreement.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- ui/src/app/pages/profile/data-use-agreement.spec.tsx
- ui/src/app/pages/profile/data-use-agreement.tsx
Still need to figure out how to view as if I'm a user with a signed DUA, but this is mostly done
> [RW-3773][risk = no] Capture names, initials with which DUA was signed

- ui/src/app/pages/analysis/interactive-notebook.tsx
> [RW-3316][risk=no] Clear notebook load timer on navigate

- api/config/featured_workspaces_prod.json
Notes:
- I haven't published these in prod yet, looking at that next (this just needs to happen before this release goes to prod).
- "name" looks like it's probably unused, cleanup task: https://precisionmedicineinitiative.atlassian.net/browse/RW-3787
> [RW-3738][risk=no] Update prod featured workspaces

- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/resources/cb_search_api.yaml
- ui/src/app/cohort-search/constant.ts
adding fix for demographics trees
> [risk=no] adding fix for demographics trees

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
adding PPI numeric answers
updating demographics to handle new data
adding in additional PPI answers
updating wrong PPI concept IDs
flipped position of PM and PPI
fixed problem where ICD9/10 parents were dropping out
fixed demographics
adding sex at birth criteria
added in code to flip precise ingredient to ingredient to bring in more drugs
added in "other vocab" section to pull in concepts not captured by any trees
> [RW-3493][risk=no] Updating criteria tables generation script

- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Blocked on https://github.com/all-of-us/workbench/pull/2746
> [RW-2569][risk=low] Enable DUA in all environments

- api/src/main/resources/workbench.yaml
> [risk=no] Fix deleteCluster docs

- api/libproject/devstart.rb
> [risk=no][no ticket] Add run-local-rw-migrations to project.rb

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixed problem with query that was generating some of the PM criteria
> [RW-3972][risk=no] Fixed problem with pregnant at enrollment criteria

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixed problem where race/ethnicity concepts had "pmi: " in their names
> [RW-3793][risk=no] fixed problem where race/ethnicity concepts had "pmi: " in their names

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
> [RW-3806][risk=no] Set DUA time/version

- api/src/main/java/org/pmiops/workbench/audit/targetproperties/WorkspaceTargetProperty.java
> fix spotless

- api/config/cdr_versions_prod.json
moving cloud cdr version for prod -> r_2019q4_2
> [RW-3821][risk=low] moving cloud cdr version for prod.

- api/tools/src/main/java/org/pmiops/workbench/tools/LoadDataDictionary.java
- api/tools/src/main/resources/data_dictionary_exports/AllOfUsDatasetV1Legacy.yaml
- api/tools/src/main/resources/data_dictionary_exports/AllOfUsDatasetV2Legacy.yaml
- api/tools/src/main/resources/data_dictionary_exports/SyntheticDatasetV1Legacy.yaml
Main thing to check is that the `meta_data.cdr_version` field matches the names in the `cdr_version` table in production.
> [RW-3825][risk=no] Add legacy prod data dictionary files

- api/db-cdr/generate-cdr/make-bq-data.sh
> [risk=no] fixing cloud cdr build

- ui/src/app/pages/data/data-set/export-data-set-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
This was happening because export to notebook model was not sending dataset's Prepackaged concept set values. Therefore datasets with no concept sets apart from prepackaged started throwing error.
> [RW-3782][RISK:NO]Cannot export Dataset to Notebook because "Concept Sets must contain at least one concept"

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/service/UserRecentResourceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- Removes `VisibleForTesting` setters in favor of dependency injection
- remove timestamp argument from service calls that should always be set to `now` 
- misc test code cleanup. removing unnecessary calls, object instantiations, etc
> [RW-3843][risk=no] Part 1 - Refactoring UserRecentResource 

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- ui/src/app/pages/data/cohort-review/table-page.tsx
Fixing problem with review filters
> [RW-3880][risk=no] Fixing problem with review filters

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
> [risk=no] fixing high charts problem.

- api/src/main/resources/emails/welcomeemail/content.html
Old ![Screen Shot 2019-11-06 at 5 05 10 PM](https://user-images.githubusercontent.com/2770197/68342087-d58ca180-00b7-11ea-9e74-53428e8e83fc.png)
New
> [RW-3799][risk=no] Update welcome email

- api/cluster-resources/README.md
> [risk=no] Fix outdated step in Leo local testing README

- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Adds a limit to our big query sql strings from Dataset Builder.
> [RW-3911][risk=no] Add limit to dataset builder query

- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
> [risk=no] removing unused calls.

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Only really necessary in prod, bump in staging/stable as well for QA purposes.
> [RW-3949][risk=low] Bump default cluster size to highmem

- api/config/cdr_versions_prod.json
For program reasons, we no longer want this CDR version to be usable for new analysis.
> [RW-3950][risk=no] Archive R2019Q2R1

- api/config/featured_workspaces_prod.json
These have already been published.
Details should match this ticket:
https://precisionmedicineinitiative.atlassian.net/browse/RW-3903
> [RW-3903][risk=no] Add more featured workspaces

- ui/src/app/cohort-search/search-group/search-group.component.ts
- ui/src/app/cohort-search/utils.ts
Still seeing same failures from #2846
> [risk=no] Another attempt to fix flaky test

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtil.java
Adding fix for null/empty concept ids.
> [RW-3956][risk=no] Adding fix for null/empty concept ids.

- ui/src/app/pages/homepage/recent-workspaces.tsx
> [risk=no][RW-3740] FIx recent workspace cards overflow 

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/AggregationUtils.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticSearchService.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/AggregationUtilsTest.java
Removing 0-18 age range and replacing 19-44 with 18-44
> [risk=no] changing age ranges for charts.

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/modal/modal.component.ts
Validate that the user input falls within the range of the MIN and MAX values returned with the attributes
> [RW-4002][risk=no] Add validation to Survey attributes

- api/config/cdr_versions_perf.json
- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/db-cdr/generate-cdr/csv/domain_info.csv
- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/test/java/org/pmiops/workbench/cdr/dao/DomainInfoDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/DomainInfoDao.java
Adding data for Observations in Concept Sets. Also, added a dao test case for DomainInfoDao.
> [RW-3867][risk=no] Adding data for Observations in Concept Sets

- .github/PULL_REQUEST_TEMPLATE.md
> [risk=no][no ticket]Pull Request checklist - first iteration

- api/docker-compose.yaml
> [risk=no][no ticket]The default dev-up DB timeout of 15 seconds is not always enough: increase to 30

- api/docker-compose.yaml
Description: Add a comma to #2871 which I neglected
> [risk=no] Follow up to #2871: nasty little typo

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
Rearrange asserts so that data cleanup still happens on assertion fail.
> [risk=no] fixing test case.

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
Description:
I addressed some lingering feedback from RW-3995 but I forgot to upload it before merging.
---
> [risk=no][RW-3995] Export Workspace Data - nitpick code review feedback

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
Cutting down a bit on logspam. Don't log when there's nothing to do in the billing buffer sync step.
> [no ticket][risk=no] log tweaks

- api/db/changelog/db.changelog-109-dataset-prepackaged-conceptsets-nullConstraint.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbDataset.java
Adding database script to add null constraint and also add default values as 0 to prePackagedConceptSet column
> [RW-3327][RISK=NO]/dataSet returning 500 : add null constraint 

- api/src/main/java/org/pmiops/workbench/api/OfflineClusterController.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/resources/notebooks.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineClusterControllerTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
To match changes coming in https://github.com/DataBiosphere/leonardo/pull/1124
> [risk=no][no ticket] Add ListClusterResponse to notebooks.yaml

- ui/src/app/components/resource-card-template.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/new-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/utils/analytics.ts
Description:
Building off of #2898 and #2900 
---
> [RW-4084][risk=no] Google Analytics - Notebooks

- ui/src/app/components/rename-modal.tsx
- ui/src/app/components/resource-card-template.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/new-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/export-data-set-modal.tsx
- ui/src/app/pages/data/data-set/new-dataset-modal.tsx
- ui/src/app/utils/analytics.ts
Description:
Building off of #2898
> [RW-4083][risk=no] Google Analytics - Dataset Builder

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
PR #2886 is pretty bloated, so I'm pulling these changes out as requested by @calbach.
> [no ticket][risk=no] User Service refactorings for audit

- ui/package.json
Description:
This PR runs `yarn` as part of the `yarn dev-up` command on the UI. This is important, because `yarn` is what installs packages for the developer. This avoids branch switching issues if the npm package list is different from branch to branch. (I recently hit this switching to Will's branch to test locally)
If all packages are up to date, `yarn` takes about `.6` seconds to run if all packages are already up to date.
---
> [No Ticket][Risk=no] Run yarn on dev-up

- ui/angular.json
Description:
This fixes a bug where our workspace lists page was broken on staging, perf, stable, and prod. The bug is caused by a combination of issues
1. angular optimization/buildOptimizer can create breaking optimizations. This is likely due to a particularly aggressive setting for uglify which is non configurable through angular, https://github.com/angular/angular-cli/issues/11439.
2. We updated some of our libraries to a version which is affected by the issue above. https://github.com/all-of-us/workbench/pull/2897
There were a few possible solutions
1. Revert the version upgrade PR. We didn't want to do this because it would also remove other changes which we felt like were good to keep.
2. Remove `buildOptimizer` from our angular builds. The con here is that the build step may take …
> [risk=low][RW-4136] Remove buildOptimization from our angular builds

- ui/src/app/cohort-search/overview/overview.component.tsx
Checks for existing cohorts with the same name before allowing the user to clone (save as) or create a cohort. Will show this message if there's a conflict:
---
> [RW-3239][risk=no] Prevent trying to save cohorts with duplicate names

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-110-free-credits-days-override.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/app/pages/profile/profile-page.tsx
- ui/src/testing/stubs/profile-api-stub.ts
I prefer small PRs so I split off this independent piece of RW-3660.  It's also a prerequisite to other billing stories, such as the Override API.
Description:
---
> [risk=no]Split free_tier_credits_limit_override in 2: dollars and days

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.ts
- Increase the width of the wizard, add borders to the columns in list search results table ([RW-4088](https://precisionmedicineinitiative.atlassian.net/browse/RW-4088))
- Remove conditions on showing code in CB trees ([RW-2966](https://precisionmedicineinitiative.atlassian.net/browse/RW-2966))
- Always show Add button on attributes page, greyed out if form is invalid ([RW-3148](https://precisionmedicineinitiative.atlassian.net/browse/RW-3148))
---
> [RW-4088][risk=no] UI updates for CB wizard

- ui/src/app/services/sign-in.service.ts
Description:
Adds the cloud-billing and readonly cloud billing scopes to our UI OAuth request. This adds a sign in warning because these are sensitive scopes similar to this: https://developers.google.com/accounts/images/OAuth2Consent.png
---
> [RW-2694][Risk=moderate] Add billing scopes to UI OAuth request

- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.html
- Move the workspace menu from the nav bar to the right sidebar
- Update the ellipsis icon to FontAwesome
---
> [RW-4113][risk=no] Move workspace menu to sidebar

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixed issue with drug counts
fixed issue with condition/procedure standad/source snomed parent count issue
> [RW-4059][Risk=No] fixed drug ingredient count issue, fixed condition/procedure standad count issue

- .gitignore
- api/db-cdr/changelog-data/db.changelog-1.xml
- api/db-cdr/changelog-schema/db.changelog-31.xml
- api/db-cdr/changelog-schema/db.changelog-32.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/generate-cdr/csv/domain_info.csv
- api/db-cdr/generate-cdr/csv/survey_module.csv
- api/db-cdr/generate-cdr/import-gcs-data.sh
- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/SurveyModuleDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
- ui/src/app/pages/data/concept/concept-homepage.tsx
Adding new buckets in concept set builder for surveys and PM.
> [RW-4148][risk=no] Adding new bucket for surveys and PM

- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/test/java/org/pmiops/workbench/auth/ProfileServiceTest.java
Verified the fix manually locally.
Also verified the regression test fails without this fix.
---
> [RW-4219][risk=no] Fix ProfileService programming error NPE

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/testing/stubs/concepts-api-stub.ts
- ui/src/testing/stubs/data-set-api-stub.ts
Moving method from CohortsController
```
public ResponseEntity<DomainValuesResponse> getValuesFromDomain(
String workspaceNamespace, String workspaceId, String domainValue)
```
to DataSetController where it is currently being used.
> [risk=no] Moving column lookups to dataset builder.

- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- ui/src/app/pages/data/concept/survey-details.tsx
- Updates design for concept set search according to the latest [Invision screen](https://projects.invisionapp.com/d/main?origin=v7#/console/12820961/356269809/preview)
- Adds a 'Back to Concept Set Homepage' link when searching concepts
---
> [RW-4150][RW-4152][risk=no] Update styles in concept search

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-112-free-credits-time-management.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/billing/NotificationLogger.java
- api/src/main/java/org/pmiops/workbench/billing/NotificationService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceFreeTierUsageDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Description:
Implement the logic for determining when to send email alerts based on exceeding cost and time thresholds and limits for free tier billing.
This PR does not actually send emails.  That will be done in RW-3661.
---
> [risk=no][RW-3660]Free Tier alerting for Cost and Time Thresholds

- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
Adds link to Data Browser to conditions, procedures, measurements and drugs wizards in Cohort Builder.
> [RW-4202][risk=no] Add Data Browser link to CB wizard

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
Removing all warnings from ConceptControllerTest
Using Math.min in ConceptController
> [risk=no] test case cleanup and using Math.min method in ConceptController

- ui/src/app/app-routing.module.ts
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/app/utils/analytics.ts
- ui/src/assets/json/help-sidebar.json
Events added based on the [Help tab](https://docs.google.com/spreadsheets/d/1V_Zp0ZtN8f237LNcaGQA-WZzYJu9g8ECq80gJCV8njA/edit#gid=1113086802) of the GA spreadsheet
---
> [RW-3912][risk=no] Add Google Analytics events to help sidebar

- ui/src/app/components/help-sidebar.tsx
> [RW-4248][risk=no] Remove cloud compute icon from sidebar

- ui/src/app/pages/workspace/workspace-about.tsx
Description:
This link will no longer function with GCS exfiltration prevention enabled.
---
> [RW-4131][risk=no] Drop GCS bucket link

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/integration/java/org/pmiops/workbench/ApplicationTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaAttributeDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtilTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortAnnotationDefinitionDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortReviewDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/AggregationUtilsTest.java
remove unused throw Exception from tests
> [risk=no] remove unused throw Exception from tests

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtilTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
removing Arrays.asList in favor of ImmutableList.of in test cases.
> [risk=no] removing Arrays.asList in favor of ImmutableList.of

- api/src/test/java/org/pmiops/workbench/db/dao/CohortDaoTest.java
updating test coverage on CohortDao
- findCohortByCohortId
- findCohortByNameAndWorkspaceId
- findByWorkspaceId
> [risk=no] updating test coverage on CohortDao

- api/db/changelog/db.changelog-113-user-demographics-updates.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurvey.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
- common-api/src/main/java/org/pmiops/workbench/db/model/DemographicSurveyEnum.java
- common-api/src/main/resources/common_api.yaml
- ui/src/app/pages/login/account-creation/account-creation-options.tsx
- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Description:
This adds a few new fields to the account creation forms, leaving the styling mostly untouched. It also changes a few variable names to be more in line with camelCase, and alphabetizes a few things
---
> [RW-4163][Risk=low] Add new fields to demographics survey

- api/config/featured_workspaces_prod.json
Description:
Modifying the featured workspace config to add a new featured workspace.
For code review - please double check the values that I am adding.
Things I learned
- We manage user roles through a on to many join table from User to authority. Each authority value maps to a role that the user has.
- Use `./project.rb set-authority` to add a role/authority 
- Workspace publish is done manually through the UI. See AoU RW Playbook for more details.
---
> [risk=no][RW-3984] Add tutorial workspace: versioning notebooks

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
> [RW-4252][risk=no] Change 'Any' to 'Any value' for attributes selections

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Exact source code match with standard codes after check
Exact source code match with no standard codes after check
---
> [RW-4086][risk=no] Check for standard code matches before showing standard link

- README.md
Description:
I hit a few bumps setting up my loaner laptop.
---
> [risk=no]Some missing setup steps

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Resolves RW-4090
Resolves RW-4241
---
> [risk=low][RW-4090][RW-4241]Update terra-jupyter-gatk docker to version 0.0.9

- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
workbench/api/src/main/java/org/pmiops/workbench/concept/ConceptService.java:171: warning: [unchecked] unchecked method invocation: method findConcepts in interface ConceptDao is applied to given types
? conceptDao.findConcepts(conceptTypes, domains, VOCAB_ID, CONCEPT_CLASS_ID, pageable)
^
required: ImmutableList<String>,ImmutableList<String>,String,String,Pageable
found: ImmutableList<String>,ImmutableList,String,String,Pageable
/Users/jaycarlton/repos/workbench/api/src/main/java/org/pmiops/workbench/concept/ConceptService.java:171: warning: [unchecked] unchecked conversion
? conceptDao.findConcepts(conceptTypes, domains, VOCAB_ID, CONCEPT_CLASS_ID, pageable)
> [risk=no] removing warnings about unchecked method invocation

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/mail/EmailSubstitutionField.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
Description:
Splitting off some independent work from the (forthcoming) main RW-3661 PR
---
> [risk=low]Refactoring to make RW-3661 easier

- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
fixing bug in review survey and dataset survey tables
> [RW-3493][risk=no] survey table fix

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
Remove parameter object and added Swagger entry to have request type of exportResearch as List<Long> this will also solve classCast issue on Test for RDR
> [RW-4091][RISK=NO] Remove object and add appropriate Parameter type

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
Change response object for cloud task handler from object [long] to [long]
> [RW-4079][RISK=NO]Change response object

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
Reverting the return object for task handler This is TEMP to unblock RDR and will work on another PR to have a more definite entry
> [RW-4091][RISK=NO]revert swagger change for return object

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixes bug where there were null race/ethnicity concepts in the cb_criteria table
> [RW-4325][risk=no] fixes bug where there were null race/ethnicity concepts in the cb_criteria table

- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Description:
This is the final demographics survey tweaks. Should be only styling and no functionality changes.
---
> [RW-4282][Risk=no] Final tweaks to account creation styling

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
fixed bug where certain PPI answers weren't having counts generated for them
> [RW-4326][risk=no] fixed bug with PPI answer counts

- api/db-cdr/generate-cdr/make-bq-data.sh
> [risk=no] fix PM mapping

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
fix for allowing data set builder to show Observation columns
> [risk=no] fix for allowing data set builder to show Observation columns

- ui/src/app/pages/login/account-creation/account-creation.tsx
Fixes issue where clicking 'Next' after filling out the account creation form, screen goes blank.
---
> [RW-4345][risk=no] Fix error in account creation

- api/db-cdr/generate-cdr/copy-bq-dataset.sh
- api/db-cdr/generate-cdr/libproject/devstart.rb
Blocked on: https://precisionmedicineinitiative.atlassian.net/browse/PD-4754
> [RW-3334][risk=low] Publish CDRs through an intermediate project

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
fixed bug with PPI surveys and missing data in review and dataset builder
> [RW-4333][risk=no] fixed bug with PPI surveys 

- ui/src/app/components/resource-card.tsx
- ui/src/app/components/resources.tsx
- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/data/data-set/dataset-resource-card.tsx
- ui/src/app/pages/homepage/recent-resources.tsx
Description:
Refactoring Dataset out of the mega resource card class. Doing this now so I don't have to reimplement the stuff I'm adding for RW-4384 (Disabling locked billing actions).
For reference
- Cohorts - https://github.com/all-of-us/workbench/pull/2493
- Notebooks - https://github.com/all-of-us/workbench/pull/2327
---
> [risk=no] Refactor Dataset Resource Card

- api/db-cdr/changelog-schema/db.changelog-33.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
changing indexes to reflect the current state of the concept cloud(ConceptDao) table.
> [risk=no] changing indexes to reflect the current state of the concept cloud table.

- api/db/changelog/db.changelog-122-drop-demographics-tables.xml
- api/db/changelog/db.changelog-master.xml
Description:
Removes tables. Should merge after the next release.
---
> [RW-4312][Risk=low] Drop unused demographics survey tables

- api/src/main/java/org/pmiops/workbench/compliance/ComplianceServiceImpl.java
gave it the wrong class. copy paste has failed me again.
> [risk=no][RW-2957] fix logger name in ComplianceServiceImpl

- ui/src/app/pages/analysis/notebook-redirect.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/quick-tour-modal.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/login/account-creation/account-creation-options.tsx
- ui/src/app/pages/login/account-creation/account-creation-success.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/profile/data-use-agreement-content.tsx
- ui/src/app/pages/profile/profile-page.tsx
- ui/src/app/pages/workspace/stigmatization-page.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-share.tsx
Make sure all instances of 'AoU' and 'All of Us' are spelled out and italicized
*Note: The 'All of Us' in `account-creation-options.tsx` is left unitalicized since it needs to be a string as the label for the dropdown option
---
> [RW-3062][risk=no] Fix "Aou" and "All of Us" text across workbench

- api/doc/api-rollback-safety-guidelines.md
> [No Ticket][Risk=no] Api Rollback Safety doc

- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- ui/src/testing/stubs/concepts-api-stub.ts
- [x ] This PR meets the Acceptance Criteria in the JIRA story
- [ x] The JIRA story has been moved to Dev Review
- [ x] This PR includes appropriate unit tests
- [ x] I have run and tested this change locally
Screen shots:
> [RW-4254][RISK=NO] Wording changes to Select All communication

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
exportToWorkspace call was throwing a lot of 404 error while collecting collaborator list, as part of this PR we now use workspaceService to collect the collaborators list as well as enclose the call in try catch to handle exception 
---
- [ X] This PR meets the Acceptance Criteria in the JIRA story
- [ X] I have run and tested this change locally
> [RW-4091][RISK=NO]Fix exportWorkspace error

- api/config/featured_workspaces_prod.json
> [risk=no][RW-4297] Update featured workspace for physical measurements data

- api/db/changelog/db.changelog-124-add-demographic-gender-identity.xml
- api/db/changelog/db.changelog-master.xml
- [X ] I have run and tested this change locally
> [No ticket][RISK=NO]Account creation - Add liquibase gender Identity to demographic survey 

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportEnums.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/rdr.yaml
This PR update the following RDR Parameters:
- Change sexAtBirth to array
- Add parameter identifiesAsLgbtq and lgbtqIdentity
- Update RDR workspace parameter reasonForInvestigation to scientificApproaches
- Do not call RDR exportWorkspace if the workspace list is empty
- Remove dead code: sexual Identity
> [no-ticket][RISK=NO]Update RDR attributes

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportEnums.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/rdr.yaml
- [X ] I have run and tested this change locally
- [ X] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
> [noTicket][RISK=NO]Send user demographic survey attribute Gender identity to RDR

- api/db-cdr/generate-cdr/make-bq-data.sh
> [risk=no] fixing cloud cdr mistake.

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/resources/client_api.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
- ui/src/app/pages/data/concept/survey-details.tsx
- Add participant count to the survey tables in concept search ([RW-4342](https://precisionmedicineinitiative.atlassian.net/browse/RW-4342))
- Change the count column header from "Count" to "Participant Count" ([RW-4154](https://precisionmedicineinitiative.atlassian.net/browse/RW-4154))
- Change text in tiles from "Browse Domain" to "Select Concepts" ([RW-3225](https://precisionmedicineinitiative.atlassian.net/browse/RW-3225))
---
> [RW-4342][risk=no] Concept Search - Add participant count to surveys

- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-set-details.tsx
- ui/src/app/pages/data/concept/concept-table.tsx
Add error handling for api calls in concept search and display error messages for failing calls
[Error Messaging Doc](https://docs.google.com/presentation/d/1vVK0s9AxXKyhcgZJqWAWrqiitsG-RTwh16DOTp47zEY/edit#slide=id.g5b5ba1fbdc_0_16)
---
> [RW-2820][risk=no] Add error messaging for Concept Search

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Will manually test this tomorrow. Need to pickup a bug fix in Jupyter. Welder also upgraded since it's a month old.
> [RW-4404][risk=low] Bump Jupyter and Welder images

- .gitmodules
- api/libproject/devstart.rb
I've updated step 35 of the new app guide accordingly: https://broad.io/aou-new-environment
> [RW-4408][risk=no] drop firecloud-tools and its one user

- README.md
Hopefully this will leave some breadcrumbs for the next person who wants to do this.
> [No ticket][risk=no] Update README.md with a note on OAuth client IDs.

- ui/src/app/cohort-search/list-search/list-search.component.tsx
> [RW-4266][risk=no] Prevent searching with empty text input

- api/config/config_perf.json
- api/config/config_stable.json
- api/config/config_staging.json
See Jira comments for some added context. The idea is to roll this to all lower envs next week, then to prod the week after.
> [RW-4307][risk=low] Enable keyless delegation in perf & staging

- api/config/featured_workspaces_prod.json
I've already published the workspaces following instructions from our playbook. This PR adds them to the featured workspace config.
---
> [RW-4396][risk=no] Add two new phenotype library featured workspaces

- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Description:
This changes the name over to concept_id to be more accurate
---
> [No Ticket][Risk=no] Fix tests to be more correct

- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/concept/ConceptService.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetMapper.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbConceptSet.java
- api/src/main/java/org/pmiops/workbench/utils/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/ConceptDaoTest.java
- api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetMapperTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ConceptSetDaoTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
@jaycarlton 
Addressed code from comments on https://github.com/all-of-us/workbench/pull/3101#pullrequestreview-356131667
@ericsong 
please review ConceptSetMapper and corresponding changes.
> [no-ticket][risk=no] addressing comments from another closed PR

- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
See the RW-3685 ticket for more context – this flips the flag in all environments.
The major dependency here is to update our Rainforest QA tests. Rohini should have that done by tomorrow afternoon or Tuesday. Tracked with RW-4447.
---
> [RW-3685][risk=low] Enable new account creation in all environments

- api/libproject/devstart.rb
> [RW-4469][risk=no] copy BQ tables

- api/cluster-resources/py-dataset-snippets-menu.json
- api/cluster-resources/py-gcs-snippets-menu.json
- api/cluster-resources/r-gcs-snippets-menu.json
> [RW-4433][risk=no] update code snippets

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
changed dob from timestamp to date, added two new columns age_at_consent and age_at_cdr and added code to calculate both of these data points
> [RW-4428[risk=no] added columns to cb_search_person

- api/db/changelog/db.changelog-127-free-billing-account-name.xml
- api/db/changelog/db.changelog-master.xml
To reflect migration in https://precisionmedicineinitiative.atlassian.net/browse/RW-4144
> [RW-4144][risk=no] Rebackfill the free tier billing account name

- ui/src/app/components/cookie-banner.tsx
- ui/src/app/pages/login/login.tsx
- ui/src/app/pages/login/sign-in.tsx
Description:
This makes the cookie banner its own component!
---
> [RW-4244][Risk=no] Separate cookie banner

- ui/src/app/pages/workspace/workspace-card.tsx
Description:
This removes the pending approval section from workspace cards
---
> [RW-4421][Risk=no] Remove pending review from workspace tiles

- ui/src/app/pages/login/login.tsx
> [RW-3570][Risk=no] Update Fisma language

- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
> [RW-4481][Risk=no] Remove scroll to bottom from TOS

- ui/src/app/pages/homepage/homepage.tsx
> [RW-4354][Risk=no] Update homepage tagline

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportEnums.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/rdr.yaml
Send the following data to RDR:
What is the primary purpose of your project?
What are the specific scientific question(s) you intend to study
What are the scientific approaches you plan to use for your study?
What are the anticipated findings from the study? and
Population of interest
---
> [RW-4285][RISK=NO] Changes to workspace description page -Send data to RDR

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
added code to remove temp data from prep_criteria_ancestor so it is clean for future runs
> [RW-4477][risk=no] added code to remove temp data from prep_criteria_ancestor

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
Description:
This should have been part of #3139 - not sure what happened.
Please merge without waiting for me, to unbreak the build.
---
> [risk=no] Somehow lost this import - merge error?

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/PersonDao.java
- api/src/main/java/org/pmiops/workbench/cdr/model/DbPerson.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderStorageManager.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/PersonDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceTest.java
API call for dob/age at consent/age at cdr
- Implemented a new PersonDao and test cases
- Implemented a CohortBuilderService that will eventually have all daos from CohortBuilderController
> [RW-4435][risk=no] API call for dob/age at consent/age at cdr

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
added 3 new columns to cb_search_person to hold data bucket flags
> added 3 new columns to cb_search_person to hold data bucket flags

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportService.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
Added a proper unit test. Cleaned up a typo and some other slight jank in `RdrExportServiceImpl`.
--
> [risk=low][RW-4423] Include researcher contact email in RDR export

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- ui/src/app/pages/data/concept/concept-add-modal.spec.tsx
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- Fixes name of props that caused error when trying to add concepts to a set
- Also fixed issue where editing a survey set returned no results
> [risk=no] Fix ConceptAddModal props

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
Implementing age searches for current age, age at consent and age at cdr.
- Updated BQ sql to account for age at consent and age at cdr queries
- Updated relevant BQ test cases.
> [RW-4509][risk=no] Implementing age searches for current age, age at consent and age at cdr.

- ui/src/app/app-routing.module.ts
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.html
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/assets/json/help-sidebar.json
> [risk=no][RW-4401] Help sidebar in notebooks

- ui/src/app/pages/admin/admin-workspace.tsx
- ui/src/app/pages/workspace/research-purpose.tsx
- ui/src/app/utils/research-purpose.tsx
> [No Ticket][Risk=no] Abstract the selected populations for reuse

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
during Task
` :compileJava` 
was seeing warnings for
`Unchecked assignment: 'java.util.List' to 'java.util.List<org.pmiops.workbench.model.InstitutionalAffiliation>'`
> [no ticket][risk=no] remove warning

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/delete.txt
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
> [RW-4472][risk=no] Update free tier credit limit to $300

- api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
fixing scripts to generate denormalized tables
> [no ticket][risk=no] fixing scripts to generate denormalized tables

- ui/src/app/pages/workspace/workspace-library.tsx
> [RW-4480][Risk=no Add details for workspace libraries

- api/libproject/devstart.rb
Now using service account to import sql into cloud
> [no ticket][risk=no] fixing cdr scripts.

- api/src/main/resources/workbench.yaml
Description:
Removes bad documentation
---
> [No Ticket][Risk=no] Change docs on developer authority

- api/config/cdr_versions_prod.json
> [no ticket][risk=no] rollback cdr for prod

- api/build.gradle
Restore a mis-refactor according to comment at https://github.com/all-of-us/workbench/pull/3207#discussion_r390444011
---
> [risk=no][no ticket] restore var name

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/utils/analytics.ts
- ui/src/environments/environment.stable.ts
- Change "FAQ" text to "User Support" and switch link to Zendesk support page.
- Use prod ZD link for stable since there's currently no content for non-prod environments.
---
> [RW-4526][risk=no] Update support text and link in sidebar

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/guards/disabled-guard.service.ts
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/user-disabled.tsx
Description:
The UI isn't quite like the mocks, because we haven't updated the logged out headers yet. 
I manually tested by disabling my user in test, and then hitting the UI.
---
> [RW-4475][Risk=no] Working disabled UI

- ui/docs/style-guide.md
- ui/src/app/guards/disabled-guard.service.ts
Description:
Move towards async as discussed in eng-sync
---
> [RW-4475][Risk=no] Follow up disabled user messaging

- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
Description:
This changes the spinner to fixed position so it is on the view when submit is clicked.
---
> [RW-4471][Risk=no] Change spinner to fixed on demographics page

- ui/src/app/cohort-search/search-group/search-group.component.ts
changing text for temporal selections.
> [RW-4012][risk=no] changing text for temporal selections.

- api/src/test/java/org/pmiops/workbench/db/model/StorageEnumsTest.java
> [risk=no] dumb little cleanup of storage test

- e2e/yarn.lock
Description:
Addresses https://github.com/all-of-us/workbench/network/alerts for e2e
---
> [risk=low]Update vulnerable acorn and minimist packages for e2e

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/testing/stubs/workspaces-api-stub.ts
Description:
This adds a new endpoint to get workspace free tier billing info, and shows it on the workspace about page. It is restricted to writers and owners only. 
---
> [RW-3212][Risk=no] Working workspace billing info

- README.md
> [risk=no]Add API debugging section to readme

- e2e/app/aou-elements/button.ts
- e2e/app/aou-elements/select-component.ts
- e2e/app/base-page.ts
- e2e/app/create-account-page.ts
- e2e/app/google-login.ts
- e2e/app/home-page.ts
- e2e/app/workspace-edit-page.ts
- e2e/app/workspaces-page.ts
- e2e/resources/data/user-registration-fields.ts
- e2e/resources/data/workspace-create-fields.ts
- e2e/resources/workbench-config.ts
- e2e/tests/user/login.spec.ts
- e2e/tests/user/registration-ui.spec.ts
- e2e/tests/user/registration.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/tests/workspace/workspace-ui.spec.ts
Updated tests to work with new Create Account UI and removed non-working code.
Unrelated to broken test, I also saw some flaky behavior while running tests repeatedly. I refactored few lines of code that should remove flaky behavior.
> [RW-4626][risk=no] Puppeteer: Fix Registration tests

- api/db-cdr/changelog-data/db.changelog-1.xml
- api/db-cdr/changelog-schema/db.changelog-35.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/generate-cdr/bq-schemas/cb_data_filter.json
- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBDataFilterDao.java
- api/src/main/java/org/pmiops/workbench/cdr/model/DbDataFilter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/mappers/DataFilterMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBDataFilterDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/mappers/DataFilterMapperTest.java
1. Updated CohortBuilderControllerBQTest to reflect data filters for ehr and PM
2. Added a new table to cloud cdr called cb_data_filter
3. Added cb_data_filter to cloud cdr creation scripts
4. Created a new dao -> CBDataFilterDao
5. Created a new endpoint to retrieve all data filter for UI
---
> [RW-4587][risk=no] Make global data filter db driven

- api/src/main/resources/workbench-api.yaml
Had a duplicate entry to DataFilter in workbench-api.yaml
> [no ticket][risk=no] fixing mapper issue

- ops/ruby/devops-toolkit/README.md
- ops/ruby/devops-toolkit/devops.rb
- ops/ruby/devops-toolkit/tasks/developer_environment.rb
- ops/ruby/devops-toolkit/tasks/input/aou-workbench-dev-tools.yaml
Since this script is intended to be used only on input files from trusted sources, there's no screening in place to determine that a command won't be destructive (and of course, with local aliases, all bets are really off). Still, in case some joker tries to put in a tool with the name `rf` and the version flag `-rf /`, we want to hedge our bets. As such, the tool now prints out all the commands to be run in a list and asks for confirmation before continuing.
Additoinally, we now capture:
* username
* hostname
* os
* timestamp
* shell
Again, the intention is for this to be used internally, and users have the option of deleting stuff they don't want included before sharing. I.e. this tool isn't sending any sensitive info anywhere except a local file.
---
> [risk=no][no ticket] System metadata and pre-run warning

- e2e/driver/chrome-driver.ts
- e2e/driver/chrome-startup-flags.ts
- e2e/driver/puppeteer-launch.ts
- e2e/package.json
- e2e/tests/user/registration.spec.ts
Extending Puppeteer default Chrome startUp flags (switches) with CircleCi relevant flags to improve test stability and performance.
> [RW-4634][]risk=no]Add custom Chrome startUp flags

- e2e/app/aou-elements/select-component.ts
- e2e/app/create-account-page.ts
- e2e/app/google-login.ts
- e2e/driver/chrome-driver.ts
- e2e/tests/user/login.spec.ts
- e2e/tests/user/registration-ui.spec.ts
- e2e/tests/user/registration.spec.ts
Running Puppeteer tests on Circle so far have been shown to be slower. Unrelated to app or features, tests could fail sometimes.
> [RW-4631][risk=no] Improve reliability running Puppeteer tests on Circle

- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- Under represented population SEX -> SEX AT BIRTH
- Remove duplicate option from question 3
- Add footer text to question Request for Review 
---
> [RW-4543][RISK=NO] Copy changes to workspace create page

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- Research purpose categories can be expanded either by selecting the icon next the Research purpose label or by selecting the checkbox
- The Research Purpose checkbox can only be selected. Once selected it will expand the categories.
- If the sub category is selected and un selected , the research purpose checkbox will then be un selected, but the categories will still be expanded
- Only clicking the icon next to Research Purpose will collapse the categories 
---
> [RW-4567][RISKNO] Bug with Research Purpose checkbox 

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
> [no ticket][risk=no] fixing criteria dao

- e2e/app/create-account-page.ts
- ui/src/app/components/pdf-viewer.spec.tsx
- ui/src/app/components/pdf-viewer.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/styles.css
Factor out the PDF viewer component from the account creation component. Unfortunately, I had to put an amount of the 'look, we've viewed the last page' stuff into the PDF viewer but most of it I was able to keep in the account creation component.
---
> [RW-4561][risk=no] factor out pdf viewer

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java
Add comments and tests, rename methods
Description:
---
> [risk=no]Fix NPE in userHasFreeTierCredits

- ui/src/app/components/help-sidebar.tsx
> [No Ticket][Risk=no] Remove min height from sidebar

- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Some cleanup on SearchGroupItemQueryBuilder.
> [no ticket][risk=no] removing warnings

- ui/src/app/cohort-search/cohort-search/cohort-search.component.html
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/cohort-search/overview/overview.component.tsx
Prevent showing the unsaved changes warning modal when deleting a cohort
> [risk=no] Fix CB unsaved changes warning

- ui/src/app/pages/signed-in/component.html
- ui/src/app/pages/signed-in/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
> [No Ticket][Risk=no]Environment flag for footer

- api/config/featured_workspaces_prod.json
> [risk=low][RW-4647] Feature "How to Get Started with Registered Tier Data"

- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [risk=low][RW-4449]Set enableSumoLogicEventHandling to true in all environments

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
- ui/src/testing/stubs/cohort-builder-service-stub.ts
- Renamed CohortBuilderController method from `getCriteriaAutoComplete` to `findCriteriaAutoComplete`
- Moved implementation into CohortBuilderService
- Updated test cases
> [no ticket][risk=no] updating criteria tree autocomplete

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
- ui/src/testing/stubs/cohort-builder-service-stub.ts
Updating drug brand lookups
- moved findDrugBrandOrIngredientByValue and findDrugIngredientByConceptId into CohortBuilderService
- Updated test cases.
> [no ticket][risk=no] Updating drug brand lookups

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- Move findCriteriaByDomainAndSearchTerm into CohortBuilderService
> [no ticket][risk=no] move logic for searching domain/term into service

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- move findStandardCriteriaByDomainAndConceptId to CohortBuilderService
- update UI/Test
> [no ticket][risk=no] update findStandardCriteriaByDomainAndConceptId

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
> [risk=no][RW-4592]Fix NPE and add tests

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/testing/stubs/cohort-builder-service-stub.ts
- rename/move move findParticipantDemographics
- update UI/Tests
> [RW-4702][risk=no] update getParticipantDemographics

- ui/yarn.lock
Description:
Similar to #3350, this is a partial resolution to a security alert: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/minimist/open
---
> [risk=low]Upgrades for vulnerable minimist

- e2e/app/authenticated-page.ts
- e2e/app/base-page.ts
- e2e/app/google-login.ts
- e2e/app/workspace-edit-page.ts
- e2e/app/workspaces-page.ts
- e2e/tests/user/login.spec.ts
- e2e/tests/user/registration-ui.spec.ts
- e2e/yarn.lock
Adding common method to reduce boilerplate code in e2e test framework.
> [no ticket][risk=no] Add new clickAndWait()

- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [RW-4262][risk=low] Re-enable billing lockout in all envs

- ui/src/app/pages/login/account-creation/account-creation.tsx
> [RW-4566][risk=no] Fix account creation characters display bug

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
Follow up ticket to use mapStruct to convert dbWorkspace to rdrWorkspace: https://precisionmedicineinitiative.atlassian.net/browse/RW-4715
---
> [RW-4565] Add reviewRequested fields to RDR

- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- api/db-cdr/generate-cdr/make-bq-data.sh
- api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
> [no ticket][risk=no] update cdr script

- api/config/config_prod.json
- api/config/config_stable.json
This PR should wrap up our rollout of keyless delegation. See RW-4307 for more details, including comments tracking the API enablement and IAM grants in the stable and production environments.
---
> [RW-4307][risk=low] Enable keyless delegation in stable and production

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Fixed an issue with version skew on the DUCC version - I had changed the frontend value but not the backend value.
> [no ticket][risk=no] fix version skew

- .circleci/config.yml
- e2e/package.json
Simple CircleCi config change to run e2e tests faster.
> [no ticket][risk=no] Enable CircleCi parallelism for e2e project

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
Description:
Some of these may prove useful to keep on a longer-term basis.  But my immediate goal is to give myself enough information to find out why RW-4678 is happening on Test but does not happen on Local.
---
> [RW-4678] Add some temporary logging to investigate

- api/README.md
Description:
Missed in #3368 
---
> [risk=no]doc -> docs

- e2e/app/aou-elements/button.ts
- e2e/app/aou-elements/clr-icon-link.ts
- e2e/app/aou-elements/xpath-defaults.ts
- e2e/app/aou-elements/xpath-finder.ts
- e2e/app/authenticated-page.ts
- e2e/app/create-account-page.ts
- e2e/app/home-page.ts
- e2e/tests/home/home-page.spec.ts
- e2e/tests/user/registration-ui.spec.ts
- e2e/tests/user/registration.spec.ts
Changes will also resolve ticket RW-4648.
> [RW-4736][risk=no] Puppeteer test: waitFor institution email validation

- ui/src/app/pages/profile/profile-page.tsx
- ui/src/app/utils/index.tsx
> [risk=no][RW-4684]Don't display negative free credits

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
Description:
This does NOT resolve RW-4678.  My plan to do so is here: https://docs.google.com/document/d/1opIb4W6LW78tQ78SyQ7040p5F7D5d6EeEvE7bIJ2xAQ/edit
---
> [risk=no][RW-4678]Free Tier Billing Alert cron log update

- ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
> [RW-4683][RISK=NO] Sort institutions in dropdown in alphabetical order

- api/config/cdm/cdm_5_2.json
- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/src/bigquerytest/resources/bigquery/schema/person.json
Adding column for sex at birth
> [RW-4142][risk=no] Adding column for sex at birth

- api/config/cdr_versions_prod.json
> [RW-4665][risk=no] moving cdr version

- ui/src/app/pages/login/account-creation/common.tsx
No UI changes except the updated link will now open in a new tab.
---
> [RW-4746][RISK=LOW] Change URL to Researcher Directory page

- ui/src/app/pages/login/login.tsx
> [RW-4717][Risk=no] Fix button text

- e2e/app/google-login.ts
> [No Ticket][Risk=no] Fix google login in puppeteer

- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
This is a quick fix to unblock Rainforest tests. Screenshots:
Valid case:
Error type 1:
Error type 2:
---
> [RW-4768][risk=no] Bring back the green checkmark when institutional email is validated

- ui/src/app/icons/public-displayed-icon.tsx
- ui/src/app/icons/publicly-displayed-icon.tsx
> [RW-4765][RISK=NO] Create publicly displayed component

- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/profile/profile-page.tsx
- ui/src/app/pages/profile/profile-registration-step-status.tsx
Updated language from 'Research Ethics Training' to '_All of Us_ Responsible Conduct of Research Training' on homepage and profile page:
---
> [RW-4693][risk=no] Update ethics training language

- e2e/app/aou-elements/base-element.ts
- e2e/app/aou-elements/ellipsis-menu.ts
- e2e/app/authenticated-page.ts
- e2e/app/base-page.ts
- e2e/app/create-account-page.ts
- e2e/app/data-page.ts
- e2e/app/featured-workspaces-page.ts
- e2e/app/google-login.ts
- e2e/app/home-page.ts
- e2e/app/navigation.ts
- e2e/app/page-identifiers.ts
- e2e/app/profile-page.ts
- e2e/app/user-admin-page.ts
- e2e/app/workspace-card.ts
- e2e/app/workspace-edit-page.ts
- e2e/app/workspaces-page.ts
- e2e/package.json
- e2e/resources/workbench-config.ts
- e2e/resources/workspace-data.ts
- e2e/tests/home/home-page.spec.ts
- e2e/tests/misc/sidenav.spec.ts
- e2e/tests/profile/profile-page.spec.ts
- e2e/tests/user/login.spec.ts
- e2e/tests/workspace/workspace-clone.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/tests/workspace/workspace-ui.spec.ts
- e2e/utils/test-utils.ts
Two new clone workspace tests.
One new create workspace test.
Related changes: 
- Single `Ellipsis` class and static methods for both the Data and Workspaces pages.
- Single `navigation.ts` class static methods for `sideNav` actions.
> [RW-4764][risk=no] Puppeteer new workspace tests

- ui/src/app/pages/profile/demographic-survey.tsx
> [RW-4685][Risk=no] Center spinner on view

- api/config/config_prod.json
- api/config/config_stable.json
> [risk=no][RW-4465]Enable requireInstitutionalVerification Feature Flag in Prod and Stable

- ui/src/app/pages/homepage/registration-dashboard.tsx
Description:
This updates the eRA commons description to include that there is no exchange of info.
---
> [RW-4728][Risk=no] Update eRA commons language

- ui/src/app/pages/profile/data-user-code-of-conduct.tsx
> [RW-4714][Risk=no] Update ducc to say proceed on page 1

- ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx
Use standard number input to fix issue when a user enters non-numeric input
---
> [RW-4770][risk=no] Fix integer annotation in cohort review

- api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
Missed some code cleanups from https://github.com/all-of-us/workbench/pull/3315
> [RW-3187][risk=no] Clean up dead clone workspace code

- api/config/featured_workspaces_prod.json
This PR swaps out a few existing phenotype library workspaces for the newer versions.
---
> [RW-4763][risk=no] Update featured workspaces

- README.md
Check this with Greg to confirm this was the intent. @aweng98 hit this when running through the instructions.
> [risk=no] Include sudo in docker-sync install docs

- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
> [risk=no][RW-4797]Align and update the free tier email alert text

- ui/package.json
- ui/yarn.lock
Description:
I was mistaken: #3374 did not resolve my local angular testing issues.  So I tried the other suggestion from https://github.com/karma-runner/karma-sauce-launcher/issues/117
---
> [risk=low]Reinstall wd to re-enable local angular testing

- ui/src/app/icons/publicly-displayed-icon.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/account-creation/account-creation-survey.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/login/account-creation/common.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/profile/demographic-survey.spec.tsx
- ui/src/app/pages/profile/demographic-survey.tsx
- ui/src/app/pages/profile/profile-page.tsx
> [RW-4718][risk=no] Attach required/optional/publicly displayed tags to registration pages

- api/db-cdr/generate-cdr/generate-private-cdr-counts.sh
> [no ticket][risk=no] update cdr build

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/model/DbCriteriaLookup.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtil.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtilTest.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
> [RW-4781][risk=no] fix snomed node lookup

- ui/src/app/components/pdf-viewer.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
> [RW-4813][Risk=no] Make background of PDF viewer white

- ui/src/app/pages/workspace/invalid-billing-banner.tsx
Description:
A missing piece of #3443 - don't prompt locked-out users to update their billing project if billing upgrade is not possible.
---
> [RW-4711][risk=no]Missed an 'upgrade' communication

- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
adding test to CohortReviewController
> [RW-4781][risk=no] adding test to CohortReviewController

- ui/src/app/components/icons.tsx
> [risk=no][RW-4815] change icon color

- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
Description:
Bad copypasta from #3292 
---
> [risk=no][RW-4562]Fix: log sendInstitutionUserInstructions() correctly

- ui/src/app/pages/login/account-creation/account-creation-success.tsx
Set `font-size: 16x` for ' Your contact email is...' text to match 'Your All of Us account has been created.'
---
> [RW-4821][risk=no] Update font on congratulations page

- ui/src/app/components/lists.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-4831][Risk=no] Change to bullets

- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
> [RW-4819][risk=no]Characters over text for research background text box  should be red

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/login/sign-in.tsx
> [RW-4818][risk=no] Make 'username already taken' error message red

- api/build.gradle
Description:
Update [netty-codec to 4.1.46.FINAL ](https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-564897)(via netty-codec-http)
Update these 2 as suggested by Snyk:
---
> [risk=low]Update a few vulnerable packages

- ui/src/app/pages/workspace/workspace-edit-section.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-research-summary.tsx
Description:
Align Info Icon with synthetic CDR text box 
Update Font Size for header to 14
Remove margin after 2.1 to align What and if/Free
Align Label 
Align No options and note to have wrapped text 
---
> [noTicket][RISK=NO]Workspace Edit Page formatting issue

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-research-summary.tsx
> [RW-4820][risk=no] Text area with length limits

- ui/src/app/pages/homepage/quick-tour-modal.tsx
Description:
The quick tour will now handle the responsive layout correctly, this includes:
1. Proper scaling of the images without stretch/skew issues
2. No overflowing content in the modal
3. No layering issues with the buttons/images
4. No text overflowing into the button area
I ran this by Lou and he is ok with it, but we noted 2 things:
1. The mock was not intended for a responsive design
2. The styles do not match the mock in all cases
I will create a ticket to go over the quick tour and correct additional CSS issues and make it work well without a responsive design - right now the modal will not be centered on screen without some further tweaking to the styles.
---
> [risk=no][RW-4834]Quick Tour: fix overflow, scaling and layering issues

- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [risk=low][RW-4697]Set enableV3DataUserCodeOfConduct to true in all envs

- e2e/app/element/base-element.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/utils/test-utils.ts
Fixed xpath selectors for a number of web elements due to UI change.
> [no ticket][risk=no] Puppeteer test: Fix xpath selectors on Workspace edit form

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
lowercasing column names in data set builder
> [RW-4444][risk=no] lowercasing column names in data set builder

- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/login/account-creation/common.tsx
- ui/src/app/pages/profile/demographic-survey.spec.tsx
- ui/src/app/pages/profile/demographic-survey.tsx
> [RW-4851][Risk=no] Add optional and align optional styles

- .circleci/config.yml
Fixed bugs I introduced in my last config change.
> [no ticket][risk=no] Fix cache key regression in circleci config

- .circleci/config.yml
> [risk=no]TEMP increase Circle RAM to avoid OOM errors

- api/config/featured_workspaces_prod.json
> [risk=low][RW-4810]Feature two DEMO_PROJECTs in Prod

- ui/src/app/components/buttons.tsx
- ui/src/app/pages/homepage/homepage.tsx
Description:
This fixes external links to work with our styled anchor tags.
---
> [RW-4859][Risk=no] Fix links in homepage

- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
Restore an apparently useful log statement.
---
> [no ticket][risk=no] restore auth debugging line

- ui/src/app/cohort-search/overview/overview.component.tsx
> [RW-4876][risk=no] Fix cohort delete icon

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
I have not yet tested this locally.  I'll post screenshots when I do.
---
> [risk=low][RW-4857] Always display billing account dropdown in Create/Edit Workspace, and other logic changes

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java
New approach does not involve creating a key. This is safer and requires much fewer steps.
> [risk=no] describe-cluster: suggest safer and easier gsutil impersonation commands

- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-4828][Risk=no] Add link to Research Use Statement Questions

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/test/SearchRequests.java
Rolling back cohort query changes per bug in staging. Did a little QA locally and confirmed that the query now works in a notebook.
> [no ticket][risk=no] rolling back cohort query changes.

- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Click 'contact support' workspace Edit -> Billing section should open help desk widget.
---
> [RW-4885][RISK=NO][P2] contact support link in create workspace page should open support widget

- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
> [RW-4887][RISK=NO] Change copy for "Don't see your institutions?" link

- .github/PULL_REQUEST_TEMPLATE.md
I want to make the checklist request that UI changes be screencapped / screenshotted and shown PO/UX.
> [no ticket][risk=no] update PR template

- api/db-cdr/generate-cdr/make-bq-data.sh
> [RW-4899][risk=no] fixing survey counts

- ui/src/app/app-routing.module.ts
- ui/src/app/cohort-search/cohort-search.module.ts
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.html
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
> [RW-4889][risk=no] Folder icon on help sidebar

- api/build.gradle
- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/PopulateOpsUserAffiliations.java
Description:
Populate Verified Institutional Affiliation to the AouOps Institution for a set of users, given a source CSV
---
> [risk=no][RW-4801]New PopulateOpsUserAffiliations tool

- ui/src/app/pages/profile/profile-page.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
Strictly copyediting
---
> [risk=no]Change FREE credits to free credits

- .github/PULL_REQUEST_TEMPLATE.md
updating the PR checklist again.
> [no ticket][risk=no] Reminder to run E2E tests

- api/config/config_prod.json
Enabling RDR export on PROD. Every night at 9:00pm CT workbench will export researcher and workspace data(modified/created in last 24 hours) to RDR on PROD
---
> [RW-4221][RISK=MEDIUM] Enable feature flag enableRdrExport for RDR Export

- ui/src/app/pages/profile/profile-page.tsx
Description:
Fix a regression of #3375
For a user with $1.00 spend and a maximum of -$0.01 (weird value for a different test):
Currently on Test
This PR
---
> [risk=no][RW-4684]Use the common renderUSD() function to ensure negative values are $0

- api/libproject/devstart.rb
Clean up containers on oneoff command runs from project.rb. These were not really hurting much, but generated irrelevant log spam when running `docker-compose down` from dev-up death. The containers were always generated on dev-up due to the loadConfig and DB migrations that run before.
Before:
```
^CGracefully stopping... (press Ctrl+C again to force)                                                                                                                                                               
+ docker-compose down                                                                                                                                                                                                
Stopping api_api_1_537d4f09d8b9     ... …
```
> [RW-3609][risk=no] Use --rm for docker-compose run commands

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/profile/profile-page.tsx
- ui/src/app/pages/profile/profile-registration-step-status.tsx
- ui/src/app/utils/index.tsx
> [RW-4664][Risk=no] Update profile page to match mocks

- api/src/main/java/org/pmiops/workbench/cohortbuilder/mappers/CohortBuilderMapper.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewMapper.java
- api/src/main/java/org/pmiops/workbench/cohortreview/mappers/CohortAnnotationDefinitionMapper.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMapper.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetMapper.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetMapper.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionMapper.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionUserInstructionsMapper.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionalAffiliationMapper.java
- api/src/main/java/org/pmiops/workbench/institution/PublicInstitutionDetailsMapper.java
- api/src/main/java/org/pmiops/workbench/institution/VerifiedInstitutionalAffiliationMapper.java
- api/src/main/java/org/pmiops/workbench/profile/AddressMapper.java
- api/src/main/java/org/pmiops/workbench/profile/DemographicSurveyMapper.java
- api/src/main/java/org/pmiops/workbench/profile/PageVisitMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/utils/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/MapStructConfig.java
Set common properties of all our mappers:
- componentModel is "spring"
- target property missing behavior is ERROR. Output for failure looks like [this](https://gist.github.com/jaycarlton/ede90bcee7ec9af282ba9acc4e0f3059).
---
> [RW-4926][risk=no] Top-level MapStruct Config; unmapped target props are ERRORs

- .gitignore
> [risk=no][no ticket] Add missing generated upload extension to .gitignore

- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/login/account-creation/account-creation-survey.spec.tsx
> [risk=no] Small updates

- README.md
Karthik was perusing the README and requested we mention Terra here. Also fix some typos.
> [risk=no] Update Workbench intro blurb

- api/src/main/java/org/pmiops/workbench/api/InstitutionController.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/testing/stubs/institution-api-stub.ts
> [risk=moderate][RW-4972] Change checkEmail endpoint from GET to POST with email body

- .circleci/config.yml
> [risk=no] Use medium+ in Circle for api-bigquery-test

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
Send workspace creator information: id and name to rdr as Researcher hub need to display workspace owner information along with workspace details.
> [noTicket][risk=low]Send Workspace Creator information to RDR

- api/src/main/java/org/pmiops/workbench/db/model/DbInstitution.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/tools/src/main/java/org/pmiops/workbench/tools/LoadInstitutions.java
Description:
Also add a `@Transactional` hack to InstitutionServiceImpl because it threw mysterious NPEs without it.  See https://precisionmedicineinitiative.atlassian.net/browse/RW-4968 for more details. 
---
> [RW-4952] Modify LoadInstitutions to enable updates

- api/src/main/java/org/pmiops/workbench/db/dao/InstitutionUserInstructionsDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionUserInstructions.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionMapper.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionUserInstructionsMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/institution/InstitutionMapperTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
- ui/package.json
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-institution.tsx
- ui/src/app/pages/admin/admin-review-workspace.spec.tsx
- ui/src/app/pages/admin/admin_institution.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
- ui/src/testing/stubs/institution-api-stub.ts
- ui/yarn.lock
- This PR is just to list **all institution details**. There will be another PR that will have the edit/add institution page
- The plus icon will not do anything and also the institution name are not hyperlink in this PR - Part of next PR
- If the number of email domain/ address for any institution is more than 4 just show the top 4 and have ... at the end
- if the email domain/address will not fit in the width of the table cell replace the overflow text with ...
---
> [RW-4258][risk=low] Admin UI for List Institute entities for affiliation

- api/db/settings.gradle
- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/webapp/WEB-INF/cron_default.yaml
Based on conversation on the spreadsheet I've made a few schedule adjustments. I've also tried to elaborate on the descriptions where I felt those weren't obvious at a glance.
I'll have to check on Monday if there's a good way to test this locally. I suspect I'll need to deploy to test and keep an eye on it.
*TIL*
- the AppEngine section in the Cloud Console has a nifty page describing the cron jobs, which displays the description from the cron.
---
> [RW-4904][risk=no] cron job schedule updates

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
forgot spotless on https://github.com/all-of-us/workbench/pull/3562
Description:
---
> [no ticket][risk=no] spotless

- deploy/libproject/deploy.rb
Currently the only thing this is used for is to determine what the default behavior should be for logging to Jira.
> [risk=no] Include preprod in deployed projects list

- api/config/cdr_versions_preprod.json
Already published per https://precisionmedicineinitiative.atlassian.net/browse/PD-5122
@freemabd to confirm the database index used here.
> [risk=low] Add Q4R4 to preprod CDR configs

- ui/src/app/pages/data/data-page.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/recent-workspaces.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/account-creation/account-creation-options.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-library.tsx
- ui/src/assets/json/help-sidebar.json
NIH Found some grammatical mistakes:  
Have created just one PR for all fix so its easier for cherry picking in case it does not make it to weekly release 
This PR contains fix for all the points the screen shot for some are as follows.
- Fix for 7, 8 , 9 ,10 ,11, 12
-  Issue Number: 3, 6, 19, 20, 21, 22, 23
-  Fix  for Issue: 24, 25, 26, 27, 28
- Fix for Issue 29, 30 ,31, 32 ,33 
- Issue number: 34, 35 , 36 , 37 and 38
- Fix for 39,40
-  Fix for 42, 43,44 and 445
- Fix for 49
---
> [RW-4971][RISK=NO]Fix grammatical mistakes - NIH findings

- api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
- api/libproject/devstart.rb
cleaning up code, renamed all prep tables to have "prep_" as the prefix, fixed issue with cdr_date
> [RW-4936][risk=no] Prefixing tables with "prep" and fixing date issue

- e2e/app/page/home-page.ts
- e2e/tests/home/home-page.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
Puppeteer tests were failing after changing the label See All Workspace and description.
> [RW-4971][RISK=NO]Fix test for NIH Findings

- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
NIH Findings row number 9 change update the second bullet to say 
I have read, understand, and agree to the Terms  of Use described above.
---
> [RW-4971][RISK=NO] Fix grammatical mistakes - NIH findings

- e2e/.env.sample
- e2e/README.md
- e2e/app/component/ellipsis-menu.ts
- e2e/app/component/workspace-card.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/google-login.ts
- e2e/app/page/home-page.ts
- e2e/jest-puppeteer.config.js
- e2e/jest.config.js
- e2e/jest.test-setup.ts
- e2e/puppeteer-custom-environment.ts
- e2e/resources/workbench-config.ts
- e2e/tests/home/home-page.spec.ts
- e2e/tests/workspace/workspace-clone.spec.ts
- e2e/tests/workspace/workspace-ui.spec.ts
- e2e/utils/save-file-utils.ts
- e2e/utils/str-utils.ts
Running all tests locally have passed okay.
> [no ticket][risk=no] Running puppeteer tests in circleci

- api/config/cdr_versions_test.json
adding new synth cdr to test per ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-4987
> [RW-4987][risk=no] adding new synth cdr to test

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/components/inputs.tsx
- ui/src/app/pages/admin/admin-user-bypass.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/admin/admin-users.spec.tsx
- ui/src/app/pages/admin/admin-users.tsx
> [risk=no][RW-4954] User Admin - User Information Page

- ui/src/app/pages/login/login.tsx
Description:
Added new link per the mock in [RW-4802](https://precisionmedicineinitiative.atlassian.net/browse/RW-4802)
Added screenshot after comment.
---
> Add trouble signing in link

- api/src/integration/java/org/pmiops/workbench/google/CloudResourceManagerServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerServiceImpl.java
This caused an NPE in the test environment for users with access to 0 projects.
> [RW-4906][risk=no] bulkProjectAudit: handle 0 projects case, add regression test

- e2e/app/component/create-criteria-modal.ts
- e2e/app/component/dialog.ts
- e2e/app/component/ellipsis-menu.ts
- e2e/app/component/select-menu.ts
- e2e/app/component/tiered-menu.ts
- e2e/app/element/base-element.ts
- e2e/app/element/xpath-defaults.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/data-page.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/workspace/workspace-clone.spec.ts
- e2e/utils/str-utils.ts
- e2e/utils/waits-utils.ts
> [RW-4383][risk=no] Puppeteer Cohort test case

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
This is the latest default version for Leo. Will discuss having a better method for automatically getting these updates in the future, e.g. a floating image label: https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/resources/reference.conf#L166
> [RW-4972][risk=low] Update to latest welder hash

- e2e/app/component/create-criteria-modal.ts
- e2e/app/component/dialog.ts
- e2e/app/component/select-menu.ts
- e2e/app/component/tiered-menu.ts
- e2e/app/element/button.ts
- e2e/app/element/checkbox.ts
- e2e/app/element/clr-icon-link.ts
- e2e/app/element/link.ts
- e2e/app/element/radiobutton.ts
- e2e/app/element/select.ts
- e2e/app/element/textarea.ts
- e2e/app/element/textbox.ts
- e2e/app/element/web-component.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/data-page.ts
- e2e/app/page/google-login.ts
- e2e/app/page/home-page.ts
- e2e/app/page/profile-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/misc/sidenav.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/utils/test-utils.ts
Renamed `forLabel` function name to `findByName` to be clearer.
> [no ticket][risk=no] Puppeteer function rename

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
Fixes issue caused by changes to the Dropdown component after upgrading PrimeReact version.
> [RW-5017][risk=no] Fix dropdowns on CB modifiers page

- e2e/app/component/data-resource-card.ts
- e2e/app/component/dialog.ts
- e2e/app/component/ellipsis-menu.ts
- e2e/app/component/table.ts
- e2e/app/component/tiered-menu.ts
- e2e/app/component/workspace-card.ts
- e2e/app/element/base-element.ts
- e2e/app/element/clr-icon-link.ts
- e2e/app/element/xpath-defaults.ts
- e2e/app/page-identifiers.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/data-page.ts
- e2e/app/page/workspace-about-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/jest.config.js
- e2e/jest.test-setup.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/cohorts/cohorts-ui.spec.ts
- e2e/tests/workspace/workspace-clone.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/tests/workspace/workspace-ui.spec.ts
- e2e/utils/test-utils.ts
- e2e/utils/waits-utils.ts
Adding new Cohort test cases and supporting changes that included new classes, functions and modified functions.
- new `cohort-ui.spec.ts`
- new and modified `cohort-create.spec.ts`
supporting changes:
- new `workspace-about-page.ts`
- new `cohort-participants-group.ts`
- new `table.ts`
- new `data-resource-card.ts`
- modified `ellipsis-menu.ts` to support `data-resource-card`
- more functions
> [no ticket][risk=no] Puppeteer cohort tests

- ui/src/app/components/side-nav.tsx
> [no ticket][risk=no] buildfix for updated authority

- README.md
- api/docs/developer-system-initialization.md
- api/docs/developer-system-requirements.md
Went to fix a broken link and one thing led to another. Goal is to make the main README mostly an index.
Description:
---
> [no ticket][risk=no] clean up README a bit

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/demographics/demographics.component.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- Fix NumberInput component to return input of type number instead of text
- Replace all instances of standard number inputs to use NumberInput
---
> [RW-4947][risk=no] Refactor standard number inputs to use NumberInput component

- api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
- api/tools/src/main/java/org/pmiops/workbench/tools/WorkspaceExportRow.java
These were requested by Karthik.
> [risk=no] Add additional metadata fields for user/workspace export

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
1) Adding validation for cohort definition on save
2) Adding test case for above
> RW-5019 adding validation for cohort def on save

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
Solves the following bugs:
- trim whitespaces from email Domain and email Address
- If DUA is null (can be true for existing Institution), default to MASTER only for EDIT Institution.
> [noTicket][RISK=MEDIUM] Admin UI Institution Bug

- api/libproject/devstart.rb
Description:
Followup to #3648
---
> [risk=no] remove elastic from start/stop_api_reqs

- .circleci/config.yml
Break up a large PR (#3641) into smaller separate PRs. This PR enable updates api gradle cache and its version in CircleCI.
> Addition of .gradle directory to store in api gradle cache

- api/config/cdr_versions_perf.json
- api/config/cdr_versions_preprod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
Promote new synth CDR to staging/stable/perf/preprod
Need to communicate this will others before approving.
> [RW-5081][risk=no] promote new synth CDR

- .circleci/config.yml
Disable e2e tests until billing project issue is resolved. 
https://precisionmedicineinitiative.atlassian.net/browse/RW-5080
> [no ticket][risk=no] Disable e2e tests in CircleCI

- api/config/config_test.json
Description:
Reverts #3660 
---
> [risk=no][RW-5080] Restore test billing buffer capacity to 100

- e2e/app/component/data-resource-card.ts
- e2e/app/component/dialog.ts
- e2e/app/component/workspace-card.ts
- e2e/app/element/base-element.ts
- e2e/app/element/checkbox.ts
- e2e/app/element/radiobutton.ts
- e2e/app/element/select.ts
- e2e/app/element/xpath-defaults.ts
- e2e/app/page-identifiers.ts
- e2e/app/page/analysis-page.ts
- e2e/app/page/authenticated-page.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/data-page.ts
- e2e/app/page/dataset-build-page.ts
- e2e/app/page/dataset-save-modal.ts
- e2e/app/page/notebook-preview-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/jest.test-setup.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/cohorts/cohorts-ui.spec.ts
- e2e/tests/datasets/dataset-create.spec.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
- e2e/tests/workspace/workspace-clone.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
New Puppeteer tests that covers following features:
* Create DataSet without Export to Notebook
* Export dataset to notebook in Python language
* Edit a DataSet
* Rename a DataSet
* Delete a DataSet
* Create new cohort
Additional changes in some existing files were required in order to support writing of new tests.
> [RW-4383][risk=no] Puppeteer DataSet test

- api/build.gradle
- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/RetryConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/shibboleth/ShibbolethConfig.java
- api/src/main/java/org/pmiops/workbench/shibboleth/ShibbolethRetryHandler.java
- api/src/main/java/org/pmiops/workbench/shibboleth/ShibbolethService.java
- api/src/main/java/org/pmiops/workbench/shibboleth/ShibbolethServiceImpl.java
- api/src/main/resources/shibboleth.yaml
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/shibboleth/ShibbolethServiceImplTest.java
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/environments/environment-type.ts
- ui/src/testing/default-server-config.ts
This PR adds a feature-flagged connection to the new Shibboleth service, which is operated by Terra as a separate API endpoint from the existing Firecloud-Orchestration API that we currently connect to.
Most lines of code are boilerplate in support of the new API client and supporting services & config. Only two new pieces of logic are introduced: (1) `ProfileController` checks the feature flag before deciding which service to call in order to update the Shibboleth token, and (2) `registration-dashboard` checks the feature flag to decide where to redirect the user for the Shibboleth-eRA Commons login flow.
I tested this from a local server, and both the login flow and token submission worked as expected. Note that in the dev environment, a user is not auto-redirected to …
> [RW-4257][risk=moderate] Add support for the new Shibboleth service

- e2e/app/component/concept-domain-card.ts
- e2e/app/component/data-table.ts
- e2e/app/component/table.ts
- e2e/app/element/checkbox.ts
- e2e/app/element/xpath-defaults.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/conceptset-actions-page.ts
- e2e/app/page/conceptset-save-modal.ts
- e2e/app/page/conceptset-search-page.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/data-page.ts
- e2e/app/page/dataset-build-page.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/conceptsets/conceptset-create.spec.ts
- e2e/tests/datasets/dataset-create.spec.ts
New `conceptset-create.spec.ts` test and supporting page objects files.
> [RW-4398][risk=no] Puppeteer new Concept Sets tests

- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
Updated validation messages for new workspace creation regarding character limits. The messages are set using the validation library where no additional formatting is needed.
---
> [risk=NO][RW-4880]Update validation messages for character limits

- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
Addressing feedback on code comments that was received for[ RW-4880](https://github.com/all-of-us/workbench/pull/3691) after merging.
No code changes in this PR - only comment changes
---
> [risk=no][no ticket]Update comments for RW-4880

- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
Description:
No ticket.  Friendlier response when a user name is not found.
---
> [risk=no] 404 instead of 500 for user not found

- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
@freemabd1 please hold off on next week's release until we get a go/no-go on the feature
Getting confirmation from Karthik before merging this.
Depends on a bug fix: https://github.com/all-of-us/workbench/pull/3695
> [RW-4696][risk=no] Enable footer in all environments

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/workspace/workspace-research-summary.tsx
- ui/src/app/utils/strings.ts
> Up min char counts per new caps requirements

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/SumoLogicController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/test/java/org/pmiops/workbench/api/SumoLogicControllerTest.java
This flag isn't needed anymore, as the Sumo event handling has been live in prod for awhile now.
> [RW-4686][risk=no] Remove Sumo event handling flag

- e2e/app/component/data-resource-card.ts
- e2e/app/component/dialog.ts
- e2e/app/component/workspace-card.ts
- e2e/app/element/base-element.ts
- e2e/app/page-identifiers.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/data-page.ts
- e2e/app/page/workspace-about-page.ts
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/cohorts/cohorts-rename.spec.ts
- e2e/tests/conceptsets/conceptset-create.spec.ts
- e2e/tests/datasets/dataset-create.spec.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
- e2e/utils/test-utils.ts
- e2e/utils/waits-utils.ts
To increase automation test coverage, this new test covers testing of following new actions:  
* Modify (delete a Group)
* Rename Cohort.
Also, new Criteria (Demographics Age) is used to build the Cohort.
`cohorts-rename.spec.ts` test result:
all tests results:
> [RW-5121][risk=no] Puppeteer e2e Cohort test

- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
> [RW-5055][RISK=low]  DataSetController - use CdrVersionService instead of cdrVersionDao

- .circleci/pr-skip-ci.sh
`CIRCLE_PULL_REQUEST` param is null on master branch job.
> [no ticket][risk=no] CircleCI null env variable

- e2e/app/component/data-resource-card.ts
- e2e/app/component/data-table.ts
- e2e/app/component/dialog.ts
- e2e/app/component/table.ts
- e2e/app/element/button.ts
- e2e/app/element/input-number.ts
- e2e/app/element/xpath-defaults.ts
- e2e/app/page/cohort-build-page.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/cohort-participant-detail-page.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/cohort-review-modal.ts
- e2e/app/page/cohort-review-page.ts
- e2e/app/page/data-page.ts
- e2e/app/xpath-options.ts
- e2e/tests/cohorts/cohorts-review.spec.ts
- e2e/utils/test-utils.ts
Puppeteer automation test covers Create Cohort, Create Review Set, Delete Cohort, and Cohort pages navigation.
> [no ticket][risk=no] Puppeteer Cohort Review test

- ui/src/app/app-routing.module.ts
- ui/src/app/app-routing.tsx
- ui/src/app/app.module.ts
- ui/src/app/components/app-router.tsx
- ui/src/app/pages/app/component.ts
- ui/src/app/pages/profile/data-user-code-of-conduct.tsx
- ui/src/app/services/sign-in.service.ts
This got a bit messy, some of the stuff was still needed. I ripped out the DUCC changes only, but left in some of the infra. This PR should be reverted and fixed forward with the real fix.
> [RW-5127][risk=no] Revert DUCC routing changes

- e2e/app/component/share-modal.ts
- e2e/app/page/workspace-about-page.ts
- e2e/resources/workbench-config.ts
- e2e/tests/workspace/workspace-share.spec.ts
- ui/src/app/pages/workspace/workspace-share.tsx
This is intended as a regression test for two separate bugs:
- https://github.com/all-of-us/workbench/pull/3694
- https://github.com/all-of-us/workbench/pull/3695
> [RW-4696][RW-5013][risk=no] Initial workspace sharing puppeteer test

- api/tools/src/main/java/org/pmiops/workbench/tools/institutions/OpsUser.java
- api/tools/src/main/java/org/pmiops/workbench/tools/institutions/Researcher.java
- api/tools/src/main/java/org/pmiops/workbench/tools/institutions/UserToAffiliate.java
Description:
Updates for https://github.com/all-of-us/workbench-devops/pull/46
---
> [risk=no][RW-4911] A few fixes for latest input file

- api/db-cdr/generate-cdr/make-bq-data.sh
- ui/src/app/cohort-search/utils.ts
- ui/src/app/pages/data/concept/concept-navigation-bar.tsx
- ui/src/app/pages/homepage/quick-tour-modal.tsx
Change all instances in cohort builder, cohort review and concept set selector. 
---
> [RW-3667][risk=no] Change "Measurements" to "Labs and Measurements"

- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java
This PR moves
1. conceptService into the conceptSetService
2. conceptSetMapper into the conceptSetService
> [RW-5057][risk=no] move conceptSetMapper into ConceptSetService

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
> [risk=no] remove unused ProfileController.getBillingProjects()

- e2e/tests/misc/sidenav.spec.ts
zendesk popup testing is not required.
> [no ticket][risk=no] Puppeteer: Remove contact-us test in sidenav.spec.ts

- ui/src/app/pages/workspace/research-purpose.tsx
- ui/src/app/utils/analytics.ts
As part of this PR the Review Research Purpose Prompt actions "LOOKS GOOD" and "UPDATE" will be tracked with a new  Category "Workspace update prompt"
---
> [RW-5109][RISK=LOW] set up google analytics for prompt to update research purpose

- e2e/app/component/navigation.ts
- e2e/app/element/base-element.ts
- e2e/app/page/cohort-criteria-modal.ts
- e2e/app/page/conceptset-search-page.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/tests/home/home-page.spec.ts
- e2e/tests/workspace/workspace-ui.spec.ts
- e2e/tsconfig.json
- e2e/utils/test-utils.ts
Attempt to make code more readable: Rewrote asyn/await calls with [Promises chaining](https://javascript.info/promise-chaining).
Rename `pressReturnKey()` function to `pressReturn`.
Rename `tabKey()` function to `pressTab`.
Test were not changed.
> [no ticket][risk=no] Puppeteer refactor: base-element.ts edit

- e2e/app/component/ellipsis-menu.ts
- e2e/app/component/share-modal.ts
- e2e/app/element/base-element.ts
- e2e/app/page/analysis-page.ts
- e2e/app/page/data-page.ts
- e2e/jest-puppeteer.config.js
- e2e/tests/cohorts/cohorts-create.spec.ts
- e2e/tests/workspace/workspace-share.spec.ts
- e2e/utils/test-utils.ts
Add a new test `Workspace READER cannot share edit or delete workspace` in `workspace-share.spec.ts`.
> [RW-5144][risk=no] Puppeteer test: workspace shared as READER

- ui/src/app/pages/workspace/workspace-card.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/pages/workspace/workspace-list.spec.tsx
> [risk=no] replace deprecated require.requireActual()

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- ui/src/app/pages/data/data-set/dataset-resource-card.tsx
This PR fixes the dataset rename issue cause when reloading light weight dataset objects.
> [RW-5079][risk=no] fixing DataSet rename

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
adding is_deceased column to cb_search_person table
> [RW-5215][risk=no] adding is_deceased column to cb_search_person table

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in ICD10CM and ICD10PCS criteria
> [RW-5231][risk=no] adding in ICD10CM and ICD10PCS criteria

- e2e/app/element/base-element.ts
- e2e/app/page/data-page.ts
- e2e/app/page/dataset-save-modal.ts
- e2e/tests/datasets/dataset-create.spec.ts
Bug https://precisionmedicineinitiative.atlassian.net/browse/RW-5079 fixed.
> [no ticket][risk=no] Puppeteer enable rename dataset test code

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
- api/libproject/devstart.rb
adding in CPT4 codes to criteria generation script and fixing a few bugs
> [RW-5243][risk=no] adding in CPT4 codes to criteria generation script

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in physical measurement criteria
> [RW-5244][risk=no] adding in physical measurement criteria

- api/config/featured_workspaces_prod.json
As per request from Francis we need to publish workspace Demo - Cardiovascular Risk Scoring under Demo projects
I am already an OWNER of this workspace and have clicked the Publish Button.
Adding workspace details to config files
---
> [RW-5175][RISK=LOW]  Featured Workspace: Publish the *Demonstration Projects* in the description

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
removing answer_concept_id from survey query
> [RW-5150][risk=no] removing answer_concept_id from survey query

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/testing/stubs/data-set-api-stub.ts
Removing DataSetController#getDataSetsInWorkspace
> [RW-5167][risk=no] removing unused api call

- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/conceptset-save-modal.ts
- e2e/jest.test-setup.ts
- e2e/utils/waits-utils.ts
Small fixes to address flaky tests related to ui asynchronous tasks response time.
And, revert `jest.test-setup.ts` changes made in https://github.com/all-of-us/workbench/pull/3768.
> [no ticket][risk=no] Puppeteer fix broken tests

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
- api/libproject/devstart.rb
> [RW-5245][risk=no] adding in PPI survey criteria

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in demographics criteria. Removed parent nodes from demographics as they aren't needed
> [RW-5254][risk=no] adding in demographics criteria

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in visit_occurrence criteria
> [RW-5255][risk=no] adding in visit_occurrence criteria

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in snomed source condition criteria and changing name of prep_concept_ancestor_temp to prep_ancestor_staging
> [RW-5282][risk=no] adding in snomed source condition criteria 
