all-of-us/workbench

- api/.swagger-codegen-ignore
- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/auth/UserAuthentication.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/test/Providers.java
Generating FireCloud API from Swagger definition.
> Adding /me endpoint.

- .gitignore
- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/CohortController.java
- api/src/main/resources/workbench.yaml
Adding fields to cohort resource.
> Changing path of cohorts endpoint to include namespace.

- .circleci/config.yml
- ci/Dockerfile.circle_build
- ci/README.md
- ci/deploy.sh
Add node to path
Use our own docker image to build
> Use our own build image

- .gitignore
- api/build.gradle
- api/db/changelog/db.changelog-1.xml
- api/src/main/java/org/pmiops/workbench/Application.java
- api/src/main/java/org/pmiops/workbench/db/dao/CdrVersionDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/model/CdrVersion.java
- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/resources/application.resources
- api/src/main/webapp/WEB-INF/appengine-web.xml
Adding user table, foreign keys to it from workspace and cohort creator.
> JPA clases for initial entities

- api/db/setup_local_vars.sh
- api/db/setup_vars.sh
- ci/deploy.sh
Changing setup_vars.sh and setup_local_vars.sh to default to system env vars.
> Removing generate shell command from deploy.sh; it is run in api gradle.

- api/db/vars.env
- api/libproject/devstart.rb
MySQL doesn't like it if you set the appropriate password environment variable when starting it up
> Fix local db

- .gitignore
- api/db/build.gradle
- api/db/run-migrations.sh
- api/db/vars.env
- api/libproject/devstart.rb
(Next step will be using run-cloud-migrations from Circle when doing autopush.)
> Adding drop-cloud-db, run-cloud-migrations, connect-to-cloud-db commands.

- api/src/main/java/org/pmiops/workbench/api/CohortController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
(It's no longer required that the UI calls the /me endpoint before doing stuff.)
Removing logic that creates a workspace when one doesn't exist in CohortController.
> Fixing User provider to create User row when one doesn't exist.

- ui/src/app/views/cohort-edit/component.html
- ui/src/app/views/cohort-edit/component.spec.ts
- ui/src/app/views/cohort-edit/component.ts
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
Deployed version at:
https://brubenst---pr-dot-all-of-us-workbench-test.appspot.com/
> Implemented mutex for add/save buttons to ignore clicks after the first.

- .circleci/config.yml
- api/libproject/devstart.rb
- ci/Dockerfile.circle_build
- ci/deploy.sh
Adding run_with_creds and run_with_cloud_sql_proxy for common logic.
Changing Circle deploy.sh to run cloud migrations before deploying changes.
> Adding creds_file option to commands.

- ci/deploy.sh
> Changing deploy script to use all-of-us-workbench-test, only

- api/build.gradle
- api/gradle/wrapper/gradle-wrapper.properties
- api/src/test/java/org/pmiops/workbench/api/WorkspaceControllerTest.java
- api/src/test/resources/application.properties
(More tests to come, but wanted to get this framework in place first.)
> First test of controller logic using Liquibase, H2, etc.

- api/libproject/devstart.rb
Switching from Proc.new to lambda
> Passing in command to show in usage statement.

- ui/src/helper-functions.ts
Adapted from Brew -- thanks for the description!
> Add doc to Date helpers.

- .circleci/config.yml
- api/db/run-migrations.sh
- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/src/dev/server/Dockerfile
- ci/Dockerfile.circle_build
... since it never makes sense to run it inside of a docker container.
> Turn off the Gradle daemon by default

- api/docker-compose.yaml
exposing port 8001 so we can connect a debugger.
> exposing port 8001 so we can connect a debugger.

- hooks/apply-git-secrets.sh
I wanted to try to make git secrets more JSON specific, so I updated the private key and private key id to be exactly the same as a JSON key.
> Updated git secrets to be more JSON specific.

- api/src/main/resources/workbench.yaml
> Add description doc for Cohort.criteria in Swagger definition.

- client/py/README.md
I confused my markup languages.
> Fix formatting in client README.

- api/db/changelog/db.changelog-4.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/WorkspaceController.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspaceControllerTest.java
- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
Dan and I had some discussion and think that we can just have a boolean column for each research purpose in the database, because it makes it easy to query for.
> Initial version just to add the concept of a research purpose to a workspace

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/WorkspaceController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspaceControllerTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- ui/package-lock.json
- ui/src/app/views/workspace-edit/component.ts
Right now this uses the all-of-us-broad project always (passed up from the UI.)
Once user registration is done, we can start using the billing project created for the user.
> Creating FC workspace when creating workspace in AofU.

- api/libproject/devstart.rb
- api/src/main/webapp/WEB-INF/logging.properties
Adding logging.properties in the hopes of capturing logs in cloud.
> Fixing commands to activate service account before using gsutil.

- api/config/config_test.json
- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
Also adds some explanations around GDS API usage.
Can someone else run `./project.rb update-cloud-config` for me? I'll follow-up with a PR to fix it so it works on my machine.
> Make GSuite domain configurable

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace/component.ts
This is a followup to the PR for initial notebook cluster creation, to move more of the logic into the API.
> Move more logic into API from UI for Notebook Clusters

- .circleci/config.yml
- api/build.gradle
As just removing them from starter-web wasn't actually removing them from the dependencies.
> Adding excludes to other spring boot dependencies as well

- .circleci/config.yml
- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SubjectCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/AbstractQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CriteriaQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/GroupCodesQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/api/BigQueryBaseTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/SubjectCounterTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/CriteriaQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/GroupCodesQueryBuilderTest.java
- api/src/test/resources/bigquery/schema/concept.json
- api/src/test/resources/bigquery/schema/condition_occurrence.json
- api/src/test/resources/bigquery/schema/demo_criteria.json
- api/src/test/resources/bigquery/schema/icd9_criteria.json
- api/src/test/resources/bigquery/schema/measurement.json
- api/src/test/resources/bigquery/schema/person.json
- api/src/test/resources/bigquery/schema/procedure_occurrence.json
Fixed bugs created by google-cloud-bigquery:0.26.0-beta
> Freemabd1/rw 197 - Fixed bugs created by google-cloud-bigquery:0.26.0-beta

- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/model/Workspace.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
Changing workspace logic to handle null reviewRequest value properly.
> Adding UserDao.findUserWithAuthorities(); using it where authorities are needed.

- api/libproject/devstart.rb
- api/tools/build.gradle
- api/tools/src/main/java/org/pmiops/workbench/tools/SetAuthority.java
What do you think of this approach for handling auth and CloudSQL proxy setup/teardown? To me a collection of related things you have to do before running and then after running => an object to encapsulate those things. I was trying to do it just with Ruby blocks, but couldn't get it to gel.
This implementation isn't done -- I still need to make the do_run_with_creds part happen for my new GcloudContext -- but it's close enough to demonstrate the approach.
Upside is that I can do:
```
workbench$ api/project.rb set-authority --help
Usage: ./project.rb set-authority [options]
--project [PROJECT]          Project to create credentials for (e.g. all-of-us-workbench-test)
--account [ACCOUNT]          Account to use when creating credentials (your.name@pmi-ops.org); use this or --creds_file …
```
> Add script to set authorities. Convert to object in Ruby to manage auth/proxy context.

- ci/deploy.sh
(Not sure if this will work, but at least the echo command should make it clearer what's going on...)
> Attempt to fix api build

- ci/deploy.sh
Attempt #2: move everything between setting VERSION and the deploy step above setting VERSION.
(Theory -- one of the other API commands is somehow resetting it.)
> Trying to fix build again

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
Changing clients of Provider<User> to handle null case.
> Removing initialization of User in WebMvcConfig.

- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/Utils.java
Fixing dev project creation logic to break loop when project already exists.
Changing prefix in test to a new value (so old projects are ignored.)
> Changing to use SA creds for FC interactions, too (as application default creds don't work in cloud.)

- ui/src/app/cohort-search/cohort-builder/cohort-builder.component.html
- ui/src/app/cohort-search/cohort-builder/cohort-builder.component.ts
- ui/src/app/cohort-search/redux/store.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/search-group-item/search-group-item.component.ts
- ui/src/app/cohort-search/search-group/search-group.component.html
- ui/src/app/cohort-search/search-group/search-group.component.ts
Group and total counts now display a spinner if there is a network request in flight that would update them.
> Show spinners instead of outdated counts

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
This adds an error to creating a workspace. It doesn't do any parsing on error code or text yet, but I don't know if we want to aim to add that now, or add it to the backlog as a non internal-launch ticket. (This time with rebasing)
> Add error page to workspace creation

- ui/package-lock.json
- ui/src/app/app.module.ts
- ui/src/app/views/account-creation/component.css
- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.ts
- ui/src/app/views/app/component.css
- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.spec.ts
- ui/src/app/views/app/component.ts
Ideally, this is an assault on your senses. That way, it won't stick around very long in its current form.
> Super rough UI for account creation

- libproject/workbench.rb
https://github.com/dmohs/project-management/commit/35c9fb1e363536892754bd02584c0dc704e62015
https://github.com/dmohs/project-management/commit/71c59f07184260d7a94fd5a1f2eab5241bfcbd21
https://github.com/dmohs/project-management/commit/e169447c431242c45e337cf47330be44b01e5fc2
https://github.com/dmohs/project-management/commit/e68c175f3d7c4020af769975a6c436c7571695d1
^^^ @danqrodney
> Update scripts dependency to latest

- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Forgot to push this before merging. It was included in my test deployment. Submitting TBR to fix master.
> XML syntax fix for db configuration.

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/workbench.yaml
stubbed out api call for criteria tree quick search.
> RW-241 stubbed out api call for criteria tree quick search.

- ui/src/app/cohort-search/criteria-wizard/leaf/leaf.component.ts
- ui/src/app/cohort-search/criteria-wizard/quicksearch-results/quicksearch-results.component.html
- ui/src/app/cohort-search/criteria-wizard/quicksearch-results/quicksearch-results.component.ts
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.html
- ui/src/app/cohort-search/criteria-wizard/tree/tree.component.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
Small refactor that should significantly decrease the lag I've been feeling with large numbers of selections by decreasing the amount of data being passed around.
> Faster isSelection logic

- ui/src/app/views/cohort-edit/component.spec.ts
- ui/src/app/views/workspace-share/component.css
- ui/src/app/views/workspace-share/component.html
- ui/src/app/views/workspace-share/component.spec.ts
- ui/src/app/views/workspace-share/component.ts
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/cohort-service-stub.ts
- ui/src/testing/stubs/workspace-service-stub.ts
Default the domain: Would like to change this to use based on environment.
Added non-existant email error message.
Added loading wheel.
> Prettify the sharing page.

- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- api/tools/build.gradle
Tested by creating a new account, signing-in, then creating a workspace.
> Point API to dev instance of FireCloud

- api/src/main/resources/application.properties
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Using tomcat database connection pool properties, as I think that's what's
actually being used in test.
> [RW-235] Moving properties for database connection to application.properties.

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/home-page/component.html
- ui/src/app/views/home-page/component.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-share/component.ts
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
The goal is to send along some other information with getWorkspace, that we get for free from FC, such as the current user's access level to the workspace.
I'm starting with the simplest possible piece as a building block for adding actual access controls.
> Change to workspace response.

- ui/src/app/views/home-page/component.html
- ui/src/app/views/home-page/component.ts
I ended up using star for owner, because Clarity doesn't have a crown icon, but I figure this will probably change some as Lou gets to defining our branding a bit more.
> Add permissions report to workspace list status

- api/build.gradle
- api/src/integration/java/org/pmiops/workbench/BlockscoreServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/BlockscoreService.java
- api/src/main/java/org/pmiops/workbench/BlockscoreServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
Next steps:
* add BlockScore status to /me response
* add endpoint for user to submit verification data
> Initial integration of BlockScore

- api/src/main/resources/workbench.yaml
Fixes master CI. I submitted before pulling/rebasing, so I didn't catch these newly introduced issues.
> Fix swagger validation errors

- api/build.gradle
Fixes `./project.rb dev-up` for me.
> Snap to last working BigQuery mvn version

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
Added api call for 
**getParticipantCohortStatus(String workspaceNamespace,
String workspaceId,
Long cohortReviewId,
Long participantId)**
/api/v1/workspaces/{workspaceNamespace}/{workspaceId}/review/{cohortReviewId}/participants/{participantId}
> Freemabd1/rw 309 - add api call to fetch a CohortParticipantStatus

- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/bug-report-service-stub.ts
- ui/src/testing/stubs/cohort-service-stub.ts
- ui/src/testing/stubs/profile-service-stub.ts
- ui/src/testing/stubs/workspace-service-stub.ts
Today I attempted to upgrade to Angular 5.0.  The upgrade failed, but I did notice during the process that a future version of typescript than the one we're tied to will complain without the following edits, and I'm loathe to come out of today's adventure into Angular CLI without _something_ to show for it.  So this is a bit of future-proofing; providing types to some observables so there will be that much less to do when we _can_ finally upgrade to Angular 5 (and hence typescript 2.5)
> Pre Angular 5 Typings

- ui/package-lock.json
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/app/component.css
- ui/src/app/views/app/component.html
- ui/src/app/views/app/component.ts
- ui/src/app/views/id-verification-page/component.html
- ui/src/app/views/id-verification-page/component.ts
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.ts
Terrible but functional UI allowing users to verify their own identity. Deployed here for your convenience: https://dmohs-dot-all-of-us-workbench-test.appspot.com/
> ID Verification UI

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
Background: https://docs.google.com/document/d/1RfTkoceNYL0l76qGWX9RLlKdPcI6rNdGywkHtzqvpZU
CC @danqrodney
> [RW-285] Define clone API

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Clones workspace metadata and the Firecloud workspace.
Still TODO in follow-up PRs:
- Copy cohorts
- Copy notebooks and/or GCS scratch files
> [RW-285] Basic CloneWorkspace implementation

- api/db/changelog/db.changelog-16.xml
- api/db/changelog/db.changelog-17.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
ethics training, demographics survey response.
Changing ID verification endpoint to return profile (which may have its data access level updated as a result of ID verification.)
> [RW-281] Replacing register endpoint with endpoints for submitting TOS consent,

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- At creation time, accept only a whitelist of user-specified fields, i.e. exclude server-generated or restricted access fields such as timestamps and research purpose approval
- Improve validation and reduce NPEs
- `ConflictException` if the workspace already exists
- Fix typo in `Clone` which set the approval time rather than the request time.
Before this change, a client could simply send a creation request with `workspace.researchPurpose.approved = true`.
> [RW-248] Fix create/clone issues

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Will be localized and used in notebooks.
> Making workspace creation write out a config JSON file to GCS.

- ui/src/app/services/sign-in.service.ts
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
This is still a bit raw, but this successfully removes the need for any of the manual cookie setting in notebooks.
> Seamless notebook opening

- ui/package-lock.json
- ui/package.json
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/google-analytics-events.service.ts
- ui/src/index.html
Adding emitEvent() function for future use.
> Basic Google Analytics tracking for URL changes in workbench.

- ui/package.json
Test if explicitly adding geojson will fix CircleCI's deployment to the Test server
> add types/geojson

- .circleci/config.yml
These job names are cut-off in several places in CircleCI's UI. I'm hoping these slightly shorter versions will make it clearer which jobs are running/finished at a glance.
> Slightly shorter job names

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/exceptions/BadRequestException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
- api/src/main/webapp/WEB-INF/web.xml
- api/src/main/webapp/server_unavailable.html
> [RW-36] Getting rid of stack trace when AppEngine fails to start up properly.

- .circleci/config.yml
I am not sure if this is all we need? Is there somewhere else to specify circle workflows to run?
> Initial circle job and workflow.

- ui/src/app/cohort-review/choice-filter/choice-filter.component.html
- ui/src/app/cohort-review/choice-filter/choice-filter.component.ts
- ui/src/app/cohort-review/cohort-review.module.ts
- ui/src/app/cohort-review/create-review/create-review.component.ts
- ui/src/app/cohort-review/participant-detail/participant-detail.component.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.ts
- ui/src/app/cohort-review/participant-table/participant-table.component.html
- ui/src/app/cohort-review/participant-table/participant-table.component.ts
- ui/src/app/cohort-review/participant.model.ts
- ui/src/app/cohort-review/review-nav/review-nav.component.ts
- ui/src/app/cohort-review/routing/demographic-concept-maps.resolver.ts
- ui/src/app/cohort-review/routing/routing.module.ts
- ui/src/app/cohort-review/set-annotation-master/set-annotation-master.component.ts
- ui/src/app/cohort-review/status-filter/status-filter.component.html
- ui/src/app/cohort-review/status-filter/status-filter.component.ts
Implements multiple select filters for gender, race, ethnicity, and status on the participant table.  Status is special cased, but the other three generate the select options by querying for the relevant concepts.
There is a (known) bug wherein the "multiple" part of multiple select is not actually executed; only one filter will actually be applied by the server.
This is also not intended to be the final UI. Polishing touches may be applied after we decide this is definitely the route to take (and not, say, just a single select).
> participant-table filters

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDao.java
- api/src/main/java/org/pmiops/workbench/db/model/ParticipantCohortAnnotation.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
- ui/src/app/cohort-review/annotations/annotations.component.ts
- ui/src/app/cohort-review/choice-filter/choice-filter.component.ts
- ui/src/app/cohort-review/create-review/create-review.component.ts
- ui/src/app/cohort-review/participant-annotation/participant-annotation.component.ts
- ui/src/app/cohort-review/participant-detail/participant-detail.component.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.ts
- ui/src/app/cohort-review/participant-table/participant-table.component.ts
- ui/src/app/cohort-review/routing/participant-annotations.resolver.ts
- ui/src/app/cohort-review/routing/participant.resolver.ts
- ui/src/app/resolvers/review.ts
implemented the create for ParticipantCohortAnnotations.
> Freemabd1/rw 367 implemented the create for ParticipantCohortAnnotations.

- .circleci/config.yml
> Removing client from circle build (in anticipation of moving it to

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
This fixes all broken bigquery test cases.
> fixed broken bigquery test cases.

- api/config/config_local.json
- api/config/config_test.json
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/notebooks.yaml
- ui/src/app/views/workspace/component.ts
Changing billing project prefix for local, test.
Checking for null contact email before trying to use MailChimp.
> Switching to FC prod.

- api/libproject/devstart.rb
- api/libproject/gcloudcontext.rb
- api/libproject/wboptionsparser.rb
- api/src/dev/server/Dockerfile
I needed this a while back and just now got around to documenting how I did it. Figured others would find it useful.
> Script to generate a scope access token via SA credentials

- api/libproject/devstart.rb
(Cloud migrations of CDR are going away soon.)
> Don't try to migrate CDR anymore during circle push.

- .circleci/config.yml
- api/config/config_local.json
- api/config/config_test.json
- api/libproject/devstart.rb
- api/libproject/gcloudcontext.rb
- api/libproject/wboptionsparser.rb
- api/src/dev/server/Dockerfile
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/notebooks.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- ui/src/app/cohort-review/create-review/create-review.component.ts
- ui/src/app/cohort-review/participant-annotation/participant-annotation.component.ts
- ui/src/app/cohort-review/participant-detail/participant-detail.component.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.ts
- ui/src/app/cohort-review/participant-table/participant-table.component.ts
- ui/src/app/cohort-review/routing/demographic-concept-maps.resolver.ts
- ui/src/app/cohort-review/routing/participant-annotations.resolver.ts
- ui/src/app/cohort-review/routing/participant.resolver.ts
- ui/src/app/resolvers/review.ts
- ui/src/app/views/workspace/component.ts
Moved save to only happen in the CohortReviewController.createCohortReview() method.
> refactored cohort review save.

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
(We can just make a new one on each request until we work this out.)
> Getting rid of StatusApi binding which wasn't working for some reason.

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDao.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
implemented the delete participant cohort annotation functionality.
> Freemabd1/rw 367 implemented the delete participant cohort annotation functionality.

- api/src/main/java/org/pmiops/workbench/exceptions/BadRequestException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ConflictException.java
- api/src/main/java/org/pmiops/workbench/exceptions/EmailException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/exceptions/FailedPreconditionException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ForbiddenException.java
- api/src/main/java/org/pmiops/workbench/exceptions/NotFoundException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ServerErrorException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ServerUnavailableException.java
- api/src/main/java/org/pmiops/workbench/exceptions/WorkbenchException.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/resources/workbench.yaml
- api/tools/build.gradle
- ui/src/app/services/error-handling.service.ts
I think that this fixed the all forbidden errors are user disabled piece? Also, this brings in the idea of an error code, which is a short message that describes the type of error.
> Fix disabled message.

- ui/src/app/views/account-creation/component.html
- added form tag and then necessary 'name' attributes to form elements
- added label 'for' attributes and form field 'id' attributes to pair them
> RW-382 Make account creation form more standards-compliant and accessible

- .codacy.yml
- ui/src/app/cohort-review/cohort-review.module.ts
Codacy is configured via a file in the project root called `.codacy.yml`.  In that file you are allowed to specify base directories on a per engine basis.  In this PR I attempted to specify that `tslint` should consider `./ui` its base directory (where it can pick up on _its_ configuration file).   Then I changed up a file to see what codacy did.  Codacy considers all the single quotes in the changed file (which were previously "issues") now to be "fixed issues" so I'm assuming this means that Codacy is correctly reading its configuration file, and then tslint is correctly reading _its_ configuration file, and reporting that there's no problems there.
If this is good, I'll change the mangled file back and merge the codacy config.
> Codacy config file test

- .codacy.yml
- .gitignore
- api/db-cdr/generate-cdr/cloudsql-import.sh
- api/db/changelog/db.changelog-25.xml
- api/db/changelog/db.changelog-master.xml
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDao.java
- api/src/main/java/org/pmiops/workbench/exceptions/BadRequestException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ConflictException.java
- api/src/main/java/org/pmiops/workbench/exceptions/EmailException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/exceptions/FailedPreconditionException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ForbiddenException.java
- api/src/main/java/org/pmiops/workbench/exceptions/NotFoundException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ServerErrorException.java
- api/src/main/java/org/pmiops/workbench/exceptions/ServerUnavailableException.java
- api/src/main/java/org/pmiops/workbench/exceptions/WorkbenchException.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
- api/tools/build.gradle
- ui/package.json
- ui/src/app/services/error-handling.service.ts
- ui/src/app/views/account-creation/component.html
implemented api calls for update/get collection of participant cohort annotations
> Freemabd1/rw 367 implemented api calls for update/get for participant cohort annotations

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_test.json
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/UserAuthentication.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchEnvironment.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
(For now we're still giving them a User record; in future we'll move away from this.)
> Making service accounts able to make API calls.

- api/libproject/devstart.rb
Renaming get-service-creds to get-test-service-creds, fixing logic.
> Fixing get-service-creds

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
(This is the role returned when a billing project owner requests a workspace they aren't explicitly on the ACL for.)
> Adding handling for PROJECT_OWNER role in WorkspacesController

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/CohortAnnotationEnumValue.java
- api/src/main/java/org/pmiops/workbench/db/model/ParticipantCohortAnnotation.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/ParticipantCounterTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortAnnotationDaoTest.java
- ui/src/app/cohort-review/annotation-item/annotation-item.component.html
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/annotation-list/annotation-list.component.html
- ui/src/app/cohort-review/annotation-list/annotation-list.component.ts
- ui/src/app/cohort-review/routing/participant-annotations.resolver.ts
- ui/src/app/cohort-review/set-annotation-create/set-annotation-create.component.html
- ui/src/app/cohort-review/set-annotation-create/set-annotation-create.component.ts
- ui/src/app/cohort-review/set-annotation-item/set-annotation-item.component.spec.ts
- ui/src/app/cohort-review/set-annotation-item/set-annotation-item.component.ts
- ui/src/app/resolvers/review.ts
> RW-415 implemented new demo sql.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- ui/src/app/cohort-review/routing/demographic-concept-maps.resolver.ts
Rework the api call for listing gender, race and ethnicities
> Freemabd1/rw 422 Rework the api call for listing gender, race and ethnicities

- .circleci/config.yml
- ui/README.md
- ui/karma.conf.js
I mainly want this for remote development, but use headless for Circle as well.
> support/doc ChromeHeadless for UI unit tests

- ui/src/app/cohort-search/criteria-wizard/wizard/wizard.component.ts
> Wizard buttons updated

- api/libproject/devstart.rb
Was able to run this command alone locally which I should have done before submitting my last PR, haven't confirmed circle-deploy.
> Fix deploy_gcs_artifacts

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace/component.ts
This fixes launching of notebooks in workspaces which are not owned by you, and will reduce the chances of this logic diverging in the future.
> Consolidate Jupyter-local dir structure server-side

- hooks/pre-push
@dmohs you mentioned you died a little inside every time you ran `ng lint` on pre-push for non-UI changes.
> Only ng lint on typescript changes

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/resources/workbench.yaml
- ui/src/app/services/error-reporter.service.ts
- ui/src/app/services/server-config.service.spec.ts
to publicApiKeyForErrorReports
> RW-369 Rename configuration key stackdriverApiKey	 

- README.md
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCriteria.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDao.java
- api/src/main/java/org/pmiops/workbench/db/model/ParticipantIdAndCohortStatus.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/ParticipantCounterTest.java
Changing cohort materialization service to respect status filter using whitelist / blacklist.
(Existing tests pass -- working on writing tests for the new functionality now.)
> Adding ParticipantCriteria, used to wrap SearchRequest with blacklist, or whitelist.

- ui/src/app/views/signed-in/component.html
[[RW434]](https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=planning&selectedIssue=RW-434)
> Close sidebar on use.

- ui/src/app/views/workspace-list/component.html
Re: [This issue](https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=detail&selectedIssue=RW-438)
> Workspace list spinner

- ui/src/app/app.module.ts
- ui/src/app/services/sign-in.service.ts
- ui/src/app/styles/buttons.css
- ui/src/app/views/profile-page/component.css
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.ts
Per this:
https://projects.invisionapp.com/d/main#/console/12820961/286774501/preview
Final changes are going to come with some API additions, so that is coming next.
> Prettify Profile Page

- api/config/cdm/README.md
- api/config/cdm/cdm_5_2.json
This can be used to validate and transform cohort materialization requests against the CDR, without having to hardcode the schema and relationships in Java classes.
> Beginning of a configuration file for CDR schema.

- ui/src/app/views/signed-in/component.css
Per [RW-454](https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=planning&selectedIssue=RW-454&versions=visible&epics=visible)
> Resized header image

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/config/CdrBigQuerySchemaConfig.java
- api/src/main/java/org/pmiops/workbench/config/CdrSchemaConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/Config.java
- api/tools/build.gradle
- api/tools/gradle.properties
- api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java
Changing our scripts to load both the main workbench config and CDR schema config in dev-up, etc.
> Update ConfigLoader to allow for loading of configs with different keys.

- api/build.gradle
- api/scripts/setup_notebook_cluster.sh
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/bigquerytest/resources/bigquery/data/person_data.json
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/TableQueryAndConfig.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMaterializationService.java
- api/src/main/java/org/pmiops/workbench/config/CacheSpringConfiguration.java
- api/src/main/java/org/pmiops/workbench/utils/OperatorUtils.java
- api/src/main/resources/client_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/test/TestBigQueryCdrSchemaConfig.java
- api/src/test/java/org/pmiops/workbench/test/TestCdrSchemaConfig.java
- ui/src/app/cohort-review/choice-filter/choice-filter.component.ts
- ui/src/app/cohort-review/table-page/table-page.ts
This relies on:
https://github.com/all-of-us/workbench/pull/653
> Initial implementation of field set-based cohort materialization.

- .circleci/config.yml
> Drop dependencyCheck step temporarily

- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
Re: the profile icon in the top right. More final than just adding padding.
> Change profile icon

- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.ts
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
Per this ticket: https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=planning&selectedIssue=RW-451
And this ticket: https://precisionmedicineinitiative.atlassian.net/secure/RapidBoard.jspa?rapidView=23&projectKey=RW&view=planning&selectedIssue=RW-452
(Initially was going to tie them together some, because they were touching the same things, but then we realized they didn't.)
> Workspace list revamp and gate on approval

- ui/src/app/styles/buttons.css
applies styles from btn-secondary to btn-outline (they do basically the same thing) except font-size.
> Add styles for btn-outline

- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
Pull in language gotten from Moran for the research purpose descriptions.
> Update text and styling

- .circleci/config.yml
So close, yet so far: https://circleci.com/workflow-run/dacbe3cf-85ee-4f91-ae1c-81c78cc1e8c1
> Fix bad Circle bash

- api/libproject/cloudsqlproxycontext.rb
- deploy/README.md
- deploy/bootstrap-docker.sh
- deploy/docker-compose.yaml
- deploy/libproject/deploy.rb
- deploy/project.rb
- ui/libproject/devstart.rb
PTAL - this is mostly working but still needs more testing. Sending now for feedback on the approach (see README for explanation).
> Add a manual deploy process for stable (later prod)

- .gitignore
- ui/libproject/devstart.rb
Also ignore sa-key which may be generated by deploy-ui
> Fix swagger_regen ruby issues

- ui/src/app/views/workspace-edit/component.html
Moran and I hashed this out earlier this week, this is from that conversation.
> Add more underserved research text

- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
Fixing handling of service accounts
> [RW-503] Clearing out security context at the start of threads

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Notebooks with spaces in the names will now show up in the notebook list.
> [RW-506] Drop overly strict notebook name filtering

- ui/src/app/app.module.ts
- ui/src/app/views/app/component.ts
- ui/src/app/views/breadcrumb/component.ts
- ui/src/app/views/initial-error/component.ts
- ui/src/app/views/invitation-key/component.ts
- ui/src/app/views/login/component.ts
- ui/src/app/views/profile-page/component.ts
- ui/src/app/views/signed-in/component.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-list/component.ts
- ui/src/app/views/workspace-nav-bar/component.ts
- ui/src/app/views/workspace/component.ts
We had a whole bunch of unused imports and variables, so I got rid of them. Confirmed that signin/out still work, it still loads everything it should, and things still generally work.
Also, got rid of one of the extra `getMe` calls, but I'm not sure I can eliminate the other one concurrent/parallel one easily without a possible loss of functionality?
> Remove imports, get rid of one getme call

- LICENSE.txt
Per security, this is the license the leadership team decided on.
> Add BSD 3-clause LICENSE

- ui/src/app/views/profile-page/component.css
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.ts
To match new mocks:
https://projects.invisionapp.com/d/main#/console/12820961/286774501/preview
> [RW-533]: Update to match new profile mocks

- api/libproject/devstart.rb
- deploy/libproject/deploy.rb
- ui/libproject/devstart.rb
Depends on https://github.com/all-of-us/utils/pull/11
> Update deploy scripts for utils changes

- deploy/libproject/deploy.rb
Made it almost fully through the deploy...
> Fix release ruby error

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
Still deciding where the button will go, but will need this API to actually trigger cluster recreation.
> [RW-542] Implement DeleteCluster

- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
This is a quick UX improvement to default to the leftmost tab.
> [RW-573] Default to tab on the left

- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
This fixes the bigquery integration test
> Increase criteria limit

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-597
Handle the case where FC doesn't return any workspaces better.
> [RW-597] handle empty FC workspaces

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/settings/component.css
- ui/src/app/views/settings/component.html
- ui/src/app/views/settings/component.spec.ts
- ui/src/app/views/settings/component.ts
- ui/src/app/views/signed-in/component.html
- ui/src/testing/stubs/cluster-service-stub.ts
> [RW-542] Add settings page with notebook server reset button

- ui/src/app/guards/sign-in-guard.service.ts
- ui/src/app/utils/index.ts
- ui/src/app/views/signed-in/component.ts
I'd previously fixed this only when you clicked "sign out". Didn't realize there was a secondary entrypoint via the guard.
> [RW-470] Unify login navigation for sign in guard and sign out button

- ui/src/app/views/workspace-nav-bar/component.css
It didn't update so I had thought the previous change had worked, but it hadn't. This should _finally_ fix it...
> [RW-614] Fix top bar

- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
Simple status integration test for firecloud.
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-621
Ran integration tests locally and all passed. Will wait for this to run in circle.
> [RW-621] FireCloud Integration Test

- api/src/integration/java/org/pmiops/workbench/NotebooksIntegrationTest.java
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-657
Integration tests failed overnight: https://circleci.com/gh/all-of-us/workbench/11984
> [RW-657] fix compilation error

- api/src/main/java/org/pmiops/workbench/config/RetryConfig.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/firecloud/FirecloudRetryHandler.java
- api/src/main/java/org/pmiops/workbench/google/GoogleRetryHandler.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksRetryHandler.java
Removing double-logging on FC / notebook service exceptions.
> [RW-663] Change logging for 404s to INFO, etc.

- api/src/main/java/org/pmiops/workbench/config/RetryConfig.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
Changing 504s to not be retried, thrown as 504s to client.
> [RW-663] Changing 409 logging to INFO.

- api/libproject/devstart.rb
Cleanup task from setting up the staging environment. I don't think there are any known blockers for doing this (@freemabd1 's fix should work for all environments, by my reading).
> [RW-471] Point stable at the shared test CDR

- ui/src/app/app-routing.module.ts
- ui/src/app/views/breadcrumb/component.html
- ui/src/app/views/breadcrumb/component.spec.ts
- ui/src/app/views/breadcrumb/component.ts
Deployed version available here: https://rw-619-dot-all-of-us-workbench-test.appspot.com
> [RW-619] Blrubenstein/use workspace name breadcrumb

- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
Option B from @calbach's suggestions on the other workspace share page PR.
> [RW-723] CH multiple modal solution

- api/libproject/devstart.rb
The approach here should apply elsewhere. Basically exec the script inside of the "api" docker-compose service, where we'll have access to all of the server code (+ tools), as well as the DB connection info.
> [RW-702] Add a set-authority-local command for local development use

- ui/src/app/views/account-creation/component.css
- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/account-creation/component.ts
- ui/src/testing/stubs/profile-service-stub.ts
https://rw-636-dot-all-of-us-workbench-test.appspot.com/login
This provides live validation when users complete the create account form for username, password, and password again. Only gives validation after a user leaves focus on the field, and adds color on the input as well.
> [RW-636] Take 2: Blrubenstein/password live validation

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- ui/src/app/views/account-creation/component.css
- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/account-creation/component.ts
- ui/src/testing/stubs/profile-service-stub.ts
Fixes this bug: https://precisionmedicineinitiative.atlassian.net/browse/RW-754
> RW-754 fixed bug with getGenderRaceEthnicityConcept.

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
This machine is pretty weak. This is a starting point for freedback, but I suspect we may want to adjust the RAM here.
- n1-standard-1 (1 CPU, 4GB RAM)
- 100GB
> [RW-725] Reduce cluster size

- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/resources/application.properties
- api/src/main/resources/client_api.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- api/src/test/java/org/pmiops/workbench/test/TestDialect.java
- api/src/test/resources/application.properties
- common-api/src/main/java/org/pmiops/workbench/cdr/MySQLDialect.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/NoCountFindAllDao.java
(Still working on tests.)
@biopete I think at some point we may want to move the controller code and maybe even API YAML definition for this into common-api, so we can share between data browser and workbench. For now, just putting this in workbench.
> [RW-600] Adding concept search (for use in notebooks / field set creation)

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Short-term boolean flag to avoid this; longer-term we're not going to call mailchimp here with the email verification changes (@rushtong, please double-check that assertion).
> [RW-702] Don't check mailchimp for admin ID verification reviews

- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
to get the right EntityManager hopefully.
> [RW-764] Switching ConceptService to use CDR EntityManagerFactory 

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-api/src/main/resources/public-api.yaml
Added domain id and standard concepts to concept search api call
> Domain id and standard concepts added to query concept search

- ui/src/app/app-routing.module.ts
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.ts
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.ts
- ui/src/app/views/workspace/component.ts
made "workspaces" parent instead of "workspace" where it made sense.
> [RW-777] fix for routing on workspaces Security Impact: Low

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
Mock the email sending part of the create/delete user test
> [RW-706] fix integration test

- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
…width, and added minimum width to cards on new Workspace
See https://precisionmedicineinitiative.atlassian.net/browse/RW-676
> [RW-676] Removed colon after NIH name. Made research purpose field into fixed … Security Impact: None.

- api/config/config_staging.json
This will have implications for the release QA process. This will also force us to start thinking about some new UX issues in the first-sign-in flow. Timing is not urgent if we think this will cause significant short-term pain before some of the account creation flow changes are in.
> [RW-712][risk=no] Enforce registered in staging

- api/build.rb
- api/libproject/cloudsqlproxycontext.rb
- api/libproject/devstart.rb
- api/libproject/gcloudcontext.rb
- deploy/libproject/deploy.rb
- deploy/libproject/jirarelease.rb
- ui/libproject/devstart.rb
Ignoring two codacy complaints which I plan to disable per https://docs.google.com/document/d/1o1nN4Oni9v6wgoYeFhG2yj47pqaD7XkVrRaTHqsdHhg/edit#heading=h.4kzzp7nkt8j8
> [RW-745][risk=no] Fix codacy Ruby issues

- api/build.gradle
- common-api/build.gradle
- public-api/build.gradle
https://precisionmedicineinitiative.atlassian.net/browse/RW-698
Minor change to address Snyk security warning here: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236
Tested both unit tests and integration tests locally.
> [RW-698][risk=no] Upgrade Guava Library

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
Just released in Leo per https://github.com/DataBiosphere/leonardo/issues/388
> [risk=no] Drop cluster disk size from 100GB -> 20GB

- api/src/main/resources/emails/welcomeemail/content.html
This addresses @fknabe's feedback on the email PR earlier.
> [RW-724][Risk=no] Fritz feedback

- .codacy.yml
This still didn't work. And I decided to simply ignore the specific problematic files instead.
> [RW-745][risk=no] Revert codacy excludes

- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
> refactoring

- ui/src/app/services/error-handling.service.ts
- ui/src/app/services/profile-storage.service.ts
- ui/src/app/styles/errors.css
- ui/src/app/views/admin-review-workspace/component.css
- ui/src/app/views/admin-review-workspace/component.html
- ui/src/app/views/admin-review-workspace/component.ts
- ui/src/app/views/bug-report/component.css
- ui/src/app/views/bug-report/component.html
- ui/src/app/views/bug-report/component.ts
- ui/src/app/views/error-handler/component.html
- ui/src/app/views/profile-page/component.css
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.ts
- ui/src/app/views/settings/component.css
- ui/src/app/views/settings/component.html
- ui/src/app/views/settings/component.ts
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
This should add an error handler for every API call in the UI, other than getConfig. (Wasn't sure how to handle that one)
Screenshots coming.
This does not handle API errors from the Cohort Builder. I wasn't sure how we wanted to work error messages into their UI. @freemabd1 @dolbeew
> [RW-785] [Risk=no] Add many error handlers for specific cases

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
https://precisionmedicineinitiative.atlassian.net/browse/RW-817
* Is this correct?
* Is this too long (I have heard that it could be)
* Is it useful?
My goals here are to try and put some gentle guardrails around the process that might help reduce errors.
> [RW-817][risk=no] PR Template

- ui/src/app/views/workspace/component.ts
Previously, this handler would only trigger on the first notebook opened, which means that subsequent notebooks would not auto-refresh their own credentials.
> [RW-911][risk=low] postMessage for all notebook tabs

- ui/src/app/views/signed-in/component.html
- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.spec.ts
As a heads up, I talked to Lou, apparently new AoU style guide came in, and we should be using #216FB4 for links now, rather than #6cace4. Tagging @freemabd1 and @dolbeew for this info too.
> [RW-864][risk=no] Workspace list create new workspace card

- api/build.gradle
- common-api/build.gradle
- public-api/build.gradle
This appears to fix the issue for me locally.
> [RW-916][risk=no] Upgrade to Guava 25.1 to fix local dev

- api/build.gradle
- api/db-cdr/changelog-data/db.changelog-16.xml
- api/db-cdr/changelog-data/db.changelog-master.xml
- api/db-cdr/csv/ethnicity_criteria.csv
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/person_data.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/querybuilder/DemoQueryBuilderTest.java
- common-api/build.gradle
- public-api/build.gradle
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/views/workspace/component.ts
[RW-823][risk=no] Adding ethnicity to the demographics search in CB
This PR will allow users to search by Ethnicity in the demographics section of the CB.
> [RW-823][risk=no] Adding ethnicity to the demographics search in CB

- api/build.gradle
Attempt at solving a version conflict error. 
Jira: https://precisionmedicineinitiative.atlassian.net/browse/RW-916
In `api` directory:
```
./project.rb clean
./project.rb docker-clean
./project.rb test
./project.rb integration
```
> [RW-916][risk=no] Downgrade guava

- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
> [risk=no] Fix leoApiUrl key in staging/stable environments

- common-api/README.md
This reflects my current understanding from talking to Dan. Please let me know if there's more detail I can add or if anything here sounds incorrect.
> [RW-780][risk=no] Document common-api DB access

- ui/src/app/cohort-search/overview/overview.component.ts
> [RW-678][risk=no] Redirect to cohorts list after creating a cohort

- ui/src/app/styles/cards.css
- ui/src/app/views/notebook-list/component.html
- ui/src/app/views/notebook-list/component.spec.ts
- ui/src/app/views/notebook-list/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
> [RW-862][RW-863][risk=no] - Adding help tips to workspace about and notebook list page

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionContext.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/ClearCdrVersionContextInterceptor.java
- api/src/main/resources/fireCloud.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerMockTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerMockTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
… whenever using a CDR version.
> [RW-781] Enforcing registered data access via FireCloud group membership [risk=low]

- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
> [No Ticket][risk=no] Add second iteration of groups api

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/testconfig/WorkbenchConfigConfig.java
> Fixing BigQuery tests with CdrVersionService [risk=no]

- ui/src/app/views/account-creation/component.html
- ui/src/app/views/account-creation/component.ts
> [RW-687][Risk=no] Make info icon not tab selectable

- ui/src/app/views/cohort-list/component.html
- ui/src/app/views/notebook-list/component.css
- ui/src/app/views/notebook-list/component.html
- ui/src/app/views/workspace/component.html
> [No Ticket][Risk=low] Fix review status

- ui/src/app/views/invitation-key/component.html
> [RW-684][Risk=no] Add enter and return

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/BugReportControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- GAE mail service -> mandrill
- Drop unused `admin.supportgroup`
- Drop now unused `admin.verifiedSendingAddress`
> [RW-940][risk=low] Drop GAE mail service usage and unused configs

- api/tools/build.gradle
> [NO TICKET][Security Risk=low] updating dependencies

- ui/src/app/views/workspace/component.html
> [RW-962][Risk=no] Fix cards to disable on awaiting review

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
This adds the short descriptions of the research purpose to the about page on the workspace. It also abstracts that text a level up, so we are pulling from a single location in both places (which should make it easier to change)
Please also:
> [RW-936][Risk=no] Add Research Purpose short descriptions

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/BugReportControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Now with integration tests that compile.
Reverts 88c82de with fixes.
> [RW-940][risk=low] Re-revert: Drop GAE mail service usage and unused configs

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
Note that this does not actually change workbench to take the user into notebooks in JupyterLab... probably we'll want https://github.com/DataBiosphere/leonardo/issues/474 to be fixed before we do that.
> Turning on JupyterLab in new clusters [risk=low]

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- ui/src/app/views/cohort-list/component.html
- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/cohort-list/component.ts
- ui/src/app/views/invitation-key/component.html
- ui/src/app/views/invitation-key/component.spec.ts
- ui/src/testing/stubs/cohort-service-stub.ts
The invite key piece was flaky depending on keyboard. This adds delete as an option to cohorts.
Please also:
> [RW-684][RW-604][risk=no] Fix invite key and add delete cohort

- api/config/config_prod.json
- api/libproject/devstart.rb
- ui/libproject/devstart.rb
- ui/src/environments/environment.prod.ts
> [RW-940][risk=medium] Add initial prod configuration

- public-ui/src/app/app.module.ts
- public-ui/src/app/views/app/app.component.html
- public-ui/src/app/views/db-header/db-header.component.css
- public-ui/src/app/views/db-header/db-header.component.html
Link to feedback that the databrowser testers need asap
> Biopete/public footer [risk=no]

- hooks/pre-push
See inline comment, this should reduce unnecessary linting.
> [risk=no] pre-push: Avoid some unnecessary linting, reduce duplication

- api/scripts/setup_notebook_cluster.sh
> [RW-830][risk=low] Install aou client library in setup

- ui/src/app/views/homepage/component.html
> [risk=no] Spell out AoU acronym on homepage

- api/db-cdr/generate-cdr/bq-schemas/criteria.json
Criteria schema change for big query
> Criteria bq schema change [risk=no]

- ui/src/app/views/login/component.html
- ui/src/app/views/login/component.ts
Data browser is now a separate app
> [risk=no] rm dead code: databrowser URL check

- ui/src/app/styles/cards.css
- ui/src/app/views/cohort-list/component.css
- ui/src/app/views/cohort-list/component.html
- ui/src/app/views/cohort-list/component.ts
Open questions: 
What do disabled cards look like? (Lou is doing a mock now)
Do we still want a review option in the dropdown? (It is a little more explicit?)
Please also:
> [RW-1023][Risk=no] Fix cohort name to open to review.

- ui/src/app/cohort-search/tree/tree.component.html
Hide the search bar in CB for all criteria except visits until implemented for other criteria
> [RW-1026][risk=no] Show search only for Visits

- ui/src/app/cohort-search/utils.ts
Strip HTML code from selections made using search in the Visits tree
> [RW-1027][risk=no] Strip HTML from Visit selections

- api/config/config_stable.json
- api/config/config_staging.json
> [No JIRA][Risk=no] Fix configs

- ui/src/app/services/sign-in.service.ts
+ This approach appears to be less dependent on iframes, cookies, local storage. Resolves a class of silent errors which prevent login that have been observed by beta users as well as myself (we get no useful failure information).
- This approach is a bit more jarring, and tacks a long string into the URL hash on redirect (which we then strip out).
The nuclear fix to these sign in issues which we may want eventually would  be to switch to a server side oauth flow. This would also involve the full page redirect, but would skip the giant URL hash fragment.
Demo: https://calbach-dot-all-of-us-workbench-test.appspot.com
^ @fknabe for product approval
> [RW-753][risk=low] Switch to oauth redirect

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerMockTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
> [RW-1062][risk=no] small tweak to meds api calls

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
> [RW-935][Risk=no] Rework workspace setup page

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Addresses: https://precisionmedicineinitiative.atlassian.net/browse/RW-953
Minor updates to protect against nulls in billing project memberships.
> [RW-953][risk=no] Handle NPEs from invalid billing project memberships

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/attributes-page/attributes-page.component.spec.ts
- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/views/signed-in/component.ts
- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace/component.ts
Add validation for inputs on Physical Measurements attributes form, specifically checks for negative values
> [RW-1005][risk=no] Check for negatives for PM attributes

- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/redux/reducer.ts
Fix parameter list for count requests for calculate button on PM attributes page
> [RW-1083][risk=no] Fix calculate count in PM attributes

- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/redux/reducer.ts
Set a minimum of 18 for age slider in demographics component in CB
> [RW-1016][risk=no] Set min age of 18 in demographics

- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
Add min and max validation functions for demographics age slider
> [RW-1082][risk=no] Fix age slider validation

- ui/src/app/cohort-search/redux/actions/service.ts
Added hasAttributes property to search parameters of cloned cohorts so the attributes will get properly mapped
> [RW-1096][risk=no] Fix incorrect count for cloned cohorts

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.ts
> [RW-1085][Risk=no] Fix bug in tooltip workspace creation

- api/db-cdr/changelog-data/db.changelog-19.xml
- api/db-cdr/changelog-data/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- ui/src/app/cohort-search/constant.ts
create yaml contract for Labs api calls(autocomplete and tree sub search)
> [RW-1102][risk=no] create yaml contract for Labs api calls(autocomplete and tree sub search)

- ui/src/app/views/account-creation-modals/component.spec.ts
- ui/src/app/views/account-creation-success/component.spec.ts
- ui/src/app/views/account-creation/component.spec.ts
- ui/src/app/views/admin-review-id-verification/component.spec.ts
- ui/src/app/views/admin-review-workspace/component.spec.ts
- ui/src/app/views/app/component.spec.ts
- ui/src/app/views/workspace/component.spec.ts
- ui/src/testing/stubs/profile-service-stub.ts
- ui/src/testing/stubs/workspace-service-stub.ts
This just adds a whole bunch of test files with basic render tests. 
Please also:
> Add a bunch of tests

- ui/src/app/views/workspace/component.css
If you are reviewing, please pull and test locally. It looks good on my screen, but I've learned that does not mean it looks good on everyone's. Thanks!
> [RW-1060][Risk=no] Fixing widths on workspace about page

- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/main/resources/cb_search_api.yaml
fixing a few minor bugs with labs api call.
> [RW-1146][risk=no] fixing a few minor bugs with labs api call.

- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/main/resources/cb_search_api.yaml
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/overview/overview.component.html
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/search-group/search-group.component.html
Add RXnorm Code next to drug name, only for bottom level children in drug tree.
> [RW-901][risk=no] Add RXnorm Code next to drug name

- api/demos/Import a Cohort.ipynb
`PERSON_TABLE` is not a real variable.
> [RW-1141][risk=no] Fix missing PERSON_TABLE reference

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace-share/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1012
* Change the share workspace API to return the new/updated list of user roles
* Update the UI to rely on that list instead of managing an internal list of user roles.
* Update test stub to match the updated API
> [RW-1012][risk=low] Fix duplicate user sharing bug

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
https://github.com/all-of-us/workbench/pull/1083 introduced a compilation error. This fixes it.
> [RW-1012][risk=low] fix merge conflict

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1122
Added special-casing for the conflict case.
> [RW-1122][risk=low] Update create workspace conflict error message

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
creating contract for criteria attributes api call.
> [RW-1160][risk=no] creating contract for criteria attributes api call.

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
Fix typo in attributes api call
> [RW-1161][risk=no] Fix typo in attributes api call

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- ui/src/app/views/workspace-share/component.css
- ui/src/app/views/workspace-share/component.html
- ui/src/app/views/workspace-share/component.spec.ts
- ui/src/app/views/workspace-share/component.ts
- ui/src/testing/stubs/workspace-service-stub.ts
This doesn't bring it quite to the comps, but it does bring in the correct font styling and the full name. Screenshot below.
Please also:
> [RW-1006][Risk=no] Styling upgrades and fullname on share

- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
Fix duplicate attributes fields
> [RW-1187][risk=no] Fix duplicate attributes fields

- api/db/changelog/db.changelog-45-concept-set.xml
- api/db/changelog/db.changelog-master.xml
> [RW-1189] Adding concept_set, concept_set_concept_id tables to database schema. [risk=no]

- ui/src/app/utils/workspacePermissions.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.spec.ts
- ui/src/app/views/workspace-list/component.ts
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.ts
- ui/src/app/views/workspace-share/component.spec.ts
- ui/src/app/views/workspace-share/component.ts
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
Shepherding this through for Greg. This adds the menu items to the workspace list. This will probably need specific tests, but want to open for review on basic functionality.
Please also:
> [RW-1119][Risk=No] Add workspace list page action items

- ui/src/app/styles/buttons.css
- ui/src/app/views/signed-in/component.css
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
> [RW-1220][Risk=no] Add sidebar options

- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/AbstractQueryBuilder.java
> [RW-1230][risk=no] fixed broken query.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
> Adding import to fix BQ test [risk=no]

- ui/src/app/views/confirm-delete-modal/component.html
- ui/src/app/views/confirm-delete-modal/component.ts
- ui/src/app/views/notebook-list/component.ts
- ui/src/app/views/rename-modal/component.html
- ui/src/app/views/rename-modal/component.ts
> [RW-1231][Risk=no] Loading spinner on delete and rename modals

- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/views/cohort-list/component.css
- ui/src/app/views/notebook-list/component.css
- ui/src/app/views/workspace-list/component.css
>  [RW-1244][risk=no] Reset text added

- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
> [RW-1245][risk=no]Explore link fixes

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Added in the UserRecentResource calls, added tests to make sure they are called correctly, did a little refactoring in Controller.
> [RW-1195][Risk=no] Integrate notebook actions with Users Recently Used Cache

- ui/src/app/cohort-search/modifier-page/modifier-page.component.css
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Modifiers - Change "Event Date" text  to “Shifted Event Date” and add a tooltip
> [RW-1248][risk=no]Modifiers - Change "Event Date" text  to “Shifted Event Date” and add a tooltip 

- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.css
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Modifiers and Attributes - change calculate button
> [RW-1249][risk=no]Modifiers and Attributes - change calculate button

- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.css
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Populate modifier fields when editing
> [RW-1256][risk=no] Populate modifier fields when editing

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.css
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
adding checks for Search Parameter and conceptid.
> [RW-1137][risk=no] adding checks for Search Parameter and conceptid.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Add Any option to search criteria modifiers and set as the default.
> [RW-1252][risk=no] Set Any as default for modifiers

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Measurements - range should not show up twice for "between"
> [RW-1255][risk=no]Measurements - range should not show up twice for "between"

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/attributes-page/attributes-page.component.spec.ts
- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Make 'Any' top select option and default for PM attributes. Also hides Calculate button and shows count and Add result option when 'Any' is selected
> [RW-1131][risk=no] Make 'Any' default for PM attributes

- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/search-group-select/search-group-select.component.css
- ui/src/app/cohort-search/search-group/search-group.component.css
- ui/src/app/cohort-search/selection-info/selection-info.component.html
PM - selecting one heart rhythm item selects them both
> [RW-1258][risk=no]PM - selecting one heart rhythm item selects them both

- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.ts
- ui/src/app/cohort-search/demographics/demographics.component.spec.ts
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/gender-chart/gender-chart.component.spec.ts
- ui/src/app/cohort-search/modal/modal.component.spec.ts
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.spec.ts
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.spec.ts
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/node/node.component.spec.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/search-bar/search-bar.component.spec.ts
- ui/src/app/cohort-search/search-group-select/search-group-select.component.css
- ui/src/app/cohort-search/search-group/search-group.component.css
- ui/src/app/cohort-search/selection-info/selection-info.component.spec.ts
- ui/src/app/cohort-search/tree/tree.component.spec.ts
Add basic render tests for all components under cohort-search directory
> [RW-1155][risk=no] Add render tests for all CB search components

- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Encounter modifier dropdown not populating correctly when editing
> [RW-1263][risk=no] Encounter modifier not populating correctly

- api/src/main/java/org/pmiops/workbench/api/DomainLookupService.java
fixed mixing of icd9/icd10 codes.
> [RW-1264][risk=no] fixed mixing of icd9/icd10 codes.

- ui/src/app/cohort-search/search-bar/search-bar.component.html
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
Drugs - add informational text below search
> [RW-1262][risk=no]Drugs - add informational text below search

- api/src/main/java/org/pmiops/workbench/api/DomainLookupService.java
- ui/src/app/cohort-search/demographics/demographics.component.css
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
- ui/src/app/cohort-search/multi-select/multi-select.component.html
- ui/src/app/cohort-search/search-bar/search-bar.component.html
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
Add real-time counts to demographics age slider
> [RW-998][risk=no] Add real-time counts to demographics age slider 

- ui/src/app/cohort-search/node/node.component.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
- ui/src/app/cohort-search/search-bar/search-bar.component.html
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
- Relocate loading spinner
- Prevent "No results" message from showing before api call returns
- Fix duplicate items in ingredient text for brands
- Allow autocomplete list to be navigated using arrow/enter keys
- Hide dropdown when clicking outside it
- Clear tree for each search
> [RW-1271][risk=no] Update autocomplete search

- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/node/node.component.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
- ui/src/app/cohort-search/search-bar/search-bar.component.html
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
Show counts for labs groups in measurements tree
> [RW-1273][risk=no] Show counts for labs groups

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/redux/actions/creators.ts
- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/redux/actions/types.ts
- ui/src/app/cohort-search/redux/epics.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
- ui/src/app/cohort-search/selection-info/selection-info.component.ts
- ui/src/app/views/workspace-nav-bar/component.css
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
add limit to autocomplete calls
> [RW-1290][risk=low] add limit to autocomplete calls

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/redux/epics.ts
Fix search for blood pressure nodes in PM tree
> [RW-1294][risk=no] Fix search for blood pressure nodes in PM tree

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/concept_data.json
- api/src/bigquerytest/resources/bigquery/cbdata/criteria_data.json
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/DomainLookupService.java
- api/src/main/java/org/pmiops/workbench/cdm/DomainTableEnum.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/DomainLookupServiceTest.java
- ui/src/app/cohort-review/overview-page/overview-page.ts
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/redux/actions/creators.ts
- ui/src/app/cohort-search/redux/actions/types.ts
- ui/src/app/cohort-search/redux/epics.ts
- ui/src/app/cohort-search/selection-info/selection-info.component.html
- ui/src/app/cohort-search/utils.ts
- ui/src/testing/stubs/cohort-builder-service-stub.ts
Show top 10 child concepts for conditions, procedures, labs and meds.
> [RW-270][risk=low] Charts for cohort overview

- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
> [RW-1307][risk=no] refactor path query.

- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
> [RW-1159][risk=no] Fix edit/clone of unset underserved populations

- ui/src/app/views/resource-card/component.ts
This somehow got misplaced during rebase mess
> fix for opening notebook

- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- common-api/src/main/java/org/pmiops/workbench/interceptors/SecurityHeadersInterceptor.java
- public-api/src/main/java/org/pmiops/workbench/config/PublicApiWebMvcConfig.java
- public-ui/app.yaml
- ui/app.yaml
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
> [RW-1232][risk=low] Return HSTS response headers 

- api/src/main/java/org/pmiops/workbench/api/CdrVersionsController.java
- api/src/test/java/org/pmiops/workbench/api/CdrVersionsControllerTest.java
- ui/src/app/app.module.ts
- ui/src/app/services/cdr-version-storage.service.ts
- ui/src/app/styles/buttons.css
- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/testing/stubs/cdr-version-storage-service-stub.ts
- Make the CdrVersions endpoint work for dev/test (!enforceRegistered)
- Add a cache service for CdrVersions, as these won't change normally.
> [RW-1222][risk=low] Implement CDR version toggle on create/clone

- deploy/libproject/deploy.rb
> [DB-89][risk=no] Skip prod databrowser deployment for now

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
1. Changed the cdr version with the new database built.
> Cdr version swtich changes [risk=no]

- deploy/libproject/deploy.rb
> [risk=no] Fix deploy typo

- ui/src/app/app.module.ts
- ui/src/app/views/top-box/component.css
- ui/src/app/views/top-box/component.html
- ui/src/app/views/top-box/component.ts
- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.spec.ts
This styling follows what saturn uses for their top bar curvy thing.
> Top box abstraction

- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/cb_search_api.yaml
- api/src/main/resources/client_api.yaml
- api/src/main/resources/workbench.yaml
- common-api/src/main/resources/common_api.yaml
- public-api/src/main/resources/public-api.yaml
> [risk=no] Update our swagger license names to match reality

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- ui/src/app/cohort-search/redux/epics.ts
fix drug autocomplete to include results that match on code
> [RW-1376][risk=no] fix drug autocomplete to include results that match on code

- api/libproject/devstart.rb
- common-ui/common-ui-devstart.rb
- deploy/README.md
- deploy/libproject/deploy.rb
> [RW-1344][risk=low] Support deployment dry runs, fix prod deploy

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- ui/src/environments/environment.prod.ts
> [RW-1305][risk=no] Update prod domains

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Unfortunately this requires adding another phase to the clone - a call to FC to update the ACL. This is eventually something we should request as a feature from the workspace service.
- Also, fix changing CDR version on clone.
> [RW-1312][risk=moderate] API support for optionally cloning with collaborators

- api/demos/ICD10-F31.30-Bi-polar-female.json
> [risk=no] fixing demo.

- ui/src/app/views/workspace-nav-bar/component.html
> [No Jira][Risk=no] Hide concepts tab

- public-ui/src/app/views/quick-search/quick-search.component.html
1. Using standard concept count instead of all concept count to display number of matching concepts.
> Ehr matching concept count was 0 [Risk=no]

- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
- ui/src/testing/stubs/concepts-service-stub.ts
This adds real domain counts, only disables tabs that haven't loaded yet, and adds filtering by vocabulary. We make a new call on filtering in order to properly support pagination once that is added.
> [RW-1278][RW-1280][Risk=no] Blrubenstein/domain counts

- ui/src/app/views/workspace-nav-bar/component.spec.ts
- ui/src/app/views/workspace-nav-bar/component.ts
With a regression test (verified failing without this fix). Depends on #1257
> [RW-1374][risk=no] Refresh top bar on workspace changes

- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
1. fix to display pregnancy and wheel chair results.
> Databrowser fix to display pregnancy and wheel chair results [Risk=no]

- api/src/bigquerytest/java/org/pmiops/workbench/testconfig/TestJpaConfig.java
Fixes bigquery integration tests.
> [risk=no] Update BigQuery test MySQL dialect

- ui/src/app/utils/workspace-permissions.ts
- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-list/component.spec.ts
> [RW-1225][risk=no] add permissions level labels

- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
> [RW-1397][Risk=no] Fix maxCount to return 100

- ui/src/app/views/app/component.ts
> [risk=no] Hide initial spinner on initial error

- api/src/main/resources/emails/welcomeemail/content.html
- ui/src/index.html
- ui/src/styles.css
> [RW-1422][Risk=low] Change font to montserrat

- ui/src/app/app.module.ts
- ui/src/app/views/concept-homepage/component.css
- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/sliding-fab/component.css
- ui/src/app/views/sliding-fab/component.html
- ui/src/app/views/sliding-fab/component.ts
> [RW-1285][risk=low] Factor out a sliding FAB component

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/resolvers/concept-set.ts
- ui/src/app/utils/highlight-search.pipe.ts
- ui/src/app/views/breadcrumb/component.ts
- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-set-details/component.css
- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/app/views/concept-table/component.ts
- ui/src/app/views/sliding-fab/component.css
- Fully styled
- Missing most of the interesting functionality:
- action menu functionality
- "remove from set" functionality
- edit mode
- Minor adjustments to the concepts table to support my usage
> [RW-1285][risk=no] Implement initial concept set details page

- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
No jira. This PR just does a little test refactoring to make it easier to reuse test data.
> [risk=no] Minor test refactor

- ui/src/app/views/workspace-list/component.css
> [risk=no] change ws permission label font size

- ui/src/app/styles/cards.css
- ui/src/app/views/resource-card/component.html
Quick PR to add labels to concept set resource cards, (also fix font for all labels)
> [No ticket][Risk=no] add concept set labels

- ui/src/app/views/concept-set-details/component.css
- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/testing/stubs/concept-sets-service-stub.ts
Screenshots (I took some liberties with the designs, based on other screens):
> [RW-1285][risk=no] Implement concept set details edit functionality

- ui/src/app/views/concept-set-details/component.css
- ui/src/app/views/concept-set-details/component.html
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-details/component.ts
- ui/src/app/views/confirm-delete-modal/component.ts
- ui/src/testing/stubs/concept-sets-service-stub.ts
Depends on #1283 
Screenshots:
> [RW-1285][risk=no] Implement concept set details page action menu

- public-ui/src/environments/environment.prod.ts
Forgot to send this config change (doesn't really matter for now, since the services aren't currently being deployed in prod)
> [risk=no] Point public-ui to the prod domain

- ui/src/app/icons/left-scroll/component.html
- ui/src/app/icons/right-scroll/component.html
- ui/src/app/views/recent-work/component.css
- Pointer
- Don't show alt text of "scroll@3x":
> [risk=no] Scroll component style tweaks

- ui/src/app/views/workspace-nav-bar/component.css
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.spec.ts
- Style: border color updated to match mocks
- Close the action menu after clicking an action + regression test
> [RW-1321][risk=no] Fix workspace nav bar bugs

- ui/package.json
- ui/yarn.lock
Ugrade ngx-popper version to 5.1.7
> [risk=no] Update ngx-popper version

- ui/src/app/views/concept-set-details/component.html
> [RW-1285][risk=no] Add back-link from concept set details -> list

- ui/src/app/views/concept-homepage/component.css
- ui/src/app/views/concept-homepage/component.html
> [RW-1318][Risk=no] Update styling on concepts homepage to respond more reactively

- ui/src/app/views/resource-card/component.ts
Plugging concept set details in
> [No ticket][Risk=no] open concept set details

- api/config/cdr_versions_local.json
- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-48-default-cdr.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/CdrVersionsController.java
- api/src/test/java/org/pmiops/workbench/api/CdrVersionsControllerTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/UpdateCdrVersions.java
- common-api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- common-api/src/main/java/org/pmiops/workbench/db/dao/CdrVersionDao.java
- common-api/src/main/java/org/pmiops/workbench/db/model/CdrVersion.java
- public-api/src/main/java/org/pmiops/workbench/config/CdrConfig.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/CdrVersionsController.java
Moves the default'ness config from config.json to cdr_versions.json (ultimately in MySQL).
> [RW-1355][risk=no] Set CDR default via cdr_versions.json

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-1455
Handle spaces in the recent paths.
> [RW-1455][risk=low] Handle spaces in path

- api/db/changelog/db.changelog-49-add-concept-set-to-user-recent-resource.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/UserRecentResource.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/resources/emails/idverificationemail/content.html
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/service/UserRecentResourceServiceTest.java
- ui/src/app/cohort-review/create-review-page/create-review-page.css
- ui/src/app/cohort-review/create-review-page/create-review-page.html
- ui/src/app/cohort-review/create-review-page/create-review-page.spec.ts
- ui/src/app/cohort-review/create-review-page/create-review-page.ts
- ui/src/app/cohort-review/detail-page/detail-page.spec.ts
- ui/src/app/cohort-review/page-layout/page-layout.html
- ui/src/app/cohort-review/page-layout/page-layout.spec.ts
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.spec.ts
- ui/src/app/cohort-review/routing/routing.module.ts
- ui/src/app/views/unregistered/component.html
- ui/src/app/views/unregistered/component.spec.ts
- Skin create review set page according to Invision screen:
[https://projects.invisionapp.com/d/main#/console/12820961/322629386/preview](url)
- Disable 'Create Set' button after clicked (also referenced in RW-1158 and RW-1324)
- Change 'Save' to 'Create' in title and button text
Create button disabled until a value is entered:
Button enabled with valid input:
Clarity alert shows for input errors:
> [RW-1444][risk=no] Skin create review set page

- api/src/integration/resources/schema.sql
> [risk=no] Fix integration test SQL schema

- api/src/integration/resources/data.sql
Verified passing locally, submitted the other too quickly.
> [risk=no] Actually fix ApplicationTest

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/notebooks.yaml
> Swap to create cluster V2

- api/src/main/resources/cb_search_api.yaml
> [risk=no] Adding Snomed criteria type.

- api/src/main/resources/cb_search_api.yaml
- ui/src/app/cohort-search/demographics/demographics.component.ts
Fix age slider count to update when changing age range using number inputs
> [RW-1468][risk=no] Fix age slider count in demographics

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
> [RW-1348][Risk=no] Blrubenstein/create workspace character limit

- api/config/cdr_versions_prod.json
> [RW-1416][risk=no] Upgrade prod to newly imported synthetic CDR indexes

- api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
add bad request exception handling for annotation save calls.
> [risk=no] add bad request exception handling for annotation save calls.

- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.spec.ts
- ui/src/app/views/workspace/component.ts
Demo: https://calbach-dot-all-of-us-workbench-test.appspot.com/workspaces
Note: there may be a brief delay before the name is displayed - during this time it will appear blank.
> [RW-654][risk=no] Show CDR name instead of version

- ui/src/app/views/workspace-share/component.ts
Apologies - I must have added this line after manual testing. Of course, we don't want to show errors after every click of "save".
> [risk=no] Fix share error logic

- ui/src/app/views/workspace-share/component.css
- ui/src/app/views/workspace-share/component.html
> [RISK=NO][RW-1471]Link in sharing tooltip is impossible to click

- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/concept-add-modal/component.ts
- ui/src/app/views/conceptset-create-modal/component.spec.ts
- ui/src/app/views/conceptset-create-modal/component.ts
Changing create concept set endpoint to take a request with concept set,
added IDs.
> [RW-1477] Adding concepts to concept set on creation. [risk=no]

- ui/src/app/views/account-creation-modals/component.css
- ui/src/app/views/account-creation-success/component.html
- ui/src/app/views/account-creation/component.css
- ui/src/app/views/breadcrumb/component.css
- ui/src/app/views/cohort-list/component.css
- ui/src/app/views/concept-add-modal/component.css
- ui/src/app/views/concept-homepage/component.css
- ui/src/app/views/concept-set-details/component.css
- ui/src/app/views/concept-set-list/component.css
- ui/src/app/views/concept-table/component.css
- ui/src/app/views/conceptset-create-modal/component.css
- ui/src/app/views/confirm-delete-modal/component.css
- ui/src/app/views/edit-modal/component.css
- ui/src/app/views/homepage/component.css
- ui/src/app/views/new-notebook-modal/component.css
- ui/src/app/views/notebook-list/component.css
- ui/src/app/views/profile-page/component.css
- ui/src/app/views/resource-card/component.css
- ui/src/app/views/stigmatization-page/component.css
- ui/src/app/views/workspace-edit/component.css
- ui/src/app/views/workspace-list/component.css
- ui/src/app/views/workspace-nav-bar/component.css
- ui/src/app/views/workspace-share/component.css
- ui/src/app/views/workspace/component.css
- ui/src/index.html
Lou and I caught a pretty scary bug that meant none of the bold text on the page was actually bold... this should fix that. (Loading the font only loaded the standard formatting.)
> [No Ticket][Risk=no] Fix the fonts!

- ui/src/app/views/workspace-nav-bar/component.html
ONLY merge once we're satisfied with Concept Sets.
> [No Ticket][Risk=no] uncommenting Concept Sets tab

- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
> [RW-1484][Risk=no] Add HREF

- api/scripts/setup_notebook_cluster.sh
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
Changing pyclient lib used when setting up new clusters to
pyclient-v1-15.
> [RW-1485] Fixing concept fetch used by cohort review.

- api/config/config_prod.json
- api/config/config_stable.json
> [RW-1487][risk=no] Send stable/prod verification notification emails to support list

- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
Value is set to cluster project. Will be used to bill BQ usage to the user billing project, rather than the
billing project for the workspace.
> [RW-1482] Changing cluster localization to write CDR_BILLING_CLOUD_PROJECT [risk=no]

- ui/src/app/cohort-review/annotation-item/annotation-item.component.css
- ui/src/app/cohort-review/set-annotation-create/set-annotation-create.component.html
- ui/src/app/cohort-review/set-annotation-item/set-annotation-item.component.css
Creating annotation with really long name causes 500, endless spinner
> [RW 1352][risk=no]Creating annotation with really long name causes 500, endless spinner

- api/db-cdr/changelog-data/db.changelog-9.xml
- api/db-cdr/csv/domain_vocabulary_info.csv
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/DomainVocabularyInfoDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/DomainInfo.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/DomainVocabularyInfo.java
(when there's no query string.)
> [RW-1439] Using domain_vocabulary_info for returning vocab counts [risk=no]

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- ui/src/app/views/profile-page/component.html
> [RW-1345][risk=no] Disable changing contact email until we support reverification

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/TestWebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
In prod/stable, we will not be using appspot domains.
> [RW-1479][risk=no] Refactor apiHostName -> config.apiBaseUrl to support custom domains

- api/db-cdr/generate-cdr/generate-cdr.rb
- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/scripts/setup_notebook_cluster.sh
I used this to update the ACL on the new CDR version dataset.
(Will update the playbook to indicate to run this command when creating a new CDR version dataset.)
Upgrading to pyclient-v1-16.
> Adding command for updating CDR dataset ACL.

- api/db-cdr/generate-cdr/cloudsql-import.sh
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- ui/src/app/cohort-search/demographics/demographics.component.css
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
> [RW-1492][risk=no] Demographics Enhancement

- ui/src/app/views/workspace-nav-bar/component.html
> [No Ticket][Risk=no] Swap tabs

- ui/src/app/cohort-search/node/node.component.ts
> [risk=no] Bug fixes for loading tree

- public-ui/src/app/app-routing.module.ts
- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/views/db-header/db-header.component.html
- public-ui/src/app/views/db-home/db-home.component.html
1. Changed the survey-link to direct to quick-search in surveys.
2. Fixed the sources display bug.
> [risk=no] DB-104 (survey link change and sources display bug fix)

- ui/src/app/views/cohort-list/component.css
- ui/src/app/views/cohort-list/component.html
- ui/src/app/views/concept-set-list/component.css
- ui/src/app/views/concept-set-list/component.html
- ui/src/app/views/notebook-list/component.css
- ui/src/app/views/notebook-list/component.html
> [risk=no][RW-1521] fix card wrap for notebooks list, cohorts list, and concept sets list

- ui/src/app/views/notebook-list/component.ts
> [RW-1413][risk=no] Disable "create notebook" for read-only user

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Adding length constraint to given name, family name, and area of research fields in profile page
> [RW-751][Risk=no] adding length constraints to user fields

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/jira/JiraServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/jira/JiraServiceImplTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/app/views/bug-report/component.css
- ui/src/app/views/bug-report/component.html
- ui/src/app/views/bug-report/component.ts
- API support for an alternate bug type "Data Quality" or "Workbench Application" (default is "application")
- "data" sends tickets to the CDR Jira component
- UI for dropdown (checking UX guidance with @lstrano-broad )
- Minor bug report UX fixes
- Use a loading spinner and wait for submit before closing the modal
- Clear error state on the dialog before reopening
> [RW-1270][risk=low] Fix bug report bugs, add "CDR" bug type

- public-ui/.angular-cli.json
- public-ui/src/index.html
- ui/.angular-cli.json
- ui/src/index.html
> [risk=no] Fix leftover "prototype" references from initial skeleton code

- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/cohort-list/component.ts
> [RW-1411][risk=no] Fix cohorts loading, remove lots of dead code

- api/config/cdr_versions_test.json
fixing bug with cloud cdr versions.
> [risk=no] fixing bug with cloud cdr versions.

- ui/src/app/views/homepage/component.html
- ui/src/app/views/recent-work/component.html
- ui/src/app/views/recent-work/component.ts
- ui/src/index.html
> [risk=no]make homepage recent work cards the correct size

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
> [risk=no] autocomplete fix

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace/component.html
> [risk=no][RW-1459]Must be project owner to edit workspace or research purpose

- ui/src/app/styles/cards.css
- ui/src/app/views/notebook-list/component.html
- ui/src/app/views/workspace/component.html
> [risk=no][RW-1547][P3]disable old help tips

- ui/src/app/views/signed-in/component.html
> [risk=no][RW-1546][P3] fix 'report a bug' fontsize

- ui/src/app/views/cohort-list/component.html
- ui/src/app/views/concept-set-list/component.css
- ui/src/app/views/concept-set-list/component.html
- ui/src/app/views/concept-set-list/component.ts
- ui/src/app/views/resource-card/component.ts
> [RW-1544][Risk=no] Blrubenstein/fix delete modals

- ui/src/app/cohort-search/node-info/node-info.component.ts
- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
When a parent is selected in the Drugs tree, move only the parent over, not all child nodes
> [RW-1550][risk=no] Drugs - Don't add children of selected parents

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
fix for concept set recent resource cards not displaying correctly
> [RW-1538][Risk=no] fix for concept set recent resource cards

- ui/src/app/views/quick-tour-modal/component.ts
> [risk=no][RW-1534] fix quick tour wording

- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1549
> [RW-1549][risk=no] Open Data Browser in new tab

- api/src/main/resources/emails/idverificationemail/content.html
- api/src/main/resources/emails/welcomeemail/content.html
> [RW-1180][Risk=no] Update emails

- ui/package.json
- ui/yarn.lock
https://precisionmedicineinitiative.atlassian.net/browse/RW-866
All UI tests pass locally. Waiting for CI before requesting review.
> [RW-866][risk=no] Upgrade Jasmine

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
Changed the public db version to use the latest version.
> [risk=no] public database version change

- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
> [risk=no] fix parent searh

- ui/src/app/views/homepage/component.spec.ts
- ui/src/app/views/homepage/component.ts
- ui/src/testing/stubs/profile-service-stub.ts
> [RW-1545][Risk=no] Fix for quickTour Modal not opening on first visit

- ui/src/app/views/notebook-list/component.spec.ts
- ui/src/app/views/recent-work/component.spec.ts
- ui/src/app/views/resource-card/component.html
- ui/src/app/views/resource-card/component.ts
> [No ticket][Risk=no] Fixing notebook display names

- ui/src/environments/environment.test.ts
Modified the enableTemporal flag for test
> [TempFlagRemove][risk = no] Modified the enableTemporal flag for test

- ui/src/app/cohort-search/search-group/search-group.component.spec.ts
- ui/src/app/cohort-search/search-group/search-group.component.ts
- ui/src/environments/environment.ts
Added temp flag in environtment.ts
> [temp_flag][risk=no] Added temp flag in environtment.ts

- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/resource-card/component.html
- ui/src/app/views/resource-card/component.ts
> Playground branch suggestions

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/db-cdr/generate-cdr/make-bq-data.sh
> [RW-1531][Risk=no] Blrubenstein/fix filter counts

- ui/src/app/views/settings/component.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-1535
> [RW-1535][risk=no] Relax cluster state requirements for clicking "reset"

- ui/src/app/views/workspace-share/component.html
- ui/src/app/views/workspace/component.html
> [RW-1581][Risk=no] Update tooltips

- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/overview/overview.component.html
Update disabled conditions for save cohort button
> [RW-1592][risk=no] Update disabled conditions for save cohort button

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
> [RW-1578][Risk=no] Fix users not signed in showing up

- ui/src/app/views/homepage/component.css
- ui/src/app/views/homepage/component.html
- ui/src/app/views/homepage/component.ts
- ui/src/app/views/signed-in/component.css
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
> [RW-1584][P2][risk=no] Disable workspace create until FC billing project is initialized

- ui/src/app/views/signed-in/component.ts
See https://github.com/all-of-us/workbench/pull/1461
> [RW-1584][P2][risk=no] Clean up for PR#1461

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/db/model/UserRecentResource.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- Take the first 5 notebooks in the cache and test that they actually exist
- Test via GCS getBlob, this is generally faster than list
> [RW-1528][risk=low] Verify notebooks exist before returning recent resources

- ui/src/app/views/account-creation/component.html
> reduce tooltip text on account create for research purpose

- ui/src/app/views/account-creation/component.html
- ui/src/app/views/profile-page/component.html
> [RW-1590][risk=no]correct language for research purpose

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
> [risk=no] add code to autocomplete

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
Adding upper() to sql statement.
> [risk=no] Adding upper() to sql statement.

- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
Number of participants change in Demographics when add more criterion from dropdown.
> [RW-1595][risk =no]Number of participants change in Demographics when add more criterion from dropdown.

- ui/karma.conf.js
This is the needed change to the Jasmine config... Should I also go through specs and change them back where we had changed them to follow the queryAll patter....? Thoughts
> [RW-1424][Risk=no] Updating Jasmine config to prevent breaking on null DebugElement

- ui/src/app/views/resource-card/component.css
> [RW-1404][Risk=no] Fix weird extra whitespace to make CH happy! :)

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.spec.ts
- ui/src/app/views/profile-page/component.ts
Reverts all-of-us/workbench#1481 - see comments on there as well as https://precisionmedicineinitiative.atlassian.net/browse/RW-1651
@jacmrob FYI
> [risk=no][RW-1651][RW-1523] Revert "profile edit client side input validation"

- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
making age at event column sortable.
> [RW-1620][risk=no] making age at event column sortable.

- ui/src/app/cohort-search/utils.ts
Removing codes from Snomed selections
> [RW-1632][risk=no] Removing codes from Snomed selections

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.spec.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/cohort-search/node-info/node-info.component.css
- ui/src/app/cohort-search/node/node.component.ts
- ui/src/app/cohort-search/option-info/option-info.component.ts
- ui/src/app/cohort-search/utils.ts
> [RW-1655][risk=no] fixing unnecessary api calls.

- ui/src/app/cohort-search/search-bar/search-bar.component.ts
> [RW-1614][risk=no] fixing visit search.

- api/demos/diabetes-cases.json
> [RW-1659][risk=no][P2] fix name of demo cohort

- api/demos/diabetes-cases.json
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/views/new-notebook-modal/component.spec.ts
- ui/src/app/views/new-notebook-modal/component.ts
Make api call to save annotation immediately on change, separate timeouts for loading/success icons from api call
> [RW-1619][risk=no] Cohort review - fix text annotation save

- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
- public-ui/src/app/utils/db-config.service.ts
- public-ui/src/app/views/pm/pm.component.html
- public-ui/src/app/views/pm/pm.component.ts
1. Add intersex and none sex charts in physical measurements page.
> [risk=no] Intersex and none sex charts in pm page

- ui/src/app/views/conceptset-create-modal/component.html
> [RW-1663][risk=no][P3] Fix language on concept set builder modal

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
- public-ui/src/app/utils/db-config.service.ts
- public-ui/src/app/views/pm/pm.component.html
- public-ui/src/app/views/pm/pm.component.ts
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/create-review-page/create-review-page.ts
- ui/src/app/cohort-review/detail-header/detail-header.component.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/cohort-review/overview-page/overview-page.ts
- ui/src/app/cohort-review/set-annotation-modal/set-annotation-modal.component.ts
- ui/src/app/views/conceptset-create-modal/component.html
- ui/src/app/views/new-notebook-modal/component.spec.ts
- ui/src/app/views/new-notebook-modal/component.ts
> [RW-1675][risk=no] fixing bad calls to api.

- ui/src/app/views/bug-report/component.html
- ui/src/app/views/bug-report/component.ts
> [RW-1668][Risk=no] Fix bug with ability to submit empty bugs

- ui/src/app/cohort-review/detail-page/detail-page.css
[P4] CB - review slider arrows
> [RW-1624][risk = no] [P4] CB - review slider arrows

- ui/src/app/cohort-review/detail-page/detail-page.css
- ui/src/app/cohort-search/selection-info/selection-info.component.html
- ui/src/app/views/bug-report/component.html
- ui/src/app/views/bug-report/component.ts
- ui/src/app/views/workspace-edit/component.html
> [RW-1641][risk=no][P4] CB - demo tool tip issue

- ui/src/app/cohort-review/detail-all-events/detail-all-events.component.html
- ui/src/app/cohort-review/detail-page/detail-page.css
- ui/src/app/cohort-search/selection-info/selection-info.component.html
removing hand cursor from all events list.
> [RW-1623][risk=no] removing hand cursor from all events list.

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
- public-ui/src/app/utils/highlight-search.pipe.ts
- ui/src/app/utils/highlight-search.pipe.ts
1. Fixed the regex expression to be highlighted.
2. Fixed the way multiple keywords were modified in concept service.
> [risk=no] DB-HighlightSearchTextIssueFix

- api/db/changelog/db.changelog-53-research-purpose-type.xml
- api/db/changelog/db.changelog-master.xml
> [RW-1669][risk=no][P2] support long research purpose

- api/db/changelog/db.changelog-53-research-purpose-type.xml
- api/db/changelog/db.changelog-master.xml
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
- public-ui/src/app/utils/highlight-search.pipe.ts
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/annotation-list/annotation-list.component.html
- ui/src/app/cohort-review/annotation-list/annotation-list.component.ts
- ui/src/app/utils/highlight-search.pipe.ts
Fix bug where updates to annotations values get cleared if you create or delete an annotation
> [RW-1613][risk=no] Fix annotation updates in list

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/views/account-creation/component.ts
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/invitation-key/component.spec.ts
- ui/src/app/views/profile-page/component.html
- ui/src/app/views/profile-page/component.spec.ts
- ui/src/app/views/profile-page/component.ts
- no empty fields client-side validation in create profile
- no empty fields client-side validation in update profile
- no empty fields server-side validation in create profile
- no empty fields server-side validation in update profile
- enforce character cap on research purpose
> [RW-1523][risk=no][P2] Profile validation

- ui/src/app/views/quick-tour-modal/component.css
- ui/src/app/views/quick-tour-modal/component.html
- ui/src/app/views/quick-tour-modal/component.ts
- grey background when modal open
- fix link colors
- fix button hover color (match the next button)
> [RW-1582][risk=no] quick tour fixes

- public-ui/src/environments/environment.prod.ts
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-1680
Add missing client id config so prod deploy works.
> [RW-1680][risk=no] Add client id config for prod

- ui/src/app/views/quick-tour-modal/component.ts
> [RW-1677][Risk=no] Fix link placement on quick-tour

- ui/src/app/views/quick-tour-modal/component.ts
> [RW-1679][Risk=no] Fix grammar

- ui/src/app/app-routing.module.ts
- ui/src/app/cohort-common/combo-chart/combo-chart.component.ts
- ui/src/app/cohort-review/annotation-item/annotation-item.component.css
- ui/src/app/cohort-review/annotation-item/annotation-item.component.html
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/overview-page/overview-page.css
- ui/src/app/cohort-review/overview-page/overview-page.html
- ui/src/app/views/notebook-redirect/component.css
- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/quick-tour-modal/component.ts
- ui/src/app/views/signed-in/component.css
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
- ui/src/app/views/workspace-nav-bar/component.html
- ui/src/app/views/workspace-nav-bar/component.ts
Allow users to manually enter a date in text input
> [RW-1617][risk=no] Fix date annotation entry/format bug

- public-ui/src/app/app-routing.module.ts
- public-ui/src/app/views/app/app.component.ts
- public-ui/src/environments/environment.local.ts
- public-ui/src/environments/environment.prod.ts
- public-ui/src/environments/environment.stable.ts
- public-ui/src/environments/environment.staging.ts
- public-ui/src/environments/test-env-base.ts
- public-ui/src/index.html
https://precisionmedicineinitiative.atlassian.net/browse/RW-1684
Add environment specific google analytics ids to the public ui
> [RW-1684][risk=no] Add Env Specific GA ids

- ui/src/app/views/workspace-edit/component.ts
On discussion with Brandy (From PPI) and Kayla, changing from `transman` and `transwoman` to `trans man` and `trans woman` to more accurately reflect meaning and the community.
> [No Ticket][Risk=no] Add space for trans man and trans woman

- public-ui/src/app/app-routing.module.ts
- public-ui/src/app/views/app/app.component.ts
- public-ui/src/environments/environment.local.ts
- public-ui/src/environments/environment.prod.ts
- public-ui/src/environments/environment.stable.ts
- public-ui/src/environments/environment.staging.ts
- public-ui/src/environments/test-env-base.ts
- public-ui/src/index.html
- ui/src/app/cohort-review/annotation-item/annotation-item.component.css
- ui/src/app/cohort-review/annotation-item/annotation-item.component.html
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/detail-page/detail-page.css
- ui/src/app/cohort-review/page-layout/page-layout.css
- ui/src/app/views/workspace-edit/component.ts
[P4] CB - review header problem
> [RW-1650][risk=no][P4] CB - review header problem

- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/views/concept-add-modal/component.css
- ui/src/app/views/concept-add-modal/component.html
- ui/src/app/views/concept-add-modal/component.spec.ts
- ui/src/app/views/concept-add-modal/component.ts
Remove 'Surveys' from participant details tabs until we have data to show
> [RW-1639][risk=no] Review - remove stubs from participant detail tabs

- ui/src/app/views/concept-homepage/component.css
- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
- ui/src/app/views/sliding-fab/component.html
- ui/src/app/views/sliding-fab/component.ts
> [RW-1664][Risk=no] Blrubenstein/clear search

- ui/src/app/cohort-review/detail-all-events/detail-all-events.component.css
- ui/src/app/cohort-review/detail-header/detail-header.component.css
- ui/src/app/cohort-review/detail-header/detail-header.component.html
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.css
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/views/concept-add-modal/component.css
- ui/src/app/views/concept-add-modal/component.html
- ui/src/app/views/concept-add-modal/component.spec.ts
- ui/src/app/views/concept-add-modal/component.ts
- ui/src/app/views/concept-homepage/component.css
- ui/src/app/views/concept-homepage/component.html
- ui/src/app/views/concept-homepage/component.spec.ts
- ui/src/app/views/concept-homepage/component.ts
- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/notebook-redirect/component.spec.ts
- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/sliding-fab/component.html
- ui/src/app/views/sliding-fab/component.ts
Set table height to fit in the viewport so it should only scroll within the table, also fixed border for prev/next buttons when clicked.
> [RW-1627][risk=no] Review - fix scrolling for participant detail tables

- api/config/cdr_versions_prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-1274
> [RW-1274][risk=high] Configure production workbench CDR

- ui/src/app/views/quick-tour-modal/component.css
- ui/src/app/views/quick-tour-modal/component.html
- ui/src/app/views/quick-tour-modal/component.ts
> [RW-1678][Risk = no] Polishing the Quick Tour Modal

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
1. Changed public cdr version in test, stable, staging.
> [risk=no] Public cdr version change

- api/config/cdr_versions_prod.json
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.html
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.ts
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/app/views/quick-tour-modal/component.css
- ui/src/app/views/quick-tour-modal/component.html
- ui/src/app/views/quick-tour-modal/component.ts
- ui/src/typings.d.ts
Fix issue where tooltips flicker when moving the mouse over on smaller tree nodes
> [RW-1630][risk=no] Fix flickering tooltips in CB trees

- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.html
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.ts
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/modal/modal.component.css
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/node-info/node-info.component.html
- ui/src/typings.d.ts
[P4] CB - Demo modal Finish button disable while getting calculated number
> [RW-1647][risk=no] [P4] CB - Demo modal Finish button disable while getting calculated number

- ui/src/app/cohort-search/node-info/node-info.component.ts
Show counts for non-selectable parents in CPT tree
> [RW-1728][risk=no] Show counts for parents in CPT tree

- api/libproject/devstart.rb
removing gsuite admin key in docker clean.
> [risk=no] removing gsuite admin key in docker clean.

- api/libproject/devstart.rb
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
adding title to all tabs in review
> [RW-1649][risk=no] adding title to all tabs in review

- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
> [RW-1722][risk=no] remove 'No matching concept' from chart results

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
> [risk=no] fixing bq issue.

- ui/src/app/views/quick-tour-modal/component.css
> [risk=no] fix color of the hover for next/prev/close buttons in quick tour

- ui/src/app/views/quick-tour-modal/component.css
> [RW-1726][Risk=no] Fix styling

- api/src/main/resources/cb_search_api.yaml
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
- ui/src/app/cohort-search/overview/overview.component.css
- ui/src/app/cohort-search/overview/overview.component.html
- ui/src/app/cohort-search/overview/overview.component.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.css
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/search-group-item/search-group-item.component.ts
- ui/src/app/cohort-search/search-group/search-group.component.css
- ui/src/app/cohort-search/search-group/search-group.component.html
- ui/src/app/cohort-search/search-group/search-group.component.spec.ts
- ui/src/app/cohort-search/search-group/search-group.component.ts
adding visit type name to json definition for query report
> [RW-1739][risk=no] adding visit type name to json definition for query report

- api/cluster-resources/setup_notebook_cluster.sh
This is needed to handle recent Leo image upgrades.
> [risk=no] Switch to more general pip3 in cluster init script

- api/cluster-resources/setup_notebook_cluster.sh
- ui/src/app/cohort-search/attributes-page/attributes-page.component.css
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.html
- ui/src/app/cohort-search/redux/actions/service.ts
- ui/src/app/cohort-search/redux/reducer.ts
- ui/src/app/cohort-search/redux/store/selectors.ts
Add error handling for calculate api calls in attributes and modifiers components
Modifiers error if api call fails:
Attributes page:
> [RW-1771][risk=no] Error handling for attributes and modifiers

- deploy/docker-compose.yaml
https://precisionmedicineinitiative.atlassian.net/browse/RW-1767
This ensures more consistent deployments across developer machines / time.
> [RW-1767][risk=no] Use prebuilt Circle image for deploys

- api/config/cdr_versions_prod.json
- ui/src/app/cohort-search/demographics/demographics.component.html
- ui/src/app/cohort-search/demographics/demographics.component.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
Remove caching of demographics criteria to prevent unneeded api calls
> [RW-1780][risk=no] Prevent unneeded demographics api calls

- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
Fix bug where the criteria tree is empty after using modifiers
> [RW-1789][risk=no] Fix root tree node when using modifiers

- api/cluster-resources/setup_notebook_cluster.sh
- api/demos/Using Cohorts and Concepts.ipynb
> [RW-1804][risk=no] Upgrade pyclient library version to avoid https bug

- api/cluster-resources/setup_notebook_cluster.sh
- api/demos/Using Cohorts and Concepts.ipynb
- api/src/main/webapp/WEB-INF/web.xml
- public-api/src/main/webapp/WEB-INF/web.xml
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/redux/actions/service.spec.ts
- ui/src/app/cohort-search/redux/actions/service.ts
Prevent saving empty optional properties and unused temporal properties in cohort definitions
> [RW-1788][risk=no] Clean-up fields in cohort definition

- api/cluster-resources/setup_notebook_cluster.sh
- api/demos/Using Cohorts and Concepts.ipynb
- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- api/src/main/webapp/WEB-INF/web.xml
- public-api/src/main/webapp/WEB-INF/web.xml
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/redux/actions/service.spec.ts
- ui/src/app/cohort-search/redux/actions/service.ts
removing the clear method, as it was wiping the cohort reviews.
> [RW-1785][risk=no] removing the clear method, as it was wiping the cohort reviews.

- api/libproject/devstart.rb
> [risk=no] Require SSL on SQL DB creation

- public-ui/src/environments/environment.prod.ts
Addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-1836
> [RW-1836][risk=no] Add workbench url to prod env

- public-ui/src/app/app.module.ts
- public-ui/src/app/services/error-reporter.service.ts
1. Added error reported to public-ui.
> [risk=no] DB-144 Stackdriver error logging config for db

- ui/src/app/views/concept-homepage/component.ts
> enable 'add to set' button when a concept in the domain is selected

- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
- ui/src/app/cohort-search/search-group-item/search-group-item.component.css
- ui/src/app/cohort-search/search-group-item/search-group-item.component.html
- ui/src/app/cohort-search/selection-info/selection-info.component.css
- ui/src/app/cohort-search/selection-info/selection-info.component.html
- ui/src/app/cohort-search/selection-info/selection-info.component.ts
Add 'OR' for first item of multiple grouped selections in wizard for Conditions and Procedures. Also adjusted font-weight for 'OR's to 14px
> [RW-1848][risk=no] Fix display for wizard selections

- api/db-cdr/changelog-schema/db.changelog-23.xml
> [risk=no] fixing liquibase bug.

- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.ts
- public-ui/src/app/utils/db-config.service.ts
- public-ui/src/app/views/ehr-view/ehr-view.component.css
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
1. Displaying only part of the synonyms unless user wants to view all.
> [risk=no] Db 149 Hiding the synonyms 

- public-api/README.md
- public-ui/README.md
> [risk=no] Add a databrowser README disclaimer

- api/config/cdr_versions_test.json
> [risk=no] changing test cloundsql cdr.

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
> [risk=no] promoting new cloud cdr.

- common-ui/common-ui-devstart.rb
> Try fixing UI deploy

- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/cb_search_api.yaml
- api/src/main/resources/client_api.yaml
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/jira.yaml
- api/src/main/resources/mandrill_api.yaml
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
> [RW-1856][Risk=medium] updating swagger codegen

- api/config/cdr_versions_prod.json
> [risk=no] promoting prod cdr.

- ui/src/app/cohort-search/node-info/node-info.component.ts
Remove condition where node names are hidden when the code is the same as the name
> [RW-1861][risk=no] Fix blank unmapped ingredients nodes

- api/config/cdr_versions_prod.json
> [risk=no] adding syn cdr for prod

- api/src/main/resources/cb_review_api.yaml
- api/src/main/resources/cb_search_api.yaml
- api/src/main/resources/client_api.yaml
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/jira.yaml
- api/src/main/resources/mandrill_api.yaml
- api/src/main/resources/notebooks.yaml
- api/src/main/resources/workbench.yaml
This reverts commit 3842c6497210e442883614f25253d7b110db0c42.
Temporarily revert to unblock the release.
> [risk=no] Revert "updating swagger codegen (#1595)"

- public-api/src/main/java/org/pmiops/workbench/cdr/model/QuestionConcept.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/highlight-search/highlight-search.component.html
- public-ui/src/app/styles/page.css
- public-ui/src/app/views/db-header/db-header.component.css
- public-ui/src/app/views/db-home/db-home.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.css
- public-ui/src/app/views/survey-view/survey-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.ts
1. Change in the search title.
2. Displaying survey question answers on the graph and removed concept id from the answer text.
> [risk=low] DB-14[5-8] Data Browser search title, survey graph text updates, survey answer table updates

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- public-api/src/main/java/org/pmiops/workbench/cdr/model/QuestionConcept.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/styles/page.css
- public-ui/src/app/views/db-header/db-header.component.css
- public-ui/src/app/views/db-home/db-home.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.css
- public-ui/src/app/views/survey-view/survey-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.ts
- ui/src/app/cohort-search/search-bar/search-bar.component.ts
- ui/src/app/cohort-search/utils.ts
Prevent api call for autocomplete results from returning duplicates and fix highlighting of nodes with special characters in the name
> [RW-1867][risk=no] Fix matching/highlighting for autocomplete

- ui/src/app/cohort-common/module.ts
> [risk=no] rm bad ApiModule import

- public-api/src/main/resources/public-api.yaml
Adding application type for the post request search concepts api.
> [risk=no] DB-170 Adding application type

- common-api/src/main/java/org/pmiops/workbench/cdr/CommonTestDialect.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptService.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
1. The survey search result count is different from the actual search results in the survey page. 
(The search results are fetched with wildcard* and search result count was fetched with actual term search).
> [risk=no] fixing survey search counts

- deploy/bootstrap-docker.sh
> [risk=no][RW-1869] git clean earlier and more exhaustively during deploys

- common-ui/common-ui-devstart.rb
> revert unintended script change

- ui/angular.json
- ui/package.json
Based on @calbach comments in [this doc](https://docs.google.com/document/d/1taOFbLpUb0OOB0G0KHKZN3YnTiZWJK4HO8iXFp3iFIY/edit?usp=sharing)
> remove redundant test set up steps

- ui/src/app/utils/index.ts
This provides a way to get the current window dimensions into a component, so you can generate responsive inline styles when needed.
It can be used as a decorator on a React component, e.g.
```
@withWindowSize()
class Foo extends React.Component {
...
```
It will dynamically inject a prop called `windowSize`, which looks like `{ width: number, height: number }`, which can be then be used during rendering like any other prop. The dimensions will be updated automatically if the window resizes.
FYI, this wrapper technique is called a Higher Order Component, and is a common way to abstract out state management and lifecycle hooks into reusable, composable pieces.
> [risk=no] add withWindowSize HOC

- api/db-cdr/generate-cdr/generate-criteria-table.sh
- api/docker-compose.yaml
- api/libproject/devstart.rb
criteria table creation script
> [RW-1529][Risk=no] criteria table creation script

- api/db-cdr/changelog-schema/db.changelog-24.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/csv/survey_module.csv
- api/db-cdr/generate-cdr/csv/survey_module.csv
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/model/SurveyModule.java
- public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
- public-ui/src/app/data-browser/chart/chart.component.css
- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.ts
- public-ui/src/app/highlight-search/highlight-search.component.css
- public-ui/src/app/highlight-search/highlight-search.component.html
- public-ui/src/app/styles/page.css
- public-ui/src/app/views/app/app.component.html
- public-ui/src/app/views/db-home/db-home.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
- public-ui/src/app/views/quick-search/quick-search.component.html
1. Removed content-area which gets the inner scroll container.
2. Changed gender pie charts to bar.
3. Addresses DB-161, DB-168, DB-159, DB-169
> [risk=no] Remove scrolling container

- ui/package.json
- ui/yarn.lock
Per discussion in https://github.com/all-of-us/workbench/pull/1617
> [risk=no] Drop unused local storage dependency

- api/docker-compose.yaml
fixed indentation for context in docker-compose.yml file
> [risk=no]fixed indentation for context

- ui/src/app/utils/index.ts
This formalizes and extracts the wrapper code. Key points:
* The wrapper provides minimal functionality, so any existing special behavior or state management will need to be pushed out to a higher level container. This is by design, as anything crossing this boundary should ideally use idiomatic React conventions.
* Angular input property names must now exactly match the corresponding React prop names. This is also by design, for consistency.
* Angular seems to get confused with CSS paths using this approach, so we can't use `styleUrls`. Instead, we can import the CSS file directly, and pass it via `styles`. Note that this may be changing shortly anyway when we enable CSS modules.
> [risk=no] abstract out react-to-angular wrapper

- ui/src/app/views/app/component.ts
Follow-up to https://github.com/all-of-us/workbench/pull/1617 that addresses https://precisionmedicineinitiative.atlassian.net/browse/RW-1824
* Only try to set urls when cookies are enabled
* Only load tcell js (which relies on local storage) when cookies are enabled.
> [RW-1824][risk=no] More handling of disabled cookies.

- ui/src/app/cohort-review/table-page/table-page.html
p[4] Revew: Change Name of "Cohort Query Report" to "Cohort Description"
> [RW-1924] [risk = no] Revew: Change Name of "Cohort Query Report" to "Cohort Description"

- ui/src/app/views/homepage/component.html
- ui/src/app/views/quick-tour-modal/component.html
- ui/src/app/views/quick-tour-modal/component.tsx
> [risk=no][RW-1950] Fix quick tour image expand/shrink; use base wrapper

- common-ui/common-ui-devstart.rb
> [P1][RW-1971][risk=no] set --environment flag properly for public-ui deploy

- ui/src/app/utils/index.ts
> Move to onChanges

- ui/src/app/components/buttons.tsx
- ui/src/app/components/popups.tsx
- ui/src/app/components/tables.tsx
- ui/src/app/utils/index.ts
- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/concept-set-details/component.spec.ts
- ui/src/app/views/concept-set-list/component.spec.ts
- ui/src/app/views/confirm-delete-modal/component.tsx
- ui/src/app/views/notebook-list/component.spec.ts
- ui/src/app/views/quick-tour-modal/component.spec.tsx
- ui/src/app/views/quick-tour-modal/component.tsx
- ui/src/app/views/rename-modal/component.tsx
- ui/src/app/views/workspace-list/component.spec.ts
This moves us to using data test id, over id, and changes the lodash import to fp over ld to avoid looking like Id
> [No Ticket][Risk=no] Code cleanup

- deploy/bootstrap-docker.sh
> [risk=no] Ensure we fetch all tags for deployment

- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/concept-set-list/component.spec.ts
- ui/src/app/views/edit-modal/component.spec.tsx
- ui/src/app/views/edit-modal/component.tsx
> [risk=no][no ticket] Edit Modal tests cleanup

- ui/src/app/app.module.ts
- ui/src/app/utils/index.ts
- ui/src/app/utils/resourceActions.ts
- ui/src/app/views/cohort-list/component.spec.ts
- ui/src/app/views/concept-set-list/component.spec.ts
- ui/src/app/views/homepage/component.spec.ts
- ui/src/app/views/notebook-list/component.spec.ts
- ui/src/app/views/recent-work/component.spec.ts
- ui/src/app/views/resource-card/component.html
- ui/src/app/views/resource-card/component.spec.ts
- ui/src/app/views/resource-card/component.tsx
- ui/src/app/views/workspace/component.spec.ts
Implements the popup menu on resource cards using the new popup library.
> [risk=no] convert resource card menu to React

- ui/src/app/views/account-creation/component.tsx
> [no ticket][Risk=no] Account creation follow up using new fetch, little cleanup

- ui/src/app/cohort-review/clearbutton-in-memory-filter/clearbutton-in-memory-filter.component.html
- ui/src/app/cohort-review/clearbutton-in-memory-filter/clearbutton-in-memory-filter.component.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
> [RW-1925][P4][risk=no] change "Start Date" to "Date"

- ui/yarn.lock
Looks like this was omitted from a recent PR.
> [risk=no] update yarn.lock

- public-ui/src/app/views/db-home/db-home.component.html
- public-ui/src/app/views/db-home/db-home.component.ts
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
- public-ui/src/app/views/quick-search/quick-search.component.ts
- public-ui/src/app/views/survey-view/survey-view.component.html
1. Changed AoU in text to AllOfUs
> DB-196 spelling out AoU

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/notebooks.yaml
> [RW-1990][Risk=no] Fix backwards compatibility issue with Leo

- ui/src/app/app-routing.module.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.html
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/cohort-review/individual-participants-charts/individual-participants-charts.tsx
- ui/src/app/components/alert.tsx
- ui/src/app/components/forms.tsx
- ui/src/app/components/headers.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/components/modals.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/invitation-key/component.tsx
[P3] Participants charts are not loading in the review. If there is no data for any domains hide charts for those domains.
- added info alerts when there is no data to show for chart.
> [RW-1983][risk=no] [P3] Participants charts are not loading in the review. If there is no data for any domains hide charts for those domains.	

- public-ui/src/app/app-routing.module.ts
- public-ui/src/app/views/quick-search/quick-search.component.html
- public-ui/src/app/views/quick-search/quick-search.component.ts
1. Making quick-search page the home page.
2. Adding physical measurements block under surveys in quick -search.
> DB-202 [risk=no] making quick search page home page  in db

- ui/src/app/views/notebook-redirect/component.ts
- ui/src/app/views/resource-card/component.html
- ui/src/app/views/resource-card/component.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
> [RW-1966][Risk=low] JupyterLab functional and opens

- public-ui/src/app/data-browser/chart/chart.component.css
- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/styles/page.css
- public-ui/src/app/utils/db-config.service.ts
- public-ui/src/app/views/app/app.component.css
- public-ui/src/app/views/app/app.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.css
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
1. Redesigned top 100 concept charts as per this design
https://projects.invisionapp.com/d/main#/console/13577480/339048498/preview
> [DB-180] [risk=no] Top 100 charts redesign according to new screens

- ui/src/app/views/quick-tour-modal/component.tsx
> [RW-2019][Risk=no] Fix sizing

- ui/app.yaml
- ui/src/assets/gsdv.txt
https://precisionmedicineinitiative.atlassian.net/browse/RW-2016
> [RW-2016][risk=low] Add domain verification file for stable

- ui/src/app/views/invitation-key/component.tsx
https://precisionmedicineinitiative.atlassian.net/browse/RW-1302
Depends on #1635
> [RW-1302][risk=no] Add basic client-side validation of invite keys

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
> [RW-2055][risk=no] removing unused api call

- ui/src/app/cohort-search/search-group-list/search-group-list.component.ts
Include/Exclude: remove the word "where"
> [RW-1743] [risk=no] Include/Exclude: remove the word "where"

- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/views/app/component.html
- ui/src/app/views/workspace/component.html
- ui/src/index.html
https://precisionmedicineinitiative.atlassian.net/browse/RW-2079
https://developers.google.com/web/tools/lighthouse/audits/noopener
> [RW-2079][risk=no] Add norel noopener on third party target=_blank links

- api/docker-compose.yaml
> [RW-1947][risk=low] Add Elasticsearch docker service

- ui/src/app/views/resource-card/component.tsx
This got broken along the way.
> [RW-2085][risk=no] fix notebook rename

- ui/src/app/components/buttons.tsx
- ui/src/app/components/card.tsx
This adds a component for the card-like 'Add' button on e.g. the notebooks list page.
> [risk=no] add CardButton

- ui/src/app/views/homepage/component.tsx
> [risk=no][RW-1969] missing import in homepage

- ui/src/app/views/resource-card/component.tsx
> [RW-2023][risk=no] Apply disabled styling for read-only resource card menu

- ui/src/app/app-routing.module.ts
> [No Ticket][Risk=low] Remove guard for now

- ui/src/app/app-routing.module.ts
- ui/src/app/guards/access-tasks-guard.service.ts
> [risk=no] Fix routing guard issue

- ui/src/app/components/spinners.tsx
- ui/src/app/views/homepage/component.html
- ui/src/app/views/recent-work/component.tsx
First time loading on dark background: 
Update loading on dark background: 
Update loading on light background:
> [RW-2091][risk=no] Recent work loading styles

- common-ui/common-ui-devstart.rb
> [risk=no] Fix public-ui dev-up --configuration

- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
- public-ui/src/app/data-browser/concept-charts/concept-charts.component.ts
- public-ui/src/app/utils/enum-defs.ts
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
- public-ui/src/app/views/pm/pm.component.html
- public-ui/src/app/views/pm/pm.component.ts
- public-ui/src/app/views/survey-view/survey-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.ts
1. Db-231, 232, 233, 236 related changes.
> [DB-231] [risk=no] updating chart titles and synonyms header

- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
1. See only first 110 characters of synonyms and then click on see more if you want to see more.
> [DB-198] [risk=no] change to show more synonyms

- api/libproject/devstart.rb
Note: new output does contain some spurious errors, but will correctly force rebuilds of images on the next dev-up (it's cached, so barely any slower).
```
./project.rb docker-clean
+ docker-compose down --volumes --rmi local
Removing network api_default
WARNING: Network api_default not found.
Removing volume api_db
Removing volume api_esdata
Removing volume api_gradle-cache
Removing volume api_gradle-public-api-cache
Removing image api_scripts
ERROR: Failed to remove image for service scripts: 404 Client Error: Not Found ("No such image: api_scripts:latest")
Removing image api_api
ERROR: Failed to remove image for service api: 404 Client Error: Not Found ("No such image: api_api:latest")
Removing image api_public-api
ERROR: Failed to remove image for service public-api: 404 Client Error: …
```
> [risk=no] Better docker-clean image teardown

- ui/src/app/components/buttons.tsx
- ui/src/app/views/cohort-list/component.tsx
> [RW-1918][Risk=no] Fix styling

- ui/src/app/cohort-review/annotation-item/annotation-item.component.spec.ts
- ui/src/app/cohort-review/annotation-item/annotation-item.component.ts
- ui/src/app/cohort-review/create-review-page/create-review-page.spec.ts
- ui/src/app/cohort-review/create-review-page/create-review-page.ts
- ui/src/app/cohort-review/detail-header/detail-header.component.spec.ts
- ui/src/app/cohort-review/detail-header/detail-header.component.ts
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.spec.ts
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.spec.ts
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.spec.ts
- ui/src/app/cohort-review/participant-status/participant-status.component.ts
- ui/src/app/cohort-review/table-page/table-page.spec.ts
- ui/src/app/cohort-review/table-page/table-page.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
- ui/src/app/views/workspace-wrapper/component.ts
This continues removing dependencies on the router, using the stores instead.
> [risk=no] refactor away more router dependencies

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
@calbach this should fix future accounts. I am going to work out the backfill script as soon as I can.
> [RW-2125][Risk=no] Add case insensitivity

- ui/src/environments/environment.staging.ts
> [risk=no] Point staging at prod Shibboleth; needs to match FC

- api/db/changelog/db.changelog-56-update-email-lowercase.xml
- api/db/changelog/db.changelog-master.xml
> [RW-2125][Risk=moderate] Add backfill changelog

- .circleci/config.yml
This should show what URL is actually failing.
> [RW-2152][risk=no] --verbose yarn to get more insight into flakes

- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- ui/src/app/views/admin-user/component.html
- ui/src/app/views/admin-user/component.ts
- ui/src/app/views/signed-in/component.html
> [RW-2131][Risk=low] Srubenst/refactor disabled user

- README.md
- api/db-cdr/generate-cdr/generate-criteria-table.sh
- api/docker-compose.yaml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/views/account-creation/component.spec.tsx
- ui/src/app/views/account-creation/component.tsx
> [rw-1994][Risk=no] Updating PPI and Drugs trees

- hooks/pre-push
> [RW-2158][risk=no] Include tsx in lint hook

- ui/src/app/views/homepage/component.tsx
> [RW-2176][P1][risk=no] check for null page visits for first time user

- common-ui/common-ui-devstart.rb
https://circleci.com/gh/all-of-us/workbench/38122
> [RW-2152][risk=no] Add another --verbose on yarn to diagnose flakes

- api/src/main/resources/workbench.yaml
This is for cron job   /v1/cron/bulkSyncTrainingStatus:
> [RISK=LOW] Failing cron job GET instead of POST

- ui/src/app/views/resource-card/component.tsx
- ui/src/app/views/workspace-edit/component.html
- ui/src/app/views/workspace-edit/component.spec.ts
- ui/src/app/views/workspace-edit/component.ts
- ui/src/app/views/workspace-list/component.html
- ui/src/app/views/workspace-nav-bar/component.tsx
Grep'd views/ for clone. Think I got them all...
> [RW-1876][Risk=no] Change "Clone" to "Duplicate"

- api/config/cdr_versions_prod.json
1. cdr, public db version update in prod.
2. Data changes: path,is_main columns were added to survey_question_map to display sub question branching logic in surveys.
3. Pr that has the api and data change description: https://github.com/all-of-us/workbench/pull/1784
> [risk=low] Prod cdr version change

- public-ui/package.json
- public-ui/yarn.lock
- ui/package.json
- ui/yarn.lock
> [risk=no] Drop unused bootstrap dep

- .circleci/config.yml
See the Jira ticket and comment in config.yml for more info.
> [RW-2194] [risk=no] Try reducing the Java memory limit for CircleCI.

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/compliance/ComplianceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/moodle/MoodleConfig.java
- api/src/main/resources/moodle.yaml
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Call moodle api IF moodleApi is enabled.
Depending on the environment updates moodle host
> [RISK=LOW]Moodle flag and host change

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
Replace constructor  parameter from Provider<ComplianceService> to ComplianceService
> [Risk=no]Refactor userService

- ui/src/app/views/profile-page/component.tsx
> [RW-2196] Change training button in profile to link to moodle

- ui/src/app/views/cohort-list/component.tsx
> [RW-2191][Risk=no] Fix cohort add sizing

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/components/buttons.tsx
- ui/src/app/utils/resourceActionsReact.ts
- ui/src/app/views/cohort-list/component.spec.tsx
- ui/src/app/views/data-page/component.spec.tsx
- ui/src/app/views/data-page/component.tsx
- ui/src/app/views/workspace-nav-bar/component.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
> [RW-2170][Risk=no] Add data page

- ui/src/app/views/homepage/component.tsx
> [no ticket][risk=no] fix era commons language

- ui/src/app/components/alert.tsx
- ui/src/app/views/homepage/component.spec.tsx
- ui/src/app/views/homepage/component.tsx
> [no ticket][risk=no] Add an alert when waiting on badge completion API from moodle

- api/build.gradle
- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticUtils.java
- api/tools/build.gradle
- api/tools/src/main/java/org/pmiops/workbench/tools/elastic/CloudStorageShardedLineIterator.java
- api/tools/src/main/java/org/pmiops/workbench/tools/elastic/ElasticSearchIndexer.java
- api/tools/src/main/resources/bigquery/es_person.sql
- ui/angular.json
- ui/src/app/cohort-review/detail-tab-table/detail-tab-table.component.tsx
- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
- ui/src/app/components/alert.tsx
- ui/src/app/views/homepage/component.spec.tsx
- ui/src/app/views/homepage/component.tsx
Added overlay for Value and Name rows. 
RW-2057,  RW-2042, RW-2052, RW-2041
> [RW-2038][RW-2057][RW-2042][RW-2052][RW-2041][risk=no] Added overlay for Value and Name rows. 

- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/views/data-page/component.tsx
- ui/src/app/views/dataset/component.tsx
> [RW-2107] adding data set page

- ui/src/app/views/app/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Ready for review. Any questions don't hesitate!
> [RW-2010][Risk=low] Adding in gtag user agent custom dimension to allow us to filter in GA

- public-ui/src/app/highlight-search/highlight-search.component.ts
- public-ui/src/app/views/survey-view/survey-view.component.html
1. Fixing the bug that repeats text over and over when trying to highlight.
> [DB-246] [risk=low] fixing text repeat bug

- public-ui/src/app/views/survey-view/survey-view.component.html
- public-ui/src/app/views/survey-view/survey-view.component.ts
1. Filtering out the questions that do not have the results. 
2. Moving note to top which was strangely in the bottom.
> [risk=low] Db lifestyle error

- api/libproject/devstart.rb
- api/src/dev/server/Dockerfile
This will attempt to schedule a run of all of the rainforest tests from a script. This currently will not work, because we do not have enough tabular rows for emails and passwords to execute them all in one command.
> [RW-1452][Risk=moderate] Working rainforest test script

- ui/src/app/components/resources.tsx
- ui/src/app/views/data-page/component.spec.tsx
- ui/src/app/views/dataset/component.spec.tsx
- ui/src/app/views/dataset/component.tsx
- ui/src/app/views/resource-card/component.tsx
All comments addressed. Going to work on tests. And going to change this a regular PR so that if you have time and want to approve you can go ahead and do that.
> [RW-2098][Risk=no] View and Select Concept Sets in DataSet Builder

- api/src/main/resources/cb_search_api.yaml
Please help with the TODO (feel free to use the GitHub suggest feature to fill this in).
> [risk=no] Add num_of_occurrences docs

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticUtils.java
- api/tools/src/main/resources/bigquery/es_person.sql
TODO:
- May need more indexing for physical measurements.
> [RW-1948][risk=no] Add remaining domains to events index

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
1. Updating cdr version in test, stable and staging.
> [risk=low] cdr version change in test, stable and staging

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
1. Reverting back cdr version.
> [risk=low ] reverting cdr version change

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
RW-1488 seems much more appropriate for this comment, was probably just a typo.
> [risk=no] Fix Jira ticket reference.

- ui/src/app/cohort-review/detail-tabs/detail-tabs.component.ts
Add Date to the All Events, Conditions, Procedures in Review
> [RW-2255][risk=no]Add Date to the All Events, Conditions, Procedures in Review

- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
small fix on review data script.
> [risk=no] review script update

- api/db-cdr/generate-cdr/generate-cloudsql-db.sh
- api/db-cdr/generate-cdr/generate-local-cdr-db.sh
- api/db-cdr/generate-cdr/init-new-cdr-db.sh
- api/libproject/devstart.rb
1. Adding the version-flag in script to add necessary permission to public user based on the value in flag.
> [risk=no] Handling cdr version name in init-new-cdr script

- ui/src/app/views/homepage/component.tsx
fixes a release-blocking bug; the quick tour was not showing up on first visit bc it was null in profile.
> [P1][RW-2256][risk=no] show quick tour if page visits is null

- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
> [risk=no] cdr version change

- README.md
- api/config/config_local.json
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
- api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticSearchService.java
- api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
Sending for initial feedback.
Future work:
- Handling of "attributes"
- Integration testing
> [RW-1955][RW-2114][risk=low] Initial ElasticFilters implementation

- ui/src/app/views/settings/component.tsx
> [RW-2257][P3][risk=no] make reset cluster button language consistent

- public-ui/src/app/data-browser/chart/chart.component.ts
- public-ui/src/app/views/ehr-view/ehr-view.component.html
- public-ui/src/app/views/ehr-view/ehr-view.component.ts
1. Change the text that displays coutns as 20 to <= 20 in participants number column and chart titles.
> [risk=no] [Db 245] Update result counts for 20 to <= 20

- public-ui/src/app/highlight-search/highlight-search.component.ts
1. Fixing the bug that displays jus the last letter twice.
> [risk=no] fixing last latter repeat bug

- api/demos/Get Started in R Notebooks.ipynb
> [risk=no][RW-2162] Fix typo in R demo notebook

- ui/src/app/components/buttons.tsx
- ui/src/app/components/card.tsx
- ui/src/app/views/cohort-list/component.tsx
- ui/src/app/views/data-page/component.tsx
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/notebook-list/component.tsx
- ui/src/app/views/resource-card/component.tsx
- ui/src/app/views/workspace-list/component.tsx
> [P3][RW-2258][risk=no] fix styling on cohort create card

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
clean up of some debug code in a test case.
> [risk=no] clean up of some debug code in a test case.

- api/src/main/resources/cb_search_api.yaml
I took a stab at this, could use some help filling in the blanks and on my TODOs.
> [RW-2265][risk=no] Add more criteria docs

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-57-add-era-commons-completion-time.xml
- api/db/changelog/db.changelog-57-add-era-commons-entries.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/fireCloud.yaml
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/app/guards/access-tasks-guard.service.ts
- ui/src/app/views/homepage/component.spec.tsx
- ui/src/app/views/homepage/component.tsx
- ui/src/testing/stubs/profile-api-stub.ts
@jacmrob to make sure the UI eRA commons stuff all looks good.
@NehaBroad to make sure all the API eRA commons stuff all looks good.
@gjuggler to review the overall approach as a foundation for future data access frameworks.
> [RW-2235][Risk=low] Add era commons fields to db

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
> [risk=no] removing invalid tests.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/ReviewQueryBuilder.java
- api/src/main/resources/cb_review_api.yaml
added api call to get all vocabularies for review data.
> [RW-2262][risk=no] added api call to get all vocabularies for review data.

- api/libproject/devstart.rb
- api/src/dev/server/Dockerfile
> [RW-2289][Risk=low] Move to binary of Rainforest CLI

- README.md
> [RW-1793][risk=no][Docs only] Tech debt: document yarn dev-up

- api/build.gradle
- api/config/cdr_versions_stable.json
- api/config/cdr_versions_staging.json
- api/config/cdr_versions_test.json
- api/db-cdr/generate-cdr/generate-private-cdr-counts.sh
- api/db-cdr/generate-cdr/generate-public-cdr-counts.sh
- api/db/changelog/db.changelog-59-cluster-config-default.xml
- api/db/changelog/db.changelog-master.xml
- api/src/integration/java/org/pmiops/workbench/NotebooksIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/ClusterController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/StorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/resources/mockito-extensions/README.md
- api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
updating test, staging and stable cloud private cdr to synth_r_2019q1_2
> [risk=no] - cdr update

- ui/src/app/views/bug-report/component.spec.tsx
- ui/src/testing/stubs/bug-report-api-stub.ts
> [risk=no] Bug report spec was never pushed to git

- deploy/libproject/deploy.rb
> [RW-1974][risk=no] Don't redeploy data browser

- ui/src/app/utils/index.tsx
This adds a couple useful utility functions for manipulating data.
> [risk=no] add append and toggleIncludes utils

- ui/package.json
- ui/src/typings.d.ts
- ui/yarn.lock
Tagging CH for review for workbench, tagging Will for a quick making sure removing these doesn't break the cohort builder.
> [No Ticket][Risk=no] Remove old, unused dependencies

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
> [RW-591][Risk=low] Rework get workspaces

- ui/src/app/views/concept-add-modal/component.tsx
> [risk=no] fix import in concept add modal

- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PPIQueryBuilder.java
- ui/src/app/cohort-search/node-info/node-info.component.ts
> [risk=no] fixing PPI bug.

- ui/src/app/views/workspace/component.css
- ui/src/app/views/workspace/component.html
- ui/src/app/views/workspace/component.ts
Please note : Modal design is pending Lou approv
al
> [RW-2123][risk=no]Show a policy reminder before sending users to GCS bucket

- ui/src/app/icons/icons.module.ts
- ui/src/app/icons/reminder/component.tsx
- ui/src/app/views/notebook-redirect/component.html
- ui/src/app/views/notebook-redirect/component.spec.ts
> [RW-2127][Risk=no] Srubenst/notebook policy reminder text

- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/resources/workbench.yaml
follow-up to @UrsaStutsman's work storing the bypass variables in the db, first step to making them used in the UI is making them accessible from the profile.
> [RW-2240][risk=low] Put bypass variables in Profile

- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-review/table-page/table-page.ts
- ui/src/app/cohort-search/attributes-page/attributes-page.component.html
- ui/src/app/cohort-search/attributes-page/attributes-page.component.ts
- ui/src/app/cohort-search/demographics/demographics.component.css
- ui/src/app/cohort-search/demographics/demographics.component.ts
Bug fixes:
- Increase character limit for inputs on attributes form
- Prevent id for deceased parameters from containing null
- Remove extra 'OR' div from measurements attributes form
- Fix layout of demographics wizard with large number of options
- Move vocab api call to table-page component to make sure the review is generated first
> [RW-2329][risk=no] Bug fixes for cohort search and review

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [No Ticket][Risk=no] Add back id verification

- api/demos/physical-measurements.json
> [RW-2101][Risk=no] Add PM demo concept set

- ui/src/app/views/notebook-redirect/component.html
> [risk=no] Spell out All of Us

- ui/src/app/views/data-page/component.tsx
- ui/src/app/views/dataset/component.tsx
> [RW-2334][Risk=no] Move to going directly to tool for concept set add

- ui/src/app/guards/access-tasks-guard.service.ts
> [No ticket][Risk=no] Fix routing infinite loop

- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
> [No ticket][Risk=low] Fix data browser links

- api/db/changelog/db.changelog-60-backfill-bypass.xml
- api/db/changelog/db.changelog-master.xml
To be merged before the release where we plan to turn on eRA commons, Moodle, and Beta Access. @gjuggler PTAL to verify backfill script.
I have verified locally that `id_verification_is_valid` is true if approved, false if rejected, and null if no action.
> [RW-2331][Risk=moderate] Backfill Script for Bypass

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- Use the lambda form rather than the anonymous `Function` class
> [risk=no] Reduce UserService verbosity

- README.md
- api/db-cdr/generate-cdr/generate-criteria-table.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
- api/libproject/devstart.rb
code to create denormalized tables for Data Set Builder
> [rw2330][risk=NO] code to create denormalized tables for Data Set Builder

- api/config/cdm/cdm_5_2.json
> [No Ticket][Risk=low] Added foreign key

- api/db/changelog/db.changelog-65.xml
- api/db/changelog/db.changelog-master.xml
adding update statement for review.
> [risk=no] adding update statement for review.

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/search_all_domains_data.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCounter.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/AbstractQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/CodesQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/DrugQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/MeasurementQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PMQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/PPIQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/querybuilder/VisitsQueryBuilder.java
- ui/src/app/cohort-search/modal/modal.component.html
- ui/src/app/cohort-search/modal/modal.component.ts
add source/standard to all search queries
> [RW-2365][risk=no] add source/standard to all search queries

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
> [risk=no] removing unused endpoint.

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/api/ConceptsController.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
- ui/src/app/components/resources.tsx
- ui/src/app/views/dataset/component.tsx
@freemabd1 to verify the bigquery schema request for values.
@NehaBroad to validate UI logic and look/feel
@panentheos ... there's definitely a cleaner React/LoDash way to do some of this... mind taking a look?
> [RW-2146][Risk=moderate] Srubenst/values

- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
CH, Just checking, where are we enabling elasticsearch? Should it be everywhere except prod?
> [RW-2205][Risk=moderate] Enable Zendesk, eRA commons, and Moodle in prod

- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
removing achilles tables from private cdr.
> [risk=no] removing achilles tables from private cdr.

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db-cdr/generate-cdr/make-bq-data-dump.sh
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/environment.test.ts
- ui/src/environments/environment.ts
adding feature flag for new list search
> [RW-2394][risk=no] adding feature flag for new list search

- ui/src/app/views/app/component.ts
- ui/src/app/views/signed-in/component.css
- ui/src/app/views/signed-in/component.html
- ui/src/app/views/signed-in/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Add a label to the banner to indicate what environment is in use.
> [RW-2111][risk=no] Visually distinguish stable and Prod environments

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
> [RW-2404][risk=no] Treat drug requests as approximate for now

- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
> [risk=no] Fix cohort builder API test

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/integration/resources/data.sql
- api/src/integration/resources/schema.sql
> [risk=no] Integration test fixes

- api/config/config_stable.json
- api/config/config_staging.json
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
Upon merging this PR, also need to run the following commands:
```
gsutil cp gs://all-of-us-{workbench-test,rw-staging}-credentials/moodle-key.txt
gsutil cp gs://all-of-us-{workbench-test,rw-stable}-credentials/moodle-key.txt
```
> [RW-2331][risk=low] Switch staging/stable to use Moodle dev to match SAML SSO configs

- ui/src/app/views/data-page/component.tsx
I had to modify the CSS for the cards in this page to fit the lengthened text.
> [RW-2332][risk=no]: Update Data Tab Language

- api/src/main/resources/workbench.yaml
> [No Ticket][Risk=no] Dataset yaml object

- ui/src/app/guards/dataset-guard.service.ts
> [No Ticket][Risk=no] Fix regression on data set builder access

- api/cluster-resources/README.md
- api/cluster-resources/setup_notebook_cluster.sh
Related issues:
- https://github.com/DataBiosphere/leonardo/issues/813
- https://github.com/DataBiosphere/leonardo/issues/840
> [RW-2218][risk=low] Fix summarytools, improve docs/logging

- api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
> [RW-2381][Risk=low] linking table sql

- api/src/main/java/org/pmiops/workbench/db/model/Cohort.java
- ui/src/app/views/data-page/component.tsx
Requirement that I forgot from the original RW-2332 ticket
> [RW-2332][risk=no]: Reorder sections in Data tab

- api/db-cdr/changelog-schema/db.changelog-27.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/generate-cdr/bq-schemas/criteria.json
- api/db-cdr/generate-cdr/make-bq-data.sh
> [risk=no] add new columns to criteria.

- api/config/cdr_versions_test.json
> [risk=low] moving test cdr.

- ui/src/app/views/workspace-edit/component.tsx
> [RW-2499][Risk=no] Fix namespace for cloned workspaces

- ui/src/app/views/workspace-edit/component.tsx
> [RW-2499][Risk=no] Pass the correct workspace namespace and id

- ui/src/app/views/app/component.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
> [RW-1975] [risk=no] Drop unused databrowser API environment property

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
changing access from writer to reader.
> [RW-2515][risk=no] changing access from writer to reader.

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- ui/src/app/views/dataset-page/component.tsx
> [No Ticket][Risk=no] Fix bug where column names not generated

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaDao.java
- ui/src/app/cohort-search/redux/epics.ts
- ui/src/app/cohort-search/redux/index.ts
add new criteria dao calls in the findCriteriaBy endpoint
> [RW-2536][risk=no] add new criteria dao calls in the findCriteriaBy endpoint

- api/db/changelog/db.changelog-71-remove-2fa-enabled.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/auth/ProfileService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/model/User.java
- api/src/main/resources/workbench.yaml
- api/src/main/webapp/WEB-INF/cron.xml
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/views/workspace-list/component.tsx
> [RW-2460][risk=no] set up 2FA module backend & cron job to sync from google

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/resources/workbench.yaml
- ui/src/app/app-routing.module.ts
- ui/src/app/app.module.ts
- ui/src/app/components/inputs.tsx
- ui/src/app/services/profile-storage.service.ts
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/bug-report/component.spec.tsx
- ui/src/app/views/data-use-agreement/component.tsx
- ui/src/app/views/homepage/component.spec.tsx
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/profile-page/component.spec.tsx
- ui/src/app/views/registration-dashboard/component.spec.tsx
- ui/src/app/views/registration-dashboard/component.tsx
- ui/src/app/views/workspace-list/component.spec.tsx
- ui/src/styles.css
> [risk=no][RW-2455] Aourwmob/data use agreement

- README.md
I was unable to launch the UI locally until I upgraded my version of Node and ran `yarn install`, so I added these steps to the README.
> [risk=no] Add UI setup steps to README

- ui/src/app/views/admin-user-bypass/component.tsx
- ui/src/app/views/data-use-agreement/component.tsx
> [risk=no][no ticket] add dua to bypass modules; add contact email field to form

- api/libproject/generate_appengine_web_xml.rb
> [RW-2553][risk=no] Do not log potentially sensitive GAE XML configs

- api/libproject/devstart.rb
Potentially logs secrets from system vars
> [RW-2553][risk=no] Drop gradle --info logging

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
> [risk=no][RW-2559][P1] enforce data use agreement in setting data access level

- api/db/changelog/db.changelog-72-all-participants-data-set.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DataSet.java
- api/src/main/resources/workbench.yaml
- ui/src/app/components/resources.tsx
- ui/src/app/styles/colors.ts
- ui/src/app/views/dataset-page/component.tsx
> [RW-2096][Risk=low] Srubenst/all aou participants

- ui/src/app/views/workspace-edit/component.tsx
> [RW-2558][risk=no][P1] Allow users to request review on workspaces

- ui/src/app/utils/zendesk.ts
- ui/src/app/views/signed-in/component.ts
- ui/src/index.html
Potential security risk: imports external executable code (no change from current)
> [RW-2441][risk=moderate] Only init Zendesk Widget when user is signed in

- ui/src/app/views/dataset-page/component.tsx
- ui/src/app/views/new-dataset-modal/component.tsx
> [No Ticket][Risk=no] Srubenst/Refactor away new dataset modal

- ui/package.json
- ui/src/app/views/homepage/component.tsx
- ui/src/app/views/profile-page/component.tsx
- ui/src/app/views/profile-registration-step-status/component.tsx
- ui/src/app/views/registration-dashboard/component.tsx
- ui/yarn.lock
> [risk=no][RW-2453] Add registration tasks to user profile page

- api/config/cdr_versions_test.json
move test cdr to synth_r_2019q2_2
> [risk=no] move test cdr

- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
> [risk=no] fixing new dao.

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/workbench.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/app-routing.module.ts
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/breadcrumb/component.tsx
- ui/src/app/views/workspace-edit/component.tsx
- ui/src/app/views/workspace-list/component.tsx
- ui/src/testing/stubs/workspace-service-stub.ts
> [risk=no][RW-2261][RW-2492] change all frontend 'clone' language to 'duplicate'

- api/config/cdr_versions_test.json
- api/db-cdr/changelog-schema/db.changelog-28.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
index changes for new criteria table
> [risk=no] index changes for new criteria table

- api/config/cdr_versions_test.json
- api/db-cdr/changelog-schema/db.changelog-28.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/BillingProjectBufferEntry.java
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.spec.tsx
- ui/src/app/cohort-review/sidebar-content/sidebar-content.component.tsx
- ui/src/app/components/inputs.tsx
Prevents users without write permissions from editing annotations or participant status in the review sidebar
> [RW-2516][risk=no] Fix access levels for annotations in review

- README.md
> [risk=no]Update API access in readme

- ui/src/app/views/workspace-nav-bar/component.tsx
> [risk=no] Fix duplicate workspace route

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
update rank of criteria results
> [risk=no] update rank of criteria results

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
adding standard to auto complete calls.
> [risk=no] adding standard to auto complete calls.

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/webapp/WEB-INF/cron.xml
- api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
Turns out the highest frequency cron schedule is once a minute
> [RW-2561][risk=no] switch cron schedule to every minute and increase syncs per invocation

- ui/src/app/app.module.ts
- ui/src/app/utils/navigation.tsx
- ui/src/app/views/workspace-wrapper/component.ts
I spent a good deal of time attempting to write a regression test for this, unfortunately the test router module does not support RouteReuse configurations, so I wasn't able to produce a realistic/useful unit test.
> [risk=no][RW-2508] Prevent bad view/workspace caching

- ui/CodeStyleGuide.md
- ui/src/app/views/copy-notebook-modal/component.tsx
Action item of 4/26 retrospective with patterns discussed in mob programming session on 4/30
> [No Ticket][risk=no]Start UI Coding Style Guide

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/views/dataset-page/component.tsx
- ui/src/app/views/new-dataset-modal/component.spec.tsx
- ui/src/app/views/new-dataset-modal/component.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
> [RW-2105][Risk=low] Working functionality for export to existing notebook

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/cb_search_api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- common-api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/CodeStyleGuide.md
- ui/src/app/cohort-review/page-layout/page-layout.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.ts
- ui/src/app/cohort-search/redux/epics.ts
- ui/src/app/views/copy-notebook-modal/component.tsx
- ui/src/app/views/dataset-page/component.tsx
- ui/src/app/views/new-dataset-modal/component.spec.tsx
- ui/src/app/views/new-dataset-modal/component.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
adding standard flag to existing criteria endpoint
> [RW-2603][risk=no] adding standard flag to existing criteria endpoint

- ui/src/app/views/homepage/component.tsx
- ui/src/testing/stubs/profile-api-stub.ts
> [risk=no][RW-2573] Request beta access on the dashboard if unrequested

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
> [No Ticket][Risk=no] Add app header to api calls to notebooks

- ui/src/app/cohort-search/list-attributes-page/list-attributes-page.component.spec.ts
- ui/src/app/cohort-search/list-modifier-page/list-modifier-page.component.spec.ts
- ui/src/app/cohort-search/list-search-bar/list-search-bar.component.spec.ts
Fixes ui tests for `list-attributes-page` and `list-search-bar` components. Also cleans up some unused redux code and imports.
> [risk=no] Register api client in cohort builder ui tests

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
> [No Ticket][Risk=no] Suppress unchecked warning to reduce logging noise

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
> [No Ticket][Risk=low] Srubenst/parameterize app header

- ui/src/app/views/dataset-page/component.tsx
> [No Ticket][Risk=no] Remove generate code button

- ui/src/app/guards/registration-guard.service.ts
> [RW-2627][Risk=low] Allow access to data use agreement when not registered

- api/db-cdr/changelog-schema/db.changelog-29.xml
- api/db-cdr/changelog-schema/db.changelog-master.xml
add new indexes in cb_criteria
> [risk=no] add new indexes in cb_criteria
