all-of-us/workbench

api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
api/src/main/java/org/pmiops/workbench/interceptors/ElapsedTimeDistributionInterceptor.java
api/src/main/java/org/pmiops/workbench/interceptors/RequestAttribute.java
api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java
api/src/main/java/org/pmiops/workbench/monitoring/labels/MetricLabel.java
api/src/main/java/org/pmiops/workbench/monitoring/views/DistributionMetric.java

Use a simple interceptor to create a duration and record a distribution metric.
TIL:
- request attributes can hold things that you might need later, and you don't need to worry about threading (e.g. if you were thinking of using an in-class map)
- it's really powerful stuff
---

[RW-4463][RISK=NO] Interceptor-based logging

---

ui/src/app/components/side-nav.spec.tsx
ui/src/app/components/side-nav.tsx

Description:
Changes the sidenav to disable more things when you aren't registered. Adds unit tests to test for that. Also driveby fixes a bug I found where the user can't close the admin dropdown. 
---

[RW-3848][Risk=no] Disable links for unregistered user in sidenav

---

api/src/test/java/org/pmiops/workbench/api/BaseControllerTest.java

For some reason Resources.getResource(filename) works when running test from cmd line but fails to find the resource when running from Intellij. This is a work around that finds the json config using a file path. This works for both cases.

[no ticket][risk=no] Fixing broken test case in Intellij

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java

There are some workspaces on test for which  firecloud User role is empty. In such cases RDR is expecting an empty array rather than null. 
This is important since we send WORKSPACE information to RDR in batches and if one fails all fails.

[noTicket][RISK=NO]Fix RDR exportWorkspace error

---

api/src/main/java/org/pmiops/workbench/actionaudit/ActionAuditEvent.kt
api/src/main/java/org/pmiops/workbench/actionaudit/ActionAuditServiceImpl.kt
api/src/main/java/org/pmiops/workbench/actionaudit/Agent.kt
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/AuthDomainAuditorImpl.java
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ClusterAuditorImpl.java
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorImpl.kt
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditAdapterImpl.java
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditor.java
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorImpl.kt
api/src/main/java/org/pmiops/workbench/api/ClusterController.java
api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/actionaudit/ActionAuditEventTest.java
api/src/test/java/org/pmiops/workbench/actionaudit/ActionAuditServiceTest.kt
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/AuthDomainAuditorTest.java
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorTest.kt
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditorTest.java
api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java

Two-pronged fix:
- Plumb the proper agent details through higher interfaces. After looking more closely, it was clear that the default of "administrator" was incorrect in most cases here.
- Produce null (injectable as Optional) if there is no user. Longer term fix might use a different wrapper object for this. This should make the failure mode clearer and provides a pattern if we need this in the future. Longer term fix is https://precisionmedicineinitiative.atlassian.net/browse/RW-4496
Learnings:
- `Optional` has special magic semantics in Spring, it can be used to express an "optional" injected dependency, as [described here](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/annotation/Autowired.html).
- This means that providing an …

[RW-4464][risk=low] Plumb proper agent details to audit system

---

ui/src/testing/stubs/cluster-api-stub.ts

Description:
Maybe we don't need to see this over and over:
```
console.log src/testing/stubs/cluster-api-stub.ts:25
{ clusterName: 'Cluster Name',
clusterNamespace: 'Namespace',
status: 'Creating',
createdDate: '08/08/2018' }
```
---

[risk=no]Remove listClusters test logspam

---

README.md
api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
api/libproject/devstart.rb

- Add cdr-date to make-bq-denormalized-tables.sh
- Updated readme docs for generating denormalized tables(cb, review and datasets)
- move script validation into ruby commands.

[no ticket][risk=no] update cdr date in docs and make-bq-denormalized-tables.sh

---

ui/src/app/pages/login/account-creation/account-creation-survey.spec.tsx
ui/src/app/pages/login/account-creation/account-creation-survey.tsx
ui/src/app/pages/login/account-creation/account-creation.spec.tsx
ui/src/app/pages/login/account-creation/account-creation.tsx
ui/src/app/pages/login/sign-in.tsx

This PR fixes a couple issues with account creation that Eric uncovered:
1) When switching between steps, the window scroll position remains unchanged. It should scroll to the top of each new step.
The solution here was to add a componentDidUpdate method in sign-in.tsx, which resets the scroll position whenever a new step is reached.
2) Switching back and forth from account-creation to demographic survey appeared to clear out some existing data entry.
We do seem to be correctly persisting the Profile object between account creation steps, but the demographic survey component was missing some logic to auto-populate checkboxes with existing profile data. I added some unit tests to demonstrate the new behavior.
---

[RW-4484][RW-4485][risk=no] Account creation bugfixes

---

api/build.gradle
api/libproject/devstart.rb
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
api/tools/src/main/java/org/pmiops/workbench/tools/FetchFireCloudUserProfile.java

Example Usage
`./project.rb delete-workspaces --dry-run=false --delete-list-filename delete.txt --project all-of-us-rw-staging`
delete_list.txt
```
aou-rw-test-1, fcname
aou-rw-test-2, fcname2
aou-rw-test-3, fcname3
aou-rw-test-4, fcname4
```
Notes
- fetch-firecloud-user-profile was broken so I fixed that while I was in here
- High level approach (for importing a complex class like WorkspaceService) was to build the Bean directly in the tool class and manually providing the necessary dependencies and `null` for the unnecessary ones.
---

[RW-4418][risk=low] Add project.rb tool to delete workspaces

---

api/src/main/java/org/pmiops/workbench/interceptors/InterceptorUtils.java
ui/src/app/app-routing.module.ts
ui/src/app/app.module.ts
ui/src/app/components/side-nav.tsx
ui/src/app/pages/admin/admin-workspace-search.tsx
ui/src/app/pages/admin/admin-workspace.tsx
ui/src/app/pages/signed-in/component.ts
ui/src/app/utils/index.tsx

See the Jira ticket for a bit more context. We want to be able to have URLs of the form
http://researchallofus.org/admin/workspaces/aou-rw-0a95bc0e
that will land on the admin page for that given workspace.
It was a pretty straightforward task to split the view into a search & detail component. Down the line, we can expand the search component to actually search through workspaces & show a summary table before someone digs into any of the detailed pages.
Screenshots:
---

[RW-4488][risk=no] Add workspace-specific routes for WS admin page

---

api/build.gradle
api/libproject/devstart.rb
api/src/main/java/org/pmiops/workbench/google/CloudMonitoringService.java
api/src/main/java/org/pmiops/workbench/google/CloudMonitoringServiceImpl.java
api/src/main/java/org/pmiops/workbench/google/GoogleConfig.java
api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminController.java
api/src/main/resources/workbench.yaml
api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminControllerTest.java
ui/src/app/pages/admin/admin-workspace.tsx
ui/yarn.lock

The main addition in this PR is to pipe cloud storage metrics into our Workspace admin page. I also made a handful of drive-by changes to the styling, and hooked up the button to delete a cluster. This gets us 95% of the way there to be able to respond quickly to an egress event. (The remaining piece is probably to change the routing to create a per-workspace page.)
I manually tested a full cluster deletion cycle:
* Open a second tab with a notebook running, copying a large file to the bucket.
* Refresh the ws-admin page, see the spike in GCS traffic.
* (In the real-world, that signal would indicate that we should *not* shut down the cluster.)
* To test the delete-cluster, I clicked "Delete" on the active cluster.
* My notebook in the other tab stopped working after around ~10 seconds. …

[RW-4462][risk=low] Add GCS traffic and hook up delete-cluster button to WS admin page.

---

ui/src/app/pages/login/account-creation/account-creation-tos.tsx

Description:
This fixes the bug where the button stays enabled after the checkbox is deselected.
---

[RW-4487][Risk=no] Fix checkbox issue in TOS

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/resources/workbench.yaml
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
common-api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
ui/src/app/pages/login/account-creation/account-creation.spec.tsx
ui/src/app/pages/login/account-creation/account-creation.tsx
ui/src/app/pages/login/sign-in.spec.tsx
ui/src/app/pages/login/sign-in.tsx

This flag was pushed to prod with last week's release (see https://github.com/all-of-us/workbench/pull/3130). We should clean this up sooner than later, since the verified institutional affiliation stuff will soon add some extra config-driven complexity to the account creation page.
---

[RW-4446][risk=no] Clean up the enableNewAccountCreation flag

---

api/db/changelog/db.changelog-132-non-null-contact-email.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java

I've already run the necessary SQL updates across the environments so that every user has a contact_email.
---

[RW-4135][risk=no] Add non null constraint for user.contact_email

---

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json
api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/ParticipantCriteria.java
api/src/main/java/org/pmiops/workbench/elasticsearch/AggregationUtils.java
api/src/main/resources/cb_search_api.yaml
ui/src/app/cohort-common/combo-chart/combo-chart.component.tsx
ui/src/app/cohort-search/gender-chart/gender-chart.component.tsx
ui/src/app/cohort-search/overview/overview.component.tsx
ui/src/app/pages/data/cohort-review/query-report.component.tsx

Allow graphs to use sex at birth and different age types
- Added new column sex_at_birth to BQ table cb_search_person
- Updated the sh files to assure that sex_at_birth is populated when building cb_search_person
- Updated CohortBuilderController graphs endpoint to allow sex at birth, age at consent and age at cdr
- Updated relevant test cases
- Updated cb_search_api.yaml swagger definition
- Updated UI calls to default to gender and current age
---

[RW-3861][risk=no] Allow graphs to use sex at birth and different age types

---

ui/src/app/cohort-search/search-group/search-group.component.css

[risk=no] Fix CB search group temporal styles

---

api/docker-compose.yaml

when running 
**`./project.rb docker-clean && ./project.rb dev-up && ./project.rb load-es-index`**  
creation of cdr_person index was throwing a 400 
https://github.com/all-of-us/workbench/blob/1a68804dbaace2b01fecdbde854da2796ec11619/api/tools/src/main/java/org/pmiops/workbench/tools/elastic/ElasticSearchIndexer.java#L178-L178
Noticed that we needed to update the version on the docker elasticsearch image to 6.8.3 to match
https://github.com/all-of-us/workbench/blob/1a68804dbaace2b01fecdbde854da2796ec11619/api/build.gradle#L210-L210
Created a jira ticket to address deprecated methods with move from 6.6.1 to 6.8.3:
[here](https://precisionmedicineinitiative.atlassian.net/browse/RW-4528)

[no ticket][risk=no] updating elastic image version to match dependency

---

api/src/main/resources/workbench.yaml

See my comment in https://precisionmedicineinitiative.atlassian.net/browse/RW-4508 for context – there is a small remaining issue with user registration, where a blank demographic survey will create non-null data in the 'demographics' table.
Allowing a null value on this boolean is more correct, since non-response is meaningfully different than true or false.
---

[RW-4508][risk=no] Allow a null value in the demographic survey 'disability' boolean

---

api/libproject/devstart.rb
api/tools/src/main/java/org/pmiops/workbench/tools/FetchWorkspaceDetails.java

- Hyphenate flag names
- snakecase ruby vars
- drop "=" from flag syntax
- Rename one flag for clarity
Just noticed this when running some of the tools.

[risk=no] Fix some consistency issues in project.rb flags

---

.circleci/config.yml
ci/Dockerfile.circle_build
deploy/docker-compose.yaml

(Updated: I forgot we separate Dockerfiles for local dev and for Circle/deploys)
- Upgrade our CircleCI base image out of the stone age. This was necessary for installing a newer Ruby than 2.3, which is now required by the jira-ruby gem.
- Export a variable for the gradle cache directory in the build image
- Mount/cache a consistent location for the gradle cache (across circle, local dev, deploy) in `/.gradle`
- Built and pushed a new buildimage: update references accordingly

[RW-4546][risk=low] Bump deploy/circle to use new development image

---

api/config/cdr_versions_perf.json
api/config/cdr_versions_prod.json
api/config/cdr_versions_stable.json
api/config/cdr_versions_staging.json
api/config/cdr_versions_test.json

Some participants have been removed from the current CDR, so we recreated the cloud CDR. I've also recreated and moved all the cb_, ds_ tables to `aou-res-curation-output-prod`.  So for the release Monday it will be a good exercise for the on-call engineer @NehaBroad to publish the **full CDR** since the OMOP tables have changed as well. Documented in the [CDR Playbook](https://docs.google.com/document/d/1St6pG_EUFB9oRQUQaOSO7a9UPxPkQ5n4qAVyKF9j9tk/edit#heading=h.wp54m0aomidu). 
@NehaBroad The publish command for Monday: run from the api directory
`db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset R2019Q4R3 | tee R2019Q4R3.log.txt`
@calbach Want to confirm that this all looks correct?
This also includes changing the synth cloud cdr - we added a new table …

[RW-4370][risk=no] updating the current CDR.

---

ui/src/app/pages/workspace/workspace-share.tsx

Description:
Does some moderate cleanup and adds the billing policy reminder. The modal looks like this: 
---

[RW-4400][Risk=no] Add billing reminder to share workspcae

---

ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx

Fixes bug where deleting a search group item does not give an "Undo" option and does not recalculate group or total count.

[risk=no] Fix search item delete/undo

---

api/cluster-resources/README.md
api/cluster-resources/initialize_notebook_cluster.sh
api/config/config_local.json
api/config/config_perf.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/doc/notebook-servers.md

- New image is defined here: https://github.com/DataBiosphere/terra-docker/tree/master/terra-jupyter-aou
- With the next Terra release, this image will be preloaded onto the Leo Dataproc image, which will improve startup time, however it can be used today.
- Most of the initialization script has been moved into the Dockerfile.
Functional changes to the VM:
- Installing the `bigrquery` fork with high priority PRs applied: https://github.com/all-of-us/bigrquery
- No longer installing the legacy pyclient library. I am instead installing the transitive deps of that library (this was the cause of regressions when I last tried removing the client lib)

[RW-4420][risk=low] Switch to new Leonardo AoU image, add docs

---

ui/src/app/icons/edit.tsx
ui/src/app/pages/analysis/interactive-notebook.tsx
ui/src/app/pages/data/concept/concept-set-details.tsx
ui/src/app/pages/workspace/research-purpose.tsx

- **Functional fix**: Only owners can edit workspace metadata, disable the pencil for non-owners
- `ResearchPurpose` does not actually have state, refactor it to be a stateless functional component
- The edit icon should not encode a left margin, push this up to consumers.
--> Aside from bad separation of concerns, concretely this was causing weirdness with the `Clickable` target wrapping the icon, where the left margin was still styled as clickable even when disabled

[RW-4535][risk=no] Workspace about edit icon fixes

---

.circleci/config.yml
api/build.gradle
ci/Dockerfile.circle_build
deploy/docker-compose.yaml

Reverts gradle home changes per https://github.com/all-of-us/workbench/pull/3217 .
I can't currently explain why that didn't work, but it was just a nice-to-have and should be safe to revert. build.gradle needed to be modified in this PR in order to invalidate the previous cache version (based on build.gradle checksum).
In this case we actually had a bad cached artifact. To force a new rebuild of the cache, I used this commit: https://github.com/all-of-us/workbench/pull/3238/commits/f6cb6aa677b8ad65fc70f37ce4ca7454dd0299fa

[risk=no] Fix circleci: revert gradle home, bump gradle revision

---

ui/src/app/pages/workspace/workspace-card.tsx
ui/src/app/utils/analytics.ts

Add new events to use only with featured workspaces. 
Events based on Library tab of the [analytics doc](https://docs.google.com/spreadsheets/d/1V_Zp0ZtN8f237LNcaGQA-WZzYJu9g8ECq80gJCV8njA/edit#gid=51478853) with the change of using 'Featured Workspaces' for all events instead of specifying 'Phenotype' or 'Tutorial.'
---

[RW-4558][risk=no] Add Google Analytics events for featured workspaces

---

api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java

I used hibernate's BasicFormatterImpl that formats the SQL hence now we have query from dataset as follows in notebook 
For R: 
For python
---

[RW-4412][RISK=NO]Format Dataset builder SQL query for readability

---

ui/src/app/pages/login/account-creation/account-creation-institution.tsx
ui/src/app/pages/login/account-creation/common.tsx

There was a visual regression with https://github.com/all-of-us/workbench/pull/3251, where the input fields for the second registration step were off. This PR fixes that.
Screenshot demonstrating the issue: 
---

[RW-4525][risk=no] Fix input width issues in user registration form

---

ui/yarn.lock

Description:
Resolves this alert triggered by dependabot: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/minimist/open
---

[risk=low]Update vulnerable minimist UI package

---

ui/src/app/pages/login/account-creation/account-creation-survey.spec.tsx
ui/src/app/pages/login/account-creation/account-creation-survey.tsx
ui/src/app/utils/errors.tsx
ui/src/testing/stubs/profile-api-stub.ts

Currently, all we do on a server-side error during user registration is console.error the response.
This PR adds a modal dialog, similar in spirit to what we have for failed workspace creation.
Screenshot:
---

[RW-4569][risk=no] Add user-facing error message when user creation fails

---

ui/src/app/app-routing.module.ts
ui/src/app/app.module.ts
ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx
ui/src/app/pages/profile/data-use-agreement.spec.tsx
ui/src/app/pages/profile/data-user-code-of-conduct.tsx
ui/src/app/pages/profile/profile-page.tsx

Following changes were done 
- Data user Agreement is changed “Data User Code of Conduct” ( Just the title and url assumption the file name etc changes will be done by 4561 if not i can change it here)
- the order for registration is now Two factor -> ERA Commons -> Compliance Training ->  Data Code of Conduct
- All external links (NIH, Ethics etc) from registration will open in a new tab 
- Some text and description changes
---

[RW-4563][RISK=NO] Minor changes to registration steps screen

---

ui/yarn.lock

Description:
#3253 upgraded acorn 5 to a version not vulnerable to [this alert](https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/acorn/open).  This PR does the same for acorn 6.
---

[risk=low]Bump vulnerable acorn 6 to 6.4.1

---

ui/src/app/guards/registration-guard.service.ts
ui/src/app/pages/homepage/registration-dashboard.tsx

This PR will fix the broken button @ user registration -> STEP 4 Data User Code of Conduct
the Bug: 
Click the button 'View and Sign' on Data User Code Of Conduct does nothing
Fix: 1) the new route was not change in guard service neither was the navigate url updated to use the new url data-code-of-conduct rather than new one.
---

[noTicket][RISK=NO] Fix broken data code of conduct flow

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Selecting No for underrepresented population did not uncheck previously selected Specific population, causing error when selecting Update.
This was because the Checkbox props manageOwnState was not set to false because of which even after setting populationDetails to empty the checkbox state did not change.
---

[RW-4570][RISK=NO]Workspace creation bug when selecting population of interest

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/QueryParameterUtil.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/test/SearchRequests.java
ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
ui/src/app/cohort-search/cohort-search/cohort-search.component.ts
ui/src/app/cohort-search/demographics/demographics.component.ts
ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
ui/src/app/cohort-search/search-group/search-group.component.tsx
ui/src/app/cohort-search/search-state.service.ts
ui/src/app/cohort-search/utils.ts

**Allow user selected global filters to search specific data**
1. EHR
2. PM
**Refactored BQ queries in CohortQueryBuilder(updated BQ test cases as well)**
- For Participant Counts
- For Chart Info
- For Review Chart Info
- For Random Participants with review
- For Participant Id count for Data Set Builder
**Refactored adding query parameter values into QueryParameterUtil**
Used by
1. CohortQueryBuilder
2. SearchGroupItemQueryBuilder
---

[RW-4585][risk=no] implementing data filters for search

---

ui/src/app/cohort-search/cohort-search/cohort-search.component.ts

Fixes issue where the warning modal in cohort builder pops up when you haven't added any criteria yet

[risk=no] Fix unsaved cohort changes warning

---

api/src/main/java/org/pmiops/workbench/api/InstitutionController.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
ui/src/app/components/inputs.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/testing/stubs/institution-api-stub.ts

This adds the last missing piece to the institution form, to check the validity of the user's email address before allowing them to progress.
From local testing, demonstrating the error icon and tooltip within the input element:
... and a validation error at the form level, which blocks form progression:
I also found an error in one of our existing unit tests for the form (yikes!) which was causing the test to not actually verify anything. That's fixed, and the unit tests are now exercising this entire form in what I believe is a pretty reasonable manner.
---

[RW-4524][risk=no] Add in-form institution check to user creation page.

---

api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
api/src/test/java/org/pmiops/workbench/testconfig/UserServiceTestConfiguration.java

Description:
I ran into this again and I'm now annoyed enough to solve the problem: https://github.com/all-of-us/workbench/commit/4da7c082ebc5fb94f89f914557f2703c5c8bad88
After this change, tests of controllers/services/etc which depend on UserService will not need to be individually updated after UserService's dependencies change.
---

[risk=no]UserServiceTestConfiguration: transitive imports for UserServiceImpl

---

api/build.gradle
api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
api/src/test/java/org/pmiops/workbench/api/SumoLogicControllerTest.java
api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java

There are some more advanced framework libraries we could choose to depend on with Junit 5. I haven't imported those yet. The library I've imported is mostly backwards compatible with Junit 4.
~~I'm upgrading because I want to use `@Tag` for test filtering, which is only available in Junit 5.~~ I couldn't get tags working. Still going to continue with this PR anyways since I already did the work and I don't see a downside.

[risk=no] Upgrade from junit 4 -> junit 5

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_staging.json
api/config/config_test.json
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

Enable requireInstitutionalVerification in Staging and Perf
Disable requireInvitationKey in Test, Local, Perf, and Staging
Conservatively labeling "medium" risk because we're removing one barrier to access.  Mitigated by requiring another, which should be better security-wise.
Enable/disable Feature Flags: https://precisionmedicineinitiative.atlassian.net/browse/RW-4465
TODO: Stable, Prod
Remove Feature Flags: https://precisionmedicineinitiative.atlassian.net/browse/RW-4361
Description:
---

[risk=medium][RW-4465][RW-4637]Enable requireInstitutionalVerification in Staging and Perf

---

ui/src/app/components/help-sidebar.tsx

Replace blue bar at top of sidebar with an 'X' icon in the upper right corner to close the sidebar
---

[RW-4620][risk=no] Update help sidebar UI

---

.circleci/config.yml
api/build.gradle
api/libproject/devstart.rb
api/src/integration/java/org/pmiops/workbench/NightlyTests.java
api/src/integration/java/org/pmiops/workbench/ZendeskIntegrationTest.java

This only runs nightly on account of the test generating ZD sandbox requests which aren't cleaned up. Leverages Junit "Categories" for filtering on tests. I couldn't get `@Tag` filtering to work with gradle; on further review this may only be possible if you're using the new JUnit5 platform engine, so upgrading to the JUnit5 lib may not have been sufficient:
```
> Could not find method useJUnitPlatform() for arguments [build_7rmii44aljl4a99qxkq0ucme2$_run_closure20$_closure70@31450fc0] on task ':integrationTest' of type org.gradle.api.tasks.testing.Test.
```

[RW-4621][risk=no] Add Zendesk integration test which runs nightly

---

api/build.gradle
api/config/config_local.json
api/config/config_perf.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/SumoLogicController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/opsgenie/OpsGenieConfig.java
api/src/main/java/org/pmiops/workbench/opsgenie/OpsGenieService.java
api/src/main/java/org/pmiops/workbench/opsgenie/OpsGenieServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/SumoLogicControllerTest.java
api/src/test/java/org/pmiops/workbench/opsgenie/OpsGenieServiceTest.java

To tighten up our egress alerting story, it makes more sense to directly fire OpsGenie alerts from the Workbench rather than going through the more circuitous path of Stackdriver logs-based metrics (see attached ticket for a more detailed description).
This PR adds a simple Opsgenie API client and hooks it into the SumoLogicController to create an Opsgenie alert for each high-egress event detected.
**Testing**
I tested this locally by manually firing an API request to the local backend:
```
curl -H "X-API-KEY: [redacted]" -H "Content-Type: application/json" -d @test.json http://localhost:8081/v1/admin/sumo/egressEvent
```
where API-KEY is our GCS-stored inbound-sumologic API key, and test.json is a temporary file replicating the JSON structure sent from SumoLogic to Workbench (see [this …

[RW-4445][risk=low] Add OpsGenieService to create alerts on inbound high-egress events.

---

api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticDocument.java
api/src/main/java/org/pmiops/workbench/elasticsearch/ElasticFilters.java
api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
api/tools/src/main/resources/bigquery/es_person.sql

CB will allow users to filter cohort results based on if they have EHR or Physical Measurement data. Pretty simple... adding boolean flags to the person index for each.

[RW-4618][risk=no] Adding EHR/PM data filters to Elastic

---

api/libproject/devstart.rb

Fixed some late-breaking regressions on the last PR which I apparently neglected to run afterwards. Verified locally that `./project.rb nightly-integration` now passes.

[RW-4621][risk=no] Fix nightly command

---

e2e/tests/home/home-page.spec.ts

Combine steps from `Workspace cards have same ui size` and `Check Workspace card on Home page` into one test.
Reworked code logic.
```
FAIL  tests/home/home-page.spec.ts (188.854s)
Home page ui tests
✕ Workspace cards have same ui size (117910ms)
✓ Click on See All Workspace link (23277ms)
✓ Click on Create New Workspace link (19764ms)
✓ Check Create New Workspace link on Home page (13836ms)
✓ Check Workspace card on Home page (13752ms)
● Home page ui tests › Workspace cards have same ui size
expect(received).toBeGreaterThan(expected)
Matcher error: received value must be a number or bigint
Received has value: undefined
47 |       }
48 |     }
> 49 |     expect(height).toBeGreaterThan(1);
|                    ^
50 |     expect(width).toBeGreaterThan(1);
51 |   });
52 | 
at …
```

[no ticket][risk=no] Refactoring Home page tests

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Fixing a bug found by puppeteer automation!
This should have been caught by our unit tests too but there was a bug in the test where the create test wasn't using the write test data.
---

[risk=no] fix blank page bug on workspace create page

---

ui/src/app/components/footer.tsx
ui/src/app/pages/signed-in/component.css
ui/src/app/pages/signed-in/component.html

Description:
This fixes two things per UX feedback. One, it removes the adjusting width on the footer items. This requires adding a minimum width to signed in pages to avoid weird overflow and scroll.
Two, it hides the footer on notebooks pages.
---

[No Ticket][Risk=no] Change footer based on product and UX feedback

---

e2e/app/authenticated-page.ts
e2e/app/base-page.ts
e2e/app/workspace-card.ts
e2e/tests/home/home-page.spec.ts
e2e/tests/workspace/workspace-ui.spec.ts

This failure happens on CircleCI runs but not running on localhost.
Root cause: Not waiting for Workspace Cards become visible.
```
FAIL  tests/home/home-page.spec.ts (188.854s)
Home page ui tests
✕ Workspace cards have same ui size (117910ms)
✓ Click on See All Workspace link (23277ms)
✓ Click on Create New Workspace link (19764ms)
✓ Check Create New Workspace link on Home page (13836ms)
✓ Check Workspace card on Home page (13752ms)
● Home page ui tests › Workspace cards have same ui size
expect(received).toBeGreaterThan(expected)
Matcher error: received value must be a number or bigint
Received has value: undefined
47 |       }
48 |     }
> 49 |     expect(height).toBeGreaterThan(1);
|                    ^
50 |     expect(width).toBeGreaterThan(1);
51 |   });
52 | 
at …
```

[RW-4671][risk=no] Puppeteer: Fix Home Page flaky test

---

api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspacesController.java
api/src/main/resources/fireCloud.yaml
api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java

System changes:
- Drop our custom handling of file cloning on CloneWorkspace, leverage the Firecloud cloneWorkspace file copy feature instead.
Functional changes:
- We no longer copy all files in the bucket, just in the notebooks/ subdir. This is a revert to the original behavior which was intended to mitigate accidental copies of large files. It's required for this change since Rawls clone workspace doesn't support copying all files
- Drop the size limitation on cloned file size
- Files are no longer synchronously available immediately after the clone, Rawls does this in a background thread.
Based on manual local testing:
- The propagation delay was not noticeable - tested with 50 notebook files.
- Confirmed that files outside this prefix do not get copied
- Confirmed that files in …

[RW-4583][risk=low] Switch to Rawls cloneWorkspace

---

api/src/main/resources/fireCloud.yaml

Missed this follow-up commit in my previous PR which I was using for local manual testing. Without this, the call to Firecloud clone will fail. May be worth adding a nightly integration test for this, since it will generate spam workspaces.
Without this, fails with:
```
api_1_84f0e5a17331       |   "message": "Object is missing required member 'attributes'",                                                                             
```

[RW-4583][risk=no] Fix invocation of Rawls clone API

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json

Before the release next week, we need to run the following SQL to override free tier quota for existing alpha users @jmthibault79 : https://precisionmedicineinitiative.atlassian.net/browse/RW-3662
We could also decide to run this once more at launch.

[RW-4318][RW-4262][risk=low] Enable billing lockout and alerting

---

ui/src/app/guards/disabled-guard.service.ts

This causes the initial /getMe request to fail with a 500. There is no clear user facing issue as a result of this, but it is a confounding factor in the very least to debugging other issues.
Manually tested with a disabled and a non-disabled user.

[RW-4691][risk=no] Await authentication before checking disabled status

---

api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json

Description:
The Free Tier account is missing in the dropdown on Staging, so it is not possible to create workspaces.  This has not been investigated yet.
---

Set enableBillingLockout to false in Staging, Stable, and Prod

---

ui/src/app/cohort-search/gender-chart/gender-chart.component.tsx
ui/src/app/cohort-search/overview/overview.component.tsx
ui/src/app/cohort-search/utils.ts

Add two dropdown menus, one for Gender/Sex and one for Age, for configuring the CB total count graphs.
---

[RW-3824][risk=no] Add Gender, Sex and Age options for CB graphs

---

api/src/main/java/org/pmiops/workbench/interceptors/CloudTaskInterceptor.java
api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java

Cloud queue( responsible for handling task to export workspace/researcher data to Rdr ) name was recently updated from rdrQueueTest to rdrExportQueue. For all the incoming request dispatched from queue, cloud task interceptor confirms that request is coming from valid queue.
This PR is to update the name of queue in CloudTaskInterceptor

[noTicket][risk=moderate]Cloud interceptor should have correct Rdr Export queue name

---

ui/yarn.lock

Description:
I believe this is only a partial resolution of a security alert (https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/kind-of/open) but it is a step on the way there.
---

[risk=low]upgrade vulnerable kind-of 6.0.2

---

api/src/main/webapp/WEB-INF/queue.yaml

Queue.yaml was missing target parameter for rdrExportQueue, because of which the request generated from queue was not hitting API.
https://cloud.google.com/appengine/docs/standard/python/config/queueref

[noTicket][risk=low]Add parameter 'target' to queue.yaml

---

api/src/main/java/org/pmiops/workbench/auth/ServiceAccounts.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java

Switching to use service account creds rather than user impersonation. This is needed as there are a set of users in prod who are no longer in the registered tier, and therefore no longer have permission to delete workspaces.
Verified in the test environment by deleting one of my own workspaces.

[RW-4573][risk=low] Delete workspace fixes

---

ui/package.json
ui/yarn.lock

Description:
Resolves https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/minimist/open by:
* Removing protractor, which depends on optimist, which depends on a vulnerable version of minimist
* Upgrading karma to no longer depend on optimist, which depends on a vulnerable version of minimist
---

[risk=low]Resolve UI security alert

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Add checks for the following attributes:
- **Name of disease (80)** : Error Message if Disease-focused research is selected and name of disease is empty or less than 80
- **Other primary Purpose(500):** Error messge if other primary purpose is selected but the text is empty or less than 500
- **Other disseminate research findings(100)**: If Other is selected for Question 3 and text is empty or less than 100
- **Other Special Population(100)**: If special population Yes is selected and Special population Other is selected with empty or less than 100 characters 
---

[RW-3989][risk=low] Validate length on all workspace free text fields before creation

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

Part 2 of distinguish between two institution agreement types:
Verify institution details/validate affiliation for createAccount before directoryService.createUser to avoid creating a user which is going to throw bad request exception later resulting in an entry only in directory service and not in workbench.

[RW-4500][RISK=MODERATE] Institution affiliation: distinguish between two institution agreement types

---

.circleci/config.yml
e2e/package.json

Update junit XML format to fix `No timing found` error.
Before
After

[no ticket][risk=no] jest-junit flag to support circleci split by timings

---

ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx

Description:
This fixes the eRA commons redirect to follow up by setting the task to completed. In doing this, I realized there was a loading step, so I added a loading spinner to the button. I talked to Lou about the styling on that, and we decided to move all the icons to the right of the button, because if the spinner was on the left, it would push the text when it appeared. The button is disabled but still primary while loading per Lou's request. This has been confirmed with Karthik
Here is a screenshot while loading:
---

[RW-4723][Risk=no] Fix eRA commons linking

---

ui/src/app/pages/workspace/workspace-edit.tsx

Description:
Pop up an OverlayPanel to display free credits, if the user has any remaining.
Mocks: https://projects.invisionapp.com/d/#/console/12820961/373893999/preview
TODO: Remove the pointer?  Have not figured out how to do so yet
---

[risk=no][RW-3211] Show free credits balance on Workspace Create

---

e2e/app/create-account-page.ts

The wording changed on the TOS and I forgot to look in E2E for the corresponding strings. if only we had a top level shared static content library or somethin

update content strings

---

ui/src/app/pages/login/account-creation/account-creation-institution.tsx

Update the following links on account creation institution page:
- link: “Don’t see your institution”
- The link in the Error Message “**if the institution has restricted DUA and contact email is not part of valid email address”**

[RW-4745][RISK=LOW]  Replace "don't see your institution listed" link

---

ui/src/app/pages/login/account-creation/account-creation.tsx
ui/src/app/pages/login/account-creation/common.tsx

As part of this story: 
- Add username information above the new username lable
- Update new username tooltip 
- Remove About your username section  and the extra "The All Of Us text" from the side help text
---

[RW-4747][RISK=NO]  Add text for username section

---

ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.tsx
ui/src/app/pages/login/account-creation/account-creation-survey.tsx
ui/src/app/pages/login/account-creation/account-creation.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/app/pages/profile/data-user-code-of-conduct.tsx
ui/src/app/utils/analytics.ts

Add Google Analytics for events on registration pages.
Events based off the Registration tab of the [workbench analytics doc](https://docs.google.com/spreadsheets/d/1V_Zp0ZtN8f237LNcaGQA-WZzYJu9g8ECq80gJCV8njA/edit#gid=293698803)
---

[RW-4749][risk=no] Add Google Analytics for Registration pages

---

ui/src/app/components/footer.tsx
ui/src/app/pages/profile/data-user-code-of-conduct-styles.tsx
ui/src/app/pages/signed-in/component.css
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/pages/workspace/workspace-research-summary.tsx
ui/src/environments/environment.local.ts
ui/src/environments/test-env-base.ts

Description:
This is to address the desire to audit the site for horizontal scroll bars. This disables the footer on all environments (for now), and drops the width of some workspace edit components to fit within 1280px of screen width. This makes the lowest supported web-browser width of the site 1300px. Lou has confirmed that all screens he has designed are 1280px wide. (And then we add 20px for the scroll bar)
---

[No Ticket][Risk=no] Make minimum width 1300px for site

---

api/docker-compose.yaml
ui/docker-compose.yaml

Added purely for aesthetic purposes. This will allow us to better identify the image e.g. via `docker images`. The image is always built locally and we currently do not have intention or need to be pushing it up to DockerHub.
This uses the `allofustest/` prefix since we already own that on DockerHub, and we wouldn't want to pick a label that could be snatched up by an attacker.

[risk=no] Add labels to our local dev images

---

ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.tsx

**Bug**: Institution error message was being displayed as soon as user starts typing  in email. Therefore even valid email ids were being shown some error message unless they looses email textbox focus and email verification is done, correcting the email message and the icon
**Solution**: add a check to show the validation icon or error message once email verification has been done i.e verification API has returned with some kind of response before 
---

[noTicket][RISK=MEDIUM] Should display error message only after email verification

---

api/config/config_perf.json
api/config/config_stable.json
api/config/config_staging.json

See comments on RW-4757 for more context.
This is a simple flag-flipping PR which will allow me to start testing v2 Moodle API in lower environments.
I will plan to manually push this config change to perf/staging/stable once the PR is merged; all actions will be logged in comments on the associated Jira issue.

[RW-4757][risk=no] Enable v2 Moodle API on perf/staging/stable

---

e2e/tests/workspace/workspace-create.spec.ts

Reason: Selecting YES for the "request a workspace review" option would generates some Zendesk tickets which can't be deleted. Testing of this feature was already covered by other automated tests.

[no ticket][risk=no] Puppeteer Remove a Workspace automated test

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/ClusterController.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminController.java
api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminControllerTest.java
api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
api/src/test/java/org/pmiops/workbench/workspaces/WorkspacesControllerTest.java

- Switch the admin endpoint to exclusively use service credentials
- Rename various methods to have the suffix `asService` to make this distinction clearer. Admin is slightly ambiguous since we also have user admins.
- Add contrived regression test. With more comprehensive fake services, it might be possible to have a better behavioral test here. With the current unit tests, the interactions between service layers are effectively change-detector tests.
Manually tested:
- Verified an admin can view the admin page for a workspace they don't have access to.
- Verified the admin can delete a cluster from this page.
- Observed notebook counts / sizes updating as expected.

[RW-4713][risk=moderate] Fix admin page auth and rename service methods

---

.circleci/config.yml

New CircleCI UI makes heavy use of the optional `name` attribute on job steps. I've added more, and tweaked a few existing ones for clarity. I condensed a couple of common steps into YAML anchors. There is support for more first-class reuse with parameterization in v2.1. This [ticket ](https://precisionmedicineinitiative.atlassian.net/browse/RW-4645) covers taking advantage of the new features and migrating to 2.1.
Check CircleCI run for new titles.
---

[no ticket][risk=no] CircleCI Names and anchors for common steps

---

api/src/main/java/org/pmiops/workbench/utils/WorkspaceMapper.java

The way research purposes and workspaces work together makes things awkward in several places. All I'm doing here is stifling a few warnings.
I'm deprecating the `mergeResearchPurposeIntoWorkspace()` mapper method as I'm about to get rid of it altogether.
Also, I looked into treating warnings as errors, and it choked on our generated files. For those interested, see the [output](https://gist.github.com/jaycarlton/d3d2bc9f134969576f1e8c362c25fe1d).
To enable this in the build.gradle file I did 
```
gradle.projectsEvaluated {
tasks.withType(JavaCompile) {
options.compilerArgs << "-Xlint:all" << "-Werror"
}
}
```
@calbach I didn't see an obvious way to split out our generated code.  It's in its own directory, but we share packages (and a compile target) with it.
---

[RW-4633][risk=no] Ignore more missing props & try treating warnings as errors

---

ui/src/app/components/help-sidebar.tsx

- Add data dictionary icon back to sidebar
- Link to [Zendesk support page](https://aousupporthelp.zendesk.com/hc/en-us/articles/360033200232-Data-dictionary-for-Registered-Tier-Curated-Data-Repository-CDR-) (only active in prod)

[risk=no] Add data dictionary icon to sidebar

---

api/config/config_prod.json

See the context ticket for context around the change and copious notes on testing in lower environments.
This should have little risk of impacting production users, since the access module which relies on the Moodle API (enableComplianceTraining) is still set to false in production.
---

[RW-4757][risk=no] Enable V2 Moodle API in production

---

api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
api/src/main/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterService.java
api/src/main/resources/fireCloud.yaml

Incorporate new RAWLS option into our version of the FireCloud Swagger, and set the new option to true.
I did see a couple of attempts fail before this one succeeded, so I'm not sure what happened. After restarting everything, it worked.
---

[RW-4737][risk=no] Enable Google Private IP Adddress flag on new project creation

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-research-summary.tsx

**Problem** : On create workspace page, if the text for question 2.1,2.2 or 2.3 has length 1000 characters then there were two warning messages (_0 characters remaining_ and _You have reached the character limit for this question_) that were  being displayed with no margin in between them 
**Solution**: If the text has reached the maximum length we do not need to show "0 characters remaining  just show" just one warning message is fine : **Approved by Lou**

[noTicket][RISK=NO] Fix Create workspace :two different message labels are adjacent but with no visible spacing between them.

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Description:
This changes the default selection of review requested and specific populations from `no` to nothing. It also adds error messaging when those aren't selected. From there, I cleaned up a bunch of stuff on the page. (screenshots where applicable)
---

[RW-4722][Risk=no] Remove default selections from workspace-edit page

---

ui/src/app/cohort-search/demographics/demographics.component.css
ui/src/app/cohort-search/demographics/demographics.component.html
ui/src/app/cohort-search/demographics/demographics.component.ts
ui/src/app/cohort-search/modal/modal.component.ts
ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
ui/src/app/cohort-search/utils.ts

- Separate Age and Deceased items in criteria menu dropdown
- Remove deceased checkbox from age wizard
---

[RW-4436][risk=no] Make deceased its own menu item

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Shows the user a confirmation modal before saving when creating, editing or duplicating a workspace.
---

[RW-4720][risk=no] Show confirmation modal when saving a workspace

---

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java

Description:
The motivation for this change was seeing a large number of logs like this:
```User [redacted] has 4.041393 in total free tier spending in BigQuery, which is less than the 4.041393 previous spending we have recorded in the DB (FreeTierBillingService.java:182)```
---

[risk=no][RW-4678]Followup: don't spam logs and make proper float comparisons

---

ui/src/app/pages/login/account-creation/account-creation-institution.tsx

Description:
So, this one is interesting. It looks like the PrimeReact dropdown text has a bug where it will expand out to fill the space. I am attaching a screenshot of what that does to the actual bounding boxes. 
Problem:
Solution:
We tried fixing it with `text-overflow` and with `overflow` but neither worked. The best thing we could find was pinning the width, which we do a lot on these pages anyway, so that should be okay.
Note: This solution doesn't fix the underlying issues, but does cap out the width such that the aside moves back in, so that the page doesn't get wider.
---

[RW-4817][Risk=no] Hardcode width on dropdown

---

ui/src/app/pages/workspace/workspace-edit-section.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Updated the billing section description the link 
For width reference. 

[RW-4724][RISK=NO] Link support articles to billing section of create workspace

---

ui/src/app/pages/homepage/registration-dashboard.tsx

Changes the heights of the completed cards from 160px to 190px. (min and max heights)
Before:
After:
---

[RW-4823][risk=no] Update height for completed registration cards

---

e2e/app/component/dialog.ts
e2e/app/page/base-page.ts
e2e/app/page/data-page.ts
e2e/app/page/home-page.ts
e2e/app/page/profile-page.ts
e2e/app/page/user-admin-page.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/jest.test-setup.ts
e2e/tests/workspace/workspace-clone.spec.ts
e2e/tests/workspace/workspace-create.spec.ts

This PR will address two ongoing test failures:
(1) a blank page with spinner which has seen to fail tests occasionally. I don't know why it's happening now but not before. To fix this, part 1 is refactor Page's `isLoaded` method to include `waitUntilNoSpinner` in a `Promise.all`. Part 2 is use Puppeteer global `waitFor` timeout, so I don't have to add `{timeout: 60000}` for all `waitFor`.
```
await page.setDefaultNavigationTimeout(90000);
await page.setDefaultTimeout(60000);
```
(2) UI change when creating or duplicating workspace. There is a new Confirmation Dialog now.

[no ticket][risk=no] Puppeteer framework new component Dialog

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/main/resources/rdr.yaml

**Problem** : While exporting workspace data to RDR, workbench was not sending the parameter focusOnUnderrepresentedPopulations (which represents if researcher has selected the question _Will your study focus on any historically underrepresented populations_ while creating workspace). Because of which RDR was assuming this value to be false and ignoring the workspace Demographic information being sent.
**Solution**: Populate and send the value focusOnUnderrepresentedPopulations while exporting Workspace data to RDR:
IF workspace has any Demographic information (race/age etc) send YES else NO
Confirmed with Wang Yu its working fine and RDR is able to store this value

[RW-4830][RISK=NO] Export parameter focusOnUnderrepresentedPopulations to RDR

---

ui/src/app/pages/cookie-policy.tsx

Reduced space between headers and text by .5rem.
---

[RW-4812][risk=no] Reduce spacing on cookie policy page

---

ui/yarn.lock

Description:
Update kind-of to a nonvulnerable version
Update handlebars to a version which does not select a vulnerable minimist version in its dependencies (handlebars -> optimist -> minimist)
Essentially a reapplication of #3350 and #3352
---

[risk=low]Update vulnerable kind-of and minimist packages

---

api/config/config_prod.json
api/config/config_stable.json

This config change will turn on enforcement of compliance training in our stable and prod environments. Due to time constraints for this release, I am opting not to flip the flag on stable, since we don't know how that will impact Rainforest QA tests and we don't want to delay release if we have to add or alter tests in order to make Rainforest tests pass.
---

[RW-4808][risk=no] Enable compliance training in stable & prod

---

api/libproject/devstart.rb
api/tools/src/main/java/org/pmiops/workbench/tools/ManageClusters.java

- Disallow running this tool without any criteria
- Clarify documentation / dry run mode
Still TODO, possibly not in this PR:
- This tool should be switched to the standard flag library (we have a ticket for this)
- The pattern of defaulting into a dry run is not consistent with other commands, but this command is dangerous enough that I don't want to change that behavior without adding a confirmation step.

[RW-4793][risk=no] Clean up flags to delete-cluster

---

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

Description:
When we check the user's access level (on every 2FA sync cron run, as well as triggered by certain events) enforce that the user has signed the current version of the Data User Code of Conduct (DUCC)
Not renaming any "DUA" code to DUCC here.  Filed https://precisionmedicineinitiative.atlassian.net/browse/RW-4838
---

[risk=low]Enforce DUCC version for registered tier

---

api/build.gradle

Description:
From Snyk:
```
Vulnerable module: org.springframework:spring-web
Introduced through: org.springframework.security:spring-security-web@4.2.13.RELEASE
Exploit maturity: No known exploit
Fixed in: 5.2.3, 5.1.13, 5.0.16
Detailed paths
Introduced through: project@0.0.0 › org.springframework.security:spring-security-web@4.2.13.RELEASE › org.springframework:spring-web@5.2.2.RELEASE
```
```
Vulnerable module: org.mortbay.jetty:jetty
Introduced through: com.google.oauth-client:google-oauth-client-jetty@1.30.3
Exploit maturity: No known exploit
Detailed paths
Introduced through: project@0.0.0 › com.google.oauth-client:google-oauth-client-jetty@1.30.3 › org.mortbay.jetty:jetty@6.1.26
```
---

[risk=low]Update a few more vulnerable packages

---

.circleci/config.yml
e2e/jest.config.js
e2e/package.json
e2e/resources/workbench-config.ts

Upgrade CircleCI yaml to version 2.1, leveraging new v2.1 features like `commands`, `parameters`, `when`. Re-organized common actions into `commands` for reuse by `jobs`.
High-level structures:
Notes:
-  Kept all ` jobs` names unchanged to avoid adding new confusion. and number of `jobs` are not changed.
-  Use pipeline `parameters` for set/access common configs. 
-  `command` `git_checkout` combines `- checkout` and `- git submodules update`.
-  new cache `command` s. `ui_dependencies`, `e2e_dependencies` and `api_cache` with parameters.
- New anchor `filter_pr`, for running workflow jobs on non-master and non-release (tags) branches. In other words, run workflow's jobs for PR branches after pushed to origin.
I am not able test out changes in `deploy-staging`, `deploy-perf`, …

[RW-4645][risk=no] CircleCI config upgrade to version 2.1

---

ui/src/app/app-routing.module.ts
ui/src/app/guards/disabled-guard.service.ts
ui/src/app/services/profile-storage.service.ts

1. Remove the canActivate check, this was causing the rule to execute twice.
2. Change profile storage service to send errors. Previously, it would just let callers hang indefinitely on failure.
3. Switch disabled-guard to use profile storage service. This uses the cached value of the profile rather than requesting it on every page render.
This avoids sending 2 profile requests on every navigate
Minor downside: If a user happened to be disabled during active use, they would no longer immediately see their disabled status within that client session (rather, they'd see opaque errors). This doesn't seem like a case that's worth optimizing for.
Tested manually with a disabled user and a non-disabled user.

[RW-4843][risk=no] Only check user disabled on initial load

---

ui/src/dev/server/Dockerfile

Without this, eslint package fails to install, since current Dockerfile uses Node 11.2. This breaks the dev-up workflow for those that use the docker-based wrapper instead of direct `yarn`.
```
./project.rb dev-up                                                                                                                                                                  
+ docker-compose run --rm ui yarn install                                                                                                                                                                            
WARNING: The ENV_FLAG variable is not set. Defaulting to a blank string. …
```

[risk=no] Bump UI local docker to node 12

---

api/db-cdr/generate-cdr/generate-cb-criteria-tables.sh
api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search.sh
api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
api/libproject/devstart.rb

This PR adds the following flags to the denormalized CDR table builds
1. --data-browswer indicates of were building denormalized search and criteria tables for DB. **NOTE: --data-browswer flag is false by default**
2. --dry-run when false the denormalized CDR table build scripts will echo out all provided args for validity(this helps validate that all args are being passed to child script correctly). **NOTE: --dry-run flag is false by default**
**Example CohortBuilder run:** 
`./project.rb make-bq-denormalized-tables --bq-project all-of-us-ehr-dev --bq-dataset synpuf_100 --cdr-date 2020-10-04`
**Example CohortBuilder dry run:** 
`./project.rb make-bq-denormalized-tables --bq-project all-of-us-ehr-dev --bq-dataset synpuf_100 --cdr-date 2020-10-04 --dry-run true`
**Output**
**Example …

[RW-4774][risk=no]Update denormalized scripts to allow args for databrowser

---

api/config/config_stable.json

Account creation is still restricted by invite key and institutional affiliation.

[RW-4854][risk=low] Drop beta access requirement in stable

---

api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

Along with workspace details, workbench send RDR attribute excludeFromPublicDirectory , that excludes the workspace to be show up in Researcher directory. 
By default we send the value false i.e show all workspace in researcher directory
As part of this PR: Workbench will send  excludeFromPublicDirectory flag as true if the creator of the workspace has institution All of Us Program operational Use
I have tested the exportToWorkspace call with:
-  Workspace with creator with no verified institution 
- Workspace with creator with verified institution other than All of Us Program operational Use
- Workspace with creator with verified institution as All of Us Program operational Use
---

[RW-4839][RISK=NO] Change logic to 'excludeFromPublicDirectory' flag

---

.circleci/config.yml
api/build.gradle

This turns on html and xml build reporting for JUnit tests. The XML file is used to populate the TESTS tab, which prevents users from having to Ctrl+F "FAILED" in the output.
---

[no ticket][risk=no] write build results to a file and consume that in CircleCI

---

ui/src/app/icons/publicly-displayed-icon.tsx

FIX: Remove duplicate text "Research program"
Before:
After:

[noTicket][RISK=NO]Correct tooltip for publicly displayed icon

---

api/libproject/devstart.rb

- Update bit-rotted API URL reference, this was the primary regression
- Make the arguments all required (usability issue)
- Rename the command and update docs to be more accurate
Future work, not included here:
- This CLI still suffers from not telling you which required flag you forgot (a general issue with all our commands). I don't attempt to solve that here.
- The command leaves you signed in as your admin email account. This is not ideal, but probably needs broader changes
Example usage:
```
./project.rb update-user-disabled-status --project all-of-us-workbench-test --account calbach@fake-research-aou.org --user calbach2@fake-research-aou.org --disabled true
```

[RW-4793][risk=no] Fix disable user CLI

---

ui/src/app/pages/homepage/homepage.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx
ui/src/app/pages/profile/data-user-code-of-conduct.tsx
ui/src/app/utils/code-of-conduct.tsx

Switch the registration dashboard to look at the signed DUA version instead of just the DUA completion time. This brings the UI up to date with the API's behavior on this access module. Without this, users who have completed an old DUA will be stuck on the registration homepage with no actions.
- Pull out logic for determining current DUA version, since it's now in two spots. Notes about how we could refactor in comments.
- Add regression test for this situation.
To test this, I put a user into a state where they've completed DUA v2 with no bypass in test.
Currently on test:
With this PR:

[RW-4864][risk=no] Fix dua completion logic for registration tasks

---

ui/src/app/components/inputs.tsx
ui/src/app/pages/login/account-creation/account-creation.tsx

The fixed width is too big for the account creation page, because we have the text-box on the side. This adds the ability to mess with the styling so that we can override the width on the validated text box, so that we can fix that problem.
---

[No Ticket][Risk=no] Fix the width on account creation to resize based on page.

---

ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx

Pretty straightforward change to hide the beta banner in environments where we're not using the beta access module.
Before:
After:
---

[RW-4856][risk=no] Hide beta access banner when the module is turned off

---

.circleci/config.yml

Since merge https://github.com/all-of-us/workbench/pull/3494, one job, `api-build-test` started to get OOM when running Java Unit tests in CircleCI. I don't know why at this time. To workaround it temporarily, using a bigger vm with 6GB of memory has resolved the issue. 
A previous PR changed `resource_class` to all CircleCI jobs. But that is not necessary because only `api-build-test` requires it.  
Ticket to investigate issue is https://precisionmedicineinitiative.atlassian.net/browse/RW-4874

[no ticket][risk=no] Use a bigger CircleCI vm for api-build-test

---

.circleci/config.yml

The SA key activation was recently factored out. The refactored version writes the key in the `api` subdir, while the previous approach wrote the file to the `deploy` subdir.
https://github.com/all-of-us/workbench/pull/3479/files#diff-1d37e48f9ceff6d8030570cd36286a61L325

[risk=no] Fix keyfile path for staging/perf deploys

---

api/src/main/webapp/WEB-INF/cron_default.yaml

Per request from VUMC, who would like the RDR export to be hard-coded to a specific time of day. We're aiming for this to shift things on test/stable and give it a few days to burn in on stable before we eventually turn on the RDR export in prod.
---

[RW-4877][risk=no] Configure RDR export to run at 9pm CT

---

ui/src/app/app-routing.module.ts
ui/src/app/pages/workspace/workspace-wrapper/component.html
ui/src/app/pages/workspace/workspace-wrapper/component.ts
ui/src/assets/json/help-sidebar.json

This text is now on both the notebook preview page and the actual notebook page.
---

[RW-4888][risk=no] Add helptext to notebooks

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/main/resources/rdr.yaml
api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

**Problem PR is trying to resolve**: In case of deleted workspaces or workspaces with Active_Status other than 0, the request to rdr was not able to set the status as it was doing a enum string match:
RDR has ACTIVE ,INACTIVE while Workbench has ACTIVE, DELETED and PENDING_DELETE. 
Since there was a missing attribute (status) while exportWorkspace call to RDR, the api was throwing 400 Bad Request Error.
**Solution**: Rather than matching Enum string value, check and set rdrWorkspaceStatus as Active for workspaces with active_Status as ACTIVE, else set to INACTIVE in all other cases
---

[noTicket][RISK=LOW]While calling RDR api set status as INACTIVE for deleted Workspace

---

ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx

This was arguably something I missed in the prior PR for RW-4860; the logic needed to be updated elsewhere in the UI to correctly show the "you're all set" banner once all access tasks have been completed.
TESTING: I will plan to manually validate the change post-merge on the test environment. Results will be noted in a comment on RW-4860.
---

[RW-4860][risk=low] Show "all tasks completed" dialog correctly when enableBetaAccess is false

---

api/db/create_db.sql

This caused an issue with the preprod CDR. May as well apply this in all new environments.

[RW-3955][risk=no] Update database ACLs to capture prod CDR convention

---

api/config/config_perf.json
api/config/config_preprod.json
api/config/config_staging.json

Description:
[edit] Following up on ~#3484 and~ #3547 where flags were not flipped in all environments, for release expediency.  This flips all envs to true for ~these two flags~ enableRdrExport.
---

[risk=moderate] Flag consistency for enableRdrExport

---

api/src/main/resources/emails/welcomeemail/content.html

Change 'three' to 'two' after dropping one of the bullets.

[risk=no] Fix welcome email text

---

api/db/create_db.sql
api/db/vars.env
api/libproject/devstart.rb

- Adds a new database user: `dev-readonly`, intended for developer readonly access. Our other usernames are: `workbench` (i.e. the application), `root`, and `liquibase`.
- Adds a new flag to `./project.rb connect-to-cloud-db` of `--db-user`. Defaults to the new readonly user.
If this looks good, I will need to execute the following:
- Apply a manual process to backfill the new username and generated passwords into all vars.env files in all environments
- ~~Manually run the create_db script in all environments to backfill the new user. Alternatively may issue this as manual SQL commands, will figure this out on the ticket.~~
--> **TIL**: create_db.sql gets applied on all migrations

[RW-3942][risk=moderate] Add readonly database user (1/2)

---

api/libproject/devstart.rb

Regression: `run_inline` executes and then continues, `exec` replaces the current process. Revert this change from https://github.com/all-of-us/workbench/pull/3548/files

[RW-4933][risk=no] Revert docker_run change

---

ui/src/app/pages/homepage/registration-dashboard.spec.tsx
ui/src/app/pages/homepage/registration-dashboard.tsx
ui/src/testing/stubs/profile-api-stub.ts

Based on discussion in RW-4913, this seems like the most straightforward fix to the issue encountered in the bug.
Request to reviewers: please test in your own Chrome profile by replicating the 2FA URL, including the authuser param, and trying it out in various scenarios (e.g. Gmail account is primary, G Suite is primary, etc.)
---

[RW-4913][risk=no] Improve reliability of 2FA redirects

---

api/src/main/java/org/pmiops/workbench/institution/InstitutionMapper.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionMapperTest.java

Description:
It would be nice to have a consistent order for email addresses and domains when working with Institutions.  The existing API does not imply any order, and they remain unordered sets in the DB.
---

[risk=low][no ticket] Return email addresses and domains in sorted order for Institutions

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
ui/src/app/pages/profile/profile-page.tsx

Scout noticed a problem on Local: because their user didn't have a Verified Institutional Affiliation associated with it, they couldn't update the user's profile.
It's not necessary to check here, because the control for updating is disabled.  The back end should also be updated to prevent modifying the affiliation.
Tested locally:
[x] A user without Affiliation can edit their profile
[x] User creation still requires Affiliation
[x] A user with Affiliation can edit their profile but not Affiliation
---
---
Before this change, users without Affiliation see this warning label:
And they are prevented from editing their profile:
After the change, the label remains (because it does indeed describe a wrong state):
But the user can edit their profile:
New user creation still …

[risk=no][RW-4928] Don't check Inst Affil on Profile Edit

---

.circleci/config.yml
api/libproject/cloudsqlproxycontext.rb
ci/Dockerfile.circle_build
deploy/docker-compose.yaml

Appears to work on slower starts (verified by Joel).
Simulated timeout (wrong port):
```
+ wait-for-it 0.0.0.0:3308 -t 5
wait-for-it: waiting 5 seconds for 0.0.0.0:3308
2020/05/12 18:17:04 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/05/12 18:17:04 using credential file for authentication; email=all-of-us-workbench-test@appspot.gserviceaccount.com
2020/05/12 18:17:04 Listening on 0.0.0.0:3307 for all-of-us-workbench-test:us-central1:workbenchmaindb
2020/05/12 18:17:04 Ready for new connections
wait-for-it: timeout occurred after waiting 5 seconds for 0.0.0.0:3308
```
Exits as expected

[risk=no] wait-for-it on cloud sql proxy, instead of waiting 1s

---

api/libproject/devstart.rb

This was already reviewed/approved during https://github.com/all-of-us/workbench/pull/3550, which was partially reverted. Adds a new flag to `./project.rb connect-to-cloud-db of --db-user.` Defaults to the new readonly user.
**Blocked on**: https://precisionmedicineinitiative.atlassian.net/browse/PD-5108

[RW-3942][risk=low] Leverage new readonly user in developer CLI tooling (2/2)

---

api/libproject/devstart.rb

On further review, create_db.sql isn't run during deployments. Add a standalone command to apply this per environment as needed. This would only be needed when user creation, grants, or passwords need updating.
```
./project.rb create-or-update-workbench-db --project ...
```

[RW-3942][risk=low] Add a new standalone command to create/update the DB (1.5/2)

---

api/db-cdr/generate-cdr/libproject/devstart.rb

I previously thought this wasn't possible, but I was just misunderstanding the error message. `bq rm -rf` is needed to kill datasets which still contain child tables. Leave the TTL setting in case there's a partial cancel/failure.

[risk=no] Delete the ephemeral ingest dataset on publish-cdr

---

api/db/changelog/db.changelog-135-institution-unique-display-name.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/db/dao/InstitutionDao.java
api/src/main/java/org/pmiops/workbench/db/model/DbInstitution.java
api/src/test/java/org/pmiops/workbench/db/dao/InstitutionDaoTest.java

Description:
Fixes an earlier oversight, and helps ensure correctness for the tool in RW-4911.
I confirmed that there are currently no display name duplicates in any environments.
---

[risk=no] Enforce unique display name for Institutions

---

deploy/bootstrap-docker.sh
deploy/docker-compose.yaml

- Fix the gradle cache location. I had attempted to fix this a while back, but had to rollback: https://github.com/all-of-us/workbench/pull/3238 . This should allow for incremental progress and faster subsequent deploys (e.g. stable push may be slow, preprod/prod fast). Should mitigate issues from 504 gradle installs, as incremental progress is now cached.
- Add yarn cache for consecutive UI builds (for yarn installs)

[RW-4919][risk=low] Fix yarn and gradle caches on deploy

---

api/src/main/java/org/pmiops/workbench/api/OfflineRdrExportController.java

This is a small follow-up based on Jay's observation that exceptions in the RDR export cronjob handler aren't causing the service to return a 500 response.
Screenshot demonstrating this issue (see the line with a severe error log but a 204 response):
TESTING: I haven't tested locally. I'm willing to try and set up some unit tests for RDR export controller (no test file exists yet), but it will take some DI finagling to get working correctly, so I've punted on this for a first cut of this PR.

[no ticket][risk=no] Allow RDR export cron failures to throw a server error

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/main/resources/rdr.yaml

Due to urgency of fix i am adding displayName in serviceImpl, but will create another PR to use RDRMapper for research object as well.
---

[RW-4989][RISK=NO]  Export Verified Institution Display Name to RDR

---

ui/src/app/pages/homepage/registration-dashboard.tsx
ui/src/app/pages/profile/data-user-code-of-conduct.tsx

This PR attempts to clean up some of our user registration navigation endpoints, to clear out the `?workbenchAccessTasks=true` query param if it has ever been set. Some users encountered this issue when walking through registration, where the "access tasks" dashboard never went away.
Unfortunately, the way the registration tasks component is loaded & shown as part of the homepage components makes the fix here quite ugly. (I'd attempted to motivate these two components to be entirely different routes during its original implementation, but didn't succeed.)
While walking through the registration flow, I also noticed that DUCC uses browser.back() instead of navigating to the homepage component. I think the latter is more appropriate, and also would have fixed the issue in RW-4908.
I'm not …

[RW-4908][risk=no] More aggressively clear ?workbenchAccessTasks=true

---

api/db-cdr/generate-cdr/copy-bq-dataset.sh
api/db-cdr/generate-cdr/libproject/devstart.rb

Tested manually in test environment. This is the new convention for any extra tables Cohort Builder adds to the CDR dataset.

[RW-4863][risk=no] Filter CB prep_ tables on publish

---

api/src/main/java/org/pmiops/workbench/db/dao/InstitutionEmailAddressDao.java
api/src/main/java/org/pmiops/workbench/db/dao/InstitutionEmailDomainDao.java
api/src/main/java/org/pmiops/workbench/db/model/DbInstitution.java
api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionEmailAddress.java
api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionEmailDomain.java
api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionUserInstructions.java
api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
api/src/main/java/org/pmiops/workbench/db/model/DbVerifiedInstitutionalAffiliation.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionEmailAddressMapper.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionEmailDomainMapper.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionMapper.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionUserInstructionsMapper.java
api/src/test/java/org/pmiops/workbench/db/dao/InstitutionDaoTest.java
api/src/test/java/org/pmiops/workbench/db/dao/InstitutionEmailAddressDaoTest.java
api/src/test/java/org/pmiops/workbench/db/dao/InstitutionEmailDomainDaoTest.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionEmailAddressMapperTest.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionEmailDomainMapperTest.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionMapperTest.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionUserInstructionsMapperTest.java
api/src/test/java/org/pmiops/workbench/institution/VerifiedInstitutionalAffiliationMapperTest.java
api/src/test/java/org/pmiops/workbench/testconfig/UserServiceTestConfiguration.java
api/tools/src/main/java/org/pmiops/workbench/tools/institutions/LoadInstitutions.java
api/tools/src/main/java/org/pmiops/workbench/tools/institutions/User.java

Description:
The bidirectional mapping between DbInstitution and DbInstitutionEmailDomain/Address caused a lot of confusing and subtle problems.  Now the mapping is present only on the email side of the relationship (the Many side).  Also:
* new mappers and DAOs 
* add equals() and hashCode() to DB model classes
---

[risk=low] Refactor Institutional email matching model objects

---

api/src/integration/java/org/pmiops/workbench/google/CloudResourceManagerServiceImplIntegrationTest.java
api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerService.java
api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java

- Bug fix: actually paginate the project results from CRM. Previous code only examined the first page..
- Bug fix: for default projects (no org/folder), project.parent is null. Handle this
- Behavior: continue after we hit an error. This will allow us to quantify whether we're having issues for all users, or just one.
- Logs: actually log which user we're having auth issues for. Swallowing the exception at a low level and throwing a runtime exception instead is not useful in this situation.

[RW-4906][risk=low] bulkAuditProjectAccess improvements

---

api/tools/src/main/java/org/pmiops/workbench/tools/institutions/OpsUser.java
api/tools/src/main/java/org/pmiops/workbench/tools/institutions/PopulateUserAffiliations.java
api/tools/src/main/java/org/pmiops/workbench/tools/institutions/Researcher.java
api/tools/src/main/java/org/pmiops/workbench/tools/institutions/UserToAffiliate.java

Description:
Now that DbVerifiedInstitutionalAffiliation has a usable equals(), we can use it here.
Also, rename User to UserToAffiliate so we don't confuse it with the main app's User model class.
---

[risk=no] Minor updates to Populate User Affiliation

---

ui/src/app/components/side-nav.spec.tsx
ui/src/app/components/side-nav.tsx

[risk=no][RW-4914] Disable profile in sidenav when unregistered

---

e2e/app/component/create-criteria-modal.ts
ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx

Fix difference in modifiers and attributes pages.

[risk=no] Make capitalization consistent in CB operator dropdowns

---

ui/src/app/cohort-search/modal/modal.component.css

[RW-5054][risk=no] Fix demographics selection list height

---

api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java

Originally I had a secondary check to verify the user did not have an eRA commons name set in the database in addition to firstSignIn. I decided this was probably overkill and that we should try to ensure the system is working well enough that we can depend on "first sign in" containing an accurate value.

[RW-4974][risk=low] Skip unregistered Firecloud users from bulk eRA sync

---

api/docker-compose.yaml

Procurement for Elastic is stalled out. Status is uncertain, but removing this for now will at least reduce some overhead for local dev instances.
If we get a more definitive answer on Elastic, will file a ticket to remove associated code for now.

[risk=no] Disable elastic locally

---

e2e/tests/workspace/workspace-clone.spec.ts

First time, encountered a timeOut error in workspace-clone test in CircleCI job. It's an easy fix.
https://app.circleci.com/pipelines/github/all-of-us/workbench/1570/workflows/0688721b-0a8a-41db-b9ae-1dac6b0ef3df
```
FAIL  tests/workspace/workspace-clone.spec.ts (286.246s)
Clone workspace
From "Your Workspaces" page using Workspace card ellipsis menu
✓ As OWNER, user can clone workspace (58684ms)
From "Data" page using side ellipsis menu
✕ As OWNER, user can clone workspace (123058ms)
● Clone workspace › From "Data" page using side ellipsis menu › As OWNER, user can clone workspace
TimeoutError: Navigation timeout of 30000 ms exceeded
87 |       await signIn(newPage);
88 | 
> 89 |       const response = await newPage.goto(workspaceDataUrl, {waitUntil: …
```

increase goto timeout in workspace-clone.spec

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Notes:
- Refactored validate.js usage to take better advantage built-in capabilities, including `allowEmpty: false`
- Switched to a conditional validation approach, rather than including this in the validation check
- Does not implement any API-level check for non-whitespace strings, this is probably something we should have but is out of scope.
Future work:
- We should rework the error messages to utilize the validate.js error messaging framework. Currently there's a fair amount of duplication going on in this file.

[RW-4918][RW-4767][risk=no] Validate against whitespace-only strings on workspace create/edit/clone

---

.circleci/config.yml

Rename `java-build-test` job to `java-unit-test` for clear identification and run all tests in parallel on 4 CircleCI nodes.

run java-unit-tests in parallel in CircleCI

---

api/config/config_test.json

**Please approve/merge in the morning before merging any other PRs**
I manually applied this for now, but that will be overwritten with the next PR merge.
Confirmed this had the intended effect:

[RW-5080][risk=no] Temporarily turn off FC dev project buffering

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
api/src/bigquerytest/resources/bigquery/cbdata/cb_criteria_data.json
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
api/src/main/java/org/pmiops/workbench/db/dao/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java
api/src/test/java/org/pmiops/workbench/test/SearchRequests.java

This PR addresses moving criteria children lookups from cloudsql to BQ. Also, fixed an existing bug in the SQL export from DataSetBuilder to notebooks. Important changes are listed below:
1. Removing CriteriaLookupUtil#buildCriteriaLookupMap from CohortQueryBuilder(this looks up criteria children in cloudsql and was causing OOM exceptions because of to many child nodes)
2. Adding BQ SQL to SearchGroupItemQueryBuilder to replace the above lookup.
3. Updated CohortBuilderControllerBQTest to reflect these changes
4. In DataSetController added a check for an empty query response.
5. In DataSetServiceImpl added a method(convertSqlTypeToString) to account for all BQ SQL types. The code was making an assumption that only named parameters where numeric.
6. In DataSetControllerBQTest refactored …

[RW-4781][risk=no] add criteria children lookups to BQ count SQL

---

api/docker-compose.yaml

Behavioral change:
- In a few cases, this adds the GOOGLE_APPLICATION_CREDENTIALS. Based on manual testing of commands, this looks like it had no effect, so I'll prefer just making the configs consistent.
- Remove some unused services: mysql-cloud, cloud-sql-proxy. @freemabd in case you're aware of some reason we still need these
Manually tested:
- Ran `./project.rb` commands with coverage of the various docker-compose services
Future work:
- Several of these services are redundant and could be further merged / removed

[risk=no] Refactor docker-compose to leverage anchors

---

.circleci/config.yml
api/docker-compose.yaml
api/src/dev/server/Dockerfile
ci/Dockerfile.circle_build
deploy/docker-compose.yaml

- Bump local dev image from 4.3.1 -> 4.10.3
- Bump Circle image from 4.10.2 -> 4.10.3, these shouldn't have diverged (I probably was responsible)
I want this upgrade as part of [RW-1794](https://precisionmedicineinitiative.atlassian.net/browse/RW-1794). 4.3.1 has some undesirable behavior w.r.t. daemons/locking which seem to be addressed in later versions.
This is a stacked PR against https://github.com/all-of-us/workbench/pull/3658 , I will merge that one first - then rebase this on master.

[risk=low] Upgradle to 4.10.3

---

ui/src/app/pages/data/data-set/dataset-page.spec.tsx
ui/src/app/pages/data/data-set/dataset-page.tsx

On data set page, if researcher selects a Pre packaged cohort then all workspace cohort should be unselect and vice versa
---

[RW-4940][RISK=NO]If all participants is selected in UI we should unselect other cohorts.

---

ui/src/app/pages/data/data-set/dataset-page.tsx

Data Set page: In case the select Cohort/Concept set does not return any result from API, preview table should show a message rather than a blank table
---

[RW-4352][RISK=LOW]  [P2] API doesn't handle empty response for preview table query

---

e2e/app/component/workspace-card.ts
e2e/app/element/xpath-defaults.ts
e2e/app/page-identifiers.ts
e2e/app/page/analysis-page.ts
e2e/app/page/create-account-page.ts
e2e/app/page/data-page.ts
e2e/app/page/featured-workspaces-page.ts
e2e/app/page/google-login.ts
e2e/app/page/home-page.ts
e2e/app/page/profile-page.ts
e2e/app/page/user-admin-page.ts
e2e/app/page/workspace-about-page.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/app/xpath-options.ts
e2e/jest.test-setup.ts
e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-ui.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/export-to-notebook.spec.ts
e2e/tests/user/login.spec.ts
e2e/tests/workspace/workspace-clone.spec.ts
e2e/tests/workspace/workspace-create.spec.ts
e2e/utils/test-utils.ts

typescript constant name is in PascalCase. See https://www.typescriptlang.org/docs/handbook/enums.html#enums
For consistency and standard, rename Const and Enum names in e2e project to PascalCase (aka. Upper CamelCase).
There are lot of names in `workspace-*-page.ts` which I did not rename in this PR. There will be another PR to cover rest of names for consistency in future.

[no ticket][risk=no] Puppeteer: Use PascalCase for const and enum names

---

api/src/main/resources/swaggercodegen/libraries/okhttp-gson/ApiClient.mustache

**Background**
While working on RW-4257 (integrating with a new Shibboleth service), I encountered a need to send a POST request whose message body is a primitive string.
I tried following the instructions in the Swagger 2.0 docs (https://swagger.io/docs/specification/2-0/describing-request-body/ under section "Primitive Body"). When I tried to execute a request using the generated API client, I would see an error: 'Content type "text/plain" is not supported'. Kt turns out this is a longstanding Swagger-codegen issue (https://github.com/swagger-api/swagger-codegen/issues/8288) which hasn't been fixed.
**Guide to reviewer**
This PR implements the proposed workaround (add a new 'else if' branch to support plain-text body). I tested the fix in the context of Shibboleth service integration, …

[no ticket][risk=no] Add support for plain-text request body in Swagger

---

.circleci/config.yml

`api-build-test` was recently renamed to `api-unit-test`. To be consistent, I'm also renaming `ui-build-test` to `ui-unit-test`.

[no ticket][risk=no] CircleCI job rename

---

e2e/app/page/create-account-page.ts

Update finding `Terms of Use` and `Privacy Statement` checkbox selectors because checkbox label element has `for` attribute which is useful for finding the checkbox.

[no ticket][risk=no] Puppeteer update create-account-page.ts

---

e2e/package.json

Reduce maximum number of Puppeteer tests to run in parallel on localhost, thus, reducing their probability of failing.

[no ticket][risk=no] Set maximum number of tests run in parallel

---

ui/src/app/pages/data/data-set/dataset-page.tsx

Problem: Data Set page: Selecting preview table link, sends getPreview request per domain. However the attribute "values(or column)" in the request was not filtered out by domain i.e all selected Values from all domain was part of the each domain request.
As part of this PR only domain specific values will be passed in the getPreviewData by domain request
---

[RW-4941][RISK=LOW]Refactor UI to only pass in values(columns) for the specific domain being requested(Preview DataSet)

---

ui/src/app/app-routing.tsx
ui/src/app/cohort-search/modal/modal.component.tsx
ui/src/app/components/app-router.tsx
ui/src/app/components/footer.tsx
ui/src/app/components/modals.tsx
ui/src/app/components/popups.tsx
ui/src/app/components/status-alert-banner.tsx
ui/src/app/pages/login/account-creation/account-creation-success.tsx
ui/src/app/pages/login/login.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/app/pages/profile/data-user-code-of-conduct.tsx
ui/src/app/pages/signed-in/component.css
ui/src/app/pages/signed-in/component.ts
ui/src/app/utils/stores.ts
ui/src/environments/test-env-base.ts

Demo @ https://calbach-dot-all-of-us-workbench-test.appspot.com
- Update footer to match latest mocks
- The updated content reduced the width below our minimum, which fixed several flow issues
- Fix overlap between footer and right-hand help bar
- Add some extra margin-bottom in a few places where the footer was crowding the page content
- Hide the footer in two new places: TOS and DUCC
- TOS: the account creation TOS change can just be hardcoded, due to the nature of the component
- DUCC: needed to extend the React app router HOC to also include `minimizeChrome`, which is a route config data we have in the Angular router
- Put modals on top of the side bar / footer. Previously, the help bar was not behind the modal overlay - which was a bug
Feedback on the route data changes would be …

[RW-4696][risk=no] Update footer per mocks and fix flow issues

---

api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json

This PR makes it so this flag is enabled across all environments. If we encounter any issues in production, the oncall should be able to push a config change to quickly revet to the old behavior.

[RW-4257] [risk=low] Enable new Shibboleth service in stable, preprod & prod

---

ui/src/app/components/buttons.tsx
ui/src/app/pages/data/concept/concept-homepage.spec.tsx

The FAB on the concept sets page was sliding back behind the footer, making it invisible if you scrolled down. Use position sticky to avoid it sliding beyond the footer.

[RW-4696][risk=no] FAB sticky fixes for footer

---

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java

Description:
We were disabling *all* workspaces, not just free tier.
No ticket, just happened to see this while looking elsewhere.
Note: Not addressed here, but there are two possibilities for determining if a Workspace is Free Tier.  We should fix that: https://precisionmedicineinitiative.atlassian.net/browse/RW-5107
---

[risk=low] Only lock out free tier workspaces on credit expiration

---

ui/src/app/pages/data/data-set/dataset-page.tsx

fixed --> sticky, to avoid bad double-footer interactions
I checked the codebase for fixed position, but missed this as I didn't understand the analyze button was implemented as a footer.

[RW-4696][risk=no] Sticky the dataset builder footer

---

ui/src/app/pages/workspace/workspace-share.tsx

Footer-related-fix `#3` and counting. The z-index changes inadvertently caused issues with the sharing role dropdown, which gets rendered as a floating fixed element. After auditing the other dialogs in the app, this appears to be the only regression caused by the modal z index changes.
I could not write a regression test using enzyme. Instead, I have created a puppeteer test to cover the sharing flow. I've verified that it serves as a regression test for this issue, as well as for RW-5013.

[RW-4696][risk=no] Bump the z-index of the floating dropdown in the share modal

---

.circleci/config.yml
.circleci/e2e-job-ignore-patterns.txt
.circleci/pr-skip-ci.sh
e2e/jest.config.js
e2e/package.json

The command `halt_job_noncode_changes` is called by `puppeteer-*` jobs only. Update its' regex expression to skip `puppeteer-*` job.
Don't run e2e tests if the commit includes non-product code change. I think running e2e tests would be waste of time and resources.

[RW-5125][risk=no] Update grep regex patters in CircleCI

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/profile/PageVisitMapper.java
api/src/main/resources/workbench-api.yaml

Description:
This does not seem to be used anywhere.  It's a part of the Profile model, so the user is already known.
---

[risk=low] rm userId from PageVisit model

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
api/src/main/java/org/pmiops/workbench/user/DevUserRegistrationService.java
api/src/main/java/org/pmiops/workbench/user/DevUserRegistrationServiceImpl.java
api/src/test/java/org/pmiops/workbench/config/WorkbenchConfigTest.java
api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
api/src/test/java/org/pmiops/workbench/user/DevUserRegistrationServiceTest.java

This PR attempts to formalize our dev user registration flow, which had previously been inlined into AuthInterceptor.
Breaking this function out into its own service should make it clearer to any readers what's going on.
The only slightly clever thing going on here is with institutional affiliation: to support the follow-up work (where we want to auto-load a few dev institutions into a blank-slate dev database), this PR adds some logic to dev user registration which finds the first matching institution, if available, and uses that for the verified institutional affiliation. This felt to me like the right thing to do in preparation for the future, but I'm open to alternative views.
---
- [No – this adds a long-lived server config variable] If this includes a new feature …

[RW-4929][risk=low] Add flag control & GSuite email extraction for dev auto-registration

---

api/src/main/webapp/static/aou-download-policy-extension.js
ui/src/app/pages/analysis/notebook-redirect.tsx

When a user is loading a notebook, provide a link to the DUAA on the notebook-redirect page.
When a user tries to download a notebook (dialog path visible in screenshot), show the URL to the DUAA in the alert dialog.
---

[RW-4827][risk=no] Link to DUAA when user is loading notebook or trying to download notebook

---

api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java
api/src/main/java/org/pmiops/workbench/api/StatusAlertController.java
api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
api/src/main/java/org/pmiops/workbench/billing/BillingGarbageCollectionService.java
api/src/main/java/org/pmiops/workbench/interceptors/InterceptorUtils.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/StatusAlertControllerTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java

Description:
Inspired by #2643 - let's just remove this thing.
As a consequence of doing so, move Controllers to the standard location, the `org.pmiops.workbench.api` package.
---

[risk=no] Remove our hacky API mapper

---

e2e/app/component/dialog.ts
e2e/app/component/ellipsis-menu.ts
e2e/app/page-identifiers.ts
e2e/app/page/analysis-page.ts
e2e/app/page/cohort-actions-page.ts
e2e/app/page/cohort-build-page.ts
e2e/app/page/cohort-criteria-modal.ts
e2e/app/page/cohort-participant-detail-page.ts
e2e/app/page/cohort-participants-group.ts
e2e/app/page/cohort-review-page.ts
e2e/app/page/conceptset-actions-page.ts
e2e/app/page/conceptset-save-modal.ts
e2e/app/page/create-account-page.ts
e2e/app/page/data-page.ts
e2e/app/page/dataset-save-modal.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-review.spec.ts
e2e/tests/datasets/dataset-create.spec.ts

Have text strings in one location makes easier for update and find.  And, avoid duplication across all Page-Objects files.
Created new `export enum LinkText` in `page-identifiers.ts` and updated all usage files.

[RW-5130][risk=no] Externalize link and button text strings from all Page-Objects to one file

---

e2e/jest-circus.setup.ts
e2e/jest.config.js
e2e/package.json
e2e/puppeteer-custom-environment.ts
e2e/resources/workbench-config.ts

Issue: the auto-retry in the jest-circus config is annoying for local development. It has be set manually to 0 retries when working on the test on localhost.

[no ticket][risk=no] Puppeteer disable test retries for local test development

---

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/DataSetController.java

this PR contains
1. removing unused daos (cdrVersionDao and cohortDao)
2. removing an unused method -> DataSetController#generateDataSetRequestFromPreviewRequest
3. removing unnecessary curly braces from lambda statements

[no ticket][risk=no] DataSetController cleanup

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java

Modifier AGE_AT_EVENT is working for Domain survey. This PR is just to add a test for the same
---

[RW-4599][RISK=NO] Backend: add Age at Event as modifier to Surveys

---

ui/src/app/cohort-search/modal/modal.component.tsx
ui/src/app/cohort-search/modifier-page/modifier-page.component.spec.tsx
ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx

[RW-4430][RISK=NO]  UI: add Age at Event as modifier to Surveys

---

ui/src/app/app-routing.module.ts
ui/src/app/guards/registration-guard.service.ts

Description:
The registration guard has some "hotwire" checks against certain paths. If one of these paths is in the whiltelist it will bypass the check and return `true`. This can cause unforeseen/unanticipated issues when dealing with other router changes.
The whitelist code has been integrated with the existing angular router.
[Hiding whitespace changes](https://github.com/all-of-us/workbench/pull/3724/files?diff=split&w=1) will make this diff easier to view. 
---
- [] This PR includes appropriate unit tests

[risk=no][RW-5141]Refactor registration guard to prevent sub routing

---

e2e/app/component/concept-domain-card.ts

'Measurements' was changed to 'Labs and Measurements' in the domain_info table.

[risk=no] Puppeteer fix for concept search failure

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

This was a simple regression due to some refactoring I'd done in https://github.com/all-of-us/workbench/pull/3708. It turns out our Profile API model uses 'username' with a different meaning than our codebase, which I overlooked.
---

[RW-5148][risk=no] Fix user creation via directory service

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/components/app-router.tsx
ui/src/app/pages/app/component.ts
ui/src/app/pages/profile/data-user-code-of-conduct.tsx
ui/src/app/services/sign-in.service.ts

Description:
Puts back the router changes. The original issue that required this code to be reverted should have been addressed in 
[3724](https://github.com/all-of-us/workbench/pull/3724)
The user registration flow is currently down on test. I tested this by manually setting the registered user flag in the code to click on the code of conduct link.
---

[risk=no][RW-5142] Undo Router Reversion 

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java

Description:
The code changes are big enough (in line count) that I'm splitting this into API and UI PRs.  This does NOT remove the flag itself!  Only the API code which references it - and many small changes to ProfileControllerTest
---

[risk=no][RW-4361] API portion: rm code depending on Feature Flag requireInstitutionalVerification

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/CohortsController.java
api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
api/src/main/java/org/pmiops/workbench/api/DataSetController.java
api/src/main/java/org/pmiops/workbench/cohorts/CohortService.java
api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
api/src/main/java/org/pmiops/workbench/dataset/BigQueryTableInfo.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetMapper.java
api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
api/src/main/java/org/pmiops/workbench/db/model/DbDataset.java
api/src/main/java/org/pmiops/workbench/db/model/DbDatasetValue.java
api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
api/src/test/java/org/pmiops/workbench/api/ClusterControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
api/src/test/java/org/pmiops/workbench/dataset/DataSetMapperTest.java
api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java

This PR addresses:
1. Implementing `DataSetMapper` to allow full db model to client conversion
2. Removing `DataSetController#TO_CLIENT_DATA_SET` and `DataSetController#TO_CLIENT_DOMAIN_VALUE ` functions and using `DataSetMapper`
3. Implementing `DataSetMapperTest`
4. Updating all affected test classes that use `DataSetMapper`
5. Creation of `BigQueryTableInfo` enum to replace `ConceptSetDao#DOMAIN_TO_TABLE_NAME`

[RW-5062][risk=no] Implement full DataSetMapper

---

ui/src/app/pages/login/account-creation/account-creation.tsx
ui/src/app/pages/profile/profile-page.tsx

Description:
Add validation to the professional URL field in the account creation and profile pages.
I also updated the error messages in the profile page when the save button is disabled to enumerate the errors as it done on other pages.
I looked into URL sanitization, but could not find a library I was satisfied with and also feel some requirements around sanitization should be defined - not only for URL's but all inputs. Also, it is not clear to me what we want to guard against on the client side (URL or HTML sanitization?) and how we want to sanitize (e.g. should we immediately change the input on a change? On a blur? Or not update the field, but save the sanitized value? Will there be server side sanitization, and if so should we converge on a library? etc...)
I added two additional …

[risk=no][rw-4945] Add URL validation to account creation and profile

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/cookie-policy.tsx
ui/src/app/pages/session-expired.tsx
ui/src/app/pages/sign-in-again.tsx
ui/src/app/pages/user-disabled.tsx
ui/src/app/utils/strings.ts
ui/src/app/utils/title.ts

Some of these depend on the Angular `SignInService`. Our overall approach for reactifying these things was to make all the routes themselves react first, then delete the Angular router, then delete the rest of the Angular, so I'm just pushing the `SignInService` down a layer for now.
---

[RW-5099][risk=no] Reactify unguarded static content routes

---

api/tools/README.md
api/tools/src/main/resources/data_dictionary_exports/AllofUsDatasetV3_20200701.yaml
api/tools/src/main/resources/data_dictionary_exports/SyntheticDatasetV3_20200701.yaml
ui/src/app/pages/data/data-set/dataset-page.tsx

Update Data Dictionary entries to include say sex_at_birth_concept_id, sex_at_birth
Input file ref: https://github.com/all-of-us/cdrdatadictionary/blob/development/yaml_files/CDRDD_R2019Q4R3_20200701.yaml 
Also as part of this PR, if there is no data dictionary is not present for a value,   remove the loading spinner and just show the message "Data Dictionary not found" 
This is just an example :
---

[RW-4646][RISK=LOW]  Update Data Dictionary definitions

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml

Add `enableCohortBuilderV2` feature flag and enable only in local env.
---

[RW-5210][risk=no] Create feature flag for Cohort Builder V2

---

api/config/config_test.json

Disables `enableCBAgeTypeOptions` in test env

[risk=no] Revert CB age options change

---

ui/src/app/pages/workspace/workspace-edit.tsx

As part of the story:
https://precisionmedicineinitiative.atlassian.net/browse/RW-2400
Researchers are supposed to be prompted with an information banner to approve/update the research purpose if the workspace has been created and year back or 15 days earlier. There is a cron job that runs every night to updates the attribute need_research_review_prompt to true ,if workspace is 15 days or an year old. This cron job is enabled only on TEST.
There is a bug in the story,  the update workspace call was always setting the attribute need_research_review_prompt to true hence irrespective of the environment if the user will update the workspace , they will start seeing the information banner rather than other way around.
---

[noTicket][RISK=HIGH]Needs research prompt update always setting to true on update

---

api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/resources/workbench-api.yaml
ui/src/app/guards/workspace-guard.service.ts
ui/src/app/pages/workspace/research-purpose.tsx
ui/src/app/pages/workspace/workspace-card.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/pages/workspace/workspace-list.spec.tsx
ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx
ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts

As part of the story https://precisionmedicineinitiative.atlassian.net/browse/RW-2400
A prompt to review research purpose is displayed if the workspace attribute needs_research_purpose_prompt is set to true.
This PR adds Flag check in UI to restrict the prompt on PROD/STABLE/STAGING/PERF enviornment
---

[noTicket][RISK=LOW] Use config flag in UI to show Research Review Prompt

---

api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
api/tools/src/main/java/org/pmiops/workbench/tools/WorkspaceExportRow.java

Per Karthik's request, include timestamp. I've just hardcoded it to CST since I didn't see a clear way to handle time zones in Google sheets. Karthik confirmed this was fine.

[risk=no] Include timestamp in metrics export

---

.circleci/config.yml

skip check has a bug - job were skipped when PR contains changed `.sh`, `.rb` files. I need time to find solution. remove the check in meantime.

[no ticket][risk=no] circleci config change for pupppeteer-e2e-test job

---

api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java

Does simple sorting on the server side. Tested locally by adding a "Greg" institution, which gets sorted correctly in the middle:
---

[RW-5088][risk=no] Sort institutions by display name

---

ui/src/app/pages/admin/admin-institution-edit.spec.tsx
ui/src/app/pages/admin/admin-institution-edit.tsx

Description:
Uses the email validator instead of homegrown regex
Allows numbers in domains before the TLD
---

[risk=low][RW-5251] Validate email domains by constructing test addresses

---

api/src/main/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditor.java
api/src/main/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditorImpl.java
api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
api/src/main/java/org/pmiops/workbench/db/dao/AdminActionHistoryDao.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbAdminActionHistory.java
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/UserServiceAuditorTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java

Description:
Deprecates use of the write-only old-style DbAdminActionHistory, in favor of the current auditing system
Removes 2 of 4 remaining calls because they are duplicated by new-style auditing calls
TODO, deferred to https://precisionmedicineinitiative.atlassian.net/browse/RW-5269
* replace the call to userService.logAdminUserAction() in ClusterController.updateClusterConfig() with new-style auditing
* replace the call to userService.logAdminWorkspaceAction() in WorkspaceController.reviewWorkspace() with new-style auditing
* remove the DbAdminActionHistory object, DAO, and DB table
---

[risk=no] Deprecate userService.logAdminUserAction/logAdminWorkspaceAction

---

ui/src/app/components/buttons.tsx
ui/src/app/components/footer.tsx
ui/src/app/utils/analytics.ts

- Add GA tracking on footer links
- Support an analytics callback function on `StyledAnchorTag`
- Renamed GA enum to follow more standard naming conventions (originally, I'd thought I might export this.. happy to revert if this is too much for the PR)
Alternatives considered on property name:
- `onClick`: this seemed to ambiguous in combination with the standard onclick function (which runs first, etc)
- `sideEffect`: there's nothing GA specific about the callback parameter. However, this also left things a bit ambiguous as to when the side effect might actually run and I don't have any other ideas about what else could use this callback

[RW-5111][risk=no] GA footer, support tracker callback on links

---

e2e/jest.test-setup.ts

Caused one test to fail in headless mode.
https://app.circleci.com/pipelines/github/all-of-us/workbench/2349/workflows/5fcb439c-f417-4dc4-b29a-c33033c7ba7d/jobs/90087/steps

[no ticket][risk=no] Puppeteer remove setViewport

---

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/DataSetController.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetMapper.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
api/src/test/java/org/pmiops/workbench/dataset/DataSetMapperTest.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java

This PR addresses:
1. moving DataSetMapper from DataSetController to DataSetServiceImpl
2. moving DataDictionaryEntryDao from DataSetController to DataSetServiceImpl
3. updating affected test cases.

[RW-5166][risk=no] inject DataSetMapper into DataSetServiceImpl

---

ui/src/app/cohort-search/overview/overview.component.tsx
ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
ui/src/app/cohort-search/search-group/search-group.component.tsx

At some point, the backgrounds switched to gray but should be white.
Before:
After:
---

[RW-5233][risk=no] Fix styles for CB dropdown menu buttons

---

api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java

Part 1: remove all usage of the feature flag
Part 2 (next PR): remove the feature flag
Process which we should formalize: https://github.com/all-of-us/workbench/pull/2920#discussion_r356808233

[RW-4319][risk=no] Drop all usages of sendFreeTierAlertEmails (1/2)

---

api/config/cdr_versions_perf.json
api/config/cdr_versions_preprod.json
api/config/cdr_versions_stable.json
api/config/cdr_versions_staging.json
api/config/cdr_versions_test.json
api/db-cdr/changelog-schema/db.changelog-36.xml
api/db-cdr/changelog-schema/db.changelog-master.xml
api/db-cdr/generate-cdr/bq-schemas/cb_person.json
api/db-cdr/generate-cdr/make-bq-data.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
api/libproject/devstart.rb

This PR does the following:
1. move the CDR version from `synth_r_2019q4_21` to `synth_r_2019q4_2` for test, staging, stable, perf and preprod
2. adds the `is_deceased` column to the `cb_person` table
3. fixes a bug with systolic and diastolic concept ids
4. adds `ensure_docker_sync()` to many of the CDR indexing commands in `devstart.rb`

[RW-5218][risk=no] Adding is_deceased to the cloud CDR

---

api/config/cdr_versions_prod.json

bumping cloud CDR version - change cloud cdr version(r_2019q4_4) to be inline with the BQ name(R2019Q4R3)

[RW-5218][risk=no] bumping cloud CDR version

---

ui/app.yaml

This is a stop-gap until we have CSP enforced.
Tested manually:
- Pushed to https://calbach-dot-all-of-us-workbench-test.appspot.com/
- Verified TOS and DUA still render
- Verified notebook preview still renders

[RW-4950][risk=low] Add x-frame-options SAMEORIGIN to UI responses

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java

This PR addresses:
1. removing death check from `SearchGroupItemQueryBuilder` for age at consent
2. update test to reflect changes.

[RW-5216][risk=no] removing death check for age at consent

---

api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
api/src/main/java/org/pmiops/workbench/utils/mappers/FirecloudMapper.java
api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java

Bug: getWorkspaces() was not returning googleBucketName. See https://github.com/all-of-us/workbench-snippets/pull/50#discussion_r454547600 for where this mattered. Our UI currently doesn't care.
Fix1: consolidate the field masks (request more from getWorkspaces). There should be no performance delta here given the metadata we're requesting.
Fix2: have the mapper use the Firecloud workspace
I used a custom mapper as I didn't see another way, this is pretty ugly - mapstruct experts please advise.

[RW-5295][risk=low] Consolidate field masking, fix mapper

---

ui/src/app/components/footer.tsx
ui/src/app/components/help-sidebar.tsx
ui/src/app/components/side-nav.tsx
ui/src/app/pages/data/data-set/dataset-page.tsx
ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/signed-in/component.ts
ui/src/app/pages/workspace/create-billing-account-modal.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/utils/zendesk.ts
ui/src/environments/environment-type.ts
ui/src/environments/environment.local.ts
ui/src/environments/environment.perf.ts
ui/src/environments/environment.preprod.ts
ui/src/environments/environment.prod.ts
ui/src/environments/environment.stable.ts
ui/src/environments/environment.staging.ts
ui/src/environments/test-env-base.ts

- ZD sandbox (used in lower environments), has different article IDs than in prod
- I decided to build the URLs statically to allow for static references in code
- the locale infix "/en-us/" is not necessary (except for the community forum URL). Better to leave this unset.
- the article ID is the only necessary part of the URL suffix, though when you click the URL via Zendesk it will include a sluggified title. My preference is to omit this, as those titles may change over time
Just linking the URLs directly into the environment.ts, but this felt like it might be overly complicated, for example:
```
cat environment.prod.ts
{
...,
zendeskUrls: zendesk.prodUrls,
...
cat environment.stable.ts
{
...,
zendeskUrls: zendesk.sandboxUrls,
...
```
where zendesk would need to be a hermetic package …

[RW-5089][risk=no] Centralize Zendesk urlset and correct sandbox URLs

---

api/libproject/devstart.rb
api/tools/src/main/java/org/pmiops/workbench/tools/FixDesynchronizedBillingProjectOwners.java

- Fix yet another issue with the "id list" flag approach
- Filter out 1ppw projects. These cause thrashing with the tool, as it can lead to  adding/removing the same person from a billing project repeatedly (one project may be encountered multiple times during iteration).
This tool has already run successfully, these changes are included for posterity.

[RW-5013][risk=no] Backfill tool fixes: id lists and 1ppw projects

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetMapper.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/dataset/DataSetMapperTest.java

Move the following setters from DataSetServiceImpl to AfterMapper function of DataSetMapper :
CreationTime, LastModifiedTime, invalid and CreatorId ( for update) 
---

[RW-5263][risk=no] DatSetServiceImpl.updateDataSet: Use dataSetMapper, After Mapping to set values to databaseObject

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

**Issue**: When a workspace is deleted the from workbench , it is also removed from Firecloud as well. Hence while exporting the deleted workspaces to RDR, _workspaceService.getFirecloudUserRole_ would throw an error ,because of which the deleted workspace will be skipped from export.
**Fix**: Skip the call to get collaborators list  if the workspace is deleted. 
---

[RW-5309][risk=medium] [P1] RDR Export:Workbench not exporting deleted workspaces

---

ui/package.json
ui/yarn.lock

@dolbeew : Can you please confirm if everything is fine? I think HighChart is being used for the following charts:
---

[RW-4513][risk=low] [Frontend] Upgrade our version of Highcharts-react

---

api/buildSrc/src/main/groovy/org/pmiops/workbench/tooling/IncrementalHotSwapTask.groovy

As a stop-gap, this should make the current hotswap less treacherous. Remembered to clean this up from my earlier explorations.

[RW-1794][risk=low] Detect/warn on hotswap failure

---

ui/src/app/app-routing.tsx
ui/src/app/pages/admin/admin-workspace-audit.tsx
ui/src/app/pages/admin/user-audit.tsx
ui/src/app/pages/cookie-policy.tsx
ui/src/app/pages/session-expired.tsx
ui/src/app/pages/sign-in-again.tsx
ui/src/app/pages/user-disabled.tsx

A while ago someone (I think @petesantos) introduced a `routeDataStore` atom that included some top level attributes like `title` (tab title prefix) and `minimizeChrome`. This change puts all the React routes that need to set a tab title prefix in a `withRouteData` wrapper and makes the wrapper naming convention in the React router consistent.

[risk=no][no ticket] unify routeData approach

---

api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java
api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
api/src/test/java/org/pmiops/workbench/opsgenie/EgressEventServiceTest.java

Due to a testing gap I missed the DB ID, and I believe we weren't using the most up-to-date affiliation system. It's now singular instead of plural.
---

[RW-5304][risk=no] Fix missing info in egress alert description

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/login/sign-in.spec.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/app/pages/session-expired.tsx
ui/src/app/pages/sign-in-again.tsx

This also cleans up some passing of props in some React-routed components now that I know how to do it in a nicer way
---

[risk=no][RW-5120] Replace login component route with react

---

.circleci/config.yml

The latest Firefox version (79.0) has issues installing via the CircleCI orb. Pin to 78.0 for now.

[risk=no] Pin Firefox to 78.0 to fix puppeteer

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json

- Switches us back to main bigrquery package
- Installs new workbench-snippets library
- Upgrades R to 4.0
- Additional package updates in Leo base images, see changelogs under https://github.com/DataBiosphere/terra-docker for more details
Plan is to send out user communications along with this upgrade, but we're not expecting severe user impact from these upgrades. Per ongoing designs, we will plan to have a way of running older images for reproducibility in the future.
Manually tested: ran with this image locally, verified main dataset builder flows

[RW-5329][RW-5333][risk=low] Bump aou Leo image to 1.0.4

---

e2e/app/component/modal.ts
e2e/app/component/share-modal.ts
e2e/app/page/cohort-build-page.ts
e2e/app/page/cohort-criteria-modal.ts
e2e/app/page/cohort-participants-group.ts
e2e/app/page/conceptset-page.ts
e2e/app/page/conceptset-save-modal.ts
e2e/app/page/data-page.ts
e2e/app/page/workspace-analysis-page.ts
e2e/app/page/workspace-edit-page.ts
e2e/tests/notebook/notebook-actions.spec.ts
e2e/tests/notebook/notebook-python3.spec.ts
e2e/tests/notebook/notebook-r.spec.ts
e2e/utils/test-utils.ts

Sometimes, click a button in modal should close the modal or/and causes page to change/navigate away. User has to remember to call `waitUntilClose` or/and `this.page.navigation` functions explicitly in order to keep test steps and UI in sync. The refactored`clickButton` function will make it easy to read and write lesser code when click a button in modal.
New function signature is `clickButton(buttonLabel: LinkText, waitOptions: {waitForNav?: boolean, waitForClose?: boolean} = {})`.
All tests verified to pass.

[no ticket][risk=no] Puppeteer: modal clickButton function with optional waitFor parameters

---

ui/src/app/cohort-search/selection-list/selection-list.component.tsx

I notice i left an extra } which is visible at the end of Selected Criteria 
After change: 
---

[noTicket][risk=low]Removing extra closing bracket at the end of selected Cohort

---

api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
ui/src/testing/stubs/cohort-builder-service-stub.ts

Adding sex at birth to response model
- Updated CohortBuilderServiceImpl#findParticipantDemographics to include sex at birth
- Updated workbench-api.yaml to include sexAtBirthList and sex_at_birth filter column
- Added/Fixed API/UI test

[RW-5320][risk=no] Adding sex at birth to response model

---

api/genomics/src/main/java/org/pmiops/workbench/genomics/RandomizeVcf.java

In this array, we don't look for the ref in triallelic sites, we just no-call if it's not one of the alts. So I'm now handling randomizing at triallelic sites differently than biallelic sites. I'm combining the no-call probability with the homref probability and just writing 1/2 and 2/1 where I'd otherwise write 0/1 or 1/0.

triallelic randomize

---

ui/src/app/pages/data/concept/concept-homepage.spec.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx

Prevent calling the api when an invalid MySQL string been entered since they will break the api call.
Also restricting  `[ ] |`  since they will cause errors in the matching regex once the results are returned.
( `]` actually won't cause an error but seems weird to restrict `[` and not `]` )
Shows a warning message if the user tries to search with an invalid string.
Unclosed quote:
Unclosed paren:
Too many closing parens:
Trailing + or -:
Forbidden special character:
The messages will also stack if there are multiple errors in the search string:
---

[RW-5229][risk=no] Restrict special characters that break concept search

---

e2e/tests/notebook/notebook-python3.spec.ts
e2e/tests/notebook/notebook-r.spec.ts

Change back R and Python versions due to reverted PR: https://github.com/all-of-us/workbench/pull/3861
Failed circleci job https://app.circleci.com/pipelines/github/all-of-us/workbench/2837/workflows/201d5932-3fb6-4fc3-9ea2-00402fac6b8e/jobs/93106

[no ticket][risk=no] Puppeteeer: revert R and Python versions

---

api/libproject/devstart.rb
api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
api/tools/src/main/java/org/pmiops/workbench/tools/WorkspaceExportRow.java

There is active work to move to a nightly reporting pipeline. For now though, this script is still being run manually to generate metrics. There is a high priority request for this information - however I do not wish to make it part of the standard export, since the nature of the data is sensitive.

[RW-5341][risk=low] Optionally include demographics in metrics export

---

.circleci/config.yml
e2e/jest.test-setup.ts
e2e/package.json

To make it easier to troubleshoot test failures by print out failed network requests to console. This is useful for circleci test failures investigation.
`--debug` mode circleci e2e-test job results example:
https://app.circleci.com/pipelines/github/all-of-us/workbench/2806/workflows/23bf50ec-c462-4dee-910a-b224923330d1/jobs/92891

[no ticket][risk=no] Puppeteer: log failed requests in debug mode

---

ui/src/app/cohort-search/gender-chart/gender-chart.component.tsx
ui/src/app/components/combo-chart.component.tsx
ui/src/app/styles/colors.ts

Adds a chartColors property in colors.ts based on [this Invision screen](https://projects.invisionapp.com/d/main?origin=v7#/console/12820961/423349542/preview?scrollOffset=25965), and uses the new colors in the cohort builder graphs. 
Approval given by Lou in a comment on [the ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-4588):
---

[RW-4588][risk=no] Update colors for graphs in CB

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/OfflineReportingController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingJobResult.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingMapper.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingService.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotService.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/QueryParameterColumn.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/ReportingInsertionJobBuilder.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/ResearcherParameter.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceParameter.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/main/webapp/WEB-INF/cron_default.yaml
api/src/test/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceTest.java
api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceInsertQueryImplTest.java
api/src/test/java/org/pmiops/workbench/utils/MatchersTest.java
api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java

This batch of changes introduces the notion of a reporting snapshot with a common timestamp and an equal number of rows for several tables. There are a few interesting features:
* new feature flag to enable the cron to do its work (operating at the controller function level)
* pattern to specify column information and query parameter value info in an enum
* service to build the snapshot (independently of any dependency on BigQuery itself)
* Service for BQ upload with one implementation using DML insert queries. We can add implementations for streaming or GCS bulk load if needed without affecting anything else.
* Table and schema specifications are in https://github.com/all-of-us/workbench-devops/pull/51 in workbench-devops
* basic cron schedule for 24 hours.
* distinct dataset names for …

[RW-5198][risk=low] PoC BigQuery Upload service

---

ui/src/app/components/admin/audit-card-list-view.tsx

This caused me quite some confusion when investigating RW-5373 (I though the event was 06:35, it was actually 18:35).
I haven't validated this fix locally, but I'm pretty sure it's correct per the [momentjs docs](https://momentjs.com/docs/#/parsing/string-formats/).

[no ticket][risk=no] Use 24h display for audit event dates

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java

Still seeing BigQuery errors that my insertion is too complex/long. Adding an environment config value with default of 200 (from 500).
---

[no ticket][risk = no] use configurable row limit for insert

---

api/config/cdr_versions_perf.json
api/config/cdr_versions_preprod.json
api/config/cdr_versions_prod.json
api/config/cdr_versions_stable.json
api/config/cdr_versions_staging.json
api/config/cdr_versions_test.json
api/db-cdr/changelog-data/db.changelog-1.xml
api/db-cdr/changelog-schema/db.changelog-38.xml
api/db-cdr/changelog-schema/db.changelog-master.xml
api/db-cdr/generate-cdr/bq-schemas/ds_linking.json
api/db-cdr/generate-cdr/make-bq-data-dump.sh
api/db-cdr/generate-cdr/make-bq-data.sh
api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/cdr/dao/DSLinkingDao.java
api/src/main/java/org/pmiops/workbench/cdr/model/DbDSLinking.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/cdr/dao/DSLinkingDaoTest.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java

This PR moves the ds_linking table into our cloudsql CDR instance. Its more efficient to query this table in cloudsql rather than BQ. The following changes include
1. Updated the CDR indexing scripts to include `ds_linking` table (make-bq-data.sh and make-bq-data-dump.sh)
2. Added `ds_linking` table to our local liquibase build for development purposes
3. Created `DSLinkingDao` and db model `DbDSLinking` with new test case `DSLinkingDaoTest`
4. Updated `DataSetServiceImpl` to use `DSLinkingDao`
5. Bumped all cloudsql CDR versions to allow for using the `ds_linking` table

[RW-5322][risk=no] move ds_linking table to cloud sql

---

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java

This PR creates a new response that adds criteria count
- Created a new response object `CriteriaListWithCountResponse`
- CBCriteriaDao now returns `Page` instead of `List` to allow for count
- Updated dao test

[RW-4596][risk=no] Adding count to criteria search response

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json

- Update to newer TensorFlow python package.
- Update numpy to match documented version (this fixes pandas_profiling in our tests).
- Reinstall AoU fork of bigrquery (new patch taken from ahead of the main package)
Manual testing:
- Ran a local bash shell with the new docker image
- Opened python3 and executed Alex's new test content (derived from manual QA notebook): https://github.com/all-of-us/workbench/blob/0d68c9bfd3420206f0df277b85b757a0175a8385/e2e/resources/python-code/import-libs.py 
- Opened R and executed Alex's new test content: https://github.com/all-of-us/workbench/blob/0d68c9bfd3420206f0df277b85b757a0175a8385/e2e/resources/r-code/import-libs.R

[RW-5329][risk=low] Attempt to upgrade the notebook image again

---

ui/src/app/cohort-search/selection-list/selection-list.component.tsx

When editing a search item, keep the Save Criteria button disabled until changes are made to the selections. This will prevent unnecessary count queries from running.
---

[RW-3851][risk=no] Disable Save Criteria button if no changes made

---

ui/src/app/pages/admin/admin-institution-edit.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.tsx

Description:
I noticed that UNC was oddly alphabetized first.  The reason was a leading space.  This was not immediately obvious because the Display Name is trimmed in the Dropdown.
Trim these strings onBlur
---

[risk=no][no ticket] Trim whitespace from Institution Display Name and Other Text

---

api/build.gradle
api/libproject/devstart.rb
api/src/main/java/org/pmiops/workbench/db/dao/CohortReviewDao.java
api/src/main/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDao.java
api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
api/tools/src/main/java/org/pmiops/workbench/tools/UpdateReviewDemographics.java

UpdateReviewDemographics is a tool that will backfill sex at birth in existing reviews across each env.
To Run: `./project.rb update-review-demographics --project all-of-us-workbench-test --dry-run true`
- **project** the project to run the updates 
- **dry-run** (optional) if true will output what data will get updated

[RW-5358][risk=no] Tool to update sex at birth in existing reviews.

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/workspace/workspace-library.tsx

Description:
Reverted the /library route from the route migration as this was causing an issue with multiple protected route components.
I have identified and addressed part of the issue with protected routes and will have a fix for this forthcoming.
---

[risk=no][RW-5442]Correct issue with ducc / dueling protected routes

---

api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
api/src/main/java/org/pmiops/workbench/cdrselector/WorkspaceResourcesServiceImpl.java
api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
api/src/main/java/org/pmiops/workbench/conceptset/mapper/ConceptSetMapper.java
api/src/main/java/org/pmiops/workbench/db/model/DbConceptSet.java
api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java

This PR finalizes separation of logic between ConceptSetController and ConceptSetService
- ConceptSetController only has access to services and only throws request level exceptions(BadRequestException)
- ConceptSetService has all daos and mappers and only throws service level/db level exceptions
Also added `ConceptSetMapper#dbModelToDbModel` for copy/clone of ConceptSets. Had to add an inner class `ConceptSetContext` to `ConceptSetMapper` to work around a problem with Mapstruct that throws an error: The types of `@Context` parameters must be unique. This was caused by having two `Timestamp` objects as parameters to the `@afterMapping` method.

[RW-5324][risk=no] Move ConceptSetMapper into ConceptSetService

---

ui/src/app/pages/admin/admin-user.tsx
ui/src/app/pages/login/account-creation/account-creation-institution.tsx
ui/src/app/pages/profile/profile-page.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/utils/index.tsx
ui/src/app/utils/institutions.tsx

Description:
Default case (no free tier credit limit override has been set yet) -> default values of 300-800 in dropdown
Existing override = 400 -> value of 400 is preselected, using the same default values
Existing override is not one of the default values -> this value is preselected and added to the dropdown choices, sorted appropriately. Examples for $234.50 and $1500
---

[risk=low][RW-4956] enable free credit limit override UX

---

e2e/tests/notebook/notebook-python3.spec.ts

[CiclreCI e2e test failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/3272/workflows/a00372b4-2ec8-4ad4-8611-c894fe7b6963/jobs/95709) due to unexpected new cell output texts broke one assertion. Remove failed assertion from the test.

[no ticket][risk=no] Puppeteer notebook-python3 test failure

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml

Add a new feature flag "enableConceptSetSearchV2" in api to be used for new concept set search
---

[RW-5367][risk=no] Create feature flag for concept set search refactor

---

ui/package.json

This fixes `yarn lint --fix`, only one of the `&&`'d commands can get the extra arguments. If you want to pass `--fix` to eslint, you can just run `yarn eslint --fix`.
This won't matter once we're exclusively on eslint.

[risk=no] Swap linting order to allow ng lint flag passing

---

e2e/app/component/export-to-notebook-modal.ts
e2e/app/component/modal.ts
e2e/app/component/new-notebook-modal.ts
e2e/app/page/data-page.ts
e2e/app/page/dataset-build-page.ts
e2e/app/page/dataset-save-modal.ts
e2e/app/text-labels.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/export-py-notebook.spec.ts
e2e/tests/datasets/export-r-notebook.spec.ts

Break up `export-to-notebook.spec` test into `export-py-notebook.spec` and `export-r-notebook.spec` tests by programming language.
Reasons are:
- too many tests in single test suite takes a long time to finish.
- Add `Export dataset to notebook thru ellipsis menu` test in `export-py-notebook.spec` test to cover regression https://precisionmedicineinitiative.atlassian.net/browse/RW-5388.

[no ticket][risk=no] Puppeteer dataset export to notebook

---

ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx

Prevent 'undefined' from showing for Blood Pressure and BMI selections
---

[RW-5502][risk=no] Fix units display for Physical Measurements attributes

---

api/genomics/src/main/java/org/pmiops/workbench/genomics/RandomizeVcf.java
api/genomics/src/test/java/org/pmiops/workbench/genomics/RandomizeVcfTest.java
api/libproject/devstart.rb

Example invocation: `./project.rb randomize-vcf --vcf ~/broad/variantstore/NA12878_204126160130_R01C01.vcf --sample-names-file ~/broad/workbench/api/sample_names.txt --output-path /mnt/genomics/randomized.vcf`
Created from Mob session
---

[RW-5474][risk=no] Modify RandomizeVCF to take in a list of sample names

---

.circleci/config.yml

Issue:
Thru observation, it seems when there are many circleci jobs running concurrently (triggered by PRs and merge to master branch), more concurrent login sessions are likely trigger Google captcha during login. This is all because one user email is used for all circleci jobs.
Proposed solution: 
`puppeteer-e2e-local-ui` job will run tests with a different `PUPPETEER_USER_LOCAL` user. And, increase its parallelism to 2 to reduce long test playback time.

[no ticket][risk=no] Puppeteer: e2e circleci jobs have independent test users

---

e2e/app/component/workspace-card.ts
e2e/app/element/checkbox.ts
e2e/app/page/workspace-about-page.ts
e2e/app/page/workspace-analysis-page.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-data-page.ts
e2e/app/page/workspaces-page.ts
e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-rename.spec.ts
e2e/tests/cohorts/cohorts-review.spec.ts
e2e/tests/cohorts/cohorts-ui.spec.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/export-py-notebook.spec.ts
e2e/tests/datasets/export-r-notebook.spec.ts
e2e/tests/notebook/import-r-lib.spec.ts
e2e/tests/notebook/notebook-python3.spec.ts
e2e/tests/notebook/notebook-r.spec.ts
e2e/tests/notebook/notebook-save.spec.ts
e2e/tests/notebook/owner-copy-to-workspace.spec.ts
e2e/tests/notebook/reader-copy-to-workspace.spec.ts
e2e/tests/workspace/workspace-clone.spec.ts
e2e/tests/workspace/workspace-create.spec.ts
e2e/tests/workspace/workspace-edit.spec.ts
e2e/tests/workspace/workspace-share.spec.ts

* Create new `workspace-base.ts` abstract class for extend by `workspace-data-page.ts`, `workspace-analysis-page.ts` and `workspace-about-page.ts` classes. It contains common workspace-page functions.
* Rename `data-page.ts` to `workspace-data-page.ts` to have a consistent name convention like other `workspace-*.ts` page names.

[no ticket][risk=no] Puppeteer: refactor workspace pages

---

ui/src/app/pages/workspace/workspace-wrapper/component.ts

Description:
The `minimizeChrome` data flag was not getting used when added to the react router routes. Additionally, the `minimizeChrome` flag is implicitly used even when it is not defined in the route data config.  This can cause dueling route configs, where the pass through angular route provides no data and utilizes the minimizeChrome flag as an `undefined` value (turning the nav menu on) and the react route later uses it as `true` turning the menu off.
The menu is wider than the other content and was rendering when it should not have been - this is why the help bar did not align in some cases.
I manually test the various route navigations to ensure the menu is turned off when minimizeChrome is specified.
---

[risk=no][RW-5542] Correct issue with minimizeChrome

---

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/java/org/pmiops/workbench/notebooks/NotebooksConfig.java
api/src/main/resources/notebooks.yaml
ui/src/app/pages/analysis/notebook-redirect.spec.tsx
ui/src/app/pages/analysis/notebook-redirect.tsx
ui/src/app/services/notebooks-swagger-fetch-clients.ts
ui/src/app/utils/leo-runtime-initializer.spec.tsx
ui/src/app/utils/leo-runtime-initializer.tsx
ui/src/testing/stubs/leo-runtimes-api-stub.ts
ui/src/testing/stubs/proxy-api-stub.ts

(part 4 of ??)
Depends on #3934 
I considered migrating these to OAS3, but realized I'd need to generate a new set of codegen targets and corresponding boilerplate and also bring in the swagger3 codegen CLI. This didn't seem worth the effort, so instead I downgraded these 4 simple APIs to swagger2, which was a straightforward transformation.
- Upgrade cluster APIs to new Runtime variants
- Upgrade deprecated notebooks APIs --> newer "proxy" variants
- Relabeled Welder endpoints under `proxy` for consistency

[RW-4847][RW-5405][risk=low] Upgrade remaining Leo client-side usages

---

api/snippets-menu/README.md
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/webapp/static/README.md
api/src/main/webapp/static/initialize_notebook_runtime.sh
api/src/main/webapp/static/start_notebook_runtime.sh

Renaming cluster -> runtime (part 6 of 8).
- Functional no-op
- Updated corresponding docs as well
- The two "new" shell scripts are just renamed copies of existing scripts, with wording changes in comments only
- The old assets need to stay there until the old clusters phase out, i.e. 2w after this goes live

[RW-5405][risk=no] Rename cluster assets

---

api/config/cdr_versions_test.json
api/db-cdr/changelog-data/db.changelog-1.xml

https://precisionmedicineinitiative.atlassian.net/browse/RW-5487
- Bumping to synth_r_2019q4_6 in test
- Adding cb_survey_attribute and cb_survey_version
Note: please run `./project.rb run-local-data-migrations` in order to see new cope survey trees locally.

[RW-5487][risk=no] generated new synth cdr and updated csv files

---

ui/src/app/pages/workspace/workspace-card.tsx

Only owners have this permission: https://github.com/all-of-us/workbench/blob/76478bf5553a92968629c42639bf24e044ee9589/api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java#L348
I'm out on Tuesday, so feel free to merge this for me so it makes the release cut.

[RW-5543][risk=no] Disable "edit" on the workspace card menu for writers

---

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/resources/leonardo.yaml

(part 5 of 8)
This change was temporarily held back from https://github.com/all-of-us/workbench/pull/3926, since we discovered the above issue with the CreateRuntime endpoint.
Verified locally via a new runtime creation:

[RW-4847][risk=low] Migrate last Leo endpoint: CreateCluster -> CreateRuntime

---

ui/src/app/cohort-search/tree-node/tree-node.component.spec.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx

[RW-5445][risk=no]UI: Add "versions" indicator for COPE in survey hierarchy

---

api/config/cdr_versions_preprod.json
api/config/cdr_versions_prod.json
api/config/cdr_versions_stable.json
api/config/cdr_versions_staging.json

Bumping cdr versions
**Staging** - synth_r_2019q4_5 -> synth_r_2019q4_6
**Stable**   - synth_r_2019q4_5 -> synth_r_2019q4_6
**Preprod** - r_2020q3_1  -> r_2019q4_7 and synth_r_2019q4_5 -> synth_r_2019q4_6
**Prod**      - r_2019q4_6 -> r_2019q4_7

[RW-5577][risk=no] Bumping cdr versions

---

api/genomics/wdl/IngestSyntheticVcfWf.wdl

Description:
Tested on ~100 sample set with 4 partitions and 5 batch size
Perf testing on a single batch of n=10
n1-standard-1 (1 cpu 4Gb RAM) => 68m
n1-standard-2 (2 cpu 8Gb RAM) => 45m
For 100,000 samples which would be 10,000 instances with a batch size of n=10, Google Cloud Pricing calculator estimates...
- **$113.33 if we use n1-standard-1**
- $263.33 if we use n1-standard-2
---

[RW-5477][RW-5479][risk=np=o] Workflow for creating synthetic microarray data on Cromwell

---

e2e/app/component/data-resource-card.ts
e2e/app/component/share-modal.ts
e2e/app/page/notebook-page.ts
e2e/app/page/workspace-analysis-page.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-data-page.ts
e2e/app/text-labels.ts
e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-rename.spec.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/export-py-notebook.spec.ts
e2e/tests/datasets/export-r-notebook.spec.ts
e2e/tests/notebook/notebook-owner-actions.spec.ts
e2e/tests/notebook/notebook-save.spec.ts
e2e/tests/notebook/owner-copy-to-workspace.spec.ts
e2e/tests/notebook/reader-copy-to-workspace.spec.ts
e2e/tslint.json

* Create common `deleteResource()` function in `workspace-base.ts` abstract class to replace `deleteCohort`, `deleteConceptSet`, `deleteNotebook` and `deleteDataset` functions to reduce code duplication.
* Move `CardType` enum from `data-resource-card.ts` to `text-labels.ts` and rename to `ResourceCard`.

[no ticket][risk=no] Puppeteer: workspace-base deleteResource function

---

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
api/src/main/java/org/pmiops/workbench/cdr/model/DbSurveyVersion.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
api/src/test/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapperTest.java

This PR is adding 2 new endpoints for the COPE survey versions. There are 2 ways to call for survey versions. With question concept id or question concept id and answer concept id.
1. `findSurveyVersionByQuestionConceptId(cdrVersionId, surveyConceptId, questionConceptId)`
2. `findSurveyVersionByQuestionConceptIdAndAnswerConceptId(cdrVersionId, surveyConceptId, questionConceptId, answerConceptId)`

[RW-5462][risk=no] Endpoint for COPE survey versions

---

api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java

Description:
Format pattern was incorrect - it removed apostrophes and didn't substitute all values.
Before: `INFO: User joel.broad.dev@gmail.com isnt in domain {1}, cant access the workbench`
After `INFO: User joel.broad.dev@gmail.com isn't in domain @fake-research-aou.org, can't access the workbench`
---

[risk=low] Fix auth domain error message

---

ui/src/app/components/buttons.tsx
ui/src/app/components/help-sidebar.spec.tsx
ui/src/app/components/help-sidebar.tsx
ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/machines.ts
ui/src/testing/stubs/runtime-api-stub.ts

Changes:
- Add basic runtime panel, rendered only for an active runtime
- Add loading spinner when the runtime is initially requested
- Add lookup table of GCE machine types
- Allow alternate size/configuration for the help sidebar panels; generalizes some logic which was hardcoded in for the criteria tab
- Implement basic machine type option filtering
Notes:
- I took some liberties with the mocks around the recommended runtime dropdown since we don't have a component that behaves in the way described here.
- I also took some liberty with the disk numeric input since we don't have a component for this

[RW-5402][risk=no] Read-only sidebar runtime panel

---

api/src/main/webapp/static/aou-download-policy-extension.js

See code comments for details. Note pictured in the screencap: the download triggers in a new tab, the same as it does today.
Follow-ups:
- This integration depends on implementation details of the Jupyter UI, which could change over time. Will add puppeteer coverage after this goes in.

[RW-5363][risk=low] Add checkbox with custom Jupyter modal

---

api/build.gradle

Fix for failing api-deps-check job in circle-ci

[risk=no] Upgrade dependency-check-gradle to 6.0.1

---

ui/yarn.lock

Description:
See this High Security vulnerability: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/node-forge/open
---

[risk=low] Upgrade vulnerable node-forge

---

ui/src/app/pages/login/account-creation/account-creation.tsx

Straightforward addition of client-side validation to reduce the chance of server-side errors.
Tested locally:

[RW-5624] [risk=no] Add length limits to user creation address fields

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/model/DbAddress.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

See ticket for context – this was a small bug encountered as the result of a user report.
I *think* rolling back the G Suite user creation automatically in this case is the way to go. Happy to have a deeper discussion if anyone feels strongly otherwise.

[RW-5625] [risk=no] Delete orphaned G Suite users if UserRow creation fails

---

ui/src/app/pages/admin/admin-workspace.tsx

Description:
~This is a **Stacked PR** branching off #4028~
Add [Preview] buttons to notebook files in the Workspace Admin page file listing.  Enable only if the admin provides an access reason and the file size is below the maximum (5MB).
Does not add buttons for notebook files outside of the standard location.  (TODO RW-5626)
---

[risk=medium][RW-5481] Link Admin Notebook Preview pages from Workspace Admin page

---

api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java

Removing parent rows from cb_criteria for gender, race, eth and sex at birth has caused some queries to return empty results.

[no ticket][risk=no] fixing display issue of gender, race, eth and sex at birth in review

---

api/reporting/schemas/input/schema_update/make-tables.rb

Long-term plan is to [use Terraform](https://precisionmedicineinitiative.atlassian.net/browse/RW-5272) to create and update BigQuery tables, datasets, etc in different environments. For now, a simple script to roll over a yaml input file will do. YAML files will be stored in the `workbench-devops` [repo](https://github.com/all-of-us/workbench-devops/blob/df0e7d53e192570e5d008fea22597400ac4bda7f/reporting/bq/input_yaml/reporting_test.yaml), as they contain GCP asset names that aren't relevant to the general public. 
Invocation is very simple, just `./make-tables.rb yamlFile.yaml`.
The YAML format (so far) looks like this
```
---
job:
project: environment-gcp-project
dataset: reporting_qa
tables:
- user:
description: |
All user objects eligible for reporting. Includes several denomralized …
```

[RW-5267][risk=no] simple script to make a set of tables described in a yaml file

---

api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java

A method to adjust BillingStatus values based on a feature flag is [no longer necessary](https://precisionmedicineinitiative.atlassian.net/browse/RW-4688), as the flag is always true (and the method is just a simple pass-through). However, we were seeing some really sluggish performance in the new `RreportingMapper` that might be due to this method repeatedly checking the workbench config provider (still unproven).
Since it's no longer necessary, we might as well axe it now.
---

[risk=no][no ticket] simplify billing status

---

e2e/app/page/cohort-search-page.ts

Click on `BMI` didn't work so it led to SideBar didn't open. It was the spinner that interfered with click.

[no ticket][risk=no] Puppeteer Fix flaky cohort tests

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml

Description:
Example of JSON response
```
"runtimeImages": [
{
"cloudService": "DATAPROC",
"name": "test-dataproc-docker-image"
},
{
"cloudService": "GCE",
"name": "test-gce-docker-image"
}
]
```
Please also:
-->
---

[RW-5413][risk=no] Plumb legal runtime images list through ConfigController

---

api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClient.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java

Description:
Implements the logic where we will check the user's latest deleted runtime if we cannot find an active one through getRuntime.
---

[RW-5404][risk=low] GetRuntime: support user override runtime semantics

---

api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
api/src/main/resources/workbench-api.yaml
ui/src/app/components/copy-modal.spec.tsx
ui/src/app/components/copy-modal.tsx
ui/src/app/components/resource-card.tsx
ui/src/app/pages/analysis/notebook-resource-card.tsx
ui/src/app/pages/data/concept/concept-set-details.tsx

Description:
Progress toward RW-5560 and RW-5561, and a useful feature in itself: in the copy-to-workspace Modal, group the destination Workspaces by CDR Version, with the compatible CDR Version first.
TODO (will include in final RW-5560/1 PR):
* unit tests
* e2e tests
---

[risk=low] Group workspaces in copy-to by CDR version

---

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx

As part of this PR:
- Add column Concept id
- Rename Parent and Child Column with Roll-Up and Item Count resp
- Add ToolTip to Count and Item Count Field
---

[RW-5169][risk=no]  UI: Update columns in list view

---

e2e/app/page/notebook-download-modal.ts
e2e/app/page/notebook-page.ts
e2e/tests/notebook/notebook-download.spec.ts

See code comments for details. Finally got this working after a lot of trial and error. The biggest blockers:
1. Utilities all use Page, rather than Frame. This meant I couldn't use existing libraries for frame elements.
1. Some things rendered offscreen on headless - adding the viewport fixed this.
1. Some events were not firing in headless, a `page.evaluate(() => $(..).click())` ultimately solved this, since Jupyter relies on jQuery pretty heavily.
1. Download opens a new tab. In debug mode, this takes control of the browser - need to bring the main page to the foreground in order to continue..

[RW-5363][risk=no]  Puppeteer test for notebook download

---

.circleci/config.yml
e2e/package.json

Firefox install bug was resolved.
Set `maxWorkers=3` seems to work just fine for single CI run and the e2e job completed quicker. Issue may arise if too many CI jobs running concurrently that put too much load on API & UI servers.
`puppeteer-e2e-local-ui` job took under 20 minutes. https://app.circleci.com/pipelines/github/all-of-us/workbench/4314/workflows/0c778cf9-6bc8-47c8-98c4-f4868a10c571/jobs/101540
`puppeteer-e2e-test` job took under 10 minutes. https://app.circleci.com/pipelines/github/all-of-us/workbench/4317/workflows/7bba18e4-dd0e-4447-9ce1-3dbf2ec4cea9/jobs/101551

[no ticket][risk=no] CI e2e job change

---

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx
ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
ui/src/app/cohort-search/selection-list/selection-list.component.tsx

Make the footer with the Calculate, Back and Add/Apply buttons fixed at the bottom of the Attributes & Modifiers sidebars
Top of sidebar content:
Scrolled to the bottom:
---

[RW-5558][risk=no] Make footer for Attributes & Modifiers sidebar sticky

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
ui/src/app/utils/leo-runtime-initializer.spec.tsx
ui/src/app/utils/leo-runtime-initializer.tsx
ui/src/app/utils/runtime-presets.ts
ui/src/testing/stubs/runtime-api-stub.ts

Notes:
- Add new module of runtime presets which will be used to power the create page and preset dropdown
- We expect to launch this ahead of `enableCustomRuntimes`, but I've implemented it such that we should be able to enable them in either order.
- Renames the preset options to better match upcoming mocks:
- DefaultGce -> GeneralAnalysis
- DefaultDataproc -> HailGenomicAnalysis

[RW-4848][risk=low] Add flag to use GCE by default instead of Dataproc

---

api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java

Use new Leo API to let Leo pick the latest prod Welder image for us, instead of having us update a specific hash. This is a new capability they implemented for us a few months back.
Flag can be removed with the following release.

[RW-5098][risk=low] Switch from Welder image -> registry

---

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx
ui/src/app/cohort-search/search-state.service.ts
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx

Implement UI for categorical (versions) and numerical attributes for COPE survey nodes.
COPE attributes form with categorical and numerical attributes
COPE attributes form with 'Any version' and 'Any value' selected
---

[RW-5466][risk=no] Add versions to COPE survey attributes

---

api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java

Projections against Entities in inherit attributes associated with joins,  such as `FetchType.LAZY`. Setting FETCH in the query itself should hopefully override this behavior, which is obviously very slow for large collections of users.
---

[RW-5652][risk=no] use FETCH to eagerly associate address fields

---

e2e/app/component/help-sidebar.ts
ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/components/help-sidebar.tsx

- This avoids hidden elements on the page, which interfere with testing
- This also avoids undesirable background loads which may be triggered by tab contents (currently, the runtime is unexpectedly being requested by a flagged off feature)
Note that switching tabs now may eliminate ephemeral state on the previously active tab. I'm not sure whether that was also the case previously. From manual testing, this didn't seem to cause any obvious issues.

[risk=no] Don't render the sidebar tab content unless active

---

api/config/config_local.json
api/config/config_test.json

Rawls is over some quota limit, which should be restored tomorrow. Revert once confirming with cloud integrations.

[risk=no] Temporarily disable billing buffer cron in test

---

api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java

This is the only instance I was able to find where we might have a specific dependency on the VM naming convention. Please let me know if you're aware of any others.

[RW-5614][risk=no] Handle egress events from GCE

---

api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java

Assumption at this point is that the explosion in query/projection/proxy time & memory is due to lots of lazy fetches. To see if this  is plausible, I want to  see the timing when I have no JOINs at all. To do this, I've simply returned fixed values for the address fields instead of joining on the address table.
---

[RW-5652][risk=no] Quick Perf test with no SQL join

---

api/db/vars.env
api/libproject/devstart.rb
api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/main/webapp/WEB-INF/appengine-web.xml.template
api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java

The available memory for F1  instance class on AppEngine is  256 MB.  The reporting implementation currently loads all the needed snapshot  data into memory at  once, which pushes and frequently exceeds this limit on test.
---

[RW-5652][RISK=NO] upgrade GAE  instance class on test env

---

.circleci/config.yml

If "SKIP E2E" string (case-insensitive) is present in a PR commit message, CircleCI will not run `puppeteer-e2e-test` job.
Halted job screenshot:
Continued job screenshot:
Also, single `puppeteer-e2e-test` job to run for PR commits and master branch merge.

[RW-5681][risk=no] Refactor Puppeteer job in CircleCI config file

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json

This update includes Hail, Plink, and the GATK jar. I was able to combine these all into a single image for now.

[RW-5412][RW-5584][risk=no] Bump AoU notebooks image to latest

---

ui/src/app/cohort-search/selection-list/selection-list.component.tsx
ui/src/app/components/help-sidebar.tsx

- Adjust height of list and position of Modifiers button so the selection list is the only container that scrolls
- Clear `attributesSelectionStore` when sidebar closes
- Remove back arrow from attributes sidebar
---

[RW-5637][RW-5623][risk=no] Bug fixes for criteria sidebar

---

api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json

Enable the feature flag guarding the reporting cron in all environments. Risk to user data or functionality is basically zero, as this feature is read-only w/r/t our system and only writes to the  configured BigQuery dataset.
---

enable reporting cron  in all  envs

---

ui/src/app/utils/stores.tsx

Description:
Adds a store that is not currently in use. This store will be used by RW-5410 and possibly RW-5409
---

[risk=no][no-ticket]Add runtime store to be used with custom runtimes

---

e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts

Break up `conceptset-edit.spec.ts` by concept set feature. One is for editing & rename. Other is for Copy-to-another-workspace.
Test code is not changed.

[no ticket][risk=no] Puppeteer Split ConceptSet test

---

e2e/app/page/authenticated-page.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-data-page.ts
e2e/tests/cohorts/cohorts-rename.spec.ts
e2e/tests/cohorts/cohorts-review.spec.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/dataset-rename.spec.ts
e2e/tests/datasets/export-py-notebook.spec.ts
e2e/tests/datasets/export-r-notebook.spec.ts
e2e/utils/waits-utils.ts

Small improvement in openTab functions:
- If tab is already open (ariaSelected == true), then click on element is skipped.
- If open sub-tab in Data page, users do not have to remember to open Data tab first.

[no ticket][risk=no] Puppeteer Simplify openSubtab function in Data page

---

e2e/app/component/modal.ts
e2e/app/page/authenticated-page.ts
e2e/app/page/cohort-actions-page.ts
e2e/app/page/cohort-build-page.ts
e2e/app/page/cohort-participant-detail-page.ts
e2e/app/page/cohort-review-modal.ts
e2e/app/page/cohort-review-page.ts
e2e/app/page/cohort-search-page.ts
e2e/app/page/conceptset-actions-page.ts
e2e/app/page/conceptset-page.ts
e2e/app/page/conceptset-search-page.ts
e2e/app/page/create-account-page.ts
e2e/app/page/dataset-build-page.ts
e2e/app/page/featured-workspaces-page.ts
e2e/app/page/home-page.ts
e2e/app/page/notebook-download-modal.ts
e2e/app/page/notebook-page.ts
e2e/app/page/notebook-preview-page.ts
e2e/app/page/profile-page.ts
e2e/app/page/user-admin-page.ts
e2e/app/page/workspace-about-page.ts
e2e/app/page/workspace-analysis-page.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-data-page.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/puppeteer-custom-environment.ts
e2e/utils/waits-utils.ts

Fixed blank screenshot and page content `.html` file.
Example: (note: file size is no longer 0 KB)
Code refactoring that allow `handleTestEvent` function to take screenshot and save page contents when error thrown:
- Removed `try...catch` in `isLoaded` function.
- Removed `try...catch` in `waitForLoad` function.

[RW-5700][risk=no] Puppeteer Take screenshot and save page content

---

api/build.gradle

Noticed this while looking at the flake. This matches what we have for the other integration tests.

[risk=no] Don't cache BigQuery integration test results

---

ui/yarn.lock

Description:
karma <5.2.3 depends on vulnerable versions of ua-parser-js.
https://app.snyk.io/vuln/SNYK-JS-UAPARSERJS-610226
https://github.com/karma-runner/karma/pull/3564
---

[risk=low] Upgrade karma due to dependency on vulnerable ua-parser-js

---

api/build.gradle

Description:
Not sure if these are actual vulns or mis-diagnoses by Snyk, because running `./project.rb gradle dependencies --configuration compile` indicates that the vulnerable versions of jackson-databind are actually shadowed by updated versions.  Still, this should at least clean up the Snyk output, enabling us to see the real problems.
---

[risk=low] Upgrade jackson, databind, and json-patch to address snyk vulns

---

e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/resources/workbench-config.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts
e2e/tests/workspace/workspace-create.spec.ts
e2e/tests/workspace/workspace-edit.spec.ts

Description:
Rename all uses of "Dataset" and "Synthetic Dataset" when this really means CDR Version.  Retain the use of "Dataset" to refer to the Workspace Resource of this type.
Add a config value for the default CDR Version per-environment.
Update workspace names in the Copy Concept Set test 
---

[risk=no] e2e test updates for CDR Version selection

---

e2e/app/page/conceptset-actions-page.ts
e2e/app/page/conceptset-page.ts
e2e/app/page/conceptset-save-modal.ts
e2e/app/page/conceptset-search-page.ts
e2e/app/page/dataset-build-page.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-data-page.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts
e2e/tests/workspace/workspace-create.spec.ts

Description:
Also:
* Capitalize `conceptset` to `conceptSet`
* New constant `UseFreeCredits` for the Free Credits Billing Account selection value
---

[risk=no] e2e: Rename incorrect instances of "Concept" to ConceptSet

---

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/DataSetController.java
api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java

This PR addresses the need to change dataset BQ sql generation to account for CB nuances.
- BigQueryDataSetTableInfo - added the new BQ sql to the conceptIdIn property
- DataSetServiceImpl - using feature flag to call the proper conceptIdIn method
- Updated corresponding test cases

[RW-5516][risk=no] update dataset builder BQ sql

---

e2e/app/component/modal.ts
e2e/app/page/conceptset-page.ts

`conceptsets/copy-to-workspace.spec.ts` is flaky. `Copy to Workspace` modal was not ready after open.
https://app.circleci.com/pipelines/github/all-of-us/workbench/4813/workflows/5e96ba37-155a-434f-b9b8-7c58772867f8/jobs/104053/steps
```
FAIL  tests/conceptsets/copy-to-workspace.spec.ts (603.205 s)
Copy Concept Set to another workspace
✕ Workspace OWNER can copy Concept Set (312864 ms)
● Copy Concept Set to another workspace › Workspace OWNER can copy Concept Set
TimeoutError: waiting for XPath "(//*[@role="dialog"]//label | //*[@role="dialog"]//*)[contains(text(), "Destination") or contains(@aria-label, "Destination") or contains(@placeholder, "Destination")]/ancestor::node()[1]//input[@type="text"]" failed: timeout 10000ms exceeded
34 |     if (this.element !== undefined) return …
```

[no ticket][risk=no] Puppeteer fix a flaky test

---

api/config/config_local.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
api/src/main/java/org/pmiops/workbench/cdr/dao/DomainInfoDao.java
api/src/main/java/org/pmiops/workbench/cdr/dao/SurveyModuleDao.java
api/src/main/java/org/pmiops/workbench/cdr/model/DbDomainInfo.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/pages/data/concept/concept-homepage.spec.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/criteria-search.tsx
ui/src/testing/stubs/cohort-builder-service-stub.ts

- When searching on the concept homepage, update the counts on the domain & survey cards instead of switching to the table view
- Remove 'Standard concepts only' checkbox
- Show spinners on each card when updating counts
- Filter out cards with zero counts
---

[RW-5599][risk=no] Update counts for cards on Concept Search homepage

---

e2e/app/page/notebook-page.ts
e2e/resources/python-code/import-os.py
e2e/resources/r-code/sys-print.R
e2e/tests/notebook/notebook-python3.spec.ts
e2e/tests/notebook/notebook-r.spec.ts

Description:
Adding a nonexistent variable to the notebook checks in Python and R caused failures in neither test.  This PR updates both tests so that they do fail when required environment variables are missing. 
---

[risk=no] Notebook environment checks should fail when the variables are not found

---

e2e/app/component/copy-modal.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/resources/workbench-config.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts
e2e/tests/notebook/owner-copy-to-workspace.spec.ts
e2e/utils/test-utils.ts
ui/src/app/components/copy-modal.spec.tsx
ui/src/app/components/copy-modal.tsx
ui/src/testing/stubs/cdr-versions-api-stub.ts
ui/src/testing/stubs/concept-sets-api-stub.ts

Description:
RW-5560 Prevent Copy Concept to Workspace with a different CDR, with error message
RW-5561 Warn when copying Notebook to Workspace with a different CDR (but allow it)
TODO: styling to better match mocks
~TODO: unit tests~
TODO: e2e tests
---

[risk=low][RW-5560][RW-5561] Cross-CDR UX for Copy Concept Set and Notebook to Workspace 

---

api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
api/src/test/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapperTest.java
ui/src/app/pages/data/criteria-search.tsx

Enable CS search to query Physical Measurements from the concept table
- Modified `CohortBuilderController#findCriteriaByDomainAndSearchTerm` to query concept table for the Physical Measurements domain
- Modified CohortBuilderMapper to map a DbConcept to a Criteria model object
- Updated test cases

[RW-5704][risk=no] Enable CS search to query Physical Measurements from the concept table

---

e2e/app/page/workspaces-page.ts
e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-rename.spec.ts
e2e/tests/cohorts/cohorts-review.spec.ts
e2e/tests/cohorts/cohorts-ui.spec.ts
e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/dataset-rename.spec.ts
e2e/tests/datasets/export-py-notebook.spec.ts
e2e/tests/datasets/export-r-notebook.spec.ts
e2e/tests/notebook/notebook-download.spec.ts
e2e/tests/notebook/notebook-python3.spec.ts
e2e/tests/notebook/notebook-r.spec.ts
e2e/tests/notebook/owner-copy-to-workspace.spec.ts
e2e/tests/notebook/reader-copy-to-workspace.spec.ts
e2e/tests/workspace/workspace-clone.spec.ts
e2e/tests/workspace/workspace-edit.spec.ts
e2e/tests/workspace/workspace-share.spec.ts
e2e/utils/test-utils.ts

[risk=no] e2e: rename findWorkspace() and use createWorkspace() to be more explicit

---

api/config/cdr_versions_local.json
e2e/resources/workbench-config.ts

Also resolves the recurring e2e error which looks like:
```
TimeoutError: waiting for XPath "(//label | //*)[text()="Workspace Name" or @aria-label="Workspace Name" or @placeholder="Workspace Name" or @value="Workspace Name"]/ancestor::node()[1]//select/option[text()="Synthetic Dataset v1 with Microarray"]" failed: timeout 10000ms exceeded
```
---

[risk=no] Update local CDR Versions to match test

---

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx

Add tooltips with help text to columns in cohort builder list search.
---

[RW-5639][risk=no] Add help text for CB search result columns

---

api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json

Has been enabled in test for 1.5w. Have not seen any complications yet. Average runtime creation reduced by ~1.5m

[RW-4848][risk=moderate] Enable GCE as the default notebooks runtime

---

ui/src/app/pages/analysis/interactive-notebook.tsx
ui/src/app/pages/analysis/notebook-redirect.tsx

With the switch to GCE, ~2.5m will be more typical - but currently it is already closer to ~4.5m

[risk=no] Improve accuracy of runtime startup estimate

---

ui/src/app/pages/workspace/workspace-about.tsx
ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx
ui/src/app/utils/index.tsx

Description:
Also added a cdrVersion() function to utils and updated Workspace About to remove a state variable
---

[risk=low][RW-5720] Display CDR Version name string in Workspace navbar

---

ui/src/app/pages/workspace/workspace-about.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx

Fix bug introduced in #4186 - ~if `cdrVersionListResponse` was not yet available, the navbar wouldn't render.
Workspace About may have this same problem, so I also fixed that.~
* if `workspace` was not yet available, the navbar wouldn't render.
Description:
---

[risk=no] Guard against race condition preventing navbar rendering

---

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
ui/src/app/cohort-search/demographics/demographics-v2.component.tsx
ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx

- Remove 'Age Range' label above age slider
- Move 'Add Selection' button to the right of age slider
- Remove blank space at top of Visits tree where search bar usually is
-Remove '.' from the end of all help text above trees/list search
---

[RW-5657][risk=no] UI fixes for Cohort Builder

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/runtime-utils.ts

- toolDockerImage will not be controllable for Erwin. Later, we may allow users to change this to an older version of the image.
- remove the "application configuration" header, now that the tool docker image section is gone
- fix a few assumptions to allow the create button to be enabled and functional
- (unrelated opportunistic fix) fix preset menu dropdown being off-center

[RW-5758][risk=no] Render creation panel when runtime doesn't exist + related cleanup

---

ui/src/app/pages/data/concept/concept-homepage.tsx

Show message if there are no cards with counts for any of the three sections. Used same message format as Data Browser.
Example if all sections are empty:
When searching a new term after getting no results, will show a single spinner for each empty section since there are no cards:
---

[RW-5737][risk=no] Add no results messages on concept homepage

---

ui/src/app/pages/analysis/runtime-panel.tsx

Two small things I noticed - probably both oversights from my initial read-only implementation:
- Background color on number input should be white to match others
- Gce before Dataproc is a more natural order

[risk=no] Runtime panel UI style tweaks

---

e2e/tests/conceptsets/conceptset-create.spec.ts
e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
e2e/tests/conceptsets/copy-to-workspace.spec.ts

Skip failures caused by enabling of `enableConceptSetSearchV2` flag in test environment.

[risk=no] Disable failing concept puppeteer tests

---

api/src/main/resources/workbench-api.yaml
ui/src/app/components/resource-card.spec.tsx
ui/src/app/pages/analysis/notebook-list.tsx
ui/src/app/utils/resourceActions.ts
ui/src/testing/stubs/cohorts-api-stub.ts
ui/src/testing/stubs/user-metrics-api-stub.ts
ui/src/testing/stubs/workspaces-api-stub.ts

Description:
Fix an oversight from #4064 : I didn't test copying notebooks with CDR differences from the Analysis page.  Copying from Analysis takes a different path from Recent Resources copies, and this didn't include the new `cdrVersionId` field, so the source CDR was unknown when creating the Copy Modal.
Fixing this was a one-line change: setting `cdrVersionId` from the associated workspace.  The rest is tightening the type checking around WorkspaceResource and test updates to deal with these changes.
---

[risk=low][RW-5561] Fix for Copy Notebook from Analysis page

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java

- Switch to mostly `!` over `%%bash`. I didn't realize this initially, but `!` streams stdout/stderr, while `%%bash` doesn't, which is critical here.
- As a side-effect of that change, make the UUID generation hardcoded across cells
- Update flags per new image locations, flag changes, and other discussion
- Put VCF extracts into a separate folder; may want similar treatment for .mt and .phe files, not sure yet.
Also related find, can add these flags to the GATK extract to subset the data:
```
--min-probe-id "0" \
--max-probe-id "20000" \ # up to ~1.9m
```

[risk=low] Update codegen for image changes and quality of life

---

ui/src/app/pages/workspace/workspace-wrapper/component.ts

This fixes a bug where `this.notebookStyles` was not being properly reset following certain navigations. I'm not sure why it was working in some cases, but there was no logic here to handle `notebookHelpSideBarStyles=true` -> Angular page which doesn't specify `notebookHelpSideBarStyles` (and therefore should be false).

[RW-5779][risk=no] Add fallbacks for Angular route config data

---

ui/src/app/components/copy-modal.spec.tsx
ui/src/app/components/copy-modal.tsx

Description:
No ticket.  UX approved by PO + Design.
---

[risk=no] Disable self-copy in Copy to Workspace Modals for Notebooks and Concept Sets

---

e2e/app/page/notebook-page.ts
e2e/jest.test-setup.ts
e2e/package.json
e2e/utils/waits-utils.ts

Last three CI jobs have failed with timeout failures. Increasing timeout values in few places to eliminate flaky tests.
```
Failed test:  "Workspace-owner-Jupyter-notebook-action-tests/Copy-notebook-to-another-Workspace-when-CDR-versions-match"
Error: waitForKernelIdle encountered TimeoutError: waiting for selector "#kernel_indicator_icon.kernel_idle_icon" failed: timeout 10000ms exceeded
console.error
Notebook kernel is: Kernel Busy
119 |       ]);
120 |     } catch (e) {
> 121 |       console.error(`Notebook kernel is: ${await this.kernelStatus()}`);
|               ^
122 |       throw new Error(`waitForKernelIdle encountered ${e}`);
123 |     }
124 |   }
at NotebookPage.waitForKernelIdle (app/page/notebook-page.ts:121:15)
at NotebookPage.isLoaded (app/page/notebook-page.ts:48:5)
at …
```

[no ticket][risk=no] Puppeteer e2e test timeout fix

---

ui/src/app/components/help-sidebar.tsx

Issue: margin-left on the rotating icon went offscreen, causing a horizontal scrollbar to appear.
Fix: put the margin on a container div instead, let the SVG rotate without margin.

[RW-5791][risk=no] Avoid rotating status icon offscreen

---

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx

**Issue**:  For Windows, the cohort table column does not align with table body 
**Reason**: The tableBody is enclosed in a div with css property overflow: auto, which includes a scroll bar. In windows the scroll takes up space within the body pushing the column data to the left therefore causing the mis-alignment
**Fix**: Not Ideal: however using overflow: overlay solves the issue as overlay puts the slider over the content rather than alongside. The reason its not ideal is because typescript will throw error if used as style={{overflowY: 'overlay'}} as overlay is not an option as part of the class. Using it via style tag works however as the browser is able to understand it. 
With overflow: overlay - MAC
I can test it on Windows once i push the code to test
---

[noTicket][risk=no] Fix Column Header Alignment issue

---

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java

This PR adds surveyName as an optional arg for endpoint `CohortBuilderController#findCriteriaByDomainAndSearchTerm`
- Added 2 new cbCriteriaDao calls
- Added test cases as well
- Added validation for survey domain to throw a BadRequestException if survey name is not provided.

[no ticket][risk=no] adding surveyName as an optional arg for CS search

---

api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
ui/src/app/components/popups.tsx
ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/runtime-presets.ts
ui/src/testing/stubs/runtime-api-stub.ts
ui/test-setup.js

Changes:
- Bug: `bootDiskSize` is an outdated property, just remove it - this caused a few bugs
- Bug: dataproc master settings were ignored
- Bug: preset now affects compute type
- Feature: Show genomics analysis preset IFF hasMicroarrayData
- Preset calculation performed at the end instead, this is less error prone and more future-proof
- Test coverage of form configuration through to the `createRuntime` call
- Test coverage of both presets

[RW-5797][RW-5798][RW-5800][risk=no] Bug fixes for presets and dataproc

---

api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java

This is a temporary band-aid, but it's not strictly necessary to run these crons on users who have been disabled. This should reduce load in production, where a large number of users are disabled.

[RW-5849][risk=moderate] Exclude disabled users from bulk cron

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml

**Do not merge:** until after the next release (containing https://github.com/all-of-us/workbench/pull/4213)

[RW-5658][risk=no] Fully remove deprecated enableGceAsNotebookRuntimeDefault (pt 2/2)

---

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx

When there are 1000 concepts in concept set:
- Show warning message
- Disable + icons
---

[RW-5831][risk=medium] Show warning message when 1000 concepts are added

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/pages/workspace/workspace-about.tsx
ui/src/app/utils/runtime-utils.ts

- Introduced pattern for reuse with create panel and update confirm page: `PanelContent` (open to alternate naming suggestions), which switchCase's the primary content of the panel
- Add the `Delete Environment` link and corresponding confirmation page
- Renamed `runtimeState` to `runtimeStatus`, for consistency
- A bunch of whitespace changes in the main panel - sorry for this: the only actual changes here are:
- introduction of the switchCase, per above (resulting in indentation changes)
- some style refactorings for reuse on the delete page
- Hide the old reset button when `enableCustomRuntimes` is on

[RW-5421][risk=no] Implement 'Delete Environment' button in runtime panel

---

ui/src/app/pages/workspace/workspace-wrapper/component.ts
ui/src/app/utils/runtime-utils.ts

1. Always check for namespace consistency when setting the runtime store, to ensure the async payload is still relevant.
2. Don't call set if you're already calling `LeoRuntimeInitializer`, this already sets (e.g. onPoll setter).
3. Explicitly clear the runtime store when workspace context changes.

[RW-5801][risk=no] Standardize runtimeStore.set callers

---

ui/src/app/pages/analysis/runtime-panel.tsx

- Runtime preset style was lost on rebase in #4240 
- Only show the "reset" language on update (not create)

[risk=no] Minor merge cleanups for runtime panel

---

ui/src/app/app-routing.module.ts
ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/pages/data/concept/concept-add-modal.tsx
ui/src/app/pages/data/concept/concept-homepage.spec.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/concept/concept-list.tsx
ui/src/app/pages/data/concept/concept-set-actions.tsx
ui/src/app/utils/navigation.tsx

- Add warning modal for unsaved changes when leaving concept search
- Update placeholder text in text input for surveys
---

[RW-5840][risk=no] Show warning for unsaved changes in Concept search

---

ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/homepage/recent-resources.tsx

Description:
Follow up to #4242 after Sprint review:
* home page calls getWorkspaces() once instead of twice
* workspace navigation links from notebooks go to the notebooks page
---

[risk=low] Recent Resources Table improvements

---

api/config/config_local.json

[risk=no] Increase local billing buffer to 10, to help with local e2e testing

---

api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java

@NehaBroad made a change 
https://github.com/all-of-us/workbench/blob/aaeeefea96401fbd00bc8d727b2536ed0fc8c42f/api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java#L198-L198
that now accesses the cloud CDR tables, so we needed to set the CDR version before running this query.

[no ticket][risk=no] fixing cdr version issue which is breaking e2e tests

---

e2e/app/page/workspace-edit-page.ts
e2e/tests/workspace/workspace-duplicate.spec.ts
ui/src/app/pages/data/data-set/dataset-page.tsx
ui/src/app/pages/homepage/recent-resources.tsx
ui/src/app/pages/workspace/workspace-about.tsx
ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx
ui/src/app/utils/authorities.spec.tsx
ui/src/app/utils/cdr-versions.spec.tsx
ui/src/app/utils/cdr-versions.tsx
ui/src/app/utils/index.tsx

Description:
This is only a **partial** completion of RW-5564.  The warning modal for non-latest CDR Version is not implemented here.
This also changes the Workspace Duplication UX to always choose the latest CDR Version for duplication.  It **does not** prevent choosing an older version intentionally.  It also does not warn when doing so - that will be part of the next RW-5564 PR.
Note: "v3 with Microarray" is the older version of the CDR in my local environment.  In production it will likely look more like "you are upgrading from v5 to v8"
---

[risk=low][RW-5564] Default to latest CDR on Workspace dupe and show upgrade message

---

ui/src/app/pages/analysis/runtime-panel.tsx

Fix broken UI test.
I'm not sure of which is the defined behavior, but `status` is `undefined` in tests. Either way, this change makes the logic more consistent.
Follow-ups:
- Why did presubmit on the PR not reveal this issue?
- Should status be undefined here? Does it matter?

[risk=no] Check against runtime === null, instead of status, for initial content

---

ui/src/app/cohort-search/tree-node/tree-node.component.tsx

- Hide codes for surveys
- Disable all children when parent node selected

[risk=no] Fix code and selected icon display for tree nodes

---

api/config/config_test.json

We should also look at the number of projects that a single puppeteer test run is consuming. I think it is probably way too high currently.

[risk=low] Double test env billing buffer size

---

ui/src/app/cohort-search/tree/tree.component.tsx

[RW-5829][risk=no] Make scrollbar always visible for overlapping content in CB trees

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx

Currently, you're stuck if you have a runtime in the error status - you can't delete or update the runtime. With this change, the UX is similar to not having a runtime at all.

[risk=no] Handle runtime error statuses

---

api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java
api/src/test/java/org/pmiops/workbench/dataset/mapper/DataSetMapperTest.java
ui/src/app/pages/data/concept/concept-add-modal.tsx
ui/src/app/pages/data/concept/concept-list.tsx
ui/src/app/pages/data/criteria-search.tsx
ui/src/environments/environment.preprod.ts
ui/src/environments/environment.stable.ts
ui/src/environments/environment.staging.ts
ui/src/environments/test-env-base.ts

- Enable flag in test, staging, stable and preprod envs
- Update new concept UI to handle Physical Measurements using list search instead of hierarchy view
- Update api to pull from concept table for Physical Measurements concept search
---

[RW-4606][risk=no] Enable Concept flag for Physical Measurements in preprod

---

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java

When selecting the top node in ANY survey returns 0 count

[no ticket][risk=no] When selecting the top node in ANY survey returns 0 count

---

ui/package.json
ui/src/tsconfig.jest.json
ui/test-setup.js
ui/yarn.lock

Reverts all-of-us/workbench#4287
Many report seeing the following error, though I'm unable to reproduce:
```
src/app/utils/leo-runtime-initializer.spec.tsx:85:25 - error TS2304: Cannot find name 'setImmediate'.
```
--runInBand fixed this for some, but not in all cases. Reverting for now.

[risk=no] Revert "Upgrade jest to latest"

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java

Problem with dataset survey preview rendering. 
The equals below now returns false
`SURVEY.equals(request.getPrePackagedConceptSet())`
because `getPrePackagedConceptSet()` used to return an enum but now returns a list of enums.
Solved by changing equals to use the Domain enum instead.

[RW-5955][risk=no] Problem with dataset survey preview rendering

---

e2e/app/component/workspace-card.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/tests/workspace/old-cdr-version-modal.spec.ts
e2e/tests/workspace/workspace-create.spec.ts
e2e/tests/workspace/workspace-duplicate-cdr-versions.spec.ts
e2e/tests/workspace/workspace-duplicate.spec.ts
e2e/tests/workspace/workspace-edit.spec.ts

Description:
Because WorkspacesPage inherited from WorkspaceEditPage, there were some strange semantics going on here.  Split these two completely, to make tests clearer.
---

[risk=no] e2e: Split WorkspacesPage and WorkspaceEditPage usages

---

ui/src/app/components/help-sidebar.spec.tsx
ui/src/app/components/help-sidebar.tsx

Currently, there's a flash of a yellow spinner after you do an initial creation, on account of the previous logic. This fixes that, and doesn't make much of a difference for the delete/create cycle.

[risk=no] Use creating rather than deleting indicator during compound operation

---

api/db/changelog/db.changelog-143-alter-concept-set-concept-id.xml
api/db/changelog/db.changelog-master.xml

Adding column for standard flag to the concept_set_concept_id table. This is needed to complete [RW-5954](https://precisionmedicineinitiative.atlassian.net/browse/RW-5954)(slated for 12-7 release) and [RW-5978](https://precisionmedicineinitiative.atlassian.net/browse/RW-5978)(slated between 11-30 and 12-7 releases). Please deploy locally and confirm that this doesn't break any concept set functionality

[RW-5977] adding column for standard flag

---

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx
ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
ui/src/app/cohort-search/search-group/search-group.component.tsx

- Fix rename for Fitbit items
- Disable temporal switch for search groups with Fitbit items
- Add URL to 'More Info' link in COPE attributes sidebar
---

[RW-5972][RW-5979][RW-5981][risk=no] Fixes for CB search UI

---

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/criteria-search.tsx

- Add link to Survey Explorer to Cohort Builder and Concept Survey searches
- Move shared help text and links from `CohortSearch` and `ConceptHomepage` to `CriteriaSearch` component
---

[RW-5820][risk=no] Add Survey Explorer link to Surveys criteria search

---

ui/src/environments/environment.preprod.ts
ui/src/environments/environment.stable.ts
ui/src/environments/environment.staging.ts

Turn of Physical Measurement Flag off on Preprod, staging and stable until https://github.com/all-of-us/workbench/pull/4329 is merged in.
---

[noTicket][risk=no]Turn off Physical Measurement flag - preprod staging and stable

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx

Disable the customize form if a runtime exists, and it is not modifiable (running / active).
Changes:
- Plumb `disabled` through all panel components
- Remove some duplication in `CostEstimator`
- Show alternate colors on preset selector when disabled

[RW-5755][risk=no] Disable form controls during runtime state transitions

---

api/build.gradle

Description:
Restore #4314 which somehow got reverted, to address https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415
---

[risk=low] Update to Guava 30 again (got reverted somehow)

---

api/libproject/devstart.rb

We should be able to get away with the second-biggest instance type.
---

[RW-5710][risk=no]downgrade to F4 (1028 MB) on test

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/machines.ts

Will add a test to cover the `useEffect` - going to wait on https://github.com/all-of-us/workbench/pull/4281 before I include this.

[RW-5763][risk=no] Allow cheaper GCE and Dataproc worker machine types

---

api/src/main/java/org/pmiops/workbench/actionaudit/ActionAuditQueryServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceDmlImpl.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceStreamingImpl.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationService.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java

Little service to count rows in all the reporting tables with a given timestamp, to help catch duplicate rows. Logs to warning or info level accordingly.
This check shouldn't be necessary for the batch insert query implementation, but it's easy enough to add it there.
Output looks something like this (will add new tables as they come online):
```
api_1                    | Nov 30, 2020 7:44:18 PM org.pmiops.workbench.reporting.ReportingSnapshotServiceImpl getApplicationDbData
api_1                    | INFO: Application DB Queries: 68ms
api_1                    | Nov 30, 2020 7:44:19 PM org.pmiops.workbench.reporting.ReportingSnapshotServiceImpl convertToReportingSnapshot
api_1                    | INFO: Conversion to ReportingSnapshot: 309ms
api_1                    | Nov 30, 2020 …
```

[RW-5384][risk=no] Check for duplicate rows after streaming upload

---

ui/src/app/pages/workspace/workspace-wrapper/component.ts

Blank sidebar in notebooks was caused by init of `HelpSidebar` with a value still set in `setSidebarActiveIconStore` from a previous page, so the sidebar would open with no content to display. Fixed by resetting `setSidebarActiveIconStore` when we close the sidebar for a route change.

[RW-5920][risk=no] Fix lingering sidebar on notebooks pages

---

api/reporting/curl/upload-snapshot-local-query.sh
api/reporting/curl/upload-snapshot-local-streaming.sh
api/reporting/curl/upload-snapshot-local.sh
api/src/main/java/org/pmiops/workbench/api/OfflineReportingController.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingService.java
api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
api/src/main/java/org/pmiops/workbench/utils/ResponseEntities.java
api/src/main/resources/workbench-api.yaml
api/src/main/webapp/WEB-INF/cron_default.yaml
api/src/main/webapp/WEB-INF/cron_test.yaml

We are currently maintaining two different upload to BigQuery implementations.
1. The default, and currently configured in all environments, is the streaming upload method. This method is fast and simple in some ways, but has a potentially deal-breaking flaw because rows can be duplicated. A unique identifier provided for each row enables "best-effort" deduplication.
2. An insert query-based method, using Data Manipulation Language. In this implementation we have to build query strings and interpolate values we care about. The main operational issue with this mode so far is difficulty in making surer all our queries are below the size and complexity limits for queries.  We don't have much data yet for this mode aside from local runs.
The present PR exposes two test probe cron endpoints …

[RW-5938][risk=no] Dueling crons for Reporting

---

ui/src/environments/environment-type.ts
ui/src/environments/test-env-base.ts

Description:
`testEnvironmentBase` was untyped, which tripped me up a bit when working with environment flags.
---

[risk=no] Add an EnvironmentBase interface for typesafety

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java

So the Data Set builder has a bug where the sql generated adds all concepts into each domain query when selecting multiple concept sets.

[no ticket][risk=no] Fixing bug with multiple concept sets

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/testconfig/WorkbenchConfigConfig.java
api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java
api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java

Description:
Minor unit test cleanup.  Does not touch application code so we should ignore puppeteer in this case.
---

[risk=no] Use WorkbenchConfig.createEmptyConfig() in tests wherever possible

---

ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/leo-runtime-initializer.spec.tsx
ui/src/app/utils/leo-runtime-initializer.tsx
ui/src/app/utils/runtime-presets.ts
ui/src/app/utils/runtime-utils.tsx

Description:
- Lazily create the user's latest runtime is a valid one has been saved. No video since the status updates take too long.
---

[RW-5921][risk=no] Lazy runtime initialization should pick accurate configuration

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/utils/runtime-utils.tsx

This avoids the awkward gap between pressing "create" and the runtime status not being "Creating" yet. It may be possible to address this in other ways, but the Notebooks API doesn't return the runtime from `CreateRuntime`, and I'm not sure I can count on a strong consistency guarantee of doing create -> Get, and we'd ideally block the panel close on reaching the Creating state.
Also, fix a separate issue I found where `dataprocConfig` was `undefined` and not `null` during runtime comparison (I'm not sure if Leo returned undefined, or that was plumbed through from our preset). I would not make any assumption about what Leo is going to return here, and just handle both cases.

[RW-5995][risk=no] Show customize during pending runtime operation

---

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx

- Fix issue where Add and Calculate buttons were disabled when they should have been enabled
- Clear form error messages when switching attribute nodes
- Fix issue that prevents multiple answers being selected from the same COPE question
- Display question and answer for COPE answer selections
---

[RW-6001][risk=no] Fix disable conditions for COPE attribute buttons

---

api/libproject/devstart.rb
api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java

Description:
Improvements to the New Application Environment process via the `project.rb create-auth-domain` command.  See comment below.
**Note: this is arguably a breaking API change.**  But it's a change from an empty response to a response with a body.
---

[risk=low] Update the Create Auth Domain endpoint and project-rb command

---

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java

Make notebook queries more efficient. So BQ sql runs more efficiently when conditions are applied to base table before joining to other tables. In some cases this reduces the runtime from about 30mins to 30secs. For example:
The existing codebase executed joins before conditions are added to the base table.

[no ticket][risk=no] Make notebook queries more efficient

---

.circleci/config.yml

Background:
A single Puppeteer test login user is used for all CI jobs triggered by PRs and merge to master branch. 
Issue:
Too many logins by the same user have triggered Google login page captcha which caused tests to fail.
Proposing a solution to reduce chances of getting captcha: Each CircleCI node that tests run in will have a different test user.
CircleCI environment variables

[RW-6020][risk=no] Puppeteer test users in CircleCI nodes

---

e2e/jest.test-setup.ts

I made a merge mistake. Restoring timeout back to 30 seconds.

[no ticket][risk=no] Puppeteer Default timeout to 30 seconds

---

e2e/tests/workspace/cdr-version-upgrade.spec.ts

Combining two small CDR modal tests into one. Faster playback time, one less login and one less new workspace.

[no ticket][risk=no] Puppeteer Combining two CDR modal tests

---

e2e/app/page/workspace-analysis-page.ts
e2e/tests/cohorts/cohorts-review.spec.ts

Create new workspace in Cohort-Review test because to avoid potential problem when another test is using same workspace at same time.

[no ticket][risk=no] Puppeteer Cohort review test update

---

ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx
ui/src/app/pages/data/criteria-search.tsx

- Lookup criteria ids using `findCriteriaForCohortEdit` call when editing a search item from an existing cohort
-- Only called when entering the tree view in Cohort Builder and not needed for Physical Measurement or Visit domains
- Prevent `ListSearch` component from initializing unnecessarily (PM, Survey, and Visit trees in Cohort Builder) 
---

[RW-6016][risk=no] Lookup criteria ids when editing a cohort

---

api/libproject/devstart.rb

Description:
I suspect that I am more prone to this issue because I aggressively delete my local sa-key.json out of paranoia.
It's possible to get into a state where dev-up will start without sa-key.json and only recreate it after performing a docker-sync.  This causes the app to fail with the following message:
```
java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/w/api/sa-key.json': File does not exist.
```
This PR adds a step to ensure the keyfile exists before docker-sync.
---

[risk=low] Ensures the inclusion of sa-key.json in the docker-sync container

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java

BQ SQL tuning. This PR removes OR between source and standard concepts for Condition and Procedure domains. It is the culprit causing some of our 60s timeouts. 
Example:
```
SELECT * FROM project.dataset.cb_search_all_events
WHERE (is_standard = 1 AND concept_id IN (concept sql)
OR is_standard = 0 AND concept_id IN (concept sql) )
```
It has been refactored to use UNION ALL
Example:
```
SELECT * FROM project.dataset.cb_search_all_events
WHERE person_id IN (
SELECT person_id
FROM project.dataset.SR2019q4r3.cb_search_all_events
WHERE is_standard = 1
AND concept_id IN (concept sql)
UNION ALL
SELECT person_id
FROM project.dataset.cb_search_all_events
WHERE is_standard = 0
AND concept_id IN (concept sql) )
```

[no ticket][risk=no] BQ Sql tuning

---

e2e/jest.config.js
e2e/package.json
e2e/yarn.lock

This was removed in favor of a JSON version which is uploaded to BigQuery. However, this broke artifact upload to CircleCI's UI, which is useful for debugging.

[risk=no] Add back jest-junit for junit XML generation from puppeteer

---

ui/src/app/pages/analysis/notebook-redirect.tsx

Unfortunately the mock matchers are overly specific in Jest, I didn't see a way to cover this case without making it into a change-detector test.

[RW-6044][risk=no] Correctly encode preview page parameter

---

e2e/app/component/runtime-panel.ts

This is a hack, unfortunately it's the best solution I've found so far, and it appears to fix the issue (which I was able to repro locally on headless puppeteer). See inline comment for my working theory.

[risk=no] Sleep before clicking pause/resume

---

ui/src/app/utils/runtime-utils.tsx

With the existing behavior, the runtime initializer will delete if the runtime enters the error state. This would be confusing to the user if it happens.

[risk=no] Set maxDelete to 0 when waiting for start/stop/deletion

---

e2e/tests/runtime/runtime-status-update.spec.ts

Disable now to allow time to fix flaky functions used by tests.

[no ticket][risk=no] Puppeteer Disable flaky test runtime-status-update.spec

---

ui/src/app/pages/workspace/workspace-edit.tsx

I got annoyed enough to add this.
---

[risk=no] Add a spinner to the Workspace create/duplicate confirmation modal

---

.circleci/e2e-job-ignore-patterns.txt

Update ignore file name patterns. It will reduces numbers of test runs in CircleCI.

[no ticket][risk=no] Puppeteer Update file names pattern for skipping tests in CircleCI

---

ui/src/app/app-routing.module.ts
ui/src/app/app.module.ts
ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx
ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
ui/src/app/cohort-search/list-search/list-search.component.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.spec.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/concept/concept-search.tsx
ui/src/app/pages/data/concept/concept-set-details.tsx
ui/src/app/pages/data/criteria-search.tsx

- Move concept search page to a separate route from concept homepage
- Cleanup unused code from old concept search ui
---

[RW-6035][risk=no] Move Concept Search to separate route

---

ui/src/app/pages/workspace/workspace-edit.tsx

Description:
Attempting to edit a workspace name does not work correctly.  Here I'm succeeding at adding "end is fine" but failing at updating in the middle with "middle is not"
This is similar behavior to something we've seen before with Duplicate Workspace, and the fix is the same.  Not sure why we didn't fix both then.
Editing in the middle now works:
---

[risk=no] Fix a UI bug: could not edit WS name in the middle of the field

---

api/reporting/schemas/generate_all_tables.rb
api/reporting/schemas/input/descriptions/workspace.yaml
api/reporting/schemas/input/excluded_columns/workspace.txt
api/reporting/schemas/latest/workspace.json

Three things going on in this PR:
1. Small change to the reporting auto-gen script, to remove `workspace_namespace` as an excluded field.
2. Add some docs and a concrete invocation example to the reporting auto-gen script, after some trial and error.
3. Paste the generated schema JSON into the `latest/workspace.json` file. I'm pretty sure this file will be deprecated in favor of Terraform, but I wanted to keep it in sync for now.
For context: nothing in this PR will affect the operation of the Workbench. This code is simply used to guide the copy-pasting of config & code into other parts of the Workbench system, which will result in distinct PRs.

[RW-6090] [risk=no] Add workspace_namespace column to schema definition generation scripts

---

ui/src/app/components/warning-message.tsx
ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/testing/stubs/runtime-api-stub.ts

You can type directly into the input, and proceeding (create/update/next) is disabled until the number in the input is between 50 (GCP minimum disk GB) and 4000 (AoU maximum disk GB).
---

[RW-6042][risk=no] Allow typing in runtime disk size inputs

---

api/src/dev/server/Dockerfile

Description:
The first time (a certain version of?) `bq` is run in a new environment, it outputs an interactive prompt to choose a default project and populate `.bigqueryrc`.  If that happens to be a script, the command fails because the script is not interactive. 
I was unable to find a way to tell `bq` "stop that, I'm a script!" but it doesn't do this if a `.bigqueryrc` is present.  So let's set one.
Aside: an initial warmup run in our docker env is not sufficient because we don't have write access to `.bigqueryrc` at docker run time.  Every run will prompt and fail in this way.
---

[risk=no][RW-3768] Dumb hack to allow non-interactive runs of bq instead of crashing in a new Local env

---

ui/src/app/pages/data/criteria-search.tsx

**Issue**: If user selects a criteria of type attribute say COVID and does not take any action (back or add this) the panel remains open even on selecting other criteria.
https://user-images.githubusercontent.com/34481816/103697950-a1886700-4f6e-11eb-91da-b0e25ff0c5ad.mov
**Fix**
If criteria is selected, close attribute panel first before taking any action on selections. 
https://user-images.githubusercontent.com/34481816/103698605-9124bc00-4f6f-11eb-8ec1-591669e7a7d5.mov
---

[RW-6004][risk=low] [P4] UI - Cope survey slide out panel still open when selecting nodes from another survey

---

ui/src/app/pages/data/concept/concept-homepage.tsx

Fix issue in Concept Search where searching within a domain, then going back to the homepage and clicking the clear search icon in the search input causes unneeded api calls that fail.
https://user-images.githubusercontent.com/40036095/103854003-13e36f00-5075-11eb-86ec-9b4c2788eae9.mov
After fix:
https://user-images.githubusercontent.com/40036095/103854516-3cb83400-5076-11eb-9a33-ac6cdb1739db.mov

[risk=no] Fix clear input function on concept search homepage

---

.circleci/config.yml

Timeout waiting for notebook page to load in Puppeteer test is 20 min. 
https://github.com/all-of-us/workbench/blob/591b07c841f24e061585b0fad59c52aff7a02c0e/e2e/app/page/workspace-analysis-page.ts#L75
Additionally, another extra 5 minutes waiting for notebook kernel to become idle (ready).
https://github.com/all-of-us/workbench/blob/591b07c841f24e061585b0fad59c52aff7a02c0e/e2e/app/page/notebook-page.ts#L54
During this period of time, there is no console output. CircleCi job can fail when CI detects no console output during timeout time. Fixing issue by increase `no_output_timeout` value.
CircleCI `no_output_timeout` parameter should be >= combined two timeout.

[risk=no] Increase CircleCI no_output_timeout to 25 minutes

---

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
api/src/main/resources/leonardo.yaml
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java

Verified manually that the `configurationType` updates when changing from UserOverride to preset and preset to UserOverride on update.
---

[RW-5852][risk=no] Add preset/UserOverride labels to Leonardo updateRuntime endpoint

---

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceColumnValueExtractor.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java

This PR should cause the reporting cronjob to begin including `workspace_namespace` in the reporting output. See https://github.com/all-of-us/workbench/pull/4439 for the related PR that updates the auto-gen scripts to include the new column.
My process for making these changes was more or less:
1. Copy the new snippet of YAML from the auto-generated workbench output:
`cat /tmp/reporting-output/swagger_yaml/workspace.yaml`
2. Look for places where ReportingWorkspace seems to be referenced, and add an equivalent entry for `workspace_namespace`.
3. Update tests. 
I verified this end-to-end by running a local server, hitting the CRON endpoint, and checking the contenxt of the `all-of-us-workbench-test:reporting_local` dataset (whose schema has already been updated to include the new column). …

[RW-6090] [risk=low] API changes to add workspace_namespace to reporting output.

---

ui/src/app/components/admin/audit-page-component.tsx
ui/src/app/pages/admin/user-audit.tsx

- Switch links to be links instead of buttons
- Update "user admin" link to go to the right page, now that the target page exists.

[risk=no] Improve user audit page links

---

api/db/changelog/db.changelog-145-remove-participant-count.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
api/src/main/java/org/pmiops/workbench/conceptset/mapper/ConceptSetMapper.java
api/src/main/java/org/pmiops/workbench/db/model/DbConceptSet.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/conceptset/mapper/ConceptSetMapperTest.java
api/src/test/java/org/pmiops/workbench/db/dao/ConceptSetDaoTest.java

This PR
1. Removes participant_count from the concept_set table in the workbench db
2. Removes call to BQ for the participant count from create/clone of concept sets
3. Adds a call to BQ for the participant count in the fetch of concept sets for edit(this is the only call that needs the count)

[RW-6053][risk=no] refactoring participant count in concept sets

---

e2e/app/component/workspace-card.ts
e2e/app/page/workspace-about-page.ts
e2e/app/page/workspace-data-page.ts
e2e/tests/home/home-page.spec.ts
e2e/utils/test-utils.ts

Fix test failures caused by data concurrency problem. happens when same workspace is used by more than one tests running concurrently.
`findOrCreateWorkspace` function returns workspaces older than 30 minutes or create new if none found.

[no ticket][risk=no] Puppeteer refactor findOrCreateWorkspace function

---

e2e/tests/runtime/runtime-status-update.spec.ts

Reverts all-of-us/workbench#4417
Originally flakiness appears to have been caused by issues in the Leo dev environment, which now seem to have subsided. Will continue to monitor.

[RW-6061][risk=no] Revert "Puppeteer Disable flaky test runtime-status-update.spec"

---

api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java

This PR removes duplicate BQ sql from
1. SearchGroupItemQueryBuilder
2. ConceptBigQueryService
3. BigQueryDataSetTableInfo
and fixes test cases.

[RW-6119][risk=no] Remove duplicate BQ sql from CS and DS

---

ui/src/app/cohort-search/list-search/list-search.component.tsx

[RW-5824][risk=no] Change concept set and cohort builder search result column order

---

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java

This makes a change to use the feature enabled by https://github.com/DataBiosphere/terra-docker/pull/193
It would be possible (and maybe safer) to add a feature flag to control this. My instinct was that a feature flag would add more boilerplate without much benefit – we could simply push out a rollback PR if needed.
No explicit coordination is required with the Terra-docker push; even if this change ends up in production first, the new env var shouldn't break anything on its own.

[RW-6079] [risk=no] Turn on Jupyter debug-level logs for newly-created clusters

---

ui/src/app/pages/data/data-set/export-data-set-modal.tsx
ui/src/app/pages/data/data-set/export-data-set.spec.tsx
ui/src/app/pages/data/data-set/export-data-set.tsx
ui/src/app/pages/data/data-set/new-dataset-modal.tsx

Extract the common (generate query and notebook selection) code from New Data set modal and export data set modal
---

[RW-2674][risk=low] Code duplication between New Data Set and Export Data Set modals.

---

e2e/app/component/runtime-panel.ts
e2e/utils/waits-utils.ts

This is a low-effort attempt to fix flakiness we're seeing in notebook runtime tests. If the longer timeout seems to help with flakiness, it will be a reasonably good signal that we should split out our notebook runtime tests to run less frequently but allow longer timeouts and durations.

[RW-6162] [risk=no] Extend wait timeout for runtime status changes

---

e2e/tests/cohorts/cohorts-create.spec.ts
e2e/tests/cohorts/cohorts-duplicate.spec.ts

Breaks up single Cohort test: first test covers Create action, second test covers Duplicate action.
Test suites can run in parallel, reduces total runtime.
Test steps are not changed.

[no ticket][risk=no] Puppeteer: break up cohorts-create test into two tests

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java
api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java

This PR makes two changes to the project buffer system:
1) Parameterizes the "number of projects to sync per cron job execution". This had previously been hard-coded to 5, but is now a WorkbenchConfig entry with a standard value of 10.
2) Populates the "lastSyncRequestTime" for newly-created buffer entries to the current timestamp.
See the associated ticket for more context, and code comments for more details. The new unit test is especially interesting; it is effectively a simulation of an outage-and-recovery scenario which allowed me to test whether the above changes would have an impact on our real-world time to recovery.

[RW-6192] [risk=no] Improve project buffer recovery time

---

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoRetryHandler.java

No before image because you'd have to scroll for several hours to get past it
I fixed the spelling in a commit after taking this screenshot
Theoretically I could have threaded through a `suppress_404s` variable of some sort but all these functions override a stack of turtles that ultimately ends in Spring and I legitimately can't think of any 404 case from our interactions with Leonardo that is a case of 'the runtime isn't there and that is bad' vs 'the runtime isn't there yet cause you didn't make one and Swagger throws when this happens'
---

[RW-6080][risk=no] Suppress logspam from 404s when checking or polling for runtime

---

e2e/app/page/create-account-page.ts
e2e/package.json

`registration.spec.ts` nightly test is broken due to bad xpath selector. Broken by recent commit https://github.com/all-of-us/workbench/pull/4486.
Updated xpath selector and test passed okay.

[no ticket][risk=no] Puppeteer Fix Registration test

---

api/src/main/java/org/pmiops/workbench/api/DataSetController.java

PrePackagedSet is no longer contains a single entity, it is actually a list now. So for validating a dataset, throw an exception if there not concept set selected and Prepackaged list contains just one element i.e NONE
---

[noTicket][risk=no]Correct validate check for DataSet

---

e2e/jest.test-setup.ts

log failed requests, console errors, warnings. exclude OPTIONS and non `api-dot-all-of-us` requests. 
To keep secrets, response contents are not logged.

[RW-6234][risk=no] Log requests and console errors when running Puppeteer tests

---

e2e/app/element/base-element.ts
e2e/app/modal/base-modal.ts

Sometimes, click the `Confirm` button in `Create Workspace` modal is not working. The button was not clicked, so the modal remains open then the test fails. I did some investigation, I cannot find any failed requests or page errors after it happened.
Experimental Workaround: before click, check element's position (x,y) is constant, viewport visibility and short delay in click option.
Failure: https://app.circleci.com/pipelines/github/all-of-us/workbench/7185/workflows/46317864-3cf4-4bea-93c5-c7a2b79f3d37/jobs/118435/parallel-runs/1?filterBy=FAILED

[RW-6242][risk=no] Puppeteer click not working sporadically

---

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/pages/data/criteria-search.tsx

- Fix issue where selections don't show as selected when editing an item of an existing cohort
- Fix issue where after a criteria id lookup when editing an item, the unsaved changes warning will show even if no changes have been made.
---

[RW-6177][risk=no] Fix selection display when editing existing cohort

---

e2e/app/text-labels.ts
e2e/jest.test-setup.ts
e2e/tests/datasets/create-py-notebook.spec.ts
e2e/tests/datasets/create-r-notebook.spec.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/dataset-rename.spec.ts
e2e/tests/datasets/export-to-notebook.spec.ts
e2e/tests/notebook/notebook-r.spec.ts
e2e/utils/waits-utils.ts

[CI job 119002](https://app.circleci.com/pipelines/github/all-of-us/workbench/7272/workflows/feb10550-2b29-4fa2-924e-fd2e2a0a9d22/jobs/119002) failed. Caused by multiple test suites were using same workspace concurrently. The runtime spinner was running and caused `waitWhileLoading` function to timeout after 2 minutes.
Fixes:
- `waitWhileLoading` function to handle the runtime spinner on sidebar runtime tab (icon).
- Refactored `jest.test-setup.ts`: Make debug log easier to read and enable user to find out if any request still is in progress ( never finished ) when test is failing.
- Refactored failed `export-py-notebook.spec.ts`: externalize hard-coded strings, force create new workspaces and split the single test suite into two smaller test suites.

[RW-6257][risk=no] Puppeteer fix test failure

---

api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java
api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java

Background: Now user is loaded/uploaded in batch, it is not part of snapshot.  
```
org.pmiops.workbench.exceptions.ExceptionAdvice serverError: ErrorId fd797199-8b95-4399-81b5-31a65e6f64e9: java.lang.NullPointerException
java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
at com.google.common.collect.Lists.partition(Lists.java:659)
at org.pmiops.workbench.reporting.insertion.InsertAllRequestPayloadTransformer.buildBatchedRequests(InsertAllRequestPayloadTransformer.java:40)
at org.pmiops.workbench.reporting.ReportingUploadServiceImpl.getInsertAllRequests(ReportingUploadServiceImpl.java:249)
at org.pmiops.workbench.reporting.ReportingUploadServiceImpl.uploadSnapshot(ReportingUploadServiceImpl.java:102)
at …
```

[no ticket][risk=low]Skip build uploading user request from uploadSnapshot

---

e2e/app/component/runtime-panel.ts

Failed CI [job 119558](https://app.circleci.com/pipelines/github/all-of-us/workbench/7362/workflows/33e94ae6-8cff-466f-a32b-11508b0327cc/jobs/119558/steps).
Increase wait time for notebook runtime to start.

[RW-6279][risk=no] Puppeteer gce-to-dataproc test fix

---

api/db/changelog/db.changelog-149-demographic-survey-add-disability-prefer-no-answer.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorTest.kt
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/src/test/java/org/pmiops/workbench/db/model/StorageEnumsTest.java
ui/src/app/pages/profile/demographic-survey.tsx

Description:
Following up on DbStorageEnums cleanup in #4531 and #4544, and PNTA updates in #4516, add a PNTA enum value for Disability in Demographics Survey.  Migrate exiting NULL Db values to the new enum value.
Clean up related DbStorageEnums code.
---

[risk=low][RW-6908] Add a PREFER_NO_ANSWER enum val to Demographic Survey Disability

---

ui/src/app/pages/profile/demographic-survey.tsx

Description:
I broke the Disability section in #4558 because RadioButtons don't work like I thought they did.  Thanks to the nightly registration test for catching this.
---

[risk=no][RW-6288] Fix Demo Survey Disability bug

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
ui/src/app/pages/admin/admin-user-bypass.spec.tsx
ui/src/app/pages/admin/admin-user-bypass.tsx
ui/src/app/pages/admin/admin-users.tsx
ui/src/testing/stubs/profile-api-stub.ts

This PR makes two major changes to the user admin table:
1. Swap a projection interface in for the existing entity-based DAO calls to improve performance. SQL debugging shows that a single SQL query is now being executed, instead of previously 2-3 queries per user. This should speed up SQL execution time by a significant factor. Executing against the test database, it now takes ~10-15 secs to load (instead of 40-60 secs).
2. Revamp the UI to come closer to Lou's original mocks, including a horizontally-scrollable table with a fixed first column. To prevent extreme UI slow-down with many users, we limit the rows-on-screen to 50 and add client-side filtering. IMO this feels pretty snappy now.
and one bugfix:
- Fix the UserBypass component (it was copying values from props to state only on …

[RW-3389] [RW-4125] [risk=no] Speed up user admin table load time & refresh the UI

---

e2e/package.json

[risk=no] Enable nightly e2e runs against local API+UI

---

ui/src/app/components/card.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx

- Make text spacing on domain cards consistent with survey cards
- Fix alignment of "Select Concepts" links on survey cards
Before:
After:
---

[RW-5818][risk=no] Fix domain card text alignment on concept homepage

---

api/config/cdr_config_perf.json
api/config/cdr_config_preprod.json
api/config/cdr_config_prod.json
api/config/cdr_config_stable.json
api/config/cdr_config_staging.json
api/config/cdr_config_test.json
api/db-cdr/generate-cdr/make-bq-data.sh
api/src/main/java/org/pmiops/workbench/api/DataSetController.java
api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
ui/src/app/cohort-search/utils.ts
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/concept/concept-search.tsx
ui/src/app/pages/data/data-set/dataset-page.tsx
ui/src/app/utils/index.tsx

adding PM to concept set search and dataset preview and export to notebook. This PR also bumps the synth/preprod/prod cloud CDR indices to new version that includes the new PM criteria rows.

[RW-6200][risk=no] adding PM to concept set search

---

ui/src/app/pages/data/data-set/new-dataset-modal.tsx

- Handle all errors to avoid infinite spinner on modal that requires page refresh
- Separate save/update and export error handling to show specific messaging for export failures
Name conflict:
Save failed:
Export failed:
---

[RW-6197][risk=no] Better handling for DataSet Save/Export errors

---

ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/utils/runtime-presets.ts

Preemptively sending this out so we can have this ready to go for next week's release, if desired.
**DO NOT MERGE**: Until getting Shimon's sign-off (question pending to him).
Note: this also updates Dataproc settings for consistency. Only the single GCE change will actually affect production users, since test env genomics is the only place where you can use Dataproc.

[RW-6148][risk=no] Increase default GCE disk from 50 -> 100 GB

---

ui/src/app/pages/data/criteria-search.tsx

Changing `scrollIntoView` option from `block: 'center'` to `block: 'start'` fixes the issue. Also, removed `setTimeout` since it's no longer needed (IIRC it was necessary for Angular).
For some reason, when set to `block: 'center'`, subsequent automatic scrolls won't work if the position of the main page scrollbar was unchanged since the last automatic scroll. If the main page is moved up or down in between automatic scrolls, it seems to work fine. Setting to `block: 'start'` seems work either way.
https://user-images.githubusercontent.com/40036095/108747734-68e32380-7503-11eb-91af-2ce6226d9966.mov
---

[RW-6244][risk=no] Fix flaky automatic scroll in criteria search tree view

---

api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java

Datasets - remove all concept ids from SQL generated when selecting All Surveys using a sub-select.
Old implementation:

[RW-6303][risk=no] Datasets - remove all concept ids from SQL generated when selecting All Surveys

---

.circleci/config.yml
e2e/app/page/create-account-page.ts

Nightly job ran all tests instead tests inside the nightly folder.
CI job [122068](https://app.circleci.com/pipelines/github/all-of-us/workbench/7792/workflows/86f1df0b-b458-4226-b236-02fa50763f94/jobs/122068)
Cause: `puppeteer-executor` override `test_mode` value (`nightly-integration`) in `puppeteer-test` to `integration`. 
Fix by moving `test_mode` parameter from `puppeteer-env-setup` job to `puppeteer-test` job.

[no ticket][risk=no] Puppeteer CI nightly job fix

---

.circleci/config.yml
.circleci/skip-e2e-pr-checks.sh
e2e/package.json

Cause: `persiste_to_workspace` does not save environment variables. Thus env variable `$COMMIT_MESSAGE` was lost in `puppeteer-test` job.

[no ticket][risk=no] CircleCI "skip e2e" check not working

---

api/config/cdr_config_perf.json
api/config/cdr_config_preprod.json
api/config/cdr_config_stable.json
api/config/cdr_config_staging.json
api/config/cdr_config_test.json

bumping synth cdr indices to `synth_r_2019q4_12` for test, staging, stable, preprod

[no ticket][risk=no] bumping synth cdr indices

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java

Description:
#4576 changed the type of a config value instead of deprecating it, which can cause release problems.
Restore the original value but mark it as deprecated.  Remove it after a release cycle: https://precisionmedicineinitiative.atlassian.net/browse/RW-6387
---

[RW-5241][risk=no] Temporarily restore the integer config value bufferCapacity

---

e2e/jest.test-setup.ts

Parsing/reading page console message could fail sometimes or/and throw exception if unable to parse. Throw exception would cause tests to fail.
[log](https://circleci.com/api/v1.1/project/github/all-of-us/workbench/122328/output/107/3?file=true&allocation-id=6035c3c60e4b2a7a29e510d2-3-build%2F226CF0A0)

[no ticket][risk=no] Puppeteer test log improvement

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java

Description:
Partial completion of RW-6180
* (already completed in #4576) Choose tier-appropriate Billing Buffer for workspace create and clone/duplicate
* Choose tier-appropriate Auth Domain for workspace create and clone/duplicate
* Rejects CDR Tier mismatch when cloning/duplicating workspace
* Deprecates/removes DataAccessLevel fields
Does not cover
* Reporting changes for RW-6180
* Friendly UI when a user violates tier equality on Workspace Duplicate (TODO: will commit to not enabling in Preprod/Prod until then)
Also includes
* WorkspacesController refactoring regarding common code between Create and Clone/Duplicate
---

[RW-6180][risk=medium] update Workspace logic for Multi Tier 

---

api/src/integration/java/org/pmiops/workbench/google/CloudStorageServiceImplIntegrationTest.java

Follow-up PR will remove the remaining code that references the invite key.

[risk=no] Switch integration test away from unused invite key

---

ui/src/app/pages/profile/profile-page.tsx
ui/src/app/pages/profile/profile-registration-step-status.tsx

Description:
This is a refactor of the profile step component in preparation for the controlled tier card.
This refactor cleans up some code by:
1. Removing unused props
2. Making the render function a bit more straightforward
3. Always renders children - moving conditionally rendered content to a prop
4. Converts the cards to a CSS grid - this removes the need for some markup and styling specific to the position of the card. It also allows us to add cards dynamically without disrupting the flow or having to stick the cards into rigid 2 item flex rows.
It looks odd in JSX to have child tags that do not get rendered because the sub component conditionally bypasses the rendering of the children - hence the move to a "content" property.
This also makes it easier to fulfill the design of the …

[risk=no][no-ticket]Refactor of the profile step component

---

api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java

Code is adding a query parameter for both source and standard concepts and was using the same key name producing the error below. Also updated unit test to include this breaking scenario:
org.pmiops.workbench.exceptions.ExceptionAdvice serverError: ErrorId c7b3caa2-2a25-472e-aad0-98f99919ef87: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Multiple entries with same key: rankParam=QueryParameterValue{value=%[procedure_rank1]%, arrayValuesInner=null, structValuesInner=null, type=STRING, arrayType=null, structTypesInner=null} and rankParam=QueryParameterValue{value=%[procedure_rank1]%, arrayValuesInner=null, structValuesInner=null, type=STRING, arrayType=null, structTypesInner=null}
at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
at …

[no ticket][risk=no] fixing Multiple entries with same key error

---

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java

Description:
Similar to https://github.com/all-of-us/workbench/pull/4627 - this is the first part of RW-6187.
When we enable CT membership for users, we will report RT and CT membership for users as appropriate.  However that is complex and won't be ready for a while.  For now, unblock reporting updates with this simple binary check for Registered/Unregistered.
Terraform module update is all-of-us/workbench-terraform-modules#21
Devops update is forthcoming.
---

[RW-6187][risk=low] Report "registered" or "none" for user access tiers

---

.circleci/config.yml

Noticed today "Create circleci_parameters.json" step were skipped if previous step (run puppeteer tests) has failed. subsequently, test results upload fails.

[no ticket][risk=no] Always create circleci_parameters.json in CircleCI Puppeteer job

---

api/src/main/webapp/WEB-INF/cron_perf.yaml

This PR feels like the lowest {effort, cost} solution to the perf test failures described in RW-6430. If we discover that disabling these jobs is causing issues, rolling back this PR and re-deploying to perf should be straightforward.

[RW-6430] Disable unreliable crons in perf

---

e2e/app/page/conceptset-page.ts
ui/src/app/components/resource-card.tsx
ui/src/app/pages/data/concept/concept-search.spec.tsx
ui/src/app/pages/data/concept/concept-search.tsx

- Set 1000 character limit for concept set description text area
https://user-images.githubusercontent.com/40036095/109837678-0aa4f780-7c0b-11eb-849a-dcd50b758235.mov
- Add "Show more" button for descriptions over 250 characters
https://user-images.githubusercontent.com/40036095/109707975-6cf4ee00-7b60-11eb-995c-1d4a2ca2dd57.mov
- Prevent long words from overflowing on concept set cards
Before & After:
---

[RW-6166][risk=no] Set character limit, add "Show more" for concept set descriptions

---

api/config/config_local.json
api/genomics/wdl/WgsCohortExtractPrep.wdl
api/src/main/java/org/pmiops/workbench/genomics/WgsCohortExtractionService.java
api/src/test/java/org/pmiops/workbench/genomics/WgsCohortExtractionServiceTest.java

Description:
Invoking an extraction job will now put VCF files into the researcher bucket.
---

[RW-6291][risk=med] Add extract tables -> VCF -> researcher buckets to extraction workflow

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/admin/admin-banner.tsx
ui/src/app/pages/admin/admin-review-workspace.tsx

This is based on `as/reactify-user-admin-routes` because I don't want to cause a huge rebase kerfuffle  with several branches editing the same files at the same time
--

[RW-6317][risk=no] Reactify remaining admin routes

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx

Moved workspaceEditMode to props from routeData because this is the only component to use that concept.
---

[RW-6318][risk=no] Reactify WorkspaceEditComponent

---

api/db/changelog/db.changelog-154-wgs-cromwell-extract-submission.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/db/dao/WgsExtractCromwellSubmissionDao.java
api/src/main/java/org/pmiops/workbench/db/model/DbWgsExtractCromwellSubmission.java
api/src/main/java/org/pmiops/workbench/genomics/WgsCohortExtractionService.java
api/src/test/java/org/pmiops/workbench/dataset/mapper/DataSetMapperTest.java
api/src/test/java/org/pmiops/workbench/genomics/WgsCohortExtractionServiceTest.java

- Introduce new table
- Add row when creating a new extract job
Note:
- dataset ID is unused, this is in anticipation of moving this method out of cohorts -> datasets
- there is a chance of orphaning a job here, we will probably need to have some kind of background job here to monitoring jobs to make sure they aren't going off the rails (if desired, this could synchronize some status information in our own db)

[RW-6341][risk=low] Add cromwell WGS extract table

---

.circleci/skip-e2e-pr-checks.sh
ui/src/app/pages/workspace/workspace-edit.spec.tsx

Exit CircleCI e2e (puppeteer) job if changed files in the last commit match ignore patterns are the only changed files in the last commit.
Before:
In this [CI run](https://app.circleci.com/pipelines/github/all-of-us/workbench/8210/workflows/e969afc0-6789-40ff-b6a7-903963c86a95), only one UI test were changed in the last commit. It's okay to skip running Puppeteer tests because UI test name is one of many ignore patterns.
After (e2e job exited early due to the check):
[CI run](https://app.circleci.com/pipelines/github/all-of-us/workbench/8235/workflows/8d800e2f-7a81-4ff4-9581-30336499a70d)

[no ticket][risk=no] CircleCI config: add check to exit e2e test job early

---

api/db/changelog/db.changelog-155-add-ras-link-entries.xml
api/db/changelog/db.changelog-156-billing-buffer-entry-status-index.xml
api/db/changelog/db.changelog-master.xml

Description:
Background: post workspace times out if too many request comes at the same time. Adding index would speed up the query time.
```
mysql> SHOW INDEX FROM billing_project_buffer_entry;
+------------------------------+------------+-----------------------------------------------+--------------+---------------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                        | Non_unique | Key_name                                      | Seq_in_index | Column_name                     | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+------------------------------+------------+-----------------------------------------------+--------------+--------------------------- …
```

[RW-6461][risk=low]: Add index on status for billing_project_buffer_entry table

---

api/config/config_perf.json

Seems this was just a typo in this particular config - other environments look fine. This caused a failure on deploy because the config JSON wasn't recognized.
A very old ticket is still the correct fix for this issue, which is to add a test to cover config correctness: https://precisionmedicineinitiative.atlassian.net/browse/RW-2408

[risk=no] Fix unsafeAllowAccessToAllTiersForRegisteredUsers config value location

---

e2e/app/element/select.ts
e2e/tests/workspace/workspace-edit.spec.ts

Issue: `getSelectedValue` is not working when working inside a disabled `select` element. An workaround was used but it works with following annoying error every time.
```
console.warn
Select is disabled. Cannot select option value: "Synthetic Dataset v3".
27 |     const disabled = await this.isDisabled();
28 |     if (disabled) {
> 29 |       console.warn(`Select is disabled. Cannot select option value: "${value}".`);
|               ^
30 |     }
31 |     const selector = `${this.xpath}/option[text()="${value}"]`;
32 |     await this.page.waitForXPath(selector);
at Select.selectOption (app/element/select.ts:29:15)
at Object.<anonymous> (tests/workspace/workspace-edit.spec.ts:33:28)`
```

[no ticket][risk=no] Puppeteer getSelectedValue function fix

---

ui/src/app/pages/app/component.ts
ui/src/app/utils/title.ts

- Window title flashed in "undefined | " during initial load. Fix this by properly handling unset values in the route parameters
- Switched code to use dead utility function for building page titles
- Updated page title logic to always place the environment first; most people are unlikely to notice/care the tab title, but this feels more consistent to me

[RW-5741][risk=no] Fix "undefined" in the window title

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/app.module.ts
ui/src/app/pages/data/concept/concept-homepage.tsx
ui/src/app/pages/data/concept/concept-set-actions.tsx

Moves routes for `ConceptHomepage` and `ConceptSetActions` components from Angular to React router
---

[RW-6320][risk=no] Move concept homepage and actions page to React router

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java

Removes bufferCapacity from WorkbenchConfig

[risk=no] RW-6387 Cleanup: remove single-tier bufferCapacity config param

---

.circleci/config.yml
api/src/test/java/org/pmiops/workbench/genomics/WgsCohortExtractionServiceTest.java

2GB -> 3GB. UPdating https://precisionmedicineinitiative.atlassian.net/browse/RW-6460 with working theory. Capturing heap dump wasn't too useful, but did show some things.

[RW-6460][risk=no] Bump heap size for API unit tests

---

api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java

This caused the latest cdr_config_local change to not get picked up. I'm not sure if any other environments were affected.

[risk=no] regenerate hashCode/equals for DbCdrVersion

---

api/src/main/java/org/pmiops/workbench/institution/InstitutionUserInstructionsMapper.java
api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java

Backfill / migration should not be necessary, admins can just re-save as needed.

[RW-6107][risk=low] Escape user instructions on render, use alternate escaping library

---

api/db-cdr/generate-cdr/bq-schemas/prep_clinical_terms_nc.json
api/db-cdr/generate-cdr/bq-schemas/prep_criteria.json
api/db-cdr/generate-cdr/bq-schemas/prep_criteria_ancestor.json
api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
api/libproject/devstart.rb

This PR adds validation and load functionality for the CB prep tables used by the CDR indices build. The following has been added when running `circle-build-cdr-indices` command:
1. Create prep_criteria, prep_criteria_ancestor and prep_clinical_terms_nc from csv files
2. Create backups gzip files from prep tables prior to  step 1 and put them in gs://all-of-us-workbench-private-cloudsql/R20XXQXRX/cdr_csv_files/backup
3. Purge old versions of the csv files.

[RW-6441][risk=no] Generate prep tables for csv files

---

api/db/changelog/db.changelog-157-add-user-access-tier.xml
api/db/changelog/db.changelog-master.xml
api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/main/java/org/pmiops/workbench/access/AccessTierService.java
api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/dao/AccessTierDao.java
api/src/main/java/org/pmiops/workbench/db/dao/UserAccessTierDao.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
api/src/main/java/org/pmiops/workbench/db/model/DbUserAccessTier.java
api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapper.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/access/AccessTierServiceTest.java
api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserAccessTierDaoTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
api/src/test/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapperTest.java
api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java

Description:
Another step in the migration from using dataAccessLevel to check access to querying a new table user_access_tier / DbUserAccessTier for ENABLED status.
Several parts of RW-6187 are complete and deployed to Production: Workspace and CDR Version entities have been transitioned to this model, and we are now Reporting tier membership (in addition to DataAccessLevel).
This PR involves creating and updating DbUserAccessTier whenever we also set a user's DataAccessLevel in UserServiceImpl.  It does not remove any DataAccessLevel setting or change any access checks to use DbUserAccessTier.  My thought is that we should deploy this parallel source of truth and leave it in this state for one release cycle while confirming that everything looks correct.  After the next release, we can …

[risk=low][RW-6187] Populate a new DbUserAccessTier whenever Registration status is updated

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml

Follow-up to https://github.com/all-of-us/workbench/pull/4623

[risk=no] rm deprecated requireInviteKey flag (2/2)

---

api/build.gradle

Forgot about this option. From ssh'ing in, I observed that the actual -Xmx value was 1g. Then found this setting in the docs and in our gradle config.
Try 2G for now. Follow-up: the -Xmx3g in circle may be doing nothing. Will remove or update comments there accordingly.

[RW-6460][risk=no] Bump test heap override in gradle

---

api/src/main/java/org/pmiops/workbench/cdr/dao/DSDataDictionaryDao.java
api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/cdr/dao/DSDataDictionaryDaoTest.java

The call to retrieve data dictionary is failing in case of multiple entries in DB for same field_name and domain eg
Person id has 2 entries with same domain 1 referring to the omop table person, the other to ds_person. 
As of now getting the first entry will solve the issue,  however this is a temporary solution, and it would be better to use the relevant_omop_mapping as well to get the data dictionary.
---

[RW-6153][risk=no]  Update existing services that read from data_dictionary entry (Data Dictionary)

---

ui/src/app/pages/workspace/workspace-about.tsx

Description:
I missed renaming the info popup in #4635 from Data Access Level to Data Access Tier.
---

[risk=no][RW-6187] Rename Workspace About info section

---

api/src/main/java/org/pmiops/workbench/cdr/dao/DSDataDictionaryDao.java
api/src/main/java/org/pmiops/workbench/cdr/model/DbDSDataDictionary.java
api/src/test/java/org/pmiops/workbench/cdr/dao/DSDataDictionaryDaoTest.java
api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java

Update query to pick just one entry (referring to the correct omop table rather than ds_) from ds_Data_dictionary. 
---

[noTicket][risk=nO]Update existing services that read from data_dictionary entry (Data Dictionary) 

---

api/libproject/devstart.rb

Description:
I don't know what the variable is/was or why it was there.  So I'll hold off on merging until there's some context.
---

[risk=low] rm missing variable from docker-clean

---

e2e/app/element/select.ts

Found a bug during testing in staging env. `getSelectedValue` function should returns displayed texts instead of attribute `value`.

[no ticket][risk=no] Puppeteer fix getSelectedValue func

---

api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
api/libproject/devstart.rb

This is a new intermediate command that will build all the prep tables in a specified `project:dataset`. This command will only create prep tables, the backup commands are ignored(backups are only run in full CDR indices build).
Example run: 
`./project.rb make-prep-tables-from-csv --bq-project all-of-us-workbench-test --bq-dataset test_R2019q4r3`
This will produce:
1. `all-of-us-workbench-test:test_R2019q4r3.prep_criteria`
2. `all-of-us-workbench-test:test_R2019q4r3.prep_criteria_ancestor`
3. `all-of-us-workbench-test:test_R2019q4r3.prep_clinical_terms_nc`
4. `all-of-us-workbench-test:test_R2019q4r3.prep_concept`
5. `all-of-us-workbench-test:test_R2019q4r3.prep_concept_relationship`

[no ticket][risk=no] adding new command to build prep tables from csv files

---

ui/src/app/pages/login/login.tsx

Old anchor was removed. This is the new direct link to the FAQ details.

[RW-6535][risk=no] Update stale FAQ link for "trouble signing in?"

---

api/db-cdr/generate-cdr/bq-schemas/cb_cdr_date.json
api/db-cdr/generate-cdr/generate-private-cdr-counts.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
api/libproject/devstart.rb

This PR adds the following:
1. Removing cdr-date and bucket parameters
2. Creation of cb_cdr_dates table to hold the cutoff date for each CDR
Example command:
./project.rb circle-build-cdr-indices --project all-of-us-ehr-dev --bq-dataset test_R2019q4r3 --wgv-dataset 1kg_wgs --cdr-version synth_r_2019q4_14

[RW-6442][risk=no] removing cdr-date and bucket parameters and adding new table

---

api/src/main/java/org/pmiops/workbench/api/UserController.java
api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java

Description:
Part of RW-6190.  Use the DbAccessTier's Auth Domain Name instead of WorkbenchConfig.
One use of `registeredDomainName` will exist after this change, which will require a little bit of thought beyond this quick one-off PR.  See the notes in RW-6190 for details.
---

[risk=low] [RW-6190] rm penultimate use of WorkbenchConfig.firecloud.registeredDomainName

---

e2e/package.json
e2e/tests/nightly/dataproc-to-gce.spec.ts
e2e/tests/nightly/gce-to-dataproc.spec.ts
e2e/utils/waits-utils.ts

CircleCi [failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/8878/workflows/8007c2e1-e329-40c1-a8e5-1e467862f23c/jobs/129727).
Failure were caused by waiting for the runtime status spinner to stop in this [call](https://github.com/all-of-us/workbench/blob/283b78a4e82e3e12fa558a95be4eabcad4c722ea/e2e/app/page/notebook-page.ts#L255). The fix is to exclude runtime status spinner while for page to load.
ran on localhost:

[no ticket][risk=no] Puppeteer fix nightly tests

---

api/db/changelog/db.changelog-159-delete-data-dictionary-entry-table.xml
api/db/changelog/db.changelog-160-delete-data-dictionary-entry-table.xml
api/db/changelog/db.changelog-master.xml

workbench.data_dictionary_entry table is no longer being used to get dictionary information, this information is now being saved in cloud table.
---

[RW-6156][risk=no]  Delete the old data_dictionary_entry table in workbenchdb (Data Dictionary)

---

e2e/tests/user/login.spec.ts

Puppeteer automated tests cannot workaround Google login Captcha. Removing one login test because sometimes it encounters the Captcha page.

[no ticket][risk=no] Puppeteer remove password login test

---

api/libproject/devstart.rb

Increase GAE CPU and memory in staging to run Puppeteer e2e tests. Same GAE settings as in test env.
GAE [instance_class](https://cloud.google.com/appengine/docs/standard#second-gen-runtimes) setting.

[no ticket][risk=no] Run Puppeteer tests in staging

---

api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java

This is a long standing issue that we don't capture runtime errors when we see them - typically by the time we go to debug these issues, the runtimes have been automatically deleted. Log this in the server logs so we have some record of what happened.
This should make e2e test debugging easier as well.

[risk=no] Log runtime error messages when we observe the error status

---

api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java

Description:
It's not enough to simply JOIN on user_access_tier.  You must also check that it is ENABLED.
Added regression tests for the 3 queries which all fail on the previous versions.
---

[risk=low][no ticket] Check whether the user_access_tier mapping is ENABLED in native queries

---

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
api/db-cdr/generate-cdr/make-bq-denormalized-review.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
api/db-cdr/generate-cdr/validate-prerequisites-exist.sh

This PR contains
1. Removal of bq show checks in individual scripts of CDR indices
2. Adds check that all dependent OMOP tables exist in the validation script.

RW-6550 adding check for dependent OMOP tables

---

ui/src/app/components/help-sidebar.tsx
ui/src/app/components/help-tips.tsx

Description:
This simplifies the humungo help-sidebar component a bit and also makes it much easier to do my upcoming task where the workspace storage icon AND the help tips icon can be accessible at the same time. The current implementation makes this hard since it assumes an either or arrangement.
---

[risk=no][no ticket] Refactor HelpTips component out of Help sidebar

---

api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java

Description:
It is also used in https://github.com/all-of-us/workbench/blob/master/api/src/main/java/org/pmiops/workbench/api/RuntimeController.java#L119 but that is already replaced by https://github.com/all-of-us/workbench/pull/4795, and that endpoint will be deleted after next release
---

[RW-6559][risk=low] Migrate to googleProject for listRuntimesByProjectAsService

---

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java

Description:
Now that we're populating accessTierShortNames, we can stop populating the dataAccessLevel field in User Reporting.
Jonathan and Francis in Reporting know that this change is coming.
---

[risk=no][RW-6187] stop populating dataAccessLevel in user reporting

---

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java

Description:
We can do better than this ... but I've been unable to whip something up quickly.  This will unblock the reporting team while we think of something better.
---

[risk=low][RW-6566] Stopgap solution to resume populating first_registration_completion_time

---

api/libproject/devstart.rb

revert commit [4792](https://github.com/all-of-us/workbench/pull/4792) because it doesn't with improving Puppeteer testing in Staging env.

[no ticket][risk=no] revert commit #4792

---

api/docker-compose.yaml
api/libproject/devstart.rb

Description:
Setting this up so I can use Datagrip
---

[risk=low][no ticket] Expose db port during connect-to-cloud-db to allow usage of other SQL tools

---

ui/src/app/app-routing.tsx
ui/src/app/components/side-nav.spec.tsx
ui/src/app/components/side-nav.tsx
ui/src/app/guards/registration-guard.service.ts
ui/src/app/pages/admin/admin-user.tsx
ui/src/app/pages/homepage/homepage.spec.tsx
ui/src/app/pages/homepage/homepage.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/app/pages/signed-in/component.ts
ui/src/app/utils/access-tiers.tsx
ui/src/app/utils/index.tsx
ui/src/testing/stubs/cdr-versions-api-stub.ts
ui/src/testing/stubs/profile-api-stub.ts
ui/src/testing/stubs/workspaces.tsx

Description:
UI counterpart to https://github.com/all-of-us/workbench/pull/4755
Final cleanup of dataAccessTierFields will be done in RW-6189.
TODO and out of scope: make tier-specific access and display determinations instead of always looking for Registered Tier access.
---

[risk=medium][RW-6187] Migrate UI registration checking to accessTierShortNames

---

api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java

Previous approach:
```
for u in users:
2fa = get_2fa_from_gsuite(u)
maybe_write_to_db(u, 2fa)
```
New approach:
```
2fa_map = get_all_2fa_from_gsuite()
for u in users:
maybe_write_to_db(u, 2fa_map[u])
```
Note: this approach still may result in many serial repeated writes to the DB in a worst case scenario. On average though, we expect to rarely need to make writes here - and eventually the cron should converge if this scenario were to arise.
Possible future work:
- Move the read/write/access level checks into a cloud scheduler task, partition into groups of users

[RW-6564][risk=low] Optimize bulkSyncTwoFactorAuth by using a batch gsuite lookup

---

api/config/config_perf.json
api/config/config_stable.json
api/config/config_staging.json

For Controlled Tier Alpha, turning on unsafeAllowAccessToAllTiersForRegisteredUsers will grant access to the Controlled Tier to all Registered Tier users.  DO NOT ENABLE THIS IN PROD.
Wait for approval before enabling in Preprod: https://precisionmedicineinitiative.atlassian.net/browse/RW-6592
---

[risk=no][RW-6585] enable unsafeAllowAccessToAllTiersForRegisteredUsers in Perf and Staging

---

ui/src/app/pages/workspace/workspace-card.tsx

Description:
Two different error modals were showing up when there was a deletion error. One linked to the next. Removed the extra modal.
I confirmed with Lou that this was not the intended UX.
I found this while working on the CT workspace changes
---

[no-ticket][risk=no] Remove extraneous modal

---

api/libproject/devstart.rb
api/src/main/webapp/WEB-INF/appengine-web.xml.template

Issue: Puppeteer tests fail randomly in staging with the default appengine settings in staging:
- Default is `min_idle_instances = 0, max_instances = 10, instance_class = 'F1'` [devstart.rb#L70](https://github.com/all-of-us/workbench/blob/25b429cfb3b1cad7d2363dee64bce03d3bfe9f8c/api/libproject/devstart.rb#L70)
Google Cloud Console error is `Request was aborted after waiting too long to attempt to service your request.`
Experimented with some different appengine settings, following two works (no Puppeteer tests failures):
- `(4, 10, 'F1')`
- `(0, 10, 'F2')`
Increasing number of idle instances or increasing class type to `F2` both works. 
Difference in cost per hour per usage between `F1` and `F2` class is $0.05. Idle `F1` instance costs per hour is $0.05. Having a higher number of idle …

[no ticket][risk=no] Enable Puppeteer testing in staging env

---

api/src/main/java/org/pmiops/workbench/db/dao/UserRecentWorkspaceDao.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java

Very rarely, we will get an "ObjectOptimisticLockingFailureException" while deleting a workspace. It's happened 5 times in test according to stackdriver.
It seems to be because of a concurrency bug that will arise if a UserRecentWorkspace is updated while a delete workspace operation is taking place. Specifically, if the UserRecentWorkspace is updated in between the find() and delete() calls in this function, https://github.com/all-of-us/workbench/blob/fc41e9cf8f685f84a1feb2e56a71d0482327a403/api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java#L429.
I was unable to reproduce it locally because I couldn't find a way to run Spring locally with multiple threads but I think we can fix it by just running the delete command and foregoing the find check.
The bug happens …

[risk=no][RW-6608] Fix rare concurrency bug between updateRecentWorkspace and deleteWorkspace

---

api/src/main/java/org/pmiops/workbench/db/dao/UserRecentWorkspaceDao.java
api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java

Description:
Running into concurrency issues while deleting all recent workspaces upon deleting a workspace. We can just opt to not delete them at all since RecentWorkspace was designed to handle that case.

[risk=no][RW-6608] Don't delete recent workspaces on delete workspace

---

e2e/app/element/select.ts
e2e/app/page/workspace-edit-page.ts
e2e/app/page/workspaces-page.ts
e2e/utils/waits-utils.ts

`waitForText` used for checking Billing Account selected value is not reliable. It failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/9155/workflows/b04bb6a3-87ea-489b-ac92-8153c0b5e825/jobs/131814).
Replace it with new `waitForSelectedValue()` in `select` class.

[no ticket][risk=no] Puppeteer rework fillOutRequiredCreationFields func

---

ui/src/app/pages/profile/profile-page.tsx

Description:
Looks like the `field.subfield` format of `valueKey` was not expected after the change here: https://github.com/all-of-us/workbench/pull/4733/files#r602457959
Institution display is restored for the Profile page.
---

[risk=no][RW-6603] correct valueKey parameter for institution in profile

---

api/src/main/resources/workbench-api.yaml

Noticed in follow-up local testing. Surprisingly swagger validation did not catch this.
I'm OOO tomorrow, feel free to merge if needed.

[risk=no] Fix "dataSetId" swagger casing

---

api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java
api/src/test/java/org/pmiops/workbench/opsgenie/EgressEventServiceTest.java

Alerts from an older alerting window should now show up as:
```
[>60 mins old] High-egress event ...
```
In the OpsGenie alert name and/or alert note. I've omitted short windows (<5m) from this labeling, because there will be some lag in the system between when OpsGenie is scheduled to run, and when we actually receive the event.

[RW-6532][risk=low] Label stale egress events as such

---

api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java
api/src/test/java/org/pmiops/workbench/opsgenie/EgressEventServiceTest.java

[RW-6532][risk=no] Correct egress alert window duration parsing to expect seconds

---

ui/src/app/cohort-search/cohort-page/cohort-page.component.spec.tsx
ui/src/app/cohort-search/list-search/list-search.component.tsx
ui/src/app/cohort-search/overview/overview.component.spec.tsx
ui/src/app/cohort-search/overview/overview.component.tsx
ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx
ui/src/app/components/copy-modal.spec.tsx
ui/src/app/components/copy-modal.tsx
ui/src/app/components/side-nav.spec.tsx
ui/src/app/pages/analysis/runtime-panel.spec.tsx
ui/src/app/pages/analysis/runtime-panel.tsx
ui/src/app/pages/data/data-set/dataset-page.spec.tsx
ui/src/app/pages/data/data-set/dataset-page.tsx
ui/src/app/pages/homepage/homepage.spec.tsx
ui/src/app/pages/homepage/recent-resources.tsx
ui/src/app/pages/login/sign-in.tsx
ui/src/app/pages/profile/profile-page.spec.tsx
ui/src/app/pages/signed-in/component.ts
ui/src/app/pages/workspace/workspace-about.spec.tsx
ui/src/app/pages/workspace/workspace-about.tsx
ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx
ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts
ui/src/app/utils/cdr-versions.spec.tsx
ui/src/app/utils/cdr-versions.tsx
ui/src/app/utils/index.tsx
ui/src/app/utils/stores.tsx
ui/src/testing/stubs/cdr-versions-api-stub.ts

Description:
This does not meet the AC for RW-6300.  It's a necessary step to get there, however.
The original endpoint `getCdrVersions()` returns a `CdrVersionListResponse` with information about the Registered Tier CDR Versions.  A new endpoint `getCdrVersionsByTier()` returns a `CdrVersionTiersResponse` with information about the CDR Versions in all tiers (Registered and Controlled or just Registered, depending on environment).  This PR replaces the use of the former endpoint/entity in favor of the newer versions.  **No visual or behavior changes are expected.  If you find any, that's a bug.**  This PR also does not enable access to any Controlled Tier CDR Version - and one does exist in the Test and Local environments.  **If you are able to access any, that's a bug.**
Local manual …

[risk=low][RW-6300] transition from getCdrVersions() to getCdrVersionsByTier()

---

api/src/main/java/org/pmiops/workbench/access/AccessTierService.java
api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java

Description:
The final UI reference was removed in #4833 so we should wait until the 19 April release for deployment safety reasons.
---

[risk=no][RW-6189] Remove the final references to DataAccessLevel

---

api/config/config_perf.json
api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java

Description:
If an Access Tier is added to an environment's cdr_config.json without a corresponding config_json change to add the tier to the billing buffer capacity map, we hit an NPE preventing *all* billing project creation.
This change ensures that we don't NPE if we have a config mismatch.  I tested that a config mismatch in the other direction causes no problems.
TODO is there a better way to ensure config consistency here?  Maybe buffer capacity can live in the cdr_config?  Or maybe this is moot after Terra-PPW - we may not need a buffer then, depending on Terra performance.
---

[risk=low][no ticket] Don't NPE for this config mismatch.  Also, buffer some Perf CT projects.

---

ui/src/app/pages/homepage/recent-workspaces.tsx

Description:
Correct styling issue where scrollbars are always visible. 
Current:
Corrected:
With lots of workspaces:
With a few:
---

[no-ticket][risk=no] Correct scroll styling

---

ui/src/app/cohort-search/tree/tree.component.tsx

Description from ticket:
_When you select "visits" from add criteria and you are sending request to the API to get the list of visits, only send the domain and type which both = "VISIT". Remove parent_id = 0 as a query parameter_
---

[RW-6397][risk=no] CB UI - change request for visits

---

api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java

Description:
Since our access determination needs will become more complex in the near future (due to Annual Renewal and Controlled Tier Beta) I'd like to add some test cases.  As a first step, this PR moves existing tests into a new file.  There's no additional test code here.
---

[risk=no][no ticket] Move access determination tests to a separate test class

---

e2e/app/modal/old-cdr-version-modal.ts
e2e/app/page/workspace-edit-page.ts
e2e/tests/workspace/old-cdr-version-modal.spec.ts
ui/src/app/pages/workspace/workspace-edit.tsx

Description:
Fixes a bug introduced in #4844
---

[risk=no][no ticket] Set the CDR Version ID correctly when clicking cancel on the old-cdr-modal

---

e2e/app/component/workspace-card.ts
e2e/app/page/workspace-base.ts
e2e/app/page/workspace-edit-page.ts
e2e/tests/workspace/workspace-duplicate.spec.ts
e2e/utils/waits-utils.ts

When deleting a Workspace in "Your Workspaces" page, test can fail because the Workspace card can take a while to be removed in UI.

[no ticket][risk=no] Puppeteer workspace-duplicate flaky test fix

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json

Several base image updates, and genomics-specific tooling:
- Install gatk
- Install bolt-lmm
- Install regenie
- Install Nirvana (requires dot net)
- Install R packages: SAIGE, GENESIS
- Update Plink version
See https://github.com/DataBiosphere/terra-docker/pull/212

[RW-6313][risk=low] Bump Leo Jupyter image to latest

---

ui/yarn.lock

Description:
Security alert https://github.com/advisories/GHSA-c4w7-xm78-47vh
Dependabot attempted to fix it in #4761 but missed this one.
---

[risk=low][no ticket] bump vulnerable y18n 4.0.0 to 4.0.3

---

ui/src/app/pages/workspace/workspace-edit.spec.tsx

Issue 1:
- Followed some guidance from https://github.com/enzymejs/enzyme/issues/389
- HTML node manipulation seems to work in this particular case with the native `select` element, a bit gross, so we may want to extract this into a helper
Issue 2:
- prefer callbacks for the enzyme wrapper objects rather than local ref variables, if you're expecting updates during the lifespan of the test. Initial assertions failed on account of a stale component ref

Select fix with DOM node manipulation

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/ConfigController.java
api/src/main/java/org/pmiops/workbench/api/DataSetController.java
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
ui/src/app/components/help-sidebar.tsx
ui/src/app/components/render-resource-card.spec.tsx
ui/src/app/pages/data/data-page.spec.tsx
ui/src/app/pages/data/data-set/dataset-page.spec.tsx
ui/src/app/pages/data/data-set/dataset-page.tsx
ui/src/app/pages/data/data-set/dataset-resource-card.tsx

In the product, this has the following implications:
- Whether the prepackaged concept set appears on dataset builder
- Whether the extraction history panel is visible (still only shows on WGS CDRs) 
- Whether you can launch an extraction from the dataset card
Still allowed in WGS CDRs only, with this feature off:
- Selecting dataproc
- Filtering by WGS in cohort builder

[RW-6632][risk=no] Add genomics extract feature flag

---

api/config/cdr_config_local.json
api/config/cdr_config_perf.json
api/config/cdr_config_staging.json
api/config/cdr_config_test.json
api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
e2e/app/component/workspace-card.ts
e2e/app/page/workspace-edit-page.ts
e2e/tests/workspace/workspace-create.spec.ts
e2e/tests/workspace/workspace-duplicate.spec.ts
e2e/tests/workspace/workspace-edit.spec.ts
ui/src/app/pages/profile/data-access-panel.tsx
ui/src/app/pages/workspace/workspace-edit-text.tsx
ui/src/app/pages/workspace/workspace-edit.spec.tsx
ui/src/app/pages/workspace/workspace-edit.tsx
ui/src/app/pages/workspace/workspace-nav-bar.tsx
ui/src/app/utils/access-tiers.tsx
ui/src/app/utils/cdr-versions.spec.tsx
ui/src/app/utils/cdr-versions.tsx
ui/src/testing/react-test-helpers.ts
ui/src/testing/stubs/cdr-versions-api-stub.ts

Description:
Add an Access Tier dropdown to the Workspace Create page for environments with multiple tiers.
Workspace Edit and Duplicate: show dropdown but disable - tier changes are not possible.
Duplication of a CT Workspace - note that tier changing is not possible, and the "Old CDR Version" modal and the CDR Version upgrade text appear appropriately.
Prod will not have multiple tiers at this time, so the CdrVersionTiersResponse will not contain multiple tiers.  Therefore the tier choice dropdown will not appear (tested locally by hacking the local CdrVersionTiersResponse):
Update tooltip location to match mocks
Before
After
---

[risk=moderate][RW-6300] Access Tier dropdown for Create Workspace

---

api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java

Description:
API only - we should continue to work on a UI solution for RW-6688.
Tested locally - no visible effect on the UI but the API error message is better.  Copying notebooks between CDR Versions still works as long as they're in the same tier.
---

[risk=low][RW-6688] Prevent notebook copy between tiers in the API

---

e2e/jest.test-setup.ts

Could fail test if failed request did not have any response body.
```
test name: Loading registration workflow
status: failed
failure: [
"TypeError: Cannot read property 'status' of null\n" +
'    at logError (/home/circleci/workbench/e2e/jest.test-setup.ts:235:14)\n' +
'    at /home/circleci/workbench/e2e/jest.test-setup.ts:48:7'
]
```
After fix:
(test no longer fails when response is null caused by aborted request)
```
console.log
ERROR: [4/30/2021, 19:02:20] - Request failed:  POST https://api-dot-all-of-us-workbench-test.appspot.com/v1/institutions/Broad/checkEmail
net::ERR_ABORTED
at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)
```

[no ticket][risk=no] Puppeteer log: null response handling

---

.codacy.yml
e2e/resources/python-code/count-disk-space.py
e2e/resources/python-code/count-memory.py
e2e/tests/nightly/gce-to-dataproc.spec.ts

Default disk size has changed. Checking the volume more directly maps to the disk size we're configuring in the runtime panel. Previous error was:
```
Updating runtime compute type Switch from GCE to dataproc - tests/nightly/gce-to-dataproc.spec.ts
Error: expect(received).toBeLessThanOrEqual(expected)
Expected: <= 55000000000
Received:    63344238592
```
Previous code checked the overlay size, which I think more directly maps to a default boot disk size that Leo controls - while the notebooks volume corresponds to our requested disk size.
```
-h
!df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G   16G   41G  28% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/sda1        59G   16G   41G  28% /etc/hosts
shm …
```

[risk=no] Update nightly disk size tests

---

e2e/jest.test-setup.ts
e2e/libs/jest-reporter.js

Because two tests running in parallel caused log name mix-up. 
Ex: Failed test log should be for `conceptset-edit-rename.spec`.
`sidenav.spec` started at 16:36:50. It passed.
`conceptset-edit-rename.spec` started at 16:35:25. It failed.
Issue fixed:

[no ticket][risk=no] Puppeteer failed test log name fix

---

.circleci/config.yml
api/docs/developer-system-initialization.md
api/genomics/wdl/RandomizeVcf/Dockerfile
deploy/bootstrap-docker.sh

Description:
Deploy failed with this error:
```
+ docker-compose build deploy
deploy uses an image, skipping
+ docker-compose run --rm -e WORKBENCH_VERSION=v6-20-rc1 -v /tmp/deploy@all-of-us-rw-stable.iam.gserviceaccount.com-key20210504-29182-1w64xf4.json:/creds/sa-key.json deploy deploy/project.rb deploy --account deploy@all-of-us-rw-stable.iam.gserviceaccount.com --project all-of-us-rw-stable --promote --app-version v6-20-rc1 --git-version v6-20-rc1 --key-file /creds/sa-key.json
Creating deploy_deploy_run ... done
M       aou-utils
HEAD is now at 4194affdc syncing CDR verisons (#4925)
error: The following untracked working tree files would be overwritten by checkout:
utils/.sample-project.rb
utils/.sample-project.yaml
utils/LICENSE
utils/README.md
utils/common.rb
utils/completion.bash …
```

[risk=low][no ticket] Force submodule updates due to a recent incompatible change

---

e2e/package.json
e2e/tests/nightly/dataproc-to-gce.spec.ts
e2e/tests/nightly/gce-to-dataproc.spec.ts

Removing disk size check because it's problematic.
nightly tests verified and passed on localhost:

[no ticket][risk=no] Puppeteer remove disk size check in gce-to-dataproc.spec

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java

Looks like this was lost when we last [upgraded pandas](https://github.com/pandas-dev/pandas/blob/v1.2.4/pandas/io/gbq.py#L134-L155), the default value is no longer contextually inferred.

[risk=no] Include progress bar type in pandas GBQ codegen

---

api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
ui/src/app/components/copy-modal.spec.tsx
ui/src/app/components/copy-modal.tsx
ui/src/app/pages/analysis/notebook-resource-card.tsx
ui/src/app/pages/data/concept/concept-search.tsx
ui/src/app/pages/data/concept/concept-set-resource-card.tsx
ui/src/app/utils/resources.tsx
ui/src/testing/stubs/resources-stub.ts

Description:
UI counterpart to #4908 (but not dependent on it)
Update the Copy Modal logic to prevent copies across access tiers.  Keep the existing logic of allowing Notebook copies across CDR Versions within an access tier and preventing Concept Set copies across CDR Versions.
---

[risk=low][RW-6688] Prevent notebook copy between tiers in the UI

---

api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/resources/workbench-api.yaml

Description:
This adds expiration information for compliance training and the data use agreement.
Response to /v1/profile is hardcoded as "All modules will never expire and are not currently expired":
```
{
...
renewableAccessModules: {
modules: [
{
moduleName: 'complianceTraining',
expirationEpochMillis: null,
hasExpired: false
},
{
moduleName: 'dataUseAgreement',
expirationEpochMillis: null,
hasExpired: false
}
],
anyModuleHasExpired: false
}
}
```
---

[RW-6667][risk=no] API changes to support access module expiration and renewal

---

ui/src/app/pages/workspace/workspace-about.tsx

The height was restricting the background color in case the cdr version was too long. Removing that solved the problem 
Before
After
---

[RW-6687][risk=no]  [P2] Dataset name (CDR Version) overflows its box in the Workspace About sidebar

---

api/db/changelog/db.changelog-162-add-user-profile-publications-confirmed-times.xml
api/db/changelog/db.changelog-master.xml
api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java

Description:
Add the fields `profileLastConfirmedTime` and `publicationsLastConfirmedTime` to DbUser and populate these values from users' first_enabled time in their registered tier memberships.
Add a `POST v1/confirmProfile` endpoint for users to update their `profileLastConfirmedTime` values.
Also remove some unused code.
Testing was by DB and API interaction.
First, confirm that the DB fields are backfilled appropriately for users in the Registered Tier and not set for users who have never had Registered Tier access:
```
mysql> select * from user_access_tier where access_tier_id = 1;
+---------------------+---------+----------------+---------------+---------------------+---------------------+
| user_access_tier_id | user_id | access_tier_id | access_status | first_enabled       | …
```

[risk=low][RW-6704][RW-6628] Add access renewal module fields and confirmProfile endpoint

---

ui/src/app/styles/datatable.ts

Fixes issue where the scrollbar from the participant detail table is visible from behind the annotations sidebar.
Before:
https://user-images.githubusercontent.com/40036095/118070875-58a54c80-b36c-11eb-9873-a25b0e877490.mov
After:
https://user-images.githubusercontent.com/40036095/118070904-61961e00-b36c-11eb-9661-068f47aa3b9d.mov

[risk=no] Fix scrollbar display in cohort review table

---

ui/src/app/pages/data/cohort-review/query-report.component.tsx

- Update how we get the CDR name for the Query Report page to support Controlled Tier CDRs
- Use `cdrVersionStore` instead of calling the api since it has the same data
---

[RW-6553][risk=no] Update query report page to support Controlled Tier

---

api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionMapper.java
api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java

Now failed workflows should count as failed on our end too even though there's no 'failed' submission status.
---

[RW-6546][risk=no] Handle FAILED workflow status for cromwell submission

---

api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java

Description:
This is only part 1 or RW-5492 (the easy part)
Confirmed that no PENDING_DELETION_POST_1PPW_MIGRATION Workspaces exist in any environment: `select * from workspace where active_status = 2;` is empty in all
---

[risk=no][RW-5492] rm obsolete PENDING_DELETION_POST_1PPW_MIGRATION

---

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java

- Leverage `@UpdateTimestamp` for automatic timestamp updates via Hibernate, which resolves an issue with excessive updates to `lastModifiedTime` (i.e. on every cron run).
- Switch to `@CreationTimestamp` for consistency, this way these columns have an identical value on initial insertion
These annotations only have an effect if you make a change which would modify the database row. A no-op `save()` does not change the lastModified time, which is exactly the desired behavior for offline cronjobs etc. This should reduce RDR export user selection to expected levels, since it looks at `lastModifiedTime` to determine whether to send data.
Tested by locally triggering crons, profile updates, user create and observing the expected `last_modified_time` in the database.
Filed …

[RW-6692][risk=low] Eliminate spurious changes to user.lastModifiedTime

---

ui/src/app/pages/app/component.spec.ts
ui/src/app/pages/signed-in/component.spec.ts

Description:
This test has been failing about 1/2 of the time recently.  The reason is unknown but it could be due to the packages upgraded recently.  I haven't observed any problems with the app itself.
---

[risk=low][no ticket] Disable flaky Angular test

---

api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java

I tried to make this as concise as possible and would appreciate pointers. Unit tests are a big lift, so added RW-6750 to cover them.
I judge risk to be low because getting the logic wrong could cause someone to stay registered longer than they should be. Avoiding this should be covered by existing tests, but I haven't checked.
---

[RW-6725][risk=low] Real access renewal status in profile response

---

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
api/src/main/java/org/pmiops/workbench/dataset/mapper/DataSetMapper.java
api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java

- Avoid mocking the dao layer. I don't see an advantage to doing this.
- Move to correct package
- Eliminate testing of method with test-only visibility (getDbDatSets)
- Autowire test service, rather than manually constructing

[risk=no] Refactor dataset service tests

---

ui/src/app/app-routing.module.ts
ui/src/app/app-routing.tsx
ui/src/app/components/side-nav.spec.tsx
ui/src/app/components/side-nav.tsx
ui/src/app/pages/profile/profile-page.tsx
ui/src/app/utils/stores.tsx

Description:
This change will allow signed in users to access their profile regardless of whether they are in an access tier.
This is critical to allowing users to regain access if their account expires
Profile access before change
Profile access after change
---

[RW-6738][risk=no] Allow users to navigate to profile when signed in

---

ui/src/app/pages/data/concept/concept-search.tsx

Before:
Concept List page: 
Concept Home page:
After:
I felt Rename is a better name for option than Edit option for Concept Homepage, so the new page options:
This still does the same thing, let user change Concept Set name and description
---

[RW-6144][risk=no]  Ellipsis menu on concept-set page vs concept-set card

---

api/src/main/java/org/pmiops/workbench/rdr/RdrExportConfig.java
api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

This is spamming the logs and putting potentially sensitive information into our GAE logs.

[risk=no] Stop debug logging all outgoing RDR requests

---

api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
api/src/main/java/org/pmiops/workbench/rdr/RdrExportService.java
api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

Three changes here:
1. Bug fix: When we're **not** backfilling, update the RDR export table.
2. ~~Behavior change: When we are backfilling, update the RDR export table. I don't see why we wouldn't - asked for clarification here: https://github.com/all-of-us/workbench/pull/4674/files#r591814610~~
3. Java style change: Switch to my original preference of using the primitive boolean here. I believe this was a contributing factor to the original bug - use of a nullable boxed boolean type made the predicate in the service less readable and handling this in the controller is a better separation of concerns.
4. Wire change: always send an explicit backfill value to the RDR (true/false), no longer send `null` to imply default / `false`

[RW-6778][risk=no] Fix tracking of workspace RDR exports

---

e2e/app/element/base-element.ts
e2e/app/modal/share-modal.ts
e2e/app/page/workspace-about-page.ts
e2e/tests/datasets/dataset-create.spec.ts
e2e/tests/datasets/dataset-snowman-menu-actions.spec.ts
e2e/tests/datasets/export-to-notebook.spec.ts
e2e/tests/workspace/workspace-share-modal.spec.ts

`workspace-share-modal.spec` has failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/10494/workflows/7edb403d-69aa-4393-b504-006c715a576f/jobs/141162).
`dataset-snowman-menu-actions.spec.ts` has failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/10498/workflows/866a4093-cf0b-4cf9-afff-a29489080fcf/jobs/141189).
Adding two whitespaces at the end of the user name has caused share-modal test to fail on master branch. The fix drops the whitespace and search for dropdown as puppeteer is typing char by char instead of type all char then search for dropdown.

[no ticket][risk=no] Puppeteer flaky tests fix

---

e2e/app/modal/conceptset-save-modal.ts
e2e/app/page/cohort-build-page.ts
e2e/resources/data/user-registration-data.ts
e2e/utils/faker-utils.ts
e2e/utils/str-utils.ts

Fix eslint warnings caused by faker.
Before change (382 warnings):
After change (325 warnings):

[no ticket][risk=no] Puppeteer fix faker eslint warnings

---

e2e/jest.config.js

The terminal/JSON output of puppeteer is hard to look at when running locally. The HTML report is friendlier way to view the failures and stack traces.

[risk=no][ticket=no] Enable HTML report of puppeteer results

---

api/config/config_preprod.json

For now, we just want to turn this on for limited testing periods, so demo project users don't accidentally misuse it before the feature is complete.

[RW-6782][risk=no] Revert extraction flag in preprod

---

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java

Description:
When a user updates their profile, we want this to count as a "profile confirmation" for the purposes of annual renewal.  This adds a confirmProfile() call to **ProfileController**.updateProfile(), which is the endpoint called by the UI for user-directed profile updates.
Note that **ProfileService**.updateProfile() is used more generally, for both admin- and user-directed updates, so is not appropriate for this task. 
---

[risk=low][no ticket] ProfileController.updateProfile() confirms the profile

---

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
ui/src/app/cohort-search/demographics/demographics.component.tsx
ui/src/app/cohort-search/list-search/list-search.component.tsx
ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
ui/src/app/cohort-search/overview/overview.component.tsx
ui/src/app/cohort-search/search-bar/search-bar.component.tsx
ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
ui/src/app/cohort-search/search-group/search-group.component.tsx
ui/src/app/cohort-search/tree-node/tree-node.component.tsx
ui/src/app/cohort-search/tree/tree.component.tsx
ui/src/app/pages/data/cohort-review/cohort-review.tsx
ui/src/app/pages/data/cohort-review/query-report.component.tsx
ui/src/app/pages/data/cohort-review/table-page.tsx
ui/src/app/pages/data/concept/concept-homepage.tsx

Replacing cdrVersionId with workspaceNamespace and workspace Id information.
---

[RW-6705][risk=medium] API - change all CB API calls to use workspaceNamespace/workspaceId instead of cdrVersionId

---

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java

Description:
Not in support of a specific AAR ticket.  Add AAR checks for confirmProfile and confirmPublications.
Also attempt to comprehensively test the many ways a user can lose access to the Registered Tier.  Little of the previous version of the test file has survived, so it's probably easier to review the whole file rather than attempting to make sense of the diff.
---

[risk=medium][no ticket] Add AAR access checks and tests

---

e2e/.eslintignore
e2e/tsconfig.json

The `yarn build` command failed with eslint errors in the latest master branch.

[no ticket][risk=no] e2e eslint ignore logs dir

---

ui/yarn.lock

Description:
Dependabot says [we need version 5.2.2+](https://github.com/all-of-us/workbench/security/dependabot/ui/yarn.lock/dns-packet/closed) but the maintainer [has also patched version 1.3.4](https://github.com/mafintosh/multicast-dns/issues/75). 
---

[risk=low][no ticket] Upgrade vulnerable dns-packet

---

ui/src/app/components/data-set-reference-modal.tsx

Fix the display of the resource name so it appears as the user entered it.
---

[RW-6759][risk=no] Fix resource name in dataset reference warning modal

---

ui/src/app/pages/access/access-renewal-page.spec.tsx
ui/src/app/pages/access/access-renewal-page.tsx

Description:
One of the "polish" steps in RW-6631: ` Completion banner not showing when user has a bypassed module`
---

[risk=low][RW-6631] Show AAR completion text when modules are bypassed

---

api/config/config_local.json
api/config/config_perf.json
api/config/config_preprod.json
api/config/config_prod.json
api/config/config_stable.json
api/config/config_staging.json
api/config/config_test.json
api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java

Description:
`enableRdrExport` and `enableReportingUploadCron` have no remaining code references, so this is strictly a cleanup.
Perf had `"enableReportingUploadCron": false` but this was not actually respected.
---

[risk=no][no ticket] Remove a few obsolete Feature Flags

---

api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
api/src/main/java/org/pmiops/workbench/mail/MailService.java
api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
api/src/main/resources/workbench-api.yaml
api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java

Description:
Implement the logic of RW-6703 but not the emails, since we will not be immediately enabling emails on AAR launch.  Instead, log whether emailing would have happened, to build confidence in real environments.
---

[risk=low][RW-6703] Access expiration email infrastructure
