.github/PULL_REQUEST_TEMPLATE.md
=> [risk=no] Fix local e2e note in pull request template

e2e/app/page/data-page.ts
Add wait to check for spinner.
Failed CircleCI job: https://app.circleci.com/pipelines/github/all-of-us/workbench/2439/workflows/976c136e-2b7b-4f88-bf97-f5751dcc6f2b/jobs/90643
=> [no ticket][risk=no] Puppeteer flaky test fix: add a wait

api/config/featured_workspaces_prod.json
=> [risk=low][RW-5292] Replace an old Featured workspace with a new version

ui/src/app/components/cookie-banner.tsx
=> [RW-5297][risk=no] Fix z index of cookie banner

api/src/main/java/org/pmiops/workbench/api/OfflineReportingController.java, api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingMapper.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java, api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/reporting/ReportingServiceTest.java
Initial classes and services for reporting. Highlights:
* A ReportingService class responsible for gathering the information and building a payload for BigQuery
* Value classes (generated for convenience in Swagger) for the columns we need. Currently just researcher adn workspce tables (2-3 columns each)
* a method to capture a timestamp to use as a partition key (potentially)
* endpoint for kicking off the upload, to serve as cron target
* unit test class
---
=> [RW-5264, RW-5266][risk=no] Reporting PoC payload objects and service

ui/src/app/pages/workspace/workspace-edit.spec.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
=> [risk=no][RW-5132] Disable multiple clicks of Confirm for Create/Edit Workspace

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in snomed standard condition criteria
=> [RW-5290][risk=no] adding in snomed standard condition criteria

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Blocked on: production release of https://github.com/all-of-us/workbench/pull/2920
=> [RW-4319][risk=no] rm sendFreeTierAlertEmails feature flag (2/2)

api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, e2e/app/page/cohort-criteria-modal.ts
turning on age, age at consent and age at cdr flag for age slider
=> [RW-4608][risk=no] turning on age, age at consent and age at cdr flag for age slider

ui/src/app/app-routing.module.ts
Determined it is probably not worth additional effort to come up with a more clever/complex solution here.
=> [RW-5302][risk=no] Enshrine hardcoding of public React routes

ui/src/app/components/admin/audit-page-component.tsx, ui/src/app/components/app-router.tsx, ui/src/app/utils/index.tsx
=> [risk=no][RW-5342] Add useNavigation hook

api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
removing checks for old synth cdr
=> [RW-3291][risk=no] removing checks for old synth cdr

api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
updating dao/test cases to include sex at birth
=> [RW-5321][risk=no] updating dao to include sex at birth

api/src/main/java/org/pmiops/workbench/profile/ProfileService.java, api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
A user can have multiple TOS signature records, and we need to choose the most recent one. This fixes a map insertion error.
---
=> [RW-3389][risk=no] fix map value uniqueness

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
Reverts all-of-us/workbench#3839
=> [RW-5361][risk=no]Revert "Bump aou Leo image to 1.0.4"

api/genomics/README.md, api/genomics/build.gradle, api/genomics/src/main/java/org/pmiops/workbench/genomics/CombineGenotypingArrayVcfsEntryPoint.java, api/genomics/src/main/java/org/pmiops/workbench/genomics/RandomizeVcf.java, api/genomics/src/test/java/org/pmiops/workbench/genomics/RandomizeVcfTest.java, api/libproject/devstart.rb
Usage:
```
./project.rb randomize-vcf --vcf [vcf location] --number-of-copies [number] --output-path [output path]
```
=> [no ticket][risk=no] Make randomize fast

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in LOINC measurement (vitals/labs) criteria
=> [RW-5291][risk=no] adding in LOINC measurement (vitals/labs) criteria

ui/src/app/components/admin/audit-card-list-view.tsx
One more style fix from @petesantos 
---
=> [no ticket][risk=no] use fp.set() to simplify clone & adjust

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx, ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/modal/modal.component.tsx, ui/src/app/cohort-search/modifier-page/modifier-page-modal.component.spec.tsx, ui/src/app/cohort-search/modifier-page/modifier-page-modal.component.tsx, ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx, ui/src/app/cohort-search/selection-list/selection-list.component.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/utils/index.tsx, ui/src/app/utils/navigation.tsx
=> [RW-4594][risk=low] UI: add modifiers slideout (phase 1)

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in SNOMED measurement criteria, fixing LOINC Lab counts, removing view logic for condition source/standard SNOMED criteria
=> [RW-5307][risk=no] adding in SNOMED measurement criteria

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx, ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx, ui/src/app/cohort-search/selection-list/selection-list.component.tsx, ui/src/app/cohort-search/tree-node/tree-node.component.spec.tsx, ui/src/app/cohort-search/tree-node/tree-node.component.tsx, ui/src/app/cohort-search/tree/tree.component.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/utils/navigation.tsx
- Style updates for hierarchy view for V2 UI
- Add store for opening/closing sidebar from other components, use for 'Finish & Review' button
- Move `AttributesPageV2` component to `SelectionList`
- Add shared function `saveCriteria` for adding current criteria selections to cohort
---
=> [RW-5114][risk=no] Update hierarchy page 

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml, ui/src/app/cohort-search/demographics/demographics.component.spec.tsx, ui/src/app/cohort-search/demographics/demographics.component.tsx, ui/src/testing/default-server-config.ts
This PR removes the enableCBAgeTypeOptions flag from
- config files
- ConfigController
- WorkbenchConfig
- workbench-api.yaml
- all UI components
=> [RW-4609][risk=no] removing enableCBAgeTypeOptions flag

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in ATC/RXNORM drug criteria
=> [RW-5308][risk=no] adding in ATC/RXNORM drug criteria

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in SNOMED source/standard procedure criteria
=> [RW-5391][risk=no] adding in SNOMED source/standard procedure criteria

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
** This change has been added to the new CB UI  behind the `enableCohortBuilderV2` flag
---
=> [RW-5318][risk=no] Add total results count to CB list search

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding in other concepts not already captured, created other cb tables, fixed counts
=> [RW-5400][risk=no] adding in other concepts not already captured

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding full text info column and synonym data
=> [RW-5401][risk=no] adding full text info column and synonym data

ui/src/app/app-routing.tsx
Description:
The featured workspace route was not working correctly - this change resolves the issue.
---
- [ X] This PR meets the Acceptance Criteria in the JIRA story
=> [risk=no][RW-5441]Correct featured workspace routing issue

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
=> [RW-3576][risk=no] UI: freeze the table header

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/components/app-router.tsx
Description:
1. Added the featured workspaces back in to the react based router
2. Fix the way `ProtectedRoutes` handles child routes and guards. Guards were being applied at a higher level in the component hierarchy causing issues like unintended redirects and routes not getting hit if they were not in the "right" location in the routing component. Guards are now applied at the individual "route level" component rather than at the parent. Only if the route matches and its render function is hit will a guard be checked. At that point if the guard fails it will redirect the user.
3. The issue with "next sibling" components of the protected route has been addressed by removing the react-router `Switch` component. When no path is provided to a child of a `Switch` it will match any path. …
=> [risk=no][RW-5446] Correct issues with ProtectedRoutes routing component

ui/src/app/app-routing.module.ts
Description:
Correct workspace audit route
---
=> [risk=no][RW-5459]Update workspace audit route

api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, e2e/tests/cohorts/cohorts-review.spec.ts, ui/src/app/pages/data/cohort-review/table-page.tsx, ui/src/app/services/review-state.service.ts
=> [RW-5357][risk=no] Add Sex at Birth column in Cohort Review

.circleci/config.yml
Add add new parameter: `parallel_num` in `puppeteer-e2e-test` job to control number of parallelism.
=> [no ticket][risk=no] Puppeteer circleci config change

ui/src/app/pages/admin/admin-user.tsx
=> [risk=no] rangeStep is exclusive: need to add one to max

e2e/app/page/workspaces-page.ts
=> [no ticket][risk=no] Fix e2e project compile error

e2e/app/element/base-element.ts, e2e/app/xpath-builders.ts, e2e/app/xpath-options.ts, e2e/utils/str-utils.ts, ui/src/app/components/rename-modal.tsx
=> [risk=no] A few Puppeteer updates

ui/src/app/app-routing.tsx
I had merged this change before seeing some PR feedback - corrected comment formatting.
---
=> [risk=no][no-ticket] Fix comment per missed feedback from PR 3936

e2e/app/page/profile-page.ts, e2e/tests/misc/sidenav.spec.ts, e2e/tests/profile/profile-page.spec.ts
=> [risk=no][RW-4896] New User Profile e2e tests

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java, api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cdrselector/WorkspaceResourcesServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapper.java, api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java, api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapperTest.java, ui/src/app/pages/data/cohort-review/table-page.tsx, ui/src/testing/stubs/cohort-review-service-stub.ts
Cleanup of CohortReviewController
1. Moved mappers into CohortReviewServiceImpl
2. Separated Controller level exceptions from Service level exceptions
3. Fixed a sorting UI issue in review using FilterColumns.SEXATBIRTH
=> [RW-5379][risk=no] move mappers from CohortReviewController to CohortReviewService

api/db-cdr/changelog-schema/db.changelog-39.xml, api/db-cdr/changelog-schema/db.changelog-master.xml, api/db-cdr/generate-cdr/bq-schemas/cb_criteria.json, api/db-cdr/generate-cdr/bq-schemas/cb_search_all_events.json, api/db-cdr/generate-cdr/bq-schemas/cb_survey_attribute.json, api/db-cdr/generate-cdr/bq-schemas/cb_survey_version.json, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-data-dump.sh, api/db-cdr/generate-cdr/make-bq-data.sh, api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh, api/libproject/devstart.rb
adding in COPE survey data including cb_survey_attribute and cb_survey_version tables, adding survey_id column to cb_search_all_events and code to populate it, changing devstart to point to new script
=> [RW-5349][risk=no] adding in COPE survey data

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
[https://precisionmedicineinitiative.atlassian.net/browse/RW-5468](RW-5468) : Turn feature Flag on On Prod
[https://precisionmedicineinitiative.atlassian.net/browse/RW-5469](RW-546) : For feature flag code clean up
This also contains fix for RW-5501 Remove CohortBuilderConfig from WorkbenchConfig
---
=> [RW-5535][risk=no]Add Feature Flag for COPE Survey

e2e/tests/profile/profile-page.spec.ts
=> [risk=low][RW-4896] e2e tests for User Profile

api/db-cdr/changelog-schema/db.changelog-39.xml, api/db-cdr/generate-cdr/bq-schemas/cb_criteria.json, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-data.sh
=> [no ticket][risk=no] fixing new snyth cdr build

api/db-cdr/changelog-schema/db.changelog-39.xml
=> [no ticket][risk=no] remove drop of index

ui/package.json, ui/yarn.lock
Description:
Resolves https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/tree-kill/open
---
=> [risk=low] Upgrade build-angular to resolve a vulnerability in a dependency

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [RW-5565][risk=no] adding age parent

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
updating CDR build to use new criteria table script
=> [no ticket][risk=no] updating CDR build to use new criteria table script

ui/src/app/app-router.spec.tsx, ui/src/app/components/app-router.tsx
Built a strawman BrowserRouter and guards with nested & sibling ProtectedRoutes and tested all endpoints.
---
=> Tests for BrowserRouter

api/config/config_test.json, ui/src/app/cohort-search/tree/tree.component.tsx
Also enabled the `enableCOPESurvey` flag for test.
---
=> [RW-5568][risk=no] Hide COPE survey if enableCOPESurvey flag disabled

ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/demographics/demographics-v2.component.tsx, ui/src/app/cohort-search/demographics/demographics.component.tsx, ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx, ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx, ui/src/app/cohort-search/selection-list/selection-list.component.tsx, ui/src/app/cohort-search/tree/tree.component.tsx, ui/src/app/cohort-search/utils.ts, ui/src/app/components/help-sidebar.tsx
Cleanup of code and updating the styles to more closely match mocks. Changes include:
Give sidebar more width for criteria selections/fix styles for selection list
Update placement of external links and help text in list search view
Update age slider layout/allow for multiple age range selections
---
=> [RW-5503][risk=no] Cleanup for Cohort Builder V2 UI

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
This flag will control whether to display the runtime customization side-panel in the help bar.
=> [RW-5396][risk=no] Add enableCustomRuntimes flag

api/genomics/docs/running_cromwell.md, api/genomics/wdl/IngestSyntheticVcfInputs.json, api/genomics/wdl/IngestSyntheticVcfOptions.json, api/genomics/wdl/IngestSyntheticVcfWf.wdl, api/genomics/wdl/RandomizeVcf/Dockerfile
This PR has a wdl for RandomizeVcf plus a markdown file with instructions for running it on Terra.
---
=> [RW-5476][risk=no] WDL for RandomizeVcf

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java, ui/src/app/pages/data/data-set/export-data-set-modal.tsx
Scenarios tested:
- Generate Code and export:
> For Existing DataSet: From Snowman Menu and from DataSet Update Page
> New Data Set
- 
---
=> [RW-5388][risk=no]	 [P1]- cannot export Dataset to notebook using the snowman menu

ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/help-sidebar.tsx
=> [RW-5398][risk=no] Show sidebar icon for runtime

e2e/app/component/help-sidebar.ts, e2e/app/page/cohort-participants-group.ts, e2e/app/page/cohort-search-page.ts, e2e/app/page/workspace-data-page.ts, e2e/app/text-labels.ts, e2e/tests/cohorts/cohorts-create.spec.ts, e2e/tests/cohorts/cohorts-ui.spec.ts, e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/export-r-notebook.spec.ts, ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx, ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/demographics/demographics.component.tsx, ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx, ui/src/app/cohort-search/selection-list/selection-list.component.tsx, ui/src/app/components/help-sidebar.tsx
- Update existing tests for new cohort builder UI and workflow (converted modal to full page, use sidebar for selections, modifiers and attributes)
- Add new class for testing the `HelpSidebar` component
- Includes minor updates/cleanup of cohort builder components needed for tests
---
=> [RW-5434][risk=no] Update Puppeteer test for new Cohort Builder UI

api/src/main/java/org/pmiops/workbench/actionaudit/ActionType.kt, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/AdminAuditor.kt, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/AdminAuditorImpl.kt, api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
Description:
Tested by verifying a match between contents for admin and non-admin versions:
Authed as a non-admin user with a notebook in a workspace:
`curl (plus bearer and JSON headers) -X POST -d' ' -o j2_user.json \
http://localhost:8081/v1/workspaces/aou-rw-local1-de188ff4/joel2ws1/notebooks/spend.ipynb/readonly`
User endpoint - Saves `j2_user.json`
`curl (plus bearer and JSON headers) -X POST -d' ' \
http://localhost:8081/v1/admin/workspaces/aou-rw-local1-de188ff4/joel2ws1/notebooks/spend.ipynb/readonly`
Admin endpoint - returns 403
Authed as a different user with RESEARCHER_DATA_VIEW Authority:
`curl (plus bearer and JSON headers)  -X POST -d' ' \
http://localhost:8081/v1/workspaces/aou-rw-local1-de188ff4/joel2ws1/notebooks/spend.ipynb/readonly`
User endpoint - returns 401 because …
=> [risk=low][RW-5475] Admin read-only notebook endpoint

e2e/app/page/notebook-preview-page.ts, e2e/tests/datasets/export-py-notebook.spec.ts
Export to Notebook thru ellipsis menu is working again. Enable automated test.
https://precisionmedicineinitiative.atlassian.net/browse/RW-5388
=> [RW-5388][risk=no] Puppeteer enable failed test for Export to Notebook

ui/src/app/pages/data/concept/concept-homepage.tsx, ui/src/app/utils/index.tsx
Moves validation function for MySQL search strings to `app/utils/index.tsx` (not sure if that's the best location for it)
---
=> [RW-5517][risk=no] Make concept search validation reusable

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
Fixes the following issues in the newly enabled cohort builder UI:
- Prevent Occurrences modifier from appearing momentarily for Surveys
- Fix units display for attributes in Physical Measurements, currently displaying 'undefined' for BMI
- Hide all dropdowns and show loading spinner when waiting for Visit Type modifier to return from api
- Fix nav icons at top of sidebar, unable to click consistently
---
=> [RW-5582][risk=no] Fixes for new Cohort Builder UI

.github/PULL_REQUEST_TEMPLATE.md, e2e/README.md
=> [risk=no] Update test:local text to test-local

api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java, api/src/main/resources/workbench-api.yaml, ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/pages/admin/admin-notebook-view.tsx, ui/src/app/utils/navigation.tsx
=> [risk=high][RW-5478] Admin View Notebook page

api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java
=> [risk=no] remove warning and other minor refactoring

ui/package.json, ui/yarn.lock
=> [risk=no] Remove unused and potentially vulnerable angular2-highcharts

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java, api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/actionaudit/TargetType.kt, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/BillingProjectAuditor.kt, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/BillingProjectAuditorImpl.kt, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/main/resources/firecloud.yaml, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/ConceptsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
Description:
~DRAFT.  This will fail until~ https://github.com/broadinstitute/firecloud-orchestration/pull/799 is live
---
=> [risk=low][RW-3627] Delete project when deleting workspace

e2e/tests/notebook/owner-copy-to-workspace.spec.ts
removing the notebooks analysis executions in `owner-copy-to-workspace.spec.ts` test.
=> [no ticket][risk=no] Puppeteer Modify notebook test to shorten playback time

e2e/tests/notebook/reader-copy-to-workspace.spec.ts
This test opens and waits for two separate notebook runtimes to start. Total test time goes over 20 minutes. Removing second notebook runtimes from test reduces time by half. Test coverage is not negatively affected by removing second notebook runtimes start up.
=> [no ticket][risk=no] Puppeteer: shorten notebook test playback time

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cdr/model/DbCriteria.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
Implemented a new endpoint to return a collection of DomainInfo for the Concept Set card search
=> [RW-5512][risk=no] endpoint to return a collection of DomainInfo for the Concept Set card search

e2e/tests/home/home-page.spec.ts
=> [no ticket][risk=no] Puppeteer HomePage test change

api/db-cdr/generate-cdr/make-bq-data.sh
=> [RW-5511][risk=no] adding cope survey card

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding question data to cb_survey_attribute table
=> [RW-5621][risk=no] adding question data to cb_survey_attribute table

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
allow for null answer concept id
=> [RW-5622][risk=no] allow for null answer concept id

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
=> [RW-5557][risk=no] adding multiple ages

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json, api/src/bigquerytest/resources/bigquery/schema/cb_search_all_events.json, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/resources/workbench-api.yaml
updating BQ sql to include survey_id for cope
=> [RW-5464][risk=no] updating BQ sql to include survey_id for cope

e2e/README.md
=> [risk=no] Some e2e readme updates

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
fixing issue with data in cb_survey_attribute table
=> [RW-5632][risk=no] fixing issue with data in cb_survey_attribute table

e2e/README.md
=> [risk=no] Add Developer Tips to e2e readme

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
updating dao to use 0 instead of null for question concept id
=> [no ticket][risk=no] updating dao to use 0 instead of null for answer concept id

api/config/cdr_versions_preprod.json, api/config/cdr_versions_stable.json, api/config/cdr_versions_staging.json, api/config/cdr_versions_test.json
=> [RW-5627][risk=no] bumping synth CDR version

api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/google/CloudStorageService.java, api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java, ui/src/app/pages/admin/admin-workspace.tsx
=> [risk=medium][RW-5471][RW-5472] List workspace files on admin page

e2e/app/component/help-sidebar.ts, e2e/app/component/tiered-menu.ts, e2e/app/page/cohort-search-page.ts, e2e/app/page/create-account-page.ts, e2e/app/xpath-builders.ts
cohort tests sometimes fails due to loading spinner interfering with click action.
https://app.circleci.com/pipelines/github/all-of-us/workbench/4099/workflows/d3cd9468-1e7e-45cf-b98f-8b40832a28a2/jobs/100459/artifacts
=> [no ticket][risk=no] Puppeteer flaky cohort UI fix

e2e/tests/misc/sidenav.spec.ts
Test run faster without second sign-in.
Skip CI.
=> [no ticket][risk=no] Puppeteer Sidenav test change

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/tree/tree.component.tsx
Fyi @dolbeew and @mhigbyflowers There is a follow up ticket with Lou's comment about new cohort pages
https://precisionmedicineinitiative.atlassian.net/browse/RW-5618
---
=> [RW-5556][risk=no] UI: Make header sticky in hierarchy view

e2e/app/page/create-account-page.ts
nightly Registration test is broken due to invalid xpath selectors.
failed CI job https://app.circleci.com/pipelines/github/all-of-us/workbench/4293/workflows/0e600ab9-fd75-4df7-89d7-be150e268d65/jobs/101417
=> [no ticket][risk=no] Puppeteer Fix User Registration test

ui/src/app/pages/analysis/runtime-panel.spec.tsx
=> [RW-5660][risk=no] Temporarily disable flaky test

ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/data/concept/concept-homepage.spec.tsx, ui/src/app/pages/data/concept/concept-homepage.tsx, ui/src/app/pages/data/concept/concept-list.tsx, ui/src/app/pages/data/concept/concept-table-v2.tsx, ui/src/app/utils/index.tsx, ui/src/app/utils/navigation.tsx
=> [RW-5576][RISK=NO]  UI: Update concept set UI - duplicate shopping cart function

README.md, api/reporting/docs/cohort_definition_schema.json
Adding to api/reporting/docs
Did a bit of cleanup to make the schema file more readable and added descriptions.
=> [no ticket][risk=no] cohort definition json schema file

api/config/config_local.json, api/config/config_test.json
Reverts all-of-us/workbench#4092
=> Revert "[risk=no] Temporarily disable billing buffer cron in test"

README.md
=> [no ticket][risk=no] link from read me to json file was incorrect

e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/dataset-rename.spec.ts
Split test by feature: one is create, other is rename. No code change.
=> [no ticket][risk=no] Puppeteer: Break up Dataset test

e2e/tests/notebook/notebook-download.spec.ts, e2e/tests/workspace/workspace-share.spec.ts
`page.setViewport({width: 1280, height: 680})` is now set in `beforeEach` hook in `jest.test-setup.ts`.
=> [no ticket][risk=no] Puppeteer Remove setViewport in test file

e2e/app/xpath-builders.ts
Reverts all-of-us/workbench#4080
=> Revert "[RW-5662][risk=no] Puppeteer Fix flaky Cohort UI test"

api/db-cdr/changelog-schema/db.changelog-40.xml, api/db-cdr/changelog-schema/db.changelog-master.xml, api/db-cdr/generate-cdr/bq-schemas/domain_info.json, api/db-cdr/generate-cdr/make-bq-data.sh
Update Physical Measurements and the domain_info table
=> [no ticket][risk=no] update PM

api/config/config_local.json, api/config/config_test.json
Will enable in higher environments at end of the week, if this goes well.
=> [RW-4848][risk=no] Dataproc -> GCE in local/test

e2e/tests/notebook/notebook-download.spec.ts
Follow-up to https://github.com/all-of-us/workbench/pull/4107#discussion_r498895926
=> [risk=no] Use === and drop tslint bypass

api/db-cdr/changelog-data/db.changelog-1.xml
=> [no ticket][risk=no] update local data for CB

api/config/cdr_versions_preprod.json, api/config/cdr_versions_prod.json, api/config/cdr_versions_stable.json, api/config/cdr_versions_staging.json, api/config/cdr_versions_test.json
bumping cdr to add domain_enum to domain_info table
=> [no ticket][risk=no] bumping cdr to add domain_enum to domain_info table

api/db-cdr/generate-cdr/make-bq-data.sh
=> RW-5701 fixing domain_info counts

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding standard observation concepts to the cb_criteria table
=> [RW-5705][risk=no] adding standard observation concepts to the cb_criteria table

api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt, api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/EgressEventTargetProperty.kt, api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java, api/src/test/java/org/pmiops/workbench/opsgenie/EgressEventServiceTest.java
Changes:
- Update to reference new `vm_prefix` field instead of `vm_name`
- Include egress breakdown by machine type
=> [RW-5614][risk=low] Egress alert updates

api/build.gradle
Newer version is not susceptible to https://app.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-570204
Description:
---
=> [risk=medium] Update spring-security-core and spring-security-web

api/config/config_local.json, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/analysis/notebook-redirect.tsx, ui/src/app/pages/analysis/reset-runtime-button.tsx, ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/pages/workspace/workspace-wrapper/component.spec.ts, ui/src/app/pages/workspace/workspace-wrapper/component.ts, ui/src/app/styles/colors.ts, ui/src/app/utils/leo-runtime-initializer.spec.tsx, ui/src/app/utils/leo-runtime-initializer.tsx, ui/src/app/utils/stores.tsx
Unfortunately cannot upload video files, but they have been shared with UX and Product
---
=> [RW-5409][risk=no] Dynamic sidebar runtime icon state

api/db-cdr/generate-cdr/make-bq-data.sh
revert old physical measurement ordinal
=> [no ticket][risk=no] revert old physical measurement ordinal

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
filter out synonyms that are in Chinese
=> [RW-5712][risk=no] filter out synonyms that are in chinese

api/db-cdr/generate-cdr/make-bq-data.sh
=> [no ticket][risk=no] PM counts correction

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java, api/src/test/java/org/pmiops/workbench/cohortbuilder/util/CriteriaLookupUtilTest.java, api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java
Updating the CbCriteriaDao to use the full_text index for searching.
=> [RW-5489[[risk=no] moving to full_text index

api/db-cdr/changelog-data/db.changelog-1.xml
updating local cdr to include observations
=> [no ticket][risk=no] updating local cdr to include observations

ui/src/app/pages/analysis/interactive-notebook.tsx
=> [risk=no][RW-5723] Decrease notebook iFrame width to fit navbar

api/build.gradle
Description:
Addresses https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-1016906 and https://app.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518
---
=> [risk=low] Upgrade vulnerable httpclient and commons-codec

api/config/config_test.json
Temporarily enabled to test new api calls against test env api
=> [risk=no] Disable enableConceptSetSearchV2 config flag for test

ui/src/app/pages/data/criteria-search.tsx
Fixes the unintended caching of criteria selections in cohort builder
=> [risk=no] Fix CB selections in tree view

api/src/main/resources/firecloud.yaml
Description:
We don't call this endpoint, and Terra Cloud Integrations will be removing it soon.
---
=> [risk=no] rm obsolete grantGoogleRoleToUser from firecloud.yaml

ui/src/app/pages/workspace/workspace-wrapper/component.ts
Noticed some new error spam in the test environment, traced it to this.
=> [risk=no] Catch action exceeded errors for runtime store initializer

ui/src/app/services/error-reporter.service.ts
New log:
```
ERROR Error: 404 @ https://api-dot-all-of-us-workbench-test.appspot.com/v1/workspaces/aou-rw-test-456ce8de/asdf: {"message":"DbWorkspace aou-rw-test-456ce8de/asdf not found.","statusCode":404,"errorClassName":"org.pmiops.workbench.exceptions.NotFoundException","errorCode":null,"errorUniqueId":"6483011e-e250-47c2-8b67-711fa3ce27f5"}
```
=> [risk=no] Better logging for fetch() errors

api/db-cdr/generate-cdr/make-bq-dataset-linking.sh, api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh
adding cope survey columns to dataset builder
- Adding survey_version_id and survey_version_name to ds_survey table
- Adding survey_version_id and survey_version_name to ds_linking table
=> [RW-5540] adding cope survey columns to dataset builder

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
Description:
Before:
After:
---
=> [risk=no][RW-5566] Add CDR Version to dataset query export comment

.circleci/README.md, .circleci/config.yml
Making an effort to improve `config.yml` file to make it less cluttered, easier to understand and follow.
- Leverage CircleCI v2.1 new `executor` feature. Executor defines the docker environment in which the steps of a job will be run. It allows reuse of a single executor across multiple jobs. This is the environment which jobs will run inside of.
- New `README.md`: document anchors, jobs, commands, etc. Also describe any important information/reasons about the CI `config.yml`.  Any long comments or explanations should be included in `README.md` instead in `config.yml`.
- Job and command names are now using hyphens instead of underscores.
- Fix a bug: One or more file change in the `api/src/main/resources` dir will force UI and API tests to run.
- Bumped up cache version keys to `v5` to …
=> [RW-5742][risk=no] CircleCI config improvement

e2e/app/page/cohort-build-page.ts, e2e/app/page/cohort-participants-group.ts, e2e/tests/cohorts/cohorts-create.spec.ts, e2e/tests/cohorts/cohorts-rename.spec.ts, e2e/tests/cohorts/cohorts-ui.spec.ts, e2e/utils/waits-utils.ts
Failure occurred when waiting for calculated Group or Total Count took longer than 10 seconds. Fix issue by Increase timeout to 60 seconds.
=> [RW-5753][risk=no] Address flaky Puppeteer Cohort tests

api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java, api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
=> [RW-5646][RISK=LOW] Infinite Spinner for Concept Set Rename

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
- Adding column has_fitbit to cb_search_person
- Adding fitbit row into the cb_criteria table
=> [RW-5669][risk=no] adding column has_fitbit

api/config/config_local.json, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/utils/leo-runtime-initializer.tsx, ui/src/app/utils/runtime-presets.ts
=> [RW-5714][risk=no] Preset runtime dropdown

api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Description:
Example of generated code
---
=> [RW-5045][risk=no] Hail Microarray Demo codegen

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
Search all source/standard concepts Conditions and Procedures
- Removed dao calls no longer used
- Modified dao calls to no longer use source/standard
- Updated test cases accordingly
=> [RW-5718][risk=no] Search all source/standard concepts Conditions and Procedures

api/config/config_local.json, api/config/config_test.json
**Do not merge** until https://github.com/all-of-us/workbench/pull/4180, https://github.com/all-of-us/workbench/pull/4188 are merged, and then manually QA'd.
=> [RW-5715][risk=no] enableCustomRuntimes in local/test

ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx, ui/src/app/pages/data/data-set/new-dataset-modal.spec.tsx, ui/src/app/pages/data/data-set/new-dataset-modal.tsx
Description:
Adding UI flow to add microarray code gen
---
=> [RW-5640][risk=low] Adding UI to add microarray codegen

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
=> [RW-5764][risk=low] Update to latest notebooks image

api/build.gradle, api/src/test/java/org/pmiops/workbench/actionaudit/ActionAuditQueryServiceTest.java
Description:
May or may not clear up some minor Snyk concerns
---
=> [risk=no] Upgrade com.google.cloud packages to latest minor-version

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
=> [no ticket][risk=no] domain count correction

api/build.gradle, api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/db/dao/RdrExportDao.java, api/src/main/java/org/pmiops/workbench/rdr/RdrExportService.java, api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java, api/tools/src/main/java/org/pmiops/workbench/tools/DeleteFromRdrExport.java
Workbench send recently created/modified workspace information to RDR daily. The workspaces picked for export are as follows:
1.  **workspace id does not exist in rdr_export** <- this usually means that the workspace has been
created since the last time cron job is run
2. **workspace's lastModifiedTime > export_date_time in rdr_export table** <- this means that the workspace has been modified since the last time cron job is run
There are sometimes (maybe in case of bugs), where already exported workspace data are not in sync between workbench and RDR . In such cases, we need to make the workspace eligible for re-export. The best way to do that without manipulating real workspace data is to remove the entry from rdr_export table. 
The project.rb command delete-workspace-rdr-expor does …
=> [noTicket][risk=low] Task to delete workspace from Rdr export

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx, ui/src/app/pages/data/concept/concept-add-modal.tsx, ui/src/app/pages/data/concept/concept-list.tsx, ui/src/app/pages/data/concept/concept-set-details.tsx, ui/src/app/pages/data/concept/concept-survey-add-modal.tsx, ui/src/app/pages/data/criteria-search.tsx
1) Pass survey Name information to concept-survey-add-modal and
2) Also update concept-set-details page to display type of Survey
---
=> [noTicket] Fix :Update/Save Survey Concept Set using the new criteria search

ui/src/app/cohort-search/tree-node/tree-node.component.tsx
For new concept set, make Hierarchy Node selectable except in case of Survey - Question
1) Concept Set - Survey 
2) Concept set - Condition
3) Cohort Builder - Condition Domain
4) Cohort Builder = Survey
---
=> [noTicket][risk=low]Concept Set: Fix hierarchy node select

api/config/cdr_versions_preprod.json, api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
fixing observation and preprod CDR name
=> [no ticket][risk=no] fixing observation and preprod CDR name

api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java, ui/src/app/pages/analysis/reset-runtime-button.tsx, ui/src/app/utils/leo-runtime-initializer.tsx, ui/src/app/utils/runtime-presets.ts
Flag has now been live for two releases. Remaining references will be removed after next release, per https://docs.google.com/document/d/133JzAcrIf_ZKFqzL2jvVaBbxb69NMMSjs7iTuj8xW0A/edit#heading=h.sp5o436rip09
=> [RW-5658][risk=no] Teardown enableGceAsDefault flag

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
=> [RW-5685][risk=no] Create feature flag - Fitbit

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
This PR addresses the problem within Cope Surveys where we want to **AND** attributes together instead of using **OR** like in other cases. Please deploy and test locally.
=> [no ticket][risk=no] Cope survey attributes

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json, api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/resources/workbench-api.yaml
Adding fitbit data counts to CB
- Created a new domain called FITBIT
- Added BQ sql to select has_fitbit from cb_search_person
=> [RW-5670] Adding fitbit data counts to CB

ui/src/app/cohort-search/selection-list/selection-list.component.tsx
Clicking back on attributes page will close the [sidebar]
---
=> [noTicket][risk=no]When hitting back in attributes, sidebar should go away

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
=> [no ticket][risk=no] dataset query efficiency

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
fixing issue with LOINC lab hierarchy due to OMOP vocabulary update
=> [RW-5814][risk=no] fixing issue with LOINC lab hierarchy due to OMOP change

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding concept code to survey criteria items
=> [RW-5823][risk=no] adding concept code to survey criteria items

api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/java/org/pmiops/workbench/rdr/RdrExportEnums.java, api/src/main/resources/rdr.yaml, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/login/account-creation/account-creation-options.tsx
Add options during registration. RDR export should work as well.
@NehaBroad does this require any changes on the RDR side?
=> [RW-5077][risk=no] Add MSW, MPH degree options

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
updating ICD10 tree and fixing issues with counts
=> [RW-5835][risk=no] updating ICD10 tree and fixing issues with counts

ui/src/testing/stubs/auth-domain-api-stub.ts, ui/src/testing/stubs/cdr-versions-api-stub.ts, ui/src/testing/stubs/cohort-builder-service-stub.ts, ui/src/testing/stubs/cohort-review-service-stub.ts, ui/src/testing/stubs/cohorts-api-stub.ts, ui/src/testing/stubs/concept-sets-api-stub.ts, ui/src/testing/stubs/concepts-api-stub.ts, ui/src/testing/stubs/config-api-stub.ts, ui/src/testing/stubs/data-set-api-stub.ts, ui/src/testing/stubs/featured-workspaces-config-api-stub.ts, ui/src/testing/stubs/institution-api-stub.ts, ui/src/testing/stubs/jupyter-api-stub.ts, ui/src/testing/stubs/leo-runtimes-api-stub.ts, ui/src/testing/stubs/profile-api-stub.ts, ui/src/testing/stubs/proxy-api-stub.ts, ui/src/testing/stubs/runtime-api-stub.ts, ui/src/testing/stubs/status-alert-api-stub.ts, ui/src/testing/stubs/status-api-stub.ts, ui/src/testing/stubs/stub-utils.tsx, ui/src/testing/stubs/user-api-stub.ts, ui/src/testing/stubs/user-metrics-api-stub.ts, ui/src/testing/stubs/workspaces-api-stub.ts
=> [risk = no] "cannot fetch in tests" -> StubImplementationRequired

ui/src/app/pages/analysis/runtime-panel.tsx
An improvement - though unfortunately I couldn't get the two grids to align properly, let me know if you have ideas on this.
=> [RW-5799][risk=no] Align main CPU/ram/disk to grid

e2e/puppeteer-custom-environment.ts
=> [risk=no] Format e2e failure log file datetimes

.circleci/config.yml, e2e/resources/workbench-config.ts
Created new users for Puppeteer testing in CircleCI:
```
puppetcilocalcollaborator1@fake-research-aou.org
puppetcicollaborator1@fake-research-aou.org
stagingcilocalcollaborator1@staging.fake-research-aou.org
```
Created new CircleCI env variables that store new values:
```
PUPPETEER_COLLABORATOR_LOCAL
PUPPETEER_COLLABORATOR_TEST
PUPPETEER_COLLABORATOR_STAGING
```
=> [no ticket][risk=no] Puppeteer: new test collaborators

ui/src/app/utils/leo-runtime-initializer.tsx, ui/test-setup.js
Revert once the root issue is fixed properly.
=> [RW-5851][risk=no] Temporary hack to fix unit test flakiness

ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/utils/runtime-utils.ts
Button goes gray until the DELETE fetch completes, then navigates back to the main panel.
=> [RW-5421][risk=no] Async delete button UX

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Fixing issue with querying parent nodes in CB.
=> [RW-5890][risk=no] problem querying parent nodes

api/db-cdr/generate-cdr/make-bq-denormalized-review.sh, api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
Adding case statements to use date column if datetime column is null in make-bq-denormalized-review.sh
=> [RW-5891][risk=no] changing shell scripts to add case statements for null timestamps

.circleci/config.yml, e2e/package.json
Fixes in CircleCI config.yml for the e2e test results loading to GCS bucket.
=> jest cli --no-color

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java, ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
showing the top 250 results on landing page for CS and CB search
=> [RW-5844] showing the top 250 results on landing page for CS and CB search

e2e/tests/workspace/workspace-duplicate.spec.ts
=> [risk=no] rename workspace-clone spec to workspace-duplicate

api/db-cdr/generate-cdr/make-bq-data.sh
=> [RW-5733][risk=no] changing name of survey

ui/src/app/pages/analysis/notebook-redirect.spec.tsx, ui/src/app/pages/analysis/notebook-redirect.tsx
After the iframe is loaded, navigate back to the preview page if/when we observe the runtime leaving the running status.
=> [RW-5690][risk=no] Navigate away from notebooks iframe on runtime status change

ui/src/app/pages/signed-in/component.ts
=> [RW-5423][risk=no] Warn when reloading/navigating during compound operation

api/db-cdr/generate-cdr/make-bq-data.sh, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java, e2e/tests/workspace/workspace-duplicate.spec.ts
=> [no ticket][risk=no] domain count fix

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/constant.ts, ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx, ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx, ui/src/app/cohort-search/utils.ts
Behind the `enableFitbit` feature flag, currently available only in local environment.
---
=> [RW-5671][risk=no] Add Fitbit option to Cohort Builder criteria menu

ui/package.json, ui/src/app/pages/profile/profile-page.spec.tsx, ui/src/app/utils/index.tsx, ui/yarn.lock
Description:
eslint says:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.8.0
YOUR TYPESCRIPT VERSION: 3.1.6
```
On upgrade, Angular says
```
@angular/compiler-cli@7.2.15 requires typescript@'>=3.1.1 <3.3' but 3.7.5 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
```
So I'm compromising with `>=3.2.1 <3.3`
---
=> [risk=low] Upgrade typescript for eslint and angular compatibility

api/db-cdr/generate-cdr/make-bq-data.sh, api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
=> [no ticket][risk=no] adding PM search for CS

api/config/cdr_versions_preprod.json, api/config/cdr_versions_stable.json, api/config/cdr_versions_staging.json, api/config/cdr_versions_test.json
promoting the synth cdr in all envs
=> [RW-5793][risk=no] bumping synth cdr

e2e/app/component/concept-domain-card.ts, e2e/app/component/help-sidebar.ts, e2e/app/page/cohort-participants-group.ts, e2e/app/page/cohort-search-page.ts, e2e/app/page/conceptset-actions-page.ts, e2e/app/page/conceptset-search-page.ts, e2e/app/page/criteria-search-page.ts, e2e/app/page/workspace-data-page.ts, e2e/app/text-labels.ts, e2e/tests/cohorts/cohorts-create.spec.ts, e2e/tests/cohorts/cohorts-ui.spec.ts, e2e/tests/conceptsets/conceptset-create.spec.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/tests/conceptsets/copy-to-workspace.spec.ts, e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/export-r-notebook.spec.ts, ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx, ui/src/app/pages/data/criteria-search.tsx
- Create new `CriteriaSearchPage` class for component shared between Cohort Builder and Concept Search
- Enable cohort tests that were flaky, seem to be passing consistently now
=> [RW-5796][risk=no] Update puppeteer tests for new Concept Search UI

api/config/cdr_versions_preprod.json
bump preprod to point to new CDR indices
=> [no ticket][risk=no] bump preprod to point to new CDR indices

ui/src/app/components/buttons.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/utils/runtime-utils.ts
=> [RW-5591][risk=no] Create runtime panel

api/config/cdr_versions_local.json, api/config/cdr_versions_perf.json, api/config/cdr_versions_preprod.json, api/config/cdr_versions_stable.json, api/config/cdr_versions_staging.json, api/config/cdr_versions_test.json, api/db/changelog/db.changelog-142-cdr-version-hasCopeSurvey-field.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CdrVersionsControllerTest.java
=> [no ticket][risk=no] adding cope survey data flag

ui/src/app/cohort-search/cohort-page/cohort-page.component.spec.tsx, ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx, ui/src/app/cohort-search/tree/tree.component.tsx
- with Fitbit Data
- with COPE Survey
with no Fitbit data
with no COPE Survey
---
=> [RW-5927][risk=low] Replace feature flags for fitbit and COPE survey for flag with appropriate database metadata flagbuilder

api/genomics/build.gradle
Description:
https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415
---
=> [risk=low] Update guava to v30 to address Snyk vuln

ui/src/app/cohort-search/overview/overview.component.tsx
- Disable the delete icon on the cohort build page for users with READER access
- Minor cleanup of the variables in render function, moved to own functions
---
=> [RW-5900][risk=no] Disable delete cohort icon for READER access level

api/config/config_local.json, api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java, api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java, api/src/main/java/org/pmiops/workbench/compliance/ComplianceService.java, api/src/main/java/org/pmiops/workbench/compliance/ComplianceServiceImpl.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/db/dao/UserService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerServiceImpl.java, api/src/main/java/org/pmiops/workbench/google/CloudStorageServiceImpl.java, api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/main/resources/firecloud.yaml, api/src/main/resources/moodle.yaml, api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java, api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java, api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java, api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java, api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java, ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/environments/environment.local.ts
Description:
Remove all code paths where these flags are set to false, along with structures only referenced by false-paths.
Update tests as appropriate.
* enableMoodleV2Api
* useNewShibbolethService
* enableBillingLockout
* useKeylessDelegatedCredentials
* enableVpcFlowLogs
* enableVpcServicePerimeter
Per our Feature Flag Teardown Safety Protocol ™️ this change does not remove the config settings themselves.  I'll make a follow-up PR to do this after the next release.  See [this doc](https://docs.google.com/document/d/133JzAcrIf_ZKFqzL2jvVaBbxb69NMMSjs7iTuj8xW0A/edit#) for details.
---
=> [risk=low][RW-4798][RW-4688][RW-3882][RW-4308][RW-5091] Teardown Feature Flags, part 1

ui/src/app/pages/data/data-set/dataset-page.tsx
Feel free to merge this yourself if it's desired for the demo.
Correcting fitbit domain name
=> [risk=no] Fix "Fitbit hear rate" typo

ui/src/app/cohort-search/tree-node/tree-node.component.tsx
=> [RW-5953][risk=no] Fix attributes issue for hierarchy view in concept search

api/src/main/webapp/static/aou-download-policy-extension.js, ui/src/app/pages/workspace/old-cdr-version-modal.tsx
=> [risk=no] Update Data Use Policies links from old URL to new

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx
=> [RW-5943][risk=low] Code column data overlaps with Vocab column 

ui/src/app/components/footer.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/components/side-nav.spec.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/workspace/workspace-edit-text.tsx
Description:
Updated the text in 4 locations.
1. User menu in top left
2. Workspace footer links in bottom right
3. The Review Request text in Create Workspace
4. The link in the side help text (bottom right)
1:
2 and 3:
4:
---
=> [risk=no][RW-5781] Add "Hub" to instances of "User Support" in the UI

api/config/cdr_versions_prod.json, api/config/config_prod.json, ui/src/environments/environment.perf.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts
Turn on feature flags in prod for
1. New concept set search
2. Cope survey data
3. Fitbit data
@jscherdin @dolbeew please confirm that all flags look valid and cross reference with this ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-5930
=> [RW-5930][risk=no] Turn on prod flags for new concept set search, cope and fitbit data

ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts
turn off enableNewConceptTabs in preprod/prod
=> [no ticket][risk=no] turn off enableNewConceptTabs in preprod/prod

README.md
Description:
I needed to make this change to successfully access Terra endpoints using the Test Env SA
---
=> [risk=no] Update scopes in readme

ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx
=> [risk=no] Prevent duplicate dropdown options in PM attributes

e2e/app/component/workspace-card.ts, e2e/tests/notebook/owner-copy-to-workspace.spec.ts
Refactor test to reduces playback time by half and use one less new workspace.
=> [no ticket][risk=no] Puppeteer refactor owner-copy-to-workspace test

e2e/tests/home/home-page.spec.ts
Combining two smaller tests removes the second login.
=> [no ticket][risk=no] Puppeteer Refactor Home test

api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/tools/src/main/java/org/pmiops/workbench/tools/LoadDataDictionary.java, api/tools/src/main/resources/data_dictionary_exports/AllofUsDatasetV4.yaml
=> [RW-6019][risk=no] Temporary data dictionary for All of Us Dataset v4

api/tools/src/main/resources/data_dictionary_exports/AllofUsDatasetV5.yaml
=> [RW-6022][risk=no] Data Dictionary entry for CDR v5

ui/src/app/pages/workspace/old-cdr-version-modal.tsx
Description:
You have selected to use an older version -> You have selected an older version
---
=> [risk=no] Update outdated CDR Version modal text

e2e/app/component/help-sidebar.ts, e2e/app/component/snowman-menu.ts, e2e/app/page/base-page.ts, e2e/app/page/cdr-version-upgrade-modal.ts, e2e/app/page/google-login.ts, e2e/app/page/home-page.ts, e2e/app/page/notebook-page.ts, e2e/app/page/notebook-preview-page.ts, e2e/app/page/workspace-analysis-page.ts, e2e/jest.test-setup.ts, e2e/tests/notebook/reader-copy-to-workspace.spec.ts, e2e/tests/workspace/workspace-edit.spec.ts, e2e/tests/workspace/workspace-share.spec.ts, e2e/utils/test-utils.ts, e2e/utils/waits-utils.ts
Puppeteer tests have started to fail often in CircleCI recently. Fixes in this PR should stabilize tests again.
Implement workarounds for two open issues that made tests flaky:
1: https://precisionmedicineinitiative.atlassian.net/browse/RW-6002
2: https://precisionmedicineinitiative.atlassian.net/browse/RW-6005
Increased timeout for wait-for functions.
=> [no ticket][risk=no] Puppeteer: Flaky tests fixes

ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/styles.css
Abused the dropdown for this purpose. It's not really a dropdown. This is better than the previous attempt though.
=> [RW-5996][risk=no] Update presets controls to better match the mocks

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/resources/workbench-api.yaml
This PR adds an API call to lookup criteria by domain, source/standard and conceptId.
=> [RW-6015][risk=no] Lookup criteria by domain, source/standard and conceptId

api/config/featured_workspaces_prod.json
Updated featured workspaces for the new CDR
---
=> [RW-6017][risk=no] Update featured workspaces for CDR v4

api/libproject/devstart.rb
This is an upgrade from 256 to 1024 MB.
Description:
---
=> upgrade PROD instance to an F4 to see if we can make reporting work

ui/src/app/pages/homepage/homepage.tsx
updated video content is using new links. please verify by running locally and selecting all videos.
---
=> [RW-6028][risk=no] update video links

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
This PR addresses the refactor of the attribute part of the BQ SQL building.
AC: Please test all of the scenarios in this doc: [here](https://docs.google.com/document/d/1zMmyr0TLeE7L4cZ_JvDhLxHruR0Me2Z6LxD8u8hOMHA/edit)
=> [RW-6013][risk=no] Refactor of attribute BQ SQL

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
fixing issue with code that adds full_text
=> [RW-6037][risk=no] fixing issue with code that adds full_text

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
=> [no ticket][risk=no] fix dataset query

e2e/app/element/button.ts, e2e/app/page/workspace-analysis-page.ts, e2e/utils/waits-utils.ts
=> [no ticket][risk=no] Puppeteer Rework Button waitForEnabled function

ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx
`selectedMachine`, `selectedDisk` are authoritative. Added regression test and comment.
=> [RW-6038][risk=no] Fix price computation on Dataproc master

ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/utils/machines.ts
- Max machine price
- Max disk size
Also, increase the step from 1 -> 10 for disk size changes, so the up/down buttons are a little more useful.
=> [RW-6050][risk=no] Restrict valid machine types, disk size

ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx
It already closed after update/create.
(oops, meant to sent this PR yesterday)
=> [RW-6008][risk=no] close the runtime panel on delete

ui/src/app/cohort-search/list-search-v2/list-search-v2.component.tsx, ui/src/app/cohort-search/search-bar/search-bar.component.tsx, ui/src/app/utils/index.tsx
=> [RW-5913][risk=no] Add string validation to criteria search inputs

e2e/app/component/runtime-panel.ts
This element click is flaky, but I don't have a firm theory for how.
=> [risk=no] Try waitForVisible on status icon xpath selector

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/db-cdr/changelog-data/db.changelog-1.xml, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
=> [RW-5686][risk=no] removing fitbit flag

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml, ui/src/app/cohort-search/tree/tree.component.tsx
=> [RW-5470][risk=no] removing cope survey flag

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, ui/src/app/cohort-search/attributes-page-v2/attributes-page-v2.component.tsx
Surveys - when selecting select a value query needs to match against value_as_number is not null
=> [RW-6012][risk=no] Surveys - when selecting select a value query needs to match against value_as_number is not null

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
There's still one place we have to do this, whicih was the emaili field.
---
=> [RW-6062][risk=no] rename email column as username

api/libproject/devstart.rb
Adding ruby def for calling CDR indices build in circle ci
=> [RW-6068][risk=no] Adding ruby def for calling CDR indices build from circle ci

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
fixing bug with ICD10CM to add back in top level parent
=> [RW-6077][risk=no] fixing bug with ICD10CM to add back in top level parent

api/libproject/devstart.rb
removing docker sync reference
=> [no ticket][risk=no] removing docker sync reference

api/libproject/devstart.rb
removing unused arg from cdr-indices build
=> [no ticket][risk=no] removing unused arg from cdr-indices build

api/libproject/devstart.rb
updating cdr indices build to make shell scripts runnable from circle ci.
=> [no ticket][risk=no] updating cdr indices build

api/libproject/devstart.rb
updating indices to run in circle ci. Changing arg for ruby command for project
=> [no ticket][risk=no] updating indices to run in circle ci

api/db-cdr/generate-cdr/make-bq-data.sh
updating the domain_info table in cdr indices
=> [no ticket][risk=no] updating the domain_info table in cdr indices

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/demographics/demographics.component.spec.tsx, ui/src/app/cohort-search/demographics/demographics.component.tsx, ui/src/app/pages/data/criteria-search.tsx
- Show toast for all demographics selections
- Prevent toast when an already selected node is clicked
- Cleanup unused code in `CohortSearch` component
---
=> [RW-6060][risk=no] Fix "Criteria Added" toast for demographics selections

api/db-cdr/generate-cdr/init-new-cdr-db.sh
=> [no ticket][risk=no] export cdr name variable

api/genomics/docs/unsorted_vcf.md
=> [RW-5968][risk=no] Add notes on running genomics tools on unsorted vcf input

api/db-cdr/generate-cdr/libproject/devstart.rb, api/docker-compose.yaml, api/src/dev/server/Dockerfile
Description:
Followup to #4431, addressing other issues I have seen with publish-cdr:
* upgrade the `bq` client in the server Dockerfile to address a JWT problem
* add the App SA directly as a READER to address "too many groups" problems
---
=> [risk=low] Updates to publish-cdr

.circleci/config.yml, ci/Dockerfile.circle_build, deploy/docker-compose.yaml
=> [risk=no] bump circleci CLOUD_SDK_VERSION to 321.0.0 and buildimage to 0.0.20

e2e/app/page/notebook-page.ts
Minor update in `notebook-page` class.
=> [no ticket][risk=no] Puppeteer: Increase wait for notebook ready timeout

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
removing enableCohortBuilderV2 feature flag
=> [RW-5338][risk=no] removing enableCohortBuilderV2 feature flag

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
removing enableConceptSetSearchV2 feature flag
=> [RW-5500][risk=no] removing enableConceptSetSearchV2 feature flag

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/leonardo.yaml
Belated follow-up to https://github.com/all-of-us/workbench/pull/4072
=> [RW-5098][risk=no] Remove long-deprecated Welder flag

api/gradle/wrapper/gradle-wrapper.properties, api/src/main/java/org/pmiops/workbench/api/SumoLogicController.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/SumoLogicControllerTest.java
=> [RW-5934] [risk=low] Mark some fields in EgressEvent as required and also relax unknown properties restriction

ui/src/app/components/resource-card.tsx
Description: Allow writer delete WS content. 
Verified in local UI.
---
=> [RW-5855]allow writer delete resources

ui/src/app/pages/analysis/runtime-panel.tsx
=> [P2] Don't flash $0 of free credits on the runtime panel while loading

ui/src/app/pages/data/concept/concept-search.tsx
=> [RW-6127][risk=no] Fix blank page after creating new concept set

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, ui/src/app/cohort-search/list-search/list-search.component.tsx
=> [RW-6110][risk=no] Fix survey search within existing concept set

api/docs/tools.md
=> [risk=no] Documentation for tools

ui/src/app/components/help-sidebar.tsx
=> [risk=no][RW-6040] Add box shadow to help sidebar

ui/src/app/components/help-sidebar.tsx
=> [risk=no][RW-6135] Add Cohorts and Add Datasets links are not clickable unless Help sidebar is closed

e2e/app/page/conceptset-page.ts, e2e/tests/conceptsets/conceptset-create.spec.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/tests/conceptsets/copy-to-workspace.spec.ts, e2e/tests/datasets/dataset-rename.spec.ts, e2e/tests/datasets/export-py-notebook.spec.ts, e2e/tests/datasets/export-r-notebook.spec.ts
=> [RW-5932][risk=no] Fix and enable concept and dataset puppeteer tests

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/elasticsearch/ElasticFiltersTest.java, api/src/test/java/org/pmiops/workbench/test/SearchRequests.java, ui/src/app/cohort-search/utils.ts
This PR removes the value property from SearchParameter model and any references in the UI. Also, updated test cases to reflect changes.
=> [RW-5680][risk=no] removing value from SearchParameter

api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java, api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java, api/src/main/java/org/pmiops/workbench/conceptset/mapper/ConceptSetMapper.java, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
removing CdrBigQuerySchemaConfigService from ConceptBigQueryService and updating test cases.
=> [RW-6160][risk=no] remove CdrBigQuerySchemaConfigService from ConceptBigQueryService

api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
cleanup/rewriting test case for ConceptBigQueryServiceTest
=> [RW-5707] cleanup/rewriting test case.

ui/src/app/cohort-search/tree/tree.component.tsx
Add background color and back arrow to Return to list 
https://user-images.githubusercontent.com/34481816/105395253-85cac500-5bec-11eb-87d0-68d128776ffe.mov
---
=> [RW-5828][risk=no]"Return to list" in hierarchy is not intuitive

ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
https://user-images.githubusercontent.com/34481816/105398483-6b92e600-5bf0-11eb-9487-8fd4f586e26f.mov
---
=> [RW-5770][risk=no]  Modifiers - disallow n values <0

.circleci/config.yml, api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, ui/src/app/pages/data/cohort-review/cohort-review.tsx, ui/src/app/pages/data/cohort-review/create-review-modal.tsx, ui/src/app/pages/data/cohort-review/detail-header.component.tsx, ui/src/app/pages/data/cohort-review/detail-page.tsx, ui/src/app/pages/data/cohort-review/table-page.tsx, ui/src/app/services/review-state.service.ts, ui/src/testing/stubs/cohort-review-service-stub.ts
removing unused props from CohortReview:
1. page
2. pageSize
3. sortOrder
4. sortColumn
=> [RW-4706][risk=no] removing unused props from CohortReview

api/libproject/devstart.rb
avoid slow initial requests related to new instance start up time.
=> [no ticket][risk=no] Increase GAE Idle Instances on test

api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java, api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java, api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/dao/ConceptSetDaoTest.java, ui/src/testing/stubs/concept-sets-api-stub.ts
removing unused ConceptSetController method
=> [RW-5600][risk=no] removing unused ConceptSetController method

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
Description:
This PR puts the address and institutional data back into the reporting table
---
- [X ] This PR meets the Acceptance Criteria in the JIRA story
=> [risk=no][RW-6147] Correct reporting institution

ui/src/app/pages/data/data-set/new-dataset-modal.tsx
"DataSet with same name exist" -> "A Dataset with the same name exists"
"Data state cannot save as some information is missing" -> "Cannot save the Dataset because some information is missing"
---
=> [risk=no] Happened to see some bad error messages in new-dataset-modal

.circleci/config.yml, e2e/package.json
One Puppeteer test user for local and test env.
=> [no ticket][risk=no] e2e user env update in CircleCI config

ui/src/app/pages/data/data-set/export-data-set-modal.spec.tsx, ui/src/app/pages/data/data-set/export-data-set-modal.tsx
=> [RW-6207][risk=medium]  [P2] Bug when creating notebook from saved dataset snowman menu

api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Move the following from CohortReviewController into CohortReviewService:
1. BigQueryService
2. CohortQueryBuilder
3. ReviewQueryBuilder
=> [RW-5381][risk=no] Refactor CohortReviewController

api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
Stacked PR onto #4510 which changes configs for multi-tier.
A similar multi-tier PR for the prototype is #4427 
---
=> [risk=medium][RW-6182] Update publish-cdr for multi-tier

api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/test/java/org/pmiops/workbench/db/model/StorageEnumsTest.java
TODO: either merge these files or ensure that all have test coverage in StorageEnumsTest:
* DbStorageEnums
* DemographicSurveyEnum
* RdrExportEnums
(list generated by searching for BiMap)
---
=> [risk=no] Clean up some duplicate DB mappings which could cause bugs

api/docs/developer-system-requirements.md
=> [risk=no] Developer requirements doc: docker-sync has moved

ui/src/app/components/warning-message.tsx, ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx
Checked in with Lou about copy, since it differs from the ticket.
---
=> [RW-5414][risk=no] Runtime panel billing lockout

e2e/app/component/review-conceptset-sidebar.ts, e2e/app/component/review-criteria-sidebar.ts, e2e/app/element/base-element.ts, e2e/app/page/cohort-participants-group.ts, e2e/app/page/cohort-search-page.ts, e2e/app/page/conceptset-search-page.ts, e2e/app/page/criteria-search-page.ts, e2e/app/page/workspace-data-page.ts, e2e/tests/cohorts/cohorts-duplicate.spec.ts, e2e/tests/conceptsets/conceptset-create.spec.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/tests/conceptsets/copy-to-workspace.spec.ts, e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/export-r-notebook.spec.ts
`help-sidebar.ts` is separated into two smaller classes, `review-criteria-sidebar.ts` and `review-conceptset-sidebar.ts` because they're two different sidebars.
Both sidebar classes extends `BaseHelpSidebar.ts` abstract class.
Removed unused and duplicate functions.
=> [no ticket][risk=no] Puppeteer fix sidebar code issues

api/libproject/load_local_data_and_configs.sh
=> [risk=no] Fix lingering cdrVersionConfig reference

api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, ui/src/app/pages/homepage/registration-dashboard.tsx
Description:
NPE happens if workspace not found, that turns into 500 error to client. The real error code should be 404
---
=> [RW-5898][risk=low] Throw 404 if workspace not found instead of 500

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java, api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java
Description:
This is similar to what we did for workspace table. Those two are the most problematic tables. 
---
=> [RW-6058]: Batch load/upload user report

api/libproject/devstart.rb
Trying to see if memory is actually reduced.
Description:
---
=> [no ticket][risk=low]Reduce machine size to see if memory usage

e2e/app/page/create-account-page.ts, e2e/tests/nightly/registration.spec.ts
=> [RW-6243][risk=no] Puppeteer registration test fix

ui/src/app/cohort-search/cohort-page/cohort-page.component.spec.tsx, ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/tree/tree.component.tsx, ui/src/testing/stubs/cohort-builder-service-stub.ts
=> [RW-6102][risk=no] Add UI tests for CohortPage and CohortSearch components

ui/src/app/pages/signed-in/component.ts, ui/src/app/utils/analytics.ts, ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/environment.perf.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts, ui/src/environments/test-env-base.ts
Description:
Following the pattern of #2699, add a Google Analytics Custom Dimension and associated `analytics.ts` function to determine the Institutional Category for the logged-in user:
* **Operations** if the user has a Verified institutional Affiliation with the magic-short-name 'AouOps' institution
* **Researcher** if the user has a Verified institutional Affiliation with any other institution
* **No Institution** if the user has none
* **Unknown** for any GA events triggered before user sign-in
Tested by observing all 4 states on Local using [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)
---
=> [risk=low][RW-5616] Add institution category to Google Analytics

api/libproject/devstart.rb
Reverts all-of-us/workbench#4553
FreeTierBilling job OOM
=> Revert "[no ticket][risk=low]Reduce machine size to see if memory usage"

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
adding physical measurement concepts for concept set selector and changing BQ flag project to project_id
=> [RW-6199][risk=no] adding physical measurement concepts for concept set selector 

api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java, api/src/main/java/org/pmiops/workbench/utils/ResponseCodeRetryPolicy.java
Description: It is general a common pattern retry on 500 errors
---
=> [RW-6287][risk=low] Retry 500 errors

ui/src/app/components/help-sidebar.tsx
https://user-images.githubusercontent.com/1847690/107283895-00884280-6a2b-11eb-8e48-c2637cb917a5.mov
---
=> [RW-6041][risk=no] Stop width from changing as help sidebar opens

ui/src/app/pages/profile/demographic-survey.tsx
Description:
Corrected text to no longer include the "optional" in the description / title
---
=> [risk=no][RW-6294] Update text for demographic survey

ui/src/app/services/sign-in.service.ts
This was a bug introduced with test user impersonation, resulting in a race condition on initial rendering of the page (showing "Unknown Error").
Normal behavior:
- All code references `serverConfigStore` directly, with the assumption that it's been loaded already
- This is a safe assumption for code on the "signed in" codepath (thought it would be nice if it were formalized more), because the server config store is a prerequisite to logging in (the oauth client ID is returned by this config).
Bug:
- With user impersonation, the token is immediately available on page load
- In the previous code, this would trigger sign in immediately upon application load, potentially triggering downstream codepaths before the server config had loaded
Fix:
- sign in on impersonation now runs after the …
=> [RW-6241][risk=no] Eliminate sign in race condition during impersonation

api/config/cdr_config_local.json, api/config/cdr_config_test.json, api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
See https://github.com/all-of-us/workbench/pull/4510 for the configuration changes enabling this tier plus the addition of the existing Registered Tier.
This PR adds a new "controlled" tier for Local and Test, to help us work with multiple tiers.
---
=> [risk=low][RW-6181] Add Test/Local Controlled Tier and CDR

.gitignore
Description:
No code change.
This pr adds the .vscode directory to .gitignore
---
=> [risk=no][no-ticket] Update gitignore to ignore vscode config files

.circleci/config.yml
Wrongly changed in https://github.com/all-of-us/workbench/pull/4557
=> [no ticket][risk=no] CircleCI change back to tcp when wait for SQL start

ui/src/app/pages/profile/profile-registration-step-status.tsx, ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/environment.perf.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts, ui/src/environments/test-env-base.ts
Description:
Removing an old feature flag and associated code that was only executed when the flag was turned off.
---
=> [risk=no][no-ticket]Remove environment feature flag from RW-3441

api/config/cdr_config_local.json, api/config/cdr_config_test.json
Description:
Follow-up to #4571 except with the right CDR projects this time
---
=> [risk=no][RW-6181] Use the right second-tier CDR project

api/db-cdr/changelog-schema/db.changelog-42.xml, api/db-cdr/changelog-schema/db.changelog-master.xml
Add cdr db-> ds_data_dictionary
---
=> [RW-6152][risk=low] Integrate data dictionary load into the CDR indices build (Data Dictionary)  : Liquibase changes

api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java, api/src/main/resources/rdr.yaml
Description:
Add the CDR version name to the nightly RDR push
Testing: Manually verified that the new field is present and has a reasonable value
No novel functionality or changes to the inherent design were made, existing tests should already cover this code.
---
=> [RW-6086][risk=no] Add cdrVersion field to rdr push

e2e/jest.test-setup.ts
Improve test logging: find all page console errors/warnings, log all AoU api requests and response. Output log with pretty JSON format.
=> [no ticket][risk=no] Puppeteer rework console log handler

api/db-cdr/generate-cdr/make-bq-data.sh
updating PM cdr indices scripts
=> [no ticket][risk=no] updating PM cdr indices scripts

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
=> [no ticket][risk=no] adding PM alias

api/libproject/devstart.rb
Revert https://github.com/all-of-us/workbench/pull/4496/
Above change did not improve test performance and stability. I do not see any obvious improvement.
=> [no ticket][risk=no] revert commit 4496

api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
=> [risk=no] Fix typo in scope URL

e2e/jest.test-setup.ts
Regression caused by https://github.com/all-of-us/workbench/pull/4559
=> [no ticket][risk=no] Puppeteer test log fix

ui/src/app/pages/admin/admin-notebook-view.tsx, ui/src/app/pages/admin/admin-workspace.tsx
=> [RW-6335][risk=no] Encode/decode notebook names for admin preview

ui/package.json, ui/yarn.lock
Description:
Addresses a [Snyk vulnerability](https://snyk.io/vuln/SNYK-JS-HIGHCHARTS-1018906) and follows an [upgrade recommendation](https://github.com/browserslist/browserslist#browsers-data-updating).
---
=> [risk=low] Update UI packages caniuse-light and highcharts

ui/.eslintrc.js, ui/src/app/app-routing.tsx, ui/src/app/components/html-viewer.tsx, ui/src/app/pages/admin/admin-user-bypass.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/pages/profile/profile-registration-step-status.tsx
Description:
This will correct spacing inconsistencies in JSX curly brackets
---
=> Add eslint curly space rule for JSX

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
=> [RW-6360]: Add a feature flag to control wheter to enable RAS linking 

api/src/main/java/org/pmiops/workbench/cdr/cache/MySQLStopWords.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/config/CacheMySqlStopWordConfig.java, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, ui/src/app/cohort-search/list-search/list-search.component.tsx, ui/src/app/cohort-search/search-bar/search-bar.component.tsx
Update full text search to exclude stop words from search term. Also allow 2 search characters. 
List of stop words
=> [RW-6209][risk=no] Update full text search to exclude stop words from search term

api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
Description:
This test was causing me problems trying to update Workspace (on another branch).  Let's make it less fragile.
---
=> [risk=no] Improve fragile WorkspaceAuditorTest

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh, api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/libproject/devstart.rb
This PR adds the has_whole_genome_variant flag to CB search. 
Also, updated the criteria table to include this in the search drop down menu as well as adding args to the circle ci job that builds the CDR indices.
=> [RW-6398][risk=no] adding has_whole_genome_variant flag to CB search

api/config/cdr_config_local.json, api/config/cdr_config_test.json, api/db/changelog/db.changelog-138-cdr-version-microarray-field.xml, api/db/changelog/db.changelog-152-cdr-version-wgs-field.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/api/CohortsController.java, api/src/main/java/org/pmiops/workbench/cdr/CdrVersionMapper.java, api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java, api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CdrVersionsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, ui/src/app/cohort-search/overview/overview.component.tsx
=> [RW-6336][risk=no] WGS BQ dataset field / hasWgsData

api/src/main/java/org/pmiops/workbench/monitoring/MeasurementBundle.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
=> [risk=no] oops, I misunderstood the metrics type system and I broke it

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
Add new physical measurement bucket to list of outer join domains
=> [no ticket][risk=no] Dataset Builder SQL tweek

api/src/main/webapp/WEB-INF/cron_perf.yaml
Description:
rm line from #4656
---
=> [risk=no] fix YAML error in perf cron

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/admin/admin-workspace-search.tsx, ui/src/app/pages/admin/admin-workspace.tsx
=> [RW-6315] Reactify workspace admin routes

ui/src/app/pages/homepage/homepage.tsx
Update video for dataset and notebook on homepage as per the links provided in https://precisionmedicineinitiative.atlassian.net/browse/RW-6409
---
=> [RW-6409][risk=low] [P3] Bug: new links to tutorial videos on Workbench

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/admin/admin-user.tsx, ui/src/app/pages/admin/admin-users.tsx
=> [RW-6316][risk=no] Reactify user admin routes

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
=> [RW-6368][risk=low]: Add RAS client id and hostname into config

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json, api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/resources/workbench-api.yaml
Implement CB counts for whole genome variant
=> [RW-6399][risk=no] Implement CB counts for whole genome variant

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Adding option for CB to search participants who have PM data.
=> [RW-6112][risk=no] Adding option for CB to search participants who have PM data

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
Description:
This is one action item in our design review: we should specify login.gov in feature flag name
---
=> [RW-6360][risk=low]rename enableRasLoginGovLinking feature flag

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/data/cohort/cohort-actions.tsx
=> [RW-6324][risk=no] Move cohort actions route to React router

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/profile/profile-page.tsx
=> [RW-6319] Reactify profile page

api/db-cdr/changelog-data/db.changelog-1.xml, api/db-cdr/changelog-schema/db.changelog-43.xml, api/db-cdr/changelog-schema/db.changelog-master.xml
This table will eventually drive the CD criteria menu.
=> [RW-6401][risk=no] Create menu table for CB

api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
add check to see if genome dataset exists
=> [no ticket][risk=no] add check to see if genome dataset exists

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/app/pages/workspace/workspace-list.tsx
=> [RW-6326][risk=no] Reactify remaining (easy) workspace routes

ui/src/app/cohort-search/utils.ts
=> [RW-6356][risk=no] Replace Angular TitleCasePipe with lodash

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh, api/libproject/devstart.rb
Adding new criteria table into the CDR build
This process will add the proper cb_criteria_menu.csv into the build process.
=> [RW-6448][risk=no] Adding new criteria table into the CDR build

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
adding validation against old datasets.
=> [no ticket][risk=no] adding validation against old datasets.

e2e/jest.test-setup.ts, e2e/utils/waits-utils.ts
Add missing parameter types and comments in `wait-utils.ts`.
Fix a mistake in `waitWhileLoading` function.
=> [no ticket][risk=no] Puppeteer fix bug in function

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
fixing small bug in PM CB search
=> [no ticket][risk=no] fixing small bug in PM CB search

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CriteriaMenuDao.java, api/src/main/java/org/pmiops/workbench/cdr/model/DbCriteriaMenu.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CriteriaMenuDaoTest.java
Created a table to drive the CB menu and it will live in the CDR indices database, since it will differ per CDR.
=> [RW-6449][risk=no] New API call for CB menu

ui/src/app/cohort-search/tree/tree.component.tsx
- Add 'Has Any Physical Measurements Data' checkbox to Physical Measurements tree in CB
- Hide rest of the tree if checkbox is checked
https://user-images.githubusercontent.com/40036095/111370056-bca9de00-8665-11eb-8861-7b8fde7c014f.mov
---
=> [RW-6165][risk=no] Add 'Has Any Physical Measurements Data' checkbox to cohort builder

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-dataset-linking.sh, api/db-cdr/generate-cdr/make-bq-denormalized-dataset.sh, api/db-cdr/generate-cdr/make-bq-denormalized-review.sh, api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh, api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh, api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/libproject/devstart.rb
removing dry run flag from CDR indices build
=> [no ticket][risk=no] removing dry run flag from CDR indices build

api/config/config_staging.json
Increase billing buffer size to 150 in preparation for puppeteer testing in staging env
=> [no ticket][risk=no] Increase billing buffer in staging

api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapper.java, api/src/test/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapperTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/cdrconfig/UpdateCdrConfig.java
=> [risk=low][RW-6485] Fix a bug in UpdateCdrConfig and add tests

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cdr/model/DbMenuOption.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java, ui/src/testing/stubs/cohort-builder-service-stub.ts
Removing old api for CB menu options
CohortBuilderController#findCriteriaMenuOptions
=> [RW-6446][risk=no] Removing old api for CB menu options

api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
Description:
This helps me with some changes I'm making on another branch, split out from that branch to improve its focus.
I considered making the 3 methods more generic but there are some subtle differences, and I had some difficulties reconciling lambdas with checked exceptions.
---
=> [risk=low] refactor OfflineUserController

api/genomics/docs/uploading_1kg_wgs_test_data.md
=> [risk=no] change filename in documentation to reflect column order

api/db-cdr/generate-cdr/copy-bq-dataset.sh, api/libproject/devstart.rb
updating the copy dataset script
=> [no ticket][risk=no] copy dataset script

api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
=> [no ticket][risk=no] missing import statement

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java, api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceFreeTierUsageDao.java
Description:
Once upon a time, we expired users' Free Tier Credits once they had been registered for 180 days.  We have not done this for a long time, so we should remove references to this to avoid confusion.
Also cleaned up a bit of logic so it no longer references the first registration time unnecessarily and removed some unused code.
This is not related to https://precisionmedicineinitiative.atlassian.net/browse/RW-6280
---
=> [risk-low] Remove some unused Free Tier logic and update comments

ui/package.json
I happened to hit this today as well.
=> [risk=no] Show source map on ng test

ui/src/app/app.module.ts, ui/src/app/services/error-reporter.service.ts
Reverts all-of-us/workbench#4744
=> Revert "[RW-6351][risk=no] Reactify error reporter service"

ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/app.module.ts, ui/src/app/pages/data/cohort-review/cohort-review.tsx, ui/src/app/pages/data/cohort-review/detail-page.tsx, ui/src/app/pages/data/cohort-review/query-report.component.tsx, ui/src/app/pages/data/cohort-review/table-page.tsx
Move over the four routes for cohort review
---
=> [RW-5281][risk=no] Move cohort review routes to React router

api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
Add validation in cdr process to check:
- All necessary files are present in cdr_csv_files folder, if not exit right then
- Zip and copy the ds_data_dictionary csv file from cdr_csv_files/ to the correct cdr_version bucket
---
=> [noTicket][risk=no]Validate ds_data_dictionary file

api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
Validate that header gets removed if it exists.
=> [no ticket][risk=no] fix validation script

e2e/app/component/base-help-sidebar.ts, e2e/app/component/runtime-panel.ts, e2e/app/container.ts, e2e/jest.test-setup.ts, e2e/package.json
Fix flaky runtime sidebar functions. Test failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/8556/workflows/10e2a134-1863-44da-96e8-9504948230bd/jobs/127444).
=> [no ticket] Puppeteer wait for runtime sidebar to close

e2e/app/component/runtime-panel.ts
CircleCi build [failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/8825/workflows/17d1e70a-b06b-43b5-beca-96cd8cbd6822/jobs/129355).
=> [no ticket][risk=no] Puppeteer fix notebook runtime test

api/db-cdr/changelog-data/db.changelog-1.xml
fixing issue with `./project.rb run-local-data-migrations`
=> [no ticket][risk=no] fixing load data issue

api/db-cdr/generate-cdr/copy-bq-dataset.sh
reverting previous copy table changes
=> [no ticket][risk=no] reverting previous copy table changes

e2e/app/page/workspaces-page.ts, e2e/tests/cohorts/cohorts-create.spec.ts, e2e/tests/cohorts/cohorts-duplicate.spec.ts, e2e/tests/cohorts/cohorts-rename.spec.ts, e2e/tests/cohorts/cohorts-review.spec.ts, e2e/tests/cohorts/cohorts-ui.spec.ts, e2e/tests/conceptsets/conceptset-create.spec.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/tests/conceptsets/copy-to-workspace.spec.ts, e2e/tests/datasets/create-py-notebook.spec.ts, e2e/tests/datasets/create-r-notebook.spec.ts, e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/dataset-rename.spec.ts, e2e/tests/datasets/export-to-notebook.spec.ts, e2e/tests/nightly/dataproc-to-gce.spec.ts, e2e/tests/nightly/gce-to-dataproc.spec.ts, e2e/tests/nightly/owner-copy-to-workspace.spec.ts, e2e/tests/notebook/notebook-download.spec.ts, e2e/tests/notebook/notebook-python3.spec.ts, e2e/tests/notebook/notebook-r.spec.ts, e2e/tests/notebook/reader-copy-to-workspace.spec.ts, e2e/tests/runtime/pause-resume.spec.ts, e2e/tests/workspace/cdr-version-upgrade.spec.ts, e2e/tests/workspace/old-cdr-version-modal.spec.ts, e2e/tests/workspace/workspace-actions-share.spec.ts, e2e/tests/workspace/workspace-duplicate-cdr-versions.spec.ts, e2e/tests/workspace/workspace-duplicate.spec.ts, e2e/tests/workspace/workspace-edit.spec.ts, e2e/utils/test-utils.ts
Simplify `findOrCreateWorkspace` function. New functions are hopefully easier to read and understand.
- `createWorkspace`
- `findOrCreateWorkspace`
- `findWorkspaceCard`
- `findOrCreateWorkspaceCard`
Updated all usage.
=> [no ticket][risk=no] Puppeteer refactor test helper func

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
Adding validation for cope survey versions
=> [RW-6443][risk=no] Adding validation for cope survey versions

api/libproject/devstart.rb
Description:
Leftover from the Multi Tier Prototype branch - updated to fit what was implemented.
---
=> [risk=no][no ticket] Use cdr_config to retrieve Auth Domain Name for create-auth-domain

api/config/featured_workspaces_prod.json
=> [RW-6560][risk=no] Publish demo dataset

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
This PR breaks the processing into 2 pieces:
1. Process the prep tables - This allows creation of just the prep tables without any validation.
2. Process all tables - This allows creation of all tables with validation.
Added a few reusable functions
1. removeHeaderIfExists
2. loadCSVFile
3. validateCutoffDate
=> [no ticket][risk=no] refactor CDR indices validation

api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
=> [RW-6491]: Use googleProject when calling google's billing api

api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java, api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java, ui/src/app/pages/admin/admin-workspace.tsx
Description:
Is is copied from https://github.com/all-of-us/workbench/blob/master/api/src/main/java/org/pmiops/workbench/api/RuntimeController.java#L108
And https://github.com/all-of-us/workbench/blob/master/api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java#L718-L808
With some minor improvements
---
=> [RW-6558]: Add new endpoint in admin workspace for deleting runtime in this workspace

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Consolidating BQ SQL for:
1. Fitbit
2. Whole Genome Variant
3. Physical Measurements
=> [RW-6453][risk=no] consolidating BQ SQL

e2e/app/component/annotations-sidebar.ts, e2e/app/component/base-help-sidebar.ts, e2e/app/component/help-tips-sidebar.ts, e2e/app/component/review-conceptset-sidebar.ts, e2e/app/component/review-criteria-sidebar.ts, e2e/app/component/runtime-panel.ts, e2e/app/component/table.ts, e2e/app/component/workspace-card.ts, e2e/app/element/base-element.ts, e2e/app/modal/dataset-save-modal.ts, e2e/app/modal/share-modal.ts, e2e/app/page/profile-page.ts, e2e/app/page/workspace-base.ts, e2e/app/page/workspaces-page.ts, e2e/app/text-labels.ts, e2e/app/xpath-finder.ts, e2e/jest-puppeteer.config.js, e2e/jest.test-setup.ts, e2e/libs/jest-reporter.js, e2e/libs/logger.js, e2e/puppeteer-custom-environment.ts, e2e/tests/profile/profile-page.spec.ts, e2e/tests/workspace/workspace-edit.spec.ts, e2e/utils/save-file-utils.ts, e2e/utils/test-utils.ts
To reduce tests flakiness and improve logging.
=> [no ticket][risk=no] Puppeteer code fix and improvement

ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx, ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx, ui/src/app/cohort-search/search-group/search-group.component.tsx, ui/src/app/cohort-search/utils.ts
Adds new menu item to Cohort Builder criteria menu. There's no tree for this item, so will go straight to the cohort overview page, similar to Fitbit
---
=> [RW-6400][risk=no] Add 'Whole Genome Variant' option in criteria menu

ui/src/app/components/buttons.tsx, ui/src/app/components/icons.tsx, ui/src/app/components/resource-actions-menu.tsx, ui/src/app/pages/data/concept/concept-search.tsx, ui/src/app/pages/workspace/workspace-card.tsx
Description:
Cleaning up the abstraction around the icon button for menus
---
=> [no-ticket][risk=no] Clean up menu icon button

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
Description:
It was added in https://github.com/all-of-us/workbench/commit/3221b8d33511bade7eec597022d77c382e97d34e 
---
=> [no ticket][risk=low]: Restore workspace namespace back into reporting

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
correcting sex at birth for data browser
=> [no ticket][risk=no] correcting sex at birth for data browser

api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java, api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Description:
Follow-up to #4818 : now includes unregistered users.
---
=> [risk=low][RW-6137] Count unregistered users in the gauge metric

ui/src/app/pages/login/sign-in.tsx
Description:
A tiny piece of RW-6189 which we should sequence one release before the next piece, for deployment dependency safety.
---
=> [risk=no][RW-6189] rm dataAccessLevel from empty Profile in signin page

api/config/config_test.json
=> [risk=np] bump up buffer refill rate in test 1 -> 5 

api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceData.java
=> [no ticket][riwk=no]: fix missing dependency for export data tool

e2e/app/component/annotations-sidebar.ts, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx, ui/src/app/pages/data/concept/concept-list.tsx
Panel |                      Before         |  After
:-------------------------:|:-------------------------:|:-------------------------
help tips |  <img src="https://user-images.githubusercontent.com/2770197/114649740-188c7480-9caf-11eb-8ab1-a0a70c2b0502.png"> | <img src="https://user-images.githubusercontent.com/2770197/114649717-0ca0b280-9caf-11eb-903d-fddce610508d.png">
participant | <img src="https://user-images.githubusercontent.com/2770197/114642556-2091e780-9ca2-11eb-9186-3cdc92dd2fcf.png" width=300>  |  <img src="https://user-images.githubusercontent.com/2770197/114642511-11129e80-9ca2-11eb-9f39-e31a14a33e7a.png" width=300>
runtime | <img src="https://user-images.githubusercontent.com/2770197/114642619-3bfcf280-9ca2-11eb-8968-3c29bfd5546d.png"> | <img …
=> [risk=no] Refactor and standardize sidebar content header/closing button styling

api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
CircleCI uses circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com to deploy to Test, Staging and Perf as part of
---
=> [RW-6049][risk=no] Use correct service account for publishing perf CDR

api/libproject/wboptionsparser.rb
Description:
Thanks to @dmohs for the pointer on how to solve the problem of "my project.rb run failed and I have no idea why because it won't tell me" - I would not have guessed this.
---
=> [risk=no][RW-6479] Output the error message contained in raise ArgumentError.new()

api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java, api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/billing/BillingProjectBufferServiceTest.java
Description:
This endpoint is not used by the UI or any service, only as debugging info.  So it's safe to update in-place.
---
=> [risk=low][no ticket] Update BillingProjectBufferStatus for multi-tier

api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
adding enforceWorkspaceAccessLevel to delete concept set
=> [RW-6599][risk=no] adding enforceWorkspaceAccessLevel to delete concept set

ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/environment.perf.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts, ui/src/environments/test-env-base.ts
removing enableNewConceptTabs flag
=> [RW-4607][risk=no] removing enableNewConceptTabs flag

ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/help-sidebar.tsx
Tests on my PR were green but some commits went into master that broke my PR without causing a merge conflict.
=> [risk=no] Fix compilation bug from merge/PR conflict with CdrVersionListResponse -> CdrVersionTiersResponse change

api/config/cdr_config_local.json, api/config/cdr_config_perf.json, api/config/cdr_config_staging.json, api/config/cdr_config_test.json, api/config/config_staging.json, api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
Successfully ran: 
```
./project.rb create-auth-domain --project all-of-us-rw-staging --tier controlled --user joel-staging@staging.fake-research-aou.org
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-staging --tier controlled --bq-dataset test_R2019q4r3
```
Also renamed the "DO NOT USE" CT CDRs - we probably don't need to scare people away from these anymore
---
=> [risk=low][RW-6593] Add a Controlled Tier to Staging

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh
fixing cdr indices
data_browser variable was incorrect.
=> [no ticket][risk=no] fixing cdr indices

ui/src/app/components/buttons.tsx, ui/src/app/components/messages.tsx, ui/src/app/components/render-resource-card.spec.tsx, ui/src/app/components/render-resource-card.tsx, ui/src/app/components/resource-actions-menu.tsx, ui/src/app/pages/data/data-set/dataset-resource-card.tsx, ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx, ui/src/app/utils/analytics.ts, ui/src/app/utils/index.tsx, ui/src/testing/stubs/data-set-api-stub.ts
Also, couldn't deal with the error message TODOs in the other modals, so I rolled something custom for this use case:
=> [RW-6499][risk=no] Add genomics extraction modal on datasets with WGS concept set

api/config/config_preprod.json, api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java, ui/src/app/utils/zendesk.ts, ui/src/environments/environment-type.ts, ui/src/environments/environment.preprod.ts
Description:
https://aoupreprodsupporthelp.zendesk.com/hc/en-us 
---
=> [RW-6474][risk=low]: Setup preprod Zendesk

api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
use Timestamp.from consistently
=> [RW-6600][risk=no] use Timestamp.from consistently

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
updated code for full_text and synonyms columns, changed some parent_ids = -1 for consistency
=> [RW-6636][risk=no] updated code for full_text and synonyms columns, changed parent_ids

e2e/app/component/base-menu.ts, e2e/app/component/workspace-card.ts, e2e/app/container.ts, e2e/app/element/base-element.ts, e2e/jest.test-setup.ts
Misc test functions improvement: Fix problem that can cause test failure.
=> [no ticket][risk=no] Puppeteer test func improvement

ui/src/app/pages/app/component.ts
This fixes a bug that was causing an infinite spinner on local but not on test.
---
=> [no ticket][risk=no] error reporter null checks

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
updating code to remove un-needed text from demographics items in cb_criteria table
=> [rw-6659][risk=no] updating code to remove un-needed text from demographics items 

ui/src/app/services/sign-in.service.ts
Move declaration of this global earlier. Currently there appear to be some race conditions where we try to set this function before it's defined. This should no longer be blocked on any XHRs, just the initial Javascript load.
=> [RW-6664][risk=no] Mitigate Puppeteer access token flake

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
commenting out skip answers, so we can rerun the CT CDR indices job.
=> [no ticket][risk=no] commenting out skip answers

api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh, api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/libproject/devstart.rb
Adding wgv table as a parameter to the CDR indices build. The project.rb commands now accept:
1. wgv_project - whole genome variant project
2. wgv_dataset- whole genome variant dataset
3. wgv_table - whole genome variant table
---
=> [RW-6675][risk=no] adding wgv table as parameter to CDR indices build

api/config/config_preprod.json
Description:
Once these are completed, Controlled Tier is effectively launched in Preprod:
1. this PR
2. https://github.com/all-of-us/workbench/pull/4885 enable UI
3. https://precisionmedicineinitiative.atlassian.net/browse/RW-6594 publish CDR and cdr-config
---
=> [risk=high][RW-6592] Enable CT access to all RT users in Preprod

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/test/java/org/pmiops/workbench/db/dao/DataSetServiceTest.java
=> [RW-6610][risk=no]API - DataSetController move bigQueryService calls into DataSetServiceImpl

api/src/main/resources/workbench-api.yaml
=> [RW-6583][risk=no]  API - fix url for Data Dictionary API call

api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java, api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java, api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/conceptset/ConceptSetServiceTest.java, api/src/test/java/org/pmiops/workbench/db/dao/ConceptSetDaoTest.java
Enforce relationship between CS and workspaceNamespace / id. 
- deleteConceptSet
- getConceptSet
- updateConceptSet
- updateConceptSetConcepts
- copyConceptSet
---
=> [RW-6676][risk=no] fixing access controls for CS

ui/src/app/components/buttons.tsx
Description:
This fixes a regression in the button placement of the menu buttons on some of the cards in the app
Below are screenshots of the menu buttons before and after the fix and the playground icon button. Those are the places in the code that would be affected
**Before Fix - with regression**
---
---
**After fix**
---
=> [no-ticket][risk=no] Fix regression in menu icon button

api/config/cdr_config_preprod.json, api/config/config_preprod.json, api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
Barebones addition of a Controlled Tier to cdr_config_preprod to unblock progress.
TODO:
* ~create auth domain~ DONE
* add CDR Versions
---
=> [risk=low][RW-6594]Add a Preprod Controlled Tier - but no CDR Versions (TBD)

api/config/config_preprod.json
=> [RW-6690][risk=no] Turn off eRA in preprod

api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java, api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/dao/CohortDao.java, api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
I have done an audit of all our Controllers and unfortunately I found 2 more problems:
1. CohortReviewController
2. CohortAnnotationDefinitionController
So these controllers did have validation using workspace at one point. About 7 months back we did some cleanup in the Review part of the app, moving some logic out of the controllers and into services. It seems that in that refactor around Sept of 2020 I removed the workspace validation. Not sure what I was thinking but is was a bad oversight on my part. It's affecting all the read/write/delete methods in each controller. Thanks for finding this issue before it became a problem. 
---
=> [RW-6683][risk=no] Review Access controls

api/config/cdr_config_prod.json
Description:
The longer names do not break any of these UI elements:
* Workspace Navbar
* Workspace Edit dropdown (as long as we include the width increase from #4885)
* Recent Resources 
* Resource Copy Modal dropdown
* CDR Version Upgrade notification box
* CDR Version Upgrade Modal button
This UI element doesn't look great, but it was already a problem.  Filed https://precisionmedicineinitiative.atlassian.net/browse/RW-6687 for this.
---
=> [risk=no][RW-6647] Add 'Registered Tier' to prod Datasets (CDR Versions) v3 and v4

e2e/app/modal/workspace-review-research-purpose-modal.ts, e2e/app/page/workspaces-page.ts, e2e/app/text-labels.ts, e2e/tests/workspace/workspace-reader-actions.spec.ts, e2e/tests/workspace/workspace-writer-actions.spec.ts
Adding new tests for READER and WRITER actions. New test covers Review Research Purpose testing.
=> [no ticket][risk=no] Puppeteer new workspace reader and writer tests

e2e/jest.test-setup.ts, e2e/libs/jest-reporter.js, e2e/puppeteer-custom-environment.ts
General Improvement: 
- Clean up code
- Add comments
- Create lesser number of test logs.
> Only save logs when test fails. Log of passed tests are not saved. This change should makes easier to find failed test log 
in CircleCI.
=> [no ticket][risk=no] Puppeteer test log improvement

api/config/featured_workspaces_prod.json
=> [risk=low][RW-6693] Add Featured Workspace "Demo - Family History in EHR & PPI Data"

api/src/main/java/org/pmiops/workbench/db/dao/RdrExportDao.java
Fix RDR export logic for researchers. Might need to do a backfill as well.
=> [RW-6692][risk=no] RDR export entity bug

common-ui/common-ui-devstart.rb
=> [no ticket][risk=no] Copy down .npmrc during UI deploy

api/config/cdr_config_preprod.json
=> [RW-6594][risk=no] adding new CT CDR to preprod

api/config/cdr_config_preprod.json
=> [no ticket][risk=no] syncing CDR verisons

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [no ticket][risk=no] uncomment valid cdr code

api/config/cdr_config_staging.json
=> [risk=low][RW-6593] Correct the Staging Controlled Tier perimeter

e2e/app/page/workspace-edit-page.ts, e2e/tests/workspace/workspace-ui.spec.ts
Expand test coverage for Workspace Edit UI page, fix a flaky step, and update comments.
=> [no ticket][risk=no] Puppeteer new workspace UI test

e2e/app/component/base-help-sidebar.ts, e2e/app/container.ts, e2e/app/element/base-element.ts, e2e/app/modal/base-modal.ts, e2e/jest.test-setup.ts
`clickButton` in `base-help-sidebar.ts` and `base-modal.ts` are almost identical and both classes extends `Container`. One single new function `clickButton` in `Container.ts` to replace two copies.
=> [no ticket][risk=no] Puppeteer consolidate clickButton func

api/config/cdr_config_preprod.json
See https://precisionmedicineinitiative.atlassian.net/browse/RW-6706 for details.
=> [RW-6706][risk=low] Add placeholder WGS value for preprod alpha1

api/config/cdr_config_preprod.json
=> [no ticket][risk=no] bump cdr indices version

api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
=> [RW-6601][risk=no] API - ConceptSetService - consolidate save logic for many methods

api/config/featured_workspaces_preprod.json
=> [RW-6728][risk=low] Add placeholder genomics tutorial workspace

api/build.gradle, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/main/resources/firecloud.yaml, api/src/main/resources/swagger3codegen/libraries/okhttp-gson/ApiClient.mustache, api/src/main/resources/swagger3codegen/libraries/okhttp-gson/api.mustache, api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java, api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/CreateTerraMethodSnapshot.java, api/tools/src/main/java/org/pmiops/workbench/tools/CreateWgsCohortExtractionBillingProjectWorkspace.java
Description:
This PR does 2 things:
**First: Firecloud Swagger 2 to 3**
This is the pre-step to integration billing v2 endpoint. 
Both firecloud-orch and Rawls both are covered to Swagger 3:
https://github.com/broadinstitute/rawls/blob/develop/core/src/main/resources/swagger/api-docs.yaml
https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/resources/swagger/api-docs.yaml
(some FedRamp security from what I saw in https://broadworkbench.atlassian.net/browse/CA-853 description)
So I convert for us to easier add new billing v2 stuff
Steps to covert: 
1. Paste our swagger at https://editor.swagger.io/
2. Edit -> covert to swagger3
3. I compare that with Firecloud-orch and Rawls, seems fine
**Second: Fix Swagger 3 template:**
Previously seems swagger 3 tempate was …
=> [RW-6438][Billing V2 Step 1]convert firecloud to swagger 3

ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
Added regression test as well.
=> [risk=no] Only show WGS concept set if extraction is enabled

api/db/changelog/db.changelog-161-extraction-job-add-status.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/java/org/pmiops/workbench/db/model/DbWgsExtractCromwellSubmission.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionMapper.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/main/resources/firecloud.yaml, api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
=> [RW-6537][risk=no] Cache Terra status and submission time 

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fixing query to lookup drug ingredients
=> [no ticket][risk=no] fixing query to lookup drug ingredients

api/genomics/docs/wgs_cohort_extraction_setup.md
=> [risk=no][ticket=no] Update wgs_cohort_extraction_setup.md

api/config/cdr_config_perf.json, api/config/cdr_config_stable.json, api/config/cdr_config_staging.json, api/config/cdr_config_test.json
=> [no ticket][risk=no] bumping test cdr

api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/db/dao/UserService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Description:
Very similar to #4973 - tested in the same way.
---
=> [risk=low][RW-6739] Add confirmPublications endpoint

api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
=> [no ticket][risk=no] fixing typo

ui/package.json, ui/yarn.lock
Description:
Resolves https://github.com/advisories/GHSA-78cj-fxph-m83p and https://github.com/advisories/GHSA-h4j5-c7cj-74xg
---
=> [risk=low][no ticket] Upgrade karma to 6.3.2 to resolve transitive vulnerabilities

e2e/yarn.lock, ui/yarn.lock
Description:
Addresses https://github.com/advisories/GHSA-43f8-2h32-f4cj for UI and e2e
---
=> [risk=low][no ticket] Update hosted-git-info and referencing packages to resolve vulnerabilities

api/config/cdr_config_preprod.json
=> [no ticket][risk=no] bumping CT cdr

api/db/changelog/db.changelog-163-delete-institutional-affiliation.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/ProfileTargetProperty.kt
Description:
Remove the last reference to the old-style institutional affiliations. 
---
=> [risk=no][RW-4364] Delete institutional_affiliation DB table

api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionMapper.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java, ui/src/app/components/genomics-extraction-table.tsx
=> [RW-6642][risk=no] ABORTED status for extraction

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
Addresses https://github.com/all-of-us/workbench/pull/4999/files#r633793565
---
=> [RW-6725] [risk=no] RuntimeException -> Preconditions.checkNotNull

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Blocked on release of https://github.com/all-of-us/workbench/pull/4926
=> [RW-6034][risk=no] rm garbage collection configs (2/2)

api/config/cdr_config_preprod.json
Published per https://precisionmedicineinitiative.atlassian.net/browse/RW-6723
=> [RW-6723][risk=no] Add "published" wgs dataset to preprod config

api/db-cdr/generate-cdr/libproject/devstart.rb, api/genomics/docs/wgs_cohort_extraction_setup.md
```
./project.rb publish-cdr ...
./project.rb publish-cdr-wgs ...
```
Only added config entries for WGS where we have WGS data.
=> [RW-6723][risk=no] Split out WGS CDR publishing

api/src/main/java/org/pmiops/workbench/profile/ProfileService.java, api/src/main/resources/workbench-api.yaml, ui/src/app/app-routing.module.ts, ui/src/app/app-routing.tsx, ui/src/app/components/access-renewal-notification.tsx, ui/src/app/components/icons.tsx, ui/src/app/pages/access/access-renewal-page.tsx, ui/src/app/utils/index.tsx
Description:
Renders the AAR renewal page.
There is minimal functionality at this point. The buttons will be activated in a follow up story
https://precisionmedicineinitiative.atlassian.net/browse/RW-6618
---
---
=> Add access renewal page

ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/styles/colors.ts, ui/src/testing/stubs/data-set-api-stub.ts
=> [RW-6500][risk=no] Extraction status icon in help sidebar

ui/package.json, ui/src/app/app.module.ts, ui/src/testing/stubs/http-stub.ts, ui/src/testing/stubs/notebooks-service-stub.ts, ui/yarn.lock
=> [risk=no][no ticket] Remove a few Angular dependencies we don't need anymore

api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
=> [risk=no][no ticket] This test will fail sometimes unless we impose strict ordering

ui/yarn.lock
Description:
Fixes https://app.snyk.io/org/all-of-us-researcher-workbench/project/dff9eb4b-defa-46ad-aaf1-51eea4162a7e#issue-SNYK-JS-COLORSTRING-1082939
---
=> [risk=low][no ticket] Upgrade vulnerable color-string

e2e/app/page/dataset-build-page.ts, e2e/app/text-labels.ts, e2e/tests/datasets/dataset-create.spec.ts, e2e/tests/datasets/dataset-snowman-menu-actions.spec.ts, e2e/tests/datasets/export-to-notebook.spec.ts, ui/src/app/app-routing.tsx, ui/src/app/pages/data/data-set/data-set-component.tsx, ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx, ui/src/app/pages/data/data-set/export-dataset-modal.tsx, ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx, ui/src/testing/stubs/concept-sets-api-stub.ts, ui/src/testing/stubs/data-set-api-stub.ts
Description:
Also has some text changes to Save/Export buttons which was requested by Lou.
---
=> [RW-6503][risk=no] Add Extract VCF prompt to Export dataset

api/src/main/resources/application.properties
Will observe api-local-test logs to confirm the fix.
=> [RW-6795][risk=no] Fix plumbing of spring data source properties

api/config/config_preprod.json
Blocked on https://github.com/all-of-us/workbench/pull/5021
=> [RW-6782][risk=low] Enable genomic extraction in preprod

ui/src/app/app-routing.tsx, ui/src/app/components/icons.tsx, ui/src/app/pages/access/access-renewal-page.tsx
Description:
Joel proposed some nice refactor ideas of this page - this PR implements those. Putting them in the functionality branch made that change too big, so I pulled out the changes and made this PR. The state management around how times are handled is a bit cleaner, especially wrt: bypassed times. As a part of this I also refactored a bit of the rendering code
1. A compute function returns an object with the correctly formulated  strings for last confirmed and next review dates
2. Put the action / completed / bypassed button into its own component
1. This "flattens" out the render function a bit, and has all of the buttons using the same logic
Screenshot with new date management
---    
---
=> [no-ticket][risk=no] Refactor of AAR page

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/db/changelog/db.changelog-164-genomic-extraction-store-output-dir.xml, api/db/changelog/db.changelog-165-genomic-extraction-store-output-dir.xml, api/db/changelog/db.changelog-master.xml, api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/dao/WgsExtractCromwellSubmissionDao.java, api/src/main/java/org/pmiops/workbench/db/model/DbWgsExtractCromwellSubmission.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebooksCodeGenerationService.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java, e2e/tests/conceptsets/copy-to-workspace.spec.ts, ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx, ui/src/app/pages/data/data-set/export-dataset-modal.tsx
=> [RW-6633][RW-6634] Add Genomics Analysis Code Generation options

api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, ui/src/app/components/genomics-extraction-table.tsx, ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx, ui/src/app/utils/stores.tsx
https://user-images.githubusercontent.com/1847690/119694099-ebd58c00-be1a-11eb-98c3-89058c39894c.mov
---
=> [RW-6784][risk=no] Manage extraction job list state through a central store

api/src/main/java/org/pmiops/workbench/api/ProfileController.java
Description:
This fixes an error observed when updating a profile
Ran the unit tests locally.
---
=> [risk=no][no-ticket] Fix bug when confirming profile

api/db-cdr/prep-tables/README.md, api/db-cdr/prep-tables/make-prep-survey.py
processing REDCap csv files to Google bucket
bucket location: all-of-us-workbench-private-cloudsql/cb_prep_tables/redcap/output
updated code to:
1. handle registered_answer_suppressed flag
2. stripping "Thanks for your answers. " from lifestyle survey
3. copying local files and uploading it to the google bucket
=> [RW-6648][risk=no] creating the prep_survey table

ui/src/app/cohort-search/overview/overview.component.tsx
=> [RW-5636][risk=no] UI: Change cohort builder search charts to default to "age at CDR"

e2e/jest-puppeteer.config.js, e2e/jest.test-setup.ts, e2e/libs/logger.js, e2e/puppeteer-custom-environment.ts
=> [no ticket][risk=no] Puppeteer rework get Console messages func

ui/yarn.lock
Description:
Addresses https://github.com/advisories/GHSA-q8pj-2vqx-8ggc
---
=> [risk=low][no ticket] update css-what and depending packages

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
=> [risk=no][RW-6820] Fix AAR grace period

api/config/config_staging.json
Description:
Enable the access renewal flag on staging.
Once this is merged I will deploy to staging
---
=> [risk=no][RW-6781] Update aar flag on staging

api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
Description:
I missed a section in #5079
---
=> [risk=no][no ticket] Deprecate Beta Access in DbUser

e2e/utils/test-utils.ts, ui/src/app/services/sign-in.service.ts
- Log on successful access token sign-in
- Wait for global function to exist before calling
- Improve comments and add disclaimers for gotchas during debugging
=> [RW-6849][risk=no] Improve logging/robustness of access token sign-in

api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
=> [risk=no][RW-6703] Add AAR email test for grace period

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
I thought I tested this but this must have slipped in at the last second.. fixes some bugs in the plink codegen
---
=> [RW-6782][risk=no] Fix space and name bug in plink codegen

api/config/config_stable.json
Description:
Enable the access renewal flag in stable.
I will not merge this PR until I have verified the behavior on staging.
---
=> [risk=low][RW-6820]Turn on AAR flag in stable

api/db-cdr/prep-tables/make-prep-survey.py
Adding date to the file name when generating survey output files.
=> [RW-6845][risk=no] adding date to filename when generating survey output files

api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
=> [no ticket][risk=no] removing cb_survey_version

api/db-cdr/generate-cdr/make-bq-denormalized-search-events.sh
=> [no ticket][risk=no] remove cb survey version

api/config/config_preprod.json
=> [RW-6854][risk=low] enable genomics extraction in preprod

api/db-cdr/generate-cdr/bq-schemas/prep_concept.json, api/db-cdr/generate-cdr/bq-schemas/prep_concept_relationship.json, api/db-cdr/generate-cdr/bq-schemas/prep_physical_measurement.json, api/db-cdr/generate-cdr/bq-schemas/prep_survey.json
adding new schemas for prep tables.
=> [no ticket][risk=no] adding new schemas for prep tables

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [no ticket][risk=no] removing exit statement

ui/src/app/components/genomics-extraction-table.tsx
- Also changed the cursor to be a pointer when hovering over the ellipsis. 
Before
After
---
=> [RW-6786][risk=no] Genomics Extraction table menu actions style changes

api/src/main/webapp/WEB-INF/cron_perf.yaml, api/src/main/webapp/WEB-INF/cron_test.yaml
Reduces 140 errors in the test env, while fix is in progress.
=> [RW-6538][risk=no] Disable bulkAuditProjectAccess in test

api/src/main/resources/workbench-api.yaml, ui/src/app/components/copy-snippet-modal.tsx, ui/src/app/components/genomics-extraction-menu.tsx, ui/src/app/components/genomics-extraction-table.tsx
=> [RW-6786][risk=no] Genomic Extraction Table - View/Copy Path action

api/db-cdr/prep-tables/make-prep-survey.py
fixing make-prep-survey.py
The script was copying files to bucket before the csv writer was finished writing. Added a flush/close call at the end of each file output.
=> [no ticket][risk=no] fixing prep survey

ui/src/app/pages/data/data-set/genomic-extraction-modal.spec.tsx, ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx, ui/src/app/utils/time.ts
https://user-images.githubusercontent.com/1847690/122084821-2904bc80-cdd0-11eb-9fc1-19ebc5e33503.mov
---
=> [risk=no][RW-6745] Warn on dataset extraction if a previous extraction is pending / complete

.circleci/config.yml, e2e/app/page/google-login.ts, e2e/jest.config.js, e2e/libs/logger.js, e2e/tests/workspace/workspace-ui.spec.ts, e2e/tsconfig.json, e2e/utils/test-utils.ts
Tests will find and use workspaces that are older than 30 minutes.
=> [RW-6878][risk=no] Fix e2e workspace-ui test

api/db-cdr/generate-cdr/make-bq-prep-tables-bucket.sh, api/libproject/devstart.rb
created project.rb command to create a new bucket and copy csv files
`./project.rb make-prep-tables-bucket --new-cdr-version C2021Q2R2 --previous-cdr-version C2021Q2R1`
=> [RW-6828, RW-6829][risk=no] created project.rb command to create a new bucket and copy csv files

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [no ticket][risk=no] fixed issue with ICD10CM

api/db-cdr/prep-tables/make-prep-survey.py
fixed concept_code that wasn't showing up and the incorrect flagging in controlled & registered file
=> [risk=no][RW-6844]

ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx, ui/src/app/pages/data/cohort-review/participants-charts.tsx, ui/src/app/pages/data/cohort-review/query-report.component.tsx
Fixes issue where Cohort Description page in cohort review breaks if refreshed and only shows a blank page.
---
=> [RW-6732][risk=no] Fix blank Cohort Description page in cohort review

api/config/config_prod.json
Description:
Turns aar on in prod
Tested on staging and stable over the past 2 weeks.
---
=> [risk=low][RW-6781]Enable prod aar flag

api/config/cdr_config_perf.json, api/config/cdr_config_stable.json, api/config/cdr_config_staging.json, api/config/cdr_config_test.json
=> [no ticket][risk=no] bumping synth cdr

ui/src/app/pages/workspace/workspace-share.spec.tsx, ui/src/app/pages/workspace/workspace-share.tsx, ui/src/app/pages/workspace/workspace-wrapper/component.html, ui/src/app/pages/workspace/workspace-wrapper/component.ts
=> [RW-6920][risk=no] Disable access level dropdown for current user

api/config/cdr_config_preprod.json
=> [RW-6941][risk=no] bump alpha2 CDR indices

ui/src/app/pages/profile/profile-page.tsx
Description:
Tested locally 
~but Demo Survey updates are blocked on the backend by https://precisionmedicineinitiative.atlassian.net/browse/RW-6939~
and ready to merge
---
=> [risk=no][RW-6943] enable demographic survey update

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java, api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
=> [risk=no] Switch free tier checks from namespace -> Google project

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java, api/src/main/java/org/pmiops/workbench/db/model/DbDataset.java, api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java, api/src/test/java/org/pmiops/workbench/db/dao/DataSetDaoTest.java
https://user-images.githubusercontent.com/34481816/122969637-dc365e00-d35a-11eb-9973-cd4d25ffe62f.mov
---
=> [RW-6858][risk=no] Warning message is shown while deleting Concept Set used in invalid data set

api/config/cdr_config_local.json, api/config/cdr_config_preprod.json, api/config/cdr_config_prod.json, api/config/cdr_config_stable.json, api/config/cdr_config_staging.json, api/config/cdr_config_test.json, api/db/changelog/db.changelog-166-cdr-file-data-paths.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/db/model/DbAccessTier.java, api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java, api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java, api/src/main/java/org/pmiops/workbench/tools/cdrconfig/AccessTierVO.java, api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java, api/src/test/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapperTest.java
=> [RW-6747][risk=no] Runtime environment variables for extant file-based data

api/config/config_perf.json, api/config/config_preprod.json
Description:
Strawman - let's launch AAR into these envs with effectively no expiration date.  When we're ready to properly launch Preprod, adjust the expiryDays again: https://precisionmedicineinitiative.atlassian.net/browse/RW-6918
Benefits:
* we can remove the `enableAccessRenewal` logic and FF sooner
* lets us run the user expiration report to determine more reasonable timelines in these environments 
Downsides:
* if we have missed something in our backfills, users without completions will expire.  (I'm pretty confident we're OK, and a DB check would confirm this)
---
=> [risk=low][RW-6917] "prelaunch" AAR in Perf and Preprod by setting a 10 year expiry

ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/homepage/recent-workspaces.tsx, ui/src/app/pages/workspace/workspace-card.spec.tsx, ui/src/app/pages/workspace/workspace-card.tsx, ui/src/app/pages/workspace/workspace-library.spec.tsx, ui/src/app/pages/workspace/workspace-library.tsx, ui/src/app/pages/workspace/workspace-list.tsx, ui/src/app/pages/workspace/workspace-share.spec.tsx, ui/src/app/pages/workspace/workspace-share.tsx
I did some clean up while I was poking around. We were loading profile from various components unnecessarily.
---
=> [ticket=no][risk=no] Fix bug where workspace share from workspace card was missing an access level

api/src/main/webapp/WEB-INF/cron_test.yaml
Should hopefully run now, per #5149
=> [RW-6538][risk=no] Re-enable project audit cron in test

e2e/app/component/base-menu.ts, e2e/app/component/tiered-menu.ts, e2e/app/element/base-element.ts
Add retry click menuitem inside the menu `select` func.
=> [RW-6921][risk=no] e2e test: fix flaky menu function

api/config/config_prod.json, api/config/config_stable.json
Description:
feature flag flip: sendEmails = true for Stable and Prod
but not Preprod: https://precisionmedicineinitiative.atlassian.net/browse/RW-6918
---
=> [risk=low][RW-6703] Send AAR emails in Stable and Prod

api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
=> [risk=no][no ticket] update some of the text related to the WRD

.circleci/config.yml, .circleci/export-e2e-test-user-vars.sh
See [doc](https://docs.google.com/document/d/1rbAlU6CVgfh6R_o2BdD476AXrZR6qB7167yrhMf4KMA/edit?usp=sharing).
Created new e2e test users and updated CircleCI environment variables with new user emails (full email addresses with domain name).
=> [no ticket][risk=no] Update e2e test user emails

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/reporting/insertion/InsertAllRequestBuilderTest.java, api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
Description:
Tested locally by running `uploadReportingSnapshot`.
There's a companion PR https://github.com/all-of-us/workbench-terraform-modules/pull/26 but these can be merged independently.
---
=> [risk=no][RW-6881] Stop reporting obsolete user fields to the WRD

api/db-cdr/prep-tables/make-prep-survey.py
renamed files to what will be used in bigquery and had the files put under the date it was run against.
=> [RW-6908][risk=no]

ui/src/app/app.module.ts, ui/src/app/components/bug-report.tsx, ui/src/app/components/confirm-delete-modal.tsx, ui/src/app/pages/signed-in/component.spec.ts
The remaining components in `app.module.ts` are used either by WorkspaceWrapper, or by SignedInComponent.
=> [RW-6915][risk=no] rm dead Angular components

api/src/main/java/org/pmiops/workbench/mail/EmailSubstitutionField.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/instructionsemail/content.html, api/src/main/resources/emails/rt_access_expired_email/content.html, api/src/main/resources/emails/rt_access_threshold_email/content.html, api/src/main/resources/emails/welcomeemail/content.html
Description:
AAR expiration tomorrow
AAR expired
---
=> [risk=no][RW-6703] Italicize "All of Us" in emails

.circleci/choose-e2e-env.sh
CircleCI env variables for e2e test users have full email addresses now.
=> [no ticket][risk=no] Fix CircleCI script for e2e tests

api/db/changelog/db.changelog-168-rename-access-module-user-table.xml, api/db/changelog/db.changelog-169-add-institution-tier-requirement-tables.xml, api/db/changelog/db.changelog-170-add-access-tier-id-into-institution-tables.xml, api/db/changelog/db.changelog-master.xml
Description:
1. Add institution_tier_requirement table
2. add tier_id into institution_email_domain and institution_email_address tables
3. Drop access_module_user, and create a similar user_access_module
---
=> [RW-6925][risk=low]: Add institution tier requirement table also rename access_module_user 

ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
Before:
The error was caused by incorrect argument
https://user-images.githubusercontent.com/34481816/124050380-78f69c80-d9e8-11eb-809e-507750c5a895.mov
After:
https://user-images.githubusercontent.com/34481816/124050513-afccb280-d9e8-11eb-9253-5cf6e1a64201.mov
---
=> [RW-6979][risk=no]Fix survey answer with no value attributes error

ui/src/app/pages/signed-in/nav-bar.tsx
=> [risk=no][RW=6631] Remove aar reminder when on aar page

ui/package.json, ui/yarn.lock
Description:
Alternate solution to #5215 
---
=> [risk=no][no ticket] rm d3 package, which is apparently not used

ui/src/app/pages/workspace/workspace-card.tsx
Description:
This is no longer used, so remove it.
---
=> [risk=no][no ticket] rm loadingData state from workspace-card

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/model/DbUser.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java, api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
=> [risk=low][RW-4598] rm obsolete fields from Profile and DbUser

ui/src/app/components/side-nav.spec.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/signed-in/component.html, ui/src/app/pages/signed-in/component.ts, ui/src/app/pages/signed-in/nav-bar.tsx
- use ProfileStore in NavBar instead of pulling it in from SignedInComponent
- define constant props into NavBar
- put pass-through path-based functions in the component that actually uses them
- make everything a function component
---
=> [RW-6817][risk=no] Refactor nav-bar

ui/src/app/components/side-nav.spec.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/signed-in/component.html, ui/src/app/pages/signed-in/component.ts, ui/src/app/pages/signed-in/nav-bar.tsx
=> [RW-7007][risk=no] roll back nav bar changes

ui/src/app/pages/data/data-set/dataset-page.tsx
https://user-images.githubusercontent.com/34481816/124822372-cf5e6080-df3d-11eb-949a-36f6140117f3.mov
Clicking the icon will open a new tab and open the review page
---
=> [RW-6957][risk=no] UI: Provide link to cohort description from dataset builder

api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
Description:
Only affects the logging.  May help give us more context when we see problems.
---
=> [risk=low][no ticket] include contact email in AAR email logs

e2e/app/page/authenticated-page.ts, e2e/app/page/base-page.ts, e2e/app/text-labels.ts
=> use plain string urls in PR 5221 (ok to merge)

ui/src/app/pages/access/access-renewal.spec.tsx, ui/src/app/pages/access/access-renewal.tsx, ui/src/app/pages/admin/admin-review-workspace.spec.tsx, ui/src/app/pages/admin/admin-user-bypass.spec.tsx, ui/src/app/pages/admin/admin-user-bypass.tsx, ui/src/app/pages/admin/admin-users.spec.tsx, ui/src/app/pages/admin/admin-users.tsx, ui/src/app/pages/homepage/homepage.spec.tsx, ui/src/app/pages/homepage/homepage.tsx, ui/src/app/pages/homepage/registration-dashboard.spec.tsx, ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/pages/profile/profile-component.spec.tsx, ui/src/app/pages/profile/profile-component.tsx, ui/src/app/pages/workspace/workspace-about.spec.tsx, ui/src/testing/default-server-config.ts
Description:
UI portion of RW-7107. Wait one release cycle for the API portion for rollback safety.
Tested each of the changes pages via Local->Test with no problems.
---
=> [risk=low][RW-7017] rm UI code relating to enableDataUseAgreement 

e2e/.env.sample, e2e/app/component/table.ts, e2e/app/container.ts, e2e/app/element/radiobutton.ts, e2e/app/element/select.ts, e2e/app/text-labels.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/types.d.ts
=> [no ticket][risk=no] Minor update in e2e

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml
=> [RW-7010][risk=no] Create Feature Flag for standard /source work

ui/src/app/components/side-nav.spec.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/signed-in/component.html, ui/src/app/pages/signed-in/component.ts, ui/src/app/pages/signed-in/nav-bar.tsx
Nav bar works in test this time!
---
=> [RW-6817][risk=no] Refactor nav bar again

api/config/featured_workspaces_prod.json
Description:
Request: https://precisionmedicineinitiative.atlassian.net/browse/RW-7025
Instruction: https://docs.google.com/document/d/1qnN2035PtnzeHuzjKpPc1ooCHcwdXcBPybKvp5nUeXo/edit#
---
=> [RW-7025][risk=low] publish new feature workspace

.circleci/README.md
=> [risk=no][RW-6861] Update .circleci README

.circleci/config.yml
=> [risk=no][no ticket] Add comments for the when/unless logic for connect_local_api

api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
Remove references to the July 1 AAR enforcement launch date since it is now in the past
---
=> [risk=low][no ticket] Remove the AAR grace-period logic

ui/src/app/app-routing.tsx
=> [risk=low][RW-6922] rm UI code referencing enableAccessRenewal FF

api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
=> [risk=no][RW-6923] rm uses of the sendEmails AAR feature flag

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
Dataset preview not working properly when cohort contains parent procedure with no children per 
https://precisionmedicineinitiative.atlassian.net/browse/RW-7053
=> RW-7053 bug returning parent with no children 

api/db-cdr/generate-cdr/make-bq-prep-survey.sh
creating the prep_survey table from redcap csv files
=> [RW-6909][risk=no] creating the prep_survey table from redcap csv files

api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
In this PR, we extend the getRuntime API to support getting the diskConfig for the runtime with PD
=> [RW-7047][risk=low] GetRuntime API support getting the diskConfig for PD

api/src/main/java/org/pmiops/workbench/api/UserController.java, ui/src/app/pages/workspace/workspace-edit.tsx, ui/src/app/utils/workbench-gapi-client.ts
Description:
Also print an helpful exception when fetching billing accounts
---
=> [no ticket][risk=no]: Fix incorrect usage of workspace namespace which should be google project

api/db-cdr/generate-cdr/make-bq-denormalized-tables.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh, api/libproject/devstart.rb
=> [no ticket][risk=no] fix CDR indices build for DB

ui/src/app/pages/signed-in/signed-in.tsx
=> [no ticket][risk=no] allow registered users to access SignedInRoutes

api/src/main/java/org/pmiops/workbench/api/CdrVersionsController.java, api/src/main/java/org/pmiops/workbench/api/InstitutionController.java, api/src/main/java/org/pmiops/workbench/api/UserController.java, api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java, api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
Description:
Remove 3 endpoints which are no longer referenced by the UI because they have been replaced by newer versions.
~One of these is still referenced by the Perf tests, so we should wait until that reference is removed ( https://github.com/broadinstitute/mcnulty/pull/266 ) and a Perf run completes successfully with the new version.~ **GOOD TO GO**.
---
=> [risk=low][no ticket] Remove deprecated endpoints and related code

api/src/main/webapp/WEB-INF/queue.yaml
Description:
Slightly easier to read/understand, IMO
Hopefully this is still valid syntax
---
=> [risk=no][no ticket] group and space queue.yaml for readability

e2e/resources/workbench-config.ts, e2e/types.d.ts
=> [risk=no][no ticket] more specific types for e2e configs

api/db-cdr/generate-cdr/bq-schemas/ds_data_dictionary.json, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-data-dump.sh, api/db-cdr/generate-cdr/make-bq-data.sh, api/db-cdr/generate-cdr/make-bq-prep-survey.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
moving static prep tables into CDR indices build
=> [RW-7081][risk=no] moving static prep tables into CDR indices build

api/db-cdr/generate-cdr/make-bq-prep-survey.sh, api/db-cdr/prep-ppi-csv-files/README.md, api/db-cdr/prep-ppi-csv-files/make-prep-ppi-csv-files.py
move the location of redcap files for survey processing.
gs://all-of-us-workbench-private-cloudsql/redcap
=> [no ticket][risk=no] move the location of redcap files

ui/src/app/pages/workspace/research-purpose.tsx
Open to other wordsmithing:
- as follows:
- with the following:
- through the following means:
=> [risk=no] Fix grammatical issue on research finding dissemination

api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
rearranging method calls to make code easier to read.
=> [no ticket][risk=no] cleanup CB search by term

api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java, api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
removing a few unused variables.
=> [no ticket][risk=no] Data Apps Controller cleanup

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
survey sql cleanup and fixed a small bug in survey synonyms
=> [no ticket][risk=no] survey sql cleanup

api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java, api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/cohort-review/participants-charts.tsx, ui/src/app/pages/data/cohort-review/query-report.component.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
=> [RW-7073][noTicket] Cohort description: Use cohort Id instead of cohort review Id 

ui/src/app/pages/admin/admin-institution-edit.tsx
Description:
The initial version filter out the empty line in list of email addresses. But we should keep it until we 'blur' out. 
---
=> [no ticket][risk=no]: Fix can not enter newline between email address/domains

ui/src/app/pages/homepage/homepage.tsx
Description:
RAS Linking can auto link eRA in backend, the previous PR forget to set this state here. 
Even this page will be replaced by new CT registration page soon, it is good to add that here for testing/development purpose
---
=> [RW-6933][risk=no]Auto link eRA Commons in RAS linking flow

ui/src/app/cohort-search/list-search/list-search.component.tsx
=> [RW-7129][risk=no]  Fix Concept Id value Link on Cohort Builder to databrowser

ui/src/app/pages/analysis/runtime-panel.tsx
=> [risk=no] rm excess space literals in runtime delete panel

api/db-cdr/generate-cdr/bq-schemas/cb_criteria_menu.json, api/db-cdr/generate-cdr/bq-schemas/cb_menu.json, api/db-cdr/generate-cdr/build-cdr-indices.sh, api/db-cdr/generate-cdr/make-bq-cb-menu.sh, api/db-cdr/generate-cdr/make-bq-data-dump.sh, api/db-cdr/generate-cdr/make-bq-data.sh, api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
adding cb_criteria_menu inline in CDR indices
=> [RW-7082][risk=no] adding cb_criteria_menu inline in CDR indices

api/db-cdr/generate-cdr/make-bq-cb-menu.sh
adding comment and changing execute permission on file
=> [no ticket][risk=no] adding comment and changing execute permission on file

api/src/main/java/org/pmiops/workbench/api/InstitutionController.java, api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java, api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java, api/src/test/java/org/pmiops/workbench/institution/InstitutionTierConfigMapperTest.java, api/src/test/java/org/pmiops/workbench/institution/VerifiedInstitutionalAffiliationMapperTest.java, api/src/test/java/org/pmiops/workbench/testconfig/UserServiceTestConfiguration.java, api/tools/src/main/java/org/pmiops/workbench/tools/institutions/LoadInstitutions.java
Description:
and a few other misc lint/cleanups
---
=> [risk=low][no ticket] Don't validate emails for NO_ACCESS

api/db-cdr/changelog-data/db.changelog-1.xml, api/db-cdr/changelog-schema/db.changelog-master.xml, api/db-cdr/changelog-schema/db.changelog-v2-2-cb_menu.xml, api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cdr/dao/CBMenuDao.java, api/src/main/java/org/pmiops/workbench/cdr/model/DbCBMenu.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBMenuDaoTest.java, ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx, ui/src/testing/stubs/cohort-builder-service-stub.ts
**Default**: Using method findCriteriaMenuOld
If we update UI to use findCriteriaMenu
---
=> [RW-7109][risk=no]  API - Build new API method and menu table that includes standard flag

api/db-cdr/changelog-schema/db.changelog-master.xml, api/db-cdr/changelog-schema/db.changelog-v2-3-domain_card.xml
adding domain_card table to cloudsql cdr database.
=> adding domain_card table

ui/src/app/pages/admin/admin-user.tsx, ui/src/app/pages/login/account-creation/account-creation-institution.tsx, ui/src/app/utils/institutions.tsx
Description:
Followup to #5323 - update a few "DUA" references
---
=> [risk=no][no ticket] remove/rename a few DUA references

ui/src/app/pages/homepage/recent-resources.tsx
This is potentially causing the homepage to fail rendering and show a blank page.
---
=> [risk=no][RW-7143] Filter out recent resources that the user doesnt have access to

api/db-cdr/generate-cdr/bq-schemas/domain_card.json, api/db-cdr/generate-cdr/make-bq-data-dump.sh, api/db-cdr/generate-cdr/make-bq-data.sh
adding domain_card to CDR indices
=> [RW-7114][risk=no] adding domain_card to CDR indices

ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/components/app-router.tsx, ui/src/app/pages/data/concept/concept-search.tsx, ui/src/app/utils/stores.tsx
=> Replace navigation-guard functionality with react-router Prompt

api/db-cdr/generate-cdr/build-cdr-indices.sh, api/db-cdr/generate-cdr/make-bq-criteria-tables.sh, api/db-cdr/generate-cdr/make-bq-static-prep-tables.sh
moving static prep table creation into it's own shell script
=> [no ticket][risk=no] moving static prep table creation into it's own shell script

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
=> [risk=no][RW-6922] rm enableAccessRenewal FF

api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java, api/src/main/java/org/pmiops/workbench/db/dao/BillingProjectBufferEntryDao.java
=> [risk=low][no ticket] Update Billing Buffer metrics: report combinations with 0 projects

api/db-cdr/generate-cdr/build-cdr-indices.sh, api/db-cdr/generate-cdr/make-bq-cb-survey-version.sh
creating cb_survey_version table inline in CDR indices
=> [RW-7083][risk=no] creating cb_survey_version table inline in CDR indices

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
=> [RW-7120][risk=no]API - duplicate the following dao calls in CBCriteriaDao (search)

api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java, api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
=> [RW-7122][risk=no] API - duplicate the following dao calls in CBCriteriaDao (find domain counts)

api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
removing old reference to cb_survey_version
=> [no ticket][risk=no] removing old reference to cb_survey_version

api/db-cdr/generate-cdr/make-bq-cb-survey-version.sh
fix failing insert statement in cdr indices build
=> [no ticket][risk=no] fix failing insert statement in cdr indices build

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
These have been unused for some time.
=> [risk=no] rm unused config values

api/db-cdr/generate-cdr/make-bq-data.sh
fix CDR indices failure. Script is referencing table in wrong project and dataset.
=> [no ticket][risk=no] fix CDR indices failure

ui/src/app/pages/homepage/homepage.tsx, ui/src/app/pages/homepage/quick-tour-modal.tsx, ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/pages/login/account-creation/account-creation-institution.tsx, ui/src/app/pages/login/account-creation/account-creation-success.tsx, ui/src/app/pages/login/account-creation/account-creation-tos.tsx, ui/src/app/pages/login/account-creation/account-creation.tsx, ui/src/app/pages/profile/data-user-code-of-conduct.tsx, ui/src/app/pages/profile/profile-component.tsx, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/app/pages/workspace/workspace-edit-text.tsx, ui/src/app/pages/workspace/workspace-edit.tsx, ui/src/app/pages/workspace/workspace-library.tsx, ui/src/app/pages/workspace/workspace-share.tsx
Description:
also some import grouping/linting where I'm adding imports anyway
---
=> [risk=no][no ticket] Use the <AoU/> and <AoUTitle/> components wherever possible

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx, ui/src/testing/stubs/cohort-builder-service-stub.ts
=> [noTicket][risk=no]Use name CBMenu instead of CriteraMenu in workbench yaml

.circleci/config.yml, e2e/app/modal/share-modal.ts, e2e/tests/nightly/registration.spec.ts, e2e/tests/notebook/notebook-create-python.spec.ts, e2e/tests/user/login.spec.ts
Run yarn build & lint Puppeteer typescript before run e2e tests.
Ran `yarn lint --fix`.
=> [RW-7138][risk=no] circleci config update for e2e

api/config/cdr_config_preprod.json
Adding new RT CDR to preprod. Requesting approval to publish BQ dataset and do an out of band push for preprod.
https://precisionmedicineinitiative.atlassian.net/browse/PD-6475
=> [no ticket][risk=no] adding new RT CDR to preprod

e2e/README.md
Description:
No real changes: formatting only.
---
=> [risk=no][no ticket] Resolve e2e readme codacy complaints by running IntelliJ "Code Cleanup"

api/db-cdr/generate-cdr/build-cdr-indices.sh, api/db-cdr/generate-cdr/import-cdr-indices-to-cloudsql.sh
Adding data_browser arg to import
=> [no ticket][risk=no] Adding data_browser arg to import

ui/src/app/pages/access/access-renewal.spec.tsx, ui/src/app/pages/access/access-renewal.tsx, ui/src/app/pages/profile/profile-component.tsx, ui/src/app/signed-in-app-routing.tsx, ui/src/app/utils/access-utils.spec.tsx, ui/src/app/utils/access-utils.tsx, ui/src/testing/stubs/profile-api-stub.ts
Description:
I verified dual write worikng by query like:
https://docs.google.com/document/d/1V3V5k-cRfEcwScPMs9AIeNDyJieDdk-vZUszCQ2pZaY/edit#
---
=> [RW-7034]: use AccessModuels for AAR and remove use of ReneableAccessModules

api/libproject/devstart.rb
=> [no ticket][risk=no] adding db arg to devstart.rb

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/InstitutionColumnValueExtractor.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java, api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
=> [RW-6936][risk=low] upload RT tier requirement into institution reporting table.

ui/src/app/pages/data/data-set/dataset-page.tsx
=> Remove angular dataset

ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/utils/navigation.tsx
=> remove angular navigate

ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/admin/admin-institution-edit.tsx, ui/src/app/pages/admin/admin-workspace-search.tsx, ui/src/app/pages/data/cohort-review/detail-header.component.tsx, ui/src/app/pages/data/cohort-review/query-report.component.tsx, ui/src/app/pages/homepage/homepage.tsx, ui/src/app/pages/workspace/new-workspace-button.tsx, ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx, ui/src/app/pages/workspace/workspace-nav-bar.tsx
Description:
Tested locally
* WS sidebar - edit
* WS sidebar - dupe
* WS sidebar - delete
* Admin Inst Edit - back
* Homepage - create workspace
* Workspaces List - create workspace
* Workspace Nav Bar CDR Upgrade Modal
* Workspace Nav Tab
I'm not really sure how Cohort Review works but they're in the same pattern so I'm confident they're OK too
---
=> [risk=no][no ticket] fix non-idiomatic navigate()s

ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/routing/app-routing.tsx, ui/src/app/utils/authentication.tsx, ui/src/app/utils/navigation.tsx
=> Address angular2react TODOs and refactor app-routing

api/tools/src/main/java/org/pmiops/workbench/tools/BackfillWorkspacesToRdr.java
In project.rb, --limit is optional. Currently the tool NPE's if --limit is unset.
=> [risk=no] Fix optionality of backfill --limit flag

ui/src/app/utils/access-utils.spec.tsx
=> [RW-7034][risk=no]: Add a missing test with non-expirable modules

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
=> [RW-7113][RISK=NO]API - create new call findCriteriaByDomain

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/webapp/static/initialize_notebook_runtime.sh, e2e/resources/python-code/gsutil.py, e2e/tests/notebook/notebook-create-python.spec.ts
Attempt 3...
Adds regression test coverage to Puppeteer.
Puppeteer test passes locally.
=> [RW-7172][risk=low] Fix gcloud/gsutil on latest notebooks image

ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx, ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.tsx, ui/src/app/components/app-router.spec.tsx, ui/src/app/components/app-router.tsx, ui/src/app/components/copy-modal.spec.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/admin/admin-user.tsx, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/analysis/notebook-redirect.tsx, ui/src/app/pages/data/cohort-review/cohort-review.tsx, ui/src/app/pages/data/cohort/cohort-actions.tsx, ui/src/app/pages/data/concept/concept-list.tsx, ui/src/app/pages/data/concept/concept-navigation-bar.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
=> remove angular self review edits

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
=> [risk=no][no ticket] parameterize to resolve warnings

api/db-cdr/generate-cdr/libproject/devstart.rb, api/libproject/gcloudcontext.rb
After acting as the SA for BigQuery interactions in publish-cdr, publish-wgs-cdr, revert to the original auth user.
=> [RW-3768][risk=no] Revert auth after CDR publishing

api/config/config_local.json, api/config/config_perf.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
Description:
It would be #workbench-notification-test
---
=> [RW-7132][risk=low]: Use slack channel to receive testing emails  

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/resources/workbench-api.yaml
=> [RW-7123][risk=no]API - refactor API method findDomainCount to add new standard flag as parameter

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [RW-7084][risk=no] Removing clinical labs tree

api/config/featured_workspaces_preprod.json
Description:
https://precisionmedicineinitiative.atlassian.net/browse/RW-7163
---
=> [RW-7163][risk=low]: Publish few feature workspaces in preprod

api/db-cdr/generate-cdr/make-bq-data.sh
removing source cards for domains
=> [RW-7196][risk=no] removing source cards for domains

api/src/main/java/org/pmiops/workbench/mail/EmailSubstitutionField.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/setup_gcp_billing_account_email/content.html, api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
=> [no ticket][risk=no]: Fix few errors in billing setup email

ui/src/app/pages/data/concept/concept-homepage.tsx
If `enableStandardSourceDomains` flag is enabled, call `findDomainCountByStandardSource` else call `findDomainCount`.
---
=> [RW-7192][risk=no] Use findDomainCountByStandardSource endpoint when flag enabled

api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java, api/src/main/resources/rdr.yaml
Description:
Adds the accessTier field to the rdrExport.
Tested this locally by hitting the endpoint and inspecting the response
---
=> [RW-6775][risk=low] Add access tier to RDR export

e2e/libs/page-events-helper.ts
`/data-set/domainValues/*` api responses are clustering up test log.
=> [no ticket][risk=no] Do not log data-set api response in test

api/config/featured_workspaces_preprod.json
Description:
Request: https://precisionmedicineinitiative.atlassian.net/browse/RW-7163
---
=> [RW-7163][risk=low] publish phenotypebreastcancer feature workspace

e2e/app/component/data-resource-card.ts, e2e/app/element/base-element.ts, e2e/app/modal/base-modal.ts, e2e/app/page/authenticated-page.ts, e2e/app/page/notebook-cell.ts, e2e/app/page/notebook-page.ts, e2e/package.json, e2e/tests/nightly/dataproc-to-gce.spec.ts, e2e/tests/notebook/notebook-create-python.spec.ts, e2e/tests/notebook/notebook-reader-actions.spec.ts
Most recent CircleCI [failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/13049/workflows/b2aa5c0c-87c7-4bf4-af99-3d1d14dc69ca/jobs/158863).
Write more resilient and stable test functions. Adding logging to aid troubleshooting test failures in future.
=> [RW-7193][risk=no] flaky e2e notebook tests

ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
=> [RW-7203][RW-7202][risk=no] null check everything

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ConfigController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/access/access-renewal.tsx, ui/src/testing/default-server-config.ts
Description:
This change moves the hard coded `LOOKBACK_PERIOD` to the configuration.
---
=> [RW=6777][risk=no] Add lookbackPeriod to config for AAR

ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/analysis/notebook-redirect.spec.tsx, ui/src/app/pages/analysis/runtime-panel.spec.tsx, ui/src/app/pages/analysis/runtime-panel.tsx, ui/src/app/routing/app-routing.tsx, ui/src/app/utils/leo-runtime-initializer.tsx, ui/src/app/utils/runtime-utils.spec.tsx, ui/src/app/utils/runtime-utils.tsx, ui/src/app/utils/stores.tsx
=> [RW-7155][risk=no] Fix runtime panel defaults improperly populating during runtime load

api/db-cdr/generate-cdr/init-new-cdr-db.sh, api/db/run-migrations.sh
Fix stdin redirection for certain machines - Chenchal was hitting this issue. This is a cleaner pattern anyways, since it doesn't require mounting the create_db.sql file as a volume.
I'm out next week,  so feel free to merge for me if I'm out when this is approved.
=> [risk=no] docker DB creation redirect fix

e2e/app/page/workspace-base.ts
Description:
https://github.com/all-of-us/workbench/pull/5444 breaks our test
---
=> [no ticket] fix a test for AoU free tier billing account name

ui/src/app/routing/signed-in-app-routing.tsx
=> [risk=no][ticket=no] Turn comment into actual comment

ui/src/app/pages/admin/admin-institution-edit.tsx
=> [risk=no][no ticket] stick thing in componentDidUpdate

api/src/main/java/org/pmiops/workbench/db/dao/UserService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java, api/src/main/java/org/pmiops/workbench/profile/ProfileService.java, api/src/main/resources/workbench-api.yaml
Description:
I did not find any usage for RenewableAccessModule, so should be safe to delete
---
=> [RW-7217][risk=low] Cleanup RenewableAccessModule and ModuleTimes

e2e/app/element/base-element.ts, e2e/app/page/workspaces-page.ts, e2e/tests/conceptsets/copy-to-workspace.spec.ts, e2e/tests/nightly/dataproc-to-gce.spec.ts, e2e/tests/nightly/gce-to-dataproc.spec.ts, e2e/tests/nightly/owner-copy-to-workspace.spec.ts, e2e/tests/nightly/runtime.spec.ts, e2e/utils/test-utils.ts
=> [no ticket][risk=no] Update e2e tests

e2e/tests/datasets/export-to-notebook.spec.ts
Re-enable the test which was failing due to the Sam backlog by reverting #5482
Description:
---
=> [risk=no][no ticket] Revert "disable export-to-notebook.spec (#5482)"

e2e/app/component/concept-domain-card.ts, e2e/app/element/base-element.ts, e2e/app/modal/share-modal.ts, e2e/app/page/conceptset-page.ts, e2e/tests/conceptsets/conceptset-edit-rename.spec.ts, e2e/tests/notebook/notebook-reader-actions.spec.ts, e2e/tests/user/registration-ui.spec.ts
Share user typing 4 char at a time.
https://user-images.githubusercontent.com/35533885/130496363-f297d08e-ebdb-4b5d-9393-d3391b7883ea.mov
Clear and type issue.
https://user-images.githubusercontent.com/35533885/130501585-04b13111-af64-4a3b-b877-2fc09ffbc91a.mov
=> [no ticket][risk=no] e2e clean up base-element file

ui/src/app/pages/homepage/registration-dashboard.tsx, ui/src/app/pages/homepage/two-factor-auth-modal.spec.tsx, ui/src/app/pages/homepage/two-factor-auth-modal.tsx
So I can reuse it in DataAccessRequirements (soon).
No functional changes.
---
=> [risk=low][RW-7089] Extract TwoFactorAuthModal from RegistrationDashboard

.circleci/config.yml
Hoping to reduce e2e job total run time.
=> [no ticket][risk=no] Improve circleci e2e job configuration

api/libproject/cloudsqlproxycontext.rb, api/libproject/devstart.rb, api/libproject/mysql_docker.rb
Missed a few other instances where I was directly calling mysql.
=> [risk=no] More dockerization of mysql

api/db-cdr/generate-cdr/build-cdr-indices.sh
adding the cb_survey_version table into the DataBrowser indices build
=> [no ticket][risk=no] updating the DB CDR indices build.

api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
=> [no ticket][risk=no] fixing db indices build

ui/src/app/pages/admin/admin-workspace.tsx
Caused by a lack of a conditional check in componentDidUpdate
---
=> [RW-7249][risk=no] Fix infinite loading bug in admin workspaces

api/config/cdr_config_prod.json
bumping CDR version from `fc-aou-cdr-prod.R2020Q4R3` to `fc-aou-cdr-prod.R2021Q3R2`
=> RW-7190 bumping CDR version

ui/src/app/pages/workspace/workspace-wrapper.tsx
=> [risk=low][RW-7252] actually populate all the stores!!

e2e/tests/nightly/account-creation.spec.ts, e2e/tests/user/create-account-ui.spec.ts
=> [risk=no][no ticket] Rename some e2e tests from "registration" to "account creation"

api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java, e2e/.env.sample, e2e/tests/nightly/user-access.spec.ts
=> [RW-7234] support RAS module in set-access-module-timestamps

ui/src/app/pages/analysis/runtime-panel.tsx
=> [RW-7244][risk=no] Runtime Panel shows warning msg div when no warning message exists

api/config/cdr_config_prod.json
Rollback the RT CDR 
Decided to delay the announcement
=> [no ticket][risk=no] rollback RT CDR

.circleci/config.yml
=> [no ticklet][risk=no] update circleci config

ui/package.json
=> [no ticket][risk=no] Stop browser tab open from interrupting you

ui/src/app/components/app-router.tsx, ui/src/app/pages/homepage/homepage.tsx
=> [risk=low][RW-7266] Restore the workbenchAccessTasks functionality by stealing from #5536

ui/src/app/components/icons.tsx, ui/src/app/pages/homepage/data-access-requirements.tsx
I don't know how or why this works.  #yolo
---
=> [risk=low][no ticket] fix broken icons by magic

ui/src/app/components/app-router.tsx
=> [risk=no][no ticket] remove inline hook

ui/src/app/pages/profile/profile-component.spec.tsx
=> [risk=no][no ticket] Fix the UI unit test I just broke

ui/src/app/components/login-gov-ial2-notification.tsx
=> [no ticket][risk=no]: Change IAL enforcement date in notification

api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/mail/MailService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/dollarthresholdemail/content.html, api/src/main/resources/emails/freecreditsexpirationemail/content.html, api/src/main/resources/emails/instructionsemail/content.html, api/src/main/resources/emails/rt_access_expired_email/content.html, api/src/main/resources/emails/rt_access_threshold_email/content.html, api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java, api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Add usernames to 4 emails sent by the RW: free credits warning and expiration and AAR warning and expiration.
Before and after examples can be seen here: https://docs.google.com/document/d/1ksfIb9fgJMETz4yVA25TGafzX7-ddg7ES-Fm0pdbjcA/edit# 
---
=> [risk=low][RW-7008] Include usernames in most emails sent to users

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
GATK PRs
- https://github.com/broadinstitute/gatk/pull/7458
- https://github.com/broadinstitute/gatk/pull/7457
---
=> [risk=no][RW-7052][RW-6806] Update extraction WDL to bring in BQ label and manifest file changes

e2e/.env.circleci.local, e2e/.env.circleci.perf, e2e/.env.circleci.staging, e2e/.env.circleci.test, e2e/.env.sample, e2e/resources/workbench-config.ts, e2e/types.d.ts
=> [RW-7234][risk=no]add login.gov related env vars for e2e test

api/config/featured_workspaces_prod.json
Description:
https://precisionmedicineinitiative.atlassian.net/browse/RW-7019
---
=> [RW-7019][risk=low]: Publish a new prod feature workspace

ui/src/environments/environment.perf.ts, ui/src/environments/environment.staging.ts
=> [risk=low][RW-7089] Enable DAR in Perf and Staging to help with testing

api/genomics/docs/updating_extraction_wdl.md
=> [risk=no][ticket=no] Docs on how to update the extraction WDL

ui/src/app/pages/access/access-renewal.spec.tsx, ui/src/app/pages/access/access-renewal.tsx, ui/src/app/utils/access-utils.tsx
There should be no actual changes here.
I'm planning to reuse some of this for https://precisionmedicineinitiative.atlassian.net/browse/RW-7015.
Tested locally by viewing test/access-renewal and local-test/access-renewal side by side with a user in expired and non-expired states.
---
=> [risk=low][no ticket] Minor refactoring of AAR page to help me extract a piece later

ui/yarn.lock
#5567 should have been e2e changes only, but some UI package changes in yarn.lock were accidentally included
---
=> [risk=no][no ticket] revert the UI packages accidentally installed by #5567

api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
Ensure `WORKSPACE_BUCKET` is always available.
Tested manually.
=> [RW-7096][risk=no] Add explicit WORKSPACE_BUCKET variable to env vars

api/db-cdr/generate-cdr/import-cdr-indices-to-cloudsql.sh
=> [no ticket][risk=no] fixing db arg

ui/package.json, ui/yarn.lock
Description: 
[immer](https://github.com/all-of-us/workbench/security/dependabot/ui/yarn.lock/immer/open) needs an upgrade to 9.0.6+ but `react-scripts@4.0.3` is the latest version and it requires `react-dev-utils "^11.0.3"` which can only get us up to `immer "8.0.1"`
[brwserslist](https://github.com/all-of-us/workbench/security/dependabot/ui/yarn.lock/browserslist/open) needs an upgrade to 4.16.5+ but react-dev-utils again can only get us to `browserslist "4.14.2"`
[glob-parent](https://github.com/all-of-us/workbench/security/dependabot/ui/yarn.lock/glob-parent/open) needs an upgrade to 5.1.2+ and it's a similar story.
The developer of create-react-app (which includes react-scripts and react-dev-utils) says basically don't worry about these: …
=> [risk=low][no ticket] Resolve some UI vulnerabilities

api/config/config_local.json, api/config/config_test.json
Description:
Local and Test API servers talks to DEV Terra, I will merge this right after Terra PPW in Terra Dev
---
=> [RW-7278][risk=low]: Enable v2 billing feature flag when Terra Dev in PPW
