- e2e/tests/datasets/dataset-create.spec.ts
`beforeEach` block is wrong because last test log in by a different function, `signInAs`.
> [no ticket][risk=no] Fix Puppeteer dataset-create test login issue

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
> [RW-6820][risk=no] Set EOD June 30 2021 as the earliest access module expiration

- ui/package.json
- ui/yarn.lock
Description:
This change (originally part of #5035) may be the cause of recent e2e test failures.
Specifically, @calbach noticed that the JS console recently started showing the text `[WDS] Live Reloading enabled.`.  I was able to find that this change was #5035 via the wonderful `git bisect` and did a crude revert at #5083.  My suspicion is that we can be a little more precise and revert the specific change to Webpack Dev Server (WDS) in isolation.
FYI @aweng98 
---
> [risk=low][no ticket] Revert the forced upgrade of webpack-dev-server

- e2e/jest.test-setup.ts
Handling error thrown on rare occasion during getting JS Console messages. Test fails without handing. [CircleCI job](https://app.circleci.com/pipelines/github/all-of-us/workbench/10872/workflows/e11f53ed-f504-451d-b0d7-52519f82326d/jobs/143776/parallel-runs/0?filterBy=FAILED).
```
'Error: Execution context was destroyed, most likely because of a navigation.\n' +
'    at rewriteError (/home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:261:23)\n' +
'    at runMicrotasks (<anonymous>)\n' +
'    at runNextTicks (internal/process/task_queues.js:62:5)\n' +
'    at listOnTimeout (internal/timers.js:523:9)\n' +
'    at processTimers (internal/timers.js:497:7)\n' +
'    at ExecutionContext._evaluateInternal …
```
> [no ticket][risk=no] Puppeteer handling error: Execution context was destroyed

- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
Description:
_No functional changes. Does not satisfy RW-6827._
In my efforts to understand the current state of the world of Access Modules, I found that many DbUser fields are no longer used or can be removed (as was also observed by tech debt tickets [RW-4598](https://precisionmedicineinitiative.atlassian.net/browse/RW-4598) and [RW-5628](https://precisionmedicineinitiative.atlassian.net/browse/RW-5628)).  I'd like to start that cleanup by adding a bit of warning information, with the intention to return to it soon.
---
> [risk=no][RW-6827] Group DbUser fields by category and status

- ui/package.json
- ui/yarn.lock
Description:
Addresses https://github.com/advisories/GHSA-w7rc-rwvf-8q5r / [SNYK-JS-NODEFETCH-674311](https://app.snyk.io/vuln/SNYK-JS-NODEFETCH-674311)
Portable-fetch [hasn't seen an upgrade in 4 years](https://www.npmjs.com/package/portable-fetch), and the latest version depends on node-fetch v1, which has not been patched.  node-fetch v2 has been patched, so ... can we force an upgrade to v2?
Testing this locally, it appears that we can.
---
> [risk=low][no ticket] Force node-fetch upgrade to 2.6.1 to address vulnerability

- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/selection-list/selection-list.component.tsx
Fixes issue where Save Criteria button was still disabled after changing the modifiers of a search item
---
> [RW-6582][risk=no] Fix save criteria button when updating modifiers

- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
Uses in-memory search, same as physical measurements tree
---
> [RW-6761][risk=no] Add search bar back to visits tree in CB

- ui/yarn.lock
Description:
Upgrades path-parse to 1.0.7 to address https://app.snyk.io/vuln/SNYK-JS-PATHPARSE-1077067
---
> [risk=low][no ticket] bump path-parse to address vuln

- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- Only show 'Clinical' or 'Lab' node depending in which subtype was selected from the list search
- When searching in the hierarchy view, show results only from the selected subtype
- Hide the code for the top-level 'Clinical' and 'Lab' nodes
Show only top Clinical node when criteria of subtype CLIN are selected:
https://user-images.githubusercontent.com/40036095/121389653-43dbba80-c912-11eb-8a14-6533fca92b7f.mov
Show only top Lab node when criteria of subtype LAB are selected:
https://user-images.githubusercontent.com/40036095/121389764-58b84e00-c912-11eb-8ac4-855fb3319d43.mov
---
> [RW-6762][risk=no] Show only selected subtype in Measurements hierarchy in CB

- e2e/jest.test-setup.ts
- e2e/libs/logger.js
Better JS Console messsage grouping to make test log less cluttered and easier to read.
Before:
```
console.log
INFO: [6/10/2021, 13:35:26] - Page Console: "[Local->Test] R-7556797943 | All of Us Researcher Workbench"
actions
at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)
console.log
INFO: [6/10/2021, 13:35:26] - Page Console: "[Local->Test] R-7556797943 | All of Us Researcher Workbench"
jupyter-notebook:find-and-replace
at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)
console.log
INFO: [6/10/2021, 13:35:26] - Page Console: "[Local->Test] R-7556797943 | All of Us Researcher Workbench"
does not exist, still binding it in case it will be defined later...
at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23) …
```
> [no ticket][risk=no] Improve e2e JS console

- api/src/main/java/org/pmiops/workbench/access/AccessTierService.java
- api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserAccessTierDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
Users with ACCESS_CONTROL_ADMIN Authority can call a new endpoint `/v1/admin/accessExpirations` which produces a list of users and their AAR expiration times.  Output looks like (prettyprinted)
```
[
{
"userName": "joel-local@fake-research-aou.org",
"contactEmail": "thibault@broadinstitute.org",
"givenName": "Joel",
"familyName": "Local",
"expirationDate": "2021-07-01T00:00:00Z"
},
{
"userName": "puppetjoel2@fake-research-aou.org",
"contactEmail": "thibault@broadinstitute.org",
"givenName": "Puppet Joel",
"familyName": "2",
"expirationDate": "2021-07-01T00:00:00Z"
}
]
```
---
> [risk=low][RW-6689] Add an endpoint which returns a user expiration date report (as JSON)

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
I thought of a few improvements right after merging #5102 
* rename UserAccessExpirations to singular
* better Optional streaming via flatMap
---
> [risk=low][RW-6689] improvements to getRegisteredTierAccessExpirations

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
- api/db-cdr/generate-cdr/validate-prerequisites-exist.sh
updating criteria generation code to generate icd9/10 trees via OMOP instead of from prep_criteria. Leaving only CPT4 in prep_criteria and moving physical_measurement and survey criteria out to their own files/table. Creating prep_criteria_ancestor on the fly, not as a seed table. Updating validation script to accomodate new files
> [RW-6832][risk=no] updating criteria generation code

- api/db-cdr/generate-cdr/libproject/devstart.rb
Description:
Published CDRs now have labels indicating which access tier they belong to.  If the publisher attempts to publish a dataset to the wrong tier, an exception is raised.
```
Traceback (most recent call last):
9: from /w/api/db-cdr/generate-cdr/project.rb:6:in `<main>'
8: from /w/aou-utils/workbench.rb:61:in `handle_argv_or_die'
7: from /w/aou-utils/utils/common.rb:86:in `handle_or_die'
6: from /w/api/db-cdr/generate-cdr/libproject/devstart.rb:200:in `block in <top (required)>'
5: from /w/api/db-cdr/generate-cdr/libproject/devstart.rb:169:in `publish_cdr'
4: from /w/api/db-cdr/generate-cdr/libproject/devstart.rb:40:in `service_account_context_for_bq'
3: from /w/aou-utils/serviceaccounts.rb:60:in `run'
2: from /w/api/db-cdr/generate-cdr/libproject/devstart.rb:45:in `block in …
```
> [risk=low][RW-6240] Add a tier label safety check to publish-cdr

- ui/src/app/components/modals.spec.tsx
- ui/src/testing/react-test-helpers.ts
Description:
https://precisionmedicineinitiative.atlassian.net/browse/RW-6889
Fixes an issue in the test tools where using a `setImmediate` call can cause test flakiness when testing UI code that uses a
`setTimeout(fn, 0)`.
According to the[ node documentation](https://nodejs.dev/learn/understanding-setimmediate), it is not clear whether a `setTimeout` of 0 or `setImmediate` will execute first in the next iteration of the event loop.
Running the test in succession demonstrated non-deterministic behavior. After switching to `setTimeout` I no longer saw the issue.
---
> [risk=no][RW-6889] Fix bug in test tools

- api/src/main/webapp/WEB-INF/cron_base.yaml
Description:
Oops - forgot to add the cron endpoint in #5044 to the cron runner.
This does not yet actually enable sending of emails to users.  It currently logs that it *would* send these emails once implemented, and therefore is safe to run now in all environments.  See `MailServiceImpl` at #5044 for details.
---
> [risk=no][RW-6703] crons don't run unless you ... run them

- api/db/changelog/db.changelog-165-set-default-publications-confirmed-time.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
This will set a default value on the `publications_last_confirmed_time` column and the `profile_last_confirmed_time` column. It backfills making a best effort, then enforces a not null constraint.
---
> [risk=no][RW-6904] Publication and profile confirmed times cannot be null

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
Make the email warning days thresholds configurable
---
> [risk=no][RW-6703] Add config value expiryDaysWarningThresholds

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Description:
enableRasLoginGovLinking is part of access and should live in access not feature flag. 
This is a safe change because that is not turned on in any env yet. 
---
> [RW-6840][risk=no]: Move enableRasLoginGovLinking to access

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/cloudtasks/CloudTasksConfig.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/ForwardingCloudTasksStub.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/interceptors/CloudTaskInterceptor.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrTaskQueue.java
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/BackfillWorkspacesToRdr.java
- For local testing, swap out implementations for the `CloudTasksClient`. This constructor accepts alternate stubs, which by default will throw an `UnsupportedException` on any other method invocation.
- Provide a simple implementation of this stub which only implements the subset of the Cloud Tasks API we currently care about
- When creating a task, this stub immediately fires off an HTTP request to the API server (itself) to invoke the task handler
- The stub immediately returns without blocking on the response
This approach would swap out the `endpoint` in the CloudTasksClient, and dispatch a normal, well-formed Cloud Tasks API request to a handler we own. Unfortunately, I discovered this client appears to only support gRPC, meaning we'd need to provide a controller which spoke gRPC. …
> [RW-6873][risk=low] Implement local cloud tasks queue stub for development

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Concept Id in cohort/concept table is now a link pointing to databrowser. There is going to be a story in data browser to update the link workbench is using <databrowser>/ehr/{domain}?search={conceptId} to something that uses just the concept Id and not domain
---
> [RW-4600][risk=no] UI: link each code from concept ID column

- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
- ui/src/app/pages/data/data-set/genomic-extraction-modal.spec.tsx
- ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx
* Display the error message returned in JSON from the server, if any - currently these are intended for client consumption, so should be comprehensible by the end user
* Currently we only expect this to happen in two cases:
* 412: no WGS samples
* 412: too many WGS samples
* If a client error is encountered, gray out the "extract" button - this is not retryable
Other changes:
* Make error and warning mutually exclusive, showing both looked confusing
* Update language to reference the "genomic job history" panel, rather than the "workspace storage" panel 
* Make styling consistent between warning and error callout
Screenshots:
Error (induced by setting a limit of 1 sample) via dataset card modal:
Error (induced by setting a limit of 1 sample) via dataset builder:
> [RW-6866][risk=no] Enforce a 5K sample limit on genomic extraction

- api/build.gradle
Description:
Edit: the [vulnerabilty](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276) is actually for google-oauth-client rather than google-oauth-client-jetty.  Not quite sure how they are related, but they maintain the same version numbering...  Regardless, this keeps a library up to date.
Tested locally.  No obvious concerns.
---
> [risk=moderate][no ticket] bump google-oauth-client-jetty to address vuln

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
`updateProfile()` and `confirmProfile()` both grabbed the current user value from the `@RequestContext` provider. The behavior is undefined as to what happens if you do this multiple times within a request which mutates the user object within that request. There are no guarantees made that the value of this provider will be up-to-date for changes made within that same request. While it can be mutated during the request (arguably, this is not desirable), it should be generally considered to track the original value of the user object when the request originally came in.
In this case (I'll just talk about address here, this is also a bug for demographics survey):
-  `updateProfile()` method calls `setAddress()` with a new Address object (with no ID assigned) before saving
- after the …
> [RW-6939][risk=low] Avoid duplication of foreign entities on profile update

- ui/src/app/components/buttons.tsx
- ui/src/app/utils/runtime-utils.tsx
* Runtime store was attempting to make a state update after dismount. This custom hook is a bit messy overall, but this seems like the correct incremental fix to avoid the warning.
* Newer `Interactive` component does not have the `propagateTestId` prop. I think the option does not make sense based on my understanding of forwardRef, so I removed the caller that was supplying it.
> [RW-6224][risk=no] Eliminate some React warnings

- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/modals.tsx
- ui/src/app/pages/workspace/workspace-wrapper/component.html
- ui/src/app/pages/workspace/workspace-wrapper/component.ts
- ui/src/app/utils/stores.tsx
Trimming down the code in workspace-wrapper by moving it into help sidebar which is where the action is being rendered.
---
> [RW-3122][risk=no] Move workspace deletion code from workspace-wrapper to help-sidebar

- ui/src/app/app-routing.module.ts
- ui/src/app/app-routing.tsx
- ui/src/app/app.module.ts
- ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx
- ui/src/app/guards/navigation-guard.tsx
- ui/src/app/utils/stores.tsx
React components can register themselves with the `NavigationGuardStore` to let the application know that it could have state that should be saved before navigating away. Components should also unregister themselves on unmount.
A high level Angular guard will read from the `NavigationGuardStore` and run the `canDeactivate` check to see if the underlying page should show a warning modal or not.
The solution does use some angular code but it's only used at the root route so all the child components that were blocked on a working `CanDeactivateGuard` should be able to be converted now.
---
> [RW-5256][risk=no] Move main Cohort Builder 'build' route to React router

- e2e/app/page/base-page.ts
- e2e/jest.test-setup.ts
Failed CircleCi [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/11257/workflows/d324818d-ec7d-4dc9-a739-c0b629d7b0b6/jobs/146476/tests).
Error was
`TimeoutError: Navigation timeout of 60000 ms exceeded
at /home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111`
I think it is caused by a recent merge [pull/5110](https://github.com/all-of-us/workbench/pull/5110) that enabled navigation timeout.
Fix:
Remove `networkidle0` in goto func; Increase max nav timeout; Log goto response object to help with failure investigation if happen again.
> [RW-6948][risk=no] e2e test goto navigation timeout speculative fix

- ui/src/app/app-routing.module.ts
- ui/src/app/app-routing.tsx
- ui/src/app/app.module.ts
- ui/src/app/pages/data/concept/concept-search.tsx
Same approach as in https://github.com/all-of-us/workbench/pull/5159
---
> [RW-6321][risk=no] Move ConceptSearchComponent routes into React Router

- ui/src/app/pages/workspace/workspace-list.tsx
> [ticket=no][risk=no] Prevent the scroll bar from spazzing out on loading workspace list

- api/src/main/webapp/WEB-INF/cron_base.yaml
I don't see any reason to run this hourly. Currently, we are not even reacting to the audit alerts (we should), and nightly is completely fine for auditing this.
> [risk=no] Run project audit cron less frequently

- api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudCacheConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
This should drastically reduce the number of requests to Firecloud during the `synchronizeUserAccess` job, which will hopefully allow it to complete within the 10m time limit (as we work on more scalable approaches).
Verified locally that `synchronizeUserAccess` only makes 2 calls (one per tier), despite having 3 users.
> [RW-6919][risk=moderate] Cache Firecloud group lookups

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/google/GoogleRetryHandler.java
This is mostly relevant in test, where we often get errors like:
```
ResponseCodeRetryPolicy.java:49org.pmiops.workbench.utils.ResponseCodeRetryPolicy logRetry: Google API unavailable, retrying after 1 attempts
com.google.api.client.auth.oauth2.TokenResponseException: 400
POST https://oauth2.googleapis.com/token
{
"error" : "invalid_grant",
"error_description" : "Invalid email or User ID"
}
```
due to non-existent users. We are currently retrying these, and we shouldn't be.
> [RW-6538][risk=no] Improve retry handling of Google auth token errors

- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
- api/tools/src/main/java/org/pmiops/workbench/tools/cdrconfig/UpdateCdrConfig.java
Description:
Despite no apparent changes, Hibernate is now complaining that it can't assign DB nulls to primitive boolean.  This makes sense - but why now?
This completely blocks local development for me (so it could be something local?) so I'm converting this field to object Boolean while I consider longer term fixes.
---
> [risk=low][no ticket] Change isDefault to object Boolean

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/modals.tsx
Adding `onDismiss()` as a curried argument broke some usages of the error modal since it would require another argument before invoking the wrapped function.
---
> [ticket=no][risk=no] withErrorModal onDismiss() should be a notification property and not a curried argument

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- ui/src/app/pages/workspace/workspace-share.tsx
- ui/src/testing/stubs/user-api-stub.ts
Description:
Restrict workspace sharing to users who have access to the same tier.  We will eventually need this for Controlled Tier Workspace Sharing.
Currently does nothing, until we implement CT membership for users which differs from RT.
[why now?  spun off from a cleanup ticket in a similar area.  not urgent.]
---
> [risk=low][no ticket] Require same-tier membership for share-workspace

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_staging.json
- api/config/config_test.json
This was left on presumably unintentionally since we first attempted to launch. Just realized today it was still enabled... Will be more accurate to develop and test with this off.
> [risk=no] Turn off billing upgrade in lower environments

- api/src/main/webapp/WEB-INF/queue.yaml
The overall throughput seems correct. From what we observe in prod, there is an initial burst of requests which overtakes our project quota. After this, the 4/m stabilizes, and requests succeed. Try to manage the initial burst with this setting.
> [RW-6538][risk=no] Reduce audit queue throughput

- ui/src/app/pages/access/access-renewal-page.tsx
Description:
The diff is in the step 2 box
---
> [risk=no][RW=6631] Add support email link to aar step 2

- api/config/config_preprod.json
Error I saw from logs:
`Caused by: com.google.cloud.bigquery.BigQueryException: Not found: Dataset all-of-us-rw-preprod:workbench_action_audit_prepropd was not found in location US`
And the dataset I saw in bigquery: `workbench_action_audit_preprod`
We added an extra 'd'
Description:
---
> [no ticket][risk=low]Fix typo in preprod audit log

- e2e/tests/datasets/export-to-notebook.spec.ts
Temporarily disable failing test until bug is fixed to avoid master branch builds failures.
> [no ticket][risk=no] Puppeteer disable a test due to RW-6885

- ui/src/app/pages/workspace/workspace-card.tsx
Error message screenshot:
Steps I used to force error modal to display:
* Start local UI server.
* Connect to local UI server on 2 different incognito pages.
* Delete a workspace in page 1, then quickly delete the same workspace again in page 2.
* Because two delete calls were made, delete in page 2 failed when delete in page 1 succeeded.
New look after change:
After close modal, page is not auto reloaded:
User reload the page. workspace is gone.
> [RW-6989][risk=no] UI: Fix texts string in Delete Workspace Error modal 

- e2e/app/component/workspace-card.ts
- e2e/app/container.ts
- e2e/tests/workspace/workspace-share-modal.spec.ts
- e2e/utils/waits-utils.ts
`WorkspaceCard.deleteWorkspace()` function could fail if delete took longer than 60 seconds. Failed in `workspace-duplicate-cdr-versions.spec.ts` test [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/11495/workflows/d80070df-4913-4f55-886b-846a4f22b1b1/jobs/148187/tests) in CircleCI.
Test failure stacktrace
```
test name: OWNER can duplicate workspace to a newer CDR Version via Workspace card
status: failed
failure: [
'TimeoutError: waiting for XPath `.//*[child::*[@data-test-id="workspace-card"]]//*[@data-test-id="workspace-card-name" and normalize-space(text())="aoutest-404061625158614"]` to be hidden failed: timeout 60000ms exceeded\n' +
'    at new WaitTask (/home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)\n' +
' …
```
> [no ticket][risk=no] Puppeteer fix deleteWorkspace func failure

- e2e/tests/datasets/export-to-notebook.spec.ts
Failure caused by [RW-6885](https://precisionmedicineinitiative.atlassian.net/browse/RW-6885). Disable test temporarily.
> [no ticket][risk=no] Disable e2e dataset export to Py notebook test

- ui/src/app/app-routing.tsx
- ui/src/app/components/breadcrumb.spec.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/pages/data/cohort-review/cohort-review.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
- ui/src/app/pages/data/cohort-review/detail-tabs.component.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.spec.tsx
- ui/src/app/pages/data/cohort-review/sidebar-content.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/app/pages/data/criteria-search.tsx
- ui/src/app/services/review-state.service.ts
- ui/src/app/utils/index.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/test.ts
- ui/src/testing/stubs/cohort-review-service-stub.ts
Fixes issue where the breadcrumb link for the cohort review name only showed `...`.
- Caused by cohort review routes using the `Cohort` breadcrumb type and `currentCohortStore` being empty.
- Fixed by creating a new `CohortReview` breadcrumb type and `currentCohortReviewStore`  to use for cohort review routes.
- Also deleted `cohortReviewStore` and replaced all instances with `currentCohortReviewStore` since we don't need two stores for cohort reviews. (Sorry, this significantly increased the size of the PR but in most cases it's a simple swap out)
Before:
After:
---
> [RW-6902][risk=no] Fix breadcrumbs for cohort review routes

- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/admin/admin-users.tsx
Description:
Remove the no-longer-populated field **first_registration_completion_time / "Registration Date"** from the User Admin page:
before
after
Remove these fields from DbUser and AdminUser
```
first_registration_completion_time
beta_access_bypass_time
email_verification_completion_time
email_verification_bypass_time
id_verification_completion_time
id_verification_bypass_time
```
---
> [risk=low][RW-6882] remove obsolete fields from AdminUser and DbUser

- e2e/app/modal/notebook-download-modal.ts
- e2e/app/page/base-page.ts
- e2e/app/page/notebook-cell.ts
- e2e/app/page/notebook-frame.ts
- e2e/app/page/notebook-page.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
`getIFrame()` function were repeated in several notebook page classes. Created new abstract `notebookframe.ts` class to avoid code duplication.
> [no ticket][risk=no] e2e notebook code cleanup and refactor

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
This does not complete RW-6918.  This allows us to run the AAR expiration report in Preprod which we need to figure out the correct timing for RW-6918.  This also fixes automatic AAR expiration emails in Preprod, and this all applies to Staging as well.
The logic for sending AAR expiration emails and producing the expiration report (`getRenewableAccessModules()`) had a bug: if any of the AAR modules is disabled in an environment, in the worst case no emails would ever be sent and no users would appear in the report.  This is currently the situation on Preprod, so this fix is a requirement for enabling a reasonable expiration period on Preprod.
Correct this logic to filter out disabled modules.
---
> [risk=low][RW-6918] Fix AAR email logic when modules are disabled

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- ui/src/app/pages/access/access-renewal-page.spec.tsx
- ui/src/app/pages/access/access-renewal-page.tsx
Don't return disabled modules in Profile.renewableAccessModules and don't display them in the AAR screen.  Example where complianceTraining is disabled:
Also tested locally removing both FF-disable-able modules and it looked fine with only 2 cards.
---
> [risk=low][RW-7002] Don't show disabled access modules in AAR screen

- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
Description:
We send "you expire in 30 days" emails to users when they have 30 days **plus a small amount** remaining.  They have no action to take because the AAR notification does not appear until the user has **exactly** 30 days remaining.
Update the notification behavior to match the email.
The day count in the notification (and the AAR cards) already matched the email.
---
> [risk=low][RW-7108] fix off-by-one in maybeDaysRemaining()

- e2e/.env.sample
- e2e/README.md
- e2e/app/modal/cdr-version-upgrade-modal.ts
- e2e/app/page/authenticated-page.ts
- e2e/app/page/base-page.ts
- e2e/app/page/create-account-page.ts
- e2e/app/page/google-login.ts
- e2e/app/page/home-page.ts
- e2e/app/page/profile-page.ts
- e2e/app/page/workspace-about-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/app/text-labels.ts
- e2e/resources/workbench-config.ts
- e2e/tests/conceptsets/copy-to-workspace.spec.ts
- e2e/tests/datasets/dataset-create.spec.ts
- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
- e2e/tests/notebook/notebook-reader-actions.spec.ts
- e2e/tests/runtime/pause-resume.spec.ts
- e2e/tests/user/login.spec.ts
- e2e/tests/user/registration-ui.spec.ts
- e2e/tests/workspace/cdr-version-upgrade.spec.ts
- e2e/tests/workspace/old-cdr-version-modal.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/tests/workspace/workspace-duplicate-cdr-versions.spec.ts
- e2e/tests/workspace/workspace-share-modal.spec.ts
- e2e/types.d.ts
- e2e/utils/test-utils.ts
Rename workbench env variable names, define env variables types (`types.d.ts`). It fixed some eslint warnings.
Before:
After:
Also updated README.md for running test on localhost.
> [no ticket][risk=no] Provide e2e env variables types

- api/src/main/java/org/pmiops/workbench/db/DbRetryUtils.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/DbRetryUtilsTest.java
> [RW-6905][risk=low] Add DbRetry utils and use that to retry get recent resource operation

- e2e/app/container.ts
- e2e/app/modal/base-modal.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
Test failure was caused by code issue: `clickButton() fp.flow`.
I noticed test failure message today in CircleCI nightly [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/11702/workflows/ccbe078d-2dba-4fc9-904b-e64b200f1575/jobs/149645/artifacts) test log. Test failed silently, so the CircleCI job did not fail.
```
BUILD SUCCESSFUL in 13s
20 actionable tasks: 1 executed, 19 up-to-date
Running owner-copy-to-workspace.spec at 7/9/2021, 00:16:19
Running gce-to-dataproc.spec at 7/9/2021, 00:16:19
Saved screenshot: logs/screenshot/Copy-notebook-to-another-Workspace-when-CDR-versions-match.png
Saved html file: logs/html/Copy-notebook-to-another-Workspace-when-CDR-versions-match.html
```
> [no ticket][risk=no] e2e nightly test "owner-copy-to-workspace.spec.ts" is not working

- api/src/main/webapp/WEB-INF/queue.yaml
Previous change did not succeed in limiting QPS to below the desired rate to the projects API. After re-re-reading the documentation, this appears to be due to the token bucket algorithm: https://cloud.google.com/appengine/docs/standard/python/config/queueref
Whenever we are dispatching a task, we first consider whether we have enough tokens to do so:
- rate: 4/m, the rate at which we replenish tokens
- bucket_size: now 1, the maximum supported tokens, i.e. a burst limiter
max_concurrent_tasks is probably redundant now, but prevents any degenerate cases where we might have a long-running cloud task for any reason, resulting in a build-up of multiple concurrent tasks.
The above explains why I still saw an initial burst of sequential calls to `auditProjectAccess` (up to ~100), before they …
> [RW-6538][risk=no] Further limit project audit rate

- api/src/main/java/org/pmiops/workbench/access/AccessUtils.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/pages/admin/admin-user-bypass.tsx
- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
This is only a small portion of RW-4838.  Most of the renaming will occur as as part of the migration to the new Access Modules system.
This includes a small change to Workspace Edit:
---
> [risk=low][RW-4838] Rename a few "DUA" to "DUCC"

- api/db/changelog/db.changelog-172-backfill-user-access-module.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
Description:
Note: 
1. This PR just replace the setModuleCompletionTime, getModuleCompletionTime still read from DbUser. I will have separate PR to make all get calls use DbUserAccessModule's completion time (after dual write, and verify it works)
2. I also considered to move the entire logic to AccessModule service instead of just use to set the completion time. But that is too complicated, and I feel that is not necessary(we end up create another giant `userServiceImpl` style class). So I choose the easy and safe and clear path 
Verified data: 
```
mysql>       INSERT INTO user_access_module
->       (user_id, access_module_id, completion_time, bypass_time)
->       SELECT
->       u.user_id,
->       a.access_module_id,
->       u.era_commons_completion_time AS completion_time,
-> …
```
> [RW-6929][risk=low]: Dual write and backfill completion time for all modules

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Send all mails from "support" instead of "donotreply"
---
> [risk=no][RW-7026] Send emails from "support" instead of "donotreply"

- ui/src/app/pages/data/data-set/dataset-page.tsx
Reverting the link on dataset workbench cohort to cohort review since we need to add some more logic to check if review has been created or not while loading dataSet
---
> [noTicket][risk=no] Revert dataset cohort link to cohort review

- api/config/config_local.json
- api/config/config_test.json
Description:
Currently it is hard for me to develop UI feature because my docker sync does not well. I have to restart docker few times to make dev-up working.
Since this is activity under development, I think we can just enable this feature in test and local. Then I can use test API.
---
> [RW-7072][risk=no]enable billing feature in test and local

- ui/src/app/utils/index.tsx
- Fixes issue where highlighted terms in the tree go away when multiple search terms are typed
- Also fixed highlighting for special characters that commonly appear in criteria names ( - < > = / )
Before:
After:
---
> [RW-6910][risk=no] Fix highlighting issue for CB search in-memory trees

- e2e/app/component/data-resource-card.ts
- e2e/app/page/workspace-base.ts
- e2e/libs/page-manager.ts
- e2e/tests/datasets/dataset-snowman-menu-actions.spec.ts
Test failure:
`openDatasetsSubtab()` function fails indeterminately in `dataset-snowman-menu.spec`. e.g. [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/11990/workflows/a1ee5e9c-05aa-4ac9-a73c-d6ea3b1fa714/jobs/151491/parallel-runs/3).
UI cause:
`aria-selected` attribute is not a reliable information anymore for determining wether a tab is open or not. Data tab sometimes has `aria-selected=false` when tab is open. It's a minor UI bug recently introduced. I don't know who or what PR has caused it.
Proposed fix:
A workaround in test functions to avoid repeated failures: Don't rely on `aria-selected` attribute.
New `openDataSubtab()` function will determine if subtab exists. If found it, click it. If not found, find and click Data tab first then find the subtab.
> [RW-7074][risk=no] e2e Rework open tab function

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
These have no remaining code references: enableDataUseAgreement, enableBetaAccess, enableV3DataUserCodeOfConduct, sendEmails
A release cycle has passed, so we can now remove them fully.
Description:
---
> [risk=low][RW-6923][RW-6913][RW-4698][RW-7017] Final removal of 4 Feature Flags

- .circleci/config.yml
> [no ticket][risk=no] Fix CircleCI broken job: wait_until_previous_workflow_done

- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Description:
Wait until #5258 is deployed to Prod before merging.  (done)
After this is merged and deployed to Prod, we can remove the FF itself.
---
> [risk=low][RW-6922] rm API uses of the enableAccessRenewal Feature Flag

- api/build.gradle
- api/src/bigquerytest/java/org/pmiops/workbench/api/BigQueryBaseTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cdr/ConceptBigQueryServiceTest.java
- api/src/integration/java/org/pmiops/workbench/ApplicationTest.java
- api/src/integration/java/org/pmiops/workbench/BaseIntegrationTest.java
`@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
Adding this annotation to BigQueryBaseTest allows `@BeforeAll` and `@AfterAll` to be non static methods. This allows this class to setup/teardown data in BQ per only once per test class.
I added back all the BQ tests into CohortBuilderControllerBQTest. Only pure SpringJPA test were left in that class. The BQ test were removed with the merge of the Junit 5 upgrade.
> [no ticket][risk=no] fixing BQ test cases

- e2e/puppeteer-custom-environment.ts
Description:
The example code (https://github.com/facebook/jest/issues/6527#issuecomment-760092817) which we copied (https://github.com/all-of-us/workbench/pull/4660#discussion_r589637094) was incorrect, and has now been corrected in the original thread.  Thanks for pointing this out @brady-ds !
Closes #5301
---
> [risk=no][no ticket] Await an async call

- ui/src/app/pages/analysis/runtime-panel.tsx
This is more complicated than I'd like, but it threads the needle for requested use case per ticket.
Updated conditions where the cost error is warning, rather than a blocking error:
- user provides their own billing account (once supported)
- or, workspace creator has >$300 remaining free credits
This is because:
- The ability to potentially overspend should be tied to the free credits account you are using, if anything
- You cannot currently fetch the free credits limit for the creator, just the remaining credits (correctly); otherwise we could compare to see if they have an override instead
- Also puts some protections in place against overspend, if free credits are too low
Alternative considered:
Make this a warning for operational users. Felt like this would make it more challenging …
> [RW-7098][risk=low] Treat cost restriction as a warning for workspaces with increased credits

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
Description:
We will drop account syncing as that is a registration requirement. The RAS login only happens once, no future sync is needed. Because:
The existing cron job actually does not work for us. Terra has a daily job to sync with dpGap whitelist, and update Terra’s userinfo. Our cron job talks to Terra and updates user status in AoU. We only use expiration time, which is immutable in Terra. Terra’ cron job just update dbGap data permission, but not other field. 
---
> [RW-6373][risk = low]: Remove eRA Commons account linking. 

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/data/cohort-review/participants-charts.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
Reverts all-of-us/workbench#5278
This [broke the BigQuery integration tests](https://app.circleci.com/pipelines/github/all-of-us/workbench/12248/workflows/f272777b-8c0a-4c0b-8333-680980a13749/jobs/153125). @freemabd noticed last week these weren't running on Circle, which is why presubmit did not catch these. That issue is now fixed, so rebasing and fixing forward will reveal the issue before merge.
> Revert "[RW-7073][noTicket]  Cohort description: Use cohort Id instead of cohort review Id"

- README.md
- api/libproject/devstart.rb
- rainforesttest: long deprecated
- test-api: redundant with `test`, likely from a time where we had data browser and workbench in the same codebase. remove in favor of just `test`, it's cleaner
> [RW-6699][risk=no] rm dead project.rb commands

- ui/src/app/pages/analysis/notebook-redirect.spec.tsx
- ui/src/app/pages/analysis/notebook-redirect.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
Changes:
- Add a 3rd scenario on update: `CAN_UPDATE_IN_PLACE`; no warning is shown for this. Previous `CAN_UPDATE` becomes `CAN_UPDATE_WITH_REBOOT`
- Don't navigate from the Jupyter iframe during `UPDATING`, jupyter is still active during in-place updates
- Show alternate warning text on the customize page, depending on the update type
- Generalize the warning code
- Update some of the warning messages for consistency
> [RW-6800][risk=no] Improve runtime warnings / language

- api/config/config_local.json
- api/src/main/webapp/static/initialize_notebook_runtime.sh
- e2e/resources/python-code/git-ignore-check.py
- e2e/tests/notebook/notebook-create-python.spec.ts
- Update nbextension interactions to be consistent with Leo's usage
- Drop kernel uninstalls, no longer do anything
- Reintegrate gitignore check applied here: https://github.com/DataBiosphere/terra-docker/pull/232/files#r666388427
- Add puppeteer coverage of gitignore interactions
Note: Puppeteer will fail on the last point, since this code change isn't pushed yet.
Puppeteer passes locally
> [RW-7044][RW-7095][risk=moderate] Upgrade to latest Leo runtime image

- e2e/tests/notebook/notebook-create-python.spec.ts
Unfortunately Puppeteer reuses old workspaces, so it  picks up older images sometimes. This will be alleviated after 3d in the test env (after 8/1/21).
> [risk=no] Temporarily disable new puppeteer check while new image phases into test

- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/java/org/pmiops/workbench/institution/PublicInstitutionDetailsMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/institution/PublicInstitutionDetailsMapperTest.java
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/testing/stubs/institution-api-stub.ts
Description:
1. Seems that field only used to render which error message when creating account. 
2. API backend would contain both part, so should not be a breaking change.
---
> [RW-7029][risk=low]: Use the new tier requirement field in publicInstititionDetails

- api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java
This was resulting in a read timeout on `./project.rb list-runtimes --project all-of-us-workbench-test`
Also turn off debugging, this shouldn't be on.
> [risk=no] Increase Leo read timeout for CLI to be consistent with API

- e2e/app/element/base-element.ts
- e2e/app/modal/share-modal.ts
- e2e/utils/test-utils.ts
Failure e.g. [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/12414/workflows/45610cea-bfec-4552-a40f-783d4bf35802/jobs/154309/tests).
Test failure was caused by not finding the dropdown in Share modal.
Also, remove call to flaky `waitForNavigation` method inside `signInWithAccessToken` method.
> [no ticket][risk=no] e2e rework share user func

- ui/src/app/pages/data/data-page.spec.tsx
Description:
```
/Users/thibault/src/aou/ui/src/app/pages/data/data-page.spec.tsx
36:1  warning  Trailing spaces not allowed  no-trailing-spaces
✖ 1 problem (0 errors, 1 warning)
0 errors and 1 warning potentially fixable with the `--fix` option.
```
but `yarn lint --fix` does not fix it.  IntelliJ also could not fix this.  But vim could!
---
> [risk=no][no ticket] remove an annoying lint warning

- e2e/app/modal/share-modal.ts
Explicitly wait for `/userSearch` request to finish immediately after type a character in Name Search textbox. Because request can take a short while to finish. Long request time subsequently causes the e2e tests to have unexpected results.
e.g.
```
[7/29/2021, 21:09:32] - Request issued: GET https://api-dot-all-of-us-workbench-test.appspot.com/v1/userSearch/registered/puppeteer-reader-1%40fake-research-ao
[7/29/2021, 21:09:37] - Request finished: 200 GET https://api-dot-all-of-us-workbench-test.appspot.com/v1/userSearch/registered/puppeteer-reader-1%40fake-research-ao
```
> [no ticket][risk=no] e2e wait for request

- ui/package.json
- ui/yarn.lock
Description:
Addresses https://github.com/all-of-us/workbench/security/dependabot/ui/yarn.lock/tar/open
node-gyp 3.8.0 requires an old vulnerable tar.  We can't upgrade node-gyp in the normal manner because of a transitive angular dependency.
---
> [risk=low][no ticket] Address tar vulnerability by force-upgrading node-gyp

- e2e/package.json
- e2e/tests/datasets/export-to-notebook.spec.ts
- e2e/yarn.lock
Adding [wait-for-expect](https://github.com/TheBrainFamily/wait-for-expect) dev dependency to automatically retry `expect` until true or time out.
> [RW-7145][risk=no] Add expect retry in e2e

- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
Description:
Seems contact email in user table is case sensitive but we should ignore the case when doing institution tier access check.
Detailed doc:
https://docs.google.com/document/d/12WurIIiXwTV7xj91otZzfFYh9J2mAtSg-i4NwbxLqaY/edit#
---
> [RW-4780][risk=low]: Ignore case when comparing user contact email with institution domains or addresses

- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/registration.spec.ts
remove jest-circus retry because it interferes with jest logging: test failure log are not created if test failed.
> [no ticket][risk=no] Update e2e night tests

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/webapp/static/initialize_notebook_runtime.sh
- e2e/resources/python-code/git-ignore-check.py
- e2e/resources/python-code/nbstripoutput-filter.py
- e2e/tests/notebook/notebook-create-python.spec.ts
- Missed the nbstripout requirement from https://github.com/DataBiosphere/terra-docker/pull/232/files , reinstalled this in the initialization script.
- Added test coverage
- Actually upgrade all the images to the latest, meant to do this last week. Disagreement between script and image resulted in a broken snippets menu install.
This time, I will plan to simply manually delete all conflicting puppeteer runtimes in the test env to get puppeteer passing post-merge.
Puppeteer tests pass locally, they will fail on test.
> [RW-7095][RW-7147][risk=low] Re-enable nbstripout, upgrade image in all envs

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/resources/firecloud.yaml
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/CreateWgsCohortExtractionBillingProjectWorkspace.java
Description:
Recently I notice there is https://github.com/broadinstitute/firecloud-orchestration/pull/867 
that may break our v2_billing API. 
This PR also update the `getBilliungProject` but it is not used by us yet. This PR just fix breakage for `creatBillingProject` to unblock our upcoming PPW integration testing. 
---
> [no ticket] Change v2_billing APIs' interface according to recent FireCloud change

- api/src/main/java/org/pmiops/workbench/billing/BillingProjectBufferService.java
Description:
Fix a bug in #5359 and **actually** collect metrics for all combinations of access tier and buffer entry status.
Streams.zip() does not produce a stream of MxN combinations - it produces a stream of min(M,N) pairs. So we were missing nearly all of the metrics.
Apologies for not testing this better locally!
---
> [risk=low][no ticket] Fix bug in 5359

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
In some scenarios, this default appears to be picked up - in particular when the panel is opened while the runtime is still loading. This should probably be reworked to just depend on presets, but at least increase this for now to avoid errors and puppeteer failures.
These defaults are very broken and should be fixed. This change papers over the issue: https://precisionmedicineinitiative.atlassian.net/browse/RW-7155
> [RW-7152][risk=no] Increase default disk to match presets

- api/config/cdr_config_perf.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_prod.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
Older CDR Versions have NULLs in the DB for these fields, which functions in the same way as `false`.
However, the UpdateCdrConfig tool attempts to "update" false -> null for these every time it runs.  Let's explicitly set them to false instead.
Description:
---
> [risk=no][no ticket] Set hasFitbitData and hasCopeSurveyData to false for older CDR Versions

- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
- ui/src/app/pages/admin/admin-institution-edit.tsx
Description:
PROD is broken because of no CT.
But in UI, we set CT to NOACCESS when calling API. API would fail because CT not found in AccessTier table
---
> [no ticket][risk=low]Don't set CT if CT requirement is NOACCESS

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
We're seeing failures to use gcloud / gsutil in all envs:
```
ERROR: (gsutil) Failed to create the default configuration. Ensure your have the correct permissions on: [/home/jupyter/.config/gcloud/configurations].
Could not create directory [/home/jupyter/.config/gcloud/configurations]: Permission denied.
Please verify that you have permissions to write to the parent directory.
```
I'm verifying this fixes now.
> [RW-7172][risk=no] revert latest Leo runtime image upgrade

- ui/src/app/pages/homepage/registration-dashboard.tsx
- ui/src/app/utils/navigation.tsx
~We're going to need same-page-reload-but-different-queryString functionality to make #5385 work correectly.~
~I found a hack in #3554 which looks like it will do the job.  But... it's a hack.  Should we be expanding the use of this technique?  I don't know enough to really have an opinion here.~
~As an example of another use for this (and something which I would like to have, actually) - add a Get Started button which causes a reload after Self-Bypass~
Following Slack discussion, will redo this as a hard refresh
---
> [risk=low][no ticket] Add page reload for self bypass

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
- api/src/test/java/org/pmiops/workbench/exceptions/ExceptionAdviceTest.java
I noticed we were getting a 500 instead of 429 for a buffer empty error.
Turns out this change was the proximal cause, which should have been a fine change: https://github.com/all-of-us/workbench/commit/fc76ba68856b4a0c668e925d4e3dcc7f7c32dc4c#diff-b00e6ea4bd2cf1d5df057e2fd60045129b526ed53372577cec4b4f999f857596R217
The `ExceptionAdvice` class has had this dubious logic for a long time. The exception unwrapping here was flawed - I don't know why we did that.
Also, now we only grab the external-facing message from the `WorkbenchException.getErrorResponse()`. This will only contain the external message - it will not potentially have inner exception messages included (`exception.getMessage()` shows the cause message if the main exception message is null).
> [risk=no] Fix ExceptionAdvice for wrapped exception handling

- e2e/package.json
Missed this in #5293
Included in #5305 but I want to isolate it here
---
> [risk=no][RW-6861] Add the ACCESS_TEST_USER to the e2e impersonation list

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- Enable Spark console endpoints, per [Leo design](https://docs.google.com/document/d/1Zr6qzICStrrJwYkfoIE7fTf9Ziu3f6JmhdA9Ao3Y8Bo/edit#)
- Fix pyspark driver version, per RW-7107. See notes [here](https://docs.google.com/document/d/1vawIVby1cckPXH-Y0gPSk5RV5mXeEay2MM_SWV4FeOs/edit#heading=h.begvagrbeuc6)
- Minor code cleanup in the Leo client
The spark console cannot be accessed directly currently, because iframe auth is needed, and we don't have a page for this, nor do we have direct links from the Jupyter UI. However, this change is still useful, as users can run the following code snippet to generate Spark console links from a notebook:
```
from IPython.core.display import HTML
import os
spark_links = [
{'name': 'Yarn Resource Manager', 'path': 'yarn'},
{'name': 'MapReduce Job …
```
> [RW-7151][RW-7107][risk=moderate] Enable Spark console, fix pyspark

- api/src/main/java/org/pmiops/workbench/ras/RasLinkService.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
Description:
Background: While developing RAS, I realize that the linked identity format is problemtic, it has extra [] that makes it a array which always have single element. I filed a feature request to RAS asking for fix, now the fix is pushed to staging.
https://github.com/NIH-Auth-Services/CIT-IAM-RAS/issues/40
---
> [no ticket] Modify RAS linked identity path in JSON based on RAS recent update. 

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench-api.yaml
Description:
this is needed because the billing accounts endpoint requires the billing scope. If this scope is not present, we need a way of identifying and setting the billing account ID from the workspace edit page.
---
> [RW-7057][risk=low] Return free tier billing account id in config

- e2e/app/page/notebook-page.ts
`runCellCell` func can be used without `code` or `codeFile` parameter specified. For example: `await notebookPage.runCodeCell(1);`
CircleCI failed [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/13140/workflows/a380afc7-f6d9-486d-8d0c-85df6903f659/jobs/159557/tests).
Remove the check for undefined parameters.
```
failure: [
'Error: Code or codeFile parameter is required in runCodeCell method.\n' +
'    at NotebookPage.runCodeCell (/home/circleci/workbench/e2e/app/page/notebook-page.ts:229:13)\n' +
'    at /home/circleci/workbench/e2e/tests/datasets/export-to-notebook.spec.ts:142:24'
]
```
> [no ticket][risk=no] e2e fix runCodeCell func

- ui/src/app/pages/analysis/runtime-panel.tsx
> [risk=no][ticket=no] Fix auto pause option being pushed out of frame in dataproc config

- api/config/config_perf.json
- api/src/main/java/org/pmiops/workbench/api/InstitutionController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
> [RW-6934][risk=low] Check user emails when calculating user access tier. And make eRA commons optional if login.gov enabled.

- ui/src/app/pages/homepage/homepage.tsx
Description:
There was a bug in the Homepage -> Registration Dashboard logic: if RAS linking was complete (or bypassed) but another module was incomplete, then RAS would show as incomplete and full registration would not be possible.
Before
After (tested for both bypass and completion state - the appearance is the same)
---
> [risk=low][no ticket] Allow registration to continue when RAS is complete or bypassed

- e2e/jest-puppeteer.config.js
- e2e/libs/page-options.ts
Set `slowmo` at 10 milliseconds for test stability.
> [no ticket][risk=no] Bring back Puppeteer slowmo

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Long ago, we followed the GSuite convention of "email" to describe the primary way we identify a user.  This made sense at the time because it is indeed an email address.
Since then, the user's institutional contact email has become more important, and this is typically what we mean when we talk about a user's email.  So we renamed the original "email" to "username" in most cases (in #2929) to avoid confusion.
I noticed a few of these that we missed while looking at RW-7008.
---
> [risk=low][no ticket] Clean up a few leftover email -> username conversions

- e2e/app/element/base-element.ts
- e2e/app/page/conceptset-actions-page.ts
- e2e/app/page/conceptset-page.ts
Test debug log example that indicates new workaround had worked: 
```
console.log
maxRetries: 3
console.log
[8/31/2021, 10:18:25] - Request finished: 200 GET https://api-dot-all-of-us-*********-test.appspot.com/v1/workspaces/aou-rw-test-e436c18e/e2eeditrenameconceptsetstest/concept-sets/44118
console.log
[8/31/2021, 10:18:26] - Request finished: 200 GET https://api-dot-all-of-us-*********-test.appspot.com/v1/workspaces/aou-rw-test-e436c18e/e2eeditrenameconceptsetstest/concept-sets/44118
console.log
[8/31/2021, 10:18:27] - Request finished: 200 GET https://api-dot-all-of-us-*********-test.appspot.com/v1/workspaces/aou-rw-test-e436c18e/e2eeditrenameconceptsetstest/concept-sets/44118
console.log
maxRetries: 2
console.log
type successful. confidenceCounter 1
console.log
maxRetries: 1 …
```
> [RW-7240][risk=no] Improve e2e type function

- e2e/libs/page-events-helper.ts
Exclude few more requests' response from being logged in test log. Their long response makes test log harder to find useful info.
> [no ticket][risk=no] e2e exclude log of some requests

- api/build.gradle
- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/ResetDefaultRuntimeAutopause.java
Pseudocode of what this is doing:
- For a given environment, get all runtimes
- Filter to any runtimes with autopause == 0
- Update the runtime with autopause = true
Update only works while impersonated, cannot be done as the central SA.
No one should intentionally have an autopause setting of 0, so this should be safe in all environments.
> [RW-7248][risk=no] Add oneoff autopause reset script

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- ui/src/app/utils/runtime-utils.tsx
Code review feedback that I forgot to commit before merging, https://github.com/all-of-us/workbench/pull/5522.
---
> [RW-7248][risk=no] Do not set autopause boolean parameter if autopause integer parameter is not provided

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
Description:
After PPW WORKSPACE_NAMESPACE is not GOOGLE_PROJECT anymore. Hence leo can not set it correctly. So we should set it in our side. 
---
> [no ticket][risk=low] set WORKSPACE_NAMESPACE  environment  variable

- ui/src/app/pages/profile/profile-access-modules.spec.tsx
- ui/src/app/pages/profile/profile-access-modules.tsx
- ui/src/app/pages/profile/profile-component.spec.tsx
- ui/src/app/pages/profile/profile-component.tsx
As part of the Data Access Requirements work ([mocks](https://projects.invisionapp.com/d/main#/console/21472057/455216387/preview)) we are removing the Access Modules / Registration Tasks from the Profile page.
This PR doesn't do that - it simply extracts the relevant section into a new functional component to make the transition easier.
Tested locally.  I observed no changes.
---
> [risk=low][RW-7089] Extract ProfileAccessModules from Profile

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
- Enable in test/local
- Add cloud task based implementation
- **Change**: drop Moodle compliance checks. These are no longer necessary, since we're expiring training on our end
- **Change**: only check 2FA to verify that un-disabled users haven't turned it off, limits gsuite traffic
Tested locally
> [RW-6875][risk=low] Implement unified access sync cron

- api/config/config_local.json
- api/config/config_test.json
Tested puppeteer locally and this _shouldn't_ affect any of the current tests.
---
> [RW-7221][risk=no] Enable enableStandardSourceDomains config flag for local and test

- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
Fixes 'undefined' text in parameter list and blank space where the Gender name should be.
Before:
After:
---
> [RW-7257][risk=no] Fix text on cohort description page

- ui/src/app/utils/navigation.tsx
`URLSearchParams` is available globally. Importing from `"url"` seems to grab the module instead from the fetch codegen - unclear why. Not sure when this broke.
> [RW-7262][risk=no] rm unnecessary import, fix admin nb preview

- ui/src/app/pages/homepage/data-access-requirements.tsx
Before: every page load of DAR would sync external modules and reload the profile.  This led to weird state errors like "attempted to update state of unmounted component" at the end of that sync and "illegal invocation of callback" and failure to render the next page navigated to after DAR.
These problems no longer occur now that we only sync external modules when the Refresh button is clicked. 
---
> [risk=low][RW-7089] don't sync on initial load of DAR - causes state errors

- e2e/app/page/base-page.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/tests/cohorts/cohort-create.spec.ts
- e2e/tests/cohorts/cohort-edit.spec.ts
- e2e/tests/ui/cohort-ui.spec.ts
- e2e/utils/test-utils.ts
- e2e/utils/waits-utils.ts
Added new teset `Cohort search by code and description` in `cohort-ui.spec` and reorganized `cohort-edit.spec` and `cohort-create.spec` tests to make them run faster.
Sample run times:
Before:
`PASS tests/cohorts/cohort-edit.spec.ts (174.943 s)`
After:
`PASS tests/cohorts/cohort-edit.spec.ts (110.571 s)`
Before:
`PASS tests/cohorts/cohort-create.spec.ts (380.615 s)`
After:
`PASS tests/cohorts/cohort-create.spec.ts (316.047 s)`
> [no ticket][risk=no] Improve e2e cohort tests

- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Use a UI env flag to help stage the Controlled Tier rollout.  The first application of this is #5541
---
> [risk=low][no ticket] Add new UI env flag accessTiersVisibleToUsers

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Noticed this while making the `synchronizeUserAccess` changes, getting NPEs for users who exist in the db, but not gsuite (this is not expected outside of the test env).
- `Optional` instead of `null` sentinel
- Change some non-null-safe usages to throw an appropriate error
> [risk=no] Refactor DirectoryService.getUser to mitigate NPEs

- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
Using this approach:
- 21 samples (1.2GB), 20 workers: 31m
- 557 samples (31.5GB), 278 workers: 1h13  
This seemed to perform better than `samples/5`, but we'll likely need more data points from production to get a better sense. These measurements are very noisy.
Other data points gathered:
- 21 samples (1.2GB), 4 workers: 48m
- 143 samples (7GB), 28 workers: 62m
- 557 samples (31.5GB), 111 workers: 96m
- 557 samples (31.5GB), 557 workers: 61m
> [RW-6998][risk=no] Implement initial tuning of genomics extraction scatter count

- e2e/package.json
- e2e/utils/test-utils.ts
- e2e/yarn.lock
- ui/package.json
- ui/src/app/components/login-gov-ial2-notification.tsx
- ui/yarn.lock
Description:
The new method should be able to generate 2fa code for any applications if having the secret. Here is the secret when setting up Google login:
---
> [RW-7234][risk=no]: Add utility in e2e that can generate 2fa code

- e2e/tests/nightly/user-access.spec.ts
- e2e/utils/test-utils.ts
- e2e/utils/waits-utils.ts
Allow tests to specify an alternate sign-in destination (which AAR needs).
Tested locally by running a successful AAR test with alt sign-in, and a different test with standard Homepage sign-in.
---
> [risk=no][no ticket] Fix nightly AAR test

- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
- ui/src/app/pages/data/data-set/dataset-page.tsx
since we are already displaying Observation in concept set, make sure that PPI (which is for survey) doesnt show up as part of observation domain search list
---
> [RW-7224][risk=no]Observations domain -- ensure data inserted into criteria table

- e2e/app/component/runtime-panel.ts
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
e2e nightly test `runtime.spec` broke on Sep 9 and #5552 appears to be the culprit.  The e2e test changed from looking for the icon path (which was no longer possible) to a data-test-id based on the runtime status.  However, the icons and the statuses are not 1:1.  This PR changes the data-test-ids to always match the icons.   
Update: I expect this will resolve the other 2 nightly failures as well.
---
> [risk=no][no ticket] Runtime Panel dataTestId based on icon, not status

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- Log an assertion failure if the manifest doesn't exist, within extraction codegen.
Example:
```
import os
import subprocess
manifest_file = os.environ['DATASET_25865791_VCF_DIR'] + '/manifest.txt'
assert subprocess.run(['gsutil', '-q', 'stat', manifest_file]) == 0, (
"!" * 100 + "\n\n" +
"VCF extraction has not completed.\n" +
"Please monitor the extraction sidepanel for completion before continuing.\n\n" +
"!" * 100
)
print("VCF extraction has completed, continuing")
```
Polling until the extraction file exists. Rejected because we don't have a mechanism to detect an extraction failure within the notebook. We could build this, but it would require callbacks into the RW API from notebooks, which is a threshold I don't wish to cross at this time. Directing them to the sidepanel will …
> [RW-7022][risk=low] Add manifest checks to genomic codegen extraction

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/utils/access-utils.tsx
AAR displays certain text if "all modules are complete or bypassed".  Since the change to the new Access Module structures, it has been evaluating this based on all of a user's access modules, not just those subject to renewal/expiration.
This restores the logic of only checking expirable access modules.
Also a new unit test and some test cleanup.
---
> [risk=low][no ticket] Restrict AAR logic to only those modules which can expire

- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
When creating/cloning workspaces, set the `billingAccountName` to default free tier one. 
Then dropdown is able to populate a default value option on the `billingAccountName` 
---
> [no ticket][risk=low]: Set the default value when creating new workspace

- .circleci/config.yml
- .circleci/workflow-queue-v1.sh
Address a bug in the workflow blocking script.
The `project/all-of-us/workbench/tree/master?filter=running&shallow=true` api response does not include jobs that haven't started in an active workflow. Queued jobs in a currently running pipeline are not caught by the blocking script.
New logics to fix the script issue:
- Exclude self, find all currently running jobs on master branch.
- Save (unique) workflow IDs from running jobs. 
- Iterate through workflow IDs. Wait as long as there is a running job in each workflow.
> [no ticket][risk=no] Fix CircleCI workflow blocking script

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
We want to launch DAR on 9/20 but we are not ready to launch RAS.  However, we have sent out communications regarding the launch of RAS.  So: we need some placeholder text about RAS to avoid user confusion.
When FF enable RAS = false
When FF enable RAS = true, works normally.
---
> [risk=low][no ticket] Temporary disabled RAS module placeholder for DAR

- e2e/app/page/admin-user-profile-info.ts
- e2e/tests/nightly/admin/user-admin-ui.spec.ts
I broke the nightly tests by removing some functionality in #5593.  This also removes it from the test.
Note: the bypass toggles weren't functional anyway.
Passing test locally: `yarn test-nightly tests/nightly/admin/user-admin-ui.spec.ts`
---
> [risk=no][RW-7015] Remove admin-user-profile bypass toggles from e2e testing

- api/src/test/java/org/pmiops/workbench/testconfig/TestJpaConfig.java
- api/src/test/resources/application.properties
- api/src/test/resources/logback-test.xml
When running Java unit tests, eliminate the pages of Spring logspam. This can be re-enabled locally if desired, per comments in application.properties.
`logback-test.xml` was necessary for the initial bootstrapping logs by spring framework. Apparently these logs happen before `application.properties` gets parsed.
> [risk=no] Suppress Hibernate logspam in unit tests

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
Missed this in the latest revision of code I tested. This will be validated by Puppeteer tests in RW-7093.
> [risk=no] Fix genomics manifest check codegen

- api/src/main/java/org/pmiops/workbench/compliance/ComplianceService.java
- api/src/main/java/org/pmiops/workbench/compliance/ComplianceServiceImpl.java
`enableMoodleBackend` has been true in all envs for years now.
Description:
---
> [risk=low][no ticket] rm "enableMoodleBackend=false" paths and other obsolete Moodle code

- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
To consistently generate a runtime in the error state, you can do the following:
- Ensure you have >$300 free credits, by increasing your limit via the admin UI
- Pick a dataproc cluster
- Set the worker count to 999 (this is higher than your default project quota)
You should receive a response like this from the `GetRuntime` API:
```
{
...
errors: [{
errorCode: null
errorMessage: "Failed to create cluster aou-rw-local1-0af76d8f/all-of-us-1 due to io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Multiple validation errors:\n - Insufficient 'CPUS' quota. Requested 3998.0, available 2400.0.\n 
Requested image requires minimum boot disk size of 60 GB; requested 30 GB"
}],
...
```
> [RW-7121][risk=no] Return Leo runtime errors from RW API

- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
- api/tools/src/cron/export-to-rdr.sh
https://precisionmedicineinitiative.atlassian.net/browse/ROC-1164
- The bug: RDR wants `"CONTROLLED"`, we're sending `"controlled"`
- Fix RDR yaml
- Add a regression test
Pull both constants into a util, make them a more permanent fixture. It seems we have to be opinionated about these specific string constants in order to satisfy this API interaction. There is still a risk that our DB shortnames and their enum diverge in the future. This seemed like a more controversial change as the current `"registered"` constant indicates it is slotted for removal, so I didn't take that on here.
> [risk=no] RDR export access tier casing fix

- ui/src/app/pages/workspace/workspace-edit.tsx
Saw this while debugging today's Create Workspace outage on Dev:
---
> [risk=no][no ticket] Workspace Edit: check if UI error has message before accessing it

- ui/src/app/pages/admin/admin-institution-edit.tsx
I broke Inst Admin UI navigation (including save!) in #5611 and this restores the navigation method.
---
> [risk=low][no ticket] restore the original this.backNavigate() removed in #5611

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
Feature flag teardown part 1/2.
- Remove bulkSync2fa cron: replaced by new version of `synchronizeUserAccess`
- Remove bulkSyncComplianceTraining: unneeded, since compliance expiration is handled by AAR now
- Rework `OfflineUserController` to exercise batch -> task queue functionality.
> [RW-6877][risk=low] rm deprecated access crons

- api/libproject/environments.rb
Trying this again. Original reason for reverting to this is b/c free tier billing was OOMing. That is now happening regardless, so may as well try reducing this again.
Free tier cron is currently disabled per RW-6280.
> [risk=no] Try reducing GAE test env instance class

- ui/src/app/pages/analysis/runtime-panel.tsx
`currentRuntime` would briefly become undefined, causing an error when trying to access `currentRuntime.status` on `runtime-panel` L1127.
---
> [no ticket][risk=no] Bug when switching workspaces

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Part of RW-4838 - rename all the things w/r/t "Data Use Agreement"
UI was switched over in https://github.com/all-of-us/workbench/pull/5602 then released.
---
> [risk=low][RW-4838] Remove submitDataUseAgreement (now submitDUCC)

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
When DAR is initially loaded or the user hits Refresh which triggers a reload, DAR derives the `activeModule` by checking the user's Profile.  The `Next` and `Refresh` indicators are attached to the activeModule, and the completion banner is triggered by the "no active module" state.
When the user completes a module, the Profile is reloaded and the `activeModule` is recalculated.  This works in all cases except the last: when all modules are complete and DAR should transition to "no active module" (complete), it does not.
The fix is very simple: always set the active module, even when the module is "none", instead of only setting the active module when it has a valid value.
Added a test for this case as well as some other tests. 
---
> [risk=low][no ticket] Allow users to continue after RAS completion

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/utils/institutions.tsx
Add Institution populates an inst with no Registered Tier, and no way to enable one.  Insts w/o RT are useless, so this effectively blocked inst creation.  This is another regression caused by #5611.
Added a few basic Add Mode tests, which would have caught this.
I'll add more tests in a future PR.  I want to get this one merged ASAP.
---
> [risk=low][no ticket] Fix broken Admin Add Institution regression

- api/libproject/environments.rb
Reverts all-of-us/workbench#5608
Possibly this increased puppeteer flakiness. Try reverting.
> [risk=no] Revert: "Try reducing GAE test env instance class"

- api/config/cdr_config_preprod.json
Moving from `r_2021q3_1` to `r_2021q3_2`
> [RW-7286][risk=no] Bump cdr for registered dataset v5 in preprod

- api/libproject/environments.rb
Incidentally needed for https://precisionmedicineinitiative.atlassian.net/browse/RW-6793; just makes these config settings available to the command-line tools.
> [risk=no] Add prod CT environment config details

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
We are already alerting on these task failures, however they didn't actually fail because exceptions were being suppressed. Fail the cloud task instead.
> [RW-4982][risk=no] Throw on RDR export failures

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
Replace the awkward `onBlur` validation with `validate.js` for a much nicer user experience and a resolution to some related UX bugs.  Inspired by testing from @chavanr2019 demonstrating problems.
Before:
After:
---
> [risk=low][no ticket] Friendlier UX for Inst Admin Edit

- api/libproject/devstart.rb
- e2e/libs/page-manager.ts
- e2e/package.json
- e2e/resources/workbench-config.ts
- e2e/tests/datasets/dataset-create.spec.ts
- e2e/tests/examples/sign-in.spec.ts
- e2e/tests/nightly/admin/user-admin-ui.spec.ts
- e2e/tests/nightly/user-access.spec.ts
- e2e/tests/notebook/notebook-reader-actions.spec.ts
- e2e/tests/workspace/workspace-share.spec.ts
- e2e/types.d.ts
- e2e/utils/test-utils.ts
If tokens were created within the past 15m, don't regenerate. This speeds up iterative testing cycles.
Filename format for tokens is now:
```
token-dir/{impersonated_email}.txt
```
This change was made to avoid caching bugs. We should regenerate tokens if we, for example, switch between environments.
> [risk=no] Support cached tokens, switch filename convention

- api/config/config_test.json
> [RW-7360][risk=low]: Rollback jupyter image upgrade in test see if that breaks e2e

- ui/src/app/utils/access-utils.tsx
These fields are no longer referenced by anything since RegistrationDashboard was removed.
You may notice this pattern remains in admin-user but this is deceptive: it uses AdminTableUser instead of Profile.  AdminTableUser does not need to change at this time.
---
> [risk=no][RW-6931] rm last instances of Profile completionTime / bypassTime from the UI

- ui/src/app/pages/admin/admin-institution-edit.tsx
Change from SAVE to Save with a `textTransform: uppercase` as is our standard way to make buttons all-caps.  No visual change.
This helps with consistency in our tests.
---
> [risk=no][no ticket] Use standard capitalization for Institution Admin Edit

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java
- api/src/main/resources/workbench-api.yaml
The flag controls automated handling of alerts, and will likely also control admin UIs. However, we still store the event with or without the flag enabled.
stacked on https://github.com/all-of-us/workbench/pull/5610
> [RW-7371][risk=no] Add egress alerting V2 feature flag

- api/config/cdr_config_prod.json
Bumps version for Registered Tier Dataset v5 from `r_2021q3_1` to `r_2021q3_3`
> [RW-7334][risk=no] Bump cloud sql db version in prod

- ui/src/app/pages/admin/admin-institution-edit.tsx
> [risk=no][no ticket] Update pending changes modal text for inst admin edit

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Description:
The new terra-docker-aou version may have a problematic change that breaks notebook kernel connection. 
Revert this for now until https://broadworkbench.atlassian.net/browse/IA-2984 fixed
---
> [RW-7360][risk=low] Revert jupyter docker images to previous version

- README.md
- api/libproject/devstart.rb
This is no longer necessary, as dev-up now runs the API server outside of docker.
> [risk=no] Drop start/stop API reqs

- ui/package.json
- ui/yarn.lock
https://github.com/advisories/GHSA-rp65-9cf3-cjxr
---
> [risk=low][no ticket] force nth-check version to 2.0.1 to resolve vulnerability

- ui/package.json
- ui/yarn.lock
https://github.com/advisories/GHSA-44c6-4v22-4mhx
---
> [risk=low][no ticket] Force semver-regex bump due to vuln

- api/config/config_perf.json
- api/config/config_staging.json
This will be necessary for genomic e2e nightly tests to pass in staging. It is OK to enable here at this point, since preprod users are currently using this feature.
> [risk=no] Enable genomic extraction in staging+perf

- e2e/app/component/runtime-panel.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
The autopause 30 min default can cause test to fail when runtime creation finish quickly but extraction to vcf take a long time.
> [no ticket][risk=no] Increase e2e genomic-extraction-to-vcf test auto-pause time

- api/db/changelog/db.changelog-178-add-compute-security-suspended-column.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- Add database support for the column
- Add API support for disabling compute endpoints, with error plumbing
- Add a new `parameters` field to the error response for error-specific structured data. This will be used for rendering the "until" timestamp appropriately on the client
Not part of this PR:
- A service method for suspending a user
- UI handling of the suspended error status
Tested manually by setting the column locally:
```
update user set compute_security_suspended_until=date_add(NOW(), interval 1 minute) where user_id=1;
Query OK, 1 row affected (0.01 sec)
```
> [RW-7314][risk=low] Implement a compute security suspension state for a user

- e2e/tests/profile/profile-page.spec.ts
- e2e/utils/str-utils.ts
This eliminates a flaky scenario where we would `makeString(10)` one of the same values we previously generated / saved onto the profile in another test case. This caused the test to fail, as the test is expecting this value to be different from the existing profile field.
- This flake would occur on ~1% of runs, by my approximation
- `makeString(10)` has a .11% chance of generating the same value twice in a row
> [RW-6752][risk=no] Ensure we use a different string on profile update test

- api/src/bigquerytest/java/org/pmiops/workbench/testconfig/TestBigQueryConfig.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/config/BigQueryConfig.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
I just use a bean to allow for easy swapping here. It didn't seem necessary to allow this to be tuneable via WorkbenchConfig.
> [RW-7413][risk=no] Increase default BigQuery read timeout in integration tests

- api/build.gradle
The fix that Snyk suggested (#5794) for https://snyk.io/vuln/SNYK-JAVA-COMGITHUBJNR-1570422 did not actually do the job.  After checking the dependency tree, I saw that we need to upgrade to 1.3.x to pull in a non-vulnerable jnr-posix transitively.
---
> [risk=low][no ticket] upgrade mysql-socket-factory to latest to address vuln in jnr-posix

- ui/src/app/pages/admin/admin-users.tsx
First part of story RW-7521: UI work - For environments where `enableComplianceTraining` is true, add a column to the User Admin Table.
New column name is `CT RCR`. We also modified existing column name `Training` to `RT RCR`. (RCR: Responsible Conduct of Research)
> [RW-7521][risk=no] Add new user admin column for ct compliance training

- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/notebook-frame-error.spec.tsx
- ui/src/app/pages/analysis/notebook-frame-error.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/leo-runtime-initializer.tsx
- ui/src/app/utils/runtime-utils.tsx
- ui/src/app/utils/stores.tsx
- ui/src/app/utils/zendesk.ts
- ui/src/testing/react-test-helpers.tsx
Related changes:
- `LeoRuntimeInitializer` no longer infinitely retries 400 level errors
- `LeoRuntimeInitializer` returns the last inner error when it exceeds the retry count
- `LeoRuntimeInitializer` treats non HTTP errors as unknown errors for retry purposes
Not included in this PR:
- "suspended" status in the help sidebar
security suspended error:
suspension time hover:
unknown error (notebooks redirect):
> [RW-7326][risk=no] Implement security suspension UX

- ui/package.json
This method allows you to step through jest test code via the chrome inspector, similar to how one can debug code when running a local UI server. This is an adaptation of the general instructions found here: https://jestjs.io/docs/troubleshooting.
Node is referenced here because Jest runs via a node process. There is no browser configured by default, and therefore there is no way of using a browser-based debugger by default. With some additional flags, you can configure Chrome to connect to the running node process and use the Chrome inspector to set breakpoints etc normally.
Usage:
1. Add debugger; to code (or set a breakpoint later). Recommended: use `fit()` instead of `it()` to run an isolated test.
2.
```
yarn test:debug ...
```
3. Open chrome inspector (in any chrome tab), click …
> [risk=no] Add node debugger command to yarn

- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Missed a step in the search query: check if the user/tier association is ENABLED rather than DISABLED.
Tested locally: could share with non-CT user before, can only share with CT users now.
---
> [risk=low][RW-7533] Disallow CT workspace sharing with users who are no longer in CT

- ui/src/app/utils/research-purpose.tsx
Move the key prop up one component level.
workspace-about-spec (I'm assuming other tests as well) warns:
```
console.error
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
in Fragment (at research-purpose.tsx:62)
```
---
> [risk=no][no ticket] Fix a react key prop warning

- api/buildSrc/build.gradle
- appengine-cron-emulator/build.gradle
Addresses a large number of vulnerabilities.  See https://app.snyk.io/org/all-of-us-researcher-workbench/project/00e2691e-6250-4c65-82d6-9d94562885ca and https://app.snyk.io/org/all-of-us-researcher-workbench/project/dabaa8f4-9882-40b9-8859-c7781cf7f65f
---
> [risk=low][no ticket] bump jackson databind and dataformat-yaml for buildSrc and appengine-cron-emulator

- api/config/cdr_config_preprod.json
wgs VCFs are still pending, so this value is intentionally omitted: https://precisionmedicineinitiative.atlassian.net/browse/RW-7529
> [RW-7497][risk=no] Publish WGS BigQuery to preprod

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/jira/JiraConfig.java
- api/src/main/java/org/pmiops/workbench/jira/JiraService.java
- api/src/main/resources/jira.yaml
This is an integration we had a long time ago for Bug Reporting purposes. Adding this back in for egress incidient ticketing.
- Bump to latest v3 Jira API, which has a published Swagger spec
- Copy a subset of this swagger and make some modifications (see comments in jira.yaml)
- Setup initial create/comment/search functionality, which is needed by the EgressRemediationService
See also the follow-up PR https://github.com/all-of-us/workbench/pull/5859  for usage of this client.
> [RW-7317][risk=low] Reintegrate Jira service for Workbench

- e2e/app/text-labels.ts
The checkbox label has changed.
CircleCI failed [run](https://app.circleci.com/pipelines/github/all-of-us/workbench/15707/workflows/a4352c3c-987a-4838-bbc7-c96cacd36888/jobs/179285).
> [no ticket][risk=no] Update VCF Files checkbox xpath

- ui/.eslintrc.js
This will catch `fit()`, `test.only` etc. I accidentally checked one in recently.
See https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-focused-tests.md
> [risk=no] Lint for focused tests

- ui/src/app/pages/workspace/tier-unavailable-modal.tsx
- ui/src/app/pages/workspace/unavailable-tier-modal.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Old behavior -> for users without CT access, no tier dropdown appears in Create Workspace
New behavior -> if CT exists in an env, it always appears in Create Workspace.  users without access get a modal directing them to DAR if they select CT (and the selection is forced back to RT)
---
> [risk=low][RW-7520] CreateWorkspace TierUnavailableModal if user doesn't have access

- api/db/changelog/db.changelog-179-add-workspace-admin-locked-column.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceDaoTest.java
Adds a boolean `adminLocked` to the workspace state and allows changing the value through an admin-accessible API endpoint.
---
> [RW-7544][risk: low] Add adminLocked state to database

- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortAnnotationDefinitionMapper.java
- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapper.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortMapper.java
- api/src/main/java/org/pmiops/workbench/conceptset/mapper/ConceptSetMapper.java
- api/src/main/java/org/pmiops/workbench/dataset/mapper/DataSetMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
This CommonMappers method has a name which causes confusion and doesn't accurately represent what it does.
This always operates on a DB entity `version` rather than a CDR Version.
---
> [risk=no][no ticket] rename cdrVersionToEtag to versionToEtag

- api/src/main/resources/jira.yaml
- Remove some fields that we weren't using, and I didn't want to bother fixing
- Fix up other fields which were untyped, or using an improper `additionalProperties`
Quickest way to fix this was probably copy/paste into the online swagger validator; local codegen errors did not indicate the log line.
> [risk=no] Fix Jira openapi warnings

- api/src/test/java/org/pmiops/workbench/FakeJpaDateTimeConfiguration.java
- api/src/test/java/org/pmiops/workbench/api/OfflineEgressControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressEventServiceTest.java
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressRemediationServiceTest.java
This makes it consistent with `FakeClockConfiguration`, which makes it easier to remember / autocomplete.
> [risk=no] Rename fake JPA date time for consistency

- api/src/test/java/org/pmiops/workbench/api/AdminAuthorityTest.java
Manually removing the `@AuthorityRequired` from `getAuditLogEntries()`, i.e. the original regression, causes the test to fail:
```
Likely missing @AuthorityRequired annotation!
controller method 'getAuditLogEntries' lacks @AuthorityRequired, but endpoint '/v1/admin/users/{usernameWithoutGsuiteDomain}/audit' appears to be an admin path
expected to be false
```
One class of endpoints that this misses are those which _should_ have `@AuthorityRequired` but don't **and** also don't have a /admin/ infix. Detecting this case would require reflecting into the mind of the code author, which is not possible at this time.
> [RW-7508][risk=no] Add @AuthorityRequired heuristic test

- ui/src/app/pages/data/data-set/dataset-page.tsx
- Convert all column values to lower case to prevent conflicting upper and lower case values. 
- Fixes issue that can occur in datasets of duplicated workspaces
---
> [RW-7410][risk=no] Prevent saving dataset with no columns selected

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
This was superceded by `deleteRuntimesInWorkspace`
> [risk=no] rm deprecated admin method

- ui/src/app/routing/signed-in-app-routing.tsx
Also - switch the old user admin route to be a redirect, instead of a duplication of the UserAdmin page.
> [risk=no] Disable the app footer on admin pages

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
Stacked on #5886 
The total size of the paginated stream is needed in order to render the admin egress events table.
Also fix the type in swagger for a few fields, should be `int` instead of `number`
> [RW-7322][risk=no] Return totalSize from listEgressEvents

- .circleci/config.yml
Update CircleCI `puppeteer-access-test-user-setup` cmd -- Replace env variable `PUPPETEER_ACCESS_TEST` with `ACCESS_TEST_USER`.  Because Puppeteer env variables were deleted yesterday.
> [no ticket][risk=no] Fix env variable for access test user in nightly test

- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
As part of this PR:
- Add check to ensure request for Admin Lock of workspace should have a non empty reason and Date of request
- Also add separate call for lock and unlock of Admin Workspace
- Adding the adminLocked field to the Workspace API entity object 
---
> [RW-7544][risk=no]  Read and set an "admin locked" state for a workspace - Add check for request reason and date

- api/src/main/java/org/pmiops/workbench/compliance/ComplianceService.java
- api/src/main/java/org/pmiops/workbench/compliance/ComplianceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
Tested locally: `syncComplianceTraining` appears to have the desired effect of setting my CT compliance training module with my user who has received the "dua" badge.
Logical changes:
- We now look at both RT and CT compliance training statuses during `syncComplianceTraining`, these map to `ret` and `dua` respectively, per Moodle team
- completionTime is now updated **according to Moodle's lastissued time**, though it still is set to the current time. Previously, we looked at the expiration time to determine whether the badge data had changed (because we didn't store the exact badge completion time). This was a proxy for "has the badge changed"; and is more directly served by instead asking whether the badge has been re-issued since the user completed the training last.
Incidental …
> [RW-7518][RW-6972][risk=low] syncComplianceTraining synchronizes CT training status

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/AdminAuditor.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/AdminAuditorImpl.kt
- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
This PR:
Audit logs will save:
1)  Request reason and date when the workspace is locked
2) Workspace state as unlocked in case of AdminUnlock request
---
> [RW-7544][risk=no]  Read and set an "admin locked" state for a workspace - Add audit logs 

- ui/src/app/components/breadcrumb.spec.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/navigation.tsx
Not sure if this is the ultimately desired behavior (may want different breadcrumbs), but it's a clear improvement to add missing breadcrumbs.
Also add a regression test for missing breadcrumbs.
---
> [risk=low][RW-7572] Use Workspace breadcrumbs on the Terminal page

- api/config/config_local.json
- api/config/config_test.json
Description:
Dataproc is created successfully, but https://github.com/all-of-us/workbench/blob/master/api/docs/pyspark-usage.md
not working. Seems to be different issue, will check in slack.
---
> [no ticket][risk=no] Roll forward private dataproc feature flag in test and local

- api/config/cdr_config_preprod.json
bumping preprod cdr version for next weeks preprod release.  Putting @NehaBroad as reviewer since she is release engineer next week. Updated the Release Playbook with entry on how to determine if [CDR publish is needed](https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#bookmark=id.5y2wpcggk65g)
RT publish command for preprod
`db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod 
--bq-dataset R2021Q3R2 --tier registered --table-prefixes cb_,ds_
`
CT publish command for preprod
`db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2021Q3R2 --tier controlled --table-prefixes cb_,ds_`
> [RW-7567][risk=no] bumping preprod cdr version

- ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/workspace-app-routing.tsx
A few pieces of RW-7575: disable adminLocked workspaces' Data and Analysis tabs, and redirect most WorkspaceRoutes to About if adminLocked
---
> [risk=low][RW-7575] adminLocked workspace routing / disable tabs

- api/config/cdr_config_test.json
These buckets already existed. The config now matches local.
> [risk=no] Add genomics buckets to tests

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/resource-actions-menu.tsx
- ui/src/app/components/resource-card.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-resource-card.tsx
- ui/src/app/pages/data/cohort/cohort-resource-card.tsx
- ui/src/app/pages/data/concept/concept-set-resource-card.tsx
- ui/src/app/pages/data/data-set/dataset-resource-card.tsx
- ui/src/app/pages/homepage/recent-resources.tsx
- ui/src/app/utils/resources.tsx
- ui/src/testing/stubs/resources-stub.ts
Recent Resources
- shows a Locked icon similar to Workspace Card
- the resource name is unclickable
- the resource actions menu (snowman) is gray and unclickable
---
> [RW-7575 ][risk=no] UX for admin-locked workspaces - Recent Resources

- api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
When creating the cb_search_person table the race and gender names have semicolons in them. For example PMI:Skip will be corrected to Skip.
> [no ticket][risk=no] correcting gender and race names in indexing build

- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/app/utils/analytics.ts
Updated per UX discussion:
- added clickableModules, containing distinct([nextModule, nextRequiredModule])
- the active module is always included as a clickableModule
- all clickableModules are interactive, but only the activeModule gets the CTA
- Specifically, if a CT module is available, it receives the CTA - but the DUCC is still interactive as CT modules are optional
> [RW-7518][risk=low] Integrate CT training module within registration

- .circleci/config.yml
CircleCI job failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/16001/workflows/2bcf807c-a477-41ce-a963-56d419e783a0/jobs/181645/parallel-runs/1).
Error was `Too long with no output (exceeded 1h20m0s): context deadline exceeded`.
> [no ticket][risk=no] Increase parallel_num and no_output_time for nightly tests

- e2e/app/page/notebook-preview-page.ts
- e2e/app/page/workspace-analysis-page.ts
- e2e/utils/runtime-utils.ts
- ui/src/app/components/messages.tsx
- ui/src/app/components/runtime-cost-estimator.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/components/runtime-summary.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/leo-runtime-initializer.spec.tsx
- ui/src/app/utils/leo-runtime-initializer.tsx
- ui/src/app/utils/runtime-utils.tsx
Changes:
- Factor out the `RuntimeCostEstimator` for reuse
- Factor out `RuntimeSummary` for reuse
- `LeonardoRuntimeInitializer` no longer allows lazy creation, this scenario throws an error instead.
- Add new `RuntimeInitializerModal` which shows a runtime preview and allows the user to confirm their last or default configuration.
For flow control purposes, my approach is the easiest I could come up with, though it may be tricky to follow at first, here is a pseudocode version:
```
try {
intializeRuntime();
} catch (NotFound) {
confirmed = await promptUser
if (confirmed)
initializeRuntime(default)
else
exit
}
```
Screenshares:
- [notebook preview page](https://pmi-engteam.slack.com/files/U5KGPEEPK/F02MLPNKVEF/notebook_preview_lazy_check.webm)
- [notebook redirect …
> [RW-7251][risk=no] Require user input for lazy runtime creation

- ui/src/app/pages/workspace/workspace-card.tsx
> [RW-7485][risk=no]  Locked state of a workspace is visible in the UI - icon alignment

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- ui/src/app/utils/index.tsx
Search terms with dashes(Sars-Cov-2) aren't returning matches in CB search. Had to add  double quotes around the search term for mysql full text index to match on words containing dashes. Also, removed use of parentheses as it was causing to many problems.
> [RW-7381][risk=no] adding exact match for synonyms

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
Matches terraform change in https://github.com/all-of-us/workbench-terraform-modules/pull/35 - can be merged in either order
---
> [risk=no][RW-6972] rm compliance_training_expiration_time from DbUser and ReportingUser

- ui/src/app/pages/workspace/workspace-actions-menu.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
Workspaces and Sidebar have a Workspace Actions Menu.  Update both so these actions are disabled if the workspace is admin-locked:
* copy
* share
* delete
---
> [risk=low][RW-7575] Workspace Action Menu actions disabled if admin-locked 

- ui/src/app/pages/homepage/data-access-requirements.tsx
And pass TemporaryRASModule as a child prop.
When enableRasLoginGovLinking = false:
---
> [risk=low][no ticket] rm getVisibleRTModules

- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/testing/react-test-helpers.tsx
- Use `key` distinction to avoid reusing the `LeonardoAppRouter` component - it currently does not support reuse. Currently this manifests as a prop change on the same component if you do a direct navigation.
- Switch to RouteLink so users can ctrl+click the terminal icon for a new tab if they want to
I'm out next week, so feel free to merge this for me if you approve.
> [RW-7591][risk=no] Fix terminal link interactions

- ui/src/app/pages/data/data-set/dataset-page.tsx
small refactoring as I happened to look at this file
---
> [risk=no][no ticket] code reuse for getCdrVersion() in dataset-page

- api/src/main/java/org/pmiops/workbench/workspaces/resources/ResourceFields.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceFields.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
Remove a lot of repeated `@Mapping` annotations from WorkspaceResourceMapper by creating 2 new POJOs `WorkspaceFields` and `ResourceFields`, and mapping these separately before merging into the final WorkspaceResourceMapper object.
---
> [risk=low][RW-5638] WorkspaceResourceMapper: merge WorkspaceFields and ResourceFields

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
No idea why it was originally implemented like this. Usage of `String.replaceFirst` was entirely unnecessary and was the cause of this bug.
> [RW-7498][risk=no] Fix FileDetail name mapping

- api/src/main/resources/workbench-api.yaml
I noticed the config payload was returning `"accessRenewalExpiry": null,`
> [risk=no] rm unused renewal config value

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
Inspired by #5962 
On master it fails like:
```
> Task :compileJava
/Users/thibault/src/aou/api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java:69: error: Unmapped target property: "accessRenewalExpiry".
ConfigResponse toModel(WorkbenchConfig config);
```
---
> [risk=low][no ticket] Use MapStruct to populate ConfigResponse

- api/db/changelog/db.changelog-180-remove-period-from-institution-short-name.xml
- api/db/changelog/db.changelog-master.xml
Description:
The previous PR: https://github.com/all-of-us/workbench/pull/5960
removes period when creating institution.
This PR update existing record. 
---
> [RW-7501][risk=low] Data fix to remove dot from institution short name

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/setupTests.js
Turns out there is no automated teardown of enzyme provided by our test harness after each test case, per https://github.com/enzymejs/enzyme/issues/911
The solution described above caused some complications, as using  a common DOM root caused an additional unmount on every `mount()` call within the same test case. It's possible that fixing the issues that arise there would be a more pure solution, but it would likely require retrofitting a bunch of our components.
Specifically, it would result in this error when attempting to reattach the component:
```
console.error                                                                                                                                                                                 
Warning: Can't perform a React state update on …
```
> [RW-7610][risk=no] Unmount enzyme React components after each test case

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Terra has overly restrictive email validation, so we can create users in an invalid state.  Until they loosen their restrictions (RW-7618) we need to also prohibit apostrophes.
---
> [risk=no][RW-7255] Prohibit apostrophes in usernames

- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/java/org/pmiops/workbench/db/dao/CdrVersionDao.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
getCdrVersionsByTier() now returns all tiers' versions if the user has RT access.  
Also some misc CDR Version Service/Test/DAO cleanup.
Tested by:
* observing both tiers by calling API as an RT-only user and a CT user
* running local UI and observing no changes to Workspace Edit/Duplicate functionality as an RT-only user or a CT user
---
> [risk=moderate][RW-7609] experiment: getCdrVersionsByTier() returns RT+CT tiers to RT users

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Add info icon to source/standard toggle in Conditions and Procedures searches with explanation on the difference between searching source and standard concepts.
---
> [RW-7365][risk=no] add tooltip to source standard toggle

- api/build.gradle
Jackson is a frequent source of vulnerabilities.  There's no active vuln that I'm aware of, but I figured it was a good idea to be proactive here.
This introduces an incompatibility with our older version of Kotlin, so that gets a bump too.
Tested by running a local API+UI and confirming that our Kotlin-based Workspace Auditing is functional.
---
> [risk=low][no ticket] Bump Jackson and Kotlin

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressTerraRuntimeLogPattern.java
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
This endpoint will be used to power an egress event admin page, to be used by the oncall for event investigation. Log entries are sourced from the Terra log sink (currently the SA only has permission in test, https://precisionmedicineinitiative.atlassian.net/browse/PD-6931 tracks permissions in higher environments).
> [RW-5661][risk=no] Implement egress event audit endpoint

- ui/.eslintrc.js
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
Fix quote issue.
I thought warnings would be flagged by the CircleCI checks, but it seems not. AFAICT, the only direct impact of this change is to change the output code and error logs from `yarn lint`.
> [risk=no] Switch eslint from warn -> error

- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/webapp/static/aou-file-tree-policy-extension.js
- api/src/main/webapp/static/aou-upload-policy-extension.js
- api/src/main/webapp/static/initialize_notebook_runtime.sh
This extension is a generalization of `aou-upload-policy-extension.js` to now warn on both upload and download - the upload extension will be removed once it is phased out of usage. This warning is shown when clicking download on the file tree. The approach is unfortunately hacky, but we are a bit limited with the changes we can make here.
> [RW-6459][risk=no] Add policy warning on Jupyter download from file tree

- ui/src/assets/icons/controlled-tier-badge.svg
This is shown when hovering the CT badge.
> [risk=no] Fix alt text for CT badge

- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
- ui/src/app/components/ct-available-banner-maybe.spec.tsx
- ui/src/app/components/ct-available-banner-maybe.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/stubs/cdr-versions-api-stub.ts
Clicking X closes the toast-banner and stores a cookie, preventing the user from ever seeing this again.
Clicking `complete the necessary steps` closes the toast-banner and routes to the DAR page.
Only triggers when all of the following conditions are met.
- the env allows users to see the CT in the UI
- the user does not have CT membership
- the user is CT-eligible
- the user’s first sign in time is BEFORE the creation time of the latest CT CDR
- the user has not yet acked the notification previously
---
> [risk-low][RW-7060] Show a toast-banner when the user is newly eligible for Controlled Tier 

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditor.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorImpl.kt
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/ProfileAuditorTest.kt
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Previously, we assumed that all `updateProfile()` calls were done by the user with the profile in question.  This is not the case.
Tested by running locally and observing corrected values in BigQuery.
Does not fully resolve RW-7632 because these audit entries are not visible in the UI.
---
> [risk=low][RW-7632] Record audit-log entries for updateProfile() correctly when done by admin

- api/config/config_test.json
Reverts all-of-us/workbench#5997
With this change, runtimes are failing to start in 30m, resulting in errors at seemingly 100%, presumably due to lack of caching. Revert for now to the prior flaky behavior.
After the Terra release tomorrow, will try to switch cache to 2.0.1 + 2.0.4 and then roll this forward.
> Revert "[RW-7617][risk=no] Try reverting NB image upgrade in test"

- api/build.gradle
Seems we're no longer hitting the kotlin directory issue, and it's unclear if this extra step ever did anything to help.
> [RW-6907][risk=no] Drop Kotlin generated directory workaround

- deploy/bootstrap-docker.sh
A new gradle build dependency requires write access to `~/.cache`, which we were initializing with root permissios in the bootstrap script. Going forward, we may want to preload this into the image, so we're not wasting time installing cloud sdk twice.
> [risk=no] Permissions fix for deploy

- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
Fixes issue where selecting the prepackaged All Participants cohort on an existing dataset does not enable the save button
---
> [RW-6887][risk=no] Fix dataset builder disabled save button bug

- api/src/main/java/org/pmiops/workbench/ras/RasLinkConstants.java
- api/src/main/java/org/pmiops/workbench/ras/RasLinkService.java
- ui/src/app/utils/access-utils.tsx
Description:
RAS will revoke AoU permission asking for ga4gh passport. And we don't need that. 
---
> [no ticket][risk=low] Stop asking for passport when user link RAS account

- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
`UserService.updateUserWithRetries()` is often called simply to trigger an access tier recalculation.  This leads to a lot of unnecessary `userDao.save()` calls, which we can avoid by exposing a standalone access tier recalc method.
This PR removes roughly half of these calls from our codebase.
---
> [risk=low][no ticket] make updateUserAccessTiers() public to avoid excessive user saves

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
- ui/src/app/pages/workspace/workspace-wrapper.tsx
If user without CT access tries to access a CT Workspace directly via  a link, they will be redirected to workspace List page.
https://user-images.githubusercontent.com/34481816/144875191-4065b31a-7a43-4470-a632-208732fa44a8.mov
---
> [RW-7608][risk=no]  Behavior for URL access by non-CT users to CT workspaces/resources

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
> [risk=low][no ticket] Actually update the user DB object when calling updateProfile()

- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
There's no need to instantiate this class.  Updated all references to static ones.
---
> [risk=no][no ticket] Make TestMockFactory fully static

- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- ui/src/app/pages/admin/admin-review-workspace.spec.tsx
- ui/src/app/pages/admin/admin-review-workspace.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/testing/stubs/workspace-admin-api-stub.ts
Move the following endpoints from WorkspacesController -> WorkspaceAdminController:
- {un,}publishWorkspace
- reviewWorkspace
- getWorkspacesForReview
**No behavioral or API changes**, just moving existing methods.
The workspace review endpoints **may** be unnecessary. I'm checking on that: https://precisionmedicineinitiative.atlassian.net/browse/RW-7640
> [RW-7511][risk=no] Move workspace admin endpoints into admin controller

- .circleci/config.yml
- ui/.eslintrc.js
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
"error" has the very annoying side-effect of causing the local dev server compilation to fail; I missed this initially.
--max-warnings 0 yields a non-zero exit code if there are more than 0 warnings, which is what I was originally trying to achieve with this change.
> [risk=no] Revert eslint to warn; fail CircleCI if there are any warnings

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- `enforceWorkspaceAccessLevel()` is only called from these methods to guard the active billing check - otherwise it would expose information about the billing status to any caller
- Actual access checks on the method are implicitly made by Leo, as we forward end user credentials for these interactions
- Originally, it made sense to have this check on getRuntime, which would lazily initialize the user's notebook runtime; however, that behavior no longer exists, so calling this method cannot increase compute spend
Most of the remaining calls to check valid billing in the other methods still apply, since they could affect spending in the workspace.
As a side-effect, we'll no longer generate 403s when a user loads a read-only workspace. It may not be terrible to allow this interaction, as we …
> [RW-7199][risk=no] Drop active billing enforcement on getRuntime

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
Bug occurred when clicking "try again" for error runtimes, after changing any of the runtime panel details. This can occur without the user having interacting with the runtime panel, e.g. if the defaults changed since they last created a runtime. Verified this regression test fails at HEAD.
> [RW-7647][risk=no] Fix recreating runtimes with changes on error

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- ui/src/app/pages/admin/admin-user-bypass.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/admin/admin-users.spec.tsx
- ui/src/app/pages/admin/admin-users.tsx
- ui/src/app/pages/admin/user-audit.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/stubs/user-admin-api-stub.ts
Stacked on #6015 
- Remove **getUser()**, **getRegisteredTierExpirations**, as they are unused
- Move the other admin methods to the new controller, with no functional / API changes
There were no controller tests to move in this case, as testing was only being applied at the service layer for these methods.
> [RW-7511][risk=no] Move user admin endpoints into new user admin controller

- api/config/config_test.json
After further investigation on https://precisionmedicineinitiative.atlassian.net/browse/RW-7617, I believe the image upgrade is unrelated to this class of errors. It may still be related to 500/503 issues, but I haven't been able to reproduce these yet. Roll this forward for further observation, after https://github.com/all-of-us/workbench/pull/6041
> [RW-7617][risk=no] Roll forward 2.0.4 again

- ui/src/app/pages/admin/admin-workspace.tsx
- Actual fix: rows=100
- Related cleanups:
- page size options are not specified, remove from template
- switch to attribute syntax for boolean props
> [RW-5654][risk=no] Fix paginator item count on workspace admin page

- api/src/main/java/org/pmiops/workbench/api/InstitutionController.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
When an Institution changes its tier requirements, sync the access tiers of all of its affiliated users.  (Currently this happens at nightly cron time)
---
> [risk=low][RW-7634] updateInstitution() syncs tiers for affiliated users

- ui/src/app/components/app-router.spec.tsx
- ui/src/app/components/app-router.tsx
- ui/src/app/routing/authority-missing.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
Note: this adds guard support for rendering alternate content in-place, rather than redirecting.
> [RW-7513][risk=no] Add guard for admin routes

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
~~**Do not merge**: until https://github.com/DataBiosphere/leonardo/pull/2464 is merged~~
Update: proceeding with this PR without having the cache in place. That should land later this week. I believe 2.0.6 should be fast enough to download and will hopefully reduce flakiness, so I think it is worth merging this before the cache goes in. Will revert if that's not the case.
- This pulls in the fix from https://github.com/DataBiosphere/terra-docker/pull/263 , which should address async failures in Jupyter
- Pulls in nextflow fixes
> [RW-7654][RW-7392][risk=low] Bump AoU notebooks image to latest

- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/EgressEventMapper.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/EgressEventMapperTest.java
- ui/src/app/pages/admin/admin-egress-audit.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
Bug on the backend due to timestamp conversion.
Egress table:
Egress audit page:
> [risk=no] Fix Egress event timestamp plumbing and display

- e2e/app/component/workspace-card.ts
- e2e/app/element/base-element.ts
- e2e/jest-puppeteer.config.js
- e2e/tests/ui/cohort-ui.spec.ts
- e2e/utils/test-utils.ts
Looks like the `findAllCards` function is flaky: clicking on card name fails on rare occasions.
It caused `dataset-ui.spec` to fail in this CircleCI [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/16042/workflows/530d3bd6-a0c3-4bf1-bffb-77e386fe1aa2/jobs/181979/parallel-runs/0?filterBy=FAILED).
> [no ticket][risk=no] Deal with e2e flaky functions

- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
The PrimeReact Data table will reset its internal page count to `0` every time a checkbox is checked. This can cause a blank table if on one of the middle pages when the filter is changed. Fixed by resetting all pagination values (to `0`) whenever a filter is changed.:
Before:
After:
---
> [RW-7541][risk=no] Fix navigation for participants in cohort review

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
Dataproc worker count updates are only possible while the runtime is running.
> [RW-7571][risk=no] Disallow worker count updates while stopped

- e2e/tests/profile/profile-page.spec.ts
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/utils/urls.ts
Initially I considered improving the error message to require a scheme, however - this seemed a bit too strict for an optional user profile field. I think we should just assume a scheme if not provided.
> [RW-7310][risk=no] Avoid excessive profile URL validation

- api/genomics/build.gradle
Maven is still having problems apparently.  But this is a temporary solution.
See also #6068
---
> [risk=low][no ticket] bump gatk to fix log4j issue

- api/buildSrc/build.gradle
- appengine-cron-emulator/build.gradle
Should resolve https://security.snyk.io/vuln/SNYK-JAVA-ORGYAML-537645
---
> [risk=low][no ticket] bump jackson to 2.13.0 for buildSrc and appengine-cron-emulator

- performance/build.gradle
Not sure if this will actually do anything (since I don't think we use it) but it should quiet a lot of noise here: https://app.snyk.io/org/all-of-us-researcher-workbench/project/31ce5c7a-17c1-49cd-a69b-cdc0a44a6772
Alt: remove this entirely.
---
> [risk=low][no ticket] bump perf gatling so Snyk stops complaining

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
If the current runtime is GCE, we **do not** want to disable the worker controls, since this is not an update, but rather a full recreate.
Confirmed regression test fails at HEAD.
> [risk=no] Fix edge case on worker count update disable

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
This upgrades the Hail version on the image, making it compatible with the latest Leo Dataproc image.
> [RW-7667][risk=low] Bump AoU image to 2.0.8

- api/build.gradle
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/api/DiskController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineWorkspaceController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/utils/FieldValues.java
Joda-Time was the de-facto Java standard package for good date/time handling ... before Java 8.  The [Joda team now says](https://www.joda.org/joda-time/) to use the built-in java.time package.
---
> [risk=low][RW-5275] rm last instances of joda.time

- api/libproject/devstart.rb
- e2e/utils/str-utils.ts
- e2e/utils/test-utils.ts
Testing a hypothesis for today's nightly test failures
---
> [risk=no][no ticket] Guard against empty e2e user access tokens

- .circleci/config.yml
Fix an error thrown by the CircleCI `puppeteer-generate-access-tokens` job. 
The error is caused by a race condition: When `puppeteer-generate-access-tokens` job ran before `puppeteer-env-setup` can finish. `yarn install` is called in `puppeteer-env-setup` job only. The error only happens when CircleCI is running a new PR for the first time.
```
#!/bin/bash -eo pipefail
yarn _impersonate-test-users
yarn run v1.22.5
$ yarn _create-signin-token-dir && env-cmd -x ../api/project.rb generate-impersonated-user-tokens --impersonated-usernames \$USER_NAME,\$READER_USER,\$WRITER_USER,\$COLLABORATOR_USER,\$ACCESS_TEST_USER,\$ADMIN_TEST_USER,\$EGRESS_TEST_USER --output-token-dir ../e2e/signin-tokens
$ mkdir -p ../e2e/signin-tokens
/bin/sh: 1: env-cmd: not found
error Command failed with exit code …
```
> [no ticket][risk=no] circleci restore-cache fallback

- e2e/package.json
The CircleCI job `puppeteer-generate-access-tokens` runs against a fresh checkout of the repo.  `node_modules` may not have been built yet.
Let's ensure that all modules (including `env-cmd`) have been built regardless, when the command is run.
---
> [risk=no][no ticket] run yarn install to ensure env-cmd exists

- api/db-cdr/changelog-schema/db.changelog-v2-1.xml
- api/db-cdr/changelog-schema/db.changelog-v2-2-cb_menu.xml
- api/db-cdr/changelog-schema/db.changelog-v2-3-domain_card.xml
When importing data into cloudsql instance as part of the indexing build we noticed that liquibase changed behavior:
type="Bool" was being created as data type bit in Mysql, but it was tinyint(1) before. This was causing problems with import and all 0 or 1 values were converted to 1.
> [no ticket][risk=no] fixing liquibase problem with type Bool now converting to bit data type

- e2e/tests/nightly/egress-suspension.spec.ts
I can't determine the source of the timeout, due to poor puppeteer logs. Add some additional logging to the test case; though I'll also investigate a more general solution.
> [RW-7652][risk=no] Add logs to egress test case

- e2e/app/page/notebook-cell.ts
- e2e/app/page/notebook-preview-page.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
The Calhoun export code was recently updated, which modified some of the HTML / CSS. Update to the new selectors.
Notebooks tests pass locally with these changes.
> [RW-7687][risk=no] Fix e2e notebook preview selectors

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- e2e/app/modal/export-to-notebook-modal.ts
- e2e/app/page/notebook-preview-page.ts
- e2e/tests/datasets/export-to-notebook.spec.ts
- e2e/utils/notebook-preview-utils.ts
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
Stacked on #6121 
Recent Calhoun changes resulted in different HTML and CSS. Specifically, there are styles which are now applied to the body tag; our previous sanitizer was stripping these out. On codegen preview, this would simply result in a rendering error - this is fixed. On both notebook and export preview, this would result in ugly formatting - this is also fixed.
Add test coverage to verify the export preview feature works.
Before:
After:
> [risk=low] Fix formatting for updated Calhoun notebook previews

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/GenerateImpersonatedUserTokens.java
- e2e/utils/test-utils.ts
Previously we used unix file ctime. This is problematic on CircleCI, as ctime will always be recent when we copy in tokens using the CircleCI workspace feature. Embedding the token creation time allows us to invalidate cached tokens without any dependency on file operations.
Format for these token files is:
```
{
"created_at_epoch_seconds": 123,
"token": "asdf"
}
```
> [RW-7688][risk=low] Improve e2e token invalidation by embedding creation time

- e2e/app/element/base-element.ts
- e2e/app/modal/new-notebook-modal.ts
- e2e/app/page/workspace-analysis-page.ts
This is a test code workaround to deal with puppeteer flaky `.click` function. I don't know why it doesn't work sometimes.
Example of failed CircleCI [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/16886/workflows/e386dbd4-969b-45c0-9fab-3c7401546553/jobs/188705/tests).
```
failure: [
'TimeoutError: waiting for XPath `//*[@id="popup-root"]//*[@role="dialog" and contains(@class, "after-open")]` failed: timeout 30000ms exceeded\n' +
'    at new WaitTask (/home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)\n' +
'    at DOMWorld.waitForXPath (/home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:441:26)\n' +
'    at Frame.waitForXPath (/home/circleci/workbench/e2e/node_modules/puppeteer/lib/cjs/ …
```
> [no ticket][risk=no] e2e test: Click Create a New Notebook button is not working

- .circleci/config.yml
Local UI server launched in CircleCI VM killed at random. I don't now why. Increase CircleCI VM class to prevent failures as a temporary solution.
```
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
error Command failed with exit code 1.
```
Failed CircleCI [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/17148/workflows/348a3866-dc1a-404f-a464-a212876f9a35/jobs/191006/steps).
> [no ticket][risk=no] Upgrade CircleCI puppeteer-executor resource_class to medium+

- e2e/app/modal/annotation-field-modal.ts
- e2e/app/modal/base-modal.ts
- e2e/app/modal/cdr-version-upgrade-modal.ts
- e2e/app/modal/cohort-review-modal.ts
- e2e/app/modal/cohort-save-as-modal.ts
- e2e/app/modal/conceptset-save-modal.ts
- e2e/app/modal/copy-to-workspace-modal.ts
- e2e/app/modal/dataset-create-modal.ts
- e2e/app/modal/dataset-rename-modal.ts
- e2e/app/modal/delete-confirmation-modal.ts
- e2e/app/modal/edit-delete-annotations-modal.ts
- e2e/app/modal/export-to-notebook-modal.ts
- e2e/app/modal/genomic-extract-confirmation-modal.ts
- e2e/app/modal/institution-not-saved-modal.ts
- e2e/app/modal/modal.ts
- e2e/app/modal/new-notebook-modal.ts
- e2e/app/modal/new-workspace-modal.ts
- e2e/app/modal/old-cdr-version-modal.ts
- e2e/app/modal/profile-confirmation-modal.ts
- e2e/app/modal/replace-file-modal.ts
- e2e/app/modal/share-modal.ts
- e2e/app/modal/warning-discard-changes-modal.ts
- e2e/app/modal/workspace-review-research-purpose-modal.ts
- e2e/app/page/workspace-edit-page.ts
Fix flakiness seen in two tests failed [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/17144/workflows/9d4fd2a4-89ec-47bd-a878-d6cadaf146cf/jobs/190965/tests).
- `cdr-version-upgrade.spec.ts`: Click the `CANCEL` button in Workspace Edit page fails to work intermittently due to the button is not ready when clicking (not enabled). Caused by intermittent slow network that slows down page loading.
- `workspace-create.spec.ts`: Create workspace failed after click CONFIRM button in modal but test did not fail immediately. Fix modal xpath so test will fail immediately next time if an error modal appears on top of Create Workspace modal.
> [no ticket][risk=no] e2e flaky test fixes

- api/build.gradle
- api/settings.gradle
According to [Gradle Blog](https://blog.gradle.org/jcenter-shutdown#troubleshooting)
The Gradle Plugin Portal implicitly mirrors JCenter currently. If you’re using the Plugin Portal (via gradlePluginPortal() or the URL plugins.gradle.org/m2) to resolve your application’s dependencies, you may be relying on JCenter. You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects.
> [no ticket][risk=no] removing repo url https://plugins.gradle.org/m2/

- e2e/app/page/notebook-page.ts
- e2e/tests/nightly/egress-suspension.spec.ts
- e2e/utils/runtime-utils.ts
Problem: running the egress notebook is problematic, as we may be suspended in the middle of the run (this pauses the notebook, and makes it unresponsive). Furthermore, we can get dialogs when trying to navigate away from the notebook page, since it may not be fully saved or completed running.
Solution: run the notebook in the "background", and then refresh/check for suspension in another tab. This avoids any dependency on the code running to completion.
> [RW-7652][risk=no] Mitigate egress suspension test timeouts

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Description:
This flag is never used. And we end up using: https://github.com/all-of-us/workbench/pull/6150/files
per the previous PR feedback
---
> [no ticket][risk=low] remove unsed flag

- e2e/app/component/concept-domain-card.ts
- e2e/app/page/conceptset-search-page.ts
CircleCI example [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/17275/workflows/849e1389-6821-40e0-b4bf-091be013d60d/jobs/192080).
e2e test `conceptset-create.spec` is failing due to [pull/6107](https://github.com/all-of-us/workbench/pull/6107)
Slack discussion [here](https://pmi-engteam.slack.com/archives/C7JUTPQLE/p1642106532043400?thread_ts=1642090598.039300&cid=C7JUTPQLE).
> [RW-7701][risk=no] e2e test failure workaround: Provide alternative xpath to find domain cards

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/stores.tsx
* Generalize the LeonardoAppRedirect component to support Spark console pages
* Add a pattern for forcing remount of a component based on parameter change; otherwise navigation from spark console -> spark console via the panel fails. `withParamsKey()`
Sample usage:
https://user-images.githubusercontent.com/822298/149268710-6da9e483-947a-495d-875c-f0ac9e3b2c2b.mp4
> [RW-7151][risk=no] Add Spark console links to runtime panel

- e2e/app/modal/base-modal.ts
e2e nightly test `owner-copy-to-workspace.spec` is failing caused by [pull/6107](https://github.com/all-of-us/workbench/pull/6107).
> [no ticket][risk=no] e2e test: Fix modal getText xpath

- ui/src/app/cohort-search/cohort-page/cohort-page.component.tsx
- ui/src/app/cohort-search/overview/overview.component.tsx
Fixes issue if the total count call for the first item added to a cohort has not returned before the second item is added, the second item won't be reflected in the total count.
---
> [RW-7694][risk=no] Fix CB total count when previous call not returned

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
Proposing to leave the value population going forward, so that we can use the column for historical reference in the db. Otherwise, there are rows in the DB that simply look like deleted workspaces, and are otherwise indistinguishable. If we ever need some kind of historical batch project cleanup - it would be important to understand what their migration status was.
Also, the free tier billing cron wants to grab undeleted workspaces. We explicitly do not want this to include pre-migration projects, as the google project association will be incorrect.
> [RW-5492][risk=no] rm deprecated billing migration status enum

- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
Fixes issue where expanding content is hidden on the last row of the participant detail table in cohort review. Now it will automatically scroll to show the hidden content.
Before:
https://user-images.githubusercontent.com/40036095/150019809-f65a40f0-532c-48ad-af29-4ba53567a3f9.mov
After:
https://user-images.githubusercontent.com/40036095/150019846-11d1946b-5666-4b22-97d8-0bdfa2031b76.mov
---
> [RW-7659][risk=no] Fix hidden content in participant detail table

- ui/src/app/components/help-sidebar.tsx
Fixes issue in Cohort Builder where clicking the back arrow when editing an existing search item causes an error and the screen goes blank
Before:
https://user-images.githubusercontent.com/40036095/150175827-4dc97f4f-1b8b-4efe-8ff1-d49bb4c4f7d4.mov
After:
https://user-images.githubusercontent.com/40036095/150175876-6aa17a53-a789-4f6c-8f5c-869b429d3c13.mov
---
> [RW-7710][risk=no] Fix blank page when clicking back arrow in CB

- e2e/resources/python-code/generate-egress.py
Slight mitigation for https://app.circleci.com/pipelines/github/all-of-us/workbench/17366/workflows/75365790-14ea-48e9-a65b-e538246321df/jobs/192896
Unfortunately we don't want to go too much higher, as we risk hitting the 1h egress window, which would get in the way a lot more when retrying a test run.
> [risk=no] Generate more egress in the nightly tests

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/utils/dates.tsx
Updates the Module table on admin page for the user to include each module's Completion/Expiration time. 
If the Date is null (say if the module has been bypassed) it will show '-' instead
---
> [RW-7715][risk=no]Add module completion/expiration status to table

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
Cherry-picked log4j upgrade onto the prior gatk jar version.
Currently testing this locally.
> [RW-7734][risk=low] Bump gatk jar override version

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataDictionaryTest.java
- api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
- Introduce a feature flag to be turned on only in test and local
- If the feature flag is on : 
Insert entries for dataset in user_recently_modified when
1) Data Set is created
2) Data set is updated 
and delete entries from user_recently_modified table when the data set is deleted.
---
> [RW-7613][risk=no] Include Datasets and Cohort Reviews in "Recently Accessed Items" list - insert data set entries

- e2e/tests/conceptsets/conceptset-create.spec.ts
- e2e/tests/datasets/dataset-create.spec.ts
- e2e/tests/datasets/dataset-export-notebook.spec.ts
- e2e/tests/datasets/dataset-snowman-menu-actions.spec.ts
- e2e/tests/ui/dataset-ui.spec.ts
These tests were disabled in #6200 since the changes to the `getValuesFromDomain` call didn't exist in the test env yet.
> [RW-7754][risk=no] Enable dataset puppeteer tests

- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/testing/stubs/data-set-api-stub.ts
These tests were disabled with #6200. This PR enables them with a slight refactor to work with the new UI changes.
> [RW-7752][risk=no] Enable dataset UI unit tests

- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserCodeOfConductAgreementDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserCodeOfConductAgreement.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- ui/src/app/pages/profile/data-user-code-of-conduct.spec.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Remove DbUser.dataUseAgreementSignedVersion (use a Join instead) and rename many instances of DUA to DUCC.
Wait for the 24 Jan release before merging.
Does not complete RW-4838.  Still remaining:
* ReportingUser
* AdminTableUser and user admin UI
---
> [risk=low][RW-4838] rm DbUser.dataUseAgreementSignedVersion and rename more DUA to DUCC

- api/config/cdr_config_preprod.json
Updating cdr in preprod for RT and CT. 
@calbach You're scheduled as the release eng next week... this will require a publish of cb_ and ds_ tables in preprod RT(R2021Q3R5) and CT(C2021Q3R5).
> [RW-7727][risk=no] Updating cdr in preprod for RT and CT

- e2e/resources/workbench-config.ts
- ui/src/app/components/runtime-cost-estimator.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/components/runtime-summary.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-utils.tsx
Supporting optional detachable disks: part (1/?)
**Note**: this PR temporarily removes the ability to configure PDs; the previously implemented UX was not directly usable in the new target mocks.
Refactor to support a more extensible model in the RuntimePanel:
* Extend the data model to support detachable disks + disk types
* Eliminate the separate PD selector
* Converge on a single state tracker (`RuntimeConfig`), rather than having one per field
* Add utilities to support converting to / from RuntimeConfigs, including with defaults
* Styling: fix cost overflow display issues
* Drop PD-specific unit tests for now, these will need to be rewritten against the new components
* Converge cost estimator utilities on common `RuntimeConfig` data model
> [RW-7582][risk=no] Refactor runtime panel for detachable PD support

- .circleci/config.yml
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/concept/concept-search.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
Prevents redundant calls to the api in these components:
- `cohort-actions` - prevents `getCohort` call if cohort is already loaded in `currentCohortStore`
- `concept-set-actions` - prevents `getConceptSet` call if concept set is already loaded in `currentConceptSetStore`
- `concept-search` - prevents multiple `getConceptSet` calls when loading an existing concept set
---
> [RW-7725][risk=no] Prevent duplicate cohort and concept set calls

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/utils/access-utils.tsx
[RW-7717](https://precisionmedicineinitiative.atlassian.net/browse/RW-7717)
When a module is required for RT or CT tier or both, display tier badge icons in AdminUser table.
EraCommon required for CT and RT:
EraCommon required for CT, not required for RT:
EraCommon required for RT, not required for CT:
EraCommon not required for RT and CT:
---
> [RW-7717][risk=no] Add required-for-tier badges to access module table in AdminUserProfile

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
Part 2/??
- Return `GceWithPdConfig` when a PD is configured
- Allow updating via `GceWithPdConfig`
- Remove unused / redundant values from the workbench API
> [RW-7582][risk=low] Fix PD runtime API interactions

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Add the current DUCC version to config instead of hardcoding.
We will need to support multiple "current" DUCC versions for RW-7616.  This PR doesn't change our requirement, but it sets us up to do so.
---
> [risk=low][RW-7616] Add the current DUCC version(s) to config and allow multiple

- ui/src/assets/icons/DAR/additional.svg
- ui/src/assets/icons/DAR/electronic.svg
- ui/src/assets/icons/DAR/genomic.svg
- ui/src/assets/icons/DAR/identifying.svg
- ui/src/assets/icons/DAR/individual.svg
- ui/src/assets/icons/DAR/physical.svg
- ui/src/assets/icons/DAR/survey.svg
- ui/src/assets/icons/DAR/wearable.svg
- ui/src/assets/icons/registered-tier-badge.svg
Some icons did not have helpful text when users hoover over them.  Example from the DAR page:
After:
---
> [risk=no][no ticket] Update alt text for Controlled Tier and DAR detail icons

- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/app/pages/data/criteria-search.tsx
Use the domain selected from the criteria menu instead of the domain from the tree node for any calls to load criteria for trees
> [RW-7814][risk=no] Fix UI calls for cross domain tree nodes

- api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java
- e2e/tests/nightly/user-access.spec.ts
> [no ticket][risk=low] Don't remove RAS linking status in e2e user access testing

- api/db-cdr/generate-cdr/init-new-cdr-db.sh
@dolbeew please checkout branch and run ./project.rb run-local-data-migrations, if it inserts data correctly, then this can be approved.
Hangs for Chenchal when copying files :
...
Copying gs://all-of-us-cb-test-csv/cb_survey_attribute.csv...                  
/ [16/26 files][  2.6 MiB/  2.7 MiB]  93% Done
Stacktrace suggestions:
If you experience problems with multiprocessing on MacOS, they might be related to https://bugs.python.org/issue33725. You can disable multiprocessing by editing your .boto config or by adding the following flag to your command: `-o "GSUtil:parallel_process_count=1"`. Note that multithreading is still available even if you disable multiprocessing.
Machine configuration:
MacOS Monterey Version 12.1
Google Cloud SDK 370.0.0
alpha 2022.01.21
app-engine-java 1.9.93 …
> [RW-7832][risk=no] fix for gsutil problem

- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
Fixes issue where search items with parameters of multiple criteria types duplicate all params for each criteria type on the cohort description page.
Before (Each condition type should only have 2 parameters):
After:
---
> [RW-7709][risk=no] Fix duplicate params in cohort description

- e2e/tests/nightly/admin/institution-admin-ui.spec.ts
institution-admin-ui.spec.ts >> updated the era toggle to false by default for RT Description:
> [RW-7831][risk=low]updated the era toggle to false by default, for RT

- api/src/main/java/org/pmiops/workbench/db/dao/UserCodeOfConductAgreementDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/api/AuthDomainControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Also fix a bug: we didn't ever reset the "DUCC name out of date" flag after users sign the DUCC again.
---
> [risk=low][no ticket] rm UserCodeOfConductAgreementDao and clean up some DUCC code

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/resources/workbench-api.yaml
Don't require the field `disk.name` when it's expected for it to be `""`.
> [RW-7582][risk=no] More disk API fixes

- api/src/main/webapp/WEB-INF/cron_prod.yaml
Description:
RAS rolling out is complete, now we can bring the cron job back in the next release
---
> [RW-7066][risk=no] enable sync user access cron job

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/utils/access-tiers.tsx
- ui/src/app/utils/access-utils.tsx
Populate ERA Commons as appropriate for the user’s institution and add a note at the bottom of the table accordingly.
RT required only:
RT and CT not required with institution name:
RT and CT required:
RT and CT not required without institution name:
---
> [RW-7717][risk=no] Set footer in Admin User table

- ui/src/app/pages/admin/admin-institution-edit.tsx
Adding a loading spinner in UI to show waiting.
https://user-images.githubusercontent.com/35533885/152575280-f38c6cc4-517e-455f-8d8b-ab8f08705832.mov
---
> [risk=no][no ticket] Add spinner when saving institution changes

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
Description:
Details see: https://precisionmedicineinitiative.atlassian.net/browse/RW-7743
Also, it is wired that from the log, I just saw 3 attempts. That means our RetryConfig is not correct. 
From the RetryConfig, we should start from 100ms, until 20s. But actually we just do 100ms, 200ms. 400ms. Then stop! 
https://196686-95247186-gh.circle-artifacts.com/0/JunitTestResult/tests/integrationTest/classes/org.pmiops.workbench.google.DirectoryServiceImplIntegrationTest.html#testCreateAndDeleteTestUser()
---
> [RW-7743] [risk=low] Retry on get user call. 

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/stubs/runtime-api-stub.ts
Stacked on #6225 
The interface is named `DiskApi`, not `DisksApi`.
> [risk=no] Rename disksApi -> diskApi

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
Description:
Similar issue for update SA account. We need more retry
---
> [RW-7743][risk=no] Retry when deleting user in test

- ui/src/app/pages/data/data-set/dataset-page.tsx
- Fix cross domain message showing for non-cross domain concept sets
- Prevent concept set selections when domain values are still loading from the previous selection. This was causing an infinite component update when multiple concept sets are selected quickly, which slows down and eventually crashes the UI
> [RW-7840][risk=no] Fix concept set selections in Dataset Builder

- e2e/tests/workspace/workspace-create.spec.ts
Create new workspace with minimum fields required are already tested in many other tests. Test coverage is unchanged after removal of test.
---
> [no ticket][risk=no] Remove redundant e2e createWorkspace test

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortService.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentlyModifiedResourceDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentResource.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentlyModifiedResource.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/service/UserRecentResourceServiceTest.java
This PR is to display recent resources using  the new table user_recently_modified_resource table
In case of TEST/LOCAL it will start displaying NOTEBOOK resources as well.
---
> [RW-7613][risk=no] Include Datasets in "Recently Accessed Items" list

- ui/src/app/components/runtime-cost-estimator.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/components/runtime-summary.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
Detachable PD part 4/??
This change should be a functional no-op; renames only.
**Context**: in working out some of the reattachable PD flows, I found that it will likely be cleaner to combine the state representation of the Runtime, and the detached disk (if any). The has the following benefits:
1. We can provide a unified view of an update being made, including whether a disk delete is requested
2. We can provide an accurate cost estimate; which **should** include the detached disk cost when the analysis environment is either deleted, or the active runtime does not have the disk attached.
Renaming `RuntimeConfig` -> `AnalysisConfig` will allow me to add a `detachedDisk` property in the next PR. This now represents the overall analysis environment, rather than just the active runtime.
> [RW-7582][risk=no] rename RuntimeConfig -> AnalysisConfig

- ui/src/app/pages/admin/admin-user-profile.tsx
Remove the redundant "Access Module Status" section
Don't update initial credit limit until save
---
> [risk=low][RW-7863] more AdminUserProfile cleanup

- ui/src/app/pages/admin/admin-user-profile.tsx
Also fixes a crash bug when modules are not present
Also don't display the ERA Commons note when ERA is not enabled
Tested by disabling some modules in config_local.json and running Local API+UI
---
> [risk=low][RW-7863] Only show enabled modules in table for AdminUserProfile

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
Update the existing functionality to update the entry in user recent resource on opening or creating a cohort review with resource type COHORT to cohort_review
---
> [RW-7810][risk-no] Add cohort review as user recent resource

- api/config/cdr_config_prod.json
promoting cdr in prod.
@yonghaoy tagging you as reviewer on this PR since you are release engineer next week. This will require a cdr publish in prod before deploying release to prod. [Documented here](https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#bookmark=id.hfa4tzr0afy5)
Publish command:
`db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset R2021Q3R5 --tier registered --table-prefixes cb_,ds_`
> [RW-7868][risk=no] promoting cdr in prod

- ui/src/app/routing/app-routing.tsx
This banner was displayed after the user is authenticated. I cannot verify that since there is a issue in login on safari. However its a good idea to show the banner always starting from the login page
---
> [RW-7741][risk=no]  [P2] Show warning banner when user is on a browser not supported by Workbench

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
After the access renewal config migration in #6271 has been released, remove the old config.
---
> [risk=no][no ticket] rm deprecated accessRenewal config

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
Ideally we'd have no nullable `Boolean`s, but sometimes it's necessary to work with them.  (Some examples are Swagger/OpenAPI and nullable DB fields)
One null-safe pattern to transform them into primitive `boolean`s is `Optional.ofNullable(value).orElse(false)` but there's a simpler and more readable way: ~`BooleanUtils.isTrue()`~  **[UPDATE]** `Boolean.TRUE.equals()`
---
> [risk=no][no ticket] Use Boolean.TRUE.equals() for nulllable Boolean interactions

- api/config/cdr_config_local.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_test.json
- api/db/changelog/db.changelog-188-cdr-bucket-paths.xml
- api/db/changelog/db.changelog-189-cdr-bucket-paths.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapperTest.java
- The old VCF vars are using incorrect terminology and will be removed (specifically, they are called BUCKET - but actually refer to storage paths); rename these
- Add new vars:
- Base data path (can use this for non-standard data files)
- Hail paths (wgs and microarray)
> [RW-7835][risk=no] Add new genomic CDR env vars

- api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionTierRequirement.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/utils/institutions.tsx
- ui/src/testing/stubs/institution-api-stub.ts
Edit Institution - copies domain list but not address when enabling Controlled Tier
Add Institution - same
---
> [risk=low][RW-7866] Update initial CT config behavior for Institutions

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
As requested by Joy in this feedback mockup: https://projects.invisionapp.com/share/C5121MQVD2ZB#/screens/464159071_feedback
Now looks like:
---
> [risk=low][RW-7863] UX-requested improvements for AdminUserProfile

- api/db/changelog/db.changelog-190-billing-migration-bug-backfill.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
This was a very dumb typo of an enum value, introduced here: https://github.com/all-of-us/workbench/pull/6162/files#diff-10c390a509b150d607054d8ec2023fd71fb59bf9ba364376272d24275e994cdeR37
Backfill and fix the data which was created this way.
The only code path that considers this enum value is the free tier billing cron, so this was the only part of the system affected.
> [RW-7906][risk=low] Fix incorrect billing migration enum value and backfill

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/access/AccessTierService.java
- api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/test/java/org/pmiops/workbench/access/AccessTierServiceTest.java
- api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
This is one of a series of PRs to help with Controlled Tier rollout.
Adding CT configurations to Institutions requires a CT DB entity. We can't currently construct one in Prod (and Stable) because (a) we do not have a CDR to populate, and UpdateCDRConfig requires one to add a tier DB entity and (b) there may be a risk of users becoming aware of the CT before we are ready to launch. **This PR partially addresses (b)**.  (a) is covered by #6355 and (b) is completed by https://github.com/all-of-us/workbench/pull/6354
Add a Feature Flag to restrict `getCdrVersionsByTier()` to only those tiers which we choose to show the users, instead of all tiers.  This also prevents errors related to tiers without CDRs (see #6355)
Local testing:
* add a new tier and observe that it does not appear in …
> [risk=low][RW-7907] Add a Feature Flag to control tier visibility to users

- ui/src/app/pages/admin/admin-user-profile.tsx
One option: We can just disable the access status, if admin is viewing their own user detail page.
---
> [RW-7863][risk=low] User should not be able to modify own's access status

- api/libproject/devstart.rb
- api/libproject/load_local_data_and_configs.sh
- api/tools/src/main/java/org/pmiops/workbench/tools/cdrconfig/UpdateCdrConfig.java
This is one of a series of PRs to help with Controlled Tier rollout.
Adding CT configurations to Institutions requires a CT DB entity.  We can't currently construct one in Prod (and Stable) because (a) we do not have a CDR to populate, and UpdateCDRConfig requires one to add a tier DB entity and (b) there may be a risk of users becoming aware of the CT before we are ready to launch.  **This PR addresses (a)**.  (b) is covered by #6353 and #6354 
Local testing for this tool update:
* attempt to add a new empty third tier with flag = false -> failure 
* attempt to add a new third tier with no default version and flag = false -> failure 
* attempt to add a new empty third tier with flag = true -> success 
* attempt to add a new third tier with no default version and flag = false -> success
* …
> [risk=low][RW-7907]Modify UpdateCDRConfig to allow empty access tiers, with a flag

- api/db-cdr/generate-cdr/create-tables.sh
When moving to new parallel CDR indexing build we missed that fact that cb_person gets created in the output dataset, but it's being created in the source dataset which results in an empty table that isn't used the the BQ source dataset.
> [no ticket][risk=no] Removing the creation of cb_person in source dataset

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
A proper test would be to remove a module status and show AdminUserProfile works.  I have not yet done that, but this change should be safe and an improvement regardless.
---
> [risk=no][RW-7598] Don't crash AdminUserProfile when a module status is missing

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/ct-available-banner-maybe.spec.tsx
- ui/src/app/components/ct-available-banner-maybe.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/pages/profile/data-access-panel.spec.tsx
- ui/src/app/pages/profile/data-access-panel.tsx
- ui/src/app/pages/profile/profile-component.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
- ui/src/testing/default-server-config.ts
- ui/src/testing/test-utils.ts
This is one of a series of PRs to help with Controlled Tier rollout.
Adding CT configurations to Institutions requires a CT DB entity. We can't currently construct one in Prod (and Stable) because (a) we do not have a CDR to populate, and UpdateCDRConfig requires one to add a tier DB entity and (b) there may be a risk of users becoming aware of the CT before we are ready to launch. (a) is covered by https://github.com/all-of-us/workbench/pull/6355 and **(b) is covered by this PR** and https://github.com/all-of-us/workbench/pull/6353
Tested locally in combination with #6355 - in an env where CT exists but is not visible to users, users cannot see it:
* Profile
* DAR
* Annual Renewal
* Create Workspace
* Get CDR Versions (API call)
---
> [risk=low][RW-7907] Use API accessTiersVisibleToUsers in UI

- ui/src/app/pages/admin/admin-banner.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/utils/validators.ts
The DB only allows 80 chars.
Tested locally by using the full 80 chars and observing that it wouldn't allow me to go over.
---
> [riisk=low][RW-7633] Restrict institutional role other-text to 80 chars

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-device.sh
- api/db-cdr/generate-cdr/build-cb-criteria-drug.sh
- api/db-cdr/generate-cdr/build-cb-criteria-fitbit.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-clin.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-labs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-snomed.sh
- api/db-cdr/generate-cdr/build-cb-criteria-observation.sh
- api/db-cdr/generate-cdr/build-cb-criteria-pm-cs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-pm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-snomed-condition.sh
- api/db-cdr/generate-cdr/build-cb-criteria-snomed-procedure.sh
- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
- api/db-cdr/generate-cdr/build-cb-criteria-visit.sh
- api/db-cdr/generate-cdr/build-cb-criteria-wgs.sh
- api/db-cdr/generate-cdr/cb-criteria-utils.sh
Description:
- Removed `wait` from build-cb-criteria-* scripts
- Edited function in `cb-criteria-utils.sh` to delete temp table after copying to destination table
---
> [RW-7932][risk-low] CDR indices - remove wait calls in shell scripts and delete temp tables

- api/config/cdr_config_preprod.json
- api/config/config_preprod.json
Confirmed this is the correct filter set for beta. Updated extraction workflow works with the new V2 GVS schema.
> [RW-7771][RW-7984][risk=low] Update preprod with beta WGS dataset and workflow

- deploy/libproject/deploy.rb
This state will only need to exist for maybe 1-2 releases. Proposing just always setting it for now and tearing down later, rather than plumbing through several layers and updating our playbooks.
Let me know if you feel strongly about adding the flag.
> [risk=no] Allow empty tiers during full deploy

- e2e/.env.circleci.local
- e2e/.env.circleci.test
I suspect current failures are caused by the group limit. We likely had high accumulation of groups due to the high percentage of createworkspace failures over the past several weeks.
> [risk=no] Bump to new AoU test user

- ui/src/app/pages/admin/admin-user-profile.tsx
Following style guide https://docs.google.com/document/d/1q3qgH8A3h9-al7bFxVcTq7-L0ZKqNiUiSPE35HoD4uc/edit#heading=h.wh77ujwecbkg
- Headers should only be in Title Case when they are the name of a page
- subheaders should only have the first letter capitalized
The only rule that was not followed was 
- Labels/axes in charts and tables should always be capitalized in Title Case
And that because of consistency. Joy has approved this and has checked with Shimon
---
> [RW-7863] [risk=no] Admin User Profile page case consistency

- api/src/main/webapp/WEB-INF/queue.yaml
Surprisingly, if task_age_limit and take_retry_limit and specified together - the task is retried until **both** conditions are exceeded. Per documention: https://cloud.google.com/appengine/docs/standard/java/config/queueref-yaml
We don't want to retry, since we're currently using the operation status to track pass / fail, which should be a terminal status.
> [RW-8006][risk=no] Don't retry workspace create/duplicate

- api/db/changelog/db.changelog-192-workspace-operation-add-queued-processing.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspaceOperation.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/pages/workspace/workspace-edit.tsx
Split (and deprecate) the PENDING state into QUEUED and PROCESSING for WorkspaceOperation.  Require a QUEUED state to process a queued task, to help guard against multiple execution.
Motivation is from https://cloud.google.com/tasks/docs/common-pitfalls
> Cloud Tasks aims for a strict "execute exactly once" semantic. However, in situations where a design trade-off must be made between guaranteed execution and duplicate execution, the service errs on the side of guaranteed execution. As such, a non-zero number of duplicate executions do occur. Developers should take steps to ensure that duplicate execution is not a catastrophic event. In production, more than 99.999% of tasks are executed only once.
---
> [risk=low][RW-8006] Add QUEUED and PROCESSING states to WorkspaceOperation

- api/config/config_prod.json
- api/config/config_stable.json
This will have no effect yet on the capabilities of stable/prod, as there are still no CT CDRs.
> [RW-7992][risk=low] Configure stable/prod for genomic workflow extraction

- ui/src/assets/icons/controlled-tier-badge.svg
I noticed on hover the inconsistency with the RT badge title.
> [risk=no] Capitalize CT badge title

- api/libproject/environments.rb
This config setting was needed to publish the WGS dataset to prod. Missed in previous PRs.
> [risk=no] Add missing source WGS project to prod config

- e2e/app/container.ts
- e2e/app/modal/cohort-save-as-modal.ts
- e2e/app/modal/dataset-create-modal.ts
- e2e/app/modal/new-notebook-modal.ts
- e2e/app/modal/warning-discard-changes-modal.ts
- e2e/app/page/workspace-edit-page.ts
Fix `clickButton()` because it didn't throw exception.
Issue: Puppeteer `waitForNavigation` function has failed before timeout and `fp` swallowed exceptions. `clickButton()` should have thrown exception.
Sample log after fix:
```
[3/9/2022, 13:46:00] - "[Test] Create Workspace | All of Us Researcher Workbench" page loaded.
[3/9/2022, 13:46:13] - Modal "Create Workspace" is open
[3/9/2022, 13:46:15] - Request finished: 200 POST https://api-dot-all-of-us-workbench-test.appspot.com/v1/workspaces/createAsync
{
"id": 1803,
"status": "QUEUED",
"workspace": null
}
[3/9/2022, 13:49:13] - Request finished: 200 GET https://api-dot-all-of-us-workbench-test.appspot.com/v1/workspaces/operations/1803
{
"id": 1803,
"status": "PROCESSING",
"workspace": null
}
[3/9/2022, 13:49:14] - FAIL: WaitUntilClose …
```
> [no ticket][risk=no] update clickCreateFinishButton function

- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/app/text-labels.ts
- e2e/tests/nightly/admin/user-profile-admin.spec.ts
- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
- e2e/tests/workspace/workspace-create.spec.ts
- e2e/utils/test-utils.ts
Description:
Updated Tier Badge textContent due to a recent change in UI which has caused test to fail.
After update, `enum Tier` in `user-profile-admin.spec` become the same as in `enum AccessTierDisplayNames` in `workspace-edit.page`. So it makes sense to move `enum AccessTierDisplayNames` from `workspace-edit.page` to `text-labels.ts`.
---
> [risk=no][no ticket] Fix e2e user-profile-admin.spec

- api/config/cdr_config_test.json
Description:
- Updated cdr-indexing build as per tickets [RW-7932 ](https://precisionmedicineinitiative.atlassian.net/browse/RW-7932 ) and [RW-7891](https://precisionmedicineinitiative.atlassian.net/browse/RW-7891) 
- This PR is to test the application to compare in test environment that `search-counts` match `registered-tier` (new cdrDbName) and `controlled-tier`
---
> [no ticket][risk=no] Changed default cdrIndexBuild for registered to synth_r_2019q4_30 in test only

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/testing/react-test-helpers.tsx
Users with incomplete Publications could not complete access renewal.
Note: it's not expected that such a user can get to the access renewal page, because we expect that even new users have complete Publications.   But we have seen bugs where this did not happen, and test users might get into this state.  It's an easy fix, so let's do it.
This does not complete RW-7961.
---
> [risk=low][RW-7961] fix bug for incomplete-publications users

- ui/src/app/pages/workspace/workspace-edit.tsx
I'm observing that sometimes the retry does actually succeed - in which case the operation can still be a success after 4-5m. I've yet to see a success which took more than 6 minutes.
> [RW-8044][risk=no] Bump async polling timeout from 3m -> 6m

- ui/src/app/utils/access-utils.tsx
`syncModulesExternal()` attempts to sync all modules in parallel under the assumption that modules are independent and that updating them won't conflict.
This is not actually the case!  The RT and CT compliance modules have the same external sync endpoint, and the callback from that endpoint updates the statuses of both modules.  So whenever `syncModulesExternal()` is called with both of these specified, there is a high likelihood of conflict.  I can reliably trigger this via the `unsafeAllowUserCreationFromGSuiteData` flow which results in a permanent spinner on the DAR page.  (refreshing generally resolves this)
This PR solves the problem by calling the external training sync endpoint **once** instead of **twice** if RT and CT training are specified.
Alternate solutions
* Optimistic …
> [risk=low][RW-8039] Fix DB conflict caused by syncModulesExternal()

- e2e/tests/datasets/dataset-export-py-notebook.spec.ts
- e2e/tests/datasets/dataset-export-r-notebook.spec.ts
Description:
`dataset-export-notebook.spec.ts` and `dataset-snowman-menu-export-notebook.spec.ts` are testing the same  thing, export to R and Python kernel notebooks. Both tests take very long time to run.
Refactoring tests to remove test coverage and code redundancy:
-  `dataset-export-r-notebook.spec.ts` test export to R notebook.
- `dataset-export-py-notebook.spec.ts` test export to Python notebook.
> [no ticket][risk=no] Avoid e2e dataset export to notebook test coverage redundancy

- ui/src/app/pages/workspace/workspace-card.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
Description:
https://user-images.githubusercontent.com/34481816/159295431-e9d42db5-d7e5-4973-a246-b7743cf9c908.mov
---
> [RW-5997][risk=no] Workspace cards should be open-able in a new tab

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
Description:
- new API call:`/criteria/ehrDomainCounts` controller call: findEhrDomainCounts
- new service call: findEhrDomainCounts
- calls existing service/dao methods
- Call cant be tested since the underlying SQL query is a `nativeQuery`
---
> [RW-8056][risk=no] Added new API for Universal Search call

- e2e/resources/python-code/disk-reattach-after.py
- e2e/resources/python-code/disk-reattach-before.py
- e2e/tests/nightly/detachable-disk.spec.ts
- e2e/tests/nightly/runtime.spec.ts
Previously reviewed as https://github.com/all-of-us/workbench/pull/6293. Now working after fixes from the Leo team.
- Create a runtime with a detachable PD
- Write some files to disk, including the disk size
- Recreate with GPU enabled (this forces a recreate) and increased disk size
- Verify the file is still there
- Compare the disk size, and verify increase
> [RW-7582][risk=no] Add persistent disk e2e coverage

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- ui/src/app/pages/data/concept/concept-homepage.tsx
Description:
- new findConcepCounts API - interim fixed concept-counts using `full_text like` clause 'FULLTEXT" index is not used. 
- UI navigation back to concept-search page is fixed. 
---
> [RW-8085][risk=no] Fixed - conceptCounts and UI navigation

- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/access/AccessUtils.java
- api/src/main/java/org/pmiops/workbench/access/UserAccessModuleMapper.java
- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/AccessModuleDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbAccessModule.java
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/AccessUtilsTest.java
- api/src/test/java/org/pmiops/workbench/access/UserAccessModuleMapperTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserAccessModuleDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java
Not super exciting by itself, but this is one step in a larger effort to address the confusion between the very similar `AccessModule` API entity enum and the `AccessModuleName` DB enum.  See #6328 for more on this idea and #6325 for a speculative extension.
Split into smaller PRs for easier digestion.
---
> [risk=no][no ticket] rename AccessModuleName to DbAccessModuleName

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Now that the async create/duplicate workspace code has been running smoothly in all environments for a while, we can remove it associated UI flag.
---
> [risk=no][RW-8036] rm env flag enableAsyncWorkspaceOperations

- ui/src/app/pages/workspace/workspace-edit.tsx
Quick-fix for the problem described in RW-8094.  We may choose to do additional UX work under this story as well.
Update Workspace no longer shows the notification
Duplicate Workspace still shows the notification
Description:
---
* AoU UI
> [risk=low][RW-8094] don't show "workspace creation will take 1 minute" when not creating

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/runtime-presets.ts
- ui/src/app/utils/runtime-utils.tsx
In the event that a user has an existing disk, but no cloud environment, we should select their PD by default when they go to create a new runtime.
> [RW-8084][risk=no] Reattach to existing disk by default, if possible

- api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java
I broke it with #6328 
Tested locally.  This command failed before the fix, and now runs successfully.
```
./project.rb set-access-module-timestamps --user puppetjoel5@fake-research-aou.org
```
(this modifies the above user.  feel free to do so.)
---
* AoU UI
> [risk=no][RW-8103] fix SetAccessModuleTimestamps

- api/config/cdr_config_prod.json
Rebuilt indices for prod:
New RT CDR indices for prod - "cdrDbName": "r_2021q3_9"
New CT CDR indices for prod - "cdrDbName": "c_2021q3_10"
Changes to cdr_config_prod.json
@aweng98 You're the release engineer. Please be sure to run the following publish commands for prod before deploying to prod.
--RT publish
api$ db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset R2021Q3R5 --tier registered --table_prefixes cb_,ds_
--CT publish
api$ db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset C2021Q3R6 --tier controlled --table_prefixes cb_,ds_
Referenced in Release Playbook: https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#bookmark=id.hfa4tzr0afy5
> [RW-8090][risk=no] Updating CDR for prod

- api/config/cdr_config_preprod.json
Description:
Build indices for RW-8062 and RW-8046 in preprod:
- New RT CDR indices for preprod - `"cdrDbName": "r_2021q3_9"`
- New CT CDR indices for preProd - `"cdrDbName": "c_2021q3_10"`
Changes to `cdr_config_preprod.json`
@aweng98 You're the release engineer next week. Please be sure to run the following publish commands for preprod before deploying to preprod.
```
--RT publish
api$ db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset R2021Q3R5 --tier registered --table_prefixes cb_,ds_
--CT publish
api$ db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2021Q3R6 --tier controlled --table_prefixes cb_,ds_
Referenced in Release Playbook: https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo …
```
> [RW-8089][risk=no] Updated CDR release for preProd

- ui/src/app/pages/workspace/workspace-card.spec.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/pages/workspace/workspace-list.spec.tsx
- Fix a regression in https://github.com/all-of-us/workbench/pull/6474 , whereby clicking the workspace card normally resulted in a full page refresh rather than a normal navigate. While there was a normal call to navigate, there was no suppression of the regular `<a>` behavior, which is to navigate to the given URL. Switching to `StyledRouterLink` makes the behavior correct in both cases.
- Fix a regression from the same PR which would dispatch a Google Analytics tracking event every time the card is rerendered.
> [RW-5997][risk=no] Fix normal workspace card navigation

- api/src/main/java/org/pmiops/workbench/db/model/DbDataset.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/ResourceFields.java
- api/src/test/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapperTest.java
- Dataset.lastModified is nullable, and is null for some cases in prod, ResourceFields.lastModifiedTime therefore also should support null
- Add Mapper regression test
- QOL improvements : chainable setters for DbDataset, ResourceFields
Tested with local dev server, manually nulling out dataset.last_modified in the DB.
> [RW-8051][risk=no] Support nullable last modified dataset

- ui/src/app/components/icons.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
Tested locally.  Observed the following at the URL `http://localhost:4200/data-access-requirements?pageMode=ANNUAL_RENEWAL`
Styling issues may need to wait until future PRs - please note that this is feature-flagged and therefore not visible in Prod 
Minimal changes observed when viewing the standard modes of DAR and AAR, and these are improvements:
* AAR: removed "provide" from "to provide keep your profile information up-to-date"
* DAR: stopped hard-coding the heights of the cards, which now look more natural
---
* AoU UI …
> [risk=low][RW-7796] Update DAR-Renewal-Mode with renewal text

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> [RW-7834][risk=no] Require TOS acceptance on login when users are not Terra-TOS compliant

- ui/src/app/pages/login/account-creation/account-creation-tos.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
Existing functionality, on clicking next on  terms of service page, there is no way of knowing that the page is processing the request. This could create confusion for user, if the terms of service acceptance takes a long time and they might start clicking the next button multiple times.
Solution:  On clicking next: Disable Next button and show a spinner
TERRA TOS ACCEPTANCE 
https://user-images.githubusercontent.com/34481816/160721318-5ea97bd6-7c0f-43b0-835f-e25af461465f.mov
ACCOUNT CREATION FLOW (this is really quick since there is no API interaction so we see no difference):
https://user-images.githubusercontent.com/34481816/160721378-9c8e3bf8-61bb-4edf-b363-cd8eaa523805.mov
---
* AoU UI
* [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scal …
> [RW-7834][risk=no] Add Spinner to Account TOS page after clicking next button

- ui/src/app/pages/access/access-renewal.tsx
On the AAR and DAR-Renewal-Mode pages, make the radio button text grey if the buttons can't be clicked. 
Before
After
---
* AoU UI
> [risk=no][no ticket] style publications radio button text as disabled where appropriate

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- ui/src/app/pages/data/concept/concept-add-modal.spec.tsx
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-list.tsx
- ui/src/testing/stubs/cohort-builder-service-stub.ts
Description:
Removed unused CohortBuilderController API calls 
- findDomainCountByStandardSource and 
- findSurveyCount
and relevant methods and response objects from
- all yaml entries and response objects
- CohortBuilderController and Test classes 
- CohortBuilderServiceImpl and Test classes
- CBCriteriaDao and Test classes 
UI:
- updated all *.ts, *.ts and *.spec files to remove references to non-existing classes and objects/ unused vars
---
* AoU UI
> [RW-8055][risk=no] Remove unused CohortBuilderController API calls - take-2

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
Description:
- Fix for the full text index.  split on `'_rank1'` instead of  `'_'`
-  ref [PR#6505](https://github.com/all-of-us/workbench/pull/6505)
---
* AoU UI
> [RW-8130][risk=no]Fix full text indexing lookup in sql 

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_test.json
We're currently seeing `ZONE_RESOURCE_POOL_EXHAUSTED` in us-central-1f
> [risk=no] Switch local/test/perf VMs to us-central1-c

- api/db-cdr/generate-cdr/build-cb-criteria-full-text-synonym.sh
fixing BQ concat problem. When using the CONCAT function if a column is null, then the function will output null as a result. To fix this issue converted call to use ARRAY_TO_STRING instead. 
Reference: https://stackoverflow.com/questions/43420308/any-concat-variation-that-tolerates-null-values
> [no ticket][risk=no] fixing BQ concat problem

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
This has been flaking at a high rate for the past several weeks. Ignore until we have time to further investigate.
> [RW-7743][risk=no] Ignore flaky directory service test case

- ui/src/app/pages/admin/egress-events-table.spec.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
Bug: when changing the status for multiple events within the same client session, the picker state would bleed across rows and show the most recent updated state. This meant you had to switch the state back/forth before saving to actually make it update properly.
Added regression test which fails without this fix.
https://user-images.githubusercontent.com/822298/161840986-12ad9de0-d511-41d5-8503-d129bb465c2b.mp4
> [risk=no] Fix stale egress event status picker

- api/db-cdr/generate-cdr/copy-bq-dataset.sh
- api/db-cdr/generate-cdr/libproject/devstart.rb
Verify that a dry run of the table copy shows the same number of lines for: source -> ingest, as ingest -> dest
> [RW-8053][risk=no] Add additional validation during CDR publishing

- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
Would be nice if we can get `junit` off the classpath to avoid these kinds of errors. Maybe we still need some stuff from here though.
> [RW-7743][risk=no] Actually skip flaky DirectoryService test case

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
- fix awk fat-finger syntax error: `awk '{i*s*(NR>1)print}'` -> `awk '{if(NR>1)print}'`
---
* AoU UI
> [no-ticket][risk=no] Fix awk syntax error extracting max of id column

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
- Fix ds_linking table OMOP 52 -> use QUALIFIER_SOURCE_VALUE 
---
* AoU UI
> [no-ticket][risk=no] Fix column_name for OMOP 52 ds_procedure_occurrence

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/iam/IamService.java
- api/src/main/java/org/pmiops/workbench/iam/IamServiceImpl.java
- api/src/main/resources/workbench-api.yaml
Tested locally by itself and with #6519 
Workspace Share and Duplication continue to work, with expected API JSON output
---
* AoU UI
> [risk=low][RW-7586] Keep going after failing to set Workflow Runner roles

- e2e/app/page/create-account-page.ts
- e2e/tests/user/create-account-ui.spec.ts
- ui/src/app/pages/login/account-creation/account-creation-tos.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
- ui/src/styles.css
Asks user to re-review TOS during access renewal.
To reject the TOS for manual testing:
---
* AoU UI
> [RW-8118][risk=no] Add notification to top of new TOS page

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
Description:
- Added parent feature flag: enableMultiReview and set it to false in all environments
- set the default value of the enableMultiReview=false in all environments
---
* AoU UI
> [RW-7935][risk=no] Feature Flag: create feature flag: enableMultiReview

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
Description:
- new api for getting multiple cohort reviews for a given cohortId
- added controller test
---
* AoU UI
> [RW-7940][risk=no] new API to returning List of cohort reviews given cohortId

- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
Description:
Updated data access requirements page to include Controlled Tier training.
---
* AoU UI
> [RW-7798][risk=low] Add Controlled Tier Training to Annual Renewal Page

- api/src/main/webapp/static/initialize_notebook_runtime.sh
Prior bug: interactions with iframed Jupyter pages such as the terminal do not affect the inactivity timer
Tested by manually running the command on my notebook server, and observing activity signal being sent from the terminal application after refresh.
> [RW-8147][risk=no] Capture inactivity tracking on all Jupyter pages, not just notebooks

- api/build.gradle
Google has notified users of Google Cloud Storage that pre-2.3.0 versions will start failing soon:
> Update your Java Storage client to version 2.3.0 or higher to read/write Google Cloud Storage buckets with new lifecycle actions by June 20, 2022. You can find more details for the latest version in the [Maven Central Repository](https://notifications.google.com/g/p/AD-FnEzPA_Ih75WoC5dQLUhKwrdkT7xc5aiOkJ23lqxdqjxZIXLOFbkSJk23lPpzHRmhm_XrGD-XzNGdIHn_IxH-otcZFRqhT0B_-utN9EUtogftwmboJkJ-5f6KqcbwyuurbK7cXXFWXHzx4F2Ej16z1k9rfB6Wi_VwFk3GuFC4uhA).
Tested locally by running local API and creating a workspace and a notebook.
---
* AoU UI …
> [risk=low][no ticket] bump GCS to 2.3.0

- e2e/app/page/notebook-page.ts
- e2e/app/sidebar/runtime-panel.ts
- e2e/tests/nightly/egress-suspension.spec.ts
- e2e/utils/runtime-utils.ts
Propose some changes hopefully to make the test run reliably.
---
* AoU UI
> [RW-8175][risk=no] E2E nightly egress test

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
> [risk=low][no ticket] Fix the access-renewal UI guard when RT renewable modules are incomplete

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
> [RW-8158] Check user has permission to share(owner) in a workspace

- api/db/vars.env
- api/src/main/java/org/pmiops/workbench/api/UserController.java
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
We can enable this dropdown because if user has no balance, there will not be the free tier billing option
---
* AoU UI
> [RW-8184][risk=low] Do not disable billing dropdown even user has no ballence

- ui/src/app/pages/login/account-creation/account-creation-tos.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/routing/app-routing.tsx
Lost conditional for notification (based on whether the user is new or not) in original PR. Adding back.
Tested manually using existing user and then going through the first part of the flow for creating a new user. Note that incognito window results in a blank page and may be worth further investigation.
---
* AoU UI
> [RW-8118][risk=low] Re-add notification conditional

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceBQTest.java
- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortAnnotationDefinitionControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/AnnotationQueryBuilderTest.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/LiquibaseTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
The existing user used for impersonation tests was non-tos-compliant, so the test failed.  Keep this user to show that this does fail for non-compliant users.  Add a new compliant user to meet the original test's purpose.
---
* AoU UI
> [risk=no][RW-8212] Update Firecloud impersonation tests for ToS

- ui/src/app/pages/workspace/workspace-share.tsx
Here's an initial attempt to explain that the Workflow Runner role has not been granted to ToS-non-compliant collaborators, and the current steps required to fully recover from this scenario.
In this video, the user joelt3 is ToS-**compliant** and the users joel2 and joel4 are ToS-**non-compliant**
(text is a bit out of date, see above for latest)
Not included here:
* UX for the opposite problem: failure to remove a Workflow Runner role from ToS-non-compliant users after unsharing (or access level downgrade)
* UX for failure-to-grant when Duplicating Workspace, which has the same problem
---
* AoU UI …
> [risk=low][RW-7586] Inform the user when workspace sharing does not grant workflow runner roles

- ui/src/app/routing/guards.spec.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
Last week I noticed that my user got into a state where it couldn't recover because it was being forcibly routed to DAR when it had a non-DAR module that needed updating.  My solution was #6569 
However, this introduced additional problems.  For example, new users (who by definition have incomplete modules) were being forcibly routed to AAR, where they could not complete the set of modules required by DAR.  So I reverted this: #6584
I believe that this now handles all combinations in the right way.
---
* AoU UI
* …
> [risk=low][RW-8203] Consolidate access module routing and special-case the non-bypassable modules

- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
Per comment, all users have access to projects in the TDR folders. This is therefore not a helpful signal.
> [RW-8245][risk=no] Update audit cron with TDR folders

- ui/src/app/components/admin/admin-user-link.tsx
- ui/src/app/pages/admin/admin-egress-audit.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
- ui/src/app/pages/admin/user/admin-user-table.tsx
- ui/src/app/utils/index.spec.tsx
- ui/src/app/utils/index.tsx
Contact Email is now clickable to send the user an email (not demonstrated here because my browser is not confgured for this)
Username is now clickable and opens the AdminUserProfile page for that user in a new tab
Add an AdminUserLink component and add tests for usernameWithoutDomain.  Tested locally, has the same behavior:
* AdminUserTable, new tab
* AdminEgressAudit, same tab
* EgressEventsTable, same tab (no-op when it's the table within the AdminUserProfile)
---
* AoU UI
> [risk=no][RW-7919][RW-8256] Make AdminUserTable username and contact email clickable

- ui/src/styles.css
https://user-images.githubusercontent.com/24514630/165165792-4a939102-35dd-4cc8-8fb4-e253a650e078.mov
Description:
Updated styling to include a border on the right side of the frozen columns. The lack of border was [a design choice by the component library (PrimeReact). ](https://github.com/primefaces/primeng/issues/7755)
Alternatives considered:
- Placing the styling directly on the admin user page - decided against this, because we will want this styling to be consistent across all instances of datatable.
- Placing styling in a new file called datatable.css - there is already a file called datatable.ts that contains styling for a few specialized instances of datatable. I suspect that this will need to be moved somewhere else before datatable gets a css file for the generic case in order …
> [RW-7918][risk=no] Updated styling for datatable for frozen columns

- api/config/config_test.json
- e2e/app/component/tiered-menu.ts
- ui/src/app/cohort-search/cohort-criteria-menu.tsx
Fix e2e tests that broke on initial flip of `enableUniversalSearch` and re-enable flag.
I ended up updating the new menu to work with the existing tests (using `ul`, `li` and `a` instead of `div`s) instead of changing the tests.
Note: If you need to test with the new menu locally, add a `!` in front of the `enableUniversalSearch` flags in these components:
- [search-group-list line 333](https://github.com/all-of-us/workbench/blob/dolbeew/RW-8237/ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx#L333)
- [search-group line 744](https://github.com/all-of-us/workbench/blob/dolbeew/RW-8237/ui/src/app/cohort-search/search-group/search-group.component.tsx#L744)
> [RW-8237][risk=no] Fix cohort e2e tests for new menu

- api/config/cdr_config_local.json
- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/libproject/environments.rb
Normally when you start a local API server, your membership in the test auth domain might be affected, if access module completion is divergent. This can result in confusing access failures in the test env. To avoid this issue, I created another set of auth domains exclusively for local.
- publish-cdr --project all-of-us-workbench-test now adds both the test auth domain, and the local auth domain
- after this merges, local group membership may need to be refreshed, e.g. via the admin table disable/enable, running the access sync cron (this might run on start) - or simply by resetting your local DB
> [RW-5780][risk=no] Switch the local API server to use alternate auth domains

- api/config/config_stable.json
- api/libproject/environments.rb
- e2e/resources/workbench-config.ts
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.stable.ts
This aligns stable more closely with production, and enables equivalent WAF configuration. This was abandoned some time ago, and was not possible until recently when some of the DNS records were finally fixed.
Current state:
- all-of-us-rw-stable.appspot.com works, backed by api-dot-all-of-us-rw-stable.appspot.com
- stable.fake-research-aou.org works, backed by api-dot-all-of-us-rw-stable.appspot.com
State after this PR:
- all-of-us-rw-stable.appspot.com works, backed by api.stable.fake-research-aou.org
- stable.fake-research-aou.org works, backed by api.stable.fake-research-aou.org
Future state, after config changes:
- stable.fake-research-aou.org works, backed by api.stable.fake-research-aou.org
- direct external appspot traffic is blocked
- (possibly) direct appspot traffic is …
> [RW-1386][risk=low] Switch stable to use custom AoU domains

- ui/package.json
- ui/src/app/components/genomics-extraction-menu.tsx
- ui/src/app/components/genomics-extraction-table.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/data/data-set/genomic-extraction-modal.spec.tsx
- ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx
- ui/src/app/utils/stores.tsx
- ui/yarn.lock
Automatically refresh pending genomic extraction jobs, and deduplicate state requests using SWR.
This is a first integration of [SWR](https://swr.vercel.app/) into the Workbench, specifically it is being used here to manage shared state across different areas of the application (side bar icon, genomic extraction table, genomic extract launch modal / menu). SWR is used to implement refresh polling, as well as handle stale data.
Overall, it's a bit chattier by default than I might like (re-requests data when you return to the page, for example), but it was pretty easy to set up. This is behavior that can be tuned if we want to.
Note: on abort, ideally I would use an optimistic data update. Unfortunately it's not possible here because Cromwell does not function as expected w.r.t. abortJob …
> [RW-8031][risk=no] Dynamically update extraction jobs via SWR

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-presets.ts
- ui/src/testing/stubs/runtime-api-stub.ts
According to Leo team, this may be causing some creations to time out.
Refactor min disk size to a central location.
> [RW-8228][risk=no] Bump runtime min disk size

- ui/src/app/components/genomics-extraction-table.tsx
Exposure of job cost via the API is an unimplemented feature of genomic extraction jobs. We should not display the column until it is implemented.
> [risk=no] Drop unpopulated job cost value from genomic extract table

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- e2e/resources/python-code/import-libs.py
Roll-forward, temporarily disabling a part of the test which was causing issues. I'm going to try and fix this in the next image version, but my assessment is that this regression is not critical enough to warrant blocking the image upgrade here (this upgrade has been pending for weeks): https://precisionmedicineinitiative.atlassian.net/browse/RW-8293
The workaround to this issue is:
```
pip install --upgrade --no-dependencies pandas_profiling
```
Verified locally that the notebooks tests which previously failed are passing now.
> [RW-8167][RW-8150][RW-8112][risk=no] Re-bump AoU notebook image

- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/user/admin-user-bypass.tsx
Also deprecate module completion times, which are no longer used after #6629
After one release cycle, we can then remove DataUseAgreementBypassTime and module completion times from AdminUser
Description:
---
* AoU UI
> [risk=low][RW-4838][RW-7917] DataUseAgreementBypassTime -> DuccBypassTime and deprecate AdminUserTable completions

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- e2e/resources/python-code/import-libs.py
Reverts all-of-us/workbench#6643
This seems to have caused issues with both dsub and Hail.. reverting again.
> Revert "[RW-8167][RW-8150][RW-8112][risk=no] Re-bump AoU notebook image"

- api/db/local-vars.env
- api/docker-compose.yaml
- api/libproject/devstart.rb
Tested by running
`./project.rb dev-up`
`./project.rb connect-to-db`
`./project.rb connect-to-cloud-db`
---
* AoU UI
> [risk=low][no ticket] rename the local version of vars.env to local-vars.env

- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
These broke as we changed the defaults, and don't seem critical for this test case.
**In Progress**: locally verifying this fix
> [risk=no] Drop unnecessary assertions on genomics extract tests

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewService.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohorts/CohortService.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentlyModifiedResource.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
The new recent-resources table `user_recently_modified_resource` does not have a delete-cascade DB relationship with the Data resources (Cohort, Cohort Review, Concept Set, Dataset) so it's possible to get into a state where the recent-resources table refers to non-existent resources.  Certainly we are also attempting to ensure this doesn't happen in the code, but it is possible to protect against this more reliably, so let's do so. 
Because it's impossible to ensure that Notebooks in the table exist (users have access to the Jupyter file manager, and can delete, rename, etc) we already have protection against non-existent Notebooks.  This PR extends this to the Data resources.
Tested locally:
`main` branch
Create a variety of Data resources and observe that they appear on the homepage as …
> [risk=low][RW-8314] Don't crash on missing recent-resources references

- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/routing/guards.spec.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Description: Updated module expiration redirect to only apply to RT modules. Also deprecated anyModuleHasExpired field.
---
Ran api unit tests locally. Manually expired ct modules and made sure there was no redirect. Manually expired rt modules to make sure I was brought to the annual renewal page.
* AoU UI
> [RW-8236][risk=no] Updated module expiration guard and deprecated anyModuleHasExpired.

- api/src/main/java/org/pmiops/workbench/access/UserAccessModuleMapper.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/profile/data-user-code-of-conduct.spec.tsx
- ui/src/app/pages/profile/data-user-code-of-conduct.tsx
- ui/src/app/pages/profile/demographic-survey-panel.tsx
- ui/src/app/pages/profile/profile-component.spec.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/profile/profile-styles.ts
- ui/src/app/pages/profile/signed-ducc-panel.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/utils/code-of-conduct.tsx
- ui/src/testing/default-server-config.ts
- ui/src/testing/stubs/profile-api-stub.ts
If a user has signed **the latest version of the** DUCC, a link to view it will appear in their profile:
If a user has not signed the DUCC, they will not see this link in their profile.  If they happen to type `/signed-ducc` manually into their browser (unlikely!) they would see this:
Users who have signed older versions of the DUCC, they will also not see this link in their profile.  If they happen to type `/signed-ducc` manually into their browser (unlikely!) they would see this:
See also the prototype at #6651 
---
* AoU UI …
> [risk=low][RW-8126] Show a link to the signed DUCC in the Profile

- api/build.gradle
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/DSLinkingDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortFactoryTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/DataSetDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/model/StorageEnumsTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
- api/src/test/java/org/pmiops/workbench/monitoring/LogsBasedMetricsServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Some method calls had to be changed to their new equivalents:
`containsAllOf()` -> `containsAtLeast()`
`containsAllIn()` -> `containsAtLeastElementsIn()`
`isSameAs()` -> `isSameInstanceAs()` or `isEqualTo()`
`named()` -> `assertWithMessage()` (different syntax)
`isStrictlyOrdered()` -> `isInStrictOrder()`
I also simplified a few "contains..." which did not actually require creating a new Collection, e.g. 
```
assertThat(response).containsAllIn(ImmutableList.of(defaultConceptSet));
```
becomes
```
assertThat(response).contains(defaultConceptSet);
```
and strengthened some assertions, from "contains all" or "contains at least" to "contains exactly"
---
* AoU UI
* …
> [risk=low][no ticket] bump google-truth and update method calls

- api/libproject/devstart.rb
The project.rb tool `update-user-disabled-status` is the only remaining user of `/v1/auth-domain/users` (nice catch @evrii) so let's migrate it to the newer endpoint `/v1/admin/users/updateAccount`.
Tested by running the command with a few configurations and observing the change on the Admin User page.
Example run:
```
./project.rb update-user-disabled-status \
--user joel14@fake-research-aou.org \
--admin_account joel@fake-research-aou.org \
--disabled false
```
---
* AoU UI
> [risk=no][no ticket] Update the disable-users project.rb tool to use the newer API

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
The root cause is that we used "user is the creator for any INACTIVE free tier workspaces" as a proxy for "user has previously exhausted free credits". While A implies B, the converse does not hold. Specifically, a user who has exhausted their credits may have 0 workspaces, or only have created BYO-billing workspaces (we observed this in RW-8328).
In these scenarios, the alert will fire every time `checkFreeTierBillingUsage` runs, as the check `expired && !previouslyExpired` is always true.
> [RW-8328][risk=no] Eliminate scenario where infinite free tier expiration emails are sent

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
- api/libproject/environments.rb
(Part 1 / x)
Add a new command `./project.rb publish-cdr-files` which generates a manifest of files to publish/copy. Initially, this tool takes a single slice through the eventual target capabilities, specifically:
- only targets CRAMs
- only generates the manifest, doesn't yet handle the copy
- eventually, I would like to upload logs / manifests to GCS for provenance
Currently outputs a CSV with the following headers:
```
source_path,ingest_path,dest_path,dest_storage_class
```
This is intended to be generic across file types, not just CRAMs.
Some of the requirements this is meeting:
- In the case of CRAMs (and some other file types), we want to rename individual files
- We need to publish the data via the ingest bucket, due to VPC-SC
- We need to specify a destination storage class
I …
> [RW-8266][risk=low] Add initial genomic file manifest publish tooling

- api/config/cdr_config_preprod.json
Promoting RT/CT preprod cdr.  Adding @yonghaoy as reviewer since he is the release engineer for the week of 5/16. Please be sure to run the publish commands below from the  /api directory in workbench before releasing to preprod:
RT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset R2021Q3R5 --tier registered --table-prefixes cb_,ds_
CT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2021Q3R6 --tier controlled --table-prefixes cb_,ds_
> [no ticket][risk=no] promoting RT/CT preprod cdr

- api/build.gradle
We can't upgrade to v6 yet because it requires Java 11.
Tested briefly by running a local server and updating my Profile.  Suggestions welcome for a more thorough test.
---
* AoU UI
> [risk=low][no ticket] Bump Hibernate to the latest 5.x version

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/pages/data/cohort-review/cohort-review.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/testing/stubs/cohort-review-service-stub.ts
Cleanup unused params and rename API call:
- Removing cdrVersionId from createCohortReview
- Removing cdrVersionId from getParticipantCohortStatuses and renaming to getParticipantCohortStatusesOld to allow for new API call for multiple reviews.
Updated UI and unit test as well.
---
* AoU UI
> [no ticket][risk=no] Cleanup unused params and rename API call

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
Adds the two remaining tasks:
- STAGE_INGEST
- PUBLISH
Implements these with a multithreaded worker pool approach.
Example output (simulated a dry run mode by adding `"echo"` in front of the manifests):
```
./project.rb publish-cdr-files --project all-of-us-rw-preprod --display-version-id v6 --wgs-rids-file rids.txt --tasks STAGE_INGEST,PUBLISH                                                                                                                                                                               
skipping non-numeric research ID line: research_id                                                                                                                                                                 
Writing logs to /tmp/cdr-file-publish20220516-753383-599xm3 …
```
> [RW-8266][risk=low] Add staging/publishing capabilities for genomic tools

- api/src/main/webapp/static/initialize_notebook_runtime.sh
Our featured workspaces recommend using the GATK image, which requires a larger disk than default. Set a 20GB disk to cover some common images at least (going higher will require modifications to this config file.)
> [risk=no] Add default boot disk size for Nextflow

- e2e/tests/nightly/ras-login.spec.ts
`ras-login.spec` UI test failed last night in this CircleCI [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/20390/workflows/548ae374-cd67-45ed-a36f-4d41d9a3b3ff/jobs/220059).
Reason: click `Login.gov` button didn't work.
Fix: Slow down test with one second sleep after new page opened.
> fix ras-login.spec

- ui/src/app/pages/access/data-access-requirements.tsx
Description: Updated Annual renewal header.
Updated Expired Version:
Unexpired version
---
* AoU UI
> [none][risk=no] Updated Annual Renewal Header.

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/SetAuthority.java
I added a playbook entry for this: 
https://docs.google.com/document/d/1hbYNWzdxuRybTfW3M70hWZfr_TXRVd5rOMR9kZtwAFY/edit#heading=h.x2qjziypitz3
This is important for removing all authorities when turning down an account. See example: https://precisionmedicineinitiative.atlassian.net/browse/PD-7476
> [risk=no] Add --authorities ALL for easier authority revocation

- api/db-cdr/generate-cdr/libproject/devstart.rb
2h -> 24h
The latest WGS CDR takes >2h to copy, which is why we saw some tables get dropped last time. I saw this issue again, but my validation caught it early.
> [RW-8053][risk=no] Increase TTL for CDR BigQuery publishing

- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/CohortReviewDao.java
- api/src/test/java/org/pmiops/workbench/db/dao/CohortReviewDaoTest.java
Change CohortReviewDao to return collection of reviews. The service layer will still return the first item on the collection, but this change is only to support the feature flag. This service method will be removed after go live of multiple cohort reviews.
---
* AoU UI
> [RW-8375][risk=no] Change CohortReviewDao to return collection of reviews

- api/db/changelog/db.changelog-196-add-demographic-survey-v2.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurveyV2.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/profile/DemographicSurveyMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Tested locally by manually setting DB fields and observing Profile responses.  Unit tests confirm that updateProfile() updates the survey.
Incorporates most of #6675 
---
* AoU UI
> [risk=low][RW-8353] Add DB tables and entity model for Demo Survey V2

- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/utils/runtime-utils.tsx
Due to a regression ~8 months ago, when a runtime hit the error state the preview and notebook redirect pages would simply continue as if the runtime were ready to go. This results in a bunch of spurious 500 errors, and a confusing UX. Note that when a user does hit this scenario, they will also get a pop-up modal. This screen is mostly background, and is what they will see upon closing the modal.
https://user-images.githubusercontent.com/822298/170149067-dcc6aff5-219d-497f-b069-19e2ca3309f1.mp4
> [RW-8327][risk=no] Handle the runtime error state on notebook pages

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
Description:
UpdateWorkspace is a patch command and we should allow access tier not set. 
In this case, there should no change for that field and we should skip this check 
---
* AoU UI
> [no ticket][risk=low] skip access tier check when not trying to update this workspace field

- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
This caused an issue on the filter set name being updated in some environments. Going forward, we should look at something like AutoValue to avoid these kinds of bugs.
> [risk=no] Update CDR version hash/equals

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
Dependent on applying https://github.com/all-of-us/workbench-terraform-modules/pull/36
Tested locally via `reporting/curl/upload-snapshot-local.sh`
See the third row below, where I reverted a CT bypass for one of my users locally:
> [RW-6566][risk=no] Add first enabled time for RT,CT

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressRemediationService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/EgressEventMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressRemediationServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/EgressEventMapperTest.java
- ui/src/app/pages/admin/admin-egress-audit.tsx
Tested the UI locally by inserting a fake egress_event row:
I have not tested the JIRA change.
---
* AoU UI
> [risk=low][RW-8426] report both ends of egress time window in JIRA and admin UI

- e2e/app/page/workspace-about-page.ts
- e2e/tests/notebook/notebook-writer-actions.spec.ts
- e2e/tests/notebook/notebook-writer-clone-workspace.spec.ts
We observed a case where somehow we shared to the writer as a reader. All subsequent test runs failed.
Allow the test to recover from this scenario.
> [RW-8409][risk=no] Make e2e user sharing more robust

- ui/src/app/pages/analysis/interactive-notebook.tsx
The bugfix in #6724 was too aggressive: we do want to show the Edit/Playground buttons when there is an error (like preview failed b/c too big) that can be recovered by using the Edit or Playground features.
Before
After
---
* AoU UI
> [risk=low][RW-8444] Fix regression: display Edit/Playground for non-runtime errors

- api/db/changelog/db.changelog-198-index-rdr-export-entities.xml
- api/db/changelog/db.changelog-master.xml
[This join](https://cs.github.com/all-of-us/workbench/blob/903d3f541c5ebc78b9d73b0542423f15ff1141aa/api/src/main/java/org/pmiops/workbench/db/dao/RdrExportDao.java?q=rdrexportdao#L22-L25) is very slow. The index seems to have the desired effect, testing on a local DB:
Before:
```
explain SELECT w.workspace_id FROM workspace w LEFT JOIN rdr_export rdr ON (w.workspace_id = rdr.entity_id AND rdr.entity_type = 2) WHERE w.last_modified_time > rdr.last_export_date OR rdr.entity_id IS NULL;        
+----+-------------+-------+------------+------+---------------+------+---------+------+--------+----------+----------------------------------------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows   | filtered | Extra …
```
> [RW-8258][risk=no] Add rdr_export index on entity

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
Description:
updated impl for getParticipantCohortStatuses api, tests
---
* AoU UI
> [RW-8369][risk=no] Multiple Cohort Review - add new implementation for getParticipantCohortStatuses

- e2e/tests/examples/sign-in.spec.ts
- e2e/utils/test-utils.ts
Description:
The new signout function will sign user out across all sessions. That makes we can not run test in parallel if using the same user. 
---
* AoU UI
> [RW-8465][risk=no] remove signout in e2e test

- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/conceptset/ConceptSetService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ConceptSetDao.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ConceptSetDaoTest.java
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/testing/stubs/concept-sets-api-stub.ts
Fix long load times for concept sets by removing the concept set hydrate method.
Details are here: https://precisionmedicineinitiative.atlassian.net/browse/RW-8420
---
* AoU UI
> [RW-8420][risk=no] fix long load times for concept sets

- api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java
Missed this in https://github.com/all-of-us/workbench/pull/6751 ; without it, we never pass backfill=true to the RDR.
> [RW-8446][risk=no] Add missing RDR backfill parameter on cloud task

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Also removes now unneeded config variables:
- extractionCohortsDataset
- extractionTempTablesDataset
- extractionFilterSetName
Follow-on PRs will remove the config variables entirely.
In local/test, this change should be a no-op. For completeness, I recreated the method snapshot with my merged commit @ https://github.com/broadinstitute/gatk/commit/f6fde4e9ebfce709bf6c9b22dafc7d94fb2433b0, rather than the previous snapshot which was built off my own branch (no subsequent modifications were made during PR review).
> [RW-8274][risk=low] Update GVS extract workflow in all environments

- ui/config-overrides.js
- ui/package.json
- ui/src/app/components/app-router.spec.tsx
- ui/src/app/components/ct-available-banner-maybe.spec.tsx
- ui/src/app/components/ct-available-banner-maybe.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/index.ts
- ui/src/setupTests.js
- ui/yarn.lock
Update react-scripts to v5.  Tested locally via Local->Test interactions.
Additional changes are required, because react-scripts v5 does not provide polyfills (see https://github.com/facebook/create-react-app/issues/11756 ).  I'm not familiar with the concept of polyfills so I'd appreciate a review from someone who can confirm that I'm not doing something terrible here.
Some test updates were also required, to prevent Jest from exiting with a non-specific error code.
Additionally, CSS-Minimizer and MutationObserver-shim were causing errors/warnings and were disabled.
This change should make a variety of other cleanup/upgrading possible, but I'd prefer to make this PR only as long as it needs to be.
#6170 was an older attempt at this.
---
* AoU UI
* [Perf …
> [risk=low][RW-7729] Upgrade react-scripts to 5.x

- api/config/cdr_config_preprod.json
I missed this in preprod CDR config review; this is the new June WGS dataset.
> [risk=no] Fix preprod WGS BigQuery dataset

- ui/package.json
- ui/yarn.lock
Oops: #6765 was overzealous.  We can't un-force nth-check just yet.
Local->Test functions normally.
Resolves https://github.com/all-of-us/workbench/security/dependabot/31
---
* AoU UI
> [risk=low][no ticket] Force nth-check to ^2.0.1

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
This generalizes the original approach by accepting a flexible input manifest, which defines a mapping between upstream data sources and the output CDR bucket.
See an example manifest here: https://github.com/all-of-us/workbench-devops/pull/99
Publish will be re-implemented in a follow-up PR to integrate with storage transfer service. See file comment for more details on the changes.
> [RW-8266][risk=low] Refactor CDR manifest creation / file staging

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
Add RDR Export of the Demo Survey V2 but DO NOT ENABLE because the RDR team isn't ready for it on Test yet.  We'll turn that on in #6778
---
* AoU UI
> [risk=low][RW-8355] Export Demo Survey V2 to RDR but disable via Feature Flag

- deploy/Dockerfile
Deploy to staging failed with error 
`error react-scripts@5.0.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.12"`
Likely a result of upgrade to react-scripts in #6753 which requires a newer version of node.
Dry run deploy to stable was successful:
```
deploy/project.rb deploy --project all-of-us-rw-stable --account deploy@all-of-us-rw-stable.iam.gserviceaccount.com --git-version origin/main --app-version will-temp --dry-run --no-promote --no-update-jira
```
FYI @calbach @jmthibault79
> [risk=no] Upgrade Node to v14 in Dockerfile for deploys

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
Fix for issue in Survey 'Select a value' attributes where the Save button will be disabled after entering any input into the form with no way to enable it.
---
* AoU UI
> [RW-8525][risk=no] Fix disabled add button for survey attributes

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
Description:
Updated bq calls to backup ds_ and cb_ tables. Using bq cp instead of creating schema and inserting data through query.
Also using parallelized calls to copy
Tested locally:
`./project.rb build-backup-cb-ds-tables --bq-project all-of-us-ehr-dev --bq-dataset test_R2019q4r3 --output-project all-of-us-ehr-dev --output-dataset `test_chenchals`
---
* AoU UI
> [RW-8216]risk=no] updated calls to backup ds_ and cb_ tables.

- api/db/changelog/db.changelog-200-demographic-survey-v2-tweaks.xml
- api/db/changelog/db.changelog-master.xml
Adds missing data to database schema to support remaining demographic survey questions.
Ran schema migration against local db and checked columns. Ran alter table statements manually against dev, checked columns, then reverted.
---
* AoU UI
> [RW-8539][risk=no] AIAN as subcategory and survey comments in db

- api/db/changelog/db.changelog-201-demographic-survey-v2-aian.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurveyV2.java
- api/src/main/resources/rdr.yaml
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/demographic-survey-v2.tsx
Ran migration locally.
Started API server.
---
* AoU UI
> [RW-8556][risk-low] Separate AI and AN from AI/AN

- ui/config-overrides.js
Good morning.  I'm playing around with the PRs which were merged while I was out.  #6807 works great and I think it will reduce errors related to choosing the wrong type of local UI.  What do you think of this small update to it?
Also fixed an unrelated wrong indentation.
---
* AoU UI
> [risk=low][no ticket] Expand environmentFilePath inline and add spacing

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
Description:
- updated cdrDbName to point to new version
- doing a publish to test/staging/stable/perf environments
```
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-workbench-test --bq-dataset test_R2019q4r3 --tier controlled --table-prefixes ds_
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-staging --bq-dataset test_R2019q4r3 --tier controlled --table-prefixes ds_
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-stable --bq-dataset test_R2019q4r3 --tier controlled --table-prefixes ds_
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-perf --bq-dataset test_R2019q4r3 --tier controlled --table-prefixes ds_
```
---
* AoU UI
* [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/sca …
> [no ticket][risk=no] Bumping cdr version in test/staging/stable/perf

- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-list.tsx
Add check for max concept selection limit when editing an existing concept set
@chenchals FYI
---
* AoU UI
> [RW-8562][risk=no] Check max concept count when editing concept set

- ui/src/app/components/with-routing-spinner.tsx
- ui/src/app/pages/demographic-survey.tsx
- ui/src/app/pages/login/sign-in.tsx
**Description**:
Modified routing spinner overlay to stay centered in the screen.
Looked over spinners throughout the application. Details can be found in this [gist](https://gist.github.com/evrii/1237f8288add9f453dc5a44d7e4235a7).
I verified the overlay's behavior on the components that either make use of both hideSpinner and showSpinner as well as components where I saw the spinner overlay while using the application.
* AoU UI
> [risk=none][RW-8569] Modified routing spinner overlay to stay centered in the screen.

- api/db/local-vars.env
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench-api.yaml
- e2ev2/README.md
- e2ev2/src/test-utils.js
Does not modify data, so request should be a GET when feasible.
https://precisionmedicineinitiative.atlassian.net/browse/RW-6988
Existing:
```
curl -H "Authorization: Bearer $DMFBT" 'localhost:8081/v2/workspaces/aou-rw-test-53ff4756/mohstest/resources?resourceTypesToFetch=COHORT'
[]
```
New:
```
% curl -H "Authorization: Bearer $DMFBT" 'localhost:8081/v2/workspaces/aou-rw-test-53ff4756/mohstest/resources?resourceTypesToFetch=COHORT,DATASET'
[]
```
---
* AoU UI
> [RW-6988][risk=low] POST -> GET

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Since Data Browser does not have device data, we will now use plain text instead of a link for the Device domain in the concept id column in cohort builder and concept search. 
Device results:
Non-device results:
---
* AoU UI
> [RW-8217][risk=no] Remove link to Data Browser from device concept ids

- ui/src/app/cohort-search/tree-node/tree-node.component.spec.tsx
- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/testing/stubs/cohort-builder-service-stub.ts
Use `findVersionedSurveys` call to get versioned surveys instead of checking hardcoded values.
---
* AoU UI
> [RW-8214][risk=no] Use api call to get versioned surveys in CB tree

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
- api/libproject/affirm.rb
- api/libproject/devstart.rb
Significant changes:
- Support CDR output manifests for use with [genomic data versioning](https://docs.google.com/document/d/1-ayWRzbz654JiE90x9aMFOqoq4oMnhmIXwlaYbDZkVg/edit)
- File staging layout change: I realized that Cloud Transfer Service can only do path prefixes (includes / excludes), and my interleaved Nearline CRAMs with standard CRAM indexes would therefore be impossible to transfer. My workaround is to add a path prefix within the ingest bucket for any files destined for non-standard storage.
Also:
- a handful of fixes around file staging..
- factor out the "get_user_confirmation" method and fix some of its papercuts
> [RW-8266][risk=low] Implement CDR file publishing via Cloud Storage Transfer Service

- e2e/.env.circleci.local
- e2e/.env.circleci.test
- e2ev2/README.md
- e2ev2/src/config.js
puppeteer-tester-6 appears to have hit the maximum groups issue. This may be partially due to orphaned workspaces generated via https://precisionmedicineinitiative.atlassian.net/browse/RW-8585 , but this likely does not account for the full story. Further investigation on why we hit the limit here is likely warranted.
See also https://docs.google.com/document/d/1XVeAdtTG3Bb-OxKPOShVl6Cwd9PtO7jfnDNncroyhEQ/edit#
I just created this user.
> [risk=no] Bump to new puppeteer test user

- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
I'm double-checking with the GVS team that this should be OK... See https://precisionmedicineinitiative.atlassian.net/browse/RW-8611
> [RW-8611][risk=low] Delete intermediate output files from GVS extractions

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentResourceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserRecentlyModifiedResourceDao.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceTest.java
We were already dual-writing the old and new versions of user-recent-resources/user_recently_modified_resource but in a few cases we were still reading from the old version.
Also remove a few references to old versions and do some general cleanup.
DOES NOT complete RW-8309
---
* AoU UI
> [risk=low][RW-8309] User Recent Resources: clean up and only read from new version

- ui/src/app/components/demographic-survey-v2.tsx
Description:
Updated parent option logic to clear child other text field.
https://user-images.githubusercontent.com/24514630/179573033-4c1dd9a5-a3cd-48d8-b3f9-aea741f154e1.mov
---
* AoU UI
> [RW-8647][risk=no] Updated parent option logic to clear child other text field

- ui/src/app/utils/machines.ts
Description:
Background discussion: https://pmi-engteam.slack.com/archives/CHRN2R51N/p1658164436741819
We added a total cost check including disk size, gpu, dataproc worker. The 1.6 seems to be an legacy one and we can remove.
---
* AoU UI
> [RW-8614][risk=low] Remove 1.6/hr check to support more machine types

- .circleci/config.yml
- e2ev2/src/circle-run-tests.sh
- e2ev2/src/failure-reporter.js
- e2ev2/tests/flaky.test.js
No ticket. Changes in test code only.
The objective here is to minimize the time necessary to determine if a test failure is due to a behavior change vs. infrastructure reliability.
This change saves a list of failed tests so Circle's "Re-Run from Failed" button will only run those tests that have previously failed. The file is keyed on the git hash, so any code changes will run all tests.
> [no-ticket][risk=no] Run only failed tests when re-running from failed

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-overview.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/participants-charts.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
Allow API endpoints to use any version of cohort to render charts
---
* AoU UI
> [no ticket][risk=no] Allow API endpoints to use any version of cohort to render charts

- e2e/tests/cohorts/cohort-review.spec.ts
Second attempt at a fix for `cohort-review.spec.ts` for staging after the latest run failed again. Mixed up the review card names on the first commit (#6862).
> [risk=no] Fix cohort review e2e test staging

- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/components/breadcrumb.spec.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/pages/data/cohort-review/annotation-definition-modals.component.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-participants-table.tsx
- ui/src/app/pages/data/cohort-review/cohort-review.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
- ui/src/app/pages/data/cohort-review/detail-tabs.component.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/pages/data/cohort-review/table-page.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/cohort/cohort-resource-card.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/resources.spec.tsx
- ui/src/app/utils/resources.tsx
- ui/src/app/utils/stores.tsx
Currently, when clicking a cohort review resource card, it navigates to the old cohort review route.
This pr adds a route for the new interface that takes the cohort review id (`crid`) as a url param, and will select that review in the list after navigating to the cohort review page.
---
* AoU UI
> [RW-8630][risk=no] Navigate to new UI when clicking cohort review resource card

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/db/dao/DataSetDao.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceTest.java
https://user-images.githubusercontent.com/34481816/154352153-fa6adee7-2469-4f48-b0ca-c69ad1e99b41.mov
---
> [risk=low][RW-7613] Delete dependent resources from user_recently_modified_resource if COHORT/CONCEPT Set is deleted

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/test/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceTest.java
This flag was mostly removed in #6335 
Remove all code depending on that FF and set to true in all environments
---
* AoU UI
> [risk=low][RW-7809] Set enableDSCREntryInRecentModified to always true

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/cohort-criteria-menu.tsx
Fix attributes call for survey nodes with attributes in universal search results.
Before:
https://user-images.githubusercontent.com/40036095/181058613-4b932596-6253-4bd6-bc35-acf8a339d25a.mov
After:
https://user-images.githubusercontent.com/40036095/181058674-04d2e82c-183f-41c8-90d3-b3dd05d246e6.mov
Also added a spinner to the universal search menu when menu items are still loading:
https://user-images.githubusercontent.com/40036095/181058826-9028b012-bbc7-4f88-a0db-ba3aa5c70ef4.mov
---
* AoU UI
* SumoLogic - for …
> [RW-8675][risk=no] Fix survey attributes for universal search results

- api/config/config_perf.json
- api/config/config_staging.json
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
These environments don't have corresponding RDR endpoints, and this is causing log confusion on both sides.
Tested loocally by temporarily removing the RDR export config from `config_local.json`
---
* AoU UI
> [risk=low][no ticket] don't export to RDR in Perf or Staging

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImplTest.java
Description: Allow for queries with multiple ends with terms. This PR utilizes a custom dao implementation to all us to build a sql statement dynamically depending on how many ends with search terms are present in the parameter list.
---
* AoU UI
> [no ticket][risk=no] allow for queries with multiple ends with terms

- api/db/changelog/db.changelog-202-drop-user-recent-resource.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceImpl.java
A release has passed since we removed the last references to this table (#6857), so it's safe to delete now.
---
* AoU UI
> [risk=low][RW-8651] Drop table user_recent_resources

- e2ev2/src/circle-run-tests.sh
- e2ev2/src/config.js
- e2ev2/src/test-utils.js
- e2ev2/tests/login.test.js
- e2ev2/tests/sanity.browser.test.js
- e2ev2/tests/workspace-create.test.js
No ticket: no application code changes.
Waiting for the `networkidle0` event causes `page.goto` to fail when the page doesn't load. This is much clearer than having the timeout occur on a selector.
> [no-ticket][risk=no] Wait for page load event

- api/tools/src/main/java/org/pmiops/workbench/tools/cdrconfig/UpdateCdrConfig.java
- api/tools/src/test/resources/cdrconfig/README.md
- api/tools/src/test/resources/cdrconfig/cdr_wgsBigqueryDataset_not_defined.json
- api/tools/src/test/resources/cdrconfig/cdr_wgsFilterSetName_not_defined.json
Add a validation to ensure that both wgsBigqueryDataset and wgsFilterSetName are specified together if any one of them exists.
Description:
---
* AoU UI
> [RW-8487][risk=no] Verify-genomic-properties-are-specified

- api/config/cdr_config_preprod.json
We had to rebuild the cloud sql search indexes for RT and CT CDR. @evrii I'm tagging you as the reviewer since you are the release eng next week. You will need to run publish commands for both RT and CT in preprod. Commands are below(they should be run from the api directory). We also have entries in the release playbook that explain this as well.
RT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset R2022Q2R2 --tier registered --table-prefixes cb_
CT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes cb_
> [no ticket][risk=no] bumping cloud cdr

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
We do not refer to it anywhere after #6858 and a release has passed since it has merged.  Safe to remove the endpoint now.
Tested locally - I am able to access workspace resources as expected.
---
* AoU UI
> [risk=low][RW-6988][RW-8627] rm deprecated getWorkspaceResources()

- api/db-cdr/generate-cdr/build-cb-criteria-missing-codes.sh
Fixing a bug that exists when building drug concept non-hierarchies. The counts are not generated properly because the ancestors for the non-hierarchy drugs are never inserted into the cb_criteria_ancestor table.
> [RW-8678][risk=no] fixing drug concepts that don't belong to a hierarchy

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
Description:
- Added endsWith term capability to full_text search for *findCriteriaAutoComplete* call
---
* AoU UI
> [RW-8670][risk=no] Full Text Search - Add endsWith to findCriteriaAutoComplete call 

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Now that a released has passed since the last reference to the Feature Flag enableDSCREntryInRecentModified was removed, we can now remove the flag.
---
* AoU UI
> [risk=no][RW-7809] rm ff enableDSCREntryInRecentModified

- api/src/main/java/org/pmiops/workbench/google/CloudStorageClient.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/google/CloudStorageClientTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
Description:
Moved blobToFileDetail from interface to service. Updated tests accordingly.
---
* AoU UI
> [no-ticket][risk=no] Move blobToFileDetail from interface to service

- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/google/CloudStorageClientTest.java
No actual changes.  Fixes the linting in #6912
---
* AoU UI
> [risk=no][no ticket] Fix linting to fix texts

- api/db-cdr/generate-cdr/build-cb-criteria-missing-codes.sh
fixing drug index - the script should load all drugs of the following types into the cb_criteria_ancestor table:
1. CVX
2. HCPCS
3. RxNorm Extension
> [no ticket][risk=no] fixing drug index

- ui/src/app/cohort-search/cohort-criteria-menu.spec.tsx
- ui/src/app/cohort-search/cohort-criteria-menu.tsx
- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.tsx
- ui/src/app/cohort-search/list-search/list-search.component.spec.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/search-bar/search-bar.component.spec.tsx
- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
Adding tooltip to the following UI components:
1. list-search.component.tsx 
2. cohort-criteria-menu.tsx 
3. search-bar.component.tsx 
4. concept-homepage.tsx
> [RW-8618][risk=no] Adding tooltip for new search operators

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImplTest.java
Description:
- Implemented full text search ends with for concept search
---
* AoU UI
> [RW-8669][risk=no] Add Fulltext endsWith search for ConceptSets

- api/config/cdr_config_preprod.json
Promoting index build in preprod. @chenchals Please be sure the publish the RT/CT BQ datasets in preprod with the release next week:
RT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset R2022Q2R2 --tier registered --table-prefixes cb_
CT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes cb_
> [no ticket][risk=no] promoting index build in preprod

- api/db/changelog/db.changelog-203-delete-old-billing-migration-workspaces.xml
- api/db/changelog/db.changelog-master.xml
The presence of workspaces with the combination of (OLD BillingMigrationStatus, ACTIVE ActiveStatus) is complicating the logic of FreeTierBillingCron (see #6882, #6911, and #6922).
We had believed the migration of all ACTIVE workspaces to the NEW BillingMigrationStatus to be complete years ago, but we apparently missed a few: 31 in Test, none elsewhere.  None of these workspaces seem to be of value and they violate the assumption of 1PPW that we have relied on for a long time now.  Let's delete them.
---
* AoU UI
* …
> [risk=low][RW-8705] Set OLD/MIGRATED workspaces to DELETED

- api/db/changelog/db.changelog-204-demographic-survey-fk-constraint.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
**Problem**:   We were not able to update user profile
**Why**: This happened because when the DbUser object was being saved, it was trying to update the already existing  DbDemographicSurveyV2 as well, which caused issues: 
_'detached entity passed to persist: org.pmiops.workbench.db.model.DbDemographicSurveyV2 '
**Solution** :
The DbUser was using CASCADE.persist to save the linked DbDemographicSurveyV2. However since the object already exist in DB, it was failing, using CASCADE.MERGE solved it as it automatically merged the DbDemographicSurveyV2 object.
(ref: https://stackoverflow.com/questions/13370221/persistentobjectexception-detached-entity-passed-to-persist-thrown-by-jpa-and-h)
- Using CASCADE.MERGE , however started showing  the following error:
_'Cannot delete …
> [RW-8722][risk=high]  Cannot disable users who have taken the updated demographic survey

- ui/src/app/cohort-search/overview/overview.component.tsx
Limit size of cohorts to 1MB. If the limit is exceeded, we disable the save button and show an error icon with a tooltip
---
* AoU UI
> [RW-8558][risk=no] Limit size of cohort definition 

- ui/src/app/pages/signed-in/signed-in.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
… and prod
We have a lot of test failures just because all the users are being redirected to demographic survey page. As per a conversation with Moira, i have disabled the redirect on all environments except PRe prod and prod for now
---
* AoU UI
> [RW-8758][risk=low]  Puppeteer test failing due to Researcher Demographic Survey

- ui/src/app/cohort-search/cohort-criteria-menu.tsx
Prevents the submenu from rendering when there are search results for that item:
https://user-images.githubusercontent.com/40036095/186523673-38d34a3e-107d-4d2a-9932-05272893eb16.mov
---
* AoU UI
> [RW-8766][risk=no] Disable submenu for universal search results

- e2e/tests/datasets/dataset-export-py-notebook.spec.ts
- e2e/tests/datasets/dataset-export-r-notebook.spec.ts
- e2e/tests/notebook/notebook-create-python.spec.ts
- e2e/tests/notebook/notebook-create-r.spec.ts
- e2e/tests/notebook/notebook-reader-actions.spec.ts
- e2e/tests/notebook/notebook-upload-file.spec.ts
- e2e/tests/notebook/notebook-writer-actions.spec.ts
- e2e/tests/notebook/notebook-writer-clone-workspace.spec.ts
- e2e/tests/ui/notebook-ui.spec.ts
- ui/package.json
- ui/src/app/pages/analysis/notebook-list.spec.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/utils/resource-list.tsx
- ui/yarn.lock
https://user-images.githubusercontent.com/34481816/186704401-e6287230-ec32-4b1e-ae24-18dc1fb0892c.mov
With no notebooks
Description:
---
* AoU UI
> [RW-8692][risk=no]   Update 'Analysis' tab to use tables, not cards

- e2e/app/page/workspace-analysis-page.ts
- e2e/app/text-labels.ts
Tested locally by running `yarn test-nightly tests/nightly/admin/lock-workspace.spec.ts` with an `.env` file configured for the Test environment
---
* AoU UI
> [risk=no][RW-8788] Fix nightly tests broken due to create-new-notebook xpath change

- e2e/app/component/bypass-modules.ts
- e2e/app/page/data-access/module.ts
- e2e/app/sidebar/genomic-extractions-sidebar.ts
Tested locally by running `yarn test-nightly tests/nightly/admin/user-admin-table.spec.ts` with an `.env` file configured for the Test environment
---
* AoU UI
> [risk=no][RW-8701] fix nightly tests broken due to FontAwesome change

- e2e/tests/nightly/ras-login.spec.ts
Tested by running `yarn test-nightly tests/nightly/ras-login.spec.ts`
This DOES NOT cause the RAS test to pass, but it advances beyond one set of errors.
I'm investigating the other failure as well, which has a different cause.
---
* AoU UI
> [risk=no][RW-8816] Update nightly test due to changes in the RAS website

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/search-bar/search-bar.component.spec.tsx
- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
Adding new API call survey autocomplete. This will allow for searching concepts in all surveys as well as an individual survey. 
---
* AoU UI
> [RW-8752][risk=no] Adding new API call survey autocomplete

- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
These tests are failing since the notebook format has changed from cards to table. We will be re-writting the test in e2e version 2, so skipping it for now (Jira ticket tracking the effort: https://precisionmedicineinitiative.atlassian.net/browse/RW-8763)
---
* AoU UI
> [RW-8692][risk=no] Skip test as notebook format as changed

- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
Fixes `Uncaught Error: Required parameter surveyName was null or undefined when calling findSurveyAutoComplete` error.
> [RW-8851][risk=no] Fix survey autocomplete call

- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
Lint for e2e was broken because of which no test could run.
Description:
---
* AoU UI
> Fix puppeteer lint

- ui/src/app/pages/analysis/runtime-panel.tsx
Description:
This PR adds a tooltip to the preemptible workers setting. It also updates the text “Preemptible” to “Preemptible workers.”
Before
After
---
* AoU UI
> [RW-8244][risk=no] Add tooltip to the preemptible workers setting

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
Description:
I notice rdr export cron job fails in few envs: 
---
* AoU UI
> [no ticket][risk=low]:  Fix NPE when exportDemoSurveyV2 config is not set in certain envs

- e2e/app/page/cohort-participants-group.ts
Change expected api call from `GET` to `POST`
FYI @dmohs @chavanr2019
> [risk=no] Fix failing cohort e2e tests

- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
> [RW-8810][risk=no] Pick minimum disk size when creating dataproc runtime in e2e test. 

- ui/src/app/cohort-search/tree/tree.component.tsx
Include the top level survey node after selecting a survey from the criteria submenu
https://user-images.githubusercontent.com/40036095/189800741-9486e23e-5b0a-4431-8391-31b64ba2462e.mov
---
* AoU UI
> [RW-8836][risk=no] Show root node for survey submenu selections

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchTerm.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/SearchTermTest.java
Fine tuning full text search:
1. When using universal search for term `-12-55`, it's returning results for surveys and it should not be.
2. When using universal search for term '*ing -upper', it's only returning survey data. we should have matching data for conditions, procedures, observations and measurements.
3. When searching codes with '-12', it returns results that match which is the opposite of the minus operator(should remove terms).
> [RW-8877][risk=no] fine tuning full text search

- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/utils/index.tsx
Fix issue where full text tooltip is hidden behind the autocomplete dropdown.
Before:
After:
---
* AoU UI
> [RW-8880][risk=no] Fix hidden tooltip in CB autocomplete

- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- Fix issue on Cohort Description page where we were using the current cohort definition instead of the cohort snapshot
- Add text so the user knows data from the snapshot is being displayed
---
* AoU UI
> [RW-8884][risk=no] Use correct definition for cohort snapshots

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Description: This PR saves the demographic survey version 2 in Database when a new account is created. Along with that this PR uses a consistent definition to save demographic survey v2 object with the user object. The CASCADEType for demographicsurveyv2 was updated to type merge only because on updating  a profile of user who has submitted new version of demographic survey, was failing with the following error:
_org.hibernate.PersistentObjectException: detached entity passed to persist: org.pmiops.workbench.db.model.DbDemographicSurveyV2_
This is because the Save method accepts only transient objects. 
Definition of trainsient object: https://docs.jboss.org/hibernate/core/3.3/reference/en/html/objectstate.html
an object is transient if it has just been instantiated using the new …
> [RW-8811][risk=no]   [P2] Demo Survey V2 is not recorded during account creation

- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
Fixes 2 issues that can occur when deleting a cohort review:
- Deleting the currently selected review results in an error that causes an infinite spinner
- After deleting the last review in the list, the charts in the overview section still show with the deleted review' data
https://user-images.githubusercontent.com/40036095/191336809-56848b70-907f-4c03-b67f-f9ce141e2991.mov
---
* AoU UI
> [RW-8891][RW-8892][risk=no] Fix issues when deleting selected or last cohort review

- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Update the age range selection to get a non-zero count.
Before (20-21 age range)
After (21-22 age range)
---
* AoU UI
> [DT-52][risk=no] Fix cohort selections for nightly genomics test

- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
Description:
We use different log locations for GCE and dataproc.
1. GCE: WorkspaceRuntimeLogs.cos_containers
2. Dataproc: WorkspaceRuntimeLogs.jupyter
This PR dynamically set the file location based on whether it is dataproc or GCE
---
* AoU UI
> [RW-8479] [risk=low] Use different dataset for dataproc and gce

- e2e/.env.sample
- e2e/app/page/create-account-page.ts
- e2e/resources/data/user-registration-data.ts
Description:
Fixes a broken nightly test. We had updated the address' country field
from open text input to a Select and did not update this test.
---
* AoU UI
> [RW-8936][risk=no] Fix broken test using the country dropdown

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
Update BigQuery SQL that produces random participants for cohort review. The death table happens to have duplicate rows. This is not expected, so we will full proof the code by doing a group by to remove the duplicates. This code change will fix the problem in both RT and CT CDRs.
> DT-64 fix sql to remove duplicate entries

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
Add missing aliases to `DbCriteria` queries in `CBCriteriaDao`
---
* AoU UI
> [DT-46][risk=no] Clean up CBCriteriaDao queries

- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/zendesk.ts
When a CT workspace is "new" (here, 10 minutes old or less) display a notification with support links.  The user may dismiss this notification by clicking X
---
* AoU UI
> [risk=low][RW-8473] Show support links in new CT workspaces

- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
Description:
` Dataset all-of-us-rw-prod:fc-aou-logs-prodWorkspaceRuntimeLogs was not found in location US`
I am missing dot, it should be `fc-aou-logs-prod.WorkspaceRuntimeLogs`
---
* AoU UI
> [no ticket][risk=low] Fix Runtime audit log path, add missing '.'

- ui/src/app/pages/admin/user/admin-user-table.tsx
- ui/src/app/utils/dates.tsx
Was sorting by the output text string, which was month-first:
Now sorts correctly by using the epoch date instead of text
---
* AoU UI
> [risk=low][no ticket] Sort first-sign-in correctly in UserAdminTable

- api/db-cdr/generate-cdr/build-cb-criteria-missing-codes.sh
- api/db-cdr/generate-cdr/build-search-all-events.sh
Some cleanup of CDR indices build with new CDR version
1. Removing all source drug concepts from BQ all events table. They are never searchable in the system.
2. Adding update for Measurement and Observation data that has fallen out of the CPT4 hierarchy
3. Removing CPT4, ICD9Proc, ICD10PCS standard Procedure data from BQ all events table. CPT4, ICD9Proc, ICD10PCS are only searchable in source Procedure
4. Removing CPT4 standard Measurement and Observation data from BQ all events table. CPT4 is only search from source Measurements/Observations
> [DT-97][risk=no] Some cleanup of CDR indices build with new CDR version

- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
Remove hardcoded condition causing wrong type of attribute sent for survey with `conceptId` of 1585747
Before:
After:
---
* AoU UI
> [DT-73][risk=no] Fix attributes for survey concept

- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
Description:
SELECT timestamp, jsonPayload.message AS message should be select from {textplayload if dataproc}
Verified locally
---
* AoU UI
> [no ticket][risk=no] Fix dataproc column name

- ui/src/app/components/headers.tsx
- ui/src/app/components/public-layout.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/app/routing/app-routing.tsx
I had some confusion about a "disabled" user which should not have been.  It took a long time to realize that the problem was that I was on Local->Test instead of Local->Local.  The Disabled User and Sign-In screens did not supply this information.  Now, all aou-logo screens inform the user which environment they're in (except when on Prod, matching existing behavior)
Signed-in screens: no change
Cookies Disabled screen: could not test
Sign-In
Before
After
User Disabled screen
Before
After
---
* AoU UI
* SumoLogic - for …
> [risk=no][no ticket] Centralize references to the AoU logo and include the env tag

- ui/src/app/components/create-modal.tsx
- ui/src/app/components/rename-modal.tsx
- ui/src/app/pages/data/cohort-review/create-cohort-review-modal.tsx
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-search.tsx
- Trim whitespace from new names before validating to prevent duplicate names for resources
Before:
After:
- Add missing name validation to concept set edit page
---
* AoU UI
> [DT-65][risk=no] Fix validation when renaming resources

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
Description:
---
- Consolidated API calls that have many arguments. Merged the 2-calls below
- `CohortBuilderController.findCriteriaAutoComplete`
- `CohortBuilderController.findSurveyAutoComplete`
- Updated Swagger definition
- Updated API calls, 
- Updated UI calls 
- Updated API tests
- there were no explicit UI tests for these calls(?)
- Deployed app to local and verified autocomplete is working as expected
---
* AoU UI
> [DT-10][risk=no] Consolidate API calls that have many arguments

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
Description:
Updates API to add Login.gov access to reporting output.
Dependent on applying https://github.com/all-of-us/workbench-devops/pull/104.
I tested this in the "local" terraform environment using the process outlined in https://github.com/all-of-us/workbench/wiki/Workbench-Reporting-Dataset-(WRD)#testing.
From the checklist below:
> If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
Are there any consumers besides the BQ table I need to update for this change?
> If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests …
> [RW-8681][risk=no] API changes to add Login.gov access to reporting output

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
Description:
1. APP -> APPS
2. /workspaces/{workspaceNamespace}/apps because of [nest collections](https://restfulapi.net/resource-naming/#:~:text=1.2.%20Collection%20and%20Sub%2Dcollection%20Resources).
3. Create and List are moved to  /workspaces/{workspaceNamespace}/apps
4. GET DELETE and UPDATE in /workspaces/{workspaceNamespace}/apps/{appName}
---
* AoU UI
> [RW-8941][risk=low]: Reworks APPs api to follow rest best practice

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- ui/src/app/pages/data/cohort-review/cohort-review-participants-table.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/services/review-state.service.ts
Description:
---
- Code Cleanup - remove cohortReviewId from API call - it's not used
- Updated API and UI
---
* AoU UI
> [DT-9][risk: no] Removed cohortReviewId from API and UI calls and updated test

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_all_events.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Description:
---
- Added CATI flag to API. 
- Added appropriate BQ tests
- Deployed API/UI locally and checked
---
* AoU UI
> [DT-80][risk:no]Add is_cati flag for querying and updated BQ tests.

- ui/src/app/pages/workspace/workspace-about.tsx
Description:
After click:
---
* AoU UI
> [RW-9067] [risk=no] Add url for user to view GCS bucket in GCP console

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
Description:
I am working on a Terra side change to modify GET/LIST interface a bit. 
https://github.com/DataBiosphere/leonardo/pull/2911
This API may not work until that PR deployed
This PR also update CreateAppRequest, Leonardo interface, use new RStudio descriptor path
---
* AoU UI
> [RW-8941][RW-8925][risk=no]: Implement GET and LIST app endpoints

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
Description:
Implements the endpoint for deleting Leo apps.
This was verified locally by manually sending `curl` requests.
---
* AoU UI
> [RW-8942][risk=no] Implement delete app endpoint

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Currently workbench allows spaces to be added to the start and end of workspace name string. This causes issues not only with sorting the workspace name but also storing unnecessary extra characters.
The reason why we added the trim functionality on blur and not onChange is because we want to let the user add a space in between two text eg: 'This is my workspace' is a valid workspace name. adding trim to onChange would have prevented user to add space after `This` forcing user to name it like `Thisismyworkspace`
---
* AoU UI …
> [risk=no][noTicket]Trim workspace Name on creation/updating workspace

- ui/src/app/components/resource-list.spec.tsx
- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/analysis/notebook-list.spec.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/data/data-component.tsx
- ui/src/app/pages/data/data-page.spec.tsx
- ui/src/app/pages/homepage/recent-resources.spec.tsx
- ui/src/app/pages/homepage/recent-resources.tsx
- ui/src/app/utils/resource-list.tsx
- ui/src/testing/stubs/user-metrics-api-stub.ts
When a user has an entry in their recent-resources list but they don't have access to the resource's workspace, the current behavior is a blank screen!  Fix this by skipping such entries.
One way this might happen is if the workspace's owner unshares it with them.
We may also want to delete recent-resources on unshare, but this UI change will handle the general case of "can't see workspace" which could conceivably have other causes.
Also add some UI unit tests related to resources.
---
* AoU UI
* SumoLogic …
> [risk=low][RW-9077] Don't render recent-resources when workspaces are unavailable

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
> [RW-9114][risk=no] Don't update RDR DB table when export fails in the middle

- api/db-cdr/generate-cdr/build-cb-search-person.sh
Description:
---
- Updated `build-cb-search-person.sh` to use the use the new tables `fitbit sleep_daily_summary` and `sleep_level` for flagging `has_fitbit` column
---
* AoU UI
> [DT-116][risk:no] Updated cb_search person has_fitbit to also use fitbit sleep_daily_summary and sleep_level tables

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
Hide all content for `Personal Medical History`, `Family History` and `Personal and Family Health History` surveys until the tools have been updated to handle the new cdr.
---
* AoU UI
> [DT-127][risk=no] Temporarily filter survey conduct content

- api/libproject/devstart.rb
If the database had not started (as is often the case for me after I've restarted the dev server), the connect-to-db script fails first invocation.
This commit uses the helper method that both starts the db and waits for it to be ready for connections before connecting.
> Fix: connect-to-db waits for the db to be ready

- api/config/cdr_config_local.json
Description:
- updated fitbit sleep and survey conduct flag for `cdr_config_local.json`
- updated `ds_linking.csv` in [all-of-us-cb-test-csv](https://console.cloud.google.com/storage/browser/all-of-us-cb-test-csv) for fitbit sleep  tables
- ran local data migrations and testing  with API/UI deployment
**fitbit_sleep_daily_summary:**
**fitbit_sleep_level:**
---
* AoU UI
> [No-Ticket][risk:no] updated fitbit Sleep and survey conduct flags for RT and CT

- api/src/main/java/org/pmiops/workbench/api/DisksController.java
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
Description:
Saw a test failure: https://output.circle-artifacts.com/output/job/b17bec21-5dcc-4114-ad3e-5e7d436169bc/artifacts/2/JunitTestResult/tests/test/classes/org.pmiops.workbench.api.DisksControllerTest.html
That might be caused by compare with ISO 8601 format directly. 
I guess the cause is when the generated timestamp happens to not having  mills. 
`2022-11-07T17:16:27Z` vs `2022-11-07T17:16:27.100Z`. 
Try to use instant see if that can fix this issue
---
* AoU UI
> [no ticket][risk=no] Compare instant instead of datatime string

- deploy/libproject/deploy.rb
Description:
Added more descriptive error messaging for argument null checks in deploy script.
In order to test, run a dry run release: deploy/project.rb deploy --dry-run
Check for intuitive error messages when:
1.  --project value is not included
2.  --account value is not included
3. --promote or --no-promote is not included
---
* AoU UI
> [risk=no][no ticket] upgrade a few API packages Added more descriptive error messaging for null argument checks.

- api/config/config_local.json
- api/config/config_test.json
> [RW-9116][risk=low] Update jupyter version to 2.1.12 to upgrade hail

- ui/src/app/pages/analysis/new-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/analysis/util.ts
Minor UI cleanup.
Tested by creating a new notebook, renaming it using the snowman menu, executing cells in the notebook, using the Jupyter file manager, and observing that the homepage and the Analysis page show new and old notebooks correctly.
---
* AoU UI
> [risk=no][no ticket] use drop/appendNotebookFileSuffix where appropriate

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/NewUserSatisfactionSurveyColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/SurveysControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/NewUserSatisfactionSurveyMapperTest.java
Description:
Uploads data from the `new_user_satisfaction_survey` DB table to the `new_user_satisfaction_survey` BQ table added in [this PR](https://github.com/all-of-us/workbench-terraform-modules/pull/41).
Tested by running the `upload-snapshot-local.sh` script and verifying the data is in the local env table.
---
* AoU UI
> [RW-9030][risk=low] Upload new user survey table data to the WRD

- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebookUtils.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
- ui/src/app/pages/analysis/notebook-resource-card.tsx
Description:
- List RMD files is supported by checking rmd pattern macher
- Clone/Delete/Copy/Rename are supported without anychanges. 
- Get kernel type is not supported for rmd file
- Convert RMD file to HTLM is to be implemented. 
- Note, I can not test it because I can not create rmd files in gcs bucket and open with RStudio yet.  
---
* AoU UI
> [RW-9101][RW-9104][RW-9103][risk=no]: Support list/clone/rename/delete/copy rmd files

- api/src/main/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyServiceImpl.java
- api/src/test/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyServiceTest.java
Description:
Use account creation time instead of RT access time for new user survey eligibility.
For reviewer: Should this use the user's `first_sign_in_time` instead? What state is a `user` in if they don't have a `first_sign_in_time`?
I did not test this locally as I think unit tests suffice. Let me know if that isn't the case.
---
* AoU UI
> [RW-9194][risk=no] Use account creation time instead of RT access time for survey eligibility

- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
Add `PERSONALFAMILYHEALTHHISTORY` attribute to selections made from the Personal and Family Health History survey
---
* AoU UI
> [DT-75][risk=no] Send attribute with PFHH survey selections
