- api/config/config_perf.json
Description:
I will manually apply this change to perf right after Terra release PPW to perf, then merge this PR.
---
> [RW-7278][risk=low]: Enable v2 billing feature flag when Terra PERF in PPW

- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
Step 1 of the DAR rollout: https://precisionmedicineinitiative.atlassian.net/browse/RW-7256
---
> [risk=low][RW-7089] enableDataAccessRequirements in all environments

- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
Placed after Visits in the menu per the ticket:
---
> [RW-7271][risk=no] Add Observations to cb_criteria_menu table

- api/src/main/java/org/pmiops/workbench/ras/RasLinkService.java
> [RW-7279][risk=low] Do not log user passport and visa from RAS linking response

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/utils/access-utils.tsx
If the user sees this on the AAR page:
The Admin sees this for that user's admin page:
User Admin for an Expired or Incomplete user (in this example, the user is both) :
Corresponding to this AAR screen:
---
> [risk=low][RW-7015] Add AAR details to admin-user

- e2e/tests/notebook/notebook-reader-actions.spec.ts
Cloud integrations is investigating a fix.
> [RW-7287][risk=no] Skip Terra workspace clone test

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/profile/data-user-code-of-conduct.spec.tsx
- ui/src/app/pages/profile/data-user-code-of-conduct.tsx
- ui/src/testing/stubs/profile-api-stub.ts
One piece of RW-4838.  After a release I'll remove the now-deprecated version.
---
> [risk=no][RW-4838] Rename submitDataUseAgreement to submitDUCC

- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
> [risk=low][RW-7256] sync each module individually via refresh, and redirectToRas

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
Extract a TierConfig functional component from AdminInstitutionEdit, as well as a few smaller ones.
I have further plans for refactoring this code, mainly involving error state.  But this is a good checkpoint and a decent size for independent review.
---
> [risk=low][no ticket] Partial functional refactoring of AdminInstitutionEdit

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/testing/stubs/runtime-api-stub.ts
> [risk=no] Bump runtime panel minimum disk to 80GB

- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
Before:
```
Sep 20, 2021 4:41:27 PM org.pmiops.workbench.rdr.RdrExportServiceImpl exportUsers
SEVERE: Error while sending researcher data to RDR for user IDs: class ArrayOfLong {
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
Sep 20, 2021 4:41:27 PM org.pmiops.workbench.rdr.RdrExportServiceImpl exportUsers
INFO: successfully exported researcher data for user IDs: class ArrayOfLong {
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
```
After:
```
Sep 20, 2021 5:28:27 PM org.pmiops.workbench.rdr.RdrExportServiceImpl exportUsers
SEVERE: Error while sending researcher data to RDR for user IDs [class ArrayOfLong {
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}]: {"message": "User givenName can not be NULL"}
```
---
> [risk=low][no ticket] Log the RDR Export User APIException (and don't claim success)

- e2e/tests/nightly/gce-to-dataproc.spec.ts
Updated UI was #5617 but the e2e test also needs a bump to match.
Test passed locally.
---
> [risk=no][no ticket] Also update the gce-to-dataproc test to comply with min disk

- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
- e2e/app/text-labels.ts
- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
Name change has been requested check https://precisionmedicineinitiative.atlassian.net/browse/RW-7247
---
> [RW-7247][risk=no] Change all references to "whole genome variant data" 

- api/config/cdr_config_test.json
- e2e/tests/cohorts/cohort-group-actions.spec.ts
- Fixes test with updated name for cohort search item
- Bump cdr to `synth_r_2019q4_17` for Synthetic Dataset v3 in test env
---
> [risk=no] Fix 'Whole Genome Sequence' text in cohort actions test

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/testing/react-test-helpers.tsx
- ui/src/testing/stubs/institution-api-stub.ts
While working on Admin Inst Edit I realized that I have made enough changes here to justify pulling it out into a separate PR.
---
> [risk=no][no ticket] Update Admin Inst Edit UI tests

- api/config/cdr_config_prod.json
adding new CDR verison R2021Q3R2
> [no ticket][risk=no] adding new CDR verison R2021Q3R2

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/runtime-error-modal.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/leo-runtime-initializer.spec.tsx
- ui/src/app/utils/leo-runtime-initializer.tsx
- ui/src/app/utils/runtime-utils.tsx
> [RW-7121][risk=no] Surface runtime error messages to users via UI

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-aou/CHANGELOG.md
Primary change is a fix for multipart uploads.
Ran puppeteer locally - passed. Verified multipart file upload now working as well.
> [RW-7308][risk=low] Update Jupyter image version

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
Following up on a comment in #5639 as well as some general cleanup to support other imminent changes to inst admin edit
---
> [risk=low][no ticket] Refactor inst admin edit tests, add a few, and fix a minor bug

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
All code related to this long-obsolete FF has been removed (#5613), so we can now remove the FF itself.
---
> [risk=no][no ticket] rm enableMoodleBackend FF

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/libproject/cloudsqlproxycontext.rb
> [no ticket][risk=no] updating domain card counts

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/components/admin/audit-page-component.tsx
- ui/src/app/components/buttons.tsx
- ui/src/app/components/cookie-banner.tsx
- ui/src/app/components/footer.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/admin/admin-workspace-audit.tsx
- ui/src/app/pages/admin/user-audit.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/pages/cookie-policy.tsx
- ui/src/app/pages/data/criteria-search.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/quick-tour-modal.tsx
- ui/src/app/pages/login/login.spec.tsx
- ui/src/app/pages/login/login.tsx
- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/sign-in-again.tsx
- ui/src/app/pages/user-disabled.tsx
- ui/src/app/pages/workspace/old-cdr-version-modal.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- StyledRouterLink for a link within the router
- StyledExternalLink for a link outside of Workbench
- Renamed `Link` to `LinkButton` in order to not shadow react-router `Link`
---
> [RW-7154][risk=no] StyledAnchorTag for external links, StyledRouterLink for router links

- ui/src/app/components/buttons.tsx
Description:
Forgot to push a change before merging. Oops
---
> [no ticket][risk=no] comment on LinkButton

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
> [no ticket][risk=no] removing survey data

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
> [no ticket][risk=no] bumping test cloud cdr

- api/config/cdr_config_preprod.json
> [no ticket][risk=no] bumping cloud cdr in preprod

- ui/package.json
- ui/yarn.lock
Alternative to #5655 - we don't appear to actually use this package
---
> [risk=no][no ticket] rm vulnerable zone.js

- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/testing/stubs/runtime-api-stub.ts
> [no ticket][risk=no] runtime errors length

- api/libproject/devstart.rb
Adding a project.rb command that will build prep_survey with specified survey file.
> [no ticket][risk=no] adding command for each survey

- api/db-cdr/generate-cdr/make-bq-prep-survey.sh
> [no ticket][risk=no] fixing bug in script

- api/db-cdr/generate-cdr/make-bq-prep-survey.sh
print more output in shell script for debug
> [no ticket][risk=no] print more output in shell script for debug

- ui/src/app/routing/app-routing.tsx
- ui/src/app/services/setup.ts
- ui/src/index.ts
> [RW-7198][risk=no] Move bootstrapping out of app-routing

- e2e/tests/profile/profile-page.spec.ts
I don't have any viable theories on this issue yet. Adding additional logs for now.
> [RW-6752][risk=no] Add logging for table-driven profile test

- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Use accessModuleService as the source of truth in all cases
---
> [risk=low][no ticket] rm all calls to getCompletionTime() and getBypassTime()

- api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> [risk=low][no ticket] Add DUCC Version check to the offline access sync

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
> [risk=low][RW-7364] disable flaky DAR test

- ui/src/app/components/access-renewal-notification.tsx
- ui/src/app/components/app-router.tsx
- ui/src/app/components/buttons.tsx
- ui/src/app/components/copy-modal.tsx
- ui/src/app/components/login-gov-ial2-notification.spec.tsx
- ui/src/app/components/login-gov-ial2-notification.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/not-found.tsx
> [RW-7354] Put path prop on Button

- api/db/changelog/db.changelog-177-add-egress-event-table.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/dao/EgressEventDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbEgressEvent.java
- api/src/main/java/org/pmiops/workbench/opsgenie/EgressEventServiceImpl.java
- api/src/test/java/org/pmiops/workbench/opsgenie/EgressEventServiceTest.java
- New table: egress_event
- Adds hibernate model / dao
- Adds deduplication logic and writes to DB when receiving egress events
> [RW-7313][risk=low] Add/populate egress_event table

- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-utils.tsx
Description:
Per Shimon's comment: https://precisionmedicineinitiative.atlassian.net/browse/RW-7062
We will use the same disabled users screen
---
> [RW-7662][risk = low]: Show disable screen when user is removed from institution RT requirement

- api/db-cdr/generate-cdr/bq-schemas/prep_survey_concept_ancestor.json
- api/db-cdr/generate-cdr/create-prep-survey.sh
- api/db-cdr/generate-cdr/create-survey-criteria.sh
- api/db-cdr/generate-cdr/create-tables.sh
> [RW-7304][risk=no] adding counts for survey tree

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
~~**DO NOT MERGE**: until https://github.com/all-of-us/workbench/pull/5609 reaches production.~~
Feature flag removal part 2/2.
> [RW-6877][risk=no] rm enableUnifiedUserAccessCron feature flag

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
> [risk=no][RW-7364] Attempt to resolve flaky test using jest fake timers

- e2e/tests/ui/notebook-ui.spec.ts
This test can fail when the same notebook is deleted by another test running concurrently or Jenkins delete-workspace script.
> [no ticket][risk=no] Fix e2e notebook-ui test

- api/config/featured_workspaces_prod.json
Request to unPublish and Publish some tutorial and Phenotype workspaces.
Note:I have already manually Publish/UnPublish the workspace via the About page. 
---
> [RW-7347][risk=no] Featured Workspaces: Publish the following featured workspaces

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/pages/homepage/homepage.tsx
Currently, the Compliance Training redirect back to the RW does NOT record successful training completion.  This is a regression: the old RegistrationDashboard did so correctly.
While the problem seems to be limited to Compliance, this PR solves the problem generally: sync all incomplete modules on DAR load.  (Compliance Training completion redirects back to the RW.  For unregistered users, we redirect all RW paths to DAR.)
---
> [risk=low][RW-7309][RW-7384] DAR: sync incomplete modules to enable user completion

- api/config/config_stable.json
This will allow us Moodle devs to create Stable accounts to help test integration.
---
> [risk=low][RW-6970] Switch Stable Moodle connection from Dev to Prod

- api/config/config_local.json
- ui/src/app/pages/workspace/create-billing-account-modal.tsx
> [RW-7284][risk=low]Spin while sending emails and enable billing feature in local

- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/utils/access-utils.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
We store the Moodle URL in 2 places, so they can conflict.  Let's stop doing that.
Followup to #5710 - that change was not sufficient to actually update the environment.
Description:
---
> [risk=low][RW-6970] rm UI env var trainingUrl

- api/src/main/java/org/pmiops/workbench/config/FileConfigs.java
- api/src/test/java/org/pmiops/workbench/config/WorkbenchConfigTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java
https://github.com/all-of-us/workbench/pull/5714 proposes a more complex structure than we've used historically. It seemed like a good time to add additional test validation of these configs.
> [RW-2408][risk=no] Add unit test to validate all config_*.json

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
Code cleanup; no changes expected.
---
> [risk=low][RW-7256] refactor RegistrationTasks into AccessModuleConfig for better AAR and DAR alignment

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
Adding categorical and numeric values to observation. This allows the UI to show observations that have categorical or numerical or both
> [RW-6573][risk=no] adding categorical and numeric values to observation

- api/config/featured_workspaces_prod.json
Got a request to Publish another workspace. For more details check the latest comment 
https://precisionmedicineinitiative.atlassian.net/browse/RW-7347?focusedCommentId=98635
---
> [RW-7347][risk=no] Featured Workspaces: Publish the following featured workspaces in the description

- api/config/cdr_config_preprod.json
Adding new CT CDR to preprod. I named this new CT CDR -> All of Us Controlled Tier Dataset v6 beta. Please advise on correct name.
> [no ticket][risk=no] adding new CT CDR to preprod.

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
fixing null id problem in cb_criteria_attribute
> [no ticket][risk=no] fixing null id problem in cb_criteria_attribute

- .circleci/config.yml
Description:
`api/build/test-results` stores for XML tests reports which are hard to read. 
`api/build/reports` stores html files. 
Also, bigquery and api-integration tests reports is missing because those are stored at `api/build/test-results/{bQTests/tests}`
(I made it 
upload the entier reports directory incase one day we want to see coverage report, spotbug reports).
---
> [RW-7412][risk=low]  Use htlm test report and upload for all API tests

- api/src/main/java/org/pmiops/workbench/api/CloudTaskEgressController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressEventServiceTest.java
Stacked on https://github.com/all-of-us/workbench/pull/5721
> [RW-7316][risk=low] Add egress event queue / cloud task handler

- e2e/resources/workbench-config.ts
Temporarily changed the configs to run staging on my PR, passed: https://app.circleci.com/pipelines/github/all-of-us/workbench/14958/workflows/01770c44-1e5d-49ff-82b4-6d4150a187cc/jobs/173375
> [risk=no] Fix circle staging configs

- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/utils/institutions.tsx
- ui/src/testing/stubs/institution-api-stub.ts
Replace tier-specific functions with tier-generic functions (e.g. `setRegisteredTierRequirement()` -> `setMembershipRequirement()`) and related changes
---
> [risk=low][no ticket] Make Admin Inst Edit more tier-generic

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
Created an insert statement in observation and surveys that adds in min/max values.
> [RW-6573][risk=no] Adding in min/max for observation and surveys

- .circleci/config.yml
> [RW-7412][risk=low] Upload xml file for CI to have test reports

- api/config/cdr_config_local.json
- api/config/cdr_config_test.json
This breaks nightly tests without changes from https://github.com/all-of-us/workbench/pull/5745
> [RW-7207][risk=no] mv WGS to controlled tier in local/test

- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/utils/institutions.tsx
Update one of the inst-admin-edit functions as suggested here: https://github.com/all-of-us/workbench/pull/5658#discussion_r727362586
If we like this, I'll apply the pattern to the other functions.
---
> [risk=no][no ticket] more updateTier refactoring

- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
removing all survey concepts from observations in criteria table
> [no ticket][risk=no] removing all survey concepts from observations in criteria table

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Description:
The code that uses those configs is deleted 2 release cycles ago
---
> [no ticket][risk=no] remove PPW feature flags

- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> [risk=low][no ticket] Move getCurrentDuccVersion() from UserService to AccessModuleService

- e2e/tests/workspace/cdr-version-upgrade.spec.ts
> [risk=no][no ticket] e2e typo: llder -> older

- ui/docs/rw-7059.md
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
> [risk=low][RW-7059] Add CT card and first 2 steps to DAR

- ui/src/app/pages/homepage/data-access-requirements.tsx
Note: does not complete RW-7461.  This PR makes the text appear in all cases.  The behavior-dependent version of RW-7461 is blocked on higher-priority DAR work for CT (https://precisionmedicineinitiative.atlassian.net/browse/RW-7059) 
Unfortunately, Zendesk is broken in lower environments so I couldn't fully test this.  I was able to successfully trigger a a different action `redirectToTraining()` when I substituted it on line 450.
---
> [risk=no][RW-7461] Add help text and zendesk link to RAS module in DAR

- api/config/cdr_config_test.json
> [no ticket] [risk=no] Change CDR Version

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/db-cdr/generate-cdr/make-bq-dataset-linking.sh
- api/src/main/java/org/pmiops/workbench/cdr/dao/DSLinkingDao.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/DSLinkingDaoTest.java
adding primary key to ds_linking table, this will allow us to order the select columns.
> [no ticket][risk=no] adding primary key to ds_linking table

- ui/src/app/pages/homepage/data-access-requirements.tsx
Description:
Saw this code while learning how navigate works, seems to be a typo.
---
> [no ticket][risk=no] remove extra comma and space

- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/stubs/profile-api-stub.ts
> [RW-7517]  Add Fake Controlled Tier Training

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditor.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/EgressEventTargetProperty.kt
- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/java/org/pmiops/workbench/api/SumoLogicController.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventService.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/SumoLogicControllerTest.java
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressEventServiceTest.java
Per design doc: https://docs.google.com/document/d/1E1dj4HPNchXofRZOV_jmvGREImd0JMCTa2I4VuafdOo/edit#heading=h.2sljjr2g51z1
Follow-up PR will implement. Just Swagger for now.
> [RW-7318][risk=no] Propose listEgressEvents API

- api/config/cdr_config_test.json
> [no ticket][risk=no] Changed CDR Version

- ui/src/app/cohort-search/cohort-search/cohort-search.component.spec.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/app/pages/data/concept/concept-search.spec.tsx
found a few more references to enableStandardSourceDomains feature flag.
> [RW-7102][risk=no] found a few more references to enableStandardSourceDomains feature flag.

- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- ui/src/app/cohort-search/utils.ts
> [no ticket][risk=no] adding menu item for device

- ui/src/app/pages/admin/admin-workspace.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
- ui/src/app/pages/workspace/workspace-share.tsx
- ui/src/app/utils/workspace-utils.tsx
- ui/src/testing/default-server-config.ts
Description:
Background: https://precisionmedicineinitiative.atlassian.net/browse/RW-5107
And I think it is problematic, seems we stop setting that field at some point. 
---
> [RW-5107][risk=low]: Remove using BillingAccountType and it is problemtic

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
Changed CDR Version in staging, stable and perf
> [no ticket][risk=no] Changed CDR Version in staging, stable and perf

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cohorts/CohortMaterializationServiceTest.java
- api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
Uppercase BigQuery keywords in generated SQL
---
> [no ticket][risk=no] uppercase BigQuery keywords in generated SQL

- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
> [RW-7326][risk=no] Show security suspended UX for runtime icon in sidebar

- ui/src/app/pages/workspace/workspace-about.spec.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
> [risk=low][RW-4102] Indicate Workspace published state in UI (to FEATURED_WORKSPACE_ADMINs) 

- api/build.gradle
Addresses https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
---
> [risk=low][no ticket] bump gson to address vuln

- api/db-cdr/changelog-data/db.changelog-1.xml
> [no ticket][risk=no] updating local data load

- api/genomics/build.gradle
RandomizeVcfTest passed - is that sufficient to verify this?
---
> [risk=low][no ticket] bump genomics deps

- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/signed-in/signed-in.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-tiers.tsx
- ui/src/app/utils/access-utils.tsx
`hasRegisteredAccess()` -> `hasRegisteredTierAccess()`
add `hasTierAccess()`
a few other small changes
This will help with my work on https://precisionmedicineinitiative.atlassian.net/browse/RW-7520
---
> [risk=low][no ticket] refactor some access-utils code

- api/config/config_prod.json
> [RW-4789][risk=low] Fully launch billing 

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
changing text for VCF Files(s) to VCF Files
> [no ticket][risk=no] changing text for VCF Files(s)

- ui/src/app/components/popups.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
https://user-images.githubusercontent.com/35533885/140594121-2a8f8ca2-4dad-4e5c-a5e7-f6b1872658a4.mov
> [RW-7522][risk=no] CT workspace cards are disabled for non-CT users

- ui/src/app/pages/analysis/notebook-frame-error.tsx
Will be used in egress e2e test
> [RW-7325][risk=no] Add a data-test-id for the security suspended message

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/config/WorkbenchConfigTest.java
With the Monday Nov 8 release, all envs have this FF set to false.
---
> [risk=low][RW-7516] rm all instances of unsafeAllowAccessToAllTiersForRegisteredUsers

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ConfigController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/resources/workbench-api.yaml
removing enableStandardSourceDomains flag
> [RW-7012][risk=no] removing enableStandardSourceDomains flag

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
> [risk=no][no ticket] Make it explicit that we're using the Google Project in FreeTierBillingService

- api/docs/pyspark-usage.md
I may not merge this, just for initial review.
> [RW-7106][risk=no] Pyspark code snippets

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/EgressEventMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
THis will allow admins to mark an egress event as a verified false positive.
~~Stacked on #5875~~
> [RW-7319][risk=low] Add updateEgressEvent admin API

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceUtils.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestConfig.java
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
I might need another PR to drop the column from DB?
---
> [RW-5107][risk=no]: Remove using billingAccountType in API

- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditor.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt
- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/EgressEventTargetProperty.kt
- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
> [RW-7319][risk=no] Audit updateEgressEvent

- api/config/config_local.json
- api/config/config_test.json
Description:
Dataproc is not working because master node had private network tags while inialize it. 
See: https://terra-bio.slack.com/archives/C9C4KKU65/p1636058245032600
---
> [no ticket][risk=no] rollback private dataproc worker ff in test and local. 

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-egress-events.tsx
- ui/src/app/pages/admin/egress-events-table.spec.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/authorities.tsx
- ui/src/testing/react-test-helpers.tsx
- ui/src/testing/stubs/egress-events-admin-api-stub.ts
- Supports lazy pagination
- Supports updating event status 
Stacked on #5897
> [RW-7322][risk=no] Implement egress events admin page

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-egress-events.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/admin/admin-workspace.tsx
- ui/src/app/pages/admin/egress-events-table.spec.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/authorities.tsx
- ui/src/testing/react-test-helpers.tsx
- ui/src/testing/stubs/egress-events-admin-api-stub.ts
> [RW-7323][RW-7324][risk=no] Add egress events table to user/workspace admin pages

- api/docs/pyspark-usage.md
> [no ticket][risk=no] fix format in dataproc tutorial doc

- api/docs/pyspark-usage.md
Description:
RT workspace does not have dataproc support
---
> [no ticket][risk=no] Use CT dataset path for spark tutorial

- ui/src/app/pages/admin/admin-user-bypass.tsx
Change requested by an admin
Before
After
---
> [risk=no][no ticket] Add RT to "Compliance Training" in user admin bypass label

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
https://github.com/all-of-us/workbench/pull/5877 added the policies but forgot to flip the feature flag 🤦
> [RW-7373][risk=moderate] Actually launch egress alerting v2

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Per: https://terra-bio.slack.com/archives/C9C4KKU65/p1637184784060800
Seems the issue is less frequently, and we are ready to upgrade the version
---
> [RW-7478][risk=low]: Bump Jupyer version to 2.0.3

- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-actions-menu.tsx
Extract a WorkspaceActionsMenu from `help-sidebar` as a first step in creating a component shared with `workspace-card`
---
> [risk=low][no ticket] begin refactoring a WorkspaceActionsMenu

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
superceded by TracingInterceptor
> [RW-4826][risk=no] Drop unused recordOperationTime

- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
> [risk=low][RW-7576] Email all owners of an admin-locked workspace, not just the creator

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
Bug fix for empty search group items
> [RW-7409][risk=no] Bug fix for empty search group items

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/actionaudit/ActionAuditQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/test/java/org/pmiops/workbench/actionaudit/ActionAuditQueryServiceTest.java
Preprod and Staging are configured differently from other envs, so we need to account for this in the app config.
Tested by running user audit locally
TODO: update the config in Terraform ([RW-7601](https://precisionmedicineinitiative.atlassian.net/browse/RW-7601))
---
> [risk=low][RW-7573] add a partitionColumn field to the actionAudit config

- api/config/cdr_config_prod.json
> [no ticket][risk=no] bumping cloud cdr version

- api/docs/pyspark-usage.md
> [no ticket][risk=no] Fix another typo in spark readme

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/testing/stubs/runtime-api-stub.ts
Avoid the "min" property where possible, this results in awkward UX around changing the number
> [RW-7460][risk=no] Better number input interactions for dataproc workers

- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/ProfileTargetProperty.kt
> [RW-7509][risk=no] Stop audit logging gratuitous user data

- api/db-cdr/generate-cdr/create-local-csv-files.sh
- api/libproject/devstart.rb
Created a project.rb command to load local csv files into [google bucket](https://console.cloud.google.com/storage/browser/all-of-us-cb-test-csv;tab=objects?hl=en&organizationId=394551486437&project=all-of-us-workbench-test&prefix=&forceOnObjectsSortingFiltering=false)
> [RW-7549][risk=no] Created command to load local csv files into bucket

- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
> [RW-7501][risk=no] Remove period in institution short name

- api/build.gradle
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Upgrade our `com.google` API deps as far as possible.
Tested locally. 
---
> [risk=low][no ticket] Upgrade some Google API dependencies

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/cdrselector/WorkspaceResourcesServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/FirecloudMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceFields.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
> [risk=low][RW-5638] use MapStruct in getUserRecentResources()

- api/build.gradle
Attempt to resolve (or partially resolve) https://app.snyk.io/org/all-of-us-researcher-workbench/project/c8c259df-1b81-4f05-9924-24f9e20ec2a7#issue-SNYK-JAVA-CHQOSLOGBACK-1726923
---
> [risk=low][no ticket] bump some versions with logback transitive dependencies

- e2e/app/modal/base-modal.ts
- e2e/app/modal/copy-to-workspace-modal.ts
- e2e/app/modal/modal.ts
- e2e/app/page/workspace-analysis-page.ts
- e2e/libs/page-events-helper.ts
- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
`owner-copy-to-workspace.spec.ts`:
CircleCI run [failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/16158/workflows/0118f1ec-601a-45ad-8932-c25502302f03/jobs/182862/tests).
`notebook-create-python.spec.ts`:
CircleCI run [failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/16161/workflows/663b03a4-9855-436e-9f0b-c4aa968466fb/jobs/182895/tests).
> [no ticket][risk=no] Fix e2e flaky tests

- api/db-cdr/generate-cdr/create-tables.sh
adding debug output in create tables script
> [no ticket][risk=no] adding debug output in create tables script

- ui/src/app/routing/app-routing.tsx
- ui/src/app/routing/guards.tsx
Instead, users are redirected to the homepage.
---
> [risk=low][RW-7440] Add disabled page guard so enabled users don't see the disabled page

- api/db-cdr/generate-cdr/create-tables.sh
fixing file path in shell script
> [no ticket][risk=no] fixing file path in shell script

- api/src/main/java/org/pmiops/workbench/api/EgressEventsAdminController.java
- api/src/main/resources/workbench-api.yaml
> [RW-5661][risk=no] Add interface for egress audit endpoint

- api/db-cdr/generate-cdr/build-search-all-events.sh
> [no ticket][risk=no] fixing typo in script

- api/db-cdr/generate-cdr/make-bq-data.sh
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
fixing bug in survey_module table and making a query more efficient.
> [RW-7622][risk=no] fixing bug in survey_module table

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
> [RW-7392][risk=low]: Upgrade AoU jupyter version with nextflow installed

- ui/src/app/pages/analysis/notebook-list.tsx
New UX Design approved from Joy
https://user-images.githubusercontent.com/34481816/144456893-b3cb3be3-2dc7-44c8-83ee-4045efc48885.mov
---
> [risk=no][RW-7620] Update UX For Notebook Clone wait card

- api/db-cdr/generate-cdr/build-cb-criteria-meas-snomed.sh
- api/db-cdr/generate-cdr/build-prep-icd10pcs-rel.sh
fixing errors in cdr indexing build
> [no ticket][risk=no] fixing errors in cdr indexing build

- ui/src/app/components/status-alert-banner-maybe.tsx
- ui/src/app/components/toast-banner.tsx
- ui/src/app/pages/workspace/invalid-billing-banner.tsx
Inline comments describe the changes.  Broken out of #5950 for easier review.
---
> [risk=low][RW-7060] minor updates to the Toast Banner 

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-cb-survey-version.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
- api/db-cdr/generate-cdr/build-prep-icd10pcs-rel.sh
- api/db-cdr/generate-cdr/build-review-all-events.sh
- api/db-cdr/generate-cdr/build-search-all-events.sh
- api/db-cdr/generate-cdr/build-static-prep-tables.sh
- api/db-cdr/generate-cdr/import-cdr-indices-build-to-cloudsql.sh
fixing error and removing output from CDR indexing build
> [no ticket][risk=no] fixing error and removing output from CDR indexing build

- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
- ui/src/app/components/buttons.tsx
- ui/src/app/pages/admin/admin-egress-audit.spec.tsx
- ui/src/app/pages/admin/admin-egress-audit.tsx
- ui/src/app/pages/admin/egress-events-table.spec.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/utils/egress-events.tsx
- ui/src/app/utils/stores.tsx
- ui/src/testing/stubs/egress-events-admin-api-stub.ts
Stacked on https://github.com/all-of-us/workbench/pull/5977
> [RW-5661][risk=no] Implement egress event audit page

- api/build.gradle
Description: A prestup to upgrade Java 
---
> [RW-6779][risk=low] upgrade appengine plugin

- api/libproject/devstart.rb
adding missing params in CDR build command
> [no ticket][risk=no] adding missing params in CDR build command

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [no ticket][risk=low] launch private dataproc in all non-prod envs

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
This has been deprecated and replaced since Aug 2020 (#3901)
---
> [risk=no][no ticket] rm unused updateVerifiedInstitutionalAffiliation()

- api/config/config_test.json
See https://precisionmedicineinitiative.atlassian.net/browse/RW-7617
> [RW-7617][risk=no] Try reverting NB image upgrade in test

- api/src/main/webapp/static/aou-file-tree-policy-extension.js
> [RW-6459][risk=no] Prompt for "affirm" text on download

- ui/src/app/pages/workspace/workspace-about.tsx
> [RW-5893][risk=no]Don't load free tier usage if user does not have writer permission

- api/db-cdr/generate-cdr/build-cb-search-person.sh
removing duplicate row from sql script
> [no ticket][risk=no] removing duplicate row from sql script

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
No functional changes, just style/cleanup as I was passing thru
---
> [risk=no][no ticket] Some small API code cleanups

- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Switch back and forth betw an inst which provides CT and one which does not (as admin)
Now switch contact emails within an inst, where one email grants RT+CT access and the other only RT
Does not complete 7634 b/c a sync is not triggered when we save the institution itself.
---
> [risk=low][RW-7634] Sync user access tiers when admin updates affiliation

- api/config/config_test.json
Reverts all-of-us/workbench#6006
Trying this to confirm whether it will reduce flakiness.
Blocked on https://github.com/DataBiosphere/leonardo/pull/2441
> [RW-7617][risk=no] Downgrading notebook image to 2.0.1 in test

- api/db-cdr/generate-cdr/validate-cdr.sh
- api/libproject/devstart.rb
Created a ./project.rb command to validate synthetic data and new CDRs
> [RW-6434][risk=no] Created command to validate synthetic data and new CDRs

- e2e/tests/nightly/gce-to-dataproc.spec.ts
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/runtime-presets.ts
- ui/src/testing/stubs/runtime-api-stub.ts
> [no ticket][risk=low] bump dataproc worker disk size to 150GB

- ui/src/app/utils/research-purpose.tsx
Description:
<!-
Replace this template with your PR description.
Please remember to keep in mind the security levels outlined in
[CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/master/.github/CONTRIBUTING.md) and to
* **no**: None
Please also:
-->
---
> [RW-6170][risk=no] Add other population details in workspace about and admin workspace page

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- ui/app.yaml
- ui/src/app/utils/zendesk.ts
Description:
SSO has been configed. The next step would be correct article ids for widgets, but sandbox does not have those articles yet. 
---
> [RW-7476][risk=no] config sandbox zendesk

- ui/src/app/pages/workspace/workspace-list.spec.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
- ui/src/testing/stubs/workspaces-api-stub.ts
Add test coverage of workspace list filtering
> [RW-3856][risk=no] Fix workspace list filtering on reload

- ui/src/app/components/side-nav.tsx
> [RW-7639][risk=no] Fix admin institution highlight issue when select workspace admin

- ui/src/app/pages/admin/admin-user.tsx
Update free credits limit dropdown to allow these values as requested:
* existing quota value
* $300 to $1000, in $100 increments
* $1000 to $10,000, in $500 increments
---
> [risk=no][RW-7630] Update free credits dropdown values

- ui/yarn.lock
Resolves https://github.com/advisories/GHSA-896r-f27r-55mw
---
> [risk=low][no ticket] bump jsprim to resolve json-schema vuln

- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
fixing death date problem in cb_search_person table
> [no ticket][risk=no] fixing death date problem in cb_search_person table

- api/config/cdr_config_test.json
Most likely I copied this from `cdr_config_local.json`
> [risk=no] Fix archived CDR table name

- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
Suggestion from a comment on #6019
---
> [risk=low][no ticket] Don't allow modification of institution shortName

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Regression test covers this case.
> [RW-5656][risk=no] Disallow whitespace-only text entry on workspace create/edit

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
> [risk=low][RW-7473] Sync expiring modules on AAR load

- api/genomics/build.gradle
> [risk=low][no ticket] bump genomics deps to latest

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/admin/admin-lock-request.tsx
On the Workspace Admin page:
---
> [risk=low][RW-7482] Improvements to Admin Locking UI

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Part (2/2), stacked on #5998 
~~**Do not merge** until #5998 is in production.~~
> [RW-7372][risk=no] rm egress v2 flag

- api/db-cdr/generate-cdr/build-prep-survey.sh
fix ordering of answers in surveys
> [no ticket][risk=no] fix ordering of answers in surveys

- api/db-cdr/generate-cdr/import-cdr-indices-to-cloudsql.sh
> [no ticket][risk=no] fix typo in CDR indices build

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Will upgrade that manually after: https://precisionmedicineinitiative.atlassian.net/browse/PD-6980
---
> [ no ticket][risk=low][log4j fix] upgrade with gatk to upgrade log4j issue

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
add missing variable in CDR indices build
> [no ticket][risk=no] add missing variable in CDR indices build

- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/FieldSetQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java
- api/src/main/java/org/pmiops/workbench/utils/FieldValues.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/util/QueryParameterValuesTest.java
We're pretty used to epochMillis, so epoch**Micros** may be a little unexpected.  Let's add some helpers.
---
> [risk=low][no ticket] Help convert between Instant and BQ epoch micros

- api/genomics/build.gradle
And possibly address a [vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-31522) by upgrading plexus-utils
---
> [risk=low][no ticket] Use release version of GATK

- api/build.gradle
Local testing on API + UI: dev-up, local database connection, cohort builder, dataset builder, execute notebook BQ query
---
> [risk=low][no ticket] Bump google packages in API

- api/build.gradle
Local testing on API + UI: dev-up, local database connection, execute notebook BQ query
---
> [risk=low][no ticket] Update a few API packages 

- .circleci/config.yml
> [risk=no][no ticket] gcloud login in e2e job

- api/db-cdr/changelog-data/db.changelog-1.xml
adding column and type for cb_person for liquibase
> [no ticket][risk=no] adding column and type for cb_person for liquibase

- ui/yarn.lock
A large number of `@babel` UI packages can be minor-version-upgraded.  Changes to yarn-lock only.
---
> [risk=low][no ticket] Minor version upgrades for 'babel' UI packages

- api/config/cdr_config_prod.json
Migrating RT CDR hotfix to prod.
@dolbeew Please don't merge this PR until you hear from Kayla Marginean. Also, please publish the hotfix CDR in prod before you deploy to prod
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod  --bq-dataset R2021Q3R5 --tier registered
> [no ticket][risk=no] migrating RT CDR hotfix to prod

- api/buildSrc/build.gradle
- appengine-cron-emulator/build.gradle
> [risk=low][no ticket] Update Jackson and Databind for buildSrc and appengine-cron-emulator

- ui/.eslintrc.js
> [risk=no][RW-7280] add eslint comments w/ broken rule counts

- ui/src/app/components/admin/audit-card-list-view.tsx
- ui/src/app/components/icons.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/admin/admin-users.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/utils/audit-utils.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/institutions.tsx
AdminUserProfile is now at feature parity with the original AdminUser.  I'd like to merge this, with the understanding that there is work remaining.
TODO:
* remove AdminUser
* add the new Access Module Status table from the mocks
* add "dirty" indicators to changed-but-unsaved components
* add Enabled/Disabled toggle
* add API error messages from the previous version
* design and implement "has RT" and "has CT" indicators
* Open Question: replicate the "error" styling if the user has overspent the free credits?
* Open Question: where should we put the Other Role free-text box?
---
> Checkpointing progress on 7536

- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/app/utils/dates.tsx
Inspired by this comment: https://github.com/all-of-us/workbench/pull/6051#discussion_r768117916
---
> [risk=low][no ticket] AAR logic cleanup and tests

- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/authentication.tsx
- ui/src/app/utils/stores.tsx
> [risk=low][no ticket] Make AuthStore.authError optional

- ui/.eslintrc.js
- ui/package.json
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/yarn.lock
https://www.npmjs.com/package/eslint-plugin-react-hooks
Tested the adminLockedGuard changes on Local -> Test
Also sort the eslint rules into "Code Quality" and "Style" categories
---
> [risk=low][RW-7280] Enforce the Rules of Hooks via eslint

- api/genomics/build.gradle
> [risk=low][no ticket] Upgrade GATK and dependencies

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressRemediationService.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/java/org/pmiops/workbench/jira/JiraService.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
Sample ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-7684
> [RW-7100][risk=low] File genomic extraction failures to Jira

- api/build.gradle
As recommended by Broad AppSec
---
> [risk=low][no ticket] bump logback

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/utils/institutions.tsx
> [risk=low][no ticket] Fixes to the admin user pages

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/admin/admin-user.tsx
> [risk=low][RW-7536] Change background color of text inputs and dropdowns if changed

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
> [RW-7689][risk=low] Set zone when creating VMs

- .circleci/config.yml
> [no ticket][risk=no] add cache fallback key in CircleCI puppeteer job

- api/src/main/resources/leonardo.yaml
Description:
Not sure if we need to do this now, but those stays in my local branch for my prototyping work. Those APIs might be helpful for future k8s support
---
> [no ticket][risk=no] Update Leonardo Yaml files to catch up recent Leonardo API changes

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-cdr-indices.sh
- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
- api/libproject/devstart.rb
added in array_table as variable and as argument in devstart.rb file; also added it in as a new column in cb_search_person.json as well as a new row in build-cb-criteria-menu.sh and make-bq-cb-menu.sh.
> [RW-7648][risk=no] Adding Array Data to menu

- e2e/app/page/admin-user-profile-info.ts
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/profile/profile-styles.ts
- ui/src/app/pages/workspace/workspace-about.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/utils/index.tsx
> [risk=low][RW-7598] Rename some UI code from "free tier" and "free credits" to "initial credits"

- ui/.eslintrc.js
- ui/src/app/components/breadcrumb-type.tsx
- ui/src/app/components/breadcrumb.spec.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/admin/egress-events-table.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/pages/homepage/quick-tour-and-videos.tsx
- ui/src/app/pages/login/login.spec.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/leo-runtime-initializer.spec.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/app/utils/stores.tsx
> [risk=low][RW-7280] Apply the eslint rule @typescript-eslint/no-shadow

- api/libproject/devstart.rb
> [no ticket][risk=no] improper quoting on param

- ui/.eslintrc.js
- ui/src/app/cohort-search/utils.ts
- ui/src/app/components/app-router.spec.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/services/notebooks-swagger-fetch-clients.ts
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/access-tiers.tsx
- ui/src/app/utils/analytics.ts
- ui/src/app/utils/research-purpose.tsx
- ui/src/app/utils/resources.tsx
- ui/src/app/utils/retry.tsx
> [risk=low][RW-7280] Apply the eslint rule @typescript-eslint/no-use-before-define

- api/config/cdr_config_test.json
> [no ticket][risk=no] bumping test RT CDR

- api/config/cdr_config_test.json
> [no ticket][risk=no] revert test RT CDR

- api/config/cdr_config_perf.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_staging.json
- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
Description:
That is the real flag that controls this feature...
---
> [RW-7691][risk=low] enable workflow in non-prod env. 

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/make-bq-denormalized-search-person.sh
> [no ticket][risk=no] fixing CDR build

- ui/package.json
- ui/yarn.lock
> [risk=no][no ticket] rm unused node-gyp

- api/config/cdr_config_test.json
> [no ticket][risk=no] promoting cdr index in test

- e2e/tests/workspace/cdr-version-upgrade.spec.ts
e2e test is flaky.
CircleCI failed [job](https://app.circleci.com/pipelines/github/all-of-us/workbench/17288/workflows/b3980de7-4599-40de-86bb-2b3d9cf405f4/jobs/192203/artifacts).
> [no ticket][risk=no] Fix cdr-version-upgrade.spec

- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
It's meaningless to specify this without a moduleName, and Typescript can enforce this.
Also a small improvement to nearby code
---
> [risk=low][no ticket] make moduleName mandatory for bypass requests

- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
Adding array data to cohort builder
> [RW-7703][risk=no] adding array data to cohort builder

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
- ui/src/app/pages/data/concept/concept-list.tsx
Changing source condition/prrocedure hierarchies to ignore domain
---
> [RW-7658][risk=no] Changing source condition/prrocedure hierarchies to ignore domain

- api/build.gradle
> [risk=low][no ticket] bump a few API versions

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/admin/admin-user.tsx
- ui/src/app/utils/access-utils.tsx
> [risk=low][RW-7718] Add access module table with toggles to AdminUserProfile

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
> [no ticket][risk=no] remove billing upgrade feature flag completely 

- .circleci/config.yml
- ci/Dockerfile.circle_build
- deploy/docker-compose.yaml
- ui/src/app/pages/admin/admin-users.spec.tsx
Our current image (and all beginning with `circleci/`) are deprecated: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
---
> [risk=low][no ticket] Update deprecated CircleCI docker image to "next-gen"

- ui/src/app/pages/analysis/runtime-panel.tsx
* Visual fixes
* dead code removal
* open support link in a new tab
> [RW-7336][risk=no] GPU feature polish

- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
This redirect occurs when the runtime leaves the running state and the app is on the terminal page.
> [RW-7738][risk=no] Redirect to analysis table from terminal / spark console

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/iam/IamService.java
- api/src/main/java/org/pmiops/workbench/iam/IamServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
> [RW-7615][risk-low] Revoke user lifesciene runner role when unshare 

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/make-bq-cb-menu.sh
> [no ticket][risk=no] updating criteria menu

- ui/.eslintrc.js
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/data/cohort-review/individual-participants-charts.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/utils/resources.spec.tsx
Some rules are compatible with Prettier, some are incompatible, and some are redundant to it.
---
> [risk=no][RW-7280] Enable some Prettier-compatible eslint rules

- ui/.eslintrc.js
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/testing/stubs/cohorts-api-stub.ts
> [risk=low][RW-7280] enable eslint rule prefer-const

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
> [RW-7762][risk=no] fixing cpt hierarchy path

- ui/src/app/pages/admin/admin-user-profile.tsx
> [RW-7731][risk=no] Adding institution and profile error msg when requests fail

- e2e/app/component/card-base.ts
- e2e/app/component/workspace-card.ts
- e2e/app/container.ts
- e2e/app/element/base-element.ts
- e2e/app/modal/base-modal.ts
- e2e/app/modal/conceptset-save-modal.ts
- e2e/app/modal/copy-to-workspace-modal.ts
- e2e/app/modal/delete-runtime.modal.ts
- e2e/app/modal/edit-delete-annotations-modal.ts
- e2e/app/modal/export-to-notebook-modal.ts
- e2e/app/modal/genomic-extract-confirmation-modal.ts
- e2e/app/modal/lock-workspace-modal.ts
- e2e/app/page/base-page.ts
- e2e/app/page/cohort-participants-group.ts
- e2e/app/page/conceptset-actions-page.ts
- e2e/app/page/home-page.ts
- e2e/app/page/notebook-page.ts
- e2e/app/page/workspace-analysis-page.ts
- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/resources/workbench-config.ts
- e2e/tests/cohorts/cohort-review.spec.ts
- e2e/tests/conceptsets/conceptset-create.spec.ts
- e2e/tests/nightly/admin/workspace-admin-ui.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
- e2e/tests/nightly/owner-copy-to-workspace.spec.ts
- e2e/utils/runtime-utils.ts
- e2e/utils/test-utils.ts
- e2e/utils/waits-utils.ts
Hardening test code to deal with flaky test failure [here](https://app.circleci.com/pipelines/github/all-of-us/workbench/17457/workflows/3fd8ad0e-a652-46a3-9f12-5fbc4b853ff8/jobs/193736/tests).
> [no ticket][risk=no] Fix flaky e2e test

- ui/src/app/components/runtime-cost-estimator.tsx
- ui/src/app/components/runtime-summary.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-utils.tsx
Stacked on https://github.com/all-of-us/workbench/pull/6204
Refactor disk details into a DiskConfig.
> [RW-7582][risk=no] Refactor runtimeConfig.disk settings to diskConfig

- api/db/changelog/db.changelog-187-user-code-of-conduct-agreement-backfill-v2.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
#6111 caused some problems on Test.  I believe this will resolve them.  (May be worth a second look at #6111 though)
---
> [risk=low][RW-7784] Fix the bad backfill of user_code_of_conduct_agreement

- ui/src/app/pages/admin/admin-user-access.tsx
Description:
split only takes string type, sometimes I saw error sayting split is not function for e. So add a string check.
---
> [RW-7369][risk=no] fix few console error log

- api/src/main/java/org/pmiops/workbench/api/AuthDomainController.java
- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
> [risk=low][RW-7712] Enable/disable users from UserAdminProfile

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-full-text-synonym.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh
- api/db-cdr/generate-cdr/make-bq-criteria-tables.sh
Update CDR indices build to update source condition/procedure hierarchies to reflect proper domain
> [RW-7695][risk=no] Update source condition/procedure hierarchies to reflect proper domain

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
> [no ticket][risk=no] fixing cpt tree for RW-7695

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/webapp/WEB-INF/cron_prod.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-user-access.tsx
- ui/src/app/pages/admin/admin-users.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
Description:
- Launch RAS linking in all env. 
- Disable sync access cron job in prod
- Move user-access to a dedicate page. 
Some analysis:
- test: all users were bypassed
- perf: all users were bypassed
- staging: all users were bypassed
- stable: all users were bypassed
- preprod: I will not turn it off. 
---
> [RW-7066][risk=medium] Launch enforce RAS linking 

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
> [no ticket][risk=no] update cpt tree

- api/config/cdr_config_test.json
> [no ticket][risk=no] bump test cdr

- e2e/app/page/admin-workspace-page.ts
- e2e/app/page/authenticated-page.ts
- e2e/app/page/base-page.ts
- e2e/app/page/home-page.ts
- e2e/app/page/notebook-page.ts
- e2e/app/page/profile-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/utils/test-utils.ts
Create one generic `loadPage` function that replaces three very similar functions: `loadPageUrl`, `reloadPage` and `gotoUrl`.
---
> [risk=no][no ticket] e2e create generic function loadPage

- e2e/libs/page-manager.ts
> [risk=no][no ticket] e2e block google analytics api

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/pages/admin/admin-institution.tsx
- ui/src/app/utils/institutions.tsx
- ui/src/testing/stubs/institution-api-stub.ts
Also do a bit of refactoring
---
> [risk=low][RW-7670] Set ERA Required = false by default for institutions

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh
updating proper domain on source trees
> [no ticket][risk=no] updating proper domain on source trees

- api/db-cdr/generate-cdr/stage-redcap-files.py
fix family history staging file
> [no ticket][risk=no] fix family history staging file

- e2e/app/component/workspace-card.ts
- e2e/app/page/admin-workspace-page.ts
- e2e/app/page/cohort-actions-page.ts
- e2e/app/page/cohort-review-page.ts
- e2e/app/page/conceptset-page.ts
- e2e/app/page/notebook-frame.ts
- e2e/app/page/notebook-page.ts
- e2e/app/page/profile-page.ts
- e2e/app/page/user-admin-page.ts
- e2e/app/page/workspace-about-page.ts
- e2e/app/page/workspace-analysis-page.ts
- e2e/app/page/workspace-data-page.ts
- e2e/libs/page-events-helper.ts
- e2e/libs/page-manager.ts
Minor e2e test code refactor to reduce flakiness.
---
> [no ticket][risk=no] e2e minor improvement

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Leo cache update is https://github.com/DataBiosphere/leonardo/pull/2517
> [RW-7702][risk=low] Bump AoU notebooks image to latest

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> [RW-7745][risk=no]  While Creating Account, TOS version should be verified before creating the entries in user table and google table

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
ProfileController was using a custom method instead of MapStruct
---
> [risk=low][no ticket] use AddressMapper in ProfileController

- ui/package.json
- ui/yarn.lock
also a few other minor-version upgrades
---
> [risk=low][no ticket] Force the node-forge version to address vulnerabilities

- ui/.eslintrc.js
- ui/package.json
- ui/yarn.lock
Extend the prettier base ruleset to exclude prettier-incompatible rules
---
> [risk=no][RW-7280] Enhance prettier compatibility

- api/config/cdr_config_preprod.json
bumping cdr version in preprod
@dolbeew you are release engineer on Monday, so you will need to publish RT and CT cdr in preprod only. Please reference this [doc](https://docs.google.com/document/d/1WZvkrIaaVWFM6KD742DbEwwbK03OC_RtOreCMXFU6xQ/edit#bookmark=id.h5gra6u3il5k) for publish commands
> [RW-7818][risk=no] bumping cdr version in preprod

- ui/src/app/components/runtime-cost-estimator.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/default-server-config.ts
- ui/src/testing/react-test-helpers.tsx
- ui/src/testing/stubs/disk-api-stub.ts
- ui/src/testing/stubs/runtime-api-stub.ts
Part 3/??
Guarded by enablePersistentDisk
https://user-images.githubusercontent.com/822298/151486666-831e97b9-19bb-4182-8889-0abf5665e120.mp4
> [RW-7759][RW-7582][risk=low] Implement detachable disk selector

- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/pages/admin/admin-institution.tsx
- ui/src/app/pages/profile/data-access-panel.tsx
Follow up PR for https://github.com/all-of-us/workbench/pull/6240
---
> [risk=no][no ticket] Use orderedAccessTierShortNames array

- ui/.eslintignore
- ui/.eslintrc.js
- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/demographics/demographics.component.tsx
- ui/src/app/cohort-search/gender-chart/gender-chart.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/app/components/combo-chart.component.tsx
- ui/src/app/icons/edit.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
- ui/src/app/routing/app-routing.tsx
- ui/src/app/utils/analytics.ts
- ui/src/app/utils/zendesk.ts
There are about 15 instances where we can't apply the rule.  We can disable the rule for these temporarily, and investigate in follow-up PRs.
---
> [risk=low][RW-5572][RW-7280] Apply eslint dot-notation where possible

- ui/src/app/pages/admin/admin-institution-edit.tsx
https://user-images.githubusercontent.com/35533885/153036478-d744aa67-2f71-4161-b2c9-c945c70d5c51.mov
---
> [risk=no][RW-7858] Institution Admin page stays after Save institution edits

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
> [no ticket][risk=no] fixing cpt tree

- ui/.eslintrc.js
- ui/src/app/components/genomics-extraction-table.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/criteria-search.tsx
- ui/src/app/pages/data/data-component.tsx
- ui/src/app/pages/homepage/quick-tour-modal.tsx
- ui/src/app/pages/profile/demographic-survey.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/workspace/research-purpose.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/utils/research-purpose.tsx
- ui/src/react-app-env.d.ts
> [risk=low][RW-7280] Enable eslint rule spaced-comment

- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
Following up on #6281 
Remove a few dot-notation excpetions
---
> [risk=low][RW-5572] Convert a few to dot-notation

- api/config/cdr_config_preprod.json
> [no ticket][risk=no] bumping cdr in preprod

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Remove these unused Billing Buffer config values
---
> [risk=no][no ticket] remove unused billing buffer config

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
- api/db-cdr/generate-cdr/build-cb-criteria-observation.sh
> [no ticket][risk=no] fixing attributes

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh
Add CPT4, ICD9Proc and ICD10PCS data to ancestor table
> [no ticket][risk=no] add CPT4, ICD9Proc and ICD10PCS data to ancestor table

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
> [RW-7715][risk=no]  Add module  color to expired/expiration modules to table

- api/src/main/java/org/pmiops/workbench/access/AccessUtils.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbAccessModule.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/default-server-config.ts
> [risk=low][RW-7828] Add requiredForRTAccess and requiredForCTAccess to AccessModuleConfig

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
> [risk=low][RW-7863] Fix contact email UX in AdminUserProfile

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
- api/db-cdr/generate-cdr/build-cb-criteria-observation.sh
update to the has_attribute flag in CDR indices
> [no ticket][risk=no] update to the has_attribute flag in CDR indices

- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Description:
Added tests / comments for 
- validateDataSetCreateRequest
- generateCode (for Python and R)
- markDirty
- getDataSetByResourceId
---
> [RW-7776][risk=no] Test Coverage: DataSetController

- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
https://user-images.githubusercontent.com/34481816/153620737-87ec143e-ef3b-4155-9f9d-6df0c616b7bc.mov
---
> [RW-7766][risk=no] Add Data Access link to the hamburger menu

- api/db/changelog/db.changelog-188-controlled-tier-training-expirable.xml
- api/db/changelog/db.changelog-master.xml
> [risk=low][RW-7827] Set expirable to TRUE for CT Training

- api/config/config_test.json
> [noTicket][risk=no]Switch off enableDSCREntryInRecentModified flag on test to pass the test

- ui/src/app/pages/admin/admin-user-profile.tsx
As requested by Shimon
Tested locally by enabling/disabling a test user
---
> [risk=no][RW-7683] <i>No data access</i> when tier array is empty

- api/db-cdr/generate-cdr/import-cdr-indices-build-to-cloudsql.sh
- api/db-cdr/generate-cdr/import-cdr-indices-to-cloudsql.sh
- api/db/run-migrations.sh
- api/libproject/cloudsqlproxycontext.rb
- api/libproject/devstart.rb
- api/libproject/environments.rb
- api/libproject/mysql_docker.rb
Reverts all-of-us/workbench#6317
> Revert "[RW-7822][risk=no] Update local dev tools to use mysql8 test instance"

- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
Description:
Added test cases for CohortsController for different WorkspaceAccessLevel cases
- createCohort
- duplicateCohort
- updateCohort
- deleteCohort
---
> [risk=no][RW-7563] Add missing cohort access tests

- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Allow reusing workspaces in case re-running nightly tests.
> [no ticket][risk=no] Small update in e2e nightly tests

- ui/src/app/components/html-viewer.spec.tsx
- ui/src/app/components/html-viewer.tsx
> [risk=no][RW-7896] simple test for MS_WORD_PARAGRAPH_CLASS

- ui/src/app/pages/admin/admin-user-common.tsx
> [risk=no][RW-7863] Align tier columns for AdminUserProfile

- ui/src/app/pages/data/cohort-review/cohort-definition.component.tsx
General cleanup and refactoring of `CohortDefinition` component used on the Cohort Description page.
---
> [RW-7829][risk=no] Cleanup cohort definition component

- ui/src/app/pages/workspace/create-billing-account-modal.tsx
- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-7769][risk=no] Workspace Edit page text update

- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
> [RW-7954][risk=no] Copy Edit feedback in Create Workspace page

- ui/src/app/pages/homepage/quick-tour-modal.tsx
> [RW-7881][risk=no] Update Quick Tour

- ui/src/app/pages/homepage/data-access-requirements.tsx
> [RW-7880][risk=no] Copy Edit Feedback in Data Access page

- ui/src/app/pages/admin/admin-institution.tsx
- ui/src/app/utils/index.tsx
Institutions can have very long user instructions fields.  We attempt to display the whole field in the Inst Admin table, which can cause poor formatting and overflow.  Let's truncate the field after a certain length: experimentation led me to 300 chars.
Before
After
---
> [risk=no][no ticket?] Don't overflow the inst admin table when user instructions are too long

- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.tsx
Build on the work from https://github.com/all-of-us/workbench/pull/6365
Description:
---
> [risk=low][RW-7691][RW-7598] Better handling of missing access modules

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- Fixes issue where the user is unable to enter 0 in the number input
- Show exact values for min/max ranges instead of converting to ints
---
> [RW-7948][risk=no] Fix value and min/max display for attributes number inputs

- api/db-cdr/generate-cdr/libproject/devstart.rb
The upstream dataset names are often pretty adhoc.
> [RW-7771][risk=no] Support specifying an alternate dest dataset name for WGS publishing

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
Applies an optional joint calling filter. We are likely to need this in production (awaiting confirmation).
Tested: locally
> [RW-7984][risk=low] Pass a filter set name for genomic extraction

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
adding distinct to person query
> [no ticket][risk=no] adding distinct to person query

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-device.sh
- api/db-cdr/generate-cdr/build-cb-criteria-drug.sh
- api/db-cdr/generate-cdr/build-cb-criteria-fitbit.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-clin.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-labs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-meas-snomed.sh
- api/db-cdr/generate-cdr/build-cb-criteria-observation.sh
- api/db-cdr/generate-cdr/build-cb-criteria-pm-cs.sh
- api/db-cdr/generate-cdr/build-cb-criteria-pm.sh
- api/db-cdr/generate-cdr/build-cb-criteria-snomed-condition.sh
- api/db-cdr/generate-cdr/build-cb-criteria-snomed-procedure.sh
- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
- api/db-cdr/generate-cdr/build-cb-criteria-visit.sh
- api/db-cdr/generate-cdr/build-cb-criteria-wgs.sh
- api/db-cdr/generate-cdr/cb-criteria-utils.sh
Reverts all-of-us/workbench#6382
> [RW-7932][risk-low] reverting changes

- api/config/cdr_config_prod.json
- api/config/cdr_config_stable.json
- api/libproject/environments.rb
Follow-up PRs will add:
1. Biguery CDRs to both
2. Genomics data to both
> [RW-7963][RW-7964][risk=low] Add CT access tiers in stable/prod

- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspaceOperation.java
Strange that this passed in the PR but it didn't pass post-merge.
Make H2 agree with Liquibase (nullable) - note however that Spring always populates these anyway.
Description:
---
> [risk=no][RW-7973] fix api test

- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/utils/subscribable.spec.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
> [risk=low][RW-7973] UI for Async Create Workspace

- e2e/app/page/workspace-edit-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/tests/workspace/workspace-create.spec.ts
> [risk=no][RW-7973] e2e update: wait 3 min for create/duplicate workspace

- ui/src/app/pages/data/data-set/dataset-page.tsx
> [RW-7968][risk=no] Fix spacing on dataset page

- e2e/utils/test-utils.ts
> [no ticket][risk=no] fix e2e test-utils function

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/testing/stubs/workspaces-api-stub.ts
Tested locally.  Duplication took just over a minute - which would have failed in synchronous mode.
Followup to #6375 #6387 #6389
---
> [risk=low][RW-7973] Async Duplicate Workspace

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
Description:
- added request logging in a try-catch for DeadlineExceededException
---
> [RW-7408][risk=no] Log request for HardDeadlineExceededError - use DeadlineExceededException

- deploy/libproject/deploy.rb
I added this flag to the wrong deploy command. Unfortunately this codepath is very difficult to test locally due to how the deployed version gets pulled into docker.
> [risk=no] Fix --allow_empty_tiers placement..

- e2e/app/page/admin/user-profile-admin-page.ts
- e2e/tests/nightly/admin/user-profile-admin.spec.ts
> [risk=no][RW-7863] Update e2e test text matching for #6402

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
We may need to wait longer than 1 minute for calls to Create and Duplicate Workspace
---
> [risk=low][RW-7973] bump Firecloud timeout to 180 in all environments

- ui/src/app/pages/admin/admin-user-profile.tsx
> [RW-7863] [risk=no] Admin User Profile page add institution detail link

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
> [risk=low][RW-7973][RW-8006] Log the API Async Create/Duplicate Workspace calls to help debug issues

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/testing/stubs/workspaces-api-stub.ts
> [risk=no][RW-7973] A few more UI tests for async

- ci/Dockerfile.circle_build
- deploy/Dockerfile
- deploy/bootstrap-docker.sh
- deploy/docker-compose.yaml
No rush on verifying this. Works for me on dry run (not M1)
> [RW-7989][risk=no] Use custom Dockerfile for deploys, hopefully fix on M1

- ui/package.json
- ui/yarn.lock
> [risk=low][no ticket] rev some UI patch-versions

- ui/src/app/pages/data/data-set/genomic-extraction-modal.tsx
- ui/src/app/utils/zendesk.ts
> [RW-7604][risk=no] Emphasize cost warning on genomic extraction modal

- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
> [risk=low][RW-7973] Set enableAsyncWorkspaceOperations to true in Stable, Preprod, Prod

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.spec.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/testing/react-test-helpers.tsx
- ui/src/testing/stubs/institution-api-stub.ts
- ui/src/testing/stubs/user-admin-api-stub.ts
> [risk=low][RW-7982] Add some UI unit tests for AdminProfile

- e2e/tests/nightly/admin/user-profile-admin.spec.ts
> [risk=no][no ticket] Add expected user state comments to user-profile-admin.spec.ts

- ui/src/app/pages/admin/admin-user-profile.spec.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
> [RW-7714 ][risk=no] Remove the old AdminUser page

- api/config/cdr_config_prod.json
- api/config/cdr_config_stable.json
I will also include this change in my stable/prod config push PRs.
> [RW-8024][risk=no] Fix CT stable/prod tier perimeter names

- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/admin/admin-user-profile.spec.tsx
- ui/src/app/pages/admin/admin-user-profile.tsx
- ui/src/app/pages/workspace/create-billing-account-modal.spec.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Note: does not test the toggles.  I haven't figured out how to do that.
---
> [risk=low][RW-7982] More unit tests for AdminUserProfile

- api/config/cdr_config_stable.json
- api/config/config_stable.json
- Make CT visible
- Add synthetic CT CDR
> [RW-7967][risk=low] Stable: "launch" CT synthetic CDR

- api/docs/developer-system-initialization.md
- api/docs/developer-system-requirements.md
* Add envsubst
* remove appengineRun
Description:
---
> [risk=no][no ticket] Update developer readmes

- e2e/app/component/card/workspace-card.ts
- e2e/app/element/select.ts
- e2e/app/modal/share-modal.ts
- e2e/app/modal/unavailable-tier-modal.ts
- e2e/app/page/data-access-requirements-page.ts
- e2e/app/text-labels.ts
- e2e/tests/controlled-tier/ct-workspace-share.spec.ts
> [RW-8015][risk=no] new e2e Controlled Tier workspace test

- api/config/cdr_config_prod.json
- api/config/cdr_config_stable.json
- api/config/config_prod.json
~~**DO NOT MERGE** ahead of launch day.~~
> [RW-8016][risk=moderate] Prod: enable CT access and add initial CT CDR

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
Bumping RT/CT indices for test/staging/stable
synth_r_2019q4_30 - CT(includes wgs and array)
synth_r_2019q4_31 - RT(no wgs and array)
> [no ticket][risk=no] bumping RT/CT indices for test/staging/stable

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
Bump test/staging/stable/perf (includes new vocabularies and full text index fix)
synth_r_2019q4_32 - registered
synth_r_2019q4_33 - controlled
> [no ticket][risk=no] bump test/staging/stable/perf

- e2e/app/sidebar/genomic-extractions-sidebar.ts
- e2e/app/sidebar/runtime-panel.ts
- e2e/tests/nightly/admin/user-profile-admin.spec.ts
- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
- e2e/utils/waits-utils.ts
> [RW-8059][RW-8058][risk=no] Fix e2e nightly tests

- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
changing label from "Has Occurrences" to "Number of occurrence dates"
> [RW-7642][risk=no] changing label from "Has Occurrences" to "Number of occurrence dates"

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
updating queries to reflect proper counts for domain cards
> [RW-8062][risk=no] updating queries to reflect proper counts for domain cards

- api/build.gradle
Bumping Swagger2 causes compile errors.
---
> [risk=low][no ticket] bump swagger 3 version

- e2e/.env.circleci.local
- e2e/.env.circleci.test
Description:
`puppeteer-tester-5` has encountered issue with too many groups.
---
> [no ticket][risk=no] New puppeteer test user puppeteer-tester-6

- api/db/changelog/db.changelog-193-institution-add-request-access-link.xml
- api/db/changelog/db.changelog-193-institution-add-request-access-url.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbInstitution.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/InstitutionDaoTest.java
- ui/src/app/pages/admin/admin-institution-edit.tsx
- ui/src/app/pages/admin/admin-institution.tsx
Description: 
Updated the admin edit institution page to include a field to specify a custom request access URL.
I am unsure if we want different label and placeholder values. Do we want to add URL validation?
https://user-images.githubusercontent.com/24514630/158604337-ba90e787-a83a-476e-9521-6a674e5a3225.mov
---
> [RW-7860][risk=no] Add Custom Access URL to Admin Edit Page

- api/build.gradle
- api/db-cdr/build.gradle
- api/db/build.gradle
Addresses a vulnerability in Liquibase 3.  Tested locally with no problems.
---
> [risk=low][RW-8034] Bump liquibase-core to 4.9.0

- ui/src/app/pages/admin/admin-institution-edit.tsx
Description: Fixed how request access url validation works.
https://user-images.githubusercontent.com/24514630/159014326-6df28fca-8e35-4b66-b5f9-4d043da3d415.mov
---
> [RW-8069][risk=no] Fixed how validation works for request access urls.

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
updating survey_module with name from concept table
> [no ticket][risk=no] updating survey_module with name from concept table

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
adding name back to survey module insert, it's a required field
> [no ticket][risk=no] adding name back to survey module insert, it's a required field

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
bumping test, staging, stable and perf CDR indices
> [no ticket][risk=no] bumping test, staging, stable and perf CDR indices

- ui/src/app/pages/data/concept/concept-homepage.tsx
- ui/src/testing/stubs/cohort-builder-service-stub.ts
Description:
- calling new API method `cohortBuilderApi().findConceptCounts(namespace, id, currentInputString)` a single call to get concept counts for all EHR Domains, physical_measurement_css, and all_surveys.  This replaces 13-parallel calls (5-Ehr domains, physical_measurement_ccs, and 7-survey calls)
---
> [RW-8066][risk=no] UI - update Concept Set search component to call new API method

- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/homepage/data-access-requirements.spec.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
To access the new Annual Renewal mode of Data Access Requirements (DAR), set the environment flag `mergedAccessRenewal` and access the DAR page using this query param: `/data-access-requirements?pageMode=ANNUAL_RENEWAL`.
Please also confirm that the DAR page in standard mode (INITIAL_REGISTRATION) has not changed - except for the styling of "Please complete the necessary requirements" which I can revert if you prefer.
(does not **complete** 7796 - the individual access module cars have not yet been updated)
---
> [risk=no][RW-7796] Add an ANNUAL_RENEWAL mode to DAR

- e2e/yarn.lock
Same change as #6484 but for e2e
---
> [risk=low][no ticket] bump minimist and dependants (e2e version)

- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/access/access-renewal.spec.tsx
- ui/src/app/pages/access/access-renewal.tsx
- ui/src/app/pages/admin/admin-user-common.tsx
- ui/src/app/pages/homepage/data-access-requirements.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
> [risk=low][no ticket] Make moduleName mandatory and clean up a bit of the UI access module code

- api/db-cdr/build.gradle
- api/db/build.gradle
Description: Added rootDir to classPath for Liquibase. I was encountering errors without it set.
`Caused by: liquibase.exception.ChangeLogParseException: The file changelog/db.changelog-masterB.xml was not found in
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/legacy8ujsse.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/localedata.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar
- /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib …
> [no ticket][risk=no] Added rootDir to classPath for Liquibase.

- e2e/README.md
> [risk=no][RW-6132] rm test-local-devup from e2e readme

- api/db-cdr/generate-cdr/build-prep-survey.sh
Adding validation for sdoh/minute surveys into CDR indices build
If sdoh and minute survey concepts don't exist in the concept table then exit the script gracefully.
> [RW-8040][risk=no] Adding validation for sdoh/minute surveys into CDR indices build

- .github/PULL_REQUEST_TEMPLATE.md
I have some proposals for updating the list of things we should check when making PRs.
We don't need to necessary follow every point for every PR (some won't apply) but I want requesters and reviewers to consider each of them before we merge changes.
> [risk=no][no ticket] Proposed updates to the PR checklist

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
See https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-aou/CHANGELOG.md for details.
> [RW-8074][risk=low] Bump AoU notebooks image to 2.0.13

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
Description:
- Updated SQLs for findDomainCounts and findDomainCountsByCode to work for both standard (is_standard=1) and source (is_standard=0) domains
- to test search for Z00 (cohort --> conditions --> toggle Show results as source concepts (ICD9, ICD10) -> should show 13 results for test env
---
* AoU UI
> [RW-8087][risk=no] Fix fulltext index for findDomainCountsByCode and findDomainCounts

- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Description:
e2e night test `genomic-extraction-to-vcf.spec.ts` failed on 3/28/2022. However, the genomics extraction job did succeed. After look thru test logs, It seems the extraction job had finished sometimes during the final 10 seconds sleep.
Test ran fine on my localhost since the genomics extraction job finished under 50 minutes.
Fix test by increase the max wait time.
* AoU UI
> [RW-8108][risk=no] Make test wait longer

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
bumping synth RT in test/staging/stable/perf
> [no ticket][risk=no] bumping synth RT in test/staging/stable/perf

- api/db-cdr/generate-cdr/build-prep-survey.sh
Reverts all-of-us/workbench#6511
Need more thought...
> Revert "[RW-7959][risk=no] Pull survey answers from concept_synonym"

- e2e/app/page/workspace-about-page.ts
- e2e/app/page/workspace-data-page.ts
- e2e/app/page/workspaces-page.ts
- e2e/tests/notebook/notebook-create-python.spec.ts
- e2e/tests/notebook/notebook-writer-actions.spec.ts
- e2e/tests/notebook/notebook-writer-clone-workspace.spec.ts
Description:
Enable test to add back test coverage. But the test takes >10 min to run and create new workspaces in every run. I broke up the test into two smaller tests and refactored test code. New tests each takes <5 min to run and only create new workspaces when running for the first time on daily basis.
* AoU UI
> [RW-7854][risk=no] Enable notebook-writer-actions test

- e2e/tests/notebook/notebook-create-python.spec.ts
Broken by this change: https://github.com/all-of-us/workbench/pull/6514/files#diff-6d2d6bb7a3b19d113eb9983baa68e7a67c93f262b0e9efe6cca9ba62519c95ceL70
> [risk=no] Fix Python e2e notebooks test

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- e2e/resources/workbench-config.ts
QA plan: https://docs.google.com/document/d/1UHWv0LpO4rN9MaH3jMqKi1AB_-GJ1Hopxu1is6Q_Ffg/edit
> [RW-7582][risk=low] Launch persistent disks in all environments

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
Description:
- updated cdr indexing build and bumping RT and CT CDR versions for test/stable/staging/perf
- Changes inculde [RW-8017](https://precisionmedicineinitiative.atlassian.net/browse/RW-8017), and [RW-8060](https://precisionmedicineinitiative.atlassian.net/browse/RW-8060)
---
* AoU UI
> [no-ticket][risk=no] Bumping RT and CT CDR with changes to index builds

- api/db-cdr/generate-cdr/build-cb-criteria-full-text-synonym.sh
> [no ticket][risk=no] adding synonyms for PM

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/resources/emails/welcomeemail/content.html
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
- ui/src/app/pages/homepage/data-access-requirements.tsx
Update Sign Code of Conduct on DAR page
Email:
- Update Sign of Conduct case
-  Remove flex from bullet
---
> [RW-8020][risk=no] Improve Updated Welcome email

- ui/src/app/pages/admin/admin-user-profile.tsx
Description:
Added margin to institutional role description field to align it with the other fields.
Alternatives considered:
Considered adding an additional blank flex item so the elements would align, but it seems like a large amount of the elements on this page have fixed widths. Decided against this option for now, because it would involve a decent restructuring of the page.
---
* AoU UI
> [RW-7856][risk=no] Updated position of institutional role description field.

- api/db-cdr/generate-cdr/create-tables.sh
Description:
- fix- create `ds_procedure_occurrence` table from either `ds_procedure_occurrence.json` (v5.3.1) or `ds_procedure_occurrence_52.json` (v5.2)
---
* AoU UI
> [no-ticket][risk=no] fix ds_procedure_occurrence table creation from appropriate schema json

- e2e/yarn.lock
- ui/yarn.lock
Addresses a vulnerability: https://app.snyk.io/org/all-of-us-researcher-workbench/project/402296f3-3f30-4f07-ba1f-5b533c986665
---
* AoU UI
> [risk=low][no ticket] Bump moment in ui and e2e

- api/config/cdr_config_test.json
Description:
- modified `/api/config/cdr_config_test.json` for testing index build after schema changes to be OMOP 5.3.1 compliant
---
* AoU UI
> [no-ticket][risk=no] Test new CDR index build for OMOP 531 and OMOP 52 in test environment.

- e2e/app/component/base-menu.ts
- e2e/app/component/card/workspace-card.ts
- e2e/app/component/navigation.ts
- e2e/app/component/select-menu.ts
- e2e/app/container.ts
- e2e/app/element/base-element.ts
- e2e/app/modal/share-modal.ts
- e2e/app/page/admin-institution-edit-page.ts
- e2e/app/page/authenticated-page.ts
- e2e/app/page/notebook-cell.ts
- e2e/app/page/notebook-page.ts
- e2e/app/sidebar/base-sidebar.ts
- e2e/app/sidebar/genomic-extractions-sidebar.ts
- e2e/app/sidebar/runtime-panel.ts
- e2e/tests/ui/cohort-ui.spec.ts
- e2e/tests/ui/dataset-ui.spec.ts
- e2e/utils/element-utils.ts
- e2e/utils/runtime-utils.ts
- e2e/utils/test-utils.ts
Description: Belated follow-up PR that addresses the feedback in [RW-8015][risk=no] new e2e Controlled Tier workspace test (PR #6426).
Turn this (verbose) code
```
> +      .waitForXPath(noSearchResultsXpath, { visible: true, timeout: 100 })
+      .then(() => {
+        return false;
+      })
+      .catch(() => {
+        return true;
+      });
```
to this (simpler) code
`.waitForXPath(noSearchResultsXpath, { visible: true, timeout: 100 }).then(() => false).catch(() => true)
`
Created a new common util function to avoid code duplication.
```
export async function exists(page: Page, xpath: string, opt: { timeout?: number } = {}): Promise<boolean> {
const { timeout = 100 } = opt;
return page
.waitForXPath(xpath, { visible: true, timeout })
.then(() => false)
.catch(() => true);
}
``` …
> [no ticket][risk=no] e2e simplify code that returns boolean 

- e2e/app/component/table.ts
- e2e/app/page/admin/user-profile-admin-page.ts
- e2e/app/page/notebook-page.ts
- e2e/app/sidebar/genomic-extractions-sidebar.ts
- e2e/app/sidebar/runtime-panel.ts
- e2e/tests/nightly/admin/user-profile-admin.spec.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Checking for whether the genomic extraction job has finished was relying on existences of Success icon in Genomic Extraction History table. But, if job has failed, test just waits until test timed out because test code only look for the Success icon.
* AoU UI
> [no ticket][risk=no] Fix e2e genomic-extraction-to-vcf test: Update waitForComplete function

- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
> [risk=low][RW-7834] set enableTOSRedirectForLoggedInUser to true in all environments

- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
updating gender identity names
> [RW-8178][risk=no] updating gender identity names

- api/db-cdr/generate-cdr/bq-schemas/ds_device.json
- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
Description:
- Add Device to Concept Sets and Dataset Builder:
---
* AoU UI
> [RW-8133][risk=no] Add ds_device to concept sets and dataset builder (ds-linking)

- api/config/cdr_config_test.json
Description:
- new cdr for test env with ds-device (OMOP 531)
---
* AoU UI
> [no-ticket][risk=no] OMOP 531-new cdr that includes ds_device

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
> [no ticket][risk=no] fixing devices

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
fixing device query efficiency
> [no ticket][risk=no] fixing device query efficiency

- ui/yarn.lock
Addresses a vulnerability: https://github.com/all-of-us/workbench/security/dependabot/25
https://github.com/caolan/async/pull/1828
Ran local UI against Test with no problems.
---
* AoU UI
> [risk=low][no ticket] rev async to 2.6.4

- api/db-cdr/generate-cdr/build-cb-survey-version.sh
updating script to account for Cope Minute Survey Versions
> [RW-8186][risk=no] updating script to account for Cope Minute Survey Versions

- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
> [no ticket][risk=no] fixing script for gender

- api/db-cdr/generate-cdr/test-data/load-test-survey-data.py
Script to pull data for SDOH and Minutes surveys that has been provided by Curation.
> [RW-8101][risk=no] script to pull data for SDOH and Minutes surveys

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
add cleanup when survey has no data
> [no ticket][risk=no] add cleanup when survey has no data

- api/config/cdr_config_test.json
> [no ticket][risk=no] bumping cdr in test

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_test.json
Reverts all-of-us/workbench#6527
> [risk=no][no ticket] Revert "Switch local/test/perf VMs to us-central1-c"

- api/db-cdr/generate-cdr/build-prep-survey.sh
- api/db-cdr/generate-cdr/test-data/load-test-survey-data.py
skipping date questions since all de-identified data has text data removed
> [no ticket][risk=no] skipping date questions

- api/db-cdr/changelog-data/db.changelog-1.xml
> [no ticket][risk=no] adding local device data

- ui/src/app/routing/guards.tsx
Does not revert all of #6569 - we retain the renaming/refactoring.
Description:
---
* AoU UI
> [risk=low][RW-8203] revert the redirect part of #6569

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/cohort-search/cohort-criteria-menu.spec.tsx
- ui/src/app/cohort-search/cohort-criteria-menu.tsx
- ui/src/app/cohort-search/cohort-page/cohort-page.component.spec.tsx
- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.spec.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
- ui/src/app/pages/data/concept/concept-search.spec.tsx
- ui/src/app/pages/data/criteria-search.tsx
- ui/src/testing/stubs/cohort-builder-service-stub.ts
New criteria menu component, behind `enableUniversalSearch` config flag. 
(Add `!` in front of the config flag [here](https://github.com/all-of-us/workbench/blob/dolbeew/RW-2497/ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx#L333) to test the new menu UI)
---
* AoU UI
> [RW-2497][RW-2498][risk=no] Create new criteria menu with searchbar

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
No functional changes. Updates some outdated comments in ProfileController and renames a method. I started doing this when investigating RW-8159. Ultimately it seems our code here is fine.
> [RW-8159][risk=no] Clean up profile / registration comments

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
fix search results where duplicate survey questions exist
> [no ticket][risk=no] fix search results where duplicate survey questions exist

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
Fixes the request to fetch the attributes for the COVID-19 Vaccine Survey questions and answers.
---
* AoU UI
> [RW-8201][risk=no] Update survey tree to load minute survey attributes

- api/config/cdr_config_test.json
> [no ticket][risk=no] bumping v2 test cdr

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_test.json
Reverts all-of-us/workbench#6580
> "[risk=no] Re-revert "Switch local/test/perf VMs to us-central1-c""

- e2e/app/page/create-account-page.ts
- ui/src/app/components/terms-of-service.spec.tsx
- ui/src/app/components/terms-of-service.tsx
- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/routing/app-routing.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Removed the UI Environment Flag `enableTOSRedirectForLoggedInUser` because it’s true in all environments.
Renamed `pages/login/account-creation/account-creation-tos` to `components/terms-of-service`.
---
* AoU UI
> [risk=no][RW-8173] ToS UI cleanup

- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurvey.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
- api/src/main/java/org/pmiops/workbench/profile/DemographicSurveyMapper.java
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
While doing some refactoring in this area, noticed this atrocity in DbDemographicSurvey and had to stop and fix it.
Also remove an unused `DbDemographicsSurvey` constructor.
> [risk=no] Fix Java variable casing style

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/db/model/DbAddress.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCohort.java
- api/src/main/java/org/pmiops/workbench/db/model/DbConceptSet.java
- api/src/main/java/org/pmiops/workbench/db/model/DbConceptSetConceptId.java
- api/src/main/java/org/pmiops/workbench/db/model/DbConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/DbDatasetValue.java
- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurvey.java
- api/src/main/java/org/pmiops/workbench/db/model/DbPageVisit.java
- api/src/main/java/org/pmiops/workbench/db/model/DbRdrExport.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStatusAlert.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserCodeOfConductAgreement.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentResource.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentWorkspace.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserRecentlyModifiedResource.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWgsExtractCromwellSubmission.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspaceFreeTierUsage.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportEnums.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
~~Stacked on https://github.com/all-of-us/workbench/pull/6615~~
- Stop manually naming RDR models `Rdr`, instead use the OpenAPI codegen prefix feature to avoid naming conflicts
- Move `DbUser` -> `RdrResearcher` conversion mostly into `RdrMapper`
- Clean up `RdrExportServiceImplTest`
- Add missing `RdrMapperTest` coverage
- Eliminate `*` imports
> [RW-7996][RW-6880][risk=no] Refactor RDR export/tests for quality of life

- ui/src/app/components/admin/audit-card-list-view.tsx
- ui/src/app/pages/admin/admin-institution.spec.tsx
- ui/src/app/pages/admin/admin-notebook-view.tsx
- ui/src/app/pages/admin/user/admin-user-profile.tsx
- ui/src/app/pages/admin/user/admin-user-table.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/workspace/workspace-about.spec.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
Update some instances of `a href` to `StyledRouterLink`
Tested each of these by comparing Local->Test and Test behavior.
---
* AoU UI
> [risk=no][no ticket] Convert a few anchor-links to StyledRouterLink

- api/src/main/java/org/pmiops/workbench/db/model/DbDemographicSurvey.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java
- api/src/main/resources/rdr.yaml
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteFromRdrExport.java
Add accessTierShortNames per requested RDR field name (noted that this is slightly inconsistent with naming in the Workspace)
> [RW-7996][risk=no] Export researcher access tiers to the RDR

- ui/src/app/components/icons.tsx
- ui/src/app/pages/admin/user/admin-user-table.tsx
Merge **Status** and **User Lockout** into **Enabled**
Remove **Audit**
---
* AoU UI
> [risk=low][RW-7922][RW-7923] UserAdminTable: rm Status, User Lockout, Audit; add Enabled

- e2e/resources/python-code/batch.py
- e2e/tests/nightly/batch.spec.ts
> [RW-8043][risk=no] Add batch job e2e test coverage

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
**Do not merge:** until Leo cache updates are in place: https://github.com/DataBiosphere/leonardo/pull/2638.
See: https://github.com/DataBiosphere/terra-docker/pull/313
- Install python package for gcloud alpha storage support
- Install R SAIGE
- Install/enable igv-jupyter extension
> [RW-8167][RW-8150][RW-8112][risk=no] Bump AoU notebook image

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Reverts all-of-us/workbench#6608
> Revert "[RW-8167][RW-8150][RW-8112][risk=no] Bump AoU notebook image"

- ui/package.json
- ui/yarn.lock
Force version 3.1.7 or higher to address https://github.com/all-of-us/workbench/security/dependabot/28
Ran local UI
---
* AoU UI
> [risk=low][no ticket] Update ejs to address vulnerability

- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
> [risk=low][no ticket] Flip ToS test because Terra stopped enforcement

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/ParticipantCohortStatusMapper.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/mapper/ParticipantCohortStatusMapperTest.java
Description:
This solution removes the warnings and allows us to use multi key. 
---
* AoU UI
> [no ticket][risk=no] fix unchecked call warning

- ui/src/app/pages/profile/data-user-code-of-conduct.tsx
No changes - strictly an extraction of the Content page and Signature page
This is a small step toward RW-8126 and RW-8296: I wanted to keep this large-appearing change separate from others to avoid confusion.
---
* AoU UI
> [risk=low][RW-8126][RW-8296] Functional decomposition of DUCC UI

- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/cdrselector/WorkspaceResourcesServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
No changes expected.
---
* AoU UI
> [risk=low][RW-7873] simplify WorkspaceResourceMapper

- e2e/tests/nightly/admin/user-admin-ui.spec.ts
- e2e/tests/nightly/admin/user-profile-admin.spec.ts
disabled this test since they are failing due to product change and the test cases may have to be updated
---
* AoU UI
> [no risk] [RW-8301]Disable user-admin & user-profile test case

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
- api/db-cdr/generate-cdr/build-cb-survey-version.sh
merge duplicated cope questions into Minute Survey
> [RW-8220][risk=no] merge duplicated cope questions into Minute Survey

- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/changelog-schema/db.changelog-v2-7-maria_db_index.xml
fixing maria db full text index problem
> [no ticket][risk=no] fixing maria db full text index problem

- api/build.gradle
Address this vulnerability: 
https://app.snyk.io/org/all-of-us-researcher-workbench/project/bf2628cc-574b-4c92-a236-237ad192de46
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-2807808
Tested by running a Local->Local with no issues
---
* AoU UI
> [risk=low][no ticket] rev some google packages to address a vulnerability

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/auth/UserAuthentication.java
- api/src/main/java/org/pmiops/workbench/auth/UserInfoService.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/user/DevUserRegistrationService.java
- api/src/main/java/org/pmiops/workbench/user/DevUserRegistrationServiceImpl.java
- api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
- api/src/test/java/org/pmiops/workbench/user/DevUserRegistrationServiceTest.java
Rename all Userinfoplus references to Userinfo to match the new API
Description:
---
* AoU UI
> [risk=low][RW-8324] rev google-api-services-oauth2

- ui/src/app/cohort-search/attributes-page/attributes-page.component.spec.tsx
- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/components/html-viewer.spec.tsx
- ui/src/app/components/html-viewer.tsx
- ui/src/app/pages/analysis/confirm-playground-mode-modal.tsx
- ui/src/app/pages/analysis/notebook-in-use-modal.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/app/pages/workspace/create-billing-account-modal.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
- ui/src/app/pages/workspace/workspace-share.tsx
No expected UI changes.
---
* AoU UI
> [risk=low][no ticket] rename or remove exported 'Props' and 'State' to avoid confusion

- api/src/main/webapp/static/initialize_notebook_runtime.sh
Tested locally per https://cs.github.com/all-of-us/workbench/blob/db760dd3e504fbe6b33bc7335c4458ce510deaab/api/src/main/webapp/static/README.md?q=static+readme#L4 ; able to launch both a nextflow and cromwell workflow.
> [RW-7952][risk=no] Write workflow config files on runtime initialization

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
fix for survey universal search results
> [no ticket][risk=no] fix for survey universal search results

- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Follow up on #6628 by deleting the deprecated structures.  ~DO NOT MERGE until #6628 is released~ READY.
Tested by running Local->Local and observing that AdminUserTable and the bypass toggles work as expected.
---
* AoU UI
> [risk=low][RW-4838][RW-7917] Delete unused access module code

- ui/src/app/cohort-search/cohort-criteria-menu.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
Description:
UI: Update CB temporal menus for universal search
Updated to use new CohortCriteriaMenu - added isTemporalFlag, filtered PPI if temporal
1. ADD CRITERIA:
2. Universal search results for `blood pressure`: Show both **Program Data** items and **Domain** items
3. After searching and selecting domain-concept and toggling **Temporal**
4. ADD CRITERIA dropdown shows **Universal Search** and **Domain** items. **Program Data** items are filtered
5. When **Temporal** is toggled to **ON** Universal Search results for `blood pressure` show only **Domain** results ( **Program Data** items are filtered) compare with `step 2` above
---
* AoU UI …
> [RW-8234][risk=no] Update UI for Universal Search - temporal toggle

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
bumping CT test/staging/stable/perf cdr
> [no ticket][risk=no] bumping CT test/staging/stable/perf cdr

- api/src/main/java/org/pmiops/workbench/db/dao/CohortReviewDao.java
> [no ticket][risk=no] remove unused dao methods

- api/config/cdr_config_local.json
- api/config/cdr_config_perf.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_prod.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
- api/db/changelog/db.changelog-195-add-filter-set-name.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
Part 1/2 (part 2 will remove the old config property)
- Move the filter set onto the CDR version config, deprecate the setting on the main config. This value will need to diverge for different CDR versions
- Also archives and decommissions v5 alpha in preprod; it is currently broken
> [RW-8265][risk=no] mv WGS filter set from config -> CDR config

- ui/src/app/utils/stores.tsx
> [risk=no] Reduce chattiness on genomic extraction store SWR

- ui/src/app/routing/signed-in-app-routing.tsx
Description:
Broken in #6635. Routing does not take into account query parameters. Fixed DAR/AR title logic.
---
* AoU UI
> [RW-8239][risk=no] Consolidated DAR and AAR pages Added logic to show appropriate title between DAR and Annual Renewal.

- .circleci/config.yml
- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java
- e2e/.env.circleci.local
- e2e/.env.circleci.perf
- e2e/.env.circleci.staging
- e2e/.env.circleci.test
Modify `project.rb set-access-module-timestamps` cmd to accommodate RAS test user.
New cmd e.g.
`./project.rb set-access-module-timestamps --profile-user "puppet-access-tester-1@fake-research-aou.org" --ras-user "puppeteer-tester-3@fake-research-aou.org"`
Cmd modifies following:
- For `profile-user`, reset PROFILE module `completion_time` timestamp to a fixed value.
- For `ras-user`, set RAS module `completion_time` timestamp to null.
---
* AoU UI
> [risk=no][RW-7234] Set RAS module timestamp in DB to null for RAS test user

- e2e/app/component/notification.ts
- e2e/app/element/staticText.ts
- e2e/app/page/access-renewal-mode.ts
- e2e/tests/nightly/user-access.spec.ts
Update the condition to check for expired / not expired
---
* AoU UI
> [risk=low][RW-8239] Fix nightly access renewal test

- ui/src/app/pages/data/cohort-review/cohort-review-list-item.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/cohort-review.tsx
- ui/src/app/routing/workspace-app-routing.tsx
Add `!` before the feature flag in [cohort-review.tsx line 78](https://github.com/all-of-us/workbench/blob/dolbeew/RW-7939/ui/src/app/pages/data/cohort-review/cohort-review.tsx#L78) to test the new UI.
Note:
- The `+` button to add new reviews is not functional yet
- The participants table has no sorting or filtering yet
> [RW-7939][risk=no] Create new UI component for multiple cohort reviews

- ui/src/app/pages/admin/user/admin-user-table.tsx
What I was attempting to do at #6696 
No expected UI changes.
---
* AoU UI
> [risk=low][no ticket] AdminUserTable column refactoring

- ui/src/app/cohort-search/attributes-page/attributes-page.component.tsx
- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/demographics/demographics.component.tsx
- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/overview/overview.component.tsx
- ui/src/app/cohort-search/search-bar/search-bar.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
- ui/src/app/cohort-search/tree-node/tree-node.component.tsx
- ui/src/app/utils/analytics.ts
- Remove all calls to `triggerEvent` and use `AnalyticsTracker` functions instead
- Redefine values tracked in events to be consistent
---
* AoU UI
> [RW-8170][risk=no] Refactor Cohort Builder analytics tracking

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
CDR indexing build:
updating family history survey answer names
> [no ticket][risk=no] updating family history survey answer names

- api/config/cdr_config_prod.json
Description:
Promoting RT/CT preprod cdr. Adding @calbach  as reviewer since he is the release engineer for the week of 5/23. Please be sure to run the publish commands below from the /api directory in workbench before releasing to prod:
I have updated the [CDR Build Log](https://docs.google.com/document/d/1WZvkrIaaVWFM6KD742DbEwwbK03OC_RtOreCMXFU6xQ/edit) for 5/23
RT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset R2021Q3R5 --tier registered --table-prefixes cb_,ds_
CT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset C2021Q3R6 --tier controlled --table-prefixes cb_,ds_
---
* AoU UI
* [Researcher …
> [no ticket][risk=no] Promoting RT/CT prod cdr

- deploy/libproject/jirarelease.rb
> [risk=no] Change deploy release ticket type from task -> release

- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/libproject/devstart.rb
cdr indices fix for data browser
> [no ticket][risk=no] cdr indices fix for data browser

- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
See Jira ticket for investigation details.
> [RW-8607][risk=no] Try hacky workaround to genomic extract VPC-SC errors

- ui/package.json
- ui/yarn.lock
Resolves https://github.com/all-of-us/workbench/security/dependabot/29
No obvious concerns running Local->Test
---
* AoU UI
> [risk=low][no ticket] force eventsource to non-vulnerable 2.0.2

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
Description:
- Updated createCohortReview with logic for enableMultiReview Flag
---
* AoU UI
> [RW-8368][risk=no] multiple cohort review-create cohort review new impl

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/RdrExportDao.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/InvalidateRdrExport.java
See attached ticket for details.
> [RW-8417][risk=no] Exclude SA users from RDR export

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Description:
Choose the SA name as the contact email. 
---
* AoU UI
> [RW-8432][risk=low] Set contact email when creating user for service account

- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
- Added message and updated layout for empty list
- Using the same modal for creating new reviews when `+` icon is clicked
- Now able to create multiple reviews with `enableMultiReview` config set to `true`
---
* AoU UI
> [RW-8377][risk=no] Add create function and modal for adding multiple reviews

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
- api/db-cdr/generate-cdr/build-prep-survey.sh
> [no ticket][risk=no] fixing family history survey

- api/config/cdr_config_preprod.json
@jmthibault79 adding you as reviewer for awareness of out of band publish of CDR to preprod since you are the release engineer this week. Data Apps team will be taking care of this.
> [RW-8439][risk=no] bumping preprod indices

- api/config/cdr_config_local.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_test.json
- api/db/changelog/db.changelog-197-add-genomic-cdr-paths.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/notebooks/LeonardoNotebooksClientImpl.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/tools/cdrconfig/CdrConfigVOMapperTest.java
Additions:
- WGS_CRAM_MANIFEST_PATH
- MICROARRAY_VCF_MANIFEST_PATH
- MICROARRAY_IDAT_MANIFEST_PATH
Removals:
- SINGLE_SAMPLE_ARRAY_BUCKET
- ALL_SAMPLES_WGS_BUCKET
> [RW-8271][risk=no] Update genomic data env vars

- api/build.gradle
May resolve https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-2807808 and https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-2841508
Tested locally with no issues.
---
* AoU UI
> [risk=low][no ticket] Update bouncycastle and google packages to address vulnerabilities

- ui/package.json
- ui/src/app/cohort-search/tree-node/tree-node.component.spec.tsx
- ui/src/app/components/notification-banner.spec.tsx
- ui/src/app/components/terms-of-service.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/sign-in.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/leo-runtime-initializer.spec.tsx
- ui/src/testing/react-test-helpers.tsx
- ui/yarn.lock
React-scripts 5 (#6753) brings stricter typechecking to our UI unit tests, so we need to make some updates.  This PR covers only those test updates, for easier review separate from the upgrade itself.
Description:
---
* AoU UI
> [risk=low][RW-7729] Test fixes to comply with improved typechecking in react-scripts v5

- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/side-nav.tsx
- ui/src/app/pages/signed-in/inactivity-monitor.tsx
- ui/src/app/utils/authentication.tsx
- ui/src/app/utils/navigation.tsx
Description:
PD ticket: https://precisionmedicineinitiative.atlassian.net/browse/PD-7542
Pending on Gsuite admin granting user security scope to workbench api 
---
* AoU UI
> [RW-8445][risk=low] Add signout endpoint that sign out user RW gsuite account

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
> [RW-8466][risk=low] Set GCS bucket location as us-central1 

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench-api.yaml
Add endpoint to get cohort count from cohortId
---
* AoU UI
> [no ticket][risk=no] Add endpoint to get cohort count from cohortId

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/create-cohort-review-modal.tsx
- ui/src/app/pages/data/cohort-review/create-review-modal.tsx
Description:
Added name property to the review and updated both UI (Will Dolbeer) and api.
---
* AoU UI
> [RW-8303][risk=no] Multiple Cohort Reviews - add name property to review

- e2e/jest.config.js
- e2e/libs/jest-reporter.js
- e2e/package.json
> [risk=no][no ticket]Allow verbosity to be adjusted via environment variable

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
> [RW-8404][risk=low] remove legacy billing id

- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
I make a few small tweaks related to RDR backfill/testing while I was working on the Demo Survey V2 RDR export.  This PR has those tweaks independent of Demo Survey work.
---
* AoU UI
> [risk=low][no ticket] A few small updates to #6751

- api/build.gradle
- api/db-cdr/build.gradle
- api/db/build.gradle
The latest Liquibase update https://github.com/liquibase/liquibase/pull/2871 made it possible to remove their logspam.
```
> Task :update
liquibase-plugin: Running the 'main' activity...
####################################################
####################################################
```
Tested by running migrations and dev-up, and confirming that Local->Local works as expected.
---
* AoU UI
> [risk=no][no ticket] rm liquibase spam

- api/docs/developer-system-requirements.md
Caused by https://github.com/all-of-us/workbench/pull/6753 which caused the release bug https://github.com/all-of-us/workbench/pull/6784
Description:
---
* AoU UI
> [risk=no][no ticket] Bump required node version in developer-system-requirements.md

- api/config/config_local.json
- api/config/config_test.json
Export Demo Survey V2 to RDR in the Local/Test environments.  We have approval from RDR to start sending them data now.
Tested by running the export cron locally without errors - still need to check with RDR if the data was received OK.
---
* AoU UI
> [risk=low][RW-8355] Enable exportDemoSurveyV2 on Local and Test

- api/config/cdr_config_prod.json
Adds new entries for the June CDR refresh to `cdr_config_prod.json`
---
* AoU UI
> [RW-8359][risk=no] Add config entries for new prod CDR versions

- api/config/featured_workspaces_prod.json
Update `featured_workspaces_prod.json` to add and remove featured workspaces for the June CDR refresh.
Based on the list here: https://precisionmedicineinitiative.atlassian.net/browse/RW-8521
> [RW-8521][risk=no] Update config for featured workspaces

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [RW-8293][RW-8167][RW-8150][risk=low] Bump AoU notebook image to latest in all envs

- .circleci/config.yml
- api/build.gradle
- ci/Dockerfile.circle_build
- deploy/Dockerfile
321.0.0 had issues if you install Python 3.10 locally.
> [risk=no] Update to latest gcloud version

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
Remove special characters from criteria table: ’ or …
and replace with ' and ...
---
* AoU UI
> [RW-8557][risk=no] remove special characters

- ui/src/app/pages/data/cohort-review/cohort-review-overview.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/participants-charts.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
> [RW-7942][risk=no] Add overview section to cohort review

- api/config/cdr_config_preprod.json
- api/config/cdr_config_prod.json
> [no ticket][risk=no] bumping cdr for preprod/prod

- ui/src/app/pages/data/data-set/dataset-page.tsx
Converts the `DatasetPage` component from a class to a function component that uses React hooks
---
* AoU UI
> [RW-7167][risk=no] Convert DatasetPage component to React hooks

- ui/src/app/components/demographic-survey-v2.tsx
- ui/src/app/components/inputs.tsx
- ui/src/app/components/multiple-choice-question.tsx
- ui/src/app/pages/admin/admin-lock-request.tsx
- ui/src/app/pages/data/concept/concept-search.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/workspace/workspace-research-summary.tsx
Description:
Adjusted spacing between yes/no/prefer not to answer questions from 1rem to 0.3rem.
Set line height for questions to 1.25rem.
Changed question 15 field from input to text area.
---
* AoU UI
> [risk=low][RW-8565] Adjusted demographic survey UI

- ui/src/app/pages/admin/admin-workspace.tsx
> [risk=low][RW-8573] Add Access Tier to Workspace Admin

- api/config/cdr_config_preprod.json
- api/config/cdr_config_prod.json
Description:
This update fixes the issue with getting correct column names for `zip_code_socioeconimic status` [RW-8575](https://precisionmedicineinitiative.atlassian.net/browse/RW-8575) 
- updated cdrDbName to point to new version for preprod and prod configs
- Note release manager to run the below publish commands for preprod and prod. Only `ds_` tables are changed. Run the below commands from the `workbench/api/` directory
@calbach (Release manager for the week of 7/11)
```
PREPROD:
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes ds_
PROD:
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes ds_
```
---
* AoU UI …
> [no ticket][risk=no] updated cdrDbName to point to new version

- api/src/main/java/org/pmiops/workbench/actionaudit/ActionAuditQueryServiceImpl.java
PROFILE changes include things like account disable, contact email change, etc.
> [RW-8485][risk=no] Include profile edits in user audit page

- .circleci/config.yml
No ticket. Test configuration change.
> [no-ticket][risk=no] Run new e2e tests only on PRs

- api/build.gradle
- api/tools/src/main/java/org/pmiops/workbench/tools/CommandLineToolApplicationRunListener.java
Wee are not vulnerable now, but we will be once we upgrade our version of Java: https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
---
* AoU UI
> [risk=low][RW-6894] Bump Spring Framework version to address future vulnerability

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/genomics/docs/wgs_cohort_extraction_setup.md
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
- Also drop support for GVS method versions < 3
> [RW-8422][RW-8421] Drop unused GVS extract config settings

- api/config/config_local.json
- api/config/config_test.json
Set`enableMultiReview` config flag to `true` in local and test environments
> [RW-7971][risk=no] Enable multiple reviews in local and test environments

- e2e/app/modal/cohort-review-modal.ts
- e2e/app/page/cohort-review-page.ts
- e2e/tests/cohorts/cohort-review.spec.ts
Update puppeteer tests after enabling multiple cohort review feature flag in test environment
---
* AoU UI
> [RW-8626][risk=no] e2e changes for multiple cohort review

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Set `enableUniversalSearch` config flag to `true` in all environments
> [RW-7971][risk=no] Enable universal search in all environments

- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
> [RW-8615][risk=no] Fix runtime error bar display on unknown Leo errors

- ui/src/app/components/take-demographic-survey-v2.tsx
- ui/src/app/pages/demographic-survey.tsx
- ui/src/app/pages/signed-in/signed-in.tsx
- ui/src/app/utils/authentication.tsx
- ui/src/app/utils/constants.tsx
https://user-images.githubusercontent.com/34481816/179061066-1b87933a-32d4-4121-9b70-d4b54be4e555.mov
Description:
---
* AoU UI
> [RW-8363][risk=low]   UI to nudge users to take the V2 Demo Survey - after 30 days

- ui/src/app/components/notification-banner.tsx
- ui/src/app/components/take-demographic-survey-v2.tsx
Before Deadline:
After deadline:
---
* AoU UI
> [RW-8644][risk=no]  Update Demographic Survey Banner Text

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
removing empty topics from surveys
> [no ticket][risk=no] removing empty topics from surveys

- e2e/tests/cohorts/cohort-review.spec.ts
Update the tests in `cohort-review.spec.ts` based on the env of the current run.
This could probably be done a little cleaner but will most likely be removed in the next couple release cycles, so didn't want to spend too much time on it.
---
* AoU UI
> [risk=no] Fix cohort review e2e test for staging runs

- ui/src/app/components/demographic-survey-v2.tsx
- ui/src/app/pages/profile/demographic-survey-panel.tsx
Description:
Updated wording on profile page:
Updated logic to clear other text when prefer not to answer is clicked:
https://user-images.githubusercontent.com/24514630/180016365-b3d45250-62d9-4cdf-8876-7c0bbcad0e58.mov
https://user-images.githubusercontent.com/24514630/180017730-e3395574-cba9-4f91-bbee-be17405878ed.mov
---
* AoU UI
> [RW-8654][risk=no] Polish Demographic Survey Flow

- ui/src/app/components/demographic-survey-v2.tsx
Use correct section name : Racial and Ethnic
Use orientation rather than identity for question 4
Remove extra space in question
---
* AoU UI
> [RW-8654][risk=no]   Polish Demographic Survey Flow

- ui/src/app/components/app-router.tsx
- ui/src/app/components/buttons.tsx
> [risk=low][RW-8654] Switch Link to RouteLink, which can be disabled

- ui/src/app/components/take-demographic-survey-v2.tsx
> [RW-8654][risk=low]   Polish Demographic Survey Flow - banner text

- ui/src/app/components/buttons.tsx
https://user-images.githubusercontent.com/34481816/180052690-08e8e6b4-63b0-49f4-82fc-833b2bcfb453.mov
---
* AoU UI
> [RW-8654][risk=no]  Polish Demographic Survey Flow - disable take the survey button on survey page

- api/config/config_preprod.json
- api/config/config_prod.json
set enableUpdatedDemographicSurvey and exportDemoSurveyV2 to true in all environments
Description:
---
* AoU UI
> [risk=low][RW-8364] Launch Demo Survey V2

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
- api/libproject/environments.rb
> [RW-8624][risk=no] Fix issues in genomics extraction script to make it work with test env

- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/app/utils/index.tsx
Fixes issue where editing an item on an existing cohort causes an error because the criteria id is not set.
> [risk=no] Fix issue when editing saved cohort

- api/config/featured_workspaces_preprod.json
Description:
- updated config
- published preprod workspace
---
* AoU UI
> [RW-8656][risk=no] publish new preprod workspace

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/main/java/org/pmiops/workbench/utils/ResponseCodeRetryPolicy.java
> [RW-8585][risk=low] Retry 504 error when makes firecloud calls

- api/config/featured_workspaces_prod.json
Description:
- Demo project already published to prod.
- Config changes to go out with release
-    {
"name": "Data Quality Reports - June 2022 CDR Release",
"namespace": "aou-rw-410a6b71",
"id": "dataqualityreportsjune2022cdrrelease",
"category": "DEMO_PROJECTS"
}
---
* AoU UI
> [RW-8583][risk=no] publish new 2022 CDR reposts demo project

- ui/src/app/cohort-search/list-search/list-search.component.tsx
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
Remove all code no longer needed after enabling `enableUniversalSearch` config flag
> [RW-8676][risk=no] Remove unused code after universal search

- api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
> [no ticket][risk=no] fixing indices build

- api/build.gradle
Tested locally, no problems observed
---
* AoU UI
> [risk=low][no ticket] Rev Google packages to latest

- ui/package.json
- ui/src/app/pages/admin/admin-workspace.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/yarn.lock
> [risk=low][no ticket] Bump types/lodash to latest and refactor a few `cond()`

- ui/src/app/components/demographic-survey-v2-validation-message.tsx
- ui/src/app/components/demographic-survey-v2.tsx
- ui/src/app/utils/constants.tsx
Screen shot existing using disability 
Updated : use difficulty  rather than Disability 
---
* AoU UI
> [RW-8654][risk=no]  Polish Demographic Survey Flow - Add question number to error message

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingBatchUpdateService.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/billing/WorkspaceFreeTierUsageService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceFreeTierUsageDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/utils/CostComparisonUtils.java
- api/src/main/resources/application.properties
- api/src/main/webapp/WEB-INF/cron_test.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
> [RW-6280][risk=low] fix and optimize free tier cron

- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
because DB still has old workspaces
Description:
---
* AoU UI
> [risk=no][RW-6280] Add billing migration status to the DB query 

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Description:
Prerequired steps are done 
https://github.com/DataBiosphere/terra-docker/pull/340
https://github.com/DataBiosphere/leonardo/pull/2770
---
* AoU UI
> [RW-8720][risk=low] Upgrade AoU jupyter docker image

- ui/src/app/routing/app-routing.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-utils.tsx
> [RW-8297][risk=no]  [P3] ToS reaccept and disabled user page are shown simulatenously

- api/config/cdr_config_prod.json
bumping prod cdr. @dolbeew Please run the following publish commands for RT/CT in prod:
RT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset R2022Q2R2 --tier registered --table-prefixes cb_
CT
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes cb_
> [no ticket][risk=no] bumping prod cdr

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchTerm.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/SearchTermTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
Description:
- add endsWith search functionality to survey 
- refactor new class SearchTerm to encapsulate search term text processing
- also includes RW-8672 - fix CohortBuilderControllerTest for enableDrugWildcardSearch functionality - aka endsWith functionality
---
* AoU UI
> [RW-8668][risk=no] full text search add end with to survey

- api/config/config_local.json
- api/config/config_test.json
Description:
-- updated FeatureFlag: enableDrugWildcardSearch to activate "endsWith" search functionality in test and prod
---
* AoU UI
> [RW-8729][risk=no] enable drug wildcard search in test/local configs

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
Clean-up v2 of the search
---
* AoU UI
> [no ticket][risk=no] Clean-up v2 of the search

- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
No functional changes expected.
Tested locally by making some workspace modifications.
---
* AoU UI
> [risk=no][RW-8705] BillingMigrationStatus: comments, removal, and deprecations

- ui/src/app/pages/analysis/runtime-panel.spec.tsx
- ui/src/app/pages/analysis/runtime-panel.tsx
- ui/src/app/utils/machines.ts
- ui/src/app/utils/runtime-presets.ts
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/stubs/runtime-api-stub.ts
> [RW-8655][RISK=NO]Increase Dataproc Master Node minimum disk size

- api/config/featured_workspaces_prod.json
Adds [Data Wrangling in All of Us Program (v6)](https://workbench.researchallofus.org/workspaces/aou-rw-00d29a75/datawranglinginallofusprogramv6/data) to the Tutorial workspaces category
Tagging @freemabd for review as the releaser next week
> [RW-8713][risk=no] Add new featured workspace entry to prod config

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CriteriaParameters.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
Add toggle to remove drug brands from search results
---
* AoU UI
> [RW-8620][risk=no] Add toggle to remove drug brands from search results

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
removing universal search flag
> [RW-7972][risk=no] removing universal search flag

- ui/src/app/components/demographic-survey-v2.tsx
Screenshot from Jira: 
Issues:  was logging in to test something and found one typo and one character display problem. (See screenshot.) "Trainee" is misspelled in Q13 and " " is inserted into Q14.
Fixed:
---
* AoU UI
> [RW-8768][risk=no]   Typo on Workbench Demographic Survey [P3]

- ui/src/app/pages/workspace/workspace-share.tsx
Tested by sharing/unsharing a CT workspace on Local->Test without problems.
---
* AoU UI
> [risk=no][RW-8470] rm unnecessary WorkflowRolesErrorModal and workflowRolesErrorText

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CustomCBCriteriaDaoImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
fixing drug auto complete for search 2.0
---
* AoU UI
> [RW-8801][risk=no] fixing drug auto complete

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/BigQueryService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/chart/ChartServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapper.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapper.java
- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/ParticipantCohortStatusMapper.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortbuilder/mapper/CohortBuilderMapperTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapperTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/mapper/ParticipantCohortStatusMapperTest.java
Refactor BigQueryService
---
* AoU UI
> [RW-8748][risk=no] cleanup BigQueryService

- api/src/main/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapper.java
> [no ticket][risk=no] cleanup CohortReviewMapper

- ui/src/app/components/combo-chart.component.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-list-item.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-overview.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/participants-charts.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- Use new api calls to show charts for only participants in the selected review
- Link each review item to cohort description page that displays data from the cohort snapshot from that review
https://user-images.githubusercontent.com/40036095/189421381-27441b4e-907d-406d-a5d7-7dc1d26dfe05.mov
---
* AoU UI
> [RW-8742][risk=no] Use new api calls for review items, link to cohort description

- api/config/cdr_config_prod.json
> [risk=no][RW-8531] Update CDR config to use the new manifest instead of the single sample path

- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
Fixes issue where new cohort reviews were added to the bottom of the list instead of the top.
> [RW-8847][risk=no] Fix cohort review list order on review create

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- ui/src/app/cohort-search/list-search/list-search.component.tsx
Changing search API call to post to reduce number of args. Tagging @dolbeew to look at the UI code change.
---
* AoU UI
> [RW-8749][risk=no] Changing search API call to post to reduce number of args

- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchTerm.java
I'm assuming that this was not supposed to be committed, so removing it.
> [no ticket][risk=no] removing commented out code

- ui/src/app/cohort-search/modifier-page/modifier-page.component.spec.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
Convert ModifierPage from class component to React hooks
---
* AoU UI
> [RW-8835][risk=no] Convert ModifierPage to React hooks

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
flipping enableDrugWildcardSearch feature flag
> [RW-8865][risk=no] flipping enableDrugWildcardSearch feature flag

- ui/src/app/cohort-search/list-search/list-search.component.tsx
Add clear icon to text input in cohort builder search
https://user-images.githubusercontent.com/40036095/190675382-acd5b193-b547-49eb-b328-d0d4c4059fac.mov
---
* AoU UI
> [RW-8859][risk=no] Add clear option to cohort builder search

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
> [no ticket][risk=no] fixing sql for broken test

- ui/src/app/cohort-search/list-search/list-search.component.tsx
> [no ticket][risk=no] fixing surveyName

- api/config/config_preprod.json
- api/config/config_prod.json
flipping flag for prod/preprod
> [no ticket][risk=no] flipping flag for prod/preprod

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
- api/config/cdr_config_test.json
bumping test/staging/stable/perf cdrs to use survey submenu
> [no ticket][risk=no] bumping test/staging/stable/perf cdrs to use survey submenu

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
Description:
---
- cleaned up service calls
---
* AoU UI
> [RW-8866][risk=no] Cleanup old service calls on CohortBuilderService

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
turn on multi review in staging, stable, perf, preprod and prod
> [RW-8910][risk=no] turn on multi review in staging, stable, perf, preprod and prod

- ui/src/app/utils/index.tsx
Check the length of the entire quoted string instead of each word within the quotes.
https://user-images.githubusercontent.com/40036095/191787488-07e281ac-03fe-4885-9021-0d078cea1bfd.mov
---
* AoU UI
> [RW-8900][risk=no] Fix full text validation for quoted strings

- e2e/tests/cohorts/cohort-review.spec.ts
Fix for the `cohort-review.spec.ts` e2e test for the staging deploy after enabling the multi review config flag in staging env.
---
* AoU UI
> [DT-53][risk=no] Update cohort review test after config flag change

- api/db-cdr/generate-cdr/stage-redcap-files.py
add new redcap files and fix new bug
> [RW-8908][risk=no] add new redcap files and fix new bug

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
Description:
---
- Applied security check for CohortReviewController#getCohortReviewsByCohortId 
---
* AoU UI
> [DT-11][risk=no] Applied security check for call getCohortReviewsByCohortId

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
Description:
---
- updated security for `CohortReviewController#findCohortReviewDemoChartInfo`
---
* AoU UI
> [DT-12][risk=no] Security Vulnerability - validate that review exist in workspace

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
Description:
---
- Removed feature flag enableDrugWildcardSearch from
- API
- Config files for all environments
---
* AoU UI
> [DT-16][risk=no] Remove Feature Flag enableDrugWildcardSearch 

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDaoCustom.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDaoImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCohortReview.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebookLockingUtils.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DiskControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/CdrVersionServiceTest.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebookLockingUtilsTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceAuthServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
Some refactorings based on some ideas I had when looking at #6923 - as well as other small unrelated changes
---
* AoU UI
> [risk=low][no ticket] Some refactoring mainly related to last-modified-by

- api/config/cdr_config_preprod.json
Update entries in `cdr_config_preprod.json` for the new survey menu
@tarekmamdouh Tagging you for review as the releaser for next week (10/3) per the [Release Playbook](https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#bookmark=id.5y2wpcggk65g). 
You'll need to run the following commands after deploying the app to preprod during next week's release:
```
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset R2022Q2R2 --tier registered --table-prefixes cb_
```
```
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-preprod --bq-dataset C2022Q2R2 --tier controlled --table-prefixes cb_
```
---
* AoU UI
* [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/A …
> [DT-25][risk=no] Update preprod config with new cdr versions

- ui/src/app/pages/data/cohort-review/create-cohort-review-modal.tsx
Add error handling to `createCohortReview` call to prevent users being stuck with an infinite spinner after a failure.
---
* AoU UI
> [DT-67][risk=no] Add error handling to cohort review modal

- api/config/cdr_config_prod.json
Update entries in `cdr_config_prod.json` for the new survey menu
@chenchals Tagging you for review as the releaser for week of 10/10 per the [Release Playbook](https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#bookmark=id.5y2wpcggk65g).
Will also need to run publish commands after deploying to prod([DT-68](https://precisionmedicineinitiative.atlassian.net/browse/DT-68))
**I'll be out next week so please merge this after the release for week of 10/3 is complete**
> [DT-26][risk=no] Update prod config with new cdr versions

- api/src/main/webapp/WEB-INF/cron_test.yaml
> [noticket][risk=no]Decrease frequency of free tier cron on test to once a day

- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/cohortreview/CohortReviewServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- ui/src/app/pages/data/cohort-review/cohort-review-page.tsx
- ui/src/app/pages/data/cohort-review/cohort-review-participants-table.tsx
- ui/src/app/pages/data/cohort-review/detail-header.component.tsx
- ui/src/app/pages/data/cohort-review/detail-page.tsx
- ui/src/app/pages/data/cohort-review/query-report.component.tsx
- ui/src/testing/stubs/cohort-review-service-stub.ts
Description:
---
- Removed unused APIs
- Removed unnecessary parameters for API call
- Removed UI code referring to old APIs
- Updated tests to use new APIs
---
* AoU UI
> [DT-33][risk=no] Multiple Cohort Review - cleanup any unused API calls

- api/build.gradle
See https://app.snyk.io/org/all-of-us-researcher-workbench/project/bf2628cc-574b-4c92-a236-237ad192de46
Tested locallly.
---
* AoU UI
> [risk=low][no ticket] Address a vulnerability by updating API packages

- api/build.gradle
> [no ticket][risk=no] Remove google client deprecated class

- api/config/config_staging.json
- e2e/resources/workbench-config.ts
Description:
AoU is updating hostname: [https://all-of-us-rw-staging.appspot.com`](https://all-of-us-rw-staging.appspot.com%60/)
to new host name: staging.fake-research-aou.org
---
* AoU UI
> [RW-8919][risk=no] Update AoU staging hostname

- api/build.gradle
#6944 broke Test.  We did not detect it pre-deploy because the error apparently only affects real App Engine environments, rather than dev-up.
Looks fine locally (dev-up) but I'm not sure how much that tells us :)
---
* AoU UI
> [risk=no][RW-8981] Downgrade logback to fix the Test env

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/testing/default-server-config.ts
> [RW-8635][risk=no]: Add feature flag for enabling CUSTOM APP creation. Set to false for all envs

- api/db-cdr/generate-cdr/bq-schemas/cb_search_all_events.json
- api/db-cdr/generate-cdr/build-search-all-events.sh
adding new columns to cb_search_all_events
> [DT-69][risk=no] adding new columns to cb_search_all_events

- api/db-cdr/generate-cdr/build-search-all-events.sh
fixing SQL problem with indexing build
> [no ticket][risk=no] fixing SQL problem with indexing build

- e2e/app/component/card/data-resource-card.ts
- e2e/app/component/data-table.ts
- e2e/tests/cohorts/cohort-create.spec.ts
Cohort review test were failing as the test created more than 10 cohorts. Now that we have pagination for table showing all the resources within workspaces, the required Cohort did not appear on the page as it was on the next page
To solve this issue, the better and more precise way could be to use the search name box on the data table, to narrow down the search so that we can be sure the row will exist and it will be easier to find the resource
Description:
---
* AoU UI
> [RW-8983][risk=no]  [e2eTestFailure] Cohort Review

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [RW-9011][risk=low] Update Jupyter version in all envs

- ui/src/app/pages/workspace/workspace-wrapper.tsx
- also remove "en-us" from links
Description:
---
* AoU UI
> [risk=low][RW-8473] Add User Support Hub link to new CT WS notification

- ui/src/app/pages/homepage/quick-tour-and-videos.tsx
The user support video link was broken, this has been fixed now
https://user-images.githubusercontent.com/34481816/195641006-58dcc24d-c2ff-41b6-9857-66fedc7b7b51.mov
Description:
---
* AoU UI
> [RW-9024][risk=no] Update USH Video Link on RW [P2]

- api/config/cdr_config_test.json
> [DT-5][risk=no] adding new cloud cdr

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
> [no ticket][risk=no] fix family history survey

- e2e/app/sidebar/genomic-extractions-sidebar.ts
- e2e/app/sidebar/runtime-panel.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Description:
Fixes the broken test `genomic-extraction-to-vcf.spec.ts`. Passing locally.
---
* AoU UI
> [RW-8873][risk=no] Fix broken test: genomic-extraction-to-vcf.spec.ts

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/AppController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/config/FileConfigs.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiHelper.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoConfig.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
> [RW-8994][risk=low] Support createApp endpoints

- ui/src/app/components/system-error-handler.spec.tsx
- ui/src/app/components/system-error-handler.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/utils/errors.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/app/utils/retry.tsx
- ui/src/index.ts
Rename some structures that confused me.  These are intended to work with system-level errors, such as the API being down.  Note: **_I'm not sure these structures are actually used_**.
* globalErrorStore -> systemErrorStore
* withGlobalError -> withSystemError
* fetchWithGlobalErrorHandler -> fetchWithSystemErrorHandler
* ErrorHandler -> SystemErrorHandler
Description:
---
* AoU UI
> [risk=low][RW-8242] Rename ErrorHandler and globalEventStore to "system"

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
- api/db-cdr/generate-cdr/build-cb-survey-version.sh
> [no ticket][risk=no] fixing Cope Minute Survey

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
> [no ticket][risk=no] fixing vaccine survey

- api/db-cdr/generate-cdr/bq-schemas/cb_search_all_events.json
- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-search-all-events.sh
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_all_events.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
> [no ticket][risk=no] fix CATI concept

- ui/src/app/pages/admin/user/admin-user-bypass.tsx
No UI changes.  Tested locally by trying various bypassing configurations.
---
* AoU UI
> [risk=low][RW-8985] use updateAccountProperties() instead of bypassAccessRequirement()

- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/resources/workbench-api.yaml
- ui/src/testing/stubs/profile-api-stub.ts
- ui/src/testing/stubs/user-admin-api-stub.ts
After #7090 and a release, UserAdminController.bypassAccessRequirement() and  UserService.updateBypassTime() can be removed
- also remove (unrelated) deprecated anyModuleHasExpired
Tested locally by executing all the affected calls which aren't deleted here.
Description:
---
* AoU UI
> [risk=low][RW-8985] remove deprecated methods

- api/db-cdr/generate-cdr/build-ds-linking.sh
> [no ticket][risk=no] fixing dataset indexing

- api/config/featured_workspaces_test.json
Should help with testing Featured Workspaces.
These 3 have been created and Published by my test user `joel@fake`
---
* AoU UI
> [risk=no][RW-9092] Add 3 Featured Workspaces to Test (and remove an old one)

- api-proxy/handlers/|v1|google-account.post.mjs
- api-proxy/handlers/|v1|institutions|Broad|checkEmail.post.mjs
- api-proxy/handlers/|v1|institutions|publicDetails.get.mjs
- api-proxy/handlers/|v1|is-username-taken.get.mjs
- api-proxy/src/reqhandler.mjs
- e2ev2/src/test-utils.js
- e2ev2/tests/await-event.test.js
- e2ev2/tests/user-create.test.js
- ui/src/app/components/terms-of-service.tsx
- ui/src/app/pages/login/sign-in.tsx
This includes a test for the new demographics survey.
---
* AoU UI
> [RW-9089][risk:no] Test for new user account creation

- ui/src/app/cohort-search/constant.ts
- ui/src/app/cohort-search/modifier-page/modifier-page.component.spec.tsx
- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
Add new CATI modifier to surveys in cohort builder when the `hasSurveyConductData` property on the CDR is `true`
> [DT-81][risk=no] Add CATI  modifier to surveys in CB 

- e2ev2/README.md
- e2ev2/package.json
- e2ev2/src/circle-run-tests.sh
- e2ev2/src/config.js
- e2ev2/src/test-utils.js
- e2ev2/tests/user-create.test.js
- e2ev2/tests/workspace-create.test.js
- e2ev2/yarn.lock
- ui/shell.nix
- ui/src/app/components/confirm-delete-modal.tsx
- ui/src/app/components/demographic-survey-v2.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/terms-of-service.spec.tsx
- ui/src/app/components/terms-of-service.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/account-creation/account-creation-success.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/app/pages/login/login.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/workspace/workspace-actions-menu.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-list.tsx
Add `aria-label` and `id` attributes to UI elements as handles for CSS selectors in tests.
---
* AoU UI
> [RW-9090][risk=no] Add handles to UI to improve test reliability

- e2e/yarn.lock
- ui/yarn.lock
Address dependabot alerts for minimatch: https://github.com/all-of-us/workbench/security/dependabot
---
* AoU UI
> [risk=low][no ticket] rm vulnerable minimatches for ui and e2e

- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/utils/navigation.tsx
Split a 1273-line into 2 files (~730 and ~660) by extracting icon-related code from the help-sidebar component.
Some minor additional refactoring/cleanup.
No functional changes expected.  Local testing did not show any.  **This does not resolve RW-9006**.
---
* AoU UI
> [risk=low][RW-9006] Extract help-sidebar icons to new functional component

- api/db-cdr/generate-cdr/build-ds-tables.sh
adding new ds_survey inserts into the indexing build
> [DT-74][risk=no] adding new ds_survey inserts

- api/src/main/resources/workbench-api.yaml
adding new value to AttrName in workbench.yaml
> [DT-71][risk=no] adding new value to AttrName in workbench.yaml

- api/db-cdr/generate-cdr/bq-schemas/ds_sleep_daily_summary.json
- api/db-cdr/generate-cdr/bq-schemas/ds_sleep_level.json
- api/db-cdr/generate-cdr/build-ds-tables.sh
adding ds_ tables for fitbit sleep
> [DT-117][risk=no] adding ds_ tables for fitbit sleep

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
---
- Add sleep_level and sleep_daily_summary table info to ds_linking table
- Ran locally and checked that the relevant details are added to ds_linking table
---
* AoU UI
> [DT-113][risk:no] Add new sleep_level and sleep_daily_summary to ds_linking table

- api/db-cdr/generate-cdr/build-ds-tables.sh
> [no ticket][risk=no] fix-typo

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
---
- error in sequencing for Visit domain
---
* AoU UI
> [No-Ticket][risk:no] fixed existing sequencing error in ds_linking

- api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
fixing entries for fitbit sleep data
> [no ticket][risk=no] fixing entries for fitbit sleep data

- ui/src/app/utils/access-utils.tsx
Light search found only these two instances in the codebase.
---
* AoU UI
> [no-ticket][risk=no] Remove quote typos

- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/runtime-status-icon.tsx
We'll need this for the new apps panel.  Splitting into its own PR for ease of review.
---
* AoU UI
> [risk=low][RW-9006] Extract a runtime-status-icon component

- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
Description:
I still have this block because I am unsure if Terra will rollback this change again...
---
* AoU UI
> [no ticket][risk=no]: Mark ToS enabled to true in dev

- ui/src/app/utils/zendesk.ts
> [RW-8882][RW-8443] Fix broken billing and GPU zendesk links

- ui/yarn.lock
Addresses https://github.com/all-of-us/workbench/security/dependabot/37
---
* AoU UI
> [risk=low][no ticket] upgrade vulnerable loader-utils

- api/db-cdr/generate-cdr/libproject/devstart.rb
- api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
> [RW-8269][risk=no] Delta-based genomics manifest generation

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
adding new survey card for PFHH survey
> [DT-115][risk=no] adding new survey card for PFHH survey

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
> [no ticket][risk=no] fixing data dictionary

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
updating card count for PFHH survey
> [DT-110][risk=no] updating count for PFHH survey

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
fixing BQ project and dataset names
> [no ticket][risk=no] fixing BQ project and dataset names

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
fixing pfhh concept set counts
> [no ticket][risk=no] fixing pfhh concept set counts

- api/build.gradle
Tested by running a release deployment and dev-up.  No problems observed.
---
* AoU UI
> [risk=low][no ticket] Upgrade app engine plugin to 2.4.5

- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
Description:
Leo team suggests us not to use fixed name. So I make app name the same as PD name
---
* AoU UI
> [RW-9175][risk=no] Use random name for app name

- ui/src/app/pages/appAnalysis/apps-list.spec.tsx
- ui/src/app/pages/appAnalysis/apps-list.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/constants.tsx
Updated : 
https://user-images.githubusercontent.com/34481816/201180425-c98b6e52-3113-4d2e-ab77-48e9e027cba4.mov
Description:
---
* AoU UI
> [RW-8972][risk=no] [UI] [analysis tab] Create Jupyter Notebook from [new] Analysis tab pt 1

- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
> [risk=no][no ticket] fix typo: intializer -> initializer

- api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh
- api/db-cdr/generate-cdr/build-cb-criteria-snomed-procedure.sh
- api/db-cdr/generate-cdr/build-prep-loinc-rel.sh
- api/db-cdr/generate-cdr/build-prep-snomed-rel-meas.sh
- api/db-cdr/generate-cdr/build-prep-snomed-rel-pcs.sh
adding hierarchy levels to SNOMED Procedure. Please reference https://precisionmedicineinitiative.atlassian.net/browse/DT-132
> [DT-132][risk=no] adding hierarchy levels to SNOMED Procedure

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
removing FH and PMH survey cards
> [DT-109][risk=no] removing FH and PMH survey cards

- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/resources/workbench-api.yaml
adding new enum for long read WGS
> [DT-135][risk=no] adding new enum for long read WGS

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
updating counts for PFHH survey/questions/answers
> [DT-70][risk=no] updating counts for PFHH survey/questions/answers

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
> [no ticket][risk=no] fixing cast on indexing build

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
> [no ticket][risk=no] fixing alias on query

- ui/src/app/utils/zendesk.ts
> [no ticket][risk=no] Fix policy url in zendesk page

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
adding arg to allow 1000 rows to return in the query results
> [no ticket][risk=no] adding arg to allow 1000 rows to return in the query results

- api/config/featured_workspaces_prod.json
> [RW-9186][risk=no] Add featured workspace

- api/docs/developer-system-requirements.md
A few tweaks I noticed as I was setting up a new computer
---
* AoU UI
> [risk=no][no ticket] Updates to system requirements readme

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
updating pfhh survey question count
> [no ticket][risk=no] updating pfhh survey question count

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/libproject/devstart.rb
Description:
---
- Added new long read WGS to cb_search_person table
- Updated devstart.rb file
---
* AoU UI
> [DT-137][risk=no] Added new long read wgs flag to cb_search_person table

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
Description:
---
- Added long reag Whole genome sequence to cb criteria menu
---
* AoU UI
> [DT-134][risk=no]Added long read WGS to cb_criteria menu

- api/config/cdr_config_perf.json
- api/config/cdr_config_stable.json
- api/config/cdr_config_staging.json
updating config for staging/stable/perf
> [DT-94][risk=no] updating config for staging/stable/perf

- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
> [RW-9116][risk=no] update hail version

- e2e/app/page/cohort-participants-group.ts
- e2e/app/text-labels.ts
- e2e/tests/nightly/genomic-extraction-to-vcf.spec.ts
Update `genomic-extraction-to-vcf` test to handle updated WGS menu item
> [DT-148][risk=no] Update menu items for nightly genomics test

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_all_events_data.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
Update BQ SQL generation for PFHH survey
> [DT-72][risk=no] Update BQ SQL generation for PFHH survey

- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
> [no ticket][risk=no] fixing CS query 

- api/src/main/java/org/pmiops/workbench/exfiltration/ObjectNameLengthServiceImpl.java
Happened to see this while I was working on something else.
---
* AoU UI
> [risk=no][no ticket] Can remove some Optionals here

- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/tree/tree.component.tsx
- ui/src/app/pages/data/concept/concept-homepage.spec.tsx
- ui/src/app/pages/data/concept/concept-homepage.tsx
Revert temporary survey changes from #7128
> [DT-160][risk=no] Revert temporary survey filters

- api/db-cdr/generate-cdr/build-search-all-events.sh
Removing basics, overall health and lifestyle data when all participant questions have a null questionnaire response id
> [DT-161][risk=no] removing basics, overall health and lifestyle data

- api/config/config_test.json
Fix a mistake in #7219
---
* AoU UI
> [risk=low][RW-9269] Fix a test user email which caused NPE

- ui/yarn.lock
Resolves https://github.com/all-of-us/workbench/security/dependabot/40
---
* AoU UI
> [risk=low][no ticket] bump express to resolve qs vulnerability

- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
A bit of cleanup that I'm going to reuse for RW-9270.  Broken off into an easier-to-review piece here.
---
* AoU UI
> [risk=low][no ticket] move some WorkspaceServiceImpl logic to WorkspaceMapper

- api/libproject/devstart.rb
> [no ticket][risk=no] fixing typo in indexing build 

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-cb-survey-version.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
- api/db-cdr/generate-cdr/build-search-all-events.sh
- api/libproject/devstart.rb
Removing changes that will break June CDR, so we can rebuild for the hotfix
> [no ticket][risk=no] removing changes that will break June CDR

- api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
updating cope survey counts to not include the following question concepts:
1. 1310132
2. 1310137
> [no ticket][risk=no] updating cope survey counts

- api/db-cdr/generate-cdr/build-cb-criteria-missing-codes.sh
adding removal of source concepts listed as standard
> [DT-165][risk=no] adding removal of source concepts listed as standard

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/libproject/devstart.rb
Description:
---
- updated indexing jobs for `has_structural_variant_data` for `cb_search_person` table
- For testing indexing build  need to merge the 2PRs below:
- this PR  and
- PR for cdr-indices: [#69](https://github.com/all-of-us/cdr-indices/pull/69)
---
* AoU UI
> [DT-169][risk=no] Updated indexing job for structural_variant_data

- api/libproject/devstart.rb
Description:
---
- fixed comand line argument name for cdr-indexing build
---
* AoU UI
> [DT-169-2][risk=no] bug fix for command line argument name

- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedFirecloudService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedFirecloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
> [risk=low][RW-9270] Cron endpoint to delete test user workspaces

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
update survey module question count for cope survey
> [DT-166][risk=no] update survey module question count for cope survey

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
https://github.com/DataBiosphere/terra-docker/pull/383/files
https://github.com/DataBiosphere/leonardo/pull/3073/files
"risk=low" because security controls were not touched.
---
* AoU UI
> [RW-9296][risk=low] terra-jupyter-aou:2.1.15 everywhere

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
Description:
---
- updated scripts to populate cb_criteria_meu
- CDR-indexing build and publish will be done when the following PR approval
---
* AoU UI
> [DT-168][risk=no] updated cb_criteria menu for structural variant data

- ui/src/app/pages/data/data-set/dataset-page.tsx
Fix broken navigation for cohort description links in dataset builder
> [DT-162][risk=no] Fix url for cohort description in dataset builder

- api/db-cdr/generate-cdr/build-ds-tables.sh
Split out ds_survey generation per survey. This allows for more accurate counts.
> [DT-167][risk=no] Split out ds_survey generation per survey

- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
Description:
---
- update cohort search for 
- disable temporal for genomic domains
- do not launch domain search for `structural Variant Data` selection
---
* AoU UI
> [DT-176][risk=no] updated UI components

- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/search-group-item/search-group-item.component.tsx
- ui/src/app/cohort-search/utils.ts
> [DT-164][risk=no] Update line item display for short read WGS

- e2e/app/component/bypass-modules.ts
Description:
Updated test to account for new style of bypass button.
In order to test, run:
`yarn test-nightly tests/nightly/admin/user-admin-table.spec.ts`
---
* AoU UI
> [risk=no][RW-9322] Updated test to account for new bypass buttons.
