all-of-us/workbench

- api/db-cdr/generate-cdr/stage-redcap-files.py
Description:
---
- Removed Personal medical history and family health history processing
- Updated cdr-indexing build jobs [PR#64](https://github.com/all-of-us/cdr-indices/pull/64)
---
* AoU UI
> [DT-122][risk=no] Removed processing for personal medical history and family  health history

- ui/src/app/cohort-search/cohort-search/cohort-search.component.tsx
- ui/src/app/cohort-search/demographics/demographics.component.tsx
- Fixes issue where demographics lists in CB with more than 10 options start to overlap the parent container
- Add styles to force scrollbar to be visible when scrolling is necessary to see all options
Before:
https://user-images.githubusercontent.com/40036095/203242498-866ae0be-8c92-453e-8b37-f00d52c349b0.mov
After:
https://user-images.githubusercontent.com/40036095/203242551-e73e6080-fa01-4cd9-aefa-85a2a5976e10.mov
---
* AoU UI
> [DT-140][risk=no] Fix hidden/overlapping content in demographics lists

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
updating BQ SQL generator to include long read wgs data
---
* AoU UI
> [DT-138][risk=no] updating BQ SQL generator to include long read wgs data

- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebookUtils.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- ui/src/app/pages/admin/admin-notebook-view.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
After #7166 some endpoints now require full notebook names (including .ipynb) which broke some key RW features.
I *think* I have identified all such endpoints and have modified their calls from the RW UI to ensure that the full names are used.  Additionally I renamed some API parameters to be more explicit about this new requirement
TODO: API and UI tests
**But we need this hotfix ASAP so I am inclined to add those in another PR**
---
* AoU UI
> [risk=low][RW-9210] Use full notebook filenames

- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebookUtils.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/google/CloudStorageClientTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/MockNotebook.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/resources/UserRecentResourceServiceTest.java
Follow-up to #7166 and #7196
* add API tests to show new cases where notebook file extensions are required
* add some .rmd tests
* rename some API method params to be more explicit about requiring extensions
* remove a hard-coded with-jupyter extension which is no longer needed
* NotebookUtils.withNotebookPath()
* other small refactoring
---
* AoU UI
> [risk=low][no ticket] Notebooks API: add tests and refactor

- ui/src/app/components/multiple-choice-question.tsx
- ui/src/app/components/new-user-satisfaction-survey-modal.spec.tsx
- ui/src/app/components/new-user-satisfaction-survey-modal.tsx
- ui/src/app/components/surveys.tsx
- ui/src/app/services/swagger-fetch-clients.ts
- ui/src/app/utils/stores.tsx
- ui/src/testing/stubs/surveys-api-stub.ts
Description:
Adds a new component to display the new user satisfaction survey.
This is _not_ user facing, yet. Two future stories will show this to users via a clicked-on notification and through an email link.
A test for the full success flow will be added as a small integration test once this is user-facing.
Since this is my first bigger front-end story, I would appreciate any structural suggestions.
Screenshot:
Screenshot - Error:
---
* AoU UI
> [RW-9027][risk=no] Add new user satisfaction survey modal

- ui/src/app/components/rename-modal.tsx
- ui/src/app/pages/analysis/new-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/analysis/util.ts
- ui/src/app/pages/data/concept/concept-add-modal.tsx
- ui/src/app/pages/data/concept/concept-search.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/utils/resources.tsx
Added in #7160 and applicable in several areas.
Also allow users to type in the full notebook name for export-dataset if they wish; and a few small refactorings.
---
* AoU UI
> [risk=low][RW-5847] use getExistingNotebooks/Names everywhere

- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AdminAuthorityTest.java
Because #7095 has been released, we can now remove the endpoint.
---
* AoU UI
> [risk=no][no ticket] rm deprecated unsafeSelfBypassAccessRequirement

- ui/libproject/devstart.rb
The UI now has an extra build step after https://github.com/all-of-us/workbench/pull/7203 which breaks the release
To confirm that the fix works, run a dry-run deployment, **specifying this git branch**
```
deploy/project.rb deploy --project all-of-us-rw-stable \
--account deploy@all-of-us-rw-stable.iam.gserviceaccount.com \
--promote --dry_run --git-version joel/RW-9259
```
---
* AoU UI
> [risk=low][RW-9033][RW-9259] Fix release deployment

- api/config/config_local.json
- api/config/config_test.json
Updates the Jupyter image version. Image: https://github.com/DataBiosphere/terra-docker/pull/378
Update to Leo images: https://github.com/DataBiosphere/leonardo/pull/3070
---
* AoU UI
> [RW-9241][risk=low] Use new Jupyter image with long reads tools

- api-proxy/handlers/|v1|profile.get.mjs
- api-proxy/handlers/|v1|surveys|newUserSatisfactionSurvey.post.mjs
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyService.java
- api/src/main/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyServiceTest.java
- e2ev2/tests/new-user-satisfaction-survey.test.js
- ui/src/app/components/new-user-satisfaction-survey-banner-maybe.tsx
- ui/src/app/components/new-user-satisfaction-survey-modal.tsx
- ui/src/app/components/notification-banner.spec.tsx
- ui/src/app/components/notification-banner.tsx
- ui/src/app/components/take-demographic-survey-v2.tsx
- ui/src/app/pages/signed-in/access-renewal-notification.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
Description:
Adds a notification for the new user satisfaction survey.
This is the first user-facing satisfaction survey change. I will wait to merge this alongside the related [email story](https://precisionmedicineinitiative.atlassian.net/browse/RW-9029) so they release at the same time.
Demo video:
https://user-images.githubusercontent.com/31020403/206270652-f69fcf74-1bf7-41c3-b9c5-9bd20b0fc398.mov
---
* AoU UI
> [RW-9028][risk=no] Add notification for new user satisfaction survey

- ui/src/app/pages/data/concept/concept-homepage.tsx
Fixes issue on concept search homepage where the last search term remains in the search bar even after navigating away then returning.
---
* AoU UI
> [DT-13][risk=no] Clear input on return to concept homepage

- e2e/tests/conceptsets/conceptset-edit-rename.spec.ts
- ui/src/app/cohort-search/search-group-list/search-group-list.component.tsx
- ui/src/app/cohort-search/search-group/search-group.component.tsx
Separates the column index (`roleIndex`) from the overall group index (`groupIndex`) to prevent duplicate groups when renaming a group in the excludes column.
---
* AoU UI
> [DT-174][risk=no] Fix rename function for excludes groups

- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
The new deletion script from #7229 seems to be working well.  Let's remove all workspaces instead of just 5 per user.
---
* AoU UI
> [risk=low][RW-8425] Remove limit from test user workspace deletion cron

- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
The current version of `/v1/cron/deleteTestUserWorkspaces` will quit when it sees a 404 for a workspace that it intends to delete.  Because deleting many workspaces can take a long time, it's plausible that some workspaces will already be gone by the time it works through the list.
Now we catch `NotFoundException` and continue.
Tested locally by pausing local execution during a cron run and manually deleting one of the workspaces.  The cron run completed successfully, deleting the other workspaces.  
---
* AoU UI
* …
> [risk=low][RW-9270] Continue deleting workspaces if one is not found

- api/src/main/java/org/pmiops/workbench/access/AccessSyncService.java
- api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/access/AccessSyncServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
> refactor syncEraCommonsStatus into something that can be migrated

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Does not actually send emails - that is stubbed out until the email is ready.  This PR is safe to merge without it, so I'll follow up with a new PR at that time.
Submitted for early review because we have a quickly approaching deadline.
A better approach would be to check the user's actually-accepted Terra ToS version.  That would be a bit more involved, and may make sense as a next step:
* Sam has a new endpoint `termsOfServiceDetails`: https://github.com/broadinstitute/sam/pull/935
* Calling this using impersonation for every registered-tier user would give us the most authoritative list about who's compliant and who isn't
* Going forward we can use this endpoint in normal user flows to populate the AoU DB for the next time we'll need this information
This PR assumes we won't have time …
> [risk=no][RW-9324] Logic and endpoint for sending Terra-ToS email reminders

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUser.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
The use of "app" and "apps" in the API codebase does not always give enough context as to whether they refer to **system** apps (like the AoU app itself) or **user** apps, the new feature we're launching.  Add some clarifying text and rename some structures to show that they specifically refer to user apps
The main changes are
* WorkbenchConfig.App -> WorkbenchConfig.UserApps
* App -> UserAppEnvironment
This change is currently safe to make without worrying about the UI, because the UI does not yet use these structures.  Tested on Local->Local with no problems.
---
* AoU UI
* [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory- …
> [risk=no][no ticket] Rename some "apps" API entities to "user apps"

- api/build.gradle
We run this tool as part of the release process.  Previous versions are broken: https://github.com/jeremylong/DependencyCheck/issues/5224
Bumping to latest allows us to run the tool successfully.
Test by running this locally: `./gradlew dependencyCheckAnalyze`
`main` fails with:
```
> Task :dependencyCheckAnalyze
Verifying dependencies for project api
Checking for updates and analyzing dependencies for vulnerabilities
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569'
org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569'
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:156)
at …
```
> [risk=low][no ticket] Bump dependencycheck because previous versions are broken

- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/resources/workbench-api.yaml
> Minor copypaste fix

- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
Description:
Per Joel: 
> isGracePeriodEnabled = true now for all envs, so enforcement is off in all envs.  https://github.com/broadinstitute/firecloud-develop/commit/63a755787c0415d43512a1514d73447b19fcb5eb (e
---
* AoU UI
> [no ticket][risk=no] Turn off ToS enforcement to fix test

- ui/src/app/cohort-search/modifier-page/modifier-page.component.tsx
Switch from `JSON.parse(JSON.stringify(defaultFormState)` to `Object.assign({}, defaultFormState)` to prevent `undefined` values from converting to `null`.
> [DT-173][risk=no] Fix validation for age modifier

- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/routing/guards.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
- ui/src/testing/default-server-config.ts
Replace the use of the API/UI FF enableGkeApp in the UI with 2 new environment flags gating specific UI features:
* showAppsPanel for the Apps Panel
* showNewAnalysisTab for the new analysis tab
This will allow us to launch the Apps Panel for the Cromwell MVP without needing to also launch the new analysis tab.
Tested locally: both new flags work as expected, and they can be turned on and off independently.
---
* AoU UI
> [risk=low][RW-9007] Add 2 UI environment flags for Cromwell MVP

- api/db-cdr/generate-cdr/build-prep-survey.sh
- api/db-cdr/generate-cdr/create-tables.sh
Description:
---
Creating `prep-survey` takes significant amount of time and is unnecessary when running CDR indexing build multiple times for a giuve CDR, unless-survey-data- from curation changes or there is bug.
- updated cdr-indexing to skip building prep_survey table, if it exists in the dataset.
---
* AoU UI
> [DT-189][risk-no] Skip building prep_survey if one exists

- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/CloudTaskWorkspacesController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
Cron deleteTestUserWorkspaces was not able to complete in the 10-minute deadline, so hand off the work to a Task Queue endpoint.
It takes roughly 10 sec to delete a workspace, so the original endpoint is failing after ~ 60 workspace deletions.  This PR splits them into 15-workspace batches, for a healthy margin of error.
Wiki entry about Task Queues [here](https://github.com/all-of-us/workbench/wiki/Using-Task-Queues-when-endpoints-take-too-long-to-complete).
Tested locally, using our simulated Local queueing system.  Queue monitoring/alerting to follow.
---
* AoU UI
* [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-ex …
> [risk=low][RW-9323] Convert deleteTestUserWorkspaces to Task Queues

- ui/src/app/components/apps-panel.tsx
I'm still not 100% on why this makes a difference, but it does: because ActiveApps and AvailableApps were defined in the render function of AppsPanel, they would re-mount more often than necessary.  Inlining these components resolves that problem.
The best way to observe the effect here is via the Network tab in React Dev Tools, when the Apps Panel is experiencing a transition change for Jupyter (e.g. Pausing a Running runtime).
Before this change, there are repeated calls to check the runtime status (as expected) but also calls to check the disks and the list of notebooks (unexpected - these are called by subcomponents which should be be changing).
After this change, the only repeated calls are those to check the runtime status.
---
* AoU UI
* [Perf …
> [risk=no][RW-9007] inline the appspanel apps to avoid re-mounting

- api/db-cdr/generate-cdr/create-tables.sh
Description:
---
- CDR indices - For efficiency reason change the indexing build to pass over surveys if table already exists
- *Note* there is test code to check if CI bash has associative array feature enabled - Another PR will remove this test code
---
* AoU UI
> [DT-189-5][risk=no] CDR indexing - Speedup build - prep_survey 

- api/db-cdr/generate-cdr/build-prep-survey.sh
- api/db-cdr/generate-cdr/create-tables.sh
Description:
---
- CDR indices - For efficiency reason change the indexing build to pass over surveys if table already exists
- fix getting prepSurveyCounts 
---
* AoU UI
> [DT-189-7][risk=no] CDR indexing build - to build or not to build prep_survey

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
- api/db-cdr/generate-cdr/build-review-all-events.sh
- api/libproject/devstart.rb
Exit immediately from the following shell scripts if the DATA_BROWSER arg is true.
- build-ds-linking
- build-ds-tables
- build-review-all-events
- build-cb-search-person
- build-cb-criteria-menu
- build-cloudsql-tables
- build-backup-cb-ds-tables
> [DT-195][risk=no] adding data browser arg to indexing build

- api/config/config_local.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/pages/login/sign-in.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
When we need to share a Feature Flag between the API and UI code, the correct thing to do is to pass it via ConfigResponse.  Unfortunately this flag was implemented as two independent flags with the same name instead, allowing the values to get out of sync.  The recent change to the UI version of this flag in Local and Test to remove the Captcha check from the account creation process was not reflected in the API, so the API attempted to check a Captcha token that was not present, thus preventing account creation. 
This PR removes the duplicate UI FF, so the UI now uses the same FF as the API.
Tested locally - I was able to create an account on Local.
---
* AoU UI
* …
> [risk=low][RW-9451] rm UI duplicate FF enableCaptcha

- .circleci/config.yml
- ui/src/circle-build.sh
- ui/src/terraui/build.sh
- ui/src/terraui/patches/adjusttstarget.sh
- ui/src/terraui/patches/commentoutbadimportline.sh
- ui/src/terraui/patches/patch.mjs
- ui/src/terraui/patches/removenodeversioncheck.sh
- ui/src/terraui/patches/removereactcomponentfromsvgimports.sh
- ui/src/terraui/patches/restorerequire.sh
In https://github.com/all-of-us/workbench/pull/7319, we set `CI=false` for some builds because the benign Webpack-emitted warnings were causing builds to fail on Circle (which sets `CI=true`). This fixes those warnings and obviates the need for setting the flag to false.
main branch:
```
CI=true REACT_APP_ENVIRONMENT=test yarn build           
yarn run v1.22.19                                                                                  
$ react-app-rewired build                                                                          
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
Treating warnings as errors because …
```
> [RW-9048][risk=no] Fix some warnings

- .circleci/config.yml
UI deploys to GAE are hanging. This may fix it.
This a graph of RAM usage over time from CircleCI:
---
* AoU UI
> [RW-9048][risk=no] Use large resource class for deploy job

- ui/src/app/components/apps-panel/utils.spec.tsx
- ui/src/app/components/apps-panel/utils.tsx
Don't make the incorrect assumption that Cromwell already exists!
To test: can you expand the Cromwell logo in the Apps Panel in a newly created workspace?
---
* AoU UI
> [risk=low][RW-9446] Fix bug that prevents Cromwell apps panel expansion

- ui/src/app/components/render-resource-card.spec.tsx
- ui/src/app/components/render-resource-card.tsx
- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
- ui/src/app/pages/data/data-set/dataset-resource-card.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/pages/homepage/recent-resources.spec.tsx
- ui/src/app/pages/homepage/recent-resources.tsx
To reproduce:
* create a dataset
* go to homepage
* open the snowman menu for the dataset in the Recently Accessed Items
* choose Export to Notebook
Crashes on Test, fixed in this PR
---
* AoU UI
> [risk=low][RW-9445] Don't crash when selecting Dataset export from homepage

- .circleci/config.yml
Tested manually via CircleCI's ssh. I do not know why this behavior would have recently changed.
---
* AoU UI
> [RW-9456][risk=no] Prevent prompt during deploy

- ui/src/app/components/copy-snippet-modal.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/signed-in/signed-in.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
- ui/src/app/pages/workspace/workspace-library.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.perf.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
Remove the UI environment flags **enablePublishedWorkspaces**, **enableFooter**, and **enableDemographicSurveyV2Redirect**
* enablePublishedWorkspaces refers to an abandoned feature.  I have removed the last traces of it here.
* enableFooter has been all=true for a long time.  All environments show a footer.
* enableDemographicSurveyV2Redirect was true in some envs but not others, as a workaround to get tests to pass.  It's been true in Prod for a long time, so all other envs should reflect this if possible.  Tests are passing now, so we can remove it.
---
* AoU UI
* [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-expo …
> [risk=low][no ticket] remove 3 env flags we no longer need

- ui/src/app/components/apps-panel/utils.tsx
Some of the "can't delete" workspaces were actually caused by Cromwell apps in ERROR state.  After making deletion of ERROR apps possible (and deleting them) I could then delete the workspaces.
This mitigates RW-9545 but does not fully resolve it.  Workspaces with RUNNING or STOPPED (Paused) apps are non-deletable.
---
* AoU UI
> [risk=low][RW-9454] Allow deletion of ERROR state user apps

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
Description:
We added that FF check in API because using Cromwell/RStudio is not approved. 
Now it is approved, remove this FF check. And we will use UI FF to control show/hide this feature
---
* AoU UI
> [RW-9470][risk=no] remove enableGkeApp check in API when creating APPs

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
---
- Removed all conditional logic for OMOP version older than OMOP 5.3.1
- will be running cdr-indexing build to verify it works as expected after this PR approval
---
* AoU UI
> [DT-196][risk=no] CDR indices - cleanup any code from OMOP v5.3.1 upgrade

- api/db-cdr/generate-cdr/build-ds-linking.sh
Description:
---
- after removing initial query for getting table list, indexing fails. Local run works fine so doing
- initialize .bigqueryrc by running a count for some table
---
* AoU UI
> [DT-191-1][risk=no] CDR indexing - Fix issue after removing OMOP v5.3.1 check

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/api/DiskController.java
- api/src/main/java/org/pmiops/workbench/api/DisksController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DiskControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
Description:
When implement disks, Leo does not support the new API yet. Now change disk API to be the same. 
In the future we want to support `AdminListAppInWorkspace` when we want to display apps in admin workspace page. 
---
* AoU UI
> [RW-9274][risk=low] Exclude those apps are created by other when list apps. Also improve listDisk

- ui/src/app/components/combo-chart.component.tsx
Description:
---
- Improve user experience by showing chart for selected legend (clicked on legend: for `>65`
- Currently clicking on legend **_hides_** the bars for selected-legend
- and selecting every legend can get you into this state:
- Changed to **_show_** selected legend (this maybe a better option) (click a second time to un-select) and see all
- selecting a different legend switches the selected legend 
---
* AoU UI
> [No-Ticket][risk-no] Enhanced chart to expand chart for selected legend

- api-proxy/handlers/|v1|workspaces|aou-rw-test-ca61ee0f|apps.get.mjs
- e2ev2/tests/workspace-create.test.js
> [risk=no][no ticket] Fix e2ev2 workspace creation test

- api/libproject/devstart.rb
Description:
---
- Updated project.rb command to take domain-token as an argument for matrix job in Ci
---
* AoU UI
> [No-ticket][risk=no] Updated project.rb command for build-search-all-events

- api/libproject/devstart.rb
Description:
---
- Updated project.rb-fix argument reference error `opts.domain_token`
---
* AoU UI
> [No-ticket][risk=no] Fix project.rb build-search-all-events command

- ui/src/app/pages/signed-in/access-renewal-notification.spec.tsx
- ui/src/app/pages/signed-in/access-renewal-notification.tsx
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
A basic fix for the current behavior on Prod:
* Update the RT AAR notification so it does not consider CT-only modules
* Add a new CT AAR notification
When RT expiration is coming before CT, **we do not show the CT banner**, because the RT expiration is what's relevant.  This is equivalent to the current behavior.
When CT expiration is **sooner** than RT, we will show both banners:
We probably want to do something more intelligent here, like combining them.  That's https://precisionmedicineinitiative.atlassian.net/browse/RW-9546
---
* AoU UI …
> [risk=low][RW-9550] Correct text per-tier for AAR UI notifications

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
- api/db-cdr/generate-cdr/build-prep-survey.sh
- api/db-cdr/generate-cdr/build-review-all-events.sh
- api/db-cdr/generate-cdr/create-tables.sh
- api/db-cdr/generate-cdr/import-cdr-indices-build-to-cloudsql.sh
- api/libproject/devstart.rb
Cleanup script parameters with new conditional workflows. This PR has done the following:
- Removed all data-browser parameters from scripts since it's now checked on the circleCi workflow level
- Removed create-surveys parameters from scripts since it's now checked on the circeCi workflow level
- For scripts that still use create-surveys parameter - renamed it to create-prep-tables - This parameter now triggers the build/non-build of all prep_ tables. The intent of this is to gain more efficiency. 
Command will now look like so:
`./project.rb create-cdr-indices --project all-of-us-workbench-test --bq-dataset SR2022Q4R6 --cdr-version sr_2022q4_6 --create-prep-tables false`
> [DT-216][risk=no] cleanup script parameters with new conditional workflows

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/signed-in/nav-bar.tsx
- ui/src/testing/default-server-config.ts
Add a temporary API feature flag `enableControlledTierTrainingRenewal` to control whether we are displaying (1) CT Renewal Notifications and (2) "coming soon" text for Annual Renewal.
This PR also implements part 1: hide the notification banner.
Tested locally: I saw the banner when the flag was true, and I didn't see when the flag was false. 
---
* AoU UI
> [risk=low][RW-9561] Disable CT Renewal Notification Banner via Feature Flag

- ui/src/app/pages/access/controlled-tier-card.tsx
- ui/src/app/pages/access/data-access-requirements.spec.tsx
- ui/src/app/pages/access/data-access-requirements.tsx
When `enableControlledTierTrainingRenewal` is false, make two changes to the Annual Renewal page (Data Access Requirements in ANNUAL_RENEWAL mode)
* Don't show the new ControlledTierRenewalBanner
* Replace the CT Training module with this
---
* AoU UI
> [risk=low][RW-9561] Disable CT Training on Renewal page based on FF

- api/db-cdr/generate-cdr/export-import-cloudsql-cdr.sh
- api/db-cdr/generate-cdr/verify-counts.sql
- api/libproject/devstart.rb
- api/libproject/gcloudcontext.rb
Description:
---
- Automate export/import MySQL databases from preprod to prod.
- Verify that the database cb_ and ds_ and other table row counts match between preprod and prod
- Update [CDR Playbook](https://docs.google.com/document/d/1St6pG_EUFB9oRQUQaOSO7a9UPxPkQ5n4qAVyKF9j9tk/edit#heading=h.vq2ookfjt3a4) documentation once this PR is merged
- There are 2 project.rb commands: Note the project id defaults to as needed for the process. This process is only for export from **preprod** and import to **prod**
-  `export-import-cloudsql-cdr` For export and subsequent import. This also executes the `verify-cloud-cdr-counts`
- `./project.rb export-import-cloudsql-cdr --cdr-db-name r_2022q4_1`
- ` verify-cloud-cdr-counts` Outputs row counts for all cb_* and ds_*, and other tables in the cdr for …
> [DT-242][risk=no]CDR indexing build - automate export-import of cdr from preprod to prod

- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/runtime-status-icon.tsx
Description:
Disable users from using apps if they have an open egress event.
This was partially implemented already. Currently, if we detect that the user is suspended, we disable opening the apps panel. We detect this by responding to failed API calls to various runtime endpoints. We are individually treating many different endpoints as indicators that the user is suspended.
This approach has a few problems:
1. The app isn't aware that a user is suspended until the user attempts to perform an action
2. Leo does not have a concept of user suspension, so this approach cannot prevent direct calls to Leo
3. There are many intertwined code paths leading to the same end result
This PR moves us toward a "top-down" approach by detecting user suspension and disabling the apps panel before we …
> [RW-9505][risk=low] Disable user from using apps if they have an open egress event

- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/utils.tsx
Description: No product changes. This refactor assumes all non-Jupyter "apps" are GKE apps, which I think is reasonable.
This will make the app creation story easier to understand.
---
* AoU UI
> [RW-9408][risk=no] Refactor: Generalize some code paths across apps

- ui/src/app/components/notification-banner.tsx
- ui/src/app/pages/signed-in/access-renewal-notification.spec.tsx
- ui/src/app/pages/signed-in/access-renewal-notification.tsx
- ui/src/app/styles/colors.ts
- ui/src/app/utils/constants.tsx
2 weeks - purple / blue : 
1 week - yellow:  
1 day - red : 
Description:
---
* AoU UI
> [RW-9546][risk=no]   Notifications for CT-expiring users

- api/config/config_local.json
- api/config/config_perf.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Tested locally: I see the CT Expiration notification banner, and when I click it, I can access CT training on the Access Renewal page.
---
* AoU UI
> [risk=low][RW-9570] flip enableControlledTierTrainingRenewal to true in all envs

- api/config/config_local.json
- api/config/config_test.json
> [RW-9555][risk=no] Update jupyer image version to 2.1.17 to update hail version

- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel/apps-panel-button.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/testing/stubs/apps-api-stub.ts
- ui/src/testing/stubs/leo-apps-api-stub.ts
Description:
Allows users to pause and resume RStudio GKE apps.
Status: Running
Status: Pausing
Status: Paused
Status: Resuming
---
* AoU UI
> [RW-9409][risk=no] Pause and resume RStudio GKE apps

- e2e/tests/nightly/batch.spec.ts
- e2e/tests/nightly/dataproc-to-gce.spec.ts
- e2e/tests/nightly/gce-to-dataproc.spec.ts
- e2e/tests/nightly/runtime.spec.ts
Description:
Disabling these four tests because they are all failing in a similar way (starting or stopping an environment). Plan to refactor these in the future (https://precisionmedicineinitiative.atlassian.net/browse/RW-9658)
---
* AoU UI
> [RW-9635][risk-no] Disabling tests until they can be refactored.

- e2ev2/tests/workspace-create.test.js
Sidebar takes some time to load, so we need to wait for the menu to appear before clicking.
Tested once before the change and saw the failure. Tested after the change and the test passed.
---
* AoU UI
> [RW-9652][risk=no] Wait for selector before click

- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/testing/stubs/leo-proxy-api-stub.ts
Description:
Allows users to open RStudio apps.
Currently the RStudio app opens in a new browser tab since this was very easy to implement as an MVP. After confirming this is OK with Moira, I've [updated the ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-9613?focusedCommentId=150310) and created a [follow-up story](https://precisionmedicineinitiative.atlassian.net/browse/RW-9664) to show RStudio in the Analysis tab. Let me know if there are reasons we shouldn't do this.
I also moved a test from `apps-panel.spec.tsx` to `expanded-app.spec.tsx` to simplify it.
@jmthibault79 what testing approach did you settle on for Cromwell? Currently, I am planning to create an e2e test in a follow-up PR before marking this story as done.
I think the exact list of changes is …
> [RW-9613][risk=no] Open RStudio apps

- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/data/cohort/addConceptSetToCohortModal.tsx
- ui/src/app/pages/data/cohort/cohort-search.tsx
Add modal for selecting a concept set to add as a cohort line item. Concept menu items will only show when `enableConceptSetsInCohortBuilder` flag is enabled
https://user-images.githubusercontent.com/40036095/224393936-2fc0f20c-0b2d-4aa6-90ac-ba4d85f27f4e.mov
---
* AoU UI
> [DT-19][risk=no] Modal for adding a concept set as a cohort item

- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/help-sidebar.spec.tsx
Description:
The unexpanded Cromwell app now opens directly to the config page.
Since we will be following this up with the equivalent [RStudio story](https://precisionmedicineinitiative.atlassian.net/browse/RW-9703), I am not doing any refactoring in this PR.
This does not complete all the AC of the story. I will make additional PRs to update the buttons.
---
* AoU UI
> [RW-9614][risk=no] Open the Cromwell config panel after clicking the unexpanded app

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Docker 2.1.17 version causes the snippets menu to disappear and 2.1.16 does not work at all.
Revert for now to unblock release, then investigate.
---
* AoU UI
> [risk=low][RW-9725] Revert all docker versions to 2.1.15 to restore snippets menu

- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/testing/stubs/apps-api-stub.ts
Description:
This PR removes the Cromwell Launch button.
This PR updates the Cromwell Settings button to link to the Cromwell configuration panel.
This does not complete the ticket yet. I have [another PR](https://github.com/all-of-us/workbench/pull/7480) addressing an issue with the Cromwell configuration page.
---
* AoU UI
> [RW-9614][risk=no] Combine Cromwell Settings and Launch buttons

- api/src/main/java/org/pmiops/workbench/cdr/CdrVersionContext.java
See comments in commit. Tested via `./gradlew appengineRun`.
---
* AoU UI
> [RW-9582][risk=no] Reduce noise of missing CDR version message

- e2e/tests/nightly/detachable-disk.spec.ts
- ui/src/app/components/runtime-configuration-panel.tsx
Earlier GeneralAnalysis had default standard disk, hence selecting PD was considered User override.
Now since the default of GeneralAnalysis is PD, there could be a scenario that the runtime is deleted but PD remains. In that scenario, if the user selects the jupyter button on side bar we should be showing the configuration page and not the create pannel
Description:
---
* AoU UI
> Fix nightly test

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java
- api/src/test/java/org/pmiops/workbench/exceptions/ExceptionUtilsTest.java
Description:
Added functionality to convert Leonardo conflict exceptions to a human readable error.
---
* AoU UI
> [RW-9520][risk=no] Added API Exception Handling for Leonardo Conflicts

- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/utils/runtime-presets.ts
Fixes 2 runtime panel bugs caused by the change in #7399 - both are related to the transition between allowing GCE runtimes without Persistent Disks and not allowing them.
To reproduce bug 1 (crash)
* run #7490 as Local->Test and create a GCE runtime with no PD in a new workspace (not a duplicate)
* open that workspace in Test
* delete that runtime.  After the runtime configuration panel closes, open it again, and wait for the runtime to finish deletion
* CRASH (console error looks like "cannot reference cpu from machine because it is null")
To reproduce bug 2 (crash)
* run #7490 as Local->Test and create a GCE runtime with no PD in a new workspace (not a duplicate)
* delete that runtime
* open that workspace in Test
* choose "Create a New Notebook" in either the Analysis tab or the Apps …
> [risk=low][RW-9723] When applying General Analysis presets, don't skip the GCE with PD case

- api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/ClearCdrVersionContextInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/CloudTaskInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/CorsInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/CronInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/RequestTimeMetricInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/SecurityHeadersInterceptor.java
- api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java
HandlerInterceptorAdapter was deprecated in 2003.  Its implementation is
```
HandlerInterceptorAdapter implements AsyncHandlerInterceptor {
}
```
So I feel pretty safe in how I'm replacing it here.
Tested locally with no obvious concerns.
---
* AoU UI
> [risk=low][no ticket] HandlerInterceptorAdapter has been deprecated for literally 20 years

- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
> [risk=low][no ticket] e2e-user workspace deletion: warn when users are not found but continue

- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.tsx
- ui/src/testing/stubs/apps-api-stub.ts
- ui/src/testing/utils.ts
Description:
Refactors the Cromwell configuration panel to use shared logic for when a GKE app can be created.
Additionally, adds some tests.
~~Fixes a pre-existing bug where the user cannot create a Cromwell app if their previously-deleted app is in a DELETED state.~~
~~It's difficult to test or notice this locally since the app is quickly removed from the list of apps returned by the list apps endpoint.~~
~~Question for the reviewer: When are apps in a "DELETED" state, anyway? What happens if a user has a “deleted” app, then creates another? Would the user have two apps in that scenario, and does our code account for this?~~
---
* AoU UI …
> [RW-9614][risk=no] Refactor Cromwell configuration panel

- api/src/integration/java/org/pmiops/workbench/ApplicationTest.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
Re-enable Spring's no-op integration test to allow for more of this style of testing. This is needed to test the functionality of RW-9582.
CDR criteria loads:
---
* AoU UI
> [RW-9582][risk=no] Re-enable and fix ApplicationTest

- api/build.gradle
We split tests by timing on Circle, so there is no need to also run them in parallel.
---
* AoU UI
> [no-ticket][risk=no] Avoid parallelization on Circle

- ui/src/app/pages/data/cohort/cohort-search.tsx
- ui/src/app/pages/data/cohort/concept-quick-add-modal.tsx
- ui/src/app/pages/data/cohort/search-group-list.tsx
- New modal to lookup concepts by id or code and add directly to a cohort
- Can enter ids/codes separated by commas or one per line
- Will add multiple items if multiple domains are returned
https://user-images.githubusercontent.com/40036095/226938465-26204605-aa30-4765-856e-9c95617046f0.mov
---
* AoU UI
> [DT-279][risk=no] Add Concept Quick Add modal to CB

- ui/src/app/pages/data/cohort/search-group-item.tsx
- Adds option to the cohort item menu to add all concepts from the cohort item to a new or existing concept set
- New menu item is. hidden in the menu for any concepts that skip cohort search (Fitbit, WGS, etc.), demographics and survey items that only contain answers since answers cannot be added to a concept set.
https://user-images.githubusercontent.com/40036095/225078160-c6b3ca2a-f5dd-49ff-a646-b696d63bba57.mov
---
* AoU UI
> [DT-276][risk=no] Add concept set option to cohort item menu

- api/src/main/webapp/WEB-INF/appengine-web.xml.template
See comment inline.
Note that the docs state that the `threadsafe` flag must be removed, as it is now assumed, but this had no effect in my testing, so it can be done in a follow-up.
Tested by deploying to ephemeral GAE instance.
---
* AoU UI
> [RW-5609][risk=no] Enable app-engine-apis flag

- e2ev2/src/test-utils.js
- e2ev2/tests/new-user-satisfaction-survey.test.js
- e2ev2/tests/sanity.browser.test.js
- e2ev2/tests/user-create.test.js
- e2ev2/tests/workspace-analysis.test.js
- e2ev2/tests/workspace-create.test.js
We should not be waiting for network idle. We can't know when all requests will finish and with polling or other ongoing operations this isn't safe. We can and should wait for page events and selectors to determine when to take the next action.
Tested locally by running e2ev2 tests twenty times in a row.
---
* AoU UI
> Increase stability in e2ev2 tests

- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/pages/login/sign-in.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/authentication.tsx
- ui/src/app/utils/errors.tsx
- ui/src/app/utils/leo-runtime-initializer.tsx
Description:
Removes most of the logs recently fixed in https://github.com/all-of-us/workbench/pull/7500.
These logs are difficult to act on for a two reasons:
- The stack traces often point to our minified JS instead of our source code ([example](https://console.cloud.google.com/errors/detail/CKrT7_C37drnGg;service=web;time=P7D?project=all-of-us-rw-prod)). This may be fixable using source maps, but requires a more thorough investigation of our build system and logging library to leverage.
- Stack traces are obfuscated by anonymous functions ([example](https://console.cloud.google.com/errors/detail/CL69gZGplO7mfA;service=web;time=P30D?project=all-of-us-rw-prod))
However, the string-based logs messages are working as expected ([example](https://console.cloud.google.com/errors/detail/CIOL2tK …
> [no ticket][risk=no] Remove noisy error-based logs

- api/db/local-vars.env
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/cdr/CdrDbConfig.java
- api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
The Google AppEngine runtime for Java 11 is substantially different than that for Java 8 and requires changes to how our application talks to Cloud SQL. As I iterated on this, having the additional burden of ambiguity around whether or not Spring would decide to use my specified configuration parameters would have caused significant fatigue. This PR addresses that problem by making that relationship more explicit.
How do I know that my changes to configuration parameters will affect the application?
Before:
```
% grep -R DB_CONNECTION_STRING
src/main/webapp/WEB-INF/appengine-web.xml.template
33:    <property name="spring.datasource.url" value="${DB_CONNECTION_STRING}"/>
37:    <property name="cdr.datasource.url" value="${CDR_DB_CONNECTION_STRING}"/>
db-cdr/vars.env …
```
> [RW-5609][risk=no] Use environment variables for database configuration

- api/build.gradle
This change eliminates all instances of the warning:
```
com.example.Classname scanned from multiple locations: ...
```
except for those that are duplicated in the appengine-api-1.0-sdk jar, which will go away once we are on AppEngine's Java 11 runtime and we've migrated off of it.
Tested by building locally.
---
* AoU UI
> [no-ticket][risk=no] Reduce build noise

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
Description:
Turns out google project is not set in Runtime
---
* AoU UI
> [RW-9794][risk=no] Get google project from workspace

- api/libproject/devstart.rb
The database configuration we use for Google AppEngine's Java 11 runtime no longer needs the Cloud SQL proxy to connect to Cloud SQL. Removing `DB_HOST` is a quick fix for ignoring it.
Tested by sshing into Circle and running the same deploy command both before and after the change.
---
* AoU UI
> [no-ticket][risk=low] Fix deploy by ignoring Cloud SQL proxy

- api/libproject/devstart.rb
See https://github.com/all-of-us/workbench/pull/7533.
Tested by reproducing the failure locally, then succeeding with this change.
---
* AoU UI
> [no-ticket][risk=no] Fix set-access-module-timestamps by ignoring Cloud SQL proxy

- api-proxy/handlers/|v1|config.get.mjs
- api/src/main/java/org/pmiops/workbench/access/AccessModuleNameMapper.java
- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/BypassTimeTargetProperty.kt
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbAccessModule.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleNameMapperTest.java
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
- ui/src/app/pages/admin/user/admin-user-bypass.tsx
- ui/src/app/pages/profile/profile-component.spec.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/testing/default-server-config.ts
Allow bypassing profile and publication confirmation modules. This implements all product-facing changes for the story.
All modules are now bypassable. The remaining PRs will refactor the code based on this.
I marked this as "low" risk because this directly affects access modules.
Manually tested:
- Bypass all continues to work
- The normal renewal flow continues to work
New features:
- Admins can bypass these modules from the user index admin page
- Admins can bypass these modules from the user admin page
- The data requirements page shows that the modules have been bypassed
- The profile page doesn't show the renewal banner if the user is bypassed
`​​update user_access_module set completion_time = DATE_SUB(NOW(),INTERVAL 2 YEAR) where user_id = 2 and access_module_id = 6;`
6 = …
> [RW-9208][risk=low] Allow bypassing profile and publication confirmation modules

- api/db-cdr/generate-cdr/build-review-all-events.sh
Description:
---
- Updated indexing build for cb_review_survey to fix participant counts for surveys across: cb_criteria, cb_review_survey and ds_survey tables.
---
* AoU UI
> [DT-345][risk=no] Updated to fix participant counts for surveys across: cb/ds survey tables

- e2e/app/sidebar/apps-panel.ts
- e2e/tests/nightly/gke-apps/cromwell.spec.ts
- e2e/tests/nightly/gke-apps/rstudio.spec.ts
> [risk=low][RW-9518][RW-9608][RW-9526] Update Cromwell/RStudio e2e tests for polling

- api/libproject/devstart.rb
This avoids starting Cloud SQL Proxy whenever we run a Java tool, since our datasource configuration no longer needs it.
Manually ran few commands locally.
---
* AoU UI
> [no-ticket][risk=no] Avoid Cloud SQL Proxy when running Java tools

- api/src/integration/java/org/pmiops/workbench/ApplicationTest.java
- api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java
- api/src/main/java/org/pmiops/workbench/cdr/DbParams.java
- api/src/main/java/org/pmiops/workbench/db/Params.java
- api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java
- api/tools/src/main/java/org/pmiops/workbench/tools/Tool.java
This should unbreak stable and staging by reading and using CDR DB config variables when they are present.
Ran locally with different combinations of environment variables, deployed and tested on App Engine.
---
* AoU UI
> [no-ticket][risk=no] Clean up DB config

- api/db/build.gradle
- api/libproject/devstart.rb
The update command within the `db` directory does not use our app's database configuration, so it needs the Cloud SQL Proxy.
Reproduced the error on Circle via ssh, successful deploy after this change.
---
* AoU UI
> [no-ticket][risk=no] Use Cloud SQL Proxy for Liquibase

- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- ui/src/app/routing/guards.spec.tsx
Removes test references to modules that are now bypassable.
It might be possible to remove an [additional check in guards.tsx](https://github.com/all-of-us/workbench/blob/bdefab303b17f355dc0db62feceb4bb3bea88cff/ui/src/app/routing/guards.tsx#L66), but after discussing this with Joel I'm not confident we're covering all the cases without that check. This PR still moves us in a simpler direction.
---
* AoU UI
> [RW-9208][risk=no] Remove test references to unbypassable modules

- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/environment-cost-estimator.tsx
- ui/src/app/components/environment-informed-action-panel.tsx
- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel/confirm-update-panel.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
Description:
Add a base cost estimate for GKE apps. Per the Jira ticket, this updates the displayed cost for a running Cromwell instance to be $0.40/hour and the displayed cost for a paused Cromwell instance to be $0.20/hour.
Tested locally by checking all uses of the cost estimate component:
- Cromwell config panel
- Jupyter config panel (unchanged)
- Jupyter app creation flow via modals (unchanged)
- Updating configuration for a running Jupyter app (unchanged)
[Relevant #workbench-ux thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1681138168930999)
Screenshots:
---
* AoU UI …
> [RW-9766][risk=no] Add base cost estimate for GKE apps

- e2e/tests/nightly/gke-apps/cromwell.spec.ts
- e2e/tests/nightly/gke-apps/rstudio.spec.ts
Nightly tests sometimes fail due to Cromwell deletion timing out.  Manual inspection of the workspace shows that deletion was eventually successful.
Let's double the timeout to 2 min.
---
* AoU UI
> [risk=no][no ticket] e2e - bump GKE App deletion timeouts to 2 min

- .circleci/config.yml
CIRCLE_BRANCH isn't set on main.
---
* AoU UI
> Fix staging puppeteer-test queue

- api/libproject/devstart.rb
If I wrap the ServiceAccountContext around the update_cdr_config_for_project call it updates the sa-key.json and works. Found this comment in the tools.md file: 
`Wrapping the gradle call with ServiceAccountContext like in list-runtime will ensure that the correct sa-key.json credentials are set.`
> [no ticket][risk=no] fixing update-cdr-config command

- e2e/app/modal/warning-delete-cromwell-modal.ts
- e2e/tests/nightly/gke-apps/cromwell.spec.ts
- ui/src/app/components/apps-panel/delete-cromwell-modal.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
> [RW-9893 ][risk=no]  [MVP] warn users jobs may be terminated

- ui/src/app/components/apps-panel/apps-panel-button.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/apps-panel/pause-resume-button.tsx
- ui/src/app/components/environment-informed-action-panel.tsx
Description:
Remove pause/resume functionality for Cromwell & RStudio
- Disables pause/resume on the Applications panel
- Removes the pause/resume button on the Cromwell config page
[Relevant Workbench-UX slack thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1681220802599489).
Screenshots:
On the Applications panel, the pause/resume button is disabled with a tooltip.
On the Cromwell config page the pause/resume button has been removed.
Existing Jupyter config page for reference. No changes were made.
---
* AoU UI …
> [RW-9889][risk=no] Remove pause/resume functionality for Cromwell & RStudio

- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
Description:
---
- Fix dao calls to use only standard codes for adding concept sets in cohort builder
---
* AoU UI
> [DT-353][risk=no] Concept quick add - modify to search only standard codes/ids

- api/config/cdr_config_preprod.json
> [RW-9197][risk=no] Some preprod paths are too long for the db column

- ui/src/app/components/cromwell-configuration-panel.tsx
Description:
Update Cromwell config panel description. During user research, users found "This is the server version of Cromwell only" confusing.
New text:
---
* AoU UI
> [RW-9746][risk=no] Update Cromwell config panel description

- ui/src/app/pages/data/cohort/cohort-criteria-menu.tsx
Fixes issue where only the 'Other' title and not the menu items were hidden when the `enableConceptSetsInCohortBuilder` flag was not enabled.
---
* AoU UI
> [DT-354][risk=no] Fix condition to show concept menu items

- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/help-sidebar-icons.spec.tsx
- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/setupTests.js
Description:
Adds a sidebar icon for the RStudio config panel.
Adds a minimally-implemented RStudio config panel.
For the reviewer: How do you feel about this PR introducing a non-functional panel? Am I splitting up the story into too many PRs? It will only be visible locally and in test and will be updated within a few days.
[Relevant workbench-ux thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1681331039881969).
Our `TooltipTrigger` component is difficult to test with Enzyme so I have manually tested it and included a screenshot below.
Screenshots:
Icon with tooltip
Empty config panel
---
* AoU UI …
> [RW-9746][risk=no] Add RStudio config icon

- ui/src/app/components/configuration-panel.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
Description:
Completes the RStudio config panel header. Adds minimal panel body text, which will be replaced in the immediate next PR.
My approach here favors composition over inheritance. Rather than creating an `<AppHeader>` component with several props and internal logic, I just made the `<BetaBadge>` component more reusable. If this seems OK, I intend to try a similar approach for the panel content.
I have not posted this to #workbench-ux yet. I intend to do that once the entire panel is complete (likely the next PR) for final feedback.
Screenshots:
---
* AoU UI
* [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-exp …
> [RW-9746][risk=no] Add RStudio config panel header

- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/default-server-config.ts
useGpu and usePersistentDisk are always true, and we are removing these Feature Flags (see #7592) so we can remove the UI logic which checks if they are false.
After a release, we can fully remove these FFs.
---
* AoU UI
> [risk=low][no ticket] rm UI logic based on FFs useGpu and usePersistentDisk

- ui/src/app/components/cromwell-configuration-panel.tsx
Description:
Miscellaneous Cromwell configuration panel refactors. There are no product-facing changes.
This should simplify sharing code with a comparable RStudio config panel.
**Reviewer note: This PR is most easily reviewed commit-by-commit.**
This PR is very similar to [this refactoring PR](https://github.com/all-of-us/workbench/pull/7594). If I had noticed these updates earlier I would have included them there.
This can be verified by comparing the behavior of the Cromwell config panel before and after this change. Everything should be the same.
Screenshots (there should be no differences):
Before:
After:
---
* AoU UI …
> [RW-9746][risk=no] Miscellaneous Cromwell config panel refactors

- e2e/tests/nightly/gke-apps/cromwell.spec.ts
- ui/src/app/components/configuration-panel.tsx
- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
- ui/src/app/components/gke-app-configuration-panels/disabled-cloud-compute-profile.tsx
- ui/src/app/components/rstudio-configuration-panel.spec.tsx
- ui/src/app/components/rstudio-configuration-panel.tsx
- ui/src/app/components/with-workspace-gke-apps.spec.tsx
- ui/src/app/components/with-workspace-gke-apps.tsx
- ui/src/app/utils/user-apps-utils.tsx
Description:
Add RStudio configuration panel content.
In addition to the AC, this adds the following to both the RStudio and Cromwell config panels:
- A loading spinner when the initial list apps request is processing
- An error modal when the initial list apps request fails
The easiest way I've found to test the above is to use Chrome's network throttling feature and then open the side panel.
I leaned into using composition over inheritance. Instead of creating a single mega-component that handles all apps, I created sharable components that Cromwell and RStudio share. I think this is more testable and readable than a mega-component, but I'd be curious to hear your thoughts.
The first commit adds the RStudio panel and completes all AC. The remaining commits apply individual refactors. …
> [RW-9746][risk=no] Add RStudio configuration panel content

- api/config/cdr_config_prod.json
Reverts all-of-us/workbench#7602
because Leo fixes env var length limit issue
> [No-ticket][risk=no] Revert "[No-ticket][risk=no]Update prod CDR config to remove new env vars"

- api/src/test/java/org/pmiops/workbench/interceptors/RequestTimeMetricInterceptorTest.java
Mocking the java.lang.reflect.Method via Mockito is considered hazardous:
https://github.com/mockito/mockito/issues/2081
https://github.com/mockito/mockito/issues/2026
It seems this worked without causing issues before version 3.5.0, but after that, mocked Method classes caused pollution in the test process.
I reproduced this issue consistently using various versions of Mockito>3.5.x:
```
RequestTimeMetricInterceptorTest > testPostHandle() FAILED
java.lang.NullPointerException
at java.base/java.lang.reflect.Method.getParameterTypes(Method.java:311)
at org.mockito.internal.creation.DelegatingMethod.<init>(DelegatingMethod.java:20)
at org.mockito.internal.invocation.DefaultInvocationFactory.createMockitoMethod(DefaultInvocationFactory.java:81)
at …
```
> [no ticket][risk=no] Avoid mocking java.lang.reflect.Method in tests

- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Description:
Ignore the workspace prop when loading the workspace create page for the CDR dropdown (as described in the ticket) and the specific populations checkbox (which used the same logic, leading to the same error).
I chose the simplest approach to fix the exact issue described in the ticket. The tests in this PR fail on the `main` branch, but pass here.
The underlying problem here is that our create workspace page is injected with the current workspace from global state, allowing it to double as the edit page. I'd like to remove that dependency to prevent issues like this in the future, but I think it's out of scope for this bug.
To verify this change, follow the STR from the ticket.
---
* AoU UI
* [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/ …
> [RW-9737][risk=no] Ignore the workspace prop when loading the workspace create page

- api/build.gradle
This fixes the following warning when Gradle is executed with `--warning-mode=all`:
```
IncrementalTaskInputs has been deprecated. This is scheduled to be removed in Gradle 8.0. On method 'AbstractKotlinCompile.execute' use 'org.gradle.work.InputChanges' instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.6.1/userguide/upgrading_version_7.html#incremental_task_inputs_deprecation
```
---
* AoU UI
> [no ticket][risk=no] Upgrade Kotlin to latest

- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
---
- Turn on enableConceptSetsInCohortBuilder flag in all environments 
---
> [DT-207][risk=no] Feature Flag: activate feature flag: enableConceptSetsInCohortBuilder

- api/build.gradle
Allows control of `-Xlint:*` options from environment variables.
Tested by running some compile tasks with and without the variables defined.
---
> [no ticket][risk=no] Support for Java lint in build

- api/libproject/devstart.rb
Fixes recent authentication errors with project.rb tools by wrapping all calls previously using CloudSqlProxyContext in ServiceAccountContext.
This bug was introduced in https://github.com/all-of-us/workbench/pull/7555. The CloudSqlProxyContext wrapper was removed from many functions because CloudSqlProxyContext's functionality was no longer needed. However, CloudSqlProxyContext is a subclass of ServiceAccountContext, and that functionality is needed for those commands to function in non-test environments.
Two hotfixes for this issue using the same approach as this PR have been made: https://github.com/all-of-us/workbench/pull/7571, https://github.com/all-of-us/workbench/pull/7583.
A different fix for this issue was introduced in https://github.com/all-of-us/workbench/pull/7566. Questions …
> [no ticket][risk=no] Wrap calls previously using CloudSqlProxyContext in ServiceAccountContext

- api/src/main/java/org/pmiops/workbench/config/AppEngineConfig.java
`com.google.api.client.extensions.appengine.http.UrlFetchTransport` is only available with legacy APIs enabled in GAE. `com.google.api.client.googleapis.javanet.GoogleNetHttpTransport` works with legacy APIs disabled.
Deployed here:
https://mohstest-dot-api-dot-all-of-us-workbench-test.uc.r.appspot.com
Tested manually via UI interactions.
---
> [no ticket][risk=no] Switch from legacy HttpTransport

- e2e/tests/nightly/gke-apps/cromwell.spec.ts
There was a typo in the snippet related to the cromshell version, This was fixed as part of PR https://github.com/all-of-us/workbench/pull/7643
---
> [RW-9518][risk=no]  [tests] Cromwell / User App tests - use correct version cromshell-alpha/cromshell-beta

- api/build.gradle
- api/libproject/devstart.rb
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteOrphanedWorkspaces.java
Sometimes, the AoU DB and Terra's Workspace service (Rawls) can get out of sync.  This tool queries Rawls for which workspaces it believes the user owns, and deletes those that the AoU DB does not believe the user owns (or has been marked as deleted)
Possible future work:
* add AoU workspace deletion also / replace the DeleteWorkspaces tool
* add Terra-Sam workspace resource deletion (in case it is out of sync with Rawls)
* cron-ify this for test users: #7653
---
> [risk=low][RW-10024] Add a tool to delete a user's Rawls workspaces which are not present in the AoU DB

- api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java
- api/src/main/java/org/pmiops/workbench/cdr/DbParams.java
- api/src/main/java/org/pmiops/workbench/config/EnvVars.java
- api/src/main/java/org/pmiops/workbench/db/Params.java
- api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java
- api/src/main/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterService.java
- api/src/test/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/Tool.java
This change adds one layer of indirection between our code and `System.getenv`. By using a Spring Bean to proxy that method call, we are able to mock it when writing tests.
---
> [no ticket][risk=no] Better handling of environment variables

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
Wait one release after #7592 and #7593 have been merged.  Based on that timing, I expect we can merge this after the April 24 release. 
Remove the last references to:
- enableGpu
- enablePersistentDisk
- enableUpdatedDemographicSurvey
---
* AoU UI
> [risk=no][no ticket] Complete the removal of 3 Feature Flags

- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/ds_person_data.json
- api/src/bigquerytest/resources/bigquery/cbdata/ds_procedure_occurrence_data.json
- api/src/bigquerytest/resources/bigquery/schema/ds_person.json
- api/src/bigquerytest/resources/bigquery/schema/ds_procedure_occurrence.json
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
Fix tidyverse read_csv problem. In R notebooks the tidyverse plugin tries to dynamically determine the column types in a csv file. Sometimes it incorrectly determines that a string column is a double/integer. This fix will force any string columns to always be strings, so that merging of csv files won't fail do to incompatible types.
> [DT-379][risk=no] Fix tidyverse read_csv problem.

- api/src/main/java/org/pmiops/workbench/api/CloudTaskWorkspacesController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
Add a new cron task which continues the process of deleting test user workspaces by deleting "orphaned" Rawls workspaces which do not have associated AoU RW DB workspaces.  This can happen in at least two ways:
* attempted workspace creation partially succeeded, recording a Rawls workspace but not an AoU workspace
* attempted deletion partially succeeded, removing the AoU workspace but not the Rawls workspace
As an example, I count 47 AoU workspaces for one test user but 228 Rawls workspaces.  These numbers should match.
Tested by hitting the new cron endpoint locally.
Future work: do we also need to clean up **Sam** resources?  Can these get out of sync with Rawls?
~Future work~ [**done** in #7654] add a tool for cleanup of arbitrary users' workspaces
---
> [risk=low][RW-10024] Delete test user orphaned Rawls workspaces cron

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/utils/mappers/FirecloudMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/MapStructConfig.java
This should have no impact on the compiled code.
I tested by compiling with and without these flags and running `diff -r` on the result. The diff on this change is way shorter and much more helpful.
---
> [no ticket][risk=no] Suppress timestamps in generated code to reduce diff noise

- ui/src/app/components/resource-list.spec.tsx
- ui/src/app/pages/analysis/notebook-list.spec.tsx
- ui/src/app/utils/resources.tsx
- ui/src/testing/stubs/notebooks-api-stub.ts
**FIXED:**
The resource list table was unable to display who made the last modification to notebook. 
**Why:**
While converting the FileDetail[] to the resource type for displaying the table in a notebook, the value was getting set to null. This approach would work for other resources, because the dataPage function calls the API workspace.getWorkspaceResourcesV2() to update the lastModifiedBy parameter from the Workbench Database
The reason why notebook isnt calling the same endpoint, could be because notebook information is not stored in our Database and we get the information from Leonardo. 
**Next PR:**
This PR will solve the lastModifiedBy issue on Notebook list page (analysis and new analysis tab) however the userRecentResource still does not have this information. This will require …
> [RW-9105][risk=low] Fix missing LastModifiedBy information from notebook list

- api/src/main/resources/notebooks.yaml
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/testing/stubs/leo-proxy-api-stub.ts
Migrates Leo `setCookie` calls to the non-deprecated version.
The version of `setCookie` we were using is [deprecated](https://leonardo.dsde-prod.broadinstitute.org/#/proxy). The new version does not require the google project or runtime arguments.
The behavior should be exactly the same before and after this change.
To test this, open a notebook and observe that the Leo cookie named `LeoToken` is still set to the current access token.
The YAML changes were copied from [Leo's YAML](https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/resources/swagger/api-docs.yaml).
---
> [RW-1003][risk=no] Migrate Leo setCookie calls to the non-deprecated version

- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
We may accidentally use fields which exist - so it's better to remove them entirely.
---
> [risk=no][RW-10063] Remove deprecated fields from leonardo.yaml

- api/src/main/java/org/pmiops/workbench/api/DisksController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/stubs/disks-api-stub.ts
Wanted to rename this function, because in a separate PR, I would like to add a separate function that lists all disks in a workspace (not just disks owned by user). The function that I am renaming (listDisksInWorkspace) is ambiguous when we have functions. I am renaming the existing function to listOwnedDisksInWorkspace. I am open to different names if you prefer something different.
Tested by starting a runtime a viewing that the cost in the runtime tab are properly loaded. This indicates that the diskstore is being properly loaded.
---
> [RW-9990][risk=no]Updated controller function name in order to allow for more specificity in upcoming disk controller functions.

- e2ev2/src/utils.js
- e2ev2/tests/new-user-satisfaction-survey.test.js
- e2ev2/tests/sanity.browser.test.js
- e2ev2/tests/workspace-analysis.test.js
- e2ev2/tests/workspace-create.test.js
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/with-leo-cookie.spec.tsx
- ui/src/app/components/with-leo-cookie.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/routing/app-routing.tsx
- ui/src/app/utils/authentication.tsx
Periodically refreshes the Leo cookie to match Terra's implementation. This removes our reliance on the [Jupyter auth extension](https://github.com/DataBiosphere/terra-docker/blob/c762c950896983e760015460ab9a29ab9411e249/terra-jupyter-base/custom/google_sign_in.js).
[This thread](https://broadinstitute.slack.com/archives/CA3NP1733/p1683126985418719) provides additional background info.
Unfortunately, this does not fully resolve the problem because there is still contention between the extension and our implementation. To completely fix the bug we will need to remove our reliance on the extension. After merging this, I will find a way to remove the contention with the extension (Terra is not impacted by this contention but I haven't investigated why yet) or deprecate the extension …
> [RW-10031][risk=no] Periodically refresh the Leo cookie

- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
I want to use the LeoPdResponse mocking function in a service test as well, so I moved it to a more central location.
Ran DisksControllerTest.java locally in order to verify that the change works.
---
> [RW-9990][risk=no] Moved LeonardoListPersistentDiskResponse mocking to TestMockFactory.

- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
This shifts newDisk to TestMockFactory. I did this, because a future PR will make use of this. 
Ran api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java (the only current user of this method) and it passed.
---
> [RW-9990][risk=no] Moved newDisk into TestMockFactory.

- ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
Retry of #7650 for fixing review charts
After fix:
> [risk=no] Fix review graph styles

- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/ReviewQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortreview/util/ParticipantCohortStatusDbInfo.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCohortAnnotationEnumValue.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapperTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
Many number classes were using new _Class_ to construct that class from a string. Converted these to _Class_._valueOf_
---
> [RW-10035][risk=no] Removed several deprecation warnings.

- ui/src/app/components/popups.tsx
- ui/src/testing/stubs/cohort-review-service-stub.ts
- ui/tsconfig.json
Use es2022 target for TypeScript build and fix type check errors.
Manually tested the UI by clicking through and testing various components.
The es5 target is from 2011. Compiling to that version introduces extra code (e.g. `function () {}` instead of `() => {}` that is not necessary for our target browser (Chrome).
---
> [no ticket][risk=no] Change tsconfig target to es2022

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/EgressEventsAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/cohortreview/mapper/CohortReviewMapperTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
Test changes only.
I noticed after seeing #7694 that we were using `Long` suboptimally in some cases.
We generally want to use primitive `long` wherever possible, because it's non-nullable and uses fewer resources. 
---
> [risk=no][no ticket] Demote or adjust uses of Long in some tests

- api/build.gradle
- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java
I had an occasion to use these tools while helping a user, so I make some small fixes.
Tested by creating a runtime and running these commands locally:
```
./project.rb list-runtimes --project=all-of-us-rw-preprod --google-project terra-vpc-sc-7d68ac3f
./project.rb describe-runtime --project=all-of-us-rw-preprod --id terra-vpc-sc-7d68ac3f/all-of-us-45
./project.rb delete-runtimes --project=all-of-us-rw-preprod --ids terra-vpc-sc-7d68ac3f/all-of-us-45
```
---
> [risk=low][no ticket] Updates to ManageLeonardoRuntimes

- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.tsx
- ui/src/app/components/delete-persistent-disk-button.tsx
- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/rstudio-configuration-panel.spec.tsx
- ui/src/app/components/rstudio-configuration-panel.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
- ui/src/app/utils/user-apps-utils.tsx
- ui/src/testing/stubs/disks-api-stub.ts
Allows users to delete unattached PDs from GKE apps.
This completes the AC "User can delete disk which is currently not attached to APP" but does not complete the story.
I do not expect users to see this feature in prod since we do not allow them to detach disks yet.
There are two refactors in this PR that I considered extracting to separate PRs, but I don't think they make sense without this feature as context:
- Adding support for "panels" in the GKE app sidebar. I think the approach used by runtimes is pretty good and I mostly copied it. Unfortunately, actually sharing that logic would be a larger overhaul that I think is out of scope here.
- Extracting a simple `delete-persistent-disk-button` component from the runtime code
Manually testing:
- Create an app
- Using a direct API call, …
> [RW-9762][risk=no] Allow deleting unattached PDs from GKE apps

- api/src/main/java/org/pmiops/workbench/auth/DelegatedUserCredentials.java
- api/src/main/java/org/pmiops/workbench/auth/UserInfoService.java
- api/src/main/java/org/pmiops/workbench/cdr/CommonTestDialect.java
- api/src/main/java/org/pmiops/workbench/cdr/MySQLDialect.java
- api/src/main/java/org/pmiops/workbench/config/CommonConfig.java
- api/src/main/java/org/pmiops/workbench/config/WebMvcConfig.java
- api/src/main/java/org/pmiops/workbench/ras/OpenIdConnectClient.java
- api/src/test/java/org/pmiops/workbench/auth/DelegatedUserCredentialsTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/ParticipantCohortStatusDaoTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/CommandLineToolConfig.java
- api/tools/src/main/java/org/pmiops/workbench/tools/GenerateImpersonatedUserTokens.java
This fixes the remaining warnings visible with:
```
ADD_XLINT_DEPRECATION=1 ./gradlew clean compileTestJava compile__tools__Java
```
with the following exceptions:
- warnings in Swagger-generated code
- warnings within our own code
There is a separate ticket for fixing the Swagger-generated code. Warnings within our own code are not as risky since we will not be blocked from upgrading libraries due to using deprecated features.
Some testing thoughts described inline.
---
> [no ticket][risk=low] Fix some deprecation warnings

- api/build.gradle
Addresses the warning:
```
2023-05-18 12:06:14.903:WARN:oeja.AnnotationParser:qtp1150284200-39: org.apache.oltu.oauth2.common.OAuth$ContentType scanned from multiple locations: jar:file:///Users/dmohs/b/r/aou/gc/api/build/exploded-api/WEB-INF/lib/org.apache.oltu.oauth2.common-1.0.1.jar!/org/apache/oltu/oauth2/common/OAuth$ContentType.class, jar:file:///Users/dmohs/b/r/aou/gc/api/build/exploded-api/WEB-INF/lib/org.apache.oltu.oauth2.client-1.0.1.jar!/org/apache/oltu/oauth2/common/OAuth$ContentType.class
```
that occurs when running:
```
./gradlew appengineRun
```
---
> [no ticket][risk=no] Fix warning

- api/config/config_local.json
- api/config/config_test.json
This reverts commit 73ab32dafba6d5c89ca67f6c3a75bb41c3140b2d.
This upgrade causes Hail and Cromshell to stop working.  Reverting while we figure out why and how to fix.
https://precisionmedicineinitiative.atlassian.net/browse/RW-10154
https://precisionmedicineinitiative.atlassian.net/browse/RW-10159
My main purpose in this PR is to unblock the release.  I want to observe a successful nightly test run after this merges.
---
> [risk=low][RW-10154][RW-10159] Revert the docker upgrade to 2.1.20 in Local and Test

- e2e/app/text-labels.ts
- e2e/tests/notebook/notebook-create-python.spec.ts
- e2e/tests/notebook/notebook-snippets.spec.ts
- ui/src/environments/environment-type.ts
Followup to #7700 - make test more flexible so it passes for both docker image versions (2.1.15 and 2.1.20).  We regressed on this when we reverted the docker image.
I ran the 2 relevant tests locally and they passed.
---
> [no ticket][risk=no] e2e: Make Python kernel name check more flexible

- .github/CONTRIBUTING.md
The PR title parser we use requires the security risk to appear **first** in the title, before JIRA tickets.
---
> [risk=no][no ticket] Accurately describe how our JIRA/release process parses PR titles

- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoCustomEnvVarUtils.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
Those env vars are missing in GKE APP but available in Runtime
- `GOOGLE_PROJECT` and `OWNER_EMAIL` is required for dataset builder generated query.  Having those two we can easily copy the generate code from Jupyter to RStudio
- `WORKSPACE_NAME` is required by Leo to look up which app belongs to which user within one workspace.  Confirmed it is the firecloud name in Jupyter in terra-ui
---
> [no ticket][risk=no] Add missing env vars that is required for GKE APP

- api/tools/src/main/java/org/pmiops/workbench/tools/CommandLineToolConfig.java
This was removed in #7698 to fix a deprecation warning.  This restores it, replacing the deprecated `com.google.api.client.http.apache.ApacheHttpTransport` with the non-deprecated `com.google.api.client.http.apache.v2.ApacheHttpTransport`.
I need this because it's breaking my in-progress updates to DeleteWorkspaces.
---
> [risk=low][RW-10024] Restore HttpTransport bean to CommandLineToolConfig

- ui/src/app/pages/signed-in/inactivity-monitor.tsx
- ui/src/app/utils/analytics.ts
This will start track user inactivity logout in Google analytics 
---
> [RW-10186][risk=low] Start tracking user inactivity logout usage

- api/src/main/resources/shibboleth.yaml
Another success from https://editor.swagger.io/
To test:
1. Run local API+UI
2. Navigate to Data Access Requirements in the UI
3A. If ERA Commons has not been completed
* complete it, and observe that the user now has a completed module in AoU 
3B. If ERA Commons has been completed
* delete the user's completed entry in the DB (user_access_module table, access_module_id = 1)
* reload the UI, and observe that the user now has a completed module in AoU 
---
> [risk=low][RW-10177] Upgrade shibboleth.yaml to OpenAPI 3

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
after https://github.com/DataBiosphere/leonardo/pull/3338, Leonardo introduced a new app type RSTUDIO, instead of the custom one with `descriptorPath`
---
> [RW-9950][risk=low] Switch to use RSTUDIO app type in Leo. 

- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.tsx
- ui/src/app/components/rstudio-configuration-panel.spec.tsx
- ui/src/app/components/rstudio-configuration-panel.tsx
Allows reattaching a detached PD to GKE apps (partially).
**Note: This does not currently work for RStudio** as outlined in [this thread](https://broadinstitute.slack.com/archives/CA3NP1733/p1685121296882289?thread_ts=1684953375.577249&cid=CA3NP1733). Once [this PR](https://github.com/all-of-us/workbench/pull/7730) is merged RStudio should start working with no changes needed here. Because RStudio is not in pre-prod yet, and this is an unlikely state to be in, I think it's OK to merge as-is but am open to waiting.
As mentioned in [this PR](https://github.com/all-of-us/workbench/pull/7692), manually testing this requires an API call. The only difference here is that instead of deleting the disk, you can re-create the app (use Cromwell).
Like the above PR, I will create a workbench-ux …
> [risk=no][RW-9762] Allow reattaching a detached PD to GKE apps

- ui/src/app/pages/runtimes-list.tsx
The Cloud Environments page in Terra adds a `role=creator` filter to the API calls that improve both the latency and the relevance of the information.
Deployed here for manual testing: https://pr-6-dot-all-of-us-workbench-test.appspot.com/runtimes
Compare to test or production to see difference in page load latency and results.
---
> [risk=no][no-ticket] Only show user's apps

- ui/src/app/components/resource-actions-menu.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/appAnalysis/app-files-list.tsx
I was confused about the `appsAnalysis` prop, so I renamed it to something that made more sense to me.  What do you think?
Observed no changes in the Data, Analysis, or New Analysis tabs, or Recent Resources.
---
> [risk=low][no ticket] Be explicit about menu button component

- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceAuthServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/CreateWgsCohortExtractionBillingProjectWorkspace.java
An Access Control List is... a list of access controls.  We generally care about a single **ACL** rather than multiple **ACLs**, but we often name them in the plural because lists _feel like_ they should be plural.  But no.
No functional changes expected.  I'm making a change to an ACL and I wanted to separate this PR from the actual change I wanted to make.
Tested by running local API+UI, and observing that unsharing a workspace does not affect its published status.
---
> [risk=low][no ticket] Rename the incorrect "acls" to "acl" in most cases

- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
- ui/src/app/pages/appAnalysis/app-files-list.tsx
Micro-optimization: we can check the file type before calling Terra or Google, letting us fail more quickly.
Tested by running Local API+UI and testing every changed method: preview Jupyter, preview Rstudio, and getKernel
---
> [risk=low] Fail faster for invalid file preview

- ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
This fixes the issue where sometimes the Data tab is not selected when initially navigating to a workspace.
Tested by running local UI and navigating to workspaces I have not visited in a long time (this seems to be the trigger) on Local->Test and Test.  I can cause the bad behavior in Test but not Local->Test.
---
> [risk=low][no ticket] Default to Data tab if the tabPath is not set

- e2e/app/sidebar/apps-panel.ts
- e2e/app/sidebar/cromwell-configuration-panel.ts
- e2e/app/sidebar/rstudio-configuration-panel.ts
- e2e/tests/nightly/gke-apps/rstudio.spec.ts
- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/apps-panel-button.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
Replaces the RStudio "Create" button with a "Settings" button. Changes the wording of the "Launch" button to "Open RStudio." As a bonus, this moves existing tooltip logic from the create button to the config panel.
This fixes [a bug](https://pmi-engteam.slack.com/archives/C0150CWF6FP/p1686073620949159?thread_ts=1686072650.884329&cid=C0150CWF6FP) with the in-progress story, RW-9762: RStudio apps with detached PDs could not be re-created from the expanded app. I thought it was easier to complete RW-9703 than add the additional complexity to support re-attaching disks from that button.
[Relevant workbench-ux thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1686164080573979).
I have manually run the Cromwell and RStudio create / delete e2e tests.
Demo: …
> [risk=no][RW-9703][RW-9762] Update RStudio buttons

- e2e/tests/datasets/dataset-export-r-notebook.spec.ts
Removes unnecessary E2E coverage.
This test was consistently failing in [a recent PR](https://github.com/all-of-us/workbench/pull/7759) of mine. However, the failing section doesn't seem relevant for this particular test so I investigated removing it instead of spending the afternoon debugging it.
We have [unit tests](https://github.com/all-of-us/workbench/blob/2446b9dc4f5adf3e392db0cba968716b2e8186db/ui/src/app/components/breadcrumb.spec.tsx#L42) that check the notebook name breadcrumb, although the coverage seems light. If we don't think that coverage is sufficient, we can add a new unit test specifically for notebook names.
The workspace link doesn't seem relevant for this test. Regardless, the line `await notebookPage.goDataPage();` [leverages the workspace …
> [risk=no][no ticket] Remove unnecessary E2E coverage

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Add WorkspaceService.getPublishedWorkspacesGroupEmail()
Tested manually by:
1. creating workspaces shared with the published-group and other users
2. duplicating these workspaces in the UI with "share with same collaborators" checked
3. observing that the duplicates were shared with the **user** collaborators but not the published group
I considered taking this opportunity to migrate a piece of controller business logic to a service, but I think I'll do it in a separate PR instead.
Whether or not this completes RW-9501 is an open discussion - but I think this change is worthwhile regardless.
---
> [risk=low][RW-9501] Don't publish cloned workspaces

- ui/src/app/pages/runtimes-list.tsx
After https://github.com/all-of-us/workbench/pull/7736 the "Hide resources you did not create" checkbox doesn't do anything.  This PR removes it from view.
Tested by viewing the Cloud Environments page as the same user on Test and Local->Test and observing that removing this checkbox was the only change.
Before
After
---
> [risk=low][no ticket] Hide the "hide" button and text on Cloud Environments

- ui/src/app/pages/workspace/workspace-wrapper.spec.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
Adds a multi-region bucket cost banner.
How I determined the exact cutoff date:
- [This PR](https://github.com/all-of-us/workbench/pull/6761) implements the update
- [This release tag](https://github.com/all-of-us/workbench/tree/v7-14-rc1) marks the PR for release
- [This slack message](https://pmi-engteam.slack.com/archives/C66DX9FD0/p1655213641787859) indicates the release was completed
- Then, I added one day since the release happened mid-day.
I manually tested this by modifying the creation time of a workspace.
[Relevant workbench-ux thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1686686866796819).
Screenshot:
---
> [risk=no][RW-9965] Add multi-region bucket cost banner

- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
I noticed the "# of other files" on the Workspace Admin page was always wrong: that's because we were only looking in the notebooks directory.  Now we look in all directories.
This screenshot shows correct counting and categorization for 6 files in a bucket, 2 managed notebooks and 4 other files:
1. `text.txt` in the root directory is not a notebook file
2. `anomaly.txt` in the `notebooks` directory is not a notebook file
3. `simple1.ipynb` is a notebook file in the right location, so it is a workbench-managed file 
4. `simple2.ipynb` is a notebook file in the right location, so it is a workbench-managed file 
5. `another.txt` in `notebooks/folder1` is not a notebook file
6. `Inside.ipynb` in `notebooks/folder1` is a notebook file, but it **isn't previewable or counted as …
> [risk=low][no ticket] Fix non-notebook count for WS admin page

- e2e/tests/notebook/notebook-writer-clone-workspace.spec.ts
Similar to https://github.com/all-of-us/workbench/pull/7755/files
we reuse the same workspace name for that test an cleanup daily. The ran time stuck in ERROR state this moring, and it breaks all following tests
---
> Use random workspace name

- ui/src/app/pages/data/cohort/attributes-page.tsx
Fixes issue in attributes sidebar where selecting a concept without making changes to the form fields of the current concept prevents the new attributes from loading.
---
> [DT-447][risk=no] Fix loading of attributes after initial load

- e2e/package.json
- e2e/yarn.lock
- e2ev2/package.json
- e2ev2/yarn.lock
- ui/package.json
- ui/yarn.lock
Force-upgrade semver to 7.5.2+ to resolve vulnerabilities in UI, e2e, and e2ev2.
We can't do a normal upgrade here because of transitive dependencies.
Ran Local->Test without any noticeable problems.  (Obviously not a comprehensive test)
---
> [risk=low][no ticket] Force-update semver to resolve vulnerabilities

- e2e/package.json
- e2e/yarn.lock
- ui/package.json
- ui/yarn.lock
The vulnerable `word-wrap` package is apparently abandoned, but a new forked package has the fix: https://github.com/jonschlinkert/word-wrap/pull/33
Similarly to #7783, we can't do a normal upgrade here because of transitive dependencies.
Ran Local->Test without any noticeable problems. (Obviously not a comprehensive test)
---
> [risk=low][no ticket] Force word-wrap resolution to resolve vulnerabilities

- api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
---
- Added table definition for `VISIT` domain in BigQueryDataSetTableInfo class
- Deployed locally and tested for
- fields displayed in dataset builder
- SQL generated in query preview 
---
> [DT-431-2][risk=no]Added VISIT domain table info

- ui/src/app/utils/access-utils.tsx
This change allows for api configuration to be loaded in the UI without having a corresponding value specified. This allows to implement new access modules more safely.
In order to test this, delete an existing module from  getAccessModuleConfig and add a print statement to getAccessModuleConfig to print the resulting config. Ensure that the values for requiredForRTAccess and requiredForCTAccess match the values that you would expect for the deleted module.
---
> [RW-10520][risk=no] Add default config for access modules in UI

- e2ev2/tests/workspace-analysis.test.js
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/appAnalysis/app-selector-modal.tsx
- ui/src/app/pages/appAnalysis/app-selector.spec.tsx
- ui/src/app/pages/appAnalysis/app-selector.tsx
- ui/src/app/utils/constants.tsx
- ui/src/app/utils/user-apps-utils.tsx
Thinking about the remaining steps before launching to Preprod to gain user feedback, I felt that the Choose an App modal should allow another choice besides Jupyter - otherwise why have it?
The action taken is the same as the Edit button on the R-file preview page:
* Open Config Panel if RStudio is not currently running
* Open RStudio in a new tab if RStudio is currently running
Not running:
Running:
---
> [risk=low][RW-9754] App selector for RStudio opens config panel

- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/components/runtime-configuration-panel/confirm-delete-environment-with-pd.tsx
While it **shouldn't** (currently) happen that we ever see a GKE app without an attached PD, it **does** happen in error scenarios.  This causes the app to crash when we load the "Confirm deletion with PD" panel with a missing disk.
Instead, call up the "Confirm deletion without PD" panel in all cases when a disk is missing.
---
> [risk=low][no ticket] Allow deletion of GKE apps without PDs

- e2e/tests/datasets/dataset-export-py-notebook.spec.ts
- e2e/tests/nightly/notebook/dataset-export-r-notebook.spec.ts
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/components/copy-modal.tsx
- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/analysis/interactive-notebook.spec.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/new-jupyter-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.spec.tsx
- ui/src/app/pages/appAnalysis/app-files-list.tsx
- ui/src/app/pages/appAnalysis/apps-file-list.spec.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/cohort/overview.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/constants.tsx
- ui/src/app/utils/resources.spec.tsx
- ui/src/app/utils/resources.tsx
Motivation: as part of the replacement of the old analysis tab, I'm considering a renaming of the tab and URL element from **notebooks** to something like **appFiles** or **analysis** because the Analysis tab will no longer be strictly dealing with notebooks.  This will be easier if there's a single constant to update.  So: as a first step, I'm making the "notebooks" tab name and UI url path element a constant (TODO: should these be coupled?) 
Possible future work: do the same for other tabs?
To test: change `NOTEBOOKS_TAB_NAME` from 'notebooks'  to something else and run it as Local->Test (make sure to hard-refresh your browser)
* do you see your string in the URL when you interact with notebooks and R files (preview only)?
* does everything still work?
---
- One or more …
> [risk=low][no ticket] Constify notebooks path in the UI

- e2e/app/page/notebook-page.ts
- e2e/app/page/notebook-preview-page.ts
- e2e/app/page/workspace-analysis-page.ts
- e2ev2/tests/workspace-analysis.test.js
- ui/src/app/components/breadcrumb-type.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/components/copy-modal.tsx
- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/analysis/interactive-notebook.spec.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/pages/analysis/new-jupyter-notebook-modal.tsx
- ui/src/app/pages/analysis/notebook-list.spec.tsx
- ui/src/app/pages/analysis/util.ts
- ui/src/app/pages/appAnalysis/app-files-list.tsx
- ui/src/app/pages/appAnalysis/apps-file-list.spec.tsx
- ui/src/app/pages/data/cohort/cohort-actions.tsx
- ui/src/app/pages/data/cohort/overview.tsx
- ui/src/app/pages/data/concept/concept-set-actions.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.spec.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/routing/workspace-app-routing.tsx
- ui/src/app/utils/constants.tsx
- ui/src/app/utils/resources.spec.tsx
- ui/src/app/utils/resources.tsx
- ui/src/app/utils/user-apps-utils.tsx
When the `showNewAnalysisTab` env-flag is true, use the "new" analysis tab instead of the old one.
Also change the URL path and breadcrumbs from "notebooks" to "analysis" to reflect the tab's new role for apps beyond Jupyter
Tested by running locally with both `showAnalysisTab` UI env flag states
* true -> the New Analysis Tab replaces the old one, and URL/Breadcrumbs say "analysis"
* false -> the old analysis tab remains.  URL/Breadcrumbs for notebooks say "notebooks"
---
Note that we are displaying the new analysis tab, not the old one.  Also the URL says `analysis` instead of `notebooks`
---
The breadcrumb also says Analysis instead of Notebooks
---
The tab name is now **View Analysis Files** (sorry my tab is too small to show it)
---
- One or more of the following is …
> [risk=low][RW-9754] Replace old analysis tab with new tab when FF is true

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
No downstream team needs us to send them this sensitive information about researchers, so let's stop adding it to the WRD.
We will not be dropping these fields from the BigQuery tables in the WRD (because we can't!) so it's safe to apply the API and BQ changes in any order.
BQ Terraform module change (descriptions only): https://github.com/all-of-us/workbench-terraform-modules/pull/43
TODO: terraform application in all environments
---
> [risk=low][RW-10592] Remove 6 researcher address fields from the WRD

- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
---
- Fixed bug in code when selecting individual-survey and another pre-paackaged concept set
**Bug**
- go to data set builder **Datasets**
- Under **Select Cohorts** Select `All Participants`
- Under **Select Concept Sets** Select `The Basics` 
- Click **CREATE DATASET**
- Click **ANALYZE**
- In the popup Click **SEE CODE PREVIEW**
Breaks with  and logs would show NullPointerException
This is fixed and works as expected:
Correct SQL is generated in the notebook:
---
> [DT-465][risk=no]bug in dataset builder surveys

- api/config/config_local.json
- api/config/config_test.json
- api/db/create_db.sql
---
- Tanagra integration with AoU for test deploy needs to have the following
- turn on enableTanagra flag for local and test env
- enhanced privileges for `workbench` user for `tanagra_db` so as to perform liquibase db changes for `tanagra_db`
---
> [No-Ticket][risk=no] Updated grants for workbench user for tanagra_db

- e2e/app/page/notebook-preview-page.ts
- e2e/app/page/workspace-analysis-page.ts
- e2e/tests/nightly/detachable-disk.spec.ts
- e2e/tests/nightly/gke-apps/cromwell.spec.ts
- e2e/tests/nightly/gke-apps/rstudio.spec.ts
- e2e/utils/timeout-constants.ts
The nightly test `nightly/detachable-disk.spec.ts` frequently times out after 30min because that's not really long enough for a test to create a Jupyter runtime twice.  Increased that test to 45 min.
Also started a new pattern for making the reasoning behind timeouts more explicit, by naming those timeouts.  Replaced a few instances of 15-min environment creation timeout with this new `environmentTimeout`
---
> [risk=no][no ticket] Bump detachable-disk timeout to 45min and add a few timeout constants

- api/src/main/java/org/pmiops/workbench/notebooks/NotebookUtils.java
- ui/src/app/components/rename-modal.spec.tsx
- ui/src/app/components/rename-modal.tsx
- ui/src/app/pages/analysis/notebook-resource-card.tsx
- ui/src/app/pages/analysis/util.spec.tsx
- ui/src/app/pages/analysis/util.ts
- ui/src/app/utils/constants.tsx
No functional changes - just renaming some code structures.
The RStudio application uses "notebook" to refer to .Rmd files and "script" to .R files.
---
> [risk=low][no ticket] Rename R "Notebook" and "File" to R "Script"

- ui/src/app/pages/admin/workspace/admin-workspace.tsx
- ui/src/app/utils/runtime-utils.tsx
I was looking at a workspace for an oncall ticket where there were several users' runtimes in a workspace.  It occurred to me that it would be useful to be able to distinguish these.
Before (include redundant Google Project info)
After
---
> [risk=low][no ticket] Add runtime creators to workspace admin page

- api/config/config_preprod.json
- ui/src/environments/environment.preprod.ts
This will launch RStudio and the new analysis tab in Preprod when it's included in a release.
No changes will be made to Prod.
---
> [risk=low][RW-9416][RW-9754] Set enableRStudioGKEApp and showNewAnalysisTab to true in Preprod

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/confirm-workspace-delete-modal.tsx
- ui/src/app/components/help-sidebar-icons.spec.tsx
- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/testing/default-server-config.ts
One step in removing the `enableCromwellGKEApp` feature flag which is now always true: remove logic where it is set to false.
Tested by running locally with no obvious problems.
---
> [risk=low][no ticket] Remove logic for the obsolete case where Cromwell is not enabled

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
The reporting cron for testing has not been running, because it has been taking too long. In an attempt at addressing this, I am changing our workspace reporting to only contain workspaces that are active (not deleted).
---
> [RW-10520][risk=no] Updated reporting to not handle deleted workspaces.

- api/build.gradle
- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/java/org/pmiops/workbench/tanagra/TanagraConfig.java
- api/src/main/resources/tanagra.yaml
- api/src/main/resources/workbench-api.yaml
This will allow the workbench API to call the Tanagra API and will expose the Tanagra url for iframe rendering. The UI can reference the Tanagra URL like so:
`serverConfigStore.get().config.tanagraBaseUrl`
---
> [DT-467][risk=no] - Part 1: adding tanagra api and exposing the tanagra url

- api/src/main/resources/workbench-api.yaml
- ui/package.json
- ui/src/app/pages/tanagra-dev/tanagra-dev.tsx
- ui/src/testing/default-server-config.ts
- ui/src/testing/stubs/cdr-versions-api-stub.ts
- Listen for events from `postMessage` api to hide Tanagra iframe
- Get correct Tanagra url from `serverConfigStore`
- Update iframe styles for a smoother transition to and from the workbench
- Add property `bigqueryDataset` to the `CdrVersion` object in `CdrVersionTiersResponse` to use as the Tanagra underlay
https://github.com/all-of-us/workbench/assets/40036095/908df294-25aa-4011-9fa6-00871d6ab259
---
> [DT-298][risk=no] Update style, navigation for Tanagra iframe

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/tanagra/TanagraConfig.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFakeImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/tanagra.yaml
Adding Tanagra API call to save a study after an AoU workspace is created. 
---
> [DT-467][risk=no] Adding Tanagra API call to save a study after an AoU workspace is created

- ui/src/app/pages/admin/user/admin-user-egress-bypass.tsx
When handling [this egress ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-10671) I needed to know the *time* of the end of the window, not just the date.  I was able to find that in the DB, but it will be much easier on this page.
Also updated some text and formatting.
Tested by running local UI, as seen here:
---
> [risk=no][no ticket] Show the time of egress bypass windows, not just the date

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
---
- Added new api endpoint for tanagra to call and get workspace access level for workspaceNamespace given user's Bearer Token
- Tested the api call locally through postman
---
> [DT-474][risk=no] Tanagra authz new AoU endpoint to get workspace access level

- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java
`exportDemoSurveyV2` is always true, and `queueName` is always `rdrExportQueue`
Tested by running locally and calling the rdrExport cron job on users with and without demographic surveys.
We can fully remove these after one release cycle: #7896
---
> [risk=low][no ticket] rm references to constant config/FFs in rdrExport

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Convert enzyme tests to RTL. As mentioned in eng sync, we are now converting tests on an as-modified basis.
This was mostly an exercise in how quickly I could convert a test while producing reasonable automation to do it again. As such, I don't think it's perfect RTL (in addition to me still learning RTL).
[I created a script](https://github.com/all-of-us/workbench/commit/e35261663493a3ed4793c756eefe5cc743752fdc) to automate some of this. However, the script is hacky and certainly imperfect; most of my time was spent fixing the harder-to-automate parts.
---
> [risk=no][RW-10368] Convert enzyme tests to RTL

- ui/src/app/components/inputs.tsx
- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Improve account-creation test quality. Follows https://github.com/all-of-us/workbench/pull/7899. I think we were overusing "container" and underusing "screen".
Adds a happy-path test. The test would break if, for instance, you added a new required field.
---
> [risk=no][RW-10368] Improve account-creation test quality

- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
> [RW-10530][risk=no] Use Service account credentials to get notebook files

- ui/src/app/pages/data/cohort/overview.tsx
Fixes issue where only cohort groups in the `includes` column were getting temporal validation.
> [DT-508][risk=no] Fix temporal validation for excludes groups

- api/db-cdr/generate-cdr/bq-schemas/prep_pfhh_mapping.json
- api/db-cdr/generate-cdr/bq-schemas/prep_pfhh_non_answer.json
- api/db-cdr/generate-cdr/bq-schemas/prep_pfhh_remove_from_index.json
- api/db-cdr/generate-cdr/build-search-all-events.sh
Adding static tables for pfhh mappings. This PR will pull csv files during the indexing build from all-of-us-workbench-private-cloudsql bucket:
1. prep_pfhh_mapping.csv
2. prep_pfhh_non_answer.csv
3. prep_pfhh_remove_from_index.csv
Also added a distinct keyword when inserting observation data into cb_search_all_events to remove duplicates.
> [DT-489][risk=no] adding static tables for pfhh mappings

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
```
curl -X 'POST' \
'http://localhost:8081/v1/workspaces/aou-rw-local1-a605b797/apps' \
-H 'accept: */*' \
-H "Authorization: Bearer $(gcloud auth print-access-token)" \
-H 'Content-Type: application/json' \
-d '{
"kubernetesRuntimeConfig": {
"autoscalingEnabled": "false",
"machineType": "n1-standard-4",
"numNodes": "1"
},
"appType": "SAS",
"persistentDiskRequest": {
"diskType": "pd-standard",
"size": 100
}
}'
List App response:
```
---
> [RW-10348][risk=low] Support create SAS app in RW

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
Remove all code references to queueName and exportDemoSurveyV2.
#7882 has been released, so it's now safe to merge this.  Tested locally by running an RDR Export successfully.
---
> [risk=low][no ticket] Fully remove the deprecated rdrExport FF/config values

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/resources/workbench-api.yaml
Remove all code references to 
* FF enableResearchPurposePrompt (API) / enableResearchReviewPrompt (UI)
* workspace.needsReviewPrompt
#7874 has been released, so we can now merge this.  Tested locally by updating a workspace.
---
> [risk=low][no ticket] Fully remove enableResearchReviewPrompt and needsReviewPrompt

- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
Attempts to fix the RTL performance flake described [in Slack](https://pmi-engteam.slack.com/archives/C7JUTPQLE/p1693936544686529?thread_ts=1693936143.040119&cid=C7JUTPQLE).
I had run into performance issues using `type` when originally converting these tests, and needed to change some instances to a `click` / `paste` interaction, instead. This PR changes all instances to that, since none of the tests specifically depend on "typing."
This decreases the runtime of the two tests in question from 1.7 seconds to 0.9 seconds on my machine. As a bonus, I updated the rest of the file, decreasing the total file runtime from 12.5 seconds to 6.8 seconds.
I wasn't able to reproduce the flake locally, since those tests ran in under 5 seconds on my machine. If this issue persists I'll dig deeper.
--- …
> [risk=no][no ticket] Fix RTL performance flake

- ui/src/app/components/configuration-panel.spec.tsx
- ui/src/app/components/configuration-panel.tsx
- ui/src/app/components/cromwell-configuration-panel.spec.tsx
- ui/src/app/components/cromwell-configuration-panel.tsx
- ui/src/app/components/environment-cost-estimator.tsx
- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-panel.tsx
- ui/src/app/components/gke-app-configuration-panels/disabled-cloud-compute-profile.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/rstudio-configuration-panel.spec.tsx
- ui/src/app/components/rstudio-configuration-panel.tsx
- ui/src/app/components/runtime-configuration-panel/confirm-delete-environment-with-pd.tsx
- ui/src/app/components/runtime-configuration-panel/confirm-delete-unattached-pd.tsx
- ui/src/app/components/runtime-configuration-panel/confirm-delete.tsx
- ui/src/app/components/spinners.tsx
Move the bulk of the Cromwell and RStudio configuration panels to a new component CreateGKEAppPanel, in preparation for adding SAS.  Tested locally by running Local->Test
Also convert the relevant UI UTs from Enzyme to RTL.
Naming suggestions welcome.
Does not complete RW-9836 because this does not add SAS!
---
> [risk=low][RW-9836] Make Cromwell and Rstudio config panels generic

- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/components/gke-app-configuration-panels/create-cromwell.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-cromwell.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/components/gke-app-configuration-panels/create-rstudio.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-rstudio.tsx
This is a followup to https://github.com/all-of-us/workbench/pull/7921
GkeAppConfigurationPanel is a *container* for various types of panel content.  The default content for all GKE Apps is "create" so more appropriate names for the these panel content components are **CreateCromwell** and **CreateRStudio**.
Tested by observing these panels on Local->Test
---
> [risk=low][RW-9836] Rename GKE app creation inside-panel components to "create"

- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Add isServiceAccount test. This method was made public in [this PR](https://github.com/all-of-us/workbench/pull/7926), so I think a small test is appropriate.
---
> [risk=no][RW-10361] Add isServiceAccount test

- ui/package.json
- ui/yarn.lock
I was attempting to fix something else and found another way, but decided to proceed with this change anyway.
Tested by building and running locally and just clicking around a bit.
Our yarn.lock file already selects the indicated version, so this change acts like a comment and should have no effect on functionality.
---
> [risk=no][no ticket] Bump version of typescript

- api/db/changelog/db.changelog-226-compliance-training-verification.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/access/AccessModuleService.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/ComplianceTrainingVerificationDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbComplianceTrainingVerification.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
Track the system we used to verify a user's compliance training status. Currently, this is always Moodle. This will be used as we transition to Absorb to determine whether a user has already used Moodle or not. Once all users are using Moodle, it's possible we may remove this table.
Schema:
```
MariaDB [workbench]> desc compliance_training_verification;
+-----------------------------------------+-------------------------+------+-----+---------+----------------+
| Field                                   | Type                    | Null | Key | Default | Extra          |
+-----------------------------------------+-------------------------+------+-----+---------+----------------+
| compliance_training_verification_id     | bigint(20)              | NO   | PRI | NULL    | auto_increment |
| …
```
> [risk=no][RW-10361] Track compliance training verification system

- .circleci/config.yml
- README.md
- api/docs/developer-system-initialization.md
- ui/README.md
- ui/libproject/devstart.rb
Narrows all usage of the Fontawesome license to use the key only rather than downloading a whole .npmrc file.
Not testing locally since CircleCI was primary failure mode.
Readme files updated and merged where appropriate.
---
> [risk=no][RW-10815] Repair all instances of .npmrc usage and update some Readme files

- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
Add a `setAnalysisConfig()` call in a `useEffect()` to ensure it is triggered when `gcePersistentDisk` changes.
I don't know why this is necessary, or how to write a test for it.
To manually test
* create a GCE runtime
* delete it but keep the PD
* refresh the UI
* open the Runtime Config Panel
* create a new runtime (which will implicitly use the existing PD)
* observe that it succeeds - and specifically that it does so by calling create-runtime with a named Persistent Disk instead of null
---
> [risk=low][RW-10794] Set analysisConfig in Runtime panel in useEffect()

- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/test/java/org/pmiops/workbench/cdr/dao/CBCriteriaDaoTest.java
- ui/src/app/pages/data/cohort/tree-node.tsx
Remove old code for PFHH surveys. The index is now completely updated and added all the non-answers so we can now query this survey just like all the other surveys.
NOTE: will not merge this PR until release goes out this week.
---
> [DT-490][risk=no] Remove old code for PFHH survey

- api/snippets-menu/aou-snippets-menu.js.template
snippet menu is broken by pandas menu due to https://github.com/ipython-contrib/jupyter_contrib_nbextensions/commit/d0fb8668c1158fd17a803ebd3fda0b01014b7021
Support is okay with just remove it for now.
> [RW-10827][risk=no] Remove pandas from snippet menu

- api/config/config_local.json
- api/config/config_test.json
[RW-10288 Upgrade python version for terra-jupyter-aou docker image](https://precisionmedicineinitiative.atlassian.net/browse/RW-10288?atlOrigin=eyJpIjoiOGVhNWIxMmEwM2Y4NDNmYzljZGMwMzllMGNkMTE4MjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
@LizBaldo has done a bunch tests already. So I think we should be ok to switch in local and test...Once nightly tests pass tmr, then we can update the rest of the envs
---
> [risk=moderate] RW-10288 update jupyter image version for local and test env

- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/configuration-panel.tsx
- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/components/gke-app-configuration-panels/create-cromwell.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/components/gke-app-configuration-panels/create-rstudio.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-sas.spec.tsx
- ui/src/app/components/help-sidebar.tsx
I got increasingly frustrated by needing to go to the Apps Panel to delete apps while testing SAS.  As I recall, users often had that confusion as well.  Now we match Jupyter behavior by having a link in the configuration panel itself.
---
> [risk=low][RW-10290] Add Delete Environment links to GKE App Configuration Panels

- deploy/bootstrap-docker.sh
- deploy/docker-compose.yaml
To test:
```
deploy/project.rb deploy \
--project=foo \
--account=deploy@bar.gserviceaccount.com \
--git-version=local-source
```
The `local-source` version avoids the standard "clone from known version" behavior.
---
> [risk=no][no ticket] Add option to use local code for deploy

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserGeneralDiscoverySourceColumnValueExtractor.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/UserPartnerDiscoverySourceColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java
Tested the query using prod DB and the query works for me. 
One thing to hightlight is in ReportingQueryService, we only populate `otherText` field when choosing `OTHER` enum. 
---
> [RW-10626] [risk=low] Backend change to upload user creation questions into WDR BQ

- ui/src/app/pages/admin/user/admin-user-profile.tsx
- ui/src/app/pages/analysis/notebook-list.tsx
- ui/src/app/pages/profile/profile-component.tsx
Replaced Icons:
1. **faCircleInfo**: (used in profile page)
**Change**: 
**Original**
2. **falink** ( used in user admin)
change
original:
4. faExclamationTriangle:
change:
original:
5. faPlusCircle
change:
original
There are just two pro icons left in our code base:
1. faLockAlt: 
> The alternative in free is slightly different. 
> It is used in workspace card and workspace admin page for locked workspaces
6. faLocationCircle:
> Does not have a free version
> Used in genomics extraction
---
> [noTicket][risk=no] Use free fortawesome icons vs pro

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisService.java
- api/src/test/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisServiceTest.java
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/utils/user-apps-utils.tsx
Use the SAS localization pattern (for `.sas`) instead of using RStudio's for all GKE apps, and call the localization endpoint when opening a SAS app.
Tested locally by saving SAS files in the app and observing they appear in the Analysis tab (after some delay), as well as adding files to the bucket and observing that they are copied into the SAS app VM
---
> [risk=low][RW-10998][RW-10934] Use the correct delocalization pattern for SAS and enable in UI

- ui/src/app/pages/admin/workspace/admin-workspace.tsx
- ui/src/app/pages/admin/workspace/basic-information.tsx
- ui/src/app/pages/admin/workspace/cloud-storage-objects.tsx
- ui/src/app/pages/admin/workspace/cloud-storage-traffic-chart.tsx
- ui/src/app/pages/admin/workspace/cohort-builder.tsx
- ui/src/app/pages/admin/workspace/collaborators.tsx
- ui/src/app/pages/admin/workspace/file-table.tsx
- ui/src/app/pages/admin/workspace/research-purpose-section.tsx
- ui/src/app/pages/admin/workspace/workspace-info-field.tsx
I'm working on some updates to workspace-admin, and my first step is to refactor the page to make it easier to update.  However, that is proving to be a larger task than I expected, so I'm splitting it into smaller pieces.
This PR takes the simple (minimal-logic) display sections and converts them to components.  No changes are expected here, and the new components are simple enough that I don't think adding tests would be useful.
Tested locally - works the same as the existing page
---
> [risk=low][no ticket] Break the simple parts of admin-workspace into components

- ui/src/app/pages/data/data-set/dataset-page.tsx
This changes calls to `getValuesFromDomain()` from setting a query parameter `conceptSetId=null` where the ID is null to leaving out the parameter entirely.
The new syntax caused the API to respond with 500s when creating datasets with Prepackaged Concept Sets with the underlying error of 
```
MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "null"
````
My guess is that this behavior changed with https://github.com/all-of-us/workbench/pull/7953.
The old syntax (which we can observe on Staging+, which continues to work) is `conceptSetID=`
Tested on Local->Test by creating Datasets with Prepackaged and standard Concept Sets.
---
- …
> [risk=low][no ticket] Set prepackaged concept set IDs to undefined instead of null

- api/src/main/resources/workbench-api.yaml
**username** attribute in Profile object was marked readonly, because of which the value was not being set in request before sending to API
---
> [noTicket][risk=medium]Account creation failing as username is not being set

- ui/src/app/pages/login/account-creation/account-creation.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation.tsx
Account creation only accepted the US for valid countries.  Now it accepts all countries in the dropdown, as well as arbitrary OTHER text.
Tested by trying various combinations.
---
> [risk=low][no ticket] Allow choosing countries besides US when creating an account

- ui/package.json
- ui/src/assets/generation/runtime.mustache
Updated template of runtime in order to not make use of ResponseError.
I successfully created a runtime in a workspace that had not had one before.
---
> [RW-10655][risk=none] Override runtime mustache in order to avoid using ResponseError.

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/data/cohort/cohort-search.tsx
- ui/src/app/pages/data/cohort/utils.ts
---
- Implemented `has_ehr_data` selection under `Demographics`
- Added SQL to get counts for  `has_ehr_data`
- Indexing build nedds to be run in test environment after this PR is merged
- I have manually tested the change to `cd_criteria_menu` in local docker environment  with
- `"enableHasEhrData": true` 
https://github.com/all-of-us/workbench/assets/4452480/49cb466c-8bbc-4f50-8fd2-220fb16456dd
- `"enableHasEhrData": false`
---
- [] This change modifies the UI, so I have taken screenshots or recordings of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P).
> [DT-538][risk=no] Implement has_ehr_data for cohort builder criteria

- api/build.gradle
- api/src/integration/java/org/pmiops/workbench/AbsorbAcceptanceTest.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClient.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
- api/src/main/resources/absorb.yaml
Add Absorb API spec.
This will be used to query for course completion information instead of Moodle. As of now, it is unused.
This also adds an acceptance test for Absorb that hits actual Absorb endpoints, which I used while creating the spec. If this seems unnecessary, unhelpful, or likely to flake, then I will remove it.
I found the fastest development loop here to be:
- Change absorb.yaml
- Run `./gradlew generateSwaggerCodeAbsorb`
- Run the acceptance test
Notes from a session with the Absorb API support team:
- We should use "enrollments," not completion "certificates."
- Certificates map to enrollments, not courses, provide no additional information that we would use.
- Enrollments make re-enrollments clearer (see below)
- Certificates have a delay and are tied to enrollments, not …
> [risk=no][RW-10361] Add Absorb API spec

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingService.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/testing/stubs/profile-api-stub.ts
Redirect users to Absorb for initial training.
This PR only implements redirecting users to the right place, **not** the full flow. Support for the synchronization endpoint will be added in a future PR.
This can be manually tested by clicking on either training access module when the feature flag is set to true and the user has no training modules completed. To actually access Absorb, if desired, there are currently some additional steps: See "To manually test this..." in https://github.com/all-of-us/workbench/pull/7968.
I have `This change modifies the UI` unchecked because the feature flag is disabled in all environments.
This PR does not indicate which course a user should take. Ideally, we would link directly to courses, however, this has proven difficult to combine with SSO. If we …
> [risk=no][RW-10361] Redirect users to Absorb for initial training

- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/gke-app-configuration-panels/create-sas.spec.tsx
Chat with SAS demo users offline. They data they would need to pull is 138GB. Increase that to 250GB for now. In the future we would support customize PD size. 
---
> [no ticket][risk=no] Increase SAS default disk size to 250. 

- ui/src/app/utils/leo-runtime-initializer.spec.tsx
- ui/src/app/utils/leo-runtime-initializer.tsx
- ui/src/app/utils/runtime-presets.ts
- ui/src/testing/stubs/runtime-api-stub.ts
This is part of my effort to understand runtime logic, as well as fixing the bug which can create GCE VMs without PD.  This will probably make more sense in the context of that change, which is coming soon.
---
> [risk=low][RW-10991] Extract and test throwRuntimeNotFound() to better understand runtime logic

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
When a new user is created, this adds "Absorb_external_department_ID" as a custom GSuite field.
The need for this is outlined in [this section of the Absorb SSO setup docs](https://docs.google.com/document/d/1xgcvow0xPL6K4vxyM3PVlW-1E5Ye3X1Y5wZSD5rrPlc/edit?resourcekey=0-q_6-vFevph2piD88EfX-1g#bookmark=id.ekjh4jia8c6). In addition to reviewing this PR, I ask that the reviewing developer also reviews that document in it's entirety to gain context.
This PR builds on the [comparable work done for Moodle](https://docs.google.com/document/d/1J87xu7xSTm2q02Xaxb_XPfSBYPd-Ok1hIdg9jl2kUBg/edit#bookmark=id.bryj4yqqvh4f).
To manually test this, create a new user and follow [these instructions](https://docs.google.com/document/d/1xgcvow0xPL6K4vxyM3PVlW-1E5Ye3X1Y5wZSD5rrPlc/edit?resourcekey=0-q_6-vFevp …
> [risk=no][RW-10895] Configure Absorb department external IDs for new users

- ui/src/app/pages/data/cohort/cohort-page.tsx
- ui/src/app/pages/data/cohort/custom-funnel.tsx
- ui/src/app/pages/data/cohort/overview.tsx
Fix bugs with initial funnel plot:
- Disable funnel icon if less than 2 groups
- Don't call for intersection counts if only 2 groups, just use largest group count and total count
- Clear group count store when switching cohorts, was causing infinite spinners in plot
> [no ticket][risk=no] Fix funnel plot issues

- ui/src/app/components/data-user-code-of-conduct.tsx
- ui/src/app/pages/access/controlled-tier-card.tsx
- ui/src/app/pages/access/data-access-requirements.spec.tsx
- ui/src/app/pages/access/data-access-requirements.tsx
- ui/src/app/pages/access/identity-help-text.tsx
- ui/src/app/pages/access/login-gov-help-text.tsx
- ui/src/app/pages/access/module.tsx
- ui/src/app/pages/access/modules-for-annual-renewal.tsx
- ui/src/app/pages/admin/user/admin-user-common.tsx
- ui/src/app/pages/admin/user/admin-user-profile.tsx
- ui/src/app/pages/profile/profile-component.tsx
- ui/src/app/routing/guards.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
- ui/src/app/utils/code-of-conduct.tsx
It's possible to get into a state where the API reports DUCC to be complete, but the API also blocks access because the DUCC is either missing a required DUCC version field or has an outdated one.  It's probably worth discussing how to improve the correctness of the API, but it was already our belief that this was the case, so my assumption is that this would be a more involved fix.  This PR instead takes the approach of aggregating this information in the UI and treating the inconsistency as **incomplete**, to allow users and admins to have a more correct picture of DUCC compliance even when the API is inconsistent.
This PR makes access module completion (and bypass) checking in the UI more consistent by centralizing those checks, and adds an extra check for a correct DUCC version for …
> [risk=low][RW-11048][RW-10764] Update UI module date logic to treat the wrong DUCC version as incomplete

- ui/src/app/pages/workspace/workspace-wrapper.tsx
Workspace: https://github.com/all-of-us/workbench/blob/main/ui/src/app/pages/workspace/workspace-wrapper.tsx#L137
is populated by `withCurrentWorkspace`. 
But `withCurrentWorkspace` returns previous workspace.  
The change is small, most lines are done by yarn lint. Is that expected? 
---
> [RW-11062][risk=low] Fix currentWorkspaceStore has incorrect (previous workspace)

- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
- ui/src/app/pages/data/cohort/utils.ts
- ui/src/app/pages/data/data-set/dataset-page.spec.tsx
- ui/src/app/pages/data/data-set/dataset-page.tsx
---
- Added prepackaged conceptSet for Demographics to get participants who have EHR data
- Updated to add new overloaded name/enum `Domain.PERSON_HAS_EHR_DATA` for `Domain.PERSON`
- Updated UI for functionality to choose either `Demographics` or `Demographics Has EHR Data`
https://github.com/all-of-us/workbench/assets/4452480/16a77211-0e34-4c08-aee4-a0acd6d782e9
---
> [DT-514][risk=no] Add person has ehr data to prepackaged conceptset

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/AbsorbAcceptanceTest.java
- api/src/main/java/org/pmiops/workbench/absorb/AbsorbService.java
- api/src/main/java/org/pmiops/workbench/absorb/AbsorbServiceImpl.java
- api/src/main/java/org/pmiops/workbench/absorb/Enrollment.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingService.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
When a user who has never completed a training using Moodle (i.e. new users) takes a training they now use Absorb. This is enabled in the local, test, staging, and stable environments.
One missing feature: an indication of which course the user should take when they reach Absorb. This topic is complex enough that I think it warrants a separate ticket, so I will split that out later today with more detail. I'll share this with product/ux when we're ready to discuss that.
Additionally, this only handles _initial training_. Renewal is not supported yet. Therefore, after one year, we would start to see errors. We [plan to work on renewal](https://precisionmedicineinitiative.atlassian.net/browse/RW-10362) immediately after releasing this, so I think this is OK for now. …
> [risk=no][RW-10361] Use Absorb for initial training

- api/src/main/java/org/pmiops/workbench/absorb/AbsorbServiceImpl.java
Refresh Absorb api responses every request. This is a partial fix that will help anyone running into data access issues on the test environment, a full fix will follow.
See [this thread](https://pmi-engteam.slack.com/archives/C0150CWF6FP/p1697040108376699) for details.
The root cause is that injected Spring `@Service` object instances are shared across requests. Therefore, state within the instance is shared across requests. In this case, the Absorb user id was being cached across requests, leading to data leakage across accounts.
Steps to reproduce the bug:
- Create a new user
- Complete RT training using Absorb
- Create a second user
- Visit the data access page
Expected: RT training is incomplete
Actual: RT training is complete
---
- One or more of the following is …
> [risk=no][no ticket] Refresh Absorb api responses every request

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/integration/java/org/pmiops/workbench/google/DirectoryServiceImplIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
Remove Absorb department ID FF introduced in [this PR](https://github.com/all-of-us/workbench/pull/7968), which has now been [enabled in all environments](https://github.com/all-of-us/workbench/pull/8029).
I tested this using the relevant integration test as described in [this comment](https://github.com/all-of-us/workbench/pull/7968/files#r1333414957).
---
> [risk=no][RW-11077] Remove Absorb department ID FF

- .circleci/config.yml
- api/src/main/java/org/pmiops/workbench/ras/RasLinkConstants.java
Updated CircleCI test coverage job to upload coverage report to Codacy.
I utilized Codacy's Circle CI orb: https://circleci.com/developer/orbs/orb/codacy/coverage-reporter
This upload requires a Codacy token that can be found here: https://app.codacy.com/gh/all-of-us/workbench/settings/coverage
The token is stored as an environment variable in our Circle CI project: https://app.circleci.com/settings/project/github/all-of-us/workbench/environment-variables
Logs showing successful upload:
```
--> Actual checksum
d61e58a04f56811bf54f3ae2d4bfaabc453b3b80ec19d9d42b243968d9302aa2857b2233e5a9aa75f48a2b9455bae6f1fadbbb07f1471aa86ce385cb1b29ddcf  codacy-coverage-reporter-linux
codacy-coverage-reporter-linux: OK
2023-10-13 14:06:51.863Z  info [ConfigurationRules] API base URL: …
```
> [RW-11086][risk=no] Upload test coverage to Codacy

- api/src/integration/java/org/pmiops/workbench/AbsorbAcceptanceTest.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
The Absorb settings were changed to show the CT training after RT training is complete. This helps ensure users take the correct course when first visiting Absorb. This PR accounts for that breaking change, and documents current API behavior via acceptance tests.
I didn't manually test this as I felt the `testSyncComplianceTrainingStatus_Absorb_DoesNothingIfNoCoursesComplete` test effectively identified the error once the stub methods were updated, and manual tests of Absorb are very slow (they require creating a new account each time). Let me know if you think I should.
Steps to reproduce the bug:
- Create a new user
- Bypass all modules except the training ones
- Log into Absorb
- Do not complete any trainings
- Sync training
Expected:
- The API call succeeds
Actual:
- The API call …
> [risk=no][no ticket] CT training enrollment happens after completing RT

- api/src/main/java/org/pmiops/workbench/absorb/AbsorbServiceImpl.java
- api/src/main/java/org/pmiops/workbench/absorb/Enrollment.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
Add Absorb-specific logging for debugging purposes. I think this provides enough information to identify Absorb-side errors or reproduce workbench-side errors.
Example output obtained by running this locally:
```
[Tue Oct 17 14:45:22 EDT 2023] INFO: org.pmiops.workbench.interceptors.AuthInterceptor preHandle - peterlavigne_local_001@fake-research-aou.org logged in 
[Tue Oct 17 14:45:22 EDT 2023] INFO: org.pmiops.workbench.compliancetraining.ComplianceTrainingServiceImpl syncComplianceTrainingStatus - Syncing compliance training status for user peterlavigne_local_001@fake-research-aou.org 
[Tue Oct 17 14:45:22 EDT 2023] INFO: org.pmiops.workbench.compliancetraining.ComplianceTrainingServiceImpl syncComplianceTrainingStatusAbsorb - Using Absorb to sync compliance training status. 
[Tue Oct …
```
> [risk=no][no ticket] Add Absorb-specific logging

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- ui/src/app/pages/runtimes-list.tsx
This change adds labels when creating persistent disks so the disks may be associated with workspaces on the Cloud Environments Page. Without this association, the page's functionality is degraded.
Before:
After:
I manually deleted and re-created a runtime with a persistent disk to see the result of the change.
---
> [risk=no][RW-11144] Associate PDs with workspaces on Cloud Environments Page

- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- ui/src/app/pages/runtimes-list.tsx
Before:
After:
Tested manually by creating an RStudio app and observing the difference.
---
> [risk=no][RW-11144] Fix GKE apps and disks on Cloud Environments Page

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
I happened to notice some gaps in NPE prevention while looking at this code.  No expected changes except for an edge case: if a GceWithPDConfig is passed to CreateRuntime without a PD Request (an invalid scenario), it will now throw a BadRequestException instead of a NullPointerException.  I'm not aware of any UI paths that would lead to this situation. 
Tested locally: createRuntime continues to work 
---
> [risk=low][no ticket] Add a little more null-safety to API createRuntime()

- api/config/config_preprod.json
- api/config/config_stable.json
- api/config/config_staging.json
---
- turned on `featureFlag: enableHasEhrData` in staging, stable and preprod environments.
---
> [DT-565][risk=no] turned on enableHasEhrData in staging, stable and preprod envs

- api/config/config_prod.json
Reporting pipleline is broken with error "reporting_test not found". It is broken by this line: https://github.com/all-of-us/workbench/commit/57965bea08a782652d18a90f9fe1e64b2068f673#diff-1c2c731d0766b3759fa81a782d1af209b835d46ec2a8bf5b7a8803b541d20e67R151
It is a copy paste error from test env's config
---
> [RW-11244][risk=low] Fix reporting dataset name for prod

- api/db-cdr/generate-cdr/build-cb-variant-attribute-table.sh
Adding VAT tables into Data Apps indexing build
---
> [DT-558][risk=no] Adding VAT tables into Data Apps indexing build

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Researchers who have signed version 3 of the DUCC are non-compliant: newer versions have existed for more than a year on Prod.
Here we can see that we switched to v4 in Feb 2022, so this change is overdue.
```
SELECT signed_version, min(completion_time), max(completion_time)
FROM user_code_of_conduct_agreement
GROUP BY signed_version ORDER BY signed_version;
+----------------+----------------------+----------------------+
| signed_version | min(completion_time) | max(completion_time) |
+----------------+----------------------+----------------------+
|              2 | 2019-10-30 20:01:39  | 2020-04-21 15:59:27  |
|              3 | 2020-04-29 17:03:24  | 2022-02-07 19:36:46  |
|              4 | 2022-02-09 02:27:14  | 2023-08-22 13:34:59  |
|              5 | 2023-08-22 14:33:55  | …
```
> [risk=low][no ticket] DUCC Version 3 is not current

- .circleci/config.yml
"Wait for local API server to start" can sometimes take longer than 5 minutes in CircleCI.
We just bumped it from 4 to 5 in May (#7638) so we should look into why it's slowing down.
---
> [risk=no][no ticket] Bump the wait-for-local-api step to 6 minutes in Circle

- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel-footer.spec.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel-footer.tsx
- ui/src/app/utils/runtime-utils.tsx
- ui/src/testing/utils.ts
Allow deletion of Jupyter runtimes from the Runtime Configuration Panel and the Apps Panel.
Tested locally by creating Error runtimes (due to a current bug, creating a runtime immediately after a GKE app can do this) and observing that deletion is available to users.
---
> [risk=low][no ticket] Enable deleting of ERROR runtimes

- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Enable ID.me in higher environments.
---
> [no ticket][risk=no] Update higher environments to use ID.me

- api/build.gradle
[this](https://github.com/RetireJS/retire.js/pull/424) is blocking release. Disabling this for now to unblock release
---
> [no ticket] ignore retirejs for now

- api/build.gradle
Reverts #8103 after fix here: https://github.com/RetireJS/retire.js/pull/424
---
> [risk=low][no ticket] Restore default dependencyCheck configuration after bug fix

- api/src/main/webapp/WEB-INF/cron_test.yaml
I renamed a cron Job checkFreeTierBillingUsageCloudTask temp @ crom_base to test something. I forgot to update cron_test. This caused builds to fail while deploying at test
---
> [noTicket[risk=no]Fix for build failures : remove old cron ref from cron_test

- api/config/config_local.json
- api/config/config_test.json
This upgrades fixes Hail memory issue
---
> [no ticket][risk=low] bump test and local docker image to 2.2.7

- ui/package.json
- ui/yarn.lock
3 UI upgrades:
* force axios resolution to ^1.6.0 to resolve vulnerability https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
*  Upgrade oidc-client-ts from 2.2.1 to 2.3.0 (merged from #8113)
*  Upgrade @types/lodash from 4.14.191 to 4.14.199 (merged from #8111)
---
> [risk=low][no ticket] Update UI packages to resolve vulnerabilities

- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/cron_test.yaml
The recent change to use cloud task for checking free tier usage has been failing with the error : _INVALID_ARGUMENT: Task size too large_
. We would have to rethink the strategy of how to send the big query data. 
In the meantime since its a release day, its better to revert the change so that it doesnt go to PROD
---
> [noTicket][risk=no]Revert freeTier cron job using cloud task

- ui/src/terraui/build.sh
- ui/src/terraui/patches/rm-tests.sh
This change is needed to build under Node 18, but it's not clear why.  Because this is for the prototype `ui/src/terraui` which contains many hacks already and will eventually be replace with properly componentized `@terra-ui-packages` elements, and Node 18 is urgent, I didn't look too deeply.
The failure this change avoids is
```
➤ YN0009: │ puppeteer@npm:13.5.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-780915ac/build.log)
```
but it only happens under some circumstances - in my experience, this was only when running the deployment script.  Again, unclear why this makes a difference.  I was able to confirm that this change fixes the situation.
The only thing this could affect is the Cloud Environments page.  I observed no changes when testing locally. …
> [risk=low][RW-10556] Modify the embedded terraui build for Node 18

- api/build.gradle
Snyk reports transitive vulnerabilities through our Sam client - perhaps an upgrade will help.  Also good to keep up to date generally.
Tested locally by exercising the two paths where we currently use the Sam client:
* Delete Workspace (uses Sam to delete GKE child resources)
* Unshare CT Workspace with Owner/Writer (uses Sam to revoke the Google Life Science Runner role)
---
> [risk=low][no ticket] Update Sam client

- api/docs/developer-system-requirements.md
Node versions older than 18 will probably work for a while - but we can't guarantee it now that our build process uses 18 (#8116)
---
> [risk=low][RW-10556] Add Node 18 to developer requirements

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
Remove feature flag absorb.enabledForNewUsers. This feature has been rolled out to all environments. All new users use Absorb instead of Moodle.
To manually test this:
- Create a new user
- Using an admin user, bypass requirements other than RT and CT training
- On the data access modules page, when you select RT training, you are taken to Absorb
---
> [risk=no][RW-11040] Remove feature flag absorb.enabledForNewUsers

- api/src/integration/java/org/pmiops/workbench/AbsorbAcceptanceTest.java
- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
Add Absorb docs. This PR introduces no functional changes.
If possible, I'd prefer to avoid maintaining docs outside the code like I do for [auth](https://precisionmedicineinitiative.atlassian.net/wiki/spaces/RW/pages/2833580033/Authentication+and+Authorization), as I think separate docs are less discoverable and maintainable. These comments attempt to place Absorb information at the place you'd be most likely to look for it.
@NehaBroad Is there any other information you feel you need in order to confidently implement [RW-10362](https://precisionmedicineinitiative.atlassian.net/browse/RW-10362)? If so, let me know and we can discuss how that information should be shared.
After this is merged, I will add a small section to the oncall playbook regarding Absorb debugging.
---
**PR …
> [risk=no][no ticket] Add Absorb docs

- e2e/package.json
- e2e/yarn.lock
This reverts commit 2a75f6da594233159a68057c3448c8e68d00de1b / #8149
This change is incompatible with our e2e setup.  I attempted to debug it and fix-forward, but I was unsuccessful.
More info: some Jest and/or Puppeteer package(s) are depending on behavior removed from the latest axios: https://github.com/axios/axios/issues/5264 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Jest: Got error running globalSetup - /home/circleci/workbench/e2e/node_modules/jest-environment-puppeteer/setup.js, reason: Package subpath './lib/adapters/http' is not defined by "exports" in /home/circleci/workbench/e2e/node_modules/axios/package.json
```
Manually tested locally by un-disabling `tests/misc/sidenav.spec.ts` and running it.  I should have done that for #8149 but I believed the CircleCI run would take …
> [risk=low][no ticket] Revert "Force e2e axios to 1.6.0+ (#8149)"

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/apps-panel/apps-panel-button.tsx
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/buttons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/testing/default-server-config.ts
In order to test this, run a GKE app. Once it is in the "RUNNING" state, you should be able to click the "PAUSE" button and have your app transition to "PAUSING" and eventually "PAUSED". When "PAUSED", you should be able to click on the "RESUME" button to reverse the process
If you change enableAppPausing to false in config_local.json, you should see a disabled "PAUSE" button on a running GKE app.
---
> [RW-10256][risk=no] Enabled app pausing in local and test environments.

- ui/src/app/pages/access/aar-title.spec.tsx
- ui/src/app/pages/access/aar-title.tsx
- ui/src/app/pages/access/compliance-training-module-card-title.spec.tsx
- ui/src/app/pages/access/dar-title.spec.tsx
- ui/src/app/pages/access/dar-title.tsx
- ui/src/app/pages/access/module.tsx
- ui/src/app/pages/access/modules-for-annual-renewal.tsx
- ui/src/app/pages/access/registered-tier-card.tsx
- ui/src/app/pages/access/test-utils.ts
- ui/src/app/utils/access-utils.tsx
Reduce re-mount count of access module card titles. This reduces the number of `useAbsorb` calls on the data access and access renewal pages from 14 to 3 and 2, respectively. Since we render 2 cards and each card invokes `useAbsorb`, 2 is the minimum without other approaches like lifting state.
This can be validated by loading the data access page and counting the number of network calls to `useAbsorb`.
---
> [risk=no][RW-11283] Reduce re-mount count of access module card titles

- ui/package.json
- ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx
- ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx
- Set `REACT_APP_GET_LOCAL_AUTH_TOKEN=true` in local `start-tanagra` script so Tanagra app will expect bearer token passed in the url.
- Update cohort urls to match Tanagra router changes
> [DT-551][risk=no] Set env var for Tanagra local auth

- ui/src/app/pages/access/data-access-requirements.spec.tsx
- ui/src/app/pages/access/data-access-requirements.tsx
- ui/src/app/utils/access-utils.spec.tsx
- ui/src/app/utils/access-utils.tsx
Previously, data access requirements called syncModulesExternal, there was no catch for when the call failed. This meant that hideSpinner was never called.
To fix this, syncModulesExternal is now being called within fetchWithErrorModal. FetchWithErrorModal returns a promise, and now a finally is called that hides the spinner.
The error modal looks like the following:
If you would like to test, the easies way to reproduce would be to change line 297 of access-utils.tsx from `await profileApi().syncComplianceTrainingStatus()` to `Promise.reject()`
---
> [RW-11366][risk=no] Fix Access Module Infinite Spinner

- api/db/changelog/db.changelog-227-drop-user-data-use-agreement.xml
- api/db/changelog/db.changelog-master.xml
This removal is long overdue.  We replaced the concept of the user DUA with the DUCC in Jan/Feb 2022, so the table hasn't been used since then.  To verify, I queried the DB on Test and Prod.
Test:
```
select MAX(completion_time) FROM user_data_use_agreement;
+----------------------+
| MAX(completion_time) |
+----------------------+
| 2022-02-02 17:34:53  |
+----------------------+
```
Prod:
```
+----------------------+
| MAX(completion_time) |
+----------------------+
| 2022-02-08 18:26:37  |
+----------------------+
```
Tested locally: I was able to sign a DUCC without problems.
---
> [risk=low][no ticket] Drop the user_data_use_agreement table

- ui/src/app/pages/analysis/new-jupyter-notebook-modal.tsx
- ui/src/app/pages/analysis/util.spec.tsx
- ui/src/app/pages/analysis/util.ts
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
Filter the notebook files to Jupyter only for export-dataset.  Tested locally.
In a workspace with Jupyter, SAS, and RStudio files
Test env (Before)
Local (after)
---
> [risk=low][RW-11410] Show only Jupyter notebooks in export-dataset-modal

- api/build.gradle
- api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/calhoun/CalhounConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/sam/SamApiClientFactory.java
- api/src/main/java/org/pmiops/workbench/sam/SamConfig.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
Update Get Terra ToS for the sign-in flow and the create-account flow to use the new Sam endpoint, and update the logic to require the latest version, not just a compliant version.
Tested locally by:
1. calling the Reject ToS endpoint (the new one, in Sam) and observing that the AoU UI required me to accept the ToS again.  After doing so, I was able to use the RWB as expected.  I also called the Sam endpoints directly and everything looked correct, with one exception [a].  However I have accounted for this here.
2. creating a new user.  The process was unchanged, and calling the new endpoint reported the expected results.
Exception [a] - if a user rejects the Terra ToS, they will continue to see `"isCurrentVersion": true` and `latestAcceptedVersion` equal to the latest, so a check for …
> [risk=low][RW-11417] Use the new Sam endpoint userTermsOfServiceGetSelf to get Terra ToS status

- api/src/main/java/org/pmiops/workbench/calhoun/CalhounRetryHandler.java
- api/src/main/java/org/pmiops/workbench/firecloud/FirecloudRetryHandler.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoRetryHandler.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksRetryHandler.java
- api/src/main/java/org/pmiops/workbench/rawls/RawlsRetryHandler.java
- api/src/main/java/org/pmiops/workbench/sam/SamRetryHandler.java
- api/src/main/java/org/pmiops/workbench/shibboleth/ShibbolethRetryHandler.java
- api/src/main/java/org/pmiops/workbench/terra/TerraServiceRetryHandler.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
Tested locally by rejecting the ToS while logged in to the RWB and observing that I can't access most data.  When I looked in the network tab, I could clearly see that the endpoints had 401s with text indicating that I was not ToS-compliant.  Refreshing the UI caused the AoU ToS to appear.  After agreeing to it, I regained normal access.
---
> [risk=low][RW-11418] Update the TOS 401-error converter to use the new endpoint

- ui/src/app/components/common-env-conf-panels/environment-informed-action-panel.tsx
- ui/src/app/components/common-env-conf-panels/start-stop-environment-button.spec.tsx
- ui/src/app/components/common-env-conf-panels/start-stop-environment-button.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
- ui/src/app/components/runtime-configuration-panel/create-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel/create-panel.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
CreatePanel (for Runtimes) and CreateGkeApp no longer need to pass useless pause/resume props to EnvironmentInformedActionPanel because they are optional.
Added tests and did some refactoring too.
Tested locally by working with CreatePanel, Create App, and ConfigurationPanel in the UI
---
> [risk=low][no ticket] Make pause and resume actions optional for when they are not needed

- ui/src/app/utils/machines.ts
We previously allowed users to configure Dataproc workers that were smaller than our system would actually support.  This change increases the minimum allowable size.
Tested by successfully creating a new Dataproc cluster using the new minimum configuration (`n1-standard-2`, 2 CPUs, 7.5 GB RAM)
---
> [risk=low][RW-5763] Prevent users from creating too-small Dataproc clusters

- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedUserService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedUserServiceImpl.java
The `ensureTestUserTosCompliance` cron was using the old endpoints, and therefore could only detect when users become **noncompliant** with ToS.  This PR changes the cron to detect a new ToS earlier, by checking if users are **current with the latest version** of the ToS.
Today's e2e smoke test failed because the UI unexpectedly presented the ToS to the test user.  That user was still compliant, but not up-to-date with latest, so the cron did not sign the ToS for this user.
Similar to #8182 and #8188
Tested locally by modifying my local env a bit:
* added the test e2e users to local config
* kluged the impersonate accept tos call to not require a DB entry for the users, so it worked with just the user name string
I was able to run the cron job successfully and accept TOS on behalf of all …
> [risk=low][RW-11416][RW-11413] Update Enforce Test User ToS cron to use new get endpoint

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedFirecloudService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedFirecloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedUserServiceImpl.java
Sam fixed the bug in their Java client that was causing calls to the new accept-tos endpoint to fail.
Tested locally by running the Enforce Test User ToS cron 
---
> [risk=low][RW-11416][RW-11413] Bump sam client to fix accept-tos call

- ui/src/app/pages/analysis/new-jupyter-notebook-modal.tsx
- ui/src/app/pages/analysis/util.ts
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/resources.tsx
Confirmed that the new-notebook modal now correctly checks for Jupyter filenames
Before
After
Also confirmed that export-dataset was not broken
---
> [risk=low][no ticket] New Jupyter File modal was not correctly checking for duplicate names

- ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx
- ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx
- ui/src/app/pages/data/tanagra-dev/tanagra-resources.tsx
- Fix display of resources table for Data tab of Tanagra workspaces
- Change create cohort function to match Tanagra (create 'Untitled' cohort instead of prompting for name)
https://github.com/all-of-us/workbench/assets/40036095/d5385705-1acb-454c-bab7-4d7940f45308
---
> [DT-563][risk=no] Fix resource display for Tanagra data page

- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
Related PR https://github.com/DataBiosphere/leonardo/pull/3974
We recently migrated sas and rstudio charts to [terra-helmfile](https://github.com/broadinstitute/terra-helmfile/tree/master/charts). Along with the migration, we also renamed the chart names. Hence updating the chart names we're using
---
> [risk=low] RW-11041 update chart name

- ui/src/app/components/common-env-conf-panels/environment-cost-estimator.tsx
- ui/src/app/components/common-env-conf-panels/environment-informed-action-panel.tsx
- ui/src/app/components/common-env-conf-panels/styles.tsx
Move the "costs will be drawn from" text out of the EnvironmentCostEstimator row due to overflow, plus a few other styling tweaks.  Tested locally.
No unit test changes because this is all styling/layout
Before (GCE w/ PD)
After
Before (DataProc - this was fine but it's the same code)
After
---
> [risk=low][no ticket] Runtime panel cost styling improvements

- ui/src/app/pages/data/cohort/list-search.tsx
Fixes `Cannot read properties of undefined` error when selecting 'Has Any Physical Measurements Data' checkbox
> [DT-646][risk=no] Fix has any pm selection

- ui/src/app/pages/data/cohort/utils.ts
- ui/src/app/pages/data/cohort/variant-search.tsx
- Fixes issue where counts for variant search items are zero when loading an existing cohort
- Fixes issue with the allele count filter slider where adjusting the lower limit also sets the upper limit
> [DT-669][DT-670][risk=no] Variant search UI fixes

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
Unable to reproduce locally (yet) because we'd have to coordinate with Terra about how to get a user into the correct state, but this change seems straightforward.
Tested locally, observing no change in behavior for my (unaffected) user:
* I can access workspaces normally
* Terra ToS rejection causes my user to require a new ToS acceptance
* after re-acceptance, I have normal workspace access again.
---
> [risk=low][RW-11523][RW-11538] Catch 4xx errors when checking Terra ToS status

- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
I am still thinking about integration/acceptance test. In the meantime i wanted to add this test which test:
1) User has already completed RT AND  CT training
2) User is re-enrolled to RT Training
3) User completes RT Training
---
> [RW-10362][risk=no] Test:  Users who used Absorb can take annual renewal training using Absorb

- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoAppUtils.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
I got a reminder email about a disk associated with my "Sas" application.  This capitalization is not correct - it should always be SAS.
Add a display-name utility to produce the desired strings.
Alt: update the AppType enum.  That has the potential to be a pretty intrusive change, so I decided against it - for now anyway.
---
> [risk=low][no ticket] Use more appropriate strings for apps in emails

- api/build.gradle
Resolves https://app.snyk.io/org/all-of-us-researcher-workbench/project/bf2628cc-574b-4c92-a236-237ad192de46#issue-SNYK-JAVA-COMSQUAREUPOKIO-5820002 transitively by pulling in the latest Sam https://github.com/broadinstitute/sam/pull/1294
Tested locally by interacting with the UI, being sure to exercise the Sam ToS endpoints.
---
> [risk=low][no ticket] Bump sam client to resolve a vulnerability

- .circleci/config.yml
As a result of the Circle image update in #8238, we now test against a more recent version of Chrome.  However, the APIs for retrieving a Chromedriver have changed since then: https://github.com/CircleCI-Public/browser-tools-orb/issues/75
Update our browser-tools orb to a version with the fix (1.4.2+) https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.2
---
> [risk=low][RW-11368] Bump browser-tools to retrieve more modern Chromedrivers

- .circleci/config.yml
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Running tests often ran out of memory after the Java upgrade.  Bump the machine size to one with more RAM.
---
> [risk=low][RW-11558] Increase api-unit-tests instance size to medium+

- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/cron_test.yaml
During the holiday, I noticed alerts related to a free-tier cron job utilizing Cloud Task. To ensure the continued execution of the original production cron job while also having a separate one for testing purposes, I considered updating the configuration. I derived this idea from the following Stack Overflow post: https://stackoverflow.com/questions/48666190/cron-job-without-scheduling-in-google-app-engine
Please let me know what you all think
---
> [noTicket][risk=low] Run free tier cron job using cloud task only on test

- .circleci/config.yml
- ui/src/environments/environment-type.ts
Update the Circle config to skip the broken Chromedriver installation.  It's not clear what exactly caused that breakage, but we don't need it, so it's easy just to skip it.
---
> [risk=low][no ticket] Fix nightly-tests by not installing chromedriver

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/buttons.tsx
- ui/src/app/components/icons.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
Added copy code button to export dataset modal. This button gets its text representation from the same endpoint as preview because of significant overlap in functionality. I added logic to appropriately update preview and clipboard representation when relevant fields change. I also added logic to lock down functionality when modal is in the process of loading.
---
> [RW-10323][risk=no] Add copy code button to export dataset

- ui/src/app/components/breadcrumb-type.tsx
- ui/src/app/components/breadcrumb.spec.tsx
- ui/src/app/components/breadcrumb.tsx
- ui/src/app/routing/workspace-app-routing.tsx
We planned yesterday to disable clicking on these breadcrumbs, but I think I have a better understanding of their intention now, so I corrected it instead: now breadcrumbs for notebook/R/SAS/etc previews have appropriate URLs: they link to the preview page, not the live notebook page.
In the normal case (you are at the preview page and this breadcrumb comes last) clicking it does nothing, so you can interpret that as "disabled" if you like.
Tested locally with various file types in preview and non-preview modes.
---
> [risk=low][RW-11453] Fix Notebook Preview and User App breadcrumb URLs

- ui/src/app/components/runtime-configuration-panel.enzyme.spec.tsx
- ui/src/app/components/runtime-configuration-panel.rtl.spec.tsx
- ui/src/app/components/runtime-configuration-panel/disk-selector.tsx
Long ago, we provided an option to choose Standard disk vs. Detachable/Persistent disks for GCE VMs.  We have never offered the Persistent option for Dataproc clusters.
Since we started requiring Persistent Disks for GCE VMs, there is no longer any situation where we allow the user to make the choice between these disk types.
This PR removes the appearance of providing that option.
**I don't know why the fonts are wrong in these screenshots.**  I think something is wrong with my local browser.  There's no reason to expect that this change would have any effect on fonts, and I also see it for the version I didn't change.
Before (GCE)
After (GCE)
Before (Dataproc)
After (Dataproc)
---
> [risk=low][RW-9376] Only show Persistent Disks for GCE, and only Standard disks for Dataproc

- ui/src/app/components/common-env-conf-panels/confirm-delete-environment-with-pd.tsx
Changed language for delete environment panel to reflect the type of environment being deleted.
Currently all environments say:
> You will continue to incur persistent disk cost at $x.yz per month. You can delete your disk at any time via the SAS configuration panel.
Current Design (same for all apps and Jupyter):
Updated Design:
Jupyter:
Cromwell:
RStudio:
SAS:
---
> [no ticket][risk=no] Fix disk deletion language.

- ui/package.json
- ui/yarn.lock
follow-redirects: https://app.snyk.io/org/all-of-us-researcher-workbench/project/9c7bf90a-ef51-499c-91d9-0766a3ff8c58#issue-SNYK-JS-FOLLOWREDIRECTS-6141137
axios: https://app.snyk.io/org/all-of-us-researcher-workbench/project/9c7bf90a-ef51-499c-91d9-0766a3ff8c58#issue-SNYK-JS-AXIOS-6124857
axios is used by the OpenAPI generator, so verifying that the app functions using the generated API should be sufficient.  follow-redirects is used by axios and (transitively) by webpack-dev-server.  Tested locally.
---
> [risk=low][no ticket] Upgrade axios and follow-redirects to resolve vulnerabilities

- ui/package.json
- ui/yarn.lock
Turns out that #8263 was not enough: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
---
> [risk=low][no ticket] New vuln for axios

- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/homepage/homepage.tsx
- ui/src/app/pages/homepage/recent-workspaces.tsx
If you delete a Workspace on the homepage, using the Workspace Card context menu, the Recent Resources list doesn't update, so it's possible to have resource entries that refer to a deleted workspace or resource.  Attempting to access these leads to bad UX: the app just appears to hang.
This PR causes the Recent Resources list to refresh after deleting a workspace, ensuring that these links do not appear.
---
> [risk=low][RW-6159] Reload Recent Resources on home page after deleting a workspace

- ui/src/app/pages/signed-in/inactivity-monitor.spec.tsx
- ui/src/app/pages/signed-in/inactivity-monitor.tsx
- ui/src/app/utils/inactivity.spec.tsx
- ui/src/app/utils/inactivity.tsx
A small change to help me understand what I need to do for RW-10249 better.  Does not complete the story.
Tested locally by observing that clicking in the app continues to update `LAST_ACTIVE_TIMESTAMP_EPOCH_MS` in local storage
---
> [risk=low][RW-10249] Break out inactivity config and add accessors

- deploy/libproject/deploy.rb
We will mount a volumn in docker and put SA credential in that path. 
The current approach does not work with [colima](https://github.com/abiosoft/colima) (Verily bans docker, verily eng can only use colima).
There is a known issue with single file volumn, the suggested workaround is to use `/tmp/colima`: See: https://github.com/abiosoft/colima/issues/844
---
> [no ticket][risk=no] Use different path to store files to be mounted in docker

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/signed-in/access-renewal-notification.tsx
- ui/src/testing/default-server-config.ts
With the next release all the users who are eligible for access module update will start seeing the following banner:
As soon as the FF redirectMoodleToAbsorb is turned ON i.e all users will start using Absorb the banner text will revert to the original text
How to test:
1) With feature flag redirectMoodleToAbsorb true (default in local/test) there should be no change in access module banner
2) With feature flag redirectMoodleToAbsorb false there should be a change in text as in screenshot
---
> [RW-10362][risk=no]  Users who used Absorb can take annual renewal training using Absorb --banner text

- api/config/cdr_config_prod.json
bumping index for variant search in cohort builder.
@tarekmamdouh Appears you are the release eng next week. Please run the following commands from api directory before deploying the release to prod:
Variant search in cohort builder
Publish C2022Q4R11
db-cdr/generate-cdr/project.rb publish-cdr --project all-of-us-rw-prod --bq-dataset C2022Q4R11 --tier controlled --table-prefixes cb_
> [no ticket][risk=no] bumping index for variant search in cohort builder

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
The newest version of hail requires the argument `array_elements_required=False` for (all?  just some?) input data.
Test process
* Do a Genomic Extraction (can take ~ 1 hr)
* Run the generated notebook to import into Hail (can take several hours!)
On Test I see the reported "cannot set missing field for required type" error
On Local I see a successful import
See also:
* https://precisionmedicineinitiative.atlassian.net/browse/DST-1587
* https://discuss.hail.is/t/error-cannot-set-missing-field-for-required-type-pfloat64/3677/3
* https://github.com/hail-is/hail/issues/13346
---
> [risk=low][RW-11695] Update Hail code for latest version

- api/build.gradle
`libyear` seems to be causing `dev-up` slowdowns.  Not sure if it provides enough value to justify this - let's discuss.
This reverts commit f735d6432dba57124c470fbd2afb362759f8dce8.
---
> Revert "[risk=no][no ticket] Add the libyear gradle plugin (#8290)"

- ui/src/app/pages/data/cohort/variant-search.tsx
Add number inputs for min and max for each slider in the variant filters
---
> [DT-699][risk=no] Add number inputs for variant filter sliders

- .circleci/config.yml
- ui/src/environments/environment-type.ts
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
No expected changes.  If e2ev2 tests run and pass, we can merge this.
---
> [risk=low][no ticket] Replace deprecated CircleCI images for e2ev2 and playground

- deploy/libproject/deploy.rb
The existing script fails if the directory /tmp/colima exisit. Update the script to create the directory ONLY if it doesnt exist.
Tested by trying create the script twice 
./project.rb deploy --project all-of-us-rw-stable --account deploy@all-of-us-rw-stable.iam.gserviceaccount.com --no-promote --dry-run
---
> [noTicket][risk=none] Create colima directory  only if it does'nt exist

- ui/package.json
- ui/yarn.lock
Recently, building the UI started displaying this warning message:
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```
This PR does what it suggests, and also updates the large `babel` family of …
> [risk=low][no ticket] Bump the babel packages and silence a UI warning

- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel-footer.spec.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel-footer.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel.tsx
- ui/src/app/utils/runtime-utils.tsx
Support asked for this change, and it seems to work.  Tested locally.
Confirmed with the Leonardo team that this was appropriate: https://broadinstitute.slack.com/archives/C046XJD9MPW/p1706736760281869
---
> [risk=low][no ticket] Allow users to delete pausing/resuming runtimes

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
Absorb team has migrated all users from moodle to absorb,
this PR will do the following
- Turn **on** flag to redirect ALL users to absorb
- Turn **off** Flag to disable training card for Moddle Users
---
> [RW-11375][risk=none] Switch users using Moodle to Absorb <-Turn on for all env

- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
The log messages are making more sense now however i feel there were some messages that were redundant and creating noise. 
This PR:
- Removes the log message which shows the number of workspace that requires update
- Update the workspace that shows the id that requires update
---
> [RW-10627][risk=no] [P1] Free tier billing usage cron job starts failing recently due to timeout - Improve log messages

- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/apps-panel/expanded-app.tsx
- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/components/gke-app-configuration-panels/open-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/open-gke-app-button.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/components/runtime-initializer-modal.tsx
- ui/src/app/pages/analysis/interactive-notebook.spec.tsx
- ui/src/app/pages/data/cohort/cohort-search.tsx
- ui/src/app/pages/data/cohort/list-search.tsx
- ui/src/app/pages/data/cohort/selection-list.tsx
- ui/src/app/pages/data/cohort/tree-node.tsx
- ui/src/app/pages/data/concept/concept-list.tsx
- ui/src/app/pages/data/concept/concept-search.tsx
- ui/src/app/pages/data/criteria-search.tsx
- ui/src/app/utils/navigation.tsx
- ui/src/app/utils/user-apps-utils.spec.tsx
- ui/src/app/utils/user-apps-utils.tsx
Changes the "Start" button in the SAS and RStudio config panels to "Open <app>" when the app is running.  Works similarly to the lightning-bolt panel.
Also updated the lightning-bolt panel "open" to close the panel.
Tested by creating SAS and RStudio apps and opening them both ways.
---
> [risk=low][no ticket] Open RStudio/SAS from config panels

- ui/src/app/components/resource-list.tsx
- ui/src/app/pages/appAnalysis/app-files-list.tsx
- ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx
- ui/src/app/utils/dates.tsx
We had a silly bug: our date sorting was Month first
Now it is correctly Year first
---
> [risk=low][RW-11756] Sort by numerical last-modified, not string

- api/libproject/devstart.rb
Previously, it would simply crash with no information.
```
$ ./project.rb generate-impersonated-user-tokens --impersonated-usernames joel@fake-research-aou.org --output-token-dir NOTFOUND
/Users/thibault/src/aou/api/libproject/devstart.rb:1464:in `generate_impersonated_user_tokens': The token output directory NOTFOUND does not exist (ArgumentError)
```
---
> [risk=low][no ticket] Add directory existence check to generate-impersonated-user-tokens

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Tested by creating a user and observing this in the logs:
```
[Mon Feb 12 14:54:51 EST 2024] INFO: org.pmiops.workbench.mail.MailServiceImpl sendWithRetries - Email 'Welcome for joel-feb12@fake-research-aou.org (thibault@broadinstitute.org)' was sent.
```
---
> [risk=low][no ticket] Show both usernames and contact emails in mail server logs

- ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx
Fix 'Last Modified Date' column in the resources list for Tanagra workspaces, which was using the `lastModifiedTime` of the workspace instead of the resource.
Before:
After:
---
> [DT-736][risk=no] Fix dates for Tanagra resources

- api/build.gradle
- api/db-cdr/build.gradle
- api/db/build.gradle
First, bump spring-boot to the latest 2.x (this is not the major upgrade - that will be to 3.x)
Then made these prerequisite upgrades:
* mysql-connector
* spring-security
* jackson
Tested locally with no obvious issues.
---
> [risk=low][RW-11847] Easy prerequisites for the spring-boot upgrade

- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
- ui/src/app/pages/admin/user/admin-user-bypass.tsx
Added missing code to read identity bypass status on Admin User page.
To test that this work appropriately, bypass a user's Identity requirement from UserAdmin table and then navigate to the User Admin page for the same user to see if that user was appropriately bypassed
---
> [no ticket][risk=no] Added identity bypass time to AdminTableUser.

- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/gke-app-configuration-panel.spec.tsx
- ui/src/app/components/gke-app-configuration-panel.tsx
- ui/src/app/utils/user-apps-utils.tsx
The user apps config panel was checking for apps only **once** on load, instead of receiving updates by polling and checking the store.
Tested locally by opening the app config panel after creating and deleting apps, and observing that the button changed from "start" to "open" or vice-versa as appropriate **without any user interaction**
---
> [risk=low][no ticket] User apps config panel reacts to app changes

- ui/src/app/pages/appAnalysis/app-files-list.tsx
When we updated the analysis tab UX to the new apps-list, we accidentally removed the ability to sort by last modified time.  This PR restores it.
---
> [risk=low][no ticket] Make the last-modified-time sortable in the apps list (analysis tab)

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/main/resources/workbench-api.yaml
adding ability to use variantFilter to select variants. Now the `SearchParameter` model object allows for 2 different ways to add variants:
1. VariantId - can add variants one at a time
2. VaraintFilter - can add variants using a variantFilter
---
> [DT-773][risk=no] adding ability to use variantFilter to select variants. 

- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
Partial completion of RW-11801:
* Whenever a notebook is mentioned, we now specify that we mean a **Jupyter** notebook
* Text is added explaining that direct export to notebooks is only for Jupyter
* Language choice is now first
The "disable for SAS" portion of RW-11801 will be done along with SAS support in #8424
---
> [risk=low][RW-11801] Dataset export UI update for RStudio

- api/src/contracttest/java/org/pmiops/workbench/consumer/RuntimesApiTest.java
~~Removing deprecated fields.~~
~~https://github.com/DataBiosphere/leonardo/blob/2430b89b14f95ab51e8886def70f571c8febb610/http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/http/api/RuntimeRoutes.scala#L432~~
While these fields are still in use, that is not why the contract was failing. They were failing, because I had said they could be any string when they need to be a valid URL.
---
> [RW-11654][risk=no] Adding valid URL requirement

- ui/src/app/components/confirm-workspace-delete-modal.tsx
- ui/src/app/components/help-sidebar.tsx
- ui/src/app/pages/workspace/workspace-card.tsx
Remove the warning that prevents users from deleting their workspaces when there's app in the workspace.
New banner looks like this when trying to delete workspace
Note if you have a workspace that previously has orphaned Sam resources for apps. Workspace deletion will still fail, and eng will have to step in to help users to clean up
---
> [risk=low] RW-12040 Allow workspace deletion

- api/src/contracttest/java/org/pmiops/workbench/consumer/RuntimesApiTest.java
Most contract tests specify attribute names and types that a given request should have.
In this base case, the contract is generated in such a way that a random value of the given type will be generated by the provider when the contract is validated.
There are a few instances, where the provider requires specific bounds for the variables:
- **jupyterUserScriptUri**: must be a valid URI rather than any random string
- **jupyterStartUserScriptUri**: must be a valid URI rather than any random string
- **autopauseThreshold**: specified in minutes and must be in the range of -+292 years.
- **toolDockerImage**: must be a valid Docker image path
We could write specific tests to handle each of the positive and negative cases, but [that starts going down the line of functional …
> [RW-11654][risk=no] Updated fields that have validation

- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/AnalysisLanguageMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
Enable SAS as a dataset analysis language, but do not allow exporting to a notebook.  Tested locally by observing that running the SAS code obtained here for a dataset with multiple domains successfully caused SAS data tables to be populated.
---
> [risk=low][RW-11681][RW-11801] Dataset Export for SAS

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
Nothing in the UI references this.  I can't find any evidence that we ever used this.  The most recent reference I could find to this config block was from 2020: #4063
Tested locally by creating and interacting with GCE and DataProc runtimes.
---
> [risk=low][no ticket] Remove the unused "runtimeImages" config block

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- ui/src/app/components/apps-panel.spec.tsx
- ui/src/app/components/apps-panel.tsx
- ui/src/app/components/help-sidebar-icons.tsx
- ui/src/app/components/help-sidebar.spec.tsx
- ui/src/app/components/runtime-configuration-panel.enzyme.spec.tsx
- ui/src/app/components/runtime-configuration-panel.rtl.spec.tsx
- ui/src/app/pages/appAnalysis/app-selector-modal.tsx
- ui/src/app/pages/appAnalysis/app-selector.spec.tsx
- ui/src/app/pages/workspace/workspace-share.spec.tsx
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/testing/default-server-config.ts
enableRStudioGKEApp is now always true, so we can remove the FF.  This is step 1: remove it from API and UI logic.  Final deletion will need to wait until a release later.
Tested locally with no issues.
---
> [risk=low][RW-9646] Remove the enableRStudioGKEApp feature flag from API and UI code

- api/src/main/java/org/pmiops/workbench/google/CloudStorageClientImpl.java
This shouldn't ever happen, because any bucket we reference should exist, but I found a weird edge case today - a partially deleted workspace which I am looking into.
Anyway, we should return a better error message when this happens. 
---
> [risk=low][no ticket] 404 is better than 500/NPE when not found

- api/config/config_test.json
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_variant_attribute_data.json
- api/src/bigquerytest/resources/bigquery/cbdata/cb_variant_attribute_genes_data.json
- api/src/main/java/org/pmiops/workbench/cdr/ConceptBigQueryService.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/QueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java
- api/src/main/resources/workbench-api.yaml
Changing sql generation for variant select all
@dolbeew I've added another filter to the VariantFilterRequest object(need to add to variant filter on UI side):
This range supports the following operators: `GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN, LESS_THAN_OR_EQUAL_TO, BETWEEN`
participantCountRange:
$ref: '#/components/schemas/ParticipantCountFilter'
ParticipantCountFilter:
required:
- operator
- operands
type: object
properties:
operator:
$ref: '#/components/schemas/Operator'
operands:
type: array
items:
type: integer
---
> [DT-774][risk=no] Changing sql generation for variant select all

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/WorkbenchStringUtils.java
- api/src/test/java/org/pmiops/workbench/utils/WorkbenchStringUtilsTest.java
RStudio silently gives the wrong results when line lengths are too long: https://github.com/rstudio/rstudio/issues/14420
This PR ensures that the long SQL lines in the Dataset Builder output are short enough, by splitting on commas.
Tested locally by running split and unsplit versions of the same Dataset Builder queries in RStudio.
Portion of SQL code generated by setting a very short line length parameter (20)
```
JOIN
(
SELECT
CAST(cr.id as string) AS id       
FROM
`cb_criteria` cr       
WHERE
concept_id IN (
192671,
193250, 197925,
198212, 26727,
37311947, 378756,
4002659, 4025198,
4026112, 4059114,
4169954, 4177600,
4226021, 4245614,
42538062, 42709921,
4271696, 42873123,
4299449, 4307580,
4338544, 437312,
439040, 46273183
)       
AND full_text LIKE '%_rank1]%'      
) a 
```
with …
> [risk=low][RW-12099] Fix RStudio by splitting too-long lines

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
#8417 has been released, so it is now safe to merge the full removal.
Tested locally by running RStudio.
---
> [risk=low][RW-9646] Fully remove enableRStudioGKEApp feature flag

- ui/src/app/pages/data/cohort/search-group.tsx
Fixes display issue where deleting a group that has at least one group below it will cause the white overlay to remain after the group is removed.
> [DT-792][risk=no] Fix overlay issue when deleting search group

- ui/src/app/pages/admin/workspace/basic-information.tsx
- ui/src/app/pages/appAnalysis/app-files-list.tsx
I feel that we're giving unrealistically optimistic estimates for notebook copying time.  I've seen it take longer than an hour before.
---
> [risk=low][RW-12152] Update copying-notebooks message in the UI

- .circleci/config.yml
Passing commit SHA1 to Pact Broker in order to better keep track of versioning.
Re-enabling can-i-deploy, because tests have stabilized.
---
> [no ticket][risk=no] Updated how CircleCI updates Pact Broker versioning.

- ui/src/app/components/app-router.spec.tsx
- ui/src/app/pages/admin/admin-institution.spec.tsx
- ui/src/app/pages/data/data-set/export-dataset-modal.tsx
- ui/src/app/pages/workspace/create-billing-account-modal.spec.tsx
- ui/src/setupTests.js
- ui/src/testing/react-test-helpers.tsx
Converted three Enzyme tests with assistance of Copilot.
I described some of my process here:
https://docs.google.com/document/d/1LDxH33OzrWM0-ZpgNrR5WQb8yG5AmaKqd7cZlLTo1v0/edit
Configured RTL to use 'data-test-id' rather than 'data-testid' for its selector:
https://docs.google.com/document/d/1LDxH33OzrWM0-ZpgNrR5WQb8yG5AmaKqd7cZlLTo1v0/edit#heading=h.yohb9h5pqgoa
---
> [no ticket][risk=no] Convert a few Enzyme tests with Copilot assistance.

- .circleci/config.yml
This was ordering of CI as introduced in https://github.com/all-of-us/workbench/pull/8454
Desired ordering:
---
> [no ticket][risk=no] Changing ordering of contract requirements

- api/config/config_local.json
- api/config/config_test.json
Switching local and test environments back to using staging version of RAS.
These environments have been using a pre-production environment of RAS since just before ID.me was released.
Switching back because pre-prod RAS is supposed to be temporary.
---
> [no ticket][risk=low]Switch local and test environments back to staging RAS.

- ui/src/app/pages/data/cohort/constant.ts
- ui/src/app/pages/data/cohort/search-group-item.tsx
- ui/src/app/pages/data/cohort/selection-list.tsx
- ui/src/app/pages/data/cohort/variant-search.tsx
- Make display more user-friendly for select all filters in variant search
- Use same layout for displaying filters in search group items UI (excluding the Participant Count Overview section)
---
> [DT-777][DT-791][risk=no] Refine display for variant filter selections

- api/src/main/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisService.java
- api/src/test/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisServiceTest.java
We configure a Playground Mode for Jupyter runtimes, but the concept does not apply to RStudio and SAS.  Previously, we created a "workspaces_playground" folder for these apps, but it serves no purpose.  Remove it to avoid confusing users.
Tested locally by:
* observing the lack of playground directory in RStudio and SAS, and confirming that localization still works in these apps.
* observing that localization and playground continue to work in Jupyter
SAS
RStudio
Jupyter still has a playground
---
> [risk=low][RW-12234] Playground is for Jupyter only

- ui/src/app/pages/workspace/workspace-card.tsx
It was choosing the "id" (terra name) for display instaad of the name which is meaningful to users.
---
> [risk=low][no ticket] Fix display name for "can't delete workspace"

- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/EgressEscalationTargetProperty.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
I have been using an overly verbose pattern in some cases, based on a mistaken assumption that I need to account for nulls when using  `Optional.map()`:
`Optional.ofNullable(foo).flatMap(f -> Optional.ofNullable(f.getBar()))`
But the actual implementation of `Optional.map()` already includes this, so instead we can just call `map()`
`Optional.ofNullable(foo).map(FooType::getBar)`
---
> [risk=low][no ticket] Can simplify some cases b/c Option.map() is null safe

- api/src/main/java/org/pmiops/workbench/config/CommonConfig.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
This is deleted in https://github.com/all-of-us/workbench/pull/8462/files#diff-c99d07856632444c11b1e0088c3c5bdd85bd88c798427c02aa900dc40673c709 but used by reporting services. 
---
> [no ticket][risk=no] Add stopwatch bean back

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/interactiveanalysis/InteractiveAnalysisServiceTest.java
- api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java
- ui/src/app/components/apps-panel/expanded-app.spec.tsx
- ui/src/app/pages/analysis/leonardo-app-launcher.tsx
- ui/src/app/utils/user-apps-utils.tsx
- ui/src/testing/stubs/apps-api-stub.ts
Add a new query parameter (default as `false`), it will localize all files under `WS bucket/notebooks dir` when setting to `true`
Background detail see: https://docs.google.com/document/d/1dnpjLDZd1nhv7cRfdBlgCnnOw7QvOGZClE2HJnNruww/edit 
---
> [RW-12277][risk=low] Update localizeRuntime and localizeApp API to support localized all files

- ui/src/app/pages/data/cohort/cohort-criteria-menu.tsx
- ui/src/app/pages/data/cohort/variant-search.tsx
- Prevents UI from breaking if `exclusionList` is undefined
- Disable search input when editing select all filter
> [no ticket][risk=no] Variant select all edit fix

- ui/src/app/pages/data/cohort/list-search.spec.tsx
- ui/src/app/pages/data/cohort/selection-list.spec.tsx
- ui/src/app/pages/login/account-creation/account-creation-modals.spec.tsx
Updated the following tests from Enzyme to RTL:
ui/src/app/pages/data/cohort/list-search.spec.tsx
ui/src/app/pages/data/cohort/selection-list.spec.tsx
ui/src/app/pages/login/account-creation/account-creation-modals.spec.tsx
---
> [RW-12347][risk=no] Updated three Enzyme tests to RTL

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/auth/ServiceAccounts.java
- api/src/main/java/org/pmiops/workbench/rawls/RawlsConfig.java
- api/src/main/java/org/pmiops/workbench/utils/AppEngineUtils.java
- api/src/main/webapp/WEB-INF/appengine-web.xml.template
Similar to  https://github.com/googleapis/google-auth-library-java/pull/1087, upgrading auth breaks `createScoped` when using appengine's SA. 
This PR brings the old way back.
---
> [no ticket][risk=low] Upgrade auth library and use legacy bundle service

- ui/package.json
- ui/yarn.lock
Includes:
* typescript 5.3.3 -> 5.4.5 from #8478
* yarn 1.22.21 -> 1.22.22 from #8480
* @types/react 17.0.79 -> 17.0.80 from #8496 
* @types/lodash 4.14.202 -> 4.17.0 from #8479
There is a new error message which says that `typescript-estree` may not be compatible with this version of typescript, but I am not seeing problems there either.  I also do not see an easy way to remove this at the moment.
---
> [risk=low][no ticket] Upgrade a few UI packages

- ui/src/app/pages/data/cohort/selection-list.tsx
- ui/src/app/pages/data/cohort/variant-search-filters.tsx
- ui/src/app/pages/data/cohort/variant-search.tsx
- Fix issue where save criteria button stays disabled when editing filter for an existing search item
- Fix issue where deleting an single variant when a select all group also exists breaks the UI
- Fix React console errors due to missing `key` props
- Add tooltips when Select All Results button is disabled
> [DT-807][risk=no] CB variant select all fixes

- ui/src/app/components/runtime-status-indicator.spec.tsx
- ui/src/app/components/search-input.spec.tsx
- ui/src/app/components/search-input.tsx
- ui/src/app/components/side-nav.spec.tsx
- ui/src/app/components/side-nav.tsx
The disabled items on the left-hand Side Navigation Bar did not have our usual "not allowed" cursor styling.
Before
After
---
> [risk=low][RW-12400] 3 Enzyme conversions and a small UI change

- ui/src/app/components/inputs.spec.tsx
- ui/src/app/components/inputs.tsx
Two recent changes to input aria label logic caused some unexpected consequences in tests.
[I introduced a field (ariaLabel) to TextAreaWithLengthValidationMessage to support arbitrary aria labels.](https://github.com/all-of-us/workbench/pull/8511/files#diff-e20d25e18ad70d1c526af33dd200e80376f4c624abc466a553a1563a9c0eb3d7R165-R253)
[Joel added a change that auto populated aria-label to the id value](https://github.com/all-of-us/workbench/commit/7fbfeac86143b6d29dc26892e8af31c5f3ab5b27#diff-e20d25e18ad70d1c526af33dd200e80376f4c624abc466a553a1563a9c0eb3d7R236)
---
> [RW-12418][risk=no] Fixed duplicate aria label issue

- ui/src/app/pages/admin/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/admin-institution-edit.tsx
This is to unblock Broad deprecate shibboleth server, after this, there will no institution require eRA hence no shibboleth call from us
---
> [RW-12513][risk=no] Remove eRA required toggle from insitution admin page

- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- ui/src/app/pages/admin/workspace/admin-workspace.tsx
- ui/src/app/pages/admin/workspace/cloud-environments-table.tsx
This does not resolve RW-12516, but it improves Admin Workspace UI performance and should also help with debugging.
Instead of calling List Runtimes and List Apps internally to the Workspace Admin View call, separate those into new endpoints, and call them in parallel.
Tested by running locally.
---
> [risk=low][RW-12516] Split runtimes and apps from workspace admin endpoint

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryController.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
Ran the cron twice, the tasks are passing now
Logs show that the task is completed
Free tier Billing Service: Finished handling initial credits expiry event for users: [4599, 4485]
---
> [risk=low][no ticket] npe getting user

- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/cb_search_person_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/resources/workbench-api.yaml
adding has_wear_consent flag to CB menu and query engine.
---
> [DT-811][risk=no] adding has_wear_consent flag

- ui/src/app/components/breadcrumb.tsx
- ui/src/app/pages/appAnalysis/app-files-list.tsx
A Prod Eng Demos participant pointed out that some of the links on our Analysis tab are low-contrast, which is bad for accessibility.  Ideally we should have a [contrast ratio of 4.5 or higher](https://www.siegemedia.com/contrast-ratio).
This PR changes the behavior of "visited" links to behave in the same way as "non-visited" links on the page: they remain dark blue instead of changing to light blue, improving their contrast ratios from 2.7 to 4.7.
Before (the dark links here are un-visited)
After
---
> [risk=low][no ticket] Visited links in the Analysis tab were low-contrast

- api/src/main/resources/workbench-api.yaml
#8534 has been released, so it's now safe to remove the deprecated API fields.
No expected changes.  Tested locally with no apparent problems.
---
> [risk=low][RW-12516] Remove unused fields after release

- api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
found in prod logs a couple of exception that may cause the cloud task to fail. This PR will make the cloud tasks less flaky, and also added logs to identify why the cron job reports 500.
```
ErrorId e965b379-180f-4ed3-aac0-83104dbe9247: org.springframework.transaction.CannotCreateTransactionException
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction
at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:466)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:531)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.handleExistingTransaction(AbstractPlatformTransactionManager.java:452) …
```
> [risk=no][no-ticket] Fix transaction not found issue and concurrent modification exception

- api/config/config_preprod.json
- api/config/config_staging.json
Bring the new app machine config ability to Staging and Preprod.  Not Prod or Stable yet.
DONE ~Waiting on the resolution of a UI bug: when machine config is active, we only show the CPUs and RAM, not the disk size.  #8558 displays the disk size elsewhere, so one solution would be to merge that as well as removing the disk information from non-configurable machine config.~
---
> [risk=low][RW-9065] Enable app machine config for Staging and Preprod

- api/build.gradle
build local images: `./gradlew jibDockerBuild  `
<
!--
Reminder: If you decide to merge with any failing checks, add an explanatory comment before doing so.
-->
---
> [RW-10516][risk=low] Install jib plugin

- api/config/config_prod.json
- ui/src/app/pages/data/cohort/variant-search.tsx
- ui/src/app/pages/data/criteria-search.tsx
- Set lower select all limit to the result page size (25) and add more info to tooltip
- Fix height for results table to adjust for large screens
- Enable `enableVariantSelectAll` config flag for prod
> [DT-820][DT-768][risk=no] Variant select all updates

- api/src/bigquerytest/resources/bigquery/cbdata/cb_variant_attribute_genes_data.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java
> [DT-829][risk=no] fixing variant search bug

- .circleci/config.yml
Another problem caused by #8598 which requires a fix similar to #8599
The staging e2e test run failed because it wasn't logged in: https://app.circleci.com/pipelines/github/all-of-us/workbench/33055/workflows/50af3484-8074-4f43-9bf9-7dce519235f3/jobs/359035
---
> [risk=low][RW-11850] Fix staging e2e

- ui/src/app/pages/admin/user/admin-user-profile.spec.tsx
> [RW-12615][risk=no] Converted admin-user-profile.spec.tsx

- ui/src/app/pages/admin/workspace/basic-information.tsx
This is often useful in constructing URLs and API calls.  Tested locally.
---
> [risk=low][no ticket] Add Terra Name to the Admin Workspace page

- ui/src/app/pages/workspace/workspace-card.spec.tsx
- ui/src/app/pages/workspace/workspace-library.spec.tsx
I found a few test files that were not importing enzyme directly.
---
> [RW-12897][risk=no] Converted lingering workspace tests

- deploy/libproject/deploy.rb
Tested by pushing this version as `v8-8-rc2` and attempting a deploy of that version to Stable.  I was able to get past the current problem Yonghao was having.
```
deploy/project.rb deploy --project all-of-us-rw-stable --account deploy@all-of-us-rw-stable.iam.gserviceaccount.com --promote --app-version v8-8-rc2 --git-version v8-8-rc2
```
---
> [risk=low][RW-11850] Use new credentials for releases

- .circleci/config.yml
- e2ev2/package.json
- e2ev2/yarn.lock
The upgrade in https://github.com/all-of-us/workbench/pull/8617 did not trigger an e2ev2 run, so it was not properly tested.  This PR reverts most of it.
---
> [risk=low][no ticket] Revert an e2ev2 upgrade which broke it

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoCustomEnvVarUtils.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
Currently this is protected by feature flag. If ff is on, we will pass workspace bucket to Leo. 
In the future, mounting or not might be passed from UI depends on the UX research
This is blocked by https://github.com/DataBiosphere/leonardo/pull/4628
---
> [RW-12855][risk=low] Support mount GCS bucket in SAS and RStudio

- ui/src/app/pages/workspace/invalid-billing-banner.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Update "initial credits expired" workspace banner text, and change the button to Edit Workspace.  This navigation will also cause the billing account dropdown to be highlighted.
---
> [risk=low][RW-11636] Update workspace out of credits notification

- api/db-cdr/changelog-schema/db.changelog-master.xml
- api/db-cdr/changelog-schema/db.changelog-v2-10-cb_criteria_modify.xml
- api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json
- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortBuilderControllerBQTest.java
- api/src/bigquerytest/resources/bigquery/cbdata/person_data.json
- api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
- api/src/bigquerytest/resources/bigquery/schema/person.json
- api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
- api/src/main/resources/workbench-api.yaml
Adding self reported category to indexing build for CDRv8
---
> [DT-825][risk=no] Adding self reported category to indexing build for CDRv8

- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/UserMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapperTest.java
No intended changes here.  I was getting confused by some of the WorkspaceMapper methods, so I wanted to simplify that file.
Tested locally with no apparent problems.
---
> [risk=low][no ticket] Some WorkspaceMapper refactoring

- ui/src/app/pages/data/cohort/variant-search.tsx
Fix issue where the minimum length error still displays after a valid search or the search is cleared.
> [DT-827][risk=no] Clear error for valid variant searches

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Make the WorkspaceMapper work for both cases of the Feature Flag `enablePublishedWorkspacesViaDb` by separating the logic of the two cases with respect to Workspace: one uses `published` and the other uses `featuredCategory`.
Also deprecate `published`.
---
> [risk=low][no ticker] More WorkspaceMapper refactoring

- api/db-cdr/generate-cdr/bq-schemas/ds_person.json
- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
Self reported category is a new column added to the person table and needs to show up in dataset builder. This PR adds self reported category to the indexing build.
---
> [DT-826][risk=no] adding self reported category to dataset builder

- api/src/main/java/org/pmiops/workbench/db/dao/FeaturedWorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspaceAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Does not resolve RW-13148.  Some fixes for small problems I noticed.
Change 500s to 404s
Optional<FeaturedWorkspaceCategory> getFeaturedCategory
Tested locally by calling endpoints and interacting with workspaces in the UI
---
> [risk=low][RW-13148] Small changes to Workspace Publish

- api/build.gradle
Building our Java project produces an ugly error message when the wrong Java version is used, because we load plugins which are incompatible with older version of Java.
Moving the check earlier restores the friendly behavior.
```
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/thibault/src/aou/api/build.gradle' line: 17
* What went wrong:
A problem occurred evaluating root project 'api'.
> This build must be run with Java 17. See developer-system-initialization.md. The java version used was 11.
```
---
> [risk=low][no ticket] Check the Java version before loading plugins

- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
Publish/unpublish did not work when the workspace was not owned by the admin user.  We require Owner to publish old-style featured workspaces, but we do not want to require this in the new process.
Instead of calling "update Terra ACL" as the admin user, call it as the RWB system itself, which will always have the appropriate access to do this.
Tested locally by publishing/unpublishing workspaces which are owned by my user and not owned by my user.
---
> [risk=low][RW-13148] Enable publish/unpublish of featured workspaces when not owner

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/login/login-error-banner.tsx
- ui/src/app/pages/login/login.spec.tsx
- ui/src/app/pages/login/login.tsx
For now we can use a featureflag, but later we can control the banner and text via service banner by adding a new field say ShowOnLoginPage
---
> [RW-8478][risk=medium] Consider enabling status banners before sign-in

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
We just want the banner on Pre prod and PROD. Turning off flag on stable and stagging
---
> [noTicket][risk=low]Switch flag false on all env except preprod and prod

- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
This is part of my long-running "Don't use `ID` to refer to Terra Names" campaign.  There will be many other changes following this one.
No observable changes in the UI, as expected.  The API returns the new `terraName` and `displayName` fields, as expected:
```
"workspace": {
"id": "ctjun13",
"etag": "\"1\"",
"name": "CT Jun 13",
"displayName": "CT Jun 13",
"namespace": "aou-rw-local1-c5c09753",
"terraName": "ctjun13",
"cdrVersionId": "8",
...
```
---
> [risk=low][no ticket] Add displayName and terraName to Workspace API entity, and deprecate id and name

- api/src/main/resources/workbench-api.yaml
Part of the "Don't use `ID` to refer to Terra Names" agenda I like to push in the downtime between other work.
Tested locally - no noticeable changes, as expected.  We don't actually use the URL parameter names, so you can think of this as a documentation change.
---
> [risk=low][no ticket] Update workspace endpoint param names from workspaceId to terraName

- api/src/main/java/org/pmiops/workbench/api/CloudTaskWorkspacesController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
- api/src/test/java/org/pmiops/workbench/actionaudit/targetproperties/TargetPropertyExtractorTest.java
- api/src/test/java/org/pmiops/workbench/actionaudit/targetproperties/WorkspaceTargetPropertyTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
> [risk=low][no ticket] Use Worspace.terraName instead of id throughout api

- aou-utils/serviceaccounts.rb
Starting from jul/23 the developers are unable to run the following commands for any enviornment
deploy/project.rb deploy
As we get the following error 
_/root/workbench/aou-utils/serviceaccounts.rb:36:in `initialize': undefined method `exists?' for File:Class (NoMethodError)
Dir.mkdir(colima_path) unless File.exists?(colima_path)_
The exists method was removed on Ruby v3.2 so we are using exist. 
I did check we do not use .exists anywhere else
---
> [noTicket][risk=none] Use exist as exists doesnt work for latest Ruby version

- ui/src/app/pages/admin/workspace/admin-lock-workspace.spec.tsx
- ui/src/app/pages/admin/workspace/admin-lock-workspace.tsx
- ui/src/app/pages/workspace/workspace-about.spec.tsx
- ui/src/app/pages/workspace/workspace-about.tsx
A workspace owner should not publish a workspace that is locked. 
Admins: Should not lock a workspace that is already published. They need to unpublish and then lock it
**Published Workspace Admin page:**
**Locked Workspace About page**
---
> [RW-13222][risk=no]Locked and Published workspace

- ui/src/app/pages/admin/workspace/basic-information.spec.tsx
- ui/src/app/pages/admin/workspace/basic-information.tsx
> [RW-13222][risk=no]  Locked and published workspace

- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/emails/publish_community_workspace/content.html
- api/src/main/resources/emails/publish_workspace/content.html
- api/src/main/resources/emails/unpublish_workspace/content.html
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Update emails with text and logic as described in the Jira ticket.  Tested locally.
Publish Community Workspace
Unpublish (any) kind of Featured Workspace
---
> [risk=low][RW-13149] Update Workspace publish/unpublish email content and logic

- aou-utils/utils/common.rb
- deploy/libproject/deploy.rb
- ops/ruby/devops-toolkit/tasks/lib/service_account_manager.rb
Followup to #8677
There are now no more remaining references to `File.exists?()` in the repo.
---
> [risk=low][no ticket] Continue conversion of File.exists?() to File.exist?()

- api/db-cdr/generate-cdr/init-new-cdr-db.sh
- api/db/run-migrations.sh
- api/docker-compose.yaml
- api/libproject/devstart.rb
- api/libproject/mysql_docker.rb
- tanagra-aou-utils/init_new_tanagra_db.sh
For our local docker runs which power things like `dev-up`, deployment, config updates, environment DB access, and many other `project.rb` commands, we use MySQL-compatible [MariaDB](https://mariadb.com/) clients instead of the official MySQL docker images, because they have much better docker support.
MariaDB versions don't directly correspond to MySQL versions.  It's possible that our existing version 10.2 supports both MySQL 5.7 and 8.0, but the latest 10.x certainly should.  Let's upgrade in case that helps smooth this migration.
Tested by running these local `project.rb` commands which use the mariadb client:
* connect-to-db
* connect-to-cloud-db
* dev-up
* run-local-all-migrations
* update-cloud-config
I then confirmed that the app behavior seemed normal.
---
- One …
> [risk=low][RW-12482] Bump local mariadb clients to latest 10.x

- ui/src/app/pages/data/cohort/demographics.tsx
Fixing the age slider in Cohort Builder to account for participants over 120 years of age
---
> [DT-858][risk=no] Fixing the age slider in Cohort Builder

- api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
We weren't handling missing API endpoints, causing clients to see 500s.  Instead, handle them with the expected 404 Not Found.
Tested locally.  The RWB continues to work as expected.  Local curl calls to nonexistent endpoints now see returned 404s instead of 500s.
---
> [risk=low][no ticket] Convert missing endpoint 500s to 404s

- .circleci/config.yml
I received a CircleCI email saying that an experimental feature in our config was going away soon: notification filtering.  This PR removes it.
---
Hello,
I’m writing to inform you that the experimental feature allowing you to filter notifications by branch is now deprecated, and will be removed on September 4th 2024. If you are receiving this email your organization has been identified as utilizing this feature.
Once the change is completed you will continue to receive notifications but the code in your config will no longer modify and filter notifications.
Your builds will not be disrupted and you are not required to take any action, but we do recommend removing the experimental notify option from config to stay current with our supported features and functionality.
Example …
> [risk=low][no ticket] rm deprecated experimental-notify

- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- ui/src/app/pages/admin/workspace/basic-information.tsx
- ui/src/app/pages/admin/workspace/workspace-publishing-info.spec.tsx
- ui/src/app/pages/admin/workspace/workspace-publishing-info.tsx
No expected changes.  Tested locally, works as expected.
---
> [risk=low][no ticket] Ws admin UI: split out publishing from basic info

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
Removing cast function from query to improve efficiency.
---
> [no ticket][risk=no] fixing slow query

- api/src/main/java/org/pmiops/workbench/cdr/dao/CBCriteriaDao.java
removing cast function for CB dao
---
> [DT-863][risk=no] removing cast function for CB dao

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserInitialCreditsExpirationDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserInitialCreditsExpiration.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessSyncServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
Added logic so that when enableInitialCreditsExpiration is true, a credit expiration record is added when a user is updated.
---
> [RW-13300][risk=no] Add credit expiration for new access to RT

- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationService.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
Tested locally.  Works as expected, and includes checking the `bypassed` field.
Also add InitialCreditsExpirationService
---
> [risk=low][RW-13485] Add initial credits expiration to user Profile

- api/src/bigquerytest/java/org/pmiops/workbench/api/CohortReviewControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Return this value (when applicable) in the user Profile object and in the Workspace object for at least these API calls
* ~Get Profile~ moved to #8743
* Get Workspace
* List Workspaces
* List Recent Workspaces
* List Featured Workspaces (new style)
Tested locally
---
> [risk=low][RW-13484] Add initialCreditsExpirationEpochMillis to Workspace endpoints

- e2e/yarn.lock
- e2ev2/yarn.lock
- ui/yarn.lock
Resolves
* https://security.snyk.io/vuln/SNYK-JS-MICROMATCH-6838728
* https://github.com/all-of-us/workbench/security/dependabot/96
* https://github.com/all-of-us/workbench/security/dependabot/97
* https://github.com/all-of-us/workbench/security/dependabot/98
No noticeable changes
---
> [risk=low][no ticket] Bump micromatch to latest for ui, e2e, and e2ev2

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
DUCC v4 is no longer valid as current because it's over a year old and newer versions exist.
Similar to disabling v3 in #8097
We'll need to do this again for v5 in November.
Tested locally by manually setting my user's DUCC version to 4, observing that the user lost access, and re-enabling the user via re-signing the DUCC in Data Access Requirements.
---
> [risk=low][no ticket] DUCC v4 is no longer current

- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
fixing query in indexing build
---
> [no ticket][risk=no] fixing query in indexing build

- api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
- api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
- api/db-cdr/generate-cdr/build-cb-search-person.sh
- api/db-cdr/generate-cdr/build-ds-linking.sh
- api/db-cdr/generate-cdr/build-ds-tables.sh
setting count to zero so indexing will pass
---
> [no ticket][risk=no] setting count to zero so indexing will pass

- api/src/main/webapp/WEB-INF/cron_base.yaml
Since GCP does not seem to want a cron job in just one environment, setting up checkInitialCreditsExpiration (in all environments but test) to run a year from now. The intention is that the cron job will be ready in all environments by then.
---
> [RW-13428][no risk] Setup cron for non-test environments

- api/config/institutions_local.json
- api/db/changelog/db.changelog-233-add-user-initial-credit-expiration-notification-column.xml
- api/db/changelog/db.changelog-234-add-institution-initial-credit-expiration-bypass.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbInstitution.java
- api/src/main/java/org/pmiops/workbench/db/model/DbUserInitialCreditsExpiration.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
Also fixes a user profile 500 bug.
Note: does not connect this new field to any logic
---
> [risk=low][RW-13502] Add initial credits bypass field to institution

- ui/src/app/pages/workspace/create-billing-account-modal.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/app/utils/access-utils.spec.tsx
A workspace where the user is the creator
A workspace where they are Owner but not creator
---
> [risk=low][no ticket] UI: Only workspace creators can change billing accounts

- ui/yarn.lock
https://github.com/all-of-us/workbench/security/dependabot/101
https://github.com/all-of-us/workbench/security/dependabot/102
We have packages that depend on 3 versions of `path-to-regex`.  This PR upgrades 2 of them to non-vulnerable versions.  For a full fix, we also need to update `openapi-generator-cli` after these issues have been resolved
* https://github.com/nestjs/nest/issues/13955
* https://github.com/OpenAPITools/openapi-generator-cli/issues/796
Tested locally with no apparent effect on UX.
---
> [risk=low][no ticket] Partially address path-to-regex vulnerability

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
- api/src/main/java/org/pmiops/workbench/api/UserController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/BillingUtils.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/billing/FreeTierBillingServiceTest.java
- api/src/test/java/org/pmiops/workbench/firecloud/FireCloudServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceAuthServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/CreateWgsCohortExtractionBillingProjectWorkspace.java
Tested locally by interacting with an Initial-Credits workspace and observing that it worked nornally
---
> [risk=low][no ticket] Centralize billing account naming logic

- ui/package.json
- ui/yarn.lock
Another attempt at #8209 - I don't recall why I closed that one.
Inflight has been abandoned and will never be made secure.  Glob v8 and lower depend on Inflight.  The Glob maintainer will not be releasing a non-vulnerable version of Glob 8. https://github.com/isaacs/node-glob/issues/573
---
> [risk=low][no ticket] Force glob to 9 to resolve a vulnerability

- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/utils/user-apps-utils.tsx
Partial completion of RW-11664:
✅ can increase unattached PD size and attach to newly created app
❌ does not allow changing PD size for running app - that will need a Leo change
Because the second part requires significant effort, we may choose to deprioritize it.  This PR should unblock users.
Tested locally by creating RStudio apps, saving files to the PD, and after recreating the app with an increased disk size:
* observed that the saved files were retained
* observed that I had access to a larger home folder by creating large files in excess of the previous limit
Updated the disk size tooltip when an app is currently running.
Creation is blocked when disk size is decreased.  That requires deletion of the disk, which the user may continue to do explicitly.
---
- One or …
> [risk=low][RW-11664] Allow increasing GKE App disk size at app creation time

- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/copy-modal.spec.tsx
- ui/src/app/components/copy-modal.tsx
Part 1 of a multi-step process due to release safety: add a new field to the entity object CopyRequest, and update the UI to write to both the old name and the new.
Tested locally by copying a Notebook between workspaces
---
> [risk=low][no ticket] Terra Name: add CopyRequest.toWorkspaceTerraName and dual-write in UI

- api/build.gradle
Resolves https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-8055227 and https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-8055228
Tested locally with no apparent problems
---
> [risk=low][no ticket] Bump protobuf packages to resolve Snyk vulnerability

- ui/package.json
- ui/yarn.lock
Resolves https://github.com/all-of-us/workbench/security/dependabot/103
We can't upgrade to v3 of rollup normally, so we need to force it.
Tested locally with no observed changes.
---
> [risk=low][no ticket] Force rollup version to resolve a vulnerability

- ui/src/app/utils/analysis-config.spec.tsx
- ui/src/app/utils/analysis-config.tsx
We did not correctly apply the existing Persistent Disk information when transitioning from DataProc to "Standard VM" (GCE), so it incorrectly attempted to create a new PD.  This is not allowed since one already exists, and it fails with a 400 error.  However we did not display this information to users, so it appeared to be still creating, and would eventually time out.
To repro:
1. on Local/Test or Test, create a Standard VM (GCE) runtime in a CT workspace
2. once it is running, open the Jupyter panel and create a DataProc runtime instead.  This will involve deleting the GCE runtime.  Choose "keep the disk" when prompted.
3. once the DataProc runtime is running, open the workspace **on Test** and attempt to create a GCE runtime.  You should see in the Network tab that the runtime is …
> [risk=low][RW-13700] Could not transition from DataProc to GCE when a PD existed

- ui/src/app/components/apps-panel/utils.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx
- ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx
- ui/src/app/utils/machines.ts
Adds the choices of 1 hour and 8 hours, and makes 8 hours the SAS default.
[x] Confirm that these are desired
[x] Update Leo autodelete monitor
---
> [risk=low][RW-12525] Update GKE App autodelete thresholds

- api/src/main/java/org/pmiops/workbench/actionaudit/targetproperties/WorkspaceTargetProperty.java
- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
- api/src/test/java/org/pmiops/workbench/actionaudit/targetproperties/TargetPropertyExtractorTest.java
- api/src/test/java/org/pmiops/workbench/actionaudit/targetproperties/WorkspaceTargetPropertyTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java
- ui/src/app/utils/authorities.spec.tsx
- ui/src/app/utils/authorities.tsx
Also remove remaining FEATURED_WORKSPACE_ADMIN references from UI.
Tested locally with no problems, including interacting with featured workspaces
---
> [risk=low][RW-12248] rm workspace.published from API

- api/src/main/java/org/pmiops/workbench/api/CohortAnnotationDefinitionController.java
- api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java
- api/src/main/java/org/pmiops/workbench/api/CohortReviewController.java
- api/src/main/java/org/pmiops/workbench/api/CohortsController.java
- api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java
- api/src/main/java/org/pmiops/workbench/api/DataSetController.java
- api/src/main/java/org/pmiops/workbench/api/NotebooksController.java
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksService.java
- api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java
- ui/src/app/pages/admin/workspace/basic-information.tsx
Rename many instances of "workspaceId" to "workspaceTerraName" and similar.  No expected functional changes.
Tested locally with no observed changes
---
> [risk=low][RW-3890] API: Mass renaming of workspaceId to workspaceTerraName

- api/src/main/java/org/pmiops/workbench/api/DisksController.java
- api/src/main/java/org/pmiops/workbench/disks/DiskService.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
The UI only calls the list-all-disks-in-workspace endpoint.  We're not using this one.
Tested locally by interacting with disks
---
> [risk=low][no ticket] Remove unused getDisk/getPersistentDisk

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/app/components/ct-available-banner-maybe.spec.tsx
- ui/src/app/pages/access/data-access-requirements.spec.tsx
- ui/src/app/pages/access/data-access-requirements.tsx
- ui/src/app/pages/admin/user/admin-user-bypass.spec.tsx
- ui/src/app/pages/admin/user/admin-user-common.tsx
- ui/src/app/pages/admin/user/admin-user-profile.spec.tsx
- ui/src/app/pages/admin/user/admin-user-table.spec.tsx
- ui/src/app/pages/data/cohort/modifier-page.spec.tsx
- ui/src/app/pages/homepage/homepage.spec.tsx
- ui/src/app/pages/workspace/workspace-about.spec.tsx
- ui/src/app/utils/institutions.tsx
- ui/src/testing/default-server-config.ts
- ui/src/testing/stubs/institution-api-stub.ts
- ui/src/testing/stubs/profile-api-stub.ts
Remove `eraRequired` from UI
---
> RW-12240 Remove eraRequired from UI

- api/src/main/resources/workbench-api.yaml
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/utils/analysis-config.spec.tsx
- ui/src/app/utils/runtime-hooks.spec.tsx
- ui/src/testing/stubs/disks-api-stub.ts
I am in the process of adding functionality for users to be able to change their zone for a Jupyter environment. That ticket is getting fairly long and complex, so I am breaking this change into its own PR.
This PR adds the zone attribute to the Disk object. This attribute is needed, because of a potential zone discrepancy issue. The zone that a user selects for their Jupyter environment will also be the zone of the associated persistent disk. If a user deletes their Jupyter environment and keeps their disk, they will encounter an error if they try to create a Jupyter environment with a different zone.
Once zone can be read from a persistent disk, we can force future Jupyter environments to be created with the same environment and tell the user that if they want a different zone, they …
> [RW-9601][risk=no] Add zone to Disk object so that it will be read over from Leo.

- api/src/main/webapp/WEB-INF/cron_test.yaml
Temp disable a Test cron to help Terra debug a Sam issue
---
> [risk=low][no ticket] temp set checkPendingEgressEvents to effectively-never on test

- api/config/institutions_local.json
- api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbInstitutionTierRequirement.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java
- api/src/main/java/org/pmiops/workbench/institution/InstitutionTierConfigMapper.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/InstitutionTierRequirementDaoTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionMapperTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java
- api/src/test/java/org/pmiops/workbench/institution/InstitutionTierConfigMapperTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Test:
Ran UI locally against local API, and checked the following pages, and they all function as expected
Data Access Requirements
Institution Admin
User Admin Table - bypass controls
User Admin Profile - for an individual user
---
> RW-12240 remove `eraRequired` from API

- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/institution/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/user/admin-user-egress-bypass.spec.tsx
- ui/src/app/pages/admin/user/admin-user-egress-bypass.tsx
- ui/src/app/pages/admin/user/admin-user-profile.tsx
- ui/src/app/pages/admin/workspace/admin-workspace.tsx
- ui/src/app/utils/authorities.tsx
- ui/src/testing/react-test-helpers.tsx
We use a specific Authority for egress which differs from Workspace Admin and User Admin.  Prevent API calls from these UI pages when the user doesn't have the right authority.  This is strictly a UX improvement, because the API already correctly prevented access.
Users with the correct Authority continue to have access to list-egress-events, list-egress-windows, and bypass-egress.
---
> [risk=low][no ticket] Better UX for egress on User Admin and Workspace Admin pages

- api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
- api/src/main/java/org/pmiops/workbench/disks/DiskService.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoConfig.java
- api/src/main/java/org/pmiops/workbench/leonardo/PersistentDiskUtils.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/disk/DiskServiceTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
- api/tools/src/main/java/org/pmiops/workbench/tools/ListDisks.java
Tested by observing normal functionality of these endpoints which now use the new DisksApi:
* deleteDisk()
* updateDisk()
* listOwnedDisksInWorkspace()
* adminDeleteDisk()
* listDisksInWorkspace()
* cron - checkPersistentDisks
* ListDisks tool
---
> [risk=low][RW-10064] Use new Leo disks client in all cases

- ui/src/app/pages/admin/workspace/basic-information.tsx
Don't show an invalid "Billing Status" for User Provided billing.  For Initial Credits, break out the reasons for billing to be inactive and also show whose credits are being used.
---
> [risk=low][no ticket] Workspace Admin: only show billing status for Initial Credits

- api/src/main/java/org/pmiops/workbench/api/AppsController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoConfig.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/AppsControllerTest.java
- api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
Tested these calls from local UI to confirm that they function as expected:
* createApp
* listAppsInWorkspace
* deleteApp
* cron checkPersistentDisks (listAppsInProjectAsService)
* WorkspaceAdminController adminListUserAppsInWorkspace (listAppsInProjectAsService)
Removed because unused:
* getApp
TODO - I can't seem to trigger egress locally
* EgressRemediationService stopUserRuntimesAndApps (deleteUserAppsAsService)
---
> [risk=low][no ticket] Migrate Leo AppsApi calls to new client

- api/src/main/webapp/WEB-INF/queue.yaml
Add the missing queue required for /v1/cron/checkInitialCreditsExpiration
https://console.cloud.google.com/logs/query;query=protoPayload.taskName%3D%22163253454119015835%22%20protoPayload.taskQueueName%3D%22__cron%22;cursorTimestamp=2024-09-30T18:35:00.807870Z;duration=P30D?authuser=0&project=all-of-us-workbench-test
---
> [RW-13788][risk=no] Add missing queue

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessModuleServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
- ui/src/testing/default-server-config.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-12240
Depends on https://github.com/all-of-us/workbench/pull/8844
---
> RISK=low RW-12240 remove enableEraCommons from api

- deploy/libproject/deploy.rb
removing tanagra tag so workbench deploys properly
---
> [no ticket][risk=no] removing tanagra tag so workbench deploys properly

- ui/package.json
- ui/src/app/pages/analysis/confirm-playground-mode-modal.tsx
- ui/src/app/pages/analysis/interactive-notebook.tsx
- ui/yarn.lock
Resolves https://github.com/all-of-us/workbench/security/dependabot/104
We don't seem to use this package.  It's a transitive dependency.
Tested by interacting with a notebook, but that's actually `js-cookie`, not this package.
---
> [risk=low][no ticket] Force update cookie to resolve vulnerability

- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- ui/src/app/pages/admin/workspace/admin-workspace.tsx
- ui/src/app/pages/admin/workspace/cloud-environments-table.tsx
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/runtime-utils.tsx
This change is motivated by the ongoing Leo client upgrade process.  Soon "LeonardoListRuntimesResponse" will become "ListRuntimesResponse", which will clash with an existing ListRuntimesResponse RWB model entity.  I found that the existing ListRuntimesResponse RWB model entity is not used in many places, and also contains additional fields which we don't need, so I am replacing it with a new entity AdminRuntimeFields.
This is part 1: add new API endpoints which use the new entity, and update the UI to call the new endpoints.
Part 2 will remove the old endpoints.
Tested locally by creating a runtime and observing and deleting it in the Admin Workspace UI.
---
> [risk=low][no ticket] AdminRuntimeFields with v2 versions of admin runtime endpoints

- api/db/changelog/db.changelog-237-add-default-user-initial-credits-expiration-bypassed.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationService.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceImpl.java
- api/src/main/java/org/pmiops/workbench/institution/PublicInstitutionDetailsMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessSyncServiceTest.java
- api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserControllerTest.java
- api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/InitialCreditsExpirationServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/institution/PublicInstitutionDetailsMapperTest.java
- api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java
- api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
- ui/src/testing/stubs/institution-api-stub.ts
- ui/src/testing/stubs/profile-api-stub.ts
Split out the api work from https://github.com/all-of-us/workbench/pull/8850
Added `initialCreditsExpirationBypassed` to `Profile` and `institutionalInitialCreditsExpirationBypassed` to `PublicInstitutionDetails`
Added   these functions to InitialCreditsExpirationService.java:
```
DbUserInitialCreditsExpiration createInitialCreditsExpiration(DbUser user);
void setInitialCreditsExpirationBypassed(DbUser user, boolean isBypassed);
```
Changed AccessSyncServiceImpl.java to use function from InitialCreditsExpirationService
---
> [RW-13732][risk=no] Added api changes for user initial credit bypass

- api/libproject/cloudsqlproxycontext.rb
- api/libproject/devstart.rb
Bump the wait time which is causing many spurious CircleCI failures.  Tested locally by running a few project.rb commands.
---
> [risk=low][no ticket] mysql docker start can take a minute or longer

- api/libproject/devstart.rb
- api/tools/src/main/java/org/pmiops/workbench/tools/CreateTerraMethodSnapshot.java
This tool is used to update the Genomic Extraction Workflow.  We haven't used it for over 2 years, so it was no longer working.
I removed one of the operational modes (all-projects) and I was then able to run it with this command line (this is unlikely to produce a valid workflow / method; it's just for experimentation)
```
--source-git-repo all-of-us/workbench \
--source-git-path api/genomics/wdl/WgsCohortExtract.wdl \
--source-git-ref main \
--method-name joeltest \
--project all-of-us-workbench-test
```
I did not explore how to restore all-projects.  We don't strictly need it - a workaround is to run it once per project.
---
> [risk=low][RW-11727] Fix the Create Terra Method Snapshot tool

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
adding code to select between source or index query
---
> [DT-891][risk=no] adding code to select between source or index query

- api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/leonardo.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
This now approximates current state, to help ease the transition to using the Leo client.  No expected changes.
Tested locally by creating a runtime.  This process calls getRuntime() repeatedly to poll for success.
After deleting a runtime, opening the runtime configuration panel calls listRuntimes() to get information about previously deleted runtimes.  Tested by observing that this continued to work in cases where a disk exists and does not.
---
> [risk=low][no ticket] Update Leo swagger for GetRuntimeResponse and ListruntimeResponse

- api/src/main/java/org/pmiops/workbench/api/WorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminService.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
These are no longer used by the UI.  Tested locally by going to the Admin Workspace page and listing and deleting runtimes.
---
> [risk=low][no ticket] Remove deprecated admin runtimes endpoints

- ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx
Instead of using MILLIS_PER_DAY to determine a day length, this test subtracted calendar days.  When daylight savings is starting or ending, these values can be off by an hour.  I got unlucky this morning!
Now the test uses MILLIS_PER_DAY so it always lines up with the check.
UX impact: when we tell the user that "3 days remain" that's a whole-number estimate.  IMO it's fine to be off by an hour here.
---
> [risk=low][no ticket] Fix UI unit test which may fail on a time-change week

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
DUCC v6 has been out for a year now.  We expect all users with current access have completed annual renewal, so they have all signed v6 of the DUCC.  We don't need to support any older versions now.
Tested locally with no issues.
---
> [risk=low][no ticket] Make DUCC v6 the only valid version

- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- ui/src/app/pages/data/cohort/variant-search-filters.tsx
Fixing bug in variant filter
---
> [DT-916][risk=no] Fixing bug in variant filter

- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
For old workflow, the parameter is required, or we get the following error
```
[rawls-akka.actor.default-dispatcher-15] akka.actor.ActorSystemImpl - HttpMethod(POST) http://app:8080/api/workspaces/aou-wgs-cohort-extraction/aouwgscohortextraction/submissions: 400 Bad Request entity: {"causes":[],"message":"Validation errors: Missing inputs: GvsExtractCohortFromSampleNames.query_project","source":"rawls","stackTrace":[],"statusCode":400}
```
---
> RW-11727 add back query_project input for old workflow

- api/config/config_local.json
- api/config/config_test.json
Use the newest workflow from https://github.com/broadinstitute/gatk/pull/9036 , uploaded to Agora Dev via
```
--source-git-ref qi-attempt \
--method-namespace aouwgscohortextraction-test \
--method-name echo-prototyping \
--project all-of-us-workbench-test
```
Also remove the config from Local, because we do not have an appropriate Echo/v8 CDR there.
---
> [risk=no][RW-11727] Update test wgs extraction crdv8plus, rm local

- api/config/cdr_config_local.json
- api/config/config_local.json
To run a genomic extraction on Local:
* run the CDR migration with this branch checked out `./project.rb run-local-all-migrations`
* dev-up API and UI
* create a Workspace using this Controlled Tier CDR
* create a Dataset with genomics (the cohort does not need the "Genomics" Program Data, which may not appear on Local - many cohorts will have genomics data regardless)
* analyze/extract that dataset
---
> [risk=no][RW-11727] Add a v8 CDR and method config to local

- ui/src/app/components/footer.tsx
- ui/src/app/components/side-nav.tsx
When you are in a workspace, the "Your Workspaces" and "Featured Workspaces" do not work, though they do work when you're at the homepage - probably how we missed this.
Changing these links from relative to absolute means they now work in all cases.
---
> [risk=low][no ticket] Change footer links to absolute paths so they always work

- ui/src/styles.css
When I remove this setting using DevTools on Prod, it behaves in the way we expect.
I'm not sure why we were hiding the launcher button, but it seems that this is now the only way to close the menu, so we need it now.
---
> [risk=low][RW-13907] Fix Prod Zendesk by showing launcher button

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
Tested by running v7 and v8 extractions on Local
---
> [risk=low][RW-13930] Make gatkJarUri version-dependent

- api/db/changelog/db.changelog-243-replace-extension-count.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbUserInitialCreditsExpiration.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/profile/ProfileMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/access/AccessSyncServiceTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
- ui/src/app/pages/admin/institution/admin-institution-edit.spec.tsx
- ui/src/app/pages/admin/user/admin-user-profile.spec.tsx
- ui/src/app/pages/admin/user/admin-user-profile.tsx
- ui/src/testing/stubs/institution-api-stub.ts
The primary change in this PR relates to adding the extension date to the profile object and displaying that value on the admin user page which is shown below. In order to test this change, you should ensure that your user have a user_initial_credits_expiration record in the database. You will need to manually update the database to have an extension_time that is not null.
A secondary change was to hide fields that are irrelevant when a user has been institutionally bypassed from initial credit expiration. The result can be seen below:
https://github.com/user-attachments/assets/2682e6f3-88ca-475f-9a03-e6e404637971
---
> [RW-13736][risk=no] Add extension date

- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel/customize-panel.tsx
- ui/src/app/utils/analysis-config.spec.tsx
- ui/src/app/utils/analysis-config.tsx
- ui/src/app/utils/runtime-hooks.spec.tsx
- ui/src/app/utils/runtime-hooks.tsx
If a Jupyter PD existed (from a previous Standard/GCE VM) and there is a running DataProc cluster, it appears to be impossible to transition back to Standard (!!) or ever use that PD again (!!) - and this seems to have been true since July (!!)
At least in my local testing, this resolves that situation.
Longer term, I am thinking about how to address the complexity in the Jupyter runtime configuration and associated UI code.
---
> [risk=low][RW-13941] Re-enable transitions from DataProc to GCE

- ui/src/app/components/runtime-configuration-panel/customize-panel-footer.tsx
Tested by deleting DataProc runtimes without deleting the workspace's PD.  After deleting the runtime, it became possible to delete the PD, as expected.
---
> [risk=low][RW-13940] If a DataProc runtime and PD both exists, allow deletion of both

- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
- Remove the `showDataAppsVersionSelect` UI env var
- Only show the Data Apps version dropdown if one or more CDR version has `tanagraEnabled` set to `true
Tested locally by filtering out CDR versions with `tanagraEnabled: true` before set them in the store and verifying the data apps dropdown doesn't show:
If at least on CDR version is `tanagraEnabled`, the dropdown should show:
> [DT-914][risk=no] Switch to CDR version prop for Data Apps dropdown

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
Tested locally with smaller batch size 100
```
[Mon Nov 18 13:55:00 EST 2024] INFO: org.pmiops.workbench.reporting.ReportingUploadServiceImpl uploadBatchTable - Streaming upload into user table: 2 in 102ms (19.607843 rows/sec)
[Mon Nov 18 13:55:03 EST 2024] INFO: org.pmiops.workbench.reporting.ReportingUploadServiceImpl uploadBatchTable - Streaming upload into leonardo_app_usage table: 100 in 150ms (666.666667 rows/sec)
[Mon Nov 18 13:55:04 EST 2024] INFO: org.pmiops.workbench.reporting.ReportingUploadServiceImpl uploadBatchTable - Streaming upload into leonardo_app_usage table: 100 in 98ms (1020.408163 rows/sec)
[Mon Nov 18 13:55:05 EST 2024] INFO: org.pmiops.workbench.reporting.ReportingUploadServiceImpl uploadBatchTable - Streaming upload into leonardo_app_usage table: 100 in 97ms …
```
> [risk=low][RW-13725] Fix app usage reporting pipeline

- api/src/main/resources/emails/initial_credits_expiring/content.html
90 + 270 = 360 but 120 + 270 is not.
We could add a more accurate number, but what do you think about just leaving it out?
---
---
> [risk=low][no ticket] rm outdated reference to 270 days in credit expiration email

- api/config/config_local.json
- api/config/config_test.json
The extraction method was published from https://github.com/broadinstitute/gatk/pull/9051 (at commit 573e42063d107a5abbc0b69198c865043d0a8e4e)
```
--source-git-ref vs_1500_sample_ploidy_for_rwb_echo \
--method-namespace aouwgscohortextraction-test \
--method-name echo-prototyping
```
From the output of that command
```
New snapshot namespace/name/version: aouwgscohortextraction-test/echo-prototyping/3
```
---
> [risk=low][RW-14006] Bump extraction workflow version for Local and Test

- ui/src/app/pages/access/data-access-requirements.tsx
Add credit expiration warning to data access requirements page.
In order to test this, you will need to make sure that you have a record in the user_initial_credits_expiration table.
---
> [RW-13733][risk=no] Add expiration info to DAR completion message.

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
Also bump Local, Test, and Preprod to latest workflow versions.
Local and Test can use the more-efficient version at https://github.com/broadinstitute/gatk/tree/rwb_echo_release because we have updated the VPC controls there.
```
--source-git-ref rwb_echo_release \
--method-namespace aouwgscohortextraction-test \
--method-name echo-prototyping
Environment: all-of-us-workbench-test
New snapshot namespace/name/version: aouwgscohortextraction-test/echo-prototyping/16
Using source repo commit f4e44877ffd5bd101442325c96f856288cd319a9
```
Preprod needs to use the VPC workaround at …
> [risk=low][RW-11727] Only need to specify GATK Jar for legacy extractions

- ui/package.json
- ui/yarn.lock
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6671926
Tested locally with no apparent issues.
---
> [risk=low][no ticket] Force axios version to resolve vulnerability

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryController.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapperTest.java
DbWorkspace has a function, getBillingStatus, that has been deprecated, but billing status is still being used in various parts of the application. Until these usages can be removed throughout the application, we need to ensure that the UI is getting the correct billing status. This now being handled through mapping.
Future work:
- Drop billing_status column
- Drop getBillingStatus function
---
> [no ticket][risk=no] Account for User Provided Billing Account When Getting Billing Status.

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestConfig.java
> [risk=low][no ticket] Can't get app usage row count when we don't populate the table

- api/config/cdr_config_local.json
- api/db/changelog/db.changelog-245-add-vwb-template-id-cdr-version.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
In this PR, I add a CDR config to indicate the ID of the VWB workspace that will be used to create workspaces in AoU.
Each CDR version will have its own template to copy, that's why this is a CDR config rather than a global config
---
> [risk=no][RW-13631] Add cdr config for the VWB template that will be cloned to create a workspace

- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/workspace/invalid-billing-banner-maybe.spec.tsx
- ui/src/app/pages/workspace/invalid-billing-banner-maybe.tsx
Made workspace initial credit banners based on the extension status of the creator rather than the active user.
To test this, share a workspace between two users. Make the creator eligible for an extension by adding a record in the workbench.user_initial_credits_expiration table that has an expiration time in the past and no value for extension time.
Make the other user ineligible by adding a record in the workbench.user_initial_credits_expiration table that has expiration and extension time in the past.
Navigate to the workspace as the non-creator, and ensure that you see a banner mentioning extension.
---
> [no ticket][risk=no] Make eligibility based on workspace owner's initial credit eligibility.

- ui/src/app/pages/admin/user/admin-user-common.tsx
When a user has their initial credit expiration bypassed, the UI will currently show "credits will expire on -" when unbypassed. This is because expiration time is not exposed to bypassed users. This changes it so it will show ""credits will expire" in this case.
Current Case:
https://github.com/user-attachments/assets/67e3df23-622f-4f25-8e98-a7044e627257
Updated Case:
https://github.com/user-attachments/assets/460254f3-0489-42e4-8ba9-fb0c940318fd
In the future, explore whether expiration date needs to be filtered out in these cases.
---
> [no ticket][risk=no] Update admin page to account for missing expiration time

- ui/src/app/routing/signed-in-app-routing.tsx
When navigating away from workspaces, the invalid billing banners are still visible. This happens because the currentWorkspaceStore is not cleared when navigating away from workspace pages. 
**Before:**
https://github.com/user-attachments/assets/60dedddc-2114-4266-b648-1cda034a9fda
**After:**
https://github.com/user-attachments/assets/4545c04d-743a-43d9-b4dc-b6e1276e75c9
---
> [no ticket][risk=no] Clear workspace when navigating away from workspace.

- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
Users should not be able to request an extension if they do not have initial credits remaining. This change fixes that.
---
> [no ticket][risk=no] Add condition for initial credit eligibility.

- ui/package.json
- ui/yarn.lock
> [risk=low][no ticket] Bump express to upgrade path-to-regexp and unforce cookie

- api/src/main/webapp/static/initialize_notebook_runtime.sh
For https://precisionmedicineinitiative.atlassian.net/browse/RW-14160, user's jupyter startup script failed due to
```
INFO 2024-12-20T00:31:09.029004785Z [resource.labels.instanceId: 8215461924201628842] startup-script-url: error: failed to write new configuration file /home/jupyter/.gitconfig.lock
INFO 2024-12-20T00:31:09.029334382Z [resource.labels.instanceId: 8215461924201628842] startup-script-url: Installation failed: not a git repository!
```
Think updating gitconfig should be best effort thing, it doesn't need to fail startup
---
> [risk=low] RW-14160 don't fail startup script if we fail to update git config

- e2e/utils/runtime-utils.ts
The e2e egress suspension test seems to be timing out way too early for a particular step - less than 3 minutes when it should be waiting 25.  Adding some more info to try to figure this out.
---
> [risk=low][no ticket] Add temp debugging for e2e test

- ui/src/app/pages/workspace/invalid-billing-banner-maybe.spec.tsx
- ui/src/app/pages/workspace/invalid-billing-banner-maybe.tsx
Added expiration time to expiring soon banner. 
To test, add a record to the user_initial_credits_expiration for a user that created a workspace. Make sure the expiration date is 1 day from now.
Open that workspace as the creator and as someone that the workspace was shared.
Previous and expected banner text can be seen below.
**Creator**
**Non-creator**
**Creator**
**Non-creator**
---
> [RW-14141][risk=no] Add expiration time to expiring soon banner.

- api/libproject/cloudsqlproxycontext.rb
- api/libproject/mysql_docker.rb
The following is how to run cloud SQL locally with both v2 and v1 images
```
docker run \
-v /tmp/colima/all-of-us-rw-prod@appspot.gserviceaccount.com-key20250107-99283-auwyrp.json:/config \
--publish 3309:3307 \
--rm \
--name qi_cloud_sql \
gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2 --address 0.0.0.0 --port 3307 --credentials-file=/config all-of-us-rw-prod:us-central1:workbenchmaindb   
```
```
docker run \
-v /tmp/colima/all-of-us-rw-prod@appspot.gserviceaccount.com-key20250107-99283-auwyrp.json:/config \
-p 0.0.0.0:3309:3306 \
--rm \
--name qi_cloud_sql_v1 \
gcr.io/cloudsql-docker/gce-proxy:1.16 /cloud_sql_proxy \
-instances=all-of-us-rw-prod:us-central1:workbenchmaindb=tcp:0.0.0.0:3306 -credential_file=/config      
```
Tested by running the script locally
```
./project.rb …
```
> RW-14213 Fix ./project.rb connect-to-cloud-db --project=<project>

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoStatusUtils.java
- api/src/main/java/org/pmiops/workbench/leonardo/PersistentDiskUtils.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- api/src/test/java/org/pmiops/workbench/api/OfflineEnvironmentsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
- api/tools/src/cron/deleteUnsharedWorkspaceEnvironments.sh
Add a daily Cron job which checks all active workspaces in batches via Cloud Tasks, to delete Runtimes, GKE Apps, and Disks for users who are no longer collaborators on workspaces.
This is the offline cleanup task in RW-13727, which also specifies an interactive cleanup in the AC.  Depending on how aggressive we want to be, we may instead decide that this PR is sufficient, and an additional interactive cleanup isn't necessary. 
Tested locally.  The check-and-delete process took about 5s per workspace in the Local environment.
---
> [risk=low][RW-13727] Delete resources for unshared-from-ws users 

- ui/src/app/components/icons.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- ui/src/environments/environment-type.ts
- ui/src/environments/environment.local.ts
- ui/src/environments/environment.preprod.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.stable.ts
- ui/src/environments/environment.staging.ts
- ui/src/environments/test-env-base.ts
The dialog will guide the user to VWB
I tested the change by creating an AoU workspace which redirected correctly to the workspace screen. When I created a Verily Workbench workspace I get the dialog here:
---
> [risk=no][RW-13850] Add UI to check for VWB workspace creation and show a dialog

- api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/cron_test.yaml
The new `/v1/cloudTask/deleteUnsharedWorkspaceEnvironments` has a large number of failures.  Add some protections while we investigate:
* Don't run in higher environments (set to a single date well into the future)
* Add a try/catch around the problematic get user roles call
---
> [risk=low][RW-13727] Delay new cron in higher environments, and add try/catch

- api/src/main/java/org/pmiops/workbench/dataset/DataSetService.java
- api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/dataset/GenomicDatasetService.java
- api/src/main/java/org/pmiops/workbench/dataset/GenomicDatasetServiceImpl.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
- api/src/test/java/org/pmiops/workbench/dataset/GenomicDatasetServiceTest.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
DataSetService does a lot, and the GenomicExtractionService only needs a small piece of it.  Instead depend on this new GenomicDatasetService.  Alt: bring this in to GenomicExtractionService?
Motivated by running into Spring dependency issues from needing to include DataSetService while prototyping a "run genomic extraction" tool.
Tested locally by running a Genomic Extraction.
---
> [risk=low][RW-14230] Split off new GenomicDatasetService from DataSetService

- api/build.gradle
Part of our continued attempts to reliably run commands without seeing invalid_grant / JWT errors.
Tested locally, no apparent problems.
---
> [risk=low][RW-14199] Bump some Java packages related to google-auth (and others)

- ui/src/app/utils/leo-runtime-initializer.tsx
In order to test this behavior, create a runtime and then immediately delete it. Previously, this was producing an error, because there was still some polling for a runtime that had been deleted.
Previous Behavior:
https://github.com/user-attachments/assets/220bcfbc-0bd8-4379-8d80-b0b5b7902ee9
New Behavior:
https://github.com/user-attachments/assets/a6a38e01-447c-4e1f-b722-c3ad75c0d47f
---
> [no ticket][risk=no] Handle condition when a runtime is deleted while still polling.

- api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java
More debugging info for the failing deleteUnsharedWorkspaceEnvironments cron
---
> [risk=low][RW-13727] Add success/fail stats to delete-unshared cron

- deploy/Dockerfile
- deploy/libproject/deploy.rb
Recently there was a bug introduced in concurrent-ruby v1.3.5 that removed a dependency on logger. This is causing an issue with jira-ruby that results the following error:
`/var/lib/gems/3.2.0/gems/activesupport-6.1.4.6/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)
Logger::Severity.constants.each do |severity|
^^^^^^^^^^
from /var/lib/gems/3.2.0/gems/activesupport-6.1.4.6/lib/active_support/logger_thread_safe_level.rb:9:in <module:ActiveSupport>'
from /var/lib/gems/3.2.0/gems/activesupport-6.1.4.6/lib/active_support/logger_thread_safe_level.rb:8:in `<top (required)>'
from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
from …
> [no ticket][risk=no] Fix issue with deploy script

- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
Running this command took [only ~45 minutes](https://app.terra.bio/#workspaces/aouwgscohortextraction-prod/aouwgscohortextractionprod/job_history/21367ed9-6ebf-4b2b-a5b1-4e6dd50cddea) on this branch
```
./project.rb run-extraction \
--project all-of-us-rw-prod \
--namespace aou-rw-a2626269 \
--dataset_id 117923 \
--person-ids "1123013,1466961" \
--legacy false \
--filter_set echo_full \
--cdr_bq_project fc-aou-cdr-prod-ct \
--wgs_bq_dataset wgs_C2024Q3
```
The [same command on main](https://app.terra.bio/#workspaces/aouwgscohortextraction-prod/aouwgscohortextractionprod/job_history/e82040ac-9f31-4813-8dc0-a5a896898e54) for comparison (TODO capture total time)
---
> [risk=low][RW-14230] Explicitly set scatter count for v8 too

- api/db-cdr/generate-cdr/build-backup-cb-ds-tables.sh
- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
fixing bq commands with docker image upgrade for cdr-indices repo
---
> [DT-961][risk=no] fixing bq commands

- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
When this cron runs in Test, we see very many failures because many of the supposedly-active Workspaces are not accessible to the GAE SA when making Terra calls. (We expect the GAE SA to be an owner in Terra of all active workspaces.)
We don't see this problem in normal app usage, because our typical pattern for a call like List Workspaces is to first ask Terra which workspaces I can see as a user, and then query the RWB DB for RWB-specific details on each.
The cron however needs to check all workspaces in an environment and does not run in the context of a user. This is our first need for "List All Workspaces" (aside: we already have List All Runtimes and List All Disks) so it's the first time we're running into this problem. Instead of asking Terra for the list of workspace we have …
> [risk=low][RW-13727] Get all ws as service

- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
While testing the new delete-unshared cron, I saw errors related to apps without labels.  This PR adds context to those error messages, which will enable us to investigate these problematic apps.
---
> [risk=low][RW-13727][RW-14370] Better error messages when apps are missing labels

- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
The deleteOldRuntimes cron consistently fails with 404 in Prod.  It's unclear why.  Add logging to help us investigate, as well as ensuring that the cron continues past these errors in individual runtimes.
---
> [risk-low][RW-14370] Log 404 errors (and others) in deleteOldRuntimes

- api/build.gradle
The Jakarta family contains our final Java dependencies with >1 libyear.
Tested locally with no apparent problems.
---
> [risk=low][no ticket] Bump jakarta as far as possible

- api/db/changelog/db.changelog-251-remove-billing-status.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/UserMetricsController.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourcesServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/UserMetricsControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
Billing status is not being used from the api, so this PR removes it and replaces UI conversion to rely on feature flag and expiration and exhaustion fields rather than billing status field.
In order to have this field stick around, billing status would need to be able to tell whether the creator's institution has expiration bypassed. That is unnecessarily difficult especially since billing status as a whole will soon be removed.
---
> [no ticket][risk=no] Remove billing status from api and db.

- ui/src/app/pages/workspace/workspace-edit-text.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
Also added a conditions to prevent the tooltip from being rendered in prod as we need to update the text again before the prod release.
> [DT-905][risk=no] Update text for data apps version tooltip

- api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java
- api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java
- api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.java
- api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/UserAdminController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourcesServiceImpl.java
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaceadmin/WorkspaceAdminServiceTest.java
Convert some loops over get-user and get-workspace DB calls to "get all in this list" type calls.
Some other code cleanups. 
I'm happy to remove anything that would simplify this or is otherwise too big.
Tested locally by:
* updating user bypass times
* running the deleteUnsharedWorkspaceEnvironments cron (in debug mode, to observe the change)
* running the exportToRdr cron
* accessing workspace resources
* viewing collaborators in Workspace About
* viewing a workspace on the admin page
* sharing a workspace
---
> [risk=low][no ticket] Converted "loop over get" DB calls to "get all in", plus some other cleanups

- api/config/cdr_config_local.json
- api/config/cdr_config_preprod.json
- api/config/cdr_config_prod.json
- api/config/cdr_config_test.json
- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-253-rm-needs-v8-genomic-extraction-workflow.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java
- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java
- api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java
Tested locally by running 7 and v8 extraction workflows, and observing in Job Manager that the parameter lists were appropriate for each.  For example, v7 has `gatk_override` but v8 does not.
---
> [risk=low][no ticket] rm needsV8GenomicExtractionWorkflow because we have publicReleaseNumber

- ui/src/app/components/genomics-extraction-table.tsx
When a genomics extraction is in progress, we displayed some nonsensical text:
Now we don't:
---
> [risk=low][no ticket] Stop displaying "NaN GB" for genomics extraction

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryController.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
Apparently it is necessary to have the `@Override` to ensure the compiler correctly matches the controller method to the endpoint.  I caused a mismatch by renaming one and not the other in #9082 
---
> [risk=low][no ticket] Fix misnamed controller method

- api/config/cdr_config_local.json
- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/user/VwbUserService.java
- api/src/main/java/org/pmiops/workbench/vwb/usermanager/UserManagerClient.java
- api/src/main/java/org/pmiops/workbench/vwb/usermanager/VwbUserManagerClient.java
- api/src/main/java/org/pmiops/workbench/vwb/usermanager/VwbUserManagerConfig.java
- api/src/main/java/org/pmiops/workbench/vwb/usermanager/VwbUserManagerRetryHandler.java
- api/src/main/java/org/pmiops/workbench/vwb/wsm/WsmConfig.java
- api/src/main/resources/vwb-user-manager.yaml
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
- ui/src/environments/environment.local.ts
- ui/src/environments/test-env-base.ts
This PR will create the user in VWB when the user first signs in in AoU. The user won't be able to create workspaces yet until we implement pod/user. This will be the next PR.
Craeting the user in VWB is behind a feature flag.
---
> [risk=no][RW-13628] Create user in VWB automatically

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Note: we restrict this to an absolute max `MAX_ROWS_PER_INSERT_ALL_REQUEST` which we are updating to 50000 soon, but it missed today's release cutoff: https://github.com/all-of-us/workbench/pull/9100
---
> [risk=low][RW-14237] Set default maxRowsPerInsert to 10000 (current max) in all environments

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingTableParams.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingTableService.java
- api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
#9101 was not successful.  For some tables (at least cohort on Prod) that batch size is actually too big, and causes the insertion to fail because it exceeds the max size of 10 MB.
This is hopefully a way to enable a short-term solution by fine-tuning the right batch sizes for each table in each environment.  Once this is deployed, we can update these values by config changes instead of releases.
Unfortunately this is probably not a long-term solution, as the tables will continue growing.
---
> [risk=low][RW-14237] Enable configuring reporting batch sizes per-table

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExhaustionController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExhaustionControllerTest.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
We now have similar concepts of "exhausted initial credits" meaning the user exceeded the dollar amount and "expired initial credits" meaning that the time period when a user was eligible to use those credits has ended.
Prior to this, we sometimes used the word "expiry" to mean what we currently call "exhaustion" and this has become confusing.  Let's rename this.
We have other PRs #8994 and #9092 which rename larger portions of code, but they have been getting out of date quickly due to work in this area.  This PR is aiming for a quick review and merge before we change too much again.
---
>  [risk=low][RW-13494] Rename expiry to exhaustion where appropriate

- api/src/main/java/org/pmiops/workbench/access/VwbAccessService.java
- api/src/test/java/org/pmiops/workbench/access/VwbAccessServiceTest.java
> [no ticket][risk=no] Fixing a bug where group and user order is wrong

- ui/package.json
- ui/yarn.lock
Resolves https://github.com/all-of-us/workbench/security/dependabot/113
Also update browserslist / caniuse-lite
Tested locally
---
> [risk=low][no ticket] UI package upgrades

- api/src/main/java/org/pmiops/workbench/api/DiskAdminController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/disks/DiskAdminService.java
- api/src/main/java/org/pmiops/workbench/disks/DiskService.java
- api/src/test/java/org/pmiops/workbench/api/OfflineEnvironmentsControllerTest.java
- api/src/test/java/org/pmiops/workbench/disk/DiskAdminServiceTest.java
This does not resolve RW-14368, but will be necessary if we switch this to using TaskQueues.  Splitting out this no-change PR for easier review.
Tested locally by running Local UI and the checkPersistentDisks cron.
---
> [risk=low][RW-14368] Move checkPersistentDisks() to new DiskAdminService

- ui/src/app/pages/privacy-warning.tsx
- ui/src/app/pages/signed-in/signed-in.tsx
- ui/src/app/utils/authentication.tsx
- ui/src/app/utils/constants.tsx
Fix duplicate privacy warning.
You can test by opening one tab, acknowledging the privacy warning, and then opening RWB in a different tab.
https://github.com/user-attachments/assets/a25e4564-11b7-49a2-acbf-4c7314d837b7
---
> [no ticket][risk=no] Change session storage to local storage to prevent duplicate privacy warning

- api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/RuntimeController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/EnumSerializer.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/disks/DiskAdminService.java
- api/src/main/java/org/pmiops/workbench/disks/DiskService.java
- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
- api/src/main/java/org/pmiops/workbench/leonardo/PersistentDiskUtils.java
- api/src/main/java/org/pmiops/workbench/mail/MailService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/api/DiskAdminControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/DisksControllerTest.java
- api/src/test/java/org/pmiops/workbench/disk/DiskAdminServiceTest.java
- api/src/test/java/org/pmiops/workbench/disk/DiskServiceTest.java
- api/src/test/java/org/pmiops/workbench/mail/MailServiceTest.java
- api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
- ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx
- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/utils/analysis-config.spec.tsx
- ui/src/app/utils/runtime-hooks.spec.tsx
- ui/src/testing/stubs/disks-api-stub.ts
Cleanup of #9124
* remove TaskQueueDisk and replace with the standard Disk
* remove the TQSafe enums
* serialize enums by using their **values** when passing to TaskQueues, to match value-based deserialization
* for an example, see the `fromValues()` method in any swagger-generated enum, such as DiskType
Tested locally by running crons and interacting with disks and runtimes in the local UI
---
> [risk=low][RW-14368] Better serialization for Task Queues

- api/docs/developer-system-requirements.md
- deploy/Dockerfile
- ui/app.yaml
Deploy a Node 22 artifact for the UI.
Tested by running:
```
deploy/project.rb deploy \
--account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
--no-promote --git-version eric/RW-11310 --app-version erictest
```
and observing that a Node 22 image is deployed.
Clicking this link shows the expected UI.
The CI image seems to already be using Node 22:
```
erollins@wm091-509 ci % docker build --platform linux/x86_64 . -f Dockerfile.circle_build -t us.gcr.io/broad-dsp-gcr-public/workbench:buildimage-4.5.6
[+] Building 0.0s (11/11) FINISHED …
```
> [RW-11310][risk=no] Update to nodejs22

- api/src/main/webapp/WEB-INF/queue.yaml
Our current queue parameters are set to run every batch at once.  In practice, this means that we're currently sending 250+ Export to RDR requests within 20 seconds.
We only run this once per day and have no particular timing requirements, so let's try spacing this out to be much more gentle: 10 batches per minute.  At current (high) volume, I would expect that to be spread over ~ 30 min.
---
> [risk=low][RW-14474] Push data to RDR more slowly

- api/src/main/java/org/pmiops/workbench/api/ProfileController.java
- api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
I reverted this code because the user creation logic will be moved anyway so I was going to remove for here.
---
> [risk=no][no-ticket]Remove vwb user creation code to fix first sign in timestamp

- api/src/main/java/org/pmiops/workbench/disks/DiskAdminService.java
- api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
- api/src/test/java/org/pmiops/workbench/disk/DiskAdminServiceTest.java
Mail errors are very common for this task - over 10 per day.  Because we mark the whole batch as failed, it retries the whole batch again.  Typically it fails for this one user again, so retries again.  For the successful users (the vast majority) they will see an email for every retry.
Let's not do this.  We don't need to mark the batch as failed, and therefore there will be no need for retrying.
An alternate approach is to update the retry configuration: #9143.  I think both changes are worthwhile.
---
> [risk=low][RW-14538] Don't fail the entire checkPersistentDisksBatch when one email fails to send

- api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingService.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
Users are reporting getting flooded with "Unused disk" emails after transitioning that cron job to Task Queues.  Logs show that many more batches of these jobs (about 3x on 2/26, about 1.5x on 2/27) are executing than expected, along with frequent failures.  I see that a retry policy is specified for this queue, so I expect that this is the problem.
Also update accessExpirationEmailQueue which I expect to suffer from the same problem.
I ran local crons and local UI without issue, but this doesn't exercise the change here.
---
> [risk=low][RW-14538] Don't retry Task Queues jobs which send emails

- ui/src/app/pages/signed-in/signed-in.tsx
Moving where SignedInContent component is defined prevents an extra re-render of SignedInImpl.  This ultimately results in preventing sync-training-status from being called twice in quick succession, which locally for me consistently causes a 200 followed by a 500.
After this change, I now no longer see Absorb sync training status errors!
I expect this change will also bring performance and reliability improvements elsewhere. 
---
> [risk=low][RW-14580] Prevent unnecessary remounting of SignedInImpl

- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
The deleteUnsharedWorkspaceEnvironments cron job is timing out on both Prod and Test, because calls to Terra List Workspaces often exceed the timeout of 40s.  Because this is a cron job (and not interactive use) we can instead use the more lenient timeout.
Also rename "get workspaces" to the more idiomatic "list workspaces" where used, and add timing logs for future debugging
---
> [risk=low][RW-13727] Use lenient client for delete-unshared

- ui/.eslintrc.js
- ui/src/app/pages/access/modules-for-annual-renewal.tsx
- ui/src/app/pages/admin/admin-notebook-view.tsx
- ui/src/app/pages/admin/workspace/cloud-environments-table.tsx
- ui/src/app/pages/admin/workspace/disks-table.tsx
- ui/src/app/pages/workspace/workspace-nav-bar.tsx
Help prevent situations like #9151 by linting.
I un-nested these components found by the linter:
* TimeEstimate (annual renewal)
* Dates (annual renewal)
* Header (admin notebook view)
* Main (admin notebook view)
* DeleteButton (cloud environments table)
* NewVersionFlag (workspace nav bar)
Tested by confirming normal behavior in Annual Renewal, Admin Notebook View, the Cloud Environments Table, and the Workspace Nav Bar (when a workspace has an old CDR Version)
---
> [risk=low][RW-14580] eslint rule for nested components

- api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
- api/src/main/resources/firecloud.yaml
Genomics workflows often have data-dependent resource constraints.  In certain circumstances, our Genomics Extraction workflow may run out of memory in one or more shards (very small sub-tasks).  Today, this means that the overall workflow fails, but this is often recoverable if the shard task were given more memory.  Cromwell has configuration settings for this common scenario, and Terra gives us access to these settings.
Apply two settings which are recommended by the Variants team for everyday use of this pipeline, [Enable Call Caching](https://cromwell.readthedocs.io/en/develop/cromwell_features/CallCaching/) and [Retry with More Memory](https://cromwell.readthedocs.io/en/develop/cromwell_features/RetryWithMoreMemory/#retry-with-more-memory) (1.5x). 
I can't test directly that this …
> [risk=low][RW-14617] Apply recommendations to improve Genomic Extraction reliability

- api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
- api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/featuredworkspace/FeaturedWorkspaceTest.java
There are 3 steps in the pre-queuing phase of the deleteUnsharedWorkspaceEnvironments cron which can take a meaningful amount of time:
1. Terra List Workspaces
2. Query the RWB DB for which of these workspaces are active 
3. Combine the Terra Workspace with the RWB DbWorkspace to create a Workspace entity
Step 3 isn't necessary (we only need the Workspace Namespace) so I remove it here.
---
> [risk=low][RW-13727] Improve performance of deleteUnsharedWorkspaceEnvironments

- api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java
- api/src/test/java/org/pmiops/workbench/api/OfflineBillingControllerTest.java
This shows that it's the RWB clearing and insertion taking up the majority of the time, at least on Local:
```
[Thu Mar 13 11:36:24 EDT 2025] INFO: org.pmiops.workbench.api.OfflineBillingController checkInitialCreditsUsage - Checking initial credits usage for all workspaces
[Thu Mar 13 11:36:27 EDT 2025] INFO: org.pmiops.workbench.api.OfflineBillingController checkInitialCreditsUsage - checkInitialCreditsUsage: Retrieved 41286 workspace cost entries from BigQuery in 3s 175ms
[Thu Mar 13 11:36:49 EDT 2025] INFO: org.pmiops.workbench.api.OfflineBillingController checkInitialCreditsUsage - checkInitialCreditsUsage: cleared googleproject_cost table in 22s 411ms
[Thu Mar 13 11:37:10 EDT 2025] INFO: org.pmiops.workbench.api.OfflineBillingController checkInitialCreditsUsage - …
```
> [risk=low][RW-14654] Add timing logs for checkInitialCreditsUsage

- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceDaoTest.java
According to the logs of the first successful deleteUnsharedWorkspaceEnvironments run on Prod, we're pushing awfully close against the 10-min deadline:
```
Retrieved 19045 RWB workspaces from DB in 7m 45s 750ms
```
Update the DB query to retrieve only what we need - the namespaces.  Running this branch on Local (with only 11 DB rows returned) shows a significant speedup from main (3 runs each): [58ms, 56ms, 46ms] vs. [234ms, 133ms, 115ms]
---
> [risk=low][RW-13727] Only retrieve the namespaces - don't need the whole DbWorkspace

- api/build.gradle
Use the Spring dependency management plugin.  This allows us to stop hard-coding version numbers in many locations.
Downgrade the *specified* version of Spring Boot to match the *actual* version of Spring Boot.  See comments below.
Tested locally by running Local UI and API.
---
> [risk=low][no ticket] Let Spring handle its own dependencies

- e2e/package.json
- e2e/yarn.lock
- ui/src/app/components/buttons.tsx
Resolve a vulnerability https://github.com/all-of-us/workbench/security/dependabot/114 by unforcing axios and upgrading jest-puppeteer.
I also made a trivial UI change, to trigger an e2e run.
---
> [risk=low][no ticket] Upgrade e2e packages to resolve vulnerability

- api/build.gradle
- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
The auditProjectQueue often fails at the user impersonation step, so we are unable to query for project membership for certain users.  Limit the scope of these checks to users who currently have access to CDR resources, to cut down on noise.
---
> [risk=low][RW-14690] Audit current tier members only for project membership

- api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
The checkInitialCreditsExpiration cron is consistently timing out in Prod, even though all it's doing is retrieving a list of users and launching Task Queues to do the actual work.
Add logging timing to help figure out what's going on, and also reduce the DB query to retrieve only what we need - the user IDs.
---
> [risk=low][RW-14791] Reduce checkInitialCreditsExpiration query to ID only and log timing

- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryService.java
- api/src/main/java/org/pmiops/workbench/google/DirectoryServiceImpl.java
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
Some (test?) users cannot be found in Google Directory, which causes the nightly access sync cron to throw.  These users are clearly not compliant, so deny access instead of throwing.
---
> [risk=low][no ticket] Clean up log spam by denying access to users who aren't in Google Directory

- ui/src/app/components/runtime-configuration-panel.spec.tsx
- ui/src/app/components/runtime-configuration-panel.tsx
- ui/src/app/pages/workspace/workspace-wrapper.tsx
- ui/src/app/utils/index.tsx
- ui/src/app/utils/runtime-hooks.spec.tsx
- ui/src/app/utils/runtime-hooks.tsx
- ui/src/app/utils/runtime-utils.spec.tsx
- ui/src/app/utils/stores.tsx
- ui/src/testing/utils.ts
Before this fix, if you deleted a runtime and not its disk, the first time you load the configuration panel after deleting, you would see the size of the default disk in the description section. After re-opening the panel, you would see values reflecting the existing persistent disk.
Previous behavior:
https://github.com/user-attachments/assets/58568c04-6e4d-4733-81f7-c21ad29dff19
Updated Behavior:
https://github.com/user-attachments/assets/dd6b8319-f097-44af-b2d5-52277161fe4d
---
> [RW-14861][risk=no] Only show configuration panel after attempting to load existing disk

- api/config/config_test.json
Resolve Task Queue timeout errors by reducing the work done per task.  I expect that this problem is limited to the Test environment, because performance in this case is related to the number of Sam resources our app SA has access to, and this number is very large in Test.  I confirmed that Prod is fine.
---
> [risk=low][RW-14932] Reduce Test workspace processing to only 10 at a time

- api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExhaustionController.java
- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java
- api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/CommonMappers.java
- api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceFields.java
- api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourceMapper.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/actionaudit/auditors/WorkspaceAuditorTest.java
- api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExhaustionControllerTest.java
- api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
- ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx
- ui/src/app/utils/resources.tsx
- ui/src/testing/stubs/resources-stub.ts
Remove all references to BillingStatus except for reporting - we need to coordinate with PDR / dashboards there.
OK to merge because https://github.com/all-of-us/workbench/pull/9216 has been released.
Tested locally by interacting with workspaces, recent-resources, and runtimes.
---
> [risk=low][RW-14706] Remove most remaining references to Billing Status

- api/db/changelog/db.changelog-263-rm-workspace-billing-account-type.xml
- api/db/changelog/db.changelog-master.xml
We stopped using this field to determine initial-credits vs. user-provided billing all the way back in 2021, and we now always check whether the billing account name matches the initial-credits account name: https://github.com/all-of-us/workbench/pull/5898
Probably safe to remove it at this point ;-)
Tested by running locally and doing a local reporting snapshot.
---
> [risk=low][RW-14706][RW-5107] rm billing_account_type

- api/src/main/java/org/pmiops/workbench/api/InstitutionController.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserService.java
- api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
- ui/src/app/pages/login/account-creation/account-creation-institution.tsx
- ui/src/app/utils/institutions.tsx
Add a check for existing account during user registration. Uses new `existingAccount` property on `CheckEmailResponse`, will prevent users from continuing if `existingAccount` returns `true`.
This will allow AoU operational users to create multiple accounts.
Error message shown in UI if an existing account is found:
---
> [DT-989][risk=no] Limit non-ops users to one account per institutional email

- api/db-cdr/generate-cdr/build-cloudsql-tables.sh
- ui/src/app/pages/data/criteria-search.tsx
adding visits to concept sets
---
> [DT-1002][risk=no] adding visits to concept sets

- api/db-cdr/generate-cdr/build-ds-tables.sh
> [no-ticket][risk=no] fixing indexing build

- deploy/libproject/deploy.rb
The deploy script had an extra 'end' that was missed from https://github.com/all-of-us/workbench/pull/9237. This PR removes this syntax error.
---
> [no ticket][risk=no] Remove extra end

- api/src/main/resources/leonardo.yaml
Our version of Leo's yaml still included references to includeDeleted parameters that [Leo's version](https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/resources/swagger/api-docs.yaml) no longer has.
The only remaining instance is in `listAppByProject`. All other usages were unused and have been removed.
---
> [RW-14937][risk=no] Remove instances of includeDeleted that are no longer included in Leo's yaml

- ui/src/app/components/genomics-extraction-menu.spec.tsx
- ui/src/app/components/genomics-extraction-menu.tsx
`Delete Extract` option no longer appears in the menu
> [DT-1007][risk=no] Remove delete option from genomic extraction menu

- api/src/main/java/org/pmiops/workbench/leonardo/LeonardoCustomEnvVarUtils.java
There's a bug in the WGS_CLINVAR_MULTI_HAIL_PATH because currently It is going to the split MT but it should go to the multi MT. Fixing the code to point to the correct configuration.
---
> [risk=no][no-ticket] Fix genomic env var

- api/src/main/webapp/static/aou-file-tree-policy-extension.js
In all cases below, the "download" and "view" buttons only appear and take action on behalf of the files that are selected.
**Previous Behavior:**
The listener that triggers the download popup is only listening for the overlay (text in the middle of the download button). If you happen to click in the corner of the button (outside of the overlay/blue outline), you will not get the download warning. Also, the dialog was not showing when triggering a button via "Enter" or "Space" when focused. Likewise for the "View" button.
https://github.com/user-attachments/assets/3a21e45e-78b6-4924-990d-4ac8861b9e69
**Current/Desired Behavior**
You should be able to click the "download" button or press "enter" or "space" (when the "download" button is focused), and then, the download warning dialog …
> [RW-14663][risk=low] Update Jupyter's Download/View Click Handlers 

- api/config/config_local.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
Update non preprod/prod envs to use the latest jupyter image with ubuntu upgrade
---
> RW-14240 Update jupyter image version

- ui/src/app/utils/analysis-config.spec.tsx
- ui/src/app/utils/analysis-config.tsx
Since this PR was opened over a year ago, most of the changes proposed here have been adopted or obsoleted.  What remains after rebasing is removing an unused function: maybeWithPersistentDisk()
---
> [risk=low][no ticket] rm unused maybeWithPersistentDisk()

- api/config/config_preprod.json
Reverts all-of-us/workbench#9258
2.2.15 won't work for dataproc, so reverting in preprod for now
I'm not reverting in Test since we're expecting a fix soon and no one uses dataproc much in Test, but lmk if ppl prefer Test is also reverted
> Revert "[risk=no] RW-14240 promote to preprod"

- .circleci/config.yml
Since https://github.com/all-of-us/workbench/pull/9262 seems to have been successful, preventing production from auto-promoting no longer seems necessary.
---
> [RW-15048][risk=no] Bring back auto-promote production

- ui/src/app/components/data-user-code-of-conduct.tsx
Functionality should not change.
To test
Ensure that your user does not have data user code of conduct (ducc) signed or bypassed.
Navigate to http://localhost:4200/data-code-of-conduct
Sign the ducc.
Ensure that your ducc shows as signed on today's date on http://localhost:4200/data-access-requirements
---
> [no ticket][risk=no] Converted DataUserCodeOfConduct to a functional component

- api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java
- api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerService.java
- api/src/main/java/org/pmiops/workbench/google/CloudResourceManagerServiceImpl.java
- api/src/main/java/org/pmiops/workbench/iam/IamService.java
- api/src/main/java/org/pmiops/workbench/iam/IamServiceImpl.java
- api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Now that we're no long using GLS (to be exact, we haven't addressed dsub and cromwell.jar against batch yet), we can remove the code for `revokeWorkflowRunnerRoleForUsers` I think.
---
> [risk=low] [RW-14611] remove revokeWorkflowRunnerRoleForUsers

- ui/src/app/pages/access/data-access-requirements.spec.tsx
- ui/src/app/pages/access/data-access-requirements.tsx
Modified the banner notification that is shown when user's complete their data access requirements.
Should this banner look different after a user has swapped to their own billing account?
---
> [RW-15146][risk=no] Changed language relating to initial credits on the DAR page

- api/db/changelog/db.changelog-265-add-unique-constraint-user-initial-credits-expiration.xml
- api/db/changelog/db.changelog-master.xml
Added a unique constraint to the the user_id field in the user_initial_credits_expiration table. Duplicate records cause issues with our cron jobs.
To test, try to add two rows to user_initial_credits_expiration with the same user_id in your local database.
---
> [RW=15200][risk=no] Add user id constraint to user initial credits table.

- .circleci/config.yml
- api/build.gradle
Bump Spring Boot (and httpclient5) to latest.  Also remove the explicit logback version - a newer version is now chosen automatically to be compatible with spring-boot 3.4.5.
Tested locally - everything seems to work fine.
It's worth noting that this upgrade requires giving tests more memory resources to pass.
---
> [risk=low][no ticket] Bump Spring Boot to latest

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/db/changelog/db.changelog-266-update-user-initial-credits-expiration-to-365-days.xml
- api/db/changelog/db.changelog-master.xml
This PR involves two changes:
1. Setting all expiration dates to 365 days after their credit start dates
2. Updating all config values to set initial credit expiration dates to 365 days for all users going forward.
---
> [RW-15216][risk=no] Set initial credit expiration dates to 365 days after creation

- ui/src/app/pages/workspace/workspace-edit-providers.ts
- ui/src/app/pages/workspace/workspace-edit-validation.ts
- ui/src/app/pages/workspace/workspace-edit.spec.tsx
- ui/src/app/pages/workspace/workspace-edit.tsx
- pre-work to make zod library introduction easier to review.
- shifted validation realted code out of workplace-edit and into a wokrplace-edit-validation.ts sister-file.
- added unit tests on validation call that will later be used to add more confidence to zod validation repacement.
- also moved data calls to a -providers sister file to aid in improved unit test mocks, and silenced google-analytics unit test noise with a mock.
---
> RW-15004 [risk=low] validate.js pre-work part1

- api/build.gradle
- api/db-cdr/build.gradle
- api/db/build.gradle
Ran locally without problems. Also ran `./project.rb run-local-all-migrations` to verify that Liquibase is still able to manage Workbench and CDR databases after version bump.
---
> [risk=low][RW-15161] Upgrade com.mysql:mysql-connector-j to latest

- api/build.gradle
Broad is switching its artifact repository from JFrog to Maven. This change ensures that we are pulling from the right location.
---
> [no ticket][risk=no] Replace JFrog with Maven

- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
- api/src/main/java/org/pmiops/workbench/user/VwbUserService.java
- api/src/main/java/org/pmiops/workbench/vwb/usermanager/VwbUserManagerClient.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java
When the initial credits are increased in the admin page, the RWB should update the pod to link the initial credits billing account and update the database.
---
> [RW-15521][risk=no] Set initial credits account to pod when the credits are increased

- api/config/config_local.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateService.java
- api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsBigQueryService.java
- api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsBigQueryServiceTest.java
I tested this change by running the cron job using
`curl --header "X-AppEngine-Cron: true" localhost:8081/v1/cron/checkInitialCreditsUsage`
For a user who exceeded their initial credits usage, they get an email and their billing is unlinked in VWB.
---
> [risk=no][RW-15247] Fix query to use the new bigquery table

- api/db/changelog/db.changelog-267-add-reporting-upload-verification-table.xml
- api/db/changelog/db.changelog-269-add-reporting-upload-verification-table.xml
- api/db/changelog/db.changelog-master.xml
- api/src/main/java/org/pmiops/workbench/api/CloudTaskReportingController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineReportingController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/db/dao/ReportingUploadVerificationDao.java
- api/src/main/java/org/pmiops/workbench/db/model/DbReportingUploadVerification.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingTableService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationService.java
- api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- api/src/test/java/org/pmiops/workbench/api/CloudTaskReportingControllerTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingTableServiceTest.java
- api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java
Ticket: [RW-14979](https://precisionmedicineinitiative.atlassian.net/browse/RW-14979)
Splits the WRD upload into distinct Cloud Tasks to get around the 600 second GAE cron job timeout.
Every nightly upload to the WRD has a single timestamp associated with it that can be thought of as the snapshot identifier. When the current upload job completes, there is a final verification step that checks that the number of rows uploaded to the WRD snapshot matches the number of rows in the database. If we are able to verify the snapshot, we upload the timestamp to the `verified_snapshot` table in the WRD BQ dataset to certify it as a successful upload.
How will we continue to certify the snapshot once we’ve split the upload job into a series of asynchronous tasks? Despite its name, GCP makes no …
> [RW-14979][risk=no] Split WRD upload job into tasks

- api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
- api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceColumnValueExtractor.java
- api/src/main/resources/workbench-api.yaml
- api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
Don't merge until we update the BigQuery table: https://github.com/all-of-us/workbench-terraform-modules/pull/68
The above will update the BigQuery schema, but the change in this PR enables the api to export the correct data.
In order to run the appropriate cron job, follow [these instructions](https://github.com/all-of-us/workbench/wiki/Workbench-Reporting-Dataset-(WRD)#testing).
---
> [risk=low][RW-14827] Add AIAN fields to reporting.

- api/config/config_local.json
- api/config/config_preprod.json
- api/config/config_prod.json
- api/config/config_stable.json
- api/config/config_staging.json
- api/config/config_test.json
- api/src/main/java/org/pmiops/workbench/api/CloudTaskWorkspacesController.java
- api/src/main/java/org/pmiops/workbench/api/OfflineWorkspaceController.java
- api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
- api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java
- api/src/main/java/org/pmiops/workbench/db/dao/WorkspaceDao.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java
- api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java
- api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- api/src/main/webapp/WEB-INF/cron_base.yaml
- api/src/main/webapp/WEB-INF/queue.yaml
- api/src/test/java/org/pmiops/workbench/api/CloudTaskWorkspacesControllerTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceDaoTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
- api/src/test/java/org/pmiops/workbench/workspaces/impersonation/ImpersonatedWorkspaceServiceTest.java
- api/tools/src/cron/README.md
- api/tools/src/cron/cleanupOrphanedWorkspaces.sh
Sets up a cron job that finds all of the workspaces present in the RWB  but not in Terra. These workspaces are considered orphaned. In batches, these workspaces are set to active_status=1 (deleted).
[Lucid Chart Version of Diagram](https://lucid.app/lucidchart/91b8d7ed-2991-44e1-8a44-6d1a77d4b254/edit?viewport_loc=-336%2C-68%2C3442%2C1592%2Cb6gBZmypYXLQ&invitationId=inv_1c2b19fa-f7fa-46ad-b7db-83f71fa79ed5)
<ins>**config_**</ins> - Configures how many workspaces can be cleaned up in a single cloud task for the specified environment.
<ins>**cron_base.yaml**</ins> - sets up what endpoint(`/v1/cron/cleanupOrphanedWorkspaces`) will be called and when (every day 21:00 CT).
<ins>**queue.yaml**</ins> - Updated this to establish the `cleanupOrphanedWorkspacesQueue` in order to queue the cloud …
> [RW-15002][risk=no] Cleanup orphaned workspaces

- api/src/main/java/org/pmiops/workbench/api/VwbWorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryService.java
- api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/vwb/admin-vwb-workspace-search.tsx
- ui/src/app/pages/admin/vwb/admin-vwb-workspace.tsx
- ui/src/app/routing/signed-in-app-routing.tsx
- ui/src/app/utils/stores.tsx
- Renamed VWB ws search component  `admin-vwb-workspace.tsx` -> `admin-vwb-workspace-search.tsx` 
- Added new `admin-vwb-workspace.tsx` component for detailed admin view. Clicking on the user facing id in the search results table will navigate to the detailed view
- Added `getVwbWorkspaceAdminView` endpoint to retrieve workspace details
https://github.com/user-attachments/assets/10331791-9324-4cc9-9074-f1ef5efe9cf9
---
> [DT-1034][risk=no] Add VWB workspace admin page

- api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressJiraHandler.java
- api/src/main/java/org/pmiops/workbench/jira/JiraService.java
- api/src/main/resources/jira.yaml
- api/src/test/java/org/pmiops/workbench/exfiltration/EgressRemediationServiceTest.java
The old one that we are using are deprecated and removed
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-post
And it should be replaced by the new one: 
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-post
---
> [RW-16024][risk=low] Update Jira search endpoint

- api/src/main/java/org/pmiops/workbench/api/VwbWorkspaceAdminController.java
- api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryService.java
- api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryServiceImpl.java
- api/src/main/resources/workbench-api.yaml
- ui/src/app/pages/admin/vwb/admin-vwb-workspace.tsx
Add table to VWB workspace admin page that displays events captured in the `wsm_workspace_activity_logs` table. This feature will modified with more detail and likely moved to a separate audit page as more data becomes available.
> [DT-1037][risk=no] Add workspace activity to VWB admin page

- .circleci/config.yml
We have Snyk configured which reports new vulnerabilities so we don't need this tool. See issues documented in:
https://github.com/dependency-check/dependency-check-gradle/issues/467
This caused failures in our build for the past few days.
https://app.circleci.com/pipelines/github/all-of-us/workbench/38566/workflows/c67cec56-f5b9-4217-9ccc-452ed761ddff
---
> [risk=no][no-ticket] Remove dependency check due to issues with the tool. 
