e2ev2/.gitignore
=> [risk=no][no ticket] gitignore e2ev2/screenshots

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/src/bigquerytest/resources/bigquery/schema/cb_search_person.json
Description:
---
- cdr-indexing build -  part of add state of residence to person table and cb_search_person 
---
* AoU UI
=> [DT-181][risk=no] Add state_of_residence to cb_search_person

api/db-cdr/generate-cdr/build-cb-search-person.sh
Description:
---
- cdr-indexing-build - Update `db-cdr/generate-cdr/build-cb-search-person.sh` for state_of_residence 
---
* AoU UI
=> [DT-182][risk=no] cdr-indexing-build - Update build for state_of_residence

api/db-cdr/generate-cdr/build-cb-search-person.sh
Description:
---
- add state_of_residence column to insert statement
---
* AoU UI
=> [no-ticket][risk=no]added state_of_residence column to insert

api/db-cdr/generate-cdr/generate-circle-key/generate_circle_key.sh
adding shell script to generate creds/key for circleci cdr-indices
=> [no ticket][risk=no] adding shell script to generate creds/key for circleci cdr-indices

api/db-cdr/generate-cdr/build-cb-search-person.sh
Description:
---
- adding geo loc - state code to CT cb_search_person
---
* AoU UI
=> [no-ticket][risk=no] adding geo loc - state code to CT cb_search_person

api/src/main/webapp/static/initialize_notebook_runtime.sh
Call-caching isn’t configured through cromshell, instead its configured through cromwell in its conf file. mentioned in the cromwell docs https://cromwell.readthedocs.io/en/stable/Configuring/#call-caching
Call Caching allows Cromwell to detect when a job has been run in the past so it doesn't have to re-compute results. By default the value is set to false 
As mentioned by Steve Hung in ticket  :  _**One technical point, is that cromshell doesn’t control call-caching behavior. Ultimately, cromwell controls that (yes, the two names are confusingly close…) via its own config, as documented [here](https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/).
However, cromshell users can fine-tune the call caching behavior by providing a workflow config json file to …
=> [RW-9302][risk=no][API][Cromwell] Install and config Cromshell in AoU Jupyter image

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json
The rolling rollout began around 5:23 PM EST.  Set the cutoff time to 22:23:00 UTC (EST + 5)
Description:
---
* AoU UI
=> Update latestTerraTosTimestamp for Terra-Prod envs

api/config/featured_workspaces_prod.json
Description:
https://precisionmedicineinitiative.atlassian.net/browse/RW-9374
---
* AoU UI
=> [RW-9374][risk=no] Publish a new feature workspace in prod

ui/src/app/components/apps-panel/apps-panel-button.tsx, ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/apps-panel/new-notebook-button.tsx, ui/src/app/components/apps-panel/runtime-state-button.tsx, ui/src/app/components/apps-panel/utils.tsx
Make this easier to reuse for other apps.  Tested locally with no observed changes.
---
* AoU UI
=> [risk=low][RW-9007] Extract a common AppsPanelButton component

api/db-cdr/generate-cdr/create-tables.sh
Description:
---
- updated cdr-indexing to skip building prep_survey table, if it exists… in the dataset.
---
* AoU UI
=> [DT-189-2][risk=no] speedup CDR indexing

api/db-cdr/generate-cdr/create-tables.sh
Reverts all-of-us/workbench#7307
=> Revert "[DT-189-2][risk=no] speedup CDR indexing"

api/src/main/webapp/WEB-INF/queue.yaml
Followup to #7295 which does not work because the queue did not exist.  Ha.
Also add queue creation to the wiki: https://github.com/all-of-us/workbench/wiki/Using-Task-Queues-when-endpoints-take-too-long-to-complete
---
* AoU UI
=> [risk=low][RW-9323] Create the missing queue

api/db-cdr/generate-cdr/create-tables.sh
Description:
---
- CDR indices - For efficiency reason change the indexing build to pass over surveys if table already exists
- Note there is test code to check if CI bash has associative array feature enabled - Another PR will remove this test code
- Missed function call name; testing if /bin/bash also has associative arrays enabled
---
* AoU UI
=> [DT-189-5][risk=no] CDR indexing - Speedup build - prep_survey 

api/db-cdr/generate-cdr/build-prep-survey.sh
=> [no ticket][risk=no] fixing error in prep survey

api/db-cdr/generate-cdr/build-prep-survey.sh, api/db-cdr/generate-cdr/cb-criteria-utils.sh
Description:
---
- fix file execute permission issues
---
* AoU UI
=> [DT-189-9][risk=no] CDR indexing - improve efficiency - prep_survey

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
Update `build-cb-criteria-attribute-tables-and-cleanup.sh` to fix 2 issues in PFHH survey:
- Answers have the question added on the front, need to just show the answer
- Question on kidney disease has deprecated answers with the same name
=> [DT-184][risk=no] Update shell script to fix PFHH survey answers

api/libproject/devstart.rb
Description:
---
- fix command-line replacements for wgv tables
---
* AoU UI
=> [DT-185-1][risk=no] CDR indexing remove genomic arguments

api/libproject/devstart.rb
Description:
---
- fix command-line replacements - payload
---
* AoU UI
=> [DT-185-2][risk=no] CDR indexing remove genomic arguments

api/src/integration/java/org/pmiops/workbench/FireCloudIntegrationTest.java
We need to flip this boolean whenever that changes.
---
* AoU UI
=> [risk=low][no ticket] ToS is being enforced again in Terra Dev

api/db-cdr/generate-cdr/build-ds-tables.sh, api/libproject/devstart.rb
Description:
---
- use table-tokens to build different ds_ tables in parallel
---
* AoU UI
=> [DT-190][risk=no] split out ds table creation

api/db-cdr/generate-cdr/build-ds-tables.sh
Description:
---
- fix bug in script
---
* AoU UI
=> [DT-190-1][risk=no] fix bash bug replace eq with =

api/libproject/devstart.rb
Description:
---
- fix passing table_token, instead of data_browser for 4th argument
---
* AoU UI
=> [DT-190-2][risk=no] CDR indexing - fix argument passing to build-ds-tables script

api/db-cdr/generate-cdr/build-ds-tables.sh
Description:
---
- fix missing TABLE_LIST and exit 1 when no match for table-token arg
---
* AoU UI
=> [DT-190-3][risk=no] CDR indexing build make more efficient

api/db-cdr/generate-cdr/build-prep-survey.sh, api/db-cdr/generate-cdr/create-tables.sh, api/libproject/devstart.rb
adding flag to build prep_survey
=> [DT-211][risk=no] adding flag to build prep_survey

api/db-cdr/generate-cdr/build-cb-search-person.sh
Description:
---
- Bug fix for RT/CT logic in build-cb-search-person.sh
---
* AoU UI
=> [DT-214][risk=no] fix bug in determining RT/CT logic for genomics

api/db-cdr/generate-cdr/build-prep-survey.sh, api/libproject/devstart.rb
Description:
---
- removed id-start-block form project rb command for build-prep-survey
- added associative array for getting ID
---
* AoU UI
=> [DT-212][risk=no] CDR indexing build - build prep-survey ar matrix job

ui/package.json, ui/src/app/pages/workspace/workspace-share.spec.tsx, ui/src/styles.css, ui/yarn.lock
=> [risk=low][no ticket] Remove a few UI packages we're no longer using

ui/src/terraui/build.sh
See PR comments inline.
Tested manually, replacing `git log` with `ls` to make it easier to try both cases.
---
* AoU UI
=> [RW-9048][risk=no] Fix conditional in build.sh

ui/src/app/components/runtime-configuration-panel.tsx
Description:
Updated runtime configuration dropdowns in order to work with nightly tests.
---
* AoU UI
=> [none][risk=no] Updated how dropdowns are attached to dom in order to work with testing.

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
=> [DT-191][risk=no] - hotfix v5 build removing PFHH

deploy/Dockerfile
Description:
Adding zip to deploy image in order to handle terra ui patches.
---
* AoU UI
=> [no ticket][risk=no] Adding zip to deploy image in order to handle terra ui patches.

ui/src/app/routing/app-routing.tsx, ui/src/config/app-config.tsx, ui/src/index.ts
Description:
Creates a top-level server config component.
This is necessary to use react-oidc-context. That library requires [configuring an AuthProvider](https://github.com/authts/react-oidc-context#getting-started) that wraps your application. In our case, the configuration for the provider depends on our server config, so we need to create a component one level higher.
I think this change makes the dependency between config and the rest of the app clearer as well.
This PR introduces no functional changes to the app. Everything rendered in app-routing is indirectly dependent on the config having loaded.
This PR also removes unused app-routing props.
---
* AoU UI
* …
=> [RW-8907][risk=no] Refactor: Create top-level server config component

api/src/main/java/org/pmiops/workbench/billing/FreeTierBillingService.java
=> [risk=no][RW-8814] Update users free tier usage in multiple threads

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
removing non utf8 characters from indexing build
=> [no ticket][risk=no] removing non utf8 characters from indexing build

api/db-cdr/generate-cdr/build-prep-survey.sh
=> [no ticket][risk=no] fixing surveys for hotfix

api/db-cdr/generate-cdr/build-prep-survey.sh
Reverts all-of-us/workbench#7371
=> [no ticket][risk=no] reverting this: fixing surveys for hotfix

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh
Reverts all-of-us/workbench#7365
=> [DT-191][risk=no] Revert - "hotfix v5 build removing PFHH"

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh, api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh
adding back the special char fix
=> [DT-194][risk=no] adding back the special char fix

ui/src/styles.css
https://user-images.githubusercontent.com/24514630/215877347-ed235dfc-21c5-4337-be94-a09444017c16.mov
Description:
Updated size of input to properly trigger cursor
---
* AoU UI
=> [RW-9464][risk=no] Updated size of input to properly trigger cursor

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java, api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
Tested locally with no issues
---
* AoU UI
=> [risk=low][RW-7862] rm enforceRasLoginGovLinking FF from API

api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
A few typos from #7380
---
* AoU UI
=> [risk=no][no ticket] LEONARD -> LEONARDO

api/config/featured_workspaces_prod.json
Description:
Added Demo-Geographic Variation in Obesity (V4) to demo projects.
---
* AoU UI
=> [RW-9462][risk=low] Added Demo-Geographic Variation in Obesity (V4)

api/db-cdr/generate-cdr/libproject/genomic_manifests.rb
=> [RW-8999][risk=no] Add project in prod env call to get previous manifest correctly

e2e/app/sidebar/runtime-panel.ts, ui/src/app/components/configuration-panel.spec.tsx, ui/src/app/components/cromwell-configuration-panel.spec.tsx, ui/src/app/components/cromwell-configuration-panel.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/components/runtime-configuration-panel/disabled-panel.tsx
=> [risk=low][RW-9390] Fixing followups from PR.

ui/src/environments/environment.perf.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.staging.ts
Push the Cromwell MVP to Preprod
Don't push it to Prod, because it's not production ready.  Also don't push to Stable, which we want to match Prod.
Blocked on https://github.com/all-of-us/workbench/pull/7343 and https://github.com/all-of-us/workbench/pull/7392
---
* AoU UI
=> [risk=low][RW-9446] showAppsPanel (and Cromwell) everywhere except Stable and Prod

api/db-cdr/generate-cdr/build-ds-tables.sh
fixing overstatement of ds_survey for PFHH survey
=> [DT-237][risk=no] fixing overstatement of ds_survey for PFHH survey

ui/src/app/pages/data/data-set/dataset-page.tsx
=> [DT-210][risk=no] Add 'Short Read' to  prepackaged WGS concept set name

api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
Fixing all surveys prepackaged CS. The generated SQL was including all survey question concept ids and all answer concept ids for the PFHH survey. When the all surveys prepackaged CS is selected we really only need to select all data in the ds_survey table. No need to use concept ids.
=> [DT-238][risk=no] fixing all surveys prepackaged CS

e2e/app/component/admin-table.ts, e2e/app/component/data-table.ts, e2e/app/component/select-menu.ts, e2e/app/page/admin/admin-workspace-page.ts, e2e/app/page/admin/user-admin-table-page.ts, e2e/app/page/cohort-review-page.ts, e2e/app/page/conceptset-search-page.ts, e2e/app/sidebar/runtime-panel.ts, e2e/tests/nightly/admin/institution-admin-ui.spec.ts, e2e/tests/nightly/admin/user-admin-table.spec.ts, e2e/tests/nightly/admin/user-profile-admin.spec.ts, ui/src/app/components/inputs.tsx, ui/src/app/components/runtime-configuration-panel.tsx, ui/src/app/pages/admin/user/admin-user-common.tsx, ui/src/styles.css
Description:
Was able to update a few of the nightly tests that broke after the React 17 upgrade.
Fixed:
- tests/nightly/admin/user-admin-table.spec.ts
- tests/nightly/admin/workspace-admin-ui.spec.ts
- tests/nightly/runtime.spec.ts
- Copy Notebook to Workspace input
Note: 
Used !important to fix Copy Notebook to Workspace input. I left a note in the css to explain why. 
---
* AoU UI
=> [risk=low][no ticket] Fixing React 17 Regressions

api/db-cdr/generate-cdr/build-prep-survey.sh, api/db-cdr/generate-cdr/build-search-all-events.sh
Description:
---
- Improve CDR-indexing-build efficiency: Update build-search-all-events to be run as a matrix job in circle
- Relates to the cdr-indices repo [PR#86](https://github.com/all-of-us/cdr-indices/pull/86)
- Both this PR and the cdr-indices PR needs approval to test
---
* AoU UI
=> [DT-218][risk=no] CDR indexing - Update build-search-all-events to be run as a matrix job in circle

api/db-cdr/generate-cdr/build-search-all-events.sh
Description:
---
- split inserting measurement data into `source` and `standard`
---
* AoU UI
=> [No-Ticket][risk=no]Update build-search-all-events split insert of measurement data

api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh, api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh, api/db-cdr/generate-cdr/build-cb-criteria-device.sh, api/db-cdr/generate-cdr/build-cb-criteria-drug.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-clin.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-labs.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-snomed.sh, api/db-cdr/generate-cdr/build-cb-criteria-observation.sh, api/db-cdr/generate-cdr/build-cb-criteria-pm-cs.sh, api/db-cdr/generate-cdr/build-cb-criteria-pm.sh, api/db-cdr/generate-cdr/build-cb-criteria-snomed-condition.sh, api/db-cdr/generate-cdr/build-cb-criteria-snomed-procedure.sh, api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh, api/db-cdr/generate-cdr/build-cb-criteria-visit.sh, api/libproject/devstart.rb
statically reference id blocks in scripts
=> [DT-215][risk=no] statically reference id blocks in scripts

api/db-cdr/generate-cdr/build-cb-criteria-cpt4.sh, api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh, api/db-cdr/generate-cdr/build-cb-criteria-device.sh, api/db-cdr/generate-cdr/build-cb-criteria-drug.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd10-cm.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd10-pcs.sh, api/db-cdr/generate-cdr/build-cb-criteria-icd9.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-clin.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-labs.sh, api/db-cdr/generate-cdr/build-cb-criteria-meas-snomed.sh, api/db-cdr/generate-cdr/build-cb-criteria-observation.sh, api/db-cdr/generate-cdr/build-cb-criteria-pm-cs.sh, api/db-cdr/generate-cdr/build-cb-criteria-pm.sh, api/db-cdr/generate-cdr/build-cb-criteria-snomed-condition.sh, api/db-cdr/generate-cdr/build-cb-criteria-snomed-procedure.sh, api/db-cdr/generate-cdr/build-cb-criteria-surveys.sh, api/db-cdr/generate-cdr/build-cb-criteria-visit.sh, api/db-cdr/generate-cdr/cb-criteria-utils.sh
=> [no-ticket][risk=no] fixing temp table issue

api/db-cdr/generate-cdr/build-ds-linking.sh
The build-ds-linking.sh was taking 4+ mins to build in circleCi. This PR removes the 17 queries that were not needed.
=> [no-ticket][risk=no] speeding up inserts for ds_linking

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
Description:
---
- create feature flag for adding ConceptSet(s) to CohortBuilder
- add to config jsons for all environments
- update workbench-api.yaml#ConfigResponse
- add flag to WorkbenchConfig and WorkbenchConfigMapper
- local deploy works as expected
---
* AoU UI
=> [DT-206][risk=no] Feature Flag: create feature flag: enableConceptSetsInCohortBuilder

ui/src/app/components/buttons.tsx
Suggestions from #7425
Tested CT Annual Renewal Banner behavior locally
---
* AoU UI
=> [risk=low][no ticket] Update the new HashLink

ui/src/app/pages/access/controlled-tier-card.tsx
=> [risk=no][RW-9561] Requested text update

e2e/app/text-labels.ts
Add 'Short Read' to CS name in test to match app
=> [DT-263][risk=no] Update prepackaged WGS concept set text in nightly test

ui/src/app/components/apps-panel.spec.tsx, ui/src/app/components/apps-panel.tsx, ui/src/app/components/apps-panel/app-logo.tsx, ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/apps-panel/utils.tsx, ui/src/testing/stubs/apps-api-stub.ts, ui/src/testing/stubs/workspaces.tsx
Plus a few minor code updates
---
* AoU UI
=> [risk=low][RW-9518] Add some AppsPanel unit tests

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh, ui/src/app/pages/data/cohort/cohort-criteria-menu.tsx
Add new CB menu items for CS/Quick Add. Not sure what to call the category, so for now I named it 'Other`
=> [DT-18][risk=no] Add new CB menu items for CS/Quick Add

api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditor.kt, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt, api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java, api/src/main/java/org/pmiops/workbench/exfiltration/EgressRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressJiraHandler.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressObjectLengthsJiraHandler.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressSumologicJiraHandler.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClient.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoConfig.java, api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorTest.java, api/src/test/java/org/pmiops/workbench/exfiltration/EgressEventServiceTest.java, api/src/test/java/org/pmiops/workbench/exfiltration/EgressRemediationServiceTest.java, api/src/test/java/org/pmiops/workbench/utils/mappers/LeonardoMapperTest.java
=> [RW-9503][risk=low] Data exfill backend changes for GKE apps

e2e/app/component/select-menu.ts
Description:
To test, run ```yarnm1e2e test-local-nightly:debug tests/nightly/admin/user-profile-admin.spec.ts```
---
* AoU UI
=> [RW-9365][risk=no] Changed dropdown to close after opening to get options.

api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java, api/src/main/java/org/pmiops/workbench/access/AccessUtils.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/model/DbAccessModule.java, api/src/main/resources/emails/README.md, api/src/main/resources/emails/tier_access_expired/content.html, api/src/main/resources/emails/tier_access_threshold/content.html, api/src/main/resources/emails/tier_access_threshold/content.mjml
Followups to #7429 
Not sure if all of these are desirable.
---
* AoU UI
=> [risk=low][no ticket] Followups for access tier expiration emails

ui/src/app/pages/access/controlled-tier-card.tsx, ui/src/app/pages/access/data-access-requirements.spec.tsx, ui/src/app/pages/access/data-access-requirements.tsx, ui/src/app/pages/signed-in/nav-bar.tsx, ui/src/testing/default-server-config.ts
Followup to #7449.  Can merge after a release which includes it.
---
* AoU UI
=> [risk=low][RW-9570] rm enableControlledTierTrainingRenewal=false code from UI

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json
=> [RW-9555][risk=no] Update jupyter docker image in higher envs

ui/src/app/components/take-demographic-survey-v2.tsx, ui/src/app/pages/signed-in/signed-in.tsx, ui/src/app/utils/constants.tsx
=> [RW-8657 ][risk=no] Clean up Demographic survey banner text logic after 30 days deadline is reached

api/config/config_staging.json
RStudio should not be possible even with the flag set to true, because we are not on Terra's allowlist.
But let's fix the flag so we're not pretending that we can.
---
* AoU UI
=> [risk=low][no ticket] Disable RStudio on Staging - it doesn't work anyway

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
Followup to https://github.com/all-of-us/workbench/pull/7449 and #7456. Can merge after a release which includes #7456.
---
* AoU UI
=> [risk=low][RW-9570] Fully remove enableControlledTierTrainingRenewal feature flag

api/db-cdr/generate-cdr/build-ds-tables.sh
Removing duplicates from ds_survey.
=> [no ticket][risk=no] fixing ds_survey

api/db-cdr/generate-cdr/libproject/genomic_manifests.rb, api/src/main/webapp/static/README.md
=> [RW-8999][risk=no] Fix genomic manifest to support long reads assets

api/config/config_test.json
Description:
---
- turn on `enableConceptSetsInCohortBuilder` flag in test environment
---
* AoU UI
=> [DT-307][risk=no] Turn on feature flag: enableConceptSetsInCohortBuilder for test 

e2e/tests/notebook/notebook-snippets.spec.ts
A logical extension of #7482
---
* AoU UI
=> [risk=low][RW-9725] extend snippets e2e test to include R notebooks

ui/src/app/components/app-status-icon.tsx, ui/src/app/components/runtime-status-icon.tsx, ui/src/app/components/status-icon.tsx
Description:
Broke up status icon logic to work with both runtimes and apps.
---
* AoU UI
=> [RW-9608][risk=no] Broke up status icon logic to work with both runtimes and apps.

api/libproject/devstart.rb
=> [RW-5609][risk=no] Update cloud sql instance name

api/libproject/devstart.rb, api/src/main/webapp/WEB-INF/appengine-web.xml.template
=> [no ticket][risk=no] rename DB_PASSWORD to WORKBENCH_DB_PASSWORD

api/build.gradle, api/db/local-vars.env, api/libproject/devstart.rb, api/libproject/generate_appengine_web_xml.rb, api/src/integration/java/org/pmiops/workbench/ApplicationTest.java, api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java, api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java, api/src/main/webapp/WEB-INF/appengine-web.xml.template
Tested locally and deployed to:
https://java11-dot-api-dot-all-of-us-workbench-test.uc.r.appspot.com
---
* AoU UI
=> [RW-5609][risk=no] Upgrade to GAE's Java 11 runtime

api/build.gradle, deploy/Dockerfile
=> [no ticket][risk=no] Upgrade deploy Dockerfile java version to 11

api/config/config_prod.json, deploy/Dockerfile
Description:
https://pmi-engteam.slack.com/archives/CFK24QJK0/p1680291752323469
Somehow request is sent to appspot for prod. Need to turn it off until issue is fixed. 
---
* AoU UI
=> [no ticket][risk=low] Disable URL base check as it breaks prod

api/build.gradle, api/db/local-vars.env, api/docker-compose.yaml, api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/db/WorkbenchDbConfig.java, api/tools/src/main/java/org/pmiops/workbench/tools/Action.java, api/tools/src/main/java/org/pmiops/workbench/tools/BackfillEntitiesToRdr.java, api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java, api/tools/src/main/java/org/pmiops/workbench/tools/CreateTerraMethodSnapshot.java, api/tools/src/main/java/org/pmiops/workbench/tools/CreateWgsCohortExtractionBillingProjectWorkspace.java, api/tools/src/main/java/org/pmiops/workbench/tools/DeleteWorkspaces.java, api/tools/src/main/java/org/pmiops/workbench/tools/ExportWorkspaceOperations.java, api/tools/src/main/java/org/pmiops/workbench/tools/FetchFireCloudUserProfile.java, api/tools/src/main/java/org/pmiops/workbench/tools/FetchWorkspaceDetails.java, api/tools/src/main/java/org/pmiops/workbench/tools/FixDesynchronizedBillingProjectOwners.java, api/tools/src/main/java/org/pmiops/workbench/tools/InvalidateRdrExport.java, api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java, api/tools/src/main/java/org/pmiops/workbench/tools/SetAccessModuleTimestamps.java, api/tools/src/main/java/org/pmiops/workbench/tools/SetAuthority.java, api/tools/src/main/java/org/pmiops/workbench/tools/Tool.java, api/tools/src/main/java/org/pmiops/workbench/tools/cdrconfig/UpdateCdrConfig.java, api/tools/src/main/java/org/pmiops/workbench/tools/institutions/LoadInstitutions.java
Removes configuration garbage. Uses single source-of-truth for database configuration.
Ran set-authority and dev-up locally. Did not test every tool.
---
* AoU UI
=> [no-ticket][risk=no] Fix Spring-based command-line tools

ui/src/app/components/apps-panel.spec.tsx, ui/src/app/components/apps-panel.tsx, ui/src/app/components/apps-panel/utils.spec.tsx, ui/src/app/components/apps-panel/utils.tsx
=> [RW-9608][risk=no] Adjusted how available/active apps are shown

api/snippets-menu/aou-snippets-menu.js.template
The PR to add R snippet for cromwell, [Add R Snippets](https://github.com/all-of-us/workbench/commit/67bcb40f6a6efc8c549756a4b1bc524617fdaa67)  has been pushed however it is failing to deploy it to api. I think its because i missed the entry for new snippet in the file aou-snippets-menu.js.template
Description:
---
* AoU UI
=> [RW-9753][risk=no]   Cromwell snippet missing from Jupyter R notebook - Fix api deploy

.circleci/config.yml, ci/Dockerfile.circle_build, ci/README.md, deploy/Dockerfile
=> [risk=low][RW-6767][RW-6756] Update build image for gradle 7 and update DockerHub text to GCR

.circleci/config.yml
Update our cache keys, so gradle 7 builds don't see cache-hits for gradle 6.
Not sure is this is strictly necessary.  Followup to #7542
---
* AoU UI
=> [risk=low][RW-6767] Update our gradle cache keys from "v6" to "v7"

e2e/tests/notebook/notebook-snippets.spec.ts
=> [RW-9753][risk=no]   Cromwell snippet missing from Jupyter R notebook - e2e tests

api/db-cdr/generate-cdr/build-review-all-events.sh
Description:
---
- Fix reference to survey name for PFHH - added as a static entry
---
* AoU UI
=> [DT-345-2][risk=no] Fix ref to survey name for PFHH

api/db-cdr/generate-cdr/build-ds-tables.sh
Description:
---
- Fix entries for cope vaccine survey in ds_survey table
---
* AoU UI
=> [DT-345][risk=no] Fix df_survey covid-vaccine counts

e2e/app/page/notebook-frame.ts
=> [risk-no][no ticket] e2e: add error message for debug-mode contentFrame()

api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java, deploy/libproject/deploy.rb
Tested by running after SSH-ing onto the Circle job corresponding to the failed run here https://app.circleci.com/pipelines/github/all-of-us/workbench/25671/workflows/c710d058-5317-495b-9419-fdfffeb5b69f/jobs/275724
---
* AoU UI
=> [risk=low][no ticket] Use correct SA and creds for Circle deployments

ui/src/app/components/popups.tsx, ui/src/app/pages/admin/user/admin-user-bypass.spec.tsx, ui/src/app/pages/admin/user/admin-user-bypass.tsx, ui/src/app/pages/admin/user/admin-user-common.tsx, ui/src/app/pages/admin/user/admin-user-profile.spec.tsx, ui/src/app/pages/admin/user/admin-user-profile.tsx, ui/src/app/pages/admin/user/admin-user-table.spec.tsx
Shares code across the admin bypass toggles. Adds tests for the toggles.
This is a follow-up to [this comment](https://github.com/all-of-us/workbench/pull/7543#discussion_r1157723185).
This includes one user-facing change. To keep the code simple, the order of the toggles now matches the order on the user admin page. I think this change is OK because only a few people use this page and we don't use them very often.
I'm not marking the story as "Dev Review" yet because I'm going to do another pass to see if there are any more refactors I should do.
Compare the ordering to the screenshot in [this PR](https://github.com/all-of-us/workbench/pull/7543).
---
* AoU UI
* …
=> [RW-9208][risk=no] Refactor bypass toggles

ui/src/app/components/apps-panel.tsx, ui/src/app/pages/workspace/workspace-wrapper.tsx, ui/src/app/utils/stores.tsx, ui/src/app/utils/user-apps-utils.tsx
Description:
Added polling cleanup and initialize on workspace wrapper rather than apps panel.
---
* AoU UI
=> [RW-9923][risk=no] Fixed User App Polling

api/config/config_prod.json
=> [RW-9523][risk=low] Enable Cromwell in prod.

api/db/local-vars.env
Needed to add CDR_DB_HOST=127.0.0.1 to local-vars.evn
=> [no ticket][risk=no] fixing local api dev-up

api/libproject/devstart.rb
Description:
---
- Updated update-cloud-config to fix credential issue by wrapping in ServiceAccountContext
- This command is needed to update featured workspaces / demos / tutorials for the upcoming CDR release.
---
* AoU UI
=> [DT-355][risk=no] Fix update-cloud-config command

api/config/config_stable.json
Followup to #7581 
We generally want to keep Stable as close to Prod as we can.
---
* AoU UI
=> [RW-9523][risk=low] enable Cromwell on Stable to match Prod

ui/src/app/components/configuration-panel.spec.tsx, ui/src/app/components/configuration-panel.tsx, ui/src/app/components/cromwell-configuration-panel.spec.tsx, ui/src/app/components/cromwell-configuration-panel.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/components/runtime-configuration-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel.tsx
Description:
Miscellaneous Cromwell configuration panel refactors. There are no product-facing changes.
This should  simplify sharing code with a comparable RStudio config panel.
**Reviewer note: This PR is most easily reviewed commit-by-commit.**
This commit very loosely builds on https://github.com/all-of-us/workbench/pull/7584 so the first commit can be safely skipped in review.
---
* AoU UI
=> [RW-9746][risk=no] Cromwell configuration panel refactors

api/libproject/devstart.rb
fixing host and port problem with mysql import
=> [DT-361][risk=no] fixing host and port problem with mysql import

api/db-cdr/generate-cdr/build-prep-survey.sh
added answers for other liver condition
=> [DT-360][risk=no] added answers for other liver condition

api/config/featured_workspaces_prod.json
Description:
---
- Updated featured workspaces for new CDR version
---
* AoU UI
=> [DT=357][risk=no] Updated featured workspaces for V7 where indicated.

api/config/config_local.json, api/config/config_perf.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
adding feature flag for tanagra
=> [DT-351][risk=no] adding feature flag for tanagra

.github/PULL_REQUEST_TEMPLATE.md
The new template (edited to include the most recent changes):
---
=> [no ticket][risk=no] Update pull request template

api/build.gradle
Eliminates this warning in Gradle builds:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.6.1/userguide/command_line_interface.html#sec:command_line_warnings
```
---
=> [no ticket][risk=no] Fixes Gradle warnings

api/libproject/environments.rb
https://cloud.google.com/appengine/docs/standard
Before f1 class, now f3
---
=> [no  ticket][risk=no]Update stable and preprod instance

ui/src/app/pages/appAnalysis/app-files-list.spec.tsx, ui/src/app/pages/appAnalysis/app-files-list.tsx, ui/src/app/pages/appAnalysis/app-selector.spec.tsx, ui/src/app/pages/appAnalysis/app-selector.tsx, ui/src/app/routing/workspace-app-routing.tsx
Rename apps-list to app-files-llist (because it will eventually have a lit of files associated with user apps)
Extract an app-selector component from that file
Tested by running Local->Test and observing the same behavior as Test in the Applications (New) tab
Does not complete RW-9105.
---
=> [risk=low][RW-9105] Extract app-selector component from app files list

api/libproject/devstart.rb
Pass credential information to ServiceAccountContext. This information was lost in https://github.com/all-of-us/workbench/pull/7555, partially re-added in https://github.com/all-of-us/workbench/pull/7566, and removed again in https://github.com/all-of-us/workbench/pull/7631, breaking deploys to test.
Unfortunately, I'm not sure how to test these commands without just deploying to the test environment. My plan is to watch the next test build and possibly deploy to staging.
---
=> [no ticket][risk=no] Pass credential information to ServiceAccountContext

api/libproject/devstart.rb
Reverts two small changes from #7631 to fix test deploy. Tested via Circle SSH run. Co-authored with @Peter-Lavigne.
---
=> [no ticket][risk=no] Fix deploy by removing SAC usage

api/build.gradle
Addresses a [Snyk](https://app.snyk.io/org/all-of-us-researcher-workbench/project/bf2628cc-574b-4c92-a236-237ad192de46) vulnerability.
Tested locally by running the `uploadReportingSnapshot` cron (exercises BigQuery) on Local and exporting a dataset to a notebook (exercises JSON) on Local->Local.
---
=> [risk=low][no ticket] bump json and bigquery to latest

.circleci/config.yml
Bump 4 min wait to 5 min, because it can take that long
---
=> [risk=no][no ticket] Circle: wait 5 min for local API server

api/build.gradle
See code comments. Ran unit tests locally.
---
=> [no ticket][risk=no] Bump source/target compatibility to Java 11

api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java
Ran this command:
```
export GOOGLE_APPLICATION_CREDENTIALS=~/all-of-us-rw-prod-c2f8e2ca7c4f.json; \
./gradlew manageLeonardoRuntimes -PappArgs="['list','https://notebooks.firecloud.org','false','','TABULAR']"
```
Fails on clean, successful with this fix.
---
=> [no ticket][risk=no] Don't use DB config for ManageLeonardoRuntimes

api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java, api/src/main/java/org/pmiops/workbench/actionaudit/auditors/EgressEventAuditorImpl.kt, api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java, api/src/main/java/org/pmiops/workbench/api/RuntimeController.java, api/src/main/java/org/pmiops/workbench/api/StatusAlertController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/Params.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java, api/src/main/java/org/pmiops/workbench/exfiltration/EgressLogService.java, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/main/java/org/pmiops/workbench/iam/IamServiceImpl.java, api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java, api/src/main/java/org/pmiops/workbench/institution/InstitutionUtils.java, api/src/main/java/org/pmiops/workbench/monitoring/StackdriverStatsExporterService.java, api/src/main/java/org/pmiops/workbench/profile/ProfileService.java
I thought it would be fun to play with some of the new Java 9-11 features.  No functional changes expected.
---
=> Better uses of Optional, inspired by the Java 11 upgrade

api/build.gradle, api/src/main/java/org/pmiops/workbench/captcha/CaptchaVerificationServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java
Use Swagger Codegen V3 for all but workbench-api.yaml.
I'm not going to test every API since Joel did some and I think there is good reason to believe the compiler caught all significant differences.
---
=> [no ticket][risk=no] Remove most of Swagger Codegen V2

api/docs/tools.md, api/libproject/devstart.rb, api/tools/src/main/java/org/pmiops/workbench/tools/SetAuthority.java
Converts user confirmation to a remove-all flag by changing the arguments `--authority ALL --remove` into the newly-added `--remove-all` flag. Removes the `ALL` option entirely.
This is my third pass at converting the user confirmation message into Java. The first two attempts can be found [here](https://github.com/all-of-us/workbench/pull/7641).
Future changes that this refactor allows can be found [here](https://docs.google.com/document/d/1-4BPwzEAfxlQqMnF0EAPFmnLOPgp9-fpyMXhPywpgzQ/edit#).
**Testing**
For the same reasons as the previous PR, I have manually tested this change.
To query authorities for a given user run the following SQL: `select * from authority where user_id = (select user_id from user where email = "<email>@fake-research-aou.org");`
1. Remove …
=> [RW-9958][risk=no] Convert user confirmation to a remove-all flag

e2e/tests/nightly/gke-apps/cromwell.spec.ts
Apart from Python, this PR will use R notebook to check
-   cromshell is running
- The status of cromshell (provisioning or running)
- Upload wdl and json file
- Submit wdl using cromshell
- Clean up: delete cromshell, notebook and workspace
---
=> [RW-9518][risk=no]   [tests] Cromwell / User App tests - Using R Notebook

api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceService.java, api/src/main/java/org/pmiops/workbench/impersonation/ImpersonatedWorkspaceServiceImpl.java
=> [risk=low][no ticket] fix main after merge conflict

ui/src/app/pages/data/cohort-review/detail-tab-table.component.tsx
Fix for Labs/Vitals charts in cohort review participant detail table.
Example of broken layout:
Fixed layout:
---
=> [DT-380][risk=no] Fix styling on cohort review charts

api/config/config_test.json, e2e/.env.circleci.local, e2e/.env.circleci.test, e2ev2/src/config.js
=> [risk=low][RW-10024] bump e2e test user to 8

.github/PULL_REQUEST_TEMPLATE.md
=> [no ticket][risk=no] Tweaks to PR checklist

.gitmodules
=> [DT-384][risk=no] adding Tanagra as a submodule

api/config/config_local.json, api/config/config_test.json
https://github.com/DataBiosphere/leonardo/pull/3267
Leo pr is deployed to test now
---
=> [RW-9847][risk=low] Upgrade test and local Jupyter docker image  

e2e/app/modal/export-to-notebook-modal.ts, e2e/app/text-labels.ts, e2e/tests/notebook/notebook-create-python.spec.ts, e2e/tests/notebook/notebook-snippets.spec.ts, ui/src/environments/environment-type.ts
https://user-images.githubusercontent.com/6351731/238725508-2384746b-3d12-4972-9e58-852aa6495ff1.png
---
=> [no ticket][risk=no] Update Python kernel name caused by Jupyter upgrade

ui/src/app/pages/runtimes-list.tsx, ui/src/terraui/build.sh
Includes changes to API calls as required. Tested by loading the page and deleting a persistent disk.
https://pr-3-dot-all-of-us-workbench-test.appspot.com/runtimes
---
=> [RW-10047][risk=no] Take new version of Cloud Environments component from Terra UI

e2e/tests/nightly/ras-login.spec.ts
=> [risk=low][RW-10156] Update RAS test to reflect updated RAS site experience

api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java, api/src/main/resources/captcha.yaml, api/src/main/resources/mandrill.yaml, api/src/main/resources/rdr.yaml, api/src/test/java/org/pmiops/workbench/captcha/CaptchaVerificationServiceTest.java, api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
Update **rdr.yaml** to OpenAPI 3 by using https://editor.swagger.io/
Tested locally by running the `uploadReportingSnapshot` cron without errors.
Update **captcha.yaml** to OpenAPI 3 by using https://editor.swagger.io/
Tested locally by temporarily setting `enableCaptcha` to true and creating a new account.  It prompted me for captcha and accepted the response.
Update **mandrill.yaml** to OpenAPI 3 by using https://editor.swagger.io/
Tested locally by creating a new account, which sends an email.  I received it and the information was correct.
---
=> [risk=low][RW-8978] Update more swaggers to OpenAPI 3

api/db-cdr/generate-cdr/build-cb-search-person.sh
=> [risk=no][no ticket] fixing indices query

api/config/cdr_config_test.json
=> [risk=no][no ticket] bump cdr index

api/db/changelog/db.changelog-215-add-egress-bypass-table.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/db/dao/UserEgressBypassWindowDao.java, api/src/main/java/org/pmiops/workbench/db/model/DbUserEgressBypassWindow.java, api/src/test/java/org/pmiops/workbench/db/dao/UserEgressBypassWindwoDaoTest.java
The following PR will use this table and Dao by:
1. POST Admin API to insert record into user egress bypass table.
---
=> [RW-8828][risk=low] Add UserEgressBypass table for large file download support

api/config/featured_workspaces_prod.json
Adding featured workspace as requested by Chris Lord.
https://docs.google.com/document/d/17YVCqu4BhVV8ai3OutHx8u0m6V5NkdM5H9kLNxTPDdo/edit#heading=h.le71kr4fpdq
---
=> [RW-10188][risk=no] Updating featured workspaces.

ui/src/app/components/buttons.tsx, ui/src/app/components/icons.tsx, ui/src/app/components/resource-actions-menu.tsx, ui/src/app/pages/analysis/notebook-resource-card.tsx, ui/src/app/pages/analysis/util.ts, ui/src/app/pages/appAnalysis/app-files-list.tsx, ui/src/app/pages/appAnalysis/app-selector.tsx, ui/src/app/pages/appAnalysis/apps-file-list.spec.tsx, ui/src/styles.css
https://github.com/all-of-us/workbench/assets/34481816/57cb3564-bc7b-4508-afd2-50bc5ee2486c
Updated screen shot with header padding:
---
=> [risk=no][RW-9105]  [UI] Display existing Jupyter files in new Analysis tab

ui/src/app/components/cookie-banner.tsx, ui/src/app/components/ct-available-banner-maybe.tsx, ui/src/app/components/status-alert-banner-maybe.tsx, ui/src/app/routing/app-routing.tsx, ui/src/app/services/swagger-fetch-clients.ts, ui/src/app/utils/cookies.tsx
Removes formerly-hardcoded third-party cookie logic.
Per [this thread](https://pmi-engteam.slack.com/archives/C0150CWF6FP/p1685546457742989), to address the ticket we are creating a support article to inform users instead.
I've included the technical explanation for why we cannot check this in the code comments.
Additionally, this renames `cookiesEnabled` to `firstPartyCookiesEnabled` to more accurately reflect what the function does. If [this issue](https://github.com/Modernizr/Modernizr/issues/2444) is ever resolved we could update the function accordingly (our code is copied directly from that repo).
Additionally, this fixes the issue mentioned in [this closed PR](https://github.com/all-of-us/workbench/pull/7361). Unfortunately, trying to manually test this has exposed [a …
=> [risk=no][RW-9484] Remove third-party cookie logic

api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java, api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/analysis/util.ts, ui/src/app/pages/appAnalysis/app-files-list.tsx
- Open a Jupyter notebook from the new analysis tab. This should open a preview tab that is unchanged:
- Create a file named example.Rmd.
- Copy the contents of https://gist.github.com/jeromyanglim/2716336 into the file
- Copy example.Rmd into workspace bucket's notebooks folder:
`gsutil -i all-of-us-workbench-test@appspot.gserviceaccount.com cp  "example.Rmd" "gs://<bucket-name>/notebooks"`
- Navigate to new analysis tab and open example.Rmd.
- It should look something like this (no edit or playground buttons):
---
=> [RW-9830][risk=no] Enable Preview for Rmd files.

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
=> [no ticket][risk=no] fixing menu bug

.gitmodules, aou-tanagra-utils/init_new_tanagra_db.sh, aou-tanagra-utils/run_tanagra_server.sh
---
- updated to pin tanagra submodule to a branch [tanagra-branch](https://github.com/DataBiosphere/tanagra/tree/chenchals/DT-412-Revisit-common-schema-files)
- Updated mariadb initialization and set mac_connection=300 when running `./project.rb tanagra-dev-up`
- Added flag for dropping tanagra_db
---
=> [DT-409][risk=no] Aou tanagra integration - Local deploy only

ui/src/app/pages/data/cohort/attributes-page.spec.tsx, ui/src/app/pages/data/cohort/attributes-page.tsx
Convert `AttributesPage` component from a class to React hooks
---
* AoU UI
=> [DT-107][risk=no] Convert AttributesPage to React hooks

.gitmodules
---
- Removed branch reference from tanagra submodule
---
=> [no-ticket][risk=no] Removed branch reference from tanagra sub-module

ui/src/app/pages/appAnalysis/app-files-list.tsx
https://github.com/all-of-us/workbench/assets/34481816/5522afbd-69a1-46b4-a04c-841bebc5cb02
---
=> [risk=no][noTicket] Fix Style for New Analysis Tab

e2e/app/sidebar/apps-panel.ts, e2e/tests/nightly/gke-apps/cromwell.spec.ts
=> [risk=no][noTicket] Fix cromwell nightly test: delete pannel

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoCustomEnvVarUtils.java
=> [RW-10097][risk=no] Fix one env variable

ui/package.json, ui/src/app/pages/admin/disks-table.spec.tsx, ui/src/app/pages/analysis/interactive-notebook.spec.tsx, ui/yarn.lock
Installs the [recommended user-event library](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme#simulate-user-events) and converts all our `fireEvent` uses to it. This library is a wrapper around `fireEvent` that ensures the correct browser events are called for "user" events, such as clicking.
---
=> [risk=no][no ticket] Use the recommended user-event library

api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java, api/src/main/java/org/pmiops/workbench/mail/EmailSubstitutionField.java, api/src/main/java/org/pmiops/workbench/mail/MailService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java, api/src/main/resources/emails/unused_disk/content.html, api/src/test/java/org/pmiops/workbench/api/OfflineRuntimeControllerTest.java, api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
I saw what looks like a potential issue in #7735 - I don't think it makes the right determination about whether a Jupyter PD is attached.
The rest is mainly refactoring ideas I had about it.
---
=> [risk=low][RW-10004] Updates to disk/app logic

e2e/utils/test-utils.ts
Adds user information to e2e test logger. This would have helped identify billing failures described in [this thread](https://pmi-engteam.slack.com/archives/C7JUTPQLE/p1687275495920719).
---
=> [risk=no][no ticket] Add user information to e2e test logger

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java
This PR also exclude deleted disk from the final list.  Will check with @evrii next week about this.  
---
=> [RW-10303][risk=low] Use service api disk provider in admin disk endpoint. 

api/build.gradle
Resolves https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-5710356
Tested by running a local server.
---
=> [risk=low][no ticket] bump guava to resolve a vulnerability

api/src/main/java/org/pmiops/workbench/api/NotebooksController.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebookUtils.java, api/src/main/java/org/pmiops/workbench/notebooks/NotebooksServiceImpl.java, api/src/test/java/org/pmiops/workbench/notebooks/NotebooksServiceTest.java, ui/src/app/pages/admin/admin-workspace.tsx, ui/src/app/pages/analysis/util.ts, ui/src/app/utils/constants.tsx
https://github.com/all-of-us/workbench/assets/34481816/b17a89f8-6130-4c7f-b25b-481e62ef325b
https://github.com/all-of-us/workbench/assets/34481816/6dbe3067-b787-43cf-8d6d-29ac701448f0
---
=> [risk=no][RW-10271]  Ensure .R files show up on Analysis tab

api/db/changelog/db.changelog-218-drop-unused-columns-user-table.xml, api/db/changelog/db.changelog-master.xml
Tested locally by making user profile changes and module bypass/unbypasses, as well as running a Reporting Snapshot.
---
=> [risk=low][RW-5628] Drop DB fields for user table which are no longer used

api/src/main/java/org/pmiops/workbench/db/dao/UserEgressBypassWindowDao.java, api/src/main/java/org/pmiops/workbench/user/UserAdminService.java, api/src/test/java/org/pmiops/workbench/user/UserAdminServiceTest.java
=> [risk=low][no ticket] Some updates to #7757

api/config/featured_workspaces_prod.json
Adds the `genomics-workshop-07122023` tutorial workspace to the `featured_workspaces_prod.json` config file
---
=> [RW-10398][risk=no] Add tutorial workspace to prod config

ui/yarn.lock
It's recommended to update this regularly: https://github.com/browserslist/update-db#readme
---
=> [risk=low][no ticket] Bump caniuse-lite in ui

api/libproject/devstart.rb, tanagra-aou-utils/tanagra-api.yaml
- Updated the tanagra deployment to connect to CloudSQL with SSL.
- Updated the tanagra submodule to pull the latest code, which includes a [corresponding config change](https://github.com/DataBiosphere/tanagra/pull/469) in the main tanagra repo.
- Tested this with a successful deploy to the AoU test environment: no VPC connector, connecting over public IP. I deployed to AppEngine from my local computer using copies of `tanagra-api.yaml` and `tanagra_env_variables.yaml`.
```
env_variables:
TANAGRA_DB_URI: jdbc:mysql:///tanagra_db
TANAGRA_DB_USERNAME: *****
TANAGRA_DB_PASSWORD: *****
TANAGRA_DB_CLOUD_SQL_INSTANCE: **project:region:instance**
TANAGRA_DB_SOCKET_FACTORY: com.google.cloud.sql.mysql.SocketFactory
TANAGRA_DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
```
---
- …
=> [risk=no][no ticket] Update tanagra deployment to connect to CloudSQL with SSL.

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/cohort/search-group-item.tsx
removing enableConceptSetsInCohortBuilder feature flag
=> [DT-209][risk=no] removing enableConceptSetsInCohortBuilder feature flag

api/config/featured_workspaces_prod.json
---
Publishing featured workspaces to prod. Updated _featured_workspaces_prod.json_ conifig file for the following tickets:
- https://precisionmedicineinitiative.atlassian.net/browse/RW-10498
- https://precisionmedicineinitiative.atlassian.net/browse/RW-10499
---
=> [DT-453][risk=no] Publish featured workspaces prod

ui/src/app/components/inputs.spec.tsx, ui/src/app/components/inputs.tsx, ui/src/app/pages/admin/user/admin-user-egress-bypass.tsx
=> [noTicket][risk=no]Refactor TextAreaWithLengthValidationMessage

api/db-cdr/generate-cdr/build-ds-linking.sh
---
- Fix ds_linking table for `visit_occurrence`
---
=> Add visit data to ds_linking table

ui/src/app/pages/admin/user/admin-user-common.tsx
Admin User page:
Desired behavior, from [Slack](https://pmi-engteam.slack.com/archives/CFK24QJK0/p1689858005881969):
```
300-500 every $25
500-1000 every $100
1000-10000 every $500
```
---
=> [risk=low][no ticket] New initial credit limit ranges, as requested

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
---
- Removed checks and enabled selection of individual prepackaged surveys
- Fixed broken test for feature-flagged individual prepackaged surveys
---
=> [DT-457][risk=no] Removed checks to enable selection of individual prepackaged surveys.

api/build.gradle
=> [risk=low][no ticket] Bump API dependency check to latest

api/config/featured_workspaces_prod.json
publish a featured workspace per https://precisionmedicineinitiative.atlassian.net/browse/RW-10576
=> [RW-10576][risk=no] publish a featured workspace

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
Reverts all-of-us/workbench#7827
=> Revert "[DT-457][risk=no] Removed checks to enable selection of individual prepackaged surveys."

api/config/config_staging.json, ui/src/environments/environment.staging.ts
Let's see how well these work on Staging before pushing to Preprod
---
=> [risk=low][RW-9416][RW-9754] Set enableRStudioGKEApp and showNewAnalysisTab to true on Staging

api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java, api/src/test/java/org/pmiops/workbench/access/UserServiceAccessTest.java
Check to make sure that IDENTITY is not required for RT membership when enableRasLoginGovLinking is disabled.
---
=> [no ticket][risk=no] Added missing Identity enabled check.

api/db/changelog/db.changelog-223-modify-egress-bypass-window-datatype.xml, api/db/changelog/db.changelog-master.xml, api/src/main/resources/leonardo.yaml
Supports had issue when using long description., increase size limit to higher number
---
=> [no ticket][risk=low] increase egress bypass window description field max size

api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java, ui/src/app/pages/data/cohort/cohort-search.tsx, ui/src/app/pages/data/cohort/utils.ts, ui/src/app/pages/data/cohort/variant-search.tsx, ui/src/app/pages/data/criteria-search.tsx, ui/src/app/styles/datatable.ts
Implement UI for searching VAT table in cohort builder.
Search bar with tooltip (example searches same as Data Browser):
Lazy-load pagination:
https://github.com/all-of-us/workbench/assets/40036095/cafad267-985c-4c5d-8584-601f7ba6df40
---
=> [DT-444][risk=no] UI for CB variant search

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
Tested locally - can still use Cromwell and RStudio.
#7856 has been released, so we can now merge this PR.
---
=> fully remove the enableCromwellGKEApp FF

api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, ui/src/app/components/help-sidebar-icons.tsx, ui/src/app/components/help-sidebar.spec.tsx, ui/src/app/components/render-resource-card.spec.tsx, ui/src/app/pages/data/data-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx, ui/src/app/pages/data/data-set/dataset-resource-card.tsx
Tested locally by running a genomic extraction.  We can fully remove the flag after a release cycle: #7880
---
=> [risk=low][no ticket] Remove all API+UI code related to enableGenomicExtraction

README.md, tanagra-aou-utils/tanagra-ui.yaml, ui/libproject/devstart.rb
- Add new command for deploying the Tanagra UI to the test environment
`./project.rb deploy-tanagra-ui --project all-of-us-workbench-test --version my-version --promote --quiet`
- Update `README.md` with new command
---
=> [DT-414][DT-464][risk=no] Add command for deploying Tanagra UI to test env

api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java, api/src/main/resources/leonardo.yaml, ui/src/app/components/apps-panel/expanded-app.spec.tsx, ui/src/app/components/apps-panel/utils.tsx, ui/src/app/pages/analysis/interactive-notebook.spec.tsx, ui/src/app/utils/constants.tsx, ui/src/app/utils/user-apps-utils.tsx, ui/src/testing/stubs/apps-api-stub.ts
https://precisionmedicineinitiative.atlassian.net/browse/RW-10622
new getApp response will look like this
```
{
"appName": "qi-rstudio-812",
"cloudContext": {
"cloudProvider": "GCP",
"cloudResource": "terra-quality-bf8ac05e"
},
"kubernetesRuntimeConfig": {
"numNodes": 1,
"machineType": "n1-highmem-8",
"autoscalingEnabled": false
},
"errors": [],
"status": "RUNNING",
"proxyUrls": {
"app": "https://leonardo.qi-aou2.bee.envs-terra.bio/proxy/google/v1/apps/terra-quality-bf8ac05e/qi-rstudio-812/app",
"welder-service": "https://leonardo.qi-aou2.bee.envs-terra.bio/proxy/google/v1/apps/terra-quality-bf8ac05e/qi-rstudio-812/welder-service"
},
"diskName": "qi-rstudio-812-disk",
"customEnvironmentVariables": {
"WORKSPACE_NAME": "qi-ws"
},
"auditInfo": {
"creator": "qiwangterra@gmail.com", …
```
=> [risk=low] RW-10622 refactor proxyurl

api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Add a CAPS requirement test per [this comment](https://precisionmedicineinitiative.atlassian.net/browse/RW-10593?focusedCommentId=171870).
---
=> [risk=no][RW-10593] Add CAPS requirement test

tanagra-aou-utils/run_tanagra_server.sh
---
- updated tanagra submodule to main with tag 0.0.176
- updated underlay file refs to point to new synthetic CDRs
*testing*
Deployed to local-docker and tested that the integration works fine and user can create worksoace for new tanagra synthetic CDRs
---
=> [DT-477][risk=no] Update tanagra submodule after new synthetic CDR indexing build

api/config/cdr_config_local.json, api/config/cdr_config_test.json, tanagra-aou-utils/run_tanagra_server.sh
---
- updated cdr_config files for local and test to use new synthetic CDRs that are `tanagraEnabled`
*Testing*
Tested new underlays by deploying to kocal-docker environment
---
=> [DT-476][risk=no] Reindex new synthetic cdrs for tanagra aou integration

api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java
adding workspaceNamespace to study
---
=> [DT-480][risk=no] adding workspaceNamespace to study

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json
Added v5 DUCC to staging, stable, pre-prod, and prod.
This is a follow on PR from https://github.com/all-of-us/workbench/pull/6691
---
=> [RW-8259][risk=no] Updated DUCC version to remaining environments.

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/workspace/workspace-nav-bar.tsx
removing feature flag for enableTanagra
---
=> [DT-479][risk=no] removing feature flag for enableTanagra

ui/src/app/pages/access/controlled-tier-card.tsx, ui/src/app/pages/access/data-access-requirements.spec.tsx, ui/src/app/pages/access/two-factor-auth-modal.spec.tsx, ui/src/testing/react-test-helpers.tsx
Before doing large scale conversion of Enzyme tests to React Testing Library, I wanted to do one fairly complex file first. If this all looks good, maybe we could take the steps and apply them to a larger swath of tests.
1. Add `import { render, screen } from '@testing-library/react';`
2. Replace all instances of `mount(` with `render(` (case sensitive). Any functions that are returning this should be given a return type of RenderResult.
3. Replace all instances of 
`wrapper =` with` { conatiner } =`
4. Replace most (only ones that are attached to a container somehow) instances of `.find` with `.querySelectorAll` or `.querySelector.` If interacting with individual result, use querySelector.
5. Replace all instances of wrapper (case sensitive) with container.
waitOneTickAndUpdate and …
=> [RW-10285][risk=no] Converted Enzyme Tests in pages/access

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
OK to merge because #7876 has been through a release cycle.
Tested by running locally and doing a genomics extraction
---
=> [risk=low][no ticket] Fully remove enableGenomicExtraction FF

api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudService.java, api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java
Tested locally by creating a new user and observing that the Workbench works normally.
---
=> [risk=low][RW-10492] Stop sending first/last names in Terra's Register User call

api/config/featured_workspaces_prod.json
---
- updated new demo projects that are published [RW-10756](https://precisionmedicineinitiative.atlassian.net/browse/RW-10756)
- PD ticket [PD-13791](https://precisionmedicineinitiative.atlassian.net/browse/PD-13791)
---
[RW-10756]: https://precisionmedicineinitiative.atlassian.net/browse/RW-10756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PD-13791]: https://precisionmedicineinitiative.atlassian.net/browse/PD-13791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RW-10756][risk=no]Publishing 2-demo projects RW-10756

api/config/featured_workspaces_prod.json
---
- Remove reference to deleted demo project from `featured_workspaces_prod.json` file
---
=> [no-ticket][risk=no]One of the demo-projects was deleted by demo team- update config file.

api/config/config_test.json
---
- Update tanagra base-url to match that set by Nick et.al.
- also updated [test env bucket]/vars.env file
---
=> [no-ticket][risk=no]update tanagra base url for test-config

ui/package.json, ui/readme-terra-ui-packages.md, ui/src/app/components/app-router.tsx, ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/apps-panel/pause-resume-button.tsx, ui/src/app/components/apps-panel/utils.tsx, ui/src/app/components/configuration-panel.tsx, ui/src/app/components/copy-modal.tsx, ui/src/app/components/environment-cost-estimator.tsx, ui/src/app/components/inputs.tsx, ui/src/app/components/runtime-configuration-panel.tsx, ui/src/app/pages/access/module-icon.tsx, ui/src/app/pages/access/module.tsx, ui/src/app/pages/admin/user/admin-user-common.tsx, ui/src/app/pages/admin/user/admin-user-table.tsx, ui/src/app/pages/admin/workspace/file-table.tsx, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/analysis/util.ts, ui/src/app/pages/homepage/recent-resources.tsx, ui/src/app/pages/signed-in/access-renewal-notification.tsx, ui/src/app/routing/guards.tsx, ui/src/app/utils/access-utils.tsx, ui/src/app/utils/errors.tsx, ui/src/app/utils/index.spec.tsx, ui/src/app/utils/index.tsx, ui/src/app/utils/institutions.tsx, ui/yarn.lock
Replace `cond` with same from @terra-ui-packages/core-utils.
This PR includes a new readme file with a usage guide for how to use packages from Terra UI.
I ran unit tests throughout the process of changing files.
This change partially completes the referenced Jira story. More to follow.
---
=> [risk=no][RW-10770] Use cond from @terra-ui-packages/core-utils

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh, api/db-cdr/generate-cdr/build-review-all-events.sh
=> [DT-489][risk=no] fixing PFHH survey

api/db-cdr/generate-cdr/build-review-all-events.sh
=> [DT-489][risk=no] fixing query

api/config/featured_workspaces_prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-10820
---
=> [RW-10820][risk=no] publish new workspace

ui/src/app/components/genomics-extraction-menu.tsx, ui/src/app/components/popups.tsx, ui/src/app/components/runtime-configuration-panel.tsx
Fixes the "delete runtime" issue on Test caused by #7922 
Tests forthcoming in a future PR.  If that takes too long, this PR will unblock the release.
Tested manually by:
* observing that it is possible to delete a runtime.
* observing a popup (crashes on Test)
* accessing the Genomics Extraction Menu (crashes on Test)
---
=> [risk=low][no ticket] Fix delete-runtime and replace no-longer-valid uses of switchCase

ui/src/app/components/genomics-extraction-menu.spec.tsx, ui/src/app/components/genomics-extraction-menu.tsx, ui/src/testing/react-test-helpers.tsx, ui/src/testing/utils.ts
Add a test as a followup to #7940 - this would have caught some of the errors fixed in that PR
---
=> [risk=no][no ticket] Add genomics-extraction-menu.spec

ui/package.json, ui/readme-terra-ui-packages.md, ui/yarn.lock
=> [risk=no][no ticket] Update Readme to provide tips on Terra UI package development

api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
Refactor compliance training tests. I think this helps make existing functionality more understandable.
This PR consists of a lot of small improvements. I recommend reviewing this PR commit-by-commit, as I provide explanations in commit descriptions where appropriate.
I'm open to suggestions for additional improvements.
---
=> [risk=no][RW-10361] Refactor compliance training tests

api/db-cdr/generate-cdr/test-data/create_prep_variant_attribute_tables.sql
updating VAT tables in test
---
=> [DT-512][risk=no] updating VAT tables in test

api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingService.java, api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java, api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
Purpose duplicates https://github.com/all-of-us/workbench/pull/7949, please read that PR's description.
---
=> [risk=no][no ticket] Additional compliance training refactors

api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
Tiny update to the change in #7906 - fix comments
---
=> [risk=low][no ticket] Fix copy-paste comments

ui/libproject/devstart.rb
https://precisionmedicineinitiative.atlassian.net/browse/RW-10924
---
=> RW-10924 Unblock release

ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx
Temporary solution for implementing authz in test. Will require a redeploy of the Tanagra UI to handle the token.
=> [DT-520][risk=no] Pass bearer token to Tanagra iframe in url

api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java, ui/src/app/pages/profile/profile-component.spec.tsx, ui/src/app/pages/profile/profile-component.tsx, ui/src/app/pages/profile/profile-styles.ts
https://github.com/all-of-us/workbench/assets/34481816/dcabc47b-6a2b-4a47-97e0-17429cf1235b
---
=> [RW-10717][risk=no]  Disable country updates on researcher profile page

api/config/featured_workspaces_prod.json
Per this feedback: https://precisionmedicineinitiative.atlassian.net/browse/RW-10820?focusedCommentId=177018
This should be a tutorial workspace. 
---
=> [RW-10820][risk=no] Move a feature workspace category

ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx
Removes `faLockAlt` icon from `tanagra-resource-list.tsx` to see if it's causing issue with FA download quota
=> [no ticket][risk=no] Remove FA icon from Tanagra component

ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx
Looks like a conflict snuck in between #7953 and #7964
---
=> [risk=no][no ticket] Fix merge error

ui/src/app/pages/profile/profile-component.tsx
=> [RW-11008][risk=no] Change support email on researcher profile page

ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx, ui/src/app/services/tanagra-swagger-fetch-clients.ts
Fix for Tanagra imports after the recent [submodule update](https://github.com/all-of-us/workbench/pull/7977) introduced several name changes in the Tanagra api
=> [no ticket][risk=no] Update Tanagra imports after submodule change

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
---
- Created feature flag `enableHasEhrData`
---
- [ x I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
=> [DT-538][risk=no] Feature Flag: create feature flag: enableHasEhrData

ui/src/app/pages/data/cohort/search-group-list.tsx, ui/src/app/pages/data/cohort/tree-node.tsx, ui/src/app/pages/data/cohort/utils.ts
Fixes for requests related to the OpenAPI upgrade:
- Surveys in CB broken
- Ethnicity, Gender Identity, Race and Sex Assigned At Birth in CB broken
- Add Concept Set in CB broken
- Concept Quick Add in CB is broken
- Universal Search in CB - Physical Measurement click hierarchy view causes infinite spinner
=> [DT-542][risk=no] Fixes for UI requests in CB

ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx, ui/src/app/pages/analysis/leonardo-app-launcher.tsx, ui/src/app/routing/workspace-app-routing.tsx
Tested locally by running a terminal in the UI
---
=> [risk=low][no ticket] Fix terminal by passing in a body to the API call

api/config/cdr_config_local.json, api/config/cdr_config_preprod.json, api/config/cdr_config_prod.json, api/config/cdr_config_stable.json, api/config/cdr_config_staging.json, api/config/cdr_config_test.json, api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java
Add null check in CdrDataSource.java since migrating to Tanagra will not require a CloudSQL CDR indexes.
Set cdrDbName to null in cdr_config_xxx.json files that are removed or Tanagra specific.
=> [no ticket][risk=no] null out invalid cdrs

api/config/config_preprod.json, api/config/config_stable.json, api/config/config_staging.json
I will need to apply this change manually
https://precisionmedicineinitiative.atlassian.net/browse/PD-14002
---
=> [RW-9011][risk=low] bump preprod, staging, stable docker version

api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
Add clarifying Absorb tests. This represents the existing functionality and intention, though I am open to comments regarding the correctness of that intention.
---
=> [risk=no][RW-10361] Add clarifying Absorb tests

api/src/main/resources/workbench-api.yaml
Released that I forgot to push my last commit on the last PR.
There was a small typo on the variants endpoint.
---
=> [RW-10655][risk=no] Fixed typo in workbench-api.yml

api/config/config_preprod.json, api/config/config_stable.json, api/config/config_staging.json
Use wrong python docker version in my previous PR: https://github.com/all-of-us/workbench/pull/8007/files
---
=> [RW-9011][risk=low] Fix preprod,staging, stable Terra docker version

api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java
This does not affect actual upload, but it breaks the live_table_view and verification staus
---
=> [RW-11080][risk=no] Fix table names when counting table count

.circleci/config.yml, api/build.gradle
Adding Jacoco reports to our build/reports directory.
---
=> [RW-11086][risk=no] Adding Java test coverage reports to build artifacts.

api/config/config_prod.json
Enable setting Absorb Department ID for new users in prod. Since we're re-releasing this week, I'd like to get this in now and will remove the FF entirely later. See [this thread](https://pmi-engteam.slack.com/archives/C66DX9FD0/p1697032954740819) for details.
---
=> [risk=no][RW-11077] Enable setting Absorb Department ID for new users in prod

api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, ui/src/app/pages/access/compliance-training-module-card-title.spec.tsx, ui/src/app/pages/access/compliance-training-module-card-title.tsx, ui/src/app/pages/access/identity-help-text.tsx, ui/src/app/pages/access/login-gov-help-text.tsx, ui/src/app/pages/access/modules-for-annual-renewal.tsx, ui/src/app/pages/login/sign-in.tsx, ui/src/app/utils/access-utils.tsx
Direct users to specific Absorb courses. This is a workaround since deep links appear to require support from the Absorb team. See the comments on [this ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-11074) and [this thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1696878015979769) for details. I'll ask the Absorb team about deep links this week.
This only applies when Absorb is enabled for the user.
To test this, create a new user and check the data access page. The "enabledForNewUsers" flag can be toggled to see Moodle behavior (no change).
Screenshots:
Training incomplete:
Training complete / bypassed:
---
=> [risk=no][RW-11074] Direct users to specific Absorb courses

api/config/config_preprod.json, api/config/config_stable.json, api/config/config_staging.json
PD ticket: https://precisionmedicineinitiative.atlassian.net/browse/PD-14023
I will manually apply the change
---
=> [no ticket][risk=low] upgrade Jupyter version to 2.2.4 for preprod, stable, staging

ui/package.json, ui/yarn.lock
Dependabot: https://github.com/all-of-us/workbench/security/dependabot/67
Tested by running local UI and doing some basic RWB interactions
---
=> [risk=low][no ticket] Force-bump postcss to resolve vulnerability

ui/src/app/components/side-nav.tsx, ui/src/app/pages/runtimes-list.tsx
=> [RW-11020][risk=no] "Beta" banner for Runtimes List Page

api/src/main/java/org/pmiops/workbench/ras/RasLinkConstants.java, api/src/main/java/org/pmiops/workbench/ras/RasLinkService.java, api/src/test/java/org/pmiops/workbench/ras/RasLinkServiceTest.java
Added a series of log statements that you will see after returning from RAS for identity verification. 
---
=> [RW-11143][risk=no] Added logging to identity verification.

ui/src/app/components/apps-panel/pause-resume-button.tsx, ui/src/app/components/genomics-extraction-table.tsx, ui/src/app/components/help-sidebar-icons.tsx, ui/src/app/components/icons.tsx, ui/src/app/components/status-icon.tsx, ui/src/app/pages/data/data-set/dataset-resource-card.tsx
Circle and Repeat have Free equivalents, so we can use those.  After this PR, only 4 Pro icons remain: https://docs.google.com/document/d/1X9KX_hegNrMXf-XjwZWv1-qimS-tg2xdd5q61UljWxU/edit
Also a bit of other icon cleanup.
Tested by running locally.
Pro Circle
Free Circle
Pro Repeat
Free Repeat
---
=> [risk=no][no ticket] Convert 2 FA pro icons to free

api/config/config_preprod.json, api/config/config_stable.json, api/config/config_staging.json, ui/src/app/utils/access-utils.tsx
This change has been applied manually last week. 
https://precisionmedicineinitiative.atlassian.net/browse/PD-14023
---
=> [RW-10951][risk=low]Upgrade docker image to 2.2.4 for preprod staging and stable

ui/src/app/pages/data/cohort/custom-funnel.tsx
- Ignore search groups that have no active items
- Generate group names at funnel init to fix incorrect names when groups are deleted
=> [DT-546][risk=no] Fix funnel plot issues

api/config/config_local.json, api/config/config_test.json
Updated config for local and test environments to use credentials for RAS pre-prod environment. 
---
=> [no ticket][risk=no] Updating local and test environments to use RAS pre-prod

api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/cohort/variant-search.tsx
Add dropdown with filters to the variant search UI, only available when there are at least 2 search results.
https://github.com/all-of-us/workbench/assets/40036095/3f056d59-946b-4154-a47b-bd6866fa33d9
---
=> [DT-527][risk=no] Add filters to CB variant search UI

ui/src/app/pages/access/identity-help-text.tsx
=> [no ticket][risk=no] Fix brand spelling.

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java, ui/src/app/pages/runtimes-list.tsx
It turns out that the Cloud Environments Page Terra UI component uses labels to associate runtimes returned by Leonardo with workspaces. Without this association, the behavior of the component is degraded. This change adds the same labels when we create a runtime so this association can happen.
A similar solution should work to improve the behavior of the display of persistent disks, but that is not addressed by this change.
Tested manually by running a local UI against a local API and observing the difference. Clicking on a link to a workspace does open the correct workspace.
_Note: Any runtimes created before this PR is merged will continue to be displayed in a degraded format._
Before:
After:
---
=> [risk=no][RW-11144] Fix workspace links in Cloud Environments Page

api/build.gradle
This does not complete https://precisionmedicineinitiative.atlassian.net/browse/RW-11186 because the UI still has a reference to `swagger-codegen-cli.jar` but this does mean we can go ahead with Java/API upgrades.
Tested by running locally with no issues.
---
=> [risk=low][RW-11186] Remove Swagger 2 references from build.gradle

e2e/yarn.lock, e2ev2/yarn.lock, ui/src/terraui/yarn.lock, ui/yarn.lock
Do a minor-version upgrade for the family of "babel" packages.  No functionality is expected to change.
- UI
- TerraUI
- e2e
- e2ev2
Tested by basic Local usage of the app
---
=> [risk=low][no ticket] Rev babel-family packages to latest 7x

ui/src/app/pages/access/identity-help-text.tsx
Updated wording for identity verification help text.
Under [Login.gov](http://login.gov/), changed “For U.S. residents only” to “For U.S. residents and U.S. citizens”
under [ID.me](http://id.me/), changed to “For all users”
Previous:
Current:
---
=> [RW-11188][risk=no] Updated help desk wording.

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java, api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/model/DbUser.java, api/src/main/java/org/pmiops/workbench/exfiltration/ExfiltrationUtils.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressSumologicRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressSumologicJiraHandler.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoAppUtils.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingSnapshotServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/LeonardoAppUsageColumnValueExtractor.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java, api/src/test/java/org/pmiops/workbench/exfiltration/ExfiltrationUtilsTest.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoAppUtilsTest.java, api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java, ui/src/app/utils/access-utils.tsx
=> [RW-10825][risk=low] Support export Terra Warehouse table into AoU reporting for app usage tracking

api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java, ui/src/app/pages/data/cohort/variant-search.spec.tsx, ui/src/app/pages/data/cohort/variant-search.tsx, ui/src/app/pages/data/criteria-search.tsx
fixing participant count to sort desc
=> [no ticket][risk=no] fixing participant count to sort desc

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/integration/java/org/pmiops/workbench/AbsorbAcceptanceTest.java, api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java
=> [risk=no][no ticket] Add Absorb prod config

api/.swagger3-codegen-ignore
=> [risk=no][RW-10034] Uncomment line to make it active

ui/src/app/components/icons.tsx, ui/src/app/components/notification-banner.tsx, ui/src/app/components/resource-list.tsx, ui/src/app/pages/signed-in/access-renewal-notification.spec.tsx, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/app/pages/workspace/workspace-card.tsx
1. Notification Banners: change uses of "Alarm Exclamation" to "Exclamation Triangle"
Before:
After:
2. Locked workspaces - change "Lock Alt" to "Lock"
Before:
After:
---
=> [risk=low][no ticket] Replace 2 FontAwesome Pro icons with Free alternatives

deploy/libproject/deploy.rb, ui/libproject/devstart.rb
fixing tanagra deploy to test
---
=> [no ticket][risk=no] fixing tanagra deploy to test

api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/cohort/cohort-resource-card.tsx, ui/src/app/pages/data/concept/concept-set-resource-card.tsx
Fixing bug per ticket: https://precisionmedicineinitiative.atlassian.net/browse/DT-569
---
=> [DT-569][risk=no] fixing bug

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
adding has_ehr_data to new location in menu
---
=> [DT-570][risk=no] adding has_ehr_data to new location in menu

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
fixing vat table menu item
---
=> [no ticket][risk=no] fixing vat table menu item

ui/src/app/icons/edit.spec.tsx, ui/src/app/icons/scroll.spec.tsx, ui/src/app/pages/data/cohort/tree-node.spec.tsx
Converted a few Enzyme tests to RTL.
---
=> [RW-11184][risk=no]Converted a few Enzyme tests

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json
Updating DUCC version for the higher environments.
Local and test done here: 
https://github.com/all-of-us/workbench/pull/8026
https://github.com/all-of-us/workbench/pull/8075
---
=> [RW-11161][risk=no] Update DUCC in higher environments.

api/config/config_preprod.json, api/config/config_prod.json
Enable Absorb for new users in prod.
---
=> [risk=no][RW-10906] Enable Absorb for new users in prod

ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/runtime-configuration-panel.tsx, ui/src/app/components/runtime-configuration-panel/create-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel/create-panel.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel-footer.spec.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel-footer.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel.tsx, ui/src/app/components/runtime-configuration-panel/disk-selector.tsx, ui/src/app/utils/runtime-utils.tsx, ui/src/testing/react-test-helpers.tsx
Also add new RTL tests for these components.
Tested locally by interacting with the runtime config panel through various paths 
---
=> [risk=low][RW-10991] Extract a CustomizePanel + footer from Runtime Config Panel

ui/src/app/components/runtime-configuration-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel.tsx, ui/src/app/utils/runtime-utils.tsx
No expected functional changes, just inlining a confusing function.  Tested locally.
---
=> [risk=low][RW-10991] Remove the vague concept of "actionable" from runtime logic

.circleci/config.yml, ui/.npmrc, ui/README.md, ui/libproject/devstart.rb, ui/src/circle-build.sh, ui/yarn.lock
I was able to build the UI locally after a full clean (including rm node_modules).  Running Local UI+API did not have any obvious problems.
---
=> [risk=low][no ticket] Remove all npmrc / Font Awesome logic from UI builds

api/libproject/devstart.rb, ui/libproject/devstart.rb
=> [no ticket][risk=no] fixing local tanagra deploy

api/config/config_staging.json
Enable the use of SAS in the Staging environment
---
=> [risk=low][no ticket] Enable SAS in Staging

deploy/Dockerfile, ui/app.yaml
Deploy a Node 18 artifact for the UI.
Tested by running
```
deploy/project.rb deploy \
--account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
--no-promote --git-version joel/node-18 --app-version joeltest3
```
and observing that a Node 18 image is deployed.
Clicking this link shows the expected UI.
---
=> [risk=low][RW-10556] Use the Node 18 GAE runtime for the UI

api/src/main/java/org/pmiops/workbench/ras/RasLinkService.java, ui/src/app/pages/access/data-access-requirements.spec.tsx, ui/src/app/pages/access/data-access-requirements.tsx, ui/src/app/utils/errors.spec.tsx
Updated identity verification error reporting to be more informative:
---
=> [RW-11284][risk=no] Update Identity Verification Error Modal

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/api/DataSetController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java, ui/libproject/devstart.rb, ui/src/app/pages/data/cohort/utils.ts, ui/src/app/pages/data/data-set/dataset-page.spec.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx
Removing has ehr data from dataset builder. Backing out all changes from this PR: https://github.com/all-of-us/workbench/pull/8017
---
=> [DT-617][risk=no] removing has ehr data from dataset builder

ui/src/app/pages/workspace/workspace-about.spec.tsx, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/testing/stubs/workspaces.tsx
=> [no ticket][risk=no] Display cloud info in workspace about page

ui/package.json
Remove coverage from stdout wen testing from terminal.
---
=> [no ticket][risk=no] Remove noisy coverage report from stdout.

ui/src/app/config/app-config.tsx, ui/src/app/pages/signed-in/inactivity-modal.spec.tsx, ui/src/app/pages/signed-in/inactivity-modal.tsx, ui/src/app/pages/signed-in/inactivity-monitor.spec.tsx, ui/src/app/pages/signed-in/inactivity-monitor.tsx, ui/src/app/pages/signed-in/signed-in.tsx, ui/src/app/utils/index.tsx
Fix the double sign in bug.
**I highly recommend reviewing this PR commit-by-commit.** All but the last commit are refactors to improve understandability and testability that I introduced until I found the root cause.
To manually test this, you must set `inactivityTimeoutSeconds` and `inactivityWarningBeforeSeconds` to smaller amounts in your UI settings. See the Jira ticket for steps to reproduce.
I think this PR is a net positive in test coverage for automatic session timeouts. However, I found it difficult to create a test for this bug because the component was not designed to be tested. I have introduced tests for the modal but this required significant refactoring to achieve. While I would like to, and typically would, add tests for the entire component, I think that's out scope to …
=> [risk=low][RW-9488] Fix double sign in bug

api/src/main/java/org/pmiops/workbench/api/RuntimeController.java, api/src/main/java/org/pmiops/workbench/exceptions/ExceptionAdvice.java
~9000 errors and I suspect those are caused by the same error. Add more logs to debug
---
=> [RW-11134][risk=no] Log 400 error and print more logs for conflict PD

ui/src/app/pages/workspace/workspace-about.spec.tsx, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/testing/stubs/workspaces.tsx
=> [no ticket][risk=low]: Display workspace namespace in workspace about page

ui/src/app/pages/signed-in/inactivity-modal.spec.tsx, ui/src/app/pages/signed-in/inactivity-modal.tsx, ui/src/app/pages/signed-in/inactivity-monitor.tsx
This is a follow-up to https://github.com/all-of-us/workbench/pull/8135#discussion_r1391387343.
---
=> [risk=no][no ticket] Inline inactivityWarningBeforeMs

api/config/config_preprod.json, api/config/config_stable.json
=> [no ticket][risk=low] Enable SAS in stable and preprod

e2e/package.json, e2e/yarn.lock
Similar to #8109
Resolves https://github.com/all-of-us/workbench/security/dependabot/73
---
=> [risk=low][no ticket] Force e2e axios to 1.6.0+

e2ev2/package.json, e2ev2/yarn.lock
=> [risk=low][no ticket] Upgrade everything in e2ev2 to latest

ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/runtime-configuration-panel.tsx, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/analysis/leonardo-app-launcher.tsx, ui/src/app/utils/runtime-hooks.tsx, ui/src/app/utils/runtime-utils.spec.tsx, ui/src/app/utils/runtime-utils.tsx
Tests for most of runtime-utils... after splitting off hooks and associated functions to a new runtime-hooks file.  Continues #8143
No functional changes expected.
---
=> [risk=low][RW-10991] Runtime-utils unit tests

ui/src/app/pages/admin/user/admin-user-common.tsx, ui/src/app/pages/login/account-creation/account-creation-institution.spec.tsx, ui/src/app/pages/login/account-creation/account-creation-institution.tsx, ui/src/app/pages/login/account-creation/account-creation-options.tsx, ui/src/app/pages/profile/profile-component.tsx, ui/src/app/utils/institutions.tsx
=> [RW-10383][risk=no] UI: Update Institutional Role User Selection

ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx
---
- prefix underlay name with "aou" in tanagra-call to create a `cohort` in tanagra-enabled-workspace
**test**
- Creating a new workspace in tanagra enabled cdr 
- Click on `+` to add new cohort
- Saving the new cohort should not display an error
---
=> [No-Ticket\[risk=no] prefix underlay name with "aou" in tanagra-call to create a cohort

ui/src/app/components/runtime-configuration-panel.tsx, ui/src/app/components/runtime-configuration-panel/create-panel.spec.tsx, ui/src/app/components/runtime-configuration-panel/create-panel.tsx
Tested locally by creating a runtime
Create-Panel in context
---
=> [risk=low][RW-10991] Move some components into create-panel

e2ev2/tests/user-create.test.js, ui/src/app/components/inputs.tsx, ui/src/app/pages/login/account-creation/account-creation-institution.tsx
=> [noTicket][risk=low]Fix e2ev2: institution select

api/config/featured_workspaces_prod.json
=> [RW-11335][risk=no] Add demo workspace

api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java, api/src/main/resources/workbench-api.yaml
We removed the last UI reference to this in August.
Tested locally by doing some workspace operations.
---
=> [risk=no][no ticket] rm unused markResearchPurposeReviewed()

api/db-cdr/generate-cdr/build-search-all-events.sh
=> [no ticket][risk=no] fixing survey concept id

api/config/featured_workspaces_prod.json
Published the wrong demo project in #8157. Correcting to project requested in https://precisionmedicineinitiative.atlassian.net/browse/RW-11335
---
=> [RW-11335][risk=no] Corrected incorrect demo project.

ui/package.json, ui/src/index.ts, ui/yarn.lock
Bump `@types/enzyme` to latest - includes #8185 
Bump `@types/lodash` to latest - includes #8191 
Bump `react-modal` to latest - includes #8192 
Bump `validate.js` to latest - includes #8180
Remove unused `@webcomponents/custom-elements` instead of upgrading (#8179)
Tested react-modal by interacting with a modal, which worked normally.
Tested validate.js by interacting with a form which uses validation.  this worked normally.
---
=> [risk=low][no ticket] Upgrade some UI packages and remove unused custom-elements

api/build.gradle
Upgrade bouncycastle to latest to resolve a vulnerability.
Upgrade logback-classic to the latest 1.2.x to resolve a vulnerability.
Tested locally with no obvious problems
---
=> [risk=low][no ticket] Upgrade bouncycastle and logback

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, tanagra-aou-utils/tanagra-ui.yaml, ui/app.yaml, ui/libproject/devstart.rb, ui/package.json, ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-dev.tsx, ui/src/app/routing/app-routing.tsx, ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/test-env-base.ts, ui/src/testing/default-server-config.ts
- Update UI deploy file for new path
- Update base url properties with current domain. Also removed UI env flag and only use config flag.
=> [no ticket][risk=no] Tanagra deploy updates

ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx, ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts, ui/src/environments/test-env-base.ts
Add UI env flag to determine how to pass the auth token for Tanagra. If `true` (local env), pass in iframe url, otherwise set in `localStorage`.
=> [no ticket][risk=no] Add env flag for tanagra token

ui/src/app/pages/data/cohort/overview.tsx, ui/src/app/utils/analytics.ts
Add Google Analytics tracking to funnel plot in CB
=> [DT-661][risk=no] Add GA event to CB funnel plot

api/config/cdr_config_preprod.json
bumping cloudsql cdr with variant search
---
=> [DT-560][risk=no] bumping cloudsql cdr with variant search

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml
Removing enableHasEhrData flag
---
=> [DT-540][risk=no] removing enableHasEhrData flag

ui/src/app/components/apps-panel/expanded-app.spec.tsx, ui/src/app/components/apps-panel/expanded-app.tsx, ui/src/app/components/apps-panel/utils.tsx, ui/src/app/pages/analysis/gke-app-launcher.spec.tsx, ui/src/app/pages/analysis/interactive-notebook.spec.tsx, ui/src/app/pages/analysis/interactive-notebook.tsx, ui/src/app/pages/appAnalysis/app-selector.tsx, ui/src/app/routing/guards.spec.tsx, ui/src/app/utils/user-apps-utils.spec.tsx, ui/src/app/utils/user-apps-utils.tsx
All functionality works similar to that of RStudio
https://github.com/all-of-us/workbench/assets/34481816/38c8ff90-c6d4-47e8-87e6-ee5c4d776ce3
---
=> [RW-9664][risk=no] [UI][pre-prod] Open RStudio & SAS in AoU iframe to avoid timeouts  <- For SAS

api/db-cdr/generate-cdr/build-cb-variant-attribute-table.sh
=> [DT-668][risk=no] adding fix for variant counts

ui/src/app/pages/data/data-set/export-dataset-modal.spec.tsx, ui/src/app/pages/data/data-set/export-dataset-modal.tsx
=> [RW-10323][risk=no] Converted Export Dataset Tests from Enzyme to RTL

ui/src/app/pages/data/cohort/cohort-criteria-menu.tsx, ui/src/app/pages/data/cohort/cohort-search.tsx, ui/src/app/pages/data/cohort/overview.tsx, ui/src/app/pages/data/cohort/search-group.tsx
- Hide 'Has Any EHR Data' option in CB criteria menu if temporal is enabled for the search group
- Also set a default value of 1 for temporal number inputs
=> [DT-639][DT-642][risk=no] Hide has any ehr data option for temporal groups

ci/Dockerfile.circle_build, deploy/Dockerfile, ui/src/deps/deps.sh
Address the openapi tooling workaround described in [this thread](https://pmi-engteam.slack.com/archives/C0189PPPKFF/p1694032310063459).
This PR is split from https://github.com/all-of-us/workbench/pull/8224. Relevant comments have been copied over.
I validated this as part of https://github.com/all-of-us/workbench/pull/8224 in CircleCI. However, a non-Verily engineer should be able to validate this by simply running the deploy script. The expected behavior is that the script continues working.
---
=> [risk=no][RW-11491] Address openapi tooling workaround

.circleci/config.yml, api/build.gradle, api/src/main/webapp/WEB-INF/appengine-web.xml.template, ci/Dockerfile.circle_build, deploy/Dockerfile
Tested by deploying a java 17 runtime to GAE in the Test environment and observing no problems when routing traffic to it.
If you want to deploy a version yourself, you can run:
```
deploy/project.rb deploy \
--account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
--no-promote \
--git-version joel/java17 \
--app-version <a version ID you choose>
```
---
=> [risk=low][RW-11368] Upgrade Java to 17

api/docs/developer-system-initialization.md, api/docs/developer-system-requirements.md
=> [risk=no][RW-11368] Update dev docs to reflect Java 17

api/db/changelog/db.changelog-228-increase-resource-name-size.xml, api/db/changelog/db.changelog-master.xml, ui/src/app/components/copy-modal.tsx, ui/src/app/components/create-modal.tsx, ui/src/app/pages/data/cohort-review/cohort-review-resource-card.tsx, ui/src/app/pages/data/cohort/cohort-resource-card.tsx, ui/src/app/pages/data/cohort/overview.tsx, ui/src/app/pages/data/data-set/dataset-page.tsx, ui/src/app/utils/resources.tsx
- Increase char limit for names of non-notebook resources from 80 to 800 chars to avoid db error
- Make UI validation consistent for creating, renaming and duplicating resources
- Fix request for renaming cohort reviews
=> [DT-662][risk=no] Fix name validation for resources

ui/src/app/components/runtime-configuration-panel/disk-size-selector.tsx, ui/yarn.lock
Something is not making sense to me, re: our nightly test failures.  The purpose of this PR is just to force a cache miss by updating yarn.lock, and force an e2e run by updating a UI file.
---
=> [risk=low][no ticket] Trivial changes to trigger e2e runs and force circle cache misses

ui/src/app/components/common-env-conf-panels/styles.tsx, ui/src/app/components/runtime-configuration-panel/disk-size-selector.tsx
=> [risk=low][no ticket] Fix disk size styling

api/config/config_prod.json
=> [RW-10951][risk=low] Upgrade Jupyter image version for prod

ui/src/app/pages/data/cohort/variant-search.tsx
- Only call `findVariantFilters` for new filters when searching with new terms
- Fix min/max issue with allele sliders
---
=> [DT-692][DT-693][risk=no] Variant search fixes

api/config/featured_workspaces_prod.json
Per request from: https://precisionmedicineinitiative.atlassian.net/browse/RW-11553
---
=> [RW-11553][risk=low] publish new workspace into prod

api/config/cdr_config_preprod.json
=> [DT-624][risk=no] bumping cdr index for v6 CT

ui/src/app/pages/workspace/workspace-about.spec.tsx
=> [no ticket][risk=no] Fix copy-paste typo in ui unit test

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/ProfileController.java, api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingService.java, api/src/main/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceImpl.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/compliancetraining/ComplianceTrainingServiceTest.java, ui/src/app/pages/access/compliance-training-module-card-title.spec.tsx, ui/src/app/pages/access/compliance-training-module-card-title.tsx, ui/src/app/pages/access/module.spec.tsx, ui/src/app/pages/access/module.tsx, ui/src/testing/stubs/profile-api-stub.ts
Adds a feature flag that, when enabled, disables the training access module for users who were using Moodle.
This does not add the banner described in the AC. @NehaBroad is currently working on this.
This can be manually tested by enabling the feature flag and visiting the data access page for a user who (1) previously used Moodle and (2) has an incomplete training access module.
[Relevant workbench-ux thread](https://pmi-engteam.slack.com/archives/C02MWP2RN5P/p1704481942682759)
Because this introduces a new feature flag, I've added [a Jira ticket](https://precisionmedicineinitiative.atlassian.net/browse/RW-11652) to remove it.
Screenshot:
---
=> [risk=no][RW-11529] Disable training during the LMS migration

api/build.gradle
Run `./gradlew reportLibyears` to see the [libyear](https://libyear.com/) report for the API.
The UI equivalent is #8291
---
=> [risk=no][no ticket] Add the libyears gradle plugin

ui/src/app/components/resource-actions-menu.tsx, ui/src/app/pages/analysis/notebook-action-menu.tsx, ui/src/app/pages/appAnalysis/apps-file-list.spec.tsx
In addition to converting from Enzyme to RTL, I also added a title to notebook action menu button for accessibility and testability.
---
=> [RW-9168][risk=no] Converted apps-file-list tests to RTL.

ui/src/app/pages/data/cohort/cohort-search.tsx, ui/src/app/pages/data/cohort/selection-list.tsx, ui/src/app/pages/data/cohort/tree.tsx, ui/src/app/pages/data/cohort/variant-search.tsx, ui/src/app/pages/data/criteria-search.tsx
- Fix alignment for back arrow icons
Before:
After:
- Fix height for small screens so variant results aren't hidden
-Before:
After:
---
=> [DT-696][risk=no] Fix icon position, min height for CB variant search

ui/package.json, ui/yarn.lock
We don't use this package, so we can remove it!  Tested locally anyway - no problems.
---
=> [risk=no][no ticket] Remove unused UI package 'classnames'

ui/package.json, ui/yarn.lock
Tested locally by verifying that these directories are generated identically to the previous version:
* ui/src/generated
* ui/src/notebooks-generated
* ui/src/tanagra-generated
I also ran the local UI with no obvious problems.
---
=> [risk=low][no ticket] Bump openapi-generator-cli to latest

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoCustomEnvVarUtils.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
us-central1-docker.pkg.dev/{projectId}/aou-rw-gar-remote-repo-docker-{env}
---
=> [no ticket][risk=no] Add new env variable for GAR repos

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
The changes are already pushed to PROD using the update config script (https://precisionmedicineinitiative.atlassian.net/browse/PD-14680)
---
=> [RW-11529 ][risk=no]  Disable Moodle training module before migration

deploy/libproject/deploy.rb
I ran the deploy command AFter removing /tmp/colima
@evrii  also ran the deploy scrip with this change to deploy to preprod
---
=> [noTicket][risk=low] Fix deploy script to use colima

api/config/config_local.json, api/config/config_test.json, api/libproject/environments.rb, api/src/main/webapp/static/README.md, api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java, e2e/resources/workbench-config.ts, ui/app.yaml, ui/src/environments/test-env-base.ts
Update url references in test for custom domain:
- Change frontend urls from `https://all-of-us-workbench-test.appspot.com` to `https://test.fake-research-aou.org`
- Change api urls from `https://api-dot-all-of-us-workbench-test.appspot.com` to `https://api.test.fake-research-aou.org`
=> [DT-665][risk=no] Update test env url refs

ui/src/app/pages/appAnalysis/app-files-list.tsx
The apps list now polls waiting for the file transfer to complete, and it displays the file list when done.
There are some flaws to this approach, but I think this is an improvement in its current state and therefore worth merging.  Let's discuss whether we need to go further to call the story DONE.
Problems:
* continues polling after the user navigates to a different tab
* adds another polling loop if the user returns to the analysis tab
Tested by duplicating workspaces.  Some of them transfer the files instantly, so the "copying" screen does not appear.  (This screen also does not appear for older workspaces and non-duplicated workspaces.)  When the screen does appear, it eventually goes away and is replaced by the normal analysis tab.  However, this time is quite unpredictable.
I …
=> [risk=low][RW-11689] Add polling to apps-list waiting for transfer

ui/package.json, ui/yarn.lock
No functional changes expected. I have confirmed that all existing tests continue to pass, and I can detect no changes in the UI.
---
=> [risk=low][no ticket] Bump typescript to latest 5.3.3

.circleci/config.yml, api/src/contracttest/java/org/pmiops/workbench/consumer/RuntimesApiTest.java
=> [RW-11654][risk=no]First pass at contract test for getting a runtime.

ui/src/app/utils/zendesk.ts
It should be an article, not a section
---
=> [RW-11792] [risk=no]: Fix support article typo. section -> article 

api/src/main/java/org/pmiops/workbench/cdr/CdrDataSource.java
dev-up and a test deploy worked without issues
---
=> [risk=low][no ticket] Remove unneeded PoolConfigurations

aou-utils/serviceaccounts.rb
Copied from https://github.com/all-of-us/workbench/blob/43aba8f424344588b49c983d3587168a0fe6bbe4/deploy/libproject/deploy.rb#L107
It works for colima 
---
=> [no ticket][risk=no] Fix sqlproxy connection when running colima

api/src/main/webapp/WEB-INF/cron_base.yaml, api/src/main/webapp/WEB-INF/cron_test.yaml
We have successfully run the `checkFreeTierBillingUsageCloudTask` job  in the test environment for an extended duration. Based on the performance metrics and observations, we feel that the latest version is ready for deployment to replace the existing cron job.
**Changes Introduced:**
In this PR, we are focusing on updating the `cron.yaml` file to run latest version of the cron job `/v1/cron/checkFreeTierBillingUsageCloudTask` every 30 minutes. It's important to note that the code related to `/v1/cron/checkFreeTierBillingUsage` remains unchanged during this update.
**Next Steps:**
Following the deployment of this PR, the plan is to keep track of the new cron job (`/v1/cron/checkFreeTierBillingUsageCloudTask`) in the production environment for a period of at least a couple of weeks. Once …
=> [RW-10627]  [P1] Free tier billing usage cron job starts failing recently due to timeout

e2ev2/yarn.lock, ui/src/environments/environment-type.ts
Resolves https://github.com/all-of-us/workbench/security/dependabot/77 by removing the package entirely.
---
=> [risk=low][no ticket] Resolve vulnerability in `ip` by upgrading its referents

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
=> [no ticket][risk=no] fixing unnest issue

ui/src/app/utils/access-utils.tsx
Updated User Admin page to say "Verify your Identity" instead of "Verify your identity with Login.gov" since identity is a single login module now.
Old 
New
---
=> [no ticket][risk=no] Update access module label on User admin page.

.circleci/config.yml
=> [no ticket][risk=no] Changing to pre-breaking change.

api/db-cdr/generate-cdr/tanagra-stage-redcap-files.py, api/libproject/devstart.rb
adding command to load redcap files into BQ
=> [DT-742][risk=no] adding command to load redcap files into BQ

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/main/resources/leonardo.yaml, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
=> [RW-11933][risk=low] API support autodelete

ui/src/app/pages/appAnalysis/app-files-list.tsx
=> [RW-11954][risk=no] Increase default notebook number to 10 and add options

e2e/package.json, e2e/yarn.lock, ui/src/environments/environment-type.ts
Resolves vulnerability https://github.com/all-of-us/workbench/security/dependabot/78
No expected changes.  If e2e tests pass, we can merge.
---
=> [risk=low][no ticket] Update axios for e2e

ui/src/app/components/runtime-configuration-panel/persistent-disk-selector.tsx
PD is the only option now/ 
---
=> [no ticket][risk=no] remove outdated warning

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
=> [RW-11933][risk=no] Fix an issue with autodelete on API and add tests

ui/src/app/components/gke-app-configuration-panels/create-cromwell.tsx, ui/src/app/components/gke-app-configuration-panels/create-rstudio.tsx, ui/src/app/utils/aou_external_links.tsx, ui/src/app/utils/zendesk.ts
Added support articles to RStudio tab.
---
=> [RW-11588][risk=no] Added support articles to RStudio tab.

e2e/app/page/workspace-analysis-page.ts
Fix for nightly [egress-suspension.spec.ts failure](https://app.circleci.com/pipelines/github/all-of-us/workbench/31358/workflows/ceb79de3-c68b-44e0-84f1-57ec767cf9b3/jobs/335149/tests)
=> [RW-11966][risk=no] Fix option select for Analysis app dropdown

api/build.gradle
No expected changes.  Tested locally by interacting with the UI a bit.
---
=> [risk=low][RW-11847] Update a few more Spring Boot dependencies

ui/src/app/pages/admin/workspace/cloud-environments-table.tsx, ui/src/app/pages/admin/workspace/disks-table.spec.tsx, ui/src/app/pages/admin/workspace/disks-table.tsx
=> [risk=low][no ticket] Add tooltip to admin-workspace to show that rm runtime doesn't rm the disk

api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, ui/src/app/pages/access/module.tsx, ui/src/app/pages/access/modules-for-annual-renewal.tsx, ui/src/app/pages/signed-in/access-renewal-notification.tsx, ui/src/app/utils/access-utils.tsx, ui/src/testing/stubs/profile-api-stub.ts
A few things I thought of after looking at #8363 
Tested by viewing the DAR and AAR pages
---
=> [risk=low][no ticket] Some module UI refactoring ideas

api/config/featured_workspaces_prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-11989
---
=> [RW-11989][risk=no] publish a new new feature workspace

api/config/config_prod.json, api/config/config_stable.json, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts
=> [RW-9645][risk=no] Enable RStudio in prod

api/config/config_prod.json, api/config/config_stable.json, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts
Reverts all-of-us/workbench#8388
=> [RW-9645][risk=no] Disable RStudio in prod"

.circleci/config.yml
Benefits:
* Decreases the time of the actual test runs
* Linting errors are distinguishable from test errors
* Linting errors are visible more quickly
---
=> [risk=low][no ticket] Lint in PRs in parallel with unit tests

api/config/config_test.json, api/src/main/java/org/pmiops/workbench/exfiltration/EgressRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressObjectLengthsRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressSumologicRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressSumologicJiraHandler.java, api/src/main/java/org/pmiops/workbench/mail/MailService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/egress_remediation/content.html, api/src/test/java/org/pmiops/workbench/exfiltration/EgressRemediationServiceTest.java, api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java
Email looks like this but with <b></b> around
---
=> [RW-11996][risk=low] improve egress email text

api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java
removing code that was making temporal query inefficient
=> [DT-750][risk=no] removing code that was making temporal query inefficient

ui/src/app/components/confirm-workspace-delete-modal.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/workspace/workspace-card.tsx
Uploading Screen Recording 2024-02-29 at 11.03.36 AM.mov…
---
=> [RW-11972][risk=low] Skip running app checking when deleting workspace. 

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/exfiltration/EgressEventServiceImpl.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressSumologicRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/jirahandler/EgressSumologicJiraHandler.java, api/src/main/java/org/pmiops/workbench/mail/MailService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
Java best practice is to avoid calling `Optional.get()` wherever possible, to avoid Null Pointer Exceptions.  These calls to `.get()` are not necessary.
---
=> [risk=low][no ticket] Stop calling appServiceNameToAppType().get()

api/src/contracttest/java/org/pmiops/workbench/consumer/RuntimesApiTest.java
=> [RW-11654][risk=no] Linting

ui/src/app/components/confirm-workspace-delete-modal.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/workspace/workspace-card.tsx
Reverts all-of-us/workbench#8396
There is an issue in Terra that make may this not working
=> Revert "[RW-11972][risk=low] Skip running app checking when deleting workspace. "

api/config/config_prod.json, api/config/config_stable.json, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts
Reverts all-of-us/workbench#8392
=> [RW-9645][risk=no] Reenale RStudio in prod

ui/src/app/components/rename-modal.spec.tsx, ui/src/app/components/rename-modal.tsx
=> [risk=no][RW-11329] PR comments

ui/src/app/pages/data/cohort/modifier-page.tsx, ui/src/app/pages/data/cohort/search-group-item.tsx, ui/src/app/pages/data/cohort/search-group.tsx, ui/src/app/pages/data/cohort/selection-list.tsx
- Remove modifiers button from variant search
- Remove 'Number Of Occurrence Dates' dropdown in temporal groups
- Disable temporal toggle if 'Number Of Occurrence Dates' modifier is already set
=> [DT-787][risk=no] CB updates for modifiers, temporal

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
adding submenu for genomics in CB.
---
=> [DT-772][risk=no] adding submenu for genomics

api/src/main/java/org/pmiops/workbench/cohortbuilder/CohortBuilderServiceImpl.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java, api/src/test/java/org/pmiops/workbench/dataset/DataSetServiceTest.java
some code cleanup before starting:
- Replacing `.collect(Collectors.toList())` with `.toList()`
- Taking advantage of text blocks
---
=> [DT-774][risk=no] some code cleanup before starting

ui/src/app/components/common-env-conf-panels/environment-cost-estimator.spec.tsx, ui/src/app/components/common-env-conf-panels/environment-cost-estimator.tsx, ui/src/app/components/gke-app-configuration-panels/create-cromwell.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-rstudio.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-sas.spec.tsx
=> [risk=no][RW-12034] [UI] Remove cost when paused from GKE apps

ui/src/app/components/common-env-conf-panels/support-note-section.tsx, ui/src/app/components/gke-app-configuration-panels/create-cromwell.tsx, ui/src/app/components/gke-app-configuration-panels/create-rstudio.tsx, ui/src/app/components/gke-app-configuration-panels/create-sas.tsx, ui/src/app/utils/aou_external_links.tsx, ui/src/app/utils/zendesk.ts
Adding links for SAS and 
Extracting support note section :
---
=> [RW-11668][risk=no] Link to SAS support article from SAS cloud env page

api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/dao/UserDaoTest.java
Followup to #8372 
Tested locally by modifying a user's Identity bypass status as well as a different module's bypass status.
---
=> [risk=low][no ticket] Remove unused rasLinkLoginGovBypassTime from AdminTableUser

api/src/contracttest/java/org/pmiops/workbench/consumer/AppsApiTest.java
Consolidated Create App body and added kubernetes config.
---
=> [RW-11656][risk=no] Updated App Contracts

ui/src/app/pages/data/cohort/list-search.tsx, ui/src/app/pages/data/concept/concept-add-modal.tsx, ui/src/app/pages/data/concept/concept-search.tsx
- Check all domains for name conflicts instead of just the current domain
- Clear search term state when exiting concept search
- Prevent unneeded `findCriteriaByDomain` calls that were failing with 500 errors
---
=> [DT-788][DT-789][risk=no] Concept search fixes

api/src/contracttest/java/org/pmiops/workbench/consumer/AppsApiTest.java
Added missing contract expectations.
---
=> [RW-11656][risk=no] Added missing app contract expectations

api/src/contracttest/java/org/pmiops/workbench/consumer/AppsApiTest.java, api/src/contracttest/java/org/pmiops/workbench/consumer/DisksApiTest.java, api/src/contracttest/java/org/pmiops/workbench/consumer/RuntimesApiTest.java, api/src/contracttest/java/org/pmiops/workbench/consumer/ServiceInfoApiTest.java
=> [RW-12139][risk=no] Added contracts for Leo's status endpoint.

api/build.gradle, api/libproject/devstart.rb, api/tools/src/main/java/org/pmiops/workbench/tools/FetchWorkspaceDetails.java
I'm not sure how useful this tool remains, but I tried it out while looking into an issue and I found it didn't work.  This PR restores it to functionality plus some minor improvements to bring it more in line with the current codebase.
Tested by running 
```
./project.rb fetch-workspace-details --project all-of-us-workbench-test --workspace-namespace aou-rw-test-d15fd8ee
```
---
=> [risk=low][no ticket] Fix FetchWorkspaceDetails tool

api/src/main/webapp/static/aou-file-tree-policy-extension.js
For all files with extension **.ipynb** open in iframe
for all other files show the download pop message
https://github.com/all-of-us/workbench/assets/34481816/0becb2af-f69e-410c-b543-9455b068bd01
How to Test:
- One easy way is to copy the file aou-file-tree-policy-extension.js to a public bucket using broad account (i created a new one [aou-test-jupyter-view](https://console.cloud.google.com/storage/browser/aou-test-jupyter-view;tab=objects?forceOnBucketsSortingFiltering=true&project=terra-dev-14905480)) 
- Update the path at https://github.com/all-of-us/workbench/blob/ff3fdc9edd4c205abdd85e8245281327d8de10bc/api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java#L161  to "https://storage.googleapis.com/aou-test-jupyter-view/aou-file-tree-policy-extension.js")
- …
=> [RW-12102][risk=low]  [P1] Clicking "view" in the Jupyter Notebook menu automatically downloads files that aren't notebooks

ui/public/aou-privacy-policy.html
Step 1: We will push privacy policy HTML to test 
UPDATED:
Step 2: Update google Oath to link privacy policy link from sign in tab to this HTML
https://console.cloud.google.com/apis/credentials/consent?project=all-of-us-workbench-test
**THIS PR IS JUST STEP 1**
Text is approved by Marcie/Charissa and styling approved by Joy
---
=> [RW-11993][risk=none]  Update home page text to be compliant with SSP control AC-8

.circleci/config.yml, api/build.gradle, ci/Dockerfile.circle_build, deploy/Dockerfile
Tested locally with no issues.  I also saw no problems when doing a dry-run deployment.
---
=> [risk=low][no ticket] API dev-up was no longer working for me - this fixes it

ui/src/app/pages/data/cohort/constant.ts, ui/src/app/pages/data/cohort/search-group-item.tsx, ui/src/app/pages/data/cohort/selection-list.tsx, ui/src/app/pages/data/cohort/variant-search-filters.tsx, ui/src/app/pages/data/cohort/variant-search.spec.tsx, ui/src/app/pages/data/cohort/variant-search.tsx
Add edit icon next to select all groups in selection list that when clicked, will show all variants in the main table with the option to exclude from the group.
---
=> [DT-796][risk=no] Option to exclude variants from select all group

ui/src/app/utils/user-apps-utils.tsx
=> [risk=no][noTicket] Localize file decodingURL to prevent % in fileName

api/config/config_prod.json
=> [RW-10712][risk=low] Enable SAS in prod

ui/src/app/components/combo-chart.component.spec.tsx, ui/src/app/pages/data/cohort-review/individual-participants-charts.spec.tsx, ui/src/app/pages/data/cohort/search-group-list.spec.tsx
ui/src/app/components/combo-chart.component.spec.tsx
ui/src/app/pages/data/cohort/search-group-list.spec.tsx
ui/src/app/pages/data/cohort-review/individual-participants-charts.spec.tsx
---
=> [RW-12350][risk=no] Convert three Enzyme tests

api/config/featured_workspaces_prod.json
adding sas featured workspace
---
=> [RW-12364][risk=no] adding sas featured workspace

api/build.gradle, api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/interceptors/TracingInterceptor.java, api/src/main/java/org/pmiops/workbench/opentelemetry/NoopMetricExporter.java, api/src/main/java/org/pmiops/workbench/opentelemetry/NoopSpanExporter.java, api/src/main/java/org/pmiops/workbench/opentelemetry/OpenTelemetryConfig.java, api/src/main/resources/application.properties, api/src/main/resources/swagger3codegen/aouTraceImports.mustache, api/src/main/resources/swagger3codegen/aouTracedMethodCall.mustache, api/src/main/resources/swagger3codegen/libraries/okhttp-gson/api.mustache
Reverts all-of-us/workbench#8484
=> Revert "Revert "[RW-11948][risk=low] Opencensus to OpenTelemetry""

api/config/cdr_config_prod.json
The new path exists. This PR is to update the env var pointing to it.
---
=> [risk=no][RW-12348] Update hail.mt env variable to point to the v7.1 path

ui/src/app/pages/data/cohort/overview.spec.tsx, ui/src/app/pages/data/cohort/search-group-item.spec.tsx, ui/src/app/pages/data/cohort/tree.spec.tsx, ui/src/testing/react-test-helpers.tsx
These files all have complicated logic and would be well served with more tests. However these tests replace the existing basic render tests.
---
=> [RW-12184][risk=no] Converted three Enzyme tests.

ui/src/app/pages/admin/egress-events-table.spec.tsx
Converted Egress Event Table test from Enzyme to RTL.
---
=> [RW-12352][risk=no] Converted Egress Event Table Test

ui/src/app/components/data-set-reference-modal.spec.tsx, ui/src/app/components/modals.spec.tsx, ui/src/app/pages/analysis/notebook-frame-error.spec.tsx
=> [RW-12395][risk=no] Converted three Enzyme test files to RTL

ui/src/app/components/notification-banner.tsx
=> [risk=low][no ticket] Center-justify notification button text

api/build.gradle
Tested locally with no apparent problems
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612984
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613076
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613079
---
=> [risk=low][no ticket] Bump bouncycastle to latest, to resolve vulnerabilities

ui/src/app/pages/admin/admin-egress-audit.spec.tsx, ui/src/app/pages/admin/user/admin-user-egress-bypass.spec.tsx, ui/src/app/pages/admin/user/admin-user-table.spec.tsx
https://precisionmedicineinitiative.atlassian.net/browse/RW-12396
---
=> [RW-12396][risk=no] Converted admin egress audit to RTL.

ui/src/app/pages/analysis/new-jupyter-notebook-modal.spec.tsx
https://precisionmedicineinitiative.atlassian.net/browse/RW-12399
---
=> RW-12399 convert new-jupyter-notebook-modal.spec.tsx to RTL

ui/src/app/pages/data/cohort-review/annotation-definition-modals.component.spec.tsx, ui/src/app/pages/data/cohort/cohort-resource-card.spec.tsx, ui/src/app/pages/data/cohort/variant-search.spec.tsx, ui/src/app/pages/data/concept/concept-navigation-bar.spec.tsx
https://precisionmedicineinitiative.atlassian.net/browse/RW-12401
---
=> [RW-12401][risk=no] Convert some of src/app/pages/data

api/build.gradle
This is to prepare spring 3 upgrade with few minor upgrade and package cleanup. 
---
=> [RW-12412][risk=low]upgrade few API packages

ui/src/app/pages/analysis/notebook-action-menu.spec.tsx, ui/src/app/pages/homepage/homepage.spec.tsx, ui/src/app/pages/homepage/quick-tour-and-videos.spec.tsx, ui/src/app/pages/homepage/quick-tour-and-videos.tsx, ui/src/app/pages/homepage/quick-tour-modal.spec.tsx
=> RW-12399 a few more RTL conversion

ui/src/app/components/with-leo-cookie.spec.tsx, ui/src/app/components/with-new-user-satisfaction-survey-modal.spec.tsx
=> [risk=low][RW-12400] Convert 2 Enzyme tests to RTL

api/config/featured_workspaces_preprod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-12465
---
=> [RW-12465][risk=no] Publish new feature workspace in preprod

ui/src/app/components/inputs.spec.tsx, ui/src/app/components/inputs.tsx, ui/src/app/components/new-user-satisfaction-survey-modal.spec.tsx
=> [risk=low][RW-12400] Convert 2 more Enzyme tests to RTL

api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java
=> fix DUCC unit test for Spring Boot 3 upgrade branch

ui/src/app/components/copy-modal.spec.tsx, ui/src/app/components/system-error-handler.spec.tsx
A big one (copy-modal) and a small one (system-error-handler)
---
=> [risk=low][RW-12400] 2 enzyme test conversions

ui/src/app/pages/data/cohort/selection-list.tsx, ui/src/app/pages/data/cohort/utils.ts, ui/src/app/pages/data/cohort/variant-search.tsx
- Fix condition that disables save button for exclusions when no exclusions have been added
- Disable the Save Criteria button when editing a select all group
=> [DT-812][risk=no] CB select all fixes

ui/src/app/pages/workspace/workspace-edit.spec.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
ACL delay code was artifact of an older time (SATURN-104). This code is no longer necessary. 
I created a workspace locally to verify that all is working as expected.
---
=> [RW-12440][risk=no] Removed ACL Delay Code.

ui/src/app/components/confirm-workspace-delete-modal.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/workspace/workspace-card.tsx
Reverts all-of-us/workbench#8428
=> RW-12555 Revert "[risk=low] RW-12040 Allow workspace deletion"

api/config/featured_workspaces_prod.json
#8536 was missing the last letter of the namespace
---
=> [risk=low][RW-12445] Fix typo in featured workspace config

api/db-cdr/generate-cdr/build-cb-criteria-menu.sh
fixing bug in indexing script
---
=> [DT-811][risk=no] fixing bug in indexing script

ui/src/app/components/apps-panel/utils.tsx, ui/src/app/components/gke-app-configuration-panel.tsx, ui/src/app/components/gke-app-configuration-panels/create-cromwell.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app-button.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx, ui/src/app/components/gke-app-configuration-panels/create-rstudio.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-sas.spec.tsx, ui/src/app/components/gke-app-configuration-panels/disabled-cloud-compute-profile.spec.tsx, ui/src/app/components/gke-app-configuration-panels/disabled-cloud-compute-profile.tsx, ui/src/app/utils/strings.spec.tsx, ui/src/app/utils/strings.ts
Add a note for GKE Apps: the RAM and CPU will be shared with other GKE Apps.
---
=> [risk=low][RW-9605] Add CPU/RAM sharing note to machine configuration for User Apps

api/config/cdr_config_test.json
=> [no-ticket][risk=no] bumping test cdr

ui/src/app/components/data-user-code-of-conduct.spec.tsx
=> [RW-12543][risk=no] Remove DUCC iframe tests

ui/src/app/pages/admin/workspace/filename-cell.spec.tsx, ui/src/app/pages/admin/workspace/filename-cell.tsx
=> [risk=low][no ticket] Enable preview of RStudio and SAS files in Admin Workspace

ui/src/app/components/resources/resource-list.spec.tsx, ui/src/app/pages/admin/user/admin-user-bypass.spec.tsx, ui/src/app/pages/admin/user/admin-user-bypass.tsx, ui/src/app/pages/data/cohort-review/sidebar-content.component.spec.tsx, ui/src/app/pages/data/cohort/modifier-page.spec.tsx, ui/src/app/pages/data/cohort/search-group.spec.tsx, ui/src/app/pages/data/concept/concept-homepage.spec.tsx, ui/src/app/pages/data/concept/concept-homepage.tsx, ui/src/app/pages/homepage/recent-resources.spec.tsx, ui/src/app/pages/profile/data-access-panel.spec.tsx, ui/src/app/pages/signed-in/inactivity-monitor.spec.tsx
=> [RW-12579][risk=no] Converted a few tests to RTL.

api/db-cdr/generate-cdr/build-tanagra-static-prep-tables.sh, api/db-cdr/generate-cdr/create-tanagra-prep-tables.sh, api/libproject/devstart.rb
adding commands for tanagra prep tables
---
=> [DT-741][risk=no] adding commands for tanagra prep tables

api/libproject/devstart.rb
fixing bug in tanagra prep tables command
=> [DT-741][risk=no] fixing bug in tanagra prep tables command

api/tools/src/main/java/org/pmiops/workbench/tools/ManageLeonardoRuntimes.java
This helped me learn a bit about an on-call ticket.
---
=> [risk=low][no ticket] Add columns to the project.rb list-runtimes output

ui/src/app/pages/signed-in/access-renewal-notification.spec.tsx, ui/src/testing/react-test-helpers.tsx
=> [RW-12612][risk=no] Converted access-renewal-notification.spec.tsx to RTL.

ui/src/app/pages/data/cohort/cohort-criteria-menu.tsx, ui/src/app/pages/data/cohort/constant.ts, ui/src/app/pages/data/cohort/search-group-item.tsx, ui/src/app/pages/data/cohort/variant-search.tsx
- Make font consistent for text in exclude variant buttons
- Add select icons next to boolean criteria menu items
=> [DT-815][risk=no] UI updates for CB variant search

api/config/featured_workspaces_prod.json
=> [RW-12367][risk=low]   New Featured Workspace: Please publish this Demo workspace in current CDR in prod

ui/src/app/components/confirm-workspace-delete-modal.tsx, ui/src/app/components/help-sidebar.tsx, ui/src/app/pages/workspace/workspace-card.tsx
Reverts all-of-us/workbench#8543
=> Revert "RW-12555 Revert "[risk=low] RW-12040 Allow workspace deletion""

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh, api/db-cdr/generate-cdr/build-cb-criteria-menu.sh, api/db-cdr/generate-cdr/build-cb-search-person.sh
adding self reported population
---
=> [DT-825][risk=no] adding self reported population

ui/src/app/components/runtime-initializer-modal.tsx, ui/src/app/pages/analysis/leonardo-app-launcher.spec.tsx, ui/src/app/pages/analysis/leonardo-app-launcher.tsx
=> [RW-12613][risk=no] Converted leonardo-app-launcher.spec.tsx

api/db-cdr/generate-cdr/build-cb-search-person.sh
Reverts all-of-us/workbench#8581
=> Revert "[DT-825][risk=no] adding select for missing var"

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh, api/db-cdr/generate-cdr/build-cb-criteria-menu.sh, api/db-cdr/generate-cdr/build-cb-search-person.sh
Reverts all-of-us/workbench#8580
=> Revert "[DT-825][risk=no] adding self reported population"

ui/src/app/components/apps-panel/utils.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx, ui/src/app/utils/machines.ts
=> [risk=low][RW-12536] Change autodelete thresholds and default to enabled

api/config/featured_workspaces_prod.json
adding new demo featured workspace
---
=> [RW-12726][risk=no] adding new demo featured workspace

api/config/featured_workspaces_prod.json
adding 4 Featured Workspaces:
1. https://precisionmedicineinitiative.atlassian.net/browse/RW-12754
2. https://precisionmedicineinitiative.atlassian.net/browse/RW-12755
3. https://precisionmedicineinitiative.atlassian.net/browse/RW-12756
4. https://precisionmedicineinitiative.atlassian.net/browse/RW-12785
---
=> [no ticket][risk=no] adding 4 Featured Workspaces

tanagra-aou-utils/tanagra-api.yaml
This sets the min # of tanagra API instances to 2, should reduce wait times since there will always be an idle instance ready for requests.
---
- [x ] I have included an issue ID or "no ticket" in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [x ] I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [x ] I have manually tested this change and my testing process is described above.
- [x ] This change includes appropriate automated tests, and I have documented any behavior that cannot be tested with code.
- [x ] I have added explanatory comments where the …
=> Ticket-DT-495 Min Idle Instances

.circleci/config.yml
No functional changes are expected here.
Before I start changing how CircleCI auth works, I want to document **how** it is currently done and **why/where** it is needed.
---
=> [risk=no][RW-11850] Clarify authorization needs in the CircleCI conf

.circleci/config.yml
Fix for a bug introduced in #8598 - see test run https://app.circleci.com/pipelines/github/all-of-us/workbench/33001/workflows/779b6eb6-0433-48eb-9791-4972c1999e5b/jobs/358320
---
=> [risk=no][RW-11850] Restore access for uploading test results

.circleci/config.yml
Use a different authentication scheme (OIDC and WIF) in CircleCI to deploy to Test and Staging.  See Proposal 1 in [Security improvements for RWB deployment](https://docs.google.com/document/d/1qtTlfS7Dd44HOZ72DaBu7SlxuSTnb7IIs0Wzi7Fa-CM/edit#heading=h.xc2shbwu8yj) for more details.
This change has a **low** security level because it only affects Test and Staging, but the devops/terraform changes are **moderate**.
The corresponding Terraform change is https://github.com/all-of-us/workbench-terraform-modules/pull/59
The corresponding Devops change is https://github.com/all-of-us/workbench-devops/pull/127
---
=> [risk=low][RW-11850] Use Workload Identity Federation to deploy to Test and Staging

deploy/libproject/deploy.rb
#8597 broke the staging deploy.  The reason this was not caught during testing is because the staging deploy uses slightly different commands as test deploy, including running a few unnecessary credential commands.  These commands are also incompatible with the new auth process.
Tested by modifying the circle config to deploy staging from **this branch**.  This was [mostly successful](https://app.circleci.com/pipelines/github/all-of-us/workbench/33048/workflows/df9e0327-9a6a-4d6f-af6d-fccb7d6b5358/jobs/358948) - I believe the failure step was unrelated to auth, but rather because this branch name did not fit the expected pattern.
I also confirmed that the existing auth method remains functional, by running a local dry-run deployment to Stable.
---
- One or more of the …
=> [risk=low][RW-11850] Remove incompatible credentials commands to re-enable staging deploy

api/src/main/java/org/pmiops/workbench/leonardo/LeonardoApiClientImpl.java, api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java, api/src/main/resources/leonardo.yaml, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
=> [noTicket][risk=no] Update Leonardo swagger  for update request

api/src/main/java/org/pmiops/workbench/utils/mappers/LeonardoMapper.java
Inspired by #8600
No changes expected.  Tested locally.
---
=> [risk=low][no ticket] LeonardoMapper cleanup

ui/src/app/pages/admin/admin-institution-edit.spec.tsx, ui/src/testing/react-test-helpers.tsx
=> [RW-12616][risk=no] Converted admin-institution-edit.spec.tsx

ui/src/app/utils/access-utils.spec.tsx
=> [RW-12617][risk=no] Converted access-utils.spec.tsx to RTL.

api/config/featured_workspaces_prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-12910
---
=> [RW-12910] publish new feature workspace in prod

e2ev2/package.json, e2ev2/src/utils.js, e2ev2/yarn.lock, ui/src/environments/environment-type.ts
Resolves https://github.com/all-of-us/workbench/security/dependabot/88
---
=> [risk=low][no ticket] Bump all e2ev2 packages to latest, to resolve a vulnerability

api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/data-set/export-dataset-modal.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx, ui/src/app/utils/navigation.tsx
- Add listener for export postMessage API event from iframe and render the `ExportDatasetModal`
- Add `tanagraConceptSetIds` and `tanagraCohortIds` properties to `DataSetRequest` for retrieving export preview
---
=> [DT-838][risk=no] Handle export events from Tanagra iframe

ui/src/app/pages/data/cohort/utils.ts
=> [no ticket][risk=no] Add display text for self reported criteria type

api/src/main/java/org/pmiops/workbench/api/OfflineRuntimeController.java
Trying to understand better why https://precisionmedicineinitiative.atlassian.net/browse/RW-12698 happened
---
=> RW-12698 log last accessed time as well

ui/src/app/pages/admin/workspace/about-publish-consent-modal.spec.tsx, ui/src/app/pages/admin/workspace/about-publish-consent-modal.tsx, ui/src/app/pages/workspace/workspace-about.spec.tsx, ui/src/app/pages/workspace/workspace-about.tsx, ui/src/app/utils/zendesk.ts
=> [risk=no] RW-12606 Add article link on about page

api/config/cdr_config_test.json
=> [no-ticket][risk=no] bumping cdr in test

ui/src/app/pages/login/login-error-banner.tsx, ui/src/app/pages/login/login.spec.tsx
AS per the comments from Anna update the banner text
https://github.com/user-attachments/assets/4050679d-ae8e-4b3f-8e3a-a31d60816ea7
---
=> [noTicket][risk=medium] Update message on Login Issue banner

api/config/config_preprod.json, api/config/config_prod.json
=> [risk=low][no ticket] Disable login issue banner in all envs

api/src/main/java/org/pmiops/workbench/firecloud/FireCloudServiceImpl.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
Some changes or comments that were left from original PR
---
=> [RW-12857][risk=no] [API] Add APIs to support user publish community workspaces

api/src/main/java/org/pmiops/workbench/api/CohortBuilderController.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/CohortBuilderControllerTest.java, ui/src/app/pages/data/cohort/overview.tsx, ui/src/app/pages/data/cohort/utils.ts
Adding self reported category to charts in CB
---
=> [DT-842][risk=no] Adding self reported category to charts in CB

.circleci/config.yml
Use a different authentication scheme (OIDC and WIF) in CircleCI to deploy to Stable. See [Proposal 1 in Security improvements for RWB deployment ](https://docs.google.com/document/d/1qtTlfS7Dd44HOZ72DaBu7SlxuSTnb7IIs0Wzi7Fa-CM/edit#heading=h.xc2shbwu8yj)for more details.
This change has a low security level because it only affects stable, but the devops change is moderate.
The corresponding Devops change is: https://github.com/all-of-us/workbench-devops/pull/130
---
=> [risk=low][RW-11491]Added CircleCI config shell for deploying to stable.

ui/src/app/components/popups.tsx, ui/src/app/pages/admin/admin-institution-edit.tsx, ui/src/app/pages/admin/workspace/filename-cell.tsx, ui/src/app/pages/data/concept/concept-search.tsx, ui/src/app/pages/login/account-creation/account-creation.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
After #8691 and #8699 these will be errors.
Also better specify the props for the components in `popups.tsx`
---
=> [risk=low][no ticket] Add and correct popup types

api/config/config_local.json, ui/src/app/pages/admin/workspace/basic-information.spec.tsx, ui/src/app/pages/admin/workspace/basic-information.tsx, ui/src/testing/default-server-config.ts
=> [no ticket][risk=no] Put admin workspace publishing behind a feature flag.

e2e/yarn.lock, ui/src/environments/environment-type.ts
Resolves https://github.com/all-of-us/workbench/security/dependabot/91
---
=> [risk=low][no ticket] Resolve an e2e vulnerability by upgrading

.circleci/config.yml
=> [RW-11491][risk=no] Fix typo in CircleCI config.

.circleci/config.yml
=> [RW-11491][risk=no] Swap command to service_account parameter

.circleci/config.yml
=> [RW-11491][risk=no] Debug OIDC info

.circleci/config.yml
=> [RW-11491][risk=no] Remove debugging

api/config/config_local.json, api/config/config_preprod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
Update hail image https://precisionmedicineinitiative.atlassian.net/browse/RW-13452
---
=> [risk=low] RW-13452 update aou image version

api/db/changelog/db.changelog-232-add-user_initial_credits_expiration.xml, api/db/changelog/db.changelog-master.xml
Add table to handle user credit expiration.
Ran migration locally and the table looked as expected.
---
=> [RW-13299][risk=no] Add user_initial_credits_expiration table.

api/src/main/java/org/pmiops/workbench/db/dao/FeaturedWorkspaceDao.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
Tested: 
Featured workspace is deleted
Non featured workspace is deleted 
---
=> [noTicket][risk=low] Delete entry from featured workspace is workspace is deleted or active_status is marked as deleted

ui/src/app/pages/admin/workspace/admin-workspace.tsx, ui/src/app/pages/admin/workspace/basic-information.tsx, ui/src/app/pages/admin/workspace/collaborators.tsx
Update the Collaborators section to better clarify roles
---
=> [risk=low][no ticket] Add creator to the Workspace Admin page

ui/src/app/components/resources/dataset-action-menu.tsx, ui/src/app/pages/data/cohort-review/detail-header.component.tsx, ui/src/app/pages/data/cohort/overview.tsx, ui/src/app/pages/data/concept/concept-list.tsx, ui/src/app/pages/workspace/workspace-wrapper.tsx, ui/src/app/utils/navigation.tsx, ui/src/app/utils/user-apps-utils.tsx
Tested locally: everything worked as expected.
---
=> [risk=low][no ticket] Add types to navigate and navigateByUrl

api/src/main/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryController.java, api/src/main/java/org/pmiops/workbench/mail/MailService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/initial_credits_exhaustion/content.html, api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExpiryControllerTest.java
Swapped email language so as not to be confused with temporal credit expiration.
---
=> [RW-13428][risk=no] Renamed email resources in order to avoid confusion

api/db-cdr/generate-cdr/build-cb-criteria-demographics.sh
adding echo to print count
---
=> [no ticket][risk=no] adding echo to print count

api/config/config_prod.json
Similar to https://github.com/all-of-us/workbench/pull/8728
---
=> [risk low] RW-13452 roll hail upgrade to prod

api/src/main/resources/emails/initial_credits_exhaustion/content.html
=> [no ticket][risk=no] Re-add exhaustion template

.circleci/config.yml
Fix typo that might be causing stable deploy failure.
---
=> [no ticket][risk=no] Fix typo

ui/src/app/components/gke-app-configuration-panels/create-gke-app.spec.tsx, ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx, ui/src/testing/utils.ts
=> [risk=low][RW-13311] SAS autodelete must be enabled

api/db-cdr/generate-cdr/build-cb-criteria-menu-test.sh
testing bug fix for indexing build
---
=> [DT-874][risk=no] testing bug fix for indexing build

api/db-cdr/generate-cdr/build-cb-criteria-menu-test.sh
testing script in circleci
---
=> [no ticket][risk=no] testing script in circleci

api/db-cdr/generate-cdr/build-cb-criteria-menu-test.sh
=> [no ticket][risk=no] indexing bug test

api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java
Tested locally by interacting with a workspace
---
=> [risk=low][RW-3980] Fully remove id from workspace entity object

ui/package.json, ui/yarn.lock
Remove a force version from #8791 
Tested locally with no apparent problems.
---
=> [risk=low][no ticket] Bump openapi and un-force nestjs

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfigMapper.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/access/compliance-training-module-card-title.spec.tsx, ui/src/app/pages/access/compliance-training-module-card-title.tsx, ui/src/app/pages/access/module.spec.tsx, ui/src/app/pages/access/module.tsx, ui/src/app/pages/access/modules-for-annual-renewal.tsx, ui/src/app/pages/access/test-utils.ts, ui/src/app/utils/constants.tsx, ui/src/testing/default-server-config.ts
=> [RW-13586][risk=no] Add maintenance text for compliance training

api/libproject/devstart.rb, api/tools/src/main/java/org/pmiops/workbench/tools/ConfigLoader.java, deploy/libproject/deploy.rb
Updated Ruby script from "docker-compose" to "docker-compose"
Tested by successfully running dev-up and a deploy.
---
=> [no ticker][risk=no] Updated "docker-compose" to "docker compose"

api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceImpl.java, api/src/main/java/org/pmiops/workbench/institution/InstitutionService.java, api/src/main/java/org/pmiops/workbench/institution/InstitutionServiceImpl.java, api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsExpirationServiceTest.java, api/src/test/java/org/pmiops/workbench/institution/InstitutionServiceTest.java, api/src/test/java/org/pmiops/workbench/utils/mappers/WorkspaceMapperTest.java
=> [RW-13555][risk=no] Add logic to bypass credit expiration based on institutional bypass

api/src/main/java/org/pmiops/workbench/api/ConceptSetsController.java, api/src/main/java/org/pmiops/workbench/api/NotebooksController.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/NotebooksControllerTest.java, ui/src/app/components/copy-modal.spec.tsx, ui/src/app/components/copy-modal.tsx
No expected changes.  Tested locally by copying a notebook from one workspace to another.
---
=> [risk=low][no ticket] Complete migration of CopyRequest field from "toWorkspaceName" to "toWorkspaceTerraName"

api/config/cdr_config_test.json
updating cdr index in RT v4 test
---
=> [DT-899][risk=no] updating cdr index in RT v4 test

.circleci/config.yml
It looks like api-contract-upload is failing in Circle. I think that there have been some changes to Broad secrets and the future of contract testing. I am going to remove this Circle job for now, and we can add it back later, if we’d like.
---
=> [No ticket][risk=no] Remove contract testing

api/db-cdr/generate-cdr/create-fitbit-tables-with-id-column.sh, api/libproject/devstart.rb
adding script for create fitbit tables with primary key
---
=> [DT-888][risk=no] adding script for create fitbit tables with primary key

api/build.gradle, api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/leonardo/LeonardoLabelHelper.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/tools/src/main/java/org/pmiops/workbench/tools/ListDisks.java, api/tools/src/main/java/org/pmiops/workbench/tools/ListDisksRow.java
Example output
Initial PR: [test-disks.csv](https://github.com/user-attachments/files/17196235/test-disks.csv)
After adding billing account type: [test-disks2.csv](https://github.com/user-attachments/files/17215906/test-disks2.csv)
---
=> [risk=low][RW-13643] Add a List Disks tool to gather Persistent Disk information

api/src/main/java/org/pmiops/workbench/api/RuntimeController.java, api/src/test/java/org/pmiops/workbench/api/RuntimeControllerTest.java, api/src/test/java/org/pmiops/workbench/leonardo/LeonardoApiClientTest.java
I cleaned up these test files while integrating the Leo client, but that made a big PR.  Splitting these out to clarify the changes.
No functional changes here.
---
=> [risk=no][no ticket] Minor cleanups of unit tests

api/src/main/webapp/WEB-INF/cron_test.yaml
The syntax in #8839 was invalid
---
=> [risk=low][no ticket] Try again: disable checkPendingEgressEvents on Test

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/resources/tanagra.yaml, api/src/main/resources/workbench-api.yaml
Caused by the rename of `conceptSets` to `featureSets`
=> [DT-902][risk=no] Fix Tanagra export failure

ui/src/app/pages/access/data-access-requirements.spec.tsx, ui/src/app/pages/admin/user/admin-user-bypass.spec.tsx, ui/src/app/pages/admin/user/admin-user-profile.spec.tsx, ui/src/app/pages/admin/user/admin-user-table.spec.tsx, ui/src/app/pages/data/cohort/modifier-page.spec.tsx, ui/src/app/pages/homepage/homepage.spec.tsx, ui/src/app/pages/workspace/workspace-about.spec.tsx, ui/src/app/utils/access-utils.tsx
=> RISK=low RW-12240 more UI clean up

api/config/cdr_config_preprod.json, api/config/cdr_config_prod.json
bumping CDR v4 in preprod and prod
---
=> [DT-856][risk=no] bumping CDR v4 in preprod and prod

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/test/java/org/pmiops/workbench/api/ProfileControllerTest.java, api/src/test/java/org/pmiops/workbench/db/dao/UserServiceTest.java, api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java, ui/public/aou-tos.html, ui/src/app/components/terms-of-service.tsx, ui/src/app/utils/access-utils.tsx
Update the All of Us Terms of Service text to remove restrictions on commercial use, and show the new ToS to new users - but not existing users yet.
Also update the ToS update header to reflect this
Tested locally by observing the new text during account creation, and by observing that existing users do not yet have to re-sign the TOS.
In this update I also changed the semantics of the ToS config value to `minimumAcceptedAouVersion` to allow for a smooth upgrade.  Without this, the API would start **requiring** v2 for a brief period before the UI **provides** it.  Requiring a minimum value instead of an exact match allows us to upgrade using the following sequence:
1. (This PR) Update API to allow v1 or v2
2. (This PR) Update UI to provide v2
3. (Later) Update API to require v2
---
**PR …
=> [risk=low][RW-13695] Update TOS to allow commercial use

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/data-set/export-dataset-modal.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx, ui/src/app/utils/navigation.tsx
Check for `allParticipantsCohort` property on data exports from Tanagra
Need to wait for this PR in Tanagra before merging: https://github.com/DataBiosphere/tanagra/pull/1039
=> [DT-602][risk=no] Handle all participants flag for Tanagra exports

api/libproject/environments.rb, ui/libproject/devstart.rb
Adding tanagra deploy variables to all envs.
---
=> [DT-886][risk=no] Adding tanagra deploy variables to all envs.

api/config/cdr_config_staging.json
turning on tanagra in staging
---
=> [no ticket][risk=no] turning on tanagra in staging

ui/src/environments/environment.preprod.ts, ui/src/environments/environment.stable.ts
=> [no ticket][risk=no] turning on data apps v2

api/config/cdr_config_stable.json
enableing tanagra for stable
---
=> [no ticket][risk=no] enableing tanagra for stable

api/build.gradle, api/db-cdr/build.gradle, api/db/build.gradle
Tested locally by interacting with workspaces, runtimes, apps, and disks
---
=> [risk=low][no ticket] Upgrades to API packages and notes for cases where we can't

ui/src/app/pages/access/data-access-requirements.tsx
Checked data access requirement page and no issue observed
---
=> RISK=low RW-12216  Remove handleTerraShibbolethCallback

ui/src/app/pages/access/maybe-module.tsx, ui/src/app/routing/signed-in-app-routing.tsx, ui/src/app/utils/access-utils.tsx
Ran locally and data-access-requirements page looks fine.
---
=> risk=low RW-12216 remove nih callback

ui/src/app/pages/workspace/workspace-edit.tsx
Set value for dropdown based on `usesTanagra` workspace property
=> [no ticket][risk=no] Fix default Data Apps version

api/src/bigquerytest/java/org/pmiops/workbench/api/DataSetControllerBQTest.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
=> [no ticket][risk=no] fixing tanagra api

ui/src/app/pages/admin/user/admin-user-common.tsx, ui/src/app/pages/admin/user/admin-user-profile.tsx
Redesigning the admin user profile page was getting a bit long (https://github.com/all-of-us/workbench/pull/8850), so I broke this work into a separate PR.
Moving the institution link icon next to the "Verified Institution" link allows for this page to be redesigned a bit easier.
Old Design
New Design
---
=> [RW-13732][risk=no] Move institution link

api/db-cdr/generate-cdr/build-cb-variant-attribute-table.sh, api/src/main/java/org/pmiops/workbench/cohortbuilder/VariantQueryBuilder.java, ui/src/app/pages/data/cohort/variant-search.tsx, ui/src/app/utils/index.tsx
Fixing bug when searching for genomic position in variants.
---
=> [DT-917][risk=no] Fixing bug when searching for genomic position in variants.

api/config/cdr_config_preprod.json
enabling tanagra on CDR v7
---
=> [DT-910][risk=no] enabling tanagra on CDR v7

api/config/cdr_config_preprod.json, api/config/cdr_config_prod.json
changing config for v3 hotfix
---
=> [DT-857][risk=no] changing config for v3 hotfix

api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java, api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/main/resources/tanagra.yaml, ui/src/app/pages/data/tanagra-dev/data-component-tanagra.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-resource-list.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
Implementing artifact clones using tanagra API
---
=> [DT-330][risk=no] Implementing artifact clones using tanagra API

api/config/cdr_config_test.json
=> [no ticket][risk=no] bumping cdr index in test

api/config/cdr_config_test.json, api/config/config_local.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
=> [risk=low][RW-13861] Config fixes to run v8 extraction in test

api/config/cdr_config_test.json
=> [risk=low][RW-13861] Typo in dataset name

api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java
=> RW-11727 add back query_project

api/config/cdr_config_test.json
bumping the test cdr index
---
=> [DT-868][risk=no] bumping the test cdr index

api/libproject/cloudsqlproxycontext.rb, api/libproject/devstart.rb
Increase the time further from #8894
---
=> [risk=low][no ticket] Bump wait time to 2 minutes

api/db-cdr/generate-cdr/build-ds-linking.sh, api/src/main/java/org/pmiops/workbench/dataset/DataSetServiceImpl.java
=> [DT-868][risk=no] fixing select values

api/db-cdr/generate-cdr/build-cb-variant-attribute-table.sh
=> [no ticket][risk=no] fixing index

api/config/config_test.json
Related to https://github.com/broadinstitute/gatk/pull/9036
---
=> RW-11727 try new version of wdl

api/config/config_local.json, api/config/config_test.json
=> RW-13930 use new gatk jar

api/config/cdr_config_preprod.json, api/config/config_preprod.json
=> [risk=low][RW-13957] enable v8 genomic extraction in preprod

api/db-cdr/generate-cdr/create-fitbit-tables-with-id-column.sh
add clustering to fitbit tables for CDR v7 & v8
---
=> [DT-924][risk=no] add clustering to fitbit tables

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, ui/public/aou-tos.html
After the new ToS has been deployed, require signing the new version.  Followup to #8853
Tested locally by observing that I was required to sign the new version, and I did not see the phone number.
---
=> [risk=low][RW-13695][RW-13853] Require new version of ToS and remove phone number

api/config/cdr_config_preprod.json
updating config for preprod
---
=> [no ticket][risk=no] updating config for preprod

ui/src/app/components/breadcrumb.tsx
Converted the Breadcrumbs component to a functional component.
---
=> [no ticket][risk=no] Functional Breadcrumbs

api/db-cdr/generate-cdr/libproject/devstart.rb
=> [risk=low][RW-14006] Add sample_chromosome_ploidy table to WGS publishing

ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx
- Make sure the token for the Tanagra iframe gets updated whenever it's refreshed
- Force the iframe to reload as a temp workaround until we have a fix in core Tanagra
=> [DT-929][risk=no] Update token for Tanagra iFrame

api/tools/src/main/java/org/pmiops/workbench/tools/CreateTerraMethodSnapshot.java
=> [risk=low][RW-11727] Log the resolved commit hash when publishing a Terra method for provenance

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/VwbEgressAdminController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/api/AdminAuthorityTest.java
=> [RW-13915] [risk=low] initial api interface and feature flag for VWB egress

ui/src/app/pages/admin/workspace/file-table.tsx
This seemed useful as I was looking at Egress alerts.
---
=> [risk=low][no ticket] Add last modified to Workspace Admin file table

api/db/changelog/db.changelog-244-add-is-vwb-workspace-column.xml, api/db/changelog/db.changelog-244-add-lab-column-to-workspace.xml, api/db/changelog/db.changelog-master.xml, api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java, api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java, api/src/main/resources/workbench-api.yaml, api/src/main/resources/ws-manager.yaml
This is one of a few PRs building on top of each other to enable VWB workspace creation in AoU.
Changes in this PR include adding a new DB column in workspace table to specify which lab the workspace belongs to whether it's AoU or VWB
---
=> [risk=no][RW-13631] Add is_vwb_workspace field

.gitignore, api/db-cdr/generate-cdr/test-data/delete_preprod_datasets.sh, api/db-cdr/generate-cdr/test-data/delete_prod_datasets.sh, api/db-cdr/generate-cdr/test-data/impersonate_list_datasets_preprod.sh, api/db-cdr/generate-cdr/test-data/impersonate_list_datasets_prod.sh
adding scripts to delete datasets in the security perimeter. These can be reused next time we have to clean up old datasets in preprod and prod.
---
=> [DT-934][risk=no] adding scripts to delete datasets in the security perimeter

api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
checking to see if batched lists are being garbage collected
---
=> [no ticket][risk=no] checking to see if batched lists are being garbage collected

api/config/cdr_config_test.json
remove tanagra from new dataset
---
=> [no ticket][risk=no] remove tanagra from new dataset

api/config/cdr_config_preprod.json
config new preprod dataset for CDRv8 testing
---
=> [no ticket][risk=no] config new preprod dataset for CDRv8 testing

api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/emails/egress_remediation/content.html, api/src/test/java/org/pmiops/workbench/mail/MailServiceImplTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/SendEmail.java
DO NOT MERGE until after the 12/9 release, because we want to release this the week of 12/16.
https://precisionmedicineinitiative.atlassian.net/browse/RW-14070 
---
Compute Suspended
---
User Disabled
---
=> [risk=low][RW-14070] Egress email updates for the process transition

api/db-cdr/generate-cdr/build-tanagra-pfhh-table.sh
removing table clean it's not needed
---
=> [no ticket][risk=no] removing table clean it's not needed

api/config/config_local.json, api/config/config_preprod.json, api/config/config_test.json
Use [this version of wdl](https://github.com/broadinstitute/gatk/commit/f85aceb5ac485a4ae55872318658836f84422c67) in local, test, and preprod. This version re-enables optimization around `CreateManifestAndOptionallyCopyOutputs` step that requires VPC change.
```
--source-git-ref rwb_echo_release \
--method-namespace aouwgscohortextraction-test \
--method-name echo-prototyping
```
Output
```
Environment: all-of-us-workbench-test
New snapshot namespace/name/version: aouwgscohortextraction-test/echo-prototyping/18
Using source repo commit f85aceb5ac485a4ae55872318658836f84422c67
```
``` …
```
=> RW-14108 update wdl version

api/libproject/environments.rb, ui/src/app/pages/data/tanagra-dev/tanagra-container.tsx, ui/src/app/pages/data/tanagra-dev/tanagra-dev.tsx
adding new preprod underlays
---
=> [no ticket][risk=no] adding new preprod underlays

api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-14151
https://github.com/user-attachments/assets/2c3887ca-d702-4505-93f0-c2353530bf35
---
=> risk=no RW-14151 update RedCap link

api/db-cdr/generate-cdr/create-fitbit-tables-with-id-column.sh
adding row_id to device table
---
=> [DT-941][risk=no]  adding row_id to device table

.circleci/config.yml, api/libproject/cloudsqlproxycontext.rb, ci/Dockerfile.circle_build, deploy/Dockerfile, deploy/docker-compose.yaml
Was able to deploy to test
---
=> [risk=low][RW-14201] version updates to gcloud and cloudsql proxy

api/libproject/environments.rb
=> [no ticket][risk=no] removing underlay

api/src/main/java/org/pmiops/workbench/api/WorkspacesController.java, api/src/main/java/org/pmiops/workbench/db/model/DbCdrVersion.java, api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java, api/src/main/java/org/pmiops/workbench/tools/cdrconfig/CdrVersionVO.java, api/src/main/java/org/pmiops/workbench/utils/mappers/FirecloudMapper.java, api/src/main/java/org/pmiops/workbench/utils/mappers/WorkspaceMapper.java, api/src/main/java/org/pmiops/workbench/workspaces/VwbWorkspaceServiceImpl.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceAuthService.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapper.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceService.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceFactory.java, api/src/main/java/org/pmiops/workbench/workspaces/WorkspaceServiceImpl.java, api/src/main/java/org/pmiops/workbench/wsm/WsmClient.java, api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/api/WorkspacesControllerTest.java, api/src/test/java/org/pmiops/workbench/utils/TestMockFactory.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceAuthServiceTest.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceOperationMapperTest.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java
This PR add functionality to create workspaces via VWB.
The code changes introduce a new factory to return the correct workspace service based on the workspace chosen platform.
I tested my changes by creating a new workspace and duplicating an existing one, also created cohorts and ran some analysis on the created workspaces.
I also stopped the execution in WorkspaceController.createWorkspace method then update the flag vwbWorkspace to try and test workspace creation in VWB successfully.
---
=> [risk=low][RW-13631] VWB workspace creation 

api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java, api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java
=> [RW-14214] [risk=no] Allow VWB SAs to call AoU backend

api/db/changelog/db.changelog-247-drop-nonnull-sumologic-column-egress-event.xml, api/db/changelog/db.changelog-master.xml
In VWB, there would be no sumologic event
---
=> [RW-13918][risk=low] Allow sumologic to be null 

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/LeonardoAppUsageColumnValueExtractor.java, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
env var is a long text file and looks ~2kb per row, that may cause reporting OOM
---
=> [RW-14237] Stop uploading environment_variable in app_usage table in WRD

.circleci/config.yml, api/libproject/devstart.rb
Use the `vda-cicd` Github username/token instead of a personal one
=> [DT-841][risk=no] Update Tanagra deploy credentials

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/LeonardoAppUsageColumnValueExtractor.java, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java
Reverts all-of-us/workbench#9036
=> [risk=no]Revert "[RW-14237] Stop uploading environment_variable in app_usage table in WRD"

api/build.gradle, api/libproject/devstart.rb, api/src/main/java/org/pmiops/workbench/genomics/GenomicExtractionService.java, api/src/test/java/org/pmiops/workbench/api/CohortReviewControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/ConceptSetsControllerTest.java, api/src/test/java/org/pmiops/workbench/api/DataSetControllerTest.java, api/src/test/java/org/pmiops/workbench/genomics/GenomicExtractionServiceTest.java, api/src/test/java/org/pmiops/workbench/profile/ProfileServiceTest.java, api/src/test/java/org/pmiops/workbench/workspaces/WorkspaceServiceTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/RunGenomicExtractionWorkflow.java
Prerequisites:
* The genomics files must exist and be accessible in the Controlled Tier of the relevant environment (e.g. Prod)
* The caller must know the following information about the published data in the relevant environment (but this does not need to be a "published" CDR with a Config that allows workspace creation) 
* The CDR's BigQuery project
* The WGS dataset in that project
* The caller must know the following information about a Controlled Tier workspace in the relevant environment:
* namespace
* the ID of a dataset (contents not important - specifically, does not need to be a WGS dataset)
* The relevant environment must have a `wgsCohortExtraction.legacyVersions` block defined if the desired workflow to run is v7 or earlier (legacy = true) 
* The relevant environment must …
=> [risk=low][RW-14230] Genomics extraction testing tool

api/db-cdr/generate-cdr/libproject/devstart.rb
=> [risk=no][no ticket]Refresh access token in a separate thread for the long running script

api/config/config_prod.json
Use the same workflow version as #8993, as recommended.
Publish command:
```
--project all-of-us-rw-prod \
--source-git-ref rwb_echo_release \
--method-namespace aouwgscohortextraction-prod \
--method-name GvsExtractCohortFromSampleNamesV8
```
The result includes:
```
Environment: all-of-us-rw-prod
New snapshot namespace/name/version: aouwgscohortextraction-prod/GvsExtractCohortFromSampleNamesV8/1
Using source repo commit f85aceb5ac485a4ae55872318658836f84422c67
```
---
=> [risk=low][RW-14230] Add v8 genomics extraction config to Prod

api/config/cdr_config_prod.json
=> [no ticket][risk=no] Remove extra commas

api/build.gradle, api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java, api/src/main/java/org/pmiops/workbench/api/OfflineEgressController.java, api/src/main/java/org/pmiops/workbench/api/UserController.java, api/src/main/java/org/pmiops/workbench/cohortbuilder/util/QueryParameterValues.java, api/src/main/java/org/pmiops/workbench/config/FileConfigs.java, api/src/main/java/org/pmiops/workbench/profile/ProfileService.java, api/src/main/java/org/pmiops/workbench/rdr/RdrMapper.java, api/src/main/java/org/pmiops/workbench/utils/LogFormatters.java, api/src/main/java/org/pmiops/workbench/workspaces/resources/WorkspaceResourcesServiceImpl.java, api/src/main/resources/swagger3codegen/libraries/okhttp-gson/api.mustache, api/src/test/java/org/pmiops/workbench/api/CohortsControllerTest.java
Tested locally with no obvious problems.  I was able to update my Profile as well as admin-update a Profile.
---
=> [risk=low][no ticket] Bump Javers and GSON and update Profile validation code

ui/src/app/pages/access/data-access-requirements.tsx
=> [no ticket][risk=no] Add flag for expiration message on data access requirements page.

ui/src/app/pages/workspace/research-purpose.tsx, ui/src/app/pages/workspace/workspace-edit.tsx
Added AI/AN responses to Workspace About page
Added AI/AN to update workspace modal
---
=> [no ticket][risk=no] Added AI/AN to Workspace About Page

api/config/cdr_config_stable.json, api/config/config_stable.json
=> [risk=no][RW-14300] Update stable config to be able to create workspaces in VWB

api/src/main/java/org/pmiops/workbench/vwb/wsm/WsmClient.java
=> [risk=no][no-ticket] Check wsm error report and log it if it exists

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, ui/src/app/pages/login/login-error-banner.tsx, ui/src/app/pages/login/login.spec.tsx
Banner for this weekend's maintenance
---
=> [no ticket][risk=no] Leo maintenance banner.

api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, ui/src/app/pages/login/login-error-banner.tsx, ui/src/app/pages/login/login.spec.tsx
=> [no ticket][risk=no] Remove weekend maintenance banner

api/build.gradle, api/db-cdr/build.gradle, api/db/build.gradle
Tested locally with no apparent problems
---
=> [risk=low][no ticket] Misc Java package upgrades

api/libproject/devstart.rb, api/tools/src/main/java/org/pmiops/workbench/tools/RunGenomicExtractionWorkflow.java
Tested locally.  See https://precisionmedicineinitiative.atlassian.net/browse/RW-14362 for examples.
---
=> [risk=low][RW-14362] Use a person_id_file for easier extraction testing

api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java, api/src/main/java/org/pmiops/workbench/api/CloudTaskRdrExportController.java, api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java, api/src/main/java/org/pmiops/workbench/api/CloudTaskWorkspacesController.java, api/src/main/java/org/pmiops/workbench/api/OfflineEgressController.java, api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java, api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java, api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java, api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java, api/src/main/java/org/pmiops/workbench/survey/NewUserSatisfactionSurveyServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/main/webapp/WEB-INF/queue.yaml, api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java, api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java, api/src/test/java/org/pmiops/workbench/interceptors/AuthInterceptorTest.java, api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java, api/tools/src/cron/checkInitialCreditsExpiration.sh
Misc cloud tasks and cron improvements.  Tested locally by running all crons.
---
=> [risk=low][RW-14370] Misc cloud tasks and cron changes

api/config/config_local.json, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/exceptions/ExceptionUtils.java, api/src/main/java/org/pmiops/workbench/vwb/usermanager/UserManagerClient.java, api/src/main/java/org/pmiops/workbench/vwb/usermanager/UserManagerConfig.java, api/src/main/java/org/pmiops/workbench/vwb/usermanager/UserManagerRetryHandler.java
=> [risk=no][RW-13628] User manager url config and client code

ui/src/app/pages/admin/workspace/admin-workspace.tsx
As part of some of the cleanup from the AI/AN work, I would to use a hook on this page. I could probably get away without it, but it seemed like a good enough reason to do some cleanup.
---
=> [no ticket][risk=no] Convert admin workspace component from class based to functional.

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/CloudTaskEnvironmentsController.java, api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java, api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java, api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/db/dao/UserDao.java, api/src/main/java/org/pmiops/workbench/db/dao/UserService.java, api/src/main/java/org/pmiops/workbench/db/dao/UserServiceImpl.java, api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/main/webapp/WEB-INF/queue.yaml, api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java
Tested locally by running several cron scripts
---
=> [risk=low][RW-14369] Convert sendAccessExpirationEmails to TaskQueues and functionalize CloudTaskUserController

api/src/main/java/org/pmiops/workbench/db/model/DbWorkspace.java, api/src/main/resources/rdr.yaml, api/src/test/java/org/pmiops/workbench/rdr/RdrMapperTest.java
Adding fields to RDR export as specified here:
https://pmi-engteam.slack.com/archives/C085LUERYKF/p1736870583242619?thread_ts=1736792119.395819&cid=C085LUERYKF
---
=> [no ticket][risk=no] Add AIAN fields to RDR Workspace entity.

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingTableParams.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingTableService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationService.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingVerificationServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/CohortColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/DatasetCohortColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/DatasetColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/DatasetConceptSetColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/DatasetDomainColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/InstitutionColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/LeonardoAppUsageColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/NewUserSatisfactionSurveyColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/UserColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/UserGeneralDiscoverySourceColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/UserPartnerDiscoverySourceColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceColumnValueExtractor.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceFreeTierUsageColumnValueExtractor.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/dao/CohortDaoTest.java, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingVerificationServiceTest.java, api/src/test/java/org/pmiops/workbench/testconfig/fixtures/ReportingUserFixture.java
Removed a lot of error-prone boilerplate code from the reporting system.  Inspired by my experience checking that I wasn't missing anything for https://github.com/all-of-us/workbench/pull/9095
Tested locally by running local API/UI and uploading reporting snapshots
---
=> [risk=low][no ticket] rm duplicated code for reporting system

api/src/main/java/org/pmiops/workbench/reporting/ReportingUploadServiceImpl.java
This will help us tell which specific tables are failing.
Example from Prod logs:
```
ErrorId 512eb0d0-0c29-4bd0-86e5-d2fc9435079b: com.google.cloud.bigquery.BigQueryException
com.google.cloud.bigquery.BigQueryException: Request payload size exceeds the limit: 10485760 bytes.
at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:116)
at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:550)
at com.google.cloud.bigquery.BigQueryImpl$28.call(BigQueryImpl.java:1127)
at com.google.cloud.bigquery.BigQueryImpl$28.call(BigQueryImpl.java:1124)
at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:102)
at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
at …
```
=> [risk=low][RW-14237] Log BigQuery insertion errors and continue

api/config/config_local.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java
also throw exception, to make the failure obvious
---
=> [risk=low][RW-14237] Update local and test batch sizes, and throw exception on failure

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java
=> [risk=low][RW-14237] Report on all active workspaces, and explain corner cases

ui/src/app/pages/access/data-access-requirements.tsx
If you bypass a user, either individually or institutionally, you should see the following message:
---
=> [no ticket][risk=no] Only show expiration message if user's credits will expire.

api/build.gradle
https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-8707740
Tested locally with no apparent problems.
---
=> [risk=low][no ticket] Bump vulnerable netty-common

api/db-cdr/generate-cdr/stage-redcap-files.py
=> [no-ticket][risk=no] adding new surveys

e2e/app/page/privacy-page.ts, e2e/utils/test-utils.ts, e2ev2/package.json, e2ev2/src/test-utils.js, e2ev2/src/utils.js, e2ev2/tests/new-user-satisfaction-survey.test.js, e2ev2/tests/workspace-analysis.test.js, e2ev2/tests/workspace-create.test.js, e2ev2/yarn.lock, ui/src/app/components/card.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/appAnalysis/app-files-list.tsx, ui/src/app/pages/login/login.tsx, ui/src/app/pages/privacy-warning.tsx, ui/src/app/pages/signed-in/nav-bar.tsx, ui/src/app/pages/signed-in/signed-in.tsx, ui/src/app/utils/authentication.tsx, ui/src/app/utils/constants.tsx
Every time a user logs into RWB, they should see the screen above. They should not be able to navigate to any other pages within the signed-in portion of the application.
Clicking the "Acknowledge" button should bring the user to whichever page they were originally navigating.
Clicking the "Cancel" button will sign the user out of the application.
Clicking on the menu button will only show the user options for "Sign Out", "User Support Hub", and "Contact Us" as shown above.
---
=> [RW-13991][risk=no] Add privacy warning

api/src/main/java/org/pmiops/workbench/access/AccessModuleServiceImpl.java, api/src/main/java/org/pmiops/workbench/api/CloudTaskUserController.java, api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueuePair.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java, api/src/main/java/org/pmiops/workbench/db/dao/GoogleProjectPerCostDao.java, api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateService.java, api/src/main/resources/workbench-api.yaml, api/src/main/webapp/WEB-INF/queue.yaml, api/src/test/java/org/pmiops/workbench/api/CloudTaskInitialCreditsExhaustionControllerTest.java, api/src/test/java/org/pmiops/workbench/api/CloudTaskUserControllerTest.java, api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java, api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateServiceTest.java, api/src/test/java/org/pmiops/workbench/interceptors/CloudTaskInterceptorTest.java, api/tools/src/main/java/org/pmiops/workbench/tools/BackfillEntitiesToRdr.java
Store the Task Queue queues and endpoints together, and refactor the TaskQueueService code.
Add a note to update the task queue monitoring when the queues are updated.  (WIP: https://github.com/all-of-us/workbench-terraform-modules/pull/62 )
Tested locally by running all crons.
---
=> [risk=low][no ticket] Organize TaskQueueService

api/src/main/webapp/WEB-INF/queue.yaml
Oops!  Missed a step in #9124 
---
=> [risk=low][RW-14368] Add the queue for checkPersistentDisks

api/db-cdr/generate-cdr/build-prep-survey.sh
=> [DT-980][risk=no] adding 2 new MHWB surveys

ui/src/app/pages/access/data-access-requirements.tsx
=> [risk=low][no ticket] Don't reload profile if the external-sync didn't make any changes

api/src/main/java/org/pmiops/workbench/api/OfflineBillingController.java, api/src/main/java/org/pmiops/workbench/api/OfflineRdrExportController.java, api/src/main/java/org/pmiops/workbench/api/OfflineTestUsersController.java, api/src/main/java/org/pmiops/workbench/api/OfflineUserController.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java, api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateService.java, api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java, api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/ReportingServiceImpl.java, api/src/main/resources/workbench-api.yaml, api/src/main/webapp/WEB-INF/cron_base.yaml, api/src/main/webapp/WEB-INF/cron_test.yaml, api/src/test/java/org/pmiops/workbench/api/OfflineBillingControllerTest.java, api/src/test/java/org/pmiops/workbench/api/OfflineUserControllerTest.java, api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsBatchUpdateServiceTest.java, api/src/test/java/org/pmiops/workbench/initialcredits/InitialCreditsServiceTest.java, api/src/test/java/org/pmiops/workbench/interceptors/CronInterceptorTest.java, api/tools/src/cron/checkFreeTierBillingUsage.sh, api/tools/src/cron/checkInitialCreditsUsage.sh, api/tools/src/cron/synchronizeUserAccess.sh
Rename some crons to reflect current usage
Add and improve logging
Tested by running the renamed and re-logged crons, and running Local UI.
---
=> [risk=low][RW-14370] Minor cron improvements

api/db-cdr/generate-cdr/bq-schemas/cb_search_person.json, api/db-cdr/generate-cdr/build-cb-criteria-menu.sh, api/db-cdr/generate-cdr/build-cb-search-person.sh, api/db-cdr/generate-cdr/build-prep-survey.sh, api/src/main/java/org/pmiops/workbench/cohortbuilder/SearchGroupItemQueryBuilder.java, api/src/main/java/org/pmiops/workbench/db/model/DbStorageEnums.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/data/cohort/constant.ts, ui/src/app/pages/data/cohort/search-group.tsx
Adding EtM and MHWB data to CB
---
=> [DT-980][risk=no] Adding EtM and MHWB data to CB

ui/src/app/components/side-nav.tsx
=> [risk=low][no ticket] This caused the infinite reload for some reason

api/src/main/java/org/pmiops/workbench/disks/DiskAdminService.java
=> [risk=low][RW-14538] Add some logging for checkPersistentDisks

api/db/changelog/db.changelog-257-increase-user-version-column.xml, api/db/changelog/db.changelog-master.xml
A dozen or so users had maxed out their version field.
---
=> [no ticket][risk=no] Increase size of version for user table.

api/db-cdr/generate-cdr/build-cb-criteria-attribute-tables-and-cleanup.sh, ui/src/app/pages/data/cohort/cohort-search.tsx
=> [DT-980][risk=no] fixing MHWB survey

api/src/main/java/org/pmiops/workbench/interceptors/AuthInterceptor.java
=> [risk=low][no ticket] Slight improvement to token check

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, ui/src/app/pages/login/login-error-banner.tsx, ui/src/app/pages/login/login.spec.tsx
=> [no ticket][risk=no] Outage banner

.circleci/config.yml
=> [risk=low][no-ticket] Temporarily comment out dependency check task

.circleci/config.yml, api/build.gradle, api/buildSrc/build.gradle
=> [risk=no][no-ticket] Bump dependencycheck version

ui/src/app/utils/leo-runtime-initializer.tsx
=> [no ticket][risk=no] Reuse disk after deleting runtime

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-14615
---
=> [risk=low][RW-14615] switch enableLoginIssueBanner to false

api/db-cdr/generate-cdr/build-ds-tables.sh
fixning typo in ETM script
---
=> [no-ticket][risk=no] fixning typo in ETM script

api/db-cdr/generate-cdr/bq-schemas/ds_delaydiscounting_trial_data.json
=> [no-ticket][risk=no] fixing column name

api/src/main/java/org/pmiops/workbench/dataset/BigQueryDataSetTableInfo.java
=> [no-ticket][risk=no] fixing EtM table name

api/src/main/java/org/pmiops/workbench/initialcredits/InitialCreditsService.java
Tested locally by running the checkInitialCreditsUsage cron
---
=> [risk=low][RW-14649] Account for workspaces without Google Projects

api/config/config_stable.json
Stable will be using VWB prod. Adding/correct few missing urls
---
=> [no ticket][risk=low] Add missing VWB configs

api/src/main/java/org/pmiops/workbench/api/OfflineEnvironmentsController.java
When this cron sees a failure today, it immediately stops.  I have observed that it consistently fails while trying to delete the same runtime (which we handled in https://precisionmedicineinitiative.atlassian.net/browse/RW-14659).  Instead, we should log such "problem runtimes" but continue deleting others.  Fail at the end with a list of failures, so the cron still fails overall.
---
=> [risk=low][RW-14653] Log deleteOldRuntimes failures and continue

ui/src/app/components/icons.tsx, ui/src/app/components/multi-toast-banner.spec.tsx, ui/src/app/components/multi-toast-banner.tsx, ui/src/app/components/multi-toast-message.model.ts, ui/src/app/components/pagination-navigation.tsx, ui/src/app/components/status-alert-banner-maybe.tsx, ui/src/app/components/toast-banner.tsx
Add multi-toast-banner component in service of https://github.com/all-of-us/workbench/pull/9174
---
=> [RW-14542][risk=no] Add multi-toast-banner

api/src/main/resources/rawls.yaml
Ensure that we don't call this API after the removal is merged: https://github.com/broadinstitute/firecloud-orchestration/pull/1586 (this is a pass-through to a similar Rawls endpoint)
Tested by compiling and running Local
---
=> [risk=low][no ticket] rm Rawls API which is being removed

api/src/main/webapp/WEB-INF/queue.yaml
This cron job is straining the Sam DB: https://broadinstitute.slack.com/archives/C07QQ3L0AHX/p1742330504315059
There are a variety of possible solutions discussed there.  A simple way to help should be to slow down the processing, and that's what this PR does.
Before:
The queue processed 382 tasks of 50 workspaces each in ~2 hours, or 3 per minute.  The individual tasks complete in about 3 minutes, so there are roughly 3x3=9 concurrent executions, implying that `max_concurrent_requests: 10` is constraining the job instead of the token bucket parameters, which allow 500 executions per second (!)
After:
Reduce the token bucket parameters to allow only 1 task execution per minute.  If we assume that the tasks continue to complete in 3 minutes, then we will still have concurrent execution of …
=> [risk=low][RW-13727] Reduce delete-unshared queue processing to 1 per minute

api/config/config_local.json, api/config/config_stable.json
=> [risk=no][no-ticket]Add VWB UM url in stable config

api/build.gradle, api/buildSrc/build.gradle, api/db-cdr/build.gradle, api/db/build.gradle, appengine-cron-emulator/build.gradle
=> [risk=low][no ticket] Upgrade some Java packages

api/config/cdr_config_test.json
=> [no-ticket][risk=no] bumping index for test

README.md
Removed outdated reference to hot swapping
---
=> [no ticket][risk=no] Update README.md

api/src/main/java/org/pmiops/workbench/mail/MailServiceImpl.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-14806
---
=> [risk=low][RW-14806] Log more useful info to see what result we get from Mandril

api/src/main/java/org/pmiops/workbench/api/CloudTaskEgressController.java, api/src/main/java/org/pmiops/workbench/exfiltration/EgressRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressObjectLengthsRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressSumologicRemediationService.java, api/src/main/java/org/pmiops/workbench/exfiltration/impl/EgressVwbRemediationService.java
=> [risk=low][no ticket] Renamed a few methods to clarify their purpose

api/src/main/java/org/pmiops/workbench/rdr/RdrExportServiceImpl.java
We're logging this for Researchers, and it's helpful there.
---
=> [risk=low][no ticket] Log RDR Export Workspaces error

api/config/config_local.json, api/config/config_test.json
=> [no ticket][risk=no] turn off vwb access feature temporary

.circleci/config.yml, deploy/libproject/deploy.rb, deploy/libproject/jirarelease.rb
Trying to export deploy ticket tag into CircleCI context.
---
=> [RW-11491][risk=no] Attempting to extract Jira key from deploy script.

api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java
=> [risk=low][no ticket] Don't create VWB Pod when the flag is false

.circleci/config.yml
The JIRA_ISSUE_KEY was being written [to a non-existent directory](https://app.circleci.com/pipelines/github/all-of-us/workbench/37730/workflows/35b083f5-29fb-41c6-9b03-9978177694d9/jobs/422041). This should fix that.
---
=> [RW-11491][risk=no] Fix key storage.

.circleci/config.yml
Fixing a bash export issue for the deploy process.
---
=> [RW-11491][risk=no] Fix key storage for CI

.circleci/config.yml
=> [RW-11491][risk=no] Debugging Jira comment command

.circleci/config.yml
Utilize `>> $BASH_ENV` used elsewhere in our CircleCI config.
---
=> [RW-11491][risk=no] Try loading JIRA_ISSUE_KEY into BASH_ENV

.circleci/config.yml
=> [RW-11491][risk=no] Fix environment variable.

api/db-cdr/generate-cdr/create-cdr-indices-tables.sh
=> [no-ticket][risk=no] fixing index

api/src/main/webapp/static/initialize_notebook_runtime.sh
Adding google-batch related config. This PR won't break existing nextflow usage. We can remove the gls profile once we have all the comms ready.
Changes are based on https://cloud.google.com/batch/docs/migrate-to-batch-from-cloud-life-sciences (search for Nextflow)
User will need to run the following cmd to install nextflow v23.
```
curl -s -L https://github.com/nextflow-io/nextflow/releases/download/v23.04.1/nextflow | bash
```
Ran a simple nextflow file attached in https://precisionmedicineinitiative.atlassian.net/browse/RW-14841. Here's the result
```
./nextflow run test.nf -profile gcb -c ~/.nextflow/config
N E X T F L O W  ~  version 23.04.1
Launching `test.nf` [wise_dalembert] DSL2 - revision: 31c25ad460
executor >  google-batch (2)
[1b/89fd51] process > hello    [100%] 1 of 1 ✔ …
```
=> [risk=low] RW-14841 Update Nextflow config to support batch api

api/src/main/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceImpl.java, api/src/main/java/org/pmiops/workbench/reporting/insertion/WorkspaceColumnValueExtractor.java, api/src/main/resources/workbench-api.yaml, api/src/test/java/org/pmiops/workbench/db/jdbc/ReportingQueryServiceTest.java, api/src/test/java/org/pmiops/workbench/reporting/ReportingUploadServiceTest.java, api/src/test/java/org/pmiops/workbench/testconfig/ReportingTestUtils.java
Confirmed that this field is not used in reporting.  We can now fully remove it.
Tested locally by running the reporting cron.
---
=> [risk=low][RW-14706] Final removal of BillingStatus

.circleci/config.yml
Adding the production release to the auto deploy process. The production release will only deploy once the pre-production release has deployed successfully (which requires approvals). More details can be found on the rest of the flow here: https://github.com/all-of-us/workbench/pull/9197#issue-2944410983
---
=> [RW-11491][risk=no] Include the production release as part of the auto-release flow.

ui/src/app/utils/institutions.tsx
=> [DT-1003][risk=no] Update existing account error message

api/config/cdr_config_stable.json, api/config/config_test.json
=> [no ticket] [risk=no] fix VWB CT group name in stable and update config in test env

ui/src/app/components/gke-app-configuration-panels/create-gke-app.tsx, ui/src/app/components/runtime-configuration-panel/create-panel.tsx, ui/src/app/components/runtime-configuration-panel/customize-panel.tsx, ui/src/app/lab/components/common-env-conf-panels/environment-informed-action-panel.tsx
A deliberately small PR in order to model what the lobby/lab shift will look like.
In order to test, open the Cromwell, RStudio, SAS, and/or Jupyter tabs and ensure that the cost estimator appears correctly.
---
=> [RW-15053][risk=no]Moved EnvironmentInformedActionPanel and updated imports to accommodate new lobby/lab model

api/config/config_preprod.json
I tried out things on Test and snippets are working as expected.
Also checked with Sam about https://precisionmedicineinitiative.atlassian.net/browse/RW-14240?focusedCommentId=252648 with no immediate concern, and she's ok with promoting to preprod so that DST team can verify further.
---
=> [risk=no] RW-14240 promote to preprod

api/src/main/webapp/static/initialize_notebook_runtime.sh
[Jun has tested out Nextflow against batch](https://precisionmedicineinitiative.atlassian.net/browse/RW-14613?focusedCommentId=253218), and verified it's working.
So it should be safe to remove the nextflow gls profile.
---
=> RW-14987  Remove Nextflow GLS profile

.circleci/config.yml, api/build.gradle
This reverts commit 18dde42d711c8161c1659376a9368524052546c7.
Reverting https://github.com/all-of-us/workbench/pull/9267 because of ongoing unit test failures.
---
=> [risk=low][no ticket] Revert Bump Spring Boot to latest

api/config/config_prod.json
The checkInitialCreditsUsage cron job has been failing recently because of memory issues. Decreasing batch count to save on memory.
---
=> [no ticket][risk=no] Decrease usersPerCheckInitialCreditsUsageTask for prod.

api/config/config_stable.json
=> [no ticket][risk=no] [Exfil in prod]turn on VWB egress in stable as VWB is ready!

.circleci/config.yml
=> [no ticket][risk=no] Increase circleci timeout for api startup

api/db/changelog/db.changelog-268-recreate-vwb-pod-columns.xml, api/db/changelog/db.changelog-master.xml
=> [RW-15247][risk=no] Fix db columns not created 

.circleci/config.yml
Remove the tanagra deploy from circleci jobs as it is no longer needed
=> [no ticket][risk=no] Remove tanagra deploys from circleci

api/config/config_local.json, api/config/config_stable.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/VwbWorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryService.java, api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryServiceImpl.java, api/src/main/resources/workbench-api.yaml, ui/src/app/components/inputs.tsx, ui/src/app/components/side-nav.tsx, ui/src/app/pages/admin/vwb/admin-vwb-workspace.tsx, ui/src/app/routing/signed-in-app-routing.tsx, ui/src/app/services/swagger-fetch-clients.ts
- Add 'VWB Workspace Admin' menu item and page with the first function of viewing workspaces by creator
- Add new controller/service for querying the VWB BQ project
- Added the `all-of-us-workbench-test.vwb_admin_test.wsm_workspaces` table with the same schema that the VWB table uses to be able to test locally
---
=> [DT-1024][DT-1015][DT-1029][risk=no] Add initial endpoint and UI component for VWB admin features

ui/src/app/components/side-nav.tsx, ui/src/environments/environment-type.ts, ui/src/environments/environment.local.ts, ui/src/environments/environment.preprod.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.stable.ts, ui/src/environments/environment.staging.ts, ui/src/environments/test-env-base.ts
Add `enableVwbAdmin` property in UI env flags. Currently only enabled for local, test, and stable
=> [no ticket][risk=no] Add UI env flag for VWB admin

api/src/main/java/org/pmiops/workbench/vwb/usermanager/VwbUserManagerClient.java
=> [risk=no][no-ticket] Fix pod user facing ID to be unique

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/api/CloudTaskVwbController.java, api/src/main/java/org/pmiops/workbench/cloudtasks/TaskQueueService.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/main/java/org/pmiops/workbench/user/VwbUserService.java, api/src/test/java/org/pmiops/workbench/api/CloudTaskVwbControllerTest.java, api/src/test/java/org/pmiops/workbench/user/VwbUserServiceTest.java
=> [risk=no][no-ticket] Split feature flags

api/config/config_local.json, api/config/config_preprod.json, api/config/config_prod.json, api/config/config_stable.json, api/config/config_staging.json, api/config/config_test.json, api/src/main/java/org/pmiops/workbench/access/AccessSyncServiceImpl.java, api/src/main/java/org/pmiops/workbench/access/AccessTierServiceImpl.java, api/src/main/java/org/pmiops/workbench/access/VwbAccessService.java, api/src/main/java/org/pmiops/workbench/config/WorkbenchConfig.java, api/src/test/java/org/pmiops/workbench/access/AccessSyncServiceTest.java, api/src/test/java/org/pmiops/workbench/access/VwbAccessServiceTest.java
=> PHP-92224: Change access check logic to compare Tier in DB. And also update VWB tier checks

ui/src/app/pages/workspace/workspace-wrapper.spec.tsx, ui/src/app/pages/workspace/workspace-wrapper.tsx
Ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-15149
Projects created with initial credits may lose their billing account once credits expire. While the project remains, linked workspaces become unusable until billing is restored.
This PR adds a feature-flagged banner to the workspace UI that:
- Detects when billing has been unlinked
- Informs the user of the issue and its impact
- Provides guidance/link to re-link billing
- Disappears once billing is restored
Feature gated by `enableUnlinkBillingForInitialCredits` flag.
---
=> [RW-15149] Add banner for workspaces with unlinked billing after credits expire or exhausted

api/src/main/java/org/pmiops/workbench/api/VwbWorkspaceAdminController.java, api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryService.java, api/src/main/java/org/pmiops/workbench/vwb/admin/VwbAdminQueryServiceImpl.java, api/src/main/resources/workbench-api.yaml, ui/src/app/pages/admin/egress-events-table.tsx
=> [no ticket][risk=low] Send user to admin vwb workspaces page when it is a VWB workspace in egress event
